### ISSUE TITLE
Error: Detox.framework not found

### ISSUE THREAD

**Issue by chirag04** [wix/detox#100]
on npm detox is shipped with `Detox.framework.tbz` while the expectation is to have a decompressed framework. manually decompressing it fixes it for me inside node_modules/detox.

**Comment by rotemmiz** [comment]
Thanks for reporting this issue. Turns out our postinstall script was broken. fixed in https://github.com/wix/detox/commit/c909ceb242b4c27c1f7fee6f9ae23e902b2eaa83

**Comment by rotemmiz** [comment]
Published in 5.0.4.
