### ISSUE TITLE
_prettyPrintAppStateTracker crash

### ISSUE THREAD

**Issue by LeoNatan** [wix/Detox#1002]
Causing crashes in app state pretty print

**Comment by LeoNatan** [comment]
Seems like the crash is unrelated to `__DTXDeallocSafeProxy.object`. Something else is causing the crash. Not sure yet what.

**Comment by LeoNatan** [comment]
Can't reproduce. @rotemmiz You don't happen to have the crash stack trace we saw, right?

**Comment by rotemmiz** [comment]
not anymore. I didn't happen since. Should we close it until next time?

**Comment by LeoNatan** [comment]
No. Let's keep it for visibility. There is another one that Arnon reported, but it's a different issue.

**Comment by rotemmiz** [comment]
sure
