### ISSUE TITLE
Using Stroy book in react app so how can i define Testid for those element

### ISSUE THREAD

**Issue by akqaaditya** [wix/Detox#1010]
Using Stroy book in react app so how can i define Testid for those element

**Comment by akqaaditya** [comment]
This may be a purely new feature for detox because of haven't seen any support for Storybook

**Comment by rotemmiz** [comment]
Be specific and write an elaborate description of the issue/suggestion.
Your question is very vague. Make sure you do a research before asking/suggesting.

Whether you use any kind of framework, it is your (or the framework's) responsiblity to pass testIds to native hierarchy.
