### ISSUE TITLE
testID after change get new values only after rebuild

### ISSUE THREAD

**Issue by skv-headless** [wix/detox#102]
`detox build` takes quite a lot of time. Is it possible to fix?
or am I doing something wrong?

**Comment by rotemmiz** [comment]
`detox build` is just a convenience method for you to tie your test configurations together with specific builds.

basically, it runs an arbitrary command configured by you in `detox.configurations.build` in your package.json, so it depends what you've instructed it to do.

If you already have your app built you don't need to run `detox build` again.

regarding testIDs, can you please rephrase? I'm not sure what's your intention.

**Comment by skv-headless** [comment]
For example I have broken test. Now I need to modify code to fix it. I modify code then I need to run `detox build`  to have working code on emulator. 
It would be nice if `detox test` loads new js bundle.

I have in the beginning of the test but I'm pretty sure new js bundle won't be updated until I run `detox build`
```  beforeEach(async () => {
    await device.reloadReactNative();
  });
```

Thank you for answering.

**Comment by skv-headless** [comment]
my config

```javascript
  "detox": {
   "configurations": {
       "ios.sim.release": {
         "binaryPath": "ios/build/Build/Products/Release-iphonesimulator/HappyPancake.app",
         "build": "xcodebuild -workspace ios/HappyPancake.xcworkspace -scheme HappyPancake -sdk iphonesimulator -configuration Release -derivedDataPath ios/build",
         "type": "ios.simulator",
         "name": "iPhone 7"
       }
     }
   }
```

and test

```js
describe('Example', () => {
  beforeEach(async () => {
    await device.reloadReactNative();
  });

  it('should have welcome screen', async () => {
    //await element(by.id('Signin1')).tap();
    await element(by.label('Sign in1')).tap();
  });
});
```

**Comment by skv-headless** [comment]
@rotemmiz found debug configuration it works now. Sorry for interruption and thanks again.

**Comment by talkol** [comment]
@rotemmiz We should clarify this more in the README. Maybe a dedicated comment somewhere that we recommend to work on debug configuration while you're developing or else people will lose their minds

**Comment by rotemmiz** [comment]
@skv-headless you're welcome
@talkol I'll add a few use cases to the readme
