### ISSUE TITLE
Android - read: unexpected EOF! error on Bitrise CI

### ISSUE THREAD

**Issue by stevechun** [wix/Detox#1023]
#### Description

I'm setting CI with Detox on Bitrise, and when it comes to taking screenshots and record videos, I'm getting the following errors for each step and fails to take the screenshots/videos:

```
ERROR: [exec.js/SPAWN_STDERR, #188] read: unexpected EOF!
```

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 9.0.5, 9.0.6
* React Native: 0.57.0, 0.57.2
* Node: 9.3.0
* Device: Android Emulator (android-26, x86, Nexus 5X)
Note: I have tried API 25, 24 and getting the same errors.

**Comment by EdwardDrapkin** [comment]
happens to me periodically in Jenkins (slave running on a mac via JNLP against an emulator on API 26) too
