### ISSUE TITLE
Artifacts should include the full device log 

### ISSUE THREAD

**Issue by LeoNatan** [wix/Detox#1024]
Right now, artifacts include a portion of the device log during the time of each test. This can lead to missing portions from between the tests.

There should be a full device log at the root folder of the artifacts for reference.

**Comment by noomorph** [comment]
> device log during the time of each test

@LeoNatan, it's not a bug, it's a feature. 😃  Think of it as a video recording of the test, which apparently can also miss some things.

Even if we do this, I think it should be configurable, or well-thought in some another way. I see your point that some portions might miss, but browsing one huge log looks not nice either.

**Comment by LeoNatan** [comment]
With a video it makes sense because Detox waits for idle, which also means UI idleness. 

When reading device log, it doesn’t make sense to have it split. What is happening right now is that important parts of the log are missing, which defeats the point of having logs in the first place. 

Device log should be kept fully in addition to being split.

**Comment by noomorph** [comment]
Okay, but I think I'll need at least 2-3 SP for that, let's talk in DM.

**Comment by LeoNatan** [comment]
:)

**Comment by LeoNatan** [comment]
Closing in favor of #1445.
