### ISSUE TITLE
Detox not run in offline mode

### ISSUE THREAD

**Issue by abaddonGIT** [wix/Detox#1029]
#### Description
I need to test the application in online and offline modes, but if i try start detox test when wifi is off I get error.

#### Steps to Reproduce
1) Wi-fi off (example from terminal: networksetup -setnetworkserviceenabled Wi-Fi off)
2) after detox test

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 9.6.0
* React Native: 0.55.3
* Node: 10.13.0
* Device: iPhone 7 simulator 11.4 
* Xcode: 9.4
* macOS: 10.13.6

#### Device and verbose Detox logs

`detox[2325] ERROR: [index.js/DETOX_INIT_ERROR]
 -[__NSCFString sentry_sanitize]: unrecognized selector sent to instance 0x60000089f9f0
(
        0   CoreFoundation                      0x000000010bd431e6 __exceptionPreprocess + 294
        1   libobjc.A.dylib                     0x000000010ad67031 objc_exception_throw + 48
        2   CoreFoundation                      0x000000010bdc4784 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
        3   CoreFoundation                      0x000000010bcc5898 ___forwarding___ + 1432
        4   CoreFoundation                      0x000000010bcc5278 _CF_forwarding_prep_0 + 120
        5   Colt                                0x0000000103d19f41 -[SentryBreadcrumb serialize] + 529
        6   Colt                                0x0000000103d4c238 -[SentryFileManager storeBreadcrumb:maxCount:] + 120
        7   Colt                                0x0000000103d36c9b -[SentryBreadcrumbStore addBreadcrumb:] + 235
        8   Colt                                0x0000000103d0fec7 __30-[RNSentry captureBreadcrumb:]_block_invoke + 151
        9   libdispatch.dylib                   0x000000010e3ca6cb _dispatch_call_block_and_release + 12
        10  libdispatch.dylib                   0x000000010e3cb709 _dispatch_client_callout + 8
        11  libdispatch.dylib                   0x000000010e3d0294 _dispatch_queue_override_invoke + 887
        12  libdispatch.dylib                   0x000000010e3d5c88 _dispatch_root_queue_drain + 473
        13  libdispatch.dylib                   0x000000010e3d5a51 _dispatch_worker_thread3 + 119
        14  libsystem_pthread.dylib             0x000000010e8d4169 _pthread_wqthread + 1387
        15  libsystem_pthread.dylib             0x000000010e8d3be9 start_wqthread + 13
)
child_process.js:651
    throw err;
    ^
`

**Comment by LeoNatan** [comment]
This is a crash in Sentry, unrelated to Detox.
