### ISSUE TITLE
iOS/android concurrency

### ISSUE THREAD

**Issue by jgreen210** [wix/Detox#1034]
#### Description

I'm running detox concurrently with itself, since want parallelism across simulators/emulators/devices (and to manage their lifecycles myself). Each detox instance is given one android or iOS device/simulator. I don't run more than one iOS simulator at the same time, but do want to run one iOS simulator detox instance at the same time as multiple android detox instances.

Inspecting the detox source code, I notice that ~/Library/Detox/device.registry.state.lock is used to manage iOS concurrency within one detox invocation. It was added in: https://github.com/wix/Detox/pull/609

That's OK, since I only want to run at most one iOS detox instance at a time. I notice that the lock file is cleared even if start detox for just android though, so it will interfere with iOS detox invocations.

There is some locking around the lock file, but it's (correctly) only done after the lock file is cleared when start detox.

#### Steps to Reproduce

Run one iOS detox instance and many android detox instances concurrently with each other. Their use of ~/Library/Detox/device.registry.state.lock will collide.

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 9.0.6
* React Native: n/a
* Node: n/a
* Device: iOS and android
* Xcode: n/a
* macOS: n/a

**Comment by jgreen210** [comment]
I think this should fix this:

https://github.com/jgreen210/Detox/commit/9078a7ab9307db5426ac76cc3a0e4bbe57834974
https://github.com/jgreen210/Detox/commits/registry_locking

I've not tried to run it locally or run this project's tests against this commit yet. I'd like a little feedback on the general approach before I invest time in that and create a PR.

**Comment by jg210** [comment]
90778a7a isn't right - would need to clear registry somewhere else too. I'll fix it up on Monday.

**Comment by jgreen210** [comment]
Another way to fix this would be to make the path to the lock file configurable via a command-line option. It would then be possible to use a different file for ios and android. This would also allow e.g. iOS-iOS concurrency to be configured in a variety of ways.
