### ISSUE TITLE
Artifacts test should not run on all tests

### ISSUE THREAD

**Issue by LeoNatan** [wix/Detox#1038]
Right now, I added a new test file and it failed CI because an artifact is missing in snapshot.

This is a bad way to check the artifacts. It should be for a specific test that will never change, and so the artifacts and snapshots can be predicted correctly.

**Comment by noomorph** [comment]
I agree it was a temporary solution that we devised with @rotemmiz , but we never had time to sit and think what's the ideal one... :( I'll try to design something better in some nearest future.

The only thing we should track (if we disable this step) — ban changes to artifacts lifecycle or plugins before we merge in a better solution.

**Comment by LeoNatan** [comment]
Sure, that makes sense. Of course, barring any urgent issues, but they will likely not come if they haven't already.

Thanks

**Comment by noomorph** [comment]
Not relevant, I assume.
