### ISSUE TITLE
Support for pressing Delete key on Android

### ISSUE THREAD

**Issue by michaelgmcd** [wix/Detox#1039]
Unlike iOS, there doesn't appear a way to press the "Delete" key on Android. For iOS, I'm am able to use the `typeText` method and the `"\b"` string. From what I can tell through looking at the code is that either the [UIDevice's pressDelete method](https://github.com/wix/Detox/blob/016adbb6ec37235b17c4d036fe221daa454d22d1/detox/src/android/espressoapi/UIDevice.js#L137-L143) or the [Android Espresso pressKey](https://developer.android.com/reference/android/support/test/espresso/action/ViewActions#presskey) method are the ways to solve this, however neither of these seem to be exposed to the JavaScript API.

**Comment by michaelgmcd** [comment]
@LeoNatan, I can probably take care of the PR for this, we'll just need some discussion on the implementation. The way I see it, we can either:
* Manually handle the `\b` key in the typeText element method on Android:
```javascript
element.typeText('aa\bcc')
// on Android becomes 
element.typeText('aa')
element._pressKey(67) // internal
element.typeText('cc')
```
* Expose the `pressKey` command on Android
  * It doesn't seem like EarlGrey has a `pressKey` command, so this would be Android only
  * Issue with this is that users will have to manually implement what's in the first option for a cross-platform test
* Expose the `pressDelete` command on Android
  * Will also require users to manually implement the first option for cross-platform support
  * Doesn't support keys other than Delete

**Comment by LeoNatan** [comment]
Sadly, `\n` and `\b` are not obvious at all on iOS. I think it's probably a good idea to have functions such as `pressReturnKey()` and `pressBackspaceKey()` on element (next to `typeText`), and then inside split the impl to typing `\n` on iOS and doing the necessary key press for Android. What do you think?

**Comment by LeoNatan** [comment]
The `pressKey()` should remain internal, I think.

**Comment by LeoNatan** [comment]
If you could submit a PR, that would be lovely. Thank you!

**Comment by michaelgmcd** [comment]
I think the abstraction sounds nice. I'll take another look at this tonight. Should be able to open a PR.
