### ISSUE TITLE
Having auto-completion ?

### ISSUE THREAD

**Issue by ScreamZ** [wix/Detox#1050]
Hey,

I'm using Vscode and I would like to know if someone has found a way to get auto-completion ?
Regards

**Comment by pavilion** [comment]
@ScreamZ It should work if you have installed Detox in your project.
https://youtu.be/vwIgAHnjc1k?list=PLXXnezSEtvNPZroRdvjhEVzOhURl572Lf&t=1497

**Comment by LeoNatan** [comment]
This is out of scope for the project. This should come as a community project.
