### ISSUE TITLE
UIPickerView does not contain desired value

### ISSUE THREAD

**Issue by petrmrakava** [wix/Detox#1051]
Sorry guys, but all about iOS Picker was closed without any conclusion. I have exactly the same issue as https://github.com/wix/Detox/issues/798. Also, the  question on stackoverflow has no answer https://stackoverflow.com/questions/50082463/testing-picker-with-detox-in-react-native 

so

if I use "testID":
`await element(by.id('testIdPicker')).setColumnToValue(0, 'en');`
I get
`"Description" : "Interaction cannot continue because the desired element was not found."`
If I use "type":
`await element(by.type('UIPickerView')).setColumnToValue(0, 'en');`
I get
`"Description" : "UIPickerView does not contain desired value!"`

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 9.0.4
* React Native: 0.57.4
* Node: 11.1.0
* Device:*
* Xcode: 10.0
* macOS: 10.13.6

![detox](https://user-images.githubusercontent.com/43537625/48945878-2d281080-ef2c-11e8-8c88-2c90736ed305.png)

**Comment by LeoNatan** [comment]
Can you please create a demo project that reproduces this?

**Comment by petrmrakava** [comment]
Sorry I can not share our project with you, but I created an example based on https://github.com/wix/Detox/issues/798. There are the same issues as I reported.
You can find it here: https://github.com/petrmrakava/Detox/tree/petrmrakava/iosPicker

**Comment by LeoNatan** [comment]
Great, thank you!

**Comment by fedeerbes** [comment]
Hi @LeoNatan, any progress in this? i'm facing the same issue.

**Comment by LeoNatan** [comment]
Sorry, I am busy with other projects at the moment.

**Comment by LeoNatan** [comment]
See this:
https://github.com/facebook/react-native/pull/22537

**Comment by LeoNatan** [comment]
It seems like an RN bug.

**Comment by fedeerbes** [comment]
thanks @LeoNatan i'll be waiting for the next version with that fix.

**Comment by LeoNatan** [comment]
@fedeerbes Can you please test to see if the issue still reproduces? Thanks

**Comment by revh** [comment]
Hi, first of all thanks for the great work.

It seems that the issue still reproduces also with RN 0.59.9

`await element(by.type("UIPickerView")).setColumnToValue(0, "value");`

results in 

`"Description" : "UIPickerView does not contain desired value!" `

**Comment by noomorph** [comment]
Just to make sure, I wonder how this test passes then?

https://github.com/wix/Detox/blob/bdab58681ee6fb10100d43809a9c64f9ebf294c6/detox/test/e2e/17.datePicker.test.js#L7-L11

**Comment by revh** [comment]
I can see that you are using <DatePickerIOS> Component for the test, but I got the issue with <Picker> or <PickerIOS> Components.

**Comment by LeoNatan** [comment]
`DatePickerIOS` is mapped to a `UIDatePicker`, which is a wrapper around `UIPickerView`. The same API should work with both.

**Comment by revh** [comment]
Thanks for your reply, I see your point.

I tried to add into into my project the same test as the one that @noomorph quoted and the same DatePickerIOS component and everything worked as expected.
So this let me wonder if there are any subtle differences between those two Picker and DatePickerIOS implementations.

**Comment by LeoNatan** [comment]
Hmm, I think I see the problem. Earl Grey expect the picker view to implement a data source, but the clowns in RN just implement the methods and rely on undocumented behavior of iOS. Investigating.

**Comment by LeoNatan** [comment]
I'll be providing a fix soon. As a bonus, I will also simplify setting picker values in RN date pickers (selecting by id, not by class).

**Comment by fedeerbes** [comment]
Hi @LeoNatan, thanks for the work you did it here. Reading the above, I'll try with the new version and let you know how it goes.

**Comment by LeoNatan** [comment]
Thanks!

**Comment by revh** [comment]
I tested the new implementation and it seems to be working properly now.
Thanks @LeoNatan 🥇 👍
