### ISSUE TITLE
we should only have exactly one subview error returned

### ISSUE THREAD

**Issue by lalka-workco** [wix/Detox#1052]
_Originally posted by @brentvatne in https://github.com/wix/detox/issues/86#issuecomment-294999613_

**Comment by lalka-workco** [comment]
Error happens when you call `.toBeVisible()` on a ScrollView element.

**Comment by rotemmiz** [comment]
You posted too few details, it can not be understood where and when this happens.
Please follow the issue template.

**Comment by lalka-workco** [comment]
Sorry, I don't have the bandwidth to look at this. If someone else wants to take go ahead. Otherwise, don't call toBeVisible on a scrollview
