### ISSUE TITLE
add support for grey_getText | EarlGrey

### ISSUE THREAD

**Issue by fedeerbes** [wix/Detox#1056]
#### Description
I want to capture the value of an inputText for use it or compare it and i didn't found any reference to getText, maybe i'm wrong and already exist.

**Comment by LeoNatan** [comment]
Why aren't you using a matcher?
Or do you mean store it, check later that something matches that text?

**Comment by fedeerbes** [comment]
Yes, it'll be for store it and use the value later in the test
