### ISSUE TITLE
Getting accessibility data of a matched view

### ISSUE THREAD

**Issue by viktorijasujetaite** [wix/Detox#1057]
This issue was brought up because some views have unique testIDs. They are created along with a unique element. e.g. 'wix.bookings.pastbooking-xxxx-xxxx-xxxx-xxxx'. We need an ability to get such element's accessibility data to be able to work with it later on, while repeating less code.

Flow:
1. Element (i.e. card with buttons) with unique text is created
2. Card is assigned a unique testID
3. Use by.text matcher to get card's accessibility data
4. Get unique testID from it's accessibility data
5. Use retrieved testID to match card's elements

**Comment by LeoNatan** [comment]
Hello,

If I understand correctly, by accessibility data, you mean the testID that was assigned to a view, right?

I am trying to understand how the "xxxx-xxxx-xxxx-xxxx" is generated. Also, why can't the same element that was retrieved `byText()` be used later, rather than looking for it again `byId()`?

**Comment by viktorijasujetaite** [comment]
I think that @rotemmiz can explain better how it's generated. 

If you would continue on working by text for such elements, it would require unnecessary difficulty and repetition. I.e. instead of:
`element(by.id('some_card_button').withAncestor(by.id('unique_testID'))` (what I would prefer)

it would be:
`element(by.id('some_card_button').withAncestor(by.type('generic_item_type').withDescendant(by.text('unique_text')))`

obvious, that it's longer and more difficult to read.

**Comment by LeoNatan** [comment]
Merging this with #445 since both will be implemented in the future rewrite of Detox, where all the accessibility properties will be serialized to the test runner (JS).
