### ISSUE TITLE
Can’t run 'detox test' for Android on simulator

### ISSUE THREAD

**Issue by AlexPlekhov** [wix/Detox#1074]
#### Description
Detox is unable to launch an app for Android simulator.
The simulator is launched.
It is actual for RN 56, 57

#### Steps to Reproduce
1. Create example RN project on RN 56-57
2. Add Detox
3. run 'detox test' on android configuration

#### Detox, Node, Device, macOS Versions
•	Detox: 9.1.2
•	React Native: 0.56.1
•	Node: 10.9.0
•	Simulator: Galaxy_S5_API_23, Android 6.0
•	macOS: 10.14.1
•	android NDK 16 (RN 57 -> NDK 17)

#### Details:
1.	I created an empty project by `react-native init` with RN 56.1 
2.	Made all steps from https://github.com/wix/Detox/blob/master/docs/Introduction.GettingStarted.md
3.	I tried to run and it didn’t work, I googled and added to Package.json a few new dev dependencies, see package.json below
4.	Also I added into test a header, see below

At this point I have the android simulator is launched, but the app is not launching.
No errors in log. Just empty simulator on the screen.

#### Files examples

Package.json:

```
"dependencies": {
  "react": "16.4.1",
  "react-native": "0.56.1"
},
"devDependencies": {
  "babel-jest": "23.6.0",
  "babel-core": "^6.26.3",
  "babel-preset-react-native": "^5",
  "babel-loader": "^8.0.4",
  "babel-plugin-transform-async-to-generator": "^6.24.1",
  "babel-plugin-transform-runtime": "^6.23.0",
  "babel-polyfill": "^6.26.0",
  "detox": "^9.1.2",
  "jest": "23.6.0",
  "react-test-renderer": "16.4.1"
},
"jest": {
  "preset": "react-native"
},
"detox": {
  "configurations": {
    "android.emu.debug": {
      "binaryPath": "android/app/build/outputs/apk/app-debug.apk",
      "build": "pushd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && popd",
      "type": "android.emulator",
      "name": "Galaxy_S5_API_23"
    }
  },
  "test-runner": "jest"
}
```

e2e/config
```
    "setupTestFrameworkScriptFile": "./init.js",
    "testEnvironment": "node",
    "transform": {
        "^.+\\.js$": "<rootDir>/../node_modules/react-native/jest/preprocessor.js"
    }
}

```

test
```
'use strict';
require('babel-core/register');
require('babel-polyfill');

describe('Example', () => {
  beforeEach(async () => {
    await device.reloadReactNative();
  });

  it('should have welcome screen', async () => {
    await expect(element(by.text('welcome'))).toBeVisible();
  });

})
```
When I tried to run this test without this header, I got an error: 
`ReferenceError: regeneratorRuntime is not defined`

#### Linked issues
https://github.com/wix/detox/issues/714
#695

**Comment by rotemmiz** [comment]
The guide should be complete, it has been tested. Please go over it again, and make sure you also read the Android guide.
This type of question typically fits StackOverflow, and not the issue tracker, as it is not a bug or a feature suggestion.
