### ISSUE TITLE
Getting Timeout in RN app with RNRF

### ISSUE THREAD

**Issue by linoleum00** [wix/Detox#1077]
I have this test:

```
it('should Login in Mexico', async () => {
        const countryBtnMx = element(by.id('COUNTRY_BTN_MX'));
        await expect(countryBtnMx).toExist();
        await countryBtnMx.tap();
    });

```

My environment:
* Detox: 9.1.2
* React Native: 0.57.7
* redux: 4.0.
* redux-observable: 0.18.0
* rxjs: 5.5.10
* react-native-router-flux: 4.0.1
* Node: 10.0.0
* Xcode: 9.4.1 in my house, 10.1 in office
* macOS: High Sierra in my house, Mojave in office

Getting error:
Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.

The navigation in my app is done by react-native-router-flux,  so my button dispatches an action which changes the Scene and it is then where I'm having the timeout error. If I comment the line where I change the scene, then the test successfully passes.

**Comment by rotemmiz** [comment]
Use the FAQ and read about debug-synchronization.
