### ISSUE TITLE
Detox tests are not accepting permissions

### ISSUE THREAD

**Issue by kentapolis** [wix/Detox#1080]
#### Description
First off, I'd like to say thank you for this awesome library. I am glad this exists and would rather work with detox than appium any day of the week.

I am trying to get my detox tests up and running, but the tests are freezing until I manually accept/deny notification permissions on the app. I've looked up previous issues on StackOverflow and GitHub and could not find a solution so I'm resorting to creating an issue here.

On initial launch, the app asks users to allow/deny the app to receive push notifications. Once I manually accept/deny notification permissions, the tests then successfully start. Otherwise, it just times out at after 120000ms. I will post both logs below.

I run the tests with `await device.launchApp({permissions: {notifications: 'YES'}});` but that didn't work. I believe I followed the proper installation and setup instructions in the documentation. Applesimutils is indeed installed with version `0.6.1`. I'm not sure if this information will help, or if it's even relative at all, but the app is using `react-native-permissions` as well.

#### Steps to Reproduce
Included detox configuration in package.json
```
  "detox": {
    "configurations": {
      "ios.sim.debug": {
        "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/App.app",
        "build": "xcodebuild -project ios/App.xcodeproj -scheme 'App UAT' -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build",
        "type": "ios.simulator",
        "name": "iPhone 8"
      }
    },
    "test-runner": "jest",
    "runner-config": "e2e/config.json"
  }
```
Here's the init.js file in the e2e folder.
```
const detox = require('detox');
const { device } = require('detox');
const config = require('../package.json').detox;
const adapter = require('detox/runners/jest/adapter');

jest.setTimeout(120000);
jasmine.getEnv().addReporter(adapter);

beforeAll(async () => {
  await detox.init(config);
});

beforeEach(async () => {
  await adapter.beforeEach();
});

afterAll(async () => {
  await adapter.afterAll();
  await detox.cleanup();
});
```
Here's my test file
```
const { AUTH_BACKGROUND_IMAGE } = require('../../app/constants/test-ids');

describe('Login test', () => {
  beforeAll(async () => {
    await device.launchApp({permissions: {notifications: 'YES'}});
  });

  it('Background image exists', async () => {
    await expect(element(by.id(AUTH_BACKGROUND_IMAGE))).toExist();
  });
});
```

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 9.1.2
* React Native: 0.55.2
* Node: v8.9.1
* jest: 22.4.3
* Device: iPhone 8 --byOS "12.1"
* Xcode: 10.1
* macOS: 10.13.6

#### Device and verbose Detox logs
Here are the logs when I let the test sit idle and timeout
```
configuration="ios.sim.debug" loglevel="verbose" artifactsLocation="artifacts/ios.sim.debug.2018-12-05 23-49-28Z" node_modules/.bin/jest e2e --config=e2e/config.json --maxWorkers=1 '--testNamePattern=^((?!:android:).)*$'
detox[68876] INFO:  [DetoxServer.js] server listening on localhost:49870...
detox[68876] DEBUG: [AsyncWebSocket.js/WEBSOCKET_OPEN] opened web socket to: ws://localhost:49870
detox[68876] DEBUG: [DetoxServer.js/LOGIN] role=tester, sessionId=e92f6c82-ba7f-9f13-7468-32b5a82fc6d9
detox[68876] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=tester, sessionId=e92f6c82-ba7f-9f13-7468-32b5a82fc6d9
detox[68876] DEBUG: [exec.js/EXEC_CMD, #0] /usr/bin/xcrun simctl list -j
detox[68876] DEBUG: [exec.js/EXEC_CMD, #1] applesimutils --list --byType "iPhone 8" --byOS "12.1"
detox[68876] DEBUG: [exec.js/EXEC_TRY, #1] Searching for device matching iPhone 8...
detox[68876] DEBUG: [exec.js/EXEC_CMD, #2] applesimutils --list --byId "D8DFD648-DCD1-4E9A-961B-7492E4F9C783"
detox[68876] DEBUG: [exec.js/EXEC_CMD, #3] /usr/bin/xcrun simctl uninstall D8DFD648-DCD1-4E9A-961B-7492E4F9C783 com.test.app
detox[68876] DEBUG: [exec.js/EXEC_TRY, #3] Uninstalling com.test.app...
detox[68876] DEBUG: [exec.js/EXEC_SUCCESS, #3] com.test.app uninstalled
detox[68876] DEBUG: [exec.js/EXEC_CMD, #4] /usr/bin/xcrun simctl install D8DFD648-DCD1-4E9A-961B-7492E4F9C783 "/Users/user/Documents/app/ios/build/Build/Products/Debug-iphonesimulator/App.app"
detox[68876] DEBUG: [exec.js/EXEC_TRY, #4] Installing /Users/user/Documents/app/ios/build/Build/Products/Debug-iphonesimulator/App.app...
detox[68876] DEBUG: [exec.js/EXEC_TRY, #4] Installing /Users/user/Documents/app/ios/build/Build/Products/Debug-iphonesimulator/App.app...
detox[68876] DEBUG: [exec.js/EXEC_SUCCESS, #4] /Users/user/Documents/app/ios/build/Build/Products/Debug-iphonesimulator/App.app installed
detox[68876] DEBUG: [exec.js/EXEC_CMD, #5] /usr/bin/xcrun simctl terminate D8DFD648-DCD1-4E9A-961B-7492E4F9C783 com.test.app
detox[68876] DEBUG: [exec.js/EXEC_TRY, #5] Terminating com.test.app...
detox[68876] DEBUG: [exec.js/EXEC_SUCCESS, #5] com.test.app terminated
detox[68876] DEBUG: [exec.js/EXEC_CMD, #6] /bin/cat /dev/null >/Users/user/Library/Developer/CoreSimulator/Devices/D8DFD648-DCD1-4E9A-961B-7492E4F9C783/data/tmp/detox.last_launch_app_log.out 2>/Users/user/Library/Developer/CoreSimulator/Devices/D8DFD648-DCD1-4E9A-961B-7492E4F9C783/data/tmp/detox.last_launch_app_log.err && SIMCTL_CHILD_DYLD_INSERT_LIBRARIES="/Users/user/Library/Detox/ios/aec62188116fcc095542b8295542435cd5c8a400/Detox.framework/Detox" /usr/bin/xcrun simctl launch --stdout=/tmp/detox.last_launch_app_log.out --stderr=/tmp/detox.last_launch_app_log.err D8DFD648-DCD1-4E9A-961B-7492E4F9C783 com.test.app --args -detoxServer ws://localhost:49870 -detoxSessionId e92f6c82-ba7f-9f13-7468-32b5a82fc6d9
detox[68876] DEBUG: [exec.js/EXEC_TRY, #6] Launching com.test.app...
detox[68876] DEBUG: [exec.js/EXEC_SUCCESS, #6] com.test.app launched. The stdout and stderr logs were recreated, you can watch them with:
        tail -F /Users/user/Library/Developer/CoreSimulator/Devices/D8DFD648-DCD1-4E9A-961B-7492E4F9C783/data/tmp/detox.last_launch_app_log.{out,err}
detox[68876] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=testee not connected, cannot fw action (sessionId=e92f6c82-ba7f-9f13-7468-32b5a82fc6d9)
detox[68876] DEBUG: [DetoxServer.js/LOGIN] role=testee, sessionId=e92f6c82-ba7f-9f13-7468-32b5a82fc6d9
detox[68876] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=testee, sessionId=e92f6c82-ba7f-9f13-7468-32b5a82fc6d9
 FAIL  e2e/login/login-success.spec.js (120.664s)
  Login test
    ✕ Background image exists (3ms)

  ● Login test › Background image exists

    Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.

      at ../node_modules/jest-jasmine2/build/queue_runner.js:68:21

  ● Login test › Background image exists

    ReferenceError: device is not defined

      3 | describe('Login test', () => {
      4 |   beforeAll(async () => {
    > 5 |     await device.launchApp({permissions: {notifications: 'YES'}});
      6 |   });
      7 |
      8 |   it('Background image exists', async () => {

      at Object._callee$ (login/login-success.spec.js:5:29)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at invoke (../node_modules/regenerator-runtime/runtime.js:152:20)
      at ../node_modules/regenerator-runtime/runtime.js:195:11
      at callInvokeWithMethodAndArg (../node_modules/regenerator-runtime/runtime.js:194:16)
      at AsyncIterator.enqueue (../node_modules/regenerator-runtime/runtime.js:217:13)
      at AsyncIterator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at Object.<anonymous>.runtime.async (../node_modules/regenerator-runtime/runtime.js:241:14)
      at Object._callee (login/login-success.spec.js:4:13)

  ● Login test › Background image exists

    ReferenceError: element is not defined

       7 |
       8 |   it('Background image exists', async () => {
    >  9 |     await expect(element(by.id(AUTH_BACKGROUND_IMAGE))).toExist();
      10 |   });
      11 | });

      at Object._callee2$ (login/login-success.spec.js:9:32)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:62:40)
      at invoke (../node_modules/regenerator-runtime/runtime.js:152:20)
      at ../node_modules/regenerator-runtime/runtime.js:195:11
      at callInvokeWithMethodAndArg (../node_modules/regenerator-runtime/runtime.js:194:16)
      at AsyncIterator.enqueue (../node_modules/regenerator-runtime/runtime.js:217:13)
      at AsyncIterator.prototype.(anonymous function) [as next] (../node_modules/regenerator-runtime/runtime.js:114:21)
      at Object.<anonymous>.runtime.async (../node_modules/regenerator-runtime/runtime.js:241:14)
      at Object._callee2 (login/login-success.spec.js:8:33)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        120.734s
Ran all test suites matching /e2e/i with tests matching "^((?!:android:).)*$".
detox[68876] DEBUG: [DetoxServer.js/DISCONNECT] role=tester, sessionId=e92f6c82-ba7f-9f13-7468-32b5a82fc6d9
detox[68876] DEBUG: [DetoxServer.js/DISCONNECT] role=testee, sessionId=e92f6c82-ba7f-9f13-7468-32b5a82fc6d9
child_process.js:644
    throw err;
    ^
```
Here are the logs once I manually accept/deny the notification permissions on the app
```
configuration="ios.sim.debug" loglevel="verbose" artifactsLocation="artifacts/ios.sim.debug.2018-12-05 23-57-40Z" node_modules/.bin/jest e2e --config=e2e/config.json --maxWorkers=1 '--testNamePattern=^((?!:android:).)*$'
detox[69395] INFO:  [DetoxServer.js] server listening on localhost:50931...
detox[69395] DEBUG: [AsyncWebSocket.js/WEBSOCKET_OPEN] opened web socket to: ws://localhost:50931
detox[69395] DEBUG: [DetoxServer.js/LOGIN] role=tester, sessionId=1eda9224-2aa5-d6d6-37d9-6584489bd7cd
detox[69395] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=tester, sessionId=1eda9224-2aa5-d6d6-37d9-6584489bd7cd
detox[69395] DEBUG: [exec.js/EXEC_CMD, #0] /usr/bin/xcrun simctl list -j
detox[69395] DEBUG: [exec.js/EXEC_CMD, #1] applesimutils --list --byType "iPhone 8" --byOS "12.1"
detox[69395] DEBUG: [exec.js/EXEC_TRY, #1] Searching for device matching iPhone 8...
detox[69395] DEBUG: [exec.js/EXEC_CMD, #2] applesimutils --list --byId "D8DFD648-DCD1-4E9A-961B-7492E4F9C783"
detox[69395] DEBUG: [exec.js/EXEC_CMD, #3] /usr/bin/xcrun simctl uninstall D8DFD648-DCD1-4E9A-961B-7492E4F9C783 com.test.app
detox[69395] DEBUG: [exec.js/EXEC_TRY, #3] Uninstalling com.test.app...
detox[69395] DEBUG: [exec.js/EXEC_SUCCESS, #3] com.test.app uninstalled
detox[69395] DEBUG: [exec.js/EXEC_CMD, #4] /usr/bin/xcrun simctl install D8DFD648-DCD1-4E9A-961B-7492E4F9C783 "/Users/user/Documents/app/ios/build/Build/Products/Debug-iphonesimulator/App.app"
detox[69395] DEBUG: [exec.js/EXEC_TRY, #4] Installing /Users/user/Documents/app/ios/build/Build/Products/Debug-iphonesimulator/App.app...
detox[69395] DEBUG: [exec.js/EXEC_TRY, #4] Installing /Users/user/Documents/app/ios/build/Build/Products/Debug-iphonesimulator/App.app...
detox[69395] DEBUG: [exec.js/EXEC_SUCCESS, #4] /Users/user/Documents/app/ios/build/Build/Products/Debug-iphonesimulator/App.app installed
detox[69395] DEBUG: [exec.js/EXEC_CMD, #5] /usr/bin/xcrun simctl terminate D8DFD648-DCD1-4E9A-961B-7492E4F9C783 com.test.app
detox[69395] DEBUG: [exec.js/EXEC_TRY, #5] Terminating com.test.app...
detox[69395] DEBUG: [exec.js/EXEC_SUCCESS, #5] com.test.app terminated
detox[69395] DEBUG: [exec.js/EXEC_CMD, #6] /bin/cat /dev/null >/Users/user/Library/Developer/CoreSimulator/Devices/D8DFD648-DCD1-4E9A-961B-7492E4F9C783/data/tmp/detox.last_launch_app_log.out 2>/Users/user/Library/Developer/CoreSimulator/Devices/D8DFD648-DCD1-4E9A-961B-7492E4F9C783/data/tmp/detox.last_launch_app_log.err && SIMCTL_CHILD_DYLD_INSERT_LIBRARIES="/Users/user/Library/Detox/ios/aec62188116fcc095542b8295542435cd5c8a400/Detox.framework/Detox" /usr/bin/xcrun simctl launch --stdout=/tmp/detox.last_launch_app_log.out --stderr=/tmp/detox.last_launch_app_log.err D8DFD648-DCD1-4E9A-961B-7492E4F9C783 com.test.app --args -detoxServer ws://localhost:50931 -detoxSessionId 1eda9224-2aa5-d6d6-37d9-6584489bd7cd
detox[69395] DEBUG: [exec.js/EXEC_TRY, #6] Launching com.test.app...
detox[69395] DEBUG: [exec.js/EXEC_SUCCESS, #6] com.test.app launched. The stdout and stderr logs were recreated, you can watch them with:
        tail -F /Users/user/Library/Developer/CoreSimulator/Devices/D8DFD648-DCD1-4E9A-961B-7492E4F9C783/data/tmp/detox.last_launch_app_log.{out,err}
detox[69395] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=testee not connected, cannot fw action (sessionId=1eda9224-2aa5-d6d6-37d9-6584489bd7cd)
detox[69395] DEBUG: [DetoxServer.js/LOGIN] role=testee, sessionId=1eda9224-2aa5-d6d6-37d9-6584489bd7cd
detox[69395] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=testee, sessionId=1eda9224-2aa5-d6d6-37d9-6584489bd7cd
detox[69395] DEBUG: [exec.js/EXEC_CMD, #7] applesimutils --simulator D8DFD648-DCD1-4E9A-961B-7492E4F9C783 --bundle com.test.app --setPermissions notifications=YES
detox[69395] DEBUG: [exec.js/EXEC_TRY, #7] Trying to set permissions...
detox[69395] DEBUG: [exec.js/EXEC_SUCCESS, #7] Permissions are set
detox[69395] DEBUG: [DetoxServer.js/DISCONNECT] role=testee, sessionId=1eda9224-2aa5-d6d6-37d9-6584489bd7cd
detox[69395] DEBUG: [exec.js/EXEC_CMD, #8] /bin/cat /dev/null >/Users/user/Library/Developer/CoreSimulator/Devices/D8DFD648-DCD1-4E9A-961B-7492E4F9C783/data/tmp/detox.last_launch_app_log.out 2>/Users/user/Library/Developer/CoreSimulator/Devices/D8DFD648-DCD1-4E9A-961B-7492E4F9C783/data/tmp/detox.last_launch_app_log.err && SIMCTL_CHILD_DYLD_INSERT_LIBRARIES="/Users/user/Library/Detox/ios/aec62188116fcc095542b8295542435cd5c8a400/Detox.framework/Detox" /usr/bin/xcrun simctl launch --stdout=/tmp/detox.last_launch_app_log.out --stderr=/tmp/detox.last_launch_app_log.err D8DFD648-DCD1-4E9A-961B-7492E4F9C783 com.test.app --args -detoxServer ws://localhost:50931 -detoxSessionId 1eda9224-2aa5-d6d6-37d9-6584489bd7cd
detox[69395] DEBUG: [exec.js/EXEC_TRY, #8] Launching com.test.app...
detox[69395] DEBUG: [exec.js/EXEC_SUCCESS, #8] com.test.app launched. The stdout and stderr logs were recreated, you can watch them with:
        tail -F /Users/user/Library/Developer/CoreSimulator/Devices/D8DFD648-DCD1-4E9A-961B-7492E4F9C783/data/tmp/detox.last_launch_app_log.{out,err}
detox[69395] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=testee not connected, cannot fw action (sessionId=1eda9224-2aa5-d6d6-37d9-6584489bd7cd)
detox[69395] DEBUG: [DetoxServer.js/LOGIN] role=testee, sessionId=1eda9224-2aa5-d6d6-37d9-6584489bd7cd
detox[69395] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=testee, sessionId=1eda9224-2aa5-d6d6-37d9-6584489bd7cd
 PASS  e2e/login/login-success.spec.js (23.775s)
  Login test
    ✓ Background image exists (8ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        23.85s, estimated 121s
Ran all test suites matching /e2e/i with tests matching "^((?!:android:).)*$".
detox[69395] DEBUG: [DetoxServer.js/DISCONNECT] role=tester, sessionId=1eda9224-2aa5-d6d6-37d9-6584489bd7cd
detox[69395] DEBUG: [DetoxServer.js/DISCONNECT] role=testee, sessionId=1eda9224-2aa5-d6d6-37d9-6584489bd7cd
```

As you can see, once I accept the permissions then detox sets the applesimutils permissions and then the tests works.
```
detox[69395] DEBUG: [exec.js/EXEC_CMD, #7] applesimutils --simulator D8DFD648-DCD1-4E9A-961B-7492E4F9C783 --bundle com.test.app --setPermissions notifications=YES
detox[69395] DEBUG: [exec.js/EXEC_TRY, #7] Trying to set permissions...
detox[69395] DEBUG: [exec.js/EXEC_SUCCESS, #7] Permissions are set
```
**FYI** I changed the bundle app id and app name in the logs because I didn't want it exposed and didn't think it would be helpful ¯\_(ツ)_/¯

Any help would be appreciated!

**Comment by diegolmello** [comment]
This issue is happening here as well.
If I manually accept permissions on iOS sim, tests runs fine, but I can't do it on CI.

**Comment by kentapolis** [comment]
@Kattsallad Yep I already adding
```
beforeEach(async () => {
     await device.reloadReactNative();
});
```
but it still doesn't accept the notification permission. I don't think `const { device } = require('detox')` is required becauce device is already a [global](https://github.com/wix/Detox/blob/master/docs/Guide.Jest.md) exposed by detox.

**Comment by Kattsallad** [comment]
@kentapolis

Yeah im kinda shooting in the dark right now. As a last attempt you can try setting permissions with launchapp newinstance true (you can find the required args in the docs im currently on the phone) sadly that adds a bit of unnecessary complexion to the tests.

**Comment by kentapolis** [comment]
@Kattsallad no luck again unfortunately. I'll continue to look around the docs to see if I missed anything and update this issue if I find anything. Hopefully I won't have to resort to switching to appium.

**Comment by Kattsallad** [comment]
@kentapolis You could try to use: 
await expect(element(by.text(Allow))).tap();
As the first step of the test, however if its a system dialog its not going to work i believe

**Comment by kentapolis** [comment]
@Kattsallad yep I tried that as well. I also looked at XCodes hierarchical debugger and tried to get the element through that inspection, but had no luck with that approach either.

**Comment by Kattsallad** [comment]
Last idea i have in the current state detox is in is to pass launchapp with notification permissions: yes and delete: true,

**Comment by kentapolis** [comment]
@Kattsallad 
yeah, no luck with that one either. I agree with you and I think it's a problem with `react-native-permissions` integration with detox. I'll remove it and we'll see how it works from there.

Thanks for the help! I'll update you once I figure something out.

**Comment by EdwardDrapkin** [comment]
I don't believe it's a react-native-permissions issue as it's happening to us as well and we're not using that package.

**Comment by kentapolis** [comment]
@LeoNatan 
I have the latest version of AppleSimUtils on my machine `0.6.1` and my sim is running iOS 12.1 (not sure if that makes a difference from 12.0) and I am still experiencing the issue. I'll try to run the applesimutils command first before running the detox test and I'll update you on what happens.

**Comment by LeoNatan** [comment]
Please test with iOS 12.0 as a workaround. I see there is already an issue open with AppleSimUtils about 12.1.

**Comment by LeoNatan** [comment]
OK, I just tested a lot of things. I identified an issue with location permission setting and fixed that with 0.6.2. I see no issue with notifications permission, nor with the normal TCC.db ones, such as calendar.

First, please update AppleSimUtils to the latest version.
I've added a demo project to AppleSimUtils here: https://github.com/wix/AppleSimulatorUtils/tree/master/sample/PermissionsTest
Please clone this demo project and run it.
Click on the buttons there and see in the console if you are given a `<granted>` message.

Thanks

**Comment by testtolearn1** [comment]
Launch app and try running applesimutils --setPermissions "notifications=YES" --bundle com.ecomi.securewallet.debug --byName 'iPhone 7' on terminal  , first.

Then use this code in your detox test --
e2e/init.js

before(async () => {
  await detox.init(config, { launchApp: false });
  await device.launchApp({permissions: {notifications: 'YES'}});
});

Since detox test can run in headless mode on Xcode >9 , check if simulator is not running in background , then clean content and `settings from simulator and run $detox test -c ios.sim.debug --loglevel=trace

**Comment by kentapolis** [comment]
@LeoNatan 
Gotcha. Let me try that and I'll update you. Thanks for the response!

**Comment by LeoNatan** [comment]
I don't understand what the "solution is". It's basically the official API we provide, which calls `applesimutils` internally. If `applesimutils` doesn't work, as per your previous comment, how can that solve it? Looks to me like a misuse of the API. Closing the issue.

**Comment by kentapolis** [comment]
@LeoNatan 

Apologies, as my descriptions weren't clear but I **did not** mean to say that `applesimutils` wasn't working. I was saying that the notification permissions were not getting accepted, even after running  `applesimutils --setPermissions …` and updating it to the latest version. I was never able to pinpoint the issue at all, which is why I created this issue in the first place. In my first comment, I also stated 
>As you can see, once I accept the permissions then detox sets the applesimutils permissions and then the tests works.

I've read all of the documentation that is provided in the README. I read [here](https://github.com/wix/Detox/blob/master/docs/APIRef.DetoxObjectAPI.md#detoxinit) about setting launchApp to false, but I didn't think about adding `await device.launchApp({ permissions: { notifications: 'YES' }});` in the next line as @testtolearn1 recommended. I was adding `await device.launchApp({ permissions: { notifications: 'YES' }});` in the `beforeAll()` function in the test files, but not `init.js`.

I don't think I'm the only user that was confused by this. Perhaps an update to the documentation will prevent this issue from being created again?

**Comment by LeoNatan** [comment]
It shouldn't matter whether `launchApp: false` is sent in `init()` because `applesimutils --setPermissions` reboots the simulator anyway. So that workaround makes no sense to me. `launchApp({permissions:...})` just calls `applesimutils` (see [here](https://github.com/wix/Detox/blob/1970e9608b9a72be1548044aeeb25ff9af15ad43/detox/src/devices/drivers/SimulatorDriver.js#L113)). The simulator will reboot after that point, so even if an app was launched, it shouldn't matter, because it will be killed by the system during the reboot process.

**Comment by kentapolis** [comment]
Ok so does that mean that it is indeed an issue then? I don't know if you looked at my original comment but I had `launchApp({permissions:...})` set in my test scripts but it didn't reboot the simulator at all until I manually accepted/denied permissions.

**Comment by LeoNatan** [comment]
I don't see how that can be, if you later use the same API and it does reboot it. It's the same API.

**Comment by kentapolis** [comment]
It only reboots if I set `await detox.init(config, { launchApp: false });` in the `init.js` file. Otherwise, the app launches and immediately asks the user to accept/deny notification permissions and hangs there and `launchApp({permissions:...})` does not get called. More information is available in the logs I posted in the first comment.

**Comment by testtolearn1** [comment]
yes @LeoNatan , i too faced exactly the same issue , it worked only when i set : await detox.init(config, { launchApp: false }).

Seems like there is no issue in applesimutils utility but in launchApp() API , because 
detox.init(config);  basically launch the app and put it in foreground , then as per https://github.com/wix/Detox/blob/master/docs/APIRef.DeviceObjectAPI.md#devicelaunchappparams
if you add  device.launchApp({permissions: {notifications: 'YES'}}); then by default the {newInstance in launchApp is set to false} so it will unsuccessfully attempt to bring the app from background which is already in foreground by detox.init, hence it will hang and will be kinda confused :)

Even if you put the code as --
  await detox.init(config);
  await device.launchApp({newInstance: true, permissions: {notifications: 'YES'}}); then also no new instance is launched , since the app is already running.

Hence the only solution left is to make detox.init({ launchApp: false }) and then await device.launchApp({permissions: {notifications: 'YES'}});

Need to revisit device.launchApp() API 









 it seems that device.launchApp expects to launch its own instance of app and run applesimutils ( with permission=yes) on that instance only, If detox.init(config) is added over it , launchApp() kind of gets confused on which

**Comment by LeoNatan** [comment]
Can you guys try something?

Remove the `init()` workaround and try adding `calendar: 'YES'` to the permissions. Does that make a change?

**Comment by LeoNatan** [comment]
In the first log above, I am not seeing a call to `applesimutils` with the permission. I don't see how that can happen as `launchApp()` method attempts a call.

**Comment by kentapolis** [comment]
@LeoNatan 

Exactly. It isn't making the call and it hangs until I manually accept the permission and it is only after that when `await device.launchApp({newInstance: true, permissions: {notifications: 'YES'}})` works.

As you can see, I'm not the only one running into this issue. Do you see anything wrong the test scripts/settings/versions?

**Comment by LeoNatan** [comment]
At first I thought that the `setPermission` API inside `Deriver` only called it if no simulator was attached or `newInstance: true` was provided. But this is not the case in the code. The code checks if a `permissions` object was passed, and if so, calls `applesimutils`. I don't see that call.

**Comment by LeoNatan** [comment]
https://github.com/wix/Detox/blob/491bb52e6b259b12f0825b976cf02d4b9de771d5/detox/src/devices/Device.js#L73
https://github.com/wix/Detox/blob/491bb52e6b259b12f0825b976cf02d4b9de771d5/detox/src/devices/drivers/SimulatorDriver.js#L113
https://github.com/wix/Detox/blob/491bb52e6b259b12f0825b976cf02d4b9de771d5/detox/src/devices/ios/AppleSimUtils.js#L6

Maybe I am too tired, but I don't see a problem.
