### ISSUE TITLE
Handling the inbuilt app of OS 

### ISSUE THREAD

**Issue by yogeshthanvi** [wix/Detox#1086]
I am trying to open Maps app in iOS simulator using a link in my App. I also waited for cancel button and switch to my previous app but while waiting for the button I got the below error.

Can anyone help me on this ? 

Parameter cannot be nil or NULL.
(
	0   CoreFoundation                      0x000000010d4dc1bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010c13f735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010d4dbf42 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00000001096a1877 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194
	4   EarlGrey                            0x000000012887674d +[GREYElementHierarchy hierarchyStringForElement:] + 285
	5   Detox                               0x0000000107435139 -[TestFailureHandler handleException:details:] + 159
	6   EarlGrey                            0x00000001288563e6 -[GREYElementInteraction grey_handleFailureOfAssertion:assertionError:userProvidedOutError:] + 10182
	7   EarlGrey                            0x000000012885004c __39-[GREYElementInteraction assert:error:]_block_invoke + 3100
	8   EarlGrey                            0x0000000128882cb8 __59-[GREYUIThreadExecutor executeSyncWithTimeout:block:error:]_block_invoke + 104
	9   EarlGrey                            0x000000012882d647 __54-[GREYRunLoopSpinner grey_checkConditionInActiveMode:]_block_invoke + 471
	10  CoreFoundation                      0x000000010d44162c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	11  CoreFoundation                      0x000000010d440de0 __CFRunLoopDoBlocks + 336
	12  CoreFoundation                      0x000000010d43b62e __CFRunLoopRun + 1246
	13  CoreFoundation                      0x000000010d43ae11 CFRunLoopRunSpecific + 625
	14  EarlGrey                            0x000000012882d33d -[GREYRunLoopSpinner grey_checkConditionInActiveMode:] + 381
	15  EarlGrey                            0x000000012882be7f -[GREYRunLoopSpinner spinWithStopConditionBlock:] + 463
	16  EarlGrey                            0x00000001288823b9 -[GREYUIThreadExecutor executeSyncWithTimeout:block:error:] + 1497
	17  EarlGrey                            0x000000012884e8a4 -[GREYElementInteraction assert:error:] + 2212
	18  EarlGrey                            0x00000001288503fe -[GREYElementInteraction assertWithMatcher:error:] + 142
	19  EarlGrey                            0x000000012885030f -[GREYElementInteraction assertWithMatcher:] + 79
	20  CoreFoundation                      0x000000010d4e303c __invoking___ + 140
	21  CoreFoundation                      0x000000010d4e04d5 -[NSInvocation invoke] + 325
	22  Detox                               0x000000010743e9f4 +[DTXMethodInvocation invoke:onError:] + 833
	23  Detox                               0x000000010743a557 __35-[TestRunner invoke:withMessageId:]_block_invoke + 134
	24  CoreFoundation                      0x000000010d44162c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	25  CoreFoundation                      0x000000010d440de0 __CFRunLoopDoBlocks + 336
	26  CoreFoundation                      0x000000010d43bc2b __CFRunLoopRun + 2779
	27  CoreFoundation                      0x000000010d43ae11 CFRunLoopRunSpecific + 625
	28  GraphicsServices                    0x000000010f60d1dd GSEventRunModal + 62
	29  Detox                               0x0000000107439913 __detox_run + 284
	30  UIKitCore                           0x00000001167c881d UIApplicationMain + 140
	31  RNMasterApp                         0x0000000105929cb0 main + 112
	32  libdyld.dylib                       0x000000010e5f2575 start + 1
)

**Comment by LeoNatan** [comment]
External apps are not supported. Mock you API.

**Comment by LeoNatan** [comment]
This may be supported if/when we upgrade to Earl Grey 2.0, but there is no timeline. Better not to wait for it.
