### ISSUE TITLE
Postinstall installation error build_framework.ios.sh

### ISSUE THREAD

**Issue by pjay79** [wix/Detox#1092]
#### Description

In my React Native project, I get an when error trying to install Detox with `yarn add detox --dev`.

#### Steps to Reproduce

This is my first time installing Detox. I have seen others report similar issues, I am using the latest version of Detox. 

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 9.1.2
* React Native: 0.57.7
* Node: 10.14.1
* Device: iPhone X, simulator
* Xcode: 10.1
* macOS: macOS Mojave 10.14.2

#### Device and verbose Detox logs

```
error /Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox: Command failed.
Exit code: 1
Command: node scripts/postinstall.js
Arguments:
Directory: /Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox
Output:
+ xcodebuild -version
+++ dirname /Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox/scripts/build_framework.ios.sh
++ dirname /Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox/scripts
+ detoxRootPath=/Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox
++ node -p 'require('\''/Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox/package.json'\'').version'
+ detoxVersion=9.1.2
++ echo 9.1.2
++ xcodebuild -version
++ shasum
++ awk '{print $1}'
+ sha1=aec62188116fcc095542b8295542435cd5c8a400
+ detoxFrameworkDirPath=/Users/praveen/Library/Detox/ios/aec62188116fcc095542b8295542435cd5c8a400
+ detoxFrameworkPath=/Users/praveen/Library/Detox/ios/aec62188116fcc095542b8295542435cd5c8a400/Detox.framework
+ main
+ '[' -d /Users/praveen/Library/Detox/ios/aec62188116fcc095542b8295542435cd5c8a400 ']'
+ prepareAndBuildFramework
+ '[' -d /Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox/ios ']'
+ detoxSourcePath=/Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox/ios_src
+ extractSources /Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox/ios_src
+ detoxSourcePath=/Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox/ios_src
+ echo 'Extracting Detox sources...'
Extracting Detox sources...
+ mkdir -p /Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox/ios_src
+ tar -xjf /Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox/Detox-ios-src.tbz -C /Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox/ios_src
+ buildFramework /Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox/ios_src
+ detoxSourcePath=/Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox/ios_src
+ echo 'Building Detox.framework from /Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox/ios_src...'
+ mkdir -p /Users/praveen/Library/Detox/ios/aec62188116fcc095542b8295542435cd5c8a400
Building Detox.framework from /Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox/ios_src...
+ /Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox/scripts/build_universal_framework.sh /Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox/ios_src/Detox.xcodeproj /Users/praveen/Library/Detox/ios/aec62188116fcc095542b8295542435cd5c8a400
child_process.js:632
    throw err;
    ^

Error: Command failed: /Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox/scripts/build_framework.ios.sh
    at checkExecSyncError (child_process.js:611:11)
    at Object.execFileSync (child_process.js:629:13)
    at Object.<anonymous> (/Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox/scripts/postinstall.js:2:27)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)

```

**Comment by rotemmiz** [comment]
Run `/Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox/scripts/build_framework.ios.sh` separately, what's the output?

**Comment by pjay79** [comment]
> Run `/Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox/scripts/build_framework.ios.sh` separately, what's the output?

```
+ xcodebuild -version
+++ dirname /Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox/scripts/build_framework.ios.sh
++ dirname /Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox/scripts
+ detoxRootPath=/Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox
++ node -p 'require('\''/Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox/package.json'\'').version'
+ detoxVersion=9.1.2
++ echo 9.1.2
++ xcodebuild -version
++ shasum
++ awk '{print $1}'
+ sha1=aec62188116fcc095542b8295542435cd5c8a400
+ detoxFrameworkDirPath=/Users/praveen/Library/Detox/ios/aec62188116fcc095542b8295542435cd5c8a400
+ detoxFrameworkPath=/Users/praveen/Library/Detox/ios/aec62188116fcc095542b8295542435cd5c8a400/Detox.framework
+ main
+ '[' -d /Users/praveen/Library/Detox/ios/aec62188116fcc095542b8295542435cd5c8a400 ']'
+ '[' '!' -d /Users/praveen/Library/Detox/ios/aec62188116fcc095542b8295542435cd5c8a400/Detox.framework ']'
+ echo '/Users/praveen/Library/Detox/ios/aec62188116fcc095542b8295542435cd5c8a400 was found, but could not find Detox.framework inside it. This means that the Detox framework build process was interrupted.
         deleting /Users/praveen/Library/Detox/ios/aec62188116fcc095542b8295542435cd5c8a400 and trying to rebuild.'
/Users/praveen/Library/Detox/ios/aec62188116fcc095542b8295542435cd5c8a400 was found, but could not find Detox.framework inside it. This means that the Detox framework build process was interrupted.
         deleting /Users/praveen/Library/Detox/ios/aec62188116fcc095542b8295542435cd5c8a400 and trying to rebuild.
+ rm -rf /Users/praveen/Library/Detox/ios/aec62188116fcc095542b8295542435cd5c8a400
+ prepareAndBuildFramework
+ '[' -d /Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox/ios ']'
+ detoxSourcePath=/Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox/ios_src
+ extractSources /Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox/ios_src
+ detoxSourcePath=/Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox/ios_src
+ echo 'Extracting Detox sources...'
Extracting Detox sources...
+ mkdir -p /Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox/ios_src
+ tar -xjf /Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox/Detox-ios-src.tbz -C /Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox/ios_src
+ buildFramework /Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox/ios_src
+ detoxSourcePath=/Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox/ios_src
+ echo 'Building Detox.framework from /Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox/ios_src...'
Building Detox.framework from /Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox/ios_src...
+ mkdir -p /Users/praveen/Library/Detox/ios/aec62188116fcc095542b8295542435cd5c8a400
+ /Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox/scripts/build_universal_framework.sh /Users/praveen/Documents/coding/react/BarsAppAmplify/node_modules/detox/ios_src/Detox.xcodeproj /Users/praveen/Library/Detox/ios/aec62188116fcc095542b8295542435cd5c8a400
```

**Comment by seacloud9** [comment]
@rotemmiz I have been experiencing this issue too. 

install: 

```
Output:
+ xcodebuild -version
+++ dirname /Users/brsmith/Development/adhd/hcs-x01/node_modules/detox/scripts/build_framework.ios.sh
++ dirname /Users/brsmith/Development/adhd/hcs-x01/node_modules/detox/scripts
+ detoxRootPath=/Users/brsmith/Development/adhd/hcs-x01/node_modules/detox
++ node -p 'require('\''/Users/brsmith/Development/adhd/hcs-x01/node_modules/detox/package.json'\'').version'
+ detoxVersion=10.0.2
++ echo 10.0.2
++ xcodebuild -version
++ shasum
++ awk '{print $1}'
+ sha1=680bbde0ab5eb3ab73f26379f7c34e297d4c3a2f
+ detoxFrameworkDirPath=/Users/brsmith/Library/Detox/ios/680bbde0ab5eb3ab73f26379f7c34e297d4c3a2f
+ detoxFrameworkPath=/Users/brsmith/Library/Detox/ios/680bbde0ab5eb3ab73f26379f7c34e297d4c3a2f/Detox.framework
+ main
+ '[' -d /Users/brsmith/Library/Detox/ios/680bbde0ab5eb3ab73f26379f7c34e297d4c3a2f ']'
+ prepareAndBuildFramework
+ '[' -d /Users/brsmith/Development/adhd/hcs-x01/node_modules/detox/ios ']'
+ detoxSourcePath=/Users/brsmith/Development/adhd/hcs-x01/node_modules/detox/ios_src
+ extractSources /Users/brsmith/Development/adhd/hcs-x01/node_modules/detox/ios_src
+ detoxSourcePath=/Users/brsmith/Development/adhd/hcs-x01/node_modules/detox/ios_src
+ echo 'Extracting Detox sources...'
Extracting Detox sources...
+ mkdir -p /Users/brsmith/Development/adhd/hcs-x01/node_modules/detox/ios_src
+ tar -xjf /Users/brsmith/Development/adhd/hcs-x01/node_modules/detox/Detox-ios-src.tbz -C /Users/brsmith/Development/adhd/hcs-x01/node_modules/detox/ios_src
+ buildFramework /Users/brsmith/Development/adhd/hcs-x01/node_modules/detox/ios_src
+ detoxSourcePath=/Users/brsmith/Development/adhd/hcs-x01/node_modules/detox/ios_src
+ echo 'Building Detox.framework from /Users/brsmith/Development/adhd/hcs-x01/node_modules/detox/ios_src...'
Building Detox.framework from /Users/brsmith/Development/adhd/hcs-x01/node_modules/detox/ios_src...
+ mkdir -p /Users/brsmith/Library/Detox/ios/680bbde0ab5eb3ab73f26379f7c34e297d4c3a2f
+ /Users/brsmith/Development/adhd/hcs-x01/node_modules/detox/scripts/build_universal_framework.sh /Users/brsmith/Development/adhd/hcs-x01/node_modules/detox/ios_src/Detox.xcodeproj /Users/brsmith/Library/Detox/ios/680bbde0ab5eb3ab73f26379f7c34e297d4c3a2f
child_process.js:630
    throw err;
    ^

Error: Command failed: /Users/brsmith/Development/adhd/hcs-x01/node_modules/detox/scripts/build_framework.ios.sh
    at checkExecSyncError (child_process.js:607:13)
    at Object.execFileSync (child_process.js:627:13)
    at Object.<anonymous> (/Users/brsmith/Development/adhd/hcs-x01/node_modules/detox/scripts/postinstall.js:2:27)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
```
xcode-select path 
/Applications/Xcode.app/Contents/Developer

when I run this directly:

```
hcs-x01 brsmith$  /Users/brsmith/Development/adhd/hcs-x01/node_modules/detox/scripts/build_framework.ios.sh
+ xcodebuild -version
+++ dirname /Users/brsmith/Development/adhd/hcs-x01/node_modules/detox/scripts/build_framework.ios.sh
++ dirname /Users/brsmith/Development/adhd/hcs-x01/node_modules/detox/scripts
+ detoxRootPath=/Users/brsmith/Development/adhd/hcs-x01/node_modules/detox
++ node -p 'require('\''/Users/brsmith/Development/adhd/hcs-x01/node_modules/detox/package.json'\'').version'
+ detoxVersion=10.0.2
++ echo 10.0.2
++ xcodebuild -version
++ shasum
++ awk '{print $1}'
+ sha1=680bbde0ab5eb3ab73f26379f7c34e297d4c3a2f
+ detoxFrameworkDirPath=/Users/brsmith/Library/Detox/ios/680bbde0ab5eb3ab73f26379f7c34e297d4c3a2f
+ detoxFrameworkPath=/Users/brsmith/Library/Detox/ios/680bbde0ab5eb3ab73f26379f7c34e297d4c3a2f/Detox.framework
+ main
+ '[' -d /Users/brsmith/Library/Detox/ios/680bbde0ab5eb3ab73f26379f7c34e297d4c3a2f ']'
+ '[' '!' -d /Users/brsmith/Library/Detox/ios/680bbde0ab5eb3ab73f26379f7c34e297d4c3a2f/Detox.framework ']'
+ echo '/Users/brsmith/Library/Detox/ios/680bbde0ab5eb3ab73f26379f7c34e297d4c3a2f was found, but could not find Detox.framework inside it. This means that the Detox framework build process was interrupted.
         deleting /Users/brsmith/Library/Detox/ios/680bbde0ab5eb3ab73f26379f7c34e297d4c3a2f and trying to rebuild.'
/Users/brsmith/Library/Detox/ios/680bbde0ab5eb3ab73f26379f7c34e297d4c3a2f was found, but could not find Detox.framework inside it. This means that the Detox framework build process was interrupted.
         deleting /Users/brsmith/Library/Detox/ios/680bbde0ab5eb3ab73f26379f7c34e297d4c3a2f and trying to rebuild.
+ rm -rf /Users/brsmith/Library/Detox/ios/680bbde0ab5eb3ab73f26379f7c34e297d4c3a2f
+ prepareAndBuildFramework
+ '[' -d /Users/brsmith/Development/adhd/hcs-x01/node_modules/detox/ios ']'
+ detoxSourcePath=/Users/brsmith/Development/adhd/hcs-x01/node_modules/detox/ios_src
+ extractSources /Users/brsmith/Development/adhd/hcs-x01/node_modules/detox/ios_src
+ detoxSourcePath=/Users/brsmith/Development/adhd/hcs-x01/node_modules/detox/ios_src
+ echo 'Extracting Detox sources...'
Extracting Detox sources...
+ mkdir -p /Users/brsmith/Development/adhd/hcs-x01/node_modules/detox/ios_src
+ tar -xjf /Users/brsmith/Development/adhd/hcs-x01/node_modules/detox/Detox-ios-src.tbz -C /Users/brsmith/Development/adhd/hcs-x01/node_modules/detox/ios_src
+ buildFramework /Users/brsmith/Development/adhd/hcs-x01/node_modules/detox/ios_src
+ detoxSourcePath=/Users/brsmith/Development/adhd/hcs-x01/node_modules/detox/ios_src
+ echo 'Building Detox.framework from /Users/brsmith/Development/adhd/hcs-x01/node_modules/detox/ios_src...'
Building Detox.framework from /Users/brsmith/Development/adhd/hcs-x01/node_modules/detox/ios_src...
+ mkdir -p /Users/brsmith/Library/Detox/ios/680bbde0ab5eb3ab73f26379f7c34e297d4c3a2f
+ /Users/brsmith/Development/adhd/hcs-x01/node_modules/detox/scripts/build_universal_framework.sh /Users/brsmith/Development/adhd/hcs-x01/node_modules/detox/ios_src/Detox.xcodeproj /Users/brsmith/Library/Detox/ios/680bbde0ab5eb3ab73f26379f7c34e297d4c3a2f
```

When I run build_framework.ios.sh it seems to work but it will still not build and run the tests?  I have tried uninstalling detox etc but had no luck.  

OSX 10.14 
xCode Version 10.1 (10B61)

**Comment by seacloud9** [comment]
The issue was caused in my case by running multiple versions of xCode. To see the real issue I had to manually build detox from that point I could see the failure.  

It was fixed by https://stackoverflow.com/questions/39635735/swift-does-not-support-the-sdk-iphonesimulator9-3-sdk

**Comment by xxsnakerxx** [comment]
I have same issue

Detox 10.0.7
OSX 10.14
xCode Version 10.1 (10B61)

Found in `$HOME/Library/Detox/ios/${sha1}/detox_ios.log` error

```
node_modules/detox/ios_src/Detox/DTXMethodInvocation.m:11:9: fatal error: 'EarlGrey/GreyActions.h' file not found
#import <EarlGrey/GreyActions.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~
```

🤔

**Comment by xxsnakerxx** [comment]
changes added here https://github.com/wix/Detox/commit/6a1d700eac0d2f84294e30b4fd18776db4d604df#diff-5ee60c03716db19817f236ea45a7a851R11

how to fix this?

**Comment by igor-lemon** [comment]
I have the same error.
v10.0.5 was installed correctly
v10.0.7 couldn't install

**Comment by svenjens** [comment]
i also have this error in earlier versions of detox. 
Maybe because of the react-native version?

**Comment by Evanion** [comment]
Same here .. when Detox tries to setup it seems like it's unable to build the `Detox.framework` in `~/Library/Detox/ios/<hash>/Detox.framework`
and the hash folder instead contains a [log file](https://gist.github.com/Evanion/b582e10c36adf0300656abe5730f397f).

**Comment by rdewolff** [comment]
Same error, cannot run the examples. How can we fix this?

**Comment by jaychenjun** [comment]
+1

**Comment by rotemmiz** [comment]
We seem to have found the issue, this only happens on machines with case sensitive file system.
https://github.com/wix/Detox/commit/6a1d700eac0d2f84294e30b4fd18776db4d604df#diff-5ee60c03716db19817f236ea45a7a851R11 is now being fixed, 
`#import <EarlGrey/GreyActions.h>` -> `#import <EarlGrey/GREYActions.h>`

**Comment by LeoNatan** [comment]
🤦‍♂️

**Comment by rotemmiz** [comment]
Solved in 10.0.10 with https://github.com/wix/Detox/commit/8714bb4185480e62819134bf6db4e67751f99ba0

**Comment by svenjens** [comment]
hmm, i still have this.

**Comment by rdewolff** [comment]
With what version do you still have the issue @svenjens ?

**Comment by svenjens** [comment]
@rdewolff 10.0.10. in which it should be fixed.

**Comment by rdewolff** [comment]
Guys, please reopen the issue.

**Comment by LeoNatan** [comment]
Please post the log.

**Comment by rdewolff** [comment]
That was fast 👍

**Comment by svenjens** [comment]
> dtrace-provider@0.8.7 install /Users/svenjens/Apps/ober-app/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

  ACTION binding_gyp_ndtp_target_build_ndtp .
  TOUCH Release/obj.target/ndtp.stamp

> detox@10.0.10 postinstall /Users/svenjens/Apps/ober-app/node_modules/detox
> node scripts/postinstall.js

+ xcodebuild -version
+++ dirname /Users/svenjens/Apps/ober-app/node_modules/detox/scripts/build_framework.ios.sh
++ dirname /Users/svenjens/Apps/ober-app/node_modules/detox/scripts
+ detoxRootPath=/Users/svenjens/Apps/ober-app/node_modules/detox
++ node -p 'require('\''/Users/svenjens/Apps/ober-app/node_modules/detox/package.json'\'').version'
+ detoxVersion=10.0.10
++ echo 10.0.10
++ xcodebuild -version
++ shasum
++ awk '{print $1}'
+ sha1=68adb0e2a13b03316436762fbccbc78265ae0702
+ detoxFrameworkDirPath=/Users/svenjens/Library/Detox/ios/68adb0e2a13b03316436762fbccbc78265ae0702
+ detoxFrameworkPath=/Users/svenjens/Library/Detox/ios/68adb0e2a13b03316436762fbccbc78265ae0702/Detox.framework
+ main
+ '[' -d /Users/svenjens/Library/Detox/ios/68adb0e2a13b03316436762fbccbc78265ae0702 ']'
+ '[' '!' -d /Users/svenjens/Library/Detox/ios/68adb0e2a13b03316436762fbccbc78265ae0702/Detox.framework ']'
+ echo '/Users/svenjens/Library/Detox/ios/68adb0e2a13b03316436762fbccbc78265ae0702 was found, but could not find Detox.framework inside it. This means that the Detox framework build process was interrupted.
         deleting /Users/svenjens/Library/Detox/ios/68adb0e2a13b03316436762fbccbc78265ae0702 and trying to rebuild.'
/Users/svenjens/Library/Detox/ios/68adb0e2a13b03316436762fbccbc78265ae0702 was found, but could not find Detox.framework inside it. This means that the Detox framework build process was interrupted.
         deleting /Users/svenjens/Library/Detox/ios/68adb0e2a13b03316436762fbccbc78265ae0702 and trying to rebuild.
+ rm -rf /Users/svenjens/Library/Detox/ios/68adb0e2a13b03316436762fbccbc78265ae0702
+ prepareAndBuildFramework
+ '[' -d /Users/svenjens/Apps/ober-app/node_modules/detox/ios ']'
+ detoxSourcePath=/Users/svenjens/Apps/ober-app/node_modules/detox/ios_src
+ extractSources /Users/svenjens/Apps/ober-app/node_modules/detox/ios_src
+ detoxSourcePath=/Users/svenjens/Apps/ober-app/node_modules/detox/ios_src
+ echo 'Extracting Detox sources...'
Extracting Detox sources...
+ mkdir -p /Users/svenjens/Apps/ober-app/node_modules/detox/ios_src
+ tar -xjf /Users/svenjens/Apps/ober-app/node_modules/detox/Detox-ios-src.tbz -C /Users/svenjens/Apps/ober-app/node_modules/detox/ios_src
+ buildFramework /Users/svenjens/Apps/ober-app/node_modules/detox/ios_src
+ detoxSourcePath=/Users/svenjens/Apps/ober-app/node_modules/detox/ios_src
+ echo 'Building Detox.framework from /Users/svenjens/Apps/ober-app/node_modules/detox/ios_src...'
Building Detox.framework from /Users/svenjens/Apps/ober-app/node_modules/detox/ios_src...
+ mkdir -p /Users/svenjens/Library/Detox/ios/68adb0e2a13b03316436762fbccbc78265ae0702
+ /Users/svenjens/Apps/ober-app/node_modules/detox/scripts/build_universal_framework.sh /Users/svenjens/Apps/ober-app/node_modules/detox/ios_src/Detox.xcodeproj /Users/svenjens/Library/Detox/ios/68adb0e2a13b03316436762fbccbc78265ae0702
child_process.js:624
    throw err;
    ^

Error: Command failed: /Users/svenjens/Apps/ober-app/node_modules/detox/scripts/build_framework.ios.sh
    at checkExecSyncError (child_process.js:601:13)
    at Object.execFileSync (child_process.js:621:13)
    at Object.<anonymous> (/Users/svenjens/Apps/ober-app/node_modules/detox/scripts/postinstall.js:2:27)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! detox@10.0.10 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the detox@10.0.10 postinstall script.

**Comment by LeoNatan** [comment]
Upload the detox build log, not the npm install log. `$HOME/Library/Detox/ios/${sha1}/detox_ios.log`

**Comment by svenjens** [comment]
it gives me 21 times 
```
/Users/svenjens/Apps/ober-app/node_modules/detox/ios_src/Detox/WXJSTimerObservationIdlingResource.h:10:9: fatal error: 'EarlGrey/EarlGrey.h' file not found
#import <EarlGrey/EarlGrey.h>
        ^~~~~~~~~~~~~~~~~~~~~
1 error generated.```

Do you need to whole log ?

**Comment by svenjens** [comment]
The following files: 
TestFailureHandler.h:10:9:
WebSocket.m:10:9
WXRunLoopIdlingResource.h:10:9:
EarlGreyExtensions.h:9:9:
EarlGrey+Detox.h:10:9
GREYMatchers+Detox.h:9:9:
TestFailureHandler.h:10:9:
DTXMethodInvocation.m:10:9:
GREYCondition+Detox.h:9:9
WXRNLoadIdlingResource.h:10:9:
WXAnimatedDisplayLinkIdlingResource.h:10:9

```
DetoxAppDelegateProxy.m:13:9: fatal error: module 'COSTouchVisualizer' not found
@import COSTouchVisualizer;
```

**Comment by LeoNatan** [comment]
Please post the entire log. Make sure to clear `$HOME/Library/Detox/` first, then try to npm install where Detox fails and provide the entire log created at `$HOME/Library/Detox/ios/${sha1}/detox_ios.log`.

**Comment by svenjens** [comment]
The whole log, its big:
 
https://justpaste.it/3rmj6

**Comment by LeoNatan** [comment]
This looks unrelated to this issue. Please open a new one and attach that log. Thanks
