### ISSUE TITLE
Is it possible to send "Search" to the keyboard?

### ISSUE THREAD

**Issue by lbutterfly** [wix/Detox#1096]
#### Description

I want to use "\n" to connect search icon in keyboard for native android app, but it is nothing happen. below is my code:

await element(by.id('search_bar')).typeText('toy\n');

Note: this code is successful on my native iOS app.

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 8.2.3
* React Native: None 
* Node: v11.0.0
* Device: Emulator Nexus_6_API_28
* Xcode: 10.0.0
* macOS: 10.14

#### Screenshot for keyboard
![device-screen](https://user-images.githubusercontent.com/16079916/50415106-3b7f8a00-0854-11e9-99ab-4e747fad08f7.png)

**Comment by cucumbur** [comment]
Do you have more context for how your component is declared? i.e. what props are you using and what are you assigning to them
