### ISSUE TITLE
Issue with _queryPID function

### ISSUE THREAD

**Issue by AntaninaKaltsova** [wix/Detox#1100]
#### Description
I was faced with the problem with `async _queryPID` function in AdroidDriver.js file.
For example, the `pidof` function returns a value only from the 3rd time, then the previous 2 write errors to the console

`detox[14376] ERROR: [exec.js/EXEC_FAIL, #15] "C:\Users\User_Name\AppData\Local\Android\Sdk\platform-tools\adb -s emulator-5554 shell "ps | grep \"com\.example\.nameOfProject$\""" failed with code = 1, stdout and stderr:
`
Although this function works, and the application starts, the tests go. Is it possible to solve this problem?
At the moment I had to change the line in AdroidDriver.js file:
`if (waitAtStart) {
      await sleep(500);
    }`
to
`if (waitAtStart) {
      await sleep(3000);
    }`

* Detox: "9.1.2"
* React Native: "0.57.4"
* Node: "10.14.2"
* Device: "Nexus_5X_API_26"

**Comment by rotemmiz** [comment]
Detox is not supported officially on Windows as we don't have a way to run on Windows CI agents, the current support was added by the community. We were glad to accept it, but as noted above, can't maintain it.
Do you only see this in Windows? do you see it in any other OS?

**Comment by noomorph** [comment]
@rotemmiz, as far as I can see, the issue is about a flaw in a quite naive mechanism of awaiting till the testee app actually starts running and gets PID assigned so you can query it via `pidof` or `ps`. On one hand, I don't see harm to tweak a bit timings there and also refactor the code to use `utils/retry`, but on another hand, it would be much better to have a less naive approach than polling process id with intervals.

**Comment by solkaz** [comment]
It's an issue present on OSX as well. No, this isn't a blocker for anything, more of an annoyance (because it's not really an error)

**Comment by AntaninaKaltsova** [comment]
Yes, @solkaz it is rather misleading because the console has red messages)

**Comment by firdausious** [comment]
Any update for this ?  I faced same issue with MacOS

**Comment by AntaninaKaltsova** [comment]
Hello! Unfortunately this issue is still reproduced

**Comment by noomorph** [comment]
@AntaninaKaltsova, @solkaz, I promise to take this as a first task when I return to Detox, hopefully on this week already.
