### ISSUE TITLE
Improve the way we can interract with react-native-maps

### ISSUE THREAD

**Issue by sraikimaxime** [wix/Detox#1105]
#### Description

Hello I'm working on improvement allowing us to make a deeper / simpler use of detox with react-native-maps.
My thought came from these two issues #<250> and #<589>.

I did a first [PR](https://github.com/wix/Detox/pull/1104) before realizing I had not followed the proper contributing workflow (and created directly my earlGrey actions in the generated file :/ sorry.
I'll implement the proper generation soon for iOS and continue through android if we confirm that it is useful together :).

**Comment by rotemmiz** [comment]
Closed with #1104
