### ISSUE TITLE
 detox test - command doesn't work without additional params

### ISSUE THREAD

**Issue by DmitriyKow77** [wix/detox#111]
The command really worked for me is: detox test --configuration ios.sim.debug
But only Leo told me to use it. 
detox test return: 

 "before all" hook:
     Error: Cannot determine which configuration to use. use --configuration to choose one of the following: 
                      ios.sim.release,ios.sim.debug

**Comment by DmitriyKow77** [comment]
There is a command about later, but I didn't reach that place yet

**Comment by rotemmiz** [comment]
Docs have been revised and are now clearer as to detox-cli usage
