### ISSUE TITLE
Bring back printing of device logs location

### ISSUE THREAD

**Issue by Niryo** [wix/Detox#1110]
#### Description
In previous versions of detox, on every successful installation on the device, detox was printing the location of the device's log (line 10):
![image 2](https://user-images.githubusercontent.com/8758348/50761913-3e2aa800-1274-11e9-90e5-b689eb50c7c9.png)

On the newer version of Detox, we cannot see the location of the device log unless we turn on loglevel verbose or loglevel trace, but then the logs contain too much information for day to day usage:
![image 3](https://user-images.githubusercontent.com/8758348/50761985-6a462900-1274-11e9-9924-b0d2ef949dbc.png)

Please bring back the logs to the standard loglevel, it was very useful and made life easier. 
Thanks!

**Comment by noomorph** [comment]
What do you think if you could have used Detox log artifacts?

**Comment by Niryo** [comment]
can you explain?

**Comment by Niryo** [comment]
Without going deeply into that solution, I think it's an overkill for what I am asking for. I just want the path to the device logs so I could read them in my terminal. It was a very convenient feature of old detox versions- just copy the path, paste it in the terminal and see the logs. no boilerplate.

**Comment by noomorph** [comment]
Okay, I see.

@rotemmiz, in general, do you mind if we return the former behavior back where it was?

**Comment by rotemmiz** [comment]
We should probably stop using that and start using `xcrun simctl spawn booted log stream --level=info --predicate {somePredicate}` instead

**Comment by rotemmiz** [comment]
But to answer your question, sure, why not.

**Comment by LeoNatan** [comment]
We should be using the new log system.

**Comment by LeoNatan** [comment]
And so can @Niryo to get his log

**Comment by rotemmiz** [comment]
@LeoNatan what do you mean? `xcrun simctl spawn {deviceudid} log` ?

**Comment by LeoNatan** [comment]
Yes. In the case @Niryo, he can limit his log output using that command to only his app, which is preferable for him.

**Comment by Niryo** [comment]
the problem is not limiting the log output, but locating the device logs. look at the first picture, back at the good old days, detox was printing the location of the device logs and it was very convenient.
But maybe I got your answer wrong.

**Comment by LeoNatan** [comment]
You are missing the point. You don't need to locate anything. Using the new `log` command, you can get the output of your app's log to just stream in your terminal.

**Comment by LeoNatan** [comment]
@Niryo Read here: https://www.iosdev.recipes/simulator/os_log/

**Comment by Niryo** [comment]
@noomorph hi, this issue has been fixed in detox 13, but now it looks like the logs are gone again

**Comment by LeoNatan** [comment]
What do you mean @Niryo ? The command to print logs is no longer printed?

**Comment by LeoNatan** [comment]
Please don't reopen old issues. Open a new one and provide a description of the problem as it exists today. Thanks
