### ISSUE TITLE
Detox build failed - with solution

### ISSUE THREAD

**Issue by simonepauro** [wix/Detox#1111]
#### Description
detox build fails after following the guide

#### Steps to Reproduce
Follow this [guide](https://github.com/wix/detox/blob/master/docs/Introduction.GettingStarted.md)

#### The solution
In Xcode, go to File->Project/Workspace settings.
Change the build system to Legacy Build system.

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 9.1.2
* React Native: 0.57.8
* Node: 8.12.0
* Device: MacBook Pro (15-inch, 2016)
* Xcode: 10.1 (10B61)
* macOS: 10.14.2 (18C54)

**Comment by LeoNatan** [comment]
Hello,

Facebook has not updated their framework to support the new build system. I don't see how this is Detox related.

**Comment by simonepauro** [comment]
It’s not detox related but detox guide will not work if you miss this

**Comment by simonepauro** [comment]
I will, thank you
