### ISSUE TITLE
It should be configurable to hide Hierachy on failure.

### ISSUE THREAD

**Issue by reneeichhorn** [wix/Detox#1113]
#### Description
Larger apps especially apps that have tab navigations have a big amount of views / components.
In these cases printing the hierachy on error is not helpful at all and just causes endless scrolling in the terminal.

#### Steps to Reproduce
- Run mid to large sized app
- Cause any test to fail
- Check terminal output.

#### Detox, Node, Device, Xcode and macOS Versions
* Detox: 9.1.2
* React Native: 0.57.4 (not related)
* Node: 11.6.0 (happens on any)
* Device: iPad Air Simulator (happens on any)
* Xcode: 10.1 (not related)
* macOS: Mojave (not related)

**Comment by LeoNatan** [comment]
Hello,

This has been asked in the past and we have declined. I don't think we will reconsider at this point, sorry.

The size of app does not dictate that its view hierarchy be unmanageable or unreadable. On a general note, unrelated to Detox, if your view hierarchy is huge, you should consider improving your app. Huge view hierarchies slow down the app and give a bad user experience. In the case of React Native, even more care has to be put when building apps. If you are using JS navigation solutions, you can move to a proper solution that does not require that all views of all tabs be present on screen. That makes no sense.
