### ISSUE TITLE
Problem with generate report with detox screenshots

### ISSUE THREAD

**Issue by AntaninaKaltsova** [wix/Detox#1114]
Hi! I should test React Native app, so I use Detox framework for testing.
Using Detox in order to record .png screenshots before and after each test I add argument `--take-screenshots all` to the cli command.
My command looks like:
`node_modules/.bin/cucumber-js -f json:./e2e_reports/cucumber_report.json --require ./e2e/step_definitions --require ./e2e/support ./e2e/features --take-screenshots all --artifacts-location ./e2e_reports/screenshots/ --configuration android.emu.debug`

In this way after all tests passed, I run `node index.js` file and generate `cucumber-report.html` from `cucumber_report.json` using https://www.npmjs.com/package/cucumber-html-reporter.

My hooks.js file is the following:
`const {	Before,	AfterAll, After, BeforeAll, Status } = require('cucumber');
const detox = require('detox');
const config = require('../../package').detox;

let testSummary;

BeforeAll({	timeout: 240 * 1000 }, async () => {
	await detox.init(config, { launchApp: true });
});

Before(async testCase => {
	await device.reloadReactNative();
	testSummary = {
		title: testCase.pickle.name,
		fullName: testCase.pickle.name,
		status: 'running',
	};
	await detox.beforeEach(testSummary);
});

After(async testCase => {
	testSummary.status = testCase.result.status || Status.FAILED;
	await detox.afterEach(testSummary);
});

AfterAll(async () => {
	await detox.cleanup();
});`

My question is the following - how can I attach my screenshots created by Detox into report? I can't use smth like
`return browser.takeScreenshot().then((png) => { world.attach(Buffer.from(png, 'base64'), 'image/png'); });` in afterEach hook because I have a mobile app.

Thanks in advance!

**Comment by d4vidi** [comment]
Hi @AntaninaKaltsova.
It seems that in your command you've set up the artifacts path to `./e2e_reports/screenshots/`. In that case, all screenshots should be available under that directory when each test is over.
For more information, refer to the [artifacts guide](https://github.com/wix/Detox/blob/master/docs/APIRef.Artifacts.md#artifacts).

As a side note, consider using a simpler path (e.g. `./e2e_reports/`), as all artifacts (screenshots, logs etc.) are typically set in one place in a well defined (sub)directory structure; refer to the [Artifacts Structure](https://github.com/wix/Detox/blob/master/docs/APIRef.Artifacts.md#artifacts-structure) section of the guid for more info.

**Comment by d4vidi** [comment]
As per integrating the screenshots into the `cucumber` report -- that is more under the scope of the `cucumber` framework rather than Detox'.

**Comment by LeoNatan** [comment]
We are not familiar with the Cucumber framework. If someone is willing to write a tutorial on this, please open a PR. For now, closing as a question.

**Comment by LeoNatan** [comment]
Also see #237

**Comment by noomorph** [comment]
@AntaninaKaltsova, vote for the unfinished pull request which gives an ability to take screenshots on demand:  https://github.com/wix/Detox/pull/904  . I temporarily left Detox project support so it will take some time till I get back and will able to finish it.
