### ISSUE TITLE
FAILURE: Plugin with id 'kotlin-android' not found.

### ISSUE THREAD

**Issue by ethanneff** [wix/Detox#1122]
command
```
react-native run-android
```

version
```
"detox": "10.0.2",
```

error
```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/ethanneff/Dropbox/active/work/phoenix/node_modules/detox/android/detox/build.gradle' line: 2

* What went wrong:
A problem occurred evaluating project ':detox'.
> Plugin with id 'kotlin-android' not found.
```

**Comment by rotemmiz** [comment]
We failed to release proper release notes, but the documentation is live. https://github.com/wix/Detox/blob/master/docs/Introduction.Android.md#breaking-changes-warning
We will also add it to https://github.com/wix/Detox/blob/master/docs/Guide.Migration.md soon.

Sorry for that.

**Comment by rotemmiz** [comment]
Added to migration guide
