### ISSUE TITLE
Running Detox build command shows following ERROR #detox

### ISSUE THREAD

**Issue by Lokendra-rawat** [wix/Detox#1123]
#### Description

we are trying to add detox to our project which uses rnnv2 and running the command <code> detox build --configuration android.emu.debug </code> throws following error

#### Steps to Reproduce
run  <code> detox build --configuration android.emu.debug </code> 

#### Detox, Node, Device, Xcode and macOS Versions

* Detox:10.0.2
* React Native:0.57.8
* Node:
* Device:
* Xcode:
* macOS: 

#### Device and verbose Detox logs

<pre>
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':detox:minReactNative44DebugCompileClasspath'.
> Could not resolve com.squareup.okhttp3:okhttp:3.4.1.
  Required by:
      project :detox
   > Cannot find a version of 'com.squareup.okhttp3:okhttp' that satisfies the version constraints: 
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Constraint path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.4.1' because of the following reason: minReactNative44DebugRuntimeClasspath uses version 3.4.1
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Constraint path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.4.1' because of the following reason: minReactNative44DebugRuntimeClasspath uses version 3.4.1
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Constraint path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.4.1' because of the following reason: minReactNative44DebugRuntimeClasspath uses version 3.4.1
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Dependency path 'App:detox:unspecified' --> 'com.facebook.react:react-native:0.57.8' --> 'com.squareup.okhttp3:okhttp:3.11.0'
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp-ws:3.4.1' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Dependency path 'App:detox:unspecified' --> 'com.facebook.react:react-native:0.57.8' --> 'com.facebook.fresco:imagepipeline-okhttp3:1.10.0' --> 'com.squareup.okhttp3:okhttp:3.10.0'
        Dependency path 'App:detox:unspecified' --> 'com.facebook.react:react-native:0.57.8' --> 'com.squareup.okhttp3:okhttp-urlconnection:3.11.0' --> 'com.squareup.okhttp3:okhttp:3.11.0'

> Could not resolve com.squareup.okio:okio:1.9.0.
  Required by:
      project :detox
   > Cannot find a version of 'com.squareup.okio:okio' that satisfies the version constraints: 
        Dependency path 'App:detox:unspecified' --> 'com.facebook.react:react-native:0.57.8' --> 'com.squareup.okio:okio:1.14.0'
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp:3.11.0' --> 'com.squareup.okio:okio:1.14.0'
        Dependency path 'App:detox:unspecified' --> 'com.facebook.react:react-native:0.57.8' --> 'com.squareup.okhttp3:okhttp:3.11.0' --> 'com.squareup.okio:okio:1.14.0'
        Constraint path 'App:detox:unspecified' --> 'com.squareup.okio:okio' strictly '1.9.0' because of the following reason: minReactNative44DebugRuntimeClasspath uses version 1.9.0
        Constraint path 'App:detox:unspecified' --> 'com.squareup.okio:okio' strictly '1.9.0' because of the following reason: minReactNative44DebugRuntimeClasspath uses version 1.9.0

> Could not resolve com.squareup.okhttp3:okhttp:3.4.1.
  Required by:
      project :detox
      project :detox > com.squareup.okhttp3:okhttp-ws:3.4.1
   > Cannot find a version of 'com.squareup.okhttp3:okhttp' that satisfies the version constraints: 
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Constraint path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.4.1' because of the following reason: minReactNative44DebugRuntimeClasspath uses version 3.4.1
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Constraint path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.4.1' because of the following reason: minReactNative44DebugRuntimeClasspath uses version 3.4.1
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Constraint path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.4.1' because of the following reason: minReactNative44DebugRuntimeClasspath uses version 3.4.1
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Dependency path 'App:detox:unspecified' --> 'com.facebook.react:react-native:0.57.8' --> 'com.squareup.okhttp3:okhttp:3.11.0'
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp-ws:3.4.1' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Dependency path 'App:detox:unspecified' --> 'com.facebook.react:react-native:0.57.8' --> 'com.facebook.fresco:imagepipeline-okhttp3:1.10.0' --> 'com.squareup.okhttp3:okhttp:3.10.0'
        Dependency path 'App:detox:unspecified' --> 'com.facebook.react:react-native:0.57.8' --> 'com.squareup.okhttp3:okhttp-urlconnection:3.11.0' --> 'com.squareup.okhttp3:okhttp:3.11.0'

> Could not resolve com.squareup.okhttp3:okhttp:3.11.0.
  Required by:
      project :detox > com.facebook.react:react-native:0.57.8
      project :detox > com.facebook.react:react-native:0.57.8 > com.squareup.okhttp3:okhttp-urlconnection:3.11.0
   > Cannot find a version of 'com.squareup.okhttp3:okhttp' that satisfies the version constraints: 
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Constraint path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.4.1' because of the following reason: minReactNative44DebugRuntimeClasspath uses version 3.4.1
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Constraint path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.4.1' because of the following reason: minReactNative44DebugRuntimeClasspath uses version 3.4.1
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Constraint path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.4.1' because of the following reason: minReactNative44DebugRuntimeClasspath uses version 3.4.1
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Dependency path 'App:detox:unspecified' --> 'com.facebook.react:react-native:0.57.8' --> 'com.squareup.okhttp3:okhttp:3.11.0'
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp-ws:3.4.1' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Dependency path 'App:detox:unspecified' --> 'com.facebook.react:react-native:0.57.8' --> 'com.facebook.fresco:imagepipeline-okhttp3:1.10.0' --> 'com.squareup.okhttp3:okhttp:3.10.0'
        Dependency path 'App:detox:unspecified' --> 'com.facebook.react:react-native:0.57.8' --> 'com.squareup.okhttp3:okhttp-urlconnection:3.11.0' --> 'com.squareup.okhttp3:okhttp:3.11.0'

> Could not resolve com.squareup.okio:okio:1.14.0.
  Required by:
      project :detox > com.facebook.react:react-native:0.57.8
      project :detox > com.squareup.okhttp3:okhttp:3.11.0
   > Cannot find a version of 'com.squareup.okio:okio' that satisfies the version constraints: 
        Dependency path 'App:detox:unspecified' --> 'com.facebook.react:react-native:0.57.8' --> 'com.squareup.okio:okio:1.14.0'
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp:3.11.0' --> 'com.squareup.okio:okio:1.14.0'
        Dependency path 'App:detox:unspecified' --> 'com.facebook.react:react-native:0.57.8' --> 'com.squareup.okhttp3:okhttp:3.11.0' --> 'com.squareup.okio:okio:1.14.0'
        Constraint path 'App:detox:unspecified' --> 'com.squareup.okio:okio' strictly '1.9.0' because of the following reason: minReactNative44DebugRuntimeClasspath uses version 1.9.0
        Constraint path 'App:detox:unspecified' --> 'com.squareup.okio:okio' strictly '1.9.0' because of the following reason: minReactNative44DebugRuntimeClasspath uses version 1.9.0

> Could not resolve com.squareup.okhttp3:okhttp:3.10.0.
  Required by:
      project :detox > com.facebook.react:react-native:0.57.8 > com.facebook.fresco:imagepipeline-okhttp3:1.10.0
   > Cannot find a version of 'com.squareup.okhttp3:okhttp' that satisfies the version constraints: 
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Constraint path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.4.1' because of the following reason: minReactNative44DebugRuntimeClasspath uses version 3.4.1
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Constraint path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.4.1' because of the following reason: minReactNative44DebugRuntimeClasspath uses version 3.4.1
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Constraint path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp' strictly '3.4.1' because of the following reason: minReactNative44DebugRuntimeClasspath uses version 3.4.1
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Dependency path 'App:detox:unspecified' --> 'com.facebook.react:react-native:0.57.8' --> 'com.squareup.okhttp3:okhttp:3.11.0'
        Dependency path 'App:detox:unspecified' --> 'com.squareup.okhttp3:okhttp-ws:3.4.1' --> 'com.squareup.okhttp3:okhttp:3.4.1'
        Dependency path 'App:detox:unspecified' --> 'com.facebook.react:react-native:0.57.8' --> 'com.facebook.fresco:imagepipeline-okhttp3:1.10.0' --> 'com.squareup.okhttp3:okhttp:3.10.0'
        Dependency path 'App:detox:unspecified' --> 'com.facebook.react:react-native:0.57.8' --> 'com.squareup.okhttp3:okhttp-urlconnection:3.11.0' --> 'com.squareup.okhttp3:okhttp:3.11.0'
</pre>

**Comment by rotemmiz** [comment]
Seems like you chose the wrong build flavour for your RN version. You should set it to "minReactNative46".
Please go over the integration docs again, it should be there.

**Comment by Lokendra-rawat** [comment]
Already did that still its not working our defaultConfig in app/build.gradle looks like this
<pre>  
 defaultConfig {
        applicationId "com.testrepo2"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        missingDimensionStrategy "minReactNative", "minReactNative46" //read note
        missingDimensionStrategy "RNN.reactNativeVersion", "reactNative57_5"
        testBuildType System.getProperty('testBuildType', 'debug')  //this will later be used to control the test apk build type
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    } </pre>

**Comment by yogeshthanvi** [comment]
@Lokendra-rawat  It seems ur missing some step or done with incorrect way . I suggest read the steps properly and try it again. It is working fine at my side . For react native 57 you need to upgrade android >build.gradle as 
subprojects { afterEvaluate { project -> if (project.hasProperty("android")) { android { compileSdkVersion 28 buildToolsVersion "28.0.3" } } } }

Also please upgrade Android studio if its at lower version

**Comment by Lokendra-rawat** [comment]
Already did that 


> @Lokendra-rawat It seems ur missing some step or done with incorrect way . I suggest read the steps properly and try it again. It is working fine at my side . For react native 57 you need to upgrade android >build.gradle as
> subprojects { afterEvaluate { project -> if (project.hasProperty("android")) { android { compileSdkVersion 28 buildToolsVersion "28.0.3" } } } }
> 
> Also please upgrade Android studio if its at lower version
