### ISSUE TITLE
TypeError: expect(...).typeText is not a function. Checked issue #326 . Not seems to be similar issue. 

### ISSUE THREAD

**Issue by Siva123Prasad** [wix/Detox#1130]
Stacktrace :     

  5 |
      6 |   it('should have welcome screen', async () => {
    > 7 |     await expect(element(by.id('username'))).typeText('username');
        |                                              ^
      8 |   });
      9 | })

      at Object.typeText (firstTest.spec.js:7:46)
      at tryCatch (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:288:22)
      at Generator.prototype.(anonymous function) [as next] (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:114:21)
      at tryCatch (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:62:40)
      at invoke (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:152:20)
      at ../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:187:11
      at callInvokeWithMethodAndArg (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:186:16)
      at AsyncIterator.enqueue (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:209:13)
      at AsyncIterator.prototype.(anonymous function) [as next] (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:114:21)
      at Object.<anonymous>.runtime.async (../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:233:14)
      at Object._callee2 (firstTest.spec.js:6:36)

Package.json is as below: 
{
  "name": "react_native_template",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "react-devtools": "react-devtools"
  },
  "dependencies": {
    "@babel/preset-react": "^7.0.0",
    "fetch-intercept": "^2.3.1",
    "jest": "^23.6.0",
    "native-base": "^2.8.1",
    "react": "16.6.1",
    "react-native": "0.57.5",
    "react-native-device-info": "^0.24.3",
    "react-native-easy-grid": "^0.2.0",
    "react-native-touch-id": "^4.3.0",
    "react-native-vector-icons": "^6.1.0",
    "react-navigation": "^2.16.0",
    "react-redux": "^5.1.1",
    "redux": "^4.0.1",
    "redux-persist": "^5.10.0",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.2.2",
    "@babel/plugin-proposal-class-properties": "^7.3.0",
    "@babel/preset-env": "^7.3.1",
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "^23.6.0",
    "detox": "^10.0.2",
    "metro-react-native-babel-preset": "0.49.1",
    "react-devtools": "^3.4.2",
    "react-test-renderer": "16.6.1",
    "regenerator-runtime": "^0.13.1"
  },
  "jest": {
    "preset": "react-native"
  },
  "detox": {
    "configurations": {
      "ios.sim.debug": {
        "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/react_native_template.app",
        "build": "xcodebuild -project ios/react_native_template.xcodeproj -scheme react_native_template -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build",
        "type": "ios.simulator",
        "name": "iPhone 7"
      }
    },
    "test-runner": "jest"
  }
}

**Comment by yogeshthanvi** [comment]
This is not an issue typeText wont work with expect only toBeVisible , toHaveText and others you can find in docs.

**Comment by Siva123Prasad** [comment]
same with toBeVisible. Not working. 

Stacktrace : 

   ✕ should have welcome screen (1771ms)

  ● Example › should have welcome screen

    Failed: [Error: Error: Cannot find UI Element.
    Exception with Assertion: {
      "Assertion Criteria":  "assertWithMatcher:matcherForSufficientlyVisible(>=0.750000)",
      "Element Matcher":  "((!(kindOfClass('RCTScrollView')) && (respondsToSelector(accessibilityIdentifier) && accessibilityID('username'))) || (((kindOfClass('UIView') || respondsToSelector(accessibilityContainer)) && parentThatMatches(kindOfClass('RCTScrollView'))) && ((kindOfClass('UIView') || respondsToSelector(accessibilityContainer)) && parentThatMatches((respondsToSelector(accessibilityIdentifier) && accessibilityID('username'))))))",
      "Recovery Suggestion":  "Check if the element exists in the UI hierarchy printed below. If it exists, adjust the matcher so that it accurately matches element."
    }


    Error Trace: [
      {
        "Description":  "Interaction cannot continue because the desired element was not found.",
        "Error Domain":  "com.google.earlgrey.ElementInteractionErrorDomain",
        "Error Code":  "0",
        "File Name":  "GREYElementInteraction.m",
        "Function Name":  "-[GREYElementInteraction matchedElementsWithTimeout:error:]",
        "Line":  "124"
      }
    ]

**Comment by yogeshthanvi** [comment]
So its working correct , your element is not visible that's different thing but not an issue. Try inspectors or debug to check it you are on right page or not . Please refer docs

**Comment by Siva123Prasad** [comment]
Why do I get some or the other error? I have installed detox, jest and everything for a test to run. 

Now I am seeing this error.

**Comment by yogeshthanvi** [comment]
Please read the documents , please don't post these kind of issues over here you can check Stackoverflow
