### ISSUE TITLE
pass in files to the cli like jest and mocha do by default

### ISSUE THREAD

**Issue by tjbenton** [wix/Detox#1132]
Currently to specify a specific file you have to do this

```bash
detox test --file 'some/file.js'
```

to test a folder you have to do this

```bash
detox test --specs 'some/folder'
```

and there's a PR open to allow for regex #1083 which you will be able to do like this

```bash
detox test --file 'some/**/*.js'
detox test --specs 'some/**/*.js'
```

Both Mocha and Jest have their setups to already support this by simply passing in all extra files at the end of the commands without having to specify `--file` or `--specs`.

```
jest 'something/**/*.js'
mocha 'something/**/*.js'
```

Detox can simplify it's arguments and make it more consistent with both of these testing libraries by following their pattern since commander already supports this simple feature.

This is pretty easy to implement all you would have to do is change this [line](https://github.com/wix/Detox/blob/master/detox/local-cli/detox.js#L7) to be

```bash
.command('test [testPattern...]]', 'Initiating your test suite')
```

and then deprecate the `--file` and `--specs` so that it shows they're deprecated but will still work.

**Comment by noomorph** [comment]
Wil be resolved by #1109
