### ISSUE TITLE
Detox build fails for the react-native-video 

### ISSUE THREAD

**Issue by yogeshthanvi** [wix/Detox#1136]
Hi , when I am trying to build with detox for android it gives me following error 

Execution failed for task ':react-native-video:transformClassesWithDexBuilderForDebugAndroidTest'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/vagrant/.gradle/caches/transforms-1/files-1.1/exoplayer-dash-2.9.1.aar/8042bfda08c1c39f6e6858fcbfc8c656/jars/classes.jar

We have solved this by adding compile Options in react-native-video/android/build.gradle as
compileOptions {
targetCompatibility 1.8
sourceCompatibility 1.8
}

Now the issue is that everytime when i try to install node modules it needs to be added again and also its failure on CI

Can we do something for this or someone can help to solve this

**Comment by rotemmiz** [comment]
Ask in StackOverflow  for better visibility, this is not related to Detox per se, I'll try to add a general answer.
