### ISSUE TITLE
Detox with react-native-navigation build is failing for react-native version over 56. error is recreated in the detox-example project

### ISSUE THREAD

**Issue by Lokendra-rawat** [wix/Detox#1137]
#### Description
I am trying to use detox with react-native-navigation and it works up to react-native version 56. after that it starts failing.  

#### Steps to Reproduce
I've created an [Example-app](https://github.com/Lokendra-rawat/detoxRnnFailingBuild) with react-native-navigation that Reproduce the following build errors 
<pre>
> Task :react-native-navigation:transformDexArchiveWithExternalLibsDexMergerForReactNative57DebugAndroidTest FAILED
D8: Program type already present: android.support.design.widget.CoordinatorLayout$Behavior

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-navigation:transformDexArchiveWithExternalLibsDexMergerForReactNative57DebugAndroidTest'.
</pre>
#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 10.0.2
* React Native: 0.57.8
* React-native-navigation: 2.7.1
* Node: 10.15.0
* Device:
* Xcode:
* macOS:

**Comment by Dalamar** [comment]
Same here RN 0.57.8

```
:react-native-navigation:transformDexArchiveWithExternalLibsDexMergerForReactNative57DebugAndroidTest FAILED
D8: Program type already present: android.support.design.widget.CoordinatorLayout$Behavior

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-navigation:transformDexArchiveWithExternalLibsDexMergerForReactNative57DebugAndroidTest'.

```

**Comment by nikolas7892** [comment]
@Dalamar Does your android/app/build.gradle contain `missingDimensionStrategy "RNN.reactNativeVersion", "reactNative57_5"` in *defaultConfig {}* ?

**Comment by rajputav** [comment]
Been seeing the same issue as @Dalamar and @Lokendra-rawat, even with the `missingDimensionStrategy` you reference @nikolas7892 .

- Detox: `12.1.3`
- React Native: `0.57.5`
- React-native-navigation: 2.8.0
- Node: 8.11.1

**Comment by LeoNatan** [comment]
@d4vidi Can you please take a look?
