### ISSUE TITLE
toHaveText() not working with Expo

### ISSUE THREAD

**Issue by MilanJimi** [wix/Detox#1168]
#### Description
When asserting `await expect (element(by.id('Email-value'))).toHaveText('example@gmail.com')` I have found a problem: Even though all fits, the assertion still fails. I have even verified with Appium desktop that the locator and text are correct. Even Detox can read the value correctly, but will not clear the assertion. What gives?
The element is produced by `<Text testID={'Email-value'}>{value}</Text>`

Asserting `await expect (element(by.id('Email-value'))).toExist()` works as expected

I am using Detox-Expo interface, is that related? 
#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 10.0.9
* React Native: 32.0.0
* Node: 10.14.2
* Device: iPhone 7
* ~~Xcode:~~ Expo: 32.0.0
* macOS: 10.14.3

#### Device and verbose Detox logs

```

Error Trace: [
  {
    "Description":  "Assertion with matcher [M] failed: UI element [E] failed to match the following matcher(s): [S]",
    "Description Glossary":    {
      "M":  "(((kindOfClass('UILabel') || kindOfClass('UITextField') || kindOfClass('UITextView')) && hasText('roman@gmail.com')) || (kindOfClass('RCTTextView') && an object with accessibilityLabel "roman@gmail.com"))",
      "E":  "<ABI32_0_0RCTTextView:0x7f8bc65cd420; AX=N; AX.id='Email-value'; AX.label='roman@gmail.com'; AX.frame={{32, 252}, {287, 24.5}}; AX.activationPoint={175.5, 264.25}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{0, 24}, {287, 24.5}}; alpha=1>",
      "S":  "kindOfClass('UILabel'), kindOfClass('UITextField'), kindOfClass('UITextView'), kindOfClass('RCTTextView')"
    },
    "Error Domain":  "com.google.earlgrey.ElementInteractionErrorDomain",
    "Error Code":  "3",
    "File Name":  "GREYAssertions.m",
    "Function Name":  "+[GREYAssertions grey_createAssertionWithMatcher:]_block_invoke",
    "Line":  "75"
  }
]
```

Here I see that found element really has `AX.label='roman@gmail.com'` as expected. So why is it not passing the assertion?

**Comment by LeoNatan** [comment]
Hi,
I have no idea what `ABI32_0_0RCTTextView` is. We don't officially support Expo. If that `ABI32_0_0RCTTextView` class makes changes, we might not support it.

Please create a demo project without Expo and see if the issue reproduces there.

**Comment by MilanJimi** [comment]
Yes, this is an expo thing. Ejected project builds nicely and works as expected. I will continue with this issue on Expo websites from now on. I think I can close.

**Comment by LeoNatan** [comment]
Thanks
