### ISSUE TITLE
Stabilize flaky self animations e2e on Android

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#1171]
#### Description
Test `should wait during delays shorter than 1.5s (driver: JS)`, running on Detox demo app on Android is very flaky, often breaking builds. Need to see why and stabilize / file an actual bug.

Example: https://jenkins-oss.wixpress.com/job/detox-android-56-master/150/console

#### Device and verbose Detox logs
Typical test result:
```
Error: Error: No views in hierarchy found matching: (with tag value: is "UniqueId_AnimationsScreen_afterAnimationText" and view has effective visibility=VISIBLE)
```

**Comment by d4vidi** [comment]
I see now that this also happens on iOS. Might be something with the test's logic.

**Comment by LeoNatan** [comment]
What is happening on iOS?

**Comment by d4vidi** [comment]
@LeoNatan I can't seem to find the sample I came across earlier today. I'll stick with Android for now.
In any case, on Android I seem to be going down the rabbit hole with this one.

**Comment by LeoNatan** [comment]
From the description, it sounds like a bug in the timers idling resource. I am not familiar with such issues on iOS.

**Comment by d4vidi** [comment]
Following a very deep analysis, apparently the explanation lies in just one simple line of code (see PR).

#### Here's the flow that's causing the e2e to fail:
- The test sequence sets up a 400ms animation to start after a 500ms delay (which RN translates to a 500ms timer). When all is done (900ms), RN (JS) rerenders the test component's by changing its internal state (callback to `Animated`); This time, an `after-animation` text shows.
- Simultaneously, the test (node) sets up an `expect` to have that `after-animation` test visible.
- On the device, during the 500ms the timers IR (Idling Resource) identifies at least one pending timer, and thus is when interrogated, declares itself _busy_.
- After 500ms, the device enters an intermediate state where overdue timers are still in queue - just about to get popped by RN. Due to naïve logic, the idling resource - when interrogated in that state, declares itself *idle* (!) All in all, this causes Espresso to think *everything is idle*. And then...
- Should, by chance, the 'expect' assertion has happened to have arrived at `DetoxManager` within the 500ms window, once the timer *effectively* expires, the assertion will *immediately* be validated (to failure...)

The fix here is then to drop the aforementioned naïve condition, thus averting to consider _any_ timer (non-repeating and <1500ms) in queue as holding the system busy. That would cause Espresso to continue interrogating until the timers is busy even _after_ the 500ms effectively pops. Only - by then, the ui manager will be busy handling the animation, which will cause Espresso (and Detox) to first way for the animation to end -- before validation the text component visibility assertion.
