### ISSUE TITLE
Set up ruby and npm deps dynamically in CI (Lerna, changelog-generator)

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#1172]
#### Description
`Lerna` and the `changelog-generator` are currently globally installed and used globally by the setup (slaves) and publishing (master) scripts. Can't be installed dynamically while publishing due to user permission issues. Need to make it happen.

**Comment by LeoNatan** [comment]
What was the user permission? While testing CircleCI, I noticed that it was not possible to use `gem install` because the system Ruby is installed in a read-only path. Instead, I used `brew install ruby` to install a friendly version, and then `gem install` should succeed.

**Comment by d4vidi** [comment]
I'm not 100% sure. I'll keep that in mind if I ever revisit this.

**Comment by noomorph** [comment]
I guess it is not relevant already. I'll close this. @d4vidi, correct me if I am wrong.
