### ISSUE TITLE
Please add ability to write custom logs

### ISSUE THREAD

**Issue by DmitriyKow77** [wix/detox#118]
For each important step like 
```js
 await expect(element(by.id('intro_video'))).toBeVisible();
```
I as AQA need unqie log message to differ action at logs

**Comment by LeoNatan** [comment]
Not sure I understand the problem. Please explain in further details.

**Comment by rumax** [comment]
@LeoNatan 
The case can be: 
 - Start tests
 - App/test hangs some were in the middle
 - You get success or fail (by timeout) and you are not aware where you are now
 - Or you want to know which step is currently executing

Running with `-l info` / `-l verbose` does provide you more details.

Expected:
```
console.log('expect element #intro_video toBeVisible');
await expect(element(by.id('intro_video'))).toBeVisible();
console.log('expect element #intro_video toBeVisible DONE');
```
