### ISSUE TITLE
Upgrade min supported RN version to 59

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#1181]
### Description

Android should support .59, even if with an exception remarks due to the [RN clipping issue](https://github.com/facebook/react-native/issues/23870) on Android.

Also, the demo apps, which are currently 51 and 56, need latest (i.e. `.59`) on iOS, android and maybe `.57` (RN clipping issue, again - i.e. the full detox test suite, and a partial suite).

**Comment by d4vidi** [comment]
Android blocker: https://github.com/facebook/react-native/issues/23870

**Comment by fungilation** [comment]
Quoting @yungsters at https://github.com/facebook/react-native/issues/23870#issuecomment-497204209

> I do not have any good ideas for how to resolve this. I understand the dilemma that this places on Detox, but I do not know how else we could possibly have implemented support for `overflow: visible` without defaulting `setClipChildren(false)`. Due to the viral nature of `overflow`, a default of `overflow: hidden` (and `setClipChildren(true)`) prevents any meaningful support for `overflow: visible` which, if you might recall, was one of the top requested features for React Native.

**Comment by LeoNatan** [comment]
Clowns 🤦‍♂️

**Comment by LeoNatan** [comment]
We've introduced a workaround for this and support 0.59.x.
