### ISSUE TITLE
Running `detox test` fails if the android emulator had been renamed

### ISSUE THREAD

**Issue by teggno** [wix/Detox#1183]
#### Description
When running `detox test` using a config that contains the name of an emulator that had been renamed in Android Studio, detox is not able to start the emulator and therefore fails.

#### Steps to Reproduce
1. Make sure no emulator is running
2. Create a detox config (e.g. `android`) in `package.json` for android with a `name` field that contains the name of an emulator that you just renamed using Android Studio.
3. Run detox by executing `detox test --configuration android`
4. Observe that detox fails.

#### Detox, Node, Device, Xcode and macOS Versions
* Detox: 10.0.2
* React Native: 0.57.8
* Node: 8.12.0
* Device: Windows 10 development PC (Surface Pro 2017)
* Xcode: n/a
* macOS: n/a

#### Device and verbose Detox logs
Just the relevant part:
```
ENOENT: no such file or directory, open 'C:\Users\xxx\.android\avd\myRenamedEmulator.avd\config.ini'
      at EmulatorDriver._fixEmulatorConfigIniSkinName (node_modules/detox/src/devices/drivers/EmulatorDriver.js:23:33)
      at EmulatorDriver.acquireFreeDevice (node_modules/detox/src/devices/drivers/EmulatorDriver.js:91:16)
```

#### Explanation
The cause of the error is that, when an emulator is being renamed in Android Studio, it will only change the name of the `C:\Users\xxx\.android\avd\myRenamedEmulator.ini` file but not the name of the folder `C:\Users\xxx\.android\avd\nameBeforeRename.avd\` which contains `config.ini`. However the file `C:\Users\xxx\.android\avd\myRenamedEmulator.ini` contains a `path` property which points to the correct path, i.e. to `C:\Users\xxx\.android\avd\nameBeforeRename.avd\`.

#### Fix
Instead of just assuming that a directory under `C:\Users\xxx\.android\avd\` matches the emulator name indicated in the detox config, the `C:\Users\xxx\.android\avd\myEmulator.ini` file should be considered.

This would boil down to
```js

// EmulatorDriver.js
async _fixEmulatorConfigIniSkinName(name) {
  const iniDir = `${os.homedir()}/.android/avd/${name}.ini`;
  const iniContents = ini.parse(fs.readFileSync(iniDir, 'utf-8'));
  const configFile = path.join(iniContents["path"], "config.ini");
  const config = ini.parse(fs.readFileSync(configFile, 'utf-8'));

  // ...
}

```

**Comment by noomorph** [comment]
@teggno, thanks for pointing that out!

I'll pick it up if nobody else does, but I think it is a good first-timer's pull request, especially given that the hints on how to implement the bugfix are already given by @teggno.

**Comment by noomorph** [comment]
Partially related to #1255.

**Comment by noomorph** [comment]
Needs to be re-checked. Maybe already implemented.

**Comment by d4vidi** [comment]
Not already implemented. It doesn't sound mandatory, however.

**Comment by jonathanmos** [comment]
I was not able to reproduce this - creating an emulator and then renaming it seems to work.
