### ISSUE TITLE
Device should be booted only when we change the permission status 

### ISSUE THREAD

**Issue by yogeshthanvi** [wix/Detox#1188]
In Detox when we set the device permission the simulator is booted again but it happens every time suppose when start the app and the location permission is not given , Now if we want to check an instance where we do not want to give location permission , to handle this we have to pass location permission as 'No'. Now already the permission status is 'No' and we are also passing as 'No' then in that case the device should not be booted.

**Comment by LeoNatan** [comment]
This is a AppleSimulatorUtils issue, but don't open an issue, as I will respond here: There is no convenient way to read these permissions.

I recently made changes to applesimutils to only reboot the device when absolutely necessary. This should improve your test times. Please update your applesimutils and try.
