### ISSUE TITLE
Can't test custom keyboards

### ISSUE THREAD

**Issue by artald** [wix/detox#119]
Detox matchers can't find elements which reside inside in custom input views, probably because they are shown in a separate window (`UIRemoteKEyboardWindow`).

In addition, after a custom keyboard is shown, detox hangs. No other matchers execute after that even if not trying to interact with elements inside the keyboard.
So, it's impossible to add any tests at all, and this makes me wonder what's the real issue here since once the custom keyboard is shown - nothing works.

You can try it for yourself in [react-native-keyboard-input](https://github.com/wix/react-native-keyboard-input), I was just trying to add a [sanity test](https://github.com/wix/react-native-keyboard-input/blob/master/e2e/sanity.spec.js#L10) for it.

EarlGrey seems to have [keyboard handling](https://github.com/google/EarlGrey/blob/cf04eff3802262cf70ab47ba4f4145fa2dafc58f/EarlGrey/Core/GREYKeyboard.m#L87). For example, [this is](https://github.com/google/EarlGrey/blob/cf04eff3802262cf70ab47ba4f4145fa2dafc58f/EarlGrey/Core/GREYKeyboard.m#L149) how they type strings using the keyboard. Maybe we could utilized it and/or enhance it.

**Comment by LeoNatan** [comment]
Thanks for pointing this out. I will take a look. I am not sure how EG handles view discovery in windows.
Those keyboard handling methods are for the normal keyboard, which is not what is used here.

**Comment by LeoNatan** [comment]
@artald Unable to reproduce.
I imported the custom keyboard into the detox test project and recreated your example project there. Running the test, it works:

```
detox info 1: Listing devices... 
detox info 2: trying to boot device... 
detox info 2: device 9446E8CE-9559-4D13-AB75-E7EED7EDA36A booted 
detox info 3: Uninstalling org.reactjs.native.example.example... 
detox info 3: org.reactjs.native.example.example uninstalled 
detox info 4: Installing /Users/lnatan/Desktop/Code/detox/detox/test/ios/build/Build/Products/Release-iphonesimulator/example.app... 
detox info 4: /Users/lnatan/Desktop/Code/detox/detox/test/ios/build/Build/Products/Release-iphonesimulator/example.app installed 
detox info 5: Launching org.reactjs.native.example.example... 
detox info 5: org.reactjs.native.example.example launched 
  Custom Keyboard
    ✓ should have example screen (449ms)
    ✓ should switch between keyboards (4887ms)


  2 passing (16s)
```

Looking at the simulator, it does what it is supposed to do.

**Comment by artald** [comment]
Thanks for looking into it.

Try running the demo project of https://github.com/wix/react-native-keyboard-input
I recently added detox there and hit this problem right away after switching to a custom keyboard - detox just hangs.

**Comment by artald** [comment]
And regardless of the hang issue, I guess that at the moment you won't be able to just click or interact with elements inside the keyboard, right?

**Comment by LeoNatan** [comment]
It just werks. We had an oops during publish of the latest detox.

**Comment by artald** [comment]
thanks, it just werks
