### ISSUE TITLE
Migration Guide clarification

### ISSUE THREAD

**Issue by gsklee** [wix/Detox#1195]
#### Description

Inside the [Migration Guide](https://github.com/wix/Detox/blob/master/docs/Guide.Migration.md), from 7.x.x to 8.x.x, inside the Jest section for `./e2e/init.js`:

```
jasmine.getEnv().addReporter(adapter); // don't forget this line
```

Is this line erroneous and should be changed to:

```
jest.getEnv().addReporter(adapter); // don't forget this line
```

since it's talking about Jest here?

**Comment by d4vidi** [comment]
Well I didn't look into this but offhand I can say that jest is based on jasmine, so this isn't necessarily wrong...

**Comment by gsklee** [comment]
@wix would be great if anyone from the core team could take a look, should be a quick one I guess?

**Comment by noomorph** [comment]
Hi, @gsklee!

First of all, is there any problem you have already encountered? Feel free to report an issue if things get awry with artifacts creation and placement in recent versions of Jest. I'll make sure to react ASAP and do everything that depends on me.

On the other hand, you are right, but only partially. There is no mistake or typo in the migration guide; the code below is correct and truly represents what I meant back then:

```javascript
jasmine.getEnv().addReporter(adapter);
```

For a deeper understanding, compare the public interfaces of Jasmine and Jest reporters.

Jasmine:
https://jasmine.github.io/tutorials/custom_reporter

Jest:
https://jestjs.io/docs/en/configuration#reporters-array-modulename-modulename-options

Obviously enough, their interfaces are not compatible, so you can't use a Jasmine reporter in Jest.

On the other hand, you are right in your inquiring about why rely on a not really public `jasmine` inside Jest tests, given no warranty it remains in the further versions of Jest. I struggle to remember what diverted me at that time, a year ago, from using Jest reporter interface. I wish I remembered it clearly, but I'm condifent that it is one of those two:

1. I wanted to keep the least common denominator, enabling Jasmine users potentially to use Detox as well. Seems weird, and I agree it is weird if that was the original reason.
2. Here's a more interesting theory! I had a technical difficulty. I'm not sure, but it could have been that Jest reporters run in the parent (puppeteer/orchestrator) process, and they lack access to `detox` and `device` variables, which I rely on to enable the whole artifacts manager workflow. Therefore, inability to access `detox` in the adapter renders it useless - please take time to look into the adapter code if it is not clear why.

So, if you have willpower and time to check hypothesis 2, I'd be happy to hear from you. Currently, it is not on the priority list (we have two other issues/PRs to concentrate on, as of April 2019), but I see no harm in bringing a new Detox-Jest adapter designed in full compliance with their first-class reporter API. Surely, it will have to pass [apocryphal conformance tests](https://github.com/noomorph/detox/tree/noomorph/draft/detox-runner-modules/detox-runner-conformance-suite) (uh-oh, need to recall how to run them or even to update some parts) that haven't made their way to Detox. But other than that, why not - you are welcome to contribute a 100% Jest adapter for Detox. However, if theory 2 proves to be right, then we all have an unequivocal reasoning for why we can't use jest adapters.

Best regards,
Yaroslav.

**Comment by noomorph** [comment]
P.S. @gsklee, please close the issue either if:

1. You have checked theory 2 and supplied us with the answer. Maybe it will make sense to add something from this discussion to the documentation, I'd agree.
2. You don't have resources for the investigation and you are not experiencing critical issues with:

```
jasmine.getEnv().addReporter(adapter);
```

**Comment by noomorph** [comment]
Closing the issue due to absence of the feedback.
