### ISSUE TITLE
React Navigation v3.3.1 SafeAreaView update breaks scroll('down') (iOS only)

### ISSUE THREAD

**Issue by tomball123** [wix/Detox#1196]
### Description
A [recent update](https://github.com/react-navigation/react-navigation/issues/5625)to react-navigation increases the SafeAreaView size a small amount. 

This means all tests that use the scroll('down') function now break because the scroll begins on the safe area view so the scroll view doesn't scroll at all.

For example, I have this helper function that will infinitely try to scroll:

```
await waitFor(element(by.id(testID))).toBeVisible().whileElement(by.id(scrollView)).scroll(150, 'down');
```

#### Steps to Reproduce
1. Install detox
2. Install react-navigation v3.3.1 or higher
3. Run a detox test that uses the scroll(150, 'down')

#### Observed behaviour: Scrolling begins at the SafeAreaView, so scrolling doesn't work.

* Detox: 10.0.3
* React Navigation: 3.3.1

**Comment by LeoNatan** [comment]
Probably related to https://github.com/google/EarlGrey/issues/619 which is not fixed.
We don't use React Navigation, so I'm not sure when I will be able to check this.

**Comment by vonovak** [comment]
this was probably fixed here https://github.com/react-navigation/react-navigation-tabs/pull/110

**Comment by tomball123** [comment]
Thanks for the info @vonovak. I will test this when i get a chance.

**Comment by LeoNatan** [comment]
Thanks, guys
