### ISSUE TITLE
Lotties animation with loop as true are not been handled in android 

### ISSUE THREAD

**Issue by yogeshthanvi** [wix/Detox#1201]
When an app screen consist a Lottie animation with loop as true then detox remain hang or wait to complete the animation and gets timed out. The same case is not applicable in iOS

To Reproduce use any Lottie animation with Lottieview as 
<LottieView
ref={animation => (this.animation = animation)}
autoPlay={true}
loop={true}
/>

This happens not all time when  app is been installed first time this works properly but after few test case execution it stopped working 

It should surpass the Loop animation and check the next available element as per script 

**Environment (please complete the following information):**
 - Detox: 10.0.13
 - React Native: 0.57
 - Node: v10.15.1
 - Device: pixel 2 XL
 - OS: 8.1.0

Error: Command failed: node_modules/.bin/jest "test.spec.js" --config=./config.json --maxWorkers=1 '--testNamePattern=^((?!:ios:).)*$' 
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:653:13)

**Comment by vincenzovitale** [comment]
any progress on this?

**Comment by LeoNatan** [comment]
It might not be possible to catch correctly on Android. As with most infinite-loop animations, we suggest mocking these screens not to have a looping animation.

It would help if you could provide a clean demo project where this reproduces.
