### ISSUE TITLE
Announcement: Detox now requires Xcode 10.1

### ISSUE THREAD

**Issue by LeoNatan** [wix/Detox#1202]
As you know, **Apple now requires new apps and updates to be built with the iOS 12.1 SDK, and so this requires that all developers move to Xcode 10.1**.

Detox now also requires Xcode 10.1 in order to install (`npm install`). Please make sure to update your environment.

**Comment by yogeshthanvi** [comment]
I am sorry but also want to highlight on RN 59 which is released too in market.

**Comment by LeoNatan** [comment]
Please do not use this issue for general chatter.

**Comment by LeoNatan** [comment]
Detox 12 has been released with Xcode 10.2 support and minimum Xcode version of 10.1.
