### ISSUE TITLE
End support in RN .44, .45

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#1203]
On Android, Detox supports RN version ranges `[.44, .46)` and `[.46, inf)` using two separate build flavours. Now that versions .45 and .44 are both almost 2 years old now, I think it's safe to make .46 the new minimum. This is of additional importance as we move forward towards `.aar` publishing integration (i.e. #955), as it would simplify the jars and aars package structure (on top of the build scripts themselves).

@rotemmiz @LeoNatan your take on this?

**Comment by rotemmiz** [comment]
https://media.tenor.com/images/e1cbe9b369d835299eb3eeee8144f948/tenor.gif
