### ISSUE TITLE
cannot use Swipe along with atIndex

### ISSUE THREAD

**Issue by zitegiest** [wix/Detox#1204]
**Describe the bug**
you get thrown a multiple match error even when using atIndex before swipe

failing code: 
        await element(by.text('Bag Subtotal')).atIndex(1).swipe('up', 'fast', 0.1);

Error: 
        Multiple UI elements matched for the given criteria.

**Expected behaviour**
the element will be selected at its index and swiped from there, as it does without an index

**Comment by LeoNatan** [comment]
Does this happen only for swipe?
