### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by jorlogicus** [wix/Detox#1211]
Greetings, I'm here today to offer my services. As a graphic designer in development and an open source enthusiast, I wish to contribute to this wonderful project by making a logo for it, the process (of course) is totally free and we would be working together to create the design that fits best with your project. Of course, you can quit whenever you want. In case you agree, I would like to ask you a few simple questions about your project to have a better understanding of it and so deliver a better product, also you could share with me any preferences you may have about colors, shapes, etc. 

Sorry for disturbing if this is not the proper channel, best regards.

P.S. I see somebody was already designing a logo for this project but due to it ended up in nothing, I'm proposing this.

**Comment by LeoNatan** [comment]
Hello,

Thank you for your generous offer! We would definitely be interested.
Please let us know what ideas you have and how we can help honing down an idea that we will all love to have as a logo.

Thanks

**Comment by jorlogicus** [comment]
Hello again, sorry for the delay. I want to ask you a few simple questions that will help me a lot to deliver a better design:

- What's the name that should be displayed on the logo? If there should be any
- How would you describe this project, what is it intended to do?
- What would you like this logo to transmit?

Looking forward to your reply :) I will start making a few sketches as soon as you answer

On the other side, I saw these issues: [#1180](https://github.com/wix/Detox/issues/1180) and [#738](https://github.com/wix/Detox/issues/738), both with ideas from members of your team. Let me know if you want me to use any of those for the elaboration of the first sketches.

**Comment by LeoNatan** [comment]
Hello,

Do you mind joining a short discussion on our Wix-OSS Slack?
https://join.slack.com/t/wix-oss/shared_invite/enQtMzcwMDQ5NDI1MzYxLTkyNGUzNzk2OTg3N2RiNzIwZDAyYzA3YzhhMzJmMDgzZDIwMDNhNDM3OThkYjQ5YjM4NTcwNDNjNjEzOGM1MmU

Thanks

**Comment by jorlogicus** [comment]
Hello, sure but
"This invite link is no longer active.

If you have an @wix.com email address, you can still create an account.

If not, please check with the person who shared the invite link with you to ask for an invitation."

**Comment by LeoNatan** [comment]
Let's talk over mail. Please email me at lnatan [at] wix.com

Thanks

**Comment by jorlogicus** [comment]
Sorry for the delay, I'm from Venezuela and we've been suffering consecutive national blackouts (believe it or not, lol). Already emailed you. I'd prefer to maintain this conversation here on GitHub but if you prefer to do so through the mail, it's ok for me as well.
