### ISSUE TITLE
boolean result of expect() api 

### ISSUE THREAD

**Issue by ashah0819** [wix/Detox#1214]
Hi guys thank you for making such an amazing test framework for react-native.

I have certain situations in my react-native app when i want to check if particular element is visible I want to perform certain action else some other action.

It would be great if we have boolean expression like  " if (expect(element).isVisible() == true  ) ". 

Thanks

**Comment by LeoNatan** [comment]
Hello,

I don't think it is a good idea to have branching in your tests. You should always strive to have a deterministic state in your tests. Asking the `if` question means you are not testing all UI states of your app. If you app's state is dependent on external resources, you should mock those to ensure determinism.

**Comment by ashah0819** [comment]
Got it. Thanks. I am new to using detox so don't know all test strategies.

**Comment by LeoNatan** [comment]
Happy coding!
