### ISSUE TITLE
getValue/getText API should be added as part of Detox e2e suite

### ISSUE THREAD

**Issue by testtolearn1** [wix/Detox#1226]
getValue/getText kind of basic API should be added as part of Detox e2e suite
Sometime we need to work upon the text displayed on the UI for validating calculations or verifying any function in the code .
The text is not static most of the times . 
If detox can come up with some API which helps to fetch / get the text from the components , then it would be great for functional e2e tests.

**Comment by LeoNatan** [comment]
Hello,
This has been asked before (e.g. https://github.com/wix/Detox/issues/1057 and https://github.com/wix/Detox/issues/445). Closing in favor of those.
