### ISSUE TITLE
React Native .59+ support tracking

### ISSUE THREAD

**Issue by LeoNatan** [wix/Detox#1233]
Since this appears to a major release for our community, I figured it would be a good idea to collect the various issue we and the community see.

#### iOS
- On iOS, there is nothing inherent that should block Detox, so it should be supported
- ~~We've seen several issues related to React Navigation and React Native Gesture Handler (#1207, #1224)~~
  - ~~We believe these issues are **not related to Detox** but bugs in the aforementioned frameworks~~
- ~~Animations fail with Animated (#1234)~~

#### Android (#1181)
- Support on Android is blocked due to a bug in React Native (https://github.com/facebook/react-native/issues/23870)
  - Also see #1208

If you see more issues with RN .59 and above, which are not covered here, please create a new issue and post a link here so I update this page.

**Comment by danielgreane** [comment]
Hi,

Just upgraded RN to 0.59. Getting some wierd behaviour where animations (using react-native's Animated) are no longer triggering when running `detox test` with mocha

If I kill the detox command and re-launch the IPA that has been installed on the simulator by detox init, animations behave as expected again

Does detox launch the application with a particular set of flags? I've been able to find the launch command with a trace log level

**Comment by danielgreane** [comment]
Opened a related issue here: https://github.com/wix/Detox/issues/1234

**Comment by LeoNatan** [comment]
#1234 has been fixed. I'll release 12.1 soon with the fix.

**Comment by VincentCATILLON** [comment]
Btw, is the current Detox release (12.3) supporting RN 0.58 ? Currently, the documentation says:

> The following React Native versions have been tested:
> 
> | iOS    | Android |
> | ------ | ------- |
> | <=0.58 | <=0.56  |

**Comment by LeoNatan** [comment]
I think we're still stuck with the Android version. @d4vidi Any updates?

**Comment by diegolmello** [comment]
@LeoNatan Can you take a look at #1391?

**Comment by LeoNatan** [comment]
I think this can be closed. We support 0.59.x and there are no known serious issues anymore.
