### ISSUE TITLE
Migrate uiautomator to AndroidX

### ISSUE THREAD

**Issue by leanmazzu** [wix/Detox#1235]
**Is your feature request related to a problem? Please describe.**
I've seen you migrated most of the support libraries to AndroidX (thanks for that 💯). But I saw that there's still one dependency using the support libraries version `com.android.support.test.uiautomator:uiautomator-v18:2.1.3`. I think it'd be great to change this one as well to have the project fully migrated to AndroidX. It's also needed for us in Skyscanner as we are using `androidx.test.uiautomator:uiautomator` in our project.

**Describe the solution you'd like**
I've already done this in our Detox fork so I'd be happy to contribute with that change in your public repo. 🙂[You can check out what I've done here.](https://github.com/Skyscanner/detox/commit/d6d7998102403529c7bcb1692b9c1d235d3efadb)

**Describe alternatives you've considered**
N/A - (The alternative is to keep using the `android.support` version of `uiautomator`. 

**Additional context**
N/A

**Comment by d4vidi** [comment]
Amazing, I'll get on it asap. Thanks!
