### ISSUE TITLE
Try to type in different supported language

### ISSUE THREAD

**Issue by gran33** [wix/detox#124]
Hi,
I have 2 languages installed in the simulator.

1. I focus on text input and the keyboard popup with language 1

2. I try to type `await element(by.id('MyTextInput')).typeText(<ANY_LANGUAGE_2_TEXT>`

3. Test failed since detox failed to find the letter in the presented keyboard since the keyboard present language 1 letters

Can Detox switch languages if the input is supported language?

Thanks in advance.

**Comment by rotemmiz** [comment]
typeText types on the virtual keyboard. 
replaceText will paste any string to your text field.

**Comment by gran33** [comment]
Thanks @rotemmiz. 
I need to type, I have text input that react to any text changes and I check that.

Thanks again!

**Comment by LeoNatan** [comment]
This is a known Earl Grey issue: https://github.com/google/EarlGrey/issues/31
