### ISSUE TITLE
App crashes when Detox navigates to a Webview

### ISSUE THREAD

**Issue by alexmngn** [wix/Detox#1240]
**Describe the bug**
When the app runs with the Detox layer and it navigates to a screen that has a WebView, the application just crashes.

When I'm doing exactly the same without the Detox layer, it navigates fine to the WebView. 

It was working fine with Detox 9 but upgrading to 12.1 made this happen, not sure why

**To Reproduce**

1. Make a Detox build
2. Navigate to a screen which contains a WebView

In the below recording, the first time I use the Detox layer, the second time I don't use it. You can see it crashes the first time but works fine the second time (the webview is the screen with the DC characters)

![Detox](https://user-images.githubusercontent.com/4203845/55087880-aedaa700-50a2-11e9-9879-7d6e3ad900ea.gif)

**Environment (please complete the following information):**
 - Detox: 12.1
 - React Native: 0.59
 - Device: iOS Simulator
 - Xcode: 10.1

**Device and Verbose Detox Logs**

```sh
detox[79705] DEBUG: [DetoxServer.js/LOGIN] role=testee, sessionId=7309eb1f-577c-eab6-1e5e-d92d93295994
detox[79705] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=testee, sessionId=7309eb1f-577c-eab6-1e5e-d92d93295994
detox[79705] ERROR: [index.js/DETOX_INIT_ERROR]
 Signal 4 was raised
(
	0   Detox                               0x00000001034ae4f6 _ZL16__DTXHandleCrashP11NSExceptionP8NSNumberP8NSString + 497
	1   Detox                               0x00000001034ae27b _ZL17__DTXHandleSignali + 61
	2   libsystem_platform.dylib            0x0000000109c40b3d _sigtramp + 29
	3   ???                                 0x0000000000000020 0x0 + 32
	4   CoreFoundation                      0x0000000106f1aaa2 +[NSCalendar initialize] + 34
	5   libobjc.A.dylib                     0x00000001051612fe CALLING_SOME_+initialize_METHOD + 19
	6   libobjc.A.dylib                     0x0000000105161691 _class_initialize + 270
	7   libobjc.A.dylib                     0x0000000105168248 lookUpImpOrForward + 196
	8   libobjc.A.dylib                     0x0000000105175814 _objc_msgSend_uncached + 68
```

**Comment by LeoNatan** [comment]
I've managed to reproduce this. It's related to the fix for #1234. Investigating.

**Comment by LeoNatan** [comment]
Fixed. Please upgrade to 12.1.1

**Comment by micabe** [comment]
@LeoNatan great thanks for the new version. I confirm issue is resolved !
