### ISSUE TITLE
Error: Can't find a simulator to match with "iPhone 7"

### ISSUE THREAD

**Issue by matt-paul** [wix/Detox#1241]
**Describe the bug**
Detox can't find the simulators.

**To Reproduce**
1. Run ```detox test```

2. Run ```xcrun simctl list``` to verify available simulators.

My package.json configuration.

```
 "detox": {
    "configurations": {
      "ios.sim.debug": {
        "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/myapp.app",
        "build": "xcodebuild -workspace ios/myapp.xcworkspace -scheme myapp -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build -UseModernBuildSystem=NO",
        "type": "ios.simulator",
        "name": "iPhone 7"
      }
    }
```

config.json
```
{
  "setupFilesAfterEnv": ["./init.js"],
  "testEnvironment": "node"
}
```

init.js
```
const detox = require('detox');
const config = require('../package.json').detox;
const adapter = require('detox/runners/jest/adapter');

jest.setTimeout(120000);
jasmine.getEnv().addReporter(adapter);

beforeAll(async () => {
  await detox.init(config);
});

beforeEach(async () => {
  await adapter.beforeEach();
});

afterAll(async () => {
  await adapter.afterAll();
  await detox.cleanup();
});
```

**Expected behaviour**
Detox should find the simulator and run the test(s). Please note that I am fairly new to React Native development and so perhaps there is something simple i am missing here.

**Screenshots**
<img width="612" alt="Screenshot 2019-03-28 at 11 13 50" src="https://user-images.githubusercontent.com/13286587/55153599-c40b1080-514a-11e9-8476-515ab644e391.png">

<img width="531" alt="Screenshot 2019-03-28 at 11 08 12" src="https://user-images.githubusercontent.com/13286587/55153224-d6387f00-5149-11e9-9aba-d7d8cc64bef2.png">

**Environment**
 - Detox: 12.1.0
 - React Native: 0.59.2
 - Node: 11.12.0
 - Device: iPhone 7
 - Xcode: 10.2(10E125)
 - macOS: 10.14.4

**Comment by LeoNatan** [comment]
Detox uses `applesimutils` for finding devices.

Try running `applesimutils --list --byName "iPhone 7"`.

Most likely, you need to upgrade `applesimutils.

**Comment by matt-paul** [comment]
@LeoNatan  The result of that command was an empty array, so i have upgraded and now back up again. Strange, I am not sure how this occurred as detox was happy until (i believe) i updated Xcode, however there may well be some user error involved at some point. 🤔  Thank you for your quick response.

**Comment by LeoNatan** [comment]
Sure
