### ISSUE TITLE
Local cli doesn't exit with error

### ISSUE THREAD

**Issue by tancredi** [wix/Detox#1246]
After [introducing yargs](https://github.com/wix/Detox/pull/1109) in v12.0.0 it seems the detox cli exits normally (no error code) even when tests are failing (e.g. `detox test && echo 'Success' will always output `Success` regardlessly of test failures or unhandled exceptions)

It would be enough to add `process.exit(1)` after at https://github.com/wix/Detox/blob/master/detox/local-cli/cli.js#L26

I have to imagine there was a reason for this or I must be missing something? It's pretty essential for a test tool to be failing as one would expect.

I'm happy to submit a pull request in case this is a wanted change, otherwise if someone could let me know how I'm supposed to detect test failures it would be highly appreciated.

Thanks

**Comment by LeoNatan** [comment]
This was fixed in 12.1.2. Please update.
