### ISSUE TITLE
`detox test` fails without status code

### ISSUE THREAD

**Issue by tancredi** [wix/Detox#1247]
#### Description
After [introducing `yargs`](https://github.com/wix/Detox/pull/1109) in v12.0.0 it seems the detox cli exits normally (no error code) even when tests are failing

I must be missing something because I found no way at all to run the tests using the local cli in a way that allows me to detect failures and block the execution of further commands - which seems pretty fundamental for a tool that has to run on CI

Please let me know whether I'm missing something here - will be happy to submit a PR otherwise

#### Steps to Reproduce
In a codebase containing failing tests
```
detox test && echo "Success"
```
Always outputs `Success` after execution

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 12.1.1
* React Native: 0.59.2
* Node: 11.10.1
* Device: -
* Xcode: 10.1
* macOS: 10.14

**Comment by noomorph** [comment]
Thanks for pointing that out. I'm checking.

**Comment by LeoNatan** [comment]
The PR has landed, so I’m closing the issue. Thanks

**Comment by noomorph** [comment]
@tancredi, fixed in detox@12.1.2 .

**Comment by tancredi** [comment]
Cheers
