### ISSUE TITLE
Getting an error when running Detox - yargs

### ISSUE THREAD

**Issue by alexmngn** [wix/Detox#1250]
**Describe the bug**

I reinstalled my project and now I get the following error when I run Detox:

```
/Users/alexmngn/Workspace/myProject/node_modules/detox/node_modules/yargs/yargs.js:1163
      else throw err
           ^

ReferenceError: msg is not defined
    at Array.yargs.scriptName.parserConfiguration.commandDir.demandCommand.recommendCommands.help.wrap.fail (/Users/alexmngn/Workspace/myProject/node_modules/detox/local-cli/cli.js:23:43)
```

**Environment (please complete the following information):**
 - Detox: 12.1.1
 - React Native: 0.59

**Comment by noomorph** [comment]
The issue has been fixed in 12.1.2.
Please reopen if you have objections.
