### ISSUE TITLE
Detox does not find iPad (5th generation) simulator - but simulator is listed with xcrun simctl list

### ISSUE THREAD

**Issue by nadzic** [wix/Detox#1266]
I am having the following configuration:

```
  "detox": {
    "configurations": {
      "ios.sim.release": {
        "binaryPath": "ios/build/Build/Products/Release-iphonesimulator/KioskApp.app",
        "build": "react-native run-ios --simulator='iPad (5th generation)'",
        "type": "ios.simulator",
        "name": "iPad (5th generation)"
      },
      "ios.sim.debug": {
        "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/KioskApp.app",
        "build": "react-native run-ios --simulator='iPad (5th generation)'",
        "type": "ios.simulator",
        "name": "iPad (5th generation)"
      }
    },
    "test-runner": "jest",
    "specs": ""
  },
```

So it successfully builds, but I get then following error in terminal:

<img width="763" alt="Screenshot 2019-04-10 at 16 01 58" src="https://user-images.githubusercontent.com/6192073/55886210-9b9fff00-5bab-11e9-80b9-6a21bb2016a9.png">

Is there any other way to specify as name the iPad (5th generation) ?

Btw, when I run: xcrun simctl list, then there is iPad (5th generation) among listed devices.

**Environment (please complete the following information):**
 - Detox: 12.1.1
 - React Native: 0.58.5
 - Node: 8.6.0
 - Device: iPad simulator (5h generation)
 - Xcode: 10.2
 - iOS: 12.2
 - macOS: Mojave 10.14.4

**Comment by LeoNatan** [comment]
Please update AppleSimUtils and report back

**Comment by giancarlo88** [comment]
Had a similar issue and upgrading AppleSimUtils (`brew upgrade wix/brew/applesimutils`) solved the problem.

**Comment by LeoNatan** [comment]
Closing the issue as this seems like the solution.
