### ISSUE TITLE
device.takeScreenshot(x) doesn't work if --take-screenshots none is specified (which is the default)

### ISSUE THREAD

**Issue by LeoNatan** [wix/Detox#1278]
**Describe the bug**
`device.takeScreenshot(x)` doesn't work if `--take-screenshots none` is specified (which is the default when running tests)

The `takeScreenshot` API should be independent of `--take-screenshots` as they are unrelated logically, if the implementation behind the scenes is the same.

**Environment (please complete the following information):**
 - Detox: 12.2.1

**Comment by noomorph** [comment]
Let's discuss tomorrow. In general, I agree. 

I think that the best solution should be to add `manual` mode and make it by default. I'd still want as a user of Detox to have a solution do disable screenshots forcibly, as a setting, without having to hack into the codebase, if for some reason I have another build type on CI or have temporary issues with screenshots inside virtual machines. Some degree of freedom should exist.

**Comment by LeoNatan** [comment]
`manual` makes sense, but it should be the default when not specifying a param.

**Comment by noomorph** [comment]
Agree! Accepted, thanks!
