### ISSUE TITLE
[feature] Configurable Swipe guestures

### ISSUE THREAD

**Issue by DanielMSchmidt** [wix/detox#128]
Hi there,
Thanks for this awesome tool 🎉

I am trying to test my drawer library and the programmatic part (press a button and assume stuff) works pretty well. I would like to test the swipe guestures, but the pan responder behaves pretty specific. 

Is there a way to pump up swipe a bit by making the startpoint, endpoint and speed configurable?

If it is not possible yet, can you walk me through what needs to be done so I can help with contributing later on?

Thanks for your time!

**Comment by LeoNatan** [comment]
It is not possible in the Detox API, and I am not sure if Earl Grey supports this out of the box. Needs investigation. We are tracking this issue with #154. PRs are welcome. 😎
