### ISSUE TITLE
The flag --take-screenshots=all fails with React-Native 0.59.4

### ISSUE THREAD

**Issue by alexmngn** [wix/Detox#1286]
**Describe the bug**

Since I've updated React-Native on my project from `0.59.1` to `0.59.4` and detox from `12.1.0` to `12.3.0`, the screenshot system doesn't seem to work anymore. I'm getting an error `/usr/bin/xcrun simctl io undefined screenshot`. More details below. 

**To Reproduce**

Just run `detox test -c ios.sim.debug --take-screenshots=all`

**Environment (please complete the following information):**
 - Detox: 12.3.0
 - React Native: 0.59.4
 - Node: 11
 - Device: simulator
 - Xcode: latest

**Device and Verbose Detox Logs**
```
detox[89912] DEBUG: [exec.js/EXEC_TRY, #4] Booting device F54B447D-ED7C-4754-BBBC-88094E5E4E2C
detox[89912] DEBUG: [exec.js/EXEC_CMD, #5] /usr/bin/xcrun simctl io undefined screenshot "/private/var/folders/dc/sm5tc_l52klcp2tnt73lqq580000gp/T/f7b376e5-fa92-474a-98ca-325ab59a2bfd.png"
detox[89912] ERROR: [exec.js/EXEC_FAIL, #5] "/usr/bin/xcrun simctl io undefined screenshot "/private/var/folders/dc/sm5tc_l52klcp2tnt73lqq580000gp/T/f7b376e5-fa92-474a-98ca-325ab59a2bfd.png"" failed with code = 163, stdout and stderr:

detox[89912] ERROR: [exec.js/EXEC_FAIL, #5] 
detox[89912] ERROR: [exec.js/EXEC_FAIL, #5] Invalid device: undefined
```

**Comment by LeoNatan** [comment]
I don't think this is related to RN itself. Could you please try downgrading to 12.1.4 or 12.2.x to test if screenshots work there?

**Comment by noomorph** [comment]
@alexmgn, could you attach log level = trace logs to the issue, please. There is something weird with the device udid extraction. Need to understand where the program loses it.

**Comment by noomorph** [comment]
@alexmngn , please answer.

**Comment by LeoNatan** [comment]
@noomorph The more info label is enough.

**Comment by alexmngn** [comment]
Seems like it was an issue with our CI, we got it running properly on another computer.

**Comment by noomorph** [comment]
@alexmgn, thanks for the reply! If you reproduce it one day, please reopen and attach the log in trace mode. Maybe I'll figure it out in which edge case and race condition it happens.

**Comment by LeoNatan** [comment]
Please do not reopen issues. You may not even be able to, closed issues get locked after 3 days. Please open a new issue.
