### ISSUE TITLE
React native navigation stalling

### ISSUE THREAD

**Issue by prsauer** [wix/Detox#1287]
**Describe the bug**
React-navigation navigate calls stalling out detox

Navigation calls that cause RN-N to switch navigators cause a stall --

`detox[98477] INFO:  [actions.js] Sync Timed: animateWithDuration:delay:options:animations:completion:
detox[98477] INFO:  [actions.js] Sync WXRunLoopIdlingResource: React Native thread is busy.`
loops for a very long time (minutes); it sometimes unstalls after 4-5 minutes.

Tried using device.disableSynchronization() but it had no effect -- still stalling out

- [x ] I have tested this issue on the latest Detox release and it still reproduces

**Environment (please complete the following information):**
 - Detox: 12.3.0
 - React Native: 57.8

**Comment by LeoNatan** [comment]
I don't see how Detox is responsible here. The RNN guys use Detox in their CI, as well as our internal projects use both RNN and Detox, and we haven't seen anything like that. The piece of log you have quoted tells you that the JS thread is busy. Look in your code to see what is the cause.

**Comment by prsauer** [comment]
Too many console.log calls! 😢
