### ISSUE TITLE
Get coordinate of element

### ISSUE THREAD

**Issue by DanielMSchmidt** [wix/detox#129]
Hi there,

Thanks again for this awesome piece of code!

I would like to test if a selected element has certain absolute x and y coordinates. A matcher for this would be cool, but I can't figure out how to do it. Can you point me in the right direction, so that I may do a PR?

**Comment by LeoNatan** [comment]
You know, I don't think this is a good API. It assumes a lot on the layout system of both iOS and RN, which is not good practice.
