### ISSUE TITLE
replaceText does not trigger TextInput's onChangeText event (multiline)

### ISSUE THREAD

**Issue by RiiiDE** [wix/Detox#1292]
Related with https://github.com/wix/Detox/issues/151

It now works as expected on regular TextInput's, but it is not triggering onChangeText event on multiline={true}

Detox: 12.1.4
React Native: 0.59.1
iOS: 12.1

**Comment by LeoNatan** [comment]
If you've seen the other issue, I am not sure what you are expecting. What was said then still holds true today. It's a limitation of the framework we are using. Feel free to open an issue with Earl Grey.
