### ISSUE TITLE
URL with multiple arguments is not passed correctly to iOS

### ISSUE THREAD

**Issue by kennym** [wix/Detox#1294]
Leo edit:

> @LeoNatan it's not - if I do `launchApp({ url: 'https://testt.com/go/?screen=BehaviorLessons&behaviorKey=helpful' }}` in the app only `https://testt.com/go/?screen=BehaviorLessons` comes through.

**Comment by kennym** [comment]
@noomorph is this an iOS limitation? I would like to submit a PR.

**Comment by LeoNatan** [comment]
I think you are confusing things here. Your example is one URL with multiple arguments. That’s supported, you just need to support it in your code.

**Comment by LeoNatan** [comment]
Also, both operating systems support only URL as input. How would multiple URLs work anyway? It makes no sense.

**Comment by kennym** [comment]
@LeoNatan it's not - if I do `launchApp({ url: 'https://testt.com/go/?screen=BehaviorLessons&behaviorKey=helpful' }}` in the app only `https://testt.com/go/?screen=BehaviorLessons` comes through.

**Comment by kennym** [comment]
I think you're being a little quick here... I wouldn't raise this concern if I didn't have an issue...

**Comment by LeoNatan** [comment]
In that case, it's a bug.

**Comment by kennym** [comment]
ok, let me report it as a bug

**Comment by LeoNatan** [comment]
But that is ONE URL, not many. Those are arguments.

**Comment by LeoNatan** [comment]
I have changed the title.

**Comment by kennym** [comment]
Thanks.

Well, in your code you call them URL params: https://github.com/wix/Detox/blame/2cd7b1a2d57eee0b9fa819e1319b557955732ef1/detox/src/devices/Device.js#L119

**Comment by LeoNatan** [comment]
@noomorph Can you pls check how the JS handles URLs? Most likely it's an issue with encoding.

**Comment by LeoNatan** [comment]
@kennym That's something else. Please read the code. It checks that only one of `url`/`userNotification`/`userActivity` is provided.

**Comment by kennym** [comment]
@LeoNatan good catch.

**Comment by LeoNatan** [comment]
I think the issue lies here:
https://github.com/wix/Detox/blob/65e1975c5164ee82658255f3ec9e44fdce412896/detox/src/devices/ios/AppleSimUtils.js#L251

Perhaps `return _.map(launchArgs, (v, k) => `${k} "${v}"`).join(' ').trim();` would better. @kennym Would you like to test and possibly submit a PR with a fix?

**Comment by kennym** [comment]
@LeoNatan I'm going to give that a try tomorrow morning.

**Comment by noomorph** [comment]
Okay, guys, keep me in the loop if you need anything from me. If I got it right, @kennym volunteered to look into it today and you don't need my assistance at the moment. Correct me if I am wrong.

**Comment by kennym** [comment]
@LeoNatan that fixed it!

**Comment by noomorph** [comment]
Fixed in #1302
