### ISSUE TITLE
device.terminateApp results in ChildProcessError

### ISSUE THREAD

**Issue by cs01** [wix/Detox#1296]
**Describe the bug**

Calling this code (with Detox v12.3.0)
```
import detox, {device} from 'detox';
...
await device.terminateApp({delete: true});
```
results in this
```
    ChildProcessError: Command failed: /usr/bin/xcrun simctl terminate 77D2E143-6DCD-432E-B0A7-1453376D30EE [object Object]
    Terminate an application by identifier on a device.
    Usage: simctl terminate <device> <app bundle identifier>
     `/usr/bin/xcrun simctl terminate 77D2E143-6DCD-432E-B0A7-1453376D30EE [object Object]` (exited with error code 117)
```
**To Reproduce**

- [x] I have tested this issue on the latest Detox release and it still reproduces

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

1. in `beforeAll` Jest method, try to terminate app

**Screenshots**
![image](https://user-images.githubusercontent.com/5715368/56233964-1ef0a300-6039-11e9-9288-659e3a46c3de.png)

**Comment by noomorph** [comment]
@cs01, where did you get your impression from, that `device.terminateApp` accepts an object as a first argument?

**Comment by cs01** [comment]
Thanks for the response! That was a copy and paste error. It works fine when I take it out.
