### ISSUE TITLE
[feature] Test animation progress

### ISSUE THREAD

**Issue by DanielMSchmidt** [wix/detox#130]
Thanks​ again, sorry that I open so many issues lately. 

I was wondering how I might test animation progress in general. In my case I have an open state which is rendered. As I read through the docs I saw that detox waits for the idle state, e.g. not in the middle of the animation. 

How can I overcome this feature? I would like to write tests like "after 100ms it is about half way through", may I use the expect without an await for that or is it just not possible?

**Comment by LeoNatan** [comment]
Currently, Detox synchronises so that it is blocked when animations are in progress. In the future, we plan to have API allowing the user to disable these synchronisations for a more hands on approach to testing.

**Comment by rumax** [comment]
@LeoNatan Let assume you have a component like this (The component can be some notification on the page, etc. It is actually the example from Animated API but with Animated.sequence, where the animation should be in the loop):

```
const animatedDelay = (duration) => Animated.timing(
  new Animated.Value(0),
  {
    duration,
    isInteraction: false,
    toValue: 0,
    useNativeDriver: true,
  }
);

class FadeInView extends React.Component {
  state = {
    fadeAnim: new Animated.Value(0),
  }

  startAnimation() {
    Animated.sequence([
      Animated.timing(
        this.state.fadeAnim,
        {
          toValue: 1,
          duration: 2000,
          useNativeDriver: true,
        }
      ),
      Animated.timing(
        this.state.fadeAnim,
        {
          toValue: 0,
          duration: 2000,
          useNativeDriver: true,
        }
      ),
      animatedDelay(5000)
    ]).start(({ finished }) => {
      if (finished) {
        this.startAnimation();
      }
    });
  }

  componentDidMount() {
    this.startAnimation();
  }

  render() {
    let { fadeAnim } = this.state;

    return (
      <Animated.View
        style={{
          ...this.props.style,
          opacity: fadeAnim,
        }}
      >
        {this.props.children}
      </Animated.View>
    );
  }
}
```

Add this component to demo-react-native project 
```
  <View testID='welcome' style={{flex: 1, paddingTop: 20, justifyContent: 'center', alignItems: 'center'}}>
          <Text style={{fontSize: 25, marginBottom: 30}}>
<FadeInView style={{width: 250, height: 50, backgroundColor: 'powderblue'}}>
          <Text style={{fontSize: 28, textAlign: 'center', margin: 10}}>Fading in</Text>
        </FadeInView>
```

And tests will never pass

**Comment by Twinski** [comment]
@LeoNatan 
await device.disableSynchronization(); is now part of Detox but how do I use it? 
If I put it after device.launchApp, the test will fail immediately saying it cannot find UI element. 
So how do we bypass a certain page where you have a infinite loop of Animated-animations?
The documentation doesn't say much. Looking forward to your answer. 

PS. Great work. Detox is best test-tool I've used for React Native 👍

**Comment by zhaocaih** [comment]
I have the similar question:
I have two tests, with _await device.disableSynchronization()_, each test can pass when running them individually, but when run them together, the second always hang. 

PS. I added _await device.enableSynchronization()_ in the end of the test, or else the second test will fail immediately with cannot find UI element.
