### ISSUE TITLE
It can't create cucumber report after running is successful

### ISSUE THREAD

**Issue by hieuTranEnouvo** [wix/Detox#1300]
**That is result:**
Feature: Profile screen

    Add test profile screen

  Scenario: Testing Profile Screen Items
detox[5335] INFO:  [DetoxServer.js] server listening on localhost:51247...
detox[5335] INFO:  [AppleSimUtils.js] com.reebonz.reebonz launched. The stdout and stderr logs were recreated, you can watch them with:
        tail -F /Users/hieu/Library/Developer/CoreSimulator/Devices/34D61D1B-AB4D-4C95-9E9A-921ECC617E8D/data/tmp/detox.last_launch_app_log.{out,err}
  ✔ Given I click profile button
  ✔ When I click about us button
  ✔ Then I click back button
  ✔ Then I click faq button
  ✔ Then I click back button
  ✔ Then I click sellWithReebonz button
  ✔ Then I click back button
  ✔ Then I click reebonzRewards button
  ✔ Then I click back button
  ✔ Then I scroll ProfileScrollView

1 scenario (1 passed)
10 steps (10 passed)
1m56.176s
✨  Done in 117.82s.

**My hook.js:**
/* eslint-disable */
require('babel-polyfill');
const detox = require('detox');
const config = require('../../../package.json').detoxIOSDebug;
const { defineSupportCode } = require('cucumber');
const fs = require('fs');
const { reporter } = require('cucumber-html-reporter');
const { report } = require('cucumber-html-report');
const { mkdirp } = require('mkdirp');
const JsonFormatter = require('cucumber').JsonFormatter;
defineSupportCode(function ({ Before, registerHandler, registerListener, After, setDefaultTimeout }) {

  setDefaultTimeout(10 * 1000);
  const jsonReports = process.cwd() + '/reports/json';
  const htmlReports = process.cwd() + '/reports/html';
  const targetJson = jsonReports + '/cucumber_report.json';

  Before({ timeout: 120 * 1000 }, async () => {
    await detox.init(config, { launchApp: false });
    await device.launchApp({ permissions: { notifications: 'YES' } });
  });

  After(function (scenario) {
    const world = this;
    if (scenario.isFailed()) {
      return device.takeScreenshot().then(function (screenShot) {
        // screenshot is a base-64 encoded PNG
        world.attach(screenShot, 'image/png');
      });
    };
    detox.cleanup();
  });

  const cucumberReporterOptions = {
    theme: 'bootstrap',
    jsonFile: targetJson,
    output: htmlReports + '/cucumber_reporter.html',
    reportSuiteAsScenarios: true,
    launchReport: true
  };

  const cucumberReportOptions = {
    source: targetJson,
    dest: htmlReports,
    name: 'cucumber_report.html',
    title: 'Cucumber Report',
  };

  const logFn = string => {
    if (!fs.existsSync(jsonReports)) {
      mkdirp.sync(jsonReports);
    }
    try {
      fs.writeFileSync(targetJson, string);
      // invoke cucumber-html-reporter
      reporter.generate(cucumberReporterOptions);
      // invoke cucumber-html-report
      report.create(cucumberReportOptions).then(function () {
        console.log('Cucumber Report created successfully!');
      });
    } catch (err) {
      if (err) {
        console.log(`Failed to save cucumber test results to json file.
                             Failed to create html report.`);
        console.log(err);
      }
    }
  };

  const jsonFormatter = JsonFormatter;

  jsonFormatter.log = function (string) {

    console.log(string);
  };

  registerListener(JsonFormatter);
});

**Comment by noomorph** [comment]
@hieuTranEnouvo, I suggest you collaborate with people in #1300 and help them build `demo-react-native-cucumber` project for Detox so that people like you today will have a reference project that works out-of-the-box with Detox and Cucumber.

The issue is closed since it is a support question.

**Comment by LeoNatan** [comment]
#237
