### ISSUE TITLE
Plugin system to hooks inside the native code in some ways

### ISSUE THREAD

**Issue by mfrachet** [wix/Detox#1303]
**Is your feature request related to a problem? Please describe.**
In my company, we're actually moving to Detox in our brownfield application. The idea is to automate our E2E.

However, we also need to ensure that the different **layout and styles** don't break between different types of devices (sizes, platforms etc...) And we wanted to rely on some tools like Applitools to take screenshots and compare the old vs the new screenshot.

Correct me if I'm wrong, but Detox has not the capability to take screenshots on devices and to make comparisons on them right?

**Describe the solution you'd like**
I'm not used to the Detox codebase, but I think that a plugin system with some hooks inside the internals of Detox could be a possibility to add additional computations directly on the native engines.

For example, Applitools can work with XCUI and Espresso and the capability to tweak a bit the things using a plugin doesn't seem to be a bad solution from my side.

**Describe alternatives you've considered**
We've though of simply taking screenshots and using others tools to make the diffing computation. But I think that it might be something interesting for Detox to support a plugin system to make the possibilities wider 😊

**Comment by LeoNatan** [comment]
I have discussed my thoughts on a native plugin system here:
https://github.com/wix/Detox/issues/1091#issuecomment-448698596

I think I close this issue in favor of #1091. While the title is more specific, the discussion there covers more customization/plugins.
