### ISSUE TITLE
Reopen #992, disable stale bot

### ISSUE THREAD

**Issue by Elijen** [wix/Detox#1304]
Can we have the following issue reopened as it wasn't really resolved:
https://github.com/wix/Detox/issues/992

Is there any benefit of using Stale bot apart of ignoring issues? Can we have stale bot disabled/removed?

**Comment by LeoNatan** [comment]
No.

**Comment by LeoNatan** [comment]
See discussion here:
https://github.com/wix/Detox/issues/1227

**Comment by LeoNatan** [comment]
Regarding the bots we use and our rationale, see #1305
