### ISSUE TITLE
Detox doesn't call file abc.app in package json 

### ISSUE THREAD

**Issue by hieuTranEnouvo** [wix/Detox#1309]
Hello friends,

I want to raise an issue about build an app of detox

When I run detox. 

**My code:** 
```json
{
  "detoxIOSDebug": {
    "configurations": {
      "ios.sim.debug": {
        "binaryPath": "/Users/Library/Developer/Xcode/DerivedData/abc/Build/Products/Debug-iphonesimulator/abc.app",
        "build": "xcodebuild -project ios/ReebonzMobileApp.xcodeproj -scheme ReebonzMobileApp -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build",
        "type": "ios.simulator",
        "name": "iPhone 6"
      }
    },
}
```

==> That can't call abc.app :(

### I must turn on a simulator(Ip-6 ) then It's created a new simulator(Detox - ip6) to run 
[https://imgur.com/deGMjDw](url)

My detox: 12.3.0

**Comment by noomorph** [comment]
@hieuTranEnouvo, please read the docs.

```diff
-"detoxIOSDebug": {
+"detox": {
```

Sorry, but these errors you make in `package.json` can't convince me to react to issues you create somehow seriously. /cc @LeoNatan

**Comment by hieuTranEnouvo** [comment]
> @hieuTranEnouvo, please read the docs.
> 
> ```diff
> -"detoxIOSDebug": {
> +"detox": {
> ```

I changed this code but it still doesn't call abc.app
