### ISSUE TITLE
CI never (or rarely) generates CHANGELOG on publish 

### ISSUE THREAD

**Issue by noomorph** [wix/Detox#1312]
**Is your feature request related to a problem? Please describe.**

Just have released `detox@12.4.0`.
However, the [CHANGELOG](https://github.com/wix/Detox/blob/master/CHANGELOG.md) still has data related to `12.2.0`.
Looks like we need to see what is broken on CI.

**Comment by LeoNatan** [comment]
The whole changelog is unreadable. We should be making the changelog manually. Perhaps the last commit message should serve as that, and then use that to append to the changelog.

**Comment by LeoNatan** [comment]
Most likely this is broken on CI because the environment variable with the github access token is missing.

**Comment by noomorph** [comment]
@d4vidi, since you've been working on it for some time (e.g.: https://github.com/wix/Detox/commit/f36ce8de66be1925663123a556419dface783d57) , could you give here some updates on this?

**Comment by LeoNatan** [comment]
I found a bug I. The generator. They open too many threads, and since we have many issues, that triggers a security measure in GH. It’s a known issue which was fixed on master of the generator, but there hasn’t been a new release in several years.

**Comment by noomorph** [comment]
@LeoNatan, @rotemmiz, @d4vidi, then maybe we can switch to [semantic-release](https://github.com/semantic-release/semantic-release) eventually, with [@semantic-release/changelog](https://github.com/semantic-release/changelog) plugin?

**Comment by d4vidi** [comment]
@noomorph yes I was trying to get more info on why the changelog generator fails on CI, and essentially I've managed to:

```
17:32:44 /usr/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'minitest' (~> 5.1) among 22 total gem(s) (Gem::LoadError)
17:32:44 Checked in 'GEM_PATH=file:/var/lib/jenkins/plugins/ruby-runtime/WEB-INF/lib/stapler-jruby-1.209.jar!/gem/:/var/lib/gems/2.3.0', execute `gem env` for more information
17:32:44 	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1441:in `block in activate_dependencies'
17:32:44 	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1430:in `each'
17:32:44 	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1430:in `activate_dependencies'
17:32:44 	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1412:in `activate'
17:32:44 	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1444:in `block in activate_dependencies'
17:32:44 	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1430:in `each'
17:32:44 	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1430:in `activate_dependencies'
17:32:44 	from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1412:in `activate'
17:32:44 	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:68:in `block in gem'
17:32:44 	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:67:in `synchronize'
17:32:44 	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:67:in `gem'
17:32:44 	from /usr/local/bin/github_changelog_generator:22:in `<main>'
```

**Comment by d4vidi** [comment]
Not sure how this related to what @LeoNatan wrote, though

**Comment by noomorph** [comment]
@d4vidi, perhaps, we could try updating Ruby to something less ancient. `ruby@2.3.0` is 4 years old.

**Comment by d4vidi** [comment]
Beats me. The generator works if you run in manually on the CI agent using the CI account. Quite a mystery.

**Comment by LeoNatan** [comment]
Was speaking about this issue I think:
https://github.com/github-changelog-generator/github-changelog-generator/issues/656

This PR supposedly fixes it:
https://github.com/github-changelog-generator/github-changelog-generator/pull/661

But they haven't released a new release since 2017. 🙄

I think we should abandon github-changelog-generator.

**Comment by LeoNatan** [comment]
On my Mac, I would hit the rate limit very consistently on each run. I am sure the CI hits it also.

**Comment by d4vidi** [comment]
Well that's the reason we pass in the permissive github token, it shouldn't hit github limits (or very rarely so). Either way, the generator fails immediately before even trying to access github (ruby stuff).

**Comment by LeoNatan** [comment]
I am speaking limits with token.

**Comment by LeoNatan** [comment]
The issue even mentions that without the token, it bugs out even earlier.

**Comment by LeoNatan** [comment]
Removed github_changelog_generator and the Changelog.md file from the project. The tool is outdated and broken, the resulting output is a mess due to bugs in the tool.
