### ISSUE TITLE
CI: add demo-projects-android build

### ISSUE THREAD

**Issue by noomorph** [wix/Detox#1313]
The demo projects are tested solely in Mac+iOS chain on CI:
https://jenkins-oss.wixpress.com/job/detox-demo-projects-pr/

To achieve parity, we might add a Linux+Android build for demo projects on CI as well.

**Comment by LeoNatan** [comment]
What is the point of having the demo projects run in CI at all? They just take time and are useless. The main test suit already runs and displays viability.

**Comment by noomorph** [comment]
1. They serve as a good starting point for anyone who wants to demonstrate a Detox+iOS or Detox+Android issue to us because they are very minimalistic and simple. The example projects are almost empty and don't have a mental overhead that `detox/test` does.

2. Demo projects can become a basis for quick smoke tests, to check for any foreseeable blocker issues with newly arriving React Native, XCode, and Android SDK versions. Since their functionality is minimal, they can signalize about first install&run issues - will it blend? so to say.

**Comment by LeoNatan** [comment]
I'm not saying we should remove them. They are good examples of how to setup an app with Detox. But I don't see the value of running them in CI and blocking builds with them. The test suite is already running anyway, in several RN versions, so that gives enough sanity. The added redundancy in this case adds no redundancy.

**Comment by noomorph** [comment]
Resolved by @d4vidi . Kudos!

**Comment by d4vidi** [comment]
Thanks @noomorph :) Indeed, as a part of the work I did for #1323.

@LeoNatan you're right in a sense but in _this_ particular context it's a good way to have sanity over the creation of the `aar` etc. The overhead is pretty low.
