### ISSUE TITLE
Testing WebViews

### ISSUE THREAD

**Issue by cliren** [wix/Detox#1315]
I haven't seen any documentation on how to test WebViews using detox but found few issues that didn't have enough information. Our app uses a webview for login so nothing can be tested without performing a login. Can someone confirm if Testing ReactNative webviews is possible if not we may not be able to use detox and look for alternatives.

**Comment by LeoNatan** [comment]
This has been discussed before. Unfortunately, there is nothing we can offer. Please mock your web API so that you don’t have to display it.
