### ISSUE TITLE
Publish Detox with Android packaging artifacts

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#1323]
Publish Android artifacts (i.e. .aar, sources jar, javadoc jar) to npm, on top of the existing content being published today.

Initially, this was addressed [by this PR](https://github.com/wix/Detox/pull/955). However, up to date work show that it's become outdated to the point where it would make more sense to start a new (based on that work).

**Comment by d4vidi** [comment]
Update: basically done with this. Need to revisit the affect of declaring kotlin's stdlib as a dep (related to #1257).

**Comment by LeoNatan** [comment]
This is implemented.
