### ISSUE TITLE
Can't accept location permission from system alert pop up

### ISSUE THREAD

**Issue by ksavransky** [wix/Detox#1330]
**Describe the bug**
Can't accept location permission from system alert pop up

**To Reproduce**

- [Y] I have tested this issue on the latest Detox release and it still reproduces

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

1. Launch app from command line using detox test --configuration ios.sim.debug
2. Launch app in code via await device.launchApp({ permissions: { location: 'always', notifications: 'YES' } })
3. Go through login flow until app asks for location via react-native-permissions Permissions.request('location', { type: 'always' }) (with prior check to see if location permission check already set to 'always' (in which case app doesn't ask) )
4. See system alert pop up asking to confirm location permission
5. Detox cannot see system alert pop up and thus can't click on button to choose permission always for location

If possible, please provide a small demo project that reproduces the issue, or attach a video with the reproduction - this would be very appreciated.

**Expected behavior**
I would like to be able to click on 'Always Allow' in the system alert pop up, or set the permissions beforehand so that i don't even see this screen.

**Screenshots**
see below

**Environment (please complete the following information):**
 - Detox: 12.3.0
 - React Native: 0.57.7
 - Node: 10.15.0
 - Device: Xcode iPhone X emulator
 - Xcode: 10.2.1
 - iOS: 12.1
 - macOS: 10.14.4

**Device and Verbose Detox Logs**
  ``` Failed: [Error: Error: Cannot find UI element.
    Exception with Action: {
      "Action Name":  "Tap",
      "Element Matcher":  "((!(kindOfClass('RCTScrollView')) && (((kindOfClass('UILabel') || kindOfClass('UITextField') || kindOfClass('UITextView')) && hasText('Always Allow')) || (kindOfClass('RCTTextView') && an object with accessibilityLabel "Always Allow"))) || (((kindOfClass('UIView') || respondsToSelector(accessibilityContainer)) && parentThatMatches(kindOfClass('RCTScrollView'))) && ((kindOfClass('UIView') || respondsToSelector(accessibilityContainer)) && parentThatMatches((((kindOfClass('UILabel') || kindOfClass('UITextField') || kindOfClass('UITextView')) && hasText('Always Allow')) || (kindOfClass('RCTTextView') && an object with accessibilityLabel "Always Allow"))))))",
      "Recovery Suggestion":  "Check if the element exists in the UI hierarchy printed below. If it exists, adjust the matcher so that it accurately matches element."
    }


    Error Trace: [
      {
        "Description":  "Interaction cannot continue because the desired element was not found.",
        "Error Domain":  "com.google.earlgrey.ElementInteractionErrorDomain",
        "Error Code":  "0",
        "File Name":  "GREYElementInteraction.m",
        "Function Name":  "-[GREYElementInteraction matchedElementsWithTimeout:error:]",
        "Line":  "124"
      }
    ]

**Comment by ksavransky** [comment]
Test fails here: 
<img width="379" alt="Screen Shot 2019-04-23 at 3 53 34 PM" src="https://user-images.githubusercontent.com/15972926/56621105-0e639e00-65e0-11e9-86dc-a0511984af1b.png">

**Comment by ksavransky** [comment]
I've tried copying the code and suggestions in the following: 
https://github.com/wix/Detox/issues/9
https://github.com/wix/Detox/blob/master/detox/test/e2e/13.permissions.test.js
https://github.com/wix/Detox/blob/master/detox/test/e2e/16.location.test.js
https://github.com/wix/AppleSimulatorUtils (running command to set permission from command line before launching test)

**Comment by ksavransky** [comment]
My code:
`const detox = require('detox')
const config = require('../package.json').detox
const adapter = require('detox/runners/jest/adapter')

jest.setTimeout(120000)
jasmine.getEnv().addReporter(adapter)

beforeAll(async () => {
  await detox.init(config, { launchApp: false })
})

beforeEach(async () => {
  await adapter.beforeEach()
})

afterAll(async () => {
  await adapter.afterAll()
  await detox.cleanup()
})
`

`export const loadApp = () => (
  it('should load app and accept permissions', async () => {
    await device.launchApp({ permissions: { location: 'always', notifications: 'YES' } })
    await element(by.text('Always Allow')).tap()

  })
)

export const seeBaseAppView = () => (
  it('should load base app view', async () => {
    await expect(element(by.id('AppBaseView'))).toBeVisible()
  })
)

export const typeWillAdminLoginInfo = () => (
  it('should be able to type will_admin login info', async () => {
    await element(by.id('Login')).typeText('will_admin')
    await element(by.id('Password')).typeText('swoopthis')
  })
)

export const tapOnLogIn = () => (
  it('should be able to tap on "Log In" button', async () => {
    await element(by.text('Log In')).tap()
  })
)

export const tapOnAllowLocation = () => (
  it('should be able to tap on "Allow Location" button', async () => {
    await element(by.text('Allow Location')).tap()
  })
)

export const tapOnAlwaysAllow = () => (
  it('should be able to tap on "Always Allow" button', async () => {
    await element(by.text('Always Allow')).tap()
    // await element(by.text('Permissions')).tap()
    // await element(by.text('Location')).tap()
  })
)
`

`import {
  loadApp,
  seeBaseAppView,
  tapOnAlwaysAllow,
  tapOnAllowLocation,
  tapOnLogIn,
  typeWillAdminLoginInfo,
} from '../blocks/login'

describe('Log In', () => {
  describe('iOS: Basic Login Flow: load app, log in, accept permissions, land on job list', () => {
    loadApp()
    seeBaseAppView()
    typeWillAdminLoginInfo()
    tapOnLogIn()
    tapOnAllowLocation()
    // tapOnAlwaysAllow()
  })
})
`

**Comment by LeoNatan** [comment]
Where is the full log?
