### ISSUE TITLE
.dtxrec are not created if the performance recording was initially started via launch args

### ISSUE THREAD

**Issue by noomorph** [wix/Detox#1339]
**Describe the bug**

If you run Detox with `--record-performance all`, Detox Instruments recording is not saved if it was started first time inside a test:

```js
beforeAll(async () => {
  await detox.init(config, { launchApp: false });
});

it('should have welcome screen', async () => {
  await device.launchApp({ newInstance: true });
  await expect(element(by.text('Welcome to React Native!'))).toBeVisible();
});
```

**To Reproduce**

Clone (or [download](https://github.com/noomorph/bug-reports/archive/detox/dtxrec-on-launch.zip)) and follow the README:

https://github.com/noomorph/bug-reports/tree/detox/dtxrec-on-launch/DummyApp

**Expected behavior**

1. No errors in log.
2. There should be `artifacts/.../Dummy App should have welcome screen/test.dtxrec` after the test.

**Environment (please complete the following information):**
 - Detox: 12.4.1
 - React Native: 0.59.5
 - Node: 10.15.0
 - Device: iPhone X (Simulator)
 - Xcode: 10.2
 - iOS: 12.2
 - macOS: 10.14.4

**Device and Verbose Detox Logs**

[test.log](https://github.com/wix/Detox/files/3123695/test.log)

**Comment by LeoNatan** [comment]
This was fixed on master
