### ISSUE TITLE
test fail with timeout

### ISSUE THREAD

**Issue by iwater** [wix/detox#134]
add testid "skip_login"  and test with xcode Identifier, but always got timeout
<img width="1015" alt="2017-05-20 4 02 05" src="https://cloud.githubusercontent.com/assets/108937/26274166/caf4dbe6-3d75-11e7-868b-3002889d45bc.png">
<img width="243" alt="2017-05-20 4 02 26" src="https://cloud.githubusercontent.com/assets/108937/26274167/cd4ae638-3d75-11e7-95e1-6d0588b26b5c.png">

```
describe('Example', () => {
  beforeEach(async () => {
    await device.reloadReactNative()
  })

  it('should show hello screen after tap', async () => {
    await element(by.id('skip_login')).tap()
  })

})
```

**Comment by bogobogo** [comment]
Hey @iwater, 

Your test is missing an _Expectation_. You are currently performing an action on an element with the id `skip_login` without writing what is the desired outcome, so you are not actually testing. An example with an _Expectation_ would look like: 
```js
it('should show hello screen after tap', async () => {
    await element(by.id('skip_login')).tap()
    await expect(element(by.id('hello_screen'))).toBeVisible()
  })
```

You can read more about expectations [here](https://github.com/wix/detox/blob/master/docs/APIRef.Expect.md)

**Comment by iwater** [comment]
change to 
`await expect(element(by.id('skip_login'))).toBeVisible()`

but got same result timeout

**Comment by DanielMSchmidt** [comment]
@bogobogo May be a bit off topic, but do you think this error in general would be valuable to add to [Troubleshooting.RunningTests](https://github.com/wix/detox/blob/master/docs/Troubleshooting.RunningTests.md)?

**Comment by rotemmiz** [comment]
This issue may result from a background work that doesn't end. Detox will not execute commands while the app isn't idle.
Do you have long polling network requests? Or repeating setTimeouts?

@LeoNatan created a method that will inform the user on such background tasks when failing to execute, we will add it soon. Hopefully it will help debugging these kind of issues a breeze.

**Comment by iwater** [comment]
yes, there is a long running background task for db sync

**Comment by LeoNatan** [comment]
If you have a long running task, it may be interfering with our synchronisation mechanism. We plan to add support for granular control of what is taken into account when synchronising, as well as the aforementioned helper tool to guide you on why the tests was blocked.

**Comment by rotemmiz** [comment]
detox@5.1.0 can now report on the reason it waits for app. add `--debug-synchronization [value]` to your detox test command.

When an action/expectation takes a significant amount of time use this option to print device synchronization status. The status will be printed if the action takes more than [value]ms to complete

**Comment by LeoNatan** [comment]
❤️
