### ISSUE TITLE
[Detox 12.5.0] Could not find any matches for com.wix:detox:+

### ISSUE THREAD

**Issue by harry-nguyen-88** [wix/Detox#1342]
**Describe the bug**
With latest version 12.5.0, when I tried to build app-debug-androidTest.apk, I have an exception: 
Could not find any matches for com.wix:detox:+ as no versions of com.wix:detox are available.

I already did migration guide from 12.4.9 to 12.5.0
*To Reproduce**

- [x] I have tested this issue on the latest Detox release and it still reproduces

1. cd android 
2. ./gradlew assembleAndroidTest

**Expected behavior**
Should build fine without any errors

**Environment (please complete the following information):**
 - Detox: 12.5.0
 - React Native: 0.59.5
 - Node: 11.6.0
 - Device: Emulator Nexus_4_API_25
 - OS: 7.1.1

**Comment by kaiwen-zhang-ck** [comment]
any updates on this? does detox even work with 59?

**Comment by harry-nguyen-88** [comment]
Well, after removing node_modules and install it again then the issue was fixed! So when upgrading from 12.4.9 to 12.5.0, we need to to do like that.
