### ISSUE TITLE
Android release build not get detected though it is already build

### ISSUE THREAD

**Issue by yogeshthanvi** [wix/Detox#1343]
Detox version : 12.5.0 
RN : 0.59 

I build my app using detox and it is successfully build up . Now when i am trying to test the app it gives me an error that release build is not found . But the same works fine when the debug mode is been considered for testing.

Can someone look into this ?

**Comment by rotemmiz** [comment]
You are here for quite a lot of time now, you should know better on how to report an issue. 
Please do not ignore the issue template, we can't understand your issues without the required data.

**Comment by yogeshthanvi** [comment]
okay sorry for the inconvenience , closing this one will fill new with proper template
