### ISSUE TITLE
Override detoxFrameworkPath

### ISSUE THREAD

**Issue by cs01** [wix/Detox#1352]
**Is your feature request related to a problem? Please describe.**
Our CI system does not allow `postinstall` scripts to run. It also does not unzip node packages (it uses yarn pnp), so the `node_modules` source code is not available to run the post install step manually in CI.

**Describe the solution you'd like**
Add a parameter or environment variable `DETOX_FRAMEWORK_PATH` to manually define the path of the Detox dylib.

```js
async function getFrameworkPath() {
  if (process.env.DETOX_FRAMEWORK_PATH) {
    return process.env.DETOX_FRAMEWORK_PATH;
  }
  const detoxVersion = this.getDetoxVersion();
  const sha1 = (await exec(`(echo "${detoxVersion}" && xcodebuild -version) | shasum | awk '{print $1}'`)).stdout.trim();
  return `${DETOX_LIBRARY_ROOT_PATH}/ios/${sha1}/Detox.framework`;
}
```

**Comment by LeoNatan** [comment]
But if post install scripts are not running, how will this work? Will you build the Detox framework on your own? The framework is currently being build with specific parameters in the post install script, and there is further work to distinct the framework for each Detox and Xcode version because of Swift considerations. 

You could just run `detox build-framework-cache` inside your e2e script to make sure the framework is properly build and in the right place.

**Comment by cs01** [comment]
We will be running Detox is an unusual environment. The motivations behind this request are 

1.) we want to test at scale by leasing remote simulators on-demand. Each leased simulator runs on a shared machine that doesn't have internet access or detox source code installed. We also don't want to pollute the home directory of the machines running simulators/devices. 

2.) The test will be initiated from a linux machine that cannot build the detox framework. So the plan would be to build the Detox framework once and tag it with the relevant information (detox version and xcodebuild -version output), then reuse it as needed by pulling from our intranet without rebuilding each time. An assertion would be made that the Detox framework is compatible with the target machines.

We do understand that this is not the most common use-case, but it seems like the best solution given our architecture.

cc @lawrencelomax

**Comment by LeoNatan** [comment]
Thanks
Would you like to submit a PR with this? It seems like an easy think to accomplish. `${DETOX_FRAMEWORK_PATH}`

**Comment by cs01** [comment]
Sure, I will submit the code example I gave in the initial issue description.

**Comment by LeoNatan** [comment]
Thanks

**Comment by LeoNatan** [comment]
@cs01 Any update on the PR? Thanks

**Comment by cs01** [comment]
I have been able to make it work without the change. If I need it I will make a PR but for now I am fine closing the issue.
