### ISSUE TITLE
WebView Matchers

### ISSUE THREAD

**Issue by isnifer** [wix/detox#136]
Hi, guys!

Thank you for the great tool. We've sped up our tests in 5 times.
Please, tell me how can I test web views? Facebook login for example:
![image](https://cloud.githubusercontent.com/assets/1788245/26279372/b2ec4a12-3dba-11e7-862c-5c3adf763265.png)

**Comment by bootstraponline** [comment]
you might be interested in https://github.com/google/EarlGrey/issues/211 for how to support WebViews 😄

**Comment by isnifer** [comment]
@bootstraponline awesome. Hope, detox will too

**Comment by LeoNatan** [comment]
@bootstraponline This is not a web view. This is a Safari view controller, which renders off-process. Once Earl Grey 2.0 (https://github.com/google/EarlGrey/pull/193) is ready, there will be more support for this. Closing for now.

**Comment by bootstraponline** [comment]
Is there no way to inject JS in the Safari view controller? That should be all that's required to automate a webpage.

**Comment by LeoNatan** [comment]
No, it is not possible. A Safari view controller, unlike UIWebView and WKWebView, is intended to preserve the user’s privacy. As such, its only input is a URL and whether it should enter reader mode right away. There is no access to the DOM after it has rendered.

**Comment by bootstraponline** [comment]
Oh, thanks for the info.
