### ISSUE TITLE
Integrate parallel testing using Jest in Detox CI (iOS)

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#1369]
Introduce parallel test-execution in CI, for iOS, using the latest Jest tweaks made in `12.7.0`.

**Comment by LeoNatan** [comment]
Please wait with this. We had many issues and moved back to mocha. If debugability is still bad, we should remain with mocha.

**Comment by rawqing** [comment]
I had some problems with Mocha : https://github.com/mochajs/mocha/issues/94 ; https://github.com/ampproject/amphtml/issues/15658 , so I had to use jest
