### ISSUE TITLE
Detox can't able to run build release version

### ISSUE THREAD

**Issue by praveenkumarr88** [wix/Detox#1377]
Error: \android\app\build\outputs\apk\androidTest\debug\androidTest\app-debug-androidTest-androidTest.apk' could not be found, did you run './gradlew assembleAndroidTest' ? 

node_modules\.bin\mocha e2e --opts e2e/mocha.opts --configuration android.emu.release      --grep :ios: --invert     --artifacts-location "artifacts\android.emu.release.2019-05-10 11-31-05Z"

(node:51320) DeprecationWarning: "--compilers" will be removed in a future version of Mocha; see https://git.io/vdcSr for more info                                     detox[51320] INFO:  [DetoxServer.js] server listening on localhost:52976...
detox[51320] ERROR: [index.js/DETOX_INIT_ERROR]                                                                                                                          Error: 'C:\Users\praveen.kumar.b.ext\DetoxTesting\service_guide_mobile_v2.0\android\app\build\outputs\apk\androidTest\release\app-release-androidTest.apk' could not be found, did you run './gradlew assembleAndroidTest' ?                                                                                                                       at EmulatorDriver.getTestApkPath (C:\Users\praveen.kumar.b.ext\DetoxTesting\service_guide_mobile_v2.0\node_modules\detox\src\devices\drivers\AndroidDriver.js:69:13)    at EmulatorDriver.installApp (C:\Users\praveen.kumar.b.ext\DetoxTesting\service_guide_mobile_v2.0\node_modules\detox\src\devices\drivers\AndroidDriver.js:57:77)        at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)                                                                                                        1) "before all" hook: _callee
                                                                                                                                                                          0 passing (7s)
  1 failing
  1) "before all" hook: _callee:                                                                                                                                             Error: 'C:\Users\praveen.kumar.b.ext\DetoxTesting\service_guide_mobile_v2.0\android\app\build\outputs\apk\androidTest\release\app-release-androidTest.apk' could not be found, did you run './gradlew assembleAndroidTest' ?                                                                                                                     at EmulatorDriver.getTestApkPath (node_modules\detox\src\devices\drivers\AndroidDriver.js:69:13)
      at EmulatorDriver.installApp (node_modules\detox\src\devices\drivers\AndroidDriver.js:57:77)                                                                            at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by praveenkumarr88** [comment]
package.json

  "detox": {
    "test-runner": "mocha",
    "specs": "e2e",
    "runner-config": "e2e/mocha.opts",
    "configurations": {
      "android.emu.debug": {
        "binaryPath": "android/app/build/outputs/apk/debug/app-debug.apk",
        "build": "cd android && gradlew assembleDebug app:assembleAndroidTest -DtestBuildType=debug && cd..  && react-native start",
        "type": "android.emulator",
        "name": "Pixel_2_XL_API_28"
      },
      "android.emu.release": {
        "binaryPath": "android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk",
        "build": "cd android && gradlew assembleRelease assembleAndroidTest -DtestBuildType=release && cd..",
        "type": "android.emulator",
        "name": "Pixel_2_XL_API_28"
      }
    }
  }

**Comment by maamounapprise** [comment]
have you signed your app?

**Comment by praveenkumarr88** [comment]
> have you signed your app?

Yes app is signed
