### ISSUE TITLE
Profiler does not record network requests even if told to (by code from Detox.framework)

### ISSUE THREAD

**Issue by noomorph** [wix/Detox#1379]
# Description

The recent pull request to Detox (["Record network and events in Detox Instruments artifacts"](https://github.com/wix/Detox/pull/1333))
should have enabled recording network requests in the integration of Detox and Detox Instruments
(introduced originally in [wix/Detox#1165](https://github.com/wix/Detox/pull/1165)).  However, it does not seem to work as intended.

**[This demo project](https://github.com/noomorph/bug-reports/tree/detox/no-network-recording/NetworkRecordingIssue) demonstrates the bug.**

# Environment

* MacOS Mojave (10.14.4)
* Xcode 10.2.1 (10E1001)
* Detox Instruments 1.10 (10233)
* Node.js 10.15.0 (installed via `nvm`)
* Detox 12.6.3
* iPhone X (in Simulator)

## Steps to reproduce

1. Clone `git clone git@github.com:noomorph/bug-reports.git`
2. Checkout to branch `detox/no-network-recording`.
3. Run `npm install`.
4. Run `npm start`.
5. In another terminal tab, run `npm test`.
6. Wait till the test completes.
7. Open with Detox Instruments `artifacts/ios.<YYYY-MM-DD HH-mm-ssZ>/✓ Example should have welcome screen/test.dtxrec`.

## Expected result

**Network Activity** timeline should have at least 1 request:

```
GET 200 http://worldclockapi.com/api/json/utc/now
```

## Actual result

**Network Activity** timeline is empty.

![Detox Instruments screenshot](https://raw.githubusercontent.com/noomorph/bug-reports/detox/no-network-recording/NetworkRecordingIssue/images/dtxinst.png)

**Comment by LeoNatan** [comment]
Moved the issue to Detox, because this is where it will be fixed.

**Comment by LeoNatan** [comment]
I found the issue. It wasn't related to late framework load. It's related to swizzle order between Profiler and Earl Grey. Investigating.

**Comment by LeoNatan** [comment]
Fixed
