### ISSUE TITLE
Detox not disabling YellowBox when running tests on 0.59.8

### ISSUE THREAD

**Issue by doelgonzo** [wix/Detox#1382]
**Describe the bug**
On React Native 0.59.8, I am seeing a weird behavior where I am running tests and YellowBox appears to not be disabled. In every previous instance (most lately 0.57), I have seen YellowBox properly disabled when running E2E tests and this was working just fine. This tells me Detox is not disabling the YellowBox, or is no longer compatible with how React Native does it's warnings, anymore.

Now, given YellowBox is not disabled, warnings pop up and the test gestures try to press where buttons would be if the warnings weren't there. If I `console.disableYellowBox = true`; all my tests pass, so I'm wondering if this has anything to do with the reimplementation of YellowBox or if there is something I am missing in my mocha/detox config.

**To Reproduce**

- [ X] I have tested this issue on the latest Detox release and it still reproduces

**This did not happen on Detox 10/RN 0.57**

Config:
`
"ios.sim.debug": {
        "binaryPath": "ios/build/myProject/Build/Products/Debug-iphonesimulator/myProject.app",
        "build": "npm run ios -- --simulator=\"iPhone 7\"",
        "type": "ios.simulator",
        "name": "iPhone 7"
      },
      "ios.sim.release": {
        "binaryPath": "ios/build/myProject/Build/Products/Release-iphonesimulator/twmobile.app",
        "build": "xcodebuild -workspace ios/myProject.xcworkspace -scheme myProject -configuration Release -sdk iphonesimulator -derivedDataPath ios/build",
        "type": "ios.simulator",
        "name": "iPhone 7"
      }
`

**Environment (please complete the following information):**
 - Detox: 12.8.0
 - React Native: 0.59.8
 - Node: 10.15.3
 - Device: iPhone 7
 - Xcode: 10.2
 - iOS: 12.2
 - macOS: Mojave

**Comment by LeoNatan** [comment]
Detox makes no attempt to disable yellow boxes, nor should it. It's your responsibility, as an app owner, to do that. We always recommend building in Release so that you do not hit such issues.
