### ISSUE TITLE
Headless hardware keyboard default not working

### ISSUE THREAD

**Issue by wilau2** [wix/Detox#1393]
**Describe the bug**
When running in headless mode with parameter: 
`ConnectHardwareKeyboard boolean NO`
It behaves like if the connect hardware keyboard was at true.

**To Reproduce**

- [x] I have tested this issue on the latest Detox release and it still reproduces

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

1. Create a test that will fail if connect hardware keyboard was at true. (Usually implies typing in an input)
2. Run in headless should fail.
3. Open Simulator.app and should pass.

**Expected behavior**
Headless should behave the same when simulator.app is open

**Environment (please complete the following information):**
 - Detox: 12.6.1
 - React Native: 59.6
 - Node: 10.4.1
 - Device: Iphone7
 - Xcode: 10.1
 - iOS: 12.1
 - macOS: 10.13.6

**Device and Verbose Detox Logs**
```
visual.release --artifacts-location packages/detox/visual/tmp/ --loglevel verbose
detox[18247] INFO:  [test.js] configuration="ios.visual.release" loglevel="verbose" artifactsLocation="packages/detox/visual/tmp/" recordLogs="none" takeScreenshots="manual" recordVideos="none" recordPerformance="none" node_modules/.bin/jest --config=packages/detox/config.json --maxWorkers=1 '--testNamePattern=^((?!:android:).)*$' packages/detox/visual
detox[18248] INFO:  [DetoxServer.js] server listening on localhost:50132...
detox[18248] DEBUG: [AsyncWebSocket.js/WEBSOCKET_OPEN] opened web socket to: ws://localhost:50132
detox[18248] DEBUG: [DetoxServer.js/LOGIN] role=tester, sessionId=5de147f8-df87-0e58-c7b3-e24446a2aebe
detox[18248] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=tester, sessionId=5de147f8-df87-0e58-c7b3-e24446a2aebe
detox[18248] DEBUG: [exec.js/EXEC_CMD, #0] /usr/bin/xcrun simctl list -j
detox[18248] DEBUG: [exec.js/EXEC_CMD, #1] applesimutils --list --byType "iPhone 7" --byOS "12.1"
detox[18248] DEBUG: [exec.js/EXEC_TRY, #1] Searching for device matching iPhone 7...
detox[18248] DEBUG: [exec.js/EXEC_CMD, #2] applesimutils --list --byId "B7ECB144-869C-43D1-BAF9-2D23D358D7F4"
detox[18248] DEBUG: [exec.js/EXEC_CMD, #3] xcodebuild -version
detox[18248] DEBUG: [exec.js/EXEC_CMD, #4] /usr/bin/xcrun simctl boot B7ECB144-869C-43D1-BAF9-2D23D358D7F4
detox[18248] DEBUG: [exec.js/EXEC_TRY, #4] Booting device B7ECB144-869C-43D1-BAF9-2D23D358D7F4
detox[18248] DEBUG: [exec.js/EXEC_CMD, #5] /usr/bin/xcrun simctl bootstatus B7ECB144-869C-43D1-BAF9-2D23D358D7F4
detox[18248] DEBUG: [exec.js/EXEC_CMD, #6] /usr/bin/xcrun simctl uninstall B7ECB144-869C-43D1-BAF9-2D23D358D7F4 org.reactjs.native.example.storybook
detox[18248] DEBUG: [exec.js/EXEC_TRY, #6] Uninstalling org.reactjs.native.example.storybook...
detox[18248] DEBUG: [exec.js/EXEC_SUCCESS, #6] org.reactjs.native.example.storybook uninstalled
detox[18248] DEBUG: [exec.js/EXEC_CMD, #7] /usr/bin/xcrun simctl install B7ECB144-869C-43D1-BAF9-2D23D358D7F4 "/Users/wlauze/github.com/jive/gotoconnect-mobile/packages/storybook/ios/build/Build/Products/Release-iphonesimulator/storybook.app"
detox[18248] DEBUG: [exec.js/EXEC_TRY, #7] Installing /Users/wlauze/github.com/jive/gotoconnect-mobile/packages/storybook/ios/build/Build/Products/Release-iphonesimulator/storybook.app...
detox[18248] DEBUG: [exec.js/EXEC_SUCCESS, #7] /Users/wlauze/github.com/jive/gotoconnect-mobile/packages/storybook/ios/build/Build/Products/Release-iphonesimulator/storybook.app installed
detox[18248] DEBUG: [exec.js/EXEC_CMD, #8] /usr/bin/xcrun simctl terminate B7ECB144-869C-43D1-BAF9-2D23D358D7F4 org.reactjs.native.example.storybook
detox[18248] DEBUG: [exec.js/EXEC_TRY, #8] Terminating org.reactjs.native.example.storybook...
detox[18248] DEBUG: [exec.js/EXEC_SUCCESS, #8] org.reactjs.native.example.storybook terminated
detox[18248] DEBUG: [exec.js/EXEC_CMD, #9] /bin/cat /dev/null >/Users/wlauze/Library/Developer/CoreSimulator/Devices/B7ECB144-869C-43D1-BAF9-2D23D358D7F4/data/tmp/detox.last_launch_app_log.out 2>/Users/wlauze/Library/Developer/CoreSimulator/Devices/B7ECB144-869C-43D1-BAF9-2D23D358D7F4/data/tmp/detox.last_launch_app_log.err && SIMCTL_CHILD_DYLD_INSERT_LIBRARIES="/Users/wlauze/Library/Detox/ios/9038d6671ae06ed92ef33be8da6ef6e58588757b/Detox.framework/Detox" /usr/bin/xcrun simctl launch --stdout=/tmp/detox.last_launch_app_log.out --stderr=/tmp/detox.last_launch_app_log.err B7ECB144-869C-43D1-BAF9-2D23D358D7F4 org.reactjs.native.example.storybook --args -detoxServer "ws://localhost:50132" -detoxSessionId "5de147f8-df87-0e58-c7b3-e24446a2aebe"
detox[18248] DEBUG: [exec.js/EXEC_TRY, #9] Launching org.reactjs.native.example.storybook...
detox[18248] INFO:  [AppleSimUtils.js] org.reactjs.native.example.storybook launched. The stdout and stderr logs were recreated, you can watch them with:
        tail -F /Users/wlauze/Library/Developer/CoreSimulator/Devices/B7ECB144-869C-43D1-BAF9-2D23D358D7F4/data/tmp/detox.last_launch_app_log.{out,err}
detox[18248] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=testee not connected, cannot fw action (sessionId=5de147f8-df87-0e58-c7b3-e24446a2aebe)
detox[18248] DEBUG: [DetoxServer.js/LOGIN] role=testee, sessionId=5de147f8-df87-0e58-c7b3-e24446a2aebe
detox[18248] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=testee, sessionId=5de147f8-df87-0e58-c7b3-e24446a2aebe
```

**Comment by LeoNatan** [comment]
I am not familiar with `ConnectHardwareKeyboard`, but how are you sending the argument? It doesn't seem like it was sent in the log.

**Comment by wilau2** [comment]
This is set via xcode `~/Library/Preferences/com.apple.iphonesimulator.plist`
![image](https://user-images.githubusercontent.com/5473183/58022876-707aca80-7adc-11e9-8518-39a33d832250.png)

You can see that before xcode 9, detox was booting the simulator with a flag on. It seems to me that this is not working on xcode 10. 

https://github.com/wix/Detox/blob/32be293774383d631d0938300175204d4222dd13/detox/src/devices/ios/AppleSimUtils.js#L245

**Comment by LeoNatan** [comment]
If you add that much argument yourself, does it work?

**Comment by vadimshvetsov** [comment]
@wilau2 it looks like every developer need to set manually after clonning a repo. Is there a way to pass this argument with Detox settings?

**Comment by LeoNatan** [comment]
Does it work if passed manually?

**Comment by LeoNatan** [comment]
Guys, please confirm that it works when adding the launch argument manually to `launchApp`. If we have a confirmation, we will add this argument.

**Comment by wilau2** [comment]
@LeoNatan I'll try that today, yesterday was crazy my bad.

**Comment by LeoNatan** [comment]
Detox only supports Xcode 10 and above.

**Comment by vadimshvetsov** [comment]
@wilau2 What command do you use to build and run app with parameter `ConnectHardwareKeyboard`?

**Comment by LeoNatan** [comment]
You pass it in `luanchApp`.

**Comment by wilau2** [comment]
Tested with: 
```
await device.launchApp({ launchArgs: { ConnectHardwareKeyboard: false }, ConnectHardwareKeyboard: false });
```
and
```
await device.launchApp({ launchArgs: { ConnectHardwareKeyboard: 0 }, ConnectHardwareKeyboard: 0 });
```
in my init.js
```
beforeAll(async () => {

})
```
It's not working in headless mode. 

I also ran: 
https://github.com/evertoncunha/cocoaheads-2018-07/blob/master/fastlane/enable_simulators_keyboards.sh
Making sure everything in at 0 by default.

**Comment by wilau2** [comment]
I've been reading: 
https://www.rubydoc.info/gems/simctl/SimCtl/Command/Launch#launch_app-instance_method
It looks like there is 2 signature in the launch function and the ConnectHardwareKeyboard arg seems to be supported only by launch_device.
launch_app
launch_device

I'll try some more stuff.

**Comment by Esxiel** [comment]
Environment:
Detox: 12.1.3
React Native: 57.6
Node: 10.15.1
Device: Iphone X ( tested on iPhone 6 iOs 9 as well)
Xcode: 10.2.1
iOS: 12.2
macOS: 10.14.4

@wilau2 are you implying that if you open up the simulator, the ConnectHardwareKeyboard boolean NO set in the com.apple.iphonesimulator.plist behaves properly? Since on my end, even on a freshly opened simulator, the hardware keyboard is disconnected but the keyboard will not show up regardless 
(unless, 1. I CMD+SHIFT+K 2x, i.e. connect & disconnect hardware keyboard inside the simulator, 2. I  use CMD+K to turn on soft keyboard).

**Comment by LeoNatan** [comment]
Why does `launch_device` do? I am not familiar with this command.

**Comment by dwilt** [comment]
Any updates on this? We are trying to get detox running in CircleCI and are running into this same issue.

**Comment by LeoNatan** [comment]
I’ll take a look soon.

**Comment by dwilt** [comment]
Thanks @LeoNatan. I've worked around it via https://github.com/wix/Detox/issues/39#issuecomment-323515694

**Comment by LeoNatan** [comment]
Guys, the more I think about it, the more it doesn't make sense to me. 

`ConnectHardwareKeyboard` is only used by the Simulator app. Since we are talking about a headless boot, it shouldn't be read at all and the hardware keyboard should always be disconnected.

**Comment by dwilt** [comment]
That sounds good to me. Are you suggesting persisting it to being disconnected?

**Comment by LeoNatan** [comment]
I am suggesting that it is irrelevant in headless simulators.

**Comment by dwilt** [comment]
Well, it's causing an issue since the soft keyboard is disabled (and doesn't show) because the hardware one is enabled (even though it's a sim). What are you suggesting is the fix?

**Comment by LeoNatan** [comment]
Why did you decide that it's the hardware keyboard?
Have you tried taking a screenshot to make sure that keyboard doesn't indeed show? You can call [`device.takeScreenshot(name)`](https://github.com/wix/Detox/blob/master/docs/APIRef.DeviceObjectAPI.md#devicetakescreenshotname) after tapping on a text field but before trying to type. Please see if the keyboard is shown or not.

**Comment by dwilt** [comment]
Yea, let me take a video showing my screen. Will share in a second.

**Comment by dwilt** [comment]
hey Leo, just looking into [how to take a screenshot](https://github.com/wix/Detox/blob/master/docs/APIRef.Artifacts.md#enabling-artifacts) now and realizing it's bit involved and since I'm pretty new to CircleCI, it might take me a while.

In the meantime, what I can say is that the errors that are showing up for me in CircleCI seem to indicate that the issue is that the soft keyboard isn't showing. I mean, I can even get it to fail when _not_ in headless mode (actually running the simulator locally). Whenever I start up a brand new simulator, the hardward keyboard is enabled by default - not the soft one. So I would imagine its the same default in headless mode - no matter where it's run.

You would think being able to toggle the hardware keyboard on a simulator shouldn't be possible because as you pointed out - it's a simulator.

**Comment by LeoNatan** [comment]
But what you are describing is the Simulator.app behavior. That’s different than the simulator runtime. Detox does not launch the app, it only boots the runtime. 

To really test, kill your Simulator.app and shutdown all runtimes. Then run a detox test. 

You will probably still not reproduce as we know it works. But the tests failing in CI could be many different reasons, so a screenshot would be helpful. You could curl it somewhere or otherwise retrieve it.

**Comment by dwilt** [comment]
When you say "runtime", you mean the `xcodebuild` command, right? If I understand correctly, you mean that Detox just runs the `xcodebuild` command and it's that command that actually fires up the Simulator?

**Comment by dwilt** [comment]
BTW, I just ran the `takeScreenshot` command in CircleCI and it would seem it ran:

```sh
detox[37851] INFO:  [test.js] configuration="ios.sim.release" cleanup=true artifactsLocation="artifacts/ios.sim.release.2019-06-24 16-00-44Z" recordLogs="none" takeScreenshots="manual" recordVideos="none" recordPerformance="none" reportSpecs=true node_modules/.bin/jest --config=e2e/config.json --maxWorkers=1 '--testNamePattern=^((?!:android:).)*$' "e2e"
```
I just need to figure out how to access the screenshot..

**Comment by LeoNatan** [comment]
That's not the screenshot I mean. You can manually trigger a screenshot using `device.takeScreenshot(name)` in your test, so that it takes a screenshot in the right time.

I am not familiar with Circle. Do they have an artifacts folder where you can put stuff and they appear at the end?

**Comment by LeoNatan** [comment]
> 
> 
> When you say "runtime", you mean the `xcodebuild` command, right? If I understand correctly, you mean that Detox just runs the `xcodebuild` command and it's that command that actually fires up the Simulator?

No. I mean simulator runtime.

When you `xcrun simctl boot`, it's the simulator runtime (OS process and daemons) that are launched, not the Simulator.app, which is used for interaction with the simulator runtime.

`xcodebuild` is for compilation, unrelated.

**Comment by dwilt** [comment]
> That's not the screenshots I mean. You should manually trigger a screenshot using device.takeScreenshot(name) in your test, so that it takes a screenshot in the right time.
Oh, I thought that was showing me the folder the screenshots would be put in. Here's my code:

```js
await element(by.text('Log in')).tap();

await emailInput.replaceText('dwilt4rville@gmail.com');

const passwordInput = await element(by.id('login-password-input'));
await device.takeScreenshot('tying in password');
await passwordInput.typeText('Airapp123!');

await device.disableSynchronization();
await passwordInput.tapReturnKey();
```

**Comment by LeoNatan** [comment]
I think I see a problem.

Try changing your code to
```
const passwordInput = await element(by.id('login-password-input'));
await passwordInput.tap();
await device.takeScreenshot('typing in password');
await passwordInput.typeText('Airapp123!');
```

**Comment by vmurillo** [comment]
I am running into this issue when running on headless mode; type Text action fails with this message 

> Keyboard did not appear after tapping on element [E]. Are you sure that tapping on this element will bring up the keyboard?

I am launching my app like this
`beforeAll(async () => {
    // reinstall app
    await device.launchApp({ delete: true, launchArgs: { ConnectHardwareKeyboard: false } })
  })`

**Comment by dwilt** [comment]
So the `tap` really is required first? If so, that should be documented better because on the home page of the docs, it suggests you can just do `typeText` without the `tap` in front of it to make sure the keyboard pops up.

All this being said, I put together a video showing our scenario and what's going on. Let me know your thoughts.

[![detox debugging](https://img.youtube.com/vi/SF9zXSf5FH8/0.jpg)](https://www.youtube.com/watch?v=SF9zXSf5FH8)

**Comment by dwilt** [comment]
Update: Something I just noticed was that when I kill the simulator that I've been testing in, the issue with the keyboard goes away. But if I re-run the test without restarting the simulator, the test will fail. Here is my test code:

```js
it('you can login from the landing page and land on the gallery', async () => {
  const emailInput = await element(by.id('login-email-input'));

  await expect(emailInput).toBeNotVisible();

  await element(by.text('Log in')).tap();

  await emailInput.replaceText('dwilt4rville@gmail.com');

  const passwordInput = await element(by.id('login-password-input'));
  await passwordInput.typeText('Airapp123!');

  await device.disableSynchronization();
  await passwordInput.tapReturnKey();

  const loader = await element(by.id('loader'));

  await expect(loader).toExist();

  await waitFor(loader)
    .toNotExist()
    .withTimeout(15000);

  await expect(loader).toNotExist();
  await expect(element(by.id('gallery'))).toBeVisible();
  await device.enableSynchronization();
});
```
Notice that I'm _not_ using a `.tap()` before using `typeText` and it still works. And what's more interesting is that when it succeeds the first time after restarting the simulator, the soft keyboard wasn't enabled. I know this because if I tap into a text field manually, the keyboard doesn't come up. But it did come up during the tests. Again, if I try to run the test without restarting the simulator, the test fails.

**Comment by dwilt** [comment]
I take that back. It seems inconsistent. Here is a screenshot FYI:

![image](https://user-images.githubusercontent.com/1065539/60066300-82432500-96bb-11e9-9c0a-61d50eeccb3c.png)

**Comment by LeoNatan** [comment]
Thanks for the video!

Tap might not be necessary. (Won't help but shouldn't cause issues.)

OK, let's address the things in the video. First, local running: since you have the Simulator.app open, indeed hiding the software keyboard with CMD+K will break the test. Tap will not be able to show the software keyboard. Everything in the video is the expected behavior when Simulator.app is running.

Now, about circle: the error I saw there was about the loader (when it failed). Just want to make sure that you are seeing actual keyboard failures on CI as well. If you do, it would be really odd to have such difference between runs.

**Comment by LeoNatan** [comment]
Might have a solution that will fix this issue.

**Comment by dwilt** [comment]
Ok, another update. All of my tests are passing on CircleCI now which is great. Not sure what changed but it's awesome. 

@LeoNatan It's important to note that forcing the keyboard to show (CMD+K) in a _local_ sim is required if any of your events are using the typing. What's interesting is that my _headless_ (circle) tests are passing which sounds like where @vmurillo is having issues - so not sure why it's different. If you'd want to jump on a google hangout and chat, let me know cause I'd be more than happy to make some videos/contribute to the faqs to help document this a bit more.

**Comment by rotemmiz** [comment]
@dwilt, an unrelated question. Were you able to run Android E2E on circle CI?

**Comment by dwilt** [comment]
Here's all of my code to share so people can see what I have working in Circle:

**e2e/firstTest.spec.js**
```js
describe('Air App', () => {
  beforeEach(async () => {
    await device.reloadReactNative();
  });

  it('you can login from the landing page and land on the gallery', async () => {
    const loginButton = await element(by.id('landing-login-button'));
    await loginButton.tap();

    const emailInput = await element(by.id('login-email-input'));
    await emailInput.replaceText('dwilt4rville@gmail.com');

    const passwordInput = await element(by.id('login-password-input'));
    await passwordInput.typeText('Airapp123!');

    await device.disableSynchronization();
    await passwordInput.tapReturnKey();

    const loader = await element(by.id('loader'));
    await expect(loader).toExist();
    await waitFor(loader)
      .toNotExist()
      .withTimeout(15000);
    await expect(loader).toNotExist();

    const gallery = await element(by.id('gallery'));
    await expect(gallery).toBeVisible();

    await device.enableSynchronization();
  });

  it('can perform a text search', async () => {
    const searchButton = await element(by.id('clips-search-button'));
    await searchButton.tap();

    const searchInput = await element(by.id('search-input'));
    await searchInput.typeText('test search');

    await device.disableSynchronization();
    await searchInput.tapReturnKey();
    await device.enableSynchronization();

    const appliedFilter = await element(by.id('search-applied-filter-0'));
    await expect(appliedFilter).toExist();

    const exitSearchButton = await element(by.id('exit-search-button'));
    await exitSearchButton.tap();

    const removedAppliedFilter = await element(by.id('search-applied-filter-0'));
    expect(removedAppliedFilter).toNotExist();
  });
});
```

**.circleci/config.yml**
```yml
# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
# yml parser for sanity check: https://yaml-online-parser.appspot.com/

version: 2.1

aliases:
  - &restore-cache
    keys:
      - v2-test-{{ .Branch }}-{{ checksum "package.json" }}
      - v2-test-{{ .Branch }}

  - &save-node-cache
    key: v2-test-{{ .Branch }}-{{ checksum "package.json" }}
    paths:
      - node_modules

  - &save-ios-cache
    key: v2-test-{{ .Branch }}-{{ checksum "package.json" }}
    paths:
      - node_modules
      - ios/build

  - &install-node-dependencies |
    echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
    yarn

defaults: &defaults
  working_directory: ~/airapp

jobs:
  detox:
    <<: *defaults
    macos:
      xcode: '10.2.1'

    steps:
      - checkout
      - run:
          name: Load dependencies
          command: |
            brew update
            brew tap wix/brew
            brew install --HEAD applesimutils
            npm install -g detox-cli
      - run: *install-node-dependencies
      - run:
          name: Fetch CocoaPods Specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
            cd ios; pod install
      - run: yarn detox:release

  typescript_check:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: *install-node-dependencies

      - run:
          name: Confirm project compiles in TypeScript
          command: yarn type-check

workflows:
  version: 2
  everything:
    jobs:
      - typescript_check
      - detox
```
And a gif showing it completing locally. **AGAIN, to get these to pass, I had to make sure to enable the soft keyboard via `CMD+K`. If you quit the simulator each time, the keyboard will get reset to being disabled**
![image](https://media.aircamera.com/47e2b61e-1460-4c4b-ac5a-9b3c9a7ed8b9.gif)

**Comment by dwilt** [comment]
@rotemmiz we haven't tackled Android yet :sweat_smile:

**Comment by vmurillo** [comment]
@dwilt so it just started working magically in CircleCI? There was no change in detox config in package.json ? I am currently running tests locally a pressing cmd+K to make it work, I would like to have this running on travisCI on headless mode

**Comment by LeoNatan** [comment]
With https://github.com/wix/Detox/pull/1480 this will be solved, hopefully. I will merge it now and release a version.

**Comment by LeoNatan** [comment]
Please install Detox 13.0.0 and try.

**Comment by dwilt** [comment]
@vmurillo yea, not that I can tell. I did not make any changes that were specific to package.json, any detox config or config.yml (for CircleCI) that I'm aware of that would've made this work.

I'm looking back at my failed CircleCI builds and as you see above, it was regarding another issue - not the keyboard. I _was_ having keyboard issues locally and then seeing failed builds on the server and wrongfully assuming they were keyboard related.
