### ISSUE TITLE
iOS simulator not found after upgrading to the latest applesimutils 

### ISSUE THREAD

**Issue by vincenzovitale** [wix/Detox#1395]
**Describe the bug**
iOS simulator not found after upgrading to XCode 10.2.1 and latest applesimutils 

**To Reproduce**

- I have tested this issue on the latest Detox release and it still reproduces

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

1. Upgrade the applesimutils
2. Open the simulator
3. Execute any detox ios test with the available simulator specified

**Expected behavior**
Simulator is found and detox test run

**Screenshots**

**Environment (please complete the following information):**
 - Detox: 12.8.0
 - React Native: 0.59.5
 - Node: 10.15.3
 - Device: Simulator
 - Xcode: 10.2.1
 - iOS: 12.1
 - macOS: 10.4.5

**Device and Verbose Detox Logs**
I added some log statement to the AppleSimUtils.js and the response from appsimutils is:
```
[
      {
        "availabilityError" : "",
        "os" : {
          "bundlePath" : "\/Applications\/Xcode_10.1.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Developer\/Library\/CoreSimulator\/Profiles\/Runtimes\/iOS.simruntime",
          "availabilityError" : "",  
          "buildversion" : "16B91",  
          "availability" : "(available)",
          "isAvailable" : true,
          "identifier" : "com.apple.CoreSimulator.SimRuntime.iOS-12-1",
          "version" : "12.1",
          "name" : "iOS 12.1"
        },
        "availability" : "(available)",
        "deviceType" : {
          "name" : "iPhone 5s",
          "bundlePath" : "\/Applications\/Xcode_10.1.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Developer\/Library\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone 5s.simdevicetype",
          "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-5s"
        },
        "udid" : "401C5B87-7D59-4952-918E-46824F669895",
        "isAvailable" : true,
        "state" : "Booted",
        "name" : "iPhone 5s"
      }
    ]
```

and then:

detox[29351] ERROR: [index.js/DETOX_INIT_ERROR] 
 Error: Could not parse response from applesimutils, please update applesimutils and try again.
      'brew uninstall applesimutils && brew tap wix/brew && brew install applesimutils'

Any easy way I can downgrade the applesimutils version?

**Comment by LeoNatan** [comment]
Unfortunately, there is no easy way to downgrade. But I don't see how an upgraded AppleSimUtils will change the output. @rotemmiz Can you pls take a look? What could fail?

**Comment by hoffmabc** [comment]
I believe you just need to install the updated Xcode software tools. I did this through the App Store and it started working again.

**Comment by LeoNatan** [comment]
There was a bug in applesimutils. Please try with last applesimutils.
