### ISSUE TITLE
Is it possible to create keyboard events without having to specify a textField id?

### ISSUE THREAD

**Issue by evian-pring** [wix/Detox#1396]
I am handling the keyboard events in Android and passing them to React-Native over the bridge. My app uses a hardware scanner, for context. But essentially, I don't use a `TextInput` in RN, but my component does listen to the data coming over the bridge. 

i saw this `await element(by.id('textField')).typeText('passcode');` but I don't have an element to specify by id.

I need to simulate the keyboard events in detox. Is this possible?

**Comment by LeoNatan** [comment]
How does that work on actual devices and users? How is the keyboard presented to the user for events? You should try to recreate this exactly on Detox. Are you seeing some limitation? @evian-pring

**Comment by evian-pring** [comment]
As I have a hardware scanner scanning barcodes, I don't ever present the user with any keyboard. The scanner generates the keyboard events, which are handled in Android, and passed to React-Native, which just displays the scanned characters, and when it receives a newline it processes the scan.

Here is some code:
In my `React Native` app, in `MainActivity.java` I am passing an event called `onKeyDown` to `React-Native` on each keyboard event `onKeyDown` received in Android:
```
    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        // Create payload to send to JS
        WritableMap payload = Arguments.createMap();
        payload.putString("unicodeStr", Integer.toString(event.getUnicodeChar()));

        getReactNativeHost().getReactInstanceManager().getCurrentReactContext().getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class)
                .emit("onKeyDown", payload);

        return true;
    }
```

In `React-Native` I have, for example, a component called `BarcodeScanner` that does something like:
```
  public componentDidMount() {
      // listen to keyboard event passed in from native Android
      this.addListener();
  }

  public addListener(): void {
      DeviceEventEmitter.addListener('onKeyDown', this.scanListener);
  }

  private scanListener(e: OnKeyDownEvent) {
    const newInput = String.fromCharCode(parseInt(e.unicodeStr, 10));

    if (e.unicodeStr === '10') {
      // carriage return is last char in a scan, call the passed in callback to process the barcode
      this.props.onBarcodeScan(this.state.barcode);

      // reset the barcode info once processed
      this.setState({ barcode: '' });
      return;
    }

    // add character to saved barcode state
    this.setState(state => ({
      barcode: `${state.barcode}${newInput}`,
    }));
  }
```

The reason I am doing this like this is I have an app used to scan a lot of barcodes. When at first I used TextInput, I noticed the scanning became extremely slow after a few dozen or hundred scans. This way it is always fast.

But I need to test it.

**Comment by LeoNatan** [comment]
How are you presenting the keyboard? I don't come from the Android world. In iOS, something needs to be the first responder for the keyboard to show up. At that point, typing on the keyboard should work on iOS. I am not familiar with how this works on Android, but assume a ~ similar concepts.

CC @rotemmiz

**Comment by evian-pring** [comment]
As I said, I'm actually not presenting the keyboard at all, because the user doesn't actually need to type anything in. I use a Zebra hardware scanner connected to the Android tablet via USB, and I scan a barcode. It generates keyboard events that I can respond to in my native Android code and send to React-Native.

I'm doing everything in Android by the way. Not sure how I would use a hardware scanner on iOS, but I assume there would be a way in native iOS to respond to the generated keyboard events as well.

The workaround I guess I need to do to be able to test currently is to render a `TextInput` for the detox test build, so that I can get it `byId` and then `typeText` into it.

**Comment by LeoNatan** [comment]
I see now. Thanks

@rotemmiz Is it possible with adb to emit hardware keyboard events (like for example, from a Bluetooth keyboard)?
