### ISSUE TITLE
Detox Crashing On Android Latest version

### ISSUE THREAD

**Issue by amiceli-torstar** [wix/Detox#1398]
**Describe the bug**
Currently right now I am working on an app that is building fine on ios, the tests work in ios. I've tested the app on an emulator and it works fine, but when I try to run it with detox, it crashes upon launch.

This is a new app that I'm working with, so I installed the latest version of detox since we haven't used it with it before.

**To Reproduce**
Open metro bundler in separate terminal
detox build -c ***Android config***
detox test -c ***Android config***

**Expected behavior**
Expected test to run

**Environment (please complete the following information):**
 - Detox: 12.9.0
 - React Native: 0.58.4
 - Node: 8.10.0
 - Device: Android emulator API 26
 - OS: Android

**Device and Verbose Detox Logs**

Attached

[adblogs.txt](https://github.com/wix/Detox/files/3208552/adblogs.txt)

[detoxlogs.txt](https://github.com/wix/Detox/files/3208549/detoxlogs.txt)

**Comment by kulbhushan-ucreate** [comment]
Same here, My test cases works fine in IOS. But Not working in android. 
Please give proper docs for android setup.
:)

**Comment by d4vidi** [comment]
@amiceli-torstar could you please attach your app and project (root) `build.gradle` files? For some reason, the Kotlin standard library doesn't get wired into your .apk -- I'd be happy to understand why.

**Comment by d4vidi** [comment]
```
Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jvm.internal.Lambda" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.saveca.test-KireB2VXNNGYeFlIbIGMnw==/base.apk", zip file "/data/app/com.saveca-y_Q2-QsgfQ6cgUrkJa8BJQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.saveca.test-KireB2VXNNGYeFlIbIGMnw==/lib/x86, /data/app/com.saveca-y_Q2-QsgfQ6cgUrkJa8BJQ==/lib/x86, /data/app/com.saveca.test-KireB2VXNNGYeFlIbIGMnw==/base.apk!/lib/x86, /data/app/com.saveca-y_Q2-QsgfQ6cgUrkJa8BJQ==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
05-22 13:14:43.125 18925 18965 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
05-22 13:14:43.125 18925 18965 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
05-22 13:14:43.125 18925 18965 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
05-22 13:14:43.125 18925 18965 E AndroidRuntime: 	... 13 more
```

**Comment by amiceli-torstar** [comment]
App build.gradle (converted to txt): 

[build.gradle.txt](https://github.com/wix/Detox/files/3223872/build.gradle.txt)

**Comment by amiceli-torstar** [comment]
Project root build.gradle (converted to txt)

[build.gradle.txt](https://github.com/wix/Detox/files/3223873/build.gradle.txt)

**Comment by lapto** [comment]
Your missing step 3 - Add Kotlin: https://github.com/wix/Detox/blob/master/docs/Introduction.Android.md

``` 
buildscript {
    ext {
        buildToolsVersion = "27.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
        ext.kotlinVersion = '1.3.0' // add this 
    }
    repositories {
        google()
        jcenter() 
        maven {
           url 'https://maven.fabric.io/public'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.0'
        classpath 'com.google.gms:google-services:4.2.0'
        classpath 'io.fabric.tools:gradle:1.29.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion" //add this
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
```

**Comment by LeoNatan** [comment]
Guys, please test with @lapto ‘s suggestion. Thanks

**Comment by d4vidi** [comment]
@amiceli-torstar thanks. Not sure I understand, though - I don't see detox related configurations in the files you've had attached.
