### ISSUE TITLE
Fbsimctl issue on detox installation 

### ISSUE THREAD

**Issue by bargeharish** [wix/detox#140]
using target fbsimctl
using command build
using output directory /usr/local/Cellar/fbsimctl/HEAD-85b4660
/usr/local/opt/carthage/bin/carthage
/private/tmp/fbsimctl-20170529-14527-1lol0ig/fbsimctl /private/tmp/fbsimctl-20170529-14527-1lol0ig
dyld: Symbol not found: __TMV6Result8AnyError
  Referenced from: /usr/local/Cellar/carthage/0.23.0/bin/../Frameworks/CarthageKit.framework/Versions/Current/Frameworks/ReactiveSwift.framework/ReactiveSwift
  Expected in: /Library/Frameworks/CarthageKit.framework/Versions/Current/Frameworks/Result.framework/Versions/A/Result
 in /usr/local/Cellar/carthage/0.23.0/bin/../Frameworks/CarthageKit.framework/Versions/Current/Frameworks/ReactiveSwift.framework/ReactiveSwift
./build.sh: line 38: 14862 Abort trap: 6           carthage bootstrap --platform Mac

**Comment by LeoNatan** [comment]
Hi,
This seems like an issue with `fbsimctl`. Please open an issue at https://github.com/facebook/FBSimulatorControl/issues.

Thanks
