### ISSUE TITLE
Flaky test for Android if test contains scroll

### ISSUE THREAD

**Issue by lapto** [wix/Detox#1406]
**Describe the bug**
Test involving scrolling is flaky for android if the ScrollView has clickable/touchable children.
If the scrollview contains clickable/touchable children from edge to edge, the scroll attempt will instantly trigger the onPress/onLongPress method and break the test.

**To Reproduce**
https://github.com/lapto/demoUnstableScrollDetox

Run example code for iOS to confirm that the code and test work fine for IOS.
Run same code for android to confirm that scrolling fails and onLongPress was triggered instead.

**Expected behavior**
Scrolling should work stable for Android instead of triggering the onPress/onLongPress method.

**Environment (please complete the following information):**
 - Detox: ^12.10.0
 - React Native: 0.59.8
 - Node: 8.11.3
 - Device: Mac
 - OS: MacOS 10.14.4

**Comment by LeoNatan** [comment]
@d4vidi Could this be related to our known bug?

**Comment by d4vidi** [comment]
@LeoNatan which one are you referring to? Anyways I checked - this seems to be an actual bug, at least in RN .59.

**Comment by LeoNatan** [comment]
I meant the blocking RN .59 bug, with the visibility.

**Comment by d4vidi** [comment]
Oh the notorious one. Afraid not :)

**Comment by lapto** [comment]
On the current project i'm working on where we are having the issue we are still on 
```
"react-native": "0.57.7"
"jest": "^24.0.0"  (24.7.1)
"detox": "9.1.2"
```
So its not just for newer version of RN or Detox.

**Comment by d4vidi** [comment]
Update: It appears the bug occurs with long-press callbacks.
