### ISSUE TITLE
Accept Permissions After Log-in Flow 

### ISSUE THREAD

**Issue by BG687** [wix/Detox#1419]
**Is your feature request related to a problem? Please describe.**
It's easy to initialize / launch an app with a set of permissions. But, if you request permissions after log-in, there is no way for the app to accept or deny a permission after it's been launched. 

The tests cannot interact with the permission modals, and they block the tests. The only way to continue is to manually accept or deny the permissions in the sim. 

I've read the many other issues on this topic that have been submitted over the past couple of years, but there doesn't seem to be a clear, generalized solution to this issue. 

**Describe the solution you'd like**
To be able to set permissions at some point after the tests begin. I am testing out Detox locally at the moment, and this seems like a pre-req for getting it working with CI? 

**Describe alternatives you've considered**

**Additional context**
Thank you for your help

**Comment by LeoNatan** [comment]
This is a limitation of the system. The permission notifications, for security reasons, are presented from a system process, and Detox, which runs only in the client process, is unable to interact with. What the `setPermissions` API provides is setting global permissions for your application. Once you set them, they are in effect for the entire duration of your app's lifetime. It shouldn't matter when you request permissions in the client code. You should always set the desired permissions before launching the app. To verify your app's validity, you should test for both permission acceptance and rejection. The only case impossible to test is that the notification prompt is actually presented.
