### ISSUE TITLE
RNN issue with detox

### ISSUE THREAD

**Issue by bruchim** [wix/detox#142]
Running Detox test with react-native-navigation cause push screen to freeze between the push animation and the test failed. 

![screen shot 2017-05-28 at 11 46 06](https://cloud.githubusercontent.com/assets/5859773/26549659/bf8888e8-4482-11e7-9d13-55c2c193a0cc.png)

**Comment by LeoNatan** [comment]
This is a culmination of the async model of RN, a bug in iOS and app logic.

The first two are problematic as they cannot easily be fixed. The suggestion is to only call `focus()`/`becomeFirstResponder` after the view controller presentation has completely finished (the RNN lifecycle event analogous to `viewDidAppear`).

As such, this is not a Detox issue.
