### ISSUE TITLE
Update Mocking Guide 

### ISSUE THREAD

**Issue by MiloszFilimowski** [wix/Detox#1420]
**Is your feature request related to a problem? Please describe.**
This is releated to [this](https://github.com/wix/Detox/blob/master/docs/Guide.Mocking.md).

I believe documentation on the topic of mocking is outdated. I'm quite new to React Native and it took me a while until I figured that [current version of metro](https://facebook.github.io/metro/docs/en/configuration) does not support `rn-cli.config.js` anymore.

**Describe the solution you'd like**
1. It would be great to mention that since some metro version (not sure which one) either `metro.config.js`, `metro.config.json` or metro field in `package.json` should be configured instead. 
2. Add an example that you can put `RN_SRC_EXT` in `package.json` when not using custom session config.
```
  "detox": {
    "configurations": {
      "ios.sim.debug": {
        "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/YourApp.app",
        "build": "RN_SRC_EXT=e2e.js xcodebuild -project ios/YourApp.xcodeproj -scheme YourApp -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build",
        "type": "ios.simulator",
        "name": "iPhone X"
      }
    },
```
3. I also think that it should be mentioned that files should be in the same directory.
4. Make part about `react-native-repackager` less significant as this is only valid for rn < 0.55.

**Additional context**
I don't know how relevant this is for experienced React Native users, but as a newcomer I found it quite confusing.

Hope this sounds reasonable :)

**Comment by LeoNatan** [comment]
Thanks. Feel free to submit a pull request with the updates. Thank you

**Comment by simistern** [comment]
Is this issue still relevant? Happy to help clean up the docs for the mocking page :) 

Are there changes with Detox Next that would affect how mocking would be described here?

**Comment by LeoNatan** [comment]
Hello,

DetoxNext is a native effort, largely, so it shouldn’t affect mocking. Feel free to submit a PR.

Thank you!

**Comment by simistern** [comment]
No problem, are there any open source repos with detox mocks/ code examples (of the device camera, for example) that I can include?

**Comment by ruben00james** [comment]
Please update mocking guide.

**Comment by d4vidi** [comment]
We will get more done soon in #2935, yet I believe that the scope of this issue has already been addressed. @MiloszFilimowski please close the issue if you find the [current mocking guide](https://wix.github.io/Detox/docs/guide/mocking) thorough enough.
