### ISSUE TITLE
Occasional ECONNREFUSED connecting to emulator via telnet

### ISSUE THREAD

**Issue by rotemmiz** [wix/Detox#1427]
**Describe the bug**
Every now and then we get a `ECONNREFUSED 127.0.0.1:23`, trying to connect to the android emulator in the internal CI's.

In the standard case, we expect for the device list to be as follows:
```
List of devices attached
emulator-5554	device
```
...in which case we should connect to the device via the `5554` port rather than via `23`. Yet something happens and we fall back to the `23` default.

As the emulator is listening on `5554` rather than `23`, it is obvious that the telnet connection attempt eventually times out. Hence the problem lies in port lookup code.

**Environment (please complete the following information):**
 - Detox: 12.10.x
 - React Native: *
 - Node:*
 - Device:Android emulator
 - OS: *

**Device and Verbose Detox Logs**
```
detox[17696] ERROR: [EmulatorTelnet.js/TELNET_ERROR] connect ECONNREFUSED 127.0.0.1:23
err: Error: connect ECONNREFUSED 127.0.0.1:23
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)
```

**Comment by noomorph** [comment]
@rotemmiz, in fact, those lines go to stderr:
```
* daemon not running; starting now at tcp:5037
* daemon started successfully
```
So, technically, I see no difference (stdout-wise) between your first and second example.

**Comment by rotemmiz** [comment]
Then maybe its due to the fact that the output is not buffered, and so `stdout` has only one line?
`List of devices attached`

**Comment by noomorph** [comment]
@rotemmiz, not likely. Exec waits till the app termination. Why are you sure it has to do with "when daemon starts"? I could not reproduce this issue by just doing what you described in the steps to reproduce.

**Comment by d4vidi** [comment]
@noomorph I've verified what you're saying, indeed you are right. Which means we don't know the cause for telnet issues but we do know they seem to pop up every now and then.
Please review my PR which aims at collecting more info rather than fixing this.

**Comment by d4vidi** [comment]
@noomorph @rotemmiz I've retrofitted the description to fit better to what we know now.

**Comment by noomorph** [comment]
Please open then :)

**Comment by d4vidi** [comment]
@rotemmiz @noomorph I haven't seen instances of this error for quite a while now. Am I the only one?

**Comment by mglaze** [comment]
Having this issue in our repo as well, but it's not intermittent. I'm able to reproduce and repeat the issue using the `demo-react-native` example in the Detox Repo. Output is below.

Detox: 14.0.0
React Native: 0.59.9
Node: 11.13.0
Device: Android emulators (Nexus 5X API 26, Pixel 3 XL API 28)
OS: *
 
`detox build` - Successful
`npm run test:android-debug` - Fails

```
detox[63494] DEBUG: [exec.js/EXEC_SUCCESS, #1] List of devices attached
emulator-5554   device


detox[63494] ERROR: [EmulatorTelnet.js/TELNET_TIMEOUT] 
detox[63494] ERROR: [DetoxExportWrapper.js/DETOX_INIT_ERROR] 
 Error: response not received
    at Timeout.setTimeout [as _onTimeout] (/Users/xx/Sites/mobile/Detox/examples/demo-react-native/node_modules/telnet-client/lib/index.js:150:47)
    at listOnTimeout (internal/timers.js:535:17)
    at processTimers (internal/timers.js:479:7)
detox[63494] DEBUG: [DetoxServer.js/DISCONNECT] role=tester, sessionId=57188056-45ea-4b08-063b-f195b5bdcb00
detox[63494] DEBUG: [DetoxServer.js/WS_CLOSE] Detox server connections terminated gracefully
  1) "before all" hook in "{root}"

  0 passing (2s)
  1 failing

  1) "before all" hook in "{root}":
     Error: response not received
      at Timeout.setTimeout [as _onTimeout] (node_modules/telnet-client/lib/index.js:150:47)
      at listOnTimeout (internal/timers.js:535:17)
      at processTimers (internal/timers.js:479:7)
```

**Comment by d4vidi** [comment]
Not exactly the same issue b/c the connection does not get refused for trying to connect to port `23` (rather than the actually open port - `5554` according to your logs).
If this is consistent may I suggest to just load the terminal and try to telnet into it yourself via command line. On linux it's super easy, on a mac, you can `brew install telnet`.
