### ISSUE TITLE
Upstream React Native IdlingResource?

### ISSUE THREAD

**Issue by bootstraponline** [wix/Detox#144]
Thoughts on adding React Native idling resource support to EarlGrey upstream?

- https://github.com/google/EarlGrey/issues/518

**Comment by talkol** [comment]
It's a good idea, we've added some interesting code to EarlGrey itself using categories

Let's see what they think

@LeoNatan what do you think?

**Comment by LeoNatan** [comment]
I don’t see an issue in general. Right now, there is a known limitation in some of our own idling resources, where we only support one bridge. For an upstream submission, these need to be ironed out. Other than that, it’s a question of politics, if Google want to potentially dirty up Earl Grey with Facebook’s custom license.

**Comment by bootstraponline** [comment]
You should join the EarlGrey slack if you haven't already. In general there's interest in supporting react-native.

**Comment by LeoNatan** [comment]
I think it’s too early. Let’s first see what engagement we get on the Earl Grey issue. If there is interest, we will work with the Earl Grey maintainers to make any necessary changes they see fit.

**Comment by LeoNatan** [comment]
With the pending release of EG2.0 and not sure how that will play out inside Detox, I am closing this issue for now. There has not been much of a community engagement regarding the up-streaming of the idle resources.
