### ISSUE TITLE
Regex For Matchers

### ISSUE THREAD

**Issue by ReshmiCode** [wix/Detox#1441]
**Is your feature request related to a problem? Please describe.**
When searching for an element with long text, I'd like to keep the test file less cluttered.

**Describe the solution you'd like**
Matchers such as by.text are able to take regular expressions or parts of the desired text.

**Comment by LeoNatan** [comment]
This will probably not work with the framework we use on iOS (Earl Grey). Creating the matches on our own in order to support this is not something we will do.

**Comment by LeoNatan** [comment]
As you can see, we use Earl Grey here:
https://github.com/wix/Detox/blob/master/detox/ios/Detox/GREYMatchers%2BDetox.m
and sadly there are no matchers for regular expressions:
https://github.com/google/EarlGrey/blob/master/EarlGrey/Matcher/GREYMatchers.h

**Comment by asafkorem** [comment]
This might be relevant today, I started a new issue https://github.com/wix/Detox/issues/3366.
