### ISSUE TITLE
Not executing tests while permission dialog is visible.

### ISSUE THREAD

**Issue by witalobenicio** [wix/Detox#1442]
**Describe the bug**
I'm using OneSignal to handle my RN app notifications, and I show request permission dialog right before the `Navigation.startSingleScreen()` method from `react-native-navigation`.
When I'm with the dialog visible on screen, my tests do not run. If I manually click on accept, my tests run ok.

**To Reproduce**

- [YES] I have tested this issue on the latest Detox release and it still reproduces

**Expected behavior**
Expect to run tests

**Environment (please complete the following information):**
 - Detox: 12.9.0
 - React Native: 0.59.9
 - Node: 10.15.2
 - Device: iOS Simulator iPhone X

**Comment by noomorph** [comment]
Have you tried launching your app with [permissions](https://github.com/wix/Detox/blob/master/docs/APIRef.DeviceObjectAPI.md#2-set-runtime-permissions)?

**Comment by witalobenicio** [comment]
@noomorph how can I do that?

**Comment by witalobenicio** [comment]
@noomorph it didn't work. Because my app is launched, dialog permission is shown, then if I allow, my tests init and `device.launchApp` is called.

**Comment by rotemmiz** [comment]
You can control app initialization on init with 

```js
await detox.init(config, {launchApp: false});
```

https://github.com/wix/Detox/blob/master/docs/APIRef.DetoxObjectAPI.md#controlling-first-app-intialization
