### ISSUE TITLE
App is not installed on simulator in detox 12.11.0

### ISSUE THREAD

**Issue by swabbass** [wix/Detox#1456]
**Describe the bug**
Some test suits are failing because of the app isn't installed on the simulator
**To Reproduce**
just run 12.11.0
- [x ] I have tested this issue on the latest Detox release and it still reproduces

**Expected behavior**

**Screenshots**
https://imgur.com/BFFKt3p
https://imgur.com/engzM4g
**Environment (please complete the following information):**
 - Detox:12.11.0
 - React Native:0.59.0
 - Node:8.12.0
 - Device:Iphone 
 - Xcode:10
 - iOS:12
 - macOS: 10.14

**Device and Verbose Detox Logs**
in screenshots

**iOS Framework Build Logs**
in screenshots

**Comment by LeoNatan** [comment]
Thanks Ward!

Looking at the log, there was no `xcrun simctl install` call at all, which explains why the system complains. Going back to a previous version worked.

**Comment by LeoNatan** [comment]
@noomorph

**Comment by LeoNatan** [comment]
@noomorph This was solved, right? Please close if no longer relevant. Thanks

**Comment by noomorph** [comment]
Resolved via #1467
