### ISSUE TITLE
typeText() performs a long tap

### ISSUE THREAD

**Issue by sergiomap** [wix/Detox#1462]
On Android when I use typeText('text') it performs maybe a long tap because it shows 'paste' before type 'text'. 
I assume that you have some tap interaction behind the typeText that is causing this behavior.

<img width="341" alt="Screenshot 2019-06-19 at 10 03 36" src="https://user-images.githubusercontent.com/7563909/59752108-a648d580-9279-11e9-9844-307f4c806400.png">

**Comment by laurentS** [comment]
I am seeing a similar behaviour with detox `13.0.0` and `13.0.1` on android emulator running on linux.
react-native 
It seems to happen before, and sometimes after the actual text entry.

See the screencast below:
![screencast_ok2](https://user-images.githubusercontent.com/1745184/60443930-1a895e80-9c14-11e9-959f-c1f2cfc7b190.gif)

and the corresponding code:

        await expect(element(by.id('signup_screen'))).toBeVisible();
        await element(by.id('signup_screen')).scroll(150, 'down');
        await element(by.id('signup_username')).typeText(username);
        await element(by.id('signup_email')).typeText(email);
        await element(by.id('signup_screen')).scroll(100, 'down');
        await element(by.id('signup_password')).typeText(password);
        await element(by.id('signup_password')).tapReturnKey();
        await element(by.id('signup_screen')).scrollTo('bottom');
        await element(by.id('signup_button')).tap();


```
  React Native Environment Info:
    System:
      OS: Linux 4.15 Linux Mint 18 (Sarah)
      CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
      Memory: 164.88 MB / 11.63 GB
    Binaries:
      Node: 8.16.0 - /usr/bin/node
      Yarn: 1.16.0 - ~/.yarn/bin/yarn
      npm: 6.4.1 - /usr/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 19, 23, 25, 26, 27, 28
        Build Tools: 19.1.0, 23.0.1, 23.0.3, 24.0.1, 25.0.0, 25.0.1, 25.0.2, 26.0.1, 27.0.3, 28.0.2, 28.0.3
        System Images: android-19 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.58.0 => 0.58.0
```

**Comment by sergiomap** [comment]
yes, is the same behavior that I'm having.

btw, which emulator are you using, genymotion or android studio? It seems very quick compared with mine.

**Comment by laurentS** [comment]
This was made using android sdk emulator version `27.3.10-4969155 (KVM 12.0.0) - android 8.0 (Oreo) API 26`. Details of my machine are in the comment above. The screencast is roughly the speed I'm seeing on screen

**Comment by d4vidi** [comment]
Funny, I was not aware of that my findings in #1495 have already been submitted as an issue... :) Taking care of it now.

**Comment by d4vidi** [comment]
Please try again with Detox `13.3.0`.
