### ISSUE TITLE
Unable to select the date from the ios native date picker using detox 

### ISSUE THREAD

**Issue by karthkv** [wix/Detox#1468]
![Ios Native calender-min](https://user-images.githubusercontent.com/15605337/59917853-af37d380-9440-11e9-8193-180e75b4717f.png)

I had tried with the below code but its not working....!
> await element(by.text('Mar')).replaceText('Jun')
> await element(by.text('29')).replaceText('04')
> await element(by.text('2001')).replaceText('2000')

Can any one help on the below calendar to select the date, using #detox

Have explored on the element type and setTocoloumn with the below links but didn't worked.

https://github.com/wix/detox/issues/798
https://github.com/wix/detox/issues/778

Thanks in Advance....!

**Comment by noomorph** [comment]
Look into Detox e2e tests suite, there is an example on how to work with the picker

**Comment by karthkv** [comment]
Yeah it worked....Thank you..!
