### ISSUE TITLE
docs: deprecated relaunchApp is used in examples

### ISSUE THREAD

**Issue by ReshmiCode** [wix/Detox#1479]
**Describe the bug**
Following https://github.com/wix/Detox/blob/master/docs/APIRef.MockingOpenFromURL.md, when I add `await device.relaunchApp({ url: link });` I get the error `Property 'relaunchApp' does not exist on type 'Device'. Did you mean 'launchApp'?` Is the docs incorrect?

**To Reproduce**

- [x] I have tested this issue on the latest Detox release and it still reproduces

**Screenshots**
![Screenshot (105)](https://user-images.githubusercontent.com/16989366/60132709-ae18e600-9761-11e9-8d82-716501cff518.png)

**Environment (please complete the following information):**
Detox: 12.11.0
React Native: 0.59.8
Node: 10.15.3

**Comment by LeoNatan** [comment]
`relaunchApp` is a deprecated API and should not be used. That being said, it is still in the code https://github.com/wix/Detox/blob/dde00f8bf1975b6e7a26d83801bf4c15ee9a7c75/detox/src/devices/Device.js#L126 and is tested as working in our test suites. It's a problem on your end.

**Comment by noomorph** [comment]
In other words. We should update docs to minimize examples with deprecated APIs.

**Comment by LeoNatan** [comment]
That would be good. 
I see in the screenshot that it’s TypeScript. Not sure who generates these bindings, but most likely they have decided not to include the deprecated API.
