### ISSUE TITLE
Rerun Failed Tests Option

### ISSUE THREAD

**Issue by ReshmiCode** [wix/Detox#1488]
**Is your feature request related to a problem? Please describe.**
Some tests on occasion can be flaky.

**Describe the solution you'd like**
A command that reruns just the failed tests.

**Comment by noomorph** [comment]
I believe this is out of the scope of Detox, since this feature request asks for extending a test runner functionality. Anyway, the idea sounds awesome, just need to get convinced that this is something that indeed Detox-specific.

**Comment by noomorph** [comment]
See also https://mochajs.org/#retry-tests

**Comment by LeoNatan** [comment]
This indeed sounds like a feature of the test runner, rather than Detox.
