### ISSUE TITLE
Detox CLI does not error on unknown commands

### ISSUE THREAD

**Issue by LeoNatan** [wix/Detox#149]
For instance,

`detox start-server` instead of `detox run-server`. Should error out and print the usage. Instead, it just silently fails.

**Comment by noomorph** [comment]
Fixed in `detox@12.1.x`.

![Screenshot from 2019-04-11 13-52-45](https://user-images.githubusercontent.com/1962469/55951986-2c84e200-5c61-11e9-9cea-246323ab194a.png)

**Comment by LeoNatan** [comment]
❤
