### ISSUE TITLE
iOS + Android detox.init() hangs

### ISSUE THREAD

**Issue by mtt87** [wix/Detox#1503]
**Describe the bug**
Detox hangs at `detox.init(config)` so test globals like `element`, `device` etc are not defined.

The last log line is
```
detox[40338] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=testee not connected, cannot fw action (sessionId=f0510638-23ce-2146-cd0a-27fc25b0effb)
```

```js
beforeAll(async () => {
  console.log('BEFORE INIT');
  await detox.init(config);
  console.log('AFTER INIT');
});
```

`AFTER INIT` never happens.

I tried to run `detox test --debug-synchronization 200` then with `400` and `500` and it worked a few times, completely random.     

**To Reproduce**

- [x] I have tested this issue on the latest Detox release and it still reproduces

This happens on a newly created project so quite easy to reproduce.
`react-native init bug_detox --version react-native@0.59.9`
Then follow the detox guide.

**Expected behavior**
Should work 😄 

**Environment (please complete the following information):**
 - Detox: 13.0.2 (but I tested also 12.x.x)
 - React Native: 0.59.9
 - Node: 10.16.0
 - Device: iPhone X simulator
 - Xcode: 10.2.1
 - iOS: 12.2
 - macOS: 10.14.5

**Device and Verbose Detox Logs**
```
detox[40338] DEBUG: [exec.js/EXEC_CMD, #6] SIMCTL_CHILD_DYLD_INSERT_LIBRARIES="/Users/masti/Library/Detox/ios/d1b2c0e3c73310f29990b6226de64d67b9acc4ce/Detox.framework/Detox" /usr/bin/xcrun simctl launch 665D8016-8B94-49EA-8F3D-343DD09B4EF8 org.reactjs.native.example.bug-detox --args -detoxServer "ws://localhost:57966" -detoxSessionId "f0510638-23ce-2146-cd0a-27fc25b0effb"
detox[40338] DEBUG: [exec.js/EXEC_TRY, #6] Launching org.reactjs.native.example.bug-detox...
detox[40338] TRACE: [exec.js/EXEC_SUCCESS, #6] org.reactjs.native.example.bug-detox: 40395

detox[40338] DEBUG: [exec.js/EXEC_CMD, #7] /usr/bin/xcrun simctl get_app_container 665D8016-8B94-49EA-8F3D-343DD09B4EF8 org.reactjs.native.example.bug-detox
detox[40338] TRACE: [exec.js/EXEC_SUCCESS, #7] /Users/masti/Library/Developer/CoreSimulator/Devices/665D8016-8B94-49EA-8F3D-343DD09B4EF8/data/Containers/Bundle/Application/F762B286-0FEB-4761-9547-FA0395BA0C21/bug_detox.app

detox[40338] INFO:  [AppleSimUtils.js] org.reactjs.native.example.bug-detox launched. To watch simulator logs, run:
        /usr/bin/xcrun simctl spawn 665D8016-8B94-49EA-8F3D-343DD09B4EF8 log stream --level debug --style compact --predicate 'processImagePath beginsWith "/Users/masti/Library/Developer/CoreSimulator/Devices/665D8016-8B94-49EA-8F3D-343DD09B4EF8/data/Containers/Bundle/Application/F762B286-0FEB-4761-9547-FA0395BA0C21/bug_detox.app"'
detox[40395] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onLaunchApp({ bundleId: 'org.reactjs.native.example.bug-detox',
  deviceId: '665D8016-8B94-49EA-8F3D-343DD09B4EF8',
  launchArgs:
   { detoxServer: 'ws://localhost:57966',
     detoxSessionId: 'f0510638-23ce-2146-cd0a-27fc25b0effb' },
  pid: 40395 })
detox[40338] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"isReady","params":{},"messageId":-1000}
detox[40338] TRACE: [DetoxServer.js/MESSAGE] role=tester action=isReady (sessionId=f0510638-23ce-2146-cd0a-27fc25b0effb)
detox[40338] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=testee not connected, cannot fw action (sessionId=f0510638-23ce-2146-cd0a-27fc25b0effb)
```

**Comment by LeoNatan** [comment]
Please follow the steps here:
https://github.com/wix/Detox/blob/master/docs/Troubleshooting.Synchronization.md#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much

And post the log here. Thanks

**Comment by mtt87** [comment]
@LeoNatan sorry 😢 I'm not sure I've added that param correctly as I can't find anywhere `launchArgs` / `launchApp()`, could you guide me in the right direction?

I've added it here but doesn't seem to produce what we expect
![Screenshot 2019-07-04 at 14 48 24](https://user-images.githubusercontent.com/2150927/60671366-d8a62580-9e6a-11e9-943c-9f8ad12c6a06.png)

What I'm doing is adding that param then
```
detox build -c iPhoneX.debug
detox test -c iPhoneX.debug --debug-synchronization 200  
```
And in another terminal window
```
$ xcrun simctl spawn booted log stream --level debug --style compact --predicate "category=='EarlGreyStatistics'"
Error from getpwuid_r: 0 (Undefined error: 0)
Filtering the log data using "category == "EarlGreyStatistics""
```
Nothing appears

**Comment by LeoNatan** [comment]
Please search around for "EarlGreyStatistics" or "detoxPrintBusyIdleResources". It has been explained before.

**Comment by mtt87** [comment]
Took me some time to find it, I'm gonna leave it here for future reference in case other people are searching for it and close the issue and eventually make a PR to improve docs.
In the end it was related to a network request being stuck so not a problem with Detox, thanks for pointing me in the right direction.

Edit `/e2e/init.js`
```js
beforeAll(async () => {
  await detox.init(config, { launchApp: false });
  await device.launchApp({
    newInstance: true,
    launchArgs: { 'detoxPrintBusyIdleResources': 'YES' }
  });
});
```

**Comment by LeoNatan** [comment]
Thanks
