### ISSUE TITLE
Mock distance is not getting updated until you manually trigger it 

### ISSUE THREAD

**Issue by yogeshthanvi** [wix/Detox#1505]
**Describe the bug**
In my application there is list of locations gets populated and show the distance from the current location. When i use detox the distance never get populated until i reset the location mocking of simulator (Debug > Locations > apple or any ) using simulator menu. 
**To Reproduce**

demo cant be provided u can take example of Airbnb 

If possible, please provide a small demo project that reproduces the issue, or attach a video with the reproduction - this would be very appreciated.

**Expected behavior**
As per simulator settings it should show the distance 

**Environment (please complete the following information):**
 - Detox: 13.0.1
 - React Native:0.59
 - Node:v10.15.1
 - Device: iphone X 
 - Xcode: 11
 - iOS: 12.1
 - macOS: Mojave

**Comment by LeoNatan** [comment]
I don't see a bug here. It's a problem in your mocking. If you need a real location, use [`device.setLocation()`](https://github.com/wix/Detox/blob/master/docs/APIRef.DeviceObjectAPI.md#devicesetlocationlat-lon).
