### ISSUE TITLE
Scroll very slow on Android

### ISSUE THREAD

**Issue by sergiomap** [wix/Detox#1507]
I'm doing a waitFor an element while I'm scrolling on a list. I use this behavior and the same code for iOS and Android, in iOS the scroll runs smoothly but on Android it takes much more time (4 or 5 times more).
I already tried swipe and scrollTo but is the same thing. If I do it manually on the emulator it runs fine, so It seems a Detox problem for Android.

The code that I'm using to scroll:
`    await waitFor(element(by.text('foobar'))).toBeVisible().whileElement(by.id('list')).scroll(600, 'down', NaN, 0.96);
`

**Comment by d4vidi** [comment]
@sergiomap please try this again with `13.1.0`, which has an improved scrolling implementation. Thanks!

**Comment by sergiomap** [comment]
much better, great work guys!
thanks

**Comment by d4vidi** [comment]
Great news :-)
