### ISSUE TITLE
replaceText does not trigger TextInput's onChangeText event

### ISSUE THREAD

**Issue by irrigator** [wix/detox#151]
typeText works fine but I need to input some non-English text, so I use replaceText. The problem is that it does not trigger onChangeText event. Anyone else experienced this problem?

**Comment by LeoNatan** [comment]
This is an issue with Earl Grey, the underlying infrastructure we are using on iOS. https://github.com/google/EarlGrey/issues/31

**Comment by LeoNatan** [comment]
Closing this for now. You can track Earl Grey's progress in the issue linked above.

**Comment by Aaaaaashu** [comment]
+1
is there another way to solve the issue?

**Comment by Aaaaaashu** [comment]
```js
await id('textarea').replaceText(content)
await id('textarea').clearText()
await id('textarea').replaceText(content)
```

After replaceText, cleanText and then repalceText can trigger TextInput's onChangeText event.
cc @irrigator
