### ISSUE TITLE
Change visibility percentage in toBeVisible()

### ISSUE THREAD

**Issue by sergiomap** [wix/Detox#1524]
I would like to be able to change the visibility percentage of an element.

I know that toBeVisible() will return true if the visibility is 75% or greater but in some cases I need that the element be 100% visible, otherwise I cannot tap the element.

**Comment by rotemmiz** [comment]
You can potentially expose https://github.com/wix/Detox/blob/master/detox/src/ios/earlgreyapi/GREYMatchers.js#L277 as a new API call.

**Comment by rotemmiz** [comment]
And on Android you'll need to add it as a param (with 75 as default)
https://github.com/wix/Detox/blob/f63424ccbcb0224f51674c5c0e3c7bc73122d721/detox/android/detox/src/main/java/com/wix/detox/espresso/DetoxMatcher.java#L75

**Comment by LeoNatan** [comment]
In a future release to come soon, visibility will no longer be calculated by percentage.
