### ISSUE TITLE
Can I test props value of UI(Component)?

### ISSUE THREAD

**Issue by colorgmi** [wix/Detox#1527]
some thing like `toHaveProps(propName, propValue)`;

e.g.
test WebView source props.

**Comment by LeoNatan** [comment]
This is not possible with Detox.

**Comment by LeoNatan** [comment]
The whole concept of "props" makes no sense in Detox world, because "props" are a JS thing, while Detox runs in native. Creating a mapping of props<->native attributes is not something we are willing to do at this point.
