### ISSUE TITLE
Android performance testing

### ISSUE THREAD

**Issue by jtart** [wix/Detox#1529]
[Apologies if this is a duplication but I could not find an issue open for this]

The docs state that the `--record-performance` API is only available for iOS. Is there thoughts to implement the API for Android? If not, why not?

Furthermore, if there is aims to do so, what steps would be required to implement such?

**Comment by noomorph** [comment]
Unfortunately, we have limited time and human resources, that's mostly the reason why API is not available for Android. To add one, we need:

1) Decide which instrumentation tool to use
2) Develop integration with it (namely, a new artifact plugin in Detox)

**Comment by LeoNatan** [comment]
Detox Instruments is iOS only for now. https://github.com/wix/DetoxInstruments/issues/35
