### ISSUE TITLE
Failure on fbsimctl install

### ISSUE THREAD

**Issue by vspedr** [wix/detox#153]
I managed to work around this issue, so I thought it would be nice to leave it here in case someone runs into the same problem :)

I followed through the "Getting Started" guide and everything worked nicely until `detox test` failed with the following message, along with a bunch of other `Class foo is implemented in both ...` warnings.   
```
  1)  "before all" hook:
     Error: Command failed: fbsimctl --json 546896F6-37A1-4552-B4F2-178D49363585 install /Users/user/Projects/myapp/ios/build/Build/Products/Debug-iphonesimulator/myapp.app
```

I copied the complete `fbsimct ...` command and tried running it separately, which gave me another message:
```
{"event_type":"discrete","timestamp":1496770868,"subject":"Error Domain=com.facebook.FBSimulatorControl Code=0 \"Simulator does not support any of the architectures ([x86_64]) of the executable at \/Users\/user\/Projects\/myapp\/ios\/build\/Build\/Products\/Debug-iphonesimulator\/myapp.app\/myapp. Simulator Archs ([i386])\" UserInfo={NSLocalizedDescription=Simulator does not support any of the architectures ([x86_64]) of the executable at \/Users\/user\/Projects\/myapp\/ios\/build\/Build\/Products\/Debug-iphonesimulator\/myapp.app\/myapp. Simulator Archs ([i386])}","event_name":"failure"}
```

The solution: added the following flags to my `xcodebuild` command in detox config:
```
{
  ...
  "build": "xcodebuild ARCHS=i386 ONLY_ACTIVE_ARCH=NO ...
  ...
}
```

**Comment by LeoNatan** [comment]
This looks like an issue on your side. Your project is either configured to only build 64bit binaries, or you have built a debug build with active architecture only, targeting a 64bit simulator, then try to run on a 32bit simulator.
