### ISSUE TITLE
Android Build Has Annotation Dependency Error

### ISSUE THREAD

**Issue by ReshmiCode** [wix/Detox#1534]
**Describe the bug**
With RN 0.60.3 the Android setup for Detox from the docs is causing an issue in the build (while running detox build -c android). Happened on a new React project.

**To Reproduce**

- [x] I have tested this issue on the latest Detox release and it still reproduces

**Environment (please complete the following information):**
 - Detox: 13.1.1
 - React Native: 0.60.3

[androidError.txt](https://github.com/wix/Detox/files/3398344/androidError.txt)

**Comment by elyalvarado** [comment]
As a temporary workaround add the following to your android/app/build.gradle

```
configurations.all {
    resolutionStrategy {
        // TODO: Line below required for Detox since version 12.5
        //   It should removed as soon as the project compiles without it
        force 'androidx.annotation:annotation:1.0.0'
    }
}
```

The issue is that Detox uses version 1.1.0 for android.annotation, while react native itself (or any of your dependencies) uses version 1.0.

**Comment by iheart2code** [comment]
Same issue. Workaround fixed the problem for me. Thanks, @elyalvarado

**Comment by elyalvarado** [comment]
The issue still exists, and shouldn't be closed unless addressed, even if its just a documentation note to warn users having this error

**Comment by elyalvarado** [comment]
The issue still exists, and shouldn't be closed unless addressed, even if its just a documentation note to warn users having this error

**Comment by d4vidi** [comment]
Closing in favor of #1689. Please refer to the [versions support table](https://github.com/wix/Detox/#react-native) for latest info on this.
