### ISSUE TITLE
Tests hang randomly on iOS and throws timeout error

### ISSUE THREAD

**Issue by juandiegombr** [wix/Detox#1536]
**Describe the bug**
When I run the tests, sometimes it finish successfully and sometimes it hangs and throws a timeout error. `Async callback was not invoked`

It also throws a warning:
```
detox[12393] WARN:  [Client.js/PENDING_REQUESTS] App has not responded to the network requests below:
  (id = 4) invoke: {"target":{"type":"Invocation","value":{"target":{"type":"EarlGrey","value":"instance"},"method":"detox_selectElementWithMatcher:","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"GREYMatchers"},"method":"matcherForAccessibilityID:","args":[{"type":"NSString","value":"login_button"}]}}]}},"method":"performAction:","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"GREYActions"},"method":"actionForTap","args":[]}}]}

That might be the reason why the test "UAT_Login Incorrect username" has timed out.
```

The test is visually finished, but detox keeps waiting. Like if detox doesn't know that the test is completed.

**To Reproduce**

- [x] I have tested this issue on the latest Detox release and it still reproduces

1. Running the tests with: detox test -c [configuration] [spec file]

It happens when the tests contains the `.tap()` action

**Expected behavior**
Run the tests with the same result every time they are launched.

**Environment:**
 - Detox: 13.1.1
 - React Native: 0.59.1
 - Node: v10.15.2
 - Device: iPhone 7
 - Xcode: 10.2.1
 - iOS:
 - macOS: 10.14.5

**Device and Verbose Detox Logs**
[logs.txt](https://github.com/wix/Detox/files/3401144/logs.txt)

**Comment by LeoNatan** [comment]
Please follow this guide: https://github.com/wix/Detox/blob/master/docs/Troubleshooting.Synchronization.md#lower-level-idling-resources-rebug-ios-only

Reproduce and post the result here. Thanks

**Comment by juandiegombr** [comment]
The logs with a failing test (it has the `.tap()` action) are huge. You have them here:
https://drive.google.com/open?id=16MY79ZPErHdxY4FY1OUPXHD_c1wwDip1

To compare, here are the logs with a successful test (without the `.tap()` action).
[log.txt](https://github.com/wix/Detox/files/3402000/log.txt)

**Comment by LeoNatan** [comment]
The link provided requires permissions. Can you please upload here: https://gist.github.com/

**Comment by juandiegombr** [comment]
Sorry, It is impossible to upload the file there. I gave permissions to the file on drive. Try it again with this link.

https://drive.google.com/file/d/16MY79ZPErHdxY4FY1OUPXHD_c1wwDip1/view?usp=sharing

**Comment by lapto** [comment]
@LeoNatan Sounds very similar to the issue I'm having where the App will close it self after detox has launched it when using detox version 13.0.3 or above. This happens on my local machine and 2 other clients and all three works fine with 13.0.2 or lower.
Once the app has been closed, detox will just wait until the test time out and attempt to start the next test suit.

By using the Debugging in Xcode During Detox Tests trick I see that the app crash as 
`void)applicationDidBecomeActive:(UIApplication *)application Thread 1: EXC_BAD_ACCESS (code=2, address=0x7ffeead66ff8)`
after it has been called 34872 times.

I think this is a bug that is introduced in #1511 .

**Comment by LeoNatan** [comment]
@juandiegombr WXAnimatedDisplayLinkIdlingResource is busy, meaning there is an endless animation. Please mock that or stop the animation during testing

@lapto Your issue is followed in #1525. Please see my request there and follow it and provide the log output. Thanks

**Comment by juandiegombr** [comment]
Yes, you are right. It was an animation that was not working properly. It confused me because the error happened sometimes, not always.

Thank you for your attention.

**Comment by LeoNatan** [comment]
Cheers!
