### ISSUE TITLE
Add point to point panning API

### ISSUE THREAD

**Issue by LeoNatan** [wix/detox#154]
For various controls, we need an API that will allow the users to specify two points, and let the system perform a pan/scroll from one point to the other. For instance, a picker needs this to perform selection.

**Comment by LeoNatan** [comment]
Perhaps API should provide two variants; one in point units and one in percentage units.

**Comment by DanielMSchmidt** [comment]
[EarlGrey provides a `swipeSlowInDirectionWithStartPoint` function](http://google.github.io/EarlGrey/Functions.html#/c:@F@grey_swipeSlowInDirectionWithStartPoint). Could this be an option for us?

**Comment by DanielMSchmidt** [comment]
Did a bit more research, this EarlGrey utility looks exactly like the thing we need: [GREYPathGestureUtils](https://github.com/google/EarlGrey/blob/master/EarlGrey/Action/GREYPathGestureUtils.m#L274-L390), it is used e.g. in the [Swipe Action](https://github.com/google/EarlGrey/blob/master/EarlGrey/Action/GREYSwipeAction.m#L127-L130), which is used by [`scrollInDirectionWithStartPoint`](https://github.com/google/EarlGrey/blob/master/EarlGrey/Action/GREYActions.m#L656-L664).

My idea would be to internally extend EarlGrey to support "swipe from here to there in x seconds". Does this sound like a good idea to you? Would be willing to try a PR ;)

**Comment by LeoNatan** [comment]
Sounds good. If you can expose that method to the JS world, it would be lovely.

**Comment by DanielMSchmidt** [comment]
I will have a look at this next weekend ;) Would really help me to test my drawer library.

**Comment by rotemmiz** [comment]
[This PR](https://github.com/wix/detox/pull/178) will solve it.

**Comment by jsierles** [comment]
Is this supported now?

**Comment by LeoNatan** [comment]
Sorry, not yet.

**Comment by jsierles** [comment]
OK, thanks. Is there a workaround for testing a Picker?

**Comment by LeoNatan** [comment]
Pickers are looked at right now for a proper fix, but I don't have a timeline currently. We also found another issue which may need this point-to-point API, so this may come soon too. Again, cannot say when.

**Comment by jsierles** [comment]
OK, thanks for the update. Can you recommend a way to simulate the behavior of the picker directly? Just so one can move forward within the app.

**Comment by LeoNatan** [comment]
You can try mocking the screen or functionality for the tests. Not optimal but I can't think of something else right now. Maybe @rotemmiz may have an idea?

**Comment by LeoNatan** [comment]
This is being discussed seriously in #589. Closing this issue in favor of that one.
