### ISSUE TITLE
Spawn emulator hangs on node 12.1.0

### ISSUE THREAD

**Issue by rotemmiz** [wix/Detox#1546]
**Describe the bug**
Spawning an emulator hangs on node 12.1.0
```
detox[2920] DEBUG: [Emulator.js/SPAWN_CMD] /usr/local/share/android-sdk/emulator/emulator -verbose -no-audio -no-window @Nexus_5X_API_28 -gpu host
Too long with no output (exceeded 10m0s)
```

**To Reproduce**
Use node 12.1.0, make sure the emulator is shutdown, and let Detox try to boot it.

Wer have a few examples on our tests with CircleCI: https://circleci.com/gh/wix/Detox/91

**Environment (please complete the following information):**
 - Detox:latestr
 - React Native:*
 - Node:12.1.0
 - Device:Android Emulator
 - OS: macOS 10.14.5 (might also happen on Linux/Windows)

**Comment by LeoNatan** [comment]
It's peculiar that this is only reproduced on Android. Maybe more issues exist under the surface.

**Comment by rotemmiz** [comment]
It's a special case where we detach the a spawned process, and use `child-process-promise`. Maybe there's an issue with that lib. It can be easily replaced with node's `child_process` implementation.

https://github.com/wix/Detox/blob/master/detox/src/devices/android/Emulator.js#L65

**Comment by d4vidi** [comment]
@rotemmiz weird, this works in debug mode

**Comment by d4vidi** [comment]
Well so far the issue doesn't appear to be in the child process spawning. Have a look at this: https://github.com/nodejs/node/issues/28882. I think we need to find a different way to `tail`...
