### ISSUE TITLE
iOS test-run fails to run tests

### ISSUE THREAD

**Issue by henrymoulton** [wix/Detox#1552]
**Describe the bug**
Very similar behaviour as #1545, and searching through issues seems a similar log appeared in #673, however note there is the `launchApp` API being used:

```
export const launchApp = async () => {
  // Reinstall app to clear keychain and ensure user is logged out
  await device.launchApp({
    delete: true,
    permissions: { notifications: 'YES', calendar: 'YES' }
  });
};


it('should successfully update all their details', async () => {
      await launchApp();
      ...
      // test steps
      ...
}
```

Config: 

```
beforeAll(async () => {
  await detox.init(config.detox, { launchApp: false });
});

"ios.sim.release": {
        "binaryPath": "ios/build/Build/Products/Release-iphonesimulator/RedactedApp.app",
        "build": "xcodebuild -project ios/RedactedApp.xcodeproj -scheme RedactedApp -configuration Release-Staging -sdk iphonesimulator -derivedDataPath ios/build -UseModernBuildSystem=NO",
        "type": "ios.simulator",
        "name": "iPhone 8"
      },
```

**To Reproduce**

- [x] I have tested this issue on the latest Detox release and it still reproduces

What's strange is that there was one occurrence of the test run where it worked, this was after having booted the app on my machine using xCode.

**Environment (please complete the following information):**
 - Detox: ^13.2.0
 - React Native: 0.59.3
 - Node: v10.16.0
 - Device: iPhone 8
 - Xcode: 10.3
 - iOS: 12.4
 - macOS: 10.14.6

**Device and Verbose Detox Logs**

[Detox Log - Github Gist](https://gist.github.com/henrymoulton/7fce0e66bd4cc0e65997586144c733ba)

**Comment by LeoNatan** [comment]
This is the same issue as #1545. Please provide your Xcode log as requested on that issue.
