### ISSUE TITLE
Being able to type text with no element

### ISSUE THREAD

**Issue by rvera** [wix/Detox#1556]
The app I'm working on uses 'masked inputs', ie, there's a hidden input element to capture the input from a user, but uses a different view to display a formatted value.

Currently there doesn't seem to be a way to send input to this hidden input since the `element` selector needs a visible element to focus and we can't send text without an input.

**Describe the solution you'd like**
I'd like to be able to send text with the currently open keyboard. Without the need to specify an element.

**Describe alternatives you've considered**
Changing the behavior of my app for testing and making these visible. But that partially defeats the purpose of e2e testing/

Thanks

**Comment by LeoNatan** [comment]
What stops you from selecting the hidden element and typing on that?

**Comment by rvera** [comment]
Hi @LeoNatan the problem seems to be because the element is hidden (opacity 0 and behind another view). The error I get is:

`Error: No views in hierarchy found matching: (with tag value: is "masked_input" and view has effective visibility=VISIBLE)`

I can confirm this element exists and has the correct `testID` attribute.

**Comment by LeoNatan** [comment]
Is this on Android or iOS? I don't think there is a visibility requirement for typing on iOS, but I could be wrong.

**Comment by rvera** [comment]
This is Android. 

I can't comment on iOS, I've unable to properly setup detox for iOS. Getting the mysterious `Signal 11` error on start up, but that's another issue.
