### ISSUE TITLE
[DOCS] Broken link in .../docs/Introduction.HowDetoxWorks.md

### ISSUE THREAD

**Issue by KarinaDavtyan** [wix/Detox#1558]
Hi  👋 
The link is broken in https://github.com/wix/Detox/blob/master/docs/Introduction.HowDetoxWorks.md

In the last line [mermaid](http://knsv.github.io/mermaid/#mermaid) returns 404. 
the link should be http://knsv.github.io/mermaid/#/

**Comment by LeoNatan** [comment]
Hello,

Thank you for bringing this to our attention. I've fixed the link
