### ISSUE TITLE
Support for Android with RN 0.60.4

### ISSUE THREAD

**Issue by amadeu01** [wix/Detox#1559]
I’m trying to test using RN 0.60 but after the first tap the screen stops reacting to any UI attempt of interaction. I saw at the readme of the project that for Android builds the react native at 0.60 have not been tested yet. So, is there any known issue with android at this version of react ?

**Comment by amadeu01** [comment]
@LeoNatan if you have the time to help me on this https://stackoverflow.com/questions/57255237/after-first-tap-ui-doesnt-respond-to-anything

**Comment by amadeu01** [comment]
It seems to be related to [react-navigation](https://reactnavigation.org/en/) I just updated it to the latest version. And, the test came back working again.

**Comment by LeoNatan** [comment]
Great!

**Comment by LeoNatan** [comment]
If you found a solution, please answer your SO question so other people are aware.
