### ISSUE TITLE
Allow to disable hierarchy

### ISSUE THREAD

**Issue by Vojow** [wix/Detox#1560]
**Is your feature request related to a problem? Please describe.**
When a couple of tests or whole test suite fails due to the error console or log file from CI is overflooded with the printed hierarchy and in more complex apps or parts of apps this hierarchy can be quite big which results in an unreadable mess. 

**Describe the solution you'd like**
Allow us to pass the param to disable the print of hierarchy for better readability in whole test suites runs. 

**Describe alternatives you've considered**
We can use the disable hierarchy for the whole test suite run and enable it when we debug the failed tests when it's useful to have.

**Comment by LeoNatan** [comment]
This has been discussed in the past and has been decided against. Please use the search function.

**Comment by Vojow** [comment]
Yes, I found these issues already, before writing the suggestion but I totally disagree with you. Wanted to add some new air into the discussion. Why don't you want to add more freedom to the framework? This hierarchy display is really unneeded to be displayed in the main console if we need to stick with it, it would be more appreciated as another artifact than a wall of text in a test run. Recently you improved the test output by adding the inline reporter, but we can't appreciate that because hierarchy destroys whole test output.
