### ISSUE TITLE
redirect all logs to stderr so stdout can be parsed

### ISSUE THREAD

**Issue by cs01** [wix/Detox#1562]
**Is your feature request related to a problem? Please describe.**
I'm running detox with jest and the --json flag. At the end of the test a json summary is printed, and I want to parse that summary as valid JSON.

**Describe the solution you'd like**
All logs directed to stderr so stdout can have predictable, parsable output written to it.

**Additional context**
[This call](https://github.com/wix/Detox/blob/5ecec74910b7704c5f1f6ded6ac1e114267b7d45/detox/src/client/AsyncWebSocket.js#L26) is an example of a detox logging call that writes to stdout instead of stderr.

Example stdout:
```
{"numFailedTestSuites":1,"numFailedTests":1,"numPassedTestSuites":0,,"wasInterrupted":false}detox[47082] ERROR: [AsyncWebSocket.js/WEBSOCKET_ERROR] caught error: Error: connect ECONNREFUSED 127.0.0.1:57676
  err: Error: connect ECONNREFUSED 127.0.0.1:57676
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
```

**Comment by LeoNatan** [comment]
@noomorph @rotemmiz What was the command line tool you use to parse logs? I think the tool can be used to filter these messages.

**Comment by noomorph** [comment]
@cs01, cheers for your excellent observation! Never bothered to look what `bunyan-debug-stream` uses by default, but anyway `stderr` is a much appropriate place indeed, so I'll happy to forward logs to the place they belong via #1569 .
