### ISSUE TITLE
Running `detox-cli` from project `node_modules` causes an error

### ISSUE THREAD

**Issue by colinramsay** [wix/detox#157]
```
yarn add detox-cli --dev
yarn run detox
```

This results in:

```
node_modules/.bin/detox: fork: Resource temporarily unavailable
```

I appreciate this might be something local to my machine, but is there any reason why this general approach wouldn't work?

**Comment by rotemmiz** [comment]
detox-cli is a convenience module, it should be installed globally to be available for as a binary in your command line.
`yarn global add detox-cli`

**Comment by colinramsay** [comment]
Gotcha, thanks.
