### ISSUE TITLE
Detox is getting stuck when trying to build iOS

### ISSUE THREAD

**Issue by SMJ93** [wix/Detox#1570]
**Describe the bug**

Since updating to the latest when running `detox build` the build gets stuck at this point:

```
+ [[ Debug = *Debug* ]]
+ [[ ! iphonesimulator == *simulator ]]
+ [[ -n '' ]]
+ case "$CONFIGURATION" in
+ [[ iphonesimulator == *simulator ]]
+ [[ -n '' ]]
+ echo 'Skipping bundling in Debug for the Simulator (since the packager bundles for you). Use the FORCE_BUNDLING flag to change this behavior.'
Skipping bundling in Debug for the Simulator (since the packager bundles for you). Use the FORCE_BUNDLING flag to change this behavior.
+ exit 0
```

**To Reproduce**

- [ /] I have tested this issue on the latest Detox release and it still reproduces

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

Using this configuration:

```
 "ios.sim.debug": {
        "binaryPath": "../ios/build/Build/Products/Debug-iphonesimulator/dealsapp.app",
        "build": "xcodebuild -workspace ../ios/dealsapp.xcworkspace -scheme dealsapp -configuration Debug -sdk iphonesimulator -derivedDataPath ../ios/build",
        "type": "ios.simulator",
        "name": "iPhone 6"
      },
```

**Expected behavior**
It should build as expected

**Environment (please complete the following information):**
 - Detox: 13.3.1
 - React Native: 0.59.10
 - Node: 12.6.0
 - Device: iPhone 5S simulator
 - Xcode: 10.3.0
 - macOS: 10.14.5

Let me know if I can provide any other information that might help!

**Comment by LeoNatan** [comment]
Detox build is a convenience step. It just runs the command provided by you in package.json. The issue lies somewhere in the command.

**Comment by SMJ93** [comment]
@LeoNatan I see, thanks. Where has the change log gone? Trying to find out which version of Detox we should use with RN `0.59.10`

**Comment by LeoNatan** [comment]
You should always use the latest version of Detox, unless you have a specific issue blocking you.

**Comment by SMJ93** [comment]
Found the issue - `node` 🤦‍♂ downgrading to node `v12.3.1` fixed the issue

**Comment by LeoNatan** [comment]
Whaaa
Haha that makes no sense to me. Do you mean some incompatibility with Node and Detox?

**Comment by SMJ93** [comment]
Yeah maybe, i'll try find some time this weekend to investigate further with a blank project, but for us node `12.3.1` works and `12.6.0` does not.
