### ISSUE TITLE
App doesn't start with Detox.framework injected

### ISSUE THREAD

**Issue by trofima** [wix/Detox#1582]
**Describe the bug**

OneApp doesn't start with Detox.framework injected. It hangs for 10s and gets killed.
At the end of the issue description there is the link to the archive on Google Drive

**To Reproduce**

* Install `WixOneApp.app` onto Simulator (iPhone X, 12.4)
* Run the app via Springboard or via command:

```
/usr/bin/xcrun simctl launch <device-id> ent.wix.ios.dev
```

e.g.:

```
/usr/bin/xcrun simctl launch booted ent.wix.ios.dev
```

* See the expected result.

<img width="200" alt="expected" src="https://user-images.githubusercontent.com/1436182/62467596-cb979180-b79c-11e9-89d8-2a3aad2883cc.png">

* Now run app via:

```
SIMCTL_CHILD_DYLD_INSERT_LIBRARIES=<path-to-detox-framework> /usr/bin/xcrun simctl launch <device-id> ent.wix.ios.dev
```

, for example:

```
SIMCTL_CHILD_DYLD_INSERT_LIBRARIES="/Users/sergeyt/Library/Detox/ios/f7397ad8018984a3eb1d2731e401e1aa5037bbc2/Detox.framework/Detox" /usr/bin/xcrun simctl launch BB88254B-9FCA-46FC-BB08-3E6E7849AB4C ent.wix.ios.dev
```

* It will be stuck on logo screen. Actual result:

<img width="200" alt="actual" src="https://user-images.githubusercontent.com/1436182/62467559-b4f13a80-b79c-11e9-96ba-070956f1aa23.png">

**Environment (please complete the following information):**
 ```
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      Memory: 338.41 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.3.1 - ~/.nvm/versions/node/v12.3.1/bin/node
      Yarn: 1.6.0 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v12.3.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
      Detox: 13.3.3 - node_modules/.bin/detox
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
```

**Device and Verbose Detox Logs**
**iOS Framework Build Logs**

See in the [archive](https://drive.google.com/open?id=1LhbTZQaD2BlEN0YvG165O87MXDG5SQuY)

**Comment by LeoNatan** [comment]
@trofima Any news on the internal incompatibility between Xcode versions? Did you test?
