### ISSUE TITLE
Platform.isTesting affects Animated values

### ISSUE THREAD

**Issue by LukaszK88** [wix/Detox#1585]
**Describe the bug**
Build and tests are running fine but,
when running test build Platform.isTesting causes animations to always have value 0 and Animations callbacks are not being called. Which makes me think that Animations are not working at all.

**To Reproduce**
I have followed all setup instructions.

- [x] I have tested this issue on the latest Detox release and it still reproduces

**Expected behavior**
I would expect animations to run as expected considering elements of UI can be based on them

**Environment (please complete the following information):**
 - Detox: 14.0.0
 - React Native: 0.60.4
 - Node: 10.14
 - Device: Emu Pixel API 29
 - OS: Android

**Comment by LukaszK88** [comment]
To overcome this issue I just switch the isTesting flag after install
`sed -i -e 's/constants && constants.isTesting/false/g' node_modules/react-native/Libraries/Utilities/Platform.android.js
`
Probably will do something similar for IOs if there is no other fix.

**Comment by rodrigosfb** [comment]
I have hit this as well and I think understand what is going on. 

When Platform isTesting is on, Animated uses a mock impl that is suited best for unit testing, it is not a mock that works well for e2e testing.

I will avoid Platform.isTesting in my app (while this kind of mock is in rn). If you have a need to using that variable in your app code create your own detox specific one instead.

Note that if you are using the animated module without the mock then be aware that detox will not wait for timers beyond 1.5s, so if you use the delay feature then you may have synchronization issues.

**Comment by andresfgonz** [comment]
So there will be a fix for this?
im facing this issue on adroid devices

**Comment by d4vidi** [comment]
This [newly added logic in RN .60](https://github.com/facebook/react-native/blob/0.60-stable/ReactAndroid/src/main/java/com/facebook/react/modules/systeminfo/AndroidInfoModule.java#L94) seems to be the reason behind this odd behavior. I'm trying to figure out a solution (context is #1689).
