### ISSUE TITLE
Detox Test Suite not running on Android emulator

### ISSUE THREAD

**Issue by nelsonchen5** [wix/Detox#1586]
**Description**
Run detox build -c android.emu.debug && detox test -c android.emu.debug and get red screen with the following error:

facebook::react::Recoverable: Could not open file/data/user/0/com.detoxtest.dev/files/ReactNativeDevBundle.js: No such file or directory

Try the following to fix the issue:
• Ensure that the packager server is running
• Ensure that your device/emulator is connected to your machine and has USB debugging enabled - run 'adb devices' to see a list of connected devices
• Ensure Airplane Mode is disabled
• If you're on a physical device connected to the same machine, run 'adb reverse tcp:8081 tcp:8081' to forward requests from your device
• If your device is on the same Wi-Fi network, set 'Debug server host & port for device' in 'Dev settings' to your machine's IP address and the port of the local dev server - e.g. 10.0.1.1:8081

facebook::react::Recoverable: Could not open file/data/user/0/com.detoxtest.dev/files/ReactNativeDevBundle.js: No such file or directory
loadScript
    JSBundleLoader.java:77
runJSBundle
    CatalystInstanceImpl.java:234
createReactContext
    ReactInstanceManager.java:1137
access$900
    ReactInstanceManager.java:113
run
    ReactInstanceManager.java:944
run
    Thread.java:761

iOS build and tests work normally.

**Steps to Reproduce**
detox build -c android.emu.debug && detox test -c android.emu.debug

Detox, Node, Device, Xcode and macOS Versions
Detox: 14.0.0
React Native: 0.59.9
Node: 10.15.1
Device: Pixel_2_XL_API_28
macOS: 10.14.5

**Device and verbose Detox logs**
facebook::react::Recoverable: Could not open file/data/user/0/com.detoxtesting/files/ReactNativeDevBundle.js: No such file or directory

Try the following to fix the issue:
• Ensure that the packager server is running
• Ensure that your device/emulator is connected to your machine and has USB debugging enabled - run 'adb devices' to see a list of connected devices
• Ensure Airplane Mode is disabled
• If you're on a physical device connected to the same machine, run 'adb reverse tcp:8081 tcp:8081' to forward requests from your device
• If your device is on the same Wi-Fi network, set 'Debug server host & port for device' in 'Dev settings' to your machine's IP address and the port of the local dev server - e.g. 10.0.1.1:8081

facebook::react::Recoverable: Could not open file/data/user/0/com.detoxtesting/files/ReactNativeDevBundle.js: No such file or directory
loadScript
    JSBundleLoader.java:77
runJSBundle
    CatalystInstanceImpl.java:234
createReactContext
    ReactInstanceManager.java:1137
access$900
    ReactInstanceManager.java:113
run
    ReactInstanceManager.java:944
run
    Thread.java:761

**In the command line:**

 ● Test suite failed to run

    Error: Failed: "@Thread com.wix.detox.manager(511):
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.facebook.react.bridge.CatalystInstance com.facebook.react.bridge.ReactContext.getCatalystInstance()' on a null object reference
        at com.wix.detox.ReactNativeSupport.removeEspressoIdlingResources(ReactNativeSupport.java:245)
        at com.wix.detox.ReactNativeSupport.removeEspressoIdlingResources(ReactNativeSupport.java:233)
        at com.wix.detox.TestEngineFacade.hardResetReactNative(TestEngineFacade.kt:19)
        at com.wix.detox.CleanupActionHandler.handle(DetoxActionHandlers.kt:76)
        at com.wix.detox.DetoxManager$2.run(DetoxManager.java:104)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at com.wix.detox.Detox$1.run(Detox.java:139)
        at java.lang.Thread.run(Thread.java:764)
    "

      21 | });
      22 | 
    > 23 | afterAll(async () => {
         | ^
      24 |   await adapter.afterAll();
      25 |   await detox.cleanup();
      26 | });

      at Env.afterAll (../node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:41:24)
      at Object.afterAll (init.js:23:1)
          at Array.forEach (<anonymous>)

**Comment by d4vidi** [comment]
@nelsonchen5 could you work out a demo app where this reproduces, and share it?
