### ISSUE TITLE
Possible Earl Grey actions we would want to expose?

### ISSUE THREAD

**Issue by LeoNatan** [wix/Detox#159]
Earl Grey has [many actions](https://github.com/google/EarlGrey/blob/master/EarlGrey/Action/GREYActions.h) which we [don't yet support](https://github.com/wix/detox/blob/master/detox/src/ios/expect.js#L43) in Detox.

One such action, as discussed in #139, is for handling picker views.

We may want to add individual support or use invoke to create a general way of using these actions without explicit support in JS. Such a solution must have good user-facing API.

**Comment by colinramsay** [comment]
I raised the subject of pickers in #139. I guess the naive implementation is something like:

```
class SetPickerColumnAction extends Action {
  constructor(value) {
    super();
    if (typeof value !== 'string') throw new Error(`SetPickerColumnAction ctor argument must be a string, got ${typeof value}`);
    this._call = invoke.call(invoke.IOS.Class('GREYActions'), 'actionForSetPickerColumn:', value);
  }
}
```

As @LeoNatan said in #139:

> However, this is a very naive approach, as picker views can have custom views.

Questions, then:

1. Is it still useful to implement something like this, since it would be useful _now_?
2. What would a less naive version look like? How would Earl Grey handle a picker with custom views?

**Comment by rotemmiz** [comment]
There's a WIP PR by @DanielMSchmidt which generates JS invocations according to objC header files.
https://github.com/wix/detox/pull/178

The first milestone is to wrap `GREYActions`. We will merge it soon.

**Comment by LeoNatan** [comment]
Closing old issues. If something is needed, please open a new enhancement request.
