### ISSUE TITLE
Scroll startPosition is not working on Android

### ISSUE THREAD

**Issue by sbycrosz** [wix/Detox#1593]
**Describe the bug**

Scroll start-positions are ignored in Android

**To Reproduce**

- [x] I have tested this issue on the latest Detox release and it still reproduces

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

1. Create a submit button with position: absolute in front of a scroll-view
2. Write detox test to scroll on the scroll-view
3. Scrolling does not happen because detox keeps hitting the button instead of the scroll-view

Demo project: https://github.com/sbycrosz/Detox/commit/db368ccee4403f87d4eec6d28ecc4b97bb35f8c5

**Expected behavior**
Scrolling should happen

**Screenshots**

![scroll2](https://user-images.githubusercontent.com/4867178/62676899-e2c5c180-b9de-11e9-98da-acf8493b3b5e.gif)

**Environment (please complete the following information):**
 - Detox: 14.0.0
 - React Native: 59.9
 - Node:8.11.1
 - Device: Android Emulator
 - OS: OSX 10.14.5

**Device and Verbose Detox Logs**

```
detox[98320] INFO:  [DetoxServer.js] server listening on localhost:56653...
detox[98320] DEBUG: [AsyncWebSocket.js/WEBSOCKET_OPEN] opened web socket to: ws://localhost:56653
detox[98320] DEBUG: [DetoxServer.js/LOGIN] role=tester, sessionId=530623a2-6803-014c-4361-12040edce896
detox[98320] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=tester, sessionId=530623a2-6803-014c-4361-12040edce896
detox[98320] DEBUG: [exec.js/EXEC_CMD, #0] /Users/sam/Library/Android/sdk/emulator/emulator -list-avds --verbose
detox[98320] DEBUG: [exec.js/EXEC_CMD, #1] /Users/sam/Library/Android/sdk/platform-tools/adb  devices
detox[98320] DEBUG: [exec.js/EXEC_SUCCESS, #1] List of devices attached
emulator-5554	device


detox[98320] DEBUG: [exec.js/EXEC_CMD, #2] /Users/sam/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "getprop dev.bootcomplete"
detox[98320] DEBUG: [exec.js/EXEC_CMD, #3] /Users/sam/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "getprop ro.build.version.sdk"
detox[98320] DEBUG: [exec.js/EXEC_CMD, #4] /Users/sam/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys power | grep \"^[ ]*m[UW].*=\""
detox[98320] DEBUG: [exec.js/EXEC_CMD, #5] /Users/sam/Library/Android/sdk/build-tools/28.0.3/aapt dump badging "/Users/sam/works/detox/examples/demo-react-native/android/app/build/outputs/apk/debug/app-debug.apk" | grep -e "package: name="
detox[98320] DEBUG: [exec.js/EXEC_CMD, #6] /Users/sam/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "pm list packages com.detox.rn.example"
detox[98320] DEBUG: [exec.js/EXEC_CMD, #7] /Users/sam/Library/Android/sdk/platform-tools/adb -s emulator-5554 uninstall com.detox.rn.example
detox[98320] DEBUG: [exec.js/EXEC_CMD, #8] /Users/sam/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "pm list packages com.detox.rn.example.test"
detox[98320] DEBUG: [exec.js/EXEC_CMD, #9] /Users/sam/Library/Android/sdk/platform-tools/adb -s emulator-5554 uninstall com.detox.rn.example.test
detox[98320] DEBUG: [exec.js/EXEC_CMD, #10] /Users/sam/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -r -g -t "/Users/sam/works/detox/examples/demo-react-native/android/app/build/outputs/apk/debug/app-debug.apk"
detox[98320] DEBUG: [exec.js/EXEC_CMD, #11] /Users/sam/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -r -g -t "/Users/sam/works/detox/examples/demo-react-native/android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk"
detox[98320] DEBUG: [exec.js/EXEC_CMD, #12] /Users/sam/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "am force-stop com.detox.rn.example"
detox[98320] DEBUG: [exec.js/EXEC_CMD, #13] /Users/sam/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "date +\"%m-%d %T.000\""
detox[98320] DEBUG: [exec.js/EXEC_CMD, #14] /Users/sam/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "pm list instrumentation"
detox[98320] DEBUG: [exec.js/SPAWN_CMD, #15] [pid=98359] /Users/sam/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am instrument -w -r -e detoxServer ws://localhost:56653 -e detoxSessionId 530623a2-6803-014c-4361-12040edce896 -e debug ZmFsc2U= com.detox.rn.example.test/androidx.test.runner.AndroidJUnitRunner
detox[98320] DEBUG: [exec.js/EXEC_CMD, #16] /Users/sam/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "ps | grep \"com\.detox\.rn\.example$\""
detox[98320] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=testee not connected, cannot fw action (sessionId=530623a2-6803-014c-4361-12040edce896)
detox[98320] DEBUG: [DetoxServer.js/LOGIN] role=testee, sessionId=530623a2-6803-014c-4361-12040edce896
detox[98320] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=testee, sessionId=530623a2-6803-014c-4361-12040edce896
  Example
```

**Comment by dangtai91** [comment]
My application has a button at the bottom but scroll action does not follow the set startPosition. Therefore, cannot perform the scroll action. Please help to fix this bug soon
Environment:
- Detox: 14.0.2
- React Native: 0.59.8
- Device: Android Emulator (Nexus_6_API_28)

**Comment by thoth-ibl** [comment]
I have same issue @d4vidi .

**Comment by duynvt-ibl** [comment]
My android simulator stuck here (Detox 14.0.2, RN 0.58.9)

**Comment by ShiroFei** [comment]
I have the same this issue, the action scroll works well on iOS, but on Android, it does not.

**Comment by d4vidi** [comment]
@sbycrosz please refer to the `startPositionX` and `startPositionY` parameters for the [`scroll()` method](https://github.com/wix/Detox/blob/master/docs/APIRef.ActionsOnElement.md#scrollpixels-direction-startpositionxnan-startpositionynan), which is now supported on Android (Detox `14.3.4`).

**Comment by sbycrosz** [comment]
Thanks @d4vidi ! I will upgrade my project to use the latest detox soon!

**Comment by ShiroFei** [comment]
Hi @d4vidi , I was updated the lastest version as your recommended, but this issue still happened 
When I run, It shows message error, Please help check again.

> No such accessible method: scrollInDirection() on class: com.wix.detox.espresso.DetoxAction"

**Comment by d4vidi** [comment]
@ShiroFei this is because in this version we changed the contract between the JS and native. Be sure to recompile the native code (i.e. test APK) from scratch.
