### ISSUE TITLE
`clearText()` sometimes places the cursor at the start of the element, and so does not clear the text.

### ISSUE THREAD

**Issue by yedidyak** [wix/Detox#1594]
**Describe the bug**
`clearText()` sometimes places the cursor at the start of the element, and so does not clear the text.

**To Reproduce**

- [ X] I have tested this issue on the latest Detox release and it still reproduces

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

1. Have an element with text
2. Use clearText()

If possible, please provide a small demo project that reproduces the issue, or attach a video with the reproduction - this would be very appreciated.

Internal, ask me for details.

**Expected behavior**

Should clear the text

**Environment (please complete the following information):**
 - Detox: 14
 - React Native: 59
 - Node: 8.16.0
 - Device: iPhone X
 - Xcode: 10.1
 - iOS: 12.1
 - macOS: 10.14.6

**Comment by LeoNatan** [comment]
Will release a fix soon.
