### ISSUE TITLE
Consecutive app launches fail at times

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#1599]
**Describe the bug**
Upon detox init, there's typically an app launch.
If the first test in the following suite also has an app launch (i.e. `device.launchApp()`), sometimes the launch would fail.

The reason behind it is that in the current implementation, launching an app dynamically is performed by moving to the recent-apps view on the device, and the selecting the app (done using UIAutomator). What happens at times is that instead of showing `DetoxTest` (or whatever the app name is) as the app's title, the recent apps view shows the full activity name, instead (e.g. `com.wix.detox.MainActivity`). UIAutomator can't cope with that, it seems, and thus device simply gets hold up in that state.

**To Reproduce**

Flows test of the detox tests suite is flaky for exactly that reason.

- [x] I have tested this issue on the latest Detox release and it still reproduces

**Expected behavior**
Launch app when the app is already running in the foreground should do nothing...

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Detox: 14.0.1
 - React Native: 59.9
 - Node: 10.15.3
 - Device: Pixel_API_2
 - OS: 10.14.6

**Device and Verbose Detox Logs**

```
15:59:36  FAIL  [2m23.flows.test.js (30.329s)
15:59:36   Flows
15:59:36     ✕ [2mshould exit without timeouts if app was terminated inside test (13110ms)[22m
15:59:36 
15:59:36   ● Flows › should exit without timeouts if app was terminated inside test
15:59:36 
15:59:36     UiSelector[CONTAINS_DESCRIPTION=Detox Test]
15:59:36 [2m[22m
15:59:36 [2m  90 |     // when this test run fails, we want a stack trace from up here where the[22m
15:59:36 [2m  91 |     // $callee is still available, and not inside the catch block where it isn't[22m
15:59:36 [2m> 92 |     const potentialError = new Error();[22m
15:59:36 [2m     |                            ^[22m
15:59:36 [2m  93 | [22m
15:59:36 [2m  94 |     try {[22m
15:59:36 [2m  95 |       return await this.sendAction(new actions.Invoke(invocation));[22m
15:59:36 [2m[22m
15:59:36 [2m      [2mat Client.execute ([2msrc/client/Client.js[2m:92:28)[2m[22m
15:59:36 [2m      [2mat InvocationManager.execute ([2msrc/invoke.js[2m:11:39)[2m[22m
15:59:36 [2m      [2mat EmulatorDriver.execute [as _resumeMainActivity] ([2msrc/devices/drivers/AndroidDriver.js[2m:242:35)[2m[22m
15:59:36 [2m      [2mat EmulatorDriver._resumeMainActivity [as launchApp] ([2msrc/devices/drivers/AndroidDriver.js[2m:97:20)[2m[22m
15:59:36 
```

**Comment by LeoNatan** [comment]
If you want the issue to remain open, pin it.
