### ISSUE TITLE
Passthrough to underlying "expect" function

### ISSUE THREAD

**Issue by mnzaki** [wix/Detox#1604]
**Is your feature request related to a problem? Please describe.**
Tests some times need to use the underlying `expect` function, which is overridden

**Describe the solution you'd like**
detox's `expect` can pass the call down to the original `expect` if the argument is not a detox `Element`

**Describe alternatives you've considered**
Writing a small wrapper util, but it seems a lot of people have the same issue that it might be nice to have builtin. Ex: #198 #944 #826 and on stackoverflow

**Comment by rotemmiz** [comment]
You can control it manually

https://github.com/wix/Detox/blob/master/docs/APIRef.DetoxObjectAPI.md#explicit-imports-during-initialization

**Comment by mnzaki** [comment]
@rotemmiz yes I understand, but I ended up writing a wrapper around it to multiplex between the "native" expect and detox's expect and just thought it might be nice to have that builtin as it seems many people ask about it. It would also be especially useful (because it would be used more) after some implementation of `getText` or `getProps` is ready (#445)

**Comment by rotemmiz** [comment]
There is no original expect, or at least you can not infer it exists. If detox runs under Jest it will be there, but for mocha or Ava (or others), there is no built-in expectation library.

**Comment by mnzaki** [comment]
The other `expect` I had in mind was from `chai` of course, but I guess detox can't really infer what to use. If it cannot be inferred, though, then perhaps the fallback could potentially be configured during `detox.init`?

**Comment by rotemmiz** [comment]
But why not just use the explicit API?

**Comment by mnzaki** [comment]
Just a little annoying importing two expects and deciding between which to use each time even though code can easily make that decision for me :man_shrugging: 

Although there's still the fact that detox.expect is async and that requires attention anyway 

Ok not really sure how useful this proposal is, I will stick to using my little wrapper util and write more tests for a while first! Sorry about the noise!
