### ISSUE TITLE
Parallel testing on Android, phase 2: return of the ADB

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#1606]
With the introduction of initial parallel testing support in #1572, we've learned there's more work to be done in order to make this feature more stable and effectively useful - as briefly explained here: https://github.com/wix/Detox/pull/1595#issuecomment-521374757. 

The main issue to address is the ADB becoming a bottleneck, which mostly affects boot time:
1. With commands being sent to the booting emulators all over the place (status queries, apk's installs, etc.), it so happens that often some commands take long to complete.
2. In detox, we initially saw a 50% improvement running the suite on CI using 3 workers instead of 1. While this result is good, it was not optimized, since all emulator instances were cold-booting. I've then naively tried setting up a working quick-booting config (not too hard to work out - even without UI), and the results were surprising: it added (!!!) 17% to overall test time (~8.5min -> ~10min) - what an [Issac Asimov moment](https://www.quotes.net/quote/140). The reason behind that was of course, as describe in 1.
3. In more general terms, the typical runtime behaviour of this initial parallel testing solution was such that emulators finish loading, all preliminary work is performed to completion, and only then do the tests begin to run in near sync. This isn't healthy, showing that something (ADB) holds back stuff from executing freely.

Moving on to the solution, here are the main points in question; they must be solved and implemented within the context of this issue:
1. [This SO](https://stackoverflow.com/questions/3836571/changing-default-port-i-e-5037-on-which-adb-server-runs) shows its technically easy to set up multiple ADB server bound to different ports. Setting `ANDROID_ADB_SERVER_PORT` (must be identical for both ADB _and_ the emulator!!!) does the trick. So, the overall direction is towards having an ADB server running per each detox-dispatched emulator.
2. The first caveat with 1 - based on experimentation, is that each ADB server can only account for the emulators that have been loaded with the associated port. Namely, no - not all servers can familiarize themselves with all running emulators automagically.  This is big deal for us because we currently do not hold bookkeeping for the running ADB's -- just emulators, and also assume they're all reachable using ADB as we search for a free instance to run the current suite. Using multiple ports breaks that assumption - since, when looking up an available device, its harder to trace all running emulators (you need that kind of bookkeeping for that). That can be simplified if you uniquely, one-to-one associate emulators' and adb's ports: for example, emu running on 10666 will have an ADB server listening on 20666. With that, it'd be easy to trace back the adb server once the emu in 10666 is found, and vice versa. It can even be simplified further if we were to choose not to try to run simultaneous work on emu's not previously dispatched by detox (typically running in the standard port range (5554-5585), wired to ADB default = 5037). But we need to think that through: can we give that up in the presence of multiple workers? Either way, this bookkeeping needs to be introduced.
3. The 2nd caveat is therefore the need to manage running ADB servers. It's particularly hard because servers can live across detox test sessions, so they have to be persisted and very sensitively cleaned up in each detox testing bootstrapping.
4. With the possible exception of emulators running with the standard ports (5554-5585), an ADB server can only attach to an emulator started *after* it's already been set up. It does not seem to properly scan running emu's, not even with the utilization of `ADB_LOCAL_TRANSPORT_MAX_PORT` (run `adb`+enter and see).

---

Stockpiling tasks:
- [ ] Fix ADB bottleneck issue
- [ ] Find a way to fail elegantly in case of emulator (& simulator?) launch failures. Particularly important in this context because `-read-only` feels somewhat fragile, still.

**Comment by LeoNatan** [comment]
Electric Boogaloo

**Comment by d4vidi** [comment]
So... after some tests on multiple levels it seems that the problem here is not ADB, after all. Rather, the cause to this increase in overall test time when applying quick-boot is an emulator bug where for 1-2 minutes after quick-booting the emulators appeared to have run on very high CPU load (the culprit is [GMS](https://www.android.com/gms/), which takes up serious resources).

After solving this in our CI agents by upgrading to the latest emulator bin version (`29.0.11`->`29.2.1`), indeed we see much better test-time results.

We will write a book on those things one day.
