### ISSUE TITLE
Look for a way to catch app crashes and report to the user, rather than have test stuck until timeout

### ISSUE THREAD

**Issue by LeoNatan** [wix/detox#161]
Currently, if the app crashes (for whatever reason), Detox is unable to realize this, and is stuck until timeout. This is a bad user experience and needs to be solved.

**Comment by ambatisuman** [comment]
Detox looks awesome, unfortunately sometimes our tests gets stuck because of this. Are there any plans to get it in next releases? thanks.

**Comment by LeoNatan** [comment]
This is a big, open-ended issue. There is no magic bullet (that we have come up with, anyway). Ideas welcome.

**Comment by LeoNatan** [comment]
We discussed this internally again. and we have a short-term plan that should help solve some of these issues. Not all, but we believe most issues. We plan to work on this soon.
