### ISSUE TITLE
Visibility thresholds mismatch

### ISSUE THREAD

**Issue by yedidyak** [wix/Detox#1613]
**Describe the bug**
An element is considered visible if it is 75% visible, but can only be tapped if it is at least 90% visible. This means that if you use waitFor to scroll to an element, you are not guaranteed that the element is tappable when the waitFor promise returns.

*Expected behavior**
All thresholds should be the same

**Environment (please complete the following information):**
 - Detox: ^14
 - React Native: 59
 - Node: NA
 - Device: NA
 - OS: Android

**Device and Verbose Detox Logs**
Provide the device and "trace" Detox logs so we can understand what happened. You can obtain them by passing the loglevel param: `detox test --loglevel trace`

`Error performing 'single click' on view ...`

**Comment by yogeshchoudhary147** [comment]
@yedidyak I am facing the same. Have you found any way out?

**Comment by yedidyak** [comment]
@yogeshchoudhary147 In a sort of hacky way, I just scroll a little bit further on Android.

**Comment by yogeshchoudhary147** [comment]
@yedidyak Thanks for the suggestion.

I found another hacky way, I scroll the list till the item prior to one I want to click become invisible.

**Comment by d4vidi** [comment]
Please try this again with Detox `14.3.2` 🙏
