### ISSUE TITLE
Signal 11 with firebase pods

### ISSUE THREAD

**Issue by nikolas7892** [wix/Detox#1615]
**Describe the bug**

`pod 'Firebase/DynamicLinks'` & `  pod 'Firebase/Messaging', '~> 6.3.0'` prevent detox from running any tests. As soon as I add
`[FIRApp configure];` as instructed in the https://firebase.google.com/docs/ios/setup guide, I receive the following error message.

 -[RCTBundleURLProvider _URLOverride]: unrecognized selector sent to instance 0x6000022e8710
(
	0   CoreFoundation                      0x000000011512a8db __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000011388dac5 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000115148c94 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000011512f623 ___forwarding___ + 1443
	4   CoreFoundation                      0x0000000115131418 _CF_forwarding_prep_0 + 120
	5   Detox                               0x0000000110ec30e5 -[DetoxAppDelegateProxy application:didFinishLaunchingWithOptions:] + 266
	6   UIKitCore                           0x000000011f3d5731 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 280
	7   UIKitCore                           0x000000011f3d70cd -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 3932
	8   UIKitCore                           0x000000011f3dc4e6 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1617
	9   UIKitCore                           0x000000011ec20a4e __111-[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]_block_invoke + 904
	10  UIKitCore                           0x000000011ec29346 +[_UICanvas _enqueuePostSettingUpdateTransactionBlock:] + 153
	11  UIKitCore                           0x000000011ec20664 -[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:] + 236
	12  UIKitCore                           0x000000011ec20fc0 -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:] + 1091
	13  UIKitCore                           0x000000011ec1f332 __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke + 782
	14  UIKitCore                           0x000000011ec1efe9 -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:] + 433
	15  UIKitCore                           0x000000011ec23d2e __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke + 576
	16  UIKitCore                           0x000000011ec24988 _performActionsWithDelayForTransitionContext + 100
	17  UIKitCore                           0x000000011ec23a95 -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:] + 223
	18  UIKitCore                           0x000000011ec28a48 -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] + 392
	19  UIKitCore                           0x000000011f3dadc8 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 514
	20  UIKitCore                           0x000000011ef9202f -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 361
	21  FrontBoardServices                  0x000000011e38cd25 -[FBSSceneImpl _didCreateWithTransitionContext:completion:] + 448
	22  FrontBoardServices                  0x000000011e396ad6 __56-[FBSWorkspace client:handleCreateScene:withCompletion:]_block_invoke_2 + 283
	23  FrontBoardServices                  0x000000011e396300 __40-[FBSWorkspace _performDelegateCallOut:]_block_invoke + 53
	24  libdispatch.dylib                   0x0000000115fdbd02 _dispatch_client_callout + 8
	25  libdispatch.dylib                   0x0000000115fded41 _dispatch_block_invoke_direct + 295
	26  FrontBoardServices                  0x000000011e3c80da __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 30
	27  FrontBoardServices                  0x000000011e3c7d92 -[FBSSerialQueue _performNext] + 451
	28  FrontBoardServices                  0x000000011e3c8327 -[FBSSerialQueue _performNextFromRunLoopSource] + 42
	29  CoreFoundation                      0x0000000115091db1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	30  CoreFoundation                      0x0000000115091633 __CFRunLoopDoSources0 + 243
	31  CoreFoundation                      0x000000011508bcef __CFRunLoopRun + 1231
	32  CoreFoundation                      0x000000011508b4d2 CFRunLoopRunSpecific + 626
	33  GraphicsServices                    0x000000011701a2fe GSEventRunModal + 65
	34  Detox                               0x0000000110ebf8b8 __detox_UIApplication_run + 365
	35  UIKitCore                           0x000000011f3ddfc2 UIApplicationMain + 140
	36  ExampleApp                              0x000000010fe1d2d0 main + 112
	37  libdyld.dylib                       0x0000000116049541 start + 1
)

**To Reproduce**

1. react-native init ExampleApp
2. yarn add detox --save-dev
3. yarn add mocha --save-dev
4. detox init -r mocha
5. Add the following to podfile & `pod install`
`pod 'Firebase/Core', '~> 6.3.0'`
`pod 'Firebase/DynamicLinks', '~> 6.3.0'`
`pod 'Firebase/Messaging', '~> 6.3.0'`

6. Add to package json
`  "detox": {
    "configurations": {
      "ios.sim.debug": {
        "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/ExampleApp.app",
        "build": "xcodebuild -workspace ios/ExampleApp.xcworkspace -scheme ExampleApp -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build",
        "type": "ios.simulator",
        "name": "iPhone 7"
      }
    },
    "test-runner": "mocha"
  }`

(Detox will run up until the next step)

7. Add to AppDelegate.m at the top of the file

`#import <Firebase.h>`

8. Add in the beginning of didFinishLaunchingWithOptions

`[FIRApp configure];` 

The error will not reproduce.

reference: https://firebase.google.com/docs/ios/setup

*Example Project*

https://github.com/nikolas7892/ExampleApp-detox-.git

**Expected behavior**
As soon as i remove:
`pod 'Firebase/DynamicLinks', '~> 6.3.0'`
`pod 'Firebase/Messaging', '~> 6.3.0'`

and clean the environment:

rm -rf ios/build
rm -rf ios/Pods
cd ios && pod install

The project works as expected.
 
Example video attached:

[Untitled.mov.zip](https://github.com/wix/Detox/files/3523076/Untitled.mov.zip)

**Screenshots**

**Environment (please complete the following information):**
 - Detox:^14.0.2
 - React Native:0.60.5
 - Node:v10.16.0
 - Device: iPhone 7 (simulator)
 - Xcode: 10.3

**Device and Verbose Detox Logs**
`{"type":"AppWillTerminateWithError","messageId":-10000,"params":{"threadNumber":1,"errorDetails":"Signal 4 was raised\n(\n\t0   Detox                               0x000000011031f7c6 _ZL16__DTXHandleCrashP11NSExceptionP8NSNumberP8NSString + 497\n\t1   Detox                               0x000000011031f54b _ZL17__DTXHandleSignali + 61\n\t2   libsystem_platform.dylib            0x0000000115e2eb3d _sigtramp + 29\n\t3   libobjc.A.dylib                     0x0000000112cf0040 _ZN12_GLOBAL__N_119AutoreleasePoolPage11tls_deallocEPv + 56\n\t4   Detox                               0x000000011031d7b6 -[DetoxManager notifyOnCrashWithDetails:] + 293\n\t5   Detox                               0x000000011031f88b _ZL16__DTXHandleCrashP11NSExceptionP8NSNumberP8NSString + 694\n\t6   Detox                               0x000000011031f2f6 _ZL15__dtx_terminatev + 117\n\t7   libc++abi.dylib                     0x0000000115951a2e _ZSt11__terminatePFvvE + 8\n\t8   libc++abi.dylib                     0x0000000115951aa3 _ZSt9terminatev + 51\n\t9   libdispatch.dylib                   0x0000000115a5cd16 _dispatch_client_callout + 28\n\t10  libdispatch.dylib                   0x0000000115a5fd41 _dispatch_block_invoke_direct + 295\n\t11  FrontBoardServices                  0x000000011b5680da __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 30\n\t12  FrontBoardServices                  0x000000011b567d92 -[FBSSerialQueue _performNext] + 451\n\t13  FrontBoardServices                  0x000000011b568327 -[FBSSerialQueue _performNextFromRunLoopSource] + 42\n\t14  CoreFoundation                      0x00000001144dfdb1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17\n\t15  CoreFoundation                      0x00000001144df633 __CFRunLoopDoSources0 + 243\n\t16  CoreFoundation                      0x00000001144d9cef __CFRunLoopRun + 1231\n\t17  CoreFoundation                      0x00000001144d94d2 CFRunLoopRunSpecific + 626\n\t18  GraphicsServices                    0x000000011a1a32fe GSEventRunModal + 65\n\t19  Detox                               0x00000001103148b8 __detox_UIApplication_run + 365\n\t20  UIKitCore                           0x000000011df10fc2 UIApplicationMain + 140\n\t21  ExampleApp                          0x000000010f274790 main + 112\n\t22  libdyld.dylib                       0x0000000115aca541 start + 1\n\t23  ???                                 0x0000000000000006 0x0 + 6\n)","queueName":"com.apple.main-thread"}}`

**Comment by LA** [comment]
Thanks for taking the time to make this issue. I had something similar happen in the past. Hopefully this gets fixed.

**Comment by LeoNatan** [comment]
Fixed in latest release.
