### ISSUE TITLE
Android build fails due to androidx.annotation version mismatch

### ISSUE THREAD

**Issue by MillerGregor** [wix/Detox#1631]
***```detox build``` fails after initial android setup***

**To Reproduce**

- [ v] I have tested this issue on the latest Detox release and it still reproduces

1. install, set up, & configure detox
2. verify passing tests in ios
3. configure android following the Android Guide
4. execute ```detox build --configuration android.emu.debug```

**Expected behavior**
expected to build successfully

**Environment:**
 - Detox:  14.0.3
 - React Native:  0.60.4
 - Node:  10.16.2
 - Device:  n/a
 - OS: macOS 10.14.6 

**Device and Verbose Detox Logs**
truncated build output:
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugAndroidTestBuild'.
> Could not resolve all task dependencies for configuration ':app:debugAndroidTestRuntimeClasspath'.
   > Could not resolve androidx.annotation:annotation:{strictly 1.0.0}.
     Required by:
         project :app
      > Cannot find a version of 'androidx.annotation:annotation' that satisfies the version constraints: 
           Dependency path 'my_app:app:unspecified' --> 'com.wix:detox:14.0.3' --> 'androidx.annotation:annotation:1.1.0'
           Constraint path 'my_app:app:unspecified' --> 'androidx.annotation:annotation:{strictly 1.0.0}' because of the following reason: debugRuntimeClasspath uses version 1.0.0
```

 **Solution**
add the following to android/app/build.gradle:

```
dependencies {
    // ...
    api 'androidx.annotation:annotation:1.1.0'
}
```

this was a guess, that worked... is this the best approach?

**Comment by kolohelios** [comment]
Pretty much the same solution overall, but here's how I've handled it (I believe based off of a post here or on SO):

```
configurations.all {
    resolutionStrategy {
        // TODO the line below is required for Detox since version 12.5; it should removed as soon as the project compiles without it
        force 'androidx.annotation:annotation:1.0.0'
    }
}
```

**Comment by d4vidi** [comment]
Closing in favor of #1689. Please refer to the [versions support table](https://github.com/wix/Detox/#react-native) for latest info on this.
