### ISSUE TITLE
Are my iOS tests supposed to open up a simulator?

### ISSUE THREAD

**Issue by maximedupre** [wix/Detox#1634]
The README contains an animated GIF that shows tests running in a simulator, yet in the About section it is written that:

> Runs on Devices (not yet supported on iOS): Gain confidence to ship by testing your app on a device/simulator just like a real user.

Furthermore my tests spawn no simulator. Is it possible to clear that up?

Cheers!

**Comment by maximedupre** [comment]
Oh come on lol

**Comment by LeoNatan** [comment]
"Device" means an actual hardware device.
If you don't see the simulator while running tests, open the Simulator app from Xcode. When Detox tests run, a simulator is booted, but no UI shows up.

**Comment by maximedupre** [comment]
@LeoNatan Do I actually need to open the Simulator when running my tests? It seems like when I don't have the simulator open, my tests fail.

**Comment by LeoNatan** [comment]
No. If the app is not open, the simulator runtime runs in a headless mode.
