### ISSUE TITLE
iOS 13 Support

### ISSUE THREAD

**Issue by carlosalmonte04** [wix/Detox#1637]
I am currently unable to run Detox on iOS 13. It all works as expected if I assign a simulator with iOS 12.X. However, the app crashes with a `Signal 11` error that I am having a hard time tracing. 

Has anyone here tested Detox on iOS 13? Is it confirmed to be compatible?

**Comment by LeoNatan** [comment]
iOS 13 is not supported right now. The version of Earl Grey, which we use on iOS, is not yet compatible with iOS 13.

**Comment by LeoNatan** [comment]
I've merged some changes for iOS 13 and have gotten the Detox suite to pass on iOS 13 locally. We don't have an iOS 13 CI yet.

Please provide the crash information you are seeing so that I can be sure it is fixed.

**Comment by LeoNatan** [comment]
Ping @carlosalmonte04

**Comment by LeoNatan** [comment]
Detox 14.3.4 is out with iOS 13 support. Please test and let me know if you have issues.
