### ISSUE TITLE
Nested ScrollView cause "Multiple UI elements match"

### ISSUE THREAD

**Issue by rumax** [wix/detox#164]
Nested ScrollView cause Multiple UI elements match

## Steps to reproduce
 - Create a nested ScrollView. For example the main ScrollView will be scrolled vertically, nested will be scrolled horizontally
 - Or check this example https://github.com/rumax/detox/commit/ce3596ca0978df60a0875c47170b0919bbfd4e3e
- Add tests for `scroll`, `swipe`
```
it('should be visible', async () => {
    await expect(element(by.id('vScrollView'))).toBeVisible();
});
it('should swipe', async () => {
    await element(by.id('vScrollView')).swipe('up', 'fast');
});

it('should scroll', async () => {
    await element(by.id('vScrollView')).scroll(500, 'down');
});
```

## Actual result:
```
detox info 5: com.wix.demo.react.native launched 
  Example
    ✓ should have welcome screen (793ms)
    ✓ should show hello screen after tap (364ms)
    ✓ should show world screen after tap (360ms)
    1) should be visible


  3 passing (15s)
  1 failing

  1) Example should be visible:
     Error: Multiple UI elements matched for given criteria.
Exception with Assertion: {
  "Assertion Criteria" : "assertWithMatcher: matcherForSufficientlyVisible(>=0.750000)",
  "Element Matcher" : "(((respondsToSelector(accessibilityIdentifier) && accessibilityID('vScrollView')) && !kindOfClass('RCTScrollView')) || (kindOfClass('UIScrollView') && ((kindOfClass('UIView') || respondsToSelector(accessibilityContainer)) && ancestorThatMatches(((respondsToSelector(accessibilityIdentifier) && accessibilityID('vScrollView')) && kindOfClass('RCTScrollView'))))))",
  "Recovery Suggestion" : "Create a more specific matcher to narrow matched element"
}

Error Trace: [
  {
    "Description" : "Multiple elements were matched: (
    "<RCTCustomScrollView:0x7f85bb091000; AX=N; AX.frame={{0, 0}, {414, 736}}; AX.activationPoint={207, 368}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {414, 736}}; opaque; alpha=1>",
    "<RCTCustomScrollView:0x7f85ba833a00; AX=N; AX.frame={{0, 154}, {414, 100}}; AX.activationPoint={207, 204}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {414, 100}}; opaque; alpha=1>"
). Please use selection matchers to narrow the selection down to single element.",
    "Domain" : "com.google.earlgrey.ElementInteractionErrorDomain",
    "Code" : "5",
    "File Name" : "GREYElementInteraction.m",
    "Function Name" : "-[GREYElementInteraction grey_errorForMultipleMatchingElements:withMatchedElementsIndexOutOfBounds:]",
    "Line" : "910"
  }
]
```

## Expected result 
```
detox info 5: com.wix.demo.react.native launched 
  Example
    ✓ should have welcome screen (830ms)
    ✓ should show hello screen after tap (367ms)
    ✓ should show world screen after tap (328ms)
    ✓ should be visible (254ms)
    ✓ should swipe (471ms)
    ✓ should scroll (4822ms)


  6 passing (22s)
```

**Comment by abrel** [comment]
I am also facing this issue with nested scrollViews. Is there any known workaround?

**Comment by rumax** [comment]
> Is there any known workaround?

I use slow swipe

**Comment by abrel** [comment]
In my case, I got the same error using scroll and swipe

**Comment by holleB** [comment]
Looks like 

```javascript
async scroll(amount, direction = 'down') {
    // override the user's element selection with an extended matcher that looks for UIScrollView children
    this._selectElementWithMatcher(this._originalMatcher._extendToDescendantScrollViews());
    return await new ActionInteraction(this, new ScrollAmountAction(direction, amount)).execute();
}
```


in `detox/src/ios/expect.js`.

Could you explain why the matcher should descend to subviews by default? Would be nice to know if it's necessary before I try to implement something like `scrollToWithoutDescendant`.

**Comment by anton6** [comment]
@LeoNatan Hi. Is there any progress on this issue?

@holleB have you managed to write your custom scroller "scrollToWithoutDescendant"? Did it work?

**Comment by holleB** [comment]
@anton6 No, I did try it. But I lacked the time to dive deep enough into the code to make it work.

**Comment by kyledmellander** [comment]
We had the same issue trying to scroll when selecting the outer scrollview. There was not a scrollview, but a FlatList nested within. Tried adding the fix in #458, but it didn't seem to change the error. We removed the flatlist, and just went with an array of elements in the meantime.

**Comment by LeoNatan** [comment]
@kylemellander Could you please comment on the PR, stating your problem?

**Comment by Jhonte** [comment]
Hm I have the same problem, but instead of nested scrollviews I have one scrollview and one textinput with multiple lines set to `true`.  

I only state the testID on the scrollview this action:
`        await element(by.id('profile-scroll-view')).scrollTo('bottom')` 
returns
`     Error: Error: Multiple UI elements matched for the given criteria.
`

And atIndex(0) usage like this:
`       await element(by.id('profile-scroll-view')).atIndex(0).scrollTo('bottom')`
`
does not change the behaviour at all...   some tips?

**Comment by nezaidu** [comment]
Any progress?

**Comment by LeoNatan** [comment]
We'll look at this soon. Thanks

**Comment by Protothor** [comment]
So, here's the hack my team used to fix this problem...
in our package.json scripts section we added a "postinstall" 
```
scripts: {
  "postinstall": "node ./postinstall.js"
},
```
and then we added the fix from PR 458 into the postinstall.js
```
var fs = require('fs');
fs.readFile('./node_modules/detox/src/ios/expect.js', 'utf8', function (err,data) {
  if (err) {
    return console.log(err);
  }
  if (data.indexOf('this._selectElementWithMatcher(this._originalMatcher._extendToDescendantScrollViews()); this.atIndex(0);')) return;
  var result = data.replace(/this\._selectElementWithMatcher\(this\._originalMatcher\._extendToDescendantScrollViews\(\)\);/g, 'this._selectElementWithMatcher(this._originalMatcher._extendToDescendantScrollViews()); this.atIndex(0);');
  var result = result.replace(/this\._selectElementWithMatcher\(this\._originalMatcher\._avoidProblematicReactNativeElements\(\)\);/g, 'this._selectElementWithMatcher(this._originalMatcher._avoidProblematicReactNativeElements()); this.atIndex(0);');
  fs.writeFile('./node_modules/detox/src/ios/expect.js', result, 'utf8', function (err) {
     if (err) return console.log(err);
  });
});
```

**Comment by Leeds-eBooks** [comment]
An alternative option is https://github.com/ds300/patch-package which automates this process of manually patching an npm package and makes it safer by committing the patch to git.

**Comment by JakeHiggins** [comment]
Protothor, any status on the pull request for this? it was closed 5 days ago for inactivity.

**Comment by heuism** [comment]
@Protothor I tried the approach you put. However, It doesn't seems to be working with nested scrollview or maybe the one I am using is 1 scrollview outside and a flatlist inside? Thank you.

**Comment by moQuez** [comment]
I just used @Protothor approach but with @Leeds-eBooks patch-package recommendation... Works like a charm...

**Comment by adamgeoffrion** [comment]
Is there any update on a possible fix/PR for this?

**Comment by carlosvega20** [comment]
same issue here.

**Comment by alimtunc** [comment]
@moQuez I tried this solution too, but got same issue..

Here is my generated patch file : 

> patch-package
--- a/node_modules/detox/src/ios/expect.js
+++ b/node_modules/detox/src/ios/expect.js
@@ -290,16 +290,19 @@ class Element {
   ```
async scroll(amount, direction = 'down') {
     // override the user's element selection with an extended matcher that looks for UIScrollView children
     this._selectElementWithMatcher(this._originalMatcher._extendToDescendantScrollViews());
+    this.atIndex(0);
     return await new ActionInteraction(this, new ScrollAmountAction(direction, amount)).execute();
   }
   async scrollTo(edge) {
     // override the user's element selection with an extended matcher that looks for UIScrollView children
     this._selectElementWithMatcher(this._originalMatcher._extendToDescendantScrollViews());
+    this.atIndex(0);
     return await new ActionInteraction(this, new ScrollEdgeAction(edge)).execute();
   }
   async swipe(direction, speed = 'fast', percentage = 0) {
     // override the user's element selection with an extended matcher that avoids RN issues with RCTScrollView
     this._selectElementWithMatcher(this._originalMatcher._avoidProblematicReactNativeElements());
+    this.atIndex(0);
     return await new ActionInteraction(this, new SwipeAction(direction, speed, percentage)).execute();
   }
   async setColumnToValue(column,value) {

```

Maybe anyone have another solution to fix this temporarely ? Thank's

**Comment by compojoom** [comment]
@LeoNatan would you mind commenting on this? To me it seems a major bug that some of us are going around by applying a patch. Are you guys not running into this issue? that is the first problem I ran when I started using detox...

**Comment by LeoNatan** [comment]
We have not run into this issue, and I am not actively working on Detox right now. If someone wants to debug this and submit a PR with a fix (or at least an analysis of where the issue lies), that would be great.

**Comment by LeoNatan** [comment]
@compojoom Can you quickly please create a small demo project reproducing the issue?

**Comment by compojoom** [comment]
will send you a link this afternoon.

**Comment by compojoom** [comment]
@LeoNatan there you go https://github.com/compojoom/DetoxScrollBug

**Comment by LeoNatan** [comment]
Excellent, thank you

**Comment by LeoNatan** [comment]
Good news, we might fix this soon. See #896

**Comment by LeoNatan** [comment]
Please test and let us know if the fix solved your problem. Thank you
