### ISSUE TITLE
toHaveLabel works in iOS but not in Android

### ISSUE THREAD

**Issue by tofanelli** [wix/Detox#1642]
**Describe the bug**
I have several cases where I need to check the button label. Its works smoothly in iOS, but when runs on Android, I get a warning message

**To Reproduce**

- [x] I have tested this issue on the latest Detox release and it still reproduces

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

1. Have a button with a ternary to change the label to 'Enabled' and 'Disabled' after clicked on a checkbox (checked - 'Enabled' / unchecked - 'Disabled' 
2. use the code below
`  await expect(element(by.id(LOGIN.form.submitButton))).toHaveLabel(
      'Enabled',
    );`
3. Run on iOS - no issues 
4. Run on Android - get this error
> '(with content description text: is "Enabled" and view has effective visibility=VISIBLE)' doesn't match the selected view.
Expected: (with content description text: is "Enabled" and view has effective visibility=VISIBLE)

The button code is

`<subButton
        accessible={true} //with or without this returns the same error
        accessibilityLabel={isValid ? 'Enabled' : 'Disabled'}
        testID={LOGIN.form.submitButton}
       disabled={!isValid}
/>`

**Expected behavior**
The test runs ok as long Detox should read the label on Android in the same way as iOS

**Environment (please complete the following information):**
 - Detox: 14.0.1
 - React Native: 0.60.4
 - Node: 12.6
 - Device: Android emulator, any AVD
 - OS:  MacOS 10.14.6

**Device and Verbose Detox Logs**
Device - Pixel 2 API 24 e 28
Trace - doesn't return nothing different from what I already have

**Comment by HelloCore** [comment]
I think they fixed this issue on RN 0.60.5.

https://github.com/wix/Detox/issues/1539#issuecomment-521847227
