### ISSUE TITLE
Detox tests are crashing while performing a write to Realm DB

### ISSUE THREAD

**Issue by Liamandrew** [wix/Detox#1646]
**Describe the bug**
Our detox tests are currently crashing after the very first user action of our tests. We have a "tour" when opening the app for the first time, and our Detox tests always begin by tapping a button to finish the tour. However this tap action is causing a crash.

After some investigation, and by following the steps to debug in Xcode, I believe there might be some issue with Realm while running Detox. We use Realm for our on-device storage, and upon tapping the button described above we perform a write operation to save some data in the Realm DB.

Further, to prove that the Realm operation is the issue, if I remove the Realm write operation in the beginning of our app, then the test continues without crashing.

**To Reproduce**

- [x] I have tested this issue on the latest Detox release and it still reproduces

The last known version that this worked for us was: **12.1.4**

Steps for reproduce:

I understand that this might be quite a technical issue to be able to investigate & reproduce, therefore I will try my best to find the time to put together a sample project which can reproduce the bug. Until then, the steps are:

1. Integrate realm DB into react native app
2. Begin Detox test
3. Have Detox test tap a button which will write to a realm DB

**Expected behavior**
It is expected that the detox test would not crash whenever performing a write operation to the Realm DB

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Detox: 14.2.0
 - React Native: 0.59.10
 - Node: 9.11.2
 - Device: iPhone 7 (simulator)
 - Xcode: 10.3
 - iOS: 12.4
 - macOS: 10.14.3
 - Realm: 2.29.0

**Device and Verbose Detox Logs**
Trace Logs: https://gist.github.com/Liamandrew/1bf549c9499d6006f3aa58955a70b0a8

Xcode Logs: https://gist.github.com/Liamandrew/c875c15d80c14f867d446212d0cb3bcb

Xcode stacktrace: https://gist.github.com/Liamandrew/e22b92f8279a46eb9ad46c0d5e4038ef

**Comment by LeoNatan** [comment]
Hmm I don't see Detox or Profiler as the cause of the crash.
Please follow https://github.com/wix/Detox/blob/master/docs/Guide.DebuggingInXcode.md
Add an exception breakpoint in Xcode and reproduce the issue.

Once you hit the exception, go to the top of the stack trace and type `po $arg1` in the debugger console. Post the result here. Thanks
