### ISSUE TITLE
Bring back printing of device logs location

### ISSUE THREAD

**Issue by Niryo** [wix/Detox#1647]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
When running detox, It would be nice to see the device log location like in previous versions of detox.

**Additional context**
This is a regression of this issue: https://github.com/wix/Detox/issues/1110
In older versions of detox there was a nice printing of the device log locations for ios, and now it's gone again in the current version.

**Comment by LeoNatan** [comment]
@noomorph Was it removed?

**Comment by noomorph** [comment]
@LeoNatan, no. It is still there: https://github.com/wix/Detox/blob/master/detox/src/devices/ios/AppleSimUtils.js#L319

**Comment by noomorph** [comment]
@Niryo, what version of Detox?

**Comment by Niryo** [comment]
@noomorph 14.3.2

**Comment by LeoNatan** [comment]
We discussed this online, and the feature works as expected.
Detox prints the command to use to get the logs. App developers need to hone the predicate to make it more readable for their own apps.
