### ISSUE TITLE
Server time-out when running build

### ISSUE THREAD

**Issue by gergobalogh** [wix/Detox#1653]
**Describe the bug**
After completing all the steps to install detox I try to run:
"detox build --configuration androi.emu.release" !
It fails with : 
> Task :app:lintVitalRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:releaseAndroidTestRuntimeClasspath'.
   > Could not resolve com.wix:detox:+.
     Required by:
         project :app
      > Failed to list versions for com.wix:detox.
         > Could not list versions using M2 pattern 'https://jitpack.io/[organisation]/[module]/[revision]/[artifact]-[revision](-[classifier])(.[ext])'.
            > Could not get resource 'https://jitpack.io/com/wix/detox/'.
               > Could not GET 'https://jitpack.io/com/wix/detox/'. Received status code 522 from server: Origin Connection Time-out

**To Reproduce**
Follow setup from github and try obtaining a build. 

- [x] I have tested this issue on the latest Detox release and it still reproduces
Yes
Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.
Install the app.
If possible, please provide a small demo project that reproduces the issue, or attach a video with the reproduction - this would be very appreciated.
![image](https://user-images.githubusercontent.com/31627579/64841645-5ecbae80-d608-11e9-9f59-561014ddc92a.png)

**Comment by Kattsallad** [comment]
For some reason jitpack is not responding to requests. Try adding www. to the jitpack URL in your build.gradle

Like this
maven { url 'https://www.jitpack.io' }
Not
maven { url 'https://jitpack.io' }

**Comment by AhmedGarhy** [comment]
thanks @Kattsallad  for your comment .. it worked with me .. adding www before the jitpack.io

**Comment by rotemmiz** [comment]
Just for the sake of documentation, this is not a Detox issue, we do not use Jitpack as a code/binary repository. 100% of our artifacts are located at npmjs, and are locally available when compiling Android projects.
We had multiple issues with jitpack recently internally. My suggestion to everyone is to stop using jitpack until the prove to be stable again. Instead, download the dependencies (aars) you need and add them to your git repo instead.
