### ISSUE TITLE
Unable to test apps with IAP (Sign In to iTunes Store dialog)

### ISSUE THREAD

**Issue by maximedupre** [wix/Detox#1658]
**Describe the bug**
Applications with in-app purchases will show a "Sign In to iTunes Store" dialog, and none of the detox matchers allow to interact with this dialog. This dialog occurs at the launch of the application, since applications with IAPs need to check the available purchases made by the current user.

**Expected behavior**
Detox matchers should work with these dialogs as well. For example, `element(by.text('Cancel')).tap();` should close the dialog.

**Screenshots**
![Screen Shot 2019-09-16 at 5 08 00 PM](https://user-images.githubusercontent.com/5158181/64993739-cc940680-d8a4-11e9-8067-3437bd978748.png)

**Environment (please complete the following information):**
 - Detox: `v14.0.3`
 - React Native: `v0.60.5`
 - Node: `v11.6.0`
 - Device: `Simulator iPhone X`
 - Xcode: `v10.3`

**Comment by LeoNatan** [comment]
There is nothing we can do about this currently. The problem is that the alert is presented out-of-process. I suggest you mock your APIs to not display this alert when testing.

**Comment by maximedupre** [comment]
Thanks for the answer. I understand. 

Is this the only way to mock my API?

https://github.com/wix/Detox/blob/master/docs/Guide.Mocking.md

**Comment by LeoNatan** [comment]
That's if you are using RN to access the API. For native, you can use something like OCMock.

**Comment by maximedupre** [comment]
Got it. Yes, I'm using react-native-iap to make in app purchases, so I'll follow your mocking guide.
