### ISSUE TITLE
Autolinking in React-Native 0.60+ for Android 

### ISSUE THREAD

**Issue by wamry** [wix/Detox#1667]
**Is your feature request related to a problem? Please describe.**
yes, there's no autolinking for android.

**Describe the solution you'd like**
use the autolinking feature

**Describe alternatives you've considered**
use the autolinking feature

**Additional context**
no other additional context

**Comment by wamry** [comment]
not stale, still waiting an answer

**Comment by d4vidi** [comment]
@wamry please provide more details. In what way are you trying to initiate autolinking, and why is it related to `Detox`?
