### ISSUE TITLE
Store and retrieve arbitrary non-UI data

### ISSUE THREAD

**Issue by cs01** [wix/Detox#1670]
**Is your feature request related to a problem? Please describe.**
We would like to record and capture arbitrary data from the app that cannot be found in the ui. For example, how long it took to load an element, or a list of all the screens that were loaded during a test. These are dynamic things that happen at runtime that we'd like to make assertions on from our test client (Jest).

**Describe the solution you'd like**
An Object of "markers" that is initialized to `{}` and can be updated during the test by the Application code. For example, `Detox.setMarker('tti', 3000)`.

 This value will be stored in the App and accessible from the test client via Detox's websocket connection. A new Detox action type could be added to retrieve this marker data. The test client would then do something like 
```
expect(await detox.getMarker('tti')).toBeLessThan(5000);
```
Maybe something like this already exists?

**Describe alternatives you've considered**
A hidden UI element that stores this marker data as a string of JSON. The content of this element can be retrieved with something like https://github.com/wix/Detox/issues/445, the string can be parsed into an object, and then assertions can be made on that object with Jest.

cc @rodrigos-facebook

**Comment by LeoNatan** [comment]
This sounds a lot like DetoxInstruments. We already have a rudimentary support for that, where a recording can be started for Detox tests.

**Comment by LeoNatan** [comment]
https://github.com/wix/DetoxInstruments
https://github.com/wix/DetoxInstruments/blob/master/Documentation/DeveloperAPIReferenceIntro.md

**Comment by LeoNatan** [comment]
Albeit, it is not possible to expect or match right now.

**Comment by cs01** [comment]
Thanks! Events look exactly like what we're looking for.

I see Detox Instruments doesn't support Android at this time though, which is a requirement for us. So for now we will go with our hack as described in the "alternatives".

**Comment by LeoNatan** [comment]
Yeah, unfortunately I have no experience with or time to learn Android development, and we can’t find resources to dedicate someone on the Android version. PRs are welcome! 😛

**Comment by cs01** [comment]
Sounds good, I will mention that to the team. We definitely appreciate all the work you and your team have done so far!

**Comment by LeoNatan** [comment]
Thank you for the kind words!
