### ISSUE TITLE
Detox hangs since updating to xcode 11 / iOS 13

### ISSUE THREAD

**Issue by SMJ93** [wix/Detox#1672]
**Describe the bug**

I updated to xcode 11 last night, since this Detox does not run on any of my projects (it just hangs on the first test before timing out)

I've tried updating to `14.3.3` but it still doesn't work.

**To Reproduce**

- [x] I have tested this issue on the latest Detox release and it still reproduces

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

1. Update to xcode 13 and run on an iOS 13 simulator

If possible, please provide a small demo project that reproduces the issue, or attach a video with the reproduction - this would be very appreciated.

**Expected behavior**
Detox should work with xcode 11 / iOS 13

**Screenshots**

**Environment (please complete the following information):**
 - Detox: 14.3.3
 - React Native: 0.59.10
 - Node: 10.5.0
 - Device: iPhone 6S simulator
 - Xcode: 11.0
 - iOS: 13
 - macOS: 10.14.6 

**Device and Verbose Detox Logs**
Provide the device and "trace" Detox logs so we can understand what happened. You can obtain them by passing the loglevel param: `detox test --loglevel trace`

```
detox[14394] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=testee not connected, cannot fw action (sessionId=e1c2b496-35c7-d463-a39d-6f2d73391953)
detox[14394] DEBUG: [DetoxServer.js/LOGIN] role=testee, sessionId=e1c2b496-35c7-d463-a39d-6f2d73391953
detox[14394] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=testee, sessionId=e1c2b496-35c7-d463-a39d-6f2d73391953
```

Hangs after initial login success

**iOS Framework Build Logs**

n/a

**Comment by LeoNatan** [comment]
Hi,

This is known and tracked in #1637. We have a PR ready with iOS 13 support, just waiting for our CI machines to upgrade.
