### ISSUE TITLE
Unable to run tests on release apk on azure pipeline

### ISSUE THREAD

**Issue by yogeshchoudhary147** [wix/Detox#1677]
I am trying to run detox tests on **pre** created release and test builds. I have create a testBuilds directory in app's root directory and added both apks i.e app-release.apk and app-release-androidTest.apk. I have modified detox configuration in package.json like this

`"android.emu.azure.release": {
        "binaryPath": "testBuilds/app-release.apk",
        "testBinaryPath": "testBuilds/app-release-androidTest.apk",
        "type": "android.emulator",
        "name": "xamarin_android_emulator"
      }`

 I am able to run detox tests on mac using `detox test -c android.emu.azure.release` directly without running `detox build -c android.emu.azure.release`. Everything is working as expected. 

But when I am trying to do same thing on azure pipeline. It just hangs. It is unclear if there was a problem during app-release.apk installation? Here are logs:

> detox[2784] INFO:  [test.js] node_modules/.bin/mocha --opts e2e/mocha.opts --configuration android.emu.azure.release --loglevel trace --grep :ios: --invert --artifacts-location "artifacts/android.emu.azure.release.2019-09-25 19-58-26Z" "e2e"
> 
> 
> detox[2785] INFO:  [DetoxServer.js] server listening on localhost:50193...
> detox[2785] DEBUG: [AsyncWebSocket.js/WEBSOCKET_OPEN] opened web socket to: ws://localhost:50193
> detox[2785] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"login","params":{"sessionId":"20a3f8b6-56a5-2937-5b00-36ed70e25c1b","role":"tester"},"messageId":0}
> detox[2785] DEBUG: [DetoxServer.js/LOGIN] role=tester, sessionId=20a3f8b6-56a5-2937-5b00-36ed70e25c1b
> detox[2785] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=tester, sessionId=20a3f8b6-56a5-2937-5b00-36ed70e25c1b
> detox[2785] TRACE: [AsyncWebSocket.js/WEBSOCKET_MESSAGE] {"type":"loginSuccess","params":{"sessionId":"20a3f8b6-56a5-2937-5b00-36ed70e25c1b","role":"tester"},"messageId":0}
>  
> detox[2785] DEBUG: [exec.js/EXEC_CMD, #0] /Users/vsts/Library/Android/sdk/emulator/emulator -list-avds --verbose
> detox[2785] TRACE: [exec.js/EXEC_SUCCESS, #0] xamarin_android_emulator
> 
> detox[2785] DEBUG: [exec.js/EXEC_CMD, #1] /Users/vsts/Library/Android/sdk/platform-tools/adb  devices
> detox[2785] DEBUG: [exec.js/EXEC_SUCCESS, #1] List of devices attached
> emulator-5554	device
> 
> 
> detox[2785] TRACE: [EmulatorTelnet.js/TELNET_CONNECTING] port: 5554, host: localhost
> detox[2785] DEBUG: [exec.js/EXEC_CMD, #2] /Users/vsts/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "getprop dev.bootcomplete"
> detox[2785] TRACE: [exec.js/EXEC_SUCCESS, #2] 1
> 
> detox[2785] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBootDevice({ coldBoot: false, deviceId: 'emulator-5554' })
> detox[2785] DEBUG: [exec.js/EXEC_CMD, #3] /Users/vsts/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "getprop ro.build.version.sdk"
> detox[2785] TRACE: [exec.js/EXEC_SUCCESS, #3] 27
> 
> detox[2785] DEBUG: [exec.js/EXEC_CMD, #4] /Users/vsts/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys power | grep \"^[ ]*m[UW].*=\""
> detox[2785] TRACE: [exec.js/EXEC_SUCCESS, #4]   mWakefulness=Awake
>   mWakefulnessChanging=false
>   mWakeLockSummary=0x1
>   mUserActivitySummary=0x1
>   mWakeUpWhenPluggedOrUnpluggedConfig=false
>   mWakeUpWhenPluggedOrUnpluggedInTheaterModeConfig=false
>   mUserActivityTimeoutOverrideFromWindowManager=-1
>   mUserInactiveOverrideFromWindowManager=false
> 
> detox[2785] DEBUG: [exec.js/EXEC_CMD, #5] /Users/vsts/Library/Android/sdk/build-tools/29.0.2/aapt dump badging "/Users/vsts/agent/2.155.1/work/1/s/testBuilds/app-release.apk" | grep -e "package: name="
> detox[2785] TRACE: [exec.js/EXEC_SUCCESS, #5] package: name='com.udaan.android' versionCode='14100' versionName='5.3' compileSdkVersion='28' compileSdkVersionCodename='9'
> 
> detox[2785] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeUninstallApp({ deviceId: 'emulator-5554', bundleId: 'com.udaan.android' })
> detox[2785] DEBUG: [exec.js/EXEC_CMD, #6] /Users/vsts/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "pm list packages com.udaan.android"
> detox[2785] TRACE: [exec.js/EXEC_SUCCESS, #6] 
> detox[2785] DEBUG: [exec.js/EXEC_CMD, #7] /Users/vsts/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "pm list packages com.udaan.android.test"
> detox[2785] TRACE: [exec.js/EXEC_SUCCESS, #7] 
> detox[2785] DEBUG: [exec.js/EXEC_CMD, #8] /Users/vsts/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -r -g -t "/Users/vsts/agent/2.155.1/work/1/s/testBuilds/app-release.apk"
>   1) "before all" hook in "{root}"
> 
>   0 passing (2m)
>   1 failing
> 
>   1) "before all" hook in "{root}":
>      Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
>   
> 
> 
> 
> detox[2785] TRACE: [exec.js/EXEC_SUCCESS, #8] Performing Streamed Install
> Success
> 
> detox[2785] DEBUG: [exec.js/EXEC_CMD, #9] /Users/vsts/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -r -g -t "/Users/vsts/agent/2.155.1/work/1/s/testBuilds/app-release-androidTest.apk"
> detox[2785] TRACE: [exec.js/EXEC_SUCCESS, #9] Performing Streamed Install
> Success
> 
> detox[2785] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeTerminateApp({ deviceId: 'emulator-5554', bundleId: 'com.udaan.android' })
> detox[2785] DEBUG: [exec.js/EXEC_CMD, #10] /Users/vsts/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "am force-stop com.udaan.android"
> detox[2785] TRACE: [exec.js/EXEC_SUCCESS, #10] 
> detox[2785] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeLaunchApp({ deviceId: 'emulator-5554',
>   bundleId: 'com.udaan.android',
>   launchArgs: 
>    { detoxServer: 'ws://localhost:50193',
>      detoxSessionId: '20a3f8b6-56a5-2937-5b00-36ed70e25c1b' } })
> detox[2785] DEBUG: [exec.js/EXEC_CMD, #11] /Users/vsts/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "date +\"%m-%d %T.000\""
> detox[2785] TRACE: [exec.js/EXEC_SUCCESS, #11] 09-25 20:00:48.000
> 
> detox[2785] DEBUG: [exec.js/EXEC_CMD, #12] /Users/vsts/Library/Android/sdk/platform-tools/adb -s emulator-5554 reverse tcp:50193 tcp:50193
> detox[2785] TRACE: [exec.js/EXEC_SUCCESS, #12] 
> detox[2785] DEBUG: [exec.js/EXEC_CMD, #13] /Users/vsts/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "pm list instrumentation"
> detox[2785] TRACE: [exec.js/EXEC_SUCCESS, #13] instrumentation:com.android.emulator.smoketests/android.support.test.runner.AndroidJUnitRunner (target=com.android.emulator.smoketests)
> instrumentation:com.udaan.android.test/androidx.test.runner.AndroidJUnitRunner (target=com.udaan.android)
> instrumentation:org.chromium.webview_shell/.WebViewLayoutTestRunner (target=org.chromium.webview_shell)
> 
> detox[2785] DEBUG: [exec.js/SPAWN_CMD, #14] [pid=2805] /Users/vsts/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am instrument -w -r -e detoxServer ws://localhost:50193 -e detoxSessionId 20a3f8b6-56a5-2937-5b00-36ed70e25c1b -e debug ZmFsc2U= com.udaan.android.test/androidx.test.runner.AndroidJUnitRunner
> detox[2785] DEBUG: [exec.js/EXEC_CMD, #15] /Users/vsts/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "ps | grep \"com\.udaan\.android$\""
> detox[2785] TRACE: [exec.js/EXEC_SUCCESS, #15] u0_a79        4979  1675 1399932  62520                     0 R com.udaan.android
> 
> _detox[4979] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onLaunchApp({ deviceId: 'emulator-5554',
>   bundleId: 'com.udaan.android',
>   launchArgs: 
>    { detoxServer: 'ws://localhost:50193',
>      detoxSessionId: '20a3f8b6-56a5-2937-5b00-36ed70e25c1b' },
>   pid: 4979 })
> detox[2785] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"isReady","params":{},"messageId":-1000}
> detox[2785] TRACE: [DetoxServer.js/MESSAGE] role=tester action=isReady (sessionId=20a3f8b6-56a5-2937-5b00-36ed70e25c1b)
> detox[2785] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=testee not connected, cannot fw action (sessionId=20a3f8b6-56a5-2937-5b00-36ed70e25c1b)
> detox[2785] TRACE: [exec.js/SPAWN_STDOUT, #14] INSTRUMENTATION_STATUS: class=com.Udaan.DetoxTest
> INSTRUMENTATION_STATUS: current=1
> INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
> INSTRUMENTATION_STATUS: numtests=1
> INSTRUMENTATION_STATUS: stream=
> com.Udaan.DetoxTest:
> INSTRUMENTATION_STATUS: test=runDetoxTests
> INSTRUMENTATION_STATUS_CODE: 1
> 
> detox[2785] DEBUG: [DetoxServer.js/LOGIN] role=testee, sessionId=20a3f8b6-56a5-2937-5b00-36ed70e25c1b
> detox[2785] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=testee, sessionId=20a3f8b6-56a5-2937-5b00-36ed70e25c1b
> detox[2785] TRACE: [DetoxServer.js/MESSAGE] role=testee action=ready (sessionId=20a3f8b6-56a5-2937-5b00-36ed70e25c1b)
> detox[2785] TRACE: [AsyncWebSocket.js/WEBSOCKET_MESSAGE] {"messageId":-1000,"type":"ready","params":{}}
>  
> detox[2785] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeAll()

**Comment by yogeshchoudhary147** [comment]
@d4vidi @noomorph @LeoNatan Guys, can you please have a look at this and tell me what could be the problem.

**Comment by rotemmiz** [comment]
We never tried running on Azure. Android emulator support on most CIs is pretty limited, and is very buggy (according to my experience at least).
I can not guarantee this will work, but we can debug this together.

Add screenshots and logs as test artifacts and let's see what they are telling us.

**Comment by yogeshchoudhary147** [comment]
@rotemmiz Thanks a lot. 

It throws an error while installing the apk but later it prints a success message and then hangs forever. Here are the logs:

> detox[2817] INFO:  [test.js] node_modules/.bin/mocha --opts e2e/mocha.opts --configuration android.emu.azure.release --loglevel trace --grep :ios: --invert --artifacts-location "artifacts/android.emu.azure.release.2019-10-02 07-37-37Z" "e2e"
> 
> 
> detox[2818] INFO:  [DetoxServer.js] server listening on localhost:49957...
> detox[2818] DEBUG: [AsyncWebSocket.js/WEBSOCKET_OPEN] opened web socket to: ws://localhost:49957
> detox[2818] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"login","params":{"sessionId":"a993065f-cf5f-50d6-10f2-80bcb6742e30","role":"tester"},"messageId":0}
> detox[2818] DEBUG: [DetoxServer.js/LOGIN] role=tester, sessionId=a993065f-cf5f-50d6-10f2-80bcb6742e30
> detox[2818] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=tester, sessionId=a993065f-cf5f-50d6-10f2-80bcb6742e30
> detox[2818] TRACE: [AsyncWebSocket.js/WEBSOCKET_MESSAGE] {"type":"loginSuccess","params":{"sessionId":"a993065f-cf5f-50d6-10f2-80bcb6742e30","role":"tester"},"messageId":0}
>  
> detox[2818] DEBUG: [exec.js/EXEC_CMD, #0] /Users/vsts/Library/Android/sdk/emulator/emulator -list-avds --verbose
> detox[2818] TRACE: [exec.js/EXEC_SUCCESS, #0] xamarin_android_emulator
> 
> detox[2818] DEBUG: [exec.js/EXEC_CMD, #1] /Users/vsts/Library/Android/sdk/platform-tools/adb  devices
> detox[2818] DEBUG: [exec.js/EXEC_SUCCESS, #1] List of devices attached
> emulator-5554	device
> 
> 
> detox[2818] TRACE: [EmulatorTelnet.js/TELNET_CONNECTING] port: 5554, host: localhost
> detox[2818] DEBUG: [exec.js/EXEC_CMD, #2] /Users/vsts/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "getprop dev.bootcomplete"
> detox[2818] TRACE: [exec.js/EXEC_SUCCESS, #2] 1
> 
> detox[2818] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBootDevice({ coldBoot: false, deviceId: 'emulator-5554' })
> detox[2818] DEBUG: [exec.js/EXEC_CMD, #3] /Users/vsts/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "getprop ro.build.version.sdk"
> detox[2818] TRACE: [exec.js/EXEC_SUCCESS, #3] 27
> 
> detox[2818] DEBUG: [exec.js/EXEC_CMD, #4] /Users/vsts/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys power | grep \"^[ ]*m[UW].*=\""
> detox[2818] TRACE: [exec.js/EXEC_SUCCESS, #4]   mWakefulness=Awake
>   mWakefulnessChanging=false
>   mWakeLockSummary=0x1
>   mUserActivitySummary=0x1
>   mWakeUpWhenPluggedOrUnpluggedConfig=false
>   mWakeUpWhenPluggedOrUnpluggedInTheaterModeConfig=false
>   mUserActivityTimeoutOverrideFromWindowManager=-1
>   mUserInactiveOverrideFromWindowManager=false
> 
> detox[2818] DEBUG: [exec.js/EXEC_CMD, #5] /Users/vsts/Library/Android/sdk/build-tools/29.0.2/aapt dump badging "/Users/vsts/agent/2.155.1/work/1/s/testBuilds/app-release.apk" | grep -e "package: name="
> detox[2818] TRACE: [exec.js/EXEC_SUCCESS, #5] package: name='com.udaan.android' versionCode='14110' versionName='5.4' compileSdkVersion='28' compileSdkVersionCodename='9'
> 
> detox[2818] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeUninstallApp({ deviceId: 'emulator-5554', bundleId: 'com.udaan.android' })
> detox[2818] DEBUG: [exec.js/EXEC_CMD, #6] /Users/vsts/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "pm list packages com.udaan.android"
> detox[2818] TRACE: [exec.js/EXEC_SUCCESS, #6] 
> detox[2818] DEBUG: [exec.js/EXEC_CMD, #7] /Users/vsts/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "pm list packages com.udaan.android.test"
> detox[2818] TRACE: [exec.js/EXEC_SUCCESS, #7] 
> detox[2818] DEBUG: [exec.js/EXEC_CMD, #8] /Users/vsts/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -r -g -t "/Users/vsts/agent/2.155.1/work/1/s/testBuilds/app-release.apk"
>   1) "before all" hook in "{root}"
> 
>   0 passing (2m)
>   1 failing
> 
>   1) "before all" hook in "{root}":
>      Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
>   
> 
> 
> 
> detox[2818] TRACE: [exec.js/EXEC_SUCCESS, #8] Performing Streamed Install
> Success
> 
> detox[2818] DEBUG: [exec.js/EXEC_CMD, #9] /Users/vsts/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -r -g -t "/Users/vsts/agent/2.155.1/work/1/s/testBuilds/app-release-androidTest.apk"
> detox[2818] TRACE: [exec.js/EXEC_SUCCESS, #9] Performing Streamed Install
> Success
> 
> detox[2818] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeAll()
> detox[2818] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeLaunchApp({ deviceId: 'emulator-5554',
>   bundleId: 'com.udaan.android',
>   launchArgs: 
>    { detoxServer: 'ws://localhost:49957',
>      detoxSessionId: 'a993065f-cf5f-50d6-10f2-80bcb6742e30' } })
> detox[2818] DEBUG: [exec.js/EXEC_CMD, #10] /Users/vsts/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "date +\"%m-%d %T.000\""
> detox[2818] TRACE: [exec.js/EXEC_SUCCESS, #10] 10-02 07:39:44.000
> 
> detox[2818] DEBUG: [exec.js/EXEC_CMD, #11] /Users/vsts/Library/Android/sdk/platform-tools/adb -s emulator-5554 reverse tcp:49957 tcp:49957
> detox[2818] TRACE: [exec.js/EXEC_SUCCESS, #11] 
> detox[2818] DEBUG: [exec.js/EXEC_CMD, #12] /Users/vsts/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "pm list instrumentation"
> detox[2818] TRACE: [exec.js/EXEC_SUCCESS, #12] instrumentation:com.android.emulator.smoketests/android.support.test.runner.AndroidJUnitRunner (target=com.android.emulator.smoketests)
> instrumentation:com.udaan.android.test/androidx.test.runner.AndroidJUnitRunner (target=com.udaan.android)
> instrumentation:org.chromium.webview_shell/.WebViewLayoutTestRunner (target=org.chromium.webview_shell)
> 
> detox[2818] DEBUG: [exec.js/SPAWN_CMD, #13] [pid=2834] /Users/vsts/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am instrument -w -r -e detoxServer ws://localhost:49957 -e detoxSessionId a993065f-cf5f-50d6-10f2-80bcb6742e30 -e debug ZmFsc2U= com.udaan.android.test/androidx.test.runner.AndroidJUnitRunner
> detox[2818] DEBUG: [exec.js/EXEC_CMD, #14] /Users/vsts/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "ps | grep \"com\.udaan\.android$\""
> detox[2818] TRACE: [exec.js/EXEC_SUCCESS, #14] u0_a79        4945  1673 1401968  73748                     0 R com.udaan.android
> 
> detox[4945] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onLaunchApp({ deviceId: 'emulator-5554',
>   bundleId: 'com.udaan.android',
>   launchArgs: 
>    { detoxServer: 'ws://localhost:49957',
>      detoxSessionId: 'a993065f-cf5f-50d6-10f2-80bcb6742e30' },
>   pid: 4945 })
> detox[2818] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"isReady","params":{},"messageId":-1000}
> detox[2818] TRACE: [DetoxServer.js/MESSAGE] role=tester action=isReady (sessionId=a993065f-cf5f-50d6-10f2-80bcb6742e30)
> detox[2818] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=testee not connected, cannot fw action (sessionId=a993065f-cf5f-50d6-10f2-80bcb6742e30)
> detox[2818] TRACE: [exec.js/SPAWN_STDOUT, #13] INSTRUMENTATION_STATUS: class=com.Udaan.DetoxTest
> INSTRUMENTATION_STATUS: current=1
> INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
> INSTRUMENTATION_STATUS: numtests=1
> INSTRUMENTATION_STATUS: stream=
> com.Udaan.DetoxTest:
> INSTRUMENTATION_STATUS: test=runDetoxTests
> INSTRUMENTATION_STATUS_CODE: 1
> 
> detox[2818] DEBUG: [DetoxServer.js/LOGIN] role=testee, sessionId=a993065f-cf5f-50d6-10f2-80bcb6742e30
> detox[2818] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=testee, sessionId=a993065f-cf5f-50d6-10f2-80bcb6742e30
> detox[2818] TRACE: [DetoxServer.js/MESSAGE] role=testee action=ready (sessionId=a993065f-cf5f-50d6-10f2-80bcb6742e30)
> detox[2818] TRACE: [AsyncWebSocket.js/WEBSOCKET_MESSAGE] {"messageId":-1000,"type":"ready","params":{}}

**Comment by d4vidi** [comment]
Hi. I'd start by increasing the timeout significantly. Emulators on CI
agents are typically slowwww

**Comment by yogeshchoudhary147** [comment]
@d4vidi I want to call out one thing. I have pre created both release apk and build apk to be tested. So I run `detox test` directly without running `detox build` and it hangs.

But when I first build the test apk using `./gradlew assembleAndroidTest -DtestBuildType=release` and use pre created release apk, then everything works fine as expected.

So, it surely has something to do with `./gradlew assembleAndroidTest -DtestBuildType=release`. Do you still think increasing timeout can help?
