### ISSUE TITLE
scroll method not working

### ISSUE THREAD

**Issue by yogeshchoudhary147** [wix/Detox#1681]
The `scroll` method has stopped working after last update. Sample code which is working in 14.3.3 but not in 14.3.4.

`await element(by.id('menu_list')).scroll(100, 'down');`

react-native version : 0.59.10

**Error logs :** 

>      Error: No such accessible method: scrollInDirection() on class: com.wix.detox.espresso.DetoxAction
>       at Client.execute (node_modules/detox/src/client/Client.js:92:28)
>       at InvocationManager.execute (node_modules/detox/src/invoke.js:11:39)
>       at ActionInteraction.execute (node_modules/detox/src/android/expect.js:128:35)
>       at Element.scroll (node_modules/detox/src/android/expect.js:249:146)
>       at Context.it (e2e/firstTest.spec.js:55:39)
>       at <anonymous>
>       at process._tickCallback (internal/process/next_tick.js:189:7)

Also `scroll` with `whileElement` has stopped working.

**Comment by Antonhansel** [comment]
I confirm that scroll isn't working on iOS either

This works:
```
      await element(by.id('wrapperScrollViewCompanyDirector')).swipe('up');
```

This throws Interaction cannot continue because the desired element was not found. on version "detox": "12.3.0", 
```
      await element(by.id('wrapperScrollViewCompanyDirector')).scroll(50, 'up');
```

**Comment by mentormategeorgirusev** [comment]
@yogeshchoudhary147 - I see similar issue on detox 14.3.4
{ Error: No such accessible method: scrollInDirectionStaleAtEdge() on class: com.wix.detox.espresso.DetoxAction}

What is even stranger it works fine locally, and fails on CI.

Anyhow I'm about to check it with latest detox version, meanwhile if you have a solution/workaround please do share.

**Comment by mentormategeorgirusev** [comment]
It seems everything is resolved. I'm currently using version 14.5.1

**Comment by d4vidi** [comment]
This typically happens when the JS and native-android code are of different versions.
The solution is thus to rebuild the test apk from scratch (e.g. `./gradlew assembleAndroidTest`)
