### ISSUE TITLE
Detox Build for Android Failing

### ISSUE THREAD

**Issue by ReshmiCode** [wix/Detox#1682]
**Describe the bug**
When I run detox build -c android, it is failing.

**Environment (please complete the following information):**
 - Detox: 14.3.4
 - React Native: 0.60.3
 - Node: 10.15.3
 - Device: 5.1 WVGA

**Device and Verbose Detox Logs**
[error.txt](https://github.com/wix/Detox/files/3673700/error.txt)

**Comment by noomorph** [comment]
What is the project that you are building?

**Comment by maamounapprise** [comment]
getting the same error

**Comment by rotemmiz** [comment]
React Native 0.60 is still not 100% supported unfortunately, this includes compilation issues. We hope this will be resolved soon.

**Comment by ReshmiCode** [comment]
It is a private repo. Android worked before with RN 0.60.3 so I think something in a newer Detox is breaking or some dependencies changed. If I have the time I can try to make a basic reproducing repo but I assumed it was just something that needed to be changed/added in the gradle file.

**Comment by ReshmiCode** [comment]
I tried running it again and the build passed but the tests showed this error. When building it again after this, it fails with the same error in the original comment in the issue.
[error.txt](https://github.com/wix/Detox/files/3678472/error.txt)

**Comment by rotemmiz** [comment]
What have you tried? Can you please be specific?
Did you try two different versions of detox on the same project (which?), did it compile on one and failed on the other?

**Comment by ReshmiCode** [comment]
I ran it with the same version of Detox, 14.3.4. I ran detox build, detox test, then detox build in that order with 2 minutes between each command after it finished running.

**Comment by d4vidi** [comment]
Closing in favor of #1689. Please refer to the [versions support table](https://github.com/wix/Detox/#react-native) for latest info on this.

**Comment by d4vidi** [comment]
@ReshmiCode you simply have a discrepancy among the required kotlin standard lib version through various deps. This can be resolved by either excluding kotlin from `Detox`'s deps ([example](https://discuss.gradle.org/t/how-do-i-exclude-specific-transitive-dependencies-of-something-i-depend-on/17991)) or by forcing a specific kotlin version globally ([stackoverflow](https://stackoverflow.com/a/28444896/453052)).
