### ISSUE TITLE
sendToHome / waitForBackground broken on Detox 14.3.4 and iOS 13

### ISSUE THREAD

**Issue by brandons** [wix/Detox#1684]
**Describe the bug**
`device.sendToHome()` on Detox 14.3.4 with our app compiled for iOS 13 no longer works. It will time out every time, on `waitForBackground`,

**To Reproduce**
- [x ] I have tested this issue on the latest Detox release and it still reproduces

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.
1. Create a test which calls `device.sendToHome()`
2. Run the test
3. Observe the test will timeout on `waitForBackground`

This functionality was previously working for us on Detox 14.0.3 compiled for iOS 12.

**Expected behavior**
waitForBackground should resolve correctly and the test should pass.

**Environment (please complete the following information):**
 - Detox: 14.3.4
 - React Native: 0.61
 - Node: 8.11.2
 - Device: iOS Simulator iPhone Xs
 - Xcode: 11
 - iOS: 13
 - macOS: 10.14.6

**Device and Verbose Detox Logs**
Provide the device and "trace" Detox logs so we can understand what happened. You can obtain them by passing the loglevel param: `detox test --loglevel trace`

```
detox[5448] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onLaunchApp({ bundleId: 'com.mobile.ios.testnet',
  deviceId: 'B5A29C5C-6811-44DD-A9A0-5AC4ABA4AA3E',
  launchArgs: 
   { detoxServer: 'ws://localhost:50901',
     detoxSessionId: '565e964c-ba97-3e99-f196-a9d4aaaa67cc' },
  pid: 5448 })
detox[5373] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"isReady","params":{},"messageId":-1000}
detox[5373] TRACE: [DetoxServer.js/MESSAGE] role=tester action=isReady (sessionId=565e964c-ba97-3e99-f196-a9d4aaaa67cc)
detox[5373] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=testee not connected, cannot fw action (sessionId=565e964c-ba97-3e99-f196-a9d4aaaa67cc)
detox[5373] DEBUG: [DetoxServer.js/LOGIN] role=testee, sessionId=565e964c-ba97-3e99-f196-a9d4aaaa67cc
detox[5373] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=testee, sessionId=565e964c-ba97-3e99-f196-a9d4aaaa67cc
detox[5373] TRACE: [DetoxServer.js/MESSAGE] role=testee action=ready (sessionId=565e964c-ba97-3e99-f196-a9d4aaaa67cc)
detox[5373] TRACE: [AsyncWebSocket.js/WEBSOCKET_MESSAGE] {"type":"ready","messageId":-1000,"params":{}}
 
detox[5373] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"waitForActive","params":{},"messageId":1}
detox[5373] TRACE: [DetoxServer.js/MESSAGE] role=tester action=waitForActive (sessionId=565e964c-ba97-3e99-f196-a9d4aaaa67cc)
detox[5373] TRACE: [DetoxServer.js/MESSAGE] role=testee action=waitForActiveDone (sessionId=565e964c-ba97-3e99-f196-a9d4aaaa67cc)
detox[5373] TRACE: [AsyncWebSocket.js/WEBSOCKET_MESSAGE] {"type":"waitForActiveDone","messageId":1,"params":{}}
 
detox[5373] DEBUG: [exec.js/EXEC_CMD, #11] /usr/bin/xcrun simctl launch B5A29C5C-6811-44DD-A9A0-5AC4ABA4AA3E com.apple.springboard
detox[5373] TRACE: [exec.js/EXEC_SUCCESS, #11] com.apple.springboard: 5434

detox[5373] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"waitForBackground","params":{},"messageId":2}
detox[5373] TRACE: [DetoxServer.js/MESSAGE] role=tester action=waitForBackground (sessionId=565e964c-ba97-3e99-f196-a9d4aaaa67cc)
detox[5373] TRACE: [Detox.js/DETOX_AFTER_EACH] failed test: "waitForBackground broken test"
detox[5373] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onAfterEach({ title: 'waitForBackground broken test',
  fullName: 'waitForBackground broken test',
  status: 'failed',
  timedOut: true })
detox[5373] WARN:  [Client.js/PENDING_REQUESTS] App has not responded to the network requests below:
  (id = 2) waitForBackground: {}

That might be the reason why the test "waitForBackground broken test" has timed out.

detox[5373] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onAfterAll()
detox[5373] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"cleanup","params":{"stopRunner":true},"messageId":-49642}
detox[5373] TRACE: [DetoxServer.js/MESSAGE] role=tester action=cleanup (sessionId=565e964c-ba97-3e99-f196-a9d4aaaa67cc)
detox[5373] TRACE: [DetoxServer.js/MESSAGE] role=testee action=cleanupDone (sessionId=565e964c-ba97-3e99-f196-a9d4aaaa67cc)
detox[5373] TRACE: [AsyncWebSocket.js/WEBSOCKET_MESSAGE] {"type":"cleanupDone","messageId":-49642,"params":{}}
 
detox[5373] DEBUG: [DetoxServer.js/DISCONNECT] role=tester, sessionId=565e964c-ba97-3e99-f196-a9d4aaaa67cc
detox[5373] DEBUG: [DetoxServer.js/DISCONNECT] role=testee, sessionId=565e964c-ba97-3e99-f196-a9d4aaaa67cc
detox[5373] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=tester not connected, cannot fw action (sessionId=565e964c-ba97-3e99-f196-a9d4aaaa67cc)
detox[5373] DEBUG: [DetoxServer.js/WS_CLOSE] Detox server connections terminated gracefully
detox[5373] DEBUG: [exec.js/EXEC_CMD, #12] /usr/bin/xcrun simctl shutdown B5A29C5C-6811-44DD-A9A0-5AC4ABA4AA3E
detox[5373] DEBUG: [exec.js/EXEC_TRY, #12] Shutting down B5A29C5C-6811-44DD-A9A0-5AC4ABA4AA3E...
waitForBackground broken test [FAIL]```

**Comment by LeoNatan** [comment]
Hmm thanks, I will take a look. Does the app actually go to background and just stuck, or does it remain on screen?

**Comment by brandons** [comment]
@LeoNatan Yes, the app goes into the background correctly, it's just the `waitForBackground` callback that times out. Do you think it could be related to background process changes in iOS 13?

**Comment by LeoNatan** [comment]
I’m not sure. It shouldn’t be, as this is a very simple check for a system notification. Unless there is a bug in iOS 13 on simulator.

**Comment by LeoNatan** [comment]
I haven't run this yet.
One potential issue I see is that the [`_waitForState:`](https://github.com/wix/Detox/blob/05afbd5b2623176a46deeddac1155a4f3ac30435/detox/ios/Detox/DetoxManager.m#L119) method does not check if the application is already in the background, and thus might miss the system and wait forever, because the app is already in the background. I'll try to fix this tomorrow.

**Comment by LeoNatan** [comment]
I am unable to reproduce. On the demo project, we already have `sendToHome()` test which succeeds on CI, and locally it also succeeds.

**Comment by LeoNatan** [comment]
Could you pls follow the sync debug docs to see what is going on while the test is stalled. Thanks

**Comment by brandons** [comment]
Thanks for looking into it. I followed all of the sync debug steps and was unable to find any helpful information. Just 'react native thread is busy'. I ended up disabling synchronization before calling `sendToHome` and re-enabling after relaunching the app. If it's not reproducible for anyone else then we can close the issue.

**Comment by LeoNatan** [comment]
I have been unable to reproduce. If you ever find more information, please open a new issue. Thanks
