### ISSUE TITLE
Upgrade Android to RN .60.x

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#1689]
**Is your feature request related to a problem? Please describe.**
Android currently does not support latest RN 0.60. Namely, at least one build issue exists that needs to be resolved (ref - #1534).
Also, these seem relevant/dups: #1667, #1682, #1631.

**Describe the solution you'd like**
Support latest RN .60 both as the library and Detox' internal demo projects.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by LeoNatan** [comment]
Perhaps even 0.61? It's already out.

**Comment by d4vidi** [comment]
@LeoNatan by all means, but we already have noticeable issues with .60 so we'll take it step by step.

**Comment by sytolk** [comment]
```
"react-native": "0.60.6",
"detox": "^14.5.0",
```
```
android.useAndroidX=true
android.enableJetifier=true
```
```
"detox": {
    "test-runner": "jest",
    "configurations": {
      "android.emu.debug": {
        "binaryPath": "android/app/build/outputs/apk/debug/app-debug.apk",
        "build": "npx jetifier && cd ./android && ./gradlew app:assembleDebug app:assembleAndroidTest -DtestBuildType=debug  && cd ..",
        "type": "android.emulator",
        "name": "Nexus_5X_API_24"
      }
    }
  }
```
Proguard is not enabled on debug build. I have this exception after `await device.launchApp(..` 
```
2019-10-17 10:17:45.459 3423-3423/? W/ClassPathPackageInfoSource: Cannot load class. Make sure it is in your apk. Class name: 'androidx.core.app.AppComponentFactory'. Message: androidx.core.app.AppComponentFactory
    java.lang.ClassNotFoundException: androidx.core.app.AppComponentFactory
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:400)
        at android.test.ClassPathPackageInfoSource.createPackageInfo(ClassPathPackageInfoSource.java:89)
```

**Comment by hanwencheng** [comment]
🍺We are using react 0.60.5 with detox 14.5.0, test all works well on Emulator. But the test failed on the Real device, got same problem like described in #1174 .

**Comment by LeoNatan** [comment]
Thanks for your reports, guys. Please don't clutter the thread with "me too" comments; this is a priority for us, and we will work on this once we are able to.
