### ISSUE TITLE
    Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout

### ISSUE THREAD

**Issue by KashifJavaid** [wix/Detox#1691]
#### Detox  , Node , Device IOS  , Xcode 11 and macOS Versions

* Detox: 14.4.0
* React Native: 0.61.2
* Node: 10.16.0 
* Device: Simulator iPhone 11
* Xcode: 11 
* macOS: 10.14.6 (Mac OS Mojave)

#### Device and verbose Detox logs
`
detox[77643] INFO:  [test.js] configuration="ios.sim.debug" loglevel="verbose" artifactsLocation="artifacts/ios.sim.debug.2019-10-07 15-21-17Z" recordLogs="none" takeScreenshots="manual" recordVideos="none" recordPerformance="none" reportSpecs=true node_modules/.bin/jest --config=e2e/config.json --maxWorkers=1 '--testNamePattern=^((?!:android:).)*$' "e2e"
detox[77645] INFO:  [DetoxServer.js] server listening on localhost:61069...
detox[77645] DEBUG: [AsyncWebSocket.js/WEBSOCKET_OPEN] opened web socket to: ws://localhost:61069
detox[77645] DEBUG: [DetoxServer.js/LOGIN] role=tester, sessionId=6a8aee11-0b31-ba0a-5442-90a5ae1f7484
detox[77645] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=tester, sessionId=6a8aee11-0b31-ba0a-5442-90a5ae1f7484
detox[77645] DEBUG: [exec.js/EXEC_CMD, #0] /usr/bin/xcrun simctl list -j
detox[77645] DEBUG: [exec.js/EXEC_CMD, #1] applesimutils --list --byType "iPhone 11" --byOS "13.0"
detox[77645] DEBUG: [exec.js/EXEC_TRY, #1] Searching for device matching iPhone 11...
detox[77645] DEBUG: [exec.js/EXEC_CMD, #2] applesimutils --list --byId "994A531F-5E17-457C-AC93-37875A358B01"
detox[77645] DEBUG: [exec.js/EXEC_CMD, #3] /usr/bin/xcrun simctl uninstall 994A531F-5E17-457C-AC93-37875A358B01 org.reactjs.native.example.DetoxNew
detox[77645] DEBUG: [exec.js/EXEC_TRY, #3] Uninstalling org.reactjs.native.example.DetoxNew...
detox[77645] DEBUG: [exec.js/EXEC_SUCCESS, #3] org.reactjs.native.example.DetoxNew uninstalled
detox[77645] DEBUG: [exec.js/EXEC_CMD, #4] /usr/bin/xcrun simctl install 994A531F-5E17-457C-AC93-37875A358B01 "/Users/kashifj/Desktop/DetoxNew/ios/build/Build/Products/Debug-iphonesimulator/DetoxNew.app"
detox[77645] DEBUG: [exec.js/EXEC_TRY, #4] Installing /Users/kashifj/Desktop/DetoxNew/ios/build/Build/Products/Debug-iphonesimulator/DetoxNew.app...
detox[77645] DEBUG: [exec.js/EXEC_SUCCESS, #4] /Users/kashifj/Desktop/DetoxNew/ios/build/Build/Products/Debug-iphonesimulator/DetoxNew.app installed
detox[77645] DEBUG: [exec.js/EXEC_CMD, #5] /usr/bin/xcrun simctl terminate 994A531F-5E17-457C-AC93-37875A358B01 org.reactjs.native.example.DetoxNew
detox[77645] DEBUG: [exec.js/EXEC_TRY, #5] Terminating org.reactjs.native.example.DetoxNew...
detox[77645] DEBUG: [exec.js/EXEC_SUCCESS, #5] org.reactjs.native.example.DetoxNew terminated
detox[77645] DEBUG: [exec.js/EXEC_CMD, #6] SIMCTL_CHILD_DYLD_INSERT_LIBRARIES="/Users/kashifj/Library/Detox/ios/9834748629ea82fcee760fb77401efb6b6d37e36/Detox.framework/Detox" /usr/bin/xcrun simctl launch 994A531F-5E17-457C-AC93-37875A358B01 org.reactjs.native.example.DetoxNew --args -detoxServer "ws://localhost:61069" -detoxSessionId "6a8aee11-0b31-ba0a-5442-90a5ae1f7484"
detox[77645] DEBUG: [exec.js/EXEC_TRY, #6] Launching org.reactjs.native.example.DetoxNew...
detox[77645] DEBUG: [exec.js/EXEC_CMD, #7] /usr/bin/xcrun simctl get_app_container 994A531F-5E17-457C-AC93-37875A358B01 org.reactjs.native.example.DetoxNew
detox[77645] INFO:  [AppleSimUtils.js] org.reactjs.native.example.DetoxNew launched. To watch simulator logs, run:
        /usr/bin/xcrun simctl spawn 994A531F-5E17-457C-AC93-37875A358B01 log stream --level debug --style compact --predicate 'processImagePath beginsWith "/Users/kashifj/Library/Developer/CoreSimulator/Devices/994A531F-5E17-457C-AC93-37875A358B01/data/Containers/Bundle/Application/709B6D73-4408-4192-9806-C7AE05E65417/DetoxNew.app"'
detox[77645] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=testee not connected, cannot fw action (sessionId=6a8aee11-0b31-ba0a-5442-90a5ae1f7484)
detox[77645] DEBUG: [DetoxServer.js/LOGIN] role=testee, sessionId=6a8aee11-0b31-ba0a-5442-90a5ae1f7484
detox[77645] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=testee, sessionId=6a8aee11-0b31-ba0a-5442-90a5ae1f7484
Example: should have welcome screen
Example: should have welcome screen [FAIL]

detox[77645] WARN:  [Client.js/PENDING_REQUESTS] App has not responded to the network requests below:
  (id = 2) invoke: {"target":{"type":"Invocation","value":{"target":{"type":"EarlGrey","value":"instance"},"method":"detox_selectElementWithMatcher:","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"GREYMatchers"},"method":"matcherForAccessibilityID:","args":[{"type":"NSString","value":"welcome"}]}}]}},"method":"assertWithMatcher:","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"GREYMatchers"},"method":"matcherForSufficientlyVisible","args":[]}}]}
  (id = -1000) reactNativeReload: {}

That might be the reason why the test "Example should have welcome screen" has timed out.

detox[77645] DEBUG: [DetoxServer.js/DISCONNECT] role=tester, sessionId=6a8aee11-0b31-ba0a-5442-90a5ae1f7484
detox[77645] DEBUG: [DetoxServer.js/DISCONNECT] role=testee, sessionId=6a8aee11-0b31-ba0a-5442-90a5ae1f7484
detox[77645] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=tester not connected, cannot fw action (sessionId=6a8aee11-0b31-ba0a-5442-90a5ae1f7484)
detox[77645] DEBUG: [DetoxServer.js/WS_CLOSE] Detox server connections terminated gracefully
 FAIL  e2e/firstTest.spec.js (246.977s)
  Example
    ✕ should have welcome screen (240016ms)

  ● Example › should have welcome screen

    Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.

      at mapper (../node_modules/jest-jasmine2/build/queueRunner.js:25:45)

  ● Example › should have welcome screen

    : Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.Error:

      4 |   });
      5 | 
    > 6 |   it('should have welcome screen', async () => {
        |   ^
      7 |     await expect(element(by.id('welcome'))).toBeVisible();
      8 |   });
      9 | 

      at new Spec (../node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.it (firstTest.spec.js:6:3)
      at Object.describe (firstTest.spec.js:1:1)

detox[77643] ERROR: [cli.js] Error: Command failed: node_modules/.bin/jest --config=e2e/config.json --maxWorkers=1 '--testNamePattern=^((?!:android:).)*$' "e2e"
`

**Comment by LeoNatan** [comment]
If your software is blocking Detox from injecting a dyld, what do you expect us to do?

**Comment by KashifJavaid** [comment]
It was a question of how detox is using DYLdInjection when apple take it is
a security risk and is it can't be inspected.

Your help is appreciated.

**Comment by LeoNatan** [comment]
In order to not require any user modifications to their projects, we use `DYLD_INSERT_LIBRARIES` to inject Detox into the user app. Apple doesn't take it as a security risk, and is fully supported by the dynamic loader. You seem to have some sort of anti-virus/malware software, which blocks this. I can understand why it would happen, but it is fundamentally incompatible with Detox. If your software allows it, add an exception for your app and/or the Detox dylib that is injected.
