### ISSUE TITLE
detoxURLBlacklistRegex not supported on Android

### ISSUE THREAD

**Issue by plaa** [wix/Detox#1695]
**Describe the bug**

The [method for initializing the URL blacklist on startup](https://github.com/wix/Detox/blob/master/docs/APIRef.DeviceObjectAPI.md#10-initialize-the-url-blacklist-at-device-launch) is implemented only in iOS code. The [PR](https://github.com/wix/Detox/pull/1000/files) changes only `ios/Detox/DetoxManager.m` and `detoxURLBlacklistRegex` cannot be found anywhere else in the code base.

This limitation is not reflected in the documentation in any way. The docs should be updated to reflect this until the feature is implemented in Android.

I just spent half a day trying to figure out why the blacklist is not working, only to arrive at this.

**Comment by LeoNatan** [comment]
Pull requests are welcome.

**Comment by kirstypeee** [comment]
Hi there, thanks for all your work on detox! I was just wondering if this is still not implemented for Android? Or if there is some kind of workaround? We are wanting to use detox as our e2e testing framework but we have open websockets to launchdarkly and apollo subscriptions.

**Comment by d4vidi** [comment]
@kirstypeee indeed so. We cannot defocus and start working on that right now - still looking for contributions here.
