### ISSUE TITLE
Detox waits for animations despite disableSynchronization

### ISSUE THREAD

**Issue by plaa** [wix/Detox#1696]
**Describe the bug**

I have a text input with search suggestions updating in realtime. On every key press, it starts a 400 ms animation graying out the current suggestions and (after a short delay) sends a request to fetch suggestions from the server.

By default, when typing into the text input using Detox, it waits for both the network request and animation to complete on every character.  When I first run `await device.disableSynchronization();` it no longer waits for the network request, but it still waits for the animation to complete.  This makes it horribly slow to type into the text input.

The docs say that `device.disableSynchronization` disables the synchronization mechanism, which I assume means *all* synchronization, including animations.

**To Reproduce**

- [ x ] I have tested this issue on the latest Detox release and it still reproduces

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

1. Create app that uses animations (in my case `Animated.timing(this.state.contentOpacity, { toValue: 0.4, duration: 600 }).start();` whenever text input changes)
2. Perform actions that trigger the animation while in `disableSynchronization`:

```
    await device.disableSynchronization();
    await element(by.id('ProductSearchBar.TextInput')).typeText('somestuff');
```

**Expected behavior**
Synchronization should be disabled and text typed in fast.  In reality it waits for the animation to complete after each character.

**Environment (please complete the following information):**
 - Detox: 14.4.1
 - React Native: 0.59.8
 - Node: 12.8.1
 - Device: Android emulator Pixel 2 API 29
 - OS: Android

**Comment by plaa** [comment]
This may actually be related or a duplicate of #1513.

**Comment by LeoNatan** [comment]
This is a dupe. Pull requests are welcome!
