### ISSUE TITLE
Snapshot Testing

### ISSUE THREAD

**Issue by Nathan-Smith** [wix/detox#170]
Is snapshot testing going to be supported by this library? 
Either in terms of comparing captured screenshots to a set of expected results similar to [how react-native runs tests](http://facebook.github.io/react-native/docs/testing.html#screenshot-snapshot-tests) or comparing a captured native view hierarchy similar to [jest](https://facebook.github.io/jest/docs/snapshot-testing.html)

**Comment by chirag04** [comment]
about screenshots, i'm working on a PR here: https://github.com/wix/detox/pull/169. what would an api for comparing screenshots look like?

**Comment by isnifer** [comment]
@Nathan-Smith detox - it is library for e2e-testing. We don't need one more library for snapshot testing

**Comment by Nathan-Smith** [comment]
@isnifer, my question was more around if detox would implement a similar API too do snapshot testing.

**Comment by isnifer** [comment]
@Nathan-Smith why detox should do that, if this library is not "snapshot testing library"?

**Comment by isnifer** [comment]
@Nathan-Smith just use jest, if you need snapshots.

**Comment by Nathan-Smith** [comment]
@isnifer detox exposes a platform agnostic API for testing. It would be ideal for consumers of detox to either capture a screenshot or capture the view hierarchy or ideally both. With this capability it wouldn't be hard to a image matching library or use the jest snapshot feature with a serialised view hierarchy.
There are two different types of snapshots:
1. Images
2. View Hierarchy

Both of these types could be supported if detox exposed an API to capture it.

**Comment by isnifer** [comment]
@Nathan-Smith images and view hierarchy are beautiful possibilities to understand why test suite was not successfully done. I do not consider them as test approach.
For example, we in tipsi wrap every test suite with next code:
```js
import test from 'tape-async'
import helper from 'tipsi-appium-helper'

export default function tape(name, callback) {
  return test(name, async (t) => {
    try {
      await callback(t)
    } catch (error) {
      await helper.source()
      await helper.screenshot()

      throw error
    }
  })
}
```
[tipsi-appium-helper](https://github.com/tipsi/tipsi-appium-helper) internally uses webdriver methods to take screenshot and get source code of current view and expose two methods:
* source
* screenshot

But we do not test our app with either screenshots nor snapshots. They are only helpers.
If you question about that - of course it will be in detox.
If I correctly remember @talkol already said about that or I saw those things in the docs.

**Comment by LeoNatan** [comment]
We plan to implement analytics of test runs over time, where it would be possible to monitor test performance over time. Perhaps we could implement a functionality similar to what is described here in that module.

**Comment by LeoNatan** [comment]
Out of scope. I also don’t think this is a good way to test non-HTML apps.
