### ISSUE TITLE
Example not working. Just with adjustment

### ISSUE THREAD

**Issue by Nestoro** [wix/Detox#1718]
In the example you write

```
await device.reloadReactNative();
await expect(element(by.id('email'))).toBeVisible();
```

but that doesn't seem to work 100% of the cases. i didn't inspect your structure further but it seems that every element() call should be awaited.

so i would like to change that to:

```
await device.reloadReactNative();
await expect(await element(by.id('email'))).toBeVisible();
```

or:

```
await device.reloadReactNative();
var element = await element(by.id('email'));
await expect(element).toBeVisible();
```

This could reduce problems new users encounter since this is a pretty easy to oversee thing if you try to get detox to run for the first time.

**Comment by LeoNatan** [comment]
Pull requests are welcome.

**Comment by LeoNatan** [comment]
The await is not necessary for the internal element. The entire call is serialized to the native iOS/Android test runner.
