### ISSUE TITLE
Guide on mocking auth0/webauth logins

### ISSUE THREAD

**Issue by J320** [wix/Detox#1725]
Given the increase in security awareness and the action that's been carried out in many organisations nowadays, I see most login approaches moving away from native to WebViews in order to implement auth0, which initially breaks the possibility of using Detox as WebViews aren't and seem like won't be in scope.

I've seen in a few other posts the suggestion of mocking the API in order to avoid the WebView and authenticating the user, however, I can't see a straightforward way of doing this with the existing documentation.

I believe this topic is important enough to work out and make a specific guide on how to deal with it as I see most logins going this route in the short to medium term.

**Comment by LeoNatan** [comment]
I'm not sure what the Detox team can do here. It is up to application developers to figure out how the API they are using works and how best to mock it in their applications.

We already have a React Native mocking guide:
https://github.com/wix/Detox/blob/master/docs/Guide.Mocking.md
We don't have a guide for native mocking, but there are plenty of resources available over the internet.

That should give your the basic idea how to mock things in general. Now you need to consider how your authentication API works and how best to tackle mocking it. Usually, you call some API, the user does what then need in the web view, and finally a callback is called with some token/cookie that you use in your future network requests.

The simplest strategy I can think of is to mock (= replace) this API with a version that automatically returns a pregenerated auth token. This sidesteps the need to display the web view. Another strategy can be to contact your own service which does the authentication for you, and returns a suitable token.

These are all application/authentication framework logic strategies, and I don't think should be part of the Detox documentation, just as we don't have guides on how to develop other parts of the application.
