### ISSUE TITLE
openURL crashing on android requiring FLAG_ACTIVITY_NEW_TASK

### ISSUE THREAD

**Issue by MrLoh** [wix/Detox#1728]
**Describe the bug**
When using `device.openURL` on android or using `device.launchApp` with `newInstance: false` on android. I get the following error:

`Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?`

**To Reproduce**

- [x] I have tested this issue on the latest Detox release and it still reproduces

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

1. call `device.launchApp({newInstance: false})` in a test and execute on android.

**Expected behavior**
It should work without error.

**Environment (please complete the following information):**
 - Detox: 14.5.1
 - React Native: 0.61.2
 - Node: 12.12.0
 - Device: emulator Pixel_API_29
 - OS: android

**Device and Verbose Detox Logs**
The error message is pretty clear, please specify, if more information is needed

**Comment by d4vidi** [comment]
@MrLoh @matejdr Just to be sure, are you both basically trying to transit the app to the device's foreground _with_ a url (i.e. in [this launch-form](https://github.com/wix/Detox/blob/master/docs/APIRef.DeviceObjectAPI.md#mock-opening-from-a-url-when-app-is-in-background))?

**Comment by matejdr** [comment]
Hi @d4vidi, for me both options did not work. launchApp with a url on an existing instance and openURL on existing instance.
`device.openURL({url})
await device.launchApp({url: url, newInstance: false});`

But opening a url on a new instance worked fine:
`await device.launchApp({url: url, newInstance: true});`

So I have a workaround for the time being, although not ideal when running heaps of tests.

I am happy to fix it, if you have a test for the process somewhere.

**Comment by MrLoh** [comment]
@d4vidi yes exactly the method you linked and yes as stated only when using `newInstance: false`.

**Comment by compojoom** [comment]
I can confirm this in our tests with detox 14.8.1 

if we use device.launchApp with the newInstance flag than the url is properly passed to the app.

**Comment by todorone** [comment]
> But opening a url on a new instance worked fine:
> `await device.launchApp({url: url, newInstance: true});`

This works, thanks @matejdr, otherwise error described initially is thrown.

**Comment by d4vidi** [comment]
Well I'm officially looking into this... on first sight, it is an SDK-version related issue. They must have added some security measures.
