### ISSUE TITLE
React Native 0.61 compliance (Android)

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#1731]
Is your feature request related to a problem? Please describe.
Following our work on RN .60 compliance in #1689, we now need to continue to .61, which is the most recent stable release.

Describe the solution you'd like
Support latest RN .61 both as the library and Detox' internal demo projects.

Describe alternatives you've considered
N/A

Additional context
N/A

**Comment by msand** [comment]
It seems like the latest version of Detox works fine with v0.61.4 of react-native as well: https://github.com/msand/react-native-svg-e2e/pull/13

**Comment by bullwrinkle** [comment]
We're seeing issues with Detox 14.6.0 and react-native v0.61.3 with Android, where detox refuses to connect to the app. Detox just sits with no error message, but not executing any tests. When  qemu-system--x86_64 is finally terminated and Detox does respond with the following:

detox[3153] INFO:  [DetoxServer.js] server listening on localhost:49930...
detox[3153] ERROR: [exec.js/EXEC_FAIL, #18] "/Users/user/Library/Android/sdk/platform-tools/adb -s emulator-11728 reverse --remove tcp:49930" failed with code = 1, stdout and stderr:

I have not seen any issues on the IOS side as its executing its tests correctly.

Please let me know if you want me to file a separate ticket or need further info.

**Comment by d4vidi** [comment]
@msand good news. The core issue I've tackled with this RN .61 upgrade was a malfunctioning detox after an RN-reload action, in debug mode. Not the standard usage case, so you must have (rightfully) overlooked it.

**Comment by d4vidi** [comment]
@bullwrinkle I'd highly appreciate a separate issue with the logs of an execution that includes the `--loglevel trace` flag, but please wait for this to be released first...
