### ISSUE TITLE
<ScrollView /> does not scroll when an input is focused

### ISSUE THREAD

**Issue by noomorph** [wix/detox#174]
See the repo for reproduction:

https://github.com/noomorph/detox-bugreport-scrollview

See the failing test in the repo:

https://github.com/noomorph/detox-bugreport-scrollview/blob/master/e2e/bug.spec.js#L9

**Comment by LeoNatan** [comment]
@silyevsk Do you think this is the same problem as before? Touch going to incorrect views?

**Comment by silyevsk** [comment]
@LeoNatan Probably, but not sure, need to check it with the new EarlGrey

**Comment by LeoNatan** [comment]
Will the API of “from point (x,y) pan to (x_2, y_2)” not fix this?

**Comment by silyevsk** [comment]
@LeoNatan I don't know. I've tried this with the newer detox (EarlGrey 1.9.4) and the issue still exists. I think it's a different issue, will check it later.

**Comment by IkerArb** [comment]
I am having this bug as well

**Comment by isnifer** [comment]
@noomorph so, did you do it in real life?

**Comment by IkerArb** [comment]
It is kind of hacky but what I did was this:

`it('should create bank account', async () => {
    await element(by.id('addBankAccountClabeInput')).typeText('123123123123123');
    await element(by.id('addBankAccountNameInput')).replaceText('Foo');
    await element(by.id('addBankAccountEmailInput')).replaceText('bar@gmail.com');
    await element(by.id('addBankAccountAliasInput')).replaceText('FooBar');
    await element(by.id('addBankAccountScrollView')).atIndex(4).tap();
    await element(by.id('addBankAccountActionButton')).tap();
  });`

with this code:

`<ScrollView
          keyboardDismissMode="on-drag"
          testID="addBankAccountScrollView"
        >
          <View style={styles.formContainer}>
            <TextInput
              onChangeText={(clabe) => this.setState({ clabe })}
              style={[styles.input, styles.amount]}
              keyboardType="numeric"
              placeholder="Clabe"
              maxLength={18}
              placeholderTextColor={Colors.hintText}
              underlineColorAndroid="transparent"
              autoFocus
              testID="addBankAccountClabeInput"
            />
            <TextInput
              style={styles.input}
              onChangeText={(name) => this.setState({ name })}
              placeholder="Nombre del titular"
              placeholderTextColor={Colors.hintText}
              underlineColorAndroid="transparent"
              testID="addBankAccountNameInput"
            />
            <TextInput
              onChangeText={(email) => this.setState({ email })}
              style={[styles.input, styles.amount]}
              keyboardType="email-address"
              placeholder="Email del titular"
              placeholderTextColor={Colors.hintText}
              underlineColorAndroid="transparent"
              testID="addBankAccountEmailInput"
            />
            <TextInput
              onChangeText={alias => this.setState({ alias })}
              style={[styles.input, styles.amount]}
              placeholder="(Opcional) Alias de cuenta"
              placeholderTextColor={Colors.hintText}
              underlineColorAndroid="transparent"
              testID="addBankAccountAliasInput"
            />
            <Picker
              selectedValue={this.state.bank}
              itemStyle={{ height: 66 }}
              onValueChange={value => this.setState({ bank: value })}
            >
              {
                this.props.banks.map(bank => (
                  <Picker.Item key={bank.id} label={bank.name} value={bank.id} />
                ))
              }
            </Picker>
          </View>
          <View marginTop={30}>
            <MPButton
              style={styles.button}
              onPress={() => this.submitBankAccount()}
              caption="Crear"
              testID="addBankAccountActionButton"
            />
          </View>
        </ScrollView>`

by dismissing the keyboard with a tap it works, I used index four because it reads the TextInputs from top to bottom from in to out.

**Comment by isnifer** [comment]
Guys, you can hide keyboard, just pass `true` as a third argument into `typeText`. Why do you create problems for yourself?

**Comment by IkerArb** [comment]
@isnifer I got this error:

```
Error Trace: [
  {
    "Description" : "GREYKeyboard: No known SHIFT key was found in the hierarchy.",
    "Error Domain" : "com.google.earlgrey.ElementInteractionErrorDomain",
    "Error Code" : "2",
    "File Name" : "GREYKeyboard.m",
    "Function Name" : "+[GREYKeyboard grey_toggleShiftKeyWithError:]",
    "Line" : "346"
  }
]
```

does it work with a number type keyboard?

**Comment by isnifer** [comment]
@IkerArb yes it does.
```js
await element(by.id(INPUT_ID)).typeText(`${YOUR_TEXT}\n`)
```
Did you try like this?

**Comment by IkerArb** [comment]
@isnifer I just have and still I am getting the same error

**Comment by noomorph** [comment]
@isnifer , I am not certain about what you meant, but yeah - I did that in a real life in many senses:

1) as a human - I fill out a long form (4-5 text inputs) and need to scroll - there's no sense to close and open keyboard all the time - neither as a human (because I'm too lazy to hide the keyboard) nor as a robot (extra time for test to run).

2) as a developer - yeah, I was writing tests for a screen in Wix mobile application when this particular bug hit me. Of course, there are workarounds but nevertheless, it doesn't make sense that quite a straightforward step cannot be taken.

Hope that answers your question.

**Comment by bharadwajsampath** [comment]
@IkerArb The solution you provided works well but only when we have not done anything with the return button on the keyboard. This breaks the test if we are going with input type as numeric, which does not have the return key at all.

**Comment by noomorph** [comment]
**[@‌‌stale](https://github.com/apps/stale)**, this issue is still relevant. Just have checked with `detox@7.3.4`.

**Comment by noomorph** [comment]
**@‌‌stale**, thanks!
