### ISSUE TITLE
Allow to override status bar on iOS simulator

### ISSUE THREAD

**Issue by sidferreira** [wix/Detox#1748]
**Is your feature request related to a problem? Please describe.**
Screenshots comparison may fail because of different times the tests run.
This feature allows overriding status bar settings ensuring it will always have the same information.

**Describe the solution you'd like**
https://github.com/sidferreira/Detox/tree/featureStatusBar

**Describe alternatives you've considered**
None

**Additional context**
Focused on iOS for now

**Comment by LeoNatan** [comment]
Please submit as a pull request.
