### ISSUE TITLE
Detox Tests Hang on iOS 13 Simulator

### ISSUE THREAD

**Issue by buzzb0x** [wix/Detox#1760]
**Describe the bug**

We've been running the same tests for a while. They stopped working when I upgraded to Catalina, Xcode 11 and Xcode started booting an iOS 13 Simulator. They work again if I specify an OS version in our `package.json`:

```json
  "detox": {
    ...
    "test-runner": "jest",
    "configurations": {
      "notworking": {
        "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/APPNAME.app",
        "build": "ENVFILE=.env xcodebuild -workspace ios/biogen.xcworkspace -scheme UAT-FR-DETOX -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 8' -derivedDataPath ios/build",
        "type": "ios.simulator",
        "device": {
          "name": "iPhone 8",
          "os": "iOS 13.2"
        }
      },
      "working": {
        "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/APPNAME.app",
        "build": "ENVFILE=.env xcodebuild -workspace ios/biogen.xcworkspace -scheme UAT-FR-DETOX -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 8' -derivedDataPath ios/build",
        "type": "ios.simulator",
        "device": {
          "name": "iPhone 8",
          "os": "iOS 12.2"
        }
      }
    }
  },
}
```

The simulator launches, installs the app and launches the app, then the tests hang forever and with a `console.log` in our `jest.setup.js` I've been able to confirm that the `device.launchApp` awaits forever:

```js
beforeAll(async () => {
  await detox.init(config, { launchApp: false })
  await device.launchApp({
    permissions: {
      notifications: 'YES',
      camera: 'YES',
      medialibrary: 'YES',
      photos: 'YES',
      microphone: 'YES'
    }
  })
})
```

**To Reproduce**

- [x] I have tested this issue on the latest Detox release and it still reproduces

1. `git clone`
2. `npm ci && (cd ios && pod install)`
3. `detox test -c working`

If possible, please provide a small demo project that reproduces the issue, or attach a video with the reproduction - this would be very appreciated.

**Expected behavior**

Detox should launch the simulator, launch the app, and execute the tests.

**Environment (please complete the following information):**
 - Detox: detox@14.7.1
 - React Native: react-native@0.59.10
 - Node: v12.4.0
 - Device: iPhone 8
 - Xcode: 11.2 (11B52)
 - iOS: 13.2
 - macOS: 10.15.1

**Device and Verbose Detox Logs**

```
detox[876] INFO:  [AppleSimUtils.js] BUNDLEID launched. To watch simulator logs, run:
        /usr/bin/xcrun simctl spawn 576BC106-EB9D-47EA-8AED-B0014D730C3C log stream --level debug --style compact --predicate 'processImagePath beginsWith "/Users/USER/Library/Developer/
CoreSimulator/Devices/576BC106-EB9D-47EA-8AED-B0014D730C3C/data/Containers/Bundle/Application/A35CC083-5EC1-47A8-A38C-ACD23D986816/APPNAME.app"'
detox[948] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onLaunchApp({
  bundleId: BUNDLEID,
  deviceId: '576BC106-EB9D-47EA-8AED-B0014D730C3C',
  launchArgs: {
    detoxServer: 'ws://localhost:63940',
    detoxSessionId: '2b1e2f66-afcb-f6e9-ee58-f1844bc05b84'
  },
  pid: 948
})
detox[876] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"isReady","params":{},"messageId":-1000}
detox[876] TRACE: [DetoxServer.js/MESSAGE] role=tester action=isReady (sessionId=2b1e2f66-afcb-f6e9-ee58-f1844bc05b84)
detox[876] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=testee not connected, cannot fw action (sessionId=2b1e2f66-afcb-f6e9-ee58-f1844bc05b84)
detox[876] DEBUG: [DetoxServer.js/LOGIN] role=testee, sessionId=2b1e2f66-afcb-f6e9-ee58-f1844bc05b84
detox[876] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=testee, sessionId=2b1e2f66-afcb-f6e9-ee58-f1844bc05b84
```

**iOS Framework Build Logs**

N/A

**Last note**

I hope I have included all necessary information, don't hesitate to tell me if something's missing. Thanks for taking the time.

**Comment by LeoNatan** [comment]
We use iOS 13 simulators in our CI, so I don't think it's an issue with Detox.
Follow the sync debugging docs and provide the information. Thanks

**Comment by buzzb0x** [comment]
I see that there are requests that Detox is waiting for, but Detox also awaits endlessly when I try to set a blacklist or disable synchronization, and this produces no specific logging, even with EarlGreyStatistics:

```js
beforeAll(async () => {
  await detox.init(config, { launchApp: false })
  console.log('DETOX INIT')
// SUCCESSFUL
  await device.disableSynchronization()
  console.log('DISABLED SYNC')
// NEVER LOGS
  await device.setURLBlacklist(['.*batch.com*'])
  console.log('SET BLACKLIST')
// NEVER LOGS
  await device.launchApp({
    launchArgs: { detoxPrintBusyIdleResources: 'YES' },
    permissions: {
      notifications: 'YES',
      camera: 'YES',
      medialibrary: 'YES',
      photos: 'YES',
      microphone: 'YES'
    }
  })
  console.log('LAUNCHED APP')
// NEVER LOGS

  await exportGlobalsFromEnv()
})
```

Where could the problem come from? I tried reinstalling applesimutils to no avail as well.

**Comment by LeoNatan** [comment]
If you disable sync, it should not be blocking. So your issue lies elsewhere, not in the native Detox part. What do you see on screen?

**Comment by buzzb0x** [comment]
Maybe my comment placement wasn't great but disable sync awaits forever as well. On screen my app is responsive on its first screen in the simulator. EarlGreyStatistics don't mention anything if I try a detox function before launching and if I launch they only display some ongoing network requests. Any idea?

**Comment by LeoNatan** [comment]
Before launching, Detox is not running.
Looking at the code (https://github.com/wix/Detox/blob/88f2170e9926b3e5c98a41c2eb3cf5418452aebc/detox/ios/Detox/DetoxManager.m#L55), the blacklist is applied very early on, before the app is running. So if you are seeing network requests in the statistics output, that means that you haven't set the blacklist correctly.

**Comment by buzzb0x** [comment]
The problem is that when I try to set a blacklist, the call awaits forever and the app doesn't launch as well. It seems all calls to `device` methods await forever.

**Comment by LeoNatan** [comment]
You need to set the blacklist as app launch argument, as described here:
https://github.com/wix/Detox/blob/master/docs/APIRef.DeviceObjectAPI.md#10-initialize-the-url-blacklist-at-device-launch
