### ISSUE TITLE
Move to Github actions instead of Jenkins

### ISSUE THREAD

**Issue by yershalom** [wix/Detox#1761]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Recently, Github added new feature called actions. The purpose is to define yml files to do the same thing as Jenkins but stay inside github. It also make easier the user management.

**Describe alternatives you've considered**
Jenkins that already is running.

**Additional context**
Also MacOS runners - https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners

**Comment by rotemmiz** [comment]
I'm don't worry re iOS builds, they work pretty good on all SaaS CIs, those are the Android emulators that worry me, none of the services we tried (Circle, Travis, and Bitrise) run Android emulators with sufficient hardware acceleration, and the results are super slow tests (60 minutes and up). We should first find a solution for Android, they if it works, iOS will surely will.

**Comment by yershalom** [comment]
Thanks for your quick answer @rotemmiz,
Can we do it in parallel to Jenkins?

**Comment by rotemmiz** [comment]
You mean both Jenkins and GitHub?

**Comment by yershalom** [comment]
Yes, and github won't fail prs

**Comment by rotemmiz** [comment]
Sure, I'm eager to try it

**Comment by yershalom** [comment]
I like it when you are eager

**Comment by LeoNatan** [comment]
Wix is a legacy account, so we can't use Actions anymore. 🤦‍♂️

**Comment by jakeleboeuf** [comment]
FWIW, I'd be very interested to see an example of a working Github Action workflow example :)

**Comment by edvinasbartkus** [comment]
Github Actions working well for my React Native iOS app detox testing. Here is my workflow with recently added caching:

https://gist.github.com/edvinasbartkus/1e3118dd13c44f43988fcd40e8308db3

**Comment by jakeleboeuf** [comment]
> Github Actions working well for my React Native iOS app detox testing. Here is my workflow with recently added caching:
> 
> https://gist.github.com/edvinasbartkus/1e3118dd13c44f43988fcd40e8308db3

Perfect- works like a charm!

**Comment by henrymoulton** [comment]
@edvinasbartkus have you attempted using Detox + Android at all (in GitHub actions or other CI/CD environment?)

**Comment by edvinasbartkus** [comment]
@henrymoulton not myself, but while researching workflow recipies I did see some successful workflows for Android. Here is one that I have bookmarked on the open-source project:
https://github.com/reime005/react-native-spaceviewer/blob/master/.github/workflows/android.yml

**Comment by LeoNatan** [comment]
@yershalom I think you should come back to do it.

**Comment by yershalom** [comment]
@LeoNatan It might happen :-)

**Comment by LeoNatan** [comment]
Davai

**Comment by edvinasbartkus** [comment]
Yesterday I was curious to experiment with Android Detox on Github Workflow. Based on the link that I have shared I have created the workflow that would pass for me. Here is the workflow gist that worked:

https://gist.github.com/edvinasbartkus/4c09d85ac6f2a2f9eec9d9c8deac5e61

cc @henrymoulton

**Comment by ohtangza** [comment]
cc: @ghsdh3409

**Comment by rotemmiz** [comment]
Reopening and pinning, this is something we need to do in a higher priority.

**Comment by LeoNatan** [comment]
Has there been a conversion with admins regarding change of licensing?

**Comment by rotemmiz** [comment]
Not that I am aware of, but I will try to run Detox e2e with Github Actions on my fork. If it is successful, we can discuss it further.

**Comment by yershalom** [comment]
@rotemmiz I started with JS on react-native-navigation and will flow with this...
https://github.com/wix/react-native-navigation/pull/5902

**Comment by asafkorem** [comment]
Thanks to @noomorph, we recently added GitHub action for [unit tests](https://github.com/wix/Detox/blob/cf95c1cd72f1b8bb4b6917ebbef0d6aace700ca7/.github/workflows/rapid-test.yml) and other checks.

Doesn't seems like we have any plan to move with all of our checks to GH actions.
