### ISSUE TITLE
Android works in development but crashes in production

### ISSUE THREAD

**Issue by henrymoulton** [wix/Detox#1765]
**Describe the bug**
Android Detox works in development but crashes in production.

**To Reproduce**

- [x] I have tested this issue on the latest Detox release and it still reproduces

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

1. android gradle file: https://gist.github.com/henrymoulton/236bbdbc0c48387c2b860a77e045b4ea
2. app gradle file: https://gist.github.com/henrymoulton/28e8c06eb25bf72c722a1766e6adccd

Video: https://streamable.com/ogvsu

**Expected behavior**
Should run as in development

**Screenshots**

**Environment (please complete the following information):**
 - Detox: "detox": "14.4.1",
 - React Native: "react-native": "0.59.10",
 - Node: 10.16.0
 - Device: Pixel_2_API_26
 - OS: 8.0

**Device and Verbose Detox Logs**
Provide the device and "trace" Detox logs so we can understand what happened. You can obtain them by passing the loglevel param: `detox test --loglevel trace`

Detox crash report: https://gist.github.com/henrymoulton/b82a3d9a311c4dcf95964b37f4cc1f19
Logcat: https://gist.github.com/henrymoulton/4165e2f1f284fc0bdec658cf91db0b2e
Most similar issue: https://github.com/wix/Detox/issues/1401

**Comment by d4vidi** [comment]
@henrymoulton the link to your app's `build.gradle` is broken ( / protected) so I can't help you out entirely, but I'll try.
From the looks of it (going over the device logs), your test apk lacks the kotlin stdlib. Could you double check that you've specified detox as a transitive dependency, namely:

```
androidTestImplementation('com.wix:detox:+') { transitive = true }
```

Also, please repost the missing app build.gradle gist :)

**Comment by d4vidi** [comment]
In any case, please post this on SO, this doesn't seem to be a detox issue.
