### ISSUE TITLE
postinstall script fails

### ISSUE THREAD

**Issue by troublediehard** [wix/Detox#1779]
**Describe the bug**
When I run yarn -D detox  on a macOS, it fails with the error:
`error /Users/my_path_to_project_root/node_modules/detox: Command failed.
Exit code: 1
Command: node scripts/postinstall.js
Arguments: 
Directory: /Users/my_path_to_project_root/node_modules/detox
Output:
/Users/dmytro/Library/Detox/ios/44590d2893a278baf0feceadfdef5355ccb28350 was found, but could not find Detox.framework inside it. This means that the Detox framework build process was interrupted.
         deleting /Users/dmytro/Library/Detox/ios/44590d2893a278baf0feceadfdef5355ccb28350 and trying to rebuild.
Extracting Detox sources...
Building Detox.framework from /Users/my_path_to_project_root/node_modules/detox/ios_src...
child_process.js:642
    throw err;
    ^

Error: Command failed: /Users/my_path_to_project_root/node_modules/detox/scripts/build_framework.ios.sh
    at checkExecSyncError (child_process.js:621:11)
    at Object.execFileSync (child_process.js:639:15)
    at Object.<anonymous> (/Users/my_path_to_project_root/node_modules/detox/scripts/postinstall.js:2:27)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:931:10)
    at internal/main/run_main_module.js:17:11 {
  status: 65,
  signal: null,
  output: [ null, null, null ],
  pid: 70438,`

I see the following error in /Users/dmytro/Library/Detox/ios/44590d2893a278baf0feceadfdef5355ccb28350/detox_ios.log

`
<unknown>:0: error: no such file or directory: '/Users/my_path_to_project_root/node_modules/detox/ios_src/@/Users/dmytro/Library/Developer/Xcode/DerivedData/target-fhnzxwqwsftaxkgqiwzxfpihuxvc/Build/Intermediates.noindex/target.build/Debug-iphonesimulator/target.build/Objects-normal/x86_64/target.SwiftFileList'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1
`

**iOS Framework Build Logs**
[detox_ios.log](https://github.com/wix/Detox/files/3890996/detox_ios.log)

**Environment (please complete the following information):**
 - Detox: ^14.8.2
 - React Native: 0.61.4
 - Node: v12.8.1
 - Xcode: 11.2.1 (11B500)
 - macOS: 10.14.6

**Comment by LeoNatan** [comment]
As instructed by the template, please provide the build log.

**Comment by troublediehard** [comment]
@LeoNatan I've attached the log file. Please take a look.

**Comment by LeoNatan** [comment]
What is `tnwconference`? It somehow tries to use things from that when building Detox. Something is configured incorrectly in your system.

**Comment by troublediehard** [comment]
@LeoNatan it is project target name.

**Comment by LeoNatan** [comment]
Detox is a standalone project built with `xcodebuild`. It doesn't know your project. Are you running `npm install` from inside Xcode project script maybe?

**Comment by troublediehard** [comment]
@LeoNatan I'm running `yarn` in my project root directory where `detox` is in devDependencies

**Comment by LeoNatan** [comment]
I'm sorry, not sure what's going on. Somehow your project is leaking into Detox compilation.

**Comment by troublediehard** [comment]
@LeoNatan thanks for your help, restart my mac did the trick.
