### ISSUE TITLE
Unable to interact with auth0 dialog on iOS

### ISSUE THREAD

**Issue by J320** [wix/Detox#1780]
When logins are handled via an auth0 custom tab, a dialog like this opens up on iOS:
![auth0_customtab](https://user-images.githubusercontent.com/28388283/69623725-4da51200-103b-11ea-8a94-35d589f7a4f1.png)

This dialog is displayed when logging out as well as it briefly opens up the link to log the user out and automatically comes back to the app, unfortunately Detox can't interact with this dialog so being able to open up the app logged in still won't allow to test logging out as Detox gets stuck here, unable to interact with any elements. 

I've found that Detox can only interact with alert dialogs that the XCode hierarchy debugger can identify, this one isn't displayed in the debugger therefore the usual methods won't work in this scenario. 

I've seen this issue also reproduced with the new Rate your App iOS dialog, with the difference that Detox can still interact with the app and even the elements behind it.

An ideal solution would be to work out a way to interact with the dialog, or perhaps being able to launch the app disabling it given that there's already some functionality for other notifications.

**Comment by LeoNatan** [comment]
Not possible. These alerts are presented by different processes, and cannot be interacted with. Please lock your API so the alert isn’t displayed.
