### ISSUE TITLE
Keyboard sometimes still open after replaceText

### ISSUE THREAD

**Issue by forki** [wix/Detox#1784]
**Describe the bug**

    await element(selector).replaceText(text);

This doesn't wait until the keyboard is closed and this means other things can't be tapped.

**Expected behavior**

replaceText should wait until keyboard is dismissed or a function for dismissing the keyboard is needed.

**Environment (please complete the following information):**
 - Detox: 14.7.0
 - React Native: 0.59.9
 - Device: Android
 - OS: Android

**Comment by Praveencena88** [comment]
Try with \n at the last with the text, it will close the keyboard.
```
await element(selector).replaceText("text\n");
```

**Comment by forki** [comment]
Is this documented?
