### ISSUE TITLE
Navigation with RNRF failing in android debug

### ISSUE THREAD

**Issue by CarbonC** [wix/Detox#1785]
**Describe the bug**
When running detox in debug, the navigation with react native router flux seems broken. The new page that the phone should navigate to is rendered (componentWillMount and render are called) , but somehow not displayed, causing the rest of the suite to fail. Everything is fine in react native debug without detox, and detox release version.

**To Reproduce**

- [X] I have tested this issue on the latest Detox release and it still reproduces

**Expected behavior**
Navigation should happens normally

**Environment (please complete the following information):**
 - Detox: 14.8.2
 - React Native: 0.61.2
 - Node: 13.2.0
 - Device: Redmi note 7 / Pixel 3A emulator
 - OS: Android

**Device and Verbose Detox Logs**
Provide the device and "trace" Detox logs so we can understand what happened. You can obtain them by passing the loglevel param: `detox test --loglevel trace`

**Comment by alexmobileinteraction** [comment]
Same issue with react-navigation on android debug

**Comment by d4vidi** [comment]
@CarbonC we could really use a reproducing demo app here, or at the very least some logs.
Also, how are things run using similar conditions on iOS?
