### ISSUE TITLE
Page Object Pattern Suggestion

### ISSUE THREAD

**Issue by kagalenitin** [wix/detox#179]
Anyone tried any page object pattern library to use with detox? Any suggestions or example on how to approach this? Thanks in advance.

**Comment by DanielMSchmidt** [comment]
I have, but in a closed source project. I now have a model like `LoginPage.visit()` or `LoginPage.login()` and I call them from the tests. What might be interesting is that I do the reset with `device.reloadReactNative()` in the tests. Otherwise you can do it exactly like in any other test lib with a pages folder you import from. Does this answer your question?

**Comment by kagalenitin** [comment]
Thanks @DanielMSchmidt 

So if I look at the example https://github.com/wix/detox/blob/master/examples/demo-native-ios/e2e/example.spec.js

And if I were to write a POM for this:
My spec file will be:
`
var loginPageObject = require('loginPage.js');

describe('Example', () => {
  beforeEach(async () => {
    await device.relaunchApp();
  });

  it('should have welcome screen', async () => {
    await expect(loginPageObject.WelcomeButton).toBeVisible();
    await expect(loginPageObject.HelloLabel).toBeVisible();
  });
});
`
And PO file loginPage.js :
`
var welcomeButton = element(by.label('Welcome'));
var helloLabel = element(by.label('Say Hello'));

exports.WelcomeButton = welcomeButton;
exports.HelloLabel = helloLabel
`

So when I tried this, its giving me an error saying 'element' is not found. How does the same work in spec file as there is no reference to element or by.label etc.

**Comment by DanielMSchmidt** [comment]
Strange, element is exported when detox is initialized. Where does the po file live?
Exporting a function and passing element in could be a workaround

**Comment by kagalenitin** [comment]
So my folder structure is:
-e2e
 -pages
   - loginPage.js
 -specs
   -loginSpec.js
 -init.js
 -mocha.opts

**Comment by DanielMSchmidt** [comment]
I don't get it, can you check your formatting maybe?

**Comment by kagalenitin** [comment]
How about now, I updated my previous comment.

**Comment by kagalenitin** [comment]
I think I was able to figure out. My export method was not correct. In my PO file:

```
var loginButton         =     'Login';

var exports = module.exports = {};

exports.userLogin = function(){
  return element(by.accessibilityLabel(loginButton));
}
```
And my spec file:
```
var loginObject = require('../pages/loginPage.js');
```

**Comment by aamorozov** [comment]
@kagalenitin did you reference the button by `loginObject.loginButton`?  Trying to do the same but getting:
```expect() argument is invalid, got undefined``` 
when i am passing it to expect as `await expect(loginObject.firstArticle).toBeVisible();`

**Comment by kagalenitin** [comment]
@aamorozov I think you need to export the variable, only then you can access it. I am doing that using function, not sure if its the correct way to do it.

**Comment by aamorozov** [comment]
@kagalenitin Yep that's exactly how i was doing that

**Comment by kagalenitin** [comment]
It works for me.
Try if you can do this.
https://stackoverflow.com/questions/7612011/how-to-get-a-variable-from-a-file-to-another-file-in-node-js

**Comment by aamorozov** [comment]
@kagalenitin 
I don't have issues with importing/exporting anything there(with both import/export or module.exports{}), but `element` command inside the page object doesn't work for me. Will be looking into this on the weekend so if anybody has any suggestions please advise

**Comment by aamorozov** [comment]
Nvm, got it working

**Comment by kagalenitin** [comment]
What was the issue? @aamorozov - Good to have it documented for future reference. Thanks.

**Comment by aamorozov** [comment]
@kagalenitin So I ended up adding argument to function and passing there a var name for label:

``` 
export function tapOnNewElement(elem) {
	return element(by.label(elem)).tap();
};

**Comment by lucassus** [comment]
My solution is something like:

```javascript
class LoginScreen {
  get emailInput() {
    return element(by.id("text-input-email"));
  }

  get passwordInput() {
    return element(by.id("text-input-password"));
  }

  get loginButton() {
    return element(by.text("Login & view cleans"));
  }

  typeEmail(email) {
    return this.emailInput.typeText(email);
  }

  typePassword(password) {
    return this.passwordInput.typeText(password);
  }

  tapLoginButton() {
    return this.loginButton.tap();
  }
}
```

```javascript
it('logs in a user', async() => {
  const loginScreen = new LoginScreen();

  await loginScreen.typeEmail('test@email.com');
  await loginScreen.typePassword('password');
  await loginScreen.tapLoginButton();
});
```

**Comment by neerajkumar-lad** [comment]
Just for the record, see my solution for above error. https://stackoverflow.com/questions/51356998/typeerror-loginscreen-visibleofwelcome-is-not-a-function
