### ISSUE TITLE
Builds Fail in CI After Upgrade to 14.5.0

### ISSUE THREAD

**Issue by AlexK777** [wix/Detox#1791]
**Describe the bug**
I **CANNOT** run my e2e tests on Bitrise after upgrading Detox to version `14.5.0`. I **CAN** run tests on my local environment without issue. I did not see anything specific in the migration docs about CI builds, but it looks like there are some issues with the lockfile on VMs in CI. FWIW, my iOS builds have continued to run without issue, this is only affecting Android. 

**To Reproduce**

- [x] I have tested this issue on the latest Detox release and it still reproduces

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

1. Have a Bitrise project set up for your app. 
2. Start an emulator during the run and start the e2e tests.

I cannot provide a repro because I do not have a personal Bitrise account, this is for my workplace. 

**Expected behavior**
Tests should execute, Bitrise builds worked as expected using version `14.4.1`. 

**Environment (please complete the following information):**
 - Detox: `14.8.4`
 - React Native: `0.60.5`
 - Node: `8.11.1`
 - Device: Android Emulator (Nexus 6) running Oreo
 - OS: Bitrise Android/Docker LTS stack (https://devcenter.bitrise.io/infrastructure/stack-update-and-removal-policy/#android--linux-docker-stacks)

**Device and Verbose Detox Logs**
No detox logs, but here are the Bitrise logs from the test run. It appears as if Detox is unable to find the `.lock` file on the VM and then everything bombs. You can see I logged `adb devices` to ensure an emulator is running. 

```
List of devices attached
emulator-5554	device
+ yarn android:test:smoke
+ npx react-native start --reset-cache
yarn run v1.6.0
$ npx cucumber-js e2e/features --tags '@smoke' -- platform=android
detox[8637] INFO:  [DetoxServer.js] server listening on localhost:42489...
detox[8637] ERROR: [DetoxExportWrapper.js/DETOX_INIT_ERROR] 
 { Error: ENOENT: no such file or directory, open '/root/.local/share/Detox/android-device.registry.state.lock'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at ExclusiveLockfile._doWrite (/bitrise/src/node_modules/detox/src/utils/ExclusiveLockfile.js:95:8)
    at ExclusiveLockfile._ensureFileExists (/bitrise/src/node_modules/detox/src/utils/ExclusiveLockfile.js:121:12)
    at ExclusiveLockfile._lock (/bitrise/src/node_modules/detox/src/utils/ExclusiveLockfile.js:103:10)
    at ExclusiveLockfile.exclusively (/bitrise/src/node_modules/detox/src/utils/ExclusiveLockfile.js:35:16)
    at DeviceRegistry.allocateDevice (/bitrise/src/node_modules/detox/src/devices/DeviceRegistry.js:21:27)
    at EmulatorDriver.acquireFreeDevice (/bitrise/src/node_modules/detox/src/devices/drivers/EmulatorDriver.js:46:47)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/root/.local/share/Detox/android-device.registry.state.lock' }
```

**Comment by henrymoulton** [comment]
@AlexK777 Bitrise runs in a virtualised environment which I believe is one reason for things to fail.

**Comment by d4vidi** [comment]
@AlexK777 what if you run an `echo '' > /root/.local/share/Detox/android-device.registry.state.lock` before detox starts?

**Comment by AlexK777** [comment]
@d4vidi yes, that was ultimately what I did to fix the problem, but the file can't be empty or Detox will throw an error. I've just been running `echo ["1"] >> /root/.local/share/Detox/android-device.registry.state.lock` before initializing Detox.

**Comment by d4vidi** [comment]
In no way does the file need to be empty (or even _be_ at all) for detox to run. I'm not yet sure what the problem here is but it seems to be related to: https://github.com/nodejs/node/blob/v8.x/lib/fs.js#L1299
