### ISSUE TITLE
Update getDirectories to follow symbolic links

### ISSUE THREAD

**Issue by dicearr** [wix/Detox#1798]
#### Problem description

In my current configuration `$ANDROID_HOME/build-tools` contains symbolic links to the build tools. When Detox looks for the Aapt binary it tries to get the latest available build tools installed by listing all the folders in `$ANDROID_HOME/build-tools`. The function used for that is `getDirectories` which is not following symlinks. All this results in Detox not being able to find the Aapt binary and throwing.

```console
$ ls -l $ANDROID_HOME/build-tools
total 4
lrwxrwxrwx 1 nobody nogroup 101 Jan  1  1970 28.0.3 -> /somepath/build-tools/28.0.3
$ detox test --config android.emu.debug --cleanup -l verbose
...
detox[10764] ERROR: [DetoxExportWrapper.js/DETOX_INIT_ERROR] 
 Error: There was no "aapt" executable file in directory: /path/to/sdk/android-sdk
...
```

#### Proposed solution

Modify the `getDirectories` function so, in case a symbolic link is found inside the root folder,  `fs.realpath` is used to determine the destination path and then check if that path is a folder or not. `fs.realpath` already deals with chains of symbolic links.

**Comment by LeoNatan** [comment]
As I mentioned in the PR review, I think the simplest solution here is to just use `stat`, rather than `lstat`.

**Comment by LeoNatan** [comment]
Merged
