### ISSUE TITLE
`detox.init()` should not launch app

### ISSUE THREAD

**Issue by rotemmiz** [wix/detox#180]
Instead, let the users control when they want to launch the app for the first time.
This is useful when using mock servers, and a better control of when the app launches is needed.

So instead of :
```js
before(async () => {
  await detox.init();
}
```

The equivalent will be:

```js
before(async () => {
  await detox.init();
  await device.relaunchApp();
}
```

* Also add an example in the demo app and docs.

**Comment by LeoNatan** [comment]
This how Apple’s XCUITest works. The user has to explicitly launch the app.

Maybe we should consider having an application proxy class, like Apples: https://developer.apple.com/documentation/xctest/xcuiapplication?language=objc
