### ISSUE TITLE
Allow not encoded launchArgs for AndroidDriver

### ISSUE THREAD

**Issue by leanmazzu** [wix/Detox#1804]
**Is your feature request related to a problem? Please describe.**
We (Skyscanner) are working on integrating the latest Detox version for React Native in Android with our current setup. It used to work, but since base64 encoding was introduced for launchArgs it stopped working. https://github.com/wix/Detox/commit/a51a88a69942a5d2cd47dc93150e1c7f01097d14#diff-278e2fae566194b7c4923c8238970e49

We are using `device.launchApp()` passing our `launchArgs`. Some of them are custom params and there’s a specific one `class` that we use to specify our test rule for Detox.

I’ve seen that the base64 encoding is not applied to any parameter named with a key that starts with `detox`.

We can prefix our custom parameters with `detox` but we can’t do that with `class` parameter since this is an `adb instrument` parameter  (https://developer.android.com/studio/test/command-line#AMOptionsSyntax). 

So let’s say we prefix `detox` then the generated adb command will look like:
`adb -s emulator-10422 shell am instrument -w -r -e detoxServer ws://localhost:57360 -e detoxSessionId dbd95b5f-bce1-1862-e35e-31562d2937e2 -e detoxclass net.skyscanner.go.detox.MainDetoxTest`

Of course in this case `detoxclass` is completely ignored by `adb am instrument`

**Describe the solution you'd like**
I think a possible approach could be to have unencoded not only `detox` prefixed params but also the different am instrument options.

**Describe alternatives you've considered**
Alternatively, it could be useful to add an option to disable args encoding altogether.

**Additional context**
N/A

**Comment by d4vidi** [comment]
Hi @leanmazzu!
Are you certain that indeed it's the encoding that breaks your tests? The commit you've specified doesn't add encoding per se, rather, it introduces custom launch args support in Android altogether. Could you specify more details (here or PM)

**Comment by leanmazzu** [comment]
Hi @d4vidi! 

So what I did is revert the changes only in `AndroidDevice.prepareLaunchArgs()` to what it was before the mentioned commit (without any encoding):

```
_prepareLaunchArgs(launchArgs) {
    return _.reduce(launchArgs, (result, value, key) => {
      result.push('-e', key, JSON.stringify(value));
      return result;
    }, []);
```

And then by looking at the logs I can see that the generated ADB command looks as expected. Example:
`adb -s emulator-16912 shell am instrument -w -r -e detoxServer "ws://localhost:51789" -e detoxSessionId "0cb9708e-a2f2-86c1-ec09-4be0cac09717" -e class "net.skyscanner.go.detox.MainDetoxTest" -e someCustomParam [“some_unencoded_value”] -e debug false net.skyscanner.android.main.debug.test/net.skyscanner.go.detox.DetoxInstrumentationTestRunner`

As you can see no `-e` argument is encoded. Now, this is what it looks like when I run it in the latest  upstream Detox version:

`adb -s emulator-16912 shell am instrument -w -r -e detoxServer ws://localhost:52105 -e detoxSessionId 512c5058-25c8-3305-f56f-22cf6adbcc18 -e class bmV0LnNreXNjYW5uZXIuZ28uZGV0b3guTWFpbkRldG94VGVzdA== -e someCustomParam WyJpbml0X3NoYXJlZF9wcmVmcyJd -e debug ZmFsc2U= net.skyscanner.android.main.debug.test/net.skyscanner.go.detox.DetoxInstrumentationTestRunner`

Now all the parameters get encoded. We can make them unencoded by just adding `detox` prefix to them, this would work for `-e someCustomParam` since this is our own param and we can read it from our side. But arguments like `-e class` or `-e debug` need to be ALWAYS unencoded since these are `adb am instrument` params and they need to be interpreted by that command.

Hope this clarifies the issue, otherwise let me know! 
Thanks!

**Comment by d4vidi** [comment]
@leanmazzu Please rework this using Detox `14.9.2`

**Comment by leanmazzu** [comment]
@d4vidi will check it out! Thanks for the quick fix :)
