### ISSUE TITLE
Add ability to run with multiple devices

### ISSUE THREAD

**Issue by fancychimp** [wix/Detox#1806]
**Is your feature request related to a problem? Please describe.**
My team would love for me to run our tests against multiple devices. I understand one would specify the device information in the `detox` configuration in the project's `package.json` file, but it would be awesome if we could specify multiple devices for each platform.

**Describe the solution you'd like**
If possible, it would be great to configure multiple devices and then specify which one you'd like to run against in the `detox test` command.

**Comment by compojoom** [comment]
When running the detox cli you have the -n option which will launch the tests against that simulator.
```
detox test -c android.emu.debug -n Pixel_2_API_28
```

Isn't this what you are looking for?

**Comment by fancychimp** [comment]
@compojoom this is exactly what I am looking for, I missed it in the documentation. Thank you for your help.
