### ISSUE TITLE
Is there a way to let assembleAndroidTest task running against specific flavor on android?

### ISSUE THREAD

**Issue by novasponge** [wix/Detox#1810]
I followed the instruction from android setup doc. 
`gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug`

it seems like  assembleAndroidTest builds every flavors
Is there a way I can specify flavor that want assembleAndroidTest to run against?

**Comment by rotemmiz** [comment]
https://github.com/wix/Detox/blob/master/detox/test/package.json#L95
