### ISSUE TITLE
Seems `device.setURLBlacklist` documented incorrectly 

### ISSUE THREAD

**Issue by vvscode** [wix/Detox#1817]
@simonracz @rotemmiz 

According to the doc I assumed that the `.setURLBlacklist` should disable connections to the listed urls. However, in test I see that 

```js
  it('setURLBlacklist() should disable synchronization for given endpoint', async () => {
    const url = device.getPlatform() === 'ios' ? '.*localhost.*' : '.*10.0.2.2.*';
    await device.setURLBlacklist([url]);

    await element(by.id('LongNetworkRequest')).tap();
    await expect(element(by.text('Long Network Request Working!!!'))).toBeNotVisible();
    await waitFor(element(by.text('Long Network Request Working!!!'))).toBeVisible().withTimeout(4000);
    await expect(element(by.text('Long Network Request Working!!!'))).toBeVisible();

    await device.setURLBlacklist([]);
  });
```

that test supposed that after blacklisting url request still work. 

Expected behaviour - 

```js
  it('setURLBlacklist() should disable synchronization for given endpoint', async () => {
    const url = device.getPlatform() === 'ios' ? '.*localhost.*' : '.*10.0.2.2.*';

    // check blocking url
    await device.setURLBlacklist([url]);
    await element(by.id('LongNetworkRequest')).tap();
    await expect(element(by.text('Long Network Request Working!!!'))).toBeNotVisible();
    await waitFor(element(by.text('Long Network Request Working!!!'))).toBeNotVisible().withTimeout(4000);
    await device.setURLBlacklist([]);

    // check reseting block
    await element(by.id('LongNetworkRequest')).tap();
    await expect(element(by.text('Long Network Request Working!!!'))).toBeNotVisible();
    await waitFor(element(by.text('Long Network Request Working!!!'))).toBeVisible().withTimeout(4000);
    await device.setURLBlacklist([]);
  });
```

am I wrong?

**Comment by rotemmiz** [comment]
As docs say, it only disables network sync to those endpoints, not the network calls themselves...

**Comment by vvscode** [comment]
however according to my test - requests (with fetch) to that url (I use mask `'*`) also blocked

I started looking in cause I can't reset that blacklick. 

Can you explain, what does `sync` in this case mean?

**Comment by LeoNatan** [comment]
Please read the documentation. There is explanation how detox works and what synchronization means. Since you aren't familiar with the synchronization concepts, why are you even attempting to use this API?

**Comment by vvscode** [comment]
@LeoNatan  I've read the docs. But 
1) docs are not clear (naming is also confusing. Is there any reason why `.setURLBlacklist` not named with mentions of synchronization?)
2) it does not explain the behavior I see in my tests

**Comment by LeoNatan** [comment]
I've looked in the "core principles" document, and indeed there is no mention of how we sync, which is peculiar, given how important this aspect is. I will add a few word on it now.

The API is called the way it is, because we reused the name from Earl Grey, which is a framework we use internally for synchronizing Detox and the app.

**Comment by LeoNatan** [comment]
OK, I've updated the docs. Please read:

https://github.com/wix/Detox/blob/master/docs/More.DesignPrinciples.md
https://github.com/wix/Detox/blob/master/docs/Troubleshooting.Synchronization.md

These documents should explain how Detox works, and more specifically, how synchronization works and how to control it.
