### ISSUE TITLE
Is it possible to have either a `containsText` or for `toHaveText` to ignore whitespace at the end of string

### ISSUE THREAD

**Issue by lowks** [wix/Detox#1818]
**Is your feature request related to a problem? Please describe.**
deTox tests always fails when there are whitespaces at the end

**Describe the solution you'd like**
Either another matcher that ignores these prepending or appending whitespaces example `containsText` or an argument to `toHaveText` that makes it ignore whitespaces at the front or back.

**Describe alternatives you've considered**
none that I can think of now

**Additional context**
none

**Comment by LeoNatan** [comment]
It's not possible to do. We provide the matcher string and it's matched against the view's labels.

Why not trim whitespace in your application?
