### ISSUE TITLE
Blog post about testing

### ISSUE THREAD

**Issue by sweatC** [wix/Detox#1820]
**Is your feature request related to a problem? Please describe.**
I am writing a blog post about the modern way of testing React Native apps and want to include one paragraph about `Detox` as an e2e testing tool.

**Describe the solution you'd like**
I need one well-described paragraph about your tool and one simple example of using.
Instead, I want you to promote my article on your site or blog.

**Comment by LeoNatan** [comment]
We have no means to promote such articles. Thanks
