### ISSUE TITLE
detox + firebase = timeout

### ISSUE THREAD

**Issue by FDiskas** [wix/Detox#1826]
If I add firebase to my project I can't use detox. All tests gets timeout
https://invertase.io/oss/react-native-firebase/quick-start

**Comment by noomorph** [comment]
Does that help? https://github.com/wix/Detox/issues/1288#issuecomment-504972842

**Comment by FDiskas** [comment]
It does not helped, probably there is more urls needs to be blacklisted. I need to dive deeper here

**Comment by FDiskas** [comment]
Solution is still unknown :)

**Comment by LeoNatan** [comment]
Please follow the sync debug guides and post the result.

**Comment by LeoNatan** [comment]
This one in particular:

https://github.com/wix/Detox/blob/master/docs/Troubleshooting.Synchronization.md#lower-level-idling-resources-debug-ios-only

**Comment by FDiskas** [comment]
Got something but noting about what kind of network request is preventing
```
App has not responded to the network requests below:
  (id = 1) invoke: {"target":{"type":"Invocation","value":{"target":{"type":"EarlGrey","value":"instance"},"method":"detox_selectElem
entWithMatcher:","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"GREYMatchers"},"method":"matcherForAccessibilityID:","args":[{"type":"NSString","value":"EnterPhoneNumber"}]}}]}},"method":"performAction:","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"GREYActions"},"method":"actionForTap","args":[]}}]}
  (id = -1000) reactNativeReload: {}
```
and later
```
Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 120000ms timeout specified by jest.setTimeout.
```

**Comment by LeoNatan** [comment]
Please provide the information I asked for.

**Comment by FDiskas** [comment]
Got flooded by 
```
2020-01-13 17:28:36.354 Db MyApp[74466:5ac6b] [com.wix.Detox:EarlGreyStatistics] WXAnimatedDisplayLinkIdlingResource -> busy (null)
```

**Comment by LeoNatan** [comment]
There you go. So you have some animation that never ends. You need to inspect your code and figure out where it is. You can use mocking to make the animation a short one only when testing.

**Comment by FDiskas** [comment]
For other who will land here read here https://stackoverflow.com/a/47401082/175404
For wix team - better documentation needed :)

**Comment by LeoNatan** [comment]
Everything is documented properly. It just needs people to read it. 😛

Troubleshooting is documented, mocking is documented, etc.
