### ISSUE TITLE
Test for item within ListView

### ISSUE THREAD

**Issue by adamski** [wix/detox#183]
I'm trying to test for an item appearing in a ListView. I have tried

```
await element(by.text('thing')).toExist();
```
and
```
await element(by.label('thing')).toExist();
```

However I get
```
 TypeError: element(...).toExist is not a function
```

Each row component is rendered as: 

```jsw
          <TouchableHighlight                                                          
          onPress={() => this.pressRow(word)}                                        
           underlayColor="grey">                                                                 
           <View style={styles.rowContainer}>                                         
             <Text style={styles.title}>{word}</Text>                                 
           </View>                                                                    
         </TouchableHighlight>
```

**Comment by adamski** [comment]
Sorry, it should be 
```
await expect(element(by.label('thing'))).toExist();
```
Works perfectly now.

**Comment by kagalenitin** [comment]
Hi @adamski 

I am not sure how you resolved it, but I am seeing something really weird behavior on the app I am testing. If you see the inspector shows my listview has an id, but when I  try to waitFor() or expect() - it doesn't identify the element and my test fails.
```
await waitFor(element(by.id('myarray'))).toBeVisible().withTimeout(4000)

```
I am looking to click on the element GET TO KNOW YOU inside this listview.
I have tried to do element(by.label()) and by.text - even by.accessibilityLabel() but no luck.

When I spoke to the devs they said, that they have a layer-upon-layer for that listview. I am assuming detox is not able to identify that layer. 

<img width="1413" alt="screen shot 2017-07-07 at 12 17 46 pm" src="https://user-images.githubusercontent.com/616741/27973440-eaeca71c-630e-11e7-9555-435fa1737016.png">

Any idea what I can do to make it work? If not, I will open up another bug. Thanks
