### ISSUE TITLE
How to close Android soft keyboard?

### ISSUE THREAD

**Issue by janoist1** [wix/Detox#1849]
How to close soft keyboard on Android?
There is a `closeSoftKeyboard` inside the `ViewActions.js`, what's that? Can it be used?
If not, what's the recommended way of achieving this?

Thanks.

**Comment by d4vidi** [comment]
@janoist1 `closeSoftKeyboard` will execute `Espresso`'s implementation for doing what you would. I'd appreciate your feedback of whether this was what you needed, and also why you needed it in the first place.
