### ISSUE TITLE
Pubnub preventing detox syncing

### ISSUE THREAD

**Issue by mckenzit** [wix/Detox#1852]
Need some help.  
I’ve got a similar issue to https://github.com/wix/detox/issues/272  
We have a Pubnub publish-subscribe SDK included in our app. So, when running a detox test, it will always time out, because it will wait for the connection to close.

I’ve tried both setURLBlacklist on launch and detoxURLBlacklistRegex but with no luck. The logs still say:

`[com.wix.Detox:EarlGreyStatistics] App State -> busy Waiting for network requests to finish: (
    "https://ps15.pndsn.com/v2/subscribe/sub-c-xxxxxxxxxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx”`

I’m fairly positive my regex is correct. The regex mentioned in the issue mentioned above doesn’t work. I wouldn't normally ask for help with simple regex, but my knowledge of EarlGrey is minimal and i've been battling with this for a while. 

Note: If I disable synchronisation the app hangs on initialisation.

**Comment by LeoNatan** [comment]
You will need to debug in Xcode using this guide:
https://github.com/wix/Detox/blob/master/docs/Guide.DebuggingInXcode.md
