### ISSUE TITLE
Detox app launch results in crash - Error: The request was denied by service delegate

### ISSUE THREAD

**Issue by prios-paul-burt** [wix/Detox#1859]
### Description
iOS react-native app installs on simulator with detox, but crashes when launching the app (“The request was denied by service delegate”)

- [x ] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

1. build the application
2. run `detox test --configuration ios.sim.dev`

#### Expected behavior
Tests to open the application and execute the tests on the iOS simulator

#### Screenshots
n/a

#### Environment (please complete the following information):
 - Detox: 15.1.2
 - React Native: 0.61.0
 - Node: 12.14.1
 - Device: iOS simulator
 - Xcode: 11.3.1
 - iOS: 13.3 & 13.0
 - macOS: 10.14.6 Mojave

### Logs
```
detox[57585] ERROR: [exec.js/EXEC_FAIL, #6] An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
The request to open "{appName}" failed.
The request was denied by service delegate (SBMainWorkspace) for reason: Unspecified ("null").
Underlying error (domain=FBSOpenApplicationErrorDomain, code=1):
    The operation couldn't be completed. (null)
    (null)
```
#### If you are experiencing a timeout in your test
- [ ] I have followed the instructions under [Lower-level Idling Resources Debug](https://github.com/wix/Detox/blob/master/docs/Troubleshooting.Synchronization.md#lower-level-idling-resources-debug-ios-only) and am providing the log below:

#### If you are seeing a build problem (e.g. during `npm install`)
- [ ] I am providing the `npm install` log below:

#### Device and verbose Detox logs
- [ x] I have run my tests using the `--loglevel trace` argument and am providing the verbose log below: 
yarn run v1.21.1
warning package.json: No license field
$ ENVFILE=.env.automated-tests && detox test --configuration ios.sim.dev --take-screenshots failing --verbose --loglevel trace
detox[83827] INFO:  [test.js] configuration="ios.sim.dev" loglevel="trace" takeScreenshots="failing" reportSpecs=true DETOX_START_TIMESTAMP=1579124879980 node_modules/.bin/jest --config jest.config.e2e.js '--testNamePattern=^((?!:android:).)*$' --maxWorkers 1 --verbose "e2e"
 
detox[83829] INFO:  [DetoxServer.js] server listening on localhost:55535...
detox[83829] DEBUG: [AsyncWebSocket.js/WEBSOCKET_OPEN] opened web socket to: ws://localhost:55535
detox[83829] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"login","params":{"sessionId":"9295f786-337e-6202-fcbc-7d994f08ffb8","role":"tester"},"messageId":0}
detox[83829] DEBUG: [DetoxServer.js/LOGIN] role=tester, sessionId=9295f786-337e-6202-fcbc-7d994f08ffb8
detox[83829] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=tester, sessionId=9295f786-337e-6202-fcbc-7d994f08ffb8
detox[83829] TRACE: [AsyncWebSocket.js/WEBSOCKET_MESSAGE] {"type":"loginSuccess","params":{"sessionId":"9295f786-337e-6202-fcbc-7d994f08ffb8","role":"tester"},"messageId":0}
 
detox[83829] DEBUG: [exec.js/EXEC_CMD, #0] applesimutils --list --byId E46AEB39-7619-4007-8DE6-88433521346B --byName "iPhone 11" --byOS "iOS 13.0" --byType "iPhone 11"
detox[83829] TRACE: [exec.js/EXEC_SUCCESS, #0] [
  {
    "deviceType" : {
      "name" : "iPhone 11",
      "bundlePath" : "\/Applications\/Xcode.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone 11.simdevicetype",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-11"
    },
    "state" : "Booted",
    "isAvailable" : true,
    "name" : "iPhone 11",
    "udid" : "E46AEB39-7619-4007-8DE6-88433521346B",
    "os" : {
      "buildversion" : "17A577",
      "bundlePath" : "\/Library\/Developer\/CoreSimulator\/Profiles\/Runtimes\/iOS 13.0.simruntime",
      "isAvailable" : true,
      "name" : "iOS 13.0",
      "identifier" : "com.apple.CoreSimulator.SimRuntime.iOS-13-0",
      "version" : "13.0"
    }
  }
]
 
detox[83829] DEBUG: [exec.js/EXEC_CMD, #1] applesimutils --list --byId E46AEB39-7619-4007-8DE6-88433521346B --maxResults 1
detox[83829] TRACE: [exec.js/EXEC_SUCCESS, #1] [
  {
    "deviceType" : {
      "name" : "iPhone 11",
      "bundlePath" : "\/Applications\/Xcode.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone 11.simdevicetype",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-11"
    },
    "state" : "Booted",
    "isAvailable" : true,
    "name" : "iPhone 11",
    "udid" : "E46AEB39-7619-4007-8DE6-88433521346B",
    "os" : {
      "buildversion" : "17A577",
      "bundlePath" : "\/Library\/Developer\/CoreSimulator\/Profiles\/Runtimes\/iOS 13.0.simruntime",
      "isAvailable" : true,
      "name" : "iOS 13.0",
      "identifier" : "com.apple.CoreSimulator.SimRuntime.iOS-13-0",
      "version" : "13.0"
    }
  }
]
 
detox[83829] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBootDevice({ coldBoot: false, deviceId: 'E46AEB39-7619-4007-8DE6-88433521346B' })
detox[83829] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeUninstallApp({
  deviceId: 'E46AEB39-7619-4007-8DE6-88433521346B',
  bundleId: 'com.appName'
})
detox[83829] DEBUG: [exec.js/EXEC_CMD, #2] /usr/bin/xcrun simctl uninstall E46AEB39-7619-4007-8DE6-88433521346B com.appName
detox[83829] DEBUG: [exec.js/EXEC_TRY, #2] Uninstalling com.appName...
detox[83829] TRACE: [exec.js/EXEC_SUCCESS, #2] 
detox[83829] DEBUG: [exec.js/EXEC_SUCCESS, #2] com.appName uninstalled
detox[83829] DEBUG: [exec.js/EXEC_CMD, #3] /usr/bin/xcrun simctl install E46AEB39-7619-4007-8DE6-88433521346B "/Users/appPath/Build/Products/Debug-iphonesimulator/app.app"
detox[83829] DEBUG: [exec.js/EXEC_TRY, #3] Installing /Users/appPath/Build/Products/Debug-iphonesimulator/app.app...
detox[83829] TRACE: [exec.js/EXEC_SUCCESS, #3] 
detox[83829] DEBUG: [exec.js/EXEC_SUCCESS, #3] /Users/appPath/Build/Products/Debug-iphonesimulator/app.app installed
detox[83829] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeLaunchApp({
  bundleId: 'com.appName',
  deviceId: 'E46AEB39-7619-4007-8DE6-88433521346B',
  launchArgs: {
    detoxServer: 'ws://localhost:55535',
    detoxSessionId: '9295f786-337e-6202-fcbc-7d994f08ffb8'
  }
})
detox[83829] DEBUG: [exec.js/EXEC_CMD, #4] SIMCTL_CHILD_DYLD_INSERT_LIBRARIES="/Users/{user}/Library/Detox/ios/6482a19f2e78285efde7a67b977225fd53e12142/Detox.framework/Detox" /usr/bin/xcrun simctl launch E46AEB39-7619-4007-8DE6-88433521346B com.appName --args -detoxServer "ws://localhost:55535" -detoxSessionId "9295f786-337e-6202-fcbc-7d994f08ffb8""
detox[83829] DEBUG: [exec.js/EXEC_TRY, #4] Launching com.appName...
detox[83829] DEBUG: [exec.js/EXEC_TRY, #4] Launching com.appName...
detox[83829] ERROR: [exec.js/EXEC_FAIL, #4] "SIMCTL_CHILD_DYLD_INSERT_LIBRARIES="/Users/user/Library/Detox/ios/6482a19f2e78285efde7a67b977225fd53e12142/Detox.framework/Detox" /usr/bin/xcrun simctl launch E46AEB39-7619-4007-8DE6-88433521346B com.appName --args -detoxServer "ws://localhost:55535" -detoxSessionId "9295f786-337e-6202-fcbc-7d994f08ffb8"" failed with code = 1, stdout and stderr:
 
detox[83829] ERROR: [exec.js/EXEC_FAIL, #4] com.appName: -1
 
detox[83829] ERROR: [exec.js/EXEC_FAIL, #4] An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
The request to open "com.appName" failed.
The request was denied by service delegate (SBMainWorkspace) for reason: Unspecified ("null").
Underlying error (domain=FBSOpenApplicationErrorDomain, code=1):
      The operation couldn’t be completed. (null)
      (null)
 
detox[83829] TRACE: [Detox.js/DETOX_BEFORE_EACH] running test: “test description”
detox[83829] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onTestStart({
  title: ‘test name’,
  fullName: ‘test description’,
  status: 'running'
})
detox[83829] TRACE: [Artifact.js/START] starting SimulatorScreenshot
detox[83829] DEBUG: [exec.js/EXEC_CMD, #5] /usr/bin/xcrun simctl io E46AEB39-7619-4007-8DE6-88433521346B screenshot "/private/var/folders/lk/gchy4y7n62vc8fw3w08b_6_wf9xk3r/T/9366dc76-30f2-4d64-a0a4-c54e9e79aafb.detox.png"
detox[83829] TRACE: [exec.js/EXEC_SUCCESS, #5] Detected file type 'PNG' from extension
Wrote screenshot to: /private/var/folders/lk/gchy4y7n62vc8fw3w08b_6_wf9xk3r/T/9366dc76-30f2-4d64-a0a4-c54e9e79aafb.detox.png
 
detox[83829] TRACE: [Artifact.js/STOP] stopping SimulatorScreenshot
detox[83829] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"invoke","params":{"target":{"type":"Invocation","value":{"target":{"type":"EarlGrey","value":"instance"},"method":"detox_selectElementWithMatcher:","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"GREYMatchers"},"method":"matcherForAccessibilityID:","args":[{"type":"NSString","value":"bc2a4462-37e0-11ea-9c5c-33a3d7594de4-listItem"}]}}]}},"method":"assertWithMatcher:","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"GREYMatchers"},"method":"matcherForNotNil","args":[]}}]},"messageId":1}
detox[83829] TRACE: [DetoxServer.js/MESSAGE] role=tester action=invoke (sessionId=9295f786-337e-6202-fcbc-7d994f08ffb8)
detox[83829] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=testee not connected, cannot fw action (sessionId=9295f786-337e-6202-fcbc-7d994f08ffb8)

**Comment by prios-paul-burt** [comment]
Based on the logs it appears that detox is launching the app twice, but no idea why that would be.

**Comment by prios-paul-burt** [comment]
> We have a retry mechanism to try and launch the app. But I don't see a crash log. Please follow [this guide](https://github.com/wix/Detox/blob/master/docs/Guide.DebuggingInXcode.md), catch the crash in Xcode, and post the details here. Thanks

@LeoNatan I went through the guide you added, but the final step seems to indicate that device.launchApp() is not called by this process and that is where we see the failure (before the app is finished launching). When I ran through the steps in the guide, the tests just hang. Got anything else I can try?

**Comment by LeoNatan** [comment]
You are supposed to launch the app using Xcode.

**Comment by LeoNatan** [comment]
If you can't provide the supposed crash information, we can't assist you.

**Comment by prios-paul-burt** [comment]
@LeoNatan I did launch the app using xcode, but there was no change. Are there logs I am supposed to retrieve somewhere after I run the last step in the guide? Nothing happens in the terminal. The script just hangs

**Comment by LeoNatan** [comment]
When you run the detox server and run in Xcode, you should start seeing logs in Xcode. Then run your test, and it should start running your tests. You claim there is a crash on launch, so you should see the problem right away within Xcode.

**Comment by prios-paul-burt** [comment]
@LeoNatan the app doesn't crash when I launch the app through Xcode, it only crashes when detox is launching the app.

**Comment by LeoNatan** [comment]
No, but if you followed the guide, they should behave almost exactly the same. There is no reason for the app to crash when launched from command line but not from Xcode.

**Comment by prios-paul-burt** [comment]
Using the guide I was able to get the tests to run, but the guide says that `device.launchApp()` is not used. This seems to be where the problem occurs.

**Comment by LeoNatan** [comment]
What device.launchApp() does is what Xcode does when running. Your problem lies elsewhere.

Make sure you are building correctly the .app that Detox uses. Make sure both Xcode and build are release configuration (you shouldn't test debug builds).

**Comment by prios-ashley-hainline** [comment]
We are noticing in regards to this problem that all other things being the same, if we cut out the part of AppleSimUtils.js which builds the command line launch command:

     let launchBin = '' /*`SIMCTL_CHILD_DYLD_INSERT_LIBRARIES="${dylibs}" `*/ +
      `/usr/bin/xcrun simctl launch ${udid} ${bundleId} --args ${args}`;

... then the app does not crash at startup and yet can still be controlled with detox.  When we uncomment that one part it fails as before.  Also, this only fails on one machine like this.  So what does this dylibs library do for us?

**Comment by prios-ashley-hainline** [comment]
After cleaning up some xcode configuration that had been used for debugging, deleting the old build, running a yarn, and making a new build, the app is still able to launch with that piece commented out, but my tests do not appear to be able to control the app.

**Comment by LeoNatan** [comment]
That makes no sense. If your app is still being controlled without Detox, that means you have Detox integrated in your app, and it will fail review. Make sure to undo what was changed following the guide I posted above.

We inject Detox dynamically so that users do not need to modify their projects. Detox is not App Store safe. That dylib brings Detox into your app. But without information on what "fails" means, I cannot assist.

**Comment by prios-ashley-hainline** [comment]
I was finally able to get it running by installing an older version of applesimutils. I had been running 0.7.6 and was able to roll it back to 0.7.2. The app is launching and the tests are running successfully on this version.

**Comment by LeoNatan** [comment]
I’m confused. applesimutils isn’t used for launching apps.
