### ISSUE TITLE
Add a way to clear app data

### ISSUE THREAD

**Issue by yedidyak** [wix/detox#186]
Since tests can be affected by persisted app data which is kept between tests, this can introduce coupling and interference between tests. A way to clear app data without having to uninstall and reinstall would help solve this.

**Comment by tronin** [comment]
Hi, you can change a redux store key/prefix for that.

**Comment by LeoNatan** [comment]
There is no API on iOS to clear app data, nor is it really technically possible, due to how the sandbox works (and sandbox exceptions for multiple vendor apps).

You need to `uninstall` and `install` the app.
