### ISSUE TITLE
detox.init() fails after updating xcode 11 / iOS 13

### ISSUE THREAD

**Issue by PoojaMD** [wix/Detox#1863]
detox.init() fails after updating xcode 11 / iOS 13
Detox: "^14.9.2", React Native: n"0.61.4" Node: v12.13.0 Device: iPhone 11 Xcode: 11.3 iOS: 13.3 macOS: 10.14.6

**Comment by LeoNatan** [comment]
> ### The issue templates are there for a reason; please follow them and provide all the requested information! Note that any issue not following the appropriate issue template or missing information will be closed.
