### ISSUE TITLE
Better real-time app log debugging

### ISSUE THREAD

**Issue by noomorph** [wix/Detox#1868]
**Is your feature request related to a problem? Please describe.**

The debugging hint below is not helpful when the tested app is (re)installed, as it strongly depends on the current app installation directory which changes with every single install.

```
detox[55742] INFO:  [AppleSimUtils.js] com.wix.detox-example launched. To watch simulator logs, run:
        /usr/bin/xcrun simctl spawn CCDA48AC-A9FD-4C78-AEC3-76F7443446ED log stream --level debug --style compact --predicate 'processImagePath beginsWith "/Users/rotemm/Library/Developer/CoreSimulator/Devices/CCDA48AC-A9FD-4C78-AEC3-76F7443446ED/data/Containers/Bundle/Application/F1F3A9BC-BA11-464C-BB7E-E85BCA7766B2/example.app"'
```

**Describe the solution you'd like**

Detox should provide an easier way to see the application logs, retaining info after the application starts.

**Describe alternatives you've considered**

At the very least, the former hint with `tail -F` was more helpful in this context:

https://github.com/wix/Detox/blob/f6b8371b9e18b256d5325d0109fe9aee01340540/detox/src/devices/ios/AppleSimUtils.js#L279-L280

/cc @rotemmiz

**Comment by silyevsk** [comment]
It would also be very helpful to see only stdout+stderr logs - without all the rest

**Comment by LeoNatan** [comment]
What is the issue here exactly?
If an app is reinstalled during test, perhaps we should use `processImagePath endswith ` and the process name. This will be stable across reinstalls.

@silyevsk It's not possible. The way Apple logging is, some stuff is not printed in stderr but is only printed in the system log. This is why we moved to this system. This is the Apple recommended way.

The recommended way to filter logs is to have a subsystem and category. No idea if this is supported by RN, but you can expose your own logging function and use that, with a custom subsystem. You can then filter for that subsystem in the predicate. There is no way to achieve this generically in Detox.

Also @noomorph https://github.com/wix/Detox/issues/1024

**Comment by silyevsk** [comment]
What stuff exactly is not printed to stderr/stdout?
The issue is that what a detox user needs in 99% of the time is their own console.logs and exceptions - and we don't have a convenient way to see it.

**Comment by LeoNatan** [comment]
Anything that is not printed using NSLog, such as Detox' own logs, but also system logs that we need. There is no generic way to separate user logs from system logs.

React Native has `RCTSetLogFunction()` which you can use to call `os_log` with a custom subsystem. Then you can easily filter the log to only include your own subsystem.

**Comment by LeoNatan** [comment]
Are we speaking about what is output in the artifacts log, or about users debugging their own logs on their own PCs? If the latter, users should know best how to filter their own logs, no?

**Comment by silyevsk** [comment]
The latter mainly. Users should have convenient way to see their logs, and now they don't. Why not to return that simple mechanism of adding `--stdout`/`--stderr` params to `simctl` ? I understand that you want to see more logs, but you've added them at the expense of convenience of your users. Why not allow both ways and let the user choose what they want to use?

**Comment by LeoNatan** [comment]
We had users requesting the current way. This (and Nir offline) is the only complaint we've had about the current system.
I'm not sure how much complexity adding both solutions would introduce to the project, and also not sure what other effects adding those arguments have. I think the solution should come from the users.

**Comment by silyevsk** [comment]
May I ask how many users requested the current way? And how many users should upvote this ticket for you to consider to return the old way?

**Comment by LeoNatan** [comment]
I don't remember. It was in TODO already because I needed it, as well as debugging Detox itself needed (like, for example, getting crash info—it's not printed in stderr). And it's not about peer-pressure, it's about where our limited resources should go. I'm not sure maintaining this complexity is something we should do, when the simplest and most correct solution is to add a logger function in your app.

**Comment by Niryo** [comment]
+1 for supporting both ways. how can it add complexity? the old way was already implemented

**Comment by LeoNatan** [comment]
@Niryo It has already been removed. Also, not sure how adding those arguments changes the log output from what we currently have.

**Comment by LeoNatan** [comment]
<img width="701" alt="Screen Shot 2020-01-22 at 10 59 21" src="https://user-images.githubusercontent.com/2270433/72879834-5f86f680-3d06-11ea-9127-f7cfb4dd6f93.png">

Verified. If you provide a custom logging function using `RCTSetLogFunction()`, the JavaScript log calls will go to that function. You can even differentiate between native RN logging and JS. That is the correct solution to your problem.

**Comment by silyevsk** [comment]
I don't understand: I'm not sure what you mean by peer-pressure, but you just mentioned that the current way of logs was requested by users - it was an argument in favor of the current way of logging, but if most users prefer the old way then this argument is not valid.

**Comment by LeoNatan** [comment]
Old way blocked me from debugging Detox. I'd reckon most users prefer their Detox working and debuggable. You and Nir are the only one requesting return to the old system. That's not "most users". Now that I've verified my proposed solution, I don't think we'll be moving forward with reverting. @rotemmiz

**Comment by silyevsk** [comment]
Causing every RN user to add this function is not user-friendly. But anyways, if it's used - what is the way to see the logs (including NSLogs and exceptions) but without all the new system logs?

**Comment by LeoNatan** [comment]
If you add the function, you can then filter by `--predicate "category=='ABC'"` or `--predicate "subsystem=='XYZ'"`.

**Comment by LeoNatan** [comment]
```
xcrun simctl spawn booted log stream --level debug --style compact --predicate "subsystem=='XYZ'"
```

**Comment by silyevsk** [comment]
That's why I asked you how many users requested the new way.

> Old way blocked me from debugging Detox. I'd reckon most users prefer their Detox working and debuggable. You and Nir are the only one requesting return to the old system. That's not "most users". Now that I've verified my proposed solution, I don't think we'll be moving forward with reverting. @rotemmiz

**Comment by LeoNatan** [comment]
@silyevsk As for RN, I agree that the default is not optimal. They are using `fprintf`. Feel free to open an issue with them, to change to `os_log` for iOS 10 and above.

**Comment by silyevsk** [comment]
> ```
> xcrun simctl spawn booted log stream --level debug --style compact --predicate "subsystem=='XYZ'"
> ```
> 
> Or limit to a specific device, if you run multiple in parallel.

Does this look user-friendly to you?

**Comment by LeoNatan** [comment]
That's what Apple recommends. That's user friendly enough for me.

**Comment by silyevsk** [comment]
I'm asking if you think it's user-friendly for detox users, not for you.

**Comment by LeoNatan** [comment]
Detox users live within the confinements of the ecosystem they develop for. I think the current `To watch simulator logs, run:` copypasta is good enough for most users already. For advanced users, the line you quoted seems fine.

**Comment by LeoNatan** [comment]
Suggested reading:
https://www.iosdev.recipes/simulator/os_log/

**Comment by LeoNatan** [comment]
https://github.com/facebook/react-native/issues/27863

I've created an issue in RN regarding `console.log()`s not appearing in the log. I'll write a PR if they accept.

**Comment by LeoNatan** [comment]
The hint text has been fixed with a correct command that will work across app reinstalls.
