### ISSUE TITLE
Seeking Input for a React Native Testing API

### ISSUE THREAD

**Issue by cs01** [wix/Detox#1886]
I am a software engineer at facebook and have been working with the React Native team to improve the compatibility and reliability of React Native with testing frameworks. There are various Detox issues describing the use of reflection and reliance on non-public APIs which may break in the future. To remedy that, we would like to support public APIs for testing. 

As you know, the React Native team is currently in the process of rewriting several pieces of React Native's core infrastructure. As part of those projects, @ejanzer is planning to investigate improving the APIs available for testing (idle detection, etc.) and is interested in hearing from the Detox team about what APIs they would like to see. 

Additionally, the team is open to changes to the core to better accommodate testing in the current infrastructure. If you would like to submit pull requests implementing these APIs before the React Native team finishes the rewrite, the team would be happy to review them.

Related issues:
https://github.com/wix/Detox/issues/1801
https://github.com/wix/detox/issues/907

cc @TheSavior @ejanzer @rodrigos-facebook @axe-fb

**Comment by ejanzer** [comment]
Like @cs01 said, I'm going to be looking into improving our testing APIs for the new (bridgeless) architecture soon - @rotemmiz have already shared a link about [Espresso's event-based idling resources](https://developer.android.com/training/testing/espresso/idling-resource#integrate-recommended-approach), which I'll definitely take a look at. But if you have other details or specific APIs you'd like to see implemented, I'd love to hear more, or meet and discuss. I can't guarantee that I'll be able to implement all of them, but I definitely want to make this better for the new architecture if I can :)

**Comment by LeoNatan** [comment]
Hi guys,

Thank you for creating this issue and offering assistance!
Is the current effort focusing on Android, or will you be willing to look into iOS APIs as well? Historically, iOS has been more stable than Android due to ability to much more easily swizzle methods, but if you are open to additions on the iOS side, I can compile our current swizzle points and think what API we can there too. On iOS, we are working to rewrite Detox to not use Earl Grey (the iOS equivalent of Espresso) and instead use [DetoxSync](https://github.com/wix/DetoxSync), our bespoke fully event-based implementation. The rewrite work is on going.

Thanks,

**Comment by ejanzer** [comment]
Hey @LeoNatan, I'm focused on the Android side, but the bridgeless rewrite is for both - I don't know much about the current state of our testing infrastructure on iOS, so I'll let @PeteTheHeat weigh in on that one. I imagine we're open to contributions on iOS as well.

**Comment by d4vidi** [comment]
@cs01 @ejanzer this is exciting to hear! We'd be thrilled to help. As already mentioned in other issues, the best way to implement idle resource monitors is in an async fashion, so putting this out there -- if you're going to provide test API's, best if you don't just migrate Detox code (which is implemented sync'ly, on Android in particular).

In any case, if you rather get a more direct channel we could embrace Discord or Wix' OSS slack.

**Comment by ejanzer** [comment]
@d4vidi Yup, agreed. Discord sounds good - maybe either #testing or #detox?

**Comment by d4vidi** [comment]
Great! Though currently off working hours, we're basically there 👍

**Comment by PeteTheHeat** [comment]
Definitely open to additions on the iOS side as well!

**Comment by crutchcorn** [comment]
@d4vidi where's the Slack/Discord you were referring to? I am having the HARDEST time getting Detox working and have spent now 8+ hours trying to get the last bit of config working and need some help. GitHub issues don't feel appropriate for this support request

**Comment by cs01** [comment]
Closing issue in favor of discussion on discord.

**Comment by d4vidi** [comment]
Hey @cs01, couldn't find the discord discussion you were referring to (not even on the RN contribs).
In any case, LMK if you need to reach out in person, we're all ears.
