### ISSUE TITLE
Unable to tap, or type or replaceText()

### ISSUE THREAD

**Issue by hqdai** [wix/Detox#1889]
### Description
I have problem with the all Detox's versions > 14.4.0, I'm using **react-native-search-bar** in my project and do some test scenarios relate to this module, this module provide a text search box that allow us to key in. My test scenarios are running fine but after upgrade to version above version 14.4.0, When I run detox test, it can't tap or type or replaceText to search bar text box. I've tried to upgrade to latest version of detox (15.1.4) and version above such as 14.4.1 ... 14.9.2,but it still not work. But if I stop detox, run the app in-depend on Detox, I can tap to search bar text box and type text manually.

#### When run Detox, can't tap or type or replaceText in search bar.
![Detox-CanNotText](https://user-images.githubusercontent.com/19548213/73834523-75380800-483e-11ea-9de0-47b608270d83.gif)

#### Without Detox or with Detox 14.4.0, working fine without Detox run or Detox version 14.4.0
![Detox-CanText](https://user-images.githubusercontent.com/19548213/73834549-7f5a0680-483e-11ea-86d1-93b8bb2e37a9.gif)

#### Environment (please complete the following information):
 - Detox: 15.1.4
 - React Native: 0.60.5
 - Node: 10.16.3
 - Device: iPhone 11
 - Xcode: 11.3.1
 - iOS: 13.3
 - macOS: Catalina 10.15.2

**Comment by LeoNatan** [comment]
Hello,
Can you please create an empty project using `react-native init`, add the component and create a basic test which reproduces this?
Thanks

**Comment by hqdai** [comment]
Yes, sure
I can reproduce by init new project with installed module. Please take a look on the zip file.
When you run the project, (react-native run-ios), you can touch and also add text, type text in SearchBar. But when you run the test (detox test), you're unable to do any thing with SearchBar.

[TestSearchBar.zip](https://github.com/wix/Detox/files/4163146/TestSearchBar.zip)
 
Thanks

**Comment by LeoNatan** [comment]
Thanks, I’ll take a look.

**Comment by LeoNatan** [comment]
Reproduced. How odd.

**Comment by LeoNatan** [comment]
It's something in Earl Grey that is causing it but not sure why it's happening. I have a hack that will solve it.

**Comment by LeoNatan** [comment]
Fixed in https://github.com/wix/Detox/commit/1634d7ee225aa4bfb9eaeaad2583e9341e072455
