### ISSUE TITLE
Post install script fails

### ISSUE THREAD

**Issue by jurajzsiga** [wix/Detox#1892]
### Description
After running `yarn` I get an error 

```

~/Library/Detox/ios/2e7c24710b5b9ca03944d3841c83806444f7bf58 was found, but could not find Detox.framework inside it. This means that the Detox framework build process was interrupted.
         deleting ~/Library/Detox/ios/2e7c24710b5b9ca03944d3841c83806444f7bf58 and trying to rebuild.
```

It seems similar to issues #1866, #1620, #1779, #1092, #1439, #897 and #889.

- [x] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

1. Clone repository
2. Install node_modules
3. Crash during postinstall.js

It is also important to note that my disk is **case insensitive**, as I saw that it was problem on another issue (but it was marked as resolved. Also **I am the only one of our team that is experiencing this issue**. So it seems there might be something wrong with my setup (but I tried clean install, reinstalling xcode, detox-cli, node modules, cloned repo again, removed DerivedData, restarted PC and nothing worked).

#### Expected behavior
Node modules should install successfully.

#### Screenshots
\-

#### Environment (please complete the following information):
 - Detox: 15.1.4
 - React Native: 0.59.10
 - Node: 10.15.0
 - Device: Not relevant
 - Xcode: 11.3.1
 - iOS: Not relevant
 - macOS: 10.15.1

#### If you are seeing a build problem (e.g. during `npm install`)
- [x] I am providing the `npm install` log below:
```
[4/4] 🔨  Building fresh packages...
[-/8] ⡀ waiting...
[-/8] ⡀ waiting...
[-/8] ⡀ waiting...
[8/8] ⡀ detox
error /Users/jurray/Documents/Webscope/staffers-pls/node_modules/detox: Command failed.
Exit code: 1
Command: node scripts/postinstall.js
Arguments: 
Directory: /Users/jurray/Documents/Webscope/staffers-pls/node_modules/detox
Output:
/Users/jurray/Library/Detox/ios/2e7c24710b5b9ca03944d3841c83806444f7bf58 was found, but could not find Detox.framework inside it. This means that the Detox framework build process was interrupted.
         deleting /Users/jurray/Library/Detox/ios/2e7c24710b5b9ca03944d3841c83806444f7bf58 and trying to rebuild.
Extracting Detox sources...
Building Detox.framework from /Users/jurray/Documents/Webscope/staffers-pls/node_modules/detox/ios_src...
child_process.js:637
    throw err;
    ^

Error: Command failed: /Users/jurray/Documents/Webscope/staffers-pls/node_modules/detox/scripts/build_framework.ios.sh
    at checkExecSyncError (child_process.js:616:11)
    at Object.execFileSync (child_process.js:634:13)
    at Object.<anonymous> (/Users/jurray/Documents/Webscope/staffers-pls/node_modules/detox/scripts/postinstall.js:2:27)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)

```

**Comment by LeoNatan** [comment]
Try running `detox rebuild-framework-cache` from your project's root dir. See if it helps.

**Comment by LeoNatan** [comment]
Hm, it's supposed to print the log of the failed script.

Can you pls provide log file from `/Users/jurray/Library/Detox/ios/2e7c24710b5b9ca03944d3841c83806444f7bf58`?

**Comment by jurajzsiga** [comment]
Sure
[detox_ios.log](https://github.com/wix/Detox/files/4168058/detox_ios.log)

**Comment by LeoNatan** [comment]
Huh, very odd. It builds both EarlGrey and SocketRocket, but then fails when code imports them. Not sure what is going on. Could be your environment is somehow influencing the build system incorrectly? Do you have a different machine to test installing?

Could you download the latest Detox tgz from npm, extract it and try to manually build the framework from Xcode?

**Comment by jurajzsiga** [comment]
Well, as for the other machines, the two colleagues of mine have no issues running Detox on their PCs on the same project.
Could you please provide some guidance on how I can manually build the framework from Xcode? I don't have much experience with it.

**Comment by LeoNatan** [comment]
Obtain the latest Detox tgz from npmjs. Extract it. Inside, you should see a Detox-ios-src.tbz file. Extract that. Go inside, there should be a Detox.xcodeproj package. Open it, and hit CMD+B to build.

**Comment by jurajzsiga** [comment]
<img width="1431" alt="Screenshot 2020-02-09 at 17 28 45" src="https://user-images.githubusercontent.com/56552975/74105844-bb080f80-4b61-11ea-864c-2491d729084f.png">

**Comment by LeoNatan** [comment]
Can you please take a screenshot of the Locations page in Preferences?

**Comment by jurajzsiga** [comment]
I figured it out. I changed the DerivedData folder from Default to Relative and now it works, thanks so much for the help.

**Comment by LeoNatan** [comment]
Hmm
That setting shouldn't influence the build script.

**Comment by jurajzsiga** [comment]
I can post the screen in the evening, I'm not on my Mac atm.

**Comment by LeoNatan** [comment]
I’ll look at the script, if we can change something in the build command to make it less dependent on user settings.

**Comment by kelokchan** [comment]
I restarted my Mac and the post-install worked

**Comment by LeoNatan** [comment]
😂

Maybe we should add that as a checkbox in the issue template. Also, dancing around the fire three times. You can’t know with Apple these days.
