### ISSUE TITLE
Detox is adding SocketRocket as a dependency to my Podfile.lock

### ISSUE THREAD

**Issue by elyalvarado** [wix/Detox#1893]
### Description
When installing Detox, it is adding SocketRocket as a dependency to my cocoa pods `Podfile.lock` file.

- [X] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction

Using React Native 0.61.5 with `use_native_modules!` in my `ios/Podfile`

1. Add Detox to the project.
2. Execute `pod install` in the iOS folder
3. Check that `SocketRocket` was added in the `Podfile.lock`

#### Expected behavior
Detox shouldn't add dependencies to the iOS project

#### Environment (please complete the following information):
 - Detox: 15.1.4
 - React Native: 0.61.5
 - Node: 10.19.0
 - Device: Independent of Device
 - Xcode: 11.1
 - iOS: Independent of iOS version
 - macOS: 10.14.6

**Comment by LeoNatan** [comment]
I'm sorry, that makes no sense. Detox does not modify any of your project's files. Something else is doing it.

**Comment by elyalvarado** [comment]
@LeoNatan I agree with you, however it does. I upgraded detox from version 15.1.1 to version 15.1.4, and after running `pod install` the following appeared on my `Podfile.lock`:

```
  - SocketRocket (from `../node_modules/detox/ios_src/SocketRocket`)
```

**Comment by elyalvarado** [comment]
Please disregard this issue. It resolved itself after I deleted and recreated `node_modules`.

**Comment by LeoNatan** [comment]
Nothing has changed in Detox regarding Cocoa Pods. Detox doesn't use it, doesn't rely on it. SocketRocket is consumed by Detox as a submodule.
