### ISSUE TITLE
Detox is adding SocketRocket as a dependency to my Podfile.lock

### ISSUE THREAD

**Issue by peterjuras** [wix/Detox#1895]
### Description

Re-opened from #1893 since this is still an issue.

The postinstall script of detox extracts the Detox-ios-src archive in node_modules. This includes the `ios-src/SocketRocket` folder, which includes a podspec that will be read by the `use_native_modules!` directive in the Podfile of the react-native ios project.

I'm not 100% sure if this is the root cause, but it definitely has something to do with the ios_src folder and SocketRocket as a dependency, since it is being added to Podfile.lock.

This leads to inconsistent builds, since I don't get the SocketRocket pod added locally, but it is added on CI (where there is no previous build cache installed).

- [X] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction

1. Ensure that the framework cache is cleared by running `detox clean-framework-cache` in your react-native project root folder
2. Remove the `node_modules` folder
3. Install node_modules (yarn or npm)
4. Install pods (`cd ios; pod install`)

-> SocketRocket is added to Podfile.lock

#### Expected behavior

SocketRocket should not be added to Podfile.lock.
One way to achieve this (?) might be to delete the ios_src folder after the postinstall script has run.

#### Screenshots

/

#### Environment (please complete the following information):
 - Detox: 15.1.4
 - React Native: 0.61.0
 - Node: 10.18.1
 - Device: /
 - Xcode: 11.3.1
 - iOS: /
 - macOS: 10.15.3

#### If you are seeing a build problem (e.g. during `npm install`)
- [x] I am providing the `npm install` log below:

```
detox-test npm i detox

> dtrace-provider@0.8.8 install /Users/juras/src/misc/detox-test/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

  ACTION binding_gyp_ndtp_target_build_ndtp .
  TOUCH Release/obj.target/ndtp.stamp

> detox@15.1.4 postinstall /Users/juras/src/misc/detox-test/node_modules/detox
> node scripts/postinstall.js

Extracting Detox sources...
Building Detox.framework from /Users/juras/src/misc/detox-test/node_modules/detox/ios_src...
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN detox-test@1.0.0 No description
npm WARN detox-test@1.0.0 No repository field.

+ detox@15.1.4
added 117 packages from 167 contributors and audited 318 packages in 42.494s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by LeoNatan** [comment]
Detox does not modify and Podfile. This could be a bug in CocoaPods. I suggest opening an issue with them to ask why this is happening. Detox is at no point added as a dependency in Podfile, so none of its contents should make its way to CocoaPods.

**Comment by leethree** [comment]
this is because there is a `SocketRocket.podspec` in `node_modules/detox/ios_src/SocketRocket/`. it's picked up automatically by [React-Native autolinking](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md). 

it can be disabled by adding
```
module.exports = {
    detox: {
      // do not autolink detox
      platforms: {
        ios: null,
        android: null,
      },
    },
};
```
to `react-native.config.js`

But it will be the best if we can somehow remove the `Podspec` file from the published module.
