### ISSUE TITLE
Android build fails with React Native v0.61 due to version conflict

### ISSUE THREAD

**Issue by sonicdoe** [wix/Detox#1898]
#### Describe the bug

The Android build fails with React Native v0.61.5 due to a version conflict with `androidx.annotation:annotation`.

#### To reproduce

✓ I have tested this issue on the latest Detox release and it still reproduces.

Steps to reproduce:

1. `npx react-native init AwesomeProject --version 0.61.5`
2. `cd AwesomeProject`
3. `yarn add detox --dev`
4. [Add Detox to the Android project](https://github.com/wix/Detox/blob/15.1.4/docs/Introduction.Android.md#2-add-detox-dependency-to-an-android-project)
5. [Add Kotlin](https://github.com/wix/Detox/blob/15.1.4/docs/Introduction.Android.md#3-add-kotlin)
6. [Create the test class](https://github.com/wix/Detox/blob/15.1.4/docs/Introduction.Android.md#4-create-android-test-class)
7. [Add the Android configuration to `package.json`](https://github.com/wix/Detox/blob/15.1.4/docs/Introduction.Android.md#5-add-android-configuration)
8. `npx detox build --configuration android.emu.debug`

The build then fails with:

```
Could not determine the dependencies of task ':app:preDebugAndroidTestBuild'.
> Could not resolve all task dependencies for configuration ':app:debugAndroidTestRuntimeClasspath'.
   > Could not resolve androidx.annotation:annotation:{strictly 1.0.0}.
     Required by:
         project :app
      > Cannot find a version of 'androidx.annotation:annotation' that satisfies the version constraints: 
           …
```

This issue does not reproduce with the [React Native demo project](https://github.com/wix/Detox/tree/15.1.4/examples/demo-react-native) because [it explicitly depends on `androidx.appcompat:appcompat:1.1.0`](https://github.com/wix/Detox/blob/15.1.4/examples/demo-react-native/android/app/build.gradle#L69) whereas [the default React Native template does not](https://github.com/facebook/react-native/blob/v0.61.5/template/android/app/build.gradle#L181-L192).

The same issue has been reported in https://github.com/wix/Detox/issues/1534, https://github.com/wix/Detox/issues/1537, https://github.com/wix/Detox/issues/1583, and https://github.com/wix/Detox/issues/1631.

#### Environment

- Detox: v15.1.4
- React Native: v0.61.5
- Node.js: v12.15.0
- OS: macOS

**Comment by d4vidi** [comment]
@sonicdoe did you try to read through the versions conflict [troubleshooting guide](https://github.com/wix/Detox/blob/15.1.4/docs/Introduction.Android.md#problem-kotlin-stdlib-version-conflicts)? If not, please review it - I hope it'd help.

**Comment by sonicdoe** [comment]
I don’t think the Kotlin version conflicts apply here. There are some workarounds such as https://github.com/wix/Detox/issues/1534#issuecomment-512270679, however, Detox should arguably work out of the box with the latest React Native version.

Would it be feasible to relax [the `androidx.annotation:annotation` version constraint](https://github.com/wix/Detox/blob/993440c59269b4fde4988fc0966dd67f26c08637/detox/android/detox/build.gradle#L77)?

**Comment by d4vidi** [comment]
The point was to apply the same technique in the scope of the annotation dep. (rather than kotlin).
The `resolutionStrategy` is indeed another way of solving that, you can use either.

>Would it be feasible to relax the androidx.annotation:annotation version constraint?
I will have to take a deeper look at that.

**Comment by sonicdoe** [comment]
Rereading my comment from yesterday, I hope “Detox should arguably work out of the box” didn’t come across as disdainful. I know there are workarounds for this issue but not every new user might know about these and immediately running into an error with a fresh React Native project can be frustrating. I opened an issue instead of a pull request because I’m not sure about the right solution; it might be relaxing the version constraint or it might be updating the Android guide.

**Comment by d4vidi** [comment]
@sonicdoe I totally agree , but on the practical side we need to choose our battles. This is actually the kind of case that we would love to get help from the community.
