### ISSUE TITLE
Demo project says Android is not supported

### ISSUE THREAD

**Issue by sonicdoe** [wix/Detox#1901]
The [Pure Native Android Demo Project](https://github.com/wix/Detox/tree/6b765fba149b054f26559db753afb778d6f74fe5/examples/demo-native-android)’s readme says:

> Android is not supported in detox yet. This project is here for development purposes and is not working at the moment.

**Comment by LeoNatan** [comment]
"Pure native Android" is not supported yet. The naming is ridiculous, I agree.
What it means is that apps without React Native are currently not supported by Detox on Android. On iOS, they are. Sorry for the confusion.

**Comment by sonicdoe** [comment]
Thank you for clarifying 👌
