### ISSUE TITLE
Test hangs when Modal is open

### ISSUE THREAD

**Issue by kelokchan** [wix/Detox#1905]
I'm writing a test that is expecting a View within a Modal to be visible. But the test would hang when the Modal is shown. When I close the modal the test would continue and fail because the View is no longer visible. 

Anyone managed to get the detox running with `Modal` open?

**Comment by d4vidi** [comment]
@kelokchan if you believe there's an actual problem here, please reopen an issue through one of the bug templates. Thanks!
