### ISSUE TITLE
Taps don't work during test after app restarts 

### ISSUE THREAD

**Issue by MrRob0t404** [wix/Detox#1907]
Describe the bug
When the tap method is called, Detox attempts to tap the button (the circle does not shows up). Replacing the tap method with the multiTap(2) does not work as well. If I click on the button on the simulator the button works correctly so tap should as well. I suspect this is because at one point, during setup, we have to restart the app, but both release and debug should be failing if that was the case. I'm pretty stuck on this. 

Running the test on debug locally, all of the tests pass. 
Running the test on release fails after a certain point in the test 

During release, this error message would appear 

` App has not responded to the network requests below:
  (id = 12) invoke: {"target":{"type":"Class","value":"com.wix.detox.espresso.EspressoDetox"},"method":"perform","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"androidx.test.espresso.Espresso"},"method":"onView","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"com.wix.detox.espresso.DetoxMatcher"},"method":"matcherForTestId","args":["splashPage.fullScreenButton"]}}]}},{"type":"Invocation","value":{"target":{"type":"Class","value":"com.wix.detox.espresso.DetoxViewActions"},"method":"click","args":[]}}]}

Unresponded network requests might result in timeout errors in Detox tests.`

To Reproduce

I have tested this issue on the latest Detox release and it still reproduces

Detox: 14.5.0
React Native: 0.60.5
Device: Android 
APK: 25
MacOS: 10.14.6

**Comment by d4vidi** [comment]
@MrRob0t404 please provide screenshots and device logs, as explained in the bugs template 🙏
