### ISSUE TITLE
Error: Detox.framework not found

### ISSUE THREAD

**Issue by tlenclos** [wix/detox#191]
I just installed Detox with yarn v0.24.6 and node v8.1.3 and the framework is not extracted.

It works with node < 8.

**Comment by LeoNatan** [comment]
@DanielZlotin Do you have any idea what could cause this?
CC @rotemmiz

**Comment by DanielZlotin** [comment]
Maybe something installed globally with npm? If you're using nvm this will be easy to rule out/confirm

**Comment by DanielZlotin** [comment]
Also, where do you get this error? Compile time in xcode? Running tests?

**Comment by rotemmiz** [comment]
You can set verbose logging when installing either with `yarn install --verbose` or `npm install --loglevel verbose`
It will be great if you can paste the relevant part of your installation log here.

**Comment by tlenclos** [comment]
I got this error after installing detox and running the tests with `detox test` but I can't reproduce it sadly. You can close this for now and I will post more info if it happens again.

**Comment by rumax** [comment]
>  installed Detox with yarn

Maybe you can try `npm rebuild` after using `yarn`. It works for me. Otherwise I get 

> node_modules/.bin/detox: fork: Resource temporarily unavailable

But I use:
 - node v7.10.0
 - detox v5.0.12
 - detox-cli v1.0.1

**Comment by AshleyRodanHP** [comment]
Its pretty clear that detox is not being compiled when installing yarn. Also _npm install detox -g_ will 

after running 
```
npm rebuild detox
```

it fixes it for me

**Comment by AshleyRodanHP** [comment]
doing some research it seems like its a yarn issue.

Same sort of issue these guys have: 
https://github.com/sass/node-sass/issues/1804
