### ISSUE TITLE
allow video codec to be specified

### ISSUE THREAD

**Issue by cs01** [wix/Detox#1912]
**Is your feature request related to a problem? Please describe.**
When recording video, Detox does not not allow for the codec of the video to be specified. This makes us run an extra step to convert the video to a format supported by web browsers, since the default format, hevc, cannot play in the browser. We are viewing test failures through a web based application, so we need to get the video to something like h.264.

**Describe the solution you'd like**
Add support for an additional argument specifying the encoding. This is supported by xcode, so it is as simple as passing another argument to the shell command. The command would optionally have ` --codec $CODEC` (i.e. `--codec h264`) appended to it:

https://github.com/wix/Detox/blob/5dfb9caa601acaf9c825bfdfd3b92611326100b5/detox/src/devices/ios/AppleSimUtils.js#L236

**Describe alternatives you've considered**
Record video, then manually convert it. Below, the video is converted to h.264
```
>> ffmpeg -i hevc_encoded.mp4 -vcodec libx264 -acodec aac h264_encoded.mp4
```

**Additional context**
```
>> xcrun simctl io --help
Set up a device IO operation.
Usage: simctl io <device> <operation> <arguments>

Supported operations:
...

	recordVideo [--codec=<codec>] [--display=<display>] [--mask=<policy>] [--force] <file or url>
	    Records the display to a QuickTime movie at the specified file or url.
	    --codec      Specifies the codec type: "h264" or "hevc". Default is "hevc".
...
```

**Comment by LeoNatan** [comment]
This sounds interesting, but unfortunately, we won't have the bandwidth to implement this internally. Would you mind submitting a PR for this?

**Comment by cs01** [comment]
I would be happy to.

**Comment by cs01** [comment]
While making these changes it occurred to me that having types, such as with TypeScript, would make me more comfortable that I'm not breaking things or making mistakes. Is TypeScript used by the Detox team during development of Detox's js code?

**Comment by noomorph** [comment]
See configuration.js, ADB.js and Android vide recording plugin source code files. The pull request should be simple enough.

As for TypeScript, this is a pain point in the team, but tl;dr - no, we use only JSDoc for some type checking and that's it.

**Comment by noomorph** [comment]
@cs01, open a new issue if PR #1920 seems not enough.
