### ISSUE TITLE
Record device logs even when a beforeAll fails

### ISSUE THREAD

**Issue by viktorijasujetaite** [wix/Detox#1914]
**Describe the bug**
Detox does not produce device logs when an inner `beforeAll()` (inside the scope of a single describe) fails to complete. In such cases - running on private projects, only the `testDone.png` artifact was available, even though `--record-logs all/failed` was used.

**Expected behavior**
Device logs should be produced in this scenario.

**Environment (please complete the following information):**
 - Detox: 15.2.2 (latest)
 - React Native: 0.61.5
 - Node: v10.15.0
 - Device: Pixel 3
 - OS: API 28
 - Test-runner (select one): Jest+jest-circus

**Comment by d4vidi** [comment]
@noomorph I believe you have insights in this regard.

**Comment by d4vidi** [comment]
not stale. has pending PR's open.

**Comment by d4vidi** [comment]
@noomorph wasn't this fixed, in essence?

**Comment by noomorph** [comment]
@d4vidi , theoretically, yes. In practice, haven't received a firm "yes/no".

**Comment by noomorph** [comment]
@viktorijasujetaite, I am closing this issue as resolved. You are welcome to reopen with a specific use case that might be still uncovered by the fixes. In theory, now the artifacts should be recorded without a problem.
