### ISSUE TITLE
Adding victory-native makes the tests hang

### ISSUE THREAD

**Issue by mgabrielyan-bb** [wix/Detox#1918]
For more details please see the following example: https://github.com/Osedea/react-native-victory-native-detox-bug

**Versions:**
Detox: 15.2.2
Victory-native: 34.0.0

Please let me know if more information is needed.

**Comment by d4vidi** [comment]
@mgabrielyan-bb please try to pinpoint the root cause and reopen a new one with detox and device logs. A demo app is indeed much appreciated, but we cannot help unless you specify what's exactly wrong with detox.
