### ISSUE TITLE
Error: While installing 'fbsimctl' dependencies

### ISSUE THREAD

**Issue by kantharia** [wix/detox#192]
I am following getting started [documentation](https://github.com/wix/detox/blob/master/docs/Introduction.GettingStarted.md). I got stuck on Step 1 -> 3. Install fbsimctl.

I am getting errors : 
- error: 'FBSimulatorControl/FBSimulatorControl.h' file not found

**_Please check screenshot for details_**

![screen shot 2017-07-11 at 4 18 03 pm](https://user-images.githubusercontent.com/8065874/28065068-a5b65df2-6654-11e7-9b86-82dc6b22fe8f.png)

**Comment by LeoNatan** [comment]
This looks like an issue with fbsimctl. Please open an issue there.
