### ISSUE TITLE
Enforce 'prettier' styling on CI build

### ISSUE THREAD

**Issue by cs01** [wix/Detox#1921]
**Is your feature request related to a problem? Please describe.**
I see a .prettierrc file, but running it results in many changes to files, indicating PRs can be merged without running prettier. Autoformatting reduces friction when developing and reviewing code. 

**Describe the solution you'd like**
Run prettier on CI build and fail if JavaSCript code has not been autoformatted with prettier. Is this something the team would be open to adding? I can put up a PR.

**Comment by LeoNatan** [comment]
I am not a fan of that. I don't know what was added, but I dislike these automated linters. Even worse is having a linter stop people (internal or community) from being able to submit PRs. We've had this discussion in the past and have decided against it.
