### ISSUE TITLE
Better Support for Lerna/Yarn worskapces

### ISSUE THREAD

**Issue by tad3j** [wix/Detox#1928]
**Is your feature request related to a problem? Please describe.**
I've got detox working with my lerna/yarn workspace/monorepo, but I have to include `jest` in package.json in sub folder to get it working. My folder structure is:
-root folder
--package.json <- jest dependency for all 4 packages
--node_modules
---.bin
----jest <- **detox can't find this executable**
---packages
----mobile
-----package.json <- **detox config + jest dependency**
-----node_modules
------.bin
-------jest <- **detox works if I add dependency to `packages\mobile\packages.json`**
...other packages

This isn't the best I think since one has to maintain common dependency in multiple package.json files. If I only place dependency in root package.json I get `'node_modules\.bin\jest' is not recognized as an internal or external command`.

**Describe the solution you'd like**
Solutions recommended by yarn: `multi-root`, `custom module map`, `clever traversing scheme` : https://classic.yarnpkg.com/blog/2018/02/15/nohoist/ (although the issue is not in hoisting...just in executables, I think solution is the same)

I think one simple solution would be to look for `test-runner` executable in working + 2 parent directories (so in my case we would first look for `node_modules/./bin/jest` in `mobile` folder, then `packages` folder and finally `root folder`...only then failing). I think this is the place where code would have to be changed/added: https://github.com/wix/Detox/blob/8b3a973c5d1937211436d7db4d05896e00eaa2b7/detox/local-cli/test.js#L258

Would you accept this in your code base? I was researching a bit and I couldn't find any other standard way to handle that. Maybe to prevent going outside the project folder we could compare if root was reached and abort there.

**Describe alternatives you've considered**
As mentioned above adding `jest` to dependencies in package.json in subfolder (mobile in my case), works as a workaround, however I think in general isn't the best solution since one could end up testing his packages with different versions of jest. Also hoisting is not an issue, since yarn will still add executable to node_modules\.bin in the directory where jest is included (package.json).

**Comment by LeoNatan** [comment]
I don't really understand the issue here as I am unfamiliar with this ecosystem, but I don't think traversing arbitrary user folders, potentially outside of the current project scope, is a good idea.

**Comment by tad3j** [comment]
Issue is that running detox throws `'node_modules\.bin\jest' is not recognized as an internal or external command` as mentioned above. Workaround is to prevent hoisting the executables in `root\node_modules\.bin` folder, so that they are available for detox in `root\packages\mobile\node_modules\.bin`. This solves the issue, but I don't like the part about adding duplicate dependencies into my root and mobile package.json (as far as I've read one should avoid it).....that's why I wanted to propose the change. I think it's the only change needed to be done to make detox fully compatible with monorepo/wrokspaces.

**Comment by LeoNatan** [comment]
I wonder if there are environment variables where the real path can be deduced? Or some other metadata.

**Comment by tad3j** [comment]
First thing that comes to my mind is that workspaces are defined in root package.json In my case:

```
"workspaces": {
    "packages": [
      "packages/*"
    ]
  },
```

Reference: https://classic.yarnpkg.com/en/docs/workspaces/#toc-how-to-use-it
