### ISSUE TITLE
Cant type text on a form field in web-page

### ISSUE THREAD

**Issue by pakkibokati2012** [wix/Detox#1933]
My app opens a webpage in browser after tapping on "Sign In" button. The user enters their username and password in respective fields. Is there any way I can type text in the form field inside webpage?

**Comment by LeoNatan** [comment]
Web views are not supported. Mock your API.

**Comment by pakkibokati2012** [comment]
@LeoNatan I am not talking about a webview. When the user tries to login a whole new app, the phone's default browser, is opened.

**Comment by LeoNatan** [comment]
But that’s even less supported. Detox only supports testing your app, not system apps, such as the browser. You really should follow our docs regarding mocking.
