### ISSUE TITLE
Device.setLocation does nothing on Android

### ISSUE THREAD

**Issue by wouterhund** [wix/Detox#1935]
**Describe the bug**

The Device.setLocation API is not implemented on Android. There once was a PR to implement this, but this PR is now locked (or I'd have commented there) and seems to never have been merged: https://github.com/wix/Detox/pull/951

**To Reproduce**

- [X] I have tested this issue on the latest Detox release and it still reproduces

Steps to reproduce:
1. Call `device.setLocation(x, y)` on android
2. Observe nothing happened

**Expected behavior**

The device location should change

**Screenshots**

Not relevant.

**Device and Verbose Detox Logs**

Not relevant.

**Environment (please complete the following information):**
 - Detox: 15.4.0
 - React Native: 0.61.5
 - Node: v10.19.0
 - Device: Any Android Emulator
 - OS: Android
 - Test-runner (select one): Mocha

**Comment by LeoNatan** [comment]
Feel free to submit a new PR, taking into account all the feedback that was given in the old PR.

**Comment by noomorph** [comment]
@wouterhund, should be available in the [18.18.0](https://github.com/wix/Detox/releases/tag/18.18.0) release.
