### ISSUE TITLE
Clean logs in terminal when running detox test

### ISSUE THREAD

**Issue by MayoudP** [wix/Detox#1938]
Hello, when I'm running `detox test` I got a lot of logs in the terminal and it's quite boring... and also not relevant informations. 
It looks like this : 
<img width="1067" alt="Capture d’écran 2020-02-27 à 16 40 28" src="https://user-images.githubusercontent.com/48682041/75459848-fdfb1d00-5980-11ea-9846-eaa289482a28.png">
I basically want to hide all the `[INFO] AppleSimUtils` which are useless... 

Any ideas about how to achieve that ? Thanks for the help !

**Comment by LeoNatan** [comment]
@noomorph Is it possible to tell it to ignore INFO messages?

**Comment by LeoNatan** [comment]
@MayoudP That is not useless information, that is how you get to your app's log 🙄 If you find that useless, let me sign you up to basic software engineering.

It should be possible to hide, though.

**Comment by MayoudP** [comment]
> @MayoudP That is not useless information, that is how you get to your app's log 🙄 If you find that useless, let me sign you up to basic software engineering.
> 
> It should be possible to hide, though.

Well if the test is actually passing, I don't really care about the log, it's indeed usefull is the test failed, but in the screenshot' case, yes it's useless since all tests are passing.

**Comment by noomorph** [comment]
Well, honestly, I would suggest moving that message from AppleSimUtils.js to DEBUG (verbose).

However, `--loglevel warning` is the direct answer to the question.

**Comment by LeoNatan** [comment]
Thanks @noomorph !
