### ISSUE TITLE
Confirming system messages

### ISSUE THREAD

**Issue by developer239** [wix/detox#194]
Hey, great framewrok. I just got stuck on confirming alert message.
I have simple code:

```
Alert.alert('Great!', 'Now Check us out.', [
  { text: 'Continue', onPress: () => { this.handleContinue() } }
])
```
How do I confirm the dialog? Thanks a lot for your help.

**Comment by rumax** [comment]
Did you try to use `text matcher`?

```
await element(by.text('Continue')).tap();
```

**Comment by LeoNatan** [comment]
Element by text should work if I recall correctly.

**Comment by almost** [comment]
This doesn't work if there is another element with the same label on the screen. Is there anything I can add to the matcher to make it more specific and only match the correct element?

**Comment by anton6** [comment]
@almost Not sure if this is still relevant, but for my case I used `.and()` with UIAlertControllerActionView to narrow it down.

https://stackoverflow.com/questions/47522081/detox-ios-simulator-how-to-confirm-alert-message

**Comment by kagalenitin** [comment]
@anton6 The solution in the stackoverflow link didn't work for me. I have tried 
`await element(by.label('Allow').and(by.type('UIAlertAction'))).tap()`
and
`await element(by.label('Allow').and(by.type('_UIAlertControllerActionView'))).tap()`
_UIAlertControllerActionView - I tried with UIAlertControllerActionView, but no luck.

Is there any other UIAlertActionAllow or something that I can use?

**Comment by jaumevn** [comment]
Hey there, I was trying to do the same, but using @anton6 didn't work for me now. Is there any other way to accomplish this? Thanks!

**Comment by anton6** [comment]
@jaumevn which iOS version? Do you know if it's the by.label or by.type part that fails to find the element?

**Comment by jaumevn** [comment]
It fails in the by.label part, I'm using iOS 8.2 version.
