### ISSUE TITLE
Jest expectations over the Detox ones

### ISSUE THREAD

**Issue by rostyaka** [wix/Detox#1959]
Hi! Can I use Jest expectations (https://jestjs.io/docs/en/expect) over the Detox ones?
Could you please tell me how to do it, if it's possible?
I have Jest runner installed

**Comment by noomorph** [comment]
Search detox.init options. exportGlobals false

**Comment by d4vidi** [comment]
@noomorph https://stackoverflow.com/questions/60686639/use-jest-expectations-over-the-detox-custom-ones
