### ISSUE TITLE
Detox configuration binaryPath for custom apk name

### ISSUE THREAD

**Issue by jayshah123** [wix/Detox#1960]
I use following in my `build.gradle` android defaultConfig to give a meaning full name to the apk.

```
        setProperty("archivesBaseName", "my-awesome-app-$versionName($versionCode)-$buildDate")
```
e.g. `my-awesome-app-2.1(12)-16-03-2020 17_53_12-uat-debug.apk`

But the following binary configuration expects a fixed  name for an APK, how can this be handled?

```
      "android.emu.uat.debug": {
        "binaryPath": "android/app/build/outputs/apk/beta/debug/app-uat-debug.apk",
        "build": "cd android && ./gradlew assembleUatDebug assembleUatDebugAndroidTest -DtestBuildType=debug && cd ..",
        "type": "android.emulator",
        "device": {
          "avdName": "Pixel_2_API_27"
        }
      }
```
Any help/suggestions are appreciated.

**Comment by d4vidi** [comment]
@jayshah123 please post on stackoverflow with the detox tag
