### ISSUE TITLE
Using xPath to locate elements

### ISSUE THREAD

**Issue by aamorozov** [wix/detox#197]

**Comment by isnifer** [comment]
@aamorozov what cases you need to use XPath?

**Comment by aamorozov** [comment]
@isnifer Looking into this framework for the second day and haven't seen something that i got used to in appium, hence the question )

**Comment by rotemmiz** [comment]
Take a look in this issue, https://github.com/wix/detox/issues/188, it might answer some of your questions

**Comment by aamorozov** [comment]
@rotemmiz @isnifer 
Thanks guys, I was asking if smth like element(by.xpath()) would work, but it doesn't seem like detox matchers have this method. 
``` 
 TypeError: by.xpath is not a function
```

**Comment by isnifer** [comment]
@aamorozov don't forget - xpath soooo sloooow instead of testIDs. I don't see iterate over testIDs.
In our app we are using detox for iOS tests and Appium for Android (I wrote a wrapper for both frameworks). All tests except tests with webview are using testIDs without problems

**Comment by aamorozov** [comment]
@isnifer Yep, I'm aware of difference between those two in speed of locating element. I am also using appium for android, right now leveraging detox for ios builds. Is it a public project that you're using the wrappers on ?

**Comment by aamorozov** [comment]
@isnifer
Oh and actually to avoid piling up the issues, do you know if there is similar to findElementsBy() method for locating multiple elements, storing them in array and then do whatever you need to do with them ? Haven't found it in the docs

**Comment by hungbm** [comment]
@isnifer 

> All tests except tests with webview are using testIDs without problems

Would you care to elaborate meaning of this? I having problem with check Webview visible.
My Webview is open a PDF file that I store inside application storage, but some how I can not get "pass" the test. 

Specify: detox stuck at `await expect(testIDofWebView).toBeVisible();` and then throw 
`Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; ifreturning a Promise, ensure it resolves.`. It happened with all PDF link (open PDF file, no mater it on the internet or local storage).

However, if I use Webview to open a website (like google.com or facebook) then the test pass as normal. Should this is a bug?

**Comment by isnifer** [comment]
@hungbm can you create a small repo to reproduce it. And we will work together on tests for it.

**Comment by rotemmiz** [comment]
We have no plans of implementing xpath support at the moment.
