### ISSUE TITLE
Record a single video from beginning to the end

### ISSUE THREAD

**Issue by NicolasSmit** [wix/Detox#1981]
Hi,
I'm not sure this is currently possible, but in our workflow we would like to have a second check by someone watching the video recorded during the tests (to check the design / the values etc). 
Recording the videos is perfectly working on iOS with `--record-videos all` but it generates one video for each item of each test. 

Is there a way to generate only one video for the whole series of tests ?

**Comment by LeoNatan** [comment]
Unfortunately not possible. 

@noomorph

**Comment by NicolasSmit** [comment]
Thanks for your reply @LeoNatan 
Just found a way to handle this using bash scripts and `xcrun simctl io booted recordVideo`

**Comment by LeoNatan** [comment]
Yes, if you use one simulator, that will work.

**Comment by noomorph** [comment]
After we go async hooks, I'll consider adding this opportunity, but it is not in short-term plans.

**Comment by noomorph** [comment]
@LeoNatan, actually we might have this issue open as a feature request.
