### ISSUE TITLE
npm install detox@5.4.0 fails on windows 7 even though I have latest nodejs and npm

### ISSUE THREAD

**Issue by sunilkumarc** [wix/detox#199]
C:\Users\sunil\Documents\git\react-native-navigation\example>npm install --save detox@5.4.0

> detox@5.4.0 postinstall C:\Users\sunil\Documents\git\react-native-navigation\example\node_modules\detox
> scripts/postinstall.sh

'scripts' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "detox@5.4.0"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! detox@5.4.0 postinstall: `scripts/postinstall.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the detox@5.4.0 postinstall script 'scripts/postinstall.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the detox package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     scripts/postinstall.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs detox
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls detox
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\sunil\Documents\git\react-native-navigation\example\npm-debug.log

**Comment by rotemmiz** [comment]
Detox only supports iOS currently, hence it only runs on macOS. We are in process of adding support for Android. When we do, it will make more sense of supporting Windows as well.

**Comment by sunilkumarc** [comment]
When is support for windows expected?

**Comment by rotemmiz** [comment]
Detox is being used internally at Wix, and currently being integrated in our build process. This process reveals bugs and missing features that we are addressing as our first priority. 
The second priority is to develop Android support (which are are already half way through I believe). When that is done we can address Windows/Linux support for Detox (sorry I have no estimates for you)

**Comment by sunilkumarc** [comment]
No problem :) That's good to know!

**Comment by cichub** [comment]
Hi
Any update on the windows fix ?

**Comment by rotemmiz** [comment]
Detox does not officially support Windows and we are uncertain if we'll ever put an effort to support it ourselves.
We will, however, happily accept PRs adding Windows support.
