### ISSUE TITLE
Detox test timeout at splashscreen

### ISSUE THREAD

**Issue by jordeguevara** [wix/Detox#1991]
### Description
When I run the detox test command, the simulator will run but get stuck on the splash screen and then it will close the app (in the simulator) while the process(detox test) will just be running until it times out. 

I looked into the issues that might have been the culprits (splash screen library, not running on release) but to no success, so create a new create react-native CLI project and it still had the same issue. 

current workaround: I reverted to the version I used previously 15.1.2 and it is working. However, not sure if this on my end or with the new release (16.0.2).

#### Reproduction

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

1```. yarn add detox -D```
2. added to package.json
 ```
    "detox": {
      "test-runner": "jest",
      "configurations": {
        "ios.release": {
          "binaryPath": "./ios/build/Build/Products/Release-iphonesimulator/AwesomeProject.app",
          "build": "xcodebuild -workspace ios/AwesomeProject.xcworkspace -configuration release -scheme AwesomeProject -sdk iphonesimulator -derivedDataPath ios/build",
          "type": "ios.simulator",
          "name": "iPhone X"
        }
      }
    }
```
3. ```detox build```
4. ```detox test```

```
//FirstTest.spec.js
describe('Example', () => {
  beforeEach(async () => {
    await device.reloadReactNative();
  });

  it('should have welcome screen', async () => {
    await expect(element(by.text('Hello, World'))).toBeVisible();
  });
});

```

```js
//app.js
import React from 'react';
import {SafeAreaView, StyleSheet, View, Text} from 'react-native';

const App: () => React$Node = () => {
  return (
    <>
      <View testID="welcome" style={styles.engine}>
        <Text style={styles.footer}>Hello, World</Text>
      </View>
    </>
  );
};

const styles = StyleSheet.create({
  engine: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  footer: {
    color: 'black',
  },
});

export default App;
``` 

#### Expected behavior
```
detox[81476] INFO:  Example: should have welcome screen
detox[81476] INFO:  Example: should have welcome screen [OK]

 PASS  e2e/firstTest.spec.js (7.442s)
  Example
    ✓ should have welcome screen (187ms)
```
#### Environment (please complete the following information):
 - Detox: 16.0.2
 - React Native: 0.62.1
 - Node: 10.16.3
 - Device :iPhone X
 - Xcode:11.3
 - iOS:
 - macOS: 10.14.6

#### Device and verbose Detox logs
- [ ] I have run my tests using the `--loglevel trace` argument and am providing the verbose log below:

**Comment by LeoNatan** [comment]
Please follow https://github.com/wix/Detox/blob/master/docs/Troubleshooting.Synchronization.md and provide log here.
