### ISSUE TITLE
Android E2E test fails on instrumentation / TimingModule init on react-native 0.62

### ISSUE THREAD

**Issue by msand** [wix/Detox#1992]
**Describe the bug**
Upgrade react-native to 0.62, detox crashes on instrumentation init, fixed by applying https://github.com/wix/Detox/commit/7e4d1d97d158a046d33bfbb17e8e29237cb7c23c

Monkey-fix using patch-package to apply cherry-picked commit from rn62 branch:
https://github.com/msand/react-native-svg-e2e/commit/ef88feb9c9864fa2ea475b73a3906dbfac779e53

**To Reproduce**
Clone, build (test:e2e:build:android or test:e2e:build:android:release), run (test:e2e:android or test:e2e:android:release or screenshots:android or screenshots:android:release)

reproduction: https://github.com/msand/react-native-svg-e2e/commit/0a2d3f2f35f0fd414bf7c773e0b5b4496c3ada09

Steps to reproduce:
1. Upgrade working project with working e2e detox tests to react-native 0.62
2. run android e2e tests
3. detox crashes on init

**Expected behavior**
detox works as in the https://github.com/wix/Detox/compare/rn62 branch

**Device and Verbose Detox Logs**

https://app.bitrise.io/build/e2906010e1ee7fe8#?tab=log

https://travis-ci.org/github/msand/react-native-svg-e2e/jobs/670791236#L3591
- [x] I have tested this issue on the latest Detox release and it still reproduces

```
detox[12843] INFO:  [test.js] configuration="android.emu.release.bitrise" cleanup=true takeScreenshots="all" reportSpecs=true readOnlyEmu=false useCustomLogger=true DETOX_START_TIMESTAMP=1585999050060 node_modules/.bin/jest --config e2e/config.json '--testNamePattern=^((?!:ios:).)*$' --maxWorkers 1 "e2e"
detox[12844] INFO:  [DetoxServer.js] server listening on localhost:50039...
detox[12844] ERROR: [DetoxExportWrapper.js/DETOX_INIT_ERROR] 
 { DetoxRuntimeError: Failed to run application on the device
HINT: Most likely, your main activity has crashed prematurely
Native stacktrace dump: 
    at AttachedAndroidDriver._getInstrumentationCrashError (/Users/vagrant/git/node_modules/detox/src/devices/drivers/AndroidDriver.js:175:12)
    at AttachedAndroidDriver.instrumentationCloseListener (/Users/vagrant/git/node_modules/detox/src/devices/drivers/AndroidDriver.js:142:67)
    at AttachedAndroidDriver._terminateInstrumentation (/Users/vagrant/git/node_modules/detox/src/devices/drivers/AndroidDriver.js:166:12)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'DetoxRuntimeError' }
detox[12844] WARN:  [Client.js/PENDING_REQUESTS] App has not responded to the network requests below:
  (id = -1000) isReady: {}
Unresponded network requests might result in timeout errors in Detox tests.

```

**Environment:**
 - Detox: 16.0.2
 - React Native: 0.62.1
 - Node: 13.12.0
 - Device: Nexus_5X_API_29_x86
 - OS: macOS Catalina 10.15.3
 - Test-runner: Jest+jasmine

**Comment by d4vidi** [comment]
@msand thanks for this, but I nevertheless have to close this is as a dup of #1922. The work on the `rn62` will be merged soon enough!

**Comment by msand** [comment]
Ah great, I tried looking for one but couldn't find, thanks for the dupe link! Mostly thought this might be useful to document for anyone wanting a quick-fix.
