### ISSUE TITLE
Unable to do Parallel testing with Detox and Jest

### ISSUE THREAD

**Issue by gothraven** [wix/Detox#2004]
> package.json
``` json
{
 ...
  "detox": {
    "configurations": {
      "ios.sim.debug": {
        "binaryPath": "ios/build/AppName/Build/Products/Debug-iphonesimulator/AppName.app",
        "build": "xcodebuild -project ios/AppName.xcodeproj -scheme AppName -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build",
        "type": "ios.simulator",
        "device": {
          "type": "iPhone 11"
        }
      }
    },
    "test-runner": "jest --detectOpenHandles --verbose",
    "runner-config": "tests/detox/jest.config.js"
  }
}
```
> tests/detox/jest.config.js
```js
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  setupFilesAfterEnv: ['./init.ts']
};
```
> init.ts

```
import { cleanup, init } from 'detox';
const adapter = require('detox/runners/jest/adapter');

const config = require('../../package.json').detox;

jest.setTimeout(90000);

jasmine.getEnv().addReporter(adapter);

beforeAll(async () => {
  await init(config, { initGlobals: false });
}, 90000);

afterAll(async () => {
  await adapter.afterAll();
  await cleanup();
});
```

And here is the command I use to start tests, after having 4 IOS simulators running and ready

`detox test -l warn -w 4 ./path-to-all-tests`

The issue is that whenever I launch this command I see only one simulator start reacting but not the others.

### Dependencies
MacOS catalina
xed version 11.4
detox: ^16.0.2
jest: ^24.9.0
ts-jest: ^24.1.0

**Comment by gothraven** [comment]
it has been asked many times on Stackover flow and we still have no answers to it
> https://stackoverflow.com/questions/55794833/detox-jest-tests-are-not-running-in-parallel

I don't even know if we're having the same issue

**Comment by d4vidi** [comment]
@gothraven thanks for this. I'll try to follow it up on SO through the link you specified. If you nevertheless feel it unhelpful, post your own question and past the link here. Thanks!

**Comment by gothraven** [comment]
@d4vidi Stack-overflow is so toxic, I'd rather rewrite Detox from the scratch to fix this issue than post a question and get down voted for "duplicate" or whatever !

**Comment by d4vidi** [comment]
I promise to upvote 😄 Anyways if you post this with a ref to the similar question then you should be fine, I believe.

**Comment by gothraven** [comment]
@d4vidi here is the question => https://stackoverflow.com/questions/61204229/unable-to-do-parallel-testing-with-detox-and-jest 😄 

I hope i won't wait for two years to get an answer !
