### ISSUE TITLE
Is there a way to cache some artifacts from Detox build?

### ISSUE THREAD

**Issue by kceb** [wix/Detox#2016]
I run detox tests whenever we merge a PR, however the detox build steps takes 40 minutes+. I'm wondering if there's a way to cache certain build artifacts to make subsequent runs faster?

**Comment by noomorph** [comment]
Leo, it is time to remove this convenience method 'detox build' so that people stop asking non-relevant questions to the project, like we see here.

**Comment by rotemmiz** [comment]
I strongly disagree, even though `detox build` is just a convenience method it is critical in order to manage multiple configurations in a sane way. The fact that these questions pop up from time to time should not act as a reason to remove it.

**Comment by kceb** [comment]
@noomorph I think you should also remove the `I Need Help with Detox
Ask a general how-to question` option from the issues page if you are going to be so dismissive about what is a supposed general how-to question.

**Comment by LeoNatan** [comment]
It’s there on purpose. Usually there is a bot that explains why the “issue” is closed. See here: https://github.com/wix/Detox/issues/1305
