### ISSUE TITLE
Selects the TabBar instead of an element during test.

### ISSUE THREAD

**Issue by henrymoulton** [wix/Detox#2017]
**Describe the bug**

During a test that waits for an elements to appear while scrolling, when it first appears and is tapped on, it actually taps on the touch region of the tab bar (the tab bar is created using React Navigation v4).

**To Reproduce**

- [x] I have tested this issue on the latest Detox release and it still reproduces

Steps to reproduce:
1. Put an element in a scrollview that is tappable underneath a React Navigation Tab Bar.

**Expected behavior**

It should not tap on the tab bar, and instead scroll a little bit down accounting for the touchable region of the tab bar.

**Screenshots**

Video of the failure: https://streamable.com/x721bh

Video showing the Touchable Link that should be tapped that's underneath the Tab Bar: https://streamable.com/refzfh

**Device and Verbose Detox Logs**

[detox_pid_39719.log](https://gist.github.com/henrymoulton/09337128d05492e1a69f0eb8c3ca304b)

[process.log](https://gist.github.com/henrymoulton/fdff32b558efe3369ee943596958798a)

**Environment (please complete the following information):**
 - Detox: "detox": "16.2.0",
 - React Native: "react-native": "0.61.5",
 - Node: v10.16.0
 - Device: Pixel_2_XL_API_27
 - OS: OS X Mojave 10.14.6
 - Test-runner (select one):  "test-runner": "jest"

Additional Info:

```
"react-navigation": "^4.3.7",
"react-navigation-stack": "^2.2.3",
"react-navigation-tabs": "^2.8.2",
```

Let me know if there's anything I can do to produce a better bug report, and thanks for all your work on Detox.

**Comment by LeoNatan** [comment]
On iOS, we have API to provide the normalized start position of scroll, so you can evade elements such as the tab bar.

https://github.com/wix/Detox/blob/master/docs/APIRef.ActionsOnElement.md#scrollpixels-direction-startpositionxnan-startpositionynan

I'm not sure, but I think it's not supported on Android. @d4vidi ?

**Comment by henrymoulton** [comment]
@LeoNatan I don't think this would help if the content was further down in a `ScrollView`.

**Comment by henrymoulton** [comment]
Thanks for your response, what do you think @d4vidi?

**Comment by d4vidi** [comment]
1. Thanks for properly submitting issue, with all the necessary details 😄 
2. The API @LeoNatan suggested is also supported on Android. However, I'm not sure it would help in your case. As a workaround on Android, you can add something like:
```
if (device.getPlatform() == 'android') {
   scrollABitFurtherDown()
}
```
right after the waitFor()/scroll() loop.

I suppose that the proper solution would be to provide a Detox API that would wait for the element to be _fully_ visible, which is something we've discussed in the past in other issues. Is that correct?

**Comment by LeoNatan** [comment]
Perhaps I misunderstood, but it sounded to me like the scrolling gesture started on top of the tab bar, rather than the scroll view. This is why I suggested this API.

**Comment by henrymoulton** [comment]
> I suppose that the proper solution would be to provide a Detox API that would wait for the element to be fully visible, which is something we've discussed in the past in other issues. Is that correct?

Or I guess visible enough to tap on it :D with the knowledge of other elements hitSlop?

**Comment by d4vidi** [comment]
@henrymoulton you are right - most probably, Detox considers the element properly visible by "seeing through" the tab bar.

@LeoNatan the scrolling seems to work, it just stops rescrolling early, assuming the element is visible enough when in fact it is not.

**Comment by d4vidi** [comment]
Seems that this is tightly related to #1185

**Comment by d4vidi** [comment]
@henrymoulton on 2nd thought, this might the RN bug we've been trying to fix for ages: https://github.com/facebook/react-native/issues/23870
