### ISSUE TITLE
Can Detox deal with http calls (as we do with Cypress in web development)?

### ISSUE THREAD

**Issue by euZebe** [wix/Detox#2020]
Coming from web development and being quite a fan of Cypress.io, I'd like to know how to deal with the following use cases with Detox:
I'd like to spy http requests sent by my app, and possibly get some information, for instance an authentication token so that I can initialize datasets before running tests.
I could understand that one says "Detox acts as a real user, then doesn't have access to http requests". 

Another great thing allowed by Cypress.io is that we can log in through an HTTP call, which prevents from having a single point of failure (the authentication screen) for a lot of tests. Is there a way to do so with Detox ?

**Comment by LeoNatan** [comment]
Not really possible. If you use React Native's JS network APIs, you can perhaps mock those to do what you'd like.
