### ISSUE TITLE
toExist() not working correctly on Android

### ISSUE THREAD

**Issue by j320** [wix/Detox#2024]
**Describe the bug**

When having a FlatList with a few elements horizontally that have to be scrolled through in order to see each of them, using the `toExist()` expectation for one of the images/elements invisible in the list doesn't work on Android. The same with attempting to scroll to the element using the `whileElement().scroll()`, it returns the `element not visible` exception.

**To Reproduce**

Steps to reproduce:
1.  Have an app with a FlatList containing several elements horizontally
2. Put individual IDs on each of them and use the `toExist()` function on Android for one of the invisible elements
3. Use the `whileElement().scroll()` function to attempt to scroll to the last element in the list
4. Run the same tests on iOS and see them passing

**Expected behavior**
Tests pass and Detox scrolls on the second second test on Android

**Environment:**
 - Detox: 16.3.0
 - React Native: 0.62.2
 - Node: 14.0.0
 - Device: iPhone 11
 - Xcode: 11.4.1
 - iOS: 13.4.1

**Comment by LeoNatan** [comment]
It makes sense the element doesn’t exist. Flat list uses virtualization, and views are created on demand. While/scroll is a different matter, and should scroll the list until the view exists/visible.

**Comment by j320** [comment]
On iOS it successfully expects all the elements in the list to exist, not Android.

And yes, the issue is the same when using the while/scroll. Perhaps it's expecting it to exist before scrolling?

**Comment by LeoNatan** [comment]
Maybe virtualization is somehow disabled on iOS.

**Comment by j320** [comment]
In that case the issue could be with while/scroll

**Comment by j320** [comment]
I can confirm that while / scroll does work as intended in iOS but doesn't on Android as it requires the element to exist

**Comment by LeoNatan** [comment]
@d4vidi @rotemmiz

**Comment by d4vidi** [comment]
@j320 we would very much appreciate it if you try to use Android Studio's [layout inspector](https://developer.android.com/studio/debug/layout-inspector) in order to see whether in the use case you described the element _does_ indeed exist or not,

**Comment by j320** [comment]
But while/scroll should work regardless if the element exists or not, it should scroll until the element is found.

**Comment by d4vidi** [comment]
@j320 I agree regarding while/scroll, but still trying to understand whether the bug is associated with a free-standing `toExist()` or not. Regardless of the result, thanks for reporting this!

**Comment by j320** [comment]
I confirm that Android Studio layout inspector doesn't display the non-visible elements in the Flat list, while Xcode does for iOS.

**Comment by d4vidi** [comment]
Great - so to be concise, there seems to be an issue with while/scroll on Android. I would appreciate a better specification of the problem, however, as in essence, this is a use case that is commonly tested by Detox' own test suite.

**Comment by LeoNatan** [comment]
We don’t have FlatList in the Detox suite.

**Comment by d4vidi** [comment]
Right, thanks for refreshing my memory - it's just a set of linearly placed items.

**Comment by LeoNatan** [comment]
I think the problem is as follows:

FlatList doesn’t create all of its items (potentially 1000s)
Detox is supposed to scroll the list until the item appears
On Android, Detox fails to scroll because it doesn’t find the element in the hierarchy

The fix should be for Detox to attempt the scroll action even if the item doesn’t exist.

**Comment by j320** [comment]
Has this been looked at?

**Comment by jonathanmos** [comment]
This doesn't reproduce for me. @j320 Can you please check and reopen this issue if it's still relevant? 

I've tested with the following layout/test case both where listBackroundImage-5 is/is not the last element, and the test passes:

   <FlatList
                testID="listBackground"
                horizontal
                keyExtractor={image => image.name}
                data={newImages}
                renderItem={({ item, index }) => {
                  return (
                    <Image
                      style={{ width: 450, height: 350 }}
                      source={item.imagePath}
                      testID={`listBackgroundImage-${index}`}
                    />
                  );
                }}
              />

  it('Attempt to scroll to element', async () => {
    await waitFor(element(by.id('listBackgroundImage-5')))
      .toExist()
      .whileElement(by.id('listBackground'))
      .scroll(50, 'right');
