### ISSUE TITLE
Disable synchronization before launchApp

### ISSUE THREAD

**Issue by 0x0ece** [wix/Detox#2032]
Is it possible to disable synchronization before/during launchApp (with newInstance: true)? Ideally I'd like the:
```await device.launchApp({ newInstance: true, url });
```
to resolve immediately.

I've inherited an app that does weird things at launch, so I'd like to bypass synchronization at the beginning and only reenable it afterwards.

I tried something like this:
```
await device.disableSynchronization();
await device.launchApp({ newInstance: true, url });
await waitFor(element(by.id('root'))).toBeVisible().withTimeout(10000);
await device.enableSynchronization();
```
but from the docs I read that synchronization is always re-enabled for new instances.

Is there a way to force synchronization to be off so that device.launchApp can actually resolve?

**Comment by LeoNatan** [comment]
I don't think we have anything like that, but if a network request is causing issues, you can pass a URL blacklist which will disable synchronization for that network request.

**Comment by 0x0ece** [comment]
I blacklisted all network calls, but still have sync issues. Would this be something of interest/should I work on a PR?

**Comment by LeoNatan** [comment]
At this point, we are actively working on removing Earl Grey, so our synchronization mechanism will change very soon. We can add it then.

**Comment by 0x0ece** [comment]
Great to know, thank you!
