### ISSUE TITLE
Support of Reanimated library

### ISSUE THREAD

**Issue by iamolegga** [wix/Detox#2041]
Hi, first of all thanks for your work.

**Is your feature request related to a problem? Please describe.**
When app has animations based on [reanimated library](https://github.com/software-mansion/react-native-reanimated), I have to add extra `sleep()` calls in tests.

**Describe the solution you'd like**
So, [there is some info in docs](https://github.com/wix/Detox/blob/master/docs/Troubleshooting.Synchronization.md) that says:

> There's special support for React Native animations with the Animated library.

And it would be great if detox could handle this animations internally, because `reanimated` is very popular library.

**Describe alternatives you've considered**
🤷‍♂️

**Additional context**
If contributors approve this feature, I could invest my time in this

**Comment by LeoNatan** [comment]
Normally, we don’t have the capacity to support third party frameworks directly. After a quick look, it seems to me like animations are powered by a CADisplayLink, which will be supported in a future version of Detox, once we switch away from Earl Grey. Stay tuned.

**Comment by iamolegga** [comment]
Ok, thanks!
