### ISSUE TITLE
Log retry attempts when running on parallel workers

### ISSUE THREAD

**Issue by viktorijasujetaite** [wix/Detox#2051]
**Is your feature request related to a problem? Please describe.**
When using jest.retryTimes(), retry attempts are not logged when tests are running in parallel. It's difficult to understand if test failed out of first attempt or after n-retries. And if it passes, it's not clear if it was flaky before that.

**Describe the solution you'd like**
Log test retry attempts when tests are running in parallel (on multiple workers)

**Comment by d4vidi** [comment]
@viktorijasujetaite https://github.com/wix/Detox/blob/master/docs/APIRef.DetoxCLI.md#test -
Specs reporting is disabled entirely by default when multiple workers are run, in order to try to prevent a messy log. You can enable them nonetheless using the `--jest-report-specs` argument to detox CLI.
