### ISSUE TITLE
Add support for pinch(scale, speed, angle) in iOS invoke2

### ISSUE THREAD

**Issue by LeoNatan** [wix/Detox#2053]
~by.type()~ and ~scrollTo()~ are already documented.

For pinch, I will add the documentation once the API is live and tested. For now, the following API is proposed:

```
pinch(scale, speed, angle)

scale = (0.0, ∞], not nan
speed = "fast"/"slow", default fast
angle = not nan, default 0
```

**Comment by rotemmiz** [comment]
[scrollTo(edge) already exists](https://github.com/wix/Detox/blob/DetoxNext/detox/src/ios/expectTwo.js#L135), doesn't it work for you?

**Comment by LeoNatan** [comment]
It’s already in?? Uff then why did I think it’s no there?

**Comment by LeoNatan** [comment]
@rotemmiz Please make sure to check input, otherwise the native will crash. `(0.0, ∞]` for scale, angle not `nan`.

**Comment by rotemmiz** [comment]
Sure, already done

**Comment by LeoNatan** [comment]
👑
