### ISSUE TITLE
Testing elements with the same testID/AccessibilityLabel ?

### ISSUE THREAD

**Issue by aamorozov** [wix/Detox#206]
In case when there are 30+ items, adding unique testID or accessibilityLabel becomes a bit of a tedious process. Any suggestions on how to handle those ?
I know you can index items, but still writing this for lots of items is a bit more time-consuming that it should be. 
Mostly wondering about iteration options, similar to what Appium has with findElementsBy() method.

**Comment by isnifer** [comment]
At tipsi we are using indexes or ids in tetIDs without problems

**Comment by aamorozov** [comment]
Yep, indexes and IDs work just fine for me as well. I'm curious if there is a way to receive an array of objects from elements with the same identifier. Will try to add something here

**Comment by aamorozov** [comment]
If any of those  https://github.com/google/EarlGrey/blob/master/EarlGrey/Matcher/GREYMatchers.m#L521,
https://github.com/google/EarlGrey/blob/master/EarlGrey/Matcher/GREYAllOf.m,
https://github.com/google/EarlGrey/blob/master/EarlGrey/Matcher/GREYAnyOf.m,
https://github.com/google/EarlGrey/blob/master/Tests/UnitTests/Sources/GREYElementFinderTest.m#L80
can be called from detox context that should work, will try on a weekend

**Comment by aamorozov** [comment]
@LeoNatan 
Do you think something like https://github.com/google/EarlGrey/blob/master/Demo/EarlGreyExample/EarlGreyExampleTests/EarlGreyExampleTests.m#L75 could work from detox context as `element` command for example?

**Comment by rawqing** [comment]
There is no better way to do this than using `atIndex(...)`

**Comment by LeoNatan** [comment]
Closing this issue. Speaking from experience internally, there is no magic. You need to add IDs to your views, or risk flakiness by using `by.Label()`/`atIndex()`.
