### ISSUE TITLE
Ensure Android invoke accepts new iOS API, even if invoke2 is not yet implemented

### ISSUE THREAD

**Issue by LeoNatan** [wix/Detox#2069]
Missing features can be implemented as shims that forward calls to old invoke1 API.

Current missing features that I can think of:
```
.not().toBeVisible()
```
```
.tap(point)
```

**Comment by d4vidi** [comment]
My advice here is to introduce `.not` rather than a `.not()` as the API for this. There's something weird about `not` being a function call. Also, it'd be more aligned with common JS assertion API's.

**Comment by LeoNatan** [comment]
I also like not, but @rotemmiz preferred not().

**Comment by rotemmiz** [comment]
I can try to change this, lets see
