### ISSUE TITLE
Unable to click continue in iOS pop (ASWebAuthenticationSession)

### ISSUE THREAD

**Issue by reachbharathan** [wix/Detox#2072]
### Description
Unable to click continue for [iOS auth pop implemented using](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession)

- [x] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

1. Implement a iOS ASWebAuthenticationSession login
2. click the login
3. A pop iOS native pop will be thrown
4. Detox is unable to click the "continue button"

#### Expected behavior
Detox should be able to click the `continue` button in the pop,
In the broser detox should be able to set the login credentials

#### Screenshots
Pop up screen
![iOS_pop_up](https://user-images.githubusercontent.com/10195912/82296613-07c27880-99e4-11ea-94fc-edb2e7330f0d.png)

#### Environment (please complete the following information):
 - Detox: 16.5
 - React Native: 16.8.6
 - Node: 13.6
 - Device: tried in both Iphone x and Iphone 8
 - Xcode: 11
 - iOS: 13
 - macOS: catalina

### Logs
there is not error logs ,
the detox fails on trying to interact with the next element

**Comment by reachbharathan** [comment]
I tried the solution mentioned in the below stackoverflow issue,
but it doesn't work

**Comment by LeoNatan** [comment]
This has been asked multiple times. We are not able to interact with this alert, as it is an alert presented from a different process. Please mock your API to not display it.
