### ISSUE TITLE
Support artifact collection of test retries (`jest.retryTimes(x)`)

### ISSUE THREAD

**Issue by rotemmiz** [wix/Detox#2073]
When running a test with `jest.retryTimes(x)`, the artifact manager will create a folder for the first retry, but will fail recording the next retries (if they happen).

Example:
```
detox[4447] WARN:  [Artifact.js/MOVE_FILE_EXISTS] cannot overwrite: "~/temp/buildTmp/d4efa026-0524-4cf9-a6da-a5c3fba4c3bc.detox.png" => "artifacts/ios.sim.release.2020-05-17 09-18-53Z/✗ testName/testDone.png"
```

I suggest we add the retry number to the folder name, 
retry no 1: `test name`
retry no 2: `test name - retry 2`
retry no 2: `test name - retry 3`

**Comment by d4vidi** [comment]
@viktorijasujetaite and I have taken a 2nd look on some tests where retry is applied and we noticed the opposite - namely, that only the artifacts from last retry prevail.

**Comment by rotemmiz** [comment]
Could be different between platforms, anyway, the dir names should solve either issue we have there.

**Comment by viktorijasujetaite** [comment]
> @viktorijasujetaite and I have taken a 2nd look on some tests where retry is applied and we noticed the opposite - namely, that only the artifacts from last retry prevail.

I would actually think that artifacts of [Retry #1] are recorded, because for latter retries (#2 & #3) we see "cannot overwrite" warning.

**Comment by d4vidi** [comment]
@viktorijasujetaite again, this is probably iOS-specific, and different on Android. In any case, solving this would solve it for both platforms
