### ISSUE TITLE
Support getAttributes on Android

### ISSUE THREAD

**Issue by plaa** [wix/Detox#2083]
**Is your feature request related to a problem? Please describe.**
In #445 a way to retrieve attributes (e.g. element text) was requested. The issue was closed by introducing [`getAttributes`](https://github.com/wix/Detox/blob/DetoxNext/docs/APIRef.ActionsOnElement.md#getAttributes--ios-only) which currently is iOS-only.

This issue is to track support for Android.

**Describe the solution you'd like**
Ability to fetch element attributes / text on Android.

**Describe alternatives you've considered**
Hacks described in #445 including [detox-getprops](https://www.npmjs.com/package/detox-getprops) package.

**Comment by RikSchefferOberon** [comment]
is there any news on this?

**Comment by d4vidi** [comment]
Sorry, no. We don't have the capacity I'm afraid.

**Comment by DenysMoro** [comment]
It will be very nice to have it for Android as well

**Comment by MuckT** [comment]
Getting `TypeError: element(...).getAttributes is not a function` when running `await element(by.id('<elementId>')).getAttributes()` on Android in 18.14.0. Which differs from [the documentation](https://github.com/wix/Detox/blob/master/docs/APIRef.ActionsOnElement.md#methods). Looking at the PR that closed this issue, it doesn't look like the types were updated to support this feature on Android.

**Comment by d4vidi** [comment]
Indeed, it is missing from the types list.
Please apply a `// @ts-ignore` for now.

**Comment by sandeep-bastola** [comment]
In Detox 18.14.0 this issue is seen in android : Test Failed: com.google.android.material.slider.Slider , when used the function getAttributes(). Anyone faced similar issue ?

**Comment by d4vidi** [comment]
@sandeep-bastola could you please submit an android bug with all the details?
https://github.com/wix/Detox/issues/new/choose

**Comment by sandeep-bastola** [comment]
https://github.com/wix/Detox/issues/2846

**Comment by plaa** [comment]
[The documentation](https://github.com/wix/Detox/blob/DetoxNext/docs/APIRef.ActionsOnElement.md#getAttributes--ios-only) still says "iOS only".  Could the documentation be updated?  Thanks!

**Comment by d4vidi** [comment]
@plaa your link is associated with an old branch. [This](https://github.com/wix/Detox/blob/master/docs/APIRef.ActionsOnElement.md#getAttributes) is the updated documentation.
