### ISSUE TITLE
Detox should fail a tap() if turned into a long-tap

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#2092]
**Is your feature request related to a problem? Please describe.**
In certain environments, it happens at times that a tap() action isn't handled fast enough (UI thread choking) and hence is eventually rendered unhandled as the tap gets registered as a long tap.

**Describe the solution you'd like**
While obviously an undesired behavior at app-level -- and should be addressed as such, it would be very helpful if Detox could very explicitly notify of the event as it is otherwise extremely difficult to detect.

**Describe alternatives you've considered**
Needless to say, it is better to come up with a different strategy for injecting events such that this cannot happen. Not to say that it is evidently possible, as this type of bugs is inherent even in Espresso itself.

**Additional context**
Happened in Wix' internal engine project on CI machines where RN's `Button` component was used and Hermes is applied.

**Comment by LeoNatan** [comment]
How does this even happen? Isn’t there a time stamp for when the touch began and when it ended? Or is that a bug in RN?

**Comment by d4vidi** [comment]
Looks like implementing this requires a change bigger than fits into common sense. I'll revisit this in the form of finding a better implementation altogether, which would - as a byproduct, make it easier to measure this time.
