### ISSUE TITLE
Print view hierarchy in loglevel verbose and trace

### ISSUE THREAD

**Issue by LeoNatan** [wix/Detox#2108]
We've moved the view hierarchy out of the normal error sequence. Now, it's provided as its own `viewHierarchy` when reporting arguments. JS should read this, and print it when loglevel is set to verbose and trace.

**Comment by LeoNatan** [comment]
@rotemmiz Can we close this? Is it implemented on Android?

**Comment by rotemmiz** [comment]
Implemented in 17.0.0
