### ISSUE TITLE
TypeError: device.launchApp is not a function

### ISSUE THREAD

**Issue by aamorozov** [wix/detox#211]
I was referencing example in detox test suit:
https://github.com/wix/detox/blob/master/detox/test/e2e/l-permissions.js
`device.launchApp({permissions: {calendar: 'NO'}});`

It throws me an error, although the app should not be launched within init as I've set launchApp to false:

`await detox.init(config, {launchApp: false});`

Am I doing anything wrong here ?

**Comment by rotemmiz** [comment]
What version of Detox do you have ? this is a feature added in Detox 5.5.0

**Comment by aamorozov** [comment]
@rotemmiz My bad, I had 5.4. Thank you!
