### ISSUE TITLE
demo-react-native does not work as specified

### ISSUE THREAD

**Issue by tapashmajumder** [wix/Detox#2113]
### Description

`demo-react-native` project does not compile. Most likely this is due to changes in latest version of react native.

- [x] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction

Follow the steps in your demo project
https://github.com/wix/Detox/tree/master/examples/demo-react-native

#### Expected behavior
No warnings. Project should build

#### Environment (please complete the following information):
 - Detox: 16.7.2
 - React Native: 0.61
 - Node: 14.0
 - Xcode: 11.4
 - iOS: 13
 - macOS:  10.15.5

**Comment by LeoNatan** [comment]
We don't maintain the iOS demo project. Feel free to submit a pull request with fixes. Thanks
