### ISSUE TITLE
Edge swipe Android doesnt work but iOS works

### ISSUE THREAD

**Issue by skheirandish** [wix/Detox#2119]
**Describe the bug**
When I try to swipe right on the `<SafeAreaView>`

```
<SafeAreaView 
      testID="identity__welcome__screen">
      <Text 
        testID="identity__welcome__message">
          Placeholder Welcome Screen
      </Text>

      <Button
        testID="identity__welcome__button">
      </Button>
</SafeAreaView>
```

With following test:

```
describe('Login e2e', () => {
    beforeEach(async () => {
      await device.reloadReactNative();
    });
  
    it('Should open menu drawer', async () => {
      await element(by.id('identity__welcome__button')).swipe('right', 'slow', 0.05)
      await element(by.text('Login')).tap();
    });
  });
```

The swipe action works for iOS but doesnt work for Android

**To Reproduce**

- [ x] I have tested this issue on the latest Detox release and it still reproduces

**Expected behavior**
Android should edge swipe right as well

**Screenshots**
![Jun-10-2020 16-26-29](https://user-images.githubusercontent.com/66039460/84328609-4658d800-ab37-11ea-94d6-8fa8ad538a4c.gif)

**Environment (please complete the following information):**
 - Detox: 16.7.2
 - React Native: 0.62.2
 - Node: 12.18.0
 - Device: Pixel_3a_API_29_x86
 - OS: iPhone 11
 - Test-runner (select one): Jest+jasmine

**Comment by d4vidi** [comment]
@skheirandish unlike with the `scroll` API, the `precentage` argument to `swipe()` isn't supported on Android, it seems. We would appreciate a PR the would introduce an equivalent support for  `precentage` to `swipe()`, as in `scroll()`.
