### ISSUE TITLE
Importing device into test case

### ISSUE THREAD

**Issue by aamorozov** [wix/detox#212]
I need to avoid no-undefined from eslint - we have strict policy regarding this 
``` 
import device from 'detox'; 
```
throwing an error

**Comment by DanielMSchmidt** [comment]
You don't need to import it, it is globally available in the tests. Just remove the import and everything should work just fine

**Comment by isnifer** [comment]
@aamorozov in your `.eslitrc`
```js
{
  // ...
  "globals": {
    "device": false,
    "expect": false,
    "waitFor": false,
    "element": false,
    "by": false,
    "describe": false,
    "it": false,
    "before": false,
  }
}
```

**Comment by aamorozov** [comment]
@isnifer Thank you, that's what I needed
