### ISSUE TITLE
Detox 16.8.0: Hangs when executing tests

### ISSUE THREAD

**Issue by j320** [wix/Detox#2129]
### Description
Upgrading to Detox 16.8.0 and running  `detox test` launches the app, immediately goes back to home and hangs, with no extra logs when running with  `--loglevel trace`

#### Reproduction

1. Upgrade to detox 16.8.0 
2. Run `detox build`
3. Run `detox test`

#### Expected behavior
Tests are executed normally

#### Environment (please complete the following information):
 - Detox: 16.8.0
 - React Native: 0.62.2

**Comment by noomorph** [comment]
@j320 , does that reproduce on Android?

**Comment by LeoNatan** [comment]
What Xcode is used?

**Comment by j320** [comment]
> @j320 , does that reproduce on Android?

I tried several times but it doesn't show any issue

> What Xcode is used?

Latest: 11.5

**Comment by LeoNatan** [comment]
Are you using Swift in your application? What Swift language version?

**Comment by LeoNatan** [comment]
Also, do you have Detox Instruments installed?

**Comment by j320** [comment]
> Are you using Swift in your application? What Swift language version?

I'm not using Swift in my application.

> Also, do you have Detox Instruments installed?

I don't have Detox Instruments installed.

**Comment by LeoNatan** [comment]
OK, thanks
I think I see something

**Comment by noomorph** [comment]
@j320, `detox@16.8.0` has been unpublished to mitigate similar issues on our users' side.

In case if you just have started a new project with Detox, there is a release candidate (`16.8.1-rc1`) available as a hotfix. @LeoNatan is working on a long-term solution.

**Comment by LeoNatan** [comment]
Please try with 16.8.1.

**Comment by j320** [comment]
I confirm that the issue doesn't reproduce in 16.8.1 and didn't break Android either.

**Comment by LeoNatan** [comment]
Great!
