### ISSUE TITLE
Safari callback

### ISSUE THREAD

**Issue by ignaciosantise** [wix/detox#213]
My app has a login with Google, and it opens safari to do that. When i run detox, it logins successfully but it doesn't go back to my application as expected. Instead of that, it remains in safari with the caption "Website name"

![screen shot 2017-07-27 at 12 37 21 pm](https://user-images.githubusercontent.com/25931366/28679815-bb45883c-72ca-11e7-91ca-1287b42d9c4c.png)

Any idea of what's happening?

#### Additional info

* react-native: 0.45.0
* iOS: 10.3

**Comment by rotemmiz** [comment]
Does it work as expected when you run it manually ? or are you obligated to press the `done` button ?
If the behaviour is different when running the Detox test, please provide the test code.

**Comment by isnifer** [comment]
@rotemmiz `SFSafariViewController` is not supported by EarlGrey now. 
@ignaciosantise How did you log in via detox?

**Comment by ignaciosantise** [comment]
@rotemmiz yes, if i run it manually it works as expected.

@isnifer i'm not logging in via detox, i log in with safari before running the test, so it remembers the account when i run detox

**Comment by rotemmiz** [comment]
Please post your test code here.

**Comment by isnifer** [comment]
@ignaciosantise cheater, haha

**Comment by ignaciosantise** [comment]
@isnifer  i could't find another solution 👼 

@rotemmiz here is the test code!

```
describe('Example', () => {
  beforeEach(async () => {
    await device.reloadReactNative();
  });

  it('Grant notification permission', async () => {
    await device.launchApp({permissions: {notifications: 'YES'}});
  });

  it('should have a login screen', async () => {
    await expect(element(by.id('loginButton'))).toBeVisible();
  });

  it('Tap login button tap', async () => {
    await element(by.id('loginButton')).tap();
  });

  it('should see the dashboard list', async () => {
    await waitFor(element(by.label('Enviados'))).toExist().withTimeout(8000);
  });
})
```

**Comment by rotemmiz** [comment]
Not sure what you're doing there, I can't make any sense from this suite.
Seems like these are 4 different tests (which probably need to be merged into 1).
In the 3rd test loginButton is tapped, but then you reload react native before the 4th test. So this tap doesn't hold for the 4th test. Is that what you intend to do ?

**Comment by ignaciosantise** [comment]
Ohh, you are right! i have to merge the tests. Clearly my mistake! Thanks for that!

**Comment by rotemmiz** [comment]
anyway, take a look at manual synchronization tests API https://github.com/wix/detox/blob/master/docs/APIRef.waitFor.md
You have to use expect after waitFor. waitFor will never fail a test.

But please, try not to use waitFor, Detox should wait until all the actions complete before continuing to the next action.

**Comment by ignaciosantise** [comment]
@rotemmiz  @isnifer Thanks for your help! 🎉
