### ISSUE TITLE
Detox repeating logs on circleci

### ISSUE THREAD

**Issue by alexbrazier** [wix/Detox#2133]
On CircleCI our output looks something like this:

```


 RUNS  ...



 RUNS  ...



 RUNS  ...



 RUNS  ...



 RUNS  ...



 RUNS  ...



 RUNS  ...





 RUNS  ...

PASS e2e/login.spec.ts (57.966s)
```

But with lots more `RUNS ...`. Is this expected, or is there something we are doing wrong?

It makes it hard to see what is passing and failing.

**Comment by noomorph** [comment]
Are you sure it's not Jest's issue there?

**Comment by alexbrazier** [comment]
It might be. I'm going to try updating and see if that fixes it
