### ISSUE TITLE
The first step in the Android instructions says to do everything in the iphone instructions.

### ISSUE THREAD

**Issue by twocs** [wix/Detox#2140]
**Describe the bug**
The first step in the instructions for Android gives a link to the Apple instructions and suggests to do those steps first.

**Expected behavior**
When you view the Android instructions, it doesn't tell you to "run through the [Apple instructions]".

**Screenshots**
https://github.com/wix/Detox/blob/master/docs/Introduction.Android.md

Setup ⚙️
1. Run through the initial Getting Started Guide
Getting Started (this is https://github.com/wix/Detox/blob/master/docs/Introduction.GettingStarted.md and it is exclusively instructions for Apple devices)

**Comment by d4vidi** [comment]
@twocs thanks for this report, which is highly acceptable. We've recently discuss on rephrasing the documentation -- unifying the platforms' instructions where possible, and uniformly split where applicable. We will address this issue very soon, I hope.
