### ISSUE TITLE
React/RCTEventDispatcher.h' file not found for building ios configuration ( debug & release)

### ISSUE THREAD

**Issue by TammyTorres** [wix/Detox#2152]
### Description
Using the example --> Detox/example/rdemo-react-native latest version 
Xcode version used 10.3
Simulator iPhone X ( 12.4) 

#### Reproduction

1.clone the project and move to the example mentioned 
2. run --> npm install
3. run --> detox build --configuration ios.sim.release

#### Expected behavior
Build for ios is successful

#### Environment (please complete the following information):
 - Detox:16.9.1
 - React Native:0.62.2
 - Node:v10.16.0
 - Device: iPhone X 
 - Xcode:10.3
 - iOS:12.4
 - macOS: 10.15.4 

### Logs
detox build --configuration ios.sim.release
detox[38584] INFO:  [build.js] export RCT_NO_LAUNCH_PACKAGER=true && xcodebuild -project ios/example.xcodeproj -UseNewBuildSystem=NO -scheme example -configuration Release -sdk iphonesimulator -derivedDataPath ios/build -quiet
=== BUILD TARGET example OF PROJECT example WITH CONFIGURATION Release ===
/Users/tamara/Downloads/Detox/examples/demo-react-native/ios/example/AppDelegate.m:11:9: fatal error: 
      'React/RCTRootView.h' file not found
#import <React/RCTRootView.h>
        ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
/Users/tamara/Downloads/Detox/examples/demo-react-native/ios/example/AppDelegate.m:11:9: fatal error: 
      'React/RCTRootView.h' file not found
#import <React/RCTRootView.h>
        ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
** BUILD FAILED **

detox[38584] ERROR: [cli.js] Error: Command failed: export RCT_NO_LAUNCH_PACKAGER=true && xcodebuild -project ios/example.xcodeproj -UseNewBuildSystem=NO -scheme example -configuration Release -sdk iphonesimulator -derivedDataPath ios/build -quiet

**Comment by LeoNatan** [comment]
The iOS demo projects are not maintained. Please submit PRs if you wish to compile them with latest RN. Thanks
