### ISSUE TITLE
waitFor always passes (false positive)

### ISSUE THREAD

**Issue by doronpr** [wix/detox#216]
The following will not fail the test:
`await waitFor(element(by.id('some-thing-that-will-never-exist'))).toExist().withTimeout(10);`
Tried it in detox's e2e test suite.

(Note if you remove the waitFor, the test will fail)

**Comment by rotemmiz** [comment]
This behavior is documented [here](https://github.com/wix/detox/blob/master/docs/APIRef.waitFor.md). We can't estimate when it will be fixed. please use the currently suggested method (`expect` after `waitFor`)

**Comment by rotemmiz** [comment]
#138

**Comment by doronpr** [comment]
@rotemmiz see https://github.com/wix/detox/tree/fix-waitFor
