### ISSUE TITLE
Deleted doc file (APIRef.waitFor.md)

### ISSUE THREAD

**Issue by CHarnel** [wix/Detox#2175]
A doc file (docs/APIRef.waitFor.md) was deleted [here](https://github.com/wix/Detox/commit/35d7f496b0a634b67d7c5a7e0c040374aef7d7c3#diff-e3e2a9bfd88566b05001b02a3f51d286) and now the link `Manual Synchronization` is broken.

**Comment by LeoNatan** [comment]
The document is no longer necessary. The information was moved to action and expectation docs.

**Comment by CHarnel** [comment]
Then you probably should remove the broken `Manual Synchronization` link from `https://github.com/wix/Detox/blob/master/docs/README.md`

**Comment by LeoNatan** [comment]
I’ll fix it. Thanks

**Comment by gmaclennan** [comment]
Hi @LeoNatan  I spent a while trying to find the documentation for `waitFor`. There is a mention of it in the [action doc](https://github.com/wix/Detox/blob/master/docs/APIRef.ActionsOnElement.md#whileelementelement) and a in the [expectation doc](https://github.com/wix/Detox/blob/master/docs/APIRef.Expect.md#withtimeouttimeout) but there is no documentation about what it does, how it works, or why it is needed. It is not in the table of contents of either doc, so it is not easy to find. It would be really useful for new users to document this method separately. It's not clear with the current docs which methods are available on `waitFor()`, I am assuming the same as `expect()`?

**Comment by LeoNatan** [comment]
The problem was the documentation was not good at all. The API itself is not well thought out. It should be expect().withTimeout(). But yes, anything expects accepts, waitfor will work.

**Comment by LeoNatan** [comment]
I’ll try to see how to update the documentation to be more clear.

**Comment by gmaclennan** [comment]
Yes `expect().withTimeout()` would be so much nicer! Anyway, thanks for taking a look, and for confirming that it works like expects. The info in the original doc, that `waitFor()` does not `expect()` (that you need to repeat the `expect()` below it), was helpful, because that is not intuitive.

**Comment by LeoNatan** [comment]
I've opened a new issue #2190 for this. Hopefully we can look at it soon.
