### ISSUE TITLE
Add Hierarchy dump (text/proprietary format) as a test artifact

### ISSUE THREAD

**Issue by rotemmiz** [wix/Detox#2181]
Detox 17 introduced split log for failures, where the failure reason is always printed, but the hierarchy is now only printed in verbose or trace logging modes.
A better solution would be to collect these hierarchy dumps as artifacts for failing tests.

An even better solution will be to actually capture the hierarchy of Xcode's View hierarchy format (https://github.com/LeoNatan/LNViewHierarchyDumper).
And on Android, to research capturing hierarchy in Layout Inspector's format.

**Comment by LeoNatan** [comment]
I need JS support. I will send a URL on failure and need the JS to read the file and take it. 

We can also offer an API, `captureViewHierarchy(name)`, which will produce the same result on demand. Need JS support for this.
