### ISSUE TITLE
Improve debug-sync print timings

### ISSUE THREAD

**Issue by rotemmiz** [wix/Detox#2182]
Debug-sync only works on iOS and only for invokes. If an app starts and never goes idle, there is no way to find about it automatically.
* we can manually add `'detoxPrintBusyIdleResources': 'YES'` to launch args but this is not an automatic mechanism, but rather a debugging mechanism.

- Implement output to log on app launch, not only during slow Invokes (can be done regardless of DetoxNext Phase 2)
- Adding debug-sync by default (only during/after DetoxNext Phase 2, since the current mechanism is not crash free).

**Comment by LeoNatan** [comment]
This already exists by adding the environment variable and looking at console. Otherwise, the debug sync should work even on launch. Perhaps the bug is on JS side, where it waits for isReady, and doesn’t send debugSync until that. Those two shouldn’t be related. If a process exists, it can be asked about debug sync.

**Comment by rotemmiz** [comment]
I dropped that from the initial description because its not automatic. Updated the first comment

**Comment by LeoNatan** [comment]
Probably good idea to wait, but can be developed independently and then wait. I’m not sure it’s a good idea to enable logs by default. It prints a lot and has a performance cost. Asking from time to time is a good idea in general, and that requires JS to be able to ask the question regardless of isReady.

**Comment by LeoNatan** [comment]
@rotemmiz Is this implemented by your PR?

**Comment by rotemmiz** [comment]
Yes, first phase is done, but it's still not on by default, waiting for DetoxSync

**Comment by LeoNatan** [comment]
Because of the pretty print crashes? Yeah, probably a good idea.
