### ISSUE TITLE
Add mode to _currentScheme

### ISSUE THREAD

**Issue by EtgarSH** [wix/detox#22]
In order to determine if we are in debug or release mode, we need to add a key to the `_currentScheme` in `simulator.js`.

Something like:

``` son
{
    app: 'ios/build/Build/Products/Debug-iphonesimulator/example.app',
    mode: 'debug',
    device: 'iPhone 6s, iOS 9.3'
}
```

**Comment by LeoNatan** [comment]
@rotemmiz I think this can be closed as part of CLI tools.

**Comment by rotemmiz** [comment]
I am not sure there's a use case for this extra param. Can anyone elaborate?

**Comment by rotemmiz** [comment]
new configurations api should nail this requirement as well.
