### ISSUE TITLE
Better documentation on `expect`

### ISSUE THREAD

**Issue by hanayashiki** [wix/Detox#2201]
**Is your feature request related to a problem? Please describe.**
I think more specification on `expect` might be given in documentation. I was hoping to find a way to specify there are two conditions both satisfiable after a specified action (for example, when user logins with unknown username/password, we assert one of login success or login failure to be there), but didn't find any straightforward documentation on it. I was not sure how `expect` works and its possible side effect outside the documentation.

So I decided to looked into the code, and found that `expect` finally leads to this function 

```
 async sendAction(action) {
    const response = await this.ws.send(action, action.messageId);
    const parsedResponse = JSON.parse(response);
    return await action.handle(parsedResponse);
}
```

and `action.handle` throws an `Error` if the expectation fails. The process doesn't have any side effects. So I find the following snippet to be plausible to implement the demand described above:

```
await AtLeastOneDoesNotThrow([
  expect(element(by.id('login-success'))).toBeVisible(),
  expect(element(by.id('login-failed'))).toBeVisible(),
]);
```

**Describe the solution you'd like**
The documentation should tell us about how `expect` works. It should state `expect` works by only raising error when it fails.

**Describe alternatives you've considered**

Add a feature for `or` connective within `expect`s

**Additional context**

**Comment by rotemmiz** [comment]
I think this usecase is not good enough, a test should have a defined input and one expected output. If there are two expected outputs you should have two tests.

That said, you are welcome to suggest a change in documentation via PR.

**Comment by hanayashiki** [comment]
May be this is not a good illustration. But I think the 'or' relation is
quite common and the test may not control every part of the condition so
that there can be different cases both accepted as 'pass'

**Comment by LeoNatan** [comment]
Complex expectations are now possible using `getAttributes()`, where you can obtain the attributes of several elements, and perform complex checks (such as visibility, hitability, values, etc.).
