### ISSUE TITLE
Using @react-native-community/masked-view will prevent Detox to run tests

### ISSUE THREAD

**Issue by jarvisluong** [wix/Detox#2206]
**Describe the bug**
There is some incompatibility with the package `@react-native-community/masked-view` which prevented Detox test actions and matcher from working properly

**To Reproduce**

- [x ] I have tested this issue on the latest Detox release and it still reproduces

Minimal repo to reproduce: https://github.com/jarvisluong/detox-maskedview-android

If we replace MaskedView with a normal View, then the test will pass.

**Expected behavior**
- The test should run as normal

**Device and Verbose Detox Logs**
The logs do not show anything useful I guess...

**Environment (please complete the following information):**
 - Detox: 17.1.1
 - React Native: 0.62.2
 - Node: 10.15.3
 - Device: Android
 - OS: API Level 27
 - Test-runner (select one): `jest-circus`

**Comment by d4vidi** [comment]
@jarvisluong does this happen even if masked-view isn't effectively used in the app's UI?

**Comment by jarvisluong** [comment]
> @jarvisluong does this happen even if masked-view isn't effectively used in the app's UI?

@d4vidi this only happens when masked view is mounted in the component hierarchy

**Comment by d4vidi** [comment]
I'm a bit confused because in the demo app there `android:usesCleartextTraffic="true"` applied only to a custom debug AndroidManifest file, yet Detox runs tests in release mode. The fatality of the problem suggests something's coming from that direction: instead of faliing, the tests do not run at all.

**Comment by jarvisluong** [comment]
I'm testing against API level 27 so the clear text issue shouldn't be the case here. The demo app is a stripped down test suite from our own app. In our actual tests, other test cases run fine, except the one which opens a screen with masked view.

**Comment by emoller** [comment]
Just ran into this one as well. @jarvisluong did you manage to find any temporary workaround? I see you're a few weeks ahead of me :)

**Comment by jarvisluong** [comment]
> Just ran into this one as well. @jarvisluong did you manage to find any temporary workaround? I see you're a few weeks ahead of me :)

Basically I'm having a dummy implementation for masked view and during the test phase, the original MaskedView is replaced with the dummy implementation 😄

**Comment by noomorph** [comment]
@jonathanmos @d4vidi  per reports on Discord of RNN, this issue is still valid. 
![image](https://user-images.githubusercontent.com/1962469/146960731-df0836db-44e5-4bf0-ab8a-56e6cdec90d3.png)
