### ISSUE TITLE
Need information on supporting multiple device instances

### ISSUE THREAD

**Issue by hsavit1** [wix/Detox#2215]
related issues: https://github.com/wix/detox/issues/393 , https://github.com/wix/Detox/pull/1144 , https://gist.github.com/noomorph/06506567a25b6098c33c37349c2fb926

I would like to use Detox in a way where 2 device instances are communicating each other. I would like each device to follow a specific test spec file, instead of a shared test spec file. How can I pass the test spec file to each device?

**Comment by andreialecu** [comment]
I see this was posted on https://stackoverflow.com/questions/62922308/supporting-multiple-detox-device-instances

There is still no information on how to do this, even though it seems to have been implemented.

I have tried:

```js
  const detoxes = await Promise.all([
    detox.init(config, { initGlobals: false }),
    detox.init(config, { initGlobals: false }),
  ]);
```

But no matter if I use `detoxes[0]` or `detoxes[1]`, the same emulator gets controlled. @noomorph would you please shed some light on this?

**Comment by andreialecu** [comment]
I think this issue should be reopened as a documentation request. There is no documentation on multiple device support, neither in the PR at https://github.com/wix/Detox/pull/1144 or here where it was announced: https://github.com/wix/detox/issues/393#issuecomment-524430838 (also cc @manuquentin)

**Comment by andreialecu** [comment]
As an update, it seems that `detoxes[0].device.launchApp()` and `detoxes[1].device.launchApp()` does interact with each separate emulator to launch the app, but `detoxes[0 or 1].element(...).replaceText(...)` always controls the same emulator.
