### ISSUE TITLE
assembleAndroidTest doesn’t use packagingOptions

### ISSUE THREAD

**Issue by androidparth90** [wix/Detox#2217]
Hi ,

In case of react native projects that use external dependencies we face errors related as follows "More than one file was found with OS independent path 'lib/x86/libc++_shared.so'. 

This is because the asssembleAndroidTest doesn't use the packagingOptions provided.
Link to this issue is here: https://discuss.gradle.org/t/assembleandroidtest-doesnt-use-packagingoptions/31673

Can someone please suggest a solution or enhancement ?

**Comment by d4vidi** [comment]
@androidparth90 Would you mind posting the question & answer on stackoverflow?
