### ISSUE TITLE
Docs need to be updated for custom environment 

### ISSUE THREAD

**Issue by codetheweb** [wix/Detox#2221]
[This link](https://github.com/wix/Detox/blob/master/docs/Guide.Jest.md#L112) in the docs is broken / obsolete. I had to go digging around in issues and PRs before I finally found [this](https://github.com/wix/Detox/pull/2009#issuecomment-648971528) which solved my issue.

**Comment by LeoNatan** [comment]
Feel free to submit a PR with necessary fixes. Thanks
