### ISSUE TITLE
How to press / tap on an `ActionSheetIOS` item

### ISSUE THREAD

**Issue by a-eid** [wix/Detox#2232]
How to press / tap on an `ActionSheetIOS` item, 
the only way I can think of it to get the item by text, but that does not work ...

Note that I'm able to assert that the item is visible by text, but tapping it produces an error 

`Test Failed: Failed expectation: TOBEVISIBLE WITH MATCHER(identifier: == “singInScreen.screen”), Another view “<RCTView: 0x7fc96cd65520>” is visible at window point “{"x":207,"y":448.71497584541066}”
    TIP: To print view hierarchy on failed actions/matches, use loglevel verbose and above.` 

![Screen Shot 2020-07-28 at 2 40 59 AM](https://user-images.githubusercontent.com/19273413/88605989-c6051c80-d07b-11ea-8cff-0e5b777d1b74.png)

**Comment by a-eid** [comment]
this could be a bug with `detox`

**Comment by LeoNatan** [comment]
It doesn't look like a bug in Detox. Your visibility assertion is failing, meaning your item is not visible.

**Comment by a-eid** [comment]
@LeoNatan the visibility assertion is passing 

getting element by label && then selecting the 0th index solves the issue for me
 
`await getByLabel("Sign Out")().atIndex(0).tap()`

**Comment by LeoNatan** [comment]
"Sign Out" is the label in the action sheet?

Just be careful with using `atIndex()`, as it might break if your interface changes, or more items appear with the same label. Sadly, UIAlertController (implementation of action sheet in iOS) does not expose its buttons and does not allow setting an identifier on them.

**Comment by a-eid** [comment]
will do, I'm new to the whole testing thing 😕 .
thank you @LeoNatan

**Comment by LeoNatan** [comment]
Cheers!

**Comment by Bijiabo** [comment]
> "Sign Out" is the label in the action sheet?
> 
> Just be careful with using `atIndex()`, as it might break if your interface changes, or more items appear with the same label. Sadly, UIAlertController (implementation of action sheet in iOS) does not expose its buttons and does not allow setting an identifier on them.

I ran into the same problem recently. My solution is to wrap the title of the option with `\u2002` when setting the action sheet options. For example:

```
"Sign Out" -> "\u2002Sign Out\u2002"
```

User will not notice the space character, but for some views that contains several "Sign out" text, it's useful :)
