### ISSUE TITLE
detox doesn't play well with reanimated 1 especially on android.

### ISSUE THREAD

**Issue by a-eid** [wix/Detox#2240]
testing hangs there till it times out whenever I use `reanimated` styling. 

**To Reproduce**

- [x] I have tested this issue on the latest Detox release and it still reproduces

Steps to reproduce:
- use `ReAnimated.Text` and provide some sort of animation with `ReAnimated.interpolate` for example.
- run tests on android & ios.

Versions: 

- "detox": "^17.2.1",
- "react-native-gesture-handler": "^1.7.0",
- "react-native-reanimated": "^1.10.1",
- "react-native": "0.62.2",
- "react": "16.11.0",

**Expected behavior**
the tests should run as normal.

**Comment by d4vidi** [comment]
@a-eid please reopen the bug with all of the required assets - detox logs, devices log, etc.
Is this a problem on both platforms?

**Comment by a-eid** [comment]
@d4vidi it's not as persistent on IOS but on android it always fails.

**Comment by a-eid** [comment]
@d4vidi I was re-reading your comment to open a new issue, 
yeah it's an issue on both platforms but different issues.
