### ISSUE TITLE
Running on emulator with -no-window

### ISSUE THREAD

**Issue by emoller** [wix/Detox#2243]
Trying to run detox in CI on a headless machine which installs android emulator with -no-window and then tests that check expect().toBeVisible() fails with:
```
    Test Failed: 'at least 75 percent of the view's area is displayed to the user.' doesn't match the selected view.
    Expected: at least 75 percent of the view's area is displayed to the user.
         Got: null
```
Reproduces just as well locally with -no-window

**To Reproduce**

[X] I have tested this issue on the latest Detox release and it still reproduces

Steps to reproduce:
1. Install an android emulator and start it with -no-window
```
sdkmanager --verbose --channel=0 emulator
sdkmanager --verbose "system-images;android-29;google_apis;x86"
avdmanager --verbose create avd --force --name Pixel_3_API_29 --device pixel --package "system-images;android-29;google_apis;x86" --tag google_apis --abi x86 --sdcard 1024M
emulator @Pixel_3_API_29 -verbose -show-kernel -no-audio -no-window -no-boot-anim -netdelay none -no-snapshot -wipe-data -gpu swiftshader_indirect -camera-back none -camera-front none
```
2. Run any test with expect().toBeVisible()

**Comment by d4vidi** [comment]
@emoller thanks for this submission. This doesn't appear to be a Detox issue; please post-back a link to Stackoverflow and we'll try to support you there.

**Comment by Jeevan-Kishore** [comment]
@emoller Did you happen to find a resolution?

**Comment by ThilekSilvadorai-TomTom** [comment]
@emoller having same issue. Did you find a solution ?

**Comment by emoller** [comment]
@ThilekSilvadorai-TomTom we ended up with a stack of self hosted mac-minis running our automation. In the end it was the most straight forward and most easily debuggable solution. Not ideal in any way, but workable.
