### ISSUE TITLE
Touching the button while scrolling issue / or scrolling is executing but the screen not actually scrolled

### ISSUE THREAD

**Issue by heuism** [wix/Detox#2254]
Hi guys, I have been using Detox for 2 years now and I have been staying at version 14 for a long time and they have been okay. But as we are thinking of testing on newer OSes and devices we think we might need to update the detox testing version as well. And so far the speed of testing has been great.

**However**, I ran into this situation constantly where the screen supposed to scroll but it is either not scroll or the scroll animation will also trigger the button pressing.

As you can see in the gif below the screen suppose to keep scrolling but it hung here and there and also the selection supposed to be "AFL" but after the whole animation it changed into "Martial Art". Which was not what we wanted to test and this affected the whole test case.

![Aug-05-2020 11-23-22](https://user-images.githubusercontent.com/8481265/89361233-1deff300-d70e-11ea-9e25-ce16e704a023.gif)

Thanks in advance.

**Comment by d4vidi** [comment]
Dup of #2255
