### ISSUE TITLE
Scrolling issue (not scroll or touch button while scrolling)

### ISSUE THREAD

**Issue by heuism** [wix/Detox#2255]
### Description
Hi guys, I have been using Detox for 2 years now and I have been staying at version 14 for a long time and they have been okay. But as we are thinking of testing on newer OSes and devices we think we might need to update the detox testing version as well. And so far the speed of testing has been great. 

**However**, I ran into this situation constantly where the screen supposed to scroll but it is either not scroll or the scroll animation will also trigger the button pressing.  

- [x] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction
Just any scrollview with a lot of buttons and selections on the scrolling touch area.

#### Expected behavior
As you can see in the gif below the screen suppose to keep scrolling but it hung here and there and also the selection supposed to be "AFL" but after the whole animation it changed into "Martial Art". Which was not what we wanted to test and this affected the whole test case.

#### Screenshots
![Aug-05-2020 11-23-22](https://user-images.githubusercontent.com/8481265/89361233-1deff300-d70e-11ea-9e25-ce16e704a023.gif) 

#### Environment (please complete the following information):
 - Detox: 17.3.4
 - React Native: 0.61.2
 - Node: v13.7.0
 - Device: iPhone 11 (simulator)
 - Xcode: 11.3 (11C29)
 - iOS: 13.3
 - macOS: Mojave 10.14.6 (18G6020)

**Comment by LeoNatan** [comment]
Try adding a start point to your scroll action, so it starts a bit above the bottom. See if that helps.

**Comment by heuism** [comment]
> Try adding a start point to your scroll action, so it starts a bit above the bottom. See if that helps.

Hi, @LeoNatan thanks for responding. Forgive me if I miss the information but I can't find how to 'add the starting point' as you suggested. Is there document about this or a workaround? Thanks
