### ISSUE TITLE
Can't type text when TextInput invisible

### ISSUE THREAD

**Issue by haocse** [wix/Detox#2256]
Hi all, I can't use typeText when input is invisible, height = 0 and width = 0. The value is displayed in another view. Is there any options for this case. Thanks.

**Comment by LeoNatan** [comment]
I don’t see how this is a good UX. How is a user supposed to tap on a 0x0 text field to tap on?
You are most likely doing something wrong.

**Comment by LeoNatan** [comment]
If we find a legit use case, maybe we can ease a bit the restriction. What error are you seeing?
