### ISSUE TITLE
Expectation/matcher for the app being in background?

### ISSUE THREAD

**Issue by kirakik** [wix/Detox#226]
#### Description
It would be nice to have a matcher/expect statement for the app being in background. For example, if I want to check that pressing on a button sends the user to the settings, I would be able to do

```js
  it('Should send the user to the settings', async () => {
    await element(by.id('settingsButton')).tap();
    await expect(element(by.id('CurrentScreen'))).toBeNotVisible();
  });
```

**Comment by DanielMSchmidt** [comment]
@kirakik is this still relevant for you or can we close the issue?

**Comment by kirakik** [comment]
No longer relevant, I’ll close this!
