### ISSUE TITLE
Mocking not working

### ISSUE THREAD

**Issue by robto09** [wix/Detox#2264]
Hellow! I am trying to mock one component in my RN project. I am currently implementing e2e testing but I have experimenting some issues.
In my scenario I have some redux actions I need to override with the actions.e2e.js. The Problem is that looks are not overridden . 

I am using react-native version 0.61.5 with typescript.

react-native version is 0.61.5.

Expected behavior
Detox uses mocked files wherever e2e.js files are present along .js

Environment (please complete the following information):

Detox: 12.1.1
React Native: 0.61.5
Node: 14.5.0
Device: ios X simulator
Xcode: 11.6
iOS: X
macOS: Catalina

My config

```
const { sourceExts } = require('metro-config/src/defaults/defaults');


module.exports = {
  resolver: {
    get sourceExts() {
      const exts = process.env.RN_SRC_EXT
        ? process.env.RN_SRC_EXT.split(',').concat(sourceExts)
        : sourceExts;
      return exts;
    },
  },
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false,
      },
    }),
  },
};
```

**Comment by d4vidi** [comment]
@robto09 while appears to be a real issue with your set up, please post this on Stackoverflow as it is not a Detox bug.
