### ISSUE TITLE
How can I use relative paths when mocking a file from react-native-image-picker in Detox?

### ISSUE THREAD

**Issue by TaylorMichaelHall** [wix/Detox#2268]
I am able to mock a picked image using a full path, but using the relative path does not work when emulating my app in the iOS simulator.

I believe that I need to resolve the path after building but I'm not sure how this can be done.

This is what is in my ImagePicker.e2e.js file:

`ImagePicker.launchImageLibrary = function showImagePicker(options, callback) {
  if (typeof options === 'function') {
    callback = options;
  }
  callback({
    success: true,
    origURL: 'www.test.com',
    path: '/Users/MyUserName/Documents/GitHub/MyRepoName/e2e/media/test.jpg', // This works
    type: 'image/jpeg',
    fileName: 'test.jpg',
    fileSize: 4000,
  });
};`

If I set the path to '../../e2e/media/test.jpg' it does not find the image file. This is the correct relative path to the image file in my repo.
This is found in my Detox build configuration: "build": "xcodebuild -workspace ios/ProjectName.xcworkspace -scheme ProjectName -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build"

Is the derivedDataPath used to resolve the relative path file?

**Comment by kneza23** [comment]
I have the same problem. We can easily mock it with base64, but not sure how to generate a image file path for mocking purpose without using another external dependencies.

**Comment by d4vidi** [comment]
@kneza23 please try going over this guide: https://medium.com/geekculture/how-to-mock-react-native-image-picker-using-detox-9f7ced41b67f

**Comment by kneza23** [comment]
@d4vidi i read that and in the tutorial they are using base64 image for mocking purposes. Im trying to mock a image for upload with formData as a multipart/form-data that has path. 

I just can't find a way to do this. First of all Android emulator does not have any stock images. But i am trying to somehow reference my images from assets folder with Image.resolveAssetSource - that works in debug, but not in release.

**Comment by ouoru** [comment]
@kneza23 did you end up finding a workaround for this?
