### ISSUE TITLE
Uninstall detox completely from MacOS

### ISSUE THREAD

**Issue by cdesch** [wix/Detox#2270]
I want to completely uninstall Detox from my Mac (`10.14.6 (18G5033)`)

I have uninstalled the global `detox-cli` with `npm uninstall -g detox-cli`

There is still a directory here `~/Library/Detox/*` with a bunch of `detox` images. Can these be removed manually? or is there an uninstall script or other directories that need to be removed?

**Comment by noomorph** [comment]
I think this is a valid question. We should add it to FAQ.

**Comment by LeoNatan** [comment]
```
rm -fr ~/Library/Detox/
```

**Comment by cdesch** [comment]
Thanks. That covers the initial directory, but is there any other directories that need to be removed?

**Comment by LeoNatan** [comment]
I don't think so. If you removed the global CLI tool and the library folder, I think you're covered.

**Comment by noomorph** [comment]
@LeoNatan, please don't close this question. I'll be back with a more comprehensive list of places. Sorry, these days a bit busy with organizing birthday party, but on Monday or Tuesday I'll take a look into this

**Comment by LeoNatan** [comment]
@noomorph Please add a document, guiding how to uninstall.

**Comment by noomorph** [comment]
So, today is Tuesday, I can finally look into this. Stay tuned.

**Comment by LeoNatan** [comment]
Any news?

**Comment by noomorph** [comment]
https://github.com/wix/Detox/blob/master/docs/Guide.Uninstalling.md
