### ISSUE TITLE
Using replaceText shows keyboard

### ISSUE THREAD

**Issue by petestewartcx** [wix/Detox#2272]
### Description
Using replaceText on a text input still displays software keyboard on v17.3.6

- [Y] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

1. Write a test using replaceText for a text input
2. Run test while viewing in Simulator

#### Expected behavior
Text input to be filled with text without the keyboard being displayed

#### Environment (please complete the following information):
 - Detox: 17.3.6
 - React Native: 0.62.0
 - Node: 10.15.3
 - Device: iPhone 8
 - Xcode: Lastest
 - iOS: 13
 - macOS: 10.5.6

**Comment by LeoNatan** [comment]
Why is this your expected behavior? It's not to me.
Replacing text goes through the same iOS typing facilities, including making the typed-into view first responder first, which automatically brings the keyboard. A reminder that your users will always use the keyboard to input text. If your app is unable to handle the keyboard, you should fix your app. `replaceText()` is there mostly for performance reasons, because we do not offer a way to control the cursor and selection of text fields/views.

**Comment by petestewartcx** [comment]
> Why is this your expected behavior? It's not to me.
> Replacing text goes through the same iOS typing facilities, including making the typed-into view first responder first, which automatically brings the keyboard. A reminder that your users will always use the keyboard to input text. If your app is unable to handle the keyboard, you should fix your app. `replaceText()` is there mostly for performance reasons, because we do not offer a way to control the cursor and selection of text fields/views.

It's an expected behaviour as this is how it operates in v16 - if I upgrade to v17 all my tests break due to the Keyboard being shown and the subsequent button tap isn't triggered.

**Comment by LeoNatan** [comment]
Detox 17 implements all actions internally, rather than rely on EarlGrey.
How is your user supposed to dismiss the keyboard to tap the button?

**Comment by petestewartcx** [comment]
> Detox 17 implements all actions internally, rather than rely on EarlGrey.
> How is your user supposed to dismiss the keyboard to tap the button?

Fair point, I guess I need to rewrite my tests. Is there a function to dismiss the keyboard?

**Comment by LeoNatan** [comment]
> Fair point, I guess I need to rewrite my tests. Is there a function to dismiss the keyboard?
We explicitly do not provide this on iOS. Your test should perform the same action the user will perform to dismiss it, e.g. scrolling, pressing "Done" or "return" in the keyboard, or tap a button in the UI.

**Comment by isilher** [comment]
I agree on the philosophy, but I think this 'fix' could be communicated more clearly. It took me a long time to find out what was breaking my CI because the local e2e specs were passing (my simulator was apparently suppressing the onscreen keyboard).

**Comment by LeoNatan** [comment]
I’m not sure what communication is required. `replaceText()` is already a hack of sorts, and you need to provide a way for your users to be able to dismiss the keyboard. If you ask me, you should only use `typeText()` and then dismiss the keyboard just like the user would.

**Comment by isilher** [comment]
I completely agree and I am implementing that right now ;-) 

The only thing I'm saying is that since I did not know I was doing it wrong, the change in default behaviour was very hard to debug, especially in the middle of a lot of co-dependant XCode 12 issues. I would suggest something like:

> Breaking change: `replaceText()` now summons the onscreen keyboard as was always the intention. This may break your tests if you used the method as a hack of sorts and did not provide steps to dismiss the keyboard.

**Comment by LeoNatan** [comment]
Are you sure the keyboard wasn’t showing before? Either way, as a native developer, this wouldn’t occur to me to write. We have a migration guide, and there were statements of change when Detox 17, but this wasn’t one of them. There were so many changes to Detox 17, I don’t think it’s realistic to expect every small change in behavior to be documented (and this does look like a slight change to me). We switched from Earl Grey actions to internal ones, and that has introduced many changes that we aren’t probably aware of. Good news is that another such major change on iOS will probably not happen again when it comes to matching and actions.

**Comment by isilher** [comment]
> Are you sure the keyboard wasn’t showing before?

Positive: I eventually noticed some of the failing spec screenshots had a keyboard on them, when previous versions didn't.

> There were so many changes to Detox 17, I don’t think it’s realistic to expect every small change in behaviour to be documented (and this does look like a slight change to me).

Fair enough! 👍 My only intention was to try to help others who might face this issue. 

> Good news is that another such major change on iOS will probably not happen again when it comes to matching and actions.

Good news indeed 😃

Thanks for your quick responses!

**Comment by LeoNatan** [comment]
I will add some words on the behavior on iOS for typeText, replaceText and clearText.

**Comment by kg-currenxie** [comment]
Borrowing this thread a bit :)

![Kapture 2020-12-10 at 17 57 00](https://user-images.githubusercontent.com/48229166/101756735-4b600980-3b11-11eb-8552-1b72866aa61b.gif)

I'm having the same behavior. Then I managed to find a way to dismiss the keyboard:

```
// fill inputs
// ...
await element(by.label('Done')).atIndex(0).tap()
await element(by.text('Log in')).tap()
```

But as you can see, somehow I guess the next tap happens to early while the keyboard is still animating.

Any suggestions?

PS. It works fine if I use `typeText()` instead of `replaceText()` 🤷‍♂️
