### ISSUE TITLE
`detox test` doesn't use exact binaryPath configuration setting, changes it to something nonexistent

### ISSUE THREAD

**Issue by lukewlms** [wix/Detox#2274]
**Describe the bug**
My `binaryPath` setting  for android.emu.debug in `.detoxrc.json` is:

`"binaryPath": "android/app/build/outputs/apk/debug/app-x86_64-debug.apk",`

However, running `detox test --configuration android.emu.debug` gives an error message with a totally different path:

`detox[52593] ERROR: Error: 'projects/android/app/build/outputs/androidTest/x86_64/debug/app-x86_64-debug-androidTest.apk' could not be found, did you run './gradlew assembleAndroidTest'?`

I can't find any references to this androidTest directory.  How do I get Detox to point to an apk that actually exists, in the `debug` directory?

**To Reproduce**

- [x] I have tested this issue on the latest Detox release and it still reproduces

My repro is just first-time setup and running `detox test`.  I've successfully run the `detox build` command for the same config.  So, it appears that the `build` command is not building at the same path that the `test` command is looking for.

(Skipping logs as they have personal information and do not appear relevant, can sanitize them and paste if need be.)

**Environment (please complete the following information):**
 - Detox: "detox": "^17.3.5",
 - React Native: "react-native": "^0.63.2",
 - Node: "node": "^14.7.0",
 - Device: Pixel_API_28_AOSP
 - OS: Mac Catalina
 - Test-runner: `jest-circus`

### Update
Detox appears to be referencing the binaryPath but attempting to transform it in a way that's broken (at least on my machine).

When I change binaryPath to this:

> android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk

I get a different error message than above, as if Detox is attempting to use part of my binaryPath but mangling the rest.  Note the "androidTest-androidTest" and "androidTest/debug/androidTest/" repetition, which is not present in my `binaryPath`.

> detox[54397] ERROR: Error: 'android/app/build/outputs/apk/androidTest/debug/androidTest/app-debug-androidTest-androidTest.apk' could not be found, did you run './gradlew assembleAndroidTest'?

The build is succeeding and writing to the directory above (`apk/androidTest/debug/app-debug-androidTest.apk`) but again, `test` is using a different path than `build` and can't find the file.  I'm using this command to ensure that the same config is definitely used for both:

`detox build -c android.emu.debug && detox test -c android.emu.debug`

### Update 2
If I use a truly nonexistent path then Detox does not appear to modify it.  I'm at a loss to explain why it modifies the path if the apk DOES exist and then does not find it.

`"binaryPath": "does/not/exist.apk",`

> detox[54805] ERROR: Error: app binary not found at 'does/not/exist.apk', did you build it?

Truly does not exist, and is not mangled or modified.

**Comment by noomorph** [comment]
If you have a custom **testBinaryPath**, then make sure to specify it as well. Are you sure there is a problem with automatic test binary path resolution for the majority of Detox users?

**Comment by lukewlms** [comment]
This does appear to be a common issue:

https://stackoverflow.com/questions/53984667/detox-app-could-not-be-found-did-you-run-gradlew-assembleandroidtest/63414420#63414420
https://stackoverflow.com/questions/53984667/detox-app-could-not-be-found-did-you-run-gradlew-assembleandroidtest/63414420#63414420

I found that Detox is mutating the path because it tries to transform it in getTestApkPath().  I don't have any custom settings, but setting `testBinaryPath` does work, thanks for the suggestion.

I would suggest adding a step to the documentation for users to try using testBinaryPath as an override.  Intuitively it seems Detox would be asking for a binaryPath to the binary you want Detox to use, but that's not what binaryPath is for - Detox tries to compute the path to its APK using binaryPath as a base.  I (and others) would think that binaryPath should be the path to Detox's binary.

Created PR here: https://github.com/wix/Detox/pull/2277

**Comment by raldred** [comment]
This just tripped me up. 
It does not correctly automate the paths for the test binary when you have multiple arch apks

**Comment by realeric23** [comment]
> This just tripped me up. It does not correctly automate the paths for the test binary when you have multiple arch apks
> 
> ![image](https://user-images.githubusercontent.com/37096/94715889-f734ee00-0345-11eb-8a0c-0474c478c5e8.png)

How did you solve it?

**Comment by Usama11a** [comment]
> @realeric23 use `testBinaryPath` alongside `binaryPath`, in order to specify the path of your _test_ APK (provided that's you've built it properly, as explained in our getting-start guides...)

@d4vidi I placed my apk file in the same folder where the .detoxrc file is preset and my binary path is as follow:
/myapk.apk
But when I run "detox test -c android" it show me an error i.e  DetoxRuntimeError: Failed to find the app binary at:
C:\Users\uyounas\AndroidStudioProjects\android\app\build\outputs\apk\debug\app-debug.apk

Please guide me where is the problem.
Thanks

**Comment by d4vidi** [comment]
@Usama11a please let us know if things do not work out for you after reiterating the Android config guide

**Comment by Usama11a** [comment]
@d4vidi I have follow every step from the documentation but still facing the following 3 issues:
![detox_window_android_errors](https://user-images.githubusercontent.com/85039104/150312772-a94777a2-081e-462a-9c6a-ea59c2f25a17.PNG)

1. DetoxRuntimeError: Failed to run application on the device
2. Detox can't seem to connect to the test app(s)!
3. Command failed: mocha --config e2e/.mocharc.json --configuration android --grep :ios: --invert --loglevel trace --use-custom-logger true e2e|

I also follow the steps mentioned in [this](https://wix.github.io/Detox/docs/troubleshooting/running-tests) link but still facing the errors.
