### ISSUE TITLE
 DetoxConfigError: Failed to find a configuration named "android.emu.release" in Detox config at path:

### ISSUE THREAD

**Issue by vksgautam1** [wix/Detox#2275]
this is how i am integrating detox in my project.
https://github.com/wix/Detox/blob/master/docs/Introduction.Android.md

 "detox build -c android.emu.release" on running this command i am getting this error;
`DetoxConfigError: Failed to find a configuration named "android.emu.release" in Detox config at path:
detox[10608] ERROR: [cli.js] E:\Vivek\OfficetraxMobile\.detoxrc.json
detox[10608] ERROR: [cli.js]
detox[10608] ERROR: [cli.js] HINT: Below are the configurations Detox was able to find:
detox[10608] ERROR: [cli.js] * ios
detox[10608] ERROR: [cli.js] * android`

 environment
nodejs -v12.9.1
npm-6.10.2
React-native -0.63.2
Detox-17.3.6

**Comment by vksgautam1** [comment]
this is a bug report , i chooses a wrong label here

**Comment by d4vidi** [comment]
As the Detox log says -- you've named your configurations `ios` and `android`, not `android.emu.release`. Hence, when running `detox`, use - for example, `detox --configuration android`.

**Comment by vksgautam1** [comment]
' "detox": {
    "configurations": {
      "android.emu.debug": {
        "binaryPath": "android/app/build/outputs/apk/debug/app-debug.apk",
        "build": "cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && cd ..",
        "type": "android.emulator",
        "name": "Nexus_5X_API_28_x86"
      },
      "android.emu.release": {
        "binaryPath": "android/app/build/outputs/apk/release/app-release.apk",
        "build": "cd android && ./gradlew assembleRelease assembleAndroidTest -DtestBuildType=release && cd ..",
        "type": "android.emulator",
        "name": "Nexus_5X_API_28_x86"
      }
    },'
this is how i am doing

**Comment by noomorph** [comment]
But this looks like content of your package.json, not `.detoxrc.json` ? Otherwise, why would you use `"detox": {` outer object? 🤷‍♂️
