### ISSUE TITLE
Generated GREYAction JS wrapper uses unsupported variable types

### ISSUE THREAD

**Issue by rotemmiz** [wix/detox#228]
The newly added GREYActions generated code relies on invocation features we don't support natively.

For instance [here](https://github.com/wix/detox/blob/e607fb368379f16af65530c271374fae016b8088/detox/src/ios/earlgreyapi/GREYActions.js#L147) we use GREYDirection (which is just an ENUM). On the original implementation we us NSInteger to invoke the method.

#### Description
Here's the invocation action that is sent when using the old method:
`{"type":"invoke","params":{"target":{"type":"Invocation","value":{"target":{"type":"EarlGrey","value":"instance"},"method":"detox_selectElementWithMatcher:","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"GREYMatchers"},"method":"detoxMatcherForScrollChildOfMatcher:","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"GREYMatchers"},"method":"matcherForAccessibilityID:","args":["ScrollView161"]}}]}}]}},"method":"performAction:","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"GREYActions"},"method":"actionForScrollInDirection:amount:","args":[{"type":"NSInteger","value":4},{"type":"CGFloat","value":100}]}}]},"messageId":5}`

Here's the invocation action that is sent with the new generated code
`{"type":"invoke","params":{"target":{"type":"Invocation","value":{"target":{"type":"EarlGrey","value":"instance"},"method":"detox_selectElementWithMatcher:","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"GREYMatchers"},"method":"detoxMatcherForScrollChildOfMatcher:","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"GREYMatchers"},"method":"matcherForAccessibilityID:","args":["ScrollView161"]}}]}}]}},"method":"performAction:","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"GREYActions"},"method":"actionForScrollInDirection:amount:","args":[{"type":"GREYDirection","value":4},{"type":"CGFloat","value":100}]}}]},"messageId":5}`

The difference is `{"type":"NSInteger","value":4}` vs `{"type":"GREYDirection","value":4}`

#### Steps to Reproduce
in [ios/expect.js](https://github.com/wix/detox/blob/e607fb368379f16af65530c271374fae016b8088/detox/src/ios/expect.js#L97), change 

```js
this._call = invoke.call(invoke.IOS.Class('GREYActions'), 'actionForScrollInDirection:amount:', invoke.IOS.NSInteger(direction), invoke.IOS.CGFloat(amount));
```
to

```js
this._call = invoke.callDirectly(GreyActions.actionForScrollInDirectionAmount(direction,amount));
```
and also, remark the switch on direction.

**Comment by rotemmiz** [comment]
These are the currently supported types:
`EarlGrey, Class, NSString, NSNumber, NSInteger, CGFloat, CGPoint, CGRect and Invocation`

**Comment by rotemmiz** [comment]
We do need to refactor the MethodInvocation part to be more flexible, but for the time being, these are our limitations.

**Comment by DanielMSchmidt** [comment]
This is actually just a small bug, will provide a fix for it. In the other hands this leads to the discussion on how to fix unsupported types being used.

The current approach is to add sanitizers (e.g. [sanitize_GREYDirection](https://github.com/wix/detox/blob/master/detox/src/ios/earlgreyapi/GREYActions.js#L10)) and I think it would be best to go this path until the end and change the invocation scheme to support arbitrary inputs afterwards.

My plan for this would be to

1) List all supported typed, like @rotemmiz already did
2) Filter the methods before building the AST ([this would be the right place to start](https://github.com/wix/detox/blob/6553486c89003524828b8bf47d6a79ab7afcd2d9/generation/earl-grey/index.js#L56))
3) Add a console.info anywhere [here](https://github.com/wix/detox/blob/master/generation/earl-grey/index.js#L202-L215) that does the opposite filter and list out which methods / types are currently unsupported.

We could also think about it the other way around and check the generated code for any types other than the ones whitelisted, that way we could be sure to spot typos too.
