### ISSUE TITLE
Quick hot reload possible??

### ISSUE THREAD

**Issue by mhyousefi** [wix/detox#229]
Every time I run `detox build && detox test`, it takes **20 to 30 seconds** to start running my test specs, making the testing process a bit tiresome (especially when developing tests).

I was wondering if there is a hot reloading capability similar to what react-native offers when you run `react-native run-android` or `react-native run-ios`.

**Comment by isnifer** [comment]
@mhyousefi did you finish development and test after that?

**Comment by mhyousefi** [comment]
Well, I'm testing my app constantly, and it is evolving as I do so. What I am looking for is a short cut like `CMD+R`in react-native, which allows you to instantly view changes you've made without having to go through the entire build process. Now, one can live with the current situation, though a behavior similar to react-native hot reloading will make the process much swifter and easier....

**Comment by rotemmiz** [comment]
1. Make sure you build a debug build 
2. Hot reloading is possible, and it works, but the Simulator starts with hardware keyboard disabled, (`Hardware -> Keyboard -> Connect Hardware Keyboard`), then cmd+d will work
3. If you build a debug build and don't change any native code, you just need to `detox test`, no need to rebuild.
4. use `--reuse` option, read about it in the docs.

**Comment by mhyousefi** [comment]
I'm not sure why but `Hardware -> Keyboard -> Connect Hardware Keyboard` doesn't seem to work and it is not ticked when I click on it. Therefore, I'm not getting functionality expected from `CMD+D`...

**Comment by isnifer** [comment]
@mhyousefi Hey, you are not alone. I have a similar problem on iOS 10 simulators. Just use `cmd+control+z` hotkey instead of `cmd+d`

**Comment by mhyousefi** [comment]
Thanks, some nice options there...
