### ISSUE TITLE
ClearText Doesn't Work

### ISSUE THREAD

**Issue by ReshmiCode** [wix/Detox#2296]
### Description
The clearText command starts at the front of the text field thus doesn't clear any of the text.

- [x] I have tested this issue on the latest Detox release and it still reproduces

#### Expected behavior
The text field should clear.

#### Screenshots
![Screen Shot 2020-08-28 at 11 54 24 AM](https://user-images.githubusercontent.com/16989366/91593141-3d50f900-e925-11ea-94dd-15c2a7ef414c.png)

#### Environment (please complete the following information):
 - Detox: 17.4.2
 - React Native: 0.62.1
 - Device: iPhone 11

**Comment by LeoNatan** [comment]
Can you please create a demo project reproducing this? There is clearly something different than normal text input in your case, because this test passes in the demo suite, as well as internally. Thanks

**Comment by ReshmiCode** [comment]
@LeoNatan is there a base repo with Detox already added that I can use as a starting point?

**Comment by LeoNatan** [comment]
Any update here?
