### ISSUE TITLE
Swipe takes percentage of the element, not screen. Small elements cannot be swiped

### ISSUE THREAD

**Issue by viktorijasujetaite** [wix/Detox#2298]
**Is your feature request related to a problem? Please describe.**
Problem is that with Detox17 swipe is almost useless, especially with small elements, as detox swipe only within bounds of that element. This results in action sheets that cannot be closed and similar issues

**Describe the solution you'd like**
In function `swipe(direction, speed, percentage)` percentage stands for % of the screen

**Describe alternatives you've considered**
In a specific case where action sheet top handle could not be swiped, I tried swiping the whole action sheet but it's not by design to close it in such way.

**Comment by LeoNatan** [comment]
Implemented in #2299. I'll release once that is merged.

**Comment by LeoNatan** [comment]
17.4.5 out with this enhancement.

**Comment by shubhnik** [comment]
@LeoNatan thanks for the fix. But this works on ios only and not on android? // @viktorijasujetaite

**Comment by LeoNatan** [comment]
Android already works like that.
