### ISSUE TITLE
Detox test not running react-native 0.63.2

### ISSUE THREAD

**Issue by ShahidAli786** [wix/Detox#2301]
Detox tests are assigned to Undefined, and all e2e are skipped

![Screenshot 2020-09-02 at 4 18 09 PM](https://user-images.githubusercontent.com/24582758/91972334-30bf0d00-ed38-11ea-9981-8bd7ce964e30.png)

**Comment by ShahidAli786** [comment]
Detox tests are assigned to Undefined, and all e2e are skipped

**Comment by ShahidAli786** [comment]
@LeoNatan this issue is not resolved

**Comment by fazlizekiqi** [comment]
Trying to deploy with Travis CI and i think that rn 0.63.0 is not supported!
