### ISSUE TITLE
Detox 17.4.5 Failing Tests Because Detox.framework could not be found as a result of Xcode version bump to 11.7

### ISSUE THREAD

**Issue by jimmyceroneii** [wix/Detox#2302]
### Description
The bug appeared with the update to Xcode 11.7. I'm using Detox 17.4.5 (just updated with yarn upgrade) and the detox build command appears to work (though it runs quickly), but when running detox test I get the following error: 

```
Error: XXX/Detox/iOS/xxx/Detox.framework could not be found, this means either you changed a version of Xcode or Detox postinstall script was unsuccessful.
      To attempt a fix try running 'detox clean-framework-cache && detox build-framework-cache'
```

However, when I try running 'detox clean-framework-cache && detox build-framework-cache', I get the following related error: 

`Error: Command failed: xxx/node_modules/detox/scripts/build_framework.ios.sh`

When I try to run each command separately, I get the same result for both. 

- [Yes ] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

1. Upgrade Xcode to version 11.7
2. Upgrade Detox to 17.4.5
3. Run Detox Build
4. Run Detox Test

#### Expected behavior
The expected behavior is that the tests run.

#### Environment (please complete the following information):
 - Detox: 17.4.5
 - React Native: 0.62.2
 - Node: 12.18.0
 - Device: iPhone Simulator 
 - Xcode: 11.7
 - iOS: 13.7
 - macOS: Catalina 10.15.6

**Comment by LeoNatan** [comment]
Either `npm install` or run `detox rebuild-framework-cache`. It tells you what to do in the error.

**Comment by LeoNatan** [comment]
Hmmm. 
Can you post the log of the scrip please?

**Comment by LeoNatan** [comment]
Let's start by

```shell
rm -r ~/Library/Detox/ios/*
npm install
cat ~/Library/Detox/ios/*/detox_ios.log
```

And post the result of the `cat` here (no need for the install log).

Thanks

**Comment by jimmyceroneii** [comment]
@LeoNatan I don't seem to have an iOS folder in my Detox folder. Do you have any idea what that means? Should I reinstall? I've been using yarn instead of npm just as an fyi.

**Comment by LeoNatan** [comment]
You don't have `ios` because you `clean-framework-cache`. That's fine. Now try to install (so it fails), and you should see `ios` there.

**Comment by jimmyceroneii** [comment]
Do you mean try to install via `npm install`?

**Comment by LeoNatan** [comment]
Yes. When you install, Detox will try to rebuild its framework cache for the current Xcode configuration.

**Comment by jimmyceroneii** [comment]
Awesome! That added the iOS folder back and here's is the output of the cat: 

`TEMP_DIR = /var/folders/sx/ytcchqx52hsf7_hd901xvh8r0000gn/T/DetoxBuild.Quip
Xcode 11.3.1
Using -UseNewBuildSystem=YES
/Users/jenkins/Library/Developer/Xcode/DerivedData/Detox-etnwnlbyimgnergyaxslmkayknjo/Build/Products/Release-iphoneos
/Users/jenkins/Library/Developer/Xcode/DerivedData/Detox-etnwnlbyimgnergyaxslmkayknjo/Build/Products/Release-iphonesimulator
note: Using new build system
note: Planning build
note: Constructing build description
warning: Skipping duplicate build file in Copy Headers build phase: /Users/jenkins/.jenkins/workspace/detox-ios-release/detox/ios/EarlGrey/EarlGrey/Common/GREYScreenshotUtil.h (in target 'EarlGrey' from project 'EarlGrey')
warning: Skipping duplicate build file in Copy Headers build phase: /Users/jenkins/.jenkins/workspace/detox-ios-release/detox/ios/EarlGrey/EarlGrey/Common/GREYErrorConstants.h (in target 'EarlGrey' from project 'EarlGrey')
warning: Skipping duplicate build file in Copy Headers build phase: /Users/jenkins/.jenkins/workspace/detox-ios-release/detox/ios/EarlGrey/EarlGrey/Common/GREYSwizzler.h (in target 'EarlGrey' from project 'EarlGrey')
note: Using new build system
note: Planning build
note: Constructing build description
warning: Skipping duplicate build file in Copy Headers build phase: /Users/jenkins/.jenkins/workspace/detox-ios-release/detox/ios/EarlGrey/EarlGrey/Common/GREYScreenshotUtil.h (in target 'EarlGrey' from project 'EarlGrey')
warning: Skipping duplicate build file in Copy Headers build phase: /Users/jenkins/.jenkins/workspace/detox-ios-release/detox/ios/EarlGrey/EarlGrey/Common/GREYErrorConstants.h (in target 'EarlGrey' from project 'EarlGrey')
warning: Skipping duplicate build file in Copy Headers build phase: /Users/jenkins/.jenkins/workspace/detox-ios-release/detox/ios/EarlGrey/EarlGrey/Common/GREYSwizzler.h (in target 'EarlGrey' from project 'EarlGrey')
Processing COSTouchVisualizer.framework as a dir
Processing EarlGrey.framework as a dir
Processing LNViewHierarchyDumper.framework as a dir
Processing SocketRocket.framework as a dir`

**Comment by jimmyceroneii** [comment]
Ok @LeoNatan that seemed to have fixed things. Thank you so much for your help! 

Just to confirm, running the `clean-framework-cache` is what caused the iOS folder to disappear?

**Comment by LeoNatan** [comment]
Yes. Next time, when you switch Xcode, just run `detox rebuild-framework-cache` and it will recreate the cache for you; no need to `npm install`.

**Comment by xavierbrin** [comment]
In my case I had to remove detox dependency and reinstall it ( i'm using yarn so )
`yarn remove detox`
`yarn add detox`

**Comment by HossamAbdelnasser0110** [comment]
I faced the same issue when running the tests on circleci. Fixed by `nom rebuild detox` after `yarn install`

**Comment by owens-ben** [comment]
This is still an issue Detox 20.6.0. Workaround is still npm rebuild detox.
