### ISSUE TITLE
testID not detected on custom tags?

### ISSUE THREAD

**Issue by danielzzz** [wix/Detox#2303]
**Describe the bug**

when I create a custom component and use testID prop on it, it seems not to be detected.

**To Reproduce**
create a sample component then include it in a view
<View><MyComponent testID="myTestID" /></View>

It only works if I apply testID to the root view of my sample component.

- [x ] I have tested this issue on the latest Detox release and it still reproduces

Steps to reproduce:
1. create a sample component
2. use a testID on it
3. try to detect it by.id

**Expected behavior**

Hoped to find this component.

It only works if I apply testID to the root view of my sample component.

**Environment (please complete the following information):**
 - Detox: 17.3.6
 - React Native: 0.63.2
 - Node: v13.12.0
 - Device: android
 - OS: linux
 - Test-runner (select one): `jest`

**Comment by noomorph** [comment]
Why it should be detected? Detox knows nothing about Virtual DOM, never knew, and never will.

Unless you pass `testID` to `RCTView` or a component that on the native level supports accessibility properties, there is no technical possibility to locate the component.

**Comment by danielzzz** [comment]
ok, it makes sense. thanks
