### ISSUE TITLE
can't get Android element in Detox

### ISSUE THREAD

**Issue by barak109** [wix/Detox#2310]
**Describe the bug**
I have a project with native code and react native code, i want to set native android element( in the native code) and except it in the react native code with detox.

**To Reproduce**
1.create button in Java and "setId" to "barak"
`button.setId("barak")
`
2.try to except it in RN test code 

```
it('should have welcome screen', async () => {
  await element(by.id('barak')).toBeVisible();
});
```

**Expected behavior**
The test will get the id and the test will pass

**ERROR**

```
detox[16266] ERROR: DetoxRuntimeError: Failed to run application on the device

HINT: Most likely, your tests have timed out and called detox.cleanup() while it was waiting for "ready" message (over WebSocket) from the instrumentation process.
detox[16266] INFO:  Example is assigned to undefined
detox[16266] INFO:  Example: should have welcome screen
detox[16266] INFO:  Example: should have welcome screen [SKIPPED]

detox[16266] WARN:  [Client.js/PENDING_REQUESTS] App has not responded to the network requests below:
  (id = -1000) isReady: {}

Unresponded network requests might result in timeout errors in Detox tests.

detox[16265] ERROR: [cli.js] Error: Command failed: node_modules/.bin/jest --config e2e/config.json '--testNamePattern=^((?!:ios:).)*$' --maxWorkers 1 e2e

```
**Environment :**
 - Detox:"^17.4.4"
 - React Native:"0.61.5"
 - Node: 14.8.0
 - Device: "Pixel_3a_XL_API_29"
 - OS: android 
-jest-circus:"^26.0.1"

**I need to find the native code attribute in android(like setId) that access to "testId" in RN**

**Comment by LeoNatan** [comment]
https://stackoverflow.com/questions/59714311/how-to-handle-pure-native-elements-using-detox/59717876?noredirect=1#comment112762224_59717876
