### ISSUE TITLE
code(jest): develop E2E test to assert correct Jest stacktraces

### ISSUE THREAD

**Issue by noomorph** [wix/Detox#2312]
TODO

Detox has learned to mangle with error stacktraces for known use cases (e. g., failing matchers, etc), so that the test runner does not point the user to internal places somewhere inside Detox' codebase, but points to the failing line in the e2e test suite instead.

This functionality came with a regression bug for the first time, and not long after the fix, we are observing the second time, when it does not work as expected, and the stack traces again point the user to the Detox internals.

I suggest developing a test asserting against the test runner output, to validate that the stack trace hint does not go deeper than the e2e tests code for the expected cases such as failing matchers, etc.

**Comment by LeoNatan** [comment]
Dog chasing its tail. Trivial cases obviously work that you don't need a test, and if you find a scenario where the test fails, you'd already fixed it so it becomes trivial.

**Comment by noomorph** [comment]
We have a regression there for the second time, that's too much.

**Comment by LeoNatan** [comment]
What’s the second bug?

**Comment by noomorph** [comment]
@rotemmiz reports that on our CI, the error stack traces again started pointing to Detox internals. I plan to look into this issue right after I merge retyarik.

**Comment by noomorph** [comment]
Resolved in #2326
