### ISSUE TITLE
Supporting Android for E2E

### ISSUE THREAD

**Issue by heuism** [wix/detox#232]
First, thank for the wonderful contribution to this crazy world of React Native.

Second, my team is interesting in using this one for one of our project. The only thing making us skeptical about this is the support OS of this which only for iOS right now. We got some issue with the Android while we develop as well. So it would be better to check the Android version as well. I wonder when will the support for Android will be available according to your milestone. I saw some of the pull request by you guys about Android Support Phase 1, and i wonder if there any progress on finishing them.

Thanks

**Comment by rotemmiz** [comment]
Please refer to #96
