### ISSUE TITLE
Allow to set AsyncStorage values for the app

### ISSUE THREAD

**Issue by pke** [wix/Detox#2325]
## Problem

My app presents the typical Welcome slider deck on first app launch (don't ask, required by customer).
The deck can be skipped or finished by sliding through all 3 slides.
When the deck is finished a value is written to `AsyncStorage` that will prevent the welcome slider to appear again at next app start.

To be able to test screen beyond the welcome screen I'd need to set the `AsyncStorage` value from my tests (in a `beforeEach` filter).

## Current solution (workaround)

I am currently working around this by simulating a tap on the "skip" button in each of my non-welcome screen tests. However that degrades performance and is not really close to e2e, since users only see the screen once.

## Past related issues

I checked there were one or two issues here about clearing the `AsyncStorage` which were closed. Is this really so out of scope for this testing library? I think cypress can modify localStorage for tests. But I'm also unaware how much access detox really has to the app context to perform such operation to change `AsyncStorage`.

**Comment by LeoNatan** [comment]
Detox operates squarely in the native side of the app. We have no access to such things. React Native already includes mocking facilities, which you can use to achieve what you want. We even have a guide for mocking.

**Comment by pke** [comment]
Thanks for your feedback @LeoNatan 
I have read about the mocking feature. So I would have to create a file `AsyncStorage.e2emock.ts` that returns a mock of the AsyncStorage API.
And since mocks are global and static I would use my `beforeEach` filter to put a value into the mock to hide the welcome screens? Do I have access to the mock from the detox tests?

**Comment by LeoNatan** [comment]
The Detox test project runs in a node process, so no access you need to spin up a mock server that serves the values you want. You can see an example of this in our test suite.

**Comment by dimameshcharakou** [comment]
I got around this with [the launch arguments](https://wix.github.io/Detox/docs/guide/launch-args/).

In the test:

```js
await device.launchApp({
  launchArgs: { skipIntro: true }
});
```

In the application code:

```js
import { LaunchArguments } from 'react-native-launch-arguments';

const skipIntro = LaunchArguments.value().skipIntro;

if (!skipIntro) {
  return <WelcomeScreen />;
};

return <HomeScreen />;
```
