### ISSUE TITLE
swipe('right', 'slow/fast', 0.999) performs action from the middle of the view

### ISSUE THREAD

**Issue by losikov** [wix/Detox#2331]
### Description
I have **ScrollView** taking full screen.
I have **DrawerLayout** hidden behind the right edge. I can pull out the drawer doing swipe from the right edge of the screen. With detox, I do it using ScrollView, swiping it from right to left.

#### Reproduction

Example repo: git@github.com:losikov/react-native-detox-test.git

1. git clone git@github.com:losikov/react-native-detox-test.git 
2. cd react-native-detox-test
3. yarn install
4. cd ios ; pod install ; cd ..
5. yarn test:e2e:build
6. yarn test:e2e:run
the second test will fail, while it works with 17.4.4 and lower.
Please pay attention to the first test, it works only with the latest detox, but not previous. I'm not sure if it is related.

#### Expected behavior
swipe('right', 'slow/fast', 0.999) -> should swipe entire view. 

#### Environment (please complete the following information):
 - Detox: 17.3.5, 17.4.4, 17.4.5, 17.4.5
 - React Native: 0.63.2
 - Node: v12.18.3
 - Device: iPhone 11 simulator
 - Xcode: Version 11.7 (11E801a)
 - iOS: 13.7
 - macOS: 10.15.6 (19G2021)

**Comment by LeoNatan** [comment]
I will look into this soon.

**Comment by LeoNatan** [comment]
Took longer than expected, but I've fixed it. Will be in the next Detox release.
