### ISSUE TITLE
Getting Started @ Node 4.2.1: SyntaxError: Block-scoped declarations

### ISSUE THREAD

**Issue by etaiklein** [wix/detox#234]
#### Description

Detox fails on node version 4.2.1. The docs say "Install Node 7.6.0 or above for native async-await support," but that implies to me that it should still work on lower node versions - just without native async-await. 

I assume my version is too low to run Detox? What's the min working version? This might just be fixed by adding 'use strict' to detox-build.js

#### Steps to Reproduce

1. https://github.com/wix/detox/blob/master/docs/Introduction.GettingStarted.md 
2. `detox build`

#### Full Trace
```
/Users/etai/Code/data/mobile/node_modules/detox/local-cli/detox-build.js:14
let buildScript;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
```

#### Node, Device, Xcode and macOS Versions

* Node:  4.2.1
* Device: Iphone 7
* Xcode:  8.2
* macOS: 10.12.6

**Comment by etaiklein** [comment]
this might just be fixed by adding 'use strict' to detox-build.js

**Comment by isnifer** [comment]
@etaiklein what's wrong with 7 or 8 versions of node? Why are you using 4?

**Comment by etaiklein** [comment]
@isnifer I'm working on a project locked at Node 4.2.1 for infrastructure reasons. It'll be on the order of months before we upgrade.

**Comment by rotemmiz** [comment]
You can skip usage in detox-cli and use mocha directly.

I think Node 6 is the minimum even if you babel your code, since we use `require('url').URL`

**Comment by etaiklein** [comment]
Alright, I guess I'll check back in if/when we upgrade.

It might be good to add the minimum in the docs somewhere.
