### ISSUE TITLE
Packaging fails when running tests with mocking setup

### ISSUE THREAD

**Issue by emeraldsanto** [wix/Detox#2340]
### Description
Running tests with mocking extension fails to package successfully, both in debug and release mode. Metro complains about a certain module imported from the Detox logger (unable to resolve module `path`). When building and starting the packager without the extension environment variable, tests work properly but obviously use the non-mock files.

- [x] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

1. Create new RN application
2. Setup Detox
3. Setup mocking, as explained in [docs/Guide.Mocking.md](https://github.com/wix/Detox/blob/master/docs/Guide.Mocking.md)
4. Build the app via `detox build`
5. Run tests via `detox test`

#### Expected behavior

Tests should run and use files with the proper extension, as intended.

#### Screenshots

<img width="300" src="https://user-images.githubusercontent.com/33291795/93480551-8fa18c00-f8cb-11ea-9aee-20285922ecd1.png" />

#### Environment
 - Detox: 17.5.4
 - React Native: 0.63.2
 - Node: 12.18.3
 - Device: iPhone 11 Simulator
 - Xcode: 11.7
 - iOS: 13.7
 - macOS: 11.0

#### Relevant files

.detoxrc.json
```json
{
	"testRunner": "jest",
	"runnerConfig": "src/e2e/config.json",
	"configurations": {
		"ios": {
			"type": "ios.simulator",
			"binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/appname.app",
			"build": "RN_SRC_EXT=e2e.ts xcodebuild -workspace ios/Appname.xcworkspace -scheme Appname -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build",
			"device": {
				"type": "iPhone 11"
			}
		},
		"android": {
			"type": "android.emulator",
			"binaryPath": "android/app/build/outputs/apk/detox/debug/app-detox-debug.apk",
			"build": "cd android && RN_SRC_EXT=e2e.ts ./gradlew assembleDetoxDebug assembleDetoxDebugAndroidTest -DtestBuildType=debug && cd ..",
			"device": {
				"avdName": "Nexus_6P_API_29"
			}
		}
	}
}
```

config.json
```json
{
	"testEnvironment": "./environment",
	"testRunner": "jest-circus/runner",
	"testTimeout": 120000,
	"testRegex": "\\.e2e\\.(js$||ts$)",
	"reporters": ["detox/runners/jest/streamlineReporter"],
	"verbose": true
}
```

environment.js
```
const {
	DetoxCircusEnvironment,
	SpecReporter,
	WorkerAssignReporter
} = require("detox/runners/jest-circus");

class CustomDetoxEnvironment extends DetoxCircusEnvironment {
	constructor(config) {
		super(config);

		// Can be safely removed, if you are content with the default value (=300000ms)
		this.initTimeout = 300000;

		// This takes care of generating status logs on a per-spec basis. By default, Jest only reports at file-level.
		// This is strictly optional.
		this.registerListeners({
			SpecReporter,
			WorkerAssignReporter
		});
	}
}

module.exports = CustomDetoxEnvironment;
```

**Comment by emeraldsanto** [comment]
I would also like to add that I've really narrowed it down to the mocking issue, since I've tried running both the build and bundler with the extension environment variable set while not importing any file that had a mocked counterpart. In this scenario the bundle is able to be built without any errors.

**Comment by noomorph** [comment]
I'll run the described steps soon and check if I am able to reproduce:

> 1. Create new RN application
> 1. Setup Detox
> 1. Setup mocking, as explained in docs/Guide.Mocking.md
> 1. Build the app via detox build
> 1. Run tests via detox test

**Comment by rotemmiz** [comment]
Something doesn't make sense, are you trying to load Detox logger into your app? Detox code is meant to run in node under your test runner, not in your app's code.
Can you verify please?

**Comment by emeraldsanto** [comment]
@rotemmiz Nope, I even tried disabling the logger via the command line argument. I just checked and I only import `expect`, `element`, `by` and `device` from Detox. As I said previously, the same setup works when removing the custom extension environment variable from build and packager commands.

**Comment by rotemmiz** [comment]
Still, this is what the error from the packager says, make sure you don't import detox code into your project (in that case, don't import detox code into your mocks).

**Comment by emeraldsanto** [comment]
I can try without importing the things I mentioned in my previous comment, those were mostly to get accurate TypeScript checking (otherwise the jest globals would take precedence).

**Comment by emeraldsanto** [comment]
I've tried removing all detox imports for `element`, `expect`, `by`, etc. and tried rebuilding + packaging with the mock extension environment variable. This resulted in a successful build (no change there) and a different error when packaging, now Metro complains about not being able to resolve one of my own files, which is a located in the `e2e` folder and contains test credentials and such.
