### ISSUE TITLE
Improve test timeout handling

### ISSUE THREAD

**Issue by noomorph** [wix/Detox#2341]
### **Is your feature request related to a problem? Please describe.**

When there is a pending (stuck) network request, spawned child process (e.g., `applesimutils ... something`) or (theoretically) FS I/O operation, Detox codebase has no consistent way to abort/cancel all the pending operations.

Sometimes that leads to abnormal conditions, when upon a timeout the test runner would invoke next Detox lifecycle methods, while the previous calls are still pending. That worsens at the moment, when `detox.cleanup()` is called, because it often releases some pending operations, and we have a batch of operations being executed after the cleanup as well, e.g.:

```js
await detox[onTestStart](...); // stuck...
await detox[onHookStart](...) // goes well
await detox[onHookSuccess](...); // stuck
await detox[onTestFnStart](...); // goes well
await detox[onTestFnSuccess](...); // stuck
await detox[onTestDone](...); // stuck
// ...
// bada-boom timeout
await detox.cleanup();
// detox[onTestStart] continues
// detox[onHookSuccess] continues
// detox[onTestFnSuccess] continues
// ...and all the three might run in parallel, creating extra issues
```

### **Describe the solution you'd like**

I'm not entirely sure about the best solution, hence I can suggest two directions.

#### Chain of promises 

We could use a chain of promises, so that:

```js
detox[onTestStart](...);
detox[onHookStart](...);
detox[onHookSuccess](...);
detox[onTestFnStart](...);
detox[onTestFnSuccess](...);
detox[onTestDone](...);
```

would get transformed into:

```js
stepByStepPromise.then(onTestStart).then(onHookStart).then(onHookSuccess).then(onTestFnStart).then(onTestFnSuccess).then(onTestDone)
```

and if suddenly, let's say, `onTestStart` is stuck, then:

1) no further lifecycle methods are executed, because they are waiting for its resolution or rejection
2) upon `detox.cleanup()` invocation, if `onTestStart` rejects a promise, then all the chain would break and never get executed.

#### detox.abortPendingOperations()

Develop a manager class, which serves as a wrapper for all the operations that might get hang up, and execute all the network, file I/O, child_process commands via this manager.

If a Detox instance exposes then a method such as `Detox.prototype.abortPendingOperations`, then every time we get into a timeout conditions, the Jest Circus environment can call this method to make sure that the pending lifecycle method stops any background activities, rejects with an error, and then safely move on to the next lifecycle phase.

This issue is related to https://github.com/wix/Detox/pull/2335. While the latter fixes some of the symptoms, this issue suggests finding a cure for the abrupt `detox.cleanup()` when many methods are stuck in the middle and get flushed at the end.

**Comment by noomorph** [comment]
@d4vidi , I've analysed the issue behind #2335, so here it is.

**Comment by d4vidi** [comment]
@noomorph should this be resurrected?

**Comment by noomorph** [comment]
Hmm, yes, let's resurrect.
