### ISSUE TITLE
How to run with Xcode 12?

### ISSUE THREAD

**Issue by Doko-Demo-Doa** [wix/Detox#2343]
Hello, I have been using detox for a while. Things were nice, until I upgraded Xcode to 12, several days ago.

My build command:

```
ENVFILE=.env.staging xcodebuild -workspace ios/DoraReactNative.xcworkspace -scheme DoraReactNative -configuration Release -sdk iphonesimulator -derivedDataPath ios/build -UseModernBuildSystem=YES
```

In my app, I'm using Amazon Chime iOS SDK.

And got this error:

```
The following build commands failed:
	Ld /Users/doko/Projects/ReactNative/DoraMobile/ios/build/Build/Intermediates.noindex/DoraReactNative.build/Release-iphonesimulator/DoraReactNative.build/Objects-normal/arm64/Binary/Dora normal arm64
(1 failure)
detox[4011] ERROR: [cli.js] Error: Command failed: ENVFILE=.env.staging xcodebuild -workspace ios/DoraReactNative.xcworkspace -scheme DoraReactNative -configuration Release -sdk iphonesimulator -derivedDataPath ios/build -UseModernBuildSystem=YES
```

This did not happen in Xcode 11, I also ask my co-worker (who is running Xcode 11 to confirm that).

What am I missing?

**Comment by Guuz** [comment]
@Doko-Demo-Doa did you ever find a solution? I'm using the same command as you and have the same issue.

**Comment by zeemyself** [comment]
https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios
This fix for me.

**Comment by joncolque** [comment]
Hi! In case you don't want to modify the xcode settings add `--destination`:
```
xcodebuild -workspace ... -destination 'platform=iOS Simulator,name=iPhone 11'
```
and replace "iPhone 11" for your device in detox configuration (.detoxrc.json or package.json)
I hope that helps.

**Comment by Doko-Demo-Doa** [comment]
Awesome, thanks @joncolque . It works!

**Comment by Guuz** [comment]
@Doko-Demo-Doa Did you just add the `-destination` flag with the value as described by @joncolque ? I tried that, even cleared my entire build directory, and tried a few times. But to no avail :(
>ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/guus/Projects/ApotheekInJeBroekzak/node_modules/@notifee/react-native/ios/NotifeeCore.framework/NotifeeCore' for architecture arm64

**Comment by Doko-Demo-Doa** [comment]
Yes, I only have to append `destination` like so:

```bash
xcodebuild -workspace ios/DoraReactNative.xcworkspace -scheme DoraReactNative -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build -UseModernBuildSystem=YES -destination 'platform=iOS Simulator,name=iPhone 8'
```

Maybe [this](https://stackoverflow.com/questions/23092201/ld-building-for-ios-simulator-but-linking-against-dylib) can solve your issue?

**Comment by Guuz** [comment]
@Doko-Demo-Doa thanks for your time and effort! unfortunately, after trying various things from the stackoverflow post, i see no difference :(

The search continue's!
