### ISSUE TITLE
Can't access elements in detox after react-native firstly load

### ISSUE THREAD

**Issue by barak109** [wix/Detox#2344]
**Describe the bug**
I'm running detox on app that started from native app and now working as a combination of react native app and native code.

I'm using iOS simulator to check the test.

My app is starting in the iOS native side, and the detox tests running on it and get the elements(all works fine), but as we go with the flow of the app, when we firstly load the bundle(index.js- for running the react-native side), we can't access the elements(in the native side) with detox, and the tests failed.

**To Reproduce**

1. start the app and run it on iOS native side 
2. Go with the flow, until you get the place you integrate with react native code.
3. The app will stop listen to detox tests 

```

describe('Previews', () => {

  beforeAll(async () => {
      await device.launchApp({ permissions: {notifications: 'YES',location:'always'}});
    });
   
     it('should tap on acceptButton', async () => {
       await element(by.id('acceptButton')).tap();
     });
   
     it('should tap on enable Notifications button', async () => {
       await element(by.id('enableNotificationsButton')).tap();
     });

     // Here the bundle of the react-native loading, and the detox can't find 'editButton'
     // 'editButton' it's still in the native side
    it('should click on editButton',  async() => {
       await element(by.id('editButton')).toBeVisible();
     });

});
```

**Expected behavior**
Will run the tests as expected and don't stop them.

**ERROR**

```
detox[73960] WARN:  [Client.js/PENDING_REQUESTS] App has not responded to the network requests below: (id = 6) invoke: {"type":"action","action":"tap","predicate":{"type":"id","value":"continueFaceIdButton"}} Unresponded network requests might result in timeout errors in Detox tests.

```
**Environment :**
 - Detox:"^17.4.4"
 - React Native:"0.61.5"
 - Node: 14.8.0
 - Device: "Pixel_3a_XL_API_29"
 - OS: android 
-jest-circus:"^26.0.1"

stackoverflow issue opens too
** https://stackoverflow.com/questions/63935855/cant-access-elements-in-detox-after-react-native-firstly-load

**Comment by LeoNatan** [comment]
Your error doesn't match the id in the test you claim doesn't work.

Also, there is a template for a reason. Please follow it and provide the following info:

> #### If you are experiencing a timeout in your test
> - [ ] I have followed the instructions under [Lower-level Idling Resources Debug](https://github.com/wix/Detox/blob/master/docs/Troubleshooting.Synchronization.md#lower-level-idling-resources-debug-ios-only) and am providing the log below:

**Comment by barak109** [comment]
@LeoNatan Thank you for the response, i don't know why but when i added this 'beforeAll', it cause opening another iOS simulator and on this simulator there is no problem when the bundle firstly load, and the tests worked as expected.
 
```

 beforeAll(async () => {
      await detox.init(undefined, { launchApp: false });
      await device.launchApp({ permissions: {notifications: 'YES',location:'always'}});
  })

```
If you have any clue i will be glad to know 🤔
Thanks.

**Comment by LeoNatan** [comment]
This is not what I asked. Please read how to obtain the log in the link I provided. Closing as a question, as this is better suited for SO.
