### ISSUE TITLE
iOS 14 Support Tracking

### ISSUE THREAD

**Issue by LeoNatan** [wix/Detox#2346]
Short term: merge some of the EG fixes here: Xcode 12: https://github.com/google/EarlGrey/pull/1431
Longer term: Ensure DetoxSync properly works on iOS 14

**Comment by StasDoskalenkoHover** [comment]
If we can have some RC or alpha to test - it would be really nice!
Thanks for your efforts @LeoNatan

**Comment by LeoNatan** [comment]
Sorry, I haven’t worked on this. Once it’s ready, it will go directly to master.

**Comment by heliojuniorkroger** [comment]
Hey @LeoNatan maybe it's not related to the iOS upgrade at all, but, after upgrading, my tests are failing due to iOS prompting an Apple login modal. I even logged in the Simulator with my Apple account, but doesn't seem to work  (the system keeps requesting login).

**Comment by LeoNatan** [comment]
@heliojuniorkroger Detox doesn't open any Apple login prompts. I'm not sure what is happening in your simulator.

**Comment by StasDoskalenkoHover** [comment]
@LeoNatan hey! Tested it locally. Looks much better and more stable 👍

**Comment by benevbright** [comment]
Hi, @LeoNatan Can we have a hotfix for 16.x.x including this fix? 
We can't update to v17 right now due to new changes in v17 that makes some of our tests fail.

**Comment by LeoNatan** [comment]
No sorry. It's time to move.

**Comment by MayoudP** [comment]
Using detox `17.6.1` and then Xcode12/iOS 14, but when building my react-native app, I'm keep having this error : 
`
clang: error: no such file or directory:.../node_modules/detox/ios_src/SocketRocket/SocketRocket/NSRunLoop+SRWebSocket.m'`

Any ideas why ? I didn't see any others related issue.

**Comment by LeoNatan** [comment]
I’ll remove the podspec from our fork of SocketRocket.

**Comment by sta-vanger** [comment]
Hi -  what version can we use this xcode 12 & iOS 14 support? Is it already on detox 18.0.0? Please advise. Thank you!

**Comment by LeoNatan** [comment]
It is supported, yes.
