### ISSUE TITLE
clearText() presses at the leftmost part of a multiline text view, putting the cursor before the text, and is unable to clear the text

### ISSUE THREAD

**Issue by rotemmiz** [wix/Detox#2349]
### Description

Reproduced a bug where `clearText()` presses at the leftmost part of a multiline text view, putting the cursor before the text, and is unable to clear the text.

#### Reproduction

1. checkout https://github.com/wix/Detox/commit/c9574fdce0e499749b6a3e17b2b55059aa0d5c2d
2. `detox build -c ios.sim.release && detox test e2e/03.actions.test.js -c ios.sim.release`

#### Environment (please complete the following information):
 - Detox: 17.5.7
 - React Native: RN63
 - Node: 
 - Device:
 - Xcode: 11.2.1
 - iOS: 13.2.2
 - macOS: 10.15.6

**Comment by LeoNatan** [comment]
Fixed
