### ISSUE TITLE
_getAbsolutePath() not compatible with expo

### ISSUE THREAD

**Issue by jackkinsella** [wix/detox#235]
In **Device.js**:

` _getAbsolutePath()`, which is used for loading the app binary, always assumes that the app is located in the current working directory. With react-native, this assumption is no longer true because of the now commonplace use of **expo**, which puts the binary down in `~/.expo`. This isn't an issue with one programmer on a team, since they can type "../../../.expo" etc., but when sharing code between two programmers who have different file system structures, it becomes problematic.

**Comment by isnifer** [comment]
Does expo allow you change application binary path? It's strange place to save binaries :)

**Comment by jackkinsella** [comment]
I was surprised too. But then again, this single Expo install gets shared by all Expo-enabled React apps, so it would make even less sense to put them in individual project folders.

There is no mention of configuration on this point in their docs...

**Comment by LeoNatan** [comment]
I think this was solved recently by @silyevsk for #98 .
