### ISSUE TITLE
Continuous scrolling via waitFor cannot reach the end and does not stop after the cleanup

### ISSUE THREAD

**Issue by noomorph** [wix/Detox#2355]
### Description

Continuous scrolling via waitFor cannot reach the end and does not stop after the cleanup.

![waitFor_bug_movie](https://user-images.githubusercontent.com/1962469/94010878-33e57000-fdaf-11ea-9e3d-54093ae51f2a.gif)

The test below does not pass E2E tests and fails with timeout:

```diff
diff --git a/detox/test/e2e/05.waitfor.test.js b/detox/test/e2e/05.waitfor.test.js
index 06c4adee..f8e2b79e 100644
--- a/detox/test/e2e/05.waitfor.test.js
+++ b/detox/test/e2e/05.waitfor.test.js
@@ -42,6 +42,11 @@ describe('WaitFor', () => {
     await expectToThrow(() => waitFor(element(by.id('neverAppearingText'))).toExist().withTimeout(1000));
   });
 
+  it('should continously scroll until it finds an item in the list', async () => {
+    await expect(element(by.text('HText8'))).not.toBeVisible();
+    await waitFor(element(by.text('HText8'))).toBeVisible().whileElement(by.id('horizontalScrollView')).scroll(20, 'right');
+  });
+
   it('should abort scrolling if element was not found', async () => {
     await element(by.id('GoButton')).tap();
     await expectToThrow(() => waitFor(element(by.text('Text1000'))).toBeVisible().whileElement(by.id('ScrollView')).scroll(50, 'down'));
```

- [x] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

1. `git fetch`
1. `git checkout fix/waitFor-scroll` ([see the branch online](https://github.com/wix/Detox/tree/fix/waitFor-scroll))
1. `cd detox/test`
1. npx detox build -c ios.sim.release
1. npx detox test -c ios.sim.release e2e/05.waitfor.test.js

#### Expected behavior

1. After the tests fail with a timeout, and Detox sends `cleanup` action, the runner should stop scrolling on the phone.
2. Ideally, the runner should manage to scroll till the end of the list without moving the scrollbar handle left.

#### Environment (please complete the following information):
 - Detox: 17.5.5
 - React Native: 0.62.2 
 - Node: 10.15.3
 - Device: iPhone 11 Pro 
 - Xcode: Xcode 11.2.1
 - iOS: 13.2.2
 - macOS: 10.15.6

**Comment by LeoNatan** [comment]
Thanks, I’ll commit your added test as another in the suite.
