### ISSUE TITLE
Tapping on a disable button should send a `testFailed` event with an error.

### ISSUE THREAD

**Issue by rotemmiz** [wix/Detox#2356]
### Description
With the actions reimplementation of Detox 17, some of the old behaviour has changed. `tap()` on a disabled button threw an error, but it doesn't on Detox 17 (17.5.8).

Old EarlGrey error for reference:
```
 Cannot perform action due to constraint(s) failure.
    Exception with Action: {
      "Action Name":  "Tap",
      "Element Description":  "<_UIButtonBarButton:0x7fddec6773b0; AX=Y; AX.id='wix.platform.ABOUT_TAB_WIDGET_SETTINGS_SCREEN_SAVE'; AX.label='Save'; AX.frame={{357, 44}, {45, 44}}; AX.activationPoint={379.5, 66}; AX.traits='UIAccessibilityTraitButton,UIAccessibilityTraitNotEnabled'; AX.focused='N'; frame={{0, 0}, {45, 44}}; opaque; alpha=1; disabled>",
      "Failed Constraint(s)":  "enabled",
      "All Constraint(s)":  "(!(isSystemAlertViewShown) && ((respondsToSelector(isAccessibilityElement) && isAccessibilityElement) || kindOfClass('UIView')) && (enabled && !(((kindOfClass('UIView') || respondsToSelector(accessibilityContainer)) && ancestorThatMatches(!(enabled))))) && interactable)",
      "Recovery Suggestion":  "Adjust element properties so that it matches the failed constraint(s)."
    }


    [
      {
        "Description":  "Cannot perform action due to constraint(s) failure.",
        "Error Domain":  "com.google.earlgrey.ElementInteractionErrorDomain",
        "Error Code":  "1",
        "File Name":  "GREYBaseAction.m",
        "Function Name":  "-[GREYBaseAction satisfiesConstraintsForElement:error:]",
        "Line":  "66"
      }
    ]
```

#### Environment (please complete the following information):
 - Detox: 17.5.8
 - React Native: 0.62.2
 - Node: .
 - Xcode: 11.2.1
 - iOS: 13.2.2
 - macOS: 10.15.6

**Comment by LeoNatan** [comment]
People wanted loose, they got loose. Detox now only checks for visibility, not hittability.

**Comment by LeoNatan** [comment]
_UIButtonBarButton

That explains it. It's an actual `UIButton`, unlike RN "buttons". Sadly, there is no way to generically support this. I will improve the attributes to return the correct value in case a view is an actual `UIControl`, but it will not work as expected, because selecting a button by text will match its inner label, instead of the button itself.

**Comment by rotemmiz** [comment]
A better approach here is to check if the view is enabled using `getAttributes()`.

**Comment by LeoNatan** [comment]
The same issue applies there

**Comment by LeoNatan** [comment]
Apparently I had this implemented already 🤦‍♂️

<img width="513" alt="Screen Shot 2020-09-30 at 00 13 47" src="https://user-images.githubusercontent.com/2270433/94617260-f0f53200-02b1-11eb-9d4c-d27e9e9942e0.png">

So, for actual buttons (and other controls), there is an `enabled` key returned in attributes exactly for this.
