### ISSUE TITLE
Detox will not tap button because it says that it is not visible enough.

### ISSUE THREAD

**Issue by taylorjosephgriffin** [wix/Detox#2358]
### Description
I have a screen where there is a button to switch views. In my tests, detox finds the button by testID but tells me that the button is not visible. Screenshots and logs below to give more context and detail. 

- [X ] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction

1. I don't know how exactly one could reproduce it as it is a specific implementation but I have tried moving the testID to various different elements including the TouchableOpacity's parent View and the TO's inner Text component and I get the same error messages each time. 

#### Expected behavior
I am trying to select the button shown below. It is expected that detox will find the button and tap it.

#### Screenshots
<img width="419" alt="Screen Shot 2020-09-23 at 11 21 59 AM" src="https://user-images.githubusercontent.com/23637586/94053503-42239400-fd8f-11ea-99d0-124dc925a3fe.png">
<img width="777" alt="Screen Shot 2020-09-23 at 11 15 36 AM" src="https://user-images.githubusercontent.com/23637586/94053176-d6412b80-fd8e-11ea-896b-a859beab99ef.png">
<img width="622" alt="Screen Shot 2020-09-23 at 11 18 27 AM" src="https://user-images.githubusercontent.com/23637586/94053190-d8a38580-fd8e-11ea-85c4-925b04798edf.png">

#### Environment (please complete the following information):
 - Detox: 17.6.0
 - React Native: 0.61.2
 - Node: 12.18.3
 - Device: iPhone 11 
 - Xcode: 11.3.1
 - iOS: 13.3
 - macOS: 11

### Logs

    Test Failed: View “<RCTView: 0x7fa08ded38f0>” is not visible: view does not pass visibility threshold (75%)
    TIP: To print view hierarchy on failed actions/matches, use loglevel verbose and above.

      94 |     await element(by.id('CreateOrder')).tap();
      95 |
    > 96 |     await element(by.id('SwitchLabelRight')).tap();
         |                                              ^
      97 |
      98 |     // await scrollToElement('ScrollView', `${orderQuantity}-Pack`, 'down');
      99 |     // await element(by.id(`${orderQuantity}-Pack`)).tap();

#### Device and verbose Detox logs
- [X] I have run my tests using the `--loglevel trace` argument and am providing the verbose log below:
Test Failed: View “<RCTView: 0x7fc93b762dd0>” is not visible: view does not pass visibility threshold (75%)
    View Hierarchy:
<Remove by Leo>

**Comment by LeoNatan** [comment]
Hello,

Showing your component code doesn’t help, because Detox lives in the native world. Please run your app with Xcode, reach the screen you have an issue, open the hierarchy inspector and post here screenshots of the two views. See if one sits on top of the other.

**Comment by taylorjosephgriffin** [comment]
<img width="871" alt="Screen Shot 2020-09-24 at 9 39 40 AM" src="https://user-images.githubusercontent.com/23637586/94174484-3517ab00-fe4a-11ea-9a5d-32dc5f02f052.png">

Sorry I haven't used the hierarchy inspector, is this what you are referring to? @LeoNatan

**Comment by LeoNatan** [comment]
Yes, but show me the 3D inspector, where you see the views

**Comment by taylorjosephgriffin** [comment]
![Kapture 2020-09-24 at 09 44 30](https://user-images.githubusercontent.com/23637586/94174905-c4bd5980-fe4a-11ea-9e33-f46d4d5b9209.gif)
Heres a gif of me dragging the 3d view. It looks like maybe that gray box is blocking but im not sure. Let me know if you need something else. I'm not familiar with these internal Xcode tools.

**Comment by LeoNatan** [comment]
But you can see from that GIF that the selected view is obscured, right?

**Comment by taylorjosephgriffin** [comment]
Yeah I see that, so in a situation like this, detox will be unable to tap the element as it is behind. Is there a way for me to ignore that obscuring view? Or is this just a composition issue on my end that I need to refactor?

**Comment by LeoNatan** [comment]
Let me get back to you. I am developing a debug tool that you will be able to enable, and get some debug images. I've seen some instances where the Xcode hierarchy inspector has shown some views that aren't really visible.

**Comment by taylorjosephgriffin** [comment]
Okay so it is a composition issue. Moving that component in code changed the order and passed the test. Thank you for your help and big thanks for letting me know about this 3d view. Let me know about the debug tool that would be immensely helpful!

**Comment by StasDoskalenkoHover** [comment]
yeah, it's kinda weird. Is it a react-native or yoga bug? Elevated elements with higher zIndex sometimes could be under the other views in LayoutInspector (so detox will see it the same way). But above other views on device/simulator.

**Comment by LeoNatan** [comment]
What matters in the end is how the views appear on device, in the actual hierarchy. Xcode could be buggy too, but I've only seen this kind of issues with React Native. The concept of zIndex doesn't really exist on iOS, and I have no idea how it's implemented behind the scenes in RN.

**Comment by LeoNatan** [comment]
I'll push my debug tool in a few minutes, where we'll be able to better look at what Detox sees.

**Comment by LeoNatan** [comment]
I've pushed and ordered a release build. Once it's out, the test tool can be enabled with `-detoxDebugVisibility YES` launch argument. What will happen is, for each view that fails visibility, two images will be saved on your desktop:

![DETOX_VISIBILITY_CustomView  0x7ffe9f50df10 _SCREEN](https://user-images.githubusercontent.com/2270433/94178906-68872380-fea4-11ea-845c-c55c25b68c0e.png)
![DETOX_VISIBILITY_CustomView  0x7ffe9f50df10 _TEST](https://user-images.githubusercontent.com/2270433/94178919-6c1aaa80-fea4-11ea-8db6-64f1f4b21361.png)

The first is supposed to show what is seen on screen. The second shows the internal buffer that Detox tests for visibility; if the pixels aren't transparent enough and less than 75% of tested region is not transparent, the view is not considered visible.

**Comment by LeoNatan** [comment]
In the above case, the red square is tested for visibility.

**Comment by StasDoskalenkoHover** [comment]
@LeoNatan wow thank you so much!!! This will be very helpful.

**Comment by StasDoskalenkoHover** [comment]
I'm also wondering, do we really need to assess a button for a 75% visibility threshold when pressing?

**Comment by LeoNatan** [comment]
Any view is tested for visibility. Otherwise, you might tap a different view. Imagine having an alert open on top of the button.

**Comment by StasDoskalenkoHover** [comment]
I guess sometimes in edge cases we might need to override the visibility threshold assessment.

**Comment by skylarbarrera** [comment]
Running into similar issues, @LeoNatan having trouble invoking the -detoxDebugVisibility tag, could you advise as to where/how to add this argument?

**Comment by danielgreane** [comment]
Are you able to pass `-detoxDebugVisibility YES` through as a param in the `detox test` cli command? I've tried  passing via `--device-launch-args` but not had much luck

**Comment by LeoNatan** [comment]
Send that argument using `device.launchApp()`. launchApp is documented in our docs.

**Comment by danielgreane** [comment]
Thanks, I've managed to get it through this way and it seems to be passing it through on the launcher, but the test looks the same visibly when the test occurs, and no screenshots are generated on my desktop. Is there a way to debug where the output screenshots are being generated?

![Screenshot 2020-09-30 at 13 15 20](https://user-images.githubusercontent.com/9444927/94683790-005e9480-031f-11eb-8685-487984ff7efc.png)
<img width="561" alt="Screenshot 2020-09-30 at 13 19 01" src="https://user-images.githubusercontent.com/9444927/94684120-84188100-031f-11eb-94b1-f925d2525278.png">

I'm on version 17.6.1 of detox

**Comment by danielgreane** [comment]
<img width="809" alt="Screenshot 2020-09-30 at 13 21 56" src="https://user-images.githubusercontent.com/9444927/94684399-ec676280-031f-11eb-804b-b8c8a01fc421.png">

For clarity, this is the output of the failed test when the args are passed through as above

**Comment by LeoNatan** [comment]
You need to edit the Deotx source files. Extract the source tbz, edit UIImage+Utils.m and run `detox rebuild-framework-cache`

**Comment by LeoNatan** [comment]
Ah, that’s a different error. That one means your view is hidden by a superview.

**Comment by anisimov74** [comment]
@LeoNatan thanks for the `detoxDebugVisibility` parameter! Is it possible somehow to configure the path where screenshots will be saved?

**Comment by d4vidi** [comment]
@anisimov74 unfortunately now. The screenshots are saved to the Desktop folder.

**Comment by 15110011** [comment]
how to bring the element behind another element to test guys?

**Comment by ziga-hvalec** [comment]
<s>Is there any solution for this? except refactoring our code to avoid something transparent covering buttons which works just fine if clicked on by user but not by detox? Other tools like maestro work just fine</s>
Actually tapping works but toBeVisible does not see the element

```js
  await waitFor(element(by.id('header-back-icon')))
    .toBeVisible()
    .withTimeout(30000);
  await element(by.id('header-back-icon')).tap();
```

But just clicking without checking works just fine

```js
  await element(by.id('header-back-icon')).tap();
```
