### ISSUE TITLE
Pull-to-refresh functionality cannot be tested, because scroll() won't go past the edges 

### ISSUE THREAD

**Issue by E1213180** [wix/Detox#2359]
**Is your feature request related to a problem? Please describe.**
We have a list with a `RefreshControl`. We would like to write E2E tests for the pull-to-refresh functionality. We cannot at the moment because `scroll()` bails out when it hits the list edges.

**Describe the solution you'd like**
A new method, `scrollPastEdge(edge: Direction, pixels: number)` 

**Describe alternatives you've considered**
None of the existing interaction actions can perform pull-to-refresh

**Comment by noomorph** [comment]
@E1213180 , could you please clone our `wix/Detox` repo?

See, there is an `detox/test` app with `e2e` folder.
Please reproduce your case, write a failing test, and submit it as a pull request.

Let's check that together.

**Comment by E1213180** [comment]
I beg your pardon, there is an action that can pull-to-refresh

`swipe('down', 'fast')`

found by looking at the E2Es 👍 

```
it(':ios: should swipe down until pull to reload is triggered', async () => {
    await element(by.id('ScrollView799')).swipe('down', 'fast');
    await expect(element(by.text('PullToReload Working!!!'))).toBeVisible();
  });
```

I'll close the issue

**Comment by noomorph** [comment]
Sounds legit, thanks for a deeper look into the codebase!
Sometimes tests can tell a lot about how to use a library, he-he.
Happy to know you've managed to find the solution.
