### ISSUE TITLE
how to import files outside src directory with absolute or relative path

### ISSUE THREAD

**Issue by sammysium** [wix/Detox#2360]
Perhaps what I want is bad idea but here it goes...in my __ tests __ directory, I have a helpers directory which I use to generate data and also have static data used in jest unit tests. In some classes I have mocked for detox (filename.e2e.js), I want to use those files but I can't import them at all. Currently I use absolute imports throughout the app and jest doesn't complain either.

the app structure is:
```

          app
              __mocks__
              __tests__
                   helpers/
                      package.json
                       user-data.js
              e2e
             src
               services
                 LService.js
                 LService.e2e.js
```
where package.json is:
```

              {
                    "name": "testhelpers"
               }

```
LService.e2e.js

          import { userData } from 'testhelpers/user-data' ;

          import { userData } from '../__tests__/helpers/user-data';

both don't work.

.detoxrc.js
```

{
  "testRunner": "jest",
  "runnerConfig": "e2e/config.json",
  "configurations": {
   
    "android.emu.debug": {
      "binaryPath": "android/app/build/outputs/apk/debug/app-debug.apk",
      "build": "cd android && ./gradlew app:assembleDebug assembleAndroidTest -DtestBuildType=debug && cd ..",
      "type": "android.emulator",
      "device": {
        "avdName": "myAvd"
      }
    }
  }
}
```

package.json

`  "jest": {
    "preset": "react-native",
    "coverageReporters": [
      "text",
      "cobertura",
      "lcov",
      "json"
    ],
    "moduleDirectories": [
      "node_modules",
      "src"
    ],
    "transform": {
      "^.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js"
    },
    "transformIgnorePatterns": [
      "node_modules/(?!((jest-)?react-native|@react-native-community/.*|react-navigation|react-navigation-drawer|@react-navigation/.*))"
    ],
    "setupFiles": [
      "./__mocks__/react-navigation.js",
      "./__mocks__/react-navigation-drawer.js",
      "./__mocks__/react-navigation-stack.js"
    ],
    "testTimeout": 8000
  }`

Anything I am missing?

**Comment by noomorph** [comment]
Jest and Babel question, you won't find help at Detox regarding this.

**Comment by sammysium** [comment]
oh okay...though yarn test does work well. thanks still.
