### ISSUE TITLE
reloadReactNative() is acting different from ios to android

### ISSUE THREAD

**Issue by vjmaiky** [wix/Detox#2361]
I have two tests:

describe('Example', () => {
  beforeEach(async () => {
    await device.reloadReactNative();
  });

  it('should have welcome screen', async () => {
    await Login.setUsername(username);
    await Login.setPassword(password);
    await Login.clickLogin();
  });

  it('second test', async () => {
    await Login.setUsername(username);
    await Login.setPassword(password);
    await Login.clickLogin();
  });

});

After each test on android app starts in login screen but on ios starts in next screen after login.
What i-m missing here? i assume that reloadReactNative() is acing different
p.s. i'm new to Detox so i'm in exploring phase.

Running on simulators: iphone 11 pro/x with ios 14/12.2, Android simulator with a9
"jest": "^26.4.2",
"jest-circus": "^26.4.2",
"detox": "^17.6.0",
"react-native": "~0.62.2",

**Comment by vjmaiky** [comment]
https://stackoverflow.com/questions/64043907/reloadreactnative-is-acting-different-from-ios-to-android

**Comment by vjmaiky** [comment]
@LeoNatan any suggestion here? (sorry to tag you but i'm struggling to understand why the difference)

**Comment by LeoNatan** [comment]
Maybe your app remembers the user has logged in on iOS.

**Comment by vjmaiky** [comment]
@LeoNatan indeed; i suppose that reload is somehow bringing the app to initial state (even if changes were made into it); thank you.
Since i got you here, one small extra question; i cannot start again the tests on Android if emulator is already open..i need to close it first and after that to start it again; any hint here?

**Comment by LeoNatan** [comment]
Sorry, not familiar with Android.
