### ISSUE TITLE
How to test in-app browsers? 

### ISSUE THREAD

**Issue by DanielDanaee** [wix/Detox#2366]
For example when i tap a button that opens up the browser, how can i validate the content of the browser to make sure the correct URL is loaded, if any, in the first place? 

Basically to check if the in-app browser opens up and the correct URL is shown.

**Comment by simistern** [comment]
hey @DanielDanaee , were you able to solve this? I am trying to do the same thing currently

**Comment by DanielDanaee** [comment]
@simistern this is the only update i have got so far: https://stackoverflow.com/questions/64103753/testing-in-app-browsers-with-detox-e2e-in-react-native?noredirect=1#comment114213705_64103753

**Comment by simistern** [comment]
ah true, thats also from me lol :)

**Comment by DanielDanaee** [comment]
@simistern haha what a small world

**Comment by sanduluca** [comment]
Did anyone solved this ?
