### ISSUE TITLE
Press triggered in place of LongPress

### ISSUE THREAD

**Issue by Andarius** [wix/Detox#2369]
**Describe the bug**

`longPress` does not trigger when using `LongPressGestureHandler` of **react-native-gesture-handler**

**To Reproduce**

- [x] I have tested this issue on the latest Detox release and it still reproduces

```
import {
    RectButton,
    LongPressGestureHandler,
    State
} from 'react-native-gesture-handler'

const Item: FC<{}> = function(){
    
    function onLongPress(){
        console.log('long press!')
    }

    function onPress(){
        console.log('press!')
    }

    return (
        <LongPressGestureHandler
            onHandlerStateChange={({ nativeEvent }) => {
                if (nativeEvent.state === State.ACTIVE) {
                    onLongPress()
                }
            }}
            minDurationMs={800}>
            <RectButton
                testID='item-0'
                onPress={onPress}>
            </RectButton>
        </LongPressGestureHandler>
    )
}
```

Steps to reproduce:
1. Run `await element(by.id('item-0')).longPress(3000)`

**Expected behavior**
`onLongPress` should be called instead of `onPress`

**Environment (please complete the following information):**
 - Detox: 17.6.1
 - React Native: 0.63.0
 - Node: 12.18.4
 - Device: Pixl API 28 AOSP
 - OS: Linux 4.15 KDE neon 5.19
 - Test-runner (select one): `jest-circus`

**Package.json**
```
"react-native-gesture-handler": "^1.8.0"
```

**Comment by d4vidi** [comment]
@Andarius thanks for this. I'm surprised to see this type of an error - usually it's the other way around: a tap registered as a long tap. Sorry to ask the obvious: Does this code work _without_ automation, at all? In Detox, for this use case, we simply resort to `Espresso`'s implementation, as-is - which _should_ work.
Last but not least, be advised that the press-length (`3000`) or whatever argument has no effect on Android.

**Comment by Andarius** [comment]
Hey @d4vidi . Yes it works without automation:
![video](https://user-images.githubusercontent.com/5070712/94623424-6eba3d00-02b4-11eb-9d26-951d1b7b0414.gif)

**Comment by Andarius** [comment]
Still not working with the latest Detox version (17.13.1)

**Comment by Andarius** [comment]
Somehow, setting the minDurationMs to <= 650 will trigger the longPress, but any value above will trigger randomly
