### ISSUE TITLE
Cucumber support

### ISSUE THREAD

**Issue by heuism** [wix/Detox#237]
Hi guys, just wonder that do you guys have a plan to support cucumber for detox as well? it would be much nicer and easy to maintain the code in my opinion.

Thanks

**Comment by AlanFoster** [comment]
@heuism Is this something you have tried to get working? 🤔 

I can't see anything that would stop detox working with cucumber's step definitions out of the box

**Comment by rotemmiz** [comment]
Hey @heuism , there's no plan currently to support Cucumber, we will not stop you from adding one though :wink:

**Comment by heuism** [comment]
Haha @rotemmiz, that is just my idea of working with cucumber for better code reuse. I wonder would this supported by cucumber and gherkin or not. I will try 👍  and add in if i can :)

**Comment by mfrachet** [comment]
I managed to make it work quite easily. Will put hands deeper and provide you a feedback / guide

**Comment by mfrachet** [comment]
Let's take a show on : https://github.com/mfrachet/detox-example/commit/f71646d874d3dfa9ea9c4bc7ce1812e7dedf7ab1

Let me know if any documentation would be helpful concerning the subject :)

**Comment by AlanFoster** [comment]
Looks really nice @mfrachet :+1:

**Comment by heuism** [comment]
@mfrachet looks pretty good. So would this be an enhancement in the future, or would this already working with Cucumber?

Thanks for spending looking at this

**Comment by mfrachet** [comment]
It's actually working on Detox 5.6.x . Didn't tried on 5.7. But, as you can run detox with, you can run detox with cucumber out of the box. It's not an enhancement, just a switch of test runner :)

**Comment by maxkomarychev** [comment]
Approach mentioned by @mfrachet works with small issue: 

```
(node:2368) DeprecationWarning: cucumber: defineSupportCode is deprecated. Please require/import the individual methods instead.
```

@LeoNatan is there any specific reason of relying only on jest/mocha rather than being test-engine agnostic?

**Comment by rotemmiz** [comment]
detox-cli supports mocha and jest, but the library itself is indeed test runner agnostic, you will need to pass the command line params to it directly.

**Comment by petrogad** [comment]
@mfrachet can you provide an example of what it looks like executing this test on the command line through detox please?

**Comment by petrogad** [comment]
Would love to see this as a working example. I followed the repo from @mfrachet and am getting errors of `Path must be a string. Received`. I'm certain there is a step i'm missing; would love an outline showing this.

As soon as I stumble upon how to do it i'll happily post it up for future people!

**Comment by evanjmg** [comment]
yes, please share!

**Comment by evanjmg** [comment]
@tomatobrown  can you please share?

**Comment by tomatobrown** [comment]
Sorry, I haven't had much time to put things together (I also am having some trouble with xcode).  I started to put together the demo-cucumber project.  This should be enough to get you started, although it doesn't have any working tests yet.  https://github.com/tomatobrown/Detox/tree/cucumber-demo

**Comment by tomatobrown** [comment]
Sorry @AntaninaKaltsova I don't know what e2e/config.json you're talking about, are you unable to get the example working?

**Comment by AntaninaKaltsova** [comment]
@tomatobrown Unfortunately not, what command should I use to run scenarios?

**Comment by tomatobrown** [comment]
```
cd demo-react-native-cucumber 
configuration="ios.sim.release" node ../node_modules/cucumber/bin/cucumber-js
```

**Comment by AntaninaKaltsova** [comment]
Hi again! @tomatobrown it works, thank you! 
Could you please clarify -  what if I want to put the feature files in the 'e2e' folder (so the path feature files will be 'e2e/features/')? How to run tests in this case? Using your command I got: 

`0 scenarios
0 steps
0m00.000s
`

**Comment by Srutherford2407** [comment]
I am looking to dive into this and willing to add some examples for the cucumber test. I had a question regarding the how to run detox with the cucumber set up. Getting Detox test to look for cucumber IE the feature files etc to run. I think that was @AntaninaKaltsova question.

**Comment by Srutherford2407** [comment]
I actually figured this out, I will post a link to the updated example using Cucumber and Detox.

The only thing it is currently missing is the console print log that you currently see for the `it` statements for the `Given, When, Then`

**Comment by Srutherford2407** [comment]
@AntaninaKaltsova @byronpople  @evanjmg 
Added an example for cucumber with IOS Native
https://github.com/Srutherford2407/Detox-Cucumber-Example

**Comment by LeoNatan** [comment]
Closing old issues. I think it's best to have this as a community support, as supporting Cucumber directly is out of scope for the project.
