### ISSUE TITLE
device.getUiDevice().pressKeyCode method does not work.

### ISSUE THREAD

**Issue by stevesuyao** [wix/Detox#2381]
**Describe the bug**

There is a bug in https://github.com/wix/Detox/blob/master/detox/src/android/espressoapi/UIDevice.js#L153-L180

If you want to use `device.getUiDevice().pressKeyCode` method as below, 
```js
  const uidevice = device.getUiDevice();
  await uidevice.pressKeyCode(24);
```
It will give you an error "**keyCode should be a number, but got [object Object] (object)**".

**To Reproduce**

- [x] I have tested this issue on the latest Detox release and it still reproduces

**Environment (please complete the following information):**
 - Detox: 17.7.1
 - React Native: 0.61.5
 - Node: 12.18.3
 - Device: android 10 Essential PH-1
 - OS: Ubuntu 16.04
 - Test-runner (select one): `jest-circus` 

**Solution:**
The bug is caused by an incorrect `arguments` length condition and reusage. Please change the `pressKeyCode` method as below: 
```js
  static pressKeyCode(element, keyCode) {
    function pressKeyCode1(element, keyCode) {
      if (typeof keyCode !== "number") throw new Error("keyCode should be a number, but got " + (keyCode + (" (" + (typeof keyCode + ")"))));
      return {
        target: element,
        method: "pressKeyCode",
        args: [{
          type: "Integer",
          value: keyCode
        }]
      };
    }

    function pressKeyCode2(element, keyCode, metaState) {
      if (typeof keyCode !== "number") throw new Error("keyCode should be a number, but got " + (keyCode + (" (" + (typeof keyCode + ")"))));
      if (typeof metaState !== "number") throw new Error("metaState should be a number, but got " + (metaState + (" (" + (typeof metaState + ")"))));
      return {
        target: element,
        method: "pressKeyCode",
        args: [{
          type: "Integer",
          value: keyCode
        }, {
          type: "Integer",
          value: metaState
        }]
      };
    }

    if (arguments.length === 1) throw new Error("keyCode should not be null.");

    if (arguments.length === 2) {
      return pressKeyCode1.apply(null, arguments);
    } 

    return pressKeyCode2.apply(null, arguments);
  }

```
I know the original code was auto-generated from the Android source file, then something went wrong in the `generation` sub-project. I have not got a chance to check it.

**Comment by d4vidi** [comment]
Thanks for this. Indeed, this code is auto-generated. We'll have to dig deeper.

**Comment by stevesuyao** [comment]
> Thanks for this. Indeed, this code is auto-generated. We'll have to dig deeper.
> In the meantime, just a lucky guess... does `pressKeyCode(null, 24)` work?

Thanks for replying. 
No, `device.getUiDevice().pressKeyCode(null, 24)` will not work. 
The arguments are actually passed through `UiDeviceProxy`
https://github.com/wix/Detox/blob/master/detox/src/android/espressoapi/UiDeviceProxy.js#L12-L21
```js
...
const call = target[prop](invoke.callDirectly(uiAutomaton.uiDevice()), ...params)
...
```
