### ISSUE TITLE
Signal 11 was raised - native iOS crash when testing with Detox

### ISSUE THREAD

**Issue by JB-CHAUVIN** [wix/Detox#2384]
### Description
Hello, when my test is being executed, I have a "Signal 11 was raised" native iOS crash.
I don't understand this error, and I have no additional informations in the RN console or 

- [OK] I have tested this issue on the latest Detox release and it still reproduces

#### Screenshots
![image](https://user-images.githubusercontent.com/8957878/94835404-f4073400-0411-11eb-9737-0f1e7a007c8b.png)

#### Environment (please complete the following information):
 - Detox:17.7.1
 - React Native: 0.63.3
 - Node: 12
 - Device: Any iOS simulator
 - Xcode: 12.2
 - iOS: 12.4 or 14
 - macOS: Latest

### Logs
[stack.txt](https://github.com/wix/Detox/files/5313431/stack.txt)

Thanks for the great work

**Comment by LeoNatan** [comment]
Hmm, this is some special case we are not familiar with. Do you have a MapView visible? It seems rendering it is causing a crash. I will investigate.

**Comment by JB-CHAUVIN** [comment]
Hello @LeoNatan I can confirm you that the MapView is causing the crash.
I removed it and the test is fine.
So it might be a bug with the MapView.

**Comment by LeoNatan** [comment]
Fixed

**Comment by russelRajitha** [comment]
I facing this issue. how to make it work with maps? and I saw another issue with same thing which says caused by firebase notifications. is there any solution for this?
