### ISSUE TITLE
Getting Started in pt-BR

### ISSUE THREAD

**Issue by jhonatasmatos** [wix/Detox#2387]
There are a lot of people using detox in Brazil but there are other people that would like to use it and They don't understand English.

We thought about translating the part of "Getting Started" for They to start using detox

So we’ve been working on this translation to help the community

Can We open a PR with this content ?

![Screen Shot 2020-10-02 at 23 50 44](https://user-images.githubusercontent.com/16242029/94981640-2431fe00-050a-11eb-8403-d183b2997b78.png)

**Comment by LeoNatan** [comment]
Hello,

Thank you for your offer!
Unfortunately, this is not something we can maintain in the long run (we are strained maintaining the English documentation). I think this effort would be better spent in creating a blog post or a website, and spreading it in your community. We can then link to that page. 

Thanks
