### ISSUE TITLE
expect(...).toBeVisible is not a function

### ISSUE THREAD

**Issue by noomorph** [wix/Detox#2390]
### Description

After upgrading to `jest@26.5.x` and `jest-circus@26.5.x`, all Detox tests began failing with:

```
TypeError: expect(...).toBeVisible is not a function
```

#### Expected behavior

Detox should initialize its global variables correctly, i.e.: Jest's `expect` should not shadow the Detox's `expect`.

#### Actual behavior

`CustomDetoxEnvironment` sets Detox globals and matchers including `this.global.expect`, but then, a few moments later the Detox's expect gets overwritten with Jest's one.

#### Screenshots

![image](https://user-images.githubusercontent.com/1962469/95107205-44e49880-0742-11eb-969e-30623264fcbf.png)

See: https://github.com/facebook/jest/pull/10484

**Comment by noomorph** [comment]
# Temporary solution

Lock your `jest` and `jest-circus` dependencies to `26.4.x`, [like demonstrated here:](https://github.com/wix/Detox/commit/1f2ca2db1f60db4089576b6efd0267b1bdd2d3f0#diff-46a457fc0b89ad23fe280438612f4e4cL36-L37)

![image](https://user-images.githubusercontent.com/1962469/95107641-db18be80-0742-11eb-8af0-e8a23c6b2b43.png)

**Comment by LeoNatan** [comment]
Can we catch this and throw an error?

**Comment by noomorph** [comment]
Catch what and which error do you want to throw, could you elaborate pls? I'll check in the morning

**Comment by LeoNatan** [comment]
If jest is above the version we support.
