### ISSUE TITLE
Add link Getting Started in pt-br

### ISSUE THREAD

**Issue by jhonatasmatos** [wix/Detox#2400]
Hello, 
According to issue #2387

We wrote an article in Portuguese with all the steps to install and configure the detox
https://medium.com/quia-digital/iniciando-com-detox-framework-1-4-ce31ad7ae812

Is it possible to add it to getting started to help other people?

**Comment by LeoNatan** [comment]
I’ll add it soon. Thank you!

**Comment by jhonatasmatos** [comment]
Thank you very much !

**Comment by LeoNatan** [comment]
Added
