### ISSUE TITLE
{question} cannot .tab on button

### ISSUE THREAD

**Issue by nicasioNCG** [wix/Detox#2401]
<Button
        title="Next"
        theme="primary"
        onPress={onNextStep}
      />

it('Screen 2 after .tab on get started button', async () => {
    await element(by.text('Get Started')).tap();
    expect(element(by.text('How it works'))).toBeVisible;
    expect(element(by.text('The alarm system for your loved ones’ finances.'))).toBeVisible;
    expect(element(by.text('Carefull examines every transaction and when we find something, we let you know immediately.'))).
    toBeVisible;
    await waitFor(element(by.text('Next'))).toBeVisible().withTimeout(200); 
    await element(by.text('Next')).tap();
  });

this line await element(by.text('Next')).tap(); is executed but next screen is not displayed 

what am i doing wrong ?

**Comment by d4vidi** [comment]
@nicasioNCG please post back a link to this question on stackoverflow with more info such as the OS, device platform, etc and we'll try to help you there. Thanks!

**Comment by nicasioNCG** [comment]
@d4vidi perfecto/perfect!
