### ISSUE TITLE
App has not responded to the network requests below:   (id = -1000) isReady: {}  Unresponded network requests might result in timeout errors in Detox tests.

### ISSUE THREAD

**Issue by thetin95** [wix/Detox#2402]
detox[7718] ERROR: Error: Exceeded timeout of 300000ms while handling jest-circus "setup" event
detox[7718] INFO:  Example is assigned to undefined
detox[7718] INFO:  Example: should have welcome screen
detox[7718] INFO:  Example: should have welcome screen [SKIPPED]

detox[7718] ERROR: DetoxRuntimeError: Aborted detox.init() execution, and now running detox.cleanup()

HINT: Most likely, your test runner is tearing down the suite due to the timeout error
detox[7718] WARN:  [Client.js/PENDING_REQUESTS] App has not responded to the network requests below:
  (id = -1000) isReady: {}

Unresponded network requests might result in timeout errors in Detox tests.

macOS version: 10.15.6
Xcode version: 11.7
detox version : 17.8.3

thanks

**Comment by jan-miksik** [comment]
In my case works change connection type on emulator Setup(three dots) Settings > Proxy > No proxy
testing on android

**Comment by jovanialferez** [comment]
in my case, i have to drop `react-native-splash-screen` and `react-native-progress`

**Comment by MoeMamdouh** [comment]
I had the same issue in iOS **release** build event it was working in **debug** build 
my current react native version `"react-native": "0.61.5"`



i fix it by add in info.plist file

```
<key>NSAllowsArbitraryLoads</key>
<true/>
```
which is added by default since react-native version 0.64

**Comment by Vladislava9009** [comment]
What was the solution?

**Comment by thetin95** [comment]
> What was the solution?

In my case. I disabled the splash screen.
