### ISSUE TITLE
Swipe left is not working

### ISSUE THREAD

**Issue by DanielEliraz** [wix/Detox#2424]
### Description
I'm using RNUILib [Drawer](https://wix.github.io/react-native-ui-lib/docs/Drawer) with left and right items.
I'm using `kompot` to test it. The swipe right works perfect but it cannot make the swipe left.

- [x] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

1. clone https://github.com/wix-private/wix-one-app-notifications
2. checkout delete-notification branch
3. run npm test

#### Expected behavior
The delete [test](https://github.com/wix-private/wix-one-app-notifications/blob/f8724a44df2edef29d90624a7c61454803c06d37/kompot/NotificationList.kompot.spec.js#L47) should do the swipe left

#### Screenshots
[movie](https://drive.google.com/file/d/1ZObvRc2XuBCWOhVbBiNEEY7qSVOs3f2P/view?usp=sharing), the first 2 tries are detox tests, then I stopped the test and showed that I can do it manually

#### Environment (please complete the following information):
 - Detox: 17.10.0
 - React Native: 0.62.2
 - Node: 12.16.3
 - Device: iphone 11
 - Xcode: 12.0
 - iOS: 14.0
 - macOS: 10.15.6

**Comment by LeoNatan** [comment]
@DanielEliraz What view are you passing to swipe? It looks like you are passing some small view on the left.

**Comment by LeoNatan** [comment]
Look at your test. You are swiping the unread indicator. How do you expect that to be swiped any further left?
