### ISSUE TITLE
Add offsetPositionX and offsetPositionY to `swipe(direction, speed, percentage)`

### ISSUE THREAD

**Issue by rotemmiz** [wix/Detox#2428]
One use case: Trying to swipe a fullscreen scrollviews with header on top it, to trigger reload, will fail.
Detox tries to swipe from to farthest position possible, so that the swipe will be maximal.

We want to add `offsetPositionX` and `offsetPositionY` to both platforms to mitigate such issues.

**Comment by LeoNatan** [comment]
I’d like us to also consider changing all our legacy x/y APIs to be normalized x/y (percentage of view instead of points). I think tap is the only one that remains with this. Perhaps phase it over several releases?

**Comment by LeoNatan** [comment]
@rotemmiz @d4vidi ^

**Comment by noomorph** [comment]
Unblocks CollapsingHeader tests in https://github.com/wix-private/mobile-guild/issues/169

**Comment by noomorph** [comment]
Resolved by #2432.
