### ISSUE TITLE
Improve `atIndex()` failure message (matches 1th view)

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#2430]
**Describe the bug**
Improve failure message associated with the `atIndex()` API:

```
Test Failed: No views in hierarchy found matching: matches 1th view.
```

Associated action:
```
await element(by.text('Remove')).atIndex(1).tap();
```

**Expected behavior**
Need to come up with a more descriptive message.

cc @rotemmiz @yoavtsook2806

**Comment by LeoNatan** [comment]
Every time I see that string, I crack up.

**Comment by vjmaiky** [comment]
Is there any workaround for it? it happens also if you have ID + index.
Already applied waitfor as pointed here: https://stackoverflow.com/questions/53945431/error-error-no-views-in-hierarchy-found-matching-with-tag-value-is-email
