### ISSUE TITLE
Missing Android consumer proguard rules

### ISSUE THREAD

**Issue by GEllickson-Hover** [wix/Detox#2431]
**Describe the bug**
We started using shrinking/obfuscation for our java code by setting `minifyEnabled true` in our `build.gradle`. We build release builds for testing with the command shown [here](https://github.com/wix/Detox/blob/master/docs/Introduction.Android.md#2-apply-detox-configuration) via `./gradlew assembleRelease assembleAndroidTest -DtestBuildType=release`. In your docs you mention adding your proguard file shown [here](https://github.com/wix/Detox/blob/master/detox/android/detox/proguard-rules-app.pro), but that doesn't seem to be enough to test on minified builds, and either our the app will crash in tests or Detox will log errors and tests will fail. 

First, we were experiencing immediate crashes when running tests from Exceptions relating to missing classes. There is an existing issue with Android Instrumentation testing in general when minified, so Slack made a plugin called [Keeper](https://slackhq.github.io/keeper/) to address this for now. The short explanation is that Detox relies on some dependencies in the main app apk like Kotlin and React-Native that the test apk is then not able to find at runtime. They are being removed from the main apk during the shrinking process because the main app is not using those classes. This plugin analyzes test code and adds Proguard rules for the main app for classes the test apk relies on. That's a separate issue, but just noting as it's not mentioned in your docs as potential watch-out.

That fixed some crashes, but your library also uses reflection in a number of your classes, and the compiler cannot know what classes you're trying to use dynamically, so they could get removed or obfuscated. We then need additional proguard rules that don't seem to be in your `proguard-rules-app.pro` file. For example, we were using react-native `0.63.2` and Detox `17.6.1`, and we see several errors like this when running tests on minified builds: 

```
E Detox   : Can't set up RN UIModule listener
E Detox   : org.joor.ReflectException: java.lang.NoSuchFieldException: mOperationsQueue
E Detox   : 	at org.joor.Reflect.field0(Reflect.java:310)
E Detox   : 	at org.joor.Reflect.field(Reflect.java:282)
E Detox   : 	at com.wix.detox.reactnative.idlingresources.UIModuleIdlingResource.isIdleNow(UIModuleIdlingResource.java:84)
E Detox   : 	at androidx.test.espresso.base.IdlingResourceRegistry.allResourcesAreIdle(IdlingResourceRegistry.java:268)
E Detox   : 	at androidx.test.espresso.base.IdlingResourceRegistry$6.isIdleNow(IdlingResourceRegistry.java:302)
E Detox   : 	at androidx.test.espresso.base.UiControllerImpl.loopMainThreadUntilIdle(UiControllerImpl.java:453)
E Detox   : 	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:275)
E Detox   : 	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:272)
E Detox   : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E Detox   : 	at android.os.Handler.handleCallback(Handler.java:790)
E Detox   : 	at android.os.Handler.dispatchMessage(Handler.java:99)
E Detox   : 	at android.os.Looper.loop(Looper.java:164)
E Detox   : 	at android.app.ActivityThread.main(ActivityThread.java:6494)
E Detox   : 	at java.lang.reflect.Method.invoke(Native Method)
E Detox   : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E Detox   : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E Detox   : Caused by: java.lang.NoSuchFieldException: mOperationsQueue
E Detox   : 	at java.lang.Class.getField(Class.java:1601)
E Detox   : 	at org.joor.Reflect.field0(Reflect.java:295)
E Detox   : 	... 15 more
```

I was able to fix some of these just by adding Proguard rules to our main app to just keep all of certain packages as I didn't know all the classes you might use reflection on.

```
-keep class com.facebook.react.modules.** { *; }
-keep class com.facebook.react.animated.** { *; }
-keep class com.facebook.react.uimanager.** { *; }
```

However, today we tried upgrading to `17.10.3` as there are new features and that led to a new crash:

```
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: to.hover.android.app, PID: 26450
    org.joor.ReflectException: org.joor.ReflectException: java.lang.NoSuchFieldException: mTasks
        at org.joor.Reflect.field(Reflect.java:286)
        at com.wix.detox.reactnative.idlingresources.SerialExecutorReflected.pendingTasks(SerialExecutorReflected.kt:14)
        at com.wix.detox.reactnative.idlingresources.SerialExecutorReflected.hasPendingTasks(SerialExecutorReflected.kt:9)
        at com.wix.detox.reactnative.idlingresources.AsyncStorageIdlingResource$idleCheckTaskImpl$1.run(AsyncStorageIdlingResource.kt:39)
        at com.reactnativecommunity.asyncstorage.AsyncStorageModule$g$a.run(AsyncStorageModule.java:1)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: org.joor.ReflectException: java.lang.NoSuchFieldException: mTasks
        at org.joor.Reflect.field0(Reflect.java:310)
        at org.joor.Reflect.field(Reflect.java:282)
        at com.wix.detox.reactnative.idlingresources.SerialExecutorReflected.pendingTasks(SerialExecutorReflected.kt:14) 
        at com.wix.detox.reactnative.idlingresources.SerialExecutorReflected.hasPendingTasks(SerialExecutorReflected.kt:9) 
        at com.wix.detox.reactnative.idlingresources.AsyncStorageIdlingResource$idleCheckTaskImpl$1.run(AsyncStorageIdlingResource.kt:39) 
        at com.reactnativecommunity.asyncstorage.AsyncStorageModule$g$a.run(AsyncStorageModule.java:1) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.lang.NoSuchFieldException: mTasks
        at java.lang.Class.getField(Class.java:1601)
        at org.joor.Reflect.field0(Reflect.java:295)
        at org.joor.Reflect.field(Reflect.java:282) 
        at com.wix.detox.reactnative.idlingresources.SerialExecutorReflected.pendingTasks(SerialExecutorReflected.kt:14) 
        at com.wix.detox.reactnative.idlingresources.SerialExecutorReflected.hasPendingTasks(SerialExecutorReflected.kt:9) 
        at com.wix.detox.reactnative.idlingresources.AsyncStorageIdlingResource$idleCheckTaskImpl$1.run(AsyncStorageIdlingResource.kt:39) 
        at com.reactnativecommunity.asyncstorage.AsyncStorageModule$g$a.run(AsyncStorageModule.java:1) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
```

It appears that another class `AsyncStorageIdlingResource` was added that uses reflection on the `com.reactnativecommunity.asyncstorage.AsyncStorageModule` class from another library we use.

**My ask then is can you provide the necessary proguard rules for any case in which you use reflection?** It's important for us to be able to test on minified builds, and it's difficult and unsustainable for us to look through your code and figure our these rules ourselves and things could still break when you add something new with reflection in between upgrades, like happened with us. These rules can just be included in your `proguard-rules-app.pro` file or at least suggestions for rules in your docs. Thank you.

**Comment by noomorph** [comment]
@d4vidi .

**Comment by d4vidi** [comment]
@GEllickson-Hover thanks for using Detox and for your patience.

First, it is reasonable that adding the rules you've mentioned regarding RN modules would fix the error you specified. However, what I don't understand is - how on earth there's an app which minification strips RN down so hard that it omits RN's very core components? Things like the `UIImplementation.mOperationsQueue` are the fundamentals of RN. Apps simply cannot work without them. This is the reason why rules such as the ones you've suggested are not bundled into Detox' progurad rules to begin with: because they pretty much state the obvious.

Moreover, as a part of our regression process, we regularly execute simple e2e tests on a lean RN app we've created (aka the Detox example app), which is built and minified using the standard proguard rules - as mentioned in guides. The app runs on works well with rules as I explained.

_That said, I don't mind adding the rules you suggestion, of course - and so I will. Although, you must understand why I'm utterly surprised by the use case you've reported. I would love to get insight as to why there are differences between our test app and your app._

Second, I sort of understand what might cause the 2nd error you've mentioned. It seems you've bundled the community's AsyncStorage module into your app as a native dependency. Is it possible that nevertheless, you're using the one provided by React Native itself, instead? Namely, import the module from ReactNative's `NativeModules` instead of directly from the community, like so:
```js
import AsyncStorage from '@react-native-community/async-storage'
```
_In any case, I will add the module in much the same way to the detox example app, and export the necessary rules, accordingly_.

Thanks

**Comment by GEllickson-Hover** [comment]
@d4vidi Thank you, I really appreciate the response. 

In regard to minification of RN Core components like `UIImplementation.mOperationsQueue`, I believe it's not that they are getting stripped in the build process and no longer exist, but rather that they get obfuscated, so the names are just shorter and harder to decode. Reflection requires strict field names, so the code is actually there under a different name such as `A.b`, but the hardcoded class / method name strings in the reflective code won't be dynamically re-written, so they fail at runtime. Shrinking isn't our only goal as large enough native Android apps typically also want to add obfuscation as an extra hurdle against reverse-engineering.

If I'm looking at the correct detox example app, it looks like obfuscation is turned off [with this rule](https://github.com/wix/Detox/blob/master/examples/demo-react-native/android/app/proguard-rules.pro#L6), which would seem to explain why you might not have encountered some of these issues.

One could argue that we don't need to obfuscate RN code, but with R8/Proguard it's more of an opt-out approach, so by default everything gets obfuscated once enabled, and it's a manual procedure to figure out what to keep and to write rules. Because of this, I feel it's generally been the native Android standard that libraries explicitly publish what they need to be kept if there's reflection (since reflection is the exception, not the norm), expecting that there could be both shrinking and obfuscation, so developers won't have to worry about runtime errors. React Native does bundle their own keep rules [here](https://github.com/facebook/react-native/blob/master/ReactAndroid/proguard-rules.pro), and these rules seem to imply that classes like `UIImplementation` are okay to be obfuscated in normal use cases.

I've since forgotten some of the context behind the `AsyncStorageIdlingResource` issue, but generally just seems again like a case of the obfuscation process shortening the class and field names and reflection then failing because of the mismatch in names.

In any case, I much appreciate the attention and potentially added keep rules as I know this is a more nuanced case.

**Comment by d4vidi** [comment]
So this is turning out to be quite an eye opener -- indeed, we were not properly compliant with obfuscating apps! I will have that worked out asap. Thank you!
