### ISSUE TITLE
Build successful but tests not launch 

### ISSUE THREAD

**Issue by julienqueffelec** [wix/Detox#2433]
Hey,

When i launch test on android i got :

`detox[12144] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=testee not connected, cannot fw action (sessionId=51fa6166-4dbf-db60-da2a-6c2bd608a55b)`

I tried the fix for this (https://github.com/wix/Detox/blob/master/docs/Introduction.Android.md#6-enable-clear-text-unencrypted-traffic-for-detox) but didn't work

My current build.gradle (i already tried 28 for targetSdkVersion)
`ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
    }`

Environment:
 - Detox: 17.10.3
 - React Native: 0.63.2
 - Device: Pixel 3
 - OS:  Pie
 - Test-runner: jest-circus

Thanks guys!

**Comment by barak109** [comment]
Same

**Comment by jaydgoss** [comment]
Seeing the same issue on iOS

Detox: 17.11.1
React Native: 0.62.2
Device: iPhone 11 - 14.1
Test-runner: jest-circus

**Comment by d4vidi** [comment]
Hey sorry - no ability to help without detox *and* device logs.
