### ISSUE TITLE
Android: Add command line argument option for enabling -read-only

### ISSUE THREAD

**Issue by j320** [wix/Detox#2441]
**Is your feature request related to a problem? Please describe.**
When attempting to run tests in parallel using test runners other than jest-circus, this is not possible due to the concurrent emulators not being launched on -read-only. 

**Describe the solution you'd like**
I've seen that there's already a flag for _readOnlyEmu_, if this could also be passed as a command line argument, that would give more flexibility for enabling running concurrent emulators using Detox.

**Describe alternatives you've considered**
I tried using the _--device-launch-args_ command line argument but it's not passing the arguments entered.

**Comment by d4vidi** [comment]
@j320 you are right. We plan on making `-read-only` the default for emulators, eventually. In the meantime, could you first kill all running emulators before running detox? The easiest way to do so on a Mac/Linux that I know is this:
```sh
killall qemu-system-x86_64 || true
killall qemu-system-x86_64-headless || true
```
