### ISSUE TITLE
Stop process and exit with error code 1 on fail

### ISSUE THREAD

**Issue by isnifer** [wix/detox#245]
#### Description
```
detox-server info 12:36:32: server listening on localhost:50682...
(node:39340) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: app binary not found at '/Users/admin/builds/999529a4/0/tipsi_frontend/tipsi-react-app/ios/build/Build/Products/Release-iphonesimulator/tipsi.app', did you build it?
(node:39340) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Currently, detox doesn't fail. This freezes our CI server. For now, I always need to check that tests have successfully started.

#### Steps to Reproduce
Run detox with incorrect binary path

#### Node, Device, Xcode and macOS Versions
No matter

**Comment by rotemmiz** [comment]
How do you run detox ? What command do you type?

I'm running `detox test -c ios.sim.release` on Node 8.1.2, with a wrong path in my config `binaryPath: wrong/path` and it fails instantly.

**Comment by isnifer** [comment]
@rotemmiz good question.
I have next command:
```json
"test:ios-detox": "INSTRUMENT=detox tape -r ./__tests__/e2e/setup ./__tests__/e2e/runner",
```
#### Setup contains next files:
```js
require('babel-register')({
  plugins: [['tipsi-flavors', { env: 'APP_ID' }]],
  ignore: /node_modules\/(?!tipsi_api)/,
  cache: false,
})
require('babel-polyfill')
```
and
```js
import ignore from 'require-ignore'

ignore.install(['png'])
```

#### Runner contains next files:
```js
// runnerDetox.js
import tape from 'tape'
import tapDiff from 'tap-diff'
import detox from 'detox'
import pkg from '../../../package.json'
import runTestSuites from '../suites'

function waitTapeFinish() {
  return new Promise(resolve => tape.onFinish(resolve))
}

export default async function runnerDetox() {
  await detox.init(pkg.detox)

  tape.createStream()
    .pipe(tapDiff())
    .pipe(process.stdout)

  runTestSuites()

  await waitTapeFinish()

  await detox.cleanup()

  process.exit(0)
}
```

So, `suites` - it's only an `Array<string>` with filenames of test suites

**Comment by MoOx** [comment]
For my concern I had to add "--exit" in mocha.opts to get a proper exit at the end of successful tests.

**Comment by rotemmiz** [comment]
Controlling the process lifecycle and exit codes is the job of a test runner, Detox is not a test runner. Test runners can either exit on the first error or continue running all tests and report on an error at the end, If we deliberately call `exit(1)` inside detox, it will break the test runner's lifecycle, and exit anyway.

**Comment by MoOx** [comment]
Any idea why "something" is still open? For example jest (and I guess mocha is doing the same) are not exiting automatically because there is still something runing. Adding things like --exit is forcing the runner to exit, but it should be natural...
