### ISSUE TITLE
Suggestion: withSibling() to avoid strange traversal + more intuitive than Ancestor/Descendant

### ISSUE THREAD

**Issue by jpoisch** [wix/Detox#2453]
**Is your feature request related to a problem? Please describe.**
First I'd like to say that **withAncestor()** and **withDescendant()** do work. They select the current node's (grand)parents or (grand)childen.
My suggestion is to create a **withSibling()** to avoid frustration when trying to select a specific node by its id/text and a sibling of that same node (not a parent or child). Here is a simple example:
```
<View>
  <Text>Foo</Text>
  <Button>SameText</Button>
</View>
  ...
<View>
  <Text>Bar</Text>
  <Button>SameText</Button>
</View>

In step file:
element(by.text('SameText').withSibling(by.text('Bar'))).tap();
```

**Describe the solution you'd like**
Thinking about it from an xpath perspective, it would essentially be the detox equivalent to 'following-sibling' and 'preceding-sibling'. I do not want to go up or down the "tree". I want to look at the specified node, and only select it if it has a specified sibling.
[https://www.w3schools.com/xml/xpath_axes.asp](url)

**Comment by LeoNatan** [comment]
Hello,

I'll be frank here; I'm inclined to refuse this. Ancestor and descendant quaries are already edge cases that should be avoided unless absolutely necessary. This proposal is even more esoteric in my eyes (first time someone has requested it in 4+ years). Coupled with the fact that XCUITest, which we want to main some compatibility with on iOS, lacks this functionality, and I just don't think this is worth the effort. The goto solution should be to put a **unique** identifier to each button, and then you can target it directly, without needing any of the `-with*()` query extensions.
