### ISSUE TITLE
Artifacts are not being collected on timeouts

### ISSUE THREAD

**Issue by rotemmiz** [wix/Detox#2457]
**Describe the bug**
When an action is not being completed due to app busyness (infinite animation, network request), and the test times out, artifacts are not being collected. 

**Environment (please complete the following information):**
 - Detox: *
 - Test-runner: jest-circus

**Comment by d4vidi** [comment]
@noomorph can this still be applicable?

**Comment by noomorph** [comment]
I think yes.
