### ISSUE TITLE
Unable to run tests in parallel

### ISSUE THREAD

**Issue by LouiseBC** [wix/Detox#2462]
In short: I seem to be having the same issue as in #2004:
I've been trying to run tests on 2 devices in parallel. I start both emulators prior to running any commands, but after doing so I only see activity on one device. Although my examples below are for android, I have the same issue for iOS. The documentation is a little sparse on how to set up parallelism -- are there any working config examples around?

**Test command**
```
detox test --configuration android.emu.debug --workers 2
```

**package.json**
```
  "android.emu.debug": {
        "binaryPath": "android/app/build/outputs/apk/normalTst/debug/app-normal-tst-debug.apk",
        "build": "cd android && ./gradlew assembleNormalTstDebug assembleAndroidTest -DtestBuildType=debug && cd ..",
        "type": "android.attached",
        "device": {
          "adbName": ".*"
        }
      },
```

**Comment by LouiseBC** [comment]
☝️ why is it an option to open an 'I need help with Detox' issue if you're going to close it immediately?

This is possibly a lack of documentation or a bug, so I'd appreciate it I could keep it open! :)

**Comment by noomorph** [comment]
@LouiseBC, if you want to report a lack of documentation or a bug, then report that as a separate dedicated ticket.
Detox issue policy is described here: https://github.com/wix/Detox/issues/1305
