### ISSUE TITLE
scroll() Commands Crash iOS Simulator

### ISSUE THREAD

**Issue by AlexK777** [wix/Detox#2465]
### Description
On certain views throughout our application, when we use the `scroll()` functions the iOS simulator freezes/crashes and the tests fail. 

One specific example:
```
        await waitFor(element(by.text(targetTime)))
            .toBeVisible()
            .whileElement(by.id(reservationTimeScroll))
            .scroll(200, 'down');
```

- [x] I have tested this issue on the latest Detox release and it still reproduces

#### Expected behavior
Detox scrolls through the ScrollView until element is found.

#### Environment (please complete the following information):
 - Detox: 17.11.2 (I tried installing 17.11.3 but yarn said that wasn't a valid version)
 - React Native: 0.63.3
 - Node: 10.22.1
 - Device: iOS Simulator - iPhone 11
 - Xcode: 12.1
 - iOS: 14.1
 - macOS: Catalina 10.15.6

#### If you are experiencing a timeout in your test
- [x] I have followed the instructions under [Lower-level Idling Resources Debug](https://github.com/wix/Detox/blob/master/docs/Troubleshooting.Synchronization.md#lower-level-idling-resources-debug-ios-only) and am providing the log below:
I know the simulator is crashing, but here is where it hangs in these logs
```
2020-11-12 13:05:47.249 Db hyvee.grocery[45678:28dd43] [com.wix.Detox:EarlGreyStatistics] WXAnimatedDisplayLinkIdlingResource -> busy (null)
2020-11-12 13:05:47.249 Db hyvee.grocery[45678:28dd43] [com.wix.Detox:EarlGreyStatistics] WXAnimatedDisplayLinkIdlingResource -> busy (null)
2020-11-12 13:05:47.249 Db hyvee.grocery[45678:28dd43] [com.wix.Detox:EarlGreyStatistics] WXAnimatedDisplayLinkIdlingResource -> busy (null)
2020-11-12 13:05:47.249 Db hyvee.grocery[45678:28dd43] [com.wix.Detox:EarlGreyStatistics] WXAnimatedDisplayLinkIdlingResource -> busy (null)
2020-11-12 13:05:47.249 Db hyvee.grocery[45678:28dd43] [com.wix.Detox:EarlGreyStatistics] WXAnimatedDisplayLinkIdlingResource -> busy (null)
2020-11-12 13:05:47.249 Db hyvee.grocery[45678:28dd43] [com.wix.Detox:EarlGreyStatistics] WXAnimatedDisplayLinkIdlingResource -> busy (null)
2020-11-12 13:05:47.249 Db hyvee.grocery[45678:28dd43] [com.wix.Detox:EarlGreyStatistics] WXAnimatedDisplayLinkIdlingResource -> busy (null)
2020-11-12 13:05:47.249 Db hyvee.grocery[45678:28dd43] [com.wix.Detox:EarlGreyStatistics] WXAnimatedDisplayLinkIdlingResource -> busy (null)
2020-11-12 13:05:47.249 Db hyvee.grocery[45678:28dd43] [com.wix.Detox:EarlGreyStatistics] WXAnimatedDisplayLinkIdlingResource -> busy (null)
2020-11-12 13:05:47.249 Db hyvee.grocery[45678:28dd43] [com.wix.Detox:EarlGreyStatistics] WXAnimatedDisplayLinkIdlingResource -> busy (null)
2020-11-12 13:05:47.249 Db hyvee.grocery[45678:28dd43] [com.wix.Detox:EarlGreyStatistics] WXAnimatedDisplayLinkIdlingResource -> busy (null)
2020-11-12 13:05:47.250 Db hyvee.grocery[45678:28dd43] [com.wix.Detox:EarlGreyStatistics] WXRunLoopIdlingResource -> busy React Native thread is busy.
```

#### If you are seeing a build problem (e.g. during `npm install`)
- [ ] I am providing the `npm install` log below:

#### Device and verbose Detox logs
- [x] I have run my tests using the `--loglevel trace` argument and am providing the verbose log below:
```
detox[45617] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"invoke","params":{"type":"action","action":"scroll","params":[200,"down",null,null],"predicate":{"type":"id","value":"reservationTimeScroll"},"while":{"type":"expectation","predicate":{"type":"text","value":"4:00 pm - 5:00 pm"},"expectation":"toBeVisible"}},"messageId":13}
detox[45617] TRACE: [DetoxServer.js/MESSAGE] role=tester action=invoke (sessionId=b941b60b-a782-aea4-ab8c-75ec84ae0ff0)
F---------Detected file type 'PNG' from extension
Wrote screenshot to: e2e/reporting/ios/screenshots/1605208005954.png
.detox[45617] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"invoke","params":{"type":"action","action":"tap","predicate":{"type":"and","predicates":[{"type":"id","value":"buttonText"},{"type":"text","value":"Try Again"}]}},"messageId":14}
detox[45617] TRACE: [DetoxServer.js/MESSAGE] role=tester action=invoke (sessionId=b941b60b-a782-aea4-ab8c-75ec84ae0ff0)
F.detox[45617] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"reactNativeReload","params":{},"messageId":-1000}
detox[45617] TRACE: [DetoxServer.js/MESSAGE] role=tester action=reactNativeReload (sessionId=b941b60b-a782-aea4-ab8c-75ec84ae0ff0)
F.detox[45617] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeCleanup()
detox[45617] WARN:  [Client.js/PENDING_REQUESTS] App has not responded to the network requests below:
  (id = 13) invoke: {"type":"action","action":"scroll","params":[200,"down",null,null],"predicate":{"type":"id","value":"reservationTimeScroll"},"while":{"type":"expectation","predicate":{"type":"text","value":"4:00 pm - 5:00 pm"},"expectation":"toBeVisible"}}
  (id = 14) invoke: {"type":"action","action":"tap","predicate":{"type":"and","predicates":[{"type":"id","value":"buttonText"},{"type":"text","value":"Try Again"}]}}
  (id = -1000) reactNativeReload: {}

Unresponded network requests might result in timeout errors in Detox tests.

detox[45617] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"cleanup","params":{"stopRunner":false},"messageId":-49642}
detox[45617] TRACE: [DetoxServer.js/MESSAGE] role=tester action=cleanup (sessionId=b941b60b-a782-aea4-ab8c-75ec84ae0ff0)
```

Here is the crash report from the Simulator as a txt file
[bulletindistributord_2020-11-12-125216_MBP-ADM-55F6D.txt](https://github.com/wix/Detox/files/5532722/bulletindistributord_2020-11-12-125216_MBP-ADM-55F6D.txt)
.

**Comment by LeoNatan** [comment]
Where do you see a crash? Your app has an infinite animation Detox is stuck waiting for the app to become idle, which never happens.

**Comment by LeoNatan** [comment]
WXAnimatedDisplayLinkIdlingResource

**Comment by AlexK777** [comment]
1) Why would I get an iOS crash report for the simulator without a crash?
2) If we do not need to scroll at all, and select the top option of the list, the test works and passes as expected. How would this be possible if we had an animation running?

**Comment by LeoNatan** [comment]
If you have a crash dump, why not post in the details? I can only speak about the information posted in your issue.

**Comment by AlexK777** [comment]
It is large so I linked it as a `txt file. It is the very last line of the issue.

**Comment by LeoNatan** [comment]
Sorry, missed it, but what is crashing is an Apple daemon. How would Detox crash that? I don’t think it’s related to Detox.

**Comment by LeoNatan** [comment]
bulletindistributord

“Bulletin” is Apple’s terminology for push notifications. Are you doing something related?

**Comment by AlexK777** [comment]
Hmm. Thanks for checking it. If we navigate through the app manually we can scroll this view. We can also use `swipe()` commands in our tests, but they are less accurate. It is only when we try running a `scroll()` command that the simulator freezes up, which is what led me to file this issue.

**Comment by LeoNatan** [comment]
The entire simulator freezes?that’s even more odd.

Do you have a watch attached to the sim? I see references to NanoRegistry and pairing.

**Comment by AlexK777** [comment]
Yes. I have to forcefully close it and start a new one up. I admittedly do not know much about these crash reports, I just know I get one each time I have to close the simulator after it freezes. Other than `Bulletin` I have some for:
`NewsTag`, `parsecd` and `NewsToday`. Do any of those sound like they would be more useful? I know that may be hard to say.

No, there should be nothing to do with watches.

**Comment by AlexK777** [comment]
![Frozen](https://user-images.githubusercontent.com/7462060/98995246-ac86c400-24f6-11eb-9d60-bcd8d041ef79.gif)

Here is a visual in hopes it may help. What we are trying to do is scroll down this list and select a time slot farther down. But you can see the whole simulator freezes as I can't select another date or do anything. However, swiping on the first time slot to scroll down does work. I also attached is an image of the crash reports that were generated. If you think any of them may be helpful here I can attach those as well.

![Screen Shot 2020-11-12 at 2 51 02 PM](https://user-images.githubusercontent.com/7462060/98995327-c7593880-24f6-11eb-83b9-dd0519293432.png)

**Comment by LeoNatan** [comment]
If you press on the home button in the simulator window toolbar, does it respond?

**Comment by LeoNatan** [comment]
Ping ^

**Comment by AlexK777** [comment]
Yes, the Simulator responds to the Home button on the toolbar. But doesn't respond to other commands as in navigating to Device -> Shake to launch the RN debug menu.

**Comment by LeoNatan** [comment]
It means your app is stuck. You are wording your comments very carelessly. "Simulator freezes", to me, means the simulator has frozen. Follow [this guide](https://github.com/wix/Detox/blob/master/docs/Guide.DebuggingInXcode.md), reproduce, and once the issue has happened, hit the pause button in Xcode and see why your app is stuck.

**Comment by AlexK777** [comment]
> You are wording your comments very carelessly.

No, I just thought that to be true at the time. I hadn't tried pressing the Home button. I tried other things such as loading the RN debug menu, moving the app into the background and closing the app, etc. Those actions not working, on top of the crash reports we spoke of earlier led me to believe the Simulator was indeed frozen. Comments like this just deter people from reporting issues. Regardless, in the future I will know to try that button when the app freezes. 

I'll work through the guide as time allows, shouldn't be more than a few days. Thanks.

**Comment by LeoNatan** [comment]
I’m not looking to deter anyone, I’m just asking that issues are reported accurately so we can give them the appropriate attention. 

All of the actions you mentioned are app specific. I’m not sure why you’d even assume the simulator itself would be frozen. What is most likely happening is you main thread is blocked for some reason. It could be Detox related or not. This is a far less serious issue than what was claimed before. I still don’t see how the Apple daemon crashing is Detox related. That’s why I will need the stack trace after reproduction, so we can see if it is somehow related. 

Thanks!

**Comment by AlexK777** [comment]
For some reason I'm having trouble getting the test to run. I have the app running in a simulator launched from XCode and is on the screen to test the scroll. I can see a `console.log()` I added right before this command:
```
        await waitFor(element(by.text(targetTime)))
            .toBeVisible()
            .whileElement(by.id(pages.nativeCheckout.view.reservationTimeScroll))
            .scroll(200, 'down');
```
but everything just hangs once the `waitFor` command is called.


Test Log:
```
detox[4911] WARN:  [Client.js/PENDING_REQUESTS] App has not responded to the network requests below:
  (id = 1) invoke: {"type":"action","action":"scroll","params":[200,"down",null,null],"predicate":{"type":"id","value":"reservationTimeScroll"},"while":{"type":"expectation","predicate":{"type":"text","value":"4:00 pm - 5:00 pm"},"expectation":"toBeVisible"}}

Unresponded network requests might result in timeout errors in Detox tests.
```

Server Log:
```
npx detox run-server --loglevel trace
detox[4984] INFO:  [DetoxServer.js] server listening on localhost:8099...
detox[4984] DEBUG: [DetoxServer.js/LOGIN] role=tester, sessionId=hyvee.grocery
detox[4984] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=tester, sessionId=hyvee.grocery
detox[4984] TRACE: [DetoxServer.js/MESSAGE] role=tester action=invoke (sessionId=hyvee.grocery)
detox[4984] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=testee not connected, cannot fw action (sessionId=hyvee.grocery)
detox[4984] DEBUG: [DetoxServer.js/DISCONNECT] role=tester, sessionId=hyvee.grocery
detox[4984] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=testee not connected, cannot fw action (sessionId=hyvee.grocery)
```

**Comment by LeoNatan** [comment]
Once a hang occurs, tap the pause button in Xcode and post some information, such as backtrace, here.

**Comment by AlexK777** [comment]
My concern is I'm not getting to the same point as I am when I run these tests without the debug configuration. As in after the test runs I can still scroll the screen, and if I swap a different command in such as a visibility test, I get the exact same hang. I don't think I am accurately reproducing the same scenario with the `scroll()` command yet, and can't quite figure out why. 

Example of a different command showing the same hang:
```
detox[24855] WARN:  [Client.js/PENDING_REQUESTS] App has not responded to the network requests below:
  (id = 1) invoke: {"type":"expectation","predicate":{"type":"text","value":"Skip Time Selection"},"expectation":"toBeVisible"}

Unresponded network requests might result in timeout errors in Detox tests.
```

Current backtrace - maybe this is helpful but as I said, I don't think I'm getting the same results with this configuration yet. 
```
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  * frame #0: 0x00007fff5df6cdfa libsystem_kernel.dylib`mach_msg_trap + 10
    frame #1: 0x00007fff5df6d170 libsystem_kernel.dylib`mach_msg + 60
    frame #2: 0x000000011aa05e77 CoreFoundation`__CFRunLoopServiceMachPort + 316
    frame #3: 0x000000011aa0058d CoreFoundation`__CFRunLoopRun + 1284
    frame #4: 0x000000011a9ffb9e CoreFoundation`CFRunLoopRunSpecific + 567
    frame #5: 0x00000001272b8db3 GraphicsServices`GSEventRunModal + 139
    frame #6: 0x000000012225840f UIKitCore`-[UIApplication _run] + 912
    frame #7: 0x000000012225d320 UIKitCore`UIApplicationMain + 101
    frame #8: 0x000000010d01d68b hyvee.grocery`main at AppDelegate.swift:8:7
    frame #9: 0x000000011c28c409 libdyld.dylib`start + 1
(lldb) 
```

**Comment by LeoNatan** [comment]
Doesn’t seem useful. 

You can run a release configuration from Xcode, if you believe that will reproduce.

I have to say, this doesn’t look like a Detox issue to me. I don’t mind us investigating it, but it just doesn’t feel like it from what I’ve seen so far.
