### ISSUE TITLE
Stabilize exiting from Jest when device allocation takes forever

### ISSUE THREAD

**Issue by noomorph** [wix/Detox#2481]
At the moment, on the JS side we have an over-simplified logic for booting Android devices:

```js
  async _waitForBootToComplete(deviceId) {
    await retry({ retries: 240, interval: 2500 }, async () => {
      const isBootComplete = await this.adb.isBootComplete(deviceId);
      if (!isBootComplete) {
        throw new DetoxRuntimeError({
          message: `Android device ${deviceId} has not completed its boot yet.`,
        });
      }
     });
```

I'm not sure what's about iOS device booting, but this comment might relevant there as well.

The fact that there is no built-in reaction to `device.cleanup()` calls, as I am afraid, will result in uncontrolled `jest-circus` timeouts because nothing can abort that retry loop. I don't think we want to have leaky exits with that `--detectOpenHandles` yellow message, which worsens the developer experience by a mile.

Personally, I witnessed 5-8 times when an Android emulator was stuck forever when requested to boot, so I am confident I'm talking about realistic use cases. Let's find some time eventually to think how to fix this.

/cc @d4vidi

**Comment by noomorph** [comment]
I think I have an idea how to solve this... in a way. I'll add it to the bugathon week.

**Comment by d4vidi** [comment]
Great to see this resolved.
