### ISSUE TITLE
App doesn't launch on emulator : DetoxRuntimeError: Failed to run application on the device  HINT: Most likely, your tests have timed out and called detox.cleanup() while it was waiting for "ready" message (over WebSocket) from the instrumentation process.

### ISSUE THREAD

**Issue by annuneetu** [wix/Detox#2484]
Configured Detox with my application, it builds successfully and install the app on emulator as well on Android device but doesn't launch the app always throw the below error (RN version : "0.60.5")"detox": "^17.11.2",

![image](https://user-images.githubusercontent.com/48721996/100299331-63db0a80-2fce-11eb-8451-f017417db10d.png)

I have added the network configurations and verified all the installation guide several times

**Comment by dancomanlive** [comment]
Same here!

**Comment by annuneetu** [comment]
issues resolved for me, it was some of the libraries that were not supported and those were dependent on the our product app, the dev in my team had a fresh installation and did all the dependencies updated and introduced some of them and then it worked .

**Comment by jovanialferez** [comment]
i did the same @annuneetu . :D and i have to drop `react-native-progress` and `react-native-splash-screen`

**Comment by annuneetu** [comment]
cool, so it worked for you as well

**Comment by jovanialferez** [comment]
@annuneetu for almost a week I have been trying to find a solution to this same issue ("App has not responded..."). Almost gave up then decided to create empty app and one by one add same library/packages I am using with the main app until found the "culprit"... will keep exploring though. :)
