### ISSUE TITLE
Allow CLI args/flags as environment variables

### ISSUE THREAD

**Issue by karlmarxlopez** [wix/Detox#2487]
**Is your feature request related to a problem? Please describe.**
I apologize in advance if this feature/enhancement is already asked. I can't find it on the issues and I don't know the right term/query to search.

Not really a detox problem. But, the official Detox + Cucumber integration is not working. Because cucumber does not allow CLI args it does not recognize to pass through. There is already an [ongoing discussion here](https://github.com/cucumber/cucumber-js/issues/1474).

**Describe the solution you'd like**
To solve this issue, all CLI args should have an environment variable counterpart.
They should be prefixed with `DETOX_` so that they will not conflict with other variables.

For example.

`--configuration platform.flavor` is equal to `DETOX_CONFIGURATION=platform.flavor`
`--headless` is equal to `DETOX_HEADLESS_MODE=1`

**Describe alternatives you've considered**
The second solution I'm thinking of is, allow these args to be set into the `detxorc` files so that no need for the extra `DETOX_*` environment variables, and instead it's up to the user to set these variables.

For example.
`.detoxrc.js`
```
module.exports = {
  testRunner: 'jest',
  runnerConfig: 'e2e/config.json',
  detox: {
	// Something like this?
	args: {
    	headless: process.env.MY_DETOX_HEADLESS_VALUE,
		defaultConfiguration: process.env.MY_DETOX_CONFIGURATION || 'android.emu.release',
	},
    behavior: {
      init: {
        exposeGlobals: false,
        reuse: true,
      },
    },
  },
  configurations: {
    'ios.sim.release': {
      type: 'ios.simulator',
      build: 'xcodebuild -workspace ios/rnsandbox.xcworkspace -scheme rnsandbox -configuration Release -sdk iphonesimulator -derivedDataPath ios/build',
      binaryPath: './ios/build/Build/Products/Debug-iphonesimulator/rnsandbox.app',
      device: {
        type: 'iPhone 12'
      }
    }
  }
}
```

**Additional context**
None

**Comment by noomorph** [comment]
Prefixed CLI vars will soon land in Detox 18.
See commit: https://github.com/wix/Detox/commit/5f07132e3c5dd887cace3e9a7042e86c37f6ac8a

**Comment by karlmarxlopez** [comment]
@noomorph Thank you for the awesome work!
