### ISSUE TITLE
Accessing External Areas to the App (e.g. photo gallery)

### ISSUE THREAD

**Issue by mhyousefi** [wix/detox#249]
**Is it possible to access areas external to the app via Detox?**
An examples could be when a user profile picture is to be set using the phone's camera or using a **photo from the gallery** or one taken with the **phone camera**.
Another example is to change the keyboard input language in order to use typeText with other languages. But then for that, the iPhone simulator settings should be changed as to include that particular language.
I think many such instances will be sought at some point in the testing process...

**Comment by mhyousefi** [comment]
Any idea?

**Comment by shoumma** [comment]
Same question. Any idea on how we can access when the app opens up a browser or another app?

**Comment by isnifer** [comment]
You should check this info in the [EarlGrey](https://github.com/google/EarlGrey) repository. Currently, EarlGrey doesn't support SFSafariViewController

**Comment by LeoNatan** [comment]
It is not currently possible to control other apps. I am not sure if we will ever be able to support such cases.
Keyboard language changing is currently not supported by Earl Grey.
