### ISSUE TITLE
Detox hangs when keyboard opens up

### ISSUE THREAD

**Issue by j320** [wix/Detox#2490]
### Description
When filling up a form with many input fields, quite often at some point the keyboard will open up with a little stumble and Detox will hang. There are no animations in the scenario I'm testing. 

When adding a _device.disableSynchronization()_ before interacting with the keyboard and a _device.enableSynchronization()_ after closing it, the issue doesn't reproduce.

#### Logs
https://gist.github.com/j320/47ab57ec2ede6fc7525173f0d3cb9483

#### Environment (please complete the following information):
 - Detox: 17.13.2
 - React Native: 0.63.3
 - Node: 14.5.1
 - Device: iPhone 12 Simulator
 - Xcode: 12.2
 - iOS: 14.2
 - macOS: Big Sur

**Comment by LeoNatan** [comment]
Do you mind providing the log of the low level idle resources?

https://github.com/wix/Detox/blob/master/docs/Troubleshooting.Synchronization.md#lower-level-idling-resources-debug-ios-only

Thanks

**Comment by j320** [comment]
Here it is: https://gist.github.com/j320/07c1b2e7e0b2fb888949bf55d037aa76#file-gistfile1-txt

**Comment by LeoNatan** [comment]
Hmm, keyboard transition
Will try to reproduce. I've been testing DetoxNext (our next major Detox release, without Earl Grey), and that one works as expected on iOS 14. But maybe something in 14.2 broke the old Earl Grey we have. I'll test and see what can be done.

**Comment by j320** [comment]
Thanks @LeoNatan 

I guess the important thing is that it works on the new DetoxNext version. Therefore I can test it when you release it, in the meantime I can disable and enable synchronization. Depends if you think it's worthwhile to fix what will become sort of deprecated.

**Comment by LeoNatan** [comment]
I think it's worth a look. Also, I'm not sure when we'll release it, and more and more people are upgrading their Xcode to the latest version. If it's a big stink, I'll just have it as a known limitation, but probably something small here.

**Comment by LeoNatan** [comment]
Hm, so for me, it's working, on iOS 14.2 simulator. I am running the test project, which has `typeText()` and `clearText()` usage. The keyboard does show up, and everything goes as expected.
