### ISSUE TITLE
Allow to take screenshots unlinked to Artifacts for HTML report attachment

### ISSUE THREAD

**Issue by j320** [wix/Detox#2491]
**Is your feature request related to a problem? Please describe.**
Currently when using HTML reports, one can't attach screenshots to reports since _device.takeScreenshot()_ requires to add a name that will send the screenshot to the Artifacts location, for this to work it has to generate a temporary file.

**Describe the solution you'd like**
The option to take a screenshot that isn't linked to Artifacts and only creates a temporary file that can be attached to HTML reports.

**Describe alternatives you've considered**
At the moment this can be achieved by using this alternative dependency: https://www.npmjs.com/package/detox-take-screenshot

**Comment by d4vidi** [comment]
Hi there. I'm not sure what exactly it is that is missing with screenshot taking in Detox. After the screenshot is take, its content becomes available in the temporarily file so that it can be utilized before the test is complete.
It seems the value of https://www.npmjs.com/package/detox-take-screenshot is in that it reads the content of that file, but uses a private API to do so (and is thus discouraged). In any case, this is something that is easy to do once the path for the temp-image is returned from Detox. Please see [this guide](https://github.com/wix/Detox/blob/master/docs/APIRef.Screenshots.md) for more details.

**Comment by j320** [comment]
Thanks for your reply @d4vidi 

I think that the issue is here: ```Important: The returned path is guaranteed to be valid only during the test execution. Later on, the screenshot will be moved to the artifacts location, and will not be available.```

An image attachment is registered, however there's no image displayed, probably because the image is no longer there.
<img width="190" alt="Screenshot 2020-11-29 at 10 11 23" src="https://user-images.githubusercontent.com/28388283/100539035-46ef4300-322b-11eb-886f-78fd7b2e33c5.png">

**Comment by d4vidi** [comment]
Would copying the image file from the temp-location to a folder of your own suite you? It can be easily done with the build-in `fs` (or `fs-extra`) modules.

**Comment by j320** [comment]
Not really, it would have to be an option that'd do something similar to the library but using the Detox APIs. I can still use the alternative dependency as a workaround but I thought it would be a good idea for this to be possible within the Detox library.

**Comment by LeoNatan** [comment]
I’m sorry, I don’t see the problem. When a path is provided, the path is valid. If you copy the screenshot to a directory where your report sits, you can then link this image in your report (the copied image, not the one returned from Detox).

**Comment by d4vidi** [comment]
I fail to understand how the external library solves your problem. It basically does the same as Detox does with respect to the `device.takeScreenshot()` method, only returns a buffer. Having a buffer does not make it available in report attachments. In addition, it uses a temporary file in a random location to do so, which again - is not available for usage by report attachment generators.

What is your dream API here? :)

**Comment by j320** [comment]
A buffer is one of the ways of attaching screenshots to json files from which HTML reports are generated, here's an example if using cucumber.js where they explicitly point this out: https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/attachments.md

**Comment by LeoNatan** [comment]
So you can rest the file contents and attach it as a stream. The reason we return a file path instead of a stream is because it blows up memory for no reason. But you can easily obtain it by reading the file.

**Comment by d4vidi** [comment]
I see. In that case, I believe this ought to work (or am I missing something here?):
```js
const fs = require('fs');
const tempfile = require('tempfile');
const { promisify } = require('util');
const copyFile = promisify(fs.copyFile);

let stream;

// ...
const imagePath = await device.takeScreenshot('usecase1');
const persistedImagePath = tempfile('.png');
await copyFile(imagePath, persistedImagePath);
stream = fs.createReadStream(imagePath);

// ... (cucumber)
After(function (testCase) {
  if (testCase.result.status === Status.FAILED) {
    return this.attach(stream, 'image/png');
  }
});
```

**Comment by LeoNatan** [comment]
Since there is no issue with the current approach, I don't see us making change to this API. Thanks

**Comment by d4vidi** [comment]
@LeoNatan let's not close this just yet, as per this suggestions --
@noomorph could an enhancement of the API where in case a `retain: true` argument is passed into `takeScreenshot()` then we do not delete the temp-file, be easy to sort out?

**Comment by LeoNatan** [comment]
But keeping the temp file will still not solve the issue, because the HTML will then link to a hardcoded file on the CI disk. It should either be a relative path, which should be created by copying the file to the correct folder, or a stream, where the report generator saves it to the correct folder or embeds it inside the html. Either way, I don't see how Detox API can be extended beyond what we have now.

**Comment by d4vidi** [comment]
The point wasn't to solve it altogether - but to simplify by allowing for a stream to be created on the temp file, without having to tediously copy it.

**Comment by LeoNatan** [comment]
Isn't the stream consumed right away by the API? It should be, so no need to copy.

**Comment by d4vidi** [comment]
No - the _consumption_ is called in the context of `After`.

**Comment by LeoNatan** [comment]
🤦‍♂️
Ridiculous design.

**Comment by d4vidi** [comment]
@LeoNatan how so?
@j320 has any of this worked out for you?

**Comment by j320** [comment]
@d4vidi Thanks for your solution, I now had a chance to try it and it worked indeed, just had to make a small amendment on the After hook since it's async:

```    After(async function (scenario) {
      if (scenario.result.status === 'failed') {
        await this.attach(stream, 'image/png');
      }
    });```

Thank you!

**Comment by d4vidi** [comment]
Happy to hear! Please close the issue if that concludes it for you.
