### ISSUE TITLE
Detox will soon drop iOS 12.x support

### ISSUE THREAD

**Issue by LeoNatan** [wix/Detox#2494]
Hello,

Please note that iOS 12.x support will soon be dropped in Detox 18. This does not require that you drop support for iOS 12 in your apps, just that tests will no longer work on iOS 12 and below. Please make sure your tests are running on iOS 13 or above.

Thanks

**Comment by kyle-ssg** [comment]
Hey @LeoNatan, out of curiosity, is the intention of detox to support the latest 2 versions of each OS?

The reason I ask is my usecase of Detox and E2E as a whole is to test older devices.

**Comment by LeoNatan** [comment]
I am no longer involved with the project. When I was, there was no rule set in place when to deprecate existing OSes, only when they became too burdensome to support. With 18, a legacy websocket implementation was removed, requiring iOS 13 and above. In the future, @d4vidi and @alon-ha will make the decision when to drop support.

**Comment by d4vidi** [comment]
Thanks @LeoNatan. I believe we shall continue following the same guideline as before. Our capacity to support things is limited, and so we have to contantly consider think of the tradeoffs.
