### ISSUE TITLE
field CFBundleIdentifier not found inside Info.plist

### ISSUE THREAD

**Issue by Chrisissorry** [wix/Detox#2499]
I cannot get detox iOS tests to run properly as I get 

```
Error: field CFBundleIdentifier not found inside Info.plist of app binary at /Users/jesus/Documents/projects/appname/ios/build/Build/Products/Debug-iphonesimulator/Appname.app
```

https://stackoverflow.com/questions/65071380/detox-field-cfbundleidentifier-not-found-inside-info-plist

**Comment by LeoNatan** [comment]
Your app is broken. `CFBundleIdentifier` is required for any app on iOS.

**Comment by Chrisissorry** [comment]
I get that. However, it runs properly in the simulator and on the device.

**Comment by retyui** [comment]
It usually happens when detox config include invalid `binaryPath`

the app wasn't compiled before running e2e tests 

https://github.com/wix/Detox/blob/b8f82498191f399ab9ad39220a501330d19c41ab/detox/src/devices/drivers/ios/SimulatorDriver.js#L78-L90

**Comment by koliapp2019** [comment]
For our case, the. binary path is correct and the IPA is good to go even for AppStore upload. But we still have the issue. May I know how to resolve this issue?

**Comment by asafkorem** [comment]
> May I know how to resolve this issue? Does anyone get the solution?

If you still have a problem, please open a new issue.

**Comment by facuescobar** [comment]
I have solved this issue by building the bundle first

`detox build -c ios.sim.debug`
