### ISSUE TITLE
role=testee not connected

### ISSUE THREAD

**Issue by sibelius** [wix/detox#25]
I'm having the following logs on detox-server

login sessionId=MyApp role=tester
fw sessionId=MyApp action=isReady from role=tester
cannot fw sessionId=MyApp since other role=testee not connected

I'm also having timeout as this issue: https://github.com/wix/detox/issues/20

**Comment by sibelius** [comment]
fixed using iPhone 5s simulator

**Comment by talkol** [comment]
I finally squeezed a few days of work and finished the sync mechanism for RN! sorry it took so much time I was busy on several other projects

most sync issues should be resolved in today's major version (3.0.0)

and the specific sync issue on test start that you see here is resolved by this [commit](https://github.com/wix/detox/commit/60b740591413a7c2870df8b3389ef97ce5426bca)
