### ISSUE TITLE
Getting past system alert on Android after device.openUrl call

### ISSUE THREAD

**Issue by munyirik** [wix/Detox#2504]
Sort of similar to the issue opened for iOS (https://github.com/wix/Detox/issues/172) a while back but for Android...

When I use device.openUrl I get the prompt to pick my app or the WebView Shell app (see image below).

Is there a way to set this up to always pick my app?

![image](https://user-images.githubusercontent.com/8389594/100945832-e83df980-34b6-11eb-923b-ebe7fb6278ea.png)

**Comment by d4vidi** [comment]
@munyirik have you published this on SO yet?

**Comment by lukebrandonfarrell** [comment]
This is still an issues, did you find a solution @munyirik ?

**Comment by d4vidi** [comment]
Oh, back in those days when our bots used to auto-closed these type of issues 🤦🏻

**Comment by d4vidi** [comment]
In any case, I think this is what you're looking for: https://stackoverflow.com/questions/65117954/getting-past-system-alert-on-android-after-device-openurl-call

**Comment by lukebrandonfarrell** [comment]
@d4vidi Makes sense so seems like we need a `.well-known/assetlinks.json` file on the url we use to deeplink for this to work.

**Comment by d4vidi** [comment]
@lukebrandonfarrell seems like it -- if indeed what you're trying to do is to associate a specific URL with your app. IIUC it some good practice to have - regardless of Detox and UI testing, if you don't want your users to be prompted with Chrome or other browsers whenever such a link is tapped on.

**Comment by lukebrandonfarrell** [comment]
Yeah agreed @d4vidi we do have these app links setup, but I haven't yet confirmed that it solved the issue, but hopefully will soon

**Comment by SMKH-PRO** [comment]
I am facing the same problem @lukebrandonfarrell , How did you solve it?
I already have `.well-known/assetlinks.json`  hosted on my domain
