### ISSUE TITLE
[Support] - 2 fingers action

### ISSUE THREAD

**Issue by xuanzhaopeng** [wix/Detox#2509]
Hey Team,

Thanks very much for the effort, and I just move from Appium to Detox as for react-native testing. So may I ask is there a way to support 2 fingers action, like zoom in, zoom out. Or something like touch-> move finger->release?

Thanks

**Comment by LeoNatan** [comment]
Hello,

We have support for zoom, but not more complex interactions. Check out pinch(): https://github.com/wix/Detox/blob/master/docs/APIRef.ActionsOnElement.md#pinchscale-speed-angle--ios-only
