### ISSUE TITLE
Progressive web application (PWA) support

### ISSUE THREAD

**Issue by Rogier-blip** [wix/Detox#2515]
**Is your feature request related to a problem? Please describe.**
Currently, there isn't (or I can't find) a testing framework that supports testing PWA's on a native device.

**Describe the solution you'd like**
Being able to write Detox tests for PWA's

**Describe alternatives you've considered**
Haven't been able to find a framework that supports testing PWA's

**Comment by LeoNatan** [comment]
Unfortunatey, this isn’t really possible currently. Even if we move to XCUITest on iOS, there are pretty big technical limitations as to what actions and matching would be possible. Web stuff should be tested with web testing frameworks.
