### ISSUE TITLE
[RN] DetoxRuntimeError: Failed to run application on the device

### ISSUE THREAD

**Issue by EasonWang01** [wix/Detox#2518]
**Describe the bug**
DetoxRuntimeError: Failed to run application on the device

**To Reproduce**

```
yarn jest jest-circus --dev
npx detox init -r jest

./gradlew assembleDebug
```

```
    "android": {
      "type": "android.emulator",
      "binaryPath": "/Users/SampleApp/android/app/build/outputs/apk/debug/app-debug.apk",
      "device": {
        "avdName": "Pixel_XL_API_30"
      }
    }
```
**Device and Verbose Detox Logs**
```
detox[29340] INFO:  [test.js] configuration="android" useCustomLogger=true forceAdbInstall=false DETOX_START_TIMESTAMP=1607480607937 readOnlyEmu=false reportSpecs=true jest --config e2e/config.json --testNamePattern '^((?!:ios:).)*$' --maxWorkers 1 e2e
detox[29341] INFO:  [DetoxServer.js] server listening on localhost:49310...
detox[29341] ERROR: DetoxRuntimeError: Failed to run application on the device

HINT: Most likely, your tests have timed out and called detox.cleanup() while it was waiting for "ready" message (over WebSocket) from the instrumentation process.
```
**Environment (please complete the following information):**
 - Detox: 17.14.3
 - React Native: 0.63.3
 - Test-runner (select one): jest-circus

**Comment by d4vidi** [comment]
@EasonWang01 please follow through the [Detox getting-started guide](https://github.com/wix/Detox/blob/master/docs/Introduction.GettingStarted.md), focusing on Android. Thanks.

**Comment by EasonWang01** [comment]
Hi, the setup is same as the document, but still getting the same error.

**Comment by EasonWang01** [comment]
Related to this https://github.com/wix/Detox/issues/2415

**Comment by d4vidi** [comment]
@EasonWang01 you're not building the `test APK`. Please refer to the guides.

**Comment by huy-lv** [comment]
Found the problem: we are missing this step: https://wix.github.io/Detox/docs/introduction/project-setup#42-adding-an-auxiliary-android-test

**Comment by MayoudP** [comment]
> Found the problem: we are missing this step: https://wix.github.io/Detox/docs/introduction/project-setup#42-adding-an-auxiliary-android-test

Have the same issue and I followed well the setup guid for android test. Which specific line were you missing ? I'm pretty sure I added everything needed (maybe not 🤔 😢 )

**Comment by huy-lv** [comment]
did you put DetoxTest.java in correct path: android/app/src/**androidTest**/java/com/<your.package>/DetoxTest.java

**Comment by MayoudP** [comment]
> did you put DetoxTest.java in correct path: android/app/src/**androidTest**/java/com/<your.package>/DetoxTest.java, folder **androidTest**, not **main**

⏫  Very good catch ⏫ 
However, still can't launch the tests. This is the errors I'm having in the artifacts : 
```
{"name":"detox","hostname":"MacBook-Pro.local","pid":20519,"level":50,"cat":"child-process,child-process-exec","ph":"i","tid":0,"fn":"execWithRetriesAndLogs","cmd":"\"/Users/user/Library/Android/sdk/platform-tools/adb\" -s emulator-5554 shell \"ps | grep \\\"my\\.package\\.name$\\\"\"","trackingId":62,"event":"EXEC_FAIL","msg":"\"\"/Users/user/Library/Android/sdk/platform-tools/adb\" -s emulator-5554 shell \"ps | grep \\\""my\\.package\\.name$\\\"\"\" failed with error = ChildProcessError: Command failed: \"/Users/user/Library/Android/sdk/platform-tools/adb\" -s emulator-5554 shell \"ps | grep \\\"my\\.package\\.name$\\\"\"\n `\"/Users/user/Library/Android/sdk/platform-tools/adb\" -s emulator-5554 shell \"ps | grep \\\"my\\.package\\.name$\\\"\"` (exited with error code 1) (code=1), stdout and stderr:\n","time":"2023-08-24T14:14:27.442Z","v":0}
{"name":"detox","hostname":"MacBook-Pro.local","pid":20519,"level":50,"cat":"child-process,child-process-exec","ph":"i","tid":0,"fn":"execWithRetriesAndLogs","cmd":"\"/Users/user/Library/Android/sdk/platform-tools/adb\" -s emulator-5554 shell \"ps | grep \\\"my\\.package\\.name$\\\"\"","trackingId":62,"event":"EXEC_FAIL","stdout":true,"msg":"","time":"2023-08-24T14:14:27.442Z","v":0}
{"name":"detox","hostname":"MacBook-Pro.local","pid":20519,"level":50,"cat":"child-process,child-process-exec","ph":"i","tid":0,"fn":"execWithRetriesAndLogs","cmd":"\"/Users/user/Library/Android/sdk/platform-tools/adb\" -s emulator-5554 shell \"ps | grep \\\"my\\.package\\.name$\\\"\"","trackingId":62,"event":"EXEC_FAIL","stderr":true,"msg":"","time":"2023-08-24T14:14:27.442Z","v":0}
```

Be aware that I didn't added the com since my package name is like that io.package.package. If I add an extra com before it lead to an issue (not finding MainActivity because it's located in `app/src/main/java/io/package/package/MainActivity.java`

I don't know what I'm missing here, if you have any ideas ? Else thanks for the fast answer 🙏

**Comment by huy-lv** [comment]
@MayoudP I can't find the problem here. Try to create new project from scratch and do setup step by step, you should find the step you missed. If you can share your project, maybe I can help.

**Comment by clarkjrcanlog** [comment]
@MayoudP 

'android.debug': {
      type: 'android.apk',
      // binaryPath: 'android\\app\\build\\outputs\\apk\\debug\\app-debug.apk',
      // build:
      // 'cd android && .\\gradlew.bat app:assembleDebug app:assembleAndroidTest -DtestBuildType=debug && cd ..',
      //use build script below for mac OS, use build script above for windows
      binaryPath: 'android/app/build/outputs/apk/debug/app-debug.apk',
      build:
        'cd android && ./gradlew app:assembleDebug app:assembleAndroidTest -DtestBuildType=debug && cd ..',
      reversePorts: [8081],
    },

this is my build script I hope this may help you
