### ISSUE TITLE
Recommended testing approach for proxies

### ISSUE THREAD

**Issue by AlanFoster** [wix/detox#252]
Is there any recommended tooling for proxying/stubbing web requests with detox?

For instance in Ruby there is [VCR](https://github.com/vcr/vcr) which can record all web requests, and save them for later use to be re-played. This allows for your tests to no longer rely on external services, and therefore improves the overall testing time - as well as reduce flakiness of tests.  

Is there a recommended approach for detox, or could anyone share their experience in this area?

**Comment by isnifer** [comment]
We do not mock anything, cause it's not like a real user. Also I think mocks better for unit tests, not e2e

**Comment by rotemmiz** [comment]
We use Detox for both E2E testing and Automation testing. The core part of our app has two suites, running ~10 E2E tests (against production, "like a real user"), and ~50 Automation tests (fully mocked environment).

See our [Advanced Mocking](https://github.com/wix/detox/blob/master/docs/Guide.Mocking.md) section for more details. In short, we have a way to make the packager take custom extensions that will replace your production code (endpoints, imports...) at build time.

**Comment by isnifer** [comment]
@rotemmiz "Automation testing" - what you mean?

**Comment by cjcaj** [comment]
@AlanFoster I've been using yakbak https://github.com/flickr/yakbak to record all web requests to be replayed. It's been working great and my tests aren't flaky at all! I'm currently writing an article with this kind of setup. I'll post it here once it is up.

**Comment by rotemmiz** [comment]
@isnifer 
E2E - test production app, as closely as possible to a real user, not mocking external endpoints. This tests more than just an app (servers, network), and it may fail for reasons that are unrelated to the app under test.
UI Automation - test a special flavor of the app that mocks all the potentially flaky parts (again, servers, network, any other external dependency) to minimize flakiness.

**Comment by isnifer** [comment]
@rotemmiz good, thank you. At Tipsi we are doing e2e :)

**Comment by LeoNatan** [comment]
I don't think this kind of functionality should be part of detox. This sounds like mock logic that the app should provide on its own.
