### ISSUE TITLE
Documentation home page implies that Detox supports native Android; example says it does not

### ISSUE THREAD

**Issue by robertlagrant** [wix/Detox#2526]
**Describe the bug**
On the home page:
> Detox is built from the ground up to support React Native projects as well as pure native ones

However the Android sample states:
> Android is not supported in detox yet. This project is here for development purposes and is not working at the moment.

**Expected behavior**
Home page documentation makes clear that "native" only refers to iOS.

**Comment by vkulmanov** [comment]
Are you sure that the expected behavior is correct here? It could be that the example README is wrong

**Comment by d4vidi** [comment]
Thanks for this submission. I've updated the documentation in this regards, and added issue #2543.
