### ISSUE TITLE
Android <24 is not supported (No instrumentation runner found on device)

### ISSUE THREAD

**Issue by amq** [wix/Detox#2527]
**Describe the bug**

Android <24 requires `pm install -rg` instead of `pm install -r -g -t` and even though [there still is a check](https://github.com/wix/Detox/blob/5ed69f81cdecefba93427fca9b51c4cdabc7a788/detox/src/devices/drivers/android/tools/ADB.js#L92) for this, it is not effective anymore since the changes in https://github.com/wix/Detox/pull/2045.

As a result, the apps do not install and the tests do not run.

The main use case for <24 are CI runs. A 21 system image is two times smaller than 24 and it is usable even without hardware virtualization. 21 is also the "lowest common denominator", as this is the minSdkVersion in React Native 0.64.

**To Reproduce**

- [x] I have tested this issue on the latest Detox release and it still reproduces

Steps to reproduce:
1. Create an AVD with SDK <24
2. Run detox test

**Expected behavior**

Should run tests.

**Screenshots**

**Device and Verbose Detox Logs**

```
detox[18184] DEBUG: [exec.js/EXEC_CMD, #4] adb -s emulator-5554 shell "getprop ro.build.version.sdk"
detox[18184] TRACE: [exec.js/EXEC_SUCCESS, #4] 21

...

detox[18184] DEBUG: [exec.js/EXEC_CMD, #15] adb -s emulator-5554 shell "pm install -r -g -t /data/local/tmp/detox/Application.apk"
detox[18184] TRACE: [exec.js/EXEC_SUCCESS, #15] Error: Unknown option: -g

...

detox[18184] DEBUG: [exec.js/EXEC_CMD, #17] adb -s emulator-5554 shell "pm install -r -g -t /data/local/tmp/detox/Test.apk"
detox[18184] TRACE: [exec.js/EXEC_SUCCESS, #17] Error: Unknown option: -g
```

**Environment (please complete the following information):**
 - Detox: 17.14.4
 - React Native: 0.63.4
 - Node: 14.15.1
 - Device: AVD pixel with SDK 21
 - OS: Win10
 - Test-runner (select one): `jest-circus`

**Comment by amq** [comment]
For now, this can be mitigated by using the `--force-adb-install` flag.

Then apps install fine, but there is another problem:

```
detox[15396] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"isReady","params":{},"messageId":-1000}
detox[15396] TRACE: [DetoxServer.js/MESSAGE] role=tester action=isReady (sessionId=7675dfe5-bc2a-65a3-7238-ff399a13b043)
detox[15396] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=testee not connected, cannot fw action (sessionId=7675dfe5-bc2a-65a3-7238-ff399a13b043)
detox[15396] TRACE: [exec.js/SPAWN_STDOUT, #20] INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.app.DetoxTest:
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: test=runDetoxTests
INSTRUMENTATION_STATUS: class=com.app.DetoxTest
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS_CODE: 1

detox[15396] TRACE: [exec.js/SPAWN_STDOUT, #20] INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
Error in runDetoxTests(com.app.DetoxTest):
org.joor.ReflectException: java.lang.NoSuchFieldException: accessFlags
        at org.joor.Reflect.set(Reflect.java:247)
        at com.wix.detox.espresso.EventsInjectorReflected.setEventsInjectionStrategy(UiControllerSpy.kt:36)
```

**Comment by d4vidi** [comment]
Thanks for submitting this. Note the latter problem is associated with this fix: https://github.com/wix/Detox/blob/9dd9635f0ad01fea8c306dd1090bf6612c88c081/detox/android/detox/src/main/java/org/joor/Reflect.java#L236

We are currently preoccupied with other things, and would appreciate contributions so as to fix support for SDK<24.

**Comment by mnightingale** [comment]
I'm just taking a look at fixing this, I've only tested api 22 so far and still need to check if >= 24 is the correct condition.

For the accessFlags error jOOR fixed the original issue by ignoring the missing modifiers field on Android.

https://github.com/jOOQ/jOOR/blob/085dde82bd3d76b544bf9d202243cfc1e9901559/jOOR/src/main/java/org/joor/Reflect.java#L389-L410

@d4vidi With that it passes the unit tests but should I do something like the following instead?
I figure you added the accessFlags code because it was required for something in that PR?

```
try
// modifiers
catch
// ignore

try
// accessFlags
catch
// ignore
```

**Comment by d4vidi** [comment]
@mnightingale I don't think the fix in jOOR is good enough: They made the function simply fail implicitly on Android, rather than have it work properly.
I indeed added the `accessFlag` because Detox uses reflection quite often.

**Comment by mnightingale** [comment]
I've done somemore investigating by throwing an exception with getDeclaredFields() when set(...) is called which is at `com.wix.detox.espresso.EventsInjectorReflected.setEventsInjectionStrategy(UiControllerSpy.kt:36)`

API 22:

```
private final java.lang.reflect.ArtField java.lang.reflect.Field.artField
public static final java.util.Comparator java.lang.reflect.Field.ORDER_BY_NAME_AND_DECLARING_CLAS
```

API 24:

```
private int java.lang.reflect.Field.accessFlags
private java.lang.Class java.lang.reflect.Field.declaringClass
private int java.lang.reflect.Field.dexFieldIndex
private int java.lang.reflect.Field.offset
private java.lang.Class java.lang.reflect.Field.type
```

So it seems to me older Android versions didn't use `accessFlags` or `modifiers`, so the jOOR fix does seem correct.
If there is no `accessFlags` field the `field.set` call still works without changing any modifiers and that's the call that the method was previously changed to support.

@d4vidi do you think I should patch the jOOR set method or update the whole library which includes the fix plus whatever else they've fixed/changed.
