### ISSUE TITLE
ERROR: DetoxRuntimeError: Failed to run application on the device

### ISSUE THREAD

**Issue by dancomanlive** [wix/Detox#2528]
Configured Detox with my application, it builds successfully and install the app on emulator as well on Android device but doesn't launch the app always throw the below error (RN version : "0.59.0")"detox": "^17.11.2",

```
detox[16032] INFO:  [DetoxServer.js] server listening on localhost:65132...
detox[16032] ERROR: DetoxRuntimeError: Failed to run application on the device

HINT: Most likely, your tests have timed out and called detox.cleanup() while it was waiting for "ready" message (over WebSocket) from the instrumentation process.
```

I have also added the network configurations and verified all the installation guide several times. This issue is same as  this issue https://github.com/wix/Detox/issues/2484 but it was closed by the bot so I am making a new one.

**Comment by MFrat** [comment]
Any solution?

**Comment by onnerfors** [comment]
Getting this too
