### ISSUE TITLE
--device-launch-args not working with multiple args and with arg&value combinations

### ISSUE THREAD

**Issue by amq** [wix/Detox#2530]
**Describe the bug**

I want to pass `-snapshot abc -wipe-data` to the android emulator when running detox tests, but only `-snapshot` seems to be captured correctly.

Multiple arguments without values are also not working: `-snapshot -wipe-data`

**To Reproduce**

- [x] I have tested this issue on the latest Detox release and it still reproduces

Steps to reproduce:

Case A:
1. Run test with `--device-launch-args="-snapshot abc -wipe-data"`
2. Observe `configuration="android.emu.release" deviceLaunchArgs="-snapshot" useCustomLogger=true forceAdbInstall=false DETOX_START_TIMESTAMP=1607880987143 readOnlyEmu=false reportSpecs=true jest --config e2e/config.json --testNamePattern "^((?!:ios:).)*$" --maxWorkers 1 -i -p -e -cache abc`
3. Notice `deviceLaunchArgs="-snapshot"` and `-cache abc`

Case B:
1. Run test with `--device-launch-args="-snapshot -wipe-data"`
2. Observe `configuration="android.emu.release" deviceLaunchArgs="-snapshot" useCustomLogger=true forceAdbInstall=false DETOX_START_TIMESTAMP=1607881090922 readOnlyEmu=false reportSpecs=true jest --config e2e/config.json --testNamePattern "^((?!:ios:).)*$" --maxWorkers 1 -i -p -e -cache`
3. Notice `deviceLaunchArgs="-snapshot"` and `-cache`

**Expected behavior**

`deviceLaunchArgs` should match contents of `--device-launch-args`

**Screenshots**

**Device and Verbose Detox Logs**

**Environment (please complete the following information):**
 - Detox: 17.14.4
 - React Native: 0.63.4
 - Node: 14.15.1
 - Device: AVD pixel with SDK 21
 - OS: Win10
 - Test-runner (select one): `jest-circus`

**Comment by amq** [comment]
Seems like wrapping it up in additional single quotes helps, but it doesn't match documentation: `--device-launch-args='"-snapshot abc -wipe-data"'`

**Comment by noomorph** [comment]
Thanks that sounds more reasonable. I'll check

**Comment by noomorph** [comment]
@amq, I don't think I'm able to reproduce it. Tried both with `--workers` and without.

```
C:\Users\IEUser\Projects\Detox\detox\test>npx detox test -c android.emu.release -n Pixel_3a_API_30_x86 e2e  -l trace --device-launch-args="-snapshot abc -wipe-data" -w 2
detox[9184] INFO:  [test.js] configuration="android.emu.release" loglevel="trace" deviceName="Pixel_3a_API_30_x86" deviceLaunchArgs="-snapshot abc -wipe-data" useCustomLogger=true forceAdbInstall=false DETOX_START_TIMESTAMP=1607965600601 readOnlyEmu=true reportSpecs=false nyc jest --config e2e/config.js --testNamePattern "^((?!:ios:).)*$" --maxWorkers 2 e2e
```

As you can see:

```
deviceLaunchArgs="-snapshot abc -wipe-data"
```

It does not match what you reported. I think you had a wrong double quote.

E.g. if I misspell it with « – here is what I get:

```
configuration="android.emu.release" deviceLaunchArgs="«-snapshot" useCustomLogger=true forceAdbInstall=false DETOX_START_TIMESTAMP=1607965930840 readOnlyEmu=false reportSpecs=true nyc jest --config e2e/config.js --testNamePattern "^((?!:ios:).)*$" --maxWorkers 1 -i -p -e -data abc
```

Looks quite close to what you report. I think there is an issue in your command line call, please investigate it yourself.
You have three days to submit extra details to renew the debug.

**Comment by amq** [comment]
@noomorph I've now literally copied your command into all possible shells on windows, and I'm getting the same erroneous result:

git bash
```
npx detox test -c android.emu.release -n Pixel_3a_API_30_x86 e2e  -l trace --device-launch-args="-snapshot abc -wipe-data" -w 2
detox[8308] INFO:  [test.js] configuration="android.emu.release" loglevel="trace" deviceName="Pixel_3a_API_30_x86" deviceLaunchArgs="-snapshot" useCustomLogger=true forceAdbInstall=false DETOX_START_TIMESTAMP=1607972595630 readOnlyEmu=true reportSpecs=false jest --config e2e/config.json --testNamePattern '^((?!:ios:).)*$' --maxWorkers 2 -i -p -e -data e2e abc
```

powershell
```
npx detox test -c android.emu.release -n Pixel_3a_API_30_x86 e2e  -l trace --device-launch-args="-snapshot abc -wipe-data" -w 2
detox[15652] INFO:  [test.js] configuration="android.emu.release" loglevel="trace" deviceName="Pixel_3a_API_30_x86" deviceLaunchArgs="-snapshot" useCustomLogger=true forceAdbInstall=false DETOX_START_TIMESTAMP=1607972611201 readOnlyEmu=true reportSpecs=false jest --config e2e/config.json --testNamePattern "^((?!:ios:).)*$" --maxWorkers 2 -i -p -e -data e2e abc
```

cmd
```
npx detox test -c android.emu.release -n Pixel_3a_API_30_x86 e2e  -l trace --device-launch-args="-snapshot abc -wipe-data" -w 2
detox[12768] INFO:  [test.js] configuration="android.emu.release" loglevel="trace" deviceName="Pixel_3a_API_30_x86" deviceLaunchArgs="-snapshot" useCustomLogger=true forceAdbInstall=false DETOX_START_TIMESTAMP=1607972634498 readOnlyEmu=true reportSpecs=false jest --config e2e/config.json --testNamePattern "^((?!:ios:).)*$" --maxWorkers 2 -i -p -e -data e2e abc
```

It is also reproducible on macos-latest on github actions with bash shell (didn't try other shells).

I've listed all versions in the first post.
