### ISSUE TITLE
Improve app install time by reinstalling on-device APK

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#2534]
On Android, we've integrated an alternative to the somewhat unstable `adb install`, by manually executing each of the subsequent commands - namely, APK's push and on-device installation.

This opens way to cutting down app installation time even further. Instead of going through the _entire_ process again and again in each suite (where the app is typically reinstalled from scratch), we could skip the APK's push part, and simply install the APK's that are already available on the device itself. Of course, this would have to come with a cost of validating the APK's integrity (e.g. by comparing checksums).

**Comment by amq** [comment]
Why is reinstalling needed at all between test suites?
