### ISSUE TITLE
Launching once with permissions

### ISSUE THREAD

**Issue by dbilgin** [wix/Detox#2536]
Right now when I want my app to launch with notification permissions enabled I call this:
```
  await device.launchApp({ permissions: { notifications: 'YES'} });
```
But with the new implementation `detox.init(config, {launchApp: false});` kind of lost its meaning and it doesn't really work, at least for me, it launches a new simulator. Without the `init`, my app launches twice when I could just launch it with the notifications already permitted. I might've gotten lost in the docs and could not have found how to do this, but it would be really nice to get rid of this "re-launch".

A setting inside config.json for example to disable the startup launch would be awesome, but I just wanted to know if this is possible at all.

**Comment by noomorph** [comment]
Sure, check out this documentation section: https://github.com/wix/Detox/blob/d09a6e273e5738342ff8b4cda957685f41ca8591/docs/APIRef.Configuration.md#behavior-configuration
