### ISSUE TITLE
Unable to create/compare screenshots of opened Share Sheet

### ISSUE THREAD

**Issue by jpoisch** [wix/Detox#2541]
**Describe the bug**
If a share sheet has been opened, and I try to perform any action thereafter (in my case was trying to capture a screenshot), the test fails. I have tried disabling the animations with: await detox.device.disableSynchronization();

Example share sheet:
![image](https://user-images.githubusercontent.com/51448684/102629836-ff821580-414b-11eb-8182-7c395b10e9cf.png)

**To Reproduce**

- [ ] I have tested this issue on the latest Detox release and it still reproduces

Steps to reproduce:
1. In an app where sharing is possible (share sheet is present), disable the animations with await detox.device.disableSynchronization();
2. Open the share sheet
3. Try to do a screen capture or screenshot comparison

**Expected behavior**
Because the animations are disabled, I should be able to create a screenshot or compare it.

**Device and Verbose Detox Logs**
Device: Android Emulator - Pixel 3
Output using --debug-synchronization 200
```detox[43318] INFO:  [DetoxServer.js] server listening on localhost:56853...
detox[43318] INFO:  [actions.js] Sync LooperIdlingResourceInterrogationHandler: LooperIdlingResource-4944-mqt_js
detox[43318] INFO:  [actions.js] Sync UIModuleIdlingResource: com.wix.detox.reactnative.idlingresources.UIModuleIdlingResource
......
.F-.detox[43318] INFO:  [actions.js] Sync AnimatedModuleIdlingResource: com.wix.detox.reactnative.idlingresources.AnimatedModuleIdlingResource
detox[43318] INFO:  [actions.js] Sync AnimatedModuleIdlingResource: com.wix.detox.reactnative.idlingresources.AnimatedModuleIdlingResource
detox[43318] INFO:  [actions.js] Sync AnimatedModuleIdlingResource: com.wix.detox.reactnative.idlingresources.AnimatedModuleIdlingResource
detox[43318] INFO:  [actions.js] Sync AnimatedModuleIdlingResource: com.wix.detox.reactnative.idlingresources.AnimatedModuleIdlingResource
detox[43318] INFO:  [actions.js] Sync AnimatedModuleIdlingResource: com.wix.detox.reactnative.idlingresources.AnimatedModuleIdlingResource
detox[43318] INFO:  [actions.js] Sync AnimatedModuleIdlingResource: com.wix.detox.reactnative.idlingresources.AnimatedModuleIdlingResource
detox[43318] INFO:  [actions.js] Sync AnimatedModuleIdlingResource: com.wix.detox.reactnative.idlingresources.AnimatedModuleIdlingResource
detox[43318] INFO:  [actions.js] Sync AnimatedModuleIdlingResource: com.wix.detox.reactnative.idlingresources.AnimatedModuleIdlingResource
detox[43318] INFO:  [actions.js] Sync AnimatedModuleIdlingResource: com.wix.detox.reactnative.idlingresources.AnimatedModuleIdlingResource
detox[43318] INFO:  [actions.js] Sync AnimatedModuleIdlingResource: com.wix.detox.reactnative.idlingresources.AnimatedModuleIdlingResource
detox[43318] INFO:  [actions.js] Sync AnimatedModuleIdlingResource: com.wix.detox.reactnative.idlingresources.AnimatedModuleIdlingResource
detox[43318] INFO:  [actions.js] Sync AnimatedModuleIdlingResource: com.wix.detox.reactnative.idlingresources.AnimatedModuleIdlingResource
```

**Environment (please complete the following information):**
 - Detox: ^17.13.1
 - React Native: 0.63.3
 - Node: 14.4.0
 - Device: Android Emulator - Pixel 3
 - OS: Android version 9
 - Test-runner (select one): cucumber-js

**Comment by d4vidi** [comment]
@jpoisch it is virtually impossible to help with this minimal chunk of logs. Please provide more info, as requested by the issue template. More so, it is likely _not_ as you describe it with respect to the share sheet, because your logs suggest RN-rooted animations running endlessly.
