### ISSUE TITLE
Cannot find TextInput by testID on IOS 

### ISSUE THREAD

**Issue by heypran** [wix/Detox#2542]
### Description

I am using testID for my TextInput in react-native. The tests are not able to find the element when using typeText.
```await element(by.id(id)).typeText(text);```
However, the visible is working,
```await waitFor(element(by.id(id))).toBeVisible();```
I am using IOS simulator for testing. This is only in case of text-input. 

I was able to make it work by using `accessibilityLabel`
```
accessible={true}
accessibilityLabel={'auth_email_address'}
```
- [x] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

The tests are not able to find the element when using typeText.
```await element(by.id(id)).typeText(text);```
However, the visible is working,
```await waitFor(element(by.id(id))).toBeVisible();```
I am using IOS simulator for testing. This is only in case of text-input. 

#### Expected behavior
Test should be able to find the element by ID
#### Environment (please complete the following information):
 - Detox:17.14.6
 - React Native: ~0.63.4
 - Node:
 - Device:
 - Xcode: 
 - iOS: 11 
 - macOS: 

#### If you are experiencing a timeout in your test
- [ ] I have followed the instructions under [Lower-level Idling Resources Debug](https://github.com/wix/Detox/blob/master/docs/Troubleshooting.Synchronization.md#lower-level-idling-resources-debug-ios-only) and am providing the log below:

#### If you are seeing a build problem (e.g. during `npm install`)
- [ ] I am providing the `npm install` log below:

#### Device and verbose Detox logs
- [ ] I have run my tests using the `--loglevel trace` argument and am providing the verbose log below:
```

Test Failed: No elements found for “MATCHER(identifier: == “email_address”)”
    TIP: To print view hierarchy on failed actions/matches, use log-level verbose or higher.

      38 | export const awaitAndEnterText = async (id: string, text: string) => {
      39 |   await waitFor(element(by.id(id))).toBeVisible();
    > 40 |   await element(by.id(id)).typeText(text);
         |                            ^
      41 | };
      42 |

**Comment by LeoNatan** [comment]
At the very least, you need to provide the error you are getting.

Both actions and expectations resolve their element using the same code, so it cannot be that `toBeVisible()` finds the element, but `typeText()` does not. It's just not possible at that level.

**Comment by heypran** [comment]
@LeoNatan , added the error!

**Comment by LeoNatan** [comment]
?

You are matching by label: `by.label(id))`.

**Comment by heypran** [comment]
> ?
> 
> You are matching by label: `by.label(id))`.

Sorry I was trying to reproduce the error, now fixed it.

**Comment by LeoNatan** [comment]
OK, run your project with Xcode, reach the screen you are having the issue, run the view hierarchy inspector and see if the text field has the identifier you are expecting.

**Comment by cjoshmartin** [comment]
For anyone reading this, I found if you add your testID and rebuild the tags show up (`detox build -c ios.sim.debug`). which kind of sucks but at least it works.
