### ISSUE TITLE
Detox failed with "Error: No instrumentation runner found on device" when running on real Android devices

### ISSUE THREAD

**Issue by Quandm1195** [wix/Detox#2544]
**Describe the bug**

If I run detox on a real device, I got the error "detox[35625] ERROR: Error: No instrumentation runner found on device HT74C0204248 for package com.example.app". If I change to simulator, it runs normally.

**Expected behavior**

**Screenshots**

**Device and Verbose Detox Logs**

detox[35563] INFO:  [test.js] configuration="android.emu.debug" loglevel="verbose" reuse=true recordLogs="failing" useCustomLogger=true forceAdbInstall=false DETOX_START_TIMESTAMP=1608540923268 readOnlyEmu=false reportSpecs=true jest --config e2e/config.json --testNamePattern '^((?!:ios:).)*$' --maxWorkers 1 e2e
detox[35564] INFO:  [DetoxServer.js] server listening on localhost:64212...
detox[35564] DEBUG: [AsyncWebSocket.js/WEBSOCKET_OPEN] opened web socket to: ws://localhost:64212
detox[35564] DEBUG: [DetoxServer.js/LOGIN] role=tester, sessionId=59051835-bdc4-2005-ac27-6a2b18915bf1
detox[35564] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=tester, sessionId=59051835-bdc4-2005-ac27-6a2b18915bf1
detox[35564] DEBUG: [exec.js/EXEC_CMD, #0] "/Users/quan/Library/Android/sdk/platform-tools/adb"  devices
detox[35564] DEBUG: [exec.js/EXEC_SUCCESS, #0] List of devices attached
HT74C0204248	device

detox[35564] DEBUG: [FreeDeviceFinder.js/DEVICE_LOOKUP] Found a matching & free device HT74C0204248
detox[35564] DEBUG: [exec.js/EXEC_CMD, #1] "/Users/quan/Library/Android/sdk/platform-tools/adb" -s HT74C0204248 shell "getprop ro.build.version.sdk"
detox[35564] DEBUG: [exec.js/EXEC_CMD, #2] "/Users/quan/Library/Android/sdk/platform-tools/adb" -s HT74C0204248 shell "dumpsys power | grep \"^[ ]*m[UW].*=\""
detox[35564] DEBUG: [exec.js/EXEC_CMD, #3] "/Users/quan/Library/Android/sdk/build-tools/30.0.3/aapt" dump badging "/Users/quan/Downloads/example/android/app/build/outputs/apk/qa/debug/app-qa-debug.apk" | grep -e "package: name="
detox[35564] DEBUG: [exec.js/EXEC_CMD, #4] "/Users/quan/Library/Android/sdk/platform-tools/adb" -s HT74C0204248 shell "am force-stop com.example.app"
detox[35564] DEBUG: [exec.js/EXEC_CMD, #5] "/Users/quan/Library/Android/sdk/platform-tools/adb" -s HT74C0204248 shell "date +\"%m-%d %T.000\""
detox[35564] DEBUG: [exec.js/EXEC_CMD, #6] "/Users/quan/Library/Android/sdk/platform-tools/adb" -s HT74C0204248 reverse tcp:64212 tcp:64212
detox[35564] DEBUG: [exec.js/EXEC_CMD, #7] "/Users/quan/Library/Android/sdk/platform-tools/adb" -s HT74C0204248 shell "pm list instrumentation"
detox[35564] ERROR: Error: No instrumentation runner found on device HT74C0204248 for package com.example.app
detox[35564] INFO:  Authentication Test is assigned to undefined
detox[35564] INFO:  Authentication Test: Valid credentials should be able to log in and log out
detox[35564] INFO:  Authentication Test: Valid credentials should be able to log in and log out [SKIPPED]

**Environment (please complete the following information):**
 - Detox: 17.8.3
 - React Native:0.63.3
 - Node:10.16.0
 - Device: Android Device
 - OS: Android 10
 - Test-runner (select one): `jest-circus` | `jest-jasmine2` (deprecated) | `mocha` jest-circus

**Comment by d4vidi** [comment]
Hi. Could you please retry running with `--loglevel trace` (instead of `verbose`)? In particular, I'm looking for the result of the `pm list instrumentation` command (which appears in your logs), and it's not available this way.
I'd be happy to help.

**Comment by Quandm1195** [comment]
Hi.
Thanks for your comment. I have found the root cause and fixed it. My scenario is that I wanted to run detox test against Android emulator in Jenkins. The binaryPath was configured as another device, so every time I try with a new device it throws a "No intrumentation" error. I have to configure 2 commands to run in ci and on local with 2 different binaryPath.
