### ISSUE TITLE
Android struggles to find "visible" elements in CI

### ISSUE THREAD

**Issue by kg-currenxie** [wix/Detox#2558]
**Describe the bug**
Visibility matchers seems to fail (almost every time) in CI (on a slow device?)

As you could see in the screenshot below, the second input is blank, so it seems it can't find the input, assuming because the keyboard is still up? (Still animating down?)

I've seen about 1 in 20 tests in CI would pass, so almost never.

This test always passes on iOS on the same CI machine.

**To Reproduce**

- [x] I have tested this issue on the latest Detox release and it still reproduces

Steps to reproduce:
```
import { isBalancesScreenMatcher } from '../helpers/matchers/BalancesScreen'
import { screenIsVisible } from '../helpers/matchers/core/ScreenVisibility'

describe('LoginScreen', () => {
  it('can log in successfully', async () => {
    await expect(element(by.id('username'))).toBeVisible()
    await element(by.id('username')).typeText('ken@test.xyz\n')
    await element(by.id('password')).typeText('password\n')
    await screenIsVisible(isBalancesScreenMatcher)
  })
})
```

**Screenshots**
Failure in CI: 🚫 
the second input is blank

![Screenshot 2020-12-29 at 11 38 14](https://user-images.githubusercontent.com/48229166/103257000-5c8e8e80-49ca-11eb-8a13-263d2a98a874.png)

**Expected behavior**
On my computer; it never fails ✅ 
gif:
![Kapture 2020-12-29 at 11 27 45](https://user-images.githubusercontent.com/48229166/103256974-3c5ecf80-49ca-11eb-8086-b1fda06e2a49.gif)

**Device and Verbose Detox Logs**
https://gist.github.com/kg-currenxie/829671b98ee5d4cad3de78c4d21034b5

**Environment (please complete the following information):**
 - Detox: 17.14.3
 - React Native: 0.61.5
 - Node: 12
 - Device: Pixel (1)
 - OS: Android 29
 - Test-runner (select one): `jest`

(Using CircleCI and Android emulator in a MacOS executor)

**Comment by kg-currenxie** [comment]
Should be re-opened :P

**Comment by d4vidi** [comment]
Hey @kg-currenxie! According to the logs, something is keeping Espresso from properly injecting the finger-down & finger-up event of the tap on _password_. Would you mind enabling taps animation and the pointer-location bar and send us the recorded from the CI execution? Execute this:
```
adb shell settings put system pointer_location 1
adb shell settings put system show_touches 1
```

To record videos, you can pass the `--record-video all` argument to `detox test`. The recorded videos will be available on your CI machine under `artifacts/` (by default).

**Comment by d4vidi** [comment]
Also, as a secondary course of action, would you mind adding a ~100 sleep between the two taps (user and password) -- to see whether it solves anything (please report back...)

**Comment by kg-currenxie** [comment]
Seems we've found a way that seems more consistent:

Previous: 
```
function fillInput(id, value) {
  return element(by.id(id)).typeText(value)
}

and

fillInput('password', 'cx-pass\n') // new-line character to submit
```

New:
```
async function fillInput(id, value, dismiss) {
  const inputElement = element(by.id(id))
  await expect(inputElement).toBeVisible() // make sure it's visible first

  if (dismiss) {
    await inputElement.replaceText(value)
    return inputElement.tapReturnKey() // instead of new-line character
  } else {
    return await inputElement.replaceText(value)
  }
}
```

We can close this issue :)

**Comment by d4vidi** [comment]
@kg-currenxie it doesn't seem like we can close the issue just yet, as your code suggests something might be unstable with `element.typeText()`.

Could you please assist a bit further, and do some/all of the following? -
1. Provide the *device* logs so we could get a better look into where things fail
2. Switch to an [AOSP emulator](https://github.com/wix/Detox/blob/master/docs/Introduction.AndroidDevEnv.md#android-aosp-emulators) and reexamine the stability of the test.
3. Work out an ultra simple example app where this takes place.

**Comment by d4vidi** [comment]
@kg-currenxie could you please try again using the latest Detox (v18), alongside the `--debug-synchronization 3000` argument to your `detox test` command?
