### ISSUE TITLE
Cannot find element by disabled trait

### ISSUE THREAD

**Issue by IkerArb** [wix/detox#256]
#### Description
I want to validate a form that when the inputs are not filled out correctly that the submit button is disabled, I have tried the by.traits(['disabled`]) but it doesn't seem to work.

#### Steps to Reproduce
I provided a touchable opacity with the disabled prop true in the following way

````
      <TouchableOpacity
        ref={(component) => { this.button = component; }}
        style={[styles.container, this.props.style]}
        onPress={this.props.onPress}
        disabled={this.props.disabled}
        testID={this.props.testID}
      >
      <Text style={styles.text}>
        {this.props.text}
      </Text>
    </TouchableOpacity>
````
and my test is written in the following way:

`````
await expect(element(by.traits(['disabled']))).toExist();
`````
#### Node, Device, Xcode and macOS Versions

* Node: 8.4.0
* Device: ios Simulator (iPhone 6 10.3)
* Xcode: 8.3.3
* macOS: 10.12.6

**Comment by mfrachet** [comment]
I'm not sure the `disabled` traits exists :/ . In fact I don't really understand the concept of traits. But from the Apple documentation, `disabled` traits doesn't seem to exist.

Maybe this one would help you [UIAccessibilityTraitNotEnabled](https://developer.apple.com/documentation/uikit/uiaccessibilitytraitnotenabled) ?

**Comment by IkerArb** [comment]
I totally forgot EarlGrey is connected to native traits, I was looking upon this ones http://facebook.github.io/react-native/releases/0.48/docs/accessibility.html#accessibilitytraits-ios

I will try with that trait

**Comment by IkerArb** [comment]
I got this error:
`````
Error: Unknown trait 'UIAccessibilityTraitNotEnabled', see list in https://facebook.github.io/react-native/docs/accessibility.html#accessibilitytraits-ios
``````
What can I do?

**Comment by mfrachet** [comment]
I've probably pushed you in a bad direction. `disabled` seems to be a valid traits

Can you try by using 

```
<View
...
accessibilityTraits="disabled"
/>
```

**Comment by IkerArb** [comment]
I did it like this and it worked:

`````
<TouchableOpacity
        ref={(component) => { this.button = component; }}
        style={[styles.container, this.props.style]}
        onPress={this.props.onPress}
        disabled={this.props.disabled}
        testID={this.props.testID}
        accessibilityTraits={this.props.disabled ? ['button', 'disabled'] : ['button']}
      >
        <Text style={styles.text}>
          {this.props.text}
        </Text>
      </TouchableOpacity>
``````
and the test like this:

``````
await expect(
    element(
      by.traits(['button', 'disabled']).and(
      by.id('sampleId'))
  )).toExist();
``````
Thanks!!
