### ISSUE TITLE
Detox build failed using Github actions

### ISSUE THREAD

**Issue by Zakyyy** [wix/Detox#2562]
<img width="908" alt="Screen Shot 2020-12-31 at 12 18 51 AM" src="https://user-images.githubusercontent.com/25394763/103384082-c5c2ee80-4afd-11eb-9c07-79914d035d14.png">

**Comment by LeoNatan** [comment]
Please don't open multiple issues. It's closed for a reason. It seems like your app build command is faulty and that is why your app is failing build. Unrelated to Detox.
