### ISSUE TITLE
 Since v18 upgrade - App has not responded to the network requests below:   (id = -1000) isReady: {}

### ISSUE THREAD

**Issue by kmistry27** [wix/Detox#2568]
I am running Detox with Expo.

Prior to upgrading to v18 of detox, I used to get the following error:

```
detox[7528] WARN:  [Client.js/PENDING_REQUESTS] App has not responded to the network requests below:
  (id = -1000) isReady: {}

That might be the reason why the test "your test" has timed out.
```

I managed to fix this issue by following the fix provided here: https://github.com/expo/detox-tools/issues/1#issuecomment-740675824. (tl;dr, make some changes to the detox expo helpers in node modules).

After upgrading to Detox 18.0.1, I have made the amendments noted in the v18.0.0 migration release (specifically to the custom detox environment class). But, I am now getting the same error as above. I have reverted the changes made in the node modules (mentioned above) and still no luck.

I have the following related packages:
```
    "detox": "^18.0.1",
    "detox-expo-helpers": "^0.6.0",
    "expo": "^38.0.0",
    "expo-detox-hook": "^1.0.10",
    "jest": "^26.6.3",
    "jest-circus": "^26.6.3",
    "jest-expo": "^39.0.0",
```

**Comment by LeoNatan** [comment]
Please use the latest 18.0.2, 18.0.1 had an issue and was reverted.

**Comment by MoeMamdouh** [comment]
I had the same issue in iOS **release** build event it was working in **debug** build 
my current react native version `"react-native": "0.61.5"`



i fix it by add in info.plist file

```
<key>NSAllowsArbitraryLoads</key>
<true/>
```
which is added by default since react-native version 0.64

**Comment by d4vidi** [comment]
@MoeMamdouh Setting `NSAllowsArbitraryLoads` to `true` enables _all_ unsecure HTTP traffic and is therefore a bad approach. It can get your app to fail app-store reviews. Read all about it [here](https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity/nsallowsarbitraryloads). Consider using [NSAllowsLocalNetworking](https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity/nsallowslocalnetworking), instead.
