### ISSUE TITLE
Updating to V18 causes detox to hang (App has not responded to the network requests below:   (id = -1000) isReady: {})

### ISSUE THREAD

**Issue by OrLevy23** [wix/Detox#2569]
### Description
I've just updated detox to 18.0.1 (from 17.8.3) and i can't seem to run tests ever since
getting this error: 
```
App has not responded to the network requests below:
  (id = -1000) isReady: {}
```
also i saw that when running `device.launchApp()` it seems to hang (although it passes successfully) 
I was able to use the simulator so i suspect something is wrong with the hook.
Downgrading to v17.8.3 solves this right away

- [X ] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction
update to version 18.0.1
run e2e tests

#### Environment (please complete the following information):
 - Detox: 18.0.1
 - React Native: 0.63.3
 - Using Jest (but also was able to reproduce it in mocha)
 - Node: 15.3.0
 - Device: iPad Pro (12.9-inch) (4th generation) (OS 14.2) 
 - Xcode: 12.2
 - iOS: 14.2
 - macOS: 11.0.1

### Logs
```
detox[57762] WARN:  [Client.js/PENDING_REQUESTS] App has not responded to the network requests below:
  (id = -1000) isReady: {}

Unresponded network requests might result in timeout errors in Detox tests.
```

Thanks in advance for the help

**Comment by LeoNatan** [comment]
Can you please test 18.0.0? I've heard some issues have arisen in 18.0.1.

**Comment by LeoNatan** [comment]
Also please attach the low level sync resources debug, as requested in the template. Thanks

**Comment by mataspetrikas** [comment]
same issue here as well: 
with 18.0.2, Xcode 12.3, simulator 14.3

app closes immediately after splash screen

**Comment by LeoNatan** [comment]
@mataspetrikas Sounds like you are having a crash. Please follow https://github.com/wix/Detox/blob/master/docs/Guide.DebuggingInXcode.md and post here the results.

**Comment by OrLevy23** [comment]
so @LeoNatan several things here:
 - switching to v18.0.0 did not solve the problem
 - running with 
 -  When i terminate test i saw crash from springboard (it happened to me several times only with this specific version)  - attaching logs 
 ```
Process:               SpringBoard [39258]
Path:                  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/CoreServices/SpringBoard.app/SpringBoard
Identifier:            SpringBoard
Version:               1.0 (50)
Code Type:             X86-64 (Native)
Parent Process:        launchd_sim [51847]
Responsible:           SimulatorTrampoline [598]
User ID:               501

Date/Time:             2021-01-05 11:31:07.235 +0200
OS Version:            macOS 11.0.1 (20B50)
Report Version:        12
Bridge OS Version:     5.0.1 (18P2561)
Anonymous UUID:        04EDBE3F-96DB-B098-03E4-5180B1271873

Sleep/Wake UUID:       DC648508-4BDF-4F17-B077-6C113C32DB29

Time Awake Since Boot: 320000 seconds
Time Since Wake:       91000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.frontboard.inprocessdataclient.prefetchqueue

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
LaunchServices observer: Installed (
    "<LSApplicationProxy: 0x6000002b4750> com.tapingo.kiosk file:///Users/orlevy/Library/Developer/CoreSimulator/Devices/8719B6CD-FBA9-42CF-A4F1-CB71A8DA8FEC/data/Containers/Bundle/Application/C1850B5E-32EC-44CD-9088-70DB52605291/TapingoKiosk.app/ <com.tapingo.kiosk <installed >:0>"
) {3C36C5DE-24E0-4C16-9FB8-82B722120F37 1908}
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSDictionaryM setObject:forKey:]: key cannot be nil'
terminating with uncaught exception of type NSException
abort() called
CoreSimulator 732.18.0.2 - Device: iPad Pro (12.9-inch) (4th generation) (8719B6CD-FBA9-42CF-A4F1-CB71A8DA8FEC) - Runtime: iOS 14.2 (18B79) - DeviceType: iPad Pro (12.9-inch) (4th generation)

```

**Comment by OrLevy23** [comment]
the one thing i saw which is a bit different is the error:
```
detox[39542] WARN:  [Client.js/PENDING_REQUESTS] App has not responded to the network requests below:
  (id = 2) waitForActive: {}
  (id = -1000) isReady: {}

Unresponded network requests might result in timeout errors in Detox tests.

```

**Comment by OrLevy23** [comment]
app seems to launch properly (and work properly) but test does not run at all

**Comment by LeoNatan** [comment]
@OrLevy23 Please follow https://github.com/wix/Detox/blob/master/docs/Troubleshooting.Synchronization.md#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much and post the output here. Thanks

**Comment by OrLevy23** [comment]
@LeoNatan i see a lot of ```2021-01-05 15:46:36.903 Db TapingoKiosk[10609:edc3dd] [com.wix.DetoxSync:SyncManager] 👎 17 views awaiting layout
⏱ 18 views awaiting display
⏱ 30 layers awaiting layout
⏱ 20 layers awaiting display
⏱ 2 view animations pending (count: 87)
```


i can't really post the full log here as it exceeds maximum char count

**Comment by LeoNatan** [comment]
Don't run the advanced log, just launch the test with `--debug-synchronization 500` and post that. Thanks

**Comment by OrLevy23** [comment]
I don't get any logs for `-debug-synchronization 500` 
only for advanced

**Comment by LeoNatan** [comment]
Hmm? But if the test is stuck, you should be seeing outputs. Maybe add `--loglevel verbose`.

**Comment by LeoNatan** [comment]
Also, just to make sure, it's `--debug-synchronization` with two dashes.

**Comment by OrLevy23** [comment]
I'm running the following:
`"node_modules/.bin/detox test --configuration debug --debug-synchronization 500  --loglevel verbose --record-videos failing --take-screenshots=failing  --record-logs=failing  --detectOpenHandles --force-exit`

the only log that i see is this:
```
detox[26309] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=app not connected, cannot fw action (sessionId=19c99c1b-90f6-4919-9c9c-19c183ee71f5)
detox[26309] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=app not connected, cannot fw action (sessionId=19c99c1b-90f6-4919-9c9c-19c183ee71f5)
detox[26309] DEBUG: [DetoxServer.js/LOGIN] role=app, sessionId=19c99c1b-90f6-4919-9c9c-19c183ee71f5
detox[26309] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=app, sessionId=19c99c1b-90f6-4919-9c9c-19c183ee71f5
```

**Comment by LeoNatan** [comment]
Hmm
@noomorph Any suggestions?

**Comment by noomorph** [comment]
No idea at the moment. I am debugging our Kompot tests that have the same issue with launchApp.

**Comment by LeoNatan** [comment]
@noomorph Do you think it’s something in JS or in iOS?

**Comment by LeoNatan** [comment]
@OrLevy23 Do you have any animation on launch that isn't hidden once loading is completed?

**Comment by noomorph** [comment]
Well, in my case I can see repeatedly printed messages like these:

```
Dispatch Queue
⏱ Queue: "Main Queue (<OS_dispatch_queue_main: com.apple.main-thread>)" with 1 work blocks

...
```

**Comment by OrLevy23** [comment]
@LeoNatan i've commented out any animations. 
as i said, switching back to v17.8.3 solves it so i doubt this is the case

**Comment by LeoNatan** [comment]
Detox 18 uses a completely new synchronization backend.

**Comment by dwightdhooge** [comment]
Same errors here on android and iOS simulators . Tested with 8.0.0 & 8.1.0 
` Reloading app
detox[22637] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=app not connected, cannot fw action (sessionId=bd1bea7f-b667-2f68-da82-8e7513392493)
detox[22637] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=app not connected, cannot fw action (sessionId=bd1bea7f-b667-2f68-da82-8e7513392493)`

**Comment by LeoNatan** [comment]
@dwightdhooge On iOS, what do you see happen in the simulator?

**Comment by mitchcivic** [comment]
Having the same issue.  In my case the app installs in the simulator but does not launch.
.

**Comment by LeoNatan** [comment]
@mitchcivic So you don't see the app launch at all? 

CC @noomorph

**Comment by mitchcivic** [comment]
@LeoNatan correct.  The app does not launch at all.  I can see it install in the simulator, but it never launches.  Debug message is the same as @dwightdhooge posted.

https://user-images.githubusercontent.com/42552268/104128691-f258e080-531d-11eb-8a68-df5ace4e623f.mov

**Comment by LeoNatan** [comment]
Thanks for the video. 

@noomorph This looks like a bug in the JS, not like the issue you had internally with the activity indicator.

**Comment by noomorph** [comment]
@LeoNatan, but I think you remember that we do not launch app by default since Detox 18. Developers should write `device.launchApp()` explicitly, do no surprise.

**Comment by LeoNatan** [comment]
🤦‍♂️
But we said we'd add a warning, no? I totally forgot about this.

**Comment by dwightdhooge** [comment]
@LeoNatan I had the same behaviour as @mitchcivic. App is installed but not launched. I do have the device.launchApp() in my before method

**Comment by d4vidi** [comment]
@mitchcivic @dwightdhooge as @noomorph explained, there was a change in policy such that `detox.init()` does not launch the app anymore. Please refer to the [migration guide](https://github.com/wix/Detox/blob/master/docs/Guide.Migration.md#180) for the complete info.

As for other matters - please submit separate issues and follow the templated. We'd be happy to assist, provided all necessary info 👍🏻

**Comment by nenjamin2405** [comment]
I'm having the same issue. I used Detox in the past and it worked fine. But for this new project, I installed the latest version and facing the same error reported above.

In my case, I just tried to run an firstTest example, below is the code:

```
import { by, element, expect, device } from 'detox';

describe('Example', () => {
  beforeAll(async () => {
    await device.launchApp({
      launchArgs: {
        DTXEnableVerboseSyncSystem: 'YES',
        DTXEnableVerboseSyncResources: 'YES',
      },
    });
  });

  beforeEach(async () => {
    await device.reloadReactNative();
  });

  it('should have welcome screen', async () => {
    await expect(element(by.id('passcode-input'))).toBeVisible();
  });
});

```
And the screenshot below describe what I faced. Actually the app is launched normally, but it will hang and log the report after the time out.

![image](https://user-images.githubusercontent.com/16648769/104697947-1fa0f680-5743-11eb-9aab-320acd5ee4ad.png)

**Comment by LeoNatan** [comment]
@noomorph How do we debug this further? This is clearly an issue.

**Comment by noomorph** [comment]
@nenjamin2405 , could you please open a separate issue and post log artifacts from the device?

**Comment by LeoNatan** [comment]
Guys, please update to the latest version of Xcode, and follow the following guide:
https://github.com/wix/Detox/blob/master/docs/Troubleshooting.Synchronization.md#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much

There is a link to a document there that explains why Detox thinks an app is not idle. Please read it and report back. Thanks

**Comment by OrLevy23** [comment]
@LeoNatan  i've updated to latest version and now i see this indeed:
```
1 layer animation pending
```

but no animation exist on the screen. any way to pinpoint what animation is hanging? i suspect that it has nothing to do with the animations we do in the code (because at that point non of them are visible) but rather something else

**Comment by LeoNatan** [comment]
Unfortunately, no, due to how animations are implemented on iOS. But I assure you, it's an animation. Perhaps an animated GIF, or an activity indicator view.

**Comment by OrLevy23** [comment]
ok i got it, it was indeed an activity indicator.
now i'm facing other issue when test launch starts too early (before screen is even loaded) and tests fail due to that. 
i can probably solve it using waitFor but is this really needed?

**Comment by LeoNatan** [comment]
No. Sounds like your synchronization is disabled?

**Comment by LeoNatan** [comment]
Do you have any native components that do something in the background?

**Comment by OrLevy23** [comment]
Ok nevermind it was my bad (instead of removing activity indicator I display it and hide when everything launches ok)
I think we can close this issue.
Thanks all for the help this new version with explicit logs is very helpful with identifying this kind of issues.

**Comment by LeoNatan** [comment]
Great. Thanks
