### ISSUE TITLE
Multiple sync issue as of 18.0.0 

### ISSUE THREAD

**Issue by watadarkstar** [wix/Detox#2586]
### Description

- [ ] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

1. 
2. 
3. 
4. 

#### Environment (please complete the following information):
 - Detox:
 - React Native:
 - Node:
 - Device:
 - Xcode:
 - iOS:
 - macOS: 

#### If you are experiencing a timeout in your test
- [ ] I have followed the instructions under [Lower-level Idling Resources Debug](https://github.com/wix/Detox/blob/master/docs/Troubleshooting.Synchronization.md#lower-level-idling-resources-debug-ios-only) and am providing the log below:

#### If you are seeing a build problem (e.g. during `npm install`)
- [ ] I am providing the `npm install` log below:

#### Device and verbose Detox logs
- [ ] I have run my tests using the `--loglevel trace` argument and am providing the verbose log below:

**Comment by d4vidi** [comment]
Sorry, there's no way we can assist with the submission of nothing more than the issue template......
Anyways, you are welcome to retry using Detox 18.1.1.

**Comment by watadarkstar** [comment]
@d4rky-pl Ah sorry must have accidentally pressed submit before I finished writing.
