### ISSUE TITLE
Unable to resolve module `util` from `node_modules/detox/src/Detox.js`

### ISSUE THREAD

**Issue by DanielDanaee** [wix/Detox#2589]
When i try to run the app, i get this error.

I have removed node_modules folder many times and ran yarn or npm install, no change. 

If i install one missing dependency it keeps asking for more.

`Unable to resolve module 'util' from 'node_modules/detox/src/Detox.js': util could not be found within the project.  If you are sure the module exists, try these steps:  1. Clear watchman watches: watchman watch-del-all  2. Delete node_modules: rm -rf node_modules and run yarn install  3. Reset Metro's cache: yarn start --reset-cache  4. Remove the cache: rm -rf /tmp/metro-*  RCTFatal __28-[RCTCxxBridge handleError:]_block_invoke _dispatch_call_block_and_release _dispatch_client_callout _dispatch_main_queue_callback_4CF __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ __CFRunLoopRun CFRunLoopRunSpecific GSEventRunModal -[UIApplication _run] UIApplicationMain main start`

**Comment by noomorph** [comment]
Make sure you are not importing Detox from the source code of your mobile application. It should run only in Node.js environment.
