### ISSUE TITLE
Detox@5.6.1 npm@5.4.0 fails with Permission denied

### ISSUE THREAD

**Issue by isnifer** [wix/detox#259]
I have updated npm to 5.4.0 and detox start fail on `postinstall` step.

#### Description
Something has changed in npm@5.4.0. I've created an issue about it on [npm#18379](https://github.com/npm/npm/issues/18379)

#### Steps to Reproduce
```sh
npm i npm@5.4.0 -g
mkdir test-detox && cd test-detox
npm init -y
npm i detox
```

#### Node, Device, Xcode and macOS Versions

* Node: v8.4.0
* Npm: 5.4.0 

![image](https://user-images.githubusercontent.com/1788245/29994164-dff5f076-8fd1-11e7-9c9d-c970e31abcca.png)

**Comment by dluksza** [comment]
Any update on this issue? I can't run my detox tests because of it :|

**Comment by zhgqthomas** [comment]
I have this error too. Please help us solve it.

**Comment by isnifer** [comment]
@dluksza @zhgqthomas As I can see @iarna fixed it in https://github.com/npm/npm/commit/767ff6eee7fa3a0f42ad677dedc0ec1f0dc15e7c. So, just update `npm` to `5.4.1`

**Comment by dluksza** [comment]
@isnifer bumping npm to 5.4.1 resolved this issue, thanks!
