### ISSUE TITLE
Exceeding timeout when using onRefresh prop

### ISSUE THREAD

**Issue by NazarB99** [wix/Detox#2590]
I have A FlatList like this
`<FlatList
            data={this.state.loading ? this.placeholderData() : this.filterMy()}
            keyExtractor={(item) => item.id.toString()}
            extraData={this.state.loading}
            refreshing={this.state.loading}
            onRefresh={() => this.onRefresh(true)}
            stickyHeaderIndices={[0]}
            renderItem={this.renderItem}
            getItemLayout={(data, index) => ({
              length: perfectSize(72),
              offset: perfectSize(72) * index,
              index,
            })}
            onScroll={({nativeEvent}) => {
              if (
                nativeEvent.contentSize.height * 0.3 <=
                  nativeEvent.contentOffset.y &&
                this.props.user &&
                !this.state.listLoading &&
                this.state.page < this.props.totalPages
              ) {
                this.setState({
                  ...this.state,
                  page: this.state.page + 1,
                  listLoading: true,
                });
              }
            }}
            ListHeaderComponent={
              <Header
                searchValue={this.state.searchText}
                onSubmitEditSearchText={() => {
                  if (this.state.searchText.length > 0) {
                    this.onRefresh();
                  }
                }}
                setSearchText={(text) => {
                  if (this.state.searchText.length > 0 && text.length === 0) {
                    this.onRefresh(true, this.state.filterMode);
                  } else {
                    this.setState({...this.state, searchText: text});
                  }
                }}
                renderText={this.state.filterMode}
                setFilterMode={(mode) => {
                  this.onRefresh(false, mode);
                }}
                headerText={translate('Inbox')}
                chevronDown={true}
              />
            }
            ListFooterComponent={
              this.props.dialogList.length > 0 && this.state.listLoading ? (
                <View style={styles.listFooter}>
                  <ActivityIndicator size="large" color={MAIN_BLUE} />
                </View>
              ) : null
            }
          />`

When I am using it like in the code above it exceeds the timeout. But if you comment out onRefresh prop, tests start to work and they are passing successfully

onRefresh function is quiet simple:
`onRefresh(clearText = false, mode = null) {
    console.log('onrefresh')
  }
`

**Comment by NazarB99** [comment]
No, it's not a general issue

**Comment by LeoNatan** [comment]
The problem is likely your `ActivityIndicator` creating an infinite animation, which makes Detox think the app is not idle.

**Comment by NazarB99** [comment]
> The problem is likely your `ActivityIndicator` creating an infinite animation, which makes Detox think the app is not idle.

And solution? For every detox execution, I have to comment out onRefresh prop?

**Comment by ball-hayden** [comment]
I'm also seeing this behaviour on `SectionList` and `ScrollView` components with a `refreshControl`.
I don't have any custom loader components etc.

I'll try and get together a minimal reproduction.

**Comment by LeoNatan** [comment]
The animation has to stop for Detox to see an idle app. The native refresh control, as well as UIActivityIndicatorView stop animating when they are stopped. 

https://developer.apple.com/documentation/uikit/uiactivityindicatorview

You need to figure out why the components you are using are still animating after whatever task you are performing (such as loading from network or disk) finishes.

**Comment by ball-hayden** [comment]
Thanks @LeoNatan.

My suspicion is that this is actually a bug in the React Native (core) components, but I have been able to put together a minimal reproduction:

https://github.com/PlayerData/DetoxSectionlistRepro/blob/main/App.tsx

Note that `loading` is definitely set to `false`, so the loader _should_ be stopped, but Detox thinks it's still animating.

**Comment by ball-hayden** [comment]
I should add - the issue goes away if `setData` and `setLoading` are called at the same time.
So the issue appears when there is a render in which only the loading state changes, after the data has already been changed.

In reality, this happens a lot while using the Apollo Client GraphQL library - it provides data from a cache, then later sets the `loading` state to `false` once it has checked with the network server.

**Comment by LeoNatan** [comment]
Run your app in Xcode following our guide. Once Detox reaches the point where it is stuck on the loader, open the UI hierarchy inspector in Xcode. See if the indicator is in animating state. If, for example, it is only “hidden” with alpha=0, but still animating internally, that won’t do (and is wasting resources of users’ phones).

**Comment by LeoNatan** [comment]
This guide:
https://github.com/wix/Detox/blob/master/docs/Guide.DebuggingInXcode.md

**Comment by ball-hayden** [comment]
Thanks again @LeoNatan, and I agree that I don't want this sticking around and animating.

I've attached the XCode debugger and got a UI hierarchy that does indeed show that a `_UIScrollViewScrollIndicator` is rendered with an alpha of 0.

However, you'll note that in my sample repo I haven't provided an indicator. Would you agree with my suggestion that this is a bug in (or even feature of) the core `SectionList` component?

**Comment by LeoNatan** [comment]
_UIScrollViewScrollIndicator Is something else. That's the little bar that pops up when you scroll. That's not your problem.

Look for UIRefreshControl or UIActivityIndicatorView.

**Comment by ball-hayden** [comment]
My apologies for the screenshot, but I can't think of a better way to share this.
This is the view hierarchy. I can't see any `UIRefreshControl` or `UIActivityIndicatorView`.

![Screenshot 2021-02-12 at 12 31 29](https://user-images.githubusercontent.com/1596233/107768396-421c3480-6d2e-11eb-9d91-c4c58fbd4a9a.png)

If you run my sample, are you able to reproduce the issue?

**Comment by LeoNatan** [comment]
Using Xcode, you can export the view hierarchy from the menu. Upload that. I'm not sure I'll have time to run the example project.

**Comment by ball-hayden** [comment]
Thank you for your help @LeoNatan, and no worries.

Here's the view hierarchy, zipped to appease GitHub: [DetoxSectionlistRepro[71354].zip](https://github.com/wix/Detox/files/5971784/DetoxSectionlistRepro.71354.zip)

**Comment by LeoNatan** [comment]
I see nothing in that view hierarchy that is suspicious; are you sure it was captured when Detox thinks there is an animation? What do you see when running your test using `--debug-synchronization 200`?

**Comment by ball-hayden** [comment]
Afirm - that was definitely captured while Detox was hanging.

I'd been running with `--debug-synchronization 5000`:

```
yarn detox test --debug-synchronization 5000
yarn run v1.22.10
$ /Users/hayden/development/GitHub/DetoxSectionlistRepro/node_modules/.bin/detox test --debug-synchronization 5000
detox[71716] INFO:  [test.js] DETOX_DEBUG_SYNCHRONIZATION=5000 DETOX_REPORT_SPECS=true DETOX_START_TIMESTAMP=1613133920738 DETOX_USE_CUSTOM_LOGGER=true jest --config e2e/config.json --testNamePattern '^((?!:android:).)*$' --maxWorkers 1 e2e
detox[71717] INFO:  [DetoxServer.js] server listening on localhost:59726...
detox[71717] INFO:  [AppleSimUtils.js] org.reactjs.native.example.DetoxSectionlistRepro launched. To watch simulator logs, run:
        /usr/bin/xcrun simctl spawn 34658A98-C0D1-4F76-8B2D-B8152DB33003 log stream --level debug --style compact --predicate 'process == "DetoxSectionlistRepro"'
detox[71717] INFO:  [actions.js] The system is busy with the following tasks:

Dispatch Queue
⏱ Queue: “Main Queue (<OS_dispatch_queue_main: com.apple.main-thread>)” with 1 work item

Run Loop
⏱ “Main Run Loop”

UI Elements
⏱ 1 view animation pending
⏱ 1 CA animation pending
detox[71717] INFO:  [actions.js] The system is busy with the following tasks:

Dispatch Queue
⏱ Queue: “Main Queue (<OS_dispatch_queue_main: com.apple.main-thread>)” with 1 work item

Run Loop
⏱ “Main Run Loop”

UI Elements
⏱ 1 view animation pending
⏱ 1 CA animation pending
```

The output is the same with `--debug-synchronization 200`, albeit more frequently.

**Comment by LeoNatan** [comment]
Yes, it thinks there is an animation going somewhere. Not sure what’s going on.

**Comment by ball-hayden** [comment]
Would you consider reopening this issue, please, since there appears to be a reproducible problem when using the `refreshing` / `onRefresh` props?

**Comment by LeoNatan** [comment]
Any chance for a simple project without TS? Just a `react-native init <bla>` with the needed UI change to trigger the issue?

**Comment by ball-hayden** [comment]
Sure - that's updated now.

**Comment by LeoNatan** [comment]
I see some animation related to the refresh control, but still not sure why it never ends. Investigating.

**Comment by LeoNatan** [comment]
Something goes wrong with the refresh control animations that is not tracked correctly.

**Comment by LeoNatan** [comment]
Fixed. Should work now.

**Comment by ball-hayden** [comment]
Thank you @LeoNatan 🎉

**Comment by rcwestlake** [comment]
@ball-hayden @LeoNatan we are running into the same issue. We are consistently getting this:
![image](https://user-images.githubusercontent.com/9679076/123668374-45552000-d7f8-11eb-831c-28ff342bd3e0.png)

The issue seems to be here:
![image](https://user-images.githubusercontent.com/9679076/123668598-7c2b3600-d7f8-11eb-9be6-2a93a107e123.png)


When I remove the `RefreshControl` from the `ScrollView` the tests pass. All `fetchAccounts` does is this:

```
  const fetchAccounts = async () => {
    setIsLoading(true);
    const api = new CAPI();
    await api.useAuth();
    const externals = await api.fetchExternalAccounts(); // this makes a call to our mock server
    setExternalAccounts(externals);
    setIsLoading(false);
  };
```

Other details:
- `"react-native": "~0.63.4"`
-  `"detox": "^18.11.1",`

I can create a new project for debugging but before going through all of the debug steps, wanted to see if there's something obvious I'm overlooking or if you're expecting this to no longer an issue. If it was a larger issue I would be surprised that more people aren't complaining. I can't imagine we're the only folks to use the `RefreshControl`.

**Comment by ball-hayden** [comment]
@rcwestlake feel free to fork https://github.com/PlayerData/DetoxSectionlistRepro as a starting point if you'd like.
We haven't been seeing this, but I think we've still got workarounds in some places (disabling the loader when running E2E tests).

**Comment by rcwestlake** [comment]
Thanks @ball-hayden, I'll work on getting a repo up.

**Comment by ball-hayden** [comment]
@rcwestlake - there is now an official template from @alon-ha - you may be better using that:
https://github.com/wix-incubator/DetoxTemplate
