### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by hqdai** [wix/Detox#2592]
### Description
When running test for 100 to 200 scenarios, I always get this issue. All test suites on my project might take more than 4 hours for complete. But when showing this error, the test process will be stuck and I can't run completely all test suite.

#### Expected behavior
Is there a way to increase the node JS timeout in DETOX (--max-old-space-size)? When doing research the node JS script, people ask to change this number, but I'm not sure about that.

#### Screenshots
<img width="916" alt="Screen Shot 2021-01-13 at 05 55 13" src="https://user-images.githubusercontent.com/19548213/104550374-4984eb00-5667-11eb-9422-b9196dea3659.png">

#### Environment (please complete the following information):
 - Detox: 17.11.4
 - React Native: 0.60.5
 - Node: 10
 - Device: iPhone 11
 - Xcode: 11.7
 - iOS: 13.7
 - macOS: 10.15.6

**Comment by noomorph** [comment]
Thanks for the report! Looks interesting, although it might take time to get to your issue — as far as I could understand, to reproduce it, I might need about 200-300 autogenerated dummy test files and run them all.

As for workarounds. I can't tell if this is going to work out, but indeed you could try prepending `NODE_OPTIONS` environment variable to your `detox test` command — something like this:

```
NODE_OPTIONS="--max-old-space-size=8192" detox test ...
```

**Comment by hqdai** [comment]
> Thanks for the report! Looks interesting, although it might take time to get to your issue — as far as I could understand, to reproduce it, I might need about 200-300 autogenerated dummy test files and run them all.
> 
> As for workarounds. I can't tell if this is going to work out, but indeed you could try prepending `NODE_OPTIONS` environment variable to your `detox test` command — something like this:
> 
> ```
> NODE_OPTIONS="--max-old-space-size=8192" detox test ...
> ```

It works, I'm not getting in this error anymore, thank you so much <3 <3 <3

**Comment by d4vidi** [comment]
@hqdai as for the huge amount of time it takes to run your tests -- have you tried applying parallel test execution (i.e. the `--workers` argument to `detox test`) in your suite?
