### ISSUE TITLE
Ignoring specified requests to fix auto sync issues for using server sent events

### ISSUE THREAD

**Issue by ismail-codar** [wix/Detox#2596]
PROBLEM:
I am using [rn-eventsource](https://github.com/adamchel/rn-eventsource) for using [server side events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events) on the react-native.  My tests timeouts because "Detox monitors in-flight requests over the network" But server send events request never ends

SUGGESTED SOLUTION:
An option can be defined to ignore some url patterns in detox.config.js
Example:
`ignoreNetworkRequestsPattern: /connections/sse-callbacks/*/**`

**Comment by LeoNatan** [comment]
https://github.com/wix/Detox/blob/master/docs/APIRef.DeviceObjectAPI.md#11-detoxurlblacklistregexinitialize-the-url-blacklist-at-app-launch

?

**Comment by ismail-codar** [comment]
Thanks @LeoNatan

**Comment by LeoNatan** [comment]
👍

Cheers
