### ISSUE TITLE
DetoxInitOptions type is missing the launchApp parameter

### ISSUE THREAD

**Issue by markpar** [wix/Detox#2599]
### Description
When Detox 18.1.0 was released, it moved the TypeScript definitions from DefinitelyTyped into the Detox repo (which is awesome!).  However, the type `DetoxInitOptions` is missing the `launchApp` parameter, so attempting to use it results in TS error TS2345: `Argument of type X is not assignable to parameter of type Y`.

- [X] I have tested this issue on the latest Detox release and it still reproduces.  (Current release is `18.2.1` at time of issue creation.)

#### Reproduction

1.  Write a test that calls `init` with the `launchApp` parameter, e.g. 
```
await init(undefined, {initGlobals: false, launchApp: false});
```
2. Invoke `tsc`.  No need to emit the JS.
```
tsc --project tsconfig.json --noEmit --skipLibCheck
```

#### Expected behavior
`tsc` should complete with no errors.

#### Screenshots
Invocation of `tsc` and the resulting error.
![image](https://user-images.githubusercontent.com/6062009/104953966-47c76a00-597c-11eb-9c08-01beec522040.png)

#### Environment:
 - Detox:  `18.2.0` (issue was introduced in `18.1.0`)
 - React Native:  `0.63.3`
 - Node:  `12.18.3`
 - Device:  iPhone 11 simulator
 - Xcode:  `12.3 (12C33)`
 - iOS:  `14.3`
 - macOS:  `11.1`

The fix looks pretty straightforward:  just adding `launchApp` to `DetoxInitOptions` in `detox/index.d.ts`, but I'm not too familiar with the Detox codebase.  🙂

**Comment by markpar** [comment]
If the fix really is as straightforward as I suppose, I'd be happy to submit a PR.

**Comment by LeoNatan** [comment]
Please do. This argument might now not be needed anyway, because no longer launches the app on init. CC @noomorph

**Comment by LeoNatan** [comment]
See here:
https://github.com/wix/Detox/commit/164000bd1e857bbb14942457a2cd7665fa03fc1a

I don't think this property should be used anymore.

**Comment by noomorph** [comment]
Exactly, launchApp was removed in 18.0.0. The 18.1.0 just fixes that omission.

**Comment by markpar** [comment]
Ah, I didn't realize `launchApp` had been removed.  I removed it and, of course, all my app launches and terminations in test code worked just fine.  👍 

What the removal of `launchApp` documented or communicated somewhere?  I want to add it to my list of "Detox Info Sources" that I routinely monitor.  😄 

Thank you for the very rapid response!

**Comment by LeoNatan** [comment]
https://github.com/wix/Detox/blob/master/docs/Guide.Migration.md#180

> JS. detox.init() will not launch the app anymore (even if asked to do so in configuration). Launching the app explicitly with device.launchApp() is now mandatory.

**Comment by markpar** [comment]
Thanks a bunch!  And thanks for the killer framework, too.
