### ISSUE TITLE
Fail tests verbosely in case of concurrent invocations

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#2601]
## Description

It's been more than once that users have approached us with "weird issues" which root cause ended up being a missing `await` over a Detox expectation or interaction.

Sometimes, such a human error can be relatively easy to detect by going over the code. However, at times, this error can appear very elusive, such as in this (highly simplistic) example:

```js
async function tapOnOldButton() {
  // ...
  console.log('Tapped on old button');
}

async function tapOnNewButton() {
  // ...
  console.log('Tapped on new button');
}

async function tapOnButton(isNew) {
  await isNew ? tapOnNewButton() : tapOnOldButton();
}

it('blah blah', async () => {
  // ...
  await tapOnButton(true);
  console.log('Test is complete');
});

```
The resulting output is likely to be:
```
Test is complete
Tapped on new button
```

Which is not what the user intended for it to be, obviously.

As a much-needed enhancement, Detox can introduce a means to detect the invocation of an expectation/interaction while another one is in-flight. Upon detection, it would fail the test with a very descriptive error, hinting that there's been an ignored interaction promise and that most likely, an `await` is missing.

With this kind of a feature, we would be:
1. Improving the experience of testers and their overall satisfaction, esp. the ones running complex suites.
2. Reducing the time needed for support.

**Comment by noomorph** [comment]
I can certainly expand the `AsyncWebSocket` implementation so it has two queues: sync requests (99%) and async requests (CurrentStatus, as far as I can tell). It can throw errors if we are attempting to send something while the app has not responded to the previous something.

**Comment by d4vidi** [comment]
Sounds good - best to have this solved on the JS (tester) side. However, if not feasible, I'm confident we could sort this out on the device' end.
