### ISSUE TITLE
Jest circus doesnt reuse simulators

### ISSUE THREAD

**Issue by frederikvanhevel** [wix/Detox#2603]
Happens following the following guide: https://github.com/wix/Detox/blob/master/docs/Guide.Jest.md

When using the jest-circus test runner, every test suite starts a new simulator and doest close the old one.
When i remove that test runner from the config it behaves as expected and reuses and closes the simulator.

I tried to use the following config in init:

```
await detox.init(
        {
            behavior: {
                cleanup: { shutdownDevice: true }
            }
        },
        { reuse: true }
    )
```
But this doesn't help. I also added the --cleanup parameter to the `detox test` command.

**Comment by noomorph** [comment]
You should not be using detox.init() with the latest Detox and Circus integration. Please re-read the docs and move the behavior flags to the config accordingly.

Also the reuse flag has no relation to the device reuse. It is about not reinstalling the app, based on assumption you have installed it independently or on previous test run.

Please close the issue if it is resolved, or provide new details with the accurate bug description.

Thanks.

**Comment by frederikvanhevel** [comment]
Thanks! That works
