### ISSUE TITLE
takeScreenshot does not return image path?

### ISSUE THREAD

**Issue by mrados7** [wix/Detox#2606]
As far as I can see `takeScreenshot` does not return path of image?
It's return type of Promise\<void\>, also some of code examples are still using it like it returns path, but it doesn't.
![Screenshot 2021-01-20 at 13 43 21](https://user-images.githubusercontent.com/32796945/105176383-7df41d80-5b25-11eb-995f-67ef2c6cfcc7.png)

**Comment by LeoNatan** [comment]
@noomorph

**Comment by noomorph** [comment]
Oh. 😸 We only recently started supporting external typings, and since it was a community product earlier, there still might be discrepancies between the real Detox API and the type declarations.

Anyway, thanks to your reports we'll align them gradually.

Good that you've raised this issue. 👍
