### ISSUE TITLE
Testing Google Sign In with Detox

### ISSUE THREAD

**Issue by ShaunStanley** [wix/Detox#2607]
Hi,

I am a currently using Detox to test my RN app on android, and when i am testing the login section, my test failed. I had search the internet for solutions, and one of it was to mock for the react-native-community/google-signin.

With regards to mocking for react-native-community/google-signin, i could not find any detailed example. Thus, could anyone please help me out? Thank you.

**Comment by ZoltanSzokodi** [comment]
hi @ShaunStanley,

have you found a solution that you could share? I am facing the same issue.

**Comment by sammysium** [comment]
@ShaunStanley @ZoltanSzokodi likely not what you are looking for but I mocked the component/button which launches it. So the component is GoogleAuth.js in my case. I put GoogleAuth.e2e.js in same folder but mock it to return predefined user. Of course, the idToken will never be valid but if your backend depends on other info, it does work well.

**Comment by d4vidi** [comment]
Hot out of the oven is our support for web-views on Android (aka Detox-web). Perhaps that could help you out, at least for Android tests?
- [Release notes](https://github.com/wix/Detox/releases/tag/18.7.0)
- [Pull request](https://github.com/wix/Detox/pull/2538) with API details

**Comment by sammysium** [comment]
@d4vidi thanks so much! Looks promising!

**Comment by sammysium** [comment]
Gave it a shot with google sign in; it didn't work but might not be a detox issue.

`<input type="email" class="whsOnd zHQkBf" jsname="YPqjbf" autocomplete="username" spellcheck="false" tabindex="0"
aria-label="Email or phone" name="identifier" value="" autocapitalize="none"
id="identifierId" dir="ltr" data-initial-dir="ltr" data-initial-value="">`

this is from google login form. I am then doing:

`      await waitFor(web.element(by.web.cssSelector('#identifierId')))
        .toBeVisible()
        .withTimeout(15000);
      await web.element(by.web.cssSelector('#identifierId')).typeText('email');`

"Checking info...." takes about 10-13 seconds in my emulator so thought I would wait for it to finish then check if the element is visible but not working. Any input?

**Comment by d4vidi** [comment]
So what eventually happens when you do this - a timeout? @noomorph

**Comment by sammysium** [comment]
it exits with error:  Test Failed: Wait for [com.wix.detox.reactnative.idlingresources.AnimatedModuleIdlingResource] to become idle timed out

**Comment by d4vidi** [comment]
That suggests there is an infinite animation running indefinitely, somewhere - regardless of the sign in. A loader, maybe?

**Comment by sammysium** [comment]
well when you click the google signin button, it loads a loader on its own then opens the login page...not sure what happens to that loader after the login UI is loaded.

**Comment by d4vidi** [comment]
And that's the point where the test hangs? Can you share a screenshot?

**Comment by sammysium** [comment]
yes it shows the login screen, waits for some seconds then displays the error as you see blow

**Comment by sammysium** [comment]
![image](https://user-images.githubusercontent.com/46919720/111185797-0ab5d780-85bb-11eb-89b0-feb4f86406f0.png)
![Screenshot_1615825202](https://user-images.githubusercontent.com/46919720/111185870-1d301100-85bb-11eb-85c3-0e819a0782bd.png)
![Screenshot_1615825210](https://user-images.githubusercontent.com/46919720/111185876-1ef9d480-85bb-11eb-827b-77ab843751d4.png)

**Comment by sammysium** [comment]
the tap() action opens the google login...no loader is directly attached to it...it just calls signIn() method of google which shows the login UI

**Comment by sammysium** [comment]
any chance the google stuff runs on its own process that Detox can't detect? Happy to do a small PR for you to check out.

**Comment by d4vidi** [comment]
I would advise to temporarily disable sync and resort to sleeps in this case (although not recommended) using [`device.disableSynchronization()`](https://github.com/wix/Detox/blob/master/docs/APIRef.DeviceObjectAPI.md#devicedisablesynchronization) -- however there are issues on Android. I'll sort them out and report back.

**Comment by d4vidi** [comment]
On 2nd thought, `AnimatedModuleIdlingResource` being busy suggests a *react native* animation is in-effect. I don't think it's likely that the animation gets somehow incepted by Google... could you please double check your screen components and try to look up an animation component, or even an animation "leak"?

**Comment by sammysium** [comment]
@d4vidi you have a valid point but the animation is out of the google-sigin library itself. When i click button, i transition animation kicks in to open the google signin form. the app never goes into idle for detox to continue. If I interrupt the google sign in form (tapping on back button of the emulator), detox reports "app is idle" and tries to find the IdenfiterId form element. Does that make sense?

**Comment by sammysium** [comment]
i don't think i am being helpful for some reason but i am getting error Test Failed: No activities in stage RESUMED. Did you forget to launch the activity. (test.getActivity() or similar)?
       await web.element(by.web.cssSelector('#identifierId')).typeText('email');

at this stage, the google form is fully visible. but thanks for helping me figure out the animation issue.

**Comment by sammysium** [comment]
@d4vidi https://discuss.appium.io/t/espresso-driver-noactivityresumedexception/30012/2                does it makes sense? the scenarious are quite similar. Given detox still uses espresso for android (right?), perhaps it is limited by limitations of espresso?

**Comment by d4vidi** [comment]
Ouch. So, as it appears, the sign-in takes place in an independent google-made activity, `com.google.android.gms.auth.api.signin.internal.SignInHubActivity`. This kind of ruins things for us. Unless there's a way to start the sign-in flow inside the original activity, I don't see a way for this to work. I'm really sorry.

**Comment by sammysium** [comment]
@d4vidi yeah kinda figured it is a dead end as well.
