### ISSUE TITLE
Mocking not working in detox 

### ISSUE THREAD

**Issue by serhii-sl** [wix/Detox#2608]
I am trying to mock one component in my RN project. I followed detox advanced mocking guide, but mock not work, using native component from lib.
### Prerequsites:
RN CLI:
- RN_SRC_EXT=e2e.js node node_modules/react-native/local-cli/cli.js start
Build and test:
- RN_SRC_EXT=e2e.js detox build --configuration android.emu.debug && RN_SRC_EXT=e2e.js detox test --configuration android.emu.debug -l verbose

metro-config:
> module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts }
  } = await getDefaultConfig()
  return {
    transformer: {
      getTransformOptions: async () => ({
        transform: {
          experimentalImportSupport: false,
          inlineRequires: false,
          resetCache: true
        }
      }),
      babelTransformerPath: require.resolve('react-native-svg-transformer')
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== 'svg'),
      sourceExts: [...sourceExts, 'svg'].concat(process.env.RN_SRC_EXT ? process.env.RN_SRC_EXT.split(',') : [])
    }
  }
})()

e2e/mock/ImagePicker.e2e.js:
> import ImagePicker from './ImagePicker'
ImagePicker.openPicker = async () => [
  {
    path: 'app/assets/images/profile/question.png',
  }
]

e2e/mock/ImagePicker.js:
>import ImagePicker from 'react-native-image-crop-picker'
export default ImagePicker;

config.json:
>{
  "setupFilesAfterEnv": ["./init.js"],
  "testEnvironment": "node",
  "reporters": ["detox/runners/jest/streamlineReporter"],
  "verbose": true,
  "testMatch": ["**/e2e/*.spec.js?(x)", "**/?(*.)(e2e).js?(x)"]
}

### Environment (please complete the following information):
 - Detox: 17.8.2
 - React Native: 0.63.2
 - Device: Emulator
 - OS: Android
 - Test-runner : `jest`

**Comment by d4vidi** [comment]
@serhii-sl The mocking guide might be slightly out of date. However, I do not see your issue as somehow related to Detox nor the guide itself. It would be very helpful if you pinpoint what exactly does not work in your case (add screenshots, logs) -- after proving that in fact your ImagePicker mock has been registered (e.g. using custom logs), and post it on SO.
Sorry and thank you.
