### ISSUE TITLE
Сan't check the text written to the constant

### ISSUE THREAD

**Issue by demchenko-a** [wix/Detox#2619]
### Description

- [x] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction

Before running the test, I write the test value into the '_deliverySum_' constant. _deliverySum_ is equal to "_1,035 ₽_". Then I expect to see this value using the `.toBeVisible ()` method. But the test fails with the error `Test Failed: No elements found for “MATCHER ((text ==“ $ 1,035 ”) && ANCESTOR (identifier ==“ orderDoneScreen ”))”.`

But if I pass the string "1 035 ₽" as a parameter, then the test is successful.

On version 18.2.1 the problem is reproduced

#### Expected behavior

I would like the design
```
     await expect (element (by.text (deliverySum)
       .withAncestor (by.id ('orderDoneScreen'))))
       .toBeVisible ()
```
was similar to the design
```
  await expect (element (by.text ('1,035 ₽')
       .withAncestor (by.id ('orderDoneScreen'))))
       .toBeVisible ()
```

#### Screenshots

Checked item
![Simulator Screen Shot - iPhone 8 - 2021-02-02 at 10 18 02](https://user-images.githubusercontent.com/68426793/106565075-03c58f00-6550-11eb-9484-441d8c99e379.png)

The first check passes, but the second fails
<img width="525" alt="Снимок экрана 2021-02-02 в 10 19 54" src="https://user-images.githubusercontent.com/68426793/106565219-471ffd80-6550-11eb-843f-211511750c07.png">

Error
<img width="929" alt="Снимок экрана 2021-02-02 в 10 17 58" src="https://user-images.githubusercontent.com/68426793/106565246-543cec80-6550-11eb-8a66-5c9e3dcc3c70.png">

#### Environment (please complete the following information):
 - Detox: 17.9.0
 - React Native: 0.63.3
 - Node: 12.16.1
 - Device: iPhone 8
 - Xcode: 12.2
 - iOS: 14.2
 - macOS: 10.15.7

**Comment by noomorph** [comment]
Wait a minute... 🤔 

![Screenshot 2021-03-04 at 12 15 54](https://user-images.githubusercontent.com/1962469/109948910-722e7600-7ce3-11eb-8d01-883d6feec34c.png)

Dollar ≠ Ruble 😉
