### ISSUE TITLE
Changing phone data or redux value while running E2E

### ISSUE THREAD

**Issue by heuism** [wix/detox#262]
I know if doing this way it wouldn't be a correct E2E

However as reading the code, i think the code will be like one day has couple of tasks for users. The next day has tasks as well. To remind the users to follow the instruction.

Thus, i am stuck with the idea of time of the devices to test that. Then I guess that they probably store the data in the phone app storage, or certainly in the Redux store of the app. So i wonder if there is a way to deal with that like increasing the day and stuff.

Thanks

**Comment by DanielMSchmidt** [comment]
Is your use case only time related? If so we could stick to #261. Changing the redux store is as far as I understand it not possible, as well as changing the app storage.

**Comment by LeoNatan** [comment]
I am sorry, I don't understand what you are trying to do, and what is needed here specifically from detox as opposed to app logic.
