### ISSUE TITLE
Use of actual ids rather than accessibility identifiers for native apps

### ISSUE THREAD

**Issue by chirag-timetac** [wix/Detox#2620]
The matcher by.id(id) matches elements with the specified accessibility identifier. Would it be possible to match elements by their actual ids?
For example my Android native app, I already have the following to define a button:
android:id="@+id/bt_login"
I now need to add the following additional line in order to match it with Detox:
android:tag="bt_login"
This is causing concerns from our developers who are not happy about adding additional lines to their code to support automation testing
Since it is possible with Espresso to match with the actual id, and since Detox now uses Espresso, are there any plans on allowing for matching with actual identifiers?

**Comment by d4vidi** [comment]
@chirag-timetac could you elaborate on your use case? Do you have intermixed screens with native and react-native views?
Would you consider this approach for your case? [Detox-Native](https://github.com/wix/Detox/blob/master/detox/detox-native/README.md)

**Comment by chirag-timetac** [comment]
@d4vidi Thanks I was using detox with our native app, I will try with Detox-Native.

**Comment by d4vidi** [comment]
In any case, I think we might be able to add a `by.nativeId()` or something similar to the JS API - regardless.

**Comment by d4vidi** [comment]
@chirag-timetac would you mind sharing what you solution of choice was? Have you decided on Espresso / Espresso+Detox-Native?

**Comment by d4vidi** [comment]
After a discussion on this, we decided not to support this. Here's the rationale:

- For native apps: Using Detox is somewhat pointless. We currently don't support that on Android (#2543).
- For greenfield RN apps: No control over native ID's, which again makes it pointless.

So the only relevant use case is greenfield RN apps, which, as it appears, the OP hasn't requested.
That said, had we had a simple solution for it (tracing back the resource ID's to their original name), we might have considered executing it nonetheless. However ATM, is appears as something that would require research, and perhaps would not be at all feasible.
