### ISSUE TITLE
App has not responded to the network requests after OpenURL

### ISSUE THREAD

**Issue by captainhaddock35** [wix/Detox#2622]
### Description

- [x] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction

Create a test and call `await device.openURL({url: 'myapp://offer/detail/5133062/4', sourceApp: 'com.mycompany.myapp'});`

1. The test launch the app
2. The openURL works, the app open good screen
3. The test stop with exceed timeout (0 line executed after the openURL)

#### Expected behavior
The test execute lines after openURL

### Logs
```
WARN:  [Client.js/PENDING_REQUESTS] App has not responded to the network requests below:
  (id = 10) deliverPayload: {"url":"myapp://offrer/detail/5133062/4","sourceApp":"com.mycompany.myapp"}

That might be the reason why the test "Apply RO FORM" has timed out.

detox[13152] INFO:  Apply: RO FORM [FAIL]

detox[13152] DEBUG: [DetoxServer.js/DISCONNECT] role=tester, sessionId=b0a46d50-5643-e6b1-f32a-0bfd51e2e646
detox[13152] DEBUG: [DetoxServer.js/DISCONNECT] role=app, sessionId=b0a46d50-5643-e6b1-f32a-0bfd51e2e646
detox[13152] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=tester not connected, cannot fw action (sessionId=b0a46d50-5643-e6b1-f32a-0bfd51e2e646)
detox[13152] DEBUG: [DetoxServer.js/WS_CLOSE] Detox server connections terminated gracefully
 FAIL  e2e/apply.e2e.js (151.263 s)
  Apply
    ✕ RO FORM (120005 ms)

  ● Apply › RO FORM

    thrown: "Exceeded timeout of 120000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

```

#### If you are experiencing a timeout in your test

- [x] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://github.com/wix/Detox/blob/master/docs/Troubleshooting.Synchronization.md#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much), I have read [synchronization debug documentation](https://github.com/wix/DetoxSync/blob/master/IdleStatusDocumentation.md) : 
```
detox[13314] INFO:  [actions.js] The system is busy with the following tasks:

Dispatch Queue
⏱ Queue: “Main Queue (<OS_dispatch_queue_main: com.apple.main-thread>)” with 1 work item

Run Loop
⏱ “Main Run Loop”

UI Elements
⏱ 16 CA animations pending
detox[13314] INFO:  [actions.js] The system is busy with the following tasks:

Dispatch Queue
⏱ Queue: “Main Queue (<OS_dispatch_queue_main: com.apple.main-thread>)” with 1 work item

Run Loop
⏱ “Main Run Loop”

UI Elements
⏱ 16 CA animations pending
detox[13314] INFO:  [actions.js] The system is busy with the following tasks:

Dispatch Queue
⏱ Queue: “Main Queue (<OS_dispatch_queue_main: com.apple.main-thread>)” with 1 work item

Run Loop
⏱ “Main Run Loop”

UI Elements
⏱ 16 CA animations pending
detox[13314] INFO:  [actions.js] The system is busy with the following tasks:

Dispatch Queue
⏱ Queue: “Main Queue (<OS_dispatch_queue_main: com.apple.main-thread>)” with 1 work item

Run Loop
⏱ “Main Run Loop”

UI Elements
⏱ 16 CA animations pending
```

Same problem with `await device.sendUserNotification(localNotification);`

**Comment by LeoNatan** [comment]
As yuo can see from the sync output, you have 16 CA animations. Please investigate your app to see why those are running.

**Comment by Jose24San** [comment]
I got this when my test was taking a long time to finish ( by design ) so I just needed to pass in a 3rd argument to my test code that specified a longer timeout 

Jest modification
`it('should run my test without it timing out before the the timeout I have set', () => {
  // my test code
  
  // increase of the jest timeout to 2 minutes which solved my issue
}, 200000)`
