### ISSUE TITLE
nvm breaks detox build on MacOS

### ISSUE THREAD

**Issue by uloco** [wix/Detox#2623]
When using nvm to manage node versions on MacOS(11.1), detox build fails with the following error
```
nvm is not compatible with the "PREFIX" environment variable: currently set to "/Users/uloco/.nvm/versions/node/v15.6.0"
Run `unset PREFIX` to unset it.
env: node: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code
```

Ubuntu works fine with nvm.
Also other builds that need node or npm work fine, it is just happening with detox.

Is detox setting the PREFIX environment variable somewhere? Is there any way of working around this problem?

**Comment by noomorph** [comment]
It is unrealistic to investigate this issue provided the feedback above.
What is your command you are trying to run?
Try wrapping it in a temporary JavaScript file, e.g.:

```
require('child_process').execSync('my unlucky command', { stdio: 'inherit' })
```

and run it. Does the result differ?

**Comment by uloco** [comment]
Detox works fine with a normal nodejs install via .deb from the website.
Since I switched to using nvm I get the error shown above.
I am running a npm script with the just the regular detox build command: `detox build -c ios.stage.release`

**Comment by uloco** [comment]
Thanks. Putting it in a separate node script and running it with `node <script>` solved the issue. Running it in a npm script with `npm run <script>` does not work though, even if it is a separate script.

**Comment by uloco** [comment]
But this works in a npm script `unset PREFIX && detox build ... `

**Comment by LeoNatan** [comment]
This is not related to Detox at all.

**Comment by uloco** [comment]
This issue just happens with detox build. I do not have any issues with other npm scripts or libraries. That's why I thought of a detox issue in the first place. I was thinking, that it is quite unlikely that any of you are using nvm and haven't had any issues regarding this. Thanks for clearing things up.

**Comment by LeoNatan** [comment]
We are actually using NVM in some of our CIs and, as far as I know, that hasn't changed. We also had developers using NVM on their development machines.

**Comment by uloco** [comment]
Looks like this was still an issue by npm 2 days ago. It used to set the PREFIX env variable for no reason.
Now it is fixed: https://github.com/npm/cli/issues/2398
`nvm install-lastest-npm` fixes this, whoever lands here. No need to unset prefix anymore.
