### ISSUE TITLE
Signal 11 was raised

### ISSUE THREAD

**Issue by sam-barker** [wix/Detox#2627]
### Description
App under test crashes in pipeline execution with detox, but does not crash locally

- [x] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

1. Install and configure latest detox version
2. Run iOS tests
3. App crashes (intermittent)

#### Expected behavior
The app doesn't crash

#### Environment (please complete the following information):
 - Detox: 18.2.1
 - React Native: 0.63.4
 - Node: 12.6.1
 - Device: iPhone 11 Pro Max
 - Xcode: 12.3
 - iOS: 14.3
 - macOS: 11.0.1

### Logs
```
detox[1456] ERROR: [exec.js/SPAWN_STDERR, #11] Wrote video to: /private/var/folders/6y/gy9gggt14379c_k39vwb50lc0000gn/T/bc35c139-7b3f-4f3a-9619-458068889d73.detox.mp4

detox[1456] ERROR: [Detox.js/APP_CRASH] App crashed in test 'Search - Sort by - Visual light mode opens sort by view and compares screenshot', here are the crash details: 
Signal 11 was raised
(
	0   Detox                               0x0000000110d81f85 +[NSThread(DetoxUtils) dtx_demangledCallStackSymbols] + 37
	1   Detox                               0x0000000110d85190 __DTXHandleCrash + 464
	2   Detox                               0x0000000110d858d5 __DTXHandleSignal + 59
	3   libsystem_platform.dylib            0x000000011b39e5fd _sigtramp + 29
	4   ???                                 0x0000000110cdc52a 0x0 + 4576888106
	5   DetoxSync                           0x0000000143849b4f -[_DTXTimerTrampoline fire:] + 188
	6   DetoxSync                           0x0000000143831f00 _DTXCFTimerTrampoline + 74
	7   CoreFoundation                      0x0000000117bb5c57 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	8   CoreFoundation                      0x0000000117bb572a __CFRunLoopDoTimer + 926
	9   CoreFoundation                      0x0000000117bb4cdd __CFRunLoopDoTimers + 265
	10  CoreFoundation                      0x0000000117baf35e __CFRunLoopRun + 1949
	11  CoreFoundation                      0x0000000117bae6d6 CFRunLoopRunSpecific + 567
	12  APP_NAME_HERE                0x000000010fdeecba +[RCTCxxBridge runRunLoop] + 274
	13  DetoxSync                           0x000000014383a3d0 swz_runRunLoopThread + 291
	14  Foundation                          0x0000000112ce0e68 __NSThread__start__ + 1042
	15  libsystem_pthread.dylib             0x000000011b3b4109 _pthread_start + 148
	16  libsystem_pthread.dylib             0x000000011b3afb8b thread_start + 15
)
```

#### If you are experiencing a timeout in your test

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://github.com/wix/Detox/blob/master/docs/Troubleshooting.Synchronization.md#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much), I have read [synchronization debug documentation](https://github.com/wix/DetoxSync/blob/master/IdleStatusDocumentation.md) and am providing the relevant synchronization debug output below:

#### If you are seeing a Detox build problem (e.g. during `npm install`, not `detox build`)

- [ ] I am providing the `npm install` log below:

#### Device and verbose Detox logs

- [ ] I have run my tests using the `--loglevel trace` argument and am providing the verbose log below:

**Comment by LeoNatan** [comment]
Hello,

Can you please create a new project where this reproduces? I'd like to investigate this.

Thanks

**Comment by sam-barker** [comment]
@LeoNatan I won't be able to do this anytime soon, but I will try and get this setup and reproduced for you

**Comment by LeoNatan** [comment]
Thanks. Without a reproduction, I won't be able to help.

**Comment by michaelgmcd** [comment]
@sam-barker Does your app have react-native-firebase? If so, this is likely the same issue as https://github.com/wix/DetoxSync/issues/5. Here's a simple repo that reproduces the issue:

https://github.com/michaelgmcd/DetoxTestApp

**Comment by sam-barker** [comment]
@michaelgmcd we are using
```
    "@react-native-firebase/app": "10.4.0",
    "@react-native-firebase/messaging": "10.4.1",
```
Good find! I'll follow https://github.com/wix/DetoxSync/issues/5 closely

**Comment by LeoNatan** [comment]
Closing favor of https://github.com/wix/DetoxSync/issues/5

@sam-barker Please join the discussion there. Thanks
