### ISSUE TITLE
SwiftUI Element matchers, visibility & actions (like tap) not working with detox 18.x

### ISSUE THREAD

**Issue by distributedinfinity** [wix/Detox#2636]
### Description
Detox 18.x can't seem to match, view & interact with swiftUI elements. 

- [X] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction

I found [this closed issue](https://github.com/wix/Detox/issues/2463) in detox issues regarding swiftUI & forked this [sample repo](https://github.com/jh-bate/TestSample) from there & added jest support for better logs, I also added an action to the button in that repo to show an alert & added a tap acton in detox tests. 

Please see this [repo](https://github.com/distributedinfinity/DetoxTestSample) for reproducing the issue,  I have created  branches for detox version [17.14.9](https://github.com/distributedinfinity/DetoxTestSample/tree/detox-17.14.9) , [18.0.0](https://github.com/distributedinfinity/DetoxTestSample/tree/detox-18.0.0) , [18.3.1](https://github.com/distributedinfinity/DetoxTestSample/tree/detox-18.3.1) for test convenience. 

- Basically with version 17.14.9 detox can see the button & click it too (but after that it seems to be waiting on some event to sync up, have included test run logs below with debug-sync) & thus never runs the next step & fails

- With version 18.0.0 & 18.3.1 , detox doesn't seem to even see the button & is also unable to tap it  (I even tried disableSync & no luck sadly).

- Adding steps to reproduce below

1. Run ```npm install```
2. Run ```npm run detox:ios:build``` 
3. Run ```npm run detox:ios:test``` (added various debug flags for convenience)

Please let me know if you need any more info 🙏🏼, also great work with detox! 

#### Expected behavior
Detox should be able to match, view SwiftUI elements & interact with them

#### Screenshots

I have attached videos of the full test runs below for detox-17.14.9 & detox-18.3.1 (notice on 17.14.9 it sees the button & taps it as the alert pops up , but with version 18.3.1 it can't even see the button)

- detox 17.14.9
https://user-images.githubusercontent.com/20133550/107684177-5e6e9180-6c9a-11eb-90cf-0609633426b1.mp4

 - detox 18.3.1
https://user-images.githubusercontent.com/20133550/107684210-69292680-6c9a-11eb-9ee6-13d5078c7060.mp4

#### Environment (please complete the following information):
 - Detox: 18.3.1
 - Node: v10.14.1
 - Device: iPhone 11 Pro
 - Xcode: Version 12.4 (12D4e)
 - iOS: 14.4
 - macOS: 11.2 (Big Sur)

#### If you are experiencing a timeout in your test

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://github.com/wix/Detox/blob/master/docs/Troubleshooting.Synchronization.md#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much), I have read [synchronization debug documentation](https://github.com/wix/DetoxSync/blob/master/IdleStatusDocumentation.md) and am providing the relevant synchronization debug output below:

#### Device and verbose Detox logs

- [X] I have run my tests using the `--loglevel trace` argument and am providing the verbose log below:

Please see the logs of test run with various detox versions below

- [detox-17.14.9-test.log](https://github.com/wix/Detox/files/5967841/detox-17.14.9-test.log)
- [detox-18.0.0-test.log](https://github.com/wix/Detox/files/5967843/detox-18.0.0-test.log)
- [detox-18.3.1-test.log](https://github.com/wix/Detox/files/5967844/detox-18.3.1-test.log)

**Comment by LeoNatan** [comment]
Not much has changed between 17 and 18 with regards to matching or interaction. What failures are you seeing? Unable to match or visibility/interaction errors?

**Comment by distributedinfinity** [comment]
@LeoNatan  

- So for 17.14.9 , detox can match the element , assert visibility & interact with the button, but after tapping the button it keeps  `Waiting for gesture recognizer to detect or fail an ongoing gesture` & thus times out before running the next step in the test. 

    Here's the excerpt from the log I attached above for detox-17.14.9.
    <img width="1156" alt="Screenshot 2021-02-12 at 06 26 36" src="https://user-images.githubusercontent.com/20133550/107737052-6e6a8d80-6cfb-11eb-9832-8cc060b2e100.png">
    
    Adding `device.disableSynchronization()` in the test for detox 17.14.9 prevents the above sync issue though.

- Whereas, For detox-18.0.0 onwards & detox-18.3.1, detox launches the app but doesn't seem to do anything after that, verbose trace logs with debug-sync don't really output much too (attached above in the issue) & the test times out after launching the app, you can see this in the video attached on the issue too. I followed this [sync troubleshooting guide](https://github.com/wix/Detox/blob/master/docs/Troubleshooting.Synchronization.md#lower-level-idling-resources-debug-ios-only) & I see following logs for SyncManager .  [detox-18.3.1-syncmanager.log](https://github.com/wix/Detox/files/5970295/detox-18.3.1-syncmanager.log)

    <img width="1156" alt="Screenshot 2021-02-12 at 07 44 47" src="https://user-images.githubusercontent.com/20133550/107742356-c78bee80-6d06-11eb-81c1-e96b148267fc.png">
    
 - I have also added failing artifacts for detox 17.14.9 & detox 18.3.1 below , hope that's useful.
 
    [detox-18.3.1-artifacts.zip](https://github.com/wix/Detox/files/5970453/detox-18.3.1-artifacts.zip)
    [detox-17.14.9-artifacts.zip](https://github.com/wix/Detox/files/5970497/detox-17.14.9-artifacts.zip)

**Comment by LeoNatan** [comment]
Thanks for the detailed report. Indeed, that makes more sense; Detox 18 uses a new synchronization mechanism. I’ll check out the demo project soon to try to figure out what’s going on.

**Comment by LeoNatan** [comment]
I see a few issues in the example project. When running, it seems App Transport Security is blocking Detox connections. 

<img width="499" alt="Screen Shot 2021-02-14 at 14 09 25" src="https://user-images.githubusercontent.com/2270433/107876372-4d0dcb00-6ece-11eb-9a20-6e12cc154011.png">

I then run the last test and saw this:

```
detox[41565] INFO:  [actions.js] The system is busy with the following tasks:

Dispatch Queue
⏱ Queue: “Main Queue (<OS_dispatch_queue_main: com.apple.main-thread>)” with 1 work item

Run Loop
⏱ “Main Run Loop”

One-time Events
⏱ “Gesture Recognizer” with object: “<SwiftUI.UIKitGestureRecognizer: 0x7f9909515a10; baseClass = UIGestureRecognizer; state = Possible; delaysTouchesEnded = NO; view = <_TtGC7SwiftUI15ListHostingViewGVS_15ModifiedContentVS_14_ViewList_ViewVVS_17CellForRowVisitor12CellModifier__ 0x7f990950a8a0>>”
```

And I'm investigating to see why this pops up. If I disable something in the sync system, it works as expected.

**Comment by LeoNatan** [comment]
https://github.com/wix/Detox/pull/2638

With this fix, your suite passes.

**Comment by distributedinfinity** [comment]
@LeoNatan I just tried ```detox 18.6.2``` release with the [sample repo](https://github.com/distributedinfinity/DetoxTestSample)) as mentioned in the above issue  (also updated main branch to 18.6.2 & sadly I still see the same issue :( . 

All the tests are still failing &  on the simulator the app is launched but nothing happens after that same as before. Please see the excerpt from the logs below . 

<img width="1147" alt="Screenshot 2021-02-23 at 19 05 59" src="https://user-images.githubusercontent.com/20133550/108894541-530c5600-760a-11eb-8f1a-6a83ee4360f5.png">

I have attached the artifacts folder from the run too. 
[detox-18.6.2.zip](https://github.com/wix/Detox/files/6031305/detox-18.6.2.zip)

Can you please try the main branch again ? 🙏🏼

**Comment by d4vidi** [comment]
@alon-ha could you please rerun the sample project to see where things fail?

**Comment by alon-ha** [comment]
Sure, will take a look

**Comment by noomorph** [comment]
@alon-ha, I'll remove stale label, if you don't mind.

**Comment by distributedinfinity** [comment]
@noomorph @alon-ha   any updates on this, please?

**Comment by d4vidi** [comment]
@alon-ha wdyt?

**Comment by alon-ha** [comment]
@d4vidi I don't think I can squeeze it this week. Of course we will solve it eventually, but the bugs in DetoxSync affect much more users IMO

**Comment by d4vidi** [comment]
I tend to agree. Nevertheless from the comments here it sounds like we're in a dead end. Can we dig up the real problem, here?

**Comment by pqkluan** [comment]
This issue thrown me off when I setup Detox.
The basic e2e test work fine for Android but not for iOS.

The only work around is using testID to query element, which is a big turn off since I'm trying to writing the tests from user perspective.
