### ISSUE TITLE
MapView with height > 1 block test

### ISSUE THREAD

**Issue by acollazomayer** [wix/Detox#2637]
### Description
I have a map view with a specific height inside of a flex view. This blocks the test. The test should continue by pressing a button. However when the map has a height > 1. The test is blocked, for a height === 0 the test passes.

- [x] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

1. 
2. 
3. 
4. 

#### Environment (please complete the following information):
 - Detox: 18.3.1
 - React Native: 0.63.4
 - Node: 14
 - Device: Sim
 - Xcode: 12.4
 - iOS: 14
 - macOS: 

#### If you are experiencing a timeout in your test

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://github.com/wix/Detox/blob/master/docs/Troubleshooting.Synchronization.md#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much), I have read [synchronization debug documentation](https://github.com/wix/DetoxSync/blob/master/IdleStatusDocumentation.md) and am providing the relevant synchronization debug output below:

#### If you are seeing a Detox build problem (e.g. during `npm install`, not `detox build`)

- [ ] I am providing the `npm install` log below:

#### Device and verbose Detox logs

- [ ] I have run my tests using the `--loglevel trace` argument and am providing the verbose log below:

**Comment by acollazomayer** [comment]
I want to add that detox hangs with pending animation. Somehow detox is not being communicated that the animation has finished. This was working on the version 17 of detox. 

```
Dispatch Queue
⏱ Queue: “Main Queue (<OS_dispatch_queue_main: com.apple.main-thread>)” with 1 work item

Run Loop
⏱ “Main Run Loop”

UI Elements
⏱ 1 CA animation pending
detox[40969] INFO:  [actions.js] The system is busy with the following tasks:

Dispatch Queue
⏱ Queue: “Main Queue (<OS_dispatch_queue_main: com.apple.main-thread>)” with 1 work item

Run Loop
⏱ “Main Run Loop”

UI Elements
⏱ 1 CA animation pending
detox[40969] INFO:  [actions.js] The system is busy with the following tasks:

Dispatch Queue
⏱ Queue: “Main Queue (<OS_dispatch_queue_main: com.apple.main-thread>)” with 1 work item
```

**Comment by LeoNatan** [comment]
Please attach a very simple example project, reproducing the issue. Thanks

**Comment by LeoNatan** [comment]
Unable to reproduce. I have made a small app with an MKMapView in it, and the system always idles at the end. Please provide the example project.
