### ISSUE TITLE
How does wix handles network automations using detox?

### ISSUE THREAD

**Issue by iradkot** [wix/Detox#2643]
I read some issues here and in stack-overflow regarding the option to simulate different internet connections which seems like it unavailable.
 
I wanted to know how does WIX simulate offline events?
I saw appium have an option of [driver.setConnection()](https://subscription.packtpub.com/book/application_development/9781787280168/11/ch11lvl1sec50/network-conditioning) , Do you know by any change if I can integrate this tool into detox or if there is any other alternative?

**Comment by noomorph** [comment]
I think only manual workarounds are available at the moment:

https://stackoverflow.com/questions/1614802/simulate-airplane-mode-in-iphone-simulator
https://stackoverflow.com/questions/62609879/how-to-enable-airplane-mode-on-android-using-adb
