### ISSUE TITLE
Error message bug/suggestion: refer to device.launchApp() if first test times out

### ISSUE THREAD

**Issue by lukewlms** [wix/Detox#2645]
### Description
This is an issue with Detox error messages.

I actually read the release notes for v18 and they *do not mention* that Detox doesn't launch the app anymore.  That led to ~an hour of wheel spinning not having any idea how to fix the "app just doesn't launch now" issue.

I think a lot more devs would have a smooth upgrade (or initial experience) if forgetting `device.launchApp()`, or perhaps a simple "troubleshooting timeouts" page url, were documented in an error message.  For example, if the very first message sent to the app times out, it may well be that the app was never launched!  In a case like Detox could just display something like:

"First test timed out.  (Did you call device.launchApp()?  See https://github.com/wix/Detox/blob/master/docs/Guide.Migration.md#180)"

Or just "See tips for resolving timeouts".  There are [Several](https://stackoverflow.com/questions/63530475/detox-app-has-not-responded-to-the-network-requests-below) [StackOverflow](https://stackoverflow.com/questions/60642122/timeout-app-has-not-responded-to-the-network-requests-below) [questions](https://stackoverflow.com/questions/57403186/cant-run-detox-tests-on-ios) with no answers that are all about timeouts - it would be great to just have a page to refer to that covers common scenarios for these (including, now, not launching the app), to help developers not throw their hands up.  I see there are troubleshooting guides but none appear to mention needing to run a new command explicitly as of v18.

I don't know what % of people seeing timeout issues would not have launched the app, but it seems like a likely scenario if the app is totally unresponsive.

I would also strongly suggest updating the [18.0 release notes](https://github.com/wix/Detox/releases/tag/18.0.0) to indicate that this isn't just a "black box" change and will actually break tests if app launch hasn't explicitly been called!

Thanks for your work on this library.

- [X] I have tested this issue on the latest Detox release and it still reproduces

#### Environment (please complete the following information):
 - Detox: 18.6.0

**Comment by noomorph** [comment]
Resolved in [18.10.0](https://github.com/wix/Detox/releases/tag/18.10.0). 😌
