### ISSUE TITLE
Detox doesn't wait for button animation

### ISSUE THREAD

**Issue by onnerfors** [wix/Detox#2648]
### Description
Hi, I'm new to Detox and not a very experienced developer so apologies if the answer to this is very obvious, I haven't found any other bugs about this problem. In the Detox documentation I read the following in the "Endless looping animations" section: 

_By default, Detox will wait until animations complete._

But it doesn't do that for me, below is a screen recording of when the test taps a button prematurely, along with the code that's being run.

https://user-images.githubusercontent.com/7572926/108333565-61eda580-71d1-11eb-8b47-26e09629b12b.mov

<img width="450" alt="Screenshot 2021-02-16 at 10 53 28" src="https://user-images.githubusercontent.com/7572926/108333859-a7aa6e00-71d1-11eb-970d-619b2fd1af19.png">

I also ran the test with the `debug-synchronization 500` argument, see log below, I've highlighted where the test taps the button too early.

<img width="672" alt="Screenshot 2021-02-16 at 15 10 02" src="https://user-images.githubusercontent.com/7572926/108334557-5babf900-71d2-11eb-90ca-2551519cee70.png">

- [x] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction

This has been the most puzzling thing about this issue, I've tried different solutions that by all indications seem to be working - for example I added the `waitFor` + `toBeVisible` before tapping the button as in the first screen shot above - but when I get back the next morning I see the problem again.

Step by step
1. Start test
2. Watch the test tap button too early

#### Expected behavior
Test should wait for button to animate before tapping it

#### Environment (please complete the following information):
 - Detox: 18.2.2
 - React Native: 0.63.4
 - Node: 15.7.0
 - Device: iPhone 11 simulator
 - Xcode: 12.4
 - iOS: 14.4
 - macOS: 10.15.7

#### If you are experiencing a timeout in your test

- [x] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://github.com/wix/Detox/blob/master/docs/Troubleshooting.Synchronization.md#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much), I have read [synchronization debug documentation](https://github.com/wix/DetoxSync/blob/master/IdleStatusDocumentation.md) and am providing the relevant synchronization debug output below: **see screen shot of log above**

#### If you are seeing a Detox build problem (e.g. during `npm install`, not `detox build`) 

I'm not

- [ ] I am providing the `npm install` log below:

#### Device and verbose Detox logs

- [x] I have run my tests using the `--loglevel trace` argument and am providing the verbose log below:

[trace.txt](https://github.com/wix/Detox/files/6001643/trace.txt)

Thanks for your time

**Comment by d4vidi** [comment]
@onnerfors do you by any chance have a timer suspending the button's fade-in animation start, that's longer than 1.5 seconds?

**Comment by d4vidi** [comment]
@alon-ha could you check and see which assertion the `waitFor(...).toBeVisible()` translates to? Namely, whether on top of not being blocked by other view in the hierarchy -- that it takes the `alpha` into account...

**Comment by onnerfors** [comment]
@d4vidi that's an idea I've had, tried reading the code but haven't figured it out so far, and my developer colleague has been sick the past few days so haven't been able to check with him, but will. So it could be that Detox is tapping the button before the animation starts?

**Comment by d4vidi** [comment]
Might be. Technically, if the view is set visible (though has alpha set to 0), and a timer suspends the animation's start by more than 1.5s, Detox would consider the app _idle_ and move forward with tapping on the button.

**Comment by onnerfors** [comment]
That screen has other animations going on before it gets to the button I want the test to tap, so that means Detox should wait I suppose. Could it have anything to do with specific animation tools? We're using Lottie. I know it's hacky but is there a way to pause the Detox process somehow? As the `withTimeout()` + `toBeVisible()` combination of methods only waits until the button is visible to Detox as I understand it, which it is before being animated, I don't see how I can get past this issue temporarily until I've found the root cause

**Comment by mentormategeorgirusev** [comment]
@onnerfors yes, it's probably a good idea to delay the process, and figure out if the animation is the root cause.
await new Promise(resolve => setTimeout(resolve, 5000));

**Comment by onnerfors** [comment]
Thank you very much! Now I at least have a workaround, will continue talking to my devs about it, sounded on them like it's possible to turn off animations all together for Detox builds. Let me know if you want more info from me, and close the bug if you want

**Comment by d4vidi** [comment]
You might want to give `waitFor()` + `withTimeout()` a try, but all in all, Detox should be able to take all running animations into account - so best if you avoid that.
In Detox 18 we've changed the synchronization mechanism. If it doesn't bother you much, could you try the same scenario with the latest Detox 17 and report back?

**Comment by alon-ha** [comment]
Seems like an animation we are not tracking. I will check it.
@onnerfors it will be great if you can provide an example project with kind of a similar screen/animation

**Comment by onnerfors** [comment]
Hello, sorry for the delay, @d4vidi I tried the same thing with version 17.14.9 and the issue reproduced 19 times out of the 20 I tried, it's the following code that fails:

```
it('Should tap "Continue" in onboarding', async () => {
    await waitFor(element(by.id('onboardingContinueButton')))
      .toBeVisible()
      .withTimeout(5000);

    await element(by.id('onboardingContinueButton')).tap();  <<< this happens before the button is animated, like in the video attached to the bug description
```

@alon-ha I wish I could set up something similar to have you guys try it yourselves, but I don't have the RN skills for that yet

**Comment by alon-ha** [comment]
@onnerfors Hey, Sorry for the delay. We have a new mechanism in detox 18 to track when the application is idle.
Since you are using Lottie, maybe we don't track the animation at all.. I can set up a basic project myself, but I need at least the json for the button so I can test it.. Otherwise there is no way that I will guess what's the problem is:/ 
Let us know if you can provide the json for the button / part of the initial code for the button.. Anything that can help before I'm starting to debug it. Thanks

**Comment by onnerfors** [comment]
Hi @alon-ha, sure, I've attached the `.tsx` of the button as well as the `Animated.View` from the screen it's a part of. Let me know if there's anything else you need.

**OnboardingContinueButton.tsx**

```
import React, { useEffect, useRef } from 'react';
import { Animated, StyleSheet } from 'react-native';
import { t } from 'i18n-js';
import Button from '@components/Button';
import OnboardingScreen from './OnboardingScreen';

const styles = StyleSheet.create({
  button: {
    marginVertical: 0,
  },
});

const DEFAULT_DURATION = 420;

type Props = {
  visible: boolean;
  nextScreen: string;
  onPress: () => void;
  animationDuration?: number;
  label?: string;
};

const OnboardingContinueButton = ({
  visible,
  onPress,
  animationDuration = DEFAULT_DURATION,
  nextScreen,
  label,
}: Props): JSX.Element => {
  const opacity = useRef(new Animated.Value(0)).current;

  useEffect(() => {
    Animated.timing(opacity, {
      toValue: visible ? 1 : 0,
      duration: animationDuration,
      useNativeDriver: false,
    }).start();
  }, [animationDuration, opacity, visible]);

  return (
    <Animated.View style={{ opacity }}>
      <Button
        buttonStyle={styles.button}
        title={label || t('onboarding.continueButtonLabel')}
        onPress={onPress}
        isDisabled={!visible}
        testID={`onboardingContinueButton${nextScreen}`}
      />
    </Animated.View>
  );
};

export default OnboardingContinueButton;
```


**Animated.View** from `OnboardingScreen.tsx`

```
<Animated.View
          style={[
            styles.continueButtonContainer,
            {
              opacity: animatedValue.current.interpolate({
                inputRange: [0, 1],
                outputRange: [1, 0],
              }),
            },
          ]}
        >
          <OnboardingContinueButton
            onPress={onPressContinue}
            label={continueButtonLabel}
            visible={continueButtonVisible}
            animationDuration={continueButtonAnimationDuration}
          />
        </Animated.View>
```

**Comment by noomorph** [comment]
@onnerfors, may I kindly ask you to check the issue with the latest Detox version?

The thing is, @alon-ha recently fixed something very curious in React Native queue status interrogation mechanism, and I just wonder if that has changed anything about your particular issue.

**Comment by onnerfors** [comment]
Good point @noomorph, in fact I thought I was running the latest version, that npm updated the package automagically on `npm install`. The issue persists with **18.11.1** though.

**Comment by noomorph** [comment]
@onnerfors thanks for the clarification!! 👍

**Comment by d4vidi** [comment]
@onnerfors Thanks for all the info, and for bearing with us.
Since this case is a bit unusual (odd set of events + fails even with Detox17), would you mind setting up a very simple, light demo app containing the lottie animation and button in question (or equivalents), where this is reproduced? That would provide a serious boost in our so-far-futile attempts to solve this.

**Comment by onnerfors** [comment]
@d4vidi no worries and I have a workaround for now so it's all good, I have some spare time at work now actually, so I will look into setting up an example with a Lottie animation so you guys can debug it. Will get back to you

**Comment by d4vidi** [comment]
@onnerfors great, keep us posted!

**Comment by d4vidi** [comment]
@onnerfors Pretty please? 😄

**Comment by onnerfors** [comment]
Sorry @d4vidi was thrown into a project at work, will try to find some time for it soon

**Comment by alon-ha** [comment]
> Hi @alon-ha, sure, I've attached the `.tsx` of the button as well as the `Animated.View` from the screen it's a part of. Let me know if there's anything else you need.
> 

Hi, Unfortunately the snippet alone wasn't enough to reproduce. Will be great if you post an example project with Lottie animation which cause it.

**Comment by onnerfors** [comment]
Hi guys, it's not likely that I'll find time for this anytime soon unfortunately. Maybe the lack of '+1' comments on this thread means that this problem isn't too common. I might take it up after summer as the project I'm using Detox for might resume then

**Comment by d4vidi** [comment]
@onnerfors no problem. Hopefully by then we will have a skeletal project you could use (#2746)

**Comment by d4vidi** [comment]
@onnerfors with #2746 all done and well, we now have [`DetoxTemplate`](https://github.com/wix-incubator/DetoxTemplate) ready for easy reproductions. Perhaps you could work out a reproduction based on it? You can easily fork it and have a project up and running in a breeze.

**Comment by adrienharnay** [comment]
Hello, it seems `MotiView` animations are not tracked either as I just ran into the same problem with Detox's latest version.

**Comment by d4vidi** [comment]
> Hello, it seems `MotiView` animations are not tracked either as I just ran into the same problem with Detox's latest version.

Hey @adrienharnay  could you elaborate on that? Does this happen on Android/iOS/both?
