### ISSUE TITLE
TypeError: device.resetContentAndSettings is not a function

### ISSUE THREAD

**Issue by DanielZlotin** [wix/detox#265]
#### Description

`detox@5.6.1`

```
await device.resetContentAndSettings();
```
throws `TypeError: device.resetContentAndSettings is not a function`

All other device functions work.

#### Node, Device, Xcode and macOS Versions

* Node: 8.4.0
* Device: sim iOS 10.3
* Xcode: 8.3.3
* macOS: 10.12.6

**Comment by rotemmiz** [comment]
You are right, Detox 5.6.1 was released before resetContentAndSettings was merged.
It'll be released soon. This is what happens when we don't release every build :(

I'll update this issue when we do.

**Comment by DanielZlotin** [comment]
@rotemmiz and why is that exactly? just take the script from [here](https://github.com/wix/react-native-navigation/blob/v2/scripts/release.js)

**Comment by rotemmiz** [comment]
detox@5.6.2 is out
