### ISSUE TITLE
[Android] tap action stuck in pending request 

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [wix/Detox#2652]
### Describe the bug

similar to https://github.com/wix/Detox/issues/1699
Tapping a button would show a new screen. The test taps the button and new screen is displayed. But the test timeouts saying it did not receive any response for the tap action.

### Steps To Reproduce

- [*] I have tested this issue on the latest Detox release and it still reproduces

### Detox Trace-Logs

```
detox[16532] TRACE: [AsyncWebSocket.js/WEBSOCKET_MESSAGE] {"messageId":1,"type":"invokeResult","params":{"result":null}}

detox[16532] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"invoke","params":{"target":{"type":"Class","value":"com.wix.detox.espresso.EspressoDetox"},"method":"perform","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"androidx.test.espresso.Espresso"},"method":"onView","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"com.wix.detox.espresso.DetoxMatcher"},"method":"matcherForTestId","args":["start_button"]}}]}},{"type":"Invocation","value":{"target":{"type":"Class","value":"com.wix.detox.espresso.DetoxViewActions"},"method":"click","args":[]}}]},"messageId":2}
detox[16532] TRACE: [DetoxServer.js/MESSAGE] role=tester action=invoke (sessionId=9056479b-3f24-d8c4-9b0f-f86049363a14)
detox[16532] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"currentStatus","params":{},"messageId":3}
detox[16532] TRACE: [DetoxServer.js/MESSAGE] role=tester action=currentStatus (sessionId=9056479b-3f24-d8c4-9b0f-f86049363a14)
detox[16532] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onTestFnFailure({ error:
   'Exceeded timeout of 120000 ms for a test.\nUse jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test.' })
detox[16532] TRACE: [Detox.js/DETOX_AFTER_EACH] failed test: "Example should have welcome screen"
detox[16532] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onTestDone({ title: 'should have welcome screen',
  fullName: 'Example should have welcome screen',
  status: 'failed',
  invocations: 1,
  timedOut: true })
detox[16532] WARN:  [Client.js/PENDING_REQUESTS] App has not responded to the network requests below:
  (id = 2) invoke: {"target":{"type":"Class","value":"com.wix.detox.espresso.EspressoDetox"},"method":"perform","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"androidx.test.espresso.Espresso"},"method":"onView","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"com.wix.detox.espresso.DetoxMatcher"},"method":"matcherForTestId","args":["start_button"]}}]}},{"type":"Invocation","value":{"target":{"type":"Class","value":"com.wix.detox.espresso.DetoxViewActions"},"method":"click","args":[]}}]}

That might be the reason why the test "Example should have welcome screen" has timed out.

detox[16532] INFO:  Example: should have welcome screen [FAIL]

```

### Environment (please complete the following information):
 - Detox:18.6.2
 - React Native: 0.63.4
 - Node: v10.18.0
 - Device: PIXEL emulator
 - OS: Android
 - Test-runner (select one): `jest-circus`

**Comment by d4vidi** [comment]
@a-c-sreedhar-reddy can you paste these logs again, but with timestamps?
Also, does the screen that opens sport an animation of sorts, which could be blocking it from ever going idle?
https://askubuntu.com/questions/391082/how-to-see-time-stamps-in-bash-history

**Comment by a-c-sreedhar-reddy** [comment]
@d4vidi Yes you are right. There is an animation which slides an icon horizontally continuously.

**Comment by d4vidi** [comment]
Our best recommendation currently is to mock away such animation (e.g. replacing them with a static placeholder), just for the context of the test. It's not entirely easy to do, but we have a [guide](https://github.com/wix/Detox/blob/master/docs/Guide.Mocking.md) for that.

**Comment by a-c-sreedhar-reddy** [comment]
Thanks @d4vidi There is one more issue where typing any letter after `@`  with typetext refreshes the app via fast refresh and the app fails. Currently I use replace text as a hack for this to work.

**Comment by d4vidi** [comment]
On Android? Wow that's an exotic one... 😆  Could you report though a separate issue, with some more details? 🙏🏻

**Comment by a-c-sreedhar-reddy** [comment]
Thanks for your time @d4vidi will create a new issue.
