### ISSUE TITLE
Cleaner Errors

### ISSUE THREAD

**Issue by dobiedad** [wix/detox#266]
Hi everyone,

Thank you for this tool! I was wondering if theres a way to display cleaner errors

If i have a failing test like this 
```
 it('Logins successfully', async () => {
    await element(by.text('Email Field')).typeText('john@smith.com');
  });
```

if the element is not found the error thrown is 
```
`     Error: Cannot find UI element.
Exception with Action: {
  "Action Name" : "Type 'john@smith.com'",
  "Element Matcher" : "(((((kindOfClass('UILabel') || kindOfClass('UITextField') || kindOfClass('UITextView')) && hasText('Email Field')) || (kindOfClass('RCTText') && an object with accessibilityLabel "Email Field")) && !(kindOfClass('RCTScrollView'))) || (kindOfClass('UIScrollView') && ((kindOfClass('UIView') || respondsToSelector(accessibilityContainer)) && ancestorThatMatches(((((kindOfClass('UILabel') || kindOfClass('UITextField') || kindOfClass('UITextView')) && hasText('Email Field')) || (kindOfClass('RCTText') && an object with accessibilityLabel "Email Field")) && kindOfClass('RCTScrollView'))))))",
  "Recovery Suggestion" : "Check if the element exists in the UI hierarchy printed below. If it exists, adjust the matcher so that it accurately matches element."
}

Error Trace: [
  {
    "Description" : "Interaction cannot continue because the desired element was not found.",
    "Error Domain" : "com.google.earlgrey.ElementInteractionErrorDomain",
    "Error Code" : "0",
    "File Name" : "GREYElementInteraction.m",
    "Function Name" : "-[GREYElementInteraction matchedElementsWithTimeout:error:]",
    "Line" : "124"
  }
]
```
This is an an issue when dealing with multiple elements as im not sure where the test has failed without digging through the error logs. It would be nicer if it just outputted

`Interaction cannot continue because element matching "Email Field" was not found`

1) If theres already a similar feature could someone direct me to it?
2) If the feature doesnt exist, id like to add it and submit a PR. I dug through the source to pin point where the errors was being thrown from but couldnt see anything obvious. Can anyone show me this?

**Comment by DanielMSchmidt** [comment]
This seems to be related to #127, but I think we had no progress in this area so far. As far as I remember we have a part in [invoke](https://github.com/wix/detox/blob/master/detox/src/invoke.js#L11) where the actual execution result is returned. Wrapping this in a try might and switch on the errors might improve the error messages. (please be aware that I have very limited knowledge on this part)

**Comment by dobiedad** [comment]
Thanks for the quick response ! Ill do a bit more digging

**Comment by DanielMSchmidt** [comment]
Thank you very much for your help!
