### ISSUE TITLE
Allow Detox to rotate the device

### ISSUE THREAD

**Issue by Vannevelj** [wix/Detox#2661]
**Is your feature request related to a problem? Please describe.**
I have an iPad app which only supports landscape mode (`UIInterfaceOrientationLandscapeRight` and `UIInterfaceOrientationLandscapeLeft`). It is a forced fullscreen app.
When the Detox test starts the iPad's content is in landscape mode, as intended, but the device itself is in portrait mode. This is particularly annoying when reviewing screenshots & videos of test failures since everything is at 90 degrees.

**Describe the solution you'd like**
I would like to be able to rotate the simulator device itself, similar to how you can manually click the "rotate" button.

**Describe alternatives you've considered**
I have figured out a workaround by patching the Info.plist with the portrait orientation in Detox builds. 

```
"e2e-patch-orientation": "/usr/libexec/PlistBuddy -c 'Add :UISupportedInterfaceOrientations~ipad:0 string UIInterfaceOrientationPortrait' ios/build/Build/Products/Debug-iphonesimulator/MyApp.app/Info.plist",
"e2e-build": "detox build --configuration ios && yarn e2e-patch-orientation",
```

This keeps the device in portrait mode but at least the content is shown in portrait. It's not quite ideal because it isn't how the user will experience the app after all

**Comment by LeoNatan** [comment]
Did you check out the documentation?
https://github.com/wix/Detox/blob/master/docs/APIRef.DeviceObjectAPI.md#devicesetorientationorientation

**Comment by Vannevelj** [comment]
I have. When I use `setOrientation('landscape')` then the app itself switches to landscape but the device remains in portrait mode, bringing me back to the 90 degree angle. This happens with and without me injecting `UIInterfaceOrientationPortrait` in the Info.plist.

**Comment by LeoNatan** [comment]
That's a technological limitation that cannot be solved currently. Once https://github.com/wix/Detox/pull/2614 is implemented and merged, it will work as you expect.

In the mean time, you should know that for all intents and purposes, the landscape mode in your app is real landscape, and it is only the simulator bezels that are drawn incorrectly. So your tests shouldn't have issues.

**Comment by Vannevelj** [comment]
That's good to hear, thanks! I'll use my workaround for the time being and will switch to the proper usage once it is available. I appreciate the effort you're putting into Detox, thank you.

**Comment by Vannevelj** [comment]
Not stale, active feature request.

**Comment by Vannevelj** [comment]
Still not stale

**Comment by asafkorem** [comment]
Due to technological limitations, the solution for this requirement is outside the scope of Detox, however you can use this workaround in your project (interact with the Simulator app UI using Apple Script): https://github.com/wix/Detox/issues/2661#issuecomment-1486869562
