### ISSUE TITLE
Detox Test command fails with network requests error

### ISSUE THREAD

**Issue by harshlukka2105** [wix/Detox#2665]
I'm using detox with following config:

`"react": "16.9.0",
  "react-native": "0.61.5"
  "detox": "^18.6.2",
  "jest": "^25.5.4",
  "jest-circus": "^26.6.3"`
  
  detox build command runs perfectly, but detox test fails with the following error:
  
```
detox[13327] INFO:  [DetoxServer.js] server listening on localhost:59074...
detox[13327] INFO:  Example is assigned to emulator-17544 (Pixel_API_28_AOSP)
detox[13327] INFO:  Example: should have welcome screen
detox[13327] INFO:  Example: should have welcome screen [FAIL]

detox[13327] WARN:  [Client.js/PENDING_REQUESTS] App has not responded to the network requests below:
  (id = -1000) isReady: {}

Unresponded network requests might result in timeout errors in Detox tests.

 FAIL  e2e/firstTest.e2e.js
  Example
    ✕ should have welcome screen

  ● Example › should have welcome screen

    DetoxRuntimeError: Failed to run application on the device

    HINT: Most likely, your tests have timed out and called detox.cleanup() while it was waiting for "ready" message (over WebSocket) from the instrumentation process.

      at MonitoredInstrumentation._getInstrumentationCrashError (../node_modules/detox/src/devices/drivers/android/tools/MonitoredInstrumentation.js:68:12)
      at MonitoredInstrumentation._rejectPendingCrashPromise (../node_modules/detox/src/devices/drivers/android/tools/MonitoredInstrumentation.js:56:37)
      at MonitoredInstrumentation._onInstrumentationTerminated (../node_modules/detox/src/devices/drivers/android/tools/MonitoredInstrumentation.js:51:10)
      at Instrumentation._onTerminated (../node_modules/detox/src/devices/drivers/android/tools/Instrumentation.js:52:18)

detox[13326] ERROR: [cli.js] Error: Command failed: jest --config e2e/config.json --testNamePattern '^((?!:ios:).)*$' --maxWorkers 1 e2e
```

I think there is some issue with `device.launchApp()` as the app also doesn't gets launched!

My firstTest.e2e.js file:

```
describe('Example', () => {
  beforeAll(async () => {
    await device.launchApp();
  });

  beforeEach(async () => {
    await device.reloadReactNative();
  });

  it('should have welcome screen', async () => {
    await expect(element(by.id('EditTextId'))).toBeVisible();
  });
});
```

**Comment by Ademar-SJ** [comment]
Same here

**Comment by d4vidi** [comment]
@noomorph seems that the:
```
detox[13327] WARN:  [Client.js/PENDING_REQUESTS] App has not responded to the network requests below:
  (id = -1000) isReady: {}
```
warning isn't very effective when is comes to a simple `isReady`. If I understand correctly, it actually comes off confusing, giving an impression there's an issue with the _device's_ network 🤷🏻 
We need to come up with a better way to describe this use case (e.g. app not loading, or whatever).

**Comment by harshlukka2105** [comment]
It actually solved in my case, 
the problem with my app was i wasn't using ReactActivity as an implementation in mainactivity.java file, 
but i had solved it by using react delegate in my mainActivity.java

**Comment by MoeMamdouh** [comment]
any updates, I'm facing the same issue in iOS
```
App has not responded to the network requests below:
  (id = -1000) isReady: {}

Unresponded network requests might result in timeout errors in Detox tests.
```

**Comment by yusufyildirim** [comment]
In my case, my app was trying to connect to an endpoint in the background and that endpoint was unreachable due to VPN or firewall, etc. doesn't really matter. It's really easy to miss this kind of situation. So, double-check your background activities. If you're confident that's not because of your code, then check the libraries you use

**Comment by MoeMamdouh** [comment]
I had the same issue in iOS **release** build event it was working in **debug** build 
my current react native version `"react-native": "0.61.5"`



i fix it by add in info.plist file

```
<key>NSAllowsArbitraryLoads</key>
<true/>
```
which is added by default since react-native version 0.64

**Comment by d4vidi** [comment]
@MoeMamdouh Setting `NSAllowsArbitraryLoads` to `true` enables _all_ unsecure HTTP traffic and is therefore a bad approach. It can get your app to fail app-store reviews. Read all about it [here](https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity/nsallowsarbitraryloads). Consider using [NSAllowsLocalNetworking](https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity/nsallowslocalnetworking), instead.

**Comment by d4vidi** [comment]
@harshlukka2105 could you please report back with logs generated using the latest Detox version (`18.12.0`)? It would make it easier for us to help, as we've greatly improved logging related to troubleshooting. Be sure to apply an `--debug-synchronization 2000` argument to `detox test`.

**Comment by harshlukka2105** [comment]
> @harshlukka2105 could you please report back with logs generated using the latest Detox version (`18.12.0`)? It would make it easier for us to help, as we've greatly improved logging related to troubleshooting in the last few [releases](https://github.com/wix/Detox/releases). Be sure to apply an `--debug-synchronization 2000` argument to `detox test`.

This issue is actually solved for me, it wasn't an actual detox issue, but an issue on my native side of app. Closing this issue. Thanks btw.

**Comment by d4vidi** [comment]
@harshlukka2105 I'm happy to hear.
Nevertheless, I would appreciate going over the logs _with_ the problem being in-effect, to see whether we've managed to improve the experience by better pin-pointing the source in the logs... 🙏🏻

**Comment by ASchwad** [comment]
I had a similar issue and `--debug-synchronization 2000` solved it for me. Thank you!
