### ISSUE TITLE
System busy

### ISSUE THREAD

**Issue by onnerfors** [wix/Detox#2668]
Hello, my tests started failing out of the blue today, literally between runs without code changes. I read the documentation about synchronization, and tried adding `await device.disableSynchronization();` and `await device.setURLBlacklist([]);` with the failing URL to the `beforeAll()`, was that the right place? Anyway I didn't get it to work and all tests currently time out. Here's what's happening every time: 

```
detox[22790] INFO:  [actions.js] The system is busy with the following tasks:

Dispatch Queue
⏱ Queue: “Main Queue (<OS_dispatch_queue_main: com.apple.main-thread>)” with 1 work item

Run Loop
⏱ “Main Run Loop”

One-time Events
⏱ “Network Request” with object: “URL: “https://api.appcenter.ms/v0.1/public/sdk/apps/d0dbb4eef-0ac8-4478-9fd8-090c37785d52/releases/latest?release_hash=b79e678f37c0cdc0f8e8fe8d3a6cd4af9def07cc2a9f6dcff2a3f92022d8d6fd””
```

Seems like the answer is simple, but I can't find it. Thanks

**Comment by noomorph** [comment]
There's a section in the docs: https://github.com/wix/Detox/blob/master/docs/Troubleshooting.Synchronization.md#controlling-network-synchronization

**Comment by onnerfors** [comment]
Thanks @noomorph, read that and tried the solutions but didn't get it to work, maybe I did it wrong. Anyhow the problem was solved by restarting my Simulator app
