### ISSUE TITLE
SwiftUI Element matchers, visibility & actions (like tap) not working with detox 18.6.2

### ISSUE THREAD

**Issue by distributedinfinity** [wix/Detox#2670]
### Description
The same bug was raised in a prior issue https://github.com/wix/Detox/issues/2636#issue-806665038 , sadly the fix doesn't seem to work with the same sample repo with the latest detox release. @LeoNatan can you please investigate 🙏🏼, 

Left a comment with more details about it here  https://github.com/wix/Detox/issues/2636#issuecomment-784441277

- [X] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction

Same steps as the prior issue mentioned above, plus more details on this comment https://github.com/wix/Detox/issues/2636#issuecomment-784441277

#### Expected behavior
Detox should be able to match, view SwiftUI elements & interact with them

#### Screenshots
Please see the issue mentioned above.

#### Environment (please complete the following information):
Please see the issue mentioned above.

#### If you are experiencing a timeout in your test

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://github.com/wix/Detox/blob/master/docs/Troubleshooting.Synchronization.md#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much), I have read [synchronization debug documentation](https://github.com/wix/DetoxSync/blob/master/IdleStatusDocumentation.md) and am providing the relevant synchronization debug output below:

Please see the issue mentioned above.

#### Device and verbose Detox logs

- [X] I have run my tests using the `--loglevel trace` argument and am providing the verbose log below:

Please see the issue mentioned above.

**Comment by d4vidi** [comment]
Closing as a dup
