### ISSUE TITLE
waitFor... toBeVisible() method fails in the same case when expect... toBeVisible() passes

### ISSUE THREAD

**Issue by olexandr13** [wix/Detox#2671]
### Description

I have tested this issue on the latest Detox release and it still reproduces. Tested on:
- 18.7
- 17.14.1

#### Reproduction
1. Next code will fail on the 2nd line.
` await expect(element(by.text('OP 1315')).atIndex(0)).toBeVisible();
   await waitFor(element(by.text('OP 1315')).atIndex(0)).toBeVisible().withTimeout(5000);`

AR:
![image](https://user-images.githubusercontent.com/16742970/109969008-10c6d100-7cfc-11eb-8315-8b1e49d41e65.png)

#### Expected behavior
Both methods should pass.

#### Environment (please complete the following information):
 - Detox: 18.7
 - React Native: 4.13.1
 - Node: v13.14.0
 - Device: iPhone 11
 - Xcode: 12.2
 - iOS: 14.2
 - macOS: 10.15.7

**Comment by noomorph** [comment]
Could you attach logs (--record-logs all), please?

**Comment by noomorph** [comment]
@olexandr13, unfortunately your bug report lacks something, because I am not able to reproduce it as-is:

```diff
diff --git a/detox/test/e2e/01.sanity.test.js b/detox/test/e2e/01.sanity.test.js
index 31c0b258..b96dbbce 100644
--- a/detox/test/e2e/01.sanity.test.js
+++ b/detox/test/e2e/01.sanity.test.js
@@ -4,10 +4,11 @@ describe('Sanity', () => {
     await detox.traceCall('Navigate to sanity', () => element(by.text('Sanity')).tap());
   });

-  it('should have welcome screen', async () => {
-    await expect(element(by.text('Welcome'))).toBeVisible();
-    await expect(element(by.text('Say Hello'))).toBeVisible();
-    await expect(element(by.text('Say World'))).toBeVisible();
+  it.only('should have welcome screen', async () => {
+    await expect(element(by.text('Welcome')).atIndex(0)).toBeVisible();
+    console.warn('1');
+    await waitFor(element(by.text('Welcome')).atIndex(0)).toBeVisible().withTimeout(5000);
+    console.warn('2');
   });

   it('should show hello screen after tap', async () => {
```

![image](https://user-images.githubusercontent.com/1962469/114524710-1e05a280-9c4e-11eb-9d42-26677914e2ce.png)

Please get back to us with new details.

**Comment by d4vidi** [comment]
@olexandr13 please report back soon with full details, so we could try to help.
Also, regarding the environment info provided:
> React Native: 4.13.1

`14.13.1` is invalid. Could you provide the actual RN version you've used? If it's .64, could you try RN .63.x?
