### ISSUE TITLE
Mocking with react-native-repackager

### ISSUE THREAD

**Issue by dobiedad** [wix/detox#269]
Hi everyone, 

Ive been following the mocking docs but i cant seem to get it to work. I was wondering if someone could help me out.

My app uses a file called `api.js` which makes http requests to the server. 
I am trying to replace this file with `e2e/api.mock.js` using [react-native-repackager](https://github.com/wix/react-native-repackager)

According to the  [react-native-repackager](https://github.com/wix/react-native-repackager) docs
i need to run `node node_modules/react-native/local-cli/cli.js start --customExtensions=mock`

Im not sure where this is supposed to be ran in terms of detox because `detox build` takes care of the building. I added that line to my npm start script but that doesnt seem to do it. Any ideas ?

**Comment by zcsongor** [comment]
did you solve your problem?
