### ISSUE TITLE
Mocking API backend, no effect?

### ISSUE THREAD

**Issue by ckcollab** [wix/Detox#2700]
First of all: thanks so much for all the hard work, docs, etc. in Detox. I appreciate it hugely and tried hard to find a solution to this but I am rather new to React Native dev.

I've tried a series of tools to mock an API backend while running Detox, following all of their installation instructions a few times from scratch and am still failing. I've tried Mock Service Worker and Mirage at least, maybe a couple more directly targeting axios.

One thing I am realizing: most of these guys require some modification of `jest.setup.js` but it seems Detox never hits this file! I have tried modifying `environment.js` to include some [required pieces of mirage...](https://miragejs.com/quickstarts/react-native/react-native-testing-library/)

```js
// jest.setup.js
global.self = global
global.window = {}
global.XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest
```

I put this, basically as is, inside `environment.js`...

```js
// environment.js
const {
  DetoxCircusEnvironment,
  SpecReporter,
  WorkerAssignReporter,
} = require('detox/runners/jest-circus');

class CustomDetoxEnvironment extends DetoxCircusEnvironment {
  constructor(config, context) {
    super(config, context);

    // Can be safely removed, if you are content with the default value (=300000ms)
    this.initTimeout = 300000;

    // This takes care of generating status logs on a per-spec basis. By default, Jest only reports at file-level.
    // This is strictly optional.
    this.registerListeners({
      SpecReporter,
      WorkerAssignReporter,
    });
  }
}

require('react-native-browser-polyfill')

global.self = global
global.window = {}
global.XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest

module.exports = CustomDetoxEnvironment;
```

And the actual tests with mock server jazz..

```js
// tests.e2e.js
let server

describe('The app', () => {

  beforeAll(async () => {
    await device.launchApp()
  })
  beforeEach(() => {
    server = createServer({
      urlPrefix: "https://our-staging-app.herokuapp.com",
    })
  })
  afterEach(() => {
    server.shutdown()
  })

  it('after tour you can register', async () => {
    // mock registering
    server.post("/api/users/register/", () => [
      { id: 1, name: "Luke" },
      { id: 2, name: "Leia" },
    ])

    // do registration
    emailInput.typeText("test@test.com")
    passwordInput.typeText("password")

    await element(by.label("User Agreement Checkbox")).tap()

    await element(by.text('Register')).tap()
    
    /***************************************************
     * Above click should have been caught by mock, but
     * it proceeds as normal!
     ***************************************************/
  })
})

```

and that certainly isn't working -- no errors just silently continues, with _seemingly_ no HTTP mocking going on.

Appreciate any help or guidance! I'll certainly update this if I sherlock my way into any solutions :)

**Comment by devinjameson** [comment]
Having the same issue.

**Comment by ckcollab** [comment]
@devinjameson I'll let you know if I figure this out, will probably look at it again this week.. I think it's likely a misunderstanding in how this is all spun up

**Comment by d4vidi** [comment]
@ckcollab thanks for the kind words!
Regarding the mocking itself - have you tried looking into our [mocking guide](https://github.com/wix/Detox/blob/master/docs/Guide.Mocking.md)? It's slightly out of date, but the general guidelines still apply.
In essence, you can't mock anything without applying the equivalent adjustments in the app itself. Typically, this is done by refactoring various server URL's into dedicated config js-files (e.g. server-config.js), and then introducing e2e-test-dedicated files equivalent to those (only, with `localhost`-based URL's.)

Let's continue the discussion on SO (please paste a link).

**Comment by ckcollab** [comment]
What I ended up doing, for future folks, was exactly as @d4vidi recommended (a separate `*.e2e.js` file hitting a different endpoint during tests)

Here's how I am running an express server during tests .. this may be stupid, but works!

```js
const express = require('express');
let server;

beforeAll(async () => {
    const app = express();

    app.post('/api/users/register/', (req, res) => {
      res.status(400)
      res.send({"email": ["Test error: Email is required!"]})
    })

    await new Promise(function(resolve) {
        server = app.listen(9091, "127.0.0.1", function() {
            console.log(` Running server on '${JSON.stringify(server.address())}'...`);
            resolve();
        });
    });
})

afterAll(() => {
    server.close()
})
```

**Comment by d4vidi** [comment]
@ckcollab That was exactly the point 👍🏻
