### ISSUE TITLE
Enable location with high accuracy on android

### ISSUE THREAD

**Issue by saransh-malik** [wix/Detox#2704]
I have an app that needs to use location at high accuracy and I am unable to test app with that on android. On iOS things work fine, but on android as and when I try to fetch location, I see this on the screen

<img width="394" alt="Screenshot 2021-03-26 at 12 59 59 PM" src="https://user-images.githubusercontent.com/56735972/112597567-48282980-8e33-11eb-9b69-b3b42babdae7.png">

Is there a way to actually press ok, on this popup. I tried `by.text` method but it just doesn't work. I want this to work or else all my location related things in the app don't work at all.

**Comment by d4vidi** [comment]
@saransh-malik This kind of popups is invisible to Detox (and Espresso), I'm afraid. As a different strategy, may I suggest enabling location in advance, so as to avoid having the popup appear in the first place: try to follow [this discussion](https://android.stackexchange.com/questions/40147/is-it-possible-to-enable-location-services-via-shell). Note that in Detox - which can run on multiple devices, `adb` can be (roughly) executed like so:

```js
const { execSync } = require('child_process');
execSync(`adb -s ${device.id} shell <command>`);
```
> Syntax not verified

**Comment by saransh-malik** [comment]
I'll try to work this out. But I guess if not last resort is just mocking location lib somehow. Thanks for your help :)
