### ISSUE TITLE
Signal 11 was raised

### ISSUE THREAD

**Issue by MFrat** [wix/Detox#2706]
### Description
All tests fails very fast with `Signal 11 was raised`. Sometimes it works, but as soon as some test need reinstall app, it breaks.

- [x] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction
1. Build iOS .app
2. Start tests
3. All tests will fail very fast

#### Environment (please complete the following information):
 - Detox: 18.7.1
 - React Native: 0.63.4
 - Node: 14.15.3
 - Device: Simulator iPhone 11 (13.7)
 - Xcode: 11.7
 - iOS: 13.7
 - macOS: Cataline 10.15.7

### Logs
```
thrown: "Signal 11 was raised
    (
        0   Detox                               0x000000010a915eb5 +[NSThread(DetoxUtils) dtx_demangledCallStackSymbols] + 37
        1   Detox                               0x000000010a9190c0 __DTXHandleCrash + 464
        2   Detox                               0x000000010a919805 __DTXHandleSignal + 59
        3   libsystem_platform.dylib            0x00007fff522f95fd _sigtramp + 29
        4   ???                                 0x000000010b6a8058 0x0 + 4486496344
        5   libobjc.A.dylib                     0x00007fff512b7a16 objc_object::sidetable_release(bool) + 174
        6   libobjc.A.dylib                     0x00007fff512b3f5a _object_remove_assocations + 240
        7   libobjc.A.dylib                     0x00007fff512b1474 objc_destructInstance + 79
        8   libobjc.A.dylib                     0x00007fff512b7296 -[NSObject dealloc] + 21
        9   libobjc.A.dylib                     0x00007fff512b7a16 objc_object::sidetable_release(bool) + 174
        10  libobjc.A.dylib                     0x00007fff512b9077 AutoreleasePoolPage::releaseUntil(objc_object**) + 147
        11  libobjc.A.dylib                     0x00007fff512b8f96 objc_autoreleasePoolPop + 199
        12  FrontBoardServices                  0x00007fff36d0e75f -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 228
        13  FrontBoardServices                  0x00007fff36d29a52 __86-[FBSWorkspaceScenesClient sceneID:createWithParameters:transitionContext:completion:]_block_invoke + 355
        14  libdispatch.dylib                   0x00007fff520dc8cb _dispatch_client_callout + 8
        15  libdispatch.dylib                   0x00007fff520df292 _dispatch_block_invoke_direct + 285
        16  FrontBoardServices                  0x00007fff36d4f6e9 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 30
        17  FrontBoardServices                  0x00007fff36d4f3d7 -[FBSSerialQueue _queue_performNextIfPossible] + 441
        18  FrontBoardServices                  0x00007fff36d4f8e6 -[FBSSerialQueue _performNextFromRunLoopSource] + 22
        19  CoreFoundation                      0x00007fff23da1c91 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
        20  CoreFoundation                      0x00007fff23da1bbc __CFRunLoopDoSource0 + 76
        21  CoreFoundation                      0x00007fff23da1394 __CFRunLoopDoSources0 + 180
        22  CoreFoundation                      0x00007fff23d9bf8e __CFRunLoopRun + 974
        23  CoreFoundation                      0x00007fff23d9b8a4 CFRunLoopRunSpecific + 404
        24  GraphicsServices                    0x00007fff38c05bbe GSEventRunModal + 139
        25  DetoxSync                           0x000000010b5ac34d __detox_sync_UIApplication_run + 362
        26  UIKitCore                           0x00007fff49372964 UIApplicationMain + 1605
        27  APP_NAME                                0x00000001088cc800 main + 112
        28  libdyld.dylib                       0x00007fff5211c1fd start + 1
        29  ???                                 0x000000000000000a 0x0 + 10
    )"
```

**Comment by deermichel** [comment]
I have a similar issue with Xcode 12.4, Big Sur 11.2.3, Detox 18.9.0, RN 0.64, iPhone 11 Simulator with iOS 14.4:

```
App crashed in test '...', here are the crash details:
Signal 11 was raised
(
	0   Detox                               0x0000000109657eb5 +[NSThread(DetoxUtils) dtx_demangledCallStackSymbols] + 37
	1   Detox                               0x000000010965b0c0 __DTXHandleCrash + 464
	2   Detox                               0x000000010965b805 __DTXHandleSignal + 59
	3   libsystem_platform.dylib            0x00007fff6115cd7d _sigtramp + 29
	4   libsystem_c.dylib                   0x00007fff86d4a728 __global_locale + 0
	5   CoreFoundation                      0x00007fff20490049 -[__NSDictionaryM dealloc] + 128
	6   libobjc.A.dylib                     0x00007fff2018f834 objc_object::sidetable_release(bool, bool) + 174
	7   libobjc.A.dylib                     0x00007fff2018bb85 _object_remove_assocations + 580
	8   libobjc.A.dylib                     0x00007fff20188f25 objc_destructInstance + 84
	9   libobjc.A.dylib                     0x00007fff2018efb8 -[NSObject dealloc] + 21
	10  PLAYSPORTS                          0x0000000105ffa7f5 -[FBSDKGraphRequestConnection dealloc] + 96
	11  libobjc.A.dylib                     0x00007fff2018f834 objc_object::sidetable_release(bool, bool) + 174
	12  CFNetwork                           0x00007fff236d0b10 _CFNetworkHTTPConnectionCacheSetLimit + 163652
	13  CFNetwork                           0x00007fff23519ec5 CFNetwork + 28357
	14  DetoxSync                           0x000000010a989270 ____detox_sync_dispatch_wrapper_block_invoke + 23
	15  libdispatch.dylib                   0x00007fff2010532f _dispatch_call_block_and_release + 12
	16  libdispatch.dylib                   0x00007fff20106508 _dispatch_client_callout + 8
	17  libdispatch.dylib                   0x00007fff2010c3f9 _dispatch_lane_serial_drain + 715
	18  libdispatch.dylib                   0x00007fff2010cfab _dispatch_lane_invoke + 458
	19  libdispatch.dylib                   0x00007fff20117577 _dispatch_workloop_worker_thread + 782
	20  libsystem_pthread.dylib             0x00007fff61167499 _pthread_wqthread + 314
	21  libsystem_pthread.dylib             0x00007fff61166467 start_wqthread + 15
)
```

Works perfectly with Detox 17.14.9.

**Comment by deermichel** [comment]
> I have a similar issue with Xcode 12.4, Big Sur 11.2.3, Detox 18.9.0, RN 0.64, iPhone 11 Simulator with iOS 14.4:
> 
> ```
> App crashed in test '...', here are the crash details:
> Signal 11 was raised...
> ```
> 
> Works perfectly with Detox 17.14.9.

**EDIT**
I tracked it down to the `@react-native-firebase/perf` package. Removing it solved the crashes for me.

somewhat related:
https://github.com/wix/Detox/issues/2627
https://github.com/wix/Detox/issues/2641
https://github.com/wix/DetoxSync/issues/5
https://github.com/firebase/firebase-ios-sdk/issues/7277

**Comment by MFrat** [comment]
@deermichel, nice catch. But what did you mean by removing? You just don't call or remove it entire from dependencies?

**Comment by deermichel** [comment]
I removed it from the deps for we didn't really use it anyways.

**Comment by MFrat** [comment]
Any news about this issue?

**Comment by MFrat** [comment]
@d4vidi i will investigate more, but this error only occurrs during detox tests. But i think this has something to do with Firebase perf as mentioned earlier, i use it here.

I will post results here as soon as i finish investigating.

**Comment by MFrat** [comment]
@d4vidi, i confirm firebase performance is the root cause. Everything started to work after removing it.

**Comment by shamilovtim** [comment]
I provide more context in #2641 with a full crash log

**Comment by d4vidi** [comment]
@MFrat Thanks for posting back. This is a great find. What's your ultimate solution, then?

**Comment by MFrat** [comment]
@d4vidi i will try this solution https://github.com/firebase/firebase-ios-sdk/issues/8095#issuecomment-842728509

**Comment by d4vidi** [comment]
@MFrat ok LMK then.

**Comment by MFrat** [comment]
@d4vidi Didn't worked :(

**Comment by karthikxorstack** [comment]
The app has crashed, see the details below:

    Signal 11 was raised
    (
        0   Detox                               0x000000010e8fddf5 +[NSThread(DetoxUtils) dtx_demangledCallStackSymbols] + 37
        1   Detox                               0x000000010e900bfc __DTXHandleCrash + 460
        2   Detox                               0x000000010e90133c __DTXHandleSignal + 59
        3   libsystem_platform.dylib            0x00007ff8377405ed _sigtramp + 29
        4   Foundation                          0x00007ff800f3d1d4 .str + 1918
        5   DetoxSync                           0x000000010ec82b1c -[_DTXTimerTrampoline setDisplayLink:] + 78
        6   DetoxSync                           0x000000010ec8043b +[DTXTimerSyncResource _timerProxyWithDisplayLink:] + 99
        7   DetoxSync                           0x000000010ec804cd +[DTXTimerSyncResource existingTimerProxyWithDisplayLink:create:] + 119
        8   DetoxSync                           0x000000010ec765e9 +[DTXSyncManager trackDisplayLink:name:] + 87
        9   DetoxSync                           0x000000010ec69ff1 -[NSObject(REANodesManagerDTXSpy) __detox_sync_startUpdatingOnAnimationFrame] + 103
        10  VyaBusinessiPad                     0x000000010c20c977 -[REANodesManager postRunUpdatesAfterAnimation] + 55
        11  VyaBusinessiPad                     0x000000010c20bc7c -[REANode markUpdated] + 124
        12  VyaBusinessiPad                     0x000000010c20b5b2 -[REANode dangerouslyRescheduleEvaluate] + 146
        13  VyaBusinessiPad                     0x000000010c20bb71 -[REANode addChild:] + 145
        14  VyaBusinessiPad                     0x000000010c20dd1c -[REANodesManager connectNodes:childID:] + 796
        15  VyaBusinessiPad                     0x000000010c209ea2 __35-[REAModule connectNodes:childTag:]_block_invoke + 66
        16  VyaBusinessiPad                     0x000000010c20af0e __42-[REAModule uiManagerWillPerformMounting:]_block_invoke + 382
        17  VyaBusinessiPad                     0x000000010c346786 __44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke + 374
        18  VyaBusinessiPad                     0x000000010c346a99 __44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke.493 + 393
        19  VyaBusinessiPad                     0x000000010c34ec3a __RCTExecuteOnMainQueue_block_invoke + 26
        20  DetoxSync                           0x000000010ec6b3b7 ____detox_sync_dispatch_wrapper_block_invoke + 23
        21  libdispatch.dylib                   0x00007ff80013be40 _dispatch_call_block_and_release + 12
        22  libdispatch.dylib                   0x00007ff80013d0d9 _dispatch_client_callout + 8
        23  libdispatch.dylib                   0x00007ff80014cb86 _dispatch_main_queue_drain + 1330
        24  libdispatch.dylib                   0x00007ff80014c646 _dispatch_main_queue_callback_4CF + 31
        25  CoreFoundation                      0x00007ff8003b26cc __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
        26  CoreFoundation                      0x00007ff8003acfbe __CFRunLoopRun + 2429
        27  CoreFoundation                      0x00007ff8003ac264 CFRunLoopRunSpecific + 560
        28  GraphicsServices                    0x00007ff809b4024e GSEventRunModal + 139
        29  UIKitCore                           0x000000010fdf27bf -[UIApplication _run] + 994
        30  DetoxSync                           0x000000010ec713a4 __detox_sync_UIApplication_run + 362
        31  UIKitCore                           0x000000010fdf75de UIApplicationMain + 123
        32  VyaBusinessiPad                     0x000000010bd40500 main + 96
        33  dyld                                0x000000010e524384 start_sim + 10
        34  ???                                 0x000000010ed4741f 0x0 + 4543771679
    )

      1 | describe('Login Screen', () => {
      2 |   beforeAll(async () => {
    > 3 |     await device.launchApp();
        |                  ^
      4 |   });
      5 |
      6 |   beforeEach(async () => {

      at launchApp (e2e/starter.test.js:3:18)
      at tryCatch (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)
      at Generator.<anonymous> (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)
      at Generator.next (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21)
      at tryCatch (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)
      at invoke (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:75:20)
      at node_modules/@babel/runtime/helpers/regeneratorRuntime.js:96:13
      at callInvokeWithMethodAndArg (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:95:18)
      at AsyncIterator.value (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:99:131)
      at AsyncIterator.next (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21)
      at Object.exports.async (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:205:63)
      at Object.async (e2e/starter.test.js:2:13) 





......I'm also getting same issue / can i find any solution
