### ISSUE TITLE
Detox test hangs sometime on CI 

### ISSUE THREAD

**Issue by saransh-malik** [wix/Detox#2709]
### Description
My test cases run fine most of the times, but some times oddly it just can't run tests at all. It works fine on my local always. I tried to put trace mode on to see what exactly was going wrong and logs attached below just keep on repeating. If I just start it all over again, the issue won't repeat and tests go just fine. Any ideas on what could be messing up here

- [x] I have tested this issue on the latest Detox release and it still reproduces

#### Expected behavior
Test should just run fine every time

#### Environment (please complete the following information):
 - Detox: 18.7.0
 - React Native: 0.63.2
 - Node: 12
 - Device: iPhone 11 Pro
 - Xcode: 12.1
 - iOS: 14
 - macOS:  10.15.7

#### Device and verbose Detox logs

- [x] I have run my tests using the `--loglevel trace` argument and am providing the verbose log below:
```
detox[16880] INFO:  [actions.js] The system is busy with the following tasks:
Dispatch Queue
⏱ Queue: “Main Queue (<OS_dispatch_queue_main: com.apple.main-thread>)” with 3 work items
Run Loop
⏱ “Main Run Loop”
UI Elements
⏱ 2 views awaiting display
⏱ 3 layers awaiting layout
⏱ 12 layers awaiting display
detox[16880] TRACE: [AsyncWebSocket.js/WEBSOCKET_SEND] {"type":"currentStatus","params":{},"messageId":509}
detox[16880] TRACE: [DetoxServer.js/MESSAGE] role=tester action=currentStatus (sessionId=f34922c9-14ed-3803-5c17-284782d6a344)
detox[16880] TRACE: [DetoxServer.js/MESSAGE] role=app action=currentStatusResult (sessionId=f34922c9-14ed-3803-5c17-284782d6a344)
detox[16880] TRACE: [AsyncWebSocket.js/WEBSOCKET_MESSAGE] {"params":{"messageId":509,"status":"The system is busy with the following tasks:\n\nDispatch Queue\n⏱ Queue: “Main Queue (<OS_dispatch_queue_main: com.apple.main-thread>)” with 3 work items\n\nRun Loop\n⏱ “Main Run Loop”\n\nUI Elements\n⏱ 2 views awaiting display\n⏱ 3 layers awaiting layout\n⏱ 12 layers awaiting display"},"messageId":509,"type":"currentStatusResult"}
```

**Comment by d4vidi** [comment]
@saransh-malik seems there's an issue with your app, perhaps a race-condition that keeps it from loading. It doesn't seem like an issue with Detox (rather, Detox seems to report the status quite clearly).
