### ISSUE TITLE
Detox test on iOS hangs because of healthkit permission

### ISSUE THREAD

**Issue by naum43312016** [wix/Detox#2711]
When I run detox test on iOS I got health access popup and because of it detox hangs, I have `permissions: { health: 'YES' }}); `when I am launching my app, but I am trying to run it on CI, and my test always hangs because of this. Every time on new virtual machine I get this problem. Image
<img width="389" alt="Screen Shot 2021-03-30 at 4 18 52 PM" src="https://user-images.githubusercontent.com/31067029/113110177-729d2c80-920f-11eb-84bc-e4d8e47dbe3e.png">

**Comment by d4vidi** [comment]
@alon-ha is still applicable? If so, let's reopen
