### ISSUE TITLE
Unify debug-sync logs between platforms

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#2714]
**Is your feature request related to a problem? Please describe.**
Related to #1788.
At the moment, debug-sync logs are quite different on Android and iOS. The experience of a user using both platforms intermittently or simultaneously, can therefore be inconsistent and confusing.

Android:
![Screen Shot 2021-04-06 at 12 15 26](https://user-images.githubusercontent.com/9818880/113688550-13895d00-96d2-11eb-9214-db200eacdf79.png)

iOS:
![Screen Shot 2021-04-06 at 12 19 27](https://user-images.githubusercontent.com/9818880/113688889-65ca7e00-96d2-11eb-9eab-60ac242cd65f.png)

**Describe the solution you'd like**
While names of resources are platform-specific, and therefore it is okay for them to be different when tests are executed on either platform, the overall log template should be unified. For example:

```
App synchronization debug: The app appears to be busy, due to:
  - <Description of busy resource #1>
  - <Description of busy resource #2>
  -  (e.g. "Animations are running on the screen")
```

While this example may be a bit oversimplified (e.g. no detailed description mentioned here, such as the list of network requests' URL's), it nevertheless conveys the overall approach.

As for the technical details, it's quite obvious that the expected architecture is that instead of the tested device sending back text containing all the info back to Detox, it ought to send back a list of busy resources descriptions, and have the Detox tester apply that into a unified log.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by noomorph** [comment]
This is a good place to start the discussion.
Let's clarify how many idling resources we have in iOS and Android, what their names are and what extra properties we could have extracted from them if we wanted.

@d4vidi, @alon-ha

**Comment by d4vidi** [comment]
IMPORTANT note: must keep https://github.com/wix/DetoxSync/blob/master/IdleStatusDocumentation.md up to date with these changes, as they take place.

**Comment by asafkorem** [comment]
Done in https://github.com/wix/Detox/pull/3064. However, as agreed, we still left to unify the network calls reports: https://github.com/wix/Detox/issues/3128
