### ISSUE TITLE
Test is not starting on release mode 

### ISSUE THREAD

**Issue by naum43312016** [wix/Detox#2718]
### Describe the bug

When i try to run test on Android release the tests just get stuck. App is just idle and the test times out.
For this to work i need manually start metro, but in release its should be unnecessary, on IOS everything work fine locally and in bitrise, but android is not working on release mode.
Maybe I am mistaken and i should start metro before test, but in IOS its working without it (it does it automatically).
Thanks in advance
### Steps To Reproduce

I have tested this issue on the latest Detox release and it still reproduces

1. build android in release mode
2. try to test it without metro 

### Expected behavior

Emulator should open app and start tests

### Detox Trace-Logs

[detox_pid_46890.json.log](https://github.com/wix/Detox/files/6279254/detox_pid_46890.json.log)
[detox_pid_46890.log](https://github.com/wix/Detox/files/6279255/detox_pid_46890.log)

### Device logs (adb logcat)

[emulator-12692 2021-04-08 14-08-48Z.startup.log](https://github.com/wix/Detox/files/6279252/emulator-12692.2021-04-08.14-08-48Z.startup.log)

### Screenshots

<img width="1402" alt="Screen Shot 2021-04-08 at 5 08 05 PM" src="https://user-images.githubusercontent.com/31067029/114041254-0cf31500-988d-11eb-829f-7dd48503e698.png">

### Environment (please complete the following information):
 - Detox:18.7.1
 - React Native:0.63.3
 - Node:15.11.0
 - Device:Android emulator (Pixel_4_API_29)
 - OS: macOS
 - Test-runner (select one): `jest-circus`

**Comment by noomorph** [comment]
Could you please retrieve the logs after upgrading to the latest Detox version? They might be a bit more informative. Thanks

**Comment by naum43312016** [comment]
Hi i tried to run ws://localhost:${port} on device, it did not work, i am sending logs after upgrading to last version of detox. Thanks @noomorph 
[detox_pid_51114.json.log](https://github.com/wix/Detox/files/6291286/detox_pid_51114.json.log)
[detox_pid_51114.log](https://github.com/wix/Detox/files/6291287/detox_pid_51114.log)
[emulator-19626 2021-04-11 06-30-03Z.startup.log](https://github.com/wix/Detox/files/6291288/emulator-19626.2021-04-11.06-30-03Z.startup.log)

**Comment by naum43312016** [comment]
The packager does not seem to be running as we got an IOException requesting its status: Failed to connect to /10.0.2.2:8081.
@noomorph it is error that i get, what can i do with that?
Thanks

**Comment by noomorph** [comment]
@d4vidi , the logs leave me confused. I clearly see that Detox was trying to send "login" but never succeeded despite the fact that DetoxServer port had been reversed.

@naum43312016 , first of all, I was asking you to check not `ws://...` protocol, but HTTP:

![image](https://user-images.githubusercontent.com/1962469/114520899-936f7400-9c4a-11eb-90e1-57ccebe4c3ca.png)

Next time, check what random port Detox assigns to Detox server and try to open that url in browser (on desktop and in emulator).

Also, it seems like you have Firebase there in your app — reportedly, you'll need to blacklist a URL with a permanent connection (at least from the feedback I was seeing in the other issues). 

But again, the problem of Detox-on-device not connecting to Detox-in-Node.js is a worse problem that must solved first.

**Comment by naum43312016** [comment]
@noomorph Thank you, i will try to connect to http, and let you know if this works (on desktop and in emulator).

**Comment by naum43312016** [comment]
@noomorph i can connect on desktop and in emulator
<img width="407" alt="Screen Shot 2021-0
[detox_pid_53670.json.log](https://github.com/wix/Detox/files/6302609/detox_pid_53670.json.log)
[detox_pid_53670.log](https://github.com/wix/Detox/files/6302610/detox_pid_53670.log)
[emulator-15260 2021-04-13 09-18-07Z.startup.log](https://github.com/wix/Detox/files/6302611/emulator-15260.2021-04-13.09-18-07Z.startup.log)


4-13 at 12 13 46 PM" src="https://user-images.githubusercontent.com/31067029/114528522-c5d09f80-9c51-11eb-9c8c-6a2e3ce789de.png">
<img width="1311" alt="Screen Shot 2021-04-13 at 12 13 59 PM" src="https://user-images.githubusercontent.com/31067029/114528542-c9642680-9c51-11eb-9487-60856e1d5c27.png">


Here is screenshots and also new logs, its very weird.
Thanks, hope you will help me with this problem.

**Comment by naum43312016** [comment]
screenshot from emulator
<img width="407" alt="Screen Shot 2021-04-13 at 12 13 46 PM" src="https://user-images.githubusercontent.com/31067029/114529406-953d3580-9c52-11eb-92f0-cf20b2169d17.png">

**Comment by d4vidi** [comment]
@naum43312016 May I suggest going over [this](https://github.com/wix/Detox/blob/master/docs/Introduction.Android.md#problem-the-app-loads-but-tests-fail-to-start-in-sdk--28) Android troubleshooting section: Setting up exclusions for unsecured HTTP traffic.
Also, from the device logs, I see that there is/are timers consistently in-flight, waiting for expiration periods. That keeps the app from ever going idle, thus keeping it "stuck". Do you use `setInterval` on your main screen, or repeatedly defining timers using `setTimeout`? BTW, sorry this isn't all-too visible to users ATM - it will be solved later today in #2703.

**Comment by naum43312016** [comment]
@d4vidi thanks for your reply, i already have android:usesCleartextTraffic="true" , i will look up for timers, i thought that i disabled all animations, setInterval and timeouts, but the problem is that Detox server is not connected, but on ios everything works perfect,
Thank you

**Comment by noomorph** [comment]
@naum43312016, please keep an eye on Detox: when our CI finishes and releases `18.11.2` — try to re-run your app again and give me the new logs (from Node.js, not the Android app, e.g: `detox_pid_51114.json.log`, `detox_pid_51114.log`). I want to know if the app succeeds to set up at least an anonymous web socket or not.

**Comment by d4vidi** [comment]
An update to @noomorph's comment: Please try Detox `18.12.0` instead, as it would add the necessary info I've mentioned with respect to debugging apps busy/freezing states (#2703). Thanks!!!

**Comment by naum43312016** [comment]
Thank you I will send new logs in 30 minutes

**Comment by naum43312016** [comment]
@d4vidi new logs after upgrading to 18.12.0, thanks.
[detox_pid_79531.json.log](https://github.com/wix/Detox/files/6331163/detox_pid_79531.json.log)
[detox_pid_79531.log](https://github.com/wix/Detox/files/6331164/detox_pid_79531.log)

**Comment by d4vidi** [comment]
As suspected - the work in #2703 indeed now tells the story. There is a vast amount of consequent logs showing what's holding things back:
```
detox[79531] INFO:  [APP_STATUS] App synchronization debug: 
The app is busy, due to: 
	 - Activity on the React-Native bridge
	 - Enqueued timers
```
As suspected, there are timers being enqueued endlessly. Please revisit the JS code involving the main screen. There has to be something - even if indirectly, that triggers and retriggers timers endlessly.

Also, note the device seems to be able to connect back to the Detox tests successfully:
```
detox[79531] DEBUG: [WSS_CREATE] Detox server listening on localhost:54084...
detox[79531] DEBUG: [WSS_CONNECTION, #54085] registered a new connection.
detox[79531] TRACE: [WS_OPEN] opened web socket to: ws://localhost:54084
detox[79531] TRACE: [WS_SEND] {"type":"login","params":{"sessionId":"ce27084c-7182-69ae-7979-fb68957de0c6","role":"tester"},"messageId":0}
detox[79531] TRACE: [WSS_GET_FROM, #54085] {"type":"login","params":{"sessionId":"ce27084c-7182-69ae-7979-fb68957de0c6","role":"tester"},"messageId":0}
detox[79531] TRACE: [SESSION_CREATED] created session ce27084c-7182-69ae-7979-fb68957de0c6
detox[79531] TRACE: [WSS_SEND_TO, #tester] {"type":"loginSuccess","params":{"testerConnected":true,"appConnected":false},"messageId":0}
detox[79531] TRACE: [SESSION_JOINED] tester joined session ce27084c-7182-69ae-7979-fb68957de0c6
```

**Comment by naum43312016** [comment]
Thank you for your help, I will look for timers on the main screen

**Comment by d4vidi** [comment]
My suggestions: try to swizzle `setTimer()` and `setInterval()` globally, making the original call alongside a preliminary call to `console.trace('setTimer or setInterval')`. The resulted stacktrace may convey the source.

**Comment by d4vidi** [comment]
@naum43312016 could you enlighten us with any insights?

**Comment by jamesmcn1** [comment]
Hey was there a fix to this? We are getting this error now. Detox tests working fine locally but not on Bitrise with release mode. Seems to be lots of logs saying:
```
The app is busy, due to: 
	 - Activity on the React-Native bridge
	 - Enqueued timers
```
