### ISSUE TITLE
Do parallel tests work on android? 

### ISSUE THREAD

**Issue by badsyntax** [wix/Detox#2729]
The docs don't mention anything about `--workers `(with jest) being only supported on iOS: https://github.com/wix/Detox/blob/master/docs/Guide.ParallelTestExecution.md

But the cli help mentions that `--workers` is "iOS Only". Running `./node_modules/.bin/detox test --help` shows:

```console
-w, --workers             [iOS Only] Specifies the number of workers the test runner should spawn, requires a test runner
                            with parallel execution support (Detox CLI currently supports Jest)
```

So this is rather confusing. Do parallel tests work on Android?

**Comment by adamivancza** [comment]
Yeah I'm struggling with the same issue - any help is highly appreciated!

**Comment by d4vidi** [comment]
Parallel testing on Android has been operative for quite a while now. I've updated the messages provided by our CLI.
Thanks for noticing the discrepancy!

**Comment by owens-ben** [comment]
Any chance parallel executions for Android is on the roadmap?

**Comment by noomorph** [comment]
@owens-ben wdym precisely? we support parallel test suite execution for both iOS and Android. If you meant something else, I'll add: _There's ongoing work to enable freestyle device allocation including multiple devices in the same suite, but this will take more than a quarter until we complete it._

**Comment by owens-ben** [comment]
What other use cases are there for parallel execution outside of multiple (duplicate) devices in the same suite? Of course running a 2 separate devices in 2 separate processes works, but that's not parallel execution.

For example running 

`yarn detox test --configuration android.emu.Pixel4.android_12.qa.debug  --max-workers 2`

results in this error

```
ERROR   | Another emulator instance is running. Please close it or run all emulators with -read-only flag.
```

**Comment by noomorph** [comment]
@owens-ben looks weird, because we run emulators always with `-read-only` flag.

You're using Detox 20.x, and you don't override readonly: false in device config on purpose, right?

**Comment by owens-ben** [comment]
I think the issue was I already had one emulator booted and connected with adb reverse.

Terminated that emulator and tried again and it worked fine 👍
