### ISSUE TITLE
Cant perform a simple click, getting timeout eventually

### ISSUE THREAD

**Issue by mhyousefi** [wix/detox#273]
I'm trying to carry out a simple test, clicking on a button in the first page of my app. I've defined a testID in the button tag and have the following two lines in my test spec:

```
await expect(element(by.id(<testID>))).toBeVisible()
await element(by.id(<testID>)).tap()
```

Now, what happens is the test is stuck in the first line and waits the whole 120 seconds and then reports a timeout: 
```
Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

Another **really funny** thing that happens is if I write a non-existing testID, the same happens and I get no error indicating the element was not found.

It's really odd; I did not witness such behavior with my other app.

_I'm using:_
`react-native: 0.44.0`
`mocha: 3.5.3`
`detox: 5.6.2`

**Comment by rotemmiz** [comment]
There are a few good tip in the docs
https://github.com/wix/detox/blob/master/docs/Troubleshooting.Synchronization.md

**Comment by mhyousefi** [comment]
I'm not sure what the synchronization issue was; I woke up today and everything was ok...
@rotemmiz 
But good link though, thanks.

**Comment by mhyousefi** [comment]
I think I've found the reason behind my problem.
My tests are stalled and nothing happens (until I get a 120-sec timeout) after my app is launched **if my VPN connection is up**. Once, I disable my VPN connection, everything works just fine.

I'll try to check other VPN connections and report back...
