### ISSUE TITLE
React Native 0.64 (Android)

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#2732]
## Description

Add/verify support for the React Native 0.64 release:
- [x] Check (and migrate) Detox test app on developer env
- [x] Upgrade demo apps
- [ ] Upgrade associated CI job config to always use 0.64
- [ ] Update support table in main README.md

**Comment by Andarius** [comment]
Hi @d4vidi, there is an issue that some of us are encountering with RN 0.64 (https://github.com/wix/Detox/issues/2712).
I first closed it has the fix was related to another library but since others are having the same issue I reopened it.
Maybe you will have more insights on what's going on.

**Comment by d4vidi** [comment]
@Andarius thank you. I've already scanned through it, but I haven't been able to dive in. I'll try to take care of it this week (sorting out a common solution to all).
