### ISSUE TITLE
React Native 0.64 (iOS)

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#2733]
## Description

Add/verify support for the React Native 0.64 release:
- [x] Check (and migrate) DetoxSync's test app
- [x] Check (and migrate) Detox test app on developer env
- [x] Upgrade demo apps (`demo-react-native`, then check `demo-react-native-jest` and `detox-react-native-detox-instruments`)
- [x] Upgrade associated CI job config to always use 0.64
- [x] Update support table in main README.md

**Comment by chevonc** [comment]
Any chance this will be done soon? I'm hitting what might be some RN 0.64.0 related bugs, and would like to see if the sample app setup hits the same

**Comment by d4vidi** [comment]
@chevonc yes, we've prioritized this, and hope to sort it out soon. Would you mind sharing some of the problems/errors you've come across?

**Comment by danilobuerger** [comment]
@d4vidi I upgrade to rn 0.64.0 and detox 18.12.1. I have the following config:
```
  "detox": {
    "test-runner": "jest",
    "configurations": {
      "ios.sim.release": {
        "binaryPath": "ios/build/Build/Products/Release-iphonesimulator/test.app",
        "build": "xcodebuild DISABLE_ATS=YES ONLY_ACTIVE_ARCH=YES -workspace ios/test.xcworkspace -scheme test -configuration Release -destination 'generic/platform=iOS Simulator' -derivedDataPath ios/build | xcpretty",
        "type": "ios.simulator",
        "name": "iPhone 11 Pro Max, iOS 14.5"
      }
    }
  }
```
When I run the build command directly in my shell, everything works. When I run it with `yarn run detox build --configuration ios.sim.release`, it errors out with:
```
❯ yarn run detox build --configuration ios.sim.release
yarn run v1.22.10
$ node_modules/.bin/detox build --configuration ios.sim.release
detox[35410] INFO:  [build.js] xcodebuild DISABLE_ATS=YES ONLY_ACTIVE_ARCH=YES -workspace ios/test.xcworkspace -scheme test -configuration Release -destination 'generic/platform=iOS Simulator' -derivedDataPath ios/build | xcpretty
▸ Running script 'Bundle React Native code and images'
** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images ios/build/Build/Intermediates.noindex/test.build/Release-iphonesimulator/test.build/Script-9F508B2C21E64C6900DC075F.sh
(1 failure)
✨  Done in 6.83s.
```

**Comment by d4vidi** [comment]
What if you just run `detox build --configuration ios.sim.release`?
Also, is it possible that the `Running script 'Bundle React Native...` log is in fact a collapsed set of of many logs? If so, could you expand it?

**Comment by danilobuerger** [comment]
@d4vidi Running `./node_modules/.bin/detox build --configuration ios.sim.release` works.

Removing `xcpretty` and running with `yarn run` reveals:
``` 
nvm is not compatible with the "PREFIX" environment variable: currently set to "/opt/homebrew"
Run `unset PREFIX` to unset it.
Command PhaseScriptExecution failed with a nonzero exit code
```

**Comment by d4vidi** [comment]
@danilobuerger so there was a problem somewhere along the way yarn executes detox? Did you sort the problem, ultimately?

**Comment by danilobuerger** [comment]
@d4vidi No, not resolved yet. I have no idea why node / nvm fails in this scenario.

**Comment by isilher** [comment]
This seems to be a RN issue that might not be Detox specific. We faced it as well and (temporarily) resolved it by adding a patch for RN as suggested here: https://github.com/react-native-community/upgrade-support/issues/138#issuecomment-811780178

**Comment by danilobuerger** [comment]
I finally had a chance to track down the issue. It has nothing to do with detox or react-native. It just manifested recently because of how react-native changed the find node script. It turns out that when installing yarn via homebrew, homebrew adds the PREFIX env variable when executing yarn (see https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/yarn.rb#L24). Which in turn causes nvm to error out. Installing yarn via npm fixes the problem.

**Comment by d4vidi** [comment]
Yikes. Thanks @danilobuerger

**Comment by alon-ha** [comment]
RN 0.64 officially tested and upgraded with Detox and DetoxSync.
Only examples in DetoxSync were needed to change, all else worked flawlessly
