### ISSUE TITLE
Settings notifications permission to 'YES' not working with launchApp

### ISSUE THREAD

**Issue by alimtunc** [wix/Detox#2735]
### Description

I'm trying to set notification permissions to 'YES' with launchApp but it's not working. I have the system alert popup appear every time and blocking my tests.. But if I allow it manually during the test, my tests are working good.

- [X] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

1. Just trying to set permissions with launchApp methods.

I've used it on my init.js file on "beforeAll" steps :
`await device.launchApp({
      newInstance: false,
      permissions: {
        notifications: 'YES',
        camera: 'YES',
        medialibrary: 'YES',
        photos: 'YES',
        microphone: 'YES',
      },
    });`

#### Expected behavior
Having the permissions allowed automatically

#### Screenshots
<img width="344" alt="Capture d’écran 2021-04-13 à 19 09 38" src="https://user-images.githubusercontent.com/18298759/114592991-da318e00-9c8b-11eb-94e1-5128d7d6eb19.png">

#### Environment (please complete the following information):
 - Detox: 18.11.1
 - React Native: 0.62.0
 - Node: v14.16.0
 - Device: Iphone 12
 - Xcode: 12
 - iOS: 14.4
 - macOS: 11.2.3

#### If you are experiencing a timeout in your test

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://github.com/wix/Detox/blob/master/docs/Troubleshooting.Synchronization.md#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much), I have read [synchronization debug documentation](https://github.com/wix/DetoxSync/blob/master/IdleStatusDocumentation.md) and am providing the relevant synchronization debug output below:

#### If you are seeing a Detox build problem (e.g. during `npm install`, not `detox build`)

- [ ] I am providing the `npm install` log below:

#### Device and verbose Detox logs

- [x] I have run my tests using the `--loglevel trace` argument and am providing the verbose log below:

**Comment by noomorph** [comment]
![image](https://user-images.githubusercontent.com/1962469/114843147-327aa400-9de2-11eb-9b70-dcdb40eddbd1.png)

??

**Comment by alimtunc** [comment]
> ![image](https://user-images.githubusercontent.com/1962469/114843147-327aa400-9de2-11eb-9b70-dcdb40eddbd1.png)
> 
> ??

Sorry, didn't thinked it could help.  Here it is : 
https://gist.github.com/alimtunc/50328cbb013d0cdf6afa7d9ea161c27d

**Comment by noomorph** [comment]
@alon-ha, so far, I see this weird status:

```
detox[32966] DEBUG: [EXEC_CMD, #5] applesimutils --byId A3C1E918-EEA2-42E6-996A-27D23D24EACB --bundle com.zestmeup.zest --restartSB --setPermissions notifications=YES,camera=YES,medialibrary=YES,photos=YES,microphone=YES
detox[32966] DEBUG: [EXEC_TRY, #5] Trying to set permissions...
detox[32966] TRACE: [EXEC_SUCCESS, #5] An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=405):
Invalid device state
```

Do you see? AppleSimUtils prints something about Invalid device state. Any clues on what's going on?

@alimtunc, arm yourself with patience — it will take a while until we get to the root of the issue due to our team's limited capacity.
Try other simulators, runtimes, Xcode versions if you can. Maybe it will help... 🤔 This is the best I can come up with since I am not on the iOS side of the force. 🎃

**Comment by alimtunc** [comment]
@noomorph Thank you 🙏  
I'm already using the 0.9.2 version, I've already tried other simulators.. We'll see with different XCode version. Actually it's working good on Android, I can work on my test using Android simulator but it's annoying if it's not working on IOS.. 

Teşekkür ederim 😄

**Comment by d4vidi** [comment]
@alon-ha could you advise?

**Comment by aikewoody** [comment]
To let the maintainers know I am having the same problem as OP so maybe more people are impacted by this than previously thought.

**Comment by d4vidi** [comment]
@alimtunc this is a shot in the dark, but could you try to run `device.launchApp()` with `newInstance: true`? According to the [documentation[(https://github.com/wix/Detox/blob/master/docs/APIRef.DeviceObjectAPI.md#2-permissionsset-runtime-permissions-ios-only) this should work either way, but it's worth a try.

Also, could you run `applesimutils` and share your version of it?

@alon-ha Are there any flows in which permissions setting could be ignored?

**Comment by alon-ha** [comment]
As far as I know `permissions` should work with or without `newInstance: true`.
@alimtunc  @aikewoody Which version of `applesimutils` you guys are running?
Will try to check it soon

**Comment by aikewoody** [comment]
> As far as I know `permissions` should work with or without `newInstance: true`.
> @alimtunc @aikewoody Which version of `applesimutils` you guys are running?
> Will try to check it soon

Version `0.9.2`

**Comment by alon-ha** [comment]
@aikewoody happy to hear.
@alimtunc what about you?

**Comment by alimtunc** [comment]
Hi, sorry I'm not working at all on this project, we can close this issue because I can't test it anymore.
