### ISSUE TITLE
(WIP) Replace fbsimctl with AppleSimUtils' setLocation

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#2736]
## Description
Integrate new location API in AppleSimUtils, and with that - eliminate the last usage of `fbsimctl`, and thus remove it as a dependency.

- [x] In the process, need to clean location related e2e test from specific refs to `fbsimctl`, and thus make it always runnable.
- [ ] Warn about running in headless mode (where setLocation doesn't work)

Related to #1371

**Comment by KatieSnell-TomTom** [comment]
https://github.com/MobileNativeFoundation/set-simulator-location is a good option for setting location on iOS simulators (not sure if it works on real devices). Could use this instead of `fbsimctl`?

**Comment by asafkorem** [comment]
Once we'll upgrade the mac agents on our internal CI with Xcode 14, we should use simctl new `location` feature.
https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes

> simctl now supports controlling simulated location, including running scenarios and interpolating between a list of waypoints. See xcrun simctl location for more information. (59422559) (FB7577924)

**Comment by d4vidi** [comment]
@asafkorem since we're making changes to our mac agents regardles... do you think we could apply `simctl` soon?

**Comment by TheRealNate** [comment]
+1 on this, it seems that it is difficult to install fbsimctl so would be good to migrate

**Comment by felipejoribeiro** [comment]
i'm not able to install `fbsimctl`. How can i run the tests with "SetLocation" without it?

**Comment by noomorph** [comment]
I'll try to add this to the next team sprints.

**Comment by asafkorem** [comment]
Resolved with Detox [v20.16](https://github.com/wix/Detox/releases/tag/20.16.0). Migrated to Simctl.
