### ISSUE TITLE
Detox on Bitrise stuck animation pending

### ISSUE THREAD

**Issue by dbilgin** [wix/Detox#2744]
#### Reproduction

Started happening with `18.12.0`, the previous version we were using is `17.14.6`.
Initially we had react-native-splash-screen, I removed this dependency thinking this is causing the problem, but even after getting rid of this splash screen completely I kept having this problem.

The tests are spamming
```
Dispatch Queue
⏱ Queue: “Main Queue (<OS_dispatch_queue_main: com.apple.main-thread>)” with 1 work item
Run Loop
⏱ “Main Run Loop”
UI Elements
⏱ 1 CA animation pending
detox[14305] INFO:  [APP_STATUS] The system is busy with the following tasks:
Dispatch Queue
⏱ Queue: “Main Queue (<OS_dispatch_queue_main: com.apple.main-thread>)” with 1 work item
```
It works all fine when I run the tests locally even when I try it windowless, but when I run the tests on bitrise, it starts spamming these errors.

Should I be doing something extra to avoid this? Does any type of animation simply block the tests now?

#### Screenshots
![Screenshot 2021-04-14 at 20 53 59](https://user-images.githubusercontent.com/15243788/114763835-8d20eb00-9d63-11eb-9261-f652c84350af.png)

#### Environment (please complete the following information):
 - Detox: 18.12.0
 - React Native: 0.63.3
 - Node: 12.21.0
 - Device: iOS 14 simulator
 - Xcode: 12.4
 - macOS: Catalina

**Comment by noomorph** [comment]
What can you see on videos and screenshots from there?
