### ISSUE TITLE
Detox bugs reporting repro (skeletal/template) demo app

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#2746]
## Describe

Quite often, we find that it is hard for us to get to the bottom of reported issues, just by relying on logs and general info. When this happens, we usually resort to explicitly asking for a light demo app, where the issue is reproduced.

While legitimate, this request is not trivial to pursue, and hence is not always fulfilled (or is addressed after a long delay). In an attempt to take measures that would make it easier for reporters to follow our request through, we can work out a mini-repo containing a light RN app capable of running tests both on Android and iOS, and with that - replace our request for a full app setup, with a far more trivial request to simply fork that mini-repo and have bug-related things bundled in.

**Comment by d4vidi** [comment]
As per implementation, I think we could reuse previously submitted demo apps: Take the original code, have it strip down to the bare minimum (1 landing screen + 1 test running on both platforms) and submit. We could definitely throw in prebaked `npm scripts`, etc.

**Comment by alon-ha** [comment]
I'm happy to sat that a repo for [DetoxTemplate](https://github.com/wix-incubator/DetoxTemplate) was created. We still need to add it to the doc in Detox, but everyone can fork it and add an example for his/her problem to speed the debug process
