### ISSUE TITLE
export globals

### ISSUE THREAD

**Issue by trofima** [wix/detox#275]
#### Description

Please export detox objects for to be able to import them (i.e. element, by etc.). 
This is needed to properly use detox in test flow libraries based on it.

**Comment by LeoNatan** [comment]
PRs are welcome.

**Comment by coderjonny** [comment]
@trofima great job with exposing the globals!

I've created a flowTyped library definition for them. 
https://github.com/flowtype/flow-typed/pull/1824

Cheers

**Comment by coderjonny** [comment]
Should we close this issue btw?

**Comment by rotemmiz** [comment]
Indeed
Closed by #374
