### ISSUE TITLE
Custom keyboard elements are never visible

### ISSUE THREAD

**Issue by tyronet-sportsbet** [wix/Detox#2754]
### Description
First of all thank you all for your hard work on Detox, it absolutely rules. As for the issue... on iOS you can supply completely custom `inputView`s on any responder, essentially allowing you to create custom keyboards. Problem is any elements that are subviews of this `inputView` are erroneously considered "not visible" by Detox.

I'm not familiar with the internals of Detox, but I think this stems from the fact that iOS renders them in a completely separate window, so however Detox is attempting to determine visibility is confused by the fact that elements in the custom keyboard share no ancestry with any other components.

- [x] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction

I have created a minimum reproduction repository here: https://github.com/tyronet-sportsbet/DetoxKeyboards

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

1. Clone my repo
2. `yarn install`
3. `yarn detox build --configuration ios.pre.sim`
4. `yarn detox test --configuration ios.pre.sim e2e/firstTest.e2e.js`

#### Expected behavior
Elements in `inputView` windows should be visible to Detox when the custom keyboard is visible.

#### Screenshots
This is the view hierarchy, notice the keyboard and the app don't share a common ancestor:
<img width="854" alt="Screen Shot 2021-04-22 at 6 28 01 pm" src="https://user-images.githubusercontent.com/14101879/115682411-c88d6c00-a398-11eb-9d65-d28becdc2d17.png">

The test app and the simulator
<img width="1097" alt="Screen Shot 2021-04-22 at 6 31 09 pm" src="https://user-images.githubusercontent.com/14101879/115682552-eb1f8500-a398-11eb-86cb-f76620d7e962.png">

#### Environment (please complete the following information):
 - Detox: 18.12.0
 - React Native: N/A (though I've tested this also happens in a React Native project)
 - Node: 14.5.0
 - Device: iOS Simulator (iPhone 8)
 - Xcode: 12.4
 - iOS: 14.4
 - macOS: 10.15.7

#### If you are experiencing a timeout in your test

- [x] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://github.com/wix/Detox/blob/master/docs/Troubleshooting.Synchronization.md#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much), I have read [synchronization debug documentation](https://github.com/wix/DetoxSync/blob/master/IdleStatusDocumentation.md) and am providing the relevant synchronization debug output below:

(This is not a synchronization issue)

#### If you are seeing a Detox build problem (e.g. during `npm install`, not `detox build`)

- This is not a detox build problem

#### Device and verbose Detox logs

- [x] I have run my tests using the `--loglevel trace` argument and am providing the verbose log below:
[detox_pid_24514.log.zip](https://github.com/wix/Detox/files/6356787/detox_pid_24514.log.zip)

**Comment by d4vidi** [comment]
@tyronet-sportsbet thanks for this well-articulated submission! I'm backlogging this, hopefully we'll get to it soon enough!
