### ISSUE TITLE
onPress button function didn't get triggered with tap() function

### ISSUE THREAD

**Issue by TiavinaRakotobe** [wix/Detox#2756]
![Screenshot from 2021-04-22 17-59-27](https://user-images.githubusercontent.com/58861550/115737540-e789ff00-a394-11eb-8c96-83c905c51ff0.png)
![Screenshot from 2021-04-22 18-00-01](https://user-images.githubusercontent.com/58861550/115737567-ed7fe000-a394-11eb-88a9-9934845ddcfe.png)

<RButton /> component is an alias for react-native Button (import {Button as RButton} from 'react-native')
react-native : 0.62.2
detox :18.12.0
react": 16.11.0,

**Comment by wabicai** [comment]
How did u deal with it? I have the same problem with it
