### ISSUE TITLE
Lack of the deterministic way to get a UINavigationButton

### ISSUE THREAD

**Issue by trofima** [wix/detox#276]
#### Description
There is no good way to get UINavigationButton which has no any label, but using index. But this way is dangerous because an order of the elements isn't guarantied.

**Comment by LeoNatan** [comment]
This is a known limitation in iOS, and there really isn't a very good way to do it there either.

See, for instance:
https://stackoverflow.com/questions/24318660/ios-get-uinavigationbars-back-button-in-order-to-set-accessibility-properties
