### ISSUE TITLE
Ability to run detox tests with just Android APKs (app & test apk)

### ISSUE THREAD

**Issue by jayshah123** [wix/Detox#2764]
There are third party tools e.g. https://www.browserstack.com/docs/app-automate/espresso/getting-started
which are based on espresso and allow the same with just uploading the actual apk and test apk.

Since Detox itself is based on espresso, is there any chance to be able to run detox tests, without the need of spinning up anything else (like node server etc)?

This is similar to running android tests equivalent to `adb shell am instrument -w com.android.demo.app.tests/android.support.test.runner.AndroidJUnitRunner
 `.

If there is no other option, will try appium as per their recommendation at https://www.browserstack.com/guide/appium-react-native-for-automation

**Comment by jayshah123** [comment]
I think the same question goes for other cloud based automation test providers like firebase test lab: https://firebase.google.com/docs/test-lab/android/get-started

**Comment by d4vidi** [comment]
Hey @jayshah123, I'm not sure I understand what you mean.
Even with `gradle connectAndroidTest`, you spin up gradle. Simlarly, for Detox to work, the node server must be started. However, Detox can work on preexisting emulators that you've started in advance. Detox looks for running instance and can connect to them (that includes installed the various APK's).

**Comment by jayshah123** [comment]
Sorry my bad in explaining the question. 
I think the tests supported by firebase test lab seems to be instrumented tests (tests as a part of test apk I think?): https://developer.android.com/training/testing/unit-testing/instrumented-unit-tests.html
I am wondering how much is possible to be done for app that uses detox to be possible on device farms like Firebase test lab where I have no control over starting a detox server.

**Comment by jayshah123** [comment]
From what I have understood, one needs control of the host machine to run the detox/js scripts that execute tests.
Closing this issue.
Would be nice if the test running process was well documented: something like:
There would be three explicit entities: host running node/detox process, app under test apk, and the test apk that communicates with detox runner.

**Comment by d4vidi** [comment]
@jayshah123 while it may not be well approachable, our document regarding [how detox works](https://github.com/wix/Detox/blob/master/docs/Introduction.HowDetoxWorks.md) could help you out. Could you please try to visit it?
