### ISSUE TITLE
detox test hangs when starting the Android emulator (Apple Silicon)

### ISSUE THREAD

**Issue by drash-course** [wix/Detox#2772]
### Describe the bug

We upgraded our Detox machine to the new M1 Mac mini and ran into this issue. `detox build -c android.emu.debug` succeeds without problems. `detox test -c android.emu.debug` starts but then hangs when the emulator window opens. The app does not launch. Here is the printout.

```
detox test -c android.emu.debug --loglevel trace --record-logs all

detox[21491] INFO:  [test.js] DETOX_CONFIGURATION="android.emu.debug" DETOX_FORCE_ADB_INSTALL=false DETOX_LOGLEVEL="trace" DETOX_READ_ONLY_EMU=false DETOX_RECORD_LOGS="all" DETOX_REPORT_SPECS=true DETOX_START_TIMESTAMP=1620319503548 DETOX_USE_CUSTOM_LOGGER=true jest --config e2e/config.json --testNamePattern '^((?!:ios:).)*$' --maxWorkers 1 e2e
detox[21492] TRACE: [DETOX_CREATE] created a Detox instance with config:
{"artifactsConfig":{"rootDir":"artifacts/android.emu.debug.2021-05-06 16-45-03Z","plugins":{"log":{"enabled":true,"keepOnlyFailedTestsArtifacts":false},"screenshot":{"enabled":true,"shouldTakeAutomaticSnapshots":false,"keepOnlyFailedTestsArtifacts":false},"video":{"enabled":false,"keepOnlyFailedTestsArtifacts":false},"instruments":{"enabled":false,"keepOnlyFailedTestsArtifacts":false},"timeline":{"enabled":false},"uiHierarchy":{"enabled":false,"keepOnlyFailedTestsArtifacts":false}},"pathBuilder":{"_rootDir":"artifacts/android.emu.debug.2021-05-06 16-45-03Z"}},"appsConfig":{"default":{"type":"android.apk","binaryPath":"android/app/build/outputs/apk/dev/debug/app-dev-debug.apk","build":"cd android && ./gradlew assembleDevDebug assembleDevDebugAndroidTest -DtestBuildType=debug && cd .."}},"behaviorConfig":{"init":{"reinstallApp":true,"exposeGlobals":true},"cleanup":{"shutdownDevice":false},"launchApp":"auto"},"cliConfig":{"recordLogs":"all","configuration":"android.emu.debug","forceAdbInstall":"false","loglevel":"trace","useCustomLogger":"true"},"deviceConfig":{"type":"android.emulator","device":{"avdName":"Pixel_4_API_S"}},"runnerConfig":{"testRunner":"jest","runnerConfig":"e2e/config.json","specs":"e2e"},"sessionConfig":{"autoStart":true,"server":"ws://localhost:53897","sessionId":"739c184a-52ba-ed62-53c8-459377c997f9","debugSynchronization":10000},"errorComposer":{"configurationName":"android.emu.debug","filepath":"/Users/fleetback-ci/builds/9J-UT-y5/0/arhs-fleetback/fleetback-app-react/.detoxrc.json","contents":{"testRunner":"jest","runnerConfig":"e2e/config.json","configurations":{"ios.sim.debug":{"binaryPath":"ios/build/Build/Products/Debug-iphonesimulator/Fleetback DEV.app","build":"xcodebuild -workspace ios/FleetbackApp.xcworkspace -scheme FleetbackApp-DEV -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build","type":"ios.simulator","device":{"type":"iPhone 11"}},"ios.sim.release":{"binaryPath":"ios/build/Build/Products/Release-iphonesimulator/Fleetback DEV.app","build":"xcodebuild -workspace ios/FleetbackApp.xcworkspace -scheme FleetbackApp-DEV-release -configuration Release -sdk iphonesimulator -derivedDataPath ios/build","type":"ios.simulator","device":{"type":"iPhone 11"}},"android.emu.debug":{"binaryPath":"android/app/build/outputs/apk/dev/debug/app-dev-debug.apk","build":"cd android && ./gradlew assembleDevDebug assembleDevDebugAndroidTest -DtestBuildType=debug && cd ..","type":"android.emulator","device":{"avdName":"Pixel_4_API_S"}},"android.emu.release":{"binaryPath":"android/app/build/outputs/apk/dev/release/app-dev-release.apk","build":"cd android && ./gradlew assembleDevRelease assembleDevReleaseAndroidTest -DtestBuildType=release && cd ..","type":"android.emulator","device":{"avdName":"Pixel_4_API_S"}}}},"_extends":false}}
detox[21492] DEBUG: [WSS_CREATE] Detox server listening on localhost:53897...
detox[21492] DEBUG: [WSS_CONNECTION, #53898] registered a new connection.
detox[21492] TRACE: [WS_OPEN] opened web socket to: ws://localhost:53897
detox[21492] TRACE: [WS_SEND] {"type":"login","params":{"sessionId":"739c184a-52ba-ed62-53c8-459377c997f9","role":"tester"},"messageId":0}
detox[21492] TRACE: [WSS_GET_FROM, #53898] {"type":"login","params":{"sessionId":"739c184a-52ba-ed62-53c8-459377c997f9","role":"tester"},"messageId":0}
detox[21492] TRACE: [SESSION_CREATED] created session 739c184a-52ba-ed62-53c8-459377c997f9
detox[21492] TRACE: [WSS_SEND_TO, #tester] {"type":"loginSuccess","params":{"testerConnected":true,"appConnected":false},"messageId":0}
detox[21492] TRACE: [SESSION_JOINED] tester joined session 739c184a-52ba-ed62-53c8-459377c997f9
detox[21492] TRACE: [WS_MESSAGE] {"type":"loginSuccess","params":{"testerConnected":true,"appConnected":false},"messageId":0}
 
detox[21492] DEBUG: [EXEC_CMD, #0] "/Users/fleetback-ci/Library/Android/sdk/emulator/emulator" -list-avds --verbose
detox[21492] TRACE: [EXEC_SUCCESS, #0] Pixel_4_API_25
Pixel_4_API_S

detox[21492] DEBUG: [EXEC_CMD, #1] "/Users/fleetback-ci/Library/Android/sdk/emulator/emulator" -version 
detox[21492] ERROR: [EXEC_FAIL, #1] ""/Users/fleetback-ci/Library/Android/sdk/emulator/emulator" -version " failed with error = ChildProcessError: Command failed: "/Users/fleetback-ci/Library/Android/sdk/emulator/emulator" -version 
 `"/Users/fleetback-ci/Library/Android/sdk/emulator/emulator" -version ` (exited with error code 255) (code=255), stdout and stderr:

detox[21492] ERROR: [EXEC_FAIL, #1] emulator: Android emulator version 30.3.5.0 (build_id 7036990) (CL:N/A)
emulator: ERROR: can't find the emulator executable.


detox[21492] ERROR: [EXEC_FAIL, #1] 
detox[21492] DEBUG: [EMU_BIN_VERSION_DETECT] Detected emulator binary version { major: 30, minor: 3, patch: 5, toString: [Function: toString] }
detox[21492] DEBUG: [ALLOCATE_DEVICE] Trying to allocate a device based on "Pixel_4_API_S"
detox[21492] DEBUG: [EXEC_CMD, #2] "/Users/fleetback-ci/Library/Android/sdk/platform-tools/adb"  devices
detox[21492] DEBUG: [EXEC_SUCCESS, #2] List of devices attached


detox[21492] DEBUG: [ALLOCATE_DEVICE] Settled on emulator-17342
detox[21492] DEBUG: [SPAWN_CMD] /Users/fleetback-ci/Library/Android/sdk/emulator/emulator -verbose -no-audio -no-boot-anim -port 17342 @Pixel_4_API_S

 RUNS  e2e/firstTest.e2e.js

```

Building and running the iOS tests works. Both iOS and Android tests build, run and pass on our Intel MacBooks. I had to patch line 22 of EmulatorVersionResolver.js because the command seems broken but still prints the version so it's easy to workaround.

If you Cmd+Q the emulator, more logs appear. The whole logs are attached to the post.

If you don't have a M1 Mac to reproduce the problem, can you give us some pointers as to why the process can get stuck on the adb command? We can help debug and fix the problem.

### Steps To Reproduce

- [x] I have tested this issue on the latest Detox release and it still reproduces

1. create a basic react native project
2. setup detox
3. patch EmulatorVersionResolver.js with `rawOutput = await (this._emulatorExec.exec(new QueryVersionCommand()).catch(e => e.stdout || e.stderr)) || '';`
4. run `detox build -c android.emu.debug && detox test -c android.emu.debug`
5. it hangs

### Expected behavior

It should launch the app and run the tests.

### Detox Trace-Logs

See attached file [detox_bug.txt](https://github.com/wix/Detox/files/6436273/detox_bug.txt)

### Device logs (adb logcat)

It says `- waiting for device -` and nothing happens. If you need them I can try with Android Studio.

### Environment (please complete the following information):
 - Detox: 18.12.2
 - React Native: 0.64.1
 - Node: v14.16.1
 - Device: Emulated Pixel 4 API 31 arm64
 - OS: macOS 11.3 on the M1 Mac mini
 - Test-runner jest-circus

**Comment by d4vidi** [comment]
Hey @drash-course,
I'm suspecting some environment setup issues, so here are some (related) follow-up questions:

1. What happens if you run `"/Users/fleetback-ci/Library/Android/sdk/emulator/emulator" -version` in a shell, regardless of Detox?

2. It seems as though your emulator is launched, but something is slightly broken - because the `adb` server cannot find it. Can you try to launch an emulator in a shell? -
a. over a specific port: `/Users/fleetback-ci/Library/Android/sdk/emulator/emulator -verbose -no-audio -no-boot-anim -port 15776 @Pixel_4_API_S`
b. using an implicit port: `/Users/fleetback-ci/Library/Android/sdk/emulator/emulator -verbose -no-audio -no-boot-anim  @Pixel_4_API_S`

in both cases, try to run `adb devices` and see whether the emulator's name shows up in the output (e.g. `emulator-15776`).

**Comment by drash-course** [comment]
`"/Users/fleetback-ci/Library/Android/sdk/emulator/emulator" -version` still prints `emulator: Android emulator version 30.3.5.0 (build_id 7036990) (CL:N/A)` after the update to 30.6.5 with the SDK manager. I'll try with a clean install of Android.

**Comment by drash-course** [comment]
Found a solution here: https://stackoverflow.com/questions/67230200/emulator-appearing-offline-on-m1-mac-after-the-last-update-of-arm64-v8a

**Comment by d4vidi** [comment]
Kudos!!! Does this work with Detox, then?

**Comment by drash-course** [comment]
Yes it works! Here are my steps if someone gets the same problem:

- Uninstall the Android SDK
- Downgrade to Android Studio 4.1.2 or 4.1.3
- Install the ARM64 images from API 30 (R)
- download the API 31 (S) from here https://dl.google.com/android/repository/sys-img/google_apis_playstore/arm64-v8a-S_r02-darwin.zip

The google_api image was not working for me, from the `idea.logs` it complained about a missing user.img file when creating the virtual device

- Unzip and place the folder `arm64-v8a` in `~/Library/Android/sdk/system-images/android-S/google_apis_playstore/`
- You can create a API 30 or API 31 AVD

On the detox side, maybe it's a regression but I had to run `adb reverse tcp:9090 tcp:9090`. I'll make another ticket if I can reproduce.

**Comment by drash-course** [comment]
I found this to download Android Studio 4.1.2.
https://www.techspot.com/downloads/downloadnow/6831/?evp=af65680fbea01bb42441cce8f4af7424&file=2

The page title is wrong though, it does download 4.1.2 and not 4.1.3.

**Comment by d4vidi** [comment]
You can invoke port reversing [through Detox](https://github.com/wix/Detox/blob/master/docs/APIRef.DeviceObjectAPI.md#devicereversetcpport-android-only) as well.

As for Android Studio versions, I'd recommend to try to look up a Google archive.

**Comment by drash-course** [comment]
Indeed, here is my `environment.js` for reference.

```js
const {
    DetoxCircusEnvironment,
    SpecReporter,
    WorkerAssignReporter,
} = require('detox/runners/jest-circus');

const TWENTY_MINUTES = 20 * 60 * 1000;

class CustomDetoxEnvironment extends DetoxCircusEnvironment {
    constructor(config, context) {
        super(config, context);
        this.initTimeout = TWENTY_MINUTES;
        this.registerListeners({ SpecReporter, WorkerAssignReporter });
    }

    async initDetox() {
        const instance = await this.detox.init(undefined, { launchApp: false });
        await instance.device.reversePort(8081); // added this line
        await instance.device.launchApp({ permissions: { notifications: 'YES', camera: 'YES', microphone: 'YES', photos: 'YES' } });
        return instance;
    }
}
```

**Comment by drash-course** [comment]
This may be off-topic. If you use `gitlab-runner` you may get this error when running your tests.

```
detox[77919] ERROR: [exec.js/EXEC_FAIL, #0] "applesimutils --list --byType "iPhone 11"" failed with code = 127, stdout and stderr:
152detox[77919] ERROR: [exec.js/EXEC_FAIL, #0] 
153detox[77919] ERROR: [exec.js/EXEC_FAIL, #0] /bin/sh: applesimutils: command not found
154detox[77919] ERROR: ChildProcessError: Command failed: applesimutils --list --byType "iPhone 11"
155/bin/sh: applesimutils: command not found
156 `applesimutils --list --byType "iPhone 11"` (exited with error code 127)
```

Note that `applesimutils` is properly installed with brew. It seems sh cannot follow the simlink. My simple fix is to copy the executable to /usr/local/bin/ like this.

`sudo cp /opt/homebrew/Cellar/applesimutils/0.9.2/bin/applesimutils /usr/local/bin/ `

You should now uninstall it from brew to avoid having multiple `applesimutils` in your path.

`brew uninstall applesimutils`

**Comment by d4vidi** [comment]
@drash-course I would advise against that. `brew` should set a symlink in `/usr/local/bin` for you. Perhaps trying to reinstall would work.

**Comment by mikehardy** [comment]
Not sure if this will be useful for others or not, but as of today (July 15, 2021) a procedure that worked for me to get Detox tests working for react-native on an Apple M1 device were:

- Get the current Arctic Fox Preview Apple Silicon build (https://developer.android.com/studio/archive - it is 2020.1.3 beta5 for me right now  / https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2020.3.1.20/android-studio-2020.3.1.20-mac_arm.zip) - you can now run it as 'Android Studio Preview'
- Use SDK Manager to install the emulator package
- From Terminal go to `$ANDROID_SDK_ROOT/emulator` and run `./emulator` make sure it updates itself with the emulator preview release etc (https://github.com/google/android-emulator-m1-preview/releases - 0.2 engine-only is what will be downloaded and unpacked). If you run `./emulator -version` you should see `30.3.5.0` because the arm64 emulator is a custom build and overwrites the SDK Manager package. It will also show the exit code 255 could not find emulator binary executable error as well, which looks dire but may be ignored
- Use AVD Manager to make a new AVD - I found if I used Android S / API31 preview networking was broken. API30 works though, both Play and Google APIs flavors. Boot it and test it, you should have a working emulator now
- When you run Detox, it will give you a dire message about the exit code 255 mentioned above, but it will carry on :-). Then it hangs and times out because the adb reverse does need to be done manually for some reason. Either as above using Detox config or in Terminal with `adb reverse tcp:8081 tcp:8081`

I believe most of this is simply confirming the above info, but an important point for me was total emulator network failure on API31 while API30 worked in general but did need the manual reverse port mapping.

Cheers

**Comment by d4vidi** [comment]
@mikehardy Thanks!!!
Worth mentioning: `adb reverse` is only needed when running in debug (dynamic bundle loading) mode.

**Comment by mikehardy** [comment]
Oh yes! If you have the bundle packed up in the app (release mode) of course, it doesn't have to go over the port to fetch - good extra detail. This arm64 stuff is still pretty fiddly but at least most things are possible now. Side note: just *last week* google finally published a .xcframework with arm64 emulator slice for google sign in. Maps still doesn't work AFAIK. So, the whole ecosystem is still fractured after this architecture earthquake. But my detox tests ran! :-). Cheers

**Comment by d4vidi** [comment]
>whole ecosystem is still fractured after this architecture earthquake. But my detox tests ran! :-)

... which makes it all the more astounding. Kudos!

**Comment by sorodrigo** [comment]
Hey I'm struggling with this issue myself we get the following message:
```
detox[85761] INFO:  [test.js] deviceLaunchArgs="-partition-size 8000 -memory 6144 -no-snapshot -wipe-data -skin 800x1280" mocha --opts ./e2e/mocha.opts --configuration android.emu.debug --grep :ios: --invert --take-screenshots failing --use-custom-logger true ./e2e/specs/01_DE/03_DE_account_spec.js
detox[85763] INFO:  [DetoxServer.js] server listening on localhost:54419...
detox[85763] ERROR: [exec.js/EXEC_FAIL, #1] ""/Users/administrator/android-sdk/emulator/emulator" -version " failed with code = 255, stdout and stderr:
detox[85763] ERROR: [exec.js/EXEC_FAIL, #1] emulator: Android emulator version 30.3.5.0 (build_id 7036990) (CL:N/A)
emulator: ERROR: can't find the emulator executable.
detox[85763] ERROR: [exec.js/EXEC_FAIL, #1] 
detox[85763] ERROR: [EmulatorVersionResolver.js/EMU_BIN_VERSION_DETECT] Could not detect emulator binary version ChildProcessError: Command failed: "/Users/administrator/android-sdk/emulator/emulator" -version 
 `"/Users/administrator/android-sdk/emulator/emulator" -version ` (exited with error code 255)
    at callback (/Users/administrator/builds/K9TR58dn/0/developers/mobile-app/node_modules/child-process-promise/lib/index.js:33:27)
    at ChildProcess.exithandler (child_process.js:397:5)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Socket.<anonymous> (internal/child_process.js:441:11)
    at Socket.emit (events.js:400:28)
    at Pipe.<anonymous> (net.js:675:12) {
  code: 255,
  childProcess: {
    _forkChild: [Function: _forkChild],
    ChildProcess: [Function: ChildProcess],
    exec: [Function: exec],
    execFile: [Function: execFile],
    execFileSync: [Function: execFileSync],
    execSync: [Function: execSync],
    fork: [Function: fork],
    spawn: [Function: spawnWithSignal],
    spawnSync: [Function: spawnSync]
  },
  stdout: 'emulator: Android emulator version 30.3.5.0 (build_id 7036990) (CL:N/A)\n' +
    "emulator: ERROR: can't find the emulator executable.\n" +
    '\n',
  stderr: ''
}
detox[85763] WARN:  [AVDValidator.js/AVD_VALIDATION] Emulator version detection failed (See previous logs)
detox[85763] ERROR: [exec.js/EXEC_FAIL, #2] ""/Users/administrator/android-sdk/emulator/emulator" -version " failed with code = 255, stdout and stderr:
detox[85763] ERROR: [exec.js/EXEC_FAIL, #2] emulator: Android emulator version 30.3.5.0 (build_id 7036990) (CL:N/A)
emulator: ERROR: can't find the emulator executable.
detox[85763] ERROR: [exec.js/EXEC_FAIL, #2] 
detox[85763] ERROR: [EmulatorVersionResolver.js/EMU_BIN_VERSION_DETECT] Could not detect emulator binary version ChildProcessError: Command failed: "/Users/administrator/android-sdk/emulator/emulator" -version 
 `"/Users/administrator/android-sdk/emulator/emulator" -version ` (exited with error code 255)
    at callback (/Users/administrator/builds/K9TR58dn/0/developers/mobile-app/node_modules/child-process-promise/lib/index.js:33:27)
    at ChildProcess.exithandler (child_process.js:397:5)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Socket.<anonymous> (internal/child_process.js:441:11)
    at Socket.emit (events.js:400:28)
    at Pipe.<anonymous> (net.js:675:12) {
  code: 255,
  childProcess: {
    _forkChild: [Function: _forkChild],
    ChildProcess: [Function: ChildProcess],
    exec: [Function: exec],
    execFile: [Function: execFile],
    execFileSync: [Function: execFileSync],
    execSync: [Function: execSync],
    fork: [Function: fork],
    spawn: [Function: spawnWithSignal],
    spawnSync: [Function: spawnSync]
  },
  stdout: 'emulator: Android emulator version 30.3.5.0 (build_id 7036990) (CL:N/A)\n' +
    "emulator: ERROR: can't find the emulator executable.\n" +
    '\n',
  stderr: ''
}
detox[85763] WARN:  [EmulatorDriver.js/EMU_SKIN_CFG_PATCH] Failed to detect emulator version! (see previous logs)
This leaves Detox unable to tell if it should automatically apply this patch-fix: https://stackoverflow.com/a/47265664/453052, which seems to be needed in emulator versions < 28.
If you feel this is not needed, you can either ignore this message, or otherwise apply the patch manually.
waitForOnboarding button
```

but then most of the times it actually continues with the tests. The main issue I have is that it's a bit unreliable and also hangs for 2 minutes before continuing (I think it keeps retrying or something).

I think it would be good to reopen this issue until a stable solution is out there, that would make it easier for folks like me to find a place they can wait for better news.

**Comment by mikehardy** [comment]
I have emulator startup to unreliable for android emulators forever, intel macs as well. I use a kill / retry loop for my CI for this reason.

Once booted, this failure to detect emulator problem should only be warning + delay though, I had 100% reliable test execution even with that warning **given** I already had an emulator successfully booted.

**Comment by sorodrigo** [comment]
@mikehardy could you share with me your `kill/retry loop` code?

**Comment by mikehardy** [comment]
Check react-native-firebase e2e workflow for android

**Comment by mikehardy** [comment]
https://github.com/invertase/react-native-firebase/blob/90b4d7021aff7d5d28140b57eb69283b04712257/.github/workflows/tests_e2e_android.yml#L132-L175

**Comment by d4vidi** [comment]
@mikehardy would you not rather let Detox spin up the emulators for ya?

**Comment by mikehardy** [comment]
Too flaky in practice. The first restart hits maybe 10% of the time in github actions, second maybe 1% and so on. That's intolerable and I don't think detox has emu restart logic? If it does and I missed it though then sure

**Comment by sorodrigo** [comment]
I finally cracked it. I was starting the emulator but then detox was also trying to start it and sometimes this caused errors in connection to it. As a solution, I made sure the launch args are identical in both cases (detox and my own launch). The most important one was to add the port option so I ensure that both will try to create it in the same port, otherwise, I could end up with 2 instances (not very often).

@d4vidi I wonder if there's a way to skip the device launch altogether and just skip straight to the install? When trying to connect and failing it will spend 2 mins. If I could skip this step this would improve my tests considerably.

**Comment by mikehardy** [comment]
In my experience if Detox detects the emulator/simulator is already up, it will not attempt to boot it, it just installs. So we boot separately (with flaky-restart-logic as above) and detox handles it. But locally (dev machines, where it's faster etc) detox boots things for me the first time in the morning according to the AVD name (android) or simulator profile (iOS) specified in detox config.

**Comment by d4vidi** [comment]
@sorodrigo, @mikehardy is right. I don't understand where this emulator boot-up race comes from but it sounds unhealthy. Technically, Detox enables you to preboot the emulator yourself. If it's an instance of the AVD specified in Detox's config of choice, then Detox should choose it for test execution.

**Comment by sorodrigo** [comment]
@d4vidi maybe then we just need to opt out of patching the emulator? Detox tries to patch it and it takes 2 min to fail and continue with the tests

**Comment by d4vidi** [comment]
@sorodrigo what's you execution environment? Strikes me odd that the emulator binary is not found.

**Comment by sorodrigo** [comment]
We're running the e2e in mac **M1** machines using **macOS Catalina**. Detox version 17, because the latest version fails in M1 and also our testing code does not work well with the new version in other machines.

**Comment by mikehardy** [comment]
I am only chiming in quickly to say this is an interesting coincidence! react-native-firebase, which is my M1 detox experience at the moment, is also stuck on Detox 17. I didn't think to mention it before, but anything I mentioned up above about it working on M1 was validated on Detox 17 and if 18 is broken I'm unaware of it and haven't tried yet

**Comment by d4vidi** [comment]
@mikehardy that's actually very important input. Obviously, we urge you'd at all times use the latest (and greatest) of Detox (i.e. version 18+).

**Comment by mikehardy** [comment]
Indeed - recognizing this is now veering off topic, our being on v17 vs v18 is totally on me/us over at RNFB (though I do have great success on M1 with detox v17). I have moving to current stable as a todo for me and for whatever it's worth we just did a competitive analysis of the various test platforms for our next generation e2e harnesses and we're re-committing to Detox after a brief Cavy dalliance, so rest assured if v18 of Detox has an M1 problem I'll be back here, but hopefully with a PR :-). Cheers

**Comment by mikehardy** [comment]
@sorodrigo not sure what parts of Detox you're using but I've updated to Detox v18 now and it works fine on M1, just not on iOS15 (a known issue #2895). I also tested Detox v18 with Android 12 and it appears fine (#2899). As far as I can tell, the only thing not working at the moment is ios15 (noted) and maybe a need for a manual adb reverse for bundler port 8081 - cheers

**Comment by d4vidi** [comment]
> Indeed - recognizing this is now veering off topic, our being on v17 vs v18 is totally on me/us over at react-native-firebase (though I do have great success on M1 with detox v17). I have moving to current stable as a todo for me and for whatever it's worth we just did a competitive analysis of the various test platforms for [our next generation e2e harnesses](https://github.com/invertase/react-native-google-ads/tree/main/example) (to be used in react-native-firebase, react-native-google-ads, notifee, react-native-mlkit, etc) and we're re-committing to Detox after a brief Cavy dalliance, so rest assured if v18 of Detox has an M1 problem I'll be back here, but hopefully with a PR :-). Cheers

Thrilled to know! Looking forward to getting feedback on v18.

**Comment by natalytolstikova** [comment]
why I cant use detox with last version of android studio?

**Comment by musikobios** [comment]
For me as @mikehardy mentioned above, a `adb reverse tcp:8081 tcp:8081` made the detox detect the react-native packager & run the tests. So the process is:

- Run detox build command
- Run react-native packager (`npx react-native start`)
- Open the emulator & run `adb reverse tcp:8081 tcp:8081`
- Run detox test command

**Comment by SkPratihar1** [comment]
""/Users/it062305/Library/Android/sdk/platform-tools/adb" -s emulator-11374 shell "ps | grep \"com\.eroev\.app$\""" failed with error = ChildProcessError: Command failed: "/Users/it062305/Library/Android/sdk/platform-tools/adb" -s emulator-11374 shell "ps | grep \"com\.eroev\.app$\""
 `"/Users/it062305/Library/Android/sdk/platform-tools/adb" -s emulator-11374 shell "ps | grep \"com\.eroev\.app$\""` (exited with error code 1) (code=1), stdout and stderr:
