### ISSUE TITLE
Detox times out on device.launchApp

### ISSUE THREAD

**Issue by jhd-lego** [wix/Detox#2773]
I have just set up detox for our project, and it seems to time out before it even hits the test cases.
We have an iOS react-native 0.64 app.
```
    thrown: "Exceeded timeout of 120000 ms for a hook.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      1 | describe('Example', () => {
    > 2 |   beforeAll(async () => {
        |   ^
      3 |     await device.launchApp();
      4 |   });
      5 |

      at first.e2e.js:2:3
      at Object.<anonymous> (first.e2e.js:1:1)
```

The app _has_ launched and the packager _is_ running. The app also works fine. I do get some output mentioning Dispatch Queue, Run Loop and One-time events, that look fine.
But unable to figure out what is wrong and why it will not continue past this.

<details>
<summary>Log output</summary>
detox[81531] INFO:  [APP_STATUS] The system is busy with the following tasks:

Dispatch Queue
⏱ Queue: “Main Queue (<OS_dispatch_queue_main: com.apple.main-thread>)” with 1 work item

Run Loop
⏱ “Main Run Loop”

One-time Events
⏱ “Network Request” with object: “URL: “https://...””
⏱ “Network Request” with object: “URL: “https://...l””
⏱ “Network Request” with object: “URL: “https://....””
detox[81531] INFO:  [APP_STATUS] The system is busy with the following tasks:

Dispatch Queue
⏱ Queue: “Main Queue (<OS_dispatch_queue_main: com.apple.main-thread>)” with 1 work item

Run Loop
⏱ “Main Run Loop”

One-time Events
⏱ “Network Request” with object: “URL: “https://...””
⏱ “Network Request” with object: “URL: “https://...l””
⏱ “Network Request” with object: “URL: “https://....””
</details>

**Comment by jhd-lego** [comment]
@FloEder Thanks, sadly no luck with that either 😞 
I tried copying your files in, but I get the same result.

**Comment by d4vidi** [comment]
@jhd-lego your logs show that there are in-flight network requests that haven't been reponded:
```
“Network Request” with object: “URL: “https://...””
```
Detox waits for everything to settle down in each step, including app launch. Does this give you a lead?

**Comment by jhd-lego** [comment]
Yeah, apparently we have a hanging network connection that "never" terminates. Stupid workaround hacks due to firewall rules 😂 
Thank you! That is why the test never wanted to run.
