### ISSUE TITLE
.scrollTo() gets stuck on Android

### ISSUE THREAD

**Issue by Sonakshi997** [wix/Detox#2779]
I've been using detox from last 4 months and this issue has arisen. On the simulator I cannot see any motion of the scroller. I do not understand any reason for it to not work properly. 
The testing screen halts when .scrollTo('bottom') action statement arises. 

This is what I get when the screen gets stuck on the .scrollTo('bottom') line and it keeps on going and the test do not even fail.

![Android](https://user-images.githubusercontent.com/79457969/118229190-35cc8280-b4a9-11eb-8c7b-ed14e33e0760.png)

Environment I am working with:

- Detox : 18.7.0
- React Native: 0.63.3
- Node: 14
- OS: Android
- Test-runner: jest-circus

**Comment by Sonakshi997** [comment]
My android version is -
![Android version](https://user-images.githubusercontent.com/79457969/118231426-c0fb4780-b4ac-11eb-9abe-edd4cf31bb57.png)

Also, the .scrollTo() works perfectly on IOS.

**Comment by d4vidi** [comment]
@Sonakshi997 please resubmit as an Android bug and add the requested info 🙏🏻 
We won't be able to help without the essential details...
