### ISSUE TITLE
My app crashes when I run detox test

### ISSUE THREAD

**Issue by bharathraj-91** [wix/Detox#2780]
When the app is launched via detox test the app crashes but the app works fine when the app is launched normally in the simulator.

I am attaching my screenshot of the error.

![Simulator Screen Shot - iPhone 11 - 2021-05-15 at 12 53 11](https://user-images.githubusercontent.com/33975215/118351976-87920d00-b57c-11eb-80a0-a596ca21ba36.png)

**Comment by bharathraj-91** [comment]
Below is the logs from detox
[detox_pid_72148.log](https://github.com/wix/Detox/files/6483765/detox_pid_72148.log)

**Comment by dasDeepankar** [comment]
I'm also facing the same issue @bharathraj-91 , when I'm trying to run 
**detox test --configuration iOS**
I'm using  "detox": "^18.13.0"
![Screenshot 2021-05-16 at 7 48 31 PM](https://user-images.githubusercontent.com/25655346/118400662-2b181600-b680-11eb-8f82-6cfca9c699e6.png)

System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 171.06 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.24.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 25, 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Automotive with Play Store Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_191 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.3 => 0.62.3

**Comment by d4vidi** [comment]
@bharathraj-91 please reopen as an iOS issue with the necessary details. Thanks.
