### ISSUE TITLE
Camera Permission issue with Detox Android

### ISSUE THREAD

**Issue by rajithaswoop** [wix/Detox#2785]
Permission Issue with Android : I have this issue on Detox 18.13.0, React Native 0.63.4, API 30 for my Android emulator. It works perfectly for camera permission on iOS but on Android, whatever I set NO or YES on permissions, they are always enabled.

If I change theses permissions on the app before launching detox test, all permissions are enabled again.
@noomorph @d4vidi

**Comment by noomorph** [comment]
@d4vidi, do we have those camera permissions correctly implemented for Android?

**Comment by rajithaswoop** [comment]
beforeAll(async () => {
    await device.launchApp({newInstance: true, permissions: {camera: ‘NO’}});
    await device.launchApp({ permissions : { location: ‘always’ }})
    await device.launchApp({ permissions : { notifications: ‘YES’ }})
  });
So here camera permissions is not taking NO permission, always camera is shown in ON state when detox test is run
@noomorph

**Comment by d4vidi** [comment]
Hey @rajithaswoop, unfortunately, the `permissions` argument to `launchApp()` is [only applicable on iOS](https://github.com/wix/Detox/blob/master/docs/APIRef.DeviceObjectAPI.md#2-permissionsset-runtime-permissions-ios-only), at the moment. You are welcomed to follow [this issue](https://github.com/wix/Detox/issues/477) for support on Android, in the future. We also accept contributions 😄
