### ISSUE TITLE
.scrollTo() gets stuck on Android

### ISSUE THREAD

**Issue by Sonakshi997** [wix/Detox#2787]
### Describe the bug

I've been using detox from last few months and this issue came into my observation. On the simulator I cannot see any motion of the scroller. I do not understand any reason for it to not work properly. 
Can it be the detox version issue?
The scroller was earlier working in all the test files so far till past 2 weeks and now failing in few of the files.

The testing screen halts when .scrollTo('top') action statement arises and nothing happens afterwards. 
If anyone have any solution to this, please share. It would be of great help.

![Screenshot 2021-05-20 at 6 16 12 PM](https://user-images.githubusercontent.com/79457969/119089509-e72e6380-ba27-11eb-87b6-fc5e13060a32.png)

### Steps To Reproduce

1. detox test -c debug

### Expected behavior
Should have scrolled the screen in either direction.

### Detox Trace-Logs
![Log_trace](https://user-images.githubusercontent.com/79457969/119089634-147b1180-ba28-11eb-8c49-d96671f1ed6b.png)
![Log_trace_1](https://user-images.githubusercontent.com/79457969/119089646-19d85c00-ba28-11eb-90ec-b3f84da55936.png)
![Log_trace_2](https://user-images.githubusercontent.com/79457969/119089652-1cd34c80-ba28-11eb-974f-99115ed1b93e.png)

Full log trace -> 
[test_log_trace.pdf](https://github.com/wix/Detox/files/6520414/test_log_trace.pdf)

### Environment :
 - Detox: 18.7.0
 - React Native: 0.63.3
 - Node: 14.16.0
 - Device: Pixel_API_23x86
 - OS: macOS Big Sur 11.2.3
 - Test-runner: jest-circus

**Comment by d4vidi** [comment]
@Sonakshi997 it's really hard to tell what wrong this way. Could you please use the `--take-screenshots all`, `--record-video all` and `--record-logs all` arguments to `detox test` and provide the artifacts generated under the `artifacts/` folder?

**Comment by Sonakshi997** [comment]
@d4vidi I understand. Here is what you asked for. I hope the issue gets clear now as I am facing this on various different screens now. Also, the `ScrollTo()` works perfectly fine on IOS. 
 
### What is expected from the `ScrollTo()` -> Done manually:

https://user-images.githubusercontent.com/79457969/119674108-8f459180-be59-11eb-9f3a-ba79c8cec8dd.mov

### What Detox is doing via test: 

https://user-images.githubusercontent.com/79457969/119674203-a4222500-be59-11eb-91c7-2bc821a223b7.mov

### Console Logs Before and After the `ScrollTo() ` : 
![ConsoleLogsForScrollTo()](https://user-images.githubusercontent.com/79457969/119675458-b05ab200-be5a-11eb-8abd-6dcbbfb9b004.png)

### What happens on the terminal -
![ConsoleLogs Output](https://user-images.githubusercontent.com/79457969/119675566-c9fbf980-be5a-11eb-814f-df41e441c50f.png)

Thank you.

**Comment by d4vidi** [comment]
@Sonakshi997 this is great, thank you. Please also spot a file called `process.log` under the failing test and upload it as well. Thank you!

**Comment by Sonakshi997** [comment]
I understand @d4vidi . I tried finding this file, but could not. Can you describe in detail where can I find this file. That will help a lot.

**Comment by d4vidi** [comment]
Add the `--record-logs all` argument to `detox test`. After the execution completes, you will have such files under an `artifacts/` subdirectory.

**Comment by Sonakshi997** [comment]
Hi @d4vidi . Here is the process.log file you requested. Let me know if anything else is required from my side.

[process.log](https://github.com/wix/Detox/files/6684452/process.log)

**Comment by Sonakshi997** [comment]
Hi @d4vidi . I was able to overcome this stuck `.scrollTo()` problem by doing this.

>  I created a function that takes the testID as arguments and calls it in files where my scrollTo() does not work.

    await element(by.id(scroller_testID)).scroll(scrollValue, 'down')
    await element(by.id(scroller_testID)).tapAtPoint({
      x: 10,
      y: 10,
    })
    await element(by.id(screenView_testID)).tapAtPoint({
        x: 10,
        y: 20,
      })

I believe this is just a temporary solution or a hack to make things work for now. Let me know if there is any progress at your part. 
Thank you.

**Comment by d4vidi** [comment]
Yikes. There shouldn't be such hacks in Detox. @jonathanmos could we get to the bottom of this together?

**Comment by d4vidi** [comment]
@jonathanmos were you able to make any progress here?

**Comment by jonathanmos** [comment]
@Sonakshi997 I was not able to reproduce this issue, except when the soft keyboard was open due to typing in the textfield - in which case, I added tapReturnKey to dismiss it and the test subsequently passed properly. What is the purpose of tapAtPoint? Is it to dismiss the keyboard or for another reason?

**Comment by AdamTyler** [comment]
I'm seeing this exact issue. Works fine on iOS but Android hangs until timing out on `scrollTo` actions:

```detox[15977] INFO:  [APP_STATUS] App synchronization debug: The app appears to be idle!
detox[15977] INFO:  [APP_STATUS] App synchronization debug: The app appears to be idle!
detox[15977] INFO:  [APP_STATUS] App synchronization debug: The app appears to be idle!
detox[15977] INFO:  [APP_STATUS] App synchronization debug: The app appears to be idle!
detox[15977] INFO:  [APP_STATUS] App synchronization debug: The app appears to be idle!
detox[15977] INFO:  [APP_STATUS] App synchronization debug: The app appears to be idle!
detox[15977] INFO:  [APP_STATUS] App synchronization debug: The app appears to be idle!
detox[15977] INFO:  [APP_STATUS] App synchronization debug: The app appears to be idle!
detox[15977] INFO:  [APP_STATUS] App synchronization debug: The app appears to be idle!
detox[15977] INFO:  [APP_STATUS] App synchronization debug: The app appears to be idle!
detox[15977] INFO:  [APP_STATUS] App synchronization debug: The app appears to be idle!
detox[15977] INFO:  [APP_STATUS] App synchronization debug: The app appears to be idle!
detox[15977] INFO:  [APP_STATUS] App synchronization debug: The app appears to be idle!
detox[15977] WARN:  [PENDING_REQUESTS] The app has not responded to the network requests below:
  (id = 50) invoke: {"target":{"type":"Class","value":"com.wix.detox.espresso.EspressoDetox"},"method":"perform","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"androidx.test.espresso.Espresso"},"method":"onView","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"com.wix.detox.espresso.DetoxMatcher"},"method":"matcherForTestId","args":["create-event-preview-post"]}}]}},{"type":"Invocation","value":{"target":{"type":"Class","value":"com.wix.detox.espresso.DetoxViewActions"},"method":"click","args":[]}}]}```

**Comment by Sonakshi997** [comment]
> @Sonakshi997 I was not able to reproduce this issue, except when the soft keyboard was open due to typing in the textfield - in which case, I added tapReturnKey to dismiss it and the test subsequently passed properly. What is the purpose of tapAtPoint? Is it to dismiss the keyboard or for another reason?

Yes, after typing on an input field, to dismiss the keyboard I used tapAtPoint(which works fine). But here the issue comes after when I think, on applying scollTo('direction') it should go in either direction, but rather the screen stays still. The console shows me initially it is busy with threads and then app is idle comes 'n' number of times and on the UI nothing happens. Just still. No particular reason I could find too for the screen stuck as there was no interruption at the screen as well.

**Comment by jonathanmos** [comment]
I was able to reproduce the issue, which looks like it occurs with any view placed before a scrollview. Although I haven't found the root cause yet, I did find that adding style={{flex: 1}} to the parent view seems to fix the problem - e.g.:

      <View testID={'screenView_id'} style={{flex: 1}}>
        <TextInput testID={'textInput_id'} placeholder={'Type here'}/>
        <ScrollView testID={'scrollView_id'}>
       ...
       </ScrollView>
       </View>

**Comment by d4vidi** [comment]
@jonathanmos any action items here?

**Comment by Mellbourn** [comment]
We have hit the same problem as earlier, so it seems that this is not fixed.

**Comment by twocs** [comment]
Still seeing this problem.  The ScrollView is inside a SafeAreaView, but ScrollTo just displays "App synchronization debug: The app appears to be idle!"

Finally setting `<SafeAreaView style={{flex: 1}}>` and it works.

**Comment by twocs** [comment]
Also had to set `style={{flex: 1}}` on a Flatlist's parent, which was a Native-Base HStack.

**Comment by owens-ben** [comment]
This is STILL not fixed.

**Comment by owens-ben** [comment]
Anyone else running into this could consider this workaround

if (device.getPlatform() !== 'ios') {
    const scrollView = element(by.type('android.widget.ScrollView'));
    try {
      if (direction === 'bottom') {
        await scrollView.swipe('up'); // swiping up scrolls down
    } else if (direction === 'top') {
        await scrollView.swipe('down');
    }
    } catch (e) { 
      console.error(e)
    }
  }

**Comment by cassiourugit** [comment]
I have the same problem. But none of the suggested fixes did it for me.
Simply unable to use detox on android because any of the drag, swipe, scroll gestures work.
Everything fine on IOS...

I wonder why there is not more people with this issue, should be a very common issue to bump into

**Comment by markpar** [comment]
I tried adding `flex: 1` to the style for the parent container and it seems to be working so far.  We have a lot of scrollable screens in our app and I'll need to verify them all, but confidence is high.

Long term, it would be nice to understand why that workaround unblocks things and, if possible, make a fix for it.  Happy to help out in any way I can.

**Comment by noomorph** [comment]
Any updates about 20.13.2-smoke.0?

**Comment by poojan010** [comment]
> Any updates about 20.13.2-smoke.0?

Did not work

**Comment by noomorph** [comment]
@poojan010 would you mind to record a video artifact with an example of what's happening there on a scroll attempt?

**Comment by poojan010** [comment]
sure i'll provide video today

**Comment by Seraphiyra** [comment]
> Any updates about 20.13.2-smoke.0?

I've just given this a shot in hope this might help with some of the issues we have been running into with android. 

Seems to have resolved the issue with scroll getting stuck, but we are still seeing swipe getting stuck in the same way.

**Comment by noomorph** [comment]
@Seraphiyra well, as long as it does not break something and fix something, it is good for me to release. Thanks for the confirmation!

If someone can fiddle with our Android source for swipe handlers, similarly to #4225, please share your solution. We'll make sure to release a public beta as soon as you submit and it passes our E2E tests.

**Comment by poojan010** [comment]
Not working for Me 

https://github.com/wix/Detox/assets/63223116/c1ed2d40-1981-4be7-88e5-173c5df02344


### simple.test.js

```
describe('Example', () => {
  beforeAll(async () => {
    await device.launchApp();
  });

  beforeEach(async () => {
    // await device.reloadReactNative();
  });

  it('scroll to bottom', async () => {
    await element(by.id('scroll-view')).scrollTo('bottom');
  });

  it('scroll to top', async () => {
    await element(by.id('scroll-view')).scrollTo('top');
  });
});
```


### App.js
```
import { Button, ScrollView, StyleSheet, Text, View } from 'react-native'
import React from 'react'

const App = () => {
  return (
    <View style={{flex:1,backgroundColor:'white'}}>
      <ScrollView testID='scroll-view' style={{ flex: 1}}>
        <Text testID='hello-text'>Hello</Text>
        <View  style={{height:500}}/>
        <View  style={{height:500}}/>
        <Button title='Press Me' testID='button'/>
        <View  style={{height:500}}/>
        <View  style={{height:500}}/>
      </ScrollView>
    </View>
  )
}

export default App

const styles = StyleSheet.create({})
```

**Comment by noomorph** [comment]
@poojan010 , what is happening here? 🤯 🤯 🤯 🤯 🤯 🤯 🤯 🤯 🤯 🤯 🤯 
🤯 🤯 🤯 🤯 🤯 🤯 🤯 🤯 🤯 🤯 🤯 🤯 🤯 🤯 🤯 🤯 🤯 
🤯 🤯 🤯 🤯 🤯 🤯 🤯 🤯 🤯 🤯 🤯 🤯 🤯 🤯 🤯 🤯 

Do I understand correctly that a scroll gesture is interpreted as some system UI action, and it gets interpreted by Android itself? If so, I wonder, can't you disable some gestures on your emulator?

**Comment by noomorph** [comment]
I had a busy day today, so I'd refrain from releasing when I'm leaving the office. Tomorrow I'll release that smoke version.

**Comment by Seraphiyra** [comment]
> @Seraphiyra well, as long as it does not break something and fix something, it is good for me to release. Thanks for the confirmation!
> 
> If someone can fiddle with our Android source for swipe handlers, similarly to #4225, please share your solution. We'll make sure to release a public beta as soon as you submit and it passes our E2E tests.

@noomorph  I had a little bit of a poke into this, but alas no success😞

I tried a few things, but in the end by changing from API 33 -> 32  was able to get swipe to work for us again.  This was a not ideal, albeit quick, fix to enable us to keep our tests running and not block releases.

We currently use significantly more swipe actions than scroll actions in our test suite. So that means this will go into my backlog to poke at again (if others don't fix beforehand 🤞)

**Comment by noomorph** [comment]
@Seraphiyra, thanks for trying! I hope someone takes it soon. I communicated the importance of these issues to my team, but the ETA is not clear yet.

**Comment by noomorph** [comment]
@poojan010 I think that @gosha212 will look quite soon into your case. There's a plan to fix scroll/swipe conflicting with Android's gesture handling.

**Comment by gosha212** [comment]
Hi @poojan010,
I'm working on a solution for your problem. A temporary solution is to disable the gesture navigation on your emulator. Here is more [details](https://github.com/wix/Detox/issues/4257#issuecomment-1859170671):

**Comment by hanna-becker** [comment]
Ran into this issue today, the workaround of adding style={{flex: 1}} to the parent view fixes the scrollTo command for us..

Android API 30, detox 20.14.8

Hope, there'll be a proper fix, soon!
