### ISSUE TITLE
Getting Error: "detox-cli" package is not meant to be installed locally when running detox

### ISSUE THREAD

**Issue by ptreitler** [wix/Detox#2789]
I just followed the getting started guide, but running any `detox` command results in this error message:
```
Error: "detox-cli" package is not meant to be installed locally, exiting...
HINT: Remove the local installation and reinstall it globally:
  npm uninstall detox-cli
  npm install -g detox-cli
```

I have verified that detox-cli is installed globally and not locally.
Running the above commands doesn't change anything.

Environment:
Windows 10
Node v14.17.0
npm 7.14.0
detox-cli@18.13.0
detox@18.13.0

I found this stackoverflow post: https://stackoverflow.com/questions/67607624/error-detox-cli-package-is-not-meant-to-be-installed-locally-exiting - but running it with the path doesn't work for me either.

`Get-Command detox` gives me `~/AppData/Roaming/npm/detox.ps1` as a path which looks fine to me.

**Comment by hgvo9** [comment]
I have the same issue and couldn't find any solutions..

**Comment by d4vidi** [comment]
Did you try the suggested fix? -
```
  npm uninstall detox-cli
  npm install -g detox-cli
```

**Comment by hgvo9** [comment]
> 
> 
> Did you try the suggested fix? -
> 
> ```
>   npm uninstall detox-cli
>   npm install -g detox-cli
> ```

![error](https://user-images.githubusercontent.com/62654884/119317046-f86daf00-bc77-11eb-9e9d-d310066949d7.png)

**Comment by noomorph** [comment]
@hgvo9 , does it happen on Windows 10 as well in your case?

**Comment by hgvo9** [comment]
> 
> 
> @hgvo9 , does it happen on Windows 10 as well in your case?

Yes, this is correct!

**Comment by noomorph** [comment]
@hgvo9 , seems like it. I am checking this theory atm.

**Comment by noomorph** [comment]
I'll release a patch version soon.

**Comment by hgvo9** [comment]
> 
> 
> I'll release a patch version soon.

Sweet, thanks a lot

**Comment by noomorph** [comment]
@hgvo9 , @ptreitler 

```
npm uninstall detox-cli
npm install -g detox-cli
```

Try again, please. Now you should get the hotfixed version. It should work as expected.

**Comment by hgvo9** [comment]
![screenshot](https://user-images.githubusercontent.com/62654884/119354755-bb6be180-bca4-11eb-9cc8-1a2ea5814877.png)
Working great for me, thanks a lot @noomorph

**Comment by noomorph** [comment]
@hgvo9, glad to hear the hotfix helped — of course, it would be awesome to get [global-dirs](https://github.com/sindresorhus/global-dirs) fixed. I'll try to open an issue there soon.

**Comment by ptreitler** [comment]
Works for me as well, thanks a lot for the quick fix @noomorph!

**Comment by caiangums** [comment]
Hey! I got the same error at MacOS 😞 

Apparently my version of `detox-cli` (global) is `18.14.1`.

I'm using:
- Node v14.17.0
- npm v6.14.13
- yarn v1.22.10

**Comment by noomorph** [comment]
@caiangums , have you got **detox-cli** installed via **yarn**? Please post your output of `npm -g bin` and `which detox` commands.

This is okay that the latest detox-cli version is 18.14.1. There were no new versions of the package since that hotfix.
