### ISSUE TITLE
D8: Cannot fit requested classes in a single dex file

### ISSUE THREAD

**Issue by Hatko** [wix/Detox#2793]
### Describe the bug
Whenever I'm trying to run the tests on Android using the commands 

`detox build --configuration android.emu.release`/`detox build --configuration android.emu.debug`

I'm getting an error:

> Task :tipsi-stripe:mergeDexDebugAndroidTest FAILED
D8: Cannot fit requested classes in a single dex file (# methods: 90835 > 65536)
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
The number of method references in a .dex file cannot exceed 64K.

I've followed the instruction to set up multidex which didn't fix the issue.
Also, making a usual build has been working without any issues regardless of changes to/from multidex.

### Steps To Reproduce

In my case, installing the dependencies and running the tests is enough. Given that `tipsi-stripe` caused us issues in the past, I suspect it being involved here as well. The version of the `tipsi-stripe` package is: "tipsi-stripe": "8.0.2"

- [X] I have tested this issue on the latest Detox release and it still reproduces

1. Install the dependencies
2. Run the tests using the mentioned commands

### Expected behavior
Tests are run

### Detox Trace-Logs

No logs obtained

### Device logs (adb logcat)

No logs generated when used `--record-logs all`

### Environment (please complete the following information):
 - Detox: 18.14.0
 - React Native: 0.63.4
 - Node: v14.15.4
 - OS: 10.15.7
 - Test-runner (select one): `jest-circus`

**Comment by noomorph** [comment]
I am afraid this issue has little to do with Detox itself.

You'll need to dance around your Gradle scripts a bit, I guess.

https://stackoverflow.com/questions/36785014/the-number-of-method-references-in-a-dex-file-cannot-exceed-64k-api-17

If there's something Detox-specific in your issue, please reopen the issue and let me know extra deals. Meanwhile, I have to close this issue. Good luck with your Android DEX investigation.
