### ISSUE TITLE
How to diagnose `detox[22352] ERROR: [APP_UNREACHABLE]`

### ISSUE THREAD

**Issue by jinhale** [wix/Detox#2796]
I'm running the following command: `detox test --record-logs all --configuration android.emu.debug`

Changing the timeout value doesn't affect the outcome. I can run the app normally in multiple emulators and is running on devices without error. The build before this I got the following error: `detox[3540] ERROR: [APP_UNREACHABLE]`. 

I'm not running the app manually on the emulators while attempting to test. I shut off the command, `npx react-native start --reset-cache`, before I tried the build and test, just to be on the safe side. 

Here is a snippet from the `.detoxrc.json` file: 

        "android.debug": {
          "type": "android.apk",
          "binaryPath": "android/app/build/outputs/apk/debug/app-debug.apk",
          "build": "cd android && .\\gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && cd .."
        },

Reading the `emulator-5554 2021-05-24 16-51-20Z.startup.log` file I see many variations of the following error: 

     Opening an oat file without a class loader. Are you using the deprecated DexFile APIs?

Testing with the _incorrect_ emulator ID will cause the test to fail sooner and with different errors, so I think the emulator is correctly set now. I don't see the app running on the device at any point of the test, but I don't see any indication of the app crashing in the log files. What should I look for next?

**Comment by noomorph** [comment]
I'd suggest looking at app logs from the device – there should be some messages from DetoxManager or at least something about Detox. If there aren't such, there's some problem with the instrumentation runner. Could you attach your logs, pls?
