### ISSUE TITLE
Detox problem with React Native Navigation(wix)

### ISSUE THREAD

**Issue by leralera2201** [wix/Detox#2797]
I set a custom component for right button and pass onPress function,  also I add testID, and when I tap on this button through my tests, onPress function doesn't work. Click is made because I see a touchable effect. But the function is not called at all. This is my right button:

```
{
  id: 'login-button',
  testID: 'publicEvents.nav-login-button',
  component: {
    name: 'LoginNavBarButton',
    passProps: {
      onPress: onEventLoginPress
    }
  }
}
```

How I tap on this button:

```js
 await element(by.id('publicEvents.nav-login-button')).tap();
```

**Comment by noomorph** [comment]
Does that happen only during Detox testing session?

If you can reproduce this problem without Detox, by tapping manually on that button, I'd suggest directing your issue to https://github.com/wix/react-native-navigation

**Comment by leralera2201** [comment]
> Does that happen only during Detox testing session?
> 
> If you can reproduce this problem without Detox, by tapping manually on that button, I'd suggest directing your issue to https://github.com/wix/react-native-navigation

Only with Detox. The app works good, but when testing this issue with Detox, the function onPress doesn't work.

**Comment by noomorph** [comment]
@guyca, does that ring any bells to you? Just in case... 🤷‍♂️

**Comment by noomorph** [comment]
Please try to avoid crossposting next time.
@guyca requested an example for the bug reproduction here https://github.com/wix/react-native-navigation/issues/7129.
Be kind to prepare the example and provide it.
Meanwhile, I'll close the issue. You can continue the discussion there on the RNN repo.
