### ISSUE TITLE
fbsimctl installation issues

### ISSUE THREAD

**Issue by rjanjua** [wix/detox#280]
#### Description

fbsimctl has installation issues when installing from brew. I noticed this when our ci tests started failing (for fructose). Initially I tried fixing it with `brew install fbsimctl --HEAD`. This worked for about a day after which it would no longer build.

I know detox will face a similar issue when a CI build gets triggered.

#### Steps to Reproduce

On a machine that doesn't have fbsimctl: 
```
brew tap facebook/fb
export CODE_SIGNING_REQUIRED=NO && brew install fbsimctl
```

#### Fix
Use the following to install fbsimctl
```
export CODE_SIGNING_REQUIRED=NO
git clone https://github.com/facebook/FBSimulatorControl.git
cd FBSimulatorControl
git checkout 4a3a339ca325ae2ac0b34fef92605204b79e0c09
./build.sh fbsimctl build output
PATH=$PATH:$(pwd)/output/bin
cd ..
```
#### Node, Device, Xcode and macOS Versions

* Xcode: 8.3, 9
* macOS: Sierra

**Comment by calclavia** [comment]
I'm getting the same problem

**Comment by DanielMSchmidt** [comment]
We are working on removing fbsimctl as a dependency, @DanielZlotin is working on that currently 👍

**Comment by LeoNatan** [comment]
This is a Facebook issue where they can't keep fbsimctl stable on HEAD, but also can't be bothered with to use releases like any other normal project.

https://github.com/facebook/FBSimulatorControl/issues/429
https://github.com/facebook/FBSimulatorControl/issues/437

And so on...

The sooner we remove the fbsimctl dependency, the better.

@DanielZlotin @rotemmiz

**Comment by DanielZlotin** [comment]
I'm on it

**Comment by LeoNatan** [comment]
@DanielZlotin Nope, in ObjC, here: https://github.com/wix/AppleSimulatorUtils/blob/master/applesimutils/applesimutils/main.m#L281
