### ISSUE TITLE
Detox header button test fail

### ISSUE THREAD

**Issue by alakdam07** [wix/Detox#2807]
I am relative new to Detox `E2E` testing.  I have header one button which will go back to the previous screen. I made `testID` for this button but I got one Detox error:  `Test Failed: No elements found for “MATCHER(identifier == “close_button”)”`.  I really don't know how to test the header button.  I am sharing my code, hope someone will help me.

**this is the component where I have button**
```

  const closeScreen = useCallback(() => {
    navigation.pop();
  }, [navigation]);

  useLayoutEffect(() => {
    navigation.setOptions({
      headerLeft: () => <View />,
      headerRight: () => (
        <CloseContainer>
          <TouchableOpacity onPress={closeScreen} testID={'close_button'}>
            <Text>hhhh</Text>
          </TouchableOpacity>
        </CloseContainer>
      ),
    });
  }, [closeScreen, navigation]);



```

**This is my Detox test**

```

 it('close button', async () => {
    const button = await element(by.id('close_button'));
    const text = await element(by.id('previous_page'));
    await button.tap();

    expect(text).toBeVisible();
  });
```

**Comment by Zeroxys** [comment]
@alakdam07  did you solve it ?
