### ISSUE TITLE
Detox continue test with other spec file 

### ISSUE THREAD

**Issue by alakdam07** [wix/Detox#2815]
I am really new Detox testing. I have two different screen tests. First onboarding screen and second is app screen. I have made two different `e2e` files. One is for Onboarding and one is for app testing. My onboarding files pass all my test but my  app screen failed the the test. I want to keep continue my `e2e` testing after it finish the onboarding testing then continue  my app screen testing which is in different files. Is there any way I can do this test where I can test my app screen? 

**This is my onboarding screen test and it pass all the test**

```
describe('Onboarding Screen', () => {
  beforeAll(async () => {
    await device.launchApp();
  });

  beforeEach(async () => {
    await device.reloadReactNative();
  });

  it('should display the welcome text', async () => {
    const text = await element(by.id('onboarding_screen_title'));

    await expect(text).toBeVisible();
  });

  it('should display bottom button', async () => {
    const button = await element(by.id('bottom_button_continue_onboarding'));

    await expect(button).toBeVisible();
  });


});

```

**This is my app screen test file where my test fails**

```
describe('App Screen', () => {
  beforeAll(async () => {
    await device.launchApp();
  });

  beforeEach(async () => {
    await device.reloadReactNative();
  });

  it('selects the store', async () => {
    const continueOnboardingButton = await waitFor(
      element(by.id('bottom_button_continue_onboarding')),
    );

    continueOnboardingButton.tap();
}
  it('Where it will show my data', async () => {
    const data = await waitFor(element(by.id('all_data')))
      .toBeVisible()
      .withTimeout(9000);
  });
});

```

**Comment by shaliniatwork** [comment]
Whats the solution here? Me too facing same error. It works if it runs in the same file. Else it raises Signal 11 and quit
