### ISSUE TITLE
Recommended setup for apps that need Google Play Services

### ISSUE THREAD

**Issue by lindboe** [wix/Detox#2818]
In the setup instructions, [you recommend using an AOSP emulator](https://github.com/wix/Detox/blob/master/docs/Introduction.AndroidDevEnv.md#android-aosp-emulators), for what seems like a couple of reasons, including the removal of Google Play Services. However, our app appears to require Google Play Services to work (I'm not totally sure why yet, but I'm guessing it's Firebase). If we try to run the app on the AOSP emulator, after the splash screen, I see a dialog box that says "This app won't run without Google Play Services..." (I can't get the full message anymore because now the app is just crashing after the splash screen instead).

My question is, if we do need Google Play Services, is it best to just use one of the default emulators, or should I be following another process that avoids some of the other potential issues (e.g., trying to install Google Play Services on the AOSP emulator, while avoiding other problem configuration)?

**Comment by naum43312016** [comment]
I have the same problem, @lindboe did you find a solution for this?

**Comment by d4vidi** [comment]
Hey @lindboe! Sorry for the delay - we've all been overly busy lately.

It's basically as you said it: AOSP-image-based emulators are strictly a recommendation, for the sake of stability, which is paramount for the success of automated testing environments. If your app requires play services, in the realm of Google emulators, you have no choice but to set up an emulator with the fully-blown Google image.

This emulator configuration generally works, but it does not provide a safe environment for running automated tests regularly (e.g. on a CI platform). We've seen things such as a very high CPU usage after load (even in idle) - which can impact the tested app's performance, and quirks from the google keyboard.

A different direction I can suggest to explore (haven't fully done so myself), is the usage of Genymotion emulators with manually added [play services support](https://www.genymotion.com/blog/2-10-open-gapps-widget/). Perhaps it would provide you a means for getting the best of both worlds. In Detox, we support local Genymotion emulators, and are in the works for fully supporting their SaaS solution, as well.

Please close the issue if this answers your question.

**Comment by lindboe** [comment]
Thank you for the answer @d4vidi! I appreciate the Genymotion suggestion too.

**Comment by humaidk2** [comment]
Hey,

I have a similar issue but with real devices, Do you have any recommendations for that?

My debug version seems to work fine, but release build type fails to launch.
