### ISSUE TITLE
Check enabled/disabled by using getAttributes() for TouchableOpacity

### ISSUE THREAD

**Issue by hqdai** [wix/Detox#2821]
Please correct me if I'm wrong with the understanding document.
I need to check the button (enabled/disabled) by using getAttributes(), but it seems the enabled value is always returned TRUE, even though I send prop disabled: TRUE to TouchableOpacity.
But I see it works with a View go with prop: pointerEvents="none".

I'm using RN 0.64 vs Detox 18.16.0
MacOS 11.3
iPhone 12 Simulator - iOS 14

<img width="1666" alt="Screen Shot 2021-06-04 at 08 51 54" src="https://user-images.githubusercontent.com/19548213/120734517-363dc380-c513-11eb-9955-9f04c8c6075c.png">

**Comment by noomorph** [comment]
@alon-ha, could you check, please, whether the logic for `enabled` property gets the value from the native view hierarchy code or we have some custom implementation there?

@hqdai, it might be that this is an implementation detail of a specific React Native component. If so, the fix is going to be very debatable and not straightforward. Get some patience with it, it might take longer to look into this properly.

**Comment by alon-ha** [comment]
@noomorph Yes, we are checking for the native view `userInteractionEnabled`
Can see in those links:
https://github.com/wix/Detox/blob/1e26e4b1d61fea47a6e690d8222dfaa48bf93b30/detox/ios/Detox/Utilities/NSObject%2BDetoxUtils.m#L304
https://github.com/wix/Detox/blob/4531220db9c22692df515c8ffe7fbbd7cd682e18/detox/ios/Detox/Utilities/UIView%2BDetoxUtils.m#L350

**Comment by d4vidi** [comment]
@alon-ha should we be inspecting a different prop, then? With `disabled: true`, it must leave a mark somewhere on the native side such that the view is not tappable. I presume with can be easily checked with xcode's hierarchy analyzer.

**Comment by alon-ha** [comment]
I think it's related to how react native "draw" TouchableOpacity view. Maybe it's a view inside another one.

**Comment by d4vidi** [comment]
@hqdai Did you find a way to resolve this problem, eventually?

**Comment by hqdai** [comment]
No, not yet, please take a look at this, and consider to re-open this issue. Thank you <3

**Comment by iMaupin** [comment]
@hqdai has there been any movement on this issue? Do we know what the enabled property on a TouchableOpacity is mapped to?

**Comment by SmartArray** [comment]
This is indeed important because 
```jsx
<AnimatedPressable disabled={true}>...</AnimatedPressable>
```
won't work.

**Comment by ansonliao** [comment]
Any update on this issue?
I am facing this problem as well.

**Comment by micahdasMA** [comment]
Has anyone been able to figure this issue out? I am having the same problem where a button that is disabled returns `enabled=true` when using `getAttributes()`

**Comment by AndreyBernardoni** [comment]
Same here, it isnt fixed yet...
