### ISSUE TITLE
Error: "detox-cli" package is not meant to be installed locally, exiting...

### ISSUE THREAD

**Issue by caiangums** [wix/Detox#2825]
Related issue: https://github.com/wix/Detox/issues/2789

Following the instructions to install Detox, I got the same error from the related issue. I already tried to uninstall and install again but seems that the version is still outdated.

My environment:
- macOS Big Sur (Just updated with everything)
- Node v14.17.0
- npm v6.14.13
- yarn v1.22.10

**Comment by noomorph** [comment]
@caiangums , have you got **detox-cli** installed via **yarn**? Please post your output of `npm -g bin` and `which detox` commands.

This is okay that the latest detox-cli version is 18.14.1. There were no new versions of the package since that hotfix.

**Comment by caiangums** [comment]
Thanks for the quick response! 

> have you got detox-cli installed via yarn?

No, I installed via `npm` and I'm using `yarn` for my project. I have `detox-cli` installed at the same directory that `npm` installed `yarn` (globally):

```sh
$ ls /usr/local/lib/node_modules                                                                                                                                                                                          
detox-cli yarn
```

> Please post your output of `npm -g bin` and `which detox` commands.

```sh
$ npm -g bin                                                                                                                                                                                                            
/usr/local/bin

$ which detox
/usr/local/bin/detox
```

I just took a look at how you guys managed to solve [at this PR](https://github.com/wix/Detox/pull/2794/files) and just commented out the full `if` statement inside my local version of `detox`. Now seems to be working for me, as I totally removed the dependency from `is-installed-globally`.

For me, doing these changes sounds wrong on many levels 😅

**Comment by noomorph** [comment]
@caiangums , could you also run this in your Terminal?

```
ls -al /usr/local/bin | grep detox
```

Just to make sure where exactly `detox-cli` is installed in your environment.

Unfortunately, I haven't been able to reproduce your issue so far. To add clarity, I tried installing Node.js from here: https://nodejs.org/dist/v14.17.0/node-v14.17.0.pkg and then switched via `nvm use system; nvm unload`:

```
Failed to find Detox executable at path: /Users/yaroslavs/Projects/node_modules/.bin/detox

Possible solutions:
1. Make sure your current working directory is correct.
2. Run "npm install" to ensure your "node_modules" directory is up-to-date.
3. Run "npm install detox --save-dev" for the fresh Detox installation in your project.
```

As you can see, the error here is an expected one.

Could you also please modify your `is-installed-globally` (index.js) code there in your globally installed packages?

```diff
 'use strict';
 const fs = require('fs');
 const globalDirs = require('global-dirs');
 const isPathInside = require('is-path-inside');
 
 module.exports = (() => {
 	try {
+          console.log('YARN DIRS', globalDirs.yarn.packages);
+          console.log('NPM DIRS', fs.realpathSync(globalDirs.npm.packages));

 		return (
 			isPathInside(__dirname, globalDirs.yarn.packages) ||
 			isPathInside(__dirname, fs.realpathSync(globalDirs.npm.packages))
 		);
 	} catch {
 		return false;
 	}
 })();
```

I'd like to see what dirs it recognizes.

**Comment by caiangums** [comment]
@noomorph Thank you so much for your help! 🙏 

The usage of `asdf` seems to solve the issue. Maybe the strive to not use any version manager made me install or configure something wrong and for `detox` this issue happened. I think this issue could be closed for now 😄

**Comment by noomorph** [comment]
@caiangums , so you were using `brew install`, apparently.
Okay, I'll check a few times more then. Thanks for the feedback.

**Comment by caiangums** [comment]
@noomorph Yes! I installed Node v14 (LTS), yarn through it and this is apparently causing the issue. If you need any further information just let me know! 😄

**Comment by baskarkarthik** [comment]
Hi @noomorph 
I'm also facing same issue.

Enviroinment: 
node: v10.24.1
npm: 6.14.12
yarn: 1.22.10

Kindly help in fixing the issue

**Comment by noomorph** [comment]
@baskarkarthik, the best I can help you with **right now** is to advise you to install Node.js [via NVM](https://github.com/nvm-sh/nvm). By the way, consider upgrading to Node v12+, at least — v10 is not supported already by anyone.

Since reverting `is-globally-installed` is going to expose another issue, and vice versa, it still might take time to implement another way to detect spawn loops (see: https://github.com/wix/Detox/issues/2750) for incorrect installation cases, yet avoid false alarms with Homebrew-installed Node. 🤷

**Comment by fjarrett** [comment]
I have the same problem. Like the OP I too installed `node@14` via Homebrew and `yarn` globally via `npm`.

macOS Big Sur 11.5.1
node 14.17.3
npm 6.14.13
yarn 1.22.11

```
$ detox init -r jest
Error: "detox-cli" package is not meant to be installed locally, exiting...
HINT: Remove the local installation and reinstall it globally:
  npm uninstall detox-cli
  npm install -g detox-cli
```

Not sure where to go from here since it's not installed locally:

```
$ which detox
/usr/local/bin/detox

$ ls -al /usr/local/bin | grep detox
lrwxr-xr-x    1 fjarrett  admin       36 Jul 29 16:34 detox -> ../lib/node_modules/detox-cli/cli.js
```

**Comment by d4vidi** [comment]
@fjarrett Please revisit with Detox `18.20.1`

**Comment by fjarrett** [comment]
@d4vidi worked great, thank you!
