### ISSUE TITLE
Assertion failed due to weird characters

### ISSUE THREAD

**Issue by mfrachet** [wix/detox#283]
#### Description

I m actually trying to make some assertions on a UILabel and the text it contains. It fails due to weird characters.

Here's the UILabel I want to test : 

<img width="367" alt="capture d ecran 2017-09-19 a 10 00 42" src="https://user-images.githubusercontent.com/3874873/30582086-bcb6f232-9d22-11e7-8efc-c9f20a10d025.png">

Here's the tests I've tried to run :
```javascript
describe("Example", () => {
  it("see the label 1", async () => {
    await expect(element(by.text('QUADRAS : AVANT-PREMI\\U00c8RE'))).toExist();
  });

  it("see the label 2", async () => {
    await expect(element(by.text('QUADRAS : AVANT-PREMI\U00c8RE'))).toExist();
  });

  it("see the label 2", async () => {
    await expect(element(by.text('QUADRAS : AVANT-PREMIÈRE'))).toExist();
  });

  it("see the label 3", async () => {
    await expect(element(by.type('UILabel'))).toExist(); // throws an error with details
  });
});
```

The detailed error contains this line :

```
"<UILabel:0x7fa3257a4510; AX=Y; AX.label='QUADRAS : AVANT-PREMI\U00c8RE'; AX.frame={{30, 245.5}, {254, 20.5}}; AX.activationPoint={157, 255.75}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{8, 4}, {254, 20.5}}; alpha=1; UIE=N; text='QUADRAS : AVANT-PREMI\U00c8RE'>"
```

I don't know how to access the field.

#### Steps to Reproduce

- Create a native app without testID but with a UILabel
- Add text with accents in the UILabel
- Create a test to match that UILabel
- Verifiy the test is failing with an output like :

```
Error: Cannot find UI Element.
    Exception with Assertion: {
      "Assertion Criteria" : "assertWithMatcher:isNotNil",
      "Element Matcher" : "(((((kindOfClass('UILabel') || kindOfClass('UITextField') || kindOfClass('UITextView')) && hasText('QUADRAS : AVANT-PREMI\U00c8RE')) || (kindOfClass('RCTText') && an object with accessibilityLabel "QUADRAS : AVANT-PREMI\U00c8RE")) && !(kindOfClass('RCTScrollView'))) || (kindOfClass('UIScrollView') && ((kindOfClass('UIView') || respondsToSelector(accessibilityContainer)) && ancestorThatMatches(((((kindOfClass('UILabel') || kindOfClass('UITextField') || kindOfClass('UITextView')) && hasText('QUADRAS : AVANT-PREMI\U00c8RE')) || (kindOfClass('RCTText') && an object with accessibilityLabel "QUADRAS : AVANT-PREMI\U00c8RE")) && kindOfClass('RCTScrollView'))))))",
      "Recovery Suggestion" : "Check if the element exists in the UI hierarchy printed below. If it exists, adjust the matcher so that it accurately matches element."
    }

    Error Trace: [
      {
        "Description" : "Interaction cannot continue because the desired element was not found.",
        "Error Domain" : "com.google.earlgrey.ElementInteractionErrorDomain",
        "Error Code" : "0",
        "File Name" : "GREYElementInteraction.m",
        "Function Name" : "-[GREYElementInteraction matchedElementsWithTimeout:error:]",
        "Line" : "124"
      }
    ]
```

#### Node, Device, Xcode and macOS Versions

* Node: v8.4.0
* Device: IPhone 7 simuator
* Xcode: v8.3.3
* macOS: 10.12.6

#### Other questions

More that this test, I m pretty curious how I can log the fully available elements of a type like the error on multiple UILabel has displayed ?

**Comment by rotemmiz** [comment]
I suggest you read [this section](https://github.com/wix/detox/blob/master/docs/Troubleshooting.RunningTests.md#debug-view-hierarchy) in the FAQ.

Find the exact accessibiltyLabel rendered in the native hierarchy, and report back.

**Comment by mfrachet** [comment]
Here's the details I've got from the XCode helper :

![details](https://user-images.githubusercontent.com/3874873/30582934-c04f7e70-9d25-11e7-8362-e743d3ce49e3.gif)

**Comment by LeoNatan** [comment]
I suggest working with identifiers, rather than text. When searching by text, you open the unicode/ascii/extended ascii Pandora box.
Set an identifier to that label and look for that.
