### ISSUE TITLE
[Android] No test found on Firebase TestLab

### ISSUE THREAD

**Issue by moonjava2005** [wix/Detox#2830]
After I upgraded to React Native 0.64.x and use the Detox >=18.15.0, I cannot run test with Firebase TestLab. The error always like this
![Screen Shot 2021-06-13 at 15 22 27](https://user-images.githubusercontent.com/16474293/121800382-9cd18880-cc5b-11eb-83e7-b0d6c8ed9217.png)

I have already contacted to Google Firebase for help and thay replied me as follow:

`I’ve got an update regarding your case. Upon checking your test APK, it only contains 1 test called DetoxTest that starts this connection and there are no other tests.  This type of test is called Detox, it is a test framework that appears to work differently than a typical Android instrumentation test.
An Android instrumentation test encodes the test itself into the test APK. The test APK contains everything that is needed to run the test, all the code logic and necessary files. For example, there are 2 components to this type of test: app APK, test APK. Detox only uses one Android instrumentation test for its testing functionality. Tests are external on the host, and are driven/executed from there. The test APK is just a bridging layer to externalize tests to the host machine. For instance, there are 3 components to a Detox test: app APK, test APK, tests on the host.
Unfortunately, this is considered as Out of Scope as Detox, or any such test framework that only uses the instrumentation test mechanism to bridge / externalize testing to the host is not covered by  Firebase support. This would be a separate test type in FTL. An Android Instrumentation Test needs to be self-contained and use the mechanism explained in the official documentation.`

Do we have any solution for this issue?

### Environment (please complete the following information):
 - Detox: 18.160.
 - React Native: 0.64.2
 - Firebase TestLab

**Comment by noomorph** [comment]
I think there aren't enough details here. 😞 

I am not really familiar with Firebase TestLab, and I don't see any interesting logs, just some messaging and a generic error message. 🤷‍♂️ 

@moonjava2005, did it work with Detox before the aforementioned upgrade? 🤨 

@d4vidi, @jonathanmos, do you have any good questions that will make @moonjava2005 elaborate on the issue? It looks more like a feature request, doesn't it? 💡

**Comment by moonjava2005** [comment]
@noomorph With verion 18.12.2, we can use Test Lab. But from version 18.3.x, we cannot use Test Lab anymore

**Comment by d4vidi** [comment]
@moonjava2005 all in all, the response you got back from Firebase' support well describes how Detox works. I understand why they would not consider it under their scope, to a certain extent.

Other than that, there are a few questions I have to ask / requests I need to make in order to get a good perspective on the problem:
1. There was nothing special about Detox changes going from 18.12.x -> 18.15.x. Is it possible that what prevents the test lab from working in the first place is in fact the switch to RN .64?
2. How did you manage to run Detox in firebase' test lab, in the first place? I would love to get more details on what the configuration looks like! In particular, what intrigues me most is which computer effectively runs the JS-side of the tests (i.e. Detox itself + Detox server).
3. Could you *please* provide all the details you can get from firebase? Anything under the `logs` tab, and more.

Thanks.

**Comment by moonjava2005** [comment]
@d4vidi 
1. After I upgrade to RN .64, the Detox 18.12.x cannot run until I upgrade to Detox 18.13.x (I remember that). But since that time, I cannot use Test Lab
2. As Detox 18.12.x, I only need export app.apk and test.apk and then, we upload these files to Firebase Test Lab via their API. We didn't need any extra effort
3. There's no log on Firebase Test Lab because they cannot find any test unit. It means no log, no record, only Error that "Test run failed to complete. Expected 1 tests, received 0"

**Comment by d4vidi** [comment]
@moonjava2005 what you said in section 2 doesn't sound right. In order for Detox to run, providing the apk's can't be enough. It's as Firebase' support said it: the test APK holds only *one single test*, which - unless driven by Detox itself (i.e. by running it on a host computer that connects to the device), does absolutely nothing.
It sounds like this has never really worked for you, TBH.

**Comment by moonjava2005** [comment]
@d4vidi 
The screen shot is the last successful test from Test Lab (may be on May 1st). At that time, I had not upgraded to 18.13.x yet (it was on 18.12.x)
![Screen Shot 2021-06-22 at 17 28 33](https://user-images.githubusercontent.com/16474293/122909492-71e3e480-d37f-11eb-88e9-6684557a1925.png)
![Screen Shot 2021-06-22 at 17 28 14](https://user-images.githubusercontent.com/16474293/122909503-74463e80-d37f-11eb-9022-723dc0155ec0.png)

**Comment by d4vidi** [comment]
As I understand it, there was nothing tested in that session on Test Lab. 1 Test for 3 sec total = nothing happened.

**Comment by moonjava2005** [comment]
@d4vidi Yes, actually, we only use TestLab for make sure CI build with the production signature whether causes the crash on real device. We run test logic in our side in another phase. But now, we cannot run this crash test any more

**Comment by d4vidi** [comment]
Ok, for the record, I don't think that makes a lot of sense.
In any case, it doesn't sound like Detox has anything to do with this. Can you try to use the latest Detox + RN 63 and try again?

**Comment by d4vidi** [comment]
Also, may I suggest a different strategy: Don't use Detox in this case. Implement just a simple native test that launches the app - similar to what we you did in `DetoxTest.java`, but without initializing Detox. Then, there are ways to execute specific suites, instead of all of them.
