### ISSUE TITLE
Interactive touch outside React-Native-Navigation Overlay when detox run

### ISSUE THREAD

**Issue by hqdai** [wix/Detox#2834]
### Description
I'm using React-native-navigation (RNN) with an overlay is showing as alert, my issue is when manual test, I can't touch outside the alert message, that is correct, but when detox runs for automation test, it can touch and scroll outside the alert area. 

So, the problem is why Detox can interact outside the overlay area ...

- [x] I have tested this issue on the latest Detox release and it still reproduces.

#### Reproduction

To reproduce, please check out my pet project and just do the test run. You can see detox can scroll even though the alert message is shown on top. Please be noted that I've turned option: interceptTouchOutside: true already. 

https://user-images.githubusercontent.com/19548213/121865961-b1c81d80-cd28-11eb-9f0f-019226435704.mov

[Interactive 2.zip](https://github.com/wix/Detox/files/6646930/Interactive.2.zip)

#### Environment:
 - Detox: 18.16.0
 - React Native: 0.64.1
 - Node: 14.10.1
 - Device: iPhone 12 (Simulator)
 - Xcode: 12
 - iOS: 14.5
 - macOS: 11.3

**Comment by noomorph** [comment]
@hqdai, sorry for replying late.
Thanks for providing the example project.
Hopefully we can check it next week.

**Comment by hqdai** [comment]
> @hqdai, sorry for replying late.
> Thanks for providing the example project.
> Hopefully we can check it next week.

Thank you @noomorph :D, it seems the issue still happens. Please reopen the issue.

**Comment by d4vidi** [comment]
@hqdai Detox has super powers 😄
I wonder whether it is plausible that touch events get somehow associated with specific views (based on interactability & visibility). @alon-ha would you mind taking a look into this sometime next week? There's an example project here ready to go.

**Comment by alon-ha** [comment]
Will check it this week and update

**Comment by phuongwd** [comment]
Not stale,

**Comment by phuongwd** [comment]
Hello @alon-ha,
Could you please give me the an update?

Many thanks

**Comment by d4vidi** [comment]
No updates so far, we apologize.

**Comment by phuongwd** [comment]
> No updates so far, we apologize.

No problems, just checking to update our progress 😊

**Comment by phuongwd** [comment]
Not stale

**Comment by asafkorem** [comment]
Thanks @hqdai for reaching out with this bug report! 
[This PR](https://github.com/wix/Detox/pull/3115) will solve the bug you described.
