### ISSUE TITLE
Device allocation issue related to ADB disconnection of Genycloud instances

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#2842]
### Describe the bug
It appears sometimes Genymotion-cloud instances get disconnected from ADB. When this happens, they appear online but are in fact unreachable:

```
{"uuid": "703bb5fe-637d-45c2-bb1f-979088dfb41d", "name": "Detox-1623848194971.2", "state": "ONLINE", "adbtunnel_state": "FAILED"...
```

To spare some details (todo), when this happens other workers keep on trying to allocate the same already occupied instance and fail to do so, over and over again. 

### Steps To Reproduce
- [x] I have tested this issue on the latest Detox release and it still reproduces

Actual build on CI: https://jenkins-oss.wixpress.com/job/detox-android-59-9-pr/2107/

TODO
1. 
2. 
3. 

### Expected behavior

Detox should overcome the failed ADB connection and avoid attempts to allocate already used instances.

### Environment (please complete the following information):
 - Detox:
 - React Native:
 - Node:
 - Device:
 - OS: 
 - Test-runner (select one): `jest-circus` | `jest-jasmine2` (deprecated) | `mocha`

**Comment by noomorph** [comment]
Looks like this is a separate issue from what #2845 was trying to address. Let's put the CI on observation, provided that workers cannot steal each other devices from now on. We might see some more interesting error messages and learn from them what to address next.

**Comment by d4vidi** [comment]
All-in-all, as I understand it, it seems that this was a result of genymotion being configured (by us) to limit the overall lifespan of instances to 30min. We resolved it by increasing to 1hr (although theoretically, test running on CI builds are not meant to reach that 30min in any standard use case).

I think this can be closed, then (@noomorph - ACK?)
