### ISSUE TITLE
multiple elements found for “MATCHER(identifier == “element”) in action

### ISSUE THREAD

**Issue by AshrafRizvi01** [wix/Detox#2844]
### Description
When using atIndex(0) function for an element while doing any actions (i.e. swipe, scroll), the atIndex(0) function is ignored.

Test Failed: Unable to scroll down in “<RCTCustomScrollView: 0x7fd87585d600>” and multiple elements found for “MATCHER(identifier == “my-element”)”
    TIP: To print view hierarchy on failed actions/matches, use log-level verbose or higher.

      23 |       .toBeVisible()
      24 |       .whileElement(by.id('flat-list'))
    > 25 |       .scroll(300, 'down');
         |        ^
      26 |     await detoxExpect(MyScreen.myElement.atIndex(0)).toBeVisible();
      27 |   });
      28 |

- [ *] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction

1.  Create multiple components in react native with same identifer
2. Now with Detox test try .whileElement(Perform any action)
3. Notice that the above error is thrown

#### Expected behavior
atIndex(index) should pick the element with provided index and the test should pass

#### Environment (please complete the following information):
 - Detox: 17.14.0
 - React Native: 0.64.1
 - Node:14.17.0
 - Device: iPhone 12 Simulator
 - Xcode: 12.5
 - iOS: 14
 - macOS: 11.1 Big Sur

**Comment by AshrafRizvi01** [comment]
Still having this issue, any update on this?

**Comment by noomorph** [comment]
I'll take a look in an hour or two. Could you please attach logs in --loglevel trace mode?

**Comment by noomorph** [comment]
@AshrafRizvi01 , thanks, I was able to confirm the bug, e.g. the payload tends to be without index:

```
{"type":"invoke","params":{"type":"action","action":"scroll","params":[50,"down",null,null],"predicate":{"type":"id","value":"ScrollView161"},"while":{"type":"expectation","predicate":{"type":"text","value":"Index"},"expectation":"toBeVisible"}},"messageId":3}
```

**Comment by noomorph** [comment]
The fix is on its way.

**Comment by noomorph** [comment]
Will be released in `detox@18.18.1` either tomorrow or on Monday, I think.

**Comment by d4vidi** [comment]
@noomorph thanks for the great job!
@AshrafRizvi01 please revisit this with Detox `18.18.1` and close the issue if it has indeed solved it.

**Comment by AshrafRizvi01** [comment]
Works!
Thank you @noomorph really appreciate the quick fix
Thanks @d4vidi Verified the same on the v18.18.1 and closing it as fixed.

**Comment by finalight** [comment]
the fix doesn't work, at least on the androd counter part

the test still scroll downwards, even though when the element is there after scrolling one time

**Comment by Legion2** [comment]
@noomorph can confirm, that on android with detox v18.20.1 the test scrolls beyond the element and the test fails. Even though the element is visible after the fist scroll action. If the element is visible on the screen without the need to scroll, the test does not fail.
```js
  await waitFor(element(by.id('some-list-item')).atIndex(0))
      .toBeVisible()
      .whileElement(by.id('list'))
      .scroll(100, 'down', NaN, 0.8);
```

```
 Test Failed: 'at least 75 percent of the view's area is displayed to the user.' doesn't match the selected view.
    Expected: at least 75 percent of the view's area is displayed to the user.
```

**Comment by d4vidi** [comment]
@finalight @Legion2 that doesn't sound related. Please provide the necessary details in a separate issue. Thanks.

**Comment by Legion2** [comment]
I created #2931
