### ISSUE TITLE
Android second test always fails with [TELNET_ERROR] connect ECONNREFUSED 127.0.0.1:23

### ISSUE THREAD

**Issue by YeeWong11** [wix/Detox#2847]
### Describe the bug

Android tests on our CI  works if we only run a single test, but when we try to run two tests the second one will always fail with the following error. 

(See attach log for more info)
```
detox[82130] DEBUG: [EMU_BIN_VERSION_DETECT] Detected emulator binary version { major: 30, minor: 6, patch: 5, toString: [Function: toString] }
detox[82130] DEBUG: [ALLOCATE_DEVICE] Trying to allocate a device based on "Pixel_API_28_AOSP"
detox[82130] DEBUG: [EXEC_CMD, #125] "/Users/administrator/.android/sdk/platform-tools/adb"  devices
detox[82130] DEBUG: [EXEC_SUCCESS, #125] List of devices attached
emulator-13150	device
detox[82130] TRACE: [TELNET_CONNECTING] port: 13150, host: localhost
detox[82130] ERROR: [TELNET_ERROR] read ECONNRESET
  err: Error: read ECONNRESET
      at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
detox[82130] ERROR: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
detox[82130] INFO:  Not logged in is assigned to undefined
detox[82130] INFO:  Not logged in: should have login flow
```

### Steps To Reproduce

Push to CI with only one test, works
Push to CI with two tests, second one will always fail with above error

### Detox Trace-Logs
[detox.log](https://github.com/wix/Detox/files/6676593/detox.log)

### Environment (please complete the following information):
 - Detox: 18.16.0
 - React Native: 0.64.2
 - Node: v14.15.4
 - Device: emulator Pixel_API_28_AOSP with test-butler
 - OS: Android
 - Test-runner (select one): `jest-circus`

**Comment by noomorph** [comment]
Last time I remember about this bug, there was that `~/.emulator_console_auth_token` file... 🤔
@d4vidi, do you remember if deleting (or emptying) it helped back then?

**Comment by noomorph** [comment]
Might be related to https://github.com/wix/Detox/issues/2320#issuecomment-724098246

**Comment by YeeWong11** [comment]
Update:

Thanks again @noomorph, we've tried deleting `~/.emulator_console_auth_token` but it didn't help. 

We found a workaround for now by remove the `--cleanup` flag so the emulator doesn't shutdown between tests. It's probably not ideal for the long term but it gets the tests running again. Maybe the cause of the error is within the `cleanup` steps?

Here are some information that might be useful:
- We tried running a script to shut down all emulators between tests suites but that didn't help.
- If we set workers to 2, we can get 2 tests to run and pass, but if we add a third test that would fail just like before.
- This error happens both on CI machine and locally

Closing this thread

**Comment by noomorph** [comment]
@d4vidi remind me to link this issue with a similar one about Android and --cleanup flag error

**Comment by noomorph** [comment]
Related to: https://github.com/wix/Detox/issues/2574.

**Comment by d4vidi** [comment]
Indeed, `--cleanup` seems to be fairly broken on Android. We will have to revisit as a part of our overhaul.

**Comment by francescov1** [comment]
This is still occurring for me, only in CI though.
