### ISSUE TITLE
run same tests on multiple different devices

### ISSUE THREAD

**Issue by finalight** [wix/Detox#2849]
is there a command or a configuration where i can run say, 3 different android devices but with the same test suite?

reason is because different device will show different UI and as such we want to make sure the test cases are able to assert correctly on the different devices

**Comment by noomorph** [comment]
Hi, @finalight!

This is something we definitely would love to have as a feature, but unfortunately, it requires quite a lot of groundwork. Therefore, I cannot give you any ETA.

At the moment you are limited to 2 options:

### Easy one

```
detox test -c android.device1 thatTestSuite
detox test -c android.device2 thatTestSuite
detox test -c android.device3 thatTestSuite
```

Obviously, it is going to take ×3 longer.

### Complicated one

Basically, this is rather a hack than a good solution. It is justified only if parallelism matters that much to you that you agree to maintain such a complexity (especially in the context of Detox and Jest major version upgrades).

You should create two extra test files (e.g. `thatTestSuite.pixel28.test.js`, `thatTestSuite.tablet.test.js`) that import your original test suite, and also add a JSDoc pragma, e.g.:

```js
/**
 * @avd-name Pixel_API_28
 */

require('./thatTestSuite.test.js');
```

and if we imagine you have some `android.emu.release` configuration like this:

```
    "android.emu.release": {
      device: "android.emulator",
      app: "android.release"
    },
```

where the device is:

```
  devices: {
    "android.emulator": {
      type: "android.emulator",
      device: {
        avdName: "Pixel_3A_API_29"
      },
    },
  }
```

what you can do is to hack the environment class like this:

```diff
diff --git a/detox/test/e2e/environment.js b/detox/test/e2e/environment.js
index dceeabb6..30136b4d 100644
--- a/detox/test/e2e/environment.js
+++ b/detox/test/e2e/environment.js
@@ -6,6 +6,8 @@ class CustomDetoxEnvironment extends DetoxCircusEnvironment {
   constructor(config, context) {
     super(config, context);

+    this._avdOverride = context.docblockPragmas['avd-name'];
+
     this.registerListeners({
       SpecReporterCircus,
       WorkerAssignReporterCircus,
@@ -13,13 +15,15 @@ class CustomDetoxEnvironment extends DetoxCircusEnvironment {
   }
+
+   async initDetox() {
+    return this.detox.init({
+      devices: {
+        'android.emulator': {
+          device: {
+            avdName: this._avdOverride,
+          },
+        },
+      },
+    });
   }
 }
```

In other words, in your Environment class, you extract that custom `avd-name` docblock pragma value and programmatically deep merge it inside your regular Detox configuration inside the overridden protected `initDetox` method.

This is the best I can help you with at the moment. Don't take the code fragments for granted, the code is quite simplistic there and just serves the demonstration purpose.
