### ISSUE TITLE
can't add timeout to waitfor when looking for not.toBeVisible

### ISSUE THREAD

**Issue by dbilgin** [wix/Detox#2851]
The documentation states:
`Every waitFor call must set a timeout using withTimeout(). Calling waitFor without setting a timeout will do nothing.`
So I'm a bit confused about this, when I am calling `waitFor(element(by.id(elementId))).not.toBeVisible()` I can't actually set a timeout using `withTimeout`. Was this intentional if so is there a reason?
I think we used to have this feature before `toBeNotVisible` got deprecated, wouldn't it be good to have the timeout option again?

**Comment by noomorph** [comment]
@dbilgin, could you elaborate, please? I am not sure I understand the question.

In our E2E self-test suite we have the exact situation you are asking about:

https://github.com/wix/Detox/blob/master/detox/test/e2e/05.waitfor.test.js#L23

```js
await waitFor(element(by.id('deletedFromHierarchyText'))).not.toBeVisible().withTimeout(timeout);
```

...and it passes for both iOS and Android. So, again, what's the problem?

Thanks in advance.

**Comment by dbilgin** [comment]
Hi, thanks for the response @noomorph,
I think I might have missed this test suite, I guess this functionality exists after all. Could it be that the types are missing for this? I was using typescript and I cannot actually call `withTimeout` with the type check.

**Comment by dbilgin** [comment]
I get the error `Property 'withTimeout' does not exist on type 'Promise<void>'.`

**Comment by noomorph** [comment]
Oh, I reckon it must be a TypeScript definition error then. Thanks for
reporting it! I can take that on Tuesday. Hope this is fine with you.

**Comment by dbilgin** [comment]
@noomorph thanks! totally fine with me, in the meantime I created this PR maybe I can save you the trouble:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53939
I'm not sure if it's the correct way to change it, but it worked in my code.

**Comment by noomorph** [comment]
@dbilgin, we don't support the external typings. Could you please check whether you have this problem without them? Detox ships its own typings. If the issue is still there, could you make a PR to our repo in that case?

**Comment by dbilgin** [comment]
@noomorph oh apologies I was not aware of this, did the typings move to internal support recently? If so could you direct me to that version of detox?

**Comment by noomorph** [comment]
Since 18.x, in Dec 2020. Just move to the latest 18.18.0 and check if it is
ok now.

**Comment by dbilgin** [comment]
yeah it seems to be working just fine now, thank you for your time @noomorph
