### ISSUE TITLE
Ability to NOT pass --maxWorkers to Jest

### ISSUE THREAD

**Issue by cdavie-weconnect** [wix/Detox#2862]
**Is your feature request related to a problem? Please describe.**
I want to be able to use Jest's `--runInBand` option. However, that option is [incompatible](https://github.com/facebook/jest/blob/bdd6282c288e58a16f6d2c79b0d2dec80e07f1de/packages/jest-cli/src/cli/args.ts#L14) with passing `--maxWorkers` to Jest — even though `--maxWorkers` will [default to 1](https://github.com/facebook/jest/blob/bc50e7f360ab1845abbaa0b3ad788caead0d3174/packages/jest-config/src/getMaxWorkers.ts#L17) when you do pass in `--runInBand`. ¯\\\_(ツ)\_/¯

**Describe the solution you'd like**
Something like `--workers 0` or `--no-workers` to disable passing `--maxWorkers` to Jest at all.

**Additional context**
I am happy to submit a PR, if that would be welcome!

**Comment by noomorph** [comment]
Is there any technical difference between --runInBand and --maxWorkers 1,
Catherine?

**Comment by cdavie-weconnect** [comment]
@noomorph Thanks for the quick reply!

As far as I can tell, there is no technical difference, especially because Jest will set `maxWorkers` to `1` when you use `--runInBand`.

Unfortunately, Jest does not _allow_ you to specify both `--runInBand` and `--maxWorkers=1` at the same time, even though that's exactly what Jest will do behind the scenes for you. If you try to pass both those options together, Jest exits early. So it's a frustrating limitation of Jest, but at least Detox can work around it by not letting the user control whether `--maxWorkers` will be sent to Jest.

**Comment by noomorph** [comment]
Nobody actively requested it, to be honest. Probably, you are the first or the second, at most.

Well, I can try to look into it quite soon, next week probably... 🤔 I might sneak it to a pull request when I'll be adding `maxWorkers` support into `.detoxrc` (JS/JSON config).

**Comment by cdavie-weconnect** [comment]
I've submitted a pull request at https://github.com/wix/Detox/pull/2863 (based on the `patch-package` changes that I've been using locally in my own project). Let me know if I can make any changes so that it's easier for you to review or accept!

**Comment by d4vidi** [comment]
@cdavie-weconnect please see my [answer on SO](https://stackoverflow.com/a/66669155/453052) regarding the differences between no-workers and `--runInBand`. I'm inclined to say we shouldn't support that in Detox.
May I ask what is the motivation for having this?

**Comment by cdavie-weconnect** [comment]
@d4vidi I want to use `--detectOpenHandles`, and per https://github.com/facebook/jest/issues/9473#issuecomment-579195412, I should use `--runInBand` with it:

> `--detectOpenHandles` without `--runInBand` does not really make sense (unless your tests are already being run in band anyway), since you will be detecting open handles in the main process, while your tests are running in child processes.

**Comment by noomorph** [comment]
I started my work on the alternative implementation of this feature: https://github.com/wix/Detox/pull/2872 .

After considering many options, I realized that we DON'T NEED to pass `--maxWorkers` **at all**.

That's just silly and redundant — both Mocha and Jest have an option to set max worker count in their config files.
In fact, refraining from passing that CLI argument makes us able to start using it programmatically, e.g.:

```
  maxWorkers: process.env.CI ? 3 : 1
```

Thanks a lot for raising this question and going an extra mile with your solution — that made me question the efficiency of the current implementation.

**Comment by d4vidi** [comment]
@noomorph could you please elaborate? Are you suggesting we should _never_ pass `--maxWorkers`, and strictly use the configuration?

**Comment by noomorph** [comment]
@d4vidi, exactly. I came to a conclusion that this was a design mistake — we never actually needed it. All that we had to do is to specify `maxWorkers: 1` in `jest.config.js` and allow passing through its native options `-w, --maxWorkers <N>`, and that's it.

I'd like to deprecate `-w, --workers` in Detox for 19th release.

**Comment by noomorph** [comment]
@cdavie-weconnect , I hope to land the PR tomorrow.

**Comment by noomorph** [comment]
Implemented in [18.19.0](https://github.com/wix/Detox/releases/tag/18.19.0).

@cdavie-weconnect, to solve your issue use the new default values for `skipLegacyWorkersInjection` and `maxWorkers` as described here: https://github.com/wix/Detox/pull/2872
