### ISSUE TITLE
Detox hangs and timeout on iOS Debug

### ISSUE THREAD

**Issue by kanelloc** [wix/Detox#2864]
### Description
Detox hangs and timeout after 12000ms

#### Reproduction

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

1.  detox build -c ios  
2. detox test -c ios --loglevel verbose

#### Screenshots
<img width="1123" alt="Screenshot 2021-06-26 at 12 02 52 PM" src="https://user-images.githubusercontent.com/17724315/123508189-88878580-d676-11eb-922c-626d3e428ef0.png">

#### Environment (please complete the following information):
 - Detox: 18.18.1
 - React Native: 0.63.2
 - Node: 12.13.0
 - Device: 12 pro max
 - Xcode: 12.5
 - iOS: 14.5
 - macOS:  11.2.3

#### Device and verbose Detox logs

detox[17639] WARN:  [PENDING_REQUESTS] The app has not responded to the network requests below:
  (id = -1000) reactNativeReload: {}

**Comment by d4vidi** [comment]
@kanelloc could you please rerun using `--loglevel trace` and `--record-logs all` and attach everything that's been generated under the `artifacts/` directory?

**Comment by kanelloc** [comment]
[ios.2021-06-27 11-21-41Z.zip](https://github.com/wix/Detox/files/6731577/ios.2021-06-27.11-21-41Z.zip)
@d4vidi Thank you

**Comment by alon-ha** [comment]
Hi @kanelloc, can you please fork the [DetoxTemplate](https://github.com/wix-incubator/DetoxTemplate) project and add a senario/test which reproduce the problem?
I can't really help here without an example I can debug

**Comment by kanelloc** [comment]
@alon-ha after your suggestion I debugged the project and everything worked fine.
Thanks
