### ISSUE TITLE
Introduce longpress(duration) for android

### ISSUE THREAD

**Issue by DmitrievAlexander** [wix/Detox#2865]
**Is your feature request related to a problem? Please describe.**
in our app we have a technical page which is opened by longpressing an element for 4000 ms

**Describe the solution you'd like**
would like to have the same behavior for longpress(duration) as for ios

**Comment by DmitrievAlexander** [comment]
still relevant

**Comment by d4vidi** [comment]
@DmitrievAlexander duration for Android sounds rather off the standard. How do you even apply a "very" long press callback? In any case, I've applied contribution label - hoping it would be picked up by the community. If I may - you might want to consider applying this yourself; It shouldn't be too difficult to set up.
