### ISSUE TITLE
`device.launchApp` doesn't always send `launchArgs` to the app

### ISSUE THREAD

**Issue by hamidhadi** [wix/Detox#2866]
### Description
I'm using `device.launchApp` to pass launch arguments to the app. I can get those arguments for the first time of running the app but during my test cases, whenever I launch the app again, those arguments will be `null`.

👇 Haven't tried but couldn't find any changes related to this bug after `v18.14.1`
 [ ] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction
```javascript

describe('My root describe', () => {
    beforeAll(async () => {
         await device.launchApp({ launchArgs: { myArgument: 'test' } })
    })

    describe('Child describe', () => {
         it('does something', async () => {
              // Do somthing in the app
              // Can see the `myArgument`
              // assert something
              
              await device.launchApp({
                    url: "some-url",
                    newInstance: true,
                    launchArgs:  { myArgument: 'test' }
               })

               // Can't get the `myArgument` anymore 😕
         })
    })
})

```

#### Expected behavior
I should be able to get the launch arguments whenever I run the app with `launchArgs`.

#### Environment (please complete the following information):
 - Detox: `18.14.1`
 - React Native: `0.64.1`
 - Node: `15.5.1`
 - Device: `iPhone 11 Pro simulator` 
 - Xcode: `12.5`
 - iOS: `14.5`
 - macOS: `11.2.2`

**Comment by alon-ha** [comment]
@noomorph Can you check the JS side?

**Comment by noomorph** [comment]
I'll check tomorrow.

**Comment by noomorph** [comment]
Had no time yesterday, I'll try to get back on Monday.

**Comment by noomorph** [comment]
@hamidhadi, unfortunately, your bug report is not sufficient. I can't reproduce it:

```js
      await device.terminateApp();
      await device.launchApp({ launchArgs: { myArgument: 'test' } });
      await device.launchApp({
        url: 'detoxtesturlscheme://such-string',
        newInstance: true,
        launchArgs:  { myArgument: 'test' }
      });
```

gets me:

```
...
SIMCTL_CHILD_DYLD_INSERT_LIBRARIES="/Users/yaroslavs/Library/Detox/ios/c75937759163e597fd8e711f4864b0417de0c8c1/Detox.framework/Detox" /usr/bin/xcrun simctl launch 6371830E-8B44-422B-A52C-DB0B62E6B6E3 com.wix.detox-example --args -detoxServer ws://localhost:62910 -detoxSessionId ab589d7e-188c-6f2a-b684-61627e3529d3 -myArgument test -detoxDebugVisibility YES
...
SIMCTL_CHILD_DYLD_INSERT_LIBRARIES="/Users/yaroslavs/Library/Detox/ios/c75937759163e597fd8e711f4864b0417de0c8c1/Detox.framework/Detox" /usr/bin/xcrun simctl launch 6371830E-8B44-422B-A52C-DB0B62E6B6E3 com.wix.detox-example --args -detoxServer ws://localhost:62910 -detoxSessionId ab589d7e-188c-6f2a-b684-61627e3529d3 -myArgument test -detoxURLOverride detoxtesturlscheme://such-string -detoxDebugVisibility YES
...
```

and I can see `-myArgument test` included in both cases.

Please find out what you have missed in your bug report and get back to us.
