### ISSUE TITLE
testNamePattern set with single quotes on git bash instead of double quotes

### ISSUE THREAD

**Issue by gabriel11447** [wix/Detox#2868]
### Describe the bug
By running the command `yarn detox test -c android.emu.debug` on a git bash terminal, we noticed that the configuration [INFO] log, shows the flag testNamePattern defined as `'^((?!:ios:).)*$'` (notice the single quotes).

![image](https://user-images.githubusercontent.com/37315220/123999045-783e1600-d9a8-11eb-8214-778ce836f384.png)

Note: the last line is in pt-BR, it means: `.)*$' was unexpected at the moment.`

Running the same command in PowerShell, for example, sets the flag with double quotes  `"^((?!:ios:).)*$"`, and it runs correctly.

![image](https://user-images.githubusercontent.com/37315220/123999361-d10dae80-d9a8-11eb-98d3-e0c5108d56b1.png)

Even running the command, forcing double quotes, git bash returns:

![image](https://user-images.githubusercontent.com/37315220/124001424-ff8c8900-d9aa-11eb-986d-2c3a4c4d8f7b.png)

### Steps To Reproduce

- [x] I have tested this issue on the latest Detox release and it still reproduces

1. Start a react native project (CRA)
2. Add Detox v18.18.1 (following the installation guide)
3. Configure `.detoxrc.json` as:
```
{
  "testRunner": "jest",
  "runnerConfig": "e2e/config.json",
  "configurations": {
    "android.emu.debug": {
      "type": "android.emulator",
      "binaryPath": "android/app/build/outputs/apk/debug/app-debug.apk",
      "build": "cd android && gradlew assembleDebug assembleAndroiTest -DtestBuildType=debug && cd ..",
      "device": {
        "avdName": "Pixel_4_XL_API_30"
      }
    }
  }
}
```
4. Open git bash terminal
5. Run `yarn detox test -c android.emu.debug`

### Expected behavior
It is expected that the script runs independently of the terminal that's being used.

### Detox Trace-Logs

![image](https://user-images.githubusercontent.com/37315220/124000040-8d677480-d9a9-11eb-963b-c2adb03befd1.png)

### Environment:
 - Detox: 18.18.1
 - React Native: 0.64.0
 - Node: 14.17.1
 - Device: Android Emulator Pixel 4 XL (API 30)
 - OS: Android / Windows
 - Test-runner: `jest-circus`

**Comment by noomorph** [comment]
The bug report is correct, but at the moment I am a bit busy with other tasks. Could you also muse about a possible solution?

If I remember right, there's a $SHELL variable that can help to distinguish between mingw's bash and CMD.exe, when `process.platform === 'win32'`. I can't understand why this logic is broken in your Windows environment. 

Could you debug this function (at least, with some console.log() calls):

https://github.com/wix/Detox/blob/a4b370e3d2dd75942453d66cf264596c0abd3e7b/detox/src/utils/shellUtils.js#L24

?

Let me know what you find for your shells: PowerShell, CMD, Git bash.

**Comment by kaminskypavel** [comment]
@noomorph yeah can confirm this is happening when I run on ***git bash*** (vscode integrated terminal) in ***windows*** .
but if I run form cmd it works fine
