### ISSUE TITLE
Detox testing with Facebook Login

### ISSUE THREAD

**Issue by calclavia** [wix/detox#287]
I've an app that requires Facebook login in order to work. During the login process a dialog from Facebook pops up and the tester should enter in a test account to be used for the test. Is there any way for Detox to interact with this dialog? Using `by.text` does not seem to allow me to interact with the popup (which seems to be running in Safari and redirects back to the app upon successful login).

**Comment by LeoNatan** [comment]
Safari view controller is not supported. This is a limitation of Earl Grey, the framework we use internally to drive the automation. 

Instead, mock the FB API to return a valid session without the actual login process.

**Comment by davidpaulsson** [comment]
If someone wants some SO reputation 😅 https://stackoverflow.com/questions/46777138/how-to-mock-facebook-login-using-react-native-detox
