### ISSUE TITLE
Hangs when typing text to an element

### ISSUE THREAD

**Issue by sondremare** [wix/detox#288]
#### Description

Using detox version 5.6.2 with react-native 0.42.3

Trying to type text into an input field (RN's TextInput) but it hangs forever.
Here is my helper method:
```

this.elements = {
      contactListItem: element(by.id(this.contactListItemId)),
      messageInput: element(by.label(this.messageInputFieldLabel)),
      searchUserInput: element(by.id(this.searchUserInputId)),
      sendMessageButton: element(by.id(this.sendButtonId)),
};

async searchForUser(name: string) {
    console.log('expecting visibility');
    await expect(this.elements.searchUserInput).toBeVisible();
    console.log('going to tap input');
    await this.elements.searchUserInput.tap();
    console.log('tapped element, going to search for', name);
    await this.elements.searchUserInput.typeText(name);
    console.log('done typing');
  }
```

The thing is, the expectation for visibility passes, and the tap-action goes well, because the keyboard comes up. But for some reason when it comes down to typing, it just hangs.
I have successfully done this for other input fields in the app (expect visibility, tap, type).

Any suggestions on how I can proceed to debug this issue?

* Node: 8.5.0
* Device: IPhone 7 Simulator
* Xcode: 8.3
* macOS: 10.12.6

**Comment by rotemmiz** [comment]
Try https://github.com/wix/detox/blob/master/docs/Troubleshooting.Synchronization.md#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much

**Comment by sondremare** [comment]
Thanks! Now I have something to work on. Animations and a heartbeat / pinging service that might be causing issues
