### ISSUE TITLE
How to skip the visible check?

### ISSUE THREAD

**Issue by cpdyj** [wix/Detox#2880]
Sometimes I need tap or typeText in an invisible Element, but I read all the document, I found nothing about how to do it.
For example, looks Detox doesn't support Webview now. So I try to resolve problem by https://stackoverflow.com/a/52123744/7121473
In another scenes, my application has some component with bad accessbility. But I have no chance to fix it. 

Thank you for your help

**Comment by d4vidi** [comment]
@cpdyj please rephrase your questions - they are no quite clear, and therefore we cannot provide help in an efficient way.
In any case, support for Webviews has been released back in [Detox 18.7.0](https://github.com/wix/Detox/releases/tag/18.7.0), you might want to revisit that.
