### ISSUE TITLE
Detox tests get stuck after running few times and needs restart of system(Big Sur 11.0.1,MacBook Air (M1, 2020))

### ISSUE THREAD

**Issue by QureshiFaizan** [wix/Detox#2885]
### Description
detox test --c ios --reuse Test1.e2e.js
After running test cases for a few times with above command
test cases get stuck at 

**Determining test suites to run...** 
**RUNS  e2e/News_Test.e2e.js** 

until system is restarted.

- [ ] I have tested this issue on the latest Detox release and it still reproduces

![image_2021_07_09T08_51_20_674Z](https://user-images.githubusercontent.com/30919201/125052147-47a15f00-e0c1-11eb-9112-29b74c35c99f.png)

#### Environment (please complete the following information):
Detox: 18.18.1
React Native: 0.63.3
Node: 14.15.4
Device: iPhone 11 Simulator
Xcode: 12.3
iOS: 14.3
macOS: Big Sur 11.0.1 MacBook Air (M1, 2020)

**Comment by noomorph** [comment]
Send the output with `--loglevel trace`, please.

**Comment by QureshiFaizan** [comment]
> Send the output with `--loglevel trace`, please.

Please find below output with --loglevel trace

Qureshis-MacBook-Air:TradingAppBetaRelease qureshi$ detox test --c ios --loglevel trace
detox[4720] INFO:  [test.js] DETOX_CONFIGURATION="ios" DETOX_LOGLEVEL="trace" DETOX_REPORT_SPECS=true DETOX_START_TIMESTAMP=1626065798036 DETOX_USE_CUSTOM_LOGGER=true jest --config e2e/config.json --testNamePattern '^((?!:android:).)*$' --maxWorkers 1 e2e
detox[4721] TRACE: [DETOX_CREATE] created a Detox instance with config:
{"artifactsConfig":{"rootDir":"artifacts/ios.2021-07-12 04-56-38Z","plugins":{"log":{"enabled":false,"keepOnlyFailedTestsArtifacts":false},"screenshot":{"enabled":true,"shouldTakeAutomaticSnapshots":false,"keepOnlyFailedTestsArtifacts":false},"video":{"enabled":false,"keepOnlyFailedTestsArtifacts":false},"instruments":{"enabled":false,"keepOnlyFailedTestsArtifacts":false},"timeline":{"enabled":false},"uiHierarchy":{"enabled":false,"keepOnlyFailedTestsArtifacts":false}},"pathBuilder":{"_rootDir":"artifacts/ios.2021-07-12 04-56-38Z"}},"appsConfig":{"default":{"type":"ios.app","binaryPath":"/Users/qureshi/Library/Developer/Xcode/DerivedData/RNTradingApp-cyyjhhtoxrthzmafydgnhvywnarp/Build/Products/Debug-iphonesimulator/Touch 2.0 Beta.app"}},"behaviorConfig":{"init":{"reinstallApp":true,"exposeGlobals":true},"cleanup":{"shutdownDevice":false},"launchApp":"auto"},"cliConfig":{"configuration":"ios","loglevel":"trace","useCustomLogger":"true"},"deviceConfig":{"type":"ios.simulator","device":{"type":"iPhone 11"}},"runnerConfig":{"testRunner":"jest","runnerConfig":"e2e/config.json","specs":"e2e"},"sessionConfig":{"autoStart":true,"server":"ws://localhost:50860","sessionId":"4195d630-c972-0829-de95-9bad7084843e","debugSynchronization":10000},"errorComposer":{"configurationName":"ios","filepath":"/Users/qureshi/Workspace/TradingAppBetaRelease/.detoxrc.json","contents":{"testRunner":"jest","runnerConfig":"e2e/config.json","apps":{"ios":{"type":"ios.app","binaryPath":"/Users/qureshi/Library/Developer/Xcode/DerivedData/RNTradingApp-cyyjhhtoxrthzmafydgnhvywnarp/Build/Products/Debug-iphonesimulator/Touch 2.0 Beta.app"},"android.debug":{"type":"android.apk","binaryPath":"android/app/build/outputs/apk/debug/app-debug.apk","build":"cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && cd .."},"android.release":{"type":"android.apk","binaryPath":"android/app/build/outputs/apk/debug/app-debug.apk","testBinaryPath":"android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk"}},"devices":{"simulator":{"type":"ios.simulator","device":{"type":"iPhone 11"}},"emulator":{"type":"android.emulator","device":{"avdName":"Pixel_3a_API_30"}}},"configurations":{"ios":{"device":"simulator","app":"ios"},"android.emu.release":{"device":"emulator","app":"android.release"},"android.emu.debug":{"device":"emulator","app":"android.debug","artifacts":{"rootDir":"/Users/tradebulls/Desktop/ScreenShots","plugins":{"instruments":"manual"}}}}},"_extends":false}}
detox[4721] DEBUG: [WSS_CREATE] Detox server listening on localhost:50860...
detox[4721] DEBUG: [WSS_CONNECTION, #50861] registered a new connection.
detox[4721] TRACE: [WS_OPEN] opened web socket to: ws://localhost:50860
detox[4721] TRACE: [WS_SEND] {"type":"login","params":{"sessionId":"4195d630-c972-0829-de95-9bad7084843e","role":"tester"},"messageId":0}
detox[4721] TRACE: [WSS_GET_FROM, #50861] {"type":"login","params":{"sessionId":"4195d630-c972-0829-de95-9bad7084843e","role":"tester"},"messageId":0}
detox[4721] TRACE: [SESSION_CREATED] created session 4195d630-c972-0829-de95-9bad7084843e
detox[4721] TRACE: [WSS_SEND_TO, #tester] {"type":"loginSuccess","params":{"testerConnected":true,"appConnected":false},"messageId":0}
detox[4721] TRACE: [SESSION_JOINED] tester joined session 4195d630-c972-0829-de95-9bad7084843e
detox[4721] TRACE: [WS_MESSAGE] {"type":"loginSuccess","params":{"testerConnected":true,"appConnected":false},"messageId":0}
 
detox[4721] DEBUG: [EXEC_CMD, #0] applesimutils --list --byType "iPhone 11"

 RUNS  e2e/EQ_Order_Reports_Test.e2e.js

**Comment by noomorph** [comment]
Check if this command hangs up in Terminal:

```
applesimutils --list --byType "iPhone 11"
```

**Comment by QureshiFaizan** [comment]
> Check if this command hangs up in Terminal:
> 
> ```
> applesimutils --list --byType "iPhone 11"
> ```

If 'detox test --c ios' works properly then above command also works properly.
But when 'detox test --c ios' gets stuck then above command also gets stuck.

**Comment by noomorph** [comment]
Interesting, @alon-ha — any ideas on how we can debug further? Maybe, `applesimutils` has some inner logs, 🤷 ?

**Comment by QureshiFaizan** [comment]
@alon-ha and @noomorph any suggestion on how we can fix this?

**Comment by alon-ha** [comment]
Sorry @QureshiFaizan I didn't get to this yet, hopefully next week

**Comment by QureshiFaizan** [comment]
@alon-ha and @noomorph  did we find anything on this?

**Comment by d4vidi** [comment]
@QureshiFaizan we now have an M1 MacBook Pro where we can test this, I hope we'd have insights soon.
@alon-ha regardless, could you double check for a debug/verbose mode in apple-sim-utils?

**Comment by alon-ha** [comment]
I'll have to wait and test on the new M1, didn't find any insights with `applesimutils`
Tested on Big Sur 11.4, iOS 14.3 as well but MacBook Pro 2018

**Comment by QureshiFaizan** [comment]
@alon-ha and @d4vidi did we get anything on this?

**Comment by d4vidi** [comment]
@QureshiFaizan we currently have limited ability to examine this, in part, due to covid restrictions and also we're basically (mostly) out for holidays.
In the meantime - and this might be an odd request, but given the situation and all: would you consider running some "monkey" tests over `applesimutils` to see whether it hangs regardless of Detox?
namely, things like:
1. listing the simulators
2. repeatedly launching and shutting various simulators down

If `applesimutils` fails, at least we'll know the problem is there. It would help a great deal when we finally get to test this out.

**Comment by QureshiFaizan** [comment]
@d4vidi I will definitely try the same and will come back

**Comment by JordanBrion** [comment]
I got the same issue. I just noticed that another process was using the same port number. Stopping it solved the problem.
