### ISSUE TITLE
Github Actions test failing: `No elements found for “MATCHER(text == “Screen 1”)”`

### ISSUE THREAD

**Issue by rawatnaresh** [wix/Detox#2889]
I'm trying to run test cases in Github actions but they are failing:

![Screen Shot 2021-07-12 at 20 21 16](https://user-images.githubusercontent.com/29520305/125306456-f5756d80-e34e-11eb-97cc-3baec34b9d62.png)

Here's the log from github action https://github.com/rawatnaresh/detox-test/runs/3047245023

Here's my detox configuration https://github.com/rawatnaresh/detox-test/commit/167da17e316e6aaf5e421cd8af79fb2c66c877c3

Test cases are passing locally though

**Comment by d4vidi** [comment]
Closing as a dup of #2873.
