### ISSUE TITLE
`device.launchApp({newInstance: true, url: url})` doesn't work properly if `url` contains `&`

### ISSUE THREAD

**Issue by erezrokah** [wix/detox#289]
#### Description:
`device.launchApp({newInstance: true, url: url})` doesn't work properly if `url` contains `&`.

It looks like the `detoxURLOverride` argument is not serialized correctly.

#### Steps to Reproduce:
Run the deep links e2e tests from this repository:
https://github.com/rmrs/detox/tree/escaping_bug

The first 3 tests should pass while the last one should fail.
In the app you'll notice the link is opened but is missing everything after the `&`.

e.g. `detoxtesturlscheme://such-string?foo=1&bar=2` shows up as `detoxtesturlscheme://such-string?foo=1`

A workaround is to send the following link:
`detoxtesturlscheme://such-string?foo=1\\&bar=2`

Notice it only happens with the `newInstance: true` variant.

#### Node, Device, Xcode and macOS Versions:

* Node: v8.5.0
* Device: iOS Simulator iPhone 7 Plus
* Xcode: 9.0
* macOS: Sierra 10.12.6

Unrelated, but I've also noticed a redundant function call in this file:
https://github.com/wix/detox/blob/master/detox/src/devices/Device.js

On line 79, this call `this._addPrefixToDefaultLaunchArgs(baseLaunchArgs)` seems to be redundant as the return value is never used and the function doesn't mutate the argument.

**Comment by LeoNatan** [comment]
Thanks, this is a bug and we need to address this. @rotemmiz

**Comment by rotemmiz** [comment]
From verbose logging I noticed that the URL is being passed correctly through launchArgs to the simulator. Could this be a native issue ?
I'll test it tomorrow on both platforms.

@erezrokah, every DeviceDriver has its own prefix mutation. In your case (iOS Simulator) there is no mutation, but on Android it uses different prefix (https://github.com/wix/detox/blob/master/detox/src/devices/EmulatorDriver.js#L122)

**Comment by bhb** [comment]
I'm still running into this with version 7.3.7
