### ISSUE TITLE
Prevent or warn when `node_modules/.bin/jest` in fact is not a Jest or an outdated Jest

### ISSUE THREAD

**Issue by noomorph** [wix/Detox#2898]
**Is your feature request related to a problem? Please describe.**

The feature should prevent issues like these: https://github.com/wix/Detox/issues/2869

**Describe the solution you'd like**

Detox should probe the binary and try to understand if it points to an outdated Jest version or something that pretends to be Jest.

**Describe alternatives you've considered**

Relax and do nothing about that. 🤷 

**Additional context**

See https://github.com/wix/Detox/issues/2869 and the discussion.

**Comment by d4vidi** [comment]
Kudos @noomorph. Also, we really ought to improve the "I need help" issue template such it would ask for env info - the same way we do so with bug submissions.

**Comment by noomorph** [comment]
Ahem... not sure. I remember why I created the issue. It was due to Expo monkey-patching Jest. I don't think it is properly resolved.

**Comment by noomorph** [comment]
Since there's not many requests for this, I'll leave it closed.
