### ISSUE TITLE
Android 12 and Java 11

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#2899]
## Description

Need to validate compliance with the upcoming release of Android 12

**Comment by mikehardy** [comment]
Testing on Android 12 today and while I needed to manually set up the adb reverse to hit the bundler (unexpected, maybe not Detox' problem - `adb reverse tcp:8081 tcp:8081`) everything in the react-native-firebase e2e tests appeared to pass with Detox current-as-of-now - v18.20.4

Note that we are not doing anything fancy with regard to artifacts and dialogs and permissions and such, but it does at least run, vs ios15 which is currently a crash-on-startup per #2895

**Comment by d4vidi** [comment]
Thanks @mikehardy, that's great input.

**Comment by mikehardy** [comment]
If you just need to bump your app to targetSdkVersion 31, this diff will work as a patch file named `patches/detox+18.23.1.patch` in your apps for [patch-package](https://github.com/ds300/patch-package), proposed in #3055 and in use now in react-native-firebase's e2e test harness

```
diff --git a/node_modules/detox/android/detox/build.gradle b/node_modules/detox/android/detox/build.gradle
index 8bef864..3689459 100644
--- a/node_modules/detox/android/detox/build.gradle
+++ b/node_modules/detox/android/detox/build.gradle
@@ -86,12 +86,12 @@ dependencies {
     // Versions are in-sync with the 'androidx-test-1.2.0' release/tag of the android-test github repo,
     // used by the Detox generator. See https://github.com/android/android-test/releases/tag/androidx-test-1.2.0
     // Important: Should remain so when generator tag is replaced!
-    api('androidx.test.espresso:espresso-core:3.3.0') { // Needed all across Detox but also makes Espresso seamlessly provided to Detox users with hybrid apps/E2E-tests.
+    api('androidx.test.espresso:espresso-core:3.4.0') { // Needed all across Detox but also makes Espresso seamlessly provided to Detox users with hybrid apps/E2E-tests.
         exclude group: 'com.google.code.findbugs', module: 'jsr305'
     }
-    api 'androidx.test.espresso:espresso-web:3.3.0' // Web-View testing
-    api 'androidx.test:rules:1.2.0' // Needed because of ActivityTestRule. Needed by users *and* internally used by Detox.
-    api 'androidx.test.ext:junit:1.1.1' // Needed so as to seamlessly provide AndroidJUnit4 to Detox users. Depends on junit core.
+    api 'androidx.test.espresso:espresso-web:3.4.0' // Web-View testing
+    api 'androidx.test:rules:1.4.0' // Needed because of ActivityTestRule. Needed by users *and* internally used by Detox.
+    api 'androidx.test.ext:junit:1.1.3' // Needed so as to seamlessly provide AndroidJUnit4 to Detox users. Depends on junit core.
 
     // Version is the latest; Cannot sync with the Github repo (e.g. android/android-test) because the androidx
     // packaging version of associated classes is simply not there...
```

**Comment by mikehardy** [comment]
If you open your android project in AndroidStudio and load the AndroidManifest.xml file, you should have a tab near the bottom that says "Merged Manifest", it is the result of AndroidStudio reading your manifest and all libraries etc manifests and combining them all in to what the system will see at the end.

In that window, you should be able to scan through and investigate to find whichever one is not setting exported correctly

**Comment by d4vidi** [comment]
Currently, the only known _Detox_ issue is this: #3560

**Comment by CallumHemsley** [comment]
> detox+18.23.1.patch

I have ensured that they are all being exported correctly now, but still have the same issue as @sergiulucaci :(

**Comment by CallumHemsley** [comment]
> If you open your android project in AndroidStudio and load the AndroidManifest.xml file, you should have a tab near the bottom that says "Merged Manifest", it is the result of AndroidStudio reading your manifest and all libraries etc manifests and combining them all in to what the system will see at the end.
> 
> In that window, you should be able to scan through and investigate to find whichever one is not setting exported correctly

I have ensured that they are all being exported correctly now, but still have the same issue as @sergiulucaci :(

**Comment by sergiulucaci** [comment]
@CallumHemsley what I recommend is to make sure you have it set up correctly. 

What I was missing was this:

> In your root buildscript (i.e. android/build.gradle), register both google() and detox as repository lookup points in all projects:

```
// Note: add the 'allproject' section if it doesn’t exist
allprojects {
    repositories {
        // ...
        google()
        maven {
            // All of Detox' artifacts are provided via the npm module
            url "$rootDir/../node_modules/detox/Detox-android"
        }
    }
}
```
