### ISSUE TITLE
Element Can't Find/Can't perform Action

### ISSUE THREAD

**Issue by rengarima** [wix/detox#290]
#### Description
Need help for: 

1. Finding Element and Typing text - typeText fails but replaceText work
      element. typeText fails with Error: "Description" : "Failed to type string 'FN', because keyboard was not shown on screen.",
        I am not sure how to get keyboard to appear consistently

2. DatePicker test - Any sample available, mine keeps failing. this could be due to test ID error

3. What's the easiest way to debug element's attribute that detox picks up?

#### Steps to Reproduce
    await expect(element(by.id('payer.name.first.text'))).toExist();
    await element(by.id('payer.name.first.text')).tap();
    await element(by.id('payer.name.first.text')).clearText();
    await element(by.id('payer.name.first.text')).typeText('FN'); 

 code fails to typeText

Sep 22 16:31:44 Garimas-MacBook-Pro workbench[56994]: ☣️ DETOX:: Test Failed:
	An action failed. Please refer to the error trace below.
	Exception with Action: {
	  "Action Name" : "Type 'FN'",
	  "Element Matcher" : "(((respondsToSelector(accessibilityIdentifier) && accessibilityID('payer.name.first.text')) && !(kindOfClass('RCTScrollView'))) || (kindOfClass('UIScrollView') && ((kindOfClass('UIView') || respondsToSelector(accessibilityContainer)) && ancestorThatMatches(((respondsToSelector(accessibilityIdentifier) && accessibilityID('payer.name.first.text')) && kindOfClass('RCTScrollView'))))))"
	}
	
	Error Trace: [
	  {
	    "Description" : "Failed to type string 'FN', because keyboard was not shown on screen.",
	    "Error Domain" : "com.google.earlgrey.ElementInteractionErrorDomain",
	    "Error Code" : "2",
	    "File Name" : "GREYKeyboard.m",
	    "Function Name" : "+[GREYKeyboard typeString:inFirstResponder:error:]",
	    "Line" : "172"
	  }
	]

This is from the debug log --
|  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |--<RCTTextField:0x7fc15ff35030; AX=Y; AX.id='payer.name.first.text'; AX.frame={{51, 335}, {1024, 36}}; AX.activationPoint={563, 353}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {1024, 36}}; opaque; alpha=1; text=''>

#### Node, Device, Xcode and macOS Versions

* Node: 8.4.0
* Device: "iPad Air 2, iOS 10.3"
* Xcode: 9.0  
* macOS: 10.12.6

**Comment by LeoNatan** [comment]
Earl Grey is very picky with keyboards.
Please check the following for me: If you run your project normally on iOS simulator, and tap a text field, does the software keyboard show in the simulator? What language does the keyboard appear on?

**Comment by rengarima** [comment]
It does if I start the simulator directly, but it's a hit and miss if detox is starting the simulator - for the time being I am using replaceText but would like to make use of typeText. Is there a way to make simulator always use software keyboard - something like device.setKeyboard("software")?

Any clarity on DatePicker test - Will there be a release for exposing EarlGrey's  actionForSetDate  or is there a work around?

**Comment by rengarima** [comment]
So after all the updates and combing through issues I still havent managed to work it consistently

Is there a way for device to enable toggle software keyboard? TypeText (in English ) is still flaky. 

On a sidenote, it works consistently if simulator is working in background ( not visible). I am not sure why simulator doesn't start

**Comment by rengarima** [comment]
I have figured out work-around for some of thses

**Comment by markhu** [comment]
What was your work-around? I found `replaceText` at https://stackoverflow.com/questions/47536361/typetext-stops-the-detox-thread works a little better sometimes.
