### ISSUE TITLE
What do these messages mean?

### ISSUE THREAD

**Issue by sta-vanger** [wix/Detox#2902]
Hi Detox Team,

I tried running my detox test again and it looks like it's hanging on a specific test case. 
I do see some logs in the command line. Can you please advise what these logs mean?

Run Loop
⏱ “Main Run Loop”
detox[8582] INFO:  [actions.js] The system is busy with the following tasks:

Dispatch Queue
**⏱ Queue: “RN Module: UIManager (<OS_dispatch_queue_serial: com.facebook.react.ShadowQueue>)” with 1 work item
⏱ Queue: “Main Queue (<OS_dispatch_queue_main: com.apple.main-thread>)” with 1 work item**

Versions Used:
    "detox": "^18.8.1",
    "react": "16.11.0",
    "react-native": "0.62.2",

Platform: iOS Simulator

Please help.

Thanks,
Bryan

**Comment by Gnarwall19** [comment]
https://github.com/wix/DetoxSync/blob/master/IdleStatusDocumentation.md
