### ISSUE TITLE
AppWillTerminateWithError with messageId: -10000 on Hybrid app

### ISSUE THREAD

**Issue by liweijian** [wix/Detox#2903]
### Describe the bug
I created a simple app and tried to use Detox to test it.

We launched the default `MainActivity.java` and clicked the button on it, we supposed to see it will open the `MyReactActivity.java`, but it just hold on the first activity and said that:

```shell
detox[50766] WARN:  [DetoxConnection.js/ERROR, #65000] Action dispatched too early, there is no session to use:

HINT: Please report this issue on our GitHub tracker:
https://github.com/wix/Detox/issues

{
  messageId: -10000,
  type: 'AppWillTerminateWithError',
  params: [Object]
}
```

### Steps To Reproduce
1. Create an empty Android project by Android Studio, just replace the default **Hello world** text to a button:

```xml
    <Button
        android:id="@+id/btnGo"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="CLICK ME!"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent" />
```

With `MainActivity.java` as follow:

```java
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Button button = findViewById(R.id.btnGo);
        button.setOnClickListener(new View.OnClickListener() {

            public void onClick(View v) {
                Intent myIntent = new Intent(MainActivity.this, MyReactActivity.class);
                MainActivity.this.startActivity(myIntent);
            }
        });
    }
}
```

Regarding the RN part, I followed [Facebook's official doc](https://reactnative.dev/docs/integration-with-existing-apps).

The test case I used(`e2e/firstTest.e2e.js`):

```js
describe('Example', () => {
  beforeAll(async () => {
    await device.launchApp();
  });

  beforeEach(async () => {
    await device.reloadReactNative();
  });

  it('should have CLICK ME screen', async () => {
    await expect(element(by.id('btnGo'))).toBeVisible();
  });

});
```

### Expected behavior
It should looks like follow by manual testing:
<img src="https://user-images.githubusercontent.com/19320783/126143662-f37a4b4e-f06f-49b6-830b-494bc64066b6.gif" width="300">

### Detox Trace-Logs
[detox.log](https://github.com/wix/Detox/files/6839925/detox.log)

### Device logs (adb logcat)
[detox_logcat.log](https://github.com/wix/Detox/files/6839926/detox_logcat.log)

### Environment (please complete the following information):
 - Detox: 18.19.0
 - React Native:  0.64.2
 - Node: v16.4.2
 - Device: Pixel_API_29_AOSP
 - OS: MacOS
 - Test-runner (select one): Jest 27.0.6

**Comment by d4vidi** [comment]
I hate to say this, but we don't currently support hybrid (aka brownfield) apps on Android - let alone ones with multiple activities. Perhaps one day ❤️

**Comment by liweijian** [comment]
@d4vidi Just curious why Detox not support brownfield apps on Android at this moment? Is there any historical discussions on the tech backend? From my understandings , Detox is based on Espresso, and it should support that.

Or if the users of Detox would try to contribute to the project and make it works, is there any prototype or WIP PRs?

**Comment by noomorph** [comment]
@liweijian see https://github.com/wix/Detox/issues/2543 and related issues. To cut it short, our team capacity is not very high, and this vector of Detox development is not prioritized. If someone from the community would take this seriously, I think it would be possible to restore brownfield support.
