### ISSUE TITLE
Enable Detox to work with `enableSeparateBuildPerCPUArchitecture` option is turned on

### ISSUE THREAD

**Issue by MuhmdRaouf** [wix/Detox#2917]
**Is your feature request related to a problem? Please describe.**
Detox cant detect and run tests in android while `enableSeparateBuildPerCPUArchitecture` option is turned on
from what I have seen right now after build detox makes sure the AOK is generated in `binaryPath` specified in the config file,  
then when test it uses the `AndroidTest` path equivalent to APK name specified in the config file.

**Describe the Problem**
when `enableSeparateBuildPerCPUArchitecture` option is turned off the output file normaly is:
`android/app/build/outputs/apk/debug/app-debug.apk`

and the `androidTest` output is:
`android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk`

but when `enableSeparateBuildPerCPUArchitecture` option is turned on the output files will be the following"
```
android/app/build/outputs/apk/debug/app-arm64-v8a-debug.apk
android/app/build/outputs/apk/debug/app-armeabi-v7a-debug.apk
android/app/build/outputs/apk/debug/app-x86-debug.apk
android/app/build/outputs/apk/debug/app-x86_64-debug.apk
```
and the `androidTest` output will also be is:
`android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk`
which case errors when detox running test as it search for
```
android/app/build/outputs/apk/debug/app-arm64-v8a-debug-androidTest.apk
android/app/build/outputs/apk/debug/app-armeabi-v7a-debug-androidTest.apk
android/app/build/outputs/apk/debug/app-x86-debug-androidTest.apk
android/app/build/outputs/apk/debug/app-x86_64-debug-androidTest.apk
```
based on which file you specified in the config file.

**Describe the solution you'd like**
we can just tell Detox to use
`android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk`
as it's not changing.

**Describe alternatives you've considered**
do the following enable `universalApk true  // If true, also generate a app-universal-debug.apk`
and do also the following 
```
// applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            // Example: versionCode 1 will generate 1001 for armeabi-v7a, 1002 for x86, etc.
            def versionCodes = ['armeabi-v7a': 1, 'x86': 2, 'arm64-v8a': 3, 'x86_64': 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride = defaultConfig.versionCode * 1000 + versionCodes.get(abi)
            } else {
                /**
                * change apk name in app-universal-(debug|release).apk variants to be app-(debug|release).apk
                * in order for detox apk locator to see the apk and run e2e tests.
                */
                output.outputFileName = output.outputFile.name.replace("app-universal", "app")
            }
        }
    }
```
in the `else ` scope which basically changes the universal app name to be  app-debug.apk in order for detox to work normally

**Comment by d4vidi** [comment]
This isn't mentioned in the set up guides, but it is described in the [configuration guide](https://github.com/wix/Detox/blob/master/docs/APIRef.Configuration.md#apps-configurations): You can specify the test APK's path explicitly using `testBinaryPath`
