### ISSUE TITLE
Tests are not running in parallel on the CircleCI

### ISSUE THREAD

**Issue by adomanich** [wix/Detox#2921]
Hello, I am new to detox.

Currently, on my project, we are working on an implementation of running e2e tests in parallel to reduce test time running.

I was able to set up that process locally, there are no issues, but, speaking about integration with CI - there are.
So, I prepared two test suites to run it in two threads.

I use default macos executor:
```
executors:
  macos_exec:
    macos:
      xcode: 12.3.0
```
I use the next commands to run tests on CI:

 ```
  brew tap wix/brew
  brew install applesimutils
  npm install -g react-native-cli
  npm install -g detox-cli
  yarn install
  cd ios && pod install
  detox build --configuration ios.debug
  detox test --configuration ios.debug --cleanup --loglevel trace --workers 2
```

I attached the log file of the output. For some reason, the second suite does not assign to the second booted device
[logFileDetoxCircleCI.txt](https://github.com/wix/Detox/files/6886397/logFileDetoxCircleCI.txt)

configurations:

.detoxrc.json
```
{
  "testRunner": "jest",
  "runnerConfig": "e2e/config.json",
  "configurations": {
    "ios.debug": {
      "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/commandmobile.app",
      "behavior": {
        "launchApp": {
          "launchArgs": {
            "connectHardwareKeyboard": "0"
          }
        }
      },
      "build":  "xcodebuild -workspace ios/commandmobile.xcworkspace -scheme commandmobile -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build -arch x86_64",
      "type": "ios.simulator",
      "device": {
        "type": "iPhone 11"
      }
    }
  }
}
```

config.json
```
{
    "testEnvironment": "./environment",
    "testRunner": "jest-circus/runner",
    "testTimeout": 480000,
    "testRegex": "\\parallel\\.js",
    "reporters": ["detox/runners/jest/streamlineReporter"],
    "verbose": true,
    "bail": false
}

```
environment.js
```
const {
  DetoxCircusEnvironment,
  SpecReporter,
  WorkerAssignReporter,
} = require('detox/runners/jest-circus');

const AllureReporter = require('./allureListener.js');
const XrayReporter = require('./xrayListener')

class CustomDetoxEnvironment extends DetoxCircusEnvironment {
  constructor(config) {
    super(config);

    // Can be safely removed, if you are content with the default value (=300000ms)
    this.initTimeout = 660000;

    // This takes care of generating status logs on a per-spec basis. By default, Jest only reports at file-level.
    // This is strictly optional.
    this.registerListeners({
      SpecReporter,
      AllureReporter,
      XrayReporter,
      WorkerAssignReporter,
    });
  }
}

module.exports = CustomDetoxEnvironment;
```

versions:
```
    "detox": "17.14.9",
    "jest": "26.6.3",
    "jest-circus": "26.6.3",
    "react-native": "0.63.3"
```

Example of run on local machine:
![ExampleOfRunOnLocalMachine](https://user-images.githubusercontent.com/54187915/127176275-2f1d0486-3a06-4a6c-8f95-7f9fa7e2b6ea.png)

On the local machine, everything looks fine, each suite assigns to a corresponding booted device. So, I am curious why that doesn't work on CircleCI.

Would be really grateful for any help

**Comment by d4vidi** [comment]
It is hard to tell just by looking at the config+logs. Here are some follow-up questions/suggestions:
1. Does the test suite run on CircleCI using just 1 simulator?
2. Would you mind retrying using a *release*-based app? Debug is discouraged.
3. It is plausible that CircleCI have some limitations regarding multiple simulators. Perhaps you'd like to revisit their specs, and approach their support.

**Comment by adomanich** [comment]
I found another way to provide parallelization on CircleCI: Run tests via multiple executors with only one device booted within each of them, instead of booting a few devices within one.
P.s If somebody will face the same need - to run detox tests in parallel on CircleCI: this doc should help -> https://circleci.com/docs/2.0/parallelism-faster-jobs/

**Comment by d4vidi** [comment]
@adomanich nice to learn that you've found a solution - although, I must say it is discouraged. Parallelism is well supported in Detox through Jest, and there ought to be a way to utilize it on Circle.

**Comment by adomanich** [comment]
@d4vidi I believe too, that there is a way (taking into account that locally it works great) I will return to it later and try to sort it out because currently, the solution I found met all our expectations
