### ISSUE TITLE
Handling 'test_fn_failure' event within ./environment.js?

### ISSUE THREAD

**Issue by sergtimosh** [wix/Detox#2924]
Hi, can somebody help to configure environment.js, so on test failure screenshot is taken automatically? Can't see any examples on the web.

**Comment by noomorph** [comment]
You just need to run Detox with `--take-screenshots failing` or use Detox config (`artifacts.plugins.screenshot` property - [see the docs](https://github.com/wix/Detox/blob/master/docs/APIRef.Artifacts.md#screenshot-plugin)).
