### ISSUE TITLE
Avoiding Unexpected Session Termination

### ISSUE THREAD

**Issue by gdoumen** [wix/Detox#2928]
**Is your feature request related to a problem? Please describe.**
I am using Detox to test on devices in a self-hosted device cloud (based on digital.io aka Experitest SeeTest). I have developed my own device driver and in principle this is working fine. However, installation of apps takes significantly longer on this device cloud than on devices connected via USB. This often leads to WSS disconnect ( DetoxServer terminates the session with the #tester - I assume that this is caused by WebSocket timeouts) 

**Describe the solution you'd like**
In order to reduce flakiness of tests, I would suggest that the websocket communication is kept alive using an heartbeat approach as described here: https://www.npmjs.com/package/ws#how-to-detect-and-close-broken-connections, i.e. sending ping/pong messages between server and all connected client sessions.

**Describe alternatives you've considered**
Alternatives could be
- Introduce a "keep-alive" message that the app or device driver(i.e. client) could send to the Detox server. That way, I could send that message in my device driver just before installing the app and instrumtented test. Also long-running tests could send this message.

**Additional context**
```
detox[1] DEBUG: [WSS_CONNECTION, #47398] registered a new connection.
detox[1] TRACE: [WSS_GET_FROM, #47398] {"type":"login","params":{"sessionId":"ba7f2a06-0dab-bef0-7f52-b5216b13f85d","role":"tester"},"messageId":0}
detox[1] TRACE: [SESSION_CREATED] created session ba7f2a06-0dab-bef0-7f52-b5216b13f85d
detox[1] TRACE: [WSS_SEND_TO, #tester] {"type":"loginSuccess","params":{"testerConnected":true,"appConnected":false},"messageId":0}
detox[1] TRACE: [SESSION_JOINED] tester joined session ba7f2a06-0dab-bef0-7f52-b5216b13f85d
detox[1] DEBUG: [WSS_CONNECTION, #19933] registered a new connection.
detox[1] TRACE: [WSS_GET_FROM, #19933] {"messageId":0,"type":"login","params":{"role":"app","sessionId":"7129fcc8-a5f8-4e6e-9966-0eb43d018aae"}}
detox[1] TRACE: [SESSION_CREATED] created session 7129fcc8-a5f8-4e6e-9966-0eb43d018aae
detox[1] TRACE: [WSS_SEND_TO, #app] {"messageId":0,"type":"loginSuccess","params":{"testerConnected":false,"appConnected":true}}
detox[1] TRACE: [SESSION_JOINED] app joined session 7129fcc8-a5f8-4e6e-9966-0eb43d018aae
detox[1] TRACE: [WSS_GET_FROM, #app] {"messageId":-1000,"type":"ready","params":{}}
detox[1] WARN:  [DetoxConnection.js/ERROR, #app] Cannot forward the message to the Detox client.

{
  messageId: -1000,
  type: 'ready',
  params: {}
}
detox[1] TRACE: [SESSION_TORN] tester exited session ba7f2a06-0dab-bef0-7f52-b5216b13f85d
```

**Comment by d4vidi** [comment]
@gdoumen I'm excited to hear that Detox fits into another environment!
However I'm not yet convinced there is a problem with app installation, per se. According to your logs snippet, the disconnection takes place sometime _after_ the app has already started running on the device.

**Comment by d4vidi** [comment]
I'm inclined to say that the app takes a long time to go idle, after launch - and this is where Detox gives up.

**Comment by gdoumen** [comment]
Hi @d4vidi I was looking at the app at the same time and had detox client running in trace mode, plus I had added some additional logs on the AsyncWebSocket.js ( methods close() and and _onClose() ) as I wanted to understand from where in the client the socket would get closed

I then was surprised that before any call to AsyncSocket.close() I saw that AsyncSocket.on_close() was called (basically just *before* you see "[DetoxConnection.js/ERROR, #app] Cannot forward the message to the Detox client." in the server log). Only a bit later the 2nd log appeared "...[SESSION_TORN].." .  (BTW another potential improvemts would be to add timestamps to logs ;-) )

On the device itself, I saw that the app was installed successfull, main screen was launched, but then it was not triggering any activity ( as the detox code was waiting for the first message from the Detoc Test script)

Therefore I am assuming that the Websocket is closed due to timeouts.

**Comment by d4vidi** [comment]
Do you know how long it takes for the 2nd log to appear, after the 1st? -
```
detox[1] TRACE: [WSS_GET_FROM, #app] {"messageId":-1000,"type":"ready","params":{}}
detox[1] WARN:  [DetoxConnection.js/ERROR, #app] Cannot forward the message to the Detox client.
```

Also, providing _device_ logs will help a great deal here.
