### ISSUE TITLE
app bundle support for detox 

### ISSUE THREAD

**Issue by vjoby-wavefin** [wix/Detox#2930]
### Describe the bug

Currently, detox works well with apk, but unfortunately, when I wanted to work with app bundles, it gives me errors while running the detox test command stating that the androidManifest.xml is not found.
So I suspect the app bundle is not yet supported for detox
Can I expect a response on this to see if there is a hacky workaround to get over this

### Screenshots

- [x] I have tested this issue on the latest Detox release and it still reproduces

1. "build": "./gradlew bundleRelease assembleAndroidTest -DtestBuildType=release"
<img width="1297" alt="Screen Shot 2021-08-03 at 10 26 08 AM" src="https://user-images.githubusercontent.com/84420760/128032788-91b80752-fd5d-4245-bcf3-5901364a24c0.png">

### Environment (please complete the following information):
 - Detox: 18.18.1
 - React Native: 0.61.5
 - Node:
 - Device:
 - OS: 
 - Test-runner (select one): `jest-circus`

**Comment by d4vidi** [comment]
@vjoby-wavefin we're looking into ways to help you out

**Comment by jonathanmos** [comment]
@vjoby-wavefin app bundle is a publishing format so detox cannot run on it directly. However, if you want detox to still be able to use it then you can use bundletool to convert the aab -> apks -> apk and then run on the apk, however it would be easier to assemble directly to an apk in the build command (assembleRelease) and run on that.
