### ISSUE TITLE
Run Detox tests on AWS

### ISSUE THREAD

**Issue by mikheyrojo** [wix/Detox#2934]
Hi, guy

is there a good solution how to tun detox tests on AWS instances?
Look like the only possible solution is to run it on c5.metal which costs a lot.

1. is there any other way to use detox on AWS instances?
2. can I somehow turn off KVM requirements for integration tests?

**Comment by d4vidi** [comment]
Hi @mikheyrojo,

sorry, AWS support is something we haven't explored yet.
I'm referring this to the community.
