### ISSUE TITLE
How to find status (Pass/Fail/Pending) of currently running (Just completed test) tests in Detox?

### ISSUE THREAD

**Issue by baskarkarthik** [wix/Detox#2951]
Hi Wix Team,
How do  I find a status of my 1st(current)test before it start executing 2nd(next) test?

For instance:
I have 2 tests. Each tests has 5 steps.
In Test1, 3rd step failed due to element not found. Before start executing 2nd Test I should get Fail status & failure reason stored in a variable.

Instead of getting status information of each test at end of execution I need to get at run time itself.

How do I achieve it?

Required information while run time:
- Status (Pass/Fail/Pending)
- Failure reason (If Failed)

**Comment by d4vidi** [comment]
I think you could be looking for [`--jest-report-specs`](https://github.com/wix/Detox/blob/master/docs/APIRef.DetoxCLI.md#test). Refer to our [Jest setup guide](https://github.com/wix/Detox/blob/master/docs/Guide.Jest.md#e2eenvironmentjs) for full details.

In any case - closing, before this is already supported.
