### ISSUE TITLE
Duplicate class com.genymotion.genyd.NetworkProfile$Status found in modules jetified-detox-18.20.2

### ISSUE THREAD

**Issue by thaole2021** [wix/Detox#2953]
I got this Exception when running "detox build --configuration android.emu.debug". How to solve it?
My environment:
"detox": "^18.20.2",
"jest": "^26.6.0",
com.android.tools.build:gradle:4.0.2
org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.21

> Task :app:checkDebugAndroidTestDuplicateClasses FAILED

> FAILURE: Build failed with an exception.

> * What went wrong:
> Execution failed for task ':app:checkDebugAndroidTestDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class com.genymotion.api.Battery found in modules jetified-detox-18.20.2-runtime.jar (com.wix:detox:18.20.2) and jetified-genymotion-api-1.2.0.jar (genymotion-api-1.2.0.jar)
  Duplicate class com.genymotion.api.Battery$1 found in modules jetified-detox-18.20.2-runtime.jar (com.wix:detox:18.20.2) and jetified-genymotion-api-1.2.0.jar (genymotion-api-1.2.0.jar)
  Duplicate class com.genymotion.api.Battery$2 found in modules jetified-detox-18.20.2-runtime.jar (com.wix:detox:18.20.2) and jetified-genymotion-api-1.2.0.jar (genymotion-api-1.2.0.jar)
  Duplicate class com.genymotion.api.Battery$Mode found in modules jetified-detox-18.20.2-runtime.jar (com.wix:detox:18.20.2) and jetified-genymotion-api-1.2.0.jar (genymotion-api-1.2.0.jar)
  Duplicate class com.genymotion.api.Battery$Status found in modules jetified-detox-18.20.2-runtime.jar (com.wix:detox:18.20.2) and jetified-genymotion-api-1.2.0.jar (genymotion-api-1.2.0.jar)
  Duplicate class com.genymotion.api.DiskIO found in modules jetified-detox-18.20.2-runtime.jar (com.wix:detox:18.20.2) and jetified-genymotion-api-1.2.0.jar (genymotion-api-1.2.0.jar)
  Duplicate class com.genymotion.api.GenydBinder found in modules jetified-detox-18.20.2-runtime.jar (com.wix:detox:18.20.2) and jetified-genymotion-api-1.2.0.jar (genymotion-api-1.2.0.jar)
  Duplicate class com.genymotion.api.GenydBinder$1 found in modules jetified-detox-18.20.2-runtime.jar (com.wix:detox:18.20.2) and jetified-genymotion-api-1.2.0.jar (genymotion-api-1.2.0.jar)
  Duplicate class com.genymotion.api.GenymotionException found in modules jetified-detox-18.20.2-runtime.jar (com.wix:detox:18.20.2) and jetified-genymotion-api-1.2.0.jar (genymotion-api-1.2.0.jar)
  Duplicate class com.genymotion.api.GenymotionManager found in modules jetified-detox-18.20.2-runtime.jar (com.wix:detox:18.20.2) and jetified-genymotion-api-1.2.0.jar (genymotion-api-1.2.0.jar)
`

**Comment by d4vidi** [comment]
Hi, do you happen to have the genymotion API library `jar` included as a directly dependency in your project? If so, please have it removed (it comes bundled in with Detox).

**Comment by thaole2021** [comment]
I have to check if jetified-genymotion-api-1.2.0.jar in my company app is from same dependency as genymotion-api-1.2.0.jar in Detox. If both are the same, I will be able to remove dependency for jetified-genymotion-api-1.2.0.jar.
I have a work around for now by using detox 18.17.0 which doesn’t have genymotion-api-1.2.0.jar.

**Comment by d4vidi** [comment]
Indeed, Detox ships with `genymotion-api-1.2.0.jar`.

**Comment by thaole2021** [comment]
genymotion API is not directly included as a dependency in my project. Do you have other suggestion?
Can I remove genymotion-api-1.2.0.jar in Detox package?

**Comment by d4vidi** [comment]
I don't think so, because it is hard-wired into the Detox `.aar`.
You can try to `exclude` genymotion in gradle, more or less like so:
```groovy
dependencies {
  	// ...
    androidTestImplementation(project(path: ":detox")) {
        exclude group: 'com.genymotion.api'
    }
}
```

**Comment by thaole2021** [comment]
Thanks @d4vidi I'm able to run the detox build without duplicate exception by adding `exclude` genymotion into android/app/build.gradle.

 ```
androidTestImplementation('com.wix:detox:+') {
        exclude group: 'com.genymotion.api'
  }
```

**Comment by d4vidi** [comment]
Great news!

**Comment by hipages-ligang** [comment]
I met the same issue.
According the guide [Detox for Android](https://github.com/wix/Detox/blob/master/docs/Introduction.Android.md), I thought it should add two line in app/build.gradle.  (I'm new for Android)
```
dependencies {
  	// ...
    androidTestImplementation('com.wix:detox:+')
    androidTestImplementation(project(path: ":detox"))
}
```

I fixed the issue by removing the first line.
Final code:
```
dependencies {
  	// ...
    androidTestImplementation(project(path: ":detox"))
}
```
