### ISSUE TITLE
I ran into this problem on android. I tried the same on iOS but I can't find it

### ISSUE THREAD

**Issue by ZineAoraya** [wix/Detox#2954]
<img width="843" alt="Screen Shot 2021-08-25 at 12 24 28" src="https://user-images.githubusercontent.com/89068341/130731367-6365b5ae-fc07-4f1d-abc2-8c6b50eb734a.png">

**Comment by d4vidi** [comment]
@ZineAoraya it pretty self explanatory 😅
In order to get actualy help, please provide sufficient details - full log, test code, etc.
