### ISSUE TITLE
Fix build in CI - create a build matrix

### ISSUE THREAD

**Issue by rotemmiz** [wix/detox#296]
Recent commits I added now use ANDROID_SDK_HOME in unit(integration) tests, I will have to move the Android specific tests into a different build pipeline, probably utilize the Travis build matrix feature to run iOS and Android tests in parallel.

On the same note, we will also need to run E2E on multiple RN versions, this should also be added to that build matrix.

**Comment by LeoNatan** [comment]
@rotemmiz

**Comment by rotemmiz** [comment]
I am reopening this issue, there still is one step to be completed, adding Android builds to the test matrix

**Comment by LeoNatan** [comment]
🤘

**Comment by LeoNatan** [comment]
Can this be closed? @rotemmiz mizmiz

**Comment by LeoNatan** [comment]
I think this was implemented already.

**Comment by rotemmiz** [comment]
Yes, sorry for missing the question :(

**Comment by rotemmiz** [comment]
It wasn't actually, waiting for our Jenkins setup since Travis CI doesn't support nested virtualization yet (for x86 Android emulators).

Reopening :(

**Comment by LeoNatan** [comment]
💩

**Comment by LeoNatan** [comment]
Now can we finally close this? 😓
