### ISSUE TITLE
[question] run on aws device farm or firebase test lab?

### ISSUE THREAD

**Issue by appsthatmatter** [wix/detox#297]
Is it possible to run detox tests on a cloud testing solution like AWS device farm or Firebase test lab?

**Comment by DanielMSchmidt** [comment]
@talkol I remember that we discussed that a while ago and I have in my mind that you had some kind of solution or future solution for this, right?

**Comment by LeoNatan** [comment]
Running on real devices is currently not supported. We plan on supporting that eventually. See #95
