### ISSUE TITLE
Add support for passing through Equals-Separated options to jest CLI

### ISSUE THREAD

**Issue by jar0s** [wix/Detox#2970]
**Is your feature request related to a problem? Please describe.**
I'm trying to use [jest-runner-groups](https://www.npmjs.com/package/jest-runner-groups) in order to be able to easily tag (using docblock) tests and specify which ones I'd like to execute from CLI. This would enable us to maintain a "smoke suite" and "regression suite" of tests in one place and execute each of them easily within different CI stages.

**Describe the solution you'd like**
It would be great if `detox test` command would support passing through the "Equals-Separated" (e.g. "--group=smoke") options to jest CLI. Currently when I run `detox test -c my-config --group=smoke`, it gets translated into the following:
```
DETOX_CONFIGURATION="my-config" ...  jest --config e2e/config.json --testNamePattern '^((?!:ios:).)*$' --maxWorkers 1 --group smoke e2e
```
which results in jest complaining it doesn't know the `group` parameter:
```
  Unrecognized CLI Parameter:

  Unrecognized option "group".

  CLI Options Documentation:
  https://jestjs.io/docs/cli
```

The correct/working command is:
`DETOX_CONFIGURATION="my-config" ...  jest --config e2e/config.json --testNamePattern '^((?!:ios:).)*$' --maxWorkers 1 --group=smoke e2e` as per [jest-runner-groups docs](https://github.com/eugene-manuilov/jest-runner-groups#run-groups-of-tests)

**Describe alternatives you've considered**
I've considered the following alternative:

* Use the jest's `--testNamePattern` parameter, instead of the `jest-runner-groups`, and include all test groups the given scenario belongs to within the test names themselves. This doesn't feel maintainable and scalable enough for our purposes, could be error-prone, and is generally inferior to what `jest-runner-groups` can do, so I'm not a fan of this approach.

**Additional context**
As a workaround, I think we'll go with a custom script that will run the jest command directly with the proper syntax of the "group" parameter. This is not great as I believe we'll miss out on some smarts that `detox test` may be doing for us currently, not to mention the whole plethora of `detox test` CLI options that we won't be able to use directly (at least in not a straightforward way)

**Comment by d4vidi** [comment]
@jar0s thanks for bringing this to our attention!
I really think that could have real value for us as well.
Also, I don't think the gap for getting this done is all to big, but probably - @noomorph would have a better insight.

**Comment by jar0s** [comment]
Throwing a comment here to prevent the bot from closing as it's still relevant despite no discussion happening.

Suggestion: Shouldn't the bot leave the issues tagged with `status: accepted` open?

**Comment by noomorph** [comment]
Try using "-- ... passthrough ..." trick (use -- to start passing forward the args)

**Comment by noomorph** [comment]
The status is not clear enough here, so I suggest to summarize the resolution here, especially in the light of Detox 20.
