### ISSUE TITLE
Methods provided for testing Biometrics don't work

### ISSUE THREAD

**Issue by arish-panjwani** [wix/Detox#2981]
### Description
I have implemented the Biometric Check Functionality(Face ID and Touch ID) in my App and I need to test it using Detox.

I have tried the methods provided in detox docs
(https://github.com/wix/Detox/blob/7bed6ea8a2bef11576ca0014a4596776d9320cfd/docs/APIRef.DeviceObjectAPI.md#devicesetbiometricenrollmentbool-ios-only) 
but they don't seem to work.

I have used the following code in my test where the biometric is asked by the app.

> it("matchFinger Test", async () => {
> await device.setBiometricEnrollment(true);
> await device.matchFinger();
> }

and

> it("matchFace Test", async () => {
> await device.setBiometricEnrollment(true);
> await device.matchFace();
> }

#### Expected behavior
It should match the face ID/touch ID and login successfully.

#### Actual Output
The test gets stuck and the following output is given continuously:

> detox[8939] INFO:  [APP_STATUS] The system is busy with the following tasks:

> Dispatch Queue
> ⏱ Queue: “Main Queue (<OS_dispatch_queue_main: com.apple.main-thread>)” with 1 work item
> 
> Run Loop
> ⏱ “Main Run Loop”
> detox[8939] INFO:  [APP_STATUS] The system is busy with the following tasks:
> 
> Dispatch Queue
> ⏱ Queue: “Main Queue (<OS_dispatch_queue_main: com.apple.main-thread>)” with 1 work item
> 
> Run Loop
> ⏱ “Main Run Loop”

- [x] I have tested this issue on the latest Detox release and it still reproduces

#### Screenshots
![image](https://user-images.githubusercontent.com/66029291/133392332-ae2ea160-43c5-47ff-80d9-8140dd483653.png)

#### Environment:
 - Detox: 18.20.3
 - React Native: 0.63.4
 - Node: v14.15.3
 - Device: iPhone 8 Simulator(For TouchID) / iPhone 11 Simulator(For FaceID) 
 - Xcode: 12.3
 - iOS: 14.3
 - macOS: Big Sur (Version 11.0.1)
 - Model: Macbook Air (M1,2020)

**Comment by tradebulls** [comment]
We are facing the same issue. Any solution?

**Comment by npjoge** [comment]
I am also facing same kind of issues. **Any solution?**

**Comment by arish-panjwani** [comment]
@noomorph @d4vidi @LeoNatan Any Solutions for this?

**Comment by noomorph** [comment]
@alon-ha, could you find some time to look this week at this?

**Comment by alon-ha** [comment]
Will take a look this week

**Comment by arish-panjwani** [comment]
@d4vidi @alon-ha Any update on this?

**Comment by noomorph** [comment]
> @d4vidi @alon-ha Any update on this?
> 
> 

@alon-ha is no longer working with us on Detox.

@asafkorem howdy! Can you take a look at this issue? 🙏

**Comment by asafkorem** [comment]
Thanks @arish-panjwani for reporting the issue!
I will investigate this issue very soon. 

In the meanwhile, I'd appreciate if you could answer me a few questions:
1. Did you called `setBiometricEnrollment(true)` **before** the authentication request was started?
2. Did you called `matchFinger()` / `matchFace()` **after** the authentication request was started?
3. In what point the test get stuck? 

* If the answer for 1 /2 is no, please try to change your code so it will fit the following flow: `set enrollment > invoke authentication request -> call the matching method`.

Also, it would be very useful if you can reproduce this issue in a real app & test that you can share with me, you can use https://github.com/wix-incubator/DetoxTemplate if it helps. Alternatively please provide here the code that you are testing with the problematic tests (unless the tests code described above is enough for reproducing the issue).

**Comment by arish-panjwani** [comment]
Thanks for the reply @asafkorem, I'll check and reply in a couple days.

**Comment by arish-panjwani** [comment]
> Thanks @arish-panjwani for reporting the issue! I will investigate this issue very soon.
> 
> In the meanwhile, I'd appreciate if you could answer me a few questions:
> 
> 1. Did you called `setBiometricEnrollment(true)` **before** the authentication request was started?
> 2. Did you called `matchFinger()` / `matchFace()` **after** the authentication request was started?
> 3. In what point the test gets stuck?
> 
> * If the answer for 1 /2 is no, please try to change your code so it will fit the following flow: `enable biomentric enrollment > invoke authentication request -> call the matching method`.
> 
> Also, it would be very useful if you can reproduce this issue in a real app & test that you can share with me, you can use https://github.com/wix-incubator/DetoxTemplate if it helps. Alternatively please provide here the code that you are testing with the problematic tests (unless the tests code described above is enough for reproducing the issue).

@asafkorem 
I did call `setBiometricEnrollment(true)` **before** the authentication request was started and 
`matchFinger()` / `matchFace()` **after** the authentication request was started.

Firstly, setBiometricEnrollment(true) does not set Biometric Enrollment to true and I have to do it manually from `Features -> Face ID -> Enrolled`.

Secondly, even after doing that, the test gets stuck at matchFace() with the message "The system is busy"(please refer to the screenshot in the original issue statement) and I have to manually match the Face on Simulator by going to `Features -> Face ID -> Matching Face`.

Thus technically neither of the commands actually work.

Please look at the following code implementation:

> import { logout, userLogin } from "@e2e/CommonTestCases";

> describe("Biometrics Test", () => {
>   beforeAll(async () => {
>     await device.launchApp();
>   });
> 
>   //Logs out the user if already logged in
>   logout();
> 
>   //Login trading user and enables biometrics from inside the app
>  userLogin(true);
> 
>   //Supposed to set Biometric Enrollment to true
>   it("Set Biometric Enrollment Test", async () => {
>     await device.setBiometricEnrollment(true);
>   });
> 
>   //Kills the app and reopens it (Note: This time login Id and password is not required but Pin/Biometrics are required as 2FA)
>   it("Kill and reopen App", async () => {
>     await device.terminateApp();
>     await device.launchApp();
>   });
> 
>   // Supposed to Match Face
>   it("matchFace Test", async () => {
>     await device.matchFace();
>   });
> });

**Comment by arish-panjwani** [comment]
@asafkorem any update on this?

**Comment by asafkorem** [comment]
Hi @arish-panjwani, first - what are `logout()` and `userLogin()`? why they are not in the `beforeAll()`?

Please help me investigate and reproduce this better, I suggest to write a small isolated test that does the minimal actions.

If I understand your flow correctly, it should be something like:
```
it("should match face", async () => {
  await device.launchApp();
  
  logout();

  await device.setBiometricEnrollment(true);
  userLogin(true);
  
  await device.matchFace();
});
```

**Comment by asafkorem** [comment]
Also, if it still fails, and you want to expedite the investigation, please reproduce this issue on our [template app](https://github.com/wix-incubator/DetoxTemplate), it will be very helpful.

**Comment by MuckT** [comment]
Was able to get this working with [react-native-touch-id](https://www.npmjs.com/package/react-native-touch-id) here: [DetoxTemplate-biometrics](https://github.com/MuckT/DetoxTemplate/tree/tomm/biometrics); however, I did run into some issues with the `device.unmatch()` timing out as I couldn't interact with the system dialog.

In attempting to [implement biometrics](https://github.com/valora-inc/wallet/issues/1776) I also found that the library [react-native-keychain](https://www.npmjs.com/package/react-native-keychain) might not work on iOS simulators, so that might be part of the issue others are experiencing. https://github.com/oblador/react-native-keychain/issues/340#issuecomment-631681484

**Comment by rikur** [comment]
Same issue, running on iOS 16 simulator and latest detox. Subscribing to the GH issue.
