### ISSUE TITLE
Boolean return for element visibility methods

### ISSUE THREAD

**Issue by sergtimosh** [wix/Detox#2986]
It was already asked for previously but was closed by the valid reason https://github.com/wix/Detox/issues/1214#issue-422414425
I still think that it would be good to have some api that returns boolean value for element presence/visibility.
ex.:
el.isVisible()
el.isPresent()

Why? 
In my mobile tests I have entities like saved searches, saved views etc. which I can't drop or set via DB or API requests, so the only way to set state is beforeAll beforeEach hooks and the actual UI. Not perfect, but thats what I have. Also having boolean as returning value makes using jest matchers more convenient and universal thorough use within detox platform. 
Currently I use try-catch to retrieve visibility which is a bit ugly solution. Maybe I'm not alone here? :)

**Comment by d4vidi** [comment]
@sergtimosh perhaps this API could settle it? - https://github.com/wix/Detox/blob/master/docs/APIRef.ActionsOnElement.md#getattributes

**Comment by asafkorem** [comment]
@sergtimosh is that issue still relevant to you?
