### ISSUE TITLE
Revisit iOS impl of detoxURLBlacklistRegex

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#2988]
## Description

A follow up on #2911, where @jonathanmos has implemented this feature for Android and has created an e2e test for it.
Unfortunately, we couldn't get the test to pass on iOS, and we're not sure if it's due to some RegEx standard limitations or that perhaps the iOS impl. is lacking (given that were no... hmm, tests...).

**Solution:**
Either the test should work on iOS, or that there's a bug on iOS (or a mismatch) - in which case, we ought to either fix or work our ways around that.

**Comment by adamivancza** [comment]
any update on this? it still seems to be broken on iOS

**Comment by noomorph** [comment]
Assigning to myself. The definition of done on my side – provide a branch with an E2E test and a clear description where the problem is. Then we'll re-triage it with @asafkorem.

**Comment by adamivancza** [comment]
any update on this @noomorph ?

**Comment by d4vidi** [comment]
Oops, missed this issue when reported #3954. @adamivancza The fix is under review in #3953.
