### ISSUE TITLE
Configuration File Equivalent of --record-videos all ? 

### ISSUE THREAD

**Issue by princefishthrower** [wix/Detox#2993]
As the title states, I can't seem to find the configuration values to set (if it is even possible) to always record videos on tests. I've read through the [Artifacts.md documentation](https://github.com/wix/Detox/blob/master/docs/APIRef.Artifacts.md) but it seems that this option to record all the videos is only available in that command line flag.

The problem is I can no longer use the command line flag, as we have linked our Cucumber scenarios and Cucumber is driving Detox.

So really I'm looking for any programmatic way to ensure that the videos are captured for each test.

**Comment by d4vidi** [comment]
Yes, you can bundle that into the Detox configuration file: https://github.com/wix/Detox/blob/master/docs/APIRef.Configuration.md#artifacts-configuration

The short answer is (example):
```json
"artifacts": {
  "plugins": {
    "video": "failing"
  }
}
```
> Either use "failing" or "all", depending on your needs...

You can also generate the configuration dynamically by setting it up in a javascript file instead of a static json, then do things like:

```js
return {
  artifacts: {
    plugins: {
      video: process.env.IS_CI ? 'failing' : undefined,
    },
  },
};
```

**Comment by d4vidi** [comment]
Closing this specific issue. We will revisit this in #3001

**Comment by princefishthrower** [comment]
@d4vidi excellent! One further question though (that may help for #3001 ), since I already had a value set for the "video" key:

```
"video": {
        "android": {
          "size": [1080, 1920]
        }
      }
```

due to [this](https://github.com/wix/Detox/issues/1451) issue I ran into. So is it somehow possible to pass those dimension parameters in addition to the `"all"` value?

**Comment by noomorph** [comment]
@princefishthrower , yes. See: https://github.com/wix/Detox/blob/master/detox/index.d.ts#L151
