### ISSUE TITLE
latest xCode 13 / iOS 15 simulators completely broken with Detox

### ISSUE THREAD

**Issue by shamilovtim** [wix/Detox#2997]
After upgrading to iOS 15 simulators / xCode 13 Detox no longer functions at all. The app seems to constantly get minimized with no clear errors. If the app is brought up manually again from background Detox seems able to work again but only temporarily as it fails over and over.

**Comment by oliveirasWell** [comment]
Here we are having this problem too,

When you try to check the simulator logs with

```
/usr/bin/xcrun simctl spawn MY-SIMULATOR-ID log stream --level debug --style compact --predicate 'process == "AwesomeApp"'
```

I'm just getting this log:

`Error from getpwuid_r: 0 (Undefined error: 0)`

**Comment by fliip92** [comment]
I had the same issue. specifying the os version its a by pass ex:
`  "devices": {
    "simulator": {
      "type": "ios.simulator",
      "device": {
        "type": "iPhone 11",
        "os": "iOS 14.0"
      }
    },`
    seems like a ios 15 issue not xcode 13

**Comment by shamilovtim** [comment]
@fliip92 I'm assuming you have to have the old SDK installed right? Just as easy bypass: remove your iOS 15 simulator, and install an earlier iOS SDK simulator. in our case we're using 14.5

**Comment by fliip92** [comment]
exactly!

**Comment by mikehardy** [comment]
This is duplicate: #2895

**Comment by mikehardy** [comment]
Really follow along on #2895 - there is more than one issue with ios15 and for me at least Detox is still not working with v18.22.0

This is a duplicate and continuing conversation here just splits the conversation
