### ISSUE TITLE
Problem with running Detox tests on the Github Actions

### ISSUE THREAD

**Issue by VladosDosvidos** [wix/Detox#3005]
I have created tests for my application and it's working perfectly on my local machine. But when I have tried to run it on the Github Action I have received some errors with tests. In all cases, tests are failed when detox tries to press the button using `.tap()`  method.  When I have used the `--loglevel trace` command I received this type of error for the buttons:
`"View “<RCTTextView: 0x7f9d66879700>” is not visible: view does not pass visibility threshold (0% visible of 75% required)"` but only on CI. On the local machine, it works well without any errors.

**Comment by d4vidi** [comment]
Visibility threshold = meaning, the expected view is not visible on the device. There is quite a set of reasons why this can happen, and the description is pretty vague. Please provide additional info such as screenshots, videos and test+device logs. See here: https://github.com/wix/Detox/blob/master/docs/APIRef.Artifacts.md

**Comment by d4vidi** [comment]
Np. Happy to hear it's been sorted out.

**Comment by crevulus** [comment]
@VladosDosvidos How does one hide the keyboard in the CI env?
