### ISSUE TITLE
How can I test when app requires OTP via SMS?

### ISSUE THREAD

**Issue by ZineAoraya** [wix/Detox#3006]
How can I test when app requires OTP via SMS?

**Comment by noomorph** [comment]
@d4vidi do we have a solution? Or we should just tell to mock this?

**Comment by MuckT** [comment]
We had a use case that was similar and ended up going the route that @indradeepchowdhury mentioned and [ended up using the Twilio API](https://github.com/valora-inc/wallet/blob/main/packages/mobile/e2e/src/utils/twilio.js).

**Comment by d4vidi** [comment]
Typically, we would advise testing in a more stable mocked environment. Namely, running the (login?) flow all the way to the OTP, mocking away the OTP service itself, and only making sure it was _triggered_ properly using your mock. For example, render a screen showing which args were passed to it and asserting them using `toBeVisible()` calls.

If, nevertheless, you need to test this E2E in an unmocked (though potentially flaky) way, you might want to consider using [twillio's OTP solution](https://www.twilio.com/code-exchange/one-time-passcode-verification-otp), as suggested.
