### ISSUE TITLE
Detox launchApp with deep link url works fine when newInstance is set to false but not when it is set to true

### ISSUE THREAD

**Issue by indradeepchowdhury** [wix/Detox#3008]
### Description
I am testing the deep link functionality in my react native app. I am using the device.launchApp to accomplish this. However, it only works if I set the newInstance to false. The deep link navigation does not happen if I set it to true.

**Works fine:**
```
await device.launchApp({
          newInstance: false,
          <my-url>,
        });
```
**Does not work:**
```
await device.launchApp({
          newInstance: true,
          <my-url>,
        });
```
**Also works fine:**
`await device.openURL({<my-url>});`

### Environment

 - Detox: Latest (18.22.1/ also tried with older versions)
 - React Native: 0.64.2/0.64
 - Node: v14.17.2
 - Device: iOS 14.5
 - Test-runner (select one): jest-circus

Please let me know if I am missing something. I have tried it with combinations of sendToHome and terminateApp but it does not work.

**Comment by d4vidi** [comment]
@indradeepchowdhury definitely plausible that like you might have a bug in your app. Would appreciate a deeper inspection on your behalf and otherwise repro using our [DetoxTemplate](https://github.com/wix-incubator/DetoxTemplate) project 🙏🏻
