### ISSUE TITLE
Detox crashes app on test start on genymotion (Android)

### ISSUE THREAD

**Issue by declanhart1** [wix/Detox#3014]
### Description
When running our app on the genymotion simulator (both GMSAAS and local version), detox is able to connect and install the app onto the device, the app launches successfully and goes into idle. After a short time, The app crashes with the following error:

> {
>   "messageId": -10000,
>   "type": "AppWillTerminateWithError",
>   "params": {
>     "errorDetails": "@Thread detox.primary(274):\njava.lang.NoSuchMethodError: No static method substringBefore$default(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/Object;)Ljava/lang/String; in class Lf/z/g; or its super classes (declaration of 'f.z.g' appears in /data/app/<REDACTED>-8lPAjedYrwKq9_EG3ThCSw==/base.apk)\n\tat com.wix.detox.adapters.server.InvokeActionHandler.extractFailurePayload(DetoxActionHandlers.kt:71)\n\tat com.wix.detox.adapters.server.InvokeActionHandler.handle(DetoxActionHandlers.kt:60)\n\tat com.wix.detox.adapters.server.ActionsExecutor$executeAction$$inlined$let$lambda$1.run(DetoxActionsDispatcher.kt:64)\n\tat android.os.Handler.handleCallback(Handler.java:883)\n\tat android.os.Handler.dispatchMessage(Handler.java:100)\n\tat android.os.Looper.loop(Looper.java:214)\n\tat com.wix.detox.adapters.server.ActionsExecutor$1.run(DetoxActionsDispatcher.kt:50)\n\tat java.lang.Thread.run(Thread.java:919)\n\nCheck device logs for full details!"
>   }
> }
>

> TRACE: [ARTIFACTS_LIFECYCLE] artifactsManager.onHookFailure({
>   error: DetoxRuntimeError: The pending request #1 ("invoke") has been rejected due to the following error:
>   
>   The app has crashed, see the details below:
>   
>   @Thread detox.primary(289):
>   java.lang.NoSuchMethodError: No static method substringBefore$default(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/Object;)Ljava/lang/String; in class Lf/z/g; or its super classes (declaration of 'f.z.g' appears in /data/app/<REDACTED>-R5S89JQn20Gh7eNP7IqBZw==/base.apk)

We have spent a considerable amount of time debugging and trying different configurations, any advice would be much appreciated.

### Environment

 - Detox: 18.22.1
 - React Native: 0.65.1 (Also occurs on 0.63.3)
 - Node: 14.16.0
 - Device: Genymotion (both GMSAAS and local install) Google nexus 2 or Samsung Galaxy S10.
 - OS: Android 6.0 (API 23) or Android 10 (API 29)
 - Test-runner (select one): `jest-circus`

**detoxrc**
> {
>     "testRunner": "jest",
>     "runnerConfig": "e2e/config.json",
>     "behavior": {
>         "init": {
>             "reinstallApp": true,
>             "exposeGlobals": true,
>             "permissions": {
>                 "notifications": "YES",
>                 "faceId": "NO"
>             }
>         }
>     },
>     "artifacts": {
>         "rootDir": "$CI_PROJECT_DIR/reports/artifacts/ios",
>         "plugins": {
>             "instruments": { "enabled": true },
>             "log": { "enabled": false },
>             "uiHierarchy": "disabled",
>             "screenshot": {
>                 "shouldTakeAutomaticSnapshots": true,
>                 "keepOnlyFailedTestsArtifacts": true,
>                 "takeWhen": {
>                     "testStart": false,
>                     "testDone": true
>                 }
>             },
>             "video": {
>                 "android": {
>                     "bitRate": 4000000
>                 },
>                 "simulator": {
>                     "codec": "hevc"
>                 }
>             }
>         }
>     },
>     "configurations": {
>         "android.geny.local": {
>             "type": "android.attached",
>             "binaryPath": "android/app/build/outputs/apk/release/app-release.apk",
>             "build": "cd android && ./gradlew assembleRelease assembleAndroidTest -DtestBuildType=release && cd -",
>             "utilBinaryPaths": ["android/test-butler-app-2.2.1.apk"],
>             "device": {
>                 "adbName": "192.168.56.107:5555"
>             }
>         },
>         "android.geny.release": {
>             "type": "android.attached",
>             "binaryPath": "android/app/build/outputs/apk/release/app-release.apk",
>             "build": "cd android && ./gradlew assembleRelease assembleAndroidTest -DtestBuildType=release && cd -",
>             "utilBinaryPaths": ["android/test-butler-app-2.2.1.apk"],
>             "device": {
>                 "adbName": "localhost:41987"
>             }
>         }
>     }
> }

**config.json**

> {
>     "globalSetup": "./global-setup.js",
>     "testEnvironment": "./environment",
>     "testRunner": "jest-circus/runner",
>     "testTimeout": 240000,
>     "testRegex": "\\.detox\\.spec\\.js$",
>     "reporters": ["detox/runners/jest/streamlineReporter"],
>     "verbose": true
> }

**Comment by jonathanmos** [comment]
@declanhart1  This looks like it's the same issue as in #3010. Please try with the latest release version https://github.com/wix/Detox/releases/tag/18.22.2 and see if it still occurs.

**Comment by jonathanmos** [comment]
@declanhart1 it looks like there's not so much to go on in the logs, so the only way I think we can find out what is actually happening here is to reproduce the issue. Could you try to fork the DetoxTemplate project and add to it the minimal things which are required to reproduce (3rd party libraries / e2e tests)?
