### ISSUE TITLE
tabBarTestID not recognized with react-navigation

### ISSUE THREAD

**Issue by SeveHo** [wix/Detox#3016]
### Description

Hi, I have problem navigating to an other bottom tab screen during my test. According to other examples this should work fine:

**Test File:**
```js
it("Should be able to log out", async () => {
  await element(by.id("account")).tab();
});
```

**Error Log:**
```sh
TypeError: element(...).tab is not a function
  22 |
  23 |   it("Should be able to log out", async () => {
> 24 |     await element(by.id("account")).tab();
     |                                     ^
  25 |   });
```
**Navigation Config:**
```js
<BottomTab.Screen
  name="Account"
  component={AccountNavigator}
  options={{
    tabBarTestID: "account",
    tabBarIcon: ({ color }) => <TabBarIcon name="user" color={color} />,
}}
/>
```
### Environment

 - Detox: 18.22.2
 - React Native: 0.63.4
 - React Navigation: 6
 - Node: 15.14.0
 - Device:  iPhone 11 Simulator
 - OS: iOS 15.0
 - Test-runner `jest-circus`

**Comment by EgorFrom** [comment]
if anyone else runs into a switch issue: "Remove all warnings"
<img width="329" alt="image" src="https://user-images.githubusercontent.com/31363936/197256511-4c8595f0-217d-4590-bf16-138787aedfe7.png">

**Comment by juls-k** [comment]
@EgorFrom Yes, I encountered problems despite correctly writing the code, but it worked when I applied the method you suggested. 
Does it fail to recognize testID if the warning log is covering the tab button? 
This is interesting.
