### ISSUE TITLE
Default AsyncStorage values before tests run

### ISSUE THREAD

**Issue by rcwestlake** [wix/Detox#3025]
### Description
I'm wondering how to default AsyncStorage values in React Native for a Detox test.

I have a welcome modal which shows when the user firsts login. We control whether to show the modal by storing an AsyncStorage value. Since our tests launch different instances of the apps (with different settings - hardware auth / no hardware auth, etc.), I'm looking for a way to default a value before a test begins. This will also save minutes over the course of our whole e2e testing because we have other instances that could use this.

I shortly investigated using a jest mock but not sure that's the right approach because I don't want to mock all of `.getItem`, I just want to mock it for this specific value that is stored and allow the non-mock AsyncStorage to be used throughout the tests. 

I also posted this in StackOverflow: https://stackoverflow.com/questions/69533417/default-asyncstorage-values-in-a-detox-test

### Environment

 - Detox: `^18.18.1`
 - React Native: `~0.63.4`
 - Node: `v16.1.0`
 - Device: `IOS Simulator`
 - OS: 
 - Test-runner (select one): `jest-circus`

**Comment by dirkpostma** [comment]
I do it by opening the app with a dynamic link, with some parameters.

for example: 

myapp://example/?action=setAsyncStoragw&key=someKey&value=someValue

the apps dynamiclink handler recognizes this dynamic link and sets a value.

**Comment by rcwestlake** [comment]
@dirkpostma do you have an example of what the command looks like? are you using the `device.launchApp` command?
