### ISSUE TITLE
Upgrade to RN 0.66 (Android)

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#3033]
## Description

Add/verify support for the React Native 0.66 release:

- [x] Check (and migrate) Detox test app on developer env
- [ ] Upgrade demo apps (demo-react-native, then check demo-react-native-jest and detox-react-native-detox-instruments)
- [x] Upgrade associated CI job config to always use 0.66
- [x] Update support table in main README.md

**Comment by jonathanmos** [comment]
https://github.com/facebook/react-native/issues/32594

**Comment by FadiAboMsalam** [comment]
Any update on this 🤔  ?

**Comment by d4vidi** [comment]
@FadiAboMsalam yes, #3035 is review-pending. Should probably land in by the end of the week 👍🏻
