### ISSUE TITLE
Run `detox text --configuration ios` fail with `TypeError: this._environment.runScript is not a function`

### ISSUE THREAD

**Issue by obiwankenoobi** [wix/Detox#3042]
### Description
When trying to run test commend I am getting this error below: 

```
detox test --configuration ios 
detox[45572] INFO:  [test.js] DETOX_CONFIGURATION="ios" DETOX_REPORT_SPECS=true DETOX_START_TIMESTAMP=1635252211020 DETOX_USE_CUSTOM_LOGGER=true jest --config e2e/config.json --testNamePattern '^((?!:android:).)*$' e2e
 FAIL  e2e/firstTest.e2e.jsrun...
  ● Test suite failed to run

    TypeError: this._environment.runScript is not a function

      at Runtime._execModule (../node_modules/jest-runner/node_modules/jest-runtime/build/index.js:856:41)

detox[45572] ERROR: [cli.js] Command failed: jest --config e2e/config.json --testNamePattern '^((?!:android:).)*$' e2e
```

- [x] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction

Following "Getting Started" tutorial step by step until getting to the actual `test` commend

#### Expected behavior

Example test to run

#### Environment

 - Detox: 18.23.1
 - React Native: 0.63.4
 - Node: v14.18.0
 - Device: ios simulator
 - Xcode: 12.5.1
 - iOS: 14
 - macOS: 11.4
 - Test-runner (select one): `jest-circus`
 
 `config.json`:
 ```
{
    "maxWorkers": 1,
    "testEnvironment": "./environment",
    "testRunner": "jest-circus/runner",
    "testTimeout": 120000,
    "testRegex": "\\.e2e\\.js$",
    "reporters": ["detox/runners/jest/streamlineReporter"],
    "verbose": true
}

```

**Comment by noomorph** [comment]
Looks like something's off with the Jest version. What versions do you have? `jest`, `jest-circus`?
Maybe it is Expo? Try updating your Expo version.
