### ISSUE TITLE
Initial Native Screens, detox hangs waiting for “React Native (bundle load)”

### ISSUE THREAD

**Issue by suark** [wix/Detox#3051]
### Description
My app starts with a native iOS Screen. 

- iOS builds work
- tests can open the app and start it running on the first screen
- it sits on the following message

```
detox[4241] INFO:  [APP_STATUS] The system is busy with the following tasks:

Dispatch Queue
⏱ Queue: “Main Queue (<OS_dispatch_queue_main: com.apple.main-thread>)” with 1 work item

Run Loop
⏱ “Main Run Loop”

One-time Events
⏱ “React Native (bundle load)”
```
- It will just timeout and then say this:

```
detox[4241] WARN:  [PENDING_REQUESTS] The app has not responded to the network requests below:
  (id = -1000) isReady: {}

Unresponded network requests might result in timeout errors in Detox tests.

...

    thrown: "Exceeded timeout of 120000 ms for a hook.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      49 | describe('Dashboard e2e Screen', () => {
      50 |
    > 51 |   beforeAll(async () => {
         |   ^
      52 |     await device.launchApp();
```

- If I manually click through the app myself until I reach the first react-native screen, then it seems to get past this step.

From my understanding, Detox should work on purely native apps, so is it really stuck waiting for a react-native screen?

I can see the bundler loading to 100% and going away at the top of the simulator so it seems like the app is totally ready to use, but detox doesn't seem to be able to confirm that things are ready.

### Environment
 - Detox: 18.23.1
 - React Native: 0.65.1
 - Node: v14.17.4
 - Device: iOS simulator iPhone 11 - 14.4
 - OS: macOS Catalina 10.15.7 
 - Test-runner: jest-circus

**Comment by suark** [comment]
Not solved yet, but I downgraded detox to 17.14.9 and my tests are running now.

**Comment by d4vidi** [comment]
@suark sorry for the delay in getting to review this. Could you better describe that first (native) screen, or try to think about what could be keeping it busy? Screenshots / videos would be welcomed.

**Comment by d4vidi** [comment]
Hey @suark could you report that status here? Are you stuck with Detox v17, or have you managed to solve this issue?

**Comment by dnsmob** [comment]
i also have the exact same behaviour (might attempted detox v17, but 18 and 19 wont play ball). i do remember a few years ago with some v12.x.y, one of them would work eventually. i have no animation/transition/load/gif/nothing on the first native screen, but it still hangs (i assume it is not getting the 'stable' status, so not sending the right comms over).

i understand awaiting for no changes to then perform the next step is one of the advantages of detox, but could there be a flag where i set a max wait time and move to the next step regardless? i know this could create a potential false-positive crash, but at least it gives the ability to bruteforce testing.
