### ISSUE TITLE
Is it possible to add yarn command to .md?

### ISSUE THREAD

**Issue by hipages-ligang** [wix/Detox#3062]
All the documents just have npm command, is it possible to add yarn command to the documents? It's helpful to developers. Thanks!

**Comment by noomorph** [comment]
Theoretically, yes, but we don't have it in the nearest plans. Putting `looking for contributors` label.

**Comment by noomorph** [comment]
@hipages-ligang , so I investigated this, and it is definitely possible, automatically.

- [ ] add `@docusaurus/remark-plugin-npm2yarn`
