### ISSUE TITLE
Hangs on `Searching for device matching iPhone 7...`

### ISSUE THREAD

**Issue by sam-n-johnston** [wix/detox#307]
#### Description

I'm unable to get detox to launch the simulator. When I follow all the installation instructions, it shows the following text and then hangs forever. But I have an iPhone 7 simulator open and ready. 
```
Searching for device matching iPhone 7...
```
So I downloaded the `react-native-detox-example` and it works correctly (so it isn't a problem with the programs installed with brew). I copied the detox config and test, but I still couldn't get it to work. But when I delete the `yarn.lock` and then `yarn` again, the `react-native-detox-example` gets the same problem as my app. So I assume it's a package (or package version) problem, but I can't figure it out. Maybe someone can shed some light on this? 

#### Steps to Reproduce
Install `react-native-detox-example`
Remove `yarn.lock`
`yarn`
`yarn test-e2e`

#### Node, Device, Xcode and macOS Versions
* Node: 8.4.0
* Device: iPhone 6 & 7
* Xcode: 9.0 (9A235)
* macOS: 10.12.6

**Comment by dsznajder** [comment]
I had the same issue few hours ago but this #304 seems to be resolving problem. Just update/reinstall `applesimutils`.

**Comment by sam-n-johnston** [comment]
This doesn't solve it for me. I installed `applesimutil ` for the first time today. I just tried to uninstall and reinstall, but it still doesn't work.

**Comment by rotemmiz** [comment]
Please provide a verbose detox log to further investigate this issue

**Comment by alex-blair** [comment]
I'm facing a similar issue with my detox tests. I'm getting this error: 
``` 
1)  "before all" hook:
     Error: Can't find a simulator to match with 'iPhone 7', run 'fbsimctl list' to list your supported devices.
It is advised to only state a device type, and not to state iOS version, e.g. 'iPhone 7'
      at Fbsimctl._callee$ (node_modules/detox/lib/devices/Fbsimctl.js:47:19)
      at tryCatch (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as throw] (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
      at step (node_modules/detox/lib/devices/Fbsimctl.js:1:809)
      at node_modules/detox/lib/devices/Fbsimctl.js:1:1008
      at <anonymous>
```
I've tried updating `applesimutil` but I'm still getting the same error. Any ideas?

Node: 8.2.1
Xcode: 9.0 (9A235)
macOS: 10.13.1

**Comment by rotemmiz** [comment]
@alex-blair , seems like you are using a pre Detox 5.8.0 version, update your library and see if it helps

**Comment by alex-blair** [comment]
Thanks @rotemmiz - that fixed it! 🎉

**Comment by sapjax** [comment]
`"detox": "^6.0.2",`   still encounter this problem.
