### ISSUE TITLE
Add timestamps for Detox logging

### ISSUE THREAD

**Issue by shamilovtim** [wix/Detox#3084]
**Is your feature request related to a problem? Please describe.**
Timestamps would help a great deal in logging when debugging failures but we currently don't have them:
<img width="371" alt="Screen Shot 2021-11-18 at 12 43 32 PM" src="https://user-images.githubusercontent.com/3495974/142468514-a1bb4404-f4ff-4a96-b87d-ffb65761b011.png">

**Describe the solution you'd like**
The ability for all of the logging to be timestamped with the date/time

**Describe alternatives you’ve considered**
I have considered adding this ourselves with some kind of helper but I think it would be a messier solution than having it part of the CLI/API

**Comment by noomorph** [comment]
@asafkorem, please write down in advance how do you plan to change the configuration options to implement this.

**Comment by asafkorem** [comment]
@noomorph it seems to me that we should add some session configuration flag param: `showDate`. 
With this, we should configure the `bunyanDebugStream` to show dates (see [bunyan-debug-stream#showdate](https://github.com/benbria/bunyan-debug-stream#showdate)), so I'm not sure where do we need that custom formatted function. Let's discuss this.

**Comment by d4vidi** [comment]
I tend to agree with @asafkorem; I'm not convinced as to why this flexibility is required...
That said, if we do pursue this path then a better option would be an explicit _logging_ configuration, IMO.

**Comment by noomorph** [comment]
Implemented in Detox v20 logger. Removing `stale: label`.
