### ISSUE TITLE
Detox in CI needs a multiTap(2) but locally a tap()

### ISSUE THREAD

**Issue by sajadghawami** [wix/Detox#3085]
Hey there,

### Description

We had detox running perfectly in our pipeline with `detox@17` and `kitten-ui@5.0.0` - so all test would pass, and we had the following:

- In one of our test-cases we have multiple inputs and a checkbox that needs to be selected to be able to continue (basic sign-up)
- We had to use `.multiTap(2)` on the checkbox to firstly release the focus from the last input and to actually be able to check the checkbox

That was fine so far. Now, after we updated, we having the following:

- Locally we had to change the use of `.multiTap(2)` to a single `.tap()` to actually check the checkbox.

This works locally without a problem.

But, now,  whenever i run this in our CI, the `.tap()` *does not* work because the focus will still be on the checkbox so it seems like a `.multiTap(2)` is necessary, which on the other hand won't work locally anymore.

I am a little bit desperate at this point, because i (obviously) cleared everything and tried to replicate this locally, but i am not able to. Locally all my tests run like a charm.

i also upgraded to  `detox@19`, `kitten-ui@5.1.1` and even `react-native` and `expo`.

I am not even sure wether or not this is an actual `kitten-ui` problem, or a `detox` problem that i am facing.

Just to be clear again, before i did the upgrade, everything was working fine. Currently, all the other tests except for the checkbox are working fine.

Does anyone happen to have a clue what i could try next to fix this?

### Environment

 - Detox: 19
 - React Native: 0.64.2
 - Node: 14.18.1
 - Device: iPhone 12 on Simulator with iOS 15
 - OS: Mac
 - jest-circus/jest: 27.3.1

### Detox Config

```
{
  "testRunner": "jest",
  "runnerConfig": "e2e/config.json",
  "configurations": {
    "ios.sim.debug": {
      "name": "iPhone 11",
      "type": "ios.simulator",
      "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/bliks.app",
      "build": "xcodebuild -workspace ios/bliks.xcworkspace -UseNewBuildSystem=YES -scheme bliks -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 11,OS=15.0' -sdk iphonesimulator -derivedDataPath ios/build",
      "device": {
        "type": "iPhone 11",
        "os": "iOS 15.0",
        "name": "iPhone 11"
      },
      "artifacts": {
        "rootDir": "./e2e/screenshots/",
        "pathBuilder": "./e2e/config/pathBuilder.js"
      }
    },
    "ios.sim.release": {
      "name": "iPhone 11",
      "binaryPath": "ios/build/Build/Products/Release-iphonesimulator/bliks.app",
      "build": "export RCT_NO_LAUNCH_PACKAGER=true && xcodebuild -workspace ios/bliks.xcworkspace -UseNewBuildSystem=YES -scheme bliks -configuration Release -destination 'platform=iOS Simulator,name=iPhone 11,OS=15.0' -sdk iphonesimulator -derivedDataPath ios/build",
      "type": "ios.simulator",
      "device": {
        "type": "iPhone 11",
        "os": "iOS 15.0",
        "name": "iPhone 11"
      }
    },
    "android": {
      "type": "android.emulator",
      "binaryPath": "SPECIFY_PATH_TO_YOUR_APP_BINARY",
      "device": {
        "avdName": "Pixel_2_API_29"
      }
    }
  }
}
```

This is the actual test:

```js
...
  it("should sign up a customer", async () => {
    // go to sign in
    await element(by.text(EnglishCommon.signUp)).tap();
    // type in the user information and sign up
    await element(by.id("firstName")).replaceText("Foo");
    await element(by.id("email")).replaceText(`${uniqueID}@tester-mail.com`);
    await element(by.id("password")).replaceText("verysecurepassword");
    await element(by.id("enableNewsletter")).tap(); // <----------- this needs to be a multiTap(2) in the CI
    await element(by.id("submit")).tap();
    await expect(element(by.text("Hello Foo 👋🏼"))).toBeVisible();
  });
...
```

**Comment by noomorph** [comment]
These issues are the hardest to help with (when something fails only on CI). 🤷‍♂️ 
1. Are you sure there's no iOS/Xcode version difference between CI and your local environment?
2. Is your CI using bare-metal machines or virtual machines? If the latter, can you try to run your tests in a virtual machine?

**Comment by ShivamJoker** [comment]
@sajadghawami although if nothing works you can just do the multiTap() by checking if `process.env.CI` is true :)

**Comment by sajadghawami** [comment]
@noomorph 

thanks for the reply!

1. i am 100% positive, though i will check again
2. its a virtual machine (github action)
3. i would try that... the problem here is, since it's running in a github action and i need to run it on a mac-os each minute mac would cost 10 times that of a linux... when my pipeline runs for 30 mins (which it does) it will count as 300 minutes... nonetheless i've run it at least 15-20 times and unfortunately the result is always the same

@ShivamJoker 

thanks... if nothing works, i will try to do that!

**Comment by ShivamJoker** [comment]
@sajadghawami would you mind creating a minimal repo with the same component ?

So that we can test it as well.
Also print the view hierarchy and see if it's different

**Comment by professorkolik** [comment]
Same happens here,
After focus on input need two tap twice on submit button in order to trigger it.

@sajadghawami did you manage to fix it?

**Comment by sajadghawami** [comment]
@professorkolik 

unfortunately not.
Are you also using `kitten-ui`?

**Comment by professorkolik** [comment]
@sajadghawami No I'm not. Amd I don't think that `kitten-ui` is the reason.
As a `quick fix` for me helped to decrease xCode version on CI (I use Bitrise). It was 13.1 and on local environment I have 13.0..

Another suggestion would be to tap somewhere before you tap to checkbox, so your input will be unfocused.
That might help to fix your multiTap on CI, so this way you don't need to write different code for CI and local

**Comment by d4vidi** [comment]
@sajadghawami somehow we've managed to overlook this issue - sorry about that.
Just to be sure I understand correctly: Technically, the _right_ way to write the test is using `.tap()`, not `.multiTap()`. Is that correct? If that is the case, it would be helpful if you could test a theory and add an `await sleep(500)` before the tap and report whether that helps on CI. `sleep` being:
```js
const sleep(ms) = new Promise((resolve) => setTimeout(ms, resolve));
```

**Comment by sajadghawami** [comment]
> @sajadghawami somehow we've managed to overlook this issue - sorry about that. Just to be sure I understand correctly: Technically, the _right_ way to write the test is using `.tap()`, not `.multiTap()`. Is that correct? If that is the case, it would be helpful if you could test a theory and add an `await sleep(500)` before the tap and report whether that helps on CI. `sleep` being:
> 
> ```js
> const sleep(ms) = new Promise((resolve) => setTimeout(ms, resolve));
> ```

@d4vidi  Thanks for the reply and sorry for the late response.
So we had to remove the e2e tests for a while, but now i came back to test it with the sleep method you provided... and strangely, everything seems to be working now - without using sleep 🤷‍♂️...
I am not sure and how and why it disappeared. 

Anyway, its working now and thank you 🙏.

**Comment by d4vidi** [comment]
@sajadghawami well, that's good news, although ideally I would like to know the root cause for this inconvenience 😅 Anyways, thanks for letting us know!
