### ISSUE TITLE
Make the timeline artifact more useful

### ISSUE THREAD

**Issue by noomorph** [wix/Detox#3088]
**Is your feature request related to a problem? Please describe.**

The timeline artifact contains just a few basic events, while it could have contained also how long the expectations/actions take to execute (due to idling resource synchronization). Also, we could have added more things regarding CLI commands execution (let's say in a verbose mode), etc.
 
![image](https://user-images.githubusercontent.com/1962469/142661106-d23d9642-0fce-4a1c-95ed-3ffc3580534d.png)

**Describe the solution you'd like**

More data.

**Comment by d4vidi** [comment]
@noomorph Does this add any important info to your current work on this?
