### ISSUE TITLE
Social Login using Apple/Facebook

### ISSUE THREAD

**Issue by kokiebisu** [wix/Detox#3099]
Hi Detox team! First off, thanks for the great package. Absolutely loving it!

### Description
I want to be able to test my logins for Apple and Facebook. Since the permission modal is out of the detox scope, not sure how I can workaround this. Is there any way we can set up a configuration in the launchApp method perhaps?

As a side note, I am using the AWS amplify framework to cover the authentication logic. 
```ts
import Auth from "@aws-amplify/auth";

// some logic ...

await Auth.federatedSignIn({
    provider: CognitoHostedUIIdentityProvider.Apple,
});
```

### Environment

 - Detox: 19.1.0
 - React Native: 0.63.4
 - Node: 14.18.1
 - Device: iPhone11
 - OS: iOS 15
 - Test-runner (select one): jest-circus
 
<img width="438" alt="Screen Shot 2021-11-23 at 9 09 53" src="https://user-images.githubusercontent.com/43525282/142953585-3b7bd3b3-bf9a-44b8-920e-7c7576c05d28.png">

**Comment by noomorph** [comment]
@asafkorem , do we have an ability to dismiss or set a default permission for this type of notification? Could you check, pls?

**Comment by asafkorem** [comment]
@noomorph @kokiebisu there isn't any documented / suggested way by Apple to do so.
However, [This blog post](https://msolarana.netlify.app/2019/12/07/ui-testing-aswebauthenticationsession/) address this issue, and the suggested solution there is to grab the first alert from the springboard process.

While in the post they did it with XCUITest methods (and we are not supporting it, yet), I'll check if that's something we can do with our current infrastructure for iOS.

**Comment by noomorph** [comment]
@asafkorem , I assume you weren't lucky to find a quick way to implement this via applesimutils?

**Comment by asafkorem** [comment]
@noomorph as of iOS 15.0, these are the permissions (or more accurate: **Private Frameworks**) we are able to set:
```
kTCCServiceAll
kTCCServiceAddressBook
kTCCServiceContactsLimited
kTCCServiceContactsFull
kTCCServiceCalendar
kTCCServiceReminders
kTCCServiceTwitter
kTCCServiceFacebook
kTCCServiceSinaWeibo
kTCCServiceLiverpool
kTCCServiceUbiquity
kTCCServiceTencentWeibo
kTCCServiceShareKit
kTCCServicePhotos
kTCCServicePhotosAdd
kTCCServiceMicrophone
kTCCServiceCamera
kTCCServiceWillow
kTCCServiceMediaLibrary
kTCCServiceSiri
kTCCServiceMotion
kTCCServiceSpeechRecognition
kTCCServiceUserTracking
kTCCServiceBluetoothAlways
kTCCServiceWebKitIntelligentTrackingPrevention
kTCCServicePrototype3Rights
kTCCServicePrototype4Rights
kTCCServiceGameCenterFriends
kTCCServiceBluetoothPeripheral
kTCCServiceBluetoothWhileInUse
kTCCServiceKeyboardNetwork
kTCCServiceMSO
kTCCServiceCalls
kTCCServiceFaceID
kTCCServiceSensorKitMotion
kTCCServiceSensorKitWatchMotion
kTCCServiceSensorKitLocationMetrics
kTCCServiceSensorKitAmbientLightSensor
kTCCServiceSensorKitWatchAmbientLightSensor
kTCCServiceSensorKitWatchHeartRate
kTCCServiceSensorKitWatchOnWristState
kTCCServiceSensorKitKeyboardMetrics
kTCCServiceSensorKitWatchPedometer
kTCCServiceSensorKitPedometer
kTCCServiceSensorKitWatchFallStats
kTCCServiceSensorKitWatchForegroundAppCategory
kTCCServiceSensorKitForegroundAppCategory
kTCCServiceSensorKitWatchSpeechMetrics
kTCCServiceSensorKitSpeechMetrics
kTCCServiceSensorKitMotionHeartRate
kTCCServiceSensorKitOdometer
kTCCServiceSensorKitElevation
kTCCServiceSensorKitStrideCalibration
kTCCServiceSensorKitDeviceUsage
kTCCServiceSensorKitPhoneUsage
kTCCServiceSensorKitMessageUsage
kTCCServiceSensorKitFacialMetrics
kTCCServiceExposureNotification
kTCCServiceExposureNotificationRegion
kTCCServiceFallDetection
kTCCServiceSensorKitBedSensing
kTCCServiceSensorKitSoundDetection
kTCCServiceSensorKitBedSensingWriting
kTCCServiceNearbyInteraction
kTCCServiceUserAvailability
kTCCServiceFocusStatus
```

This can be listed using the command:
```
 strings /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/TCC.framework/TCC | grep kTCCService
```

Seems that:
1. we can allow more permissions settings for apple's private frameworks using AppleSimUtils (from what we currently have). Including `kTCCServiceAll` (which means, allow **all**).
2. this web authentication session request doesn't seems to be one of them (public framework), moreover it appears to be a non-cached approval, so it makes sense in some way.

**Comment by asafkorem** [comment]
@d4vidi came up with an idea to provide some API that presses on alert's buttons by their coordinate on the screen, however calculating the coordinate depends on the message length (which we don't have access to), localizations (including LTR, RTL) and device model (screen size).
Also, it might not be possible because the alert isn't part of the app (and is part of the SpringBoard application), I'll explore this idea today.
