### ISSUE TITLE
tap button only if exists

### ISSUE THREAD

**Issue by pdaniloais** [wix/detox#310]
In my test, I would like to simulate a tap in the "cancelUpgrade" button only if it is displayed:

    it('should be in home menu', async () => {
      await waitFor(element(by.id('cancelUpgrade')))
        .toBeVisible()
        .withTimeout(2000);
      await element(by.id('cancelUpgrade')).tap();
    });

It returns the expected error `Error: Cannot find UI element.`

**Comment by aamorozov** [comment]
@pdaniloais You can wrap tap in the `try/catch` block:
```
try {
 await element(by.id('elemID')).tap();
} catch (e) {
 // next step in case the element is not displayed
}
```
Not the best way but i think that's what currently possible within detox

**Comment by pdaniloais** [comment]
Thx a lot ;)
