### ISSUE TITLE
Artifact contains special characters which are not supported by artifacts upload in github actions

### ISSUE THREAD

**Issue by olexandr13** [wix/Detox#3101]
Artifact contains special characters which are not supported by artifacts upload in github actions
```
profile/visibilityFailingRects/DETOX_VISIBILITY_RNSVGSvgView <0x7fd1fb77a610>_TEST.png. Contains character: "<". Invalid characters include: ",:,<,>,|,*,?.
```
**Action:** actions/upload-artifact@v2

**Describe the solution you'd like**
Make artifacts to not contain special characters which are not supported by Github Actions.

**Comment by noomorph** [comment]
@olexandr13, thanks for the report. I can see where it comes from. These files just get copied recursively and do not undergo the sanitation. I'll see if it can be fixed soon.

**Comment by noomorph** [comment]
I hope #3102 lands quickly, but please bare with us if it doesn't. I hope for the best, anyway.
