### ISSUE TITLE
Detox example projects: demo-react-native-jest missing build

### ISSUE THREAD

**Issue by teeryt** [wix/Detox#3106]
### Description
I'm trying to run the demo project `demo-react-native-jest`, it's missing a build script. How do I actually get it to build on my emulator and start running the example tests?

### Environment

 - Detox:
 - React Native:
 - Node:
 - Device:  Nexus 9 API 29
 - OS: macOS Monterey 12.0.1 ARM64
 - Test-runner (select one): `jest-circus`

**Comment by noomorph** [comment]
Check out `demo-react-native` – it has the build command you need. The point that the demo app is being built from only one place, and the other `demo-*` apps just reference it. Maybe we should change it, indeed. 🤔 

Thanks for raising the point.

**Comment by teeryt** [comment]
Right I see. So I guess the steps are to to?
- `cd detox`
- `npm run build:android`
- `cd .. cd examples/demo-react-native`
- `npm run build:android-release`

Then you can run tests on any of the example projects?

However the `npm run build:android` build command in step 1 fails for me.
`Execution failed for task ':detox:compileFullReleaseKotlin'.`

**Comment by noomorph** [comment]
Since this is now a single example project, I think this is no longer an issue.
