### ISSUE TITLE
docs: improve getting started

### ISSUE THREAD

**Issue by noomorph** [wix/Detox#3107]
**Is your feature request related to a problem? Please describe.**

See the current page: https://wix.github.io/Detox/docs/introduction/ios

![easy-to-say](https://user-images.githubusercontent.com/1962469/143428060-5ffbe7f9-76f1-4bf2-b568-42c64c6f1c3c.png)

**Describe the solution you'd like**

Describe somehow less vaguely that the user needs to write a command similar to this one:

```
xcodebuild -workspace ios/MyProject.xcworkspace -configuration Debug -scheme MyProject -sdk iphonesimulator -derivedDataPath ios/build
```

**Comment by asafkorem** [comment]
@noomorph in the introduction doc, we refer the user to the configuration API guide:
![image](https://user-images.githubusercontent.com/55082339/143442516-48e641c6-7d35-44d8-9880-7eb2fa002971.png)

https://wix.github.io/Detox/docs/api/configuration#detox-cli:

> - Building with `xcodebuild`:
> 
>   ```sh
>   xcodebuild -project ios/YourProject.xcodeproj -scheme YourProject -sdk iphonesimulator -derivedDataPath ios/build
>   ```

However, I agree that we can (and should) be clearer there.
