### ISSUE TITLE
Skip Emulator launcher on testing

### ISSUE THREAD

**Issue by oximer** [wix/detox#311]
I  want to skip all the emulator and app launching step.
I'm interesting on only run my test. 
Assume that the app and the emulator are already executing.
It's possible?

When executing "Detox test" it goes trough all those steps.

**Comment by aamorozov** [comment]
@oximer I think you should be able to do it by starting your test case with 

```
await device.launchApp({newInstance: false}); // assuming that the app has been already built within detox build
```

**Comment by simonracz** [comment]
@oximer You can try to invoke the test runner directly. For example:

```bash
node_modules/.bin/mocha ./e2e/ --opts e2e/mocha.opts --configuration your.config
```

**Comment by LeoNatan** [comment]
It's possible. Use `none` as your target in the package.json config.

**Comment by oximer** [comment]
@LeoNatan 

I add something like this and it did work.

```
"detox": {
    "configurations": {
      "android.emu.debug": {
        "binaryPath": "android/app/build/outputs/apk/app-debug.apk",
        "build": "pushd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && popd",
        "type": "android.emulator",
        "name": "none"
      }
    }
  }
```
