### ISSUE TITLE
Multi-process support for Detox Android

### ISSUE THREAD

**Issue by yongjiliu** [wix/Detox#3113]
**It is very possible that the page is in a different process.**
For example pageA In process 1, pageB In process 2, It is impossible to test pageA and pageB at the same time

**Describe alternatives you’ve considered**
Is it possible that support multi-process testing based on espresso remote
https://developer.android.com/training/testing/espresso/multiprocess

**Comment by d4vidi** [comment]
Hi @yongjiliu,

ATM Detox doesn't come with this setup out of the box. But according to the guide (as per your ref) it appears that this is very likely something you can easily add to your own app and see. If you do so, please report back so as to let us know 🙏🏻
