### ISSUE TITLE
Android/iOS behave differently with toHaveLabel

### ISSUE THREAD

**Issue by jonathanmos** [wix/Detox#3119]
On Android a view only has a contentDescription if the accessibilityLabel prop is explicitly set. On iOS, RN native views implicitly return an accessibilityLabel -> see RCTViewComponentView.mm (thanks to @asafkorem) - the accessibilityLabel of the parent is a concatenation of the accessibilityLabels of all the child views, and every child view implicitly receives an accessibilityLabel that is equal to it's text (if none was provided explicitly).

https://github.com/facebook/react-native/blob/3ba237b663215f66334bbe6f43a35a0a311dcf5c/React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm#L675

Both android/ios toHaveLabel matchers search the given id to see if the label exists. On Android the label doesn't exist because it has to be explicitly set, but on iOS it exists because it is implicitly set as a concatenation of descendants.

We should update the documentation to be clear about this difference in behavior.

Example:

```
<TouchableOpacity testID={testIDs.MY_NESTED_TEXT}>
   <Text>
      {'test123'}
   </Text>
</TouchableOpacity>

expect(element(by.id(testIDs.MY_NESTED_TEXT))).toHaveLabel('test123');
```

Passes on ios, fails on android.

**Comment by jonathanmos** [comment]
[I opened an issue regarding this on the RN project](https://github.com/facebook/react-native/issues/32826)

**Comment by d4vidi** [comment]
@jonathanmos Best if we update Detox's documentation on `.toHaveLabel()`. WDYT?

**Comment by asafkorem** [comment]
@d4vidi he already updated it: https://wix.github.io/Detox/docs/api/expect/#tohavelabellabel

**Comment by d4vidi** [comment]
🤯
