### ISSUE TITLE
Using retries flag while running tests on CI CD retries only the failed spec but ignores the rest of the specs in the directory

### ISSUE THREAD

**Issue by rajathrao** [wix/Detox#3121]
### Description

We are trying to rerun failed spec on CI CD - Bitrise. But the retry happens when the test fails but ignores all the other specs in the same directory and says that the tests passed without even running all the specs in the directory. 

Ex - we are using something like `detox test --configuration android.emu.release.e2e --take-screenshots --retries 3 failing --retries 3 --workers=1 --jest-report-specs --bail -H`
### Environment

 - Detox: `17.6.1`
 - React Native:`0.65.2`
 - Node:
 - Device: Bitrise Pipelines - Android Emulator (Pixel)   and also the same setup on Local
 - OS: Mac OS X 
 - Test-runner (select one): `jest`
Able to reproduce both locally and on CI CD Bitrise

**Comment by MuckT** [comment]
Have you tried [jest.retryTimes()](https://jestjs.io/docs/jest-object#jestretrytimes) instead?

**Comment by rajathrao** [comment]
> Have you tried [jest.retryTimes()](https://jestjs.io/docs/jest-object#jestretrytimes) instead?

Yes, but it does not work as desired.  The `retries` flag reloads the app and runs the test again whereas `jest.retryTimes() `tries to run that specific `it` block which more often than not fails. Do you think this is a bug ? Is there a work around?

**Comment by MuckT** [comment]
Are you using `await device.reloadReactNative()` in a beforeAll? Are your `it` blocks dependent on previous `it` blocks passing? Do you have any sample code you can share?

**Comment by rajathrao** [comment]
> Are you using `await device.reloadReactNative()` in a beforeAll? Are your `it` blocks dependent on previous `it` blocks passing? Do you have any sample code you can share?

Ok, let me share. But, is there any work around for the retries flag though ?

**Comment by rajathrao** [comment]
Below sample is of a` it `block which keeps failing . this case i tried` jest.retryTimes()`. though it doesnt depend on previous state but since say it fills a form and on retries I think it tries to do the same and fails. Also, I am not using await `device.reloadReactNative()` in this case.  This is one example but the result is the same for other it blocks too. Also the use case here is - sometimes the android tests are flaky and that is why I am trying this option for CI CD. If you have any specific suggestion for Android do let me know ! :) 

```
it(' name field contains an emoji', async () => {

    if (device.getPlatform() === 'ios') {
      await element(by.id('p')).replaceText('🗿');
    } else {
      await element(by.id('p')).replaceText('😁');
    }
    await sleep(500);

    await waitFor(element(by.id('a')))
      .toBeVisible()
      .whileElement(by.id('capture-scrollview'))
      .scroll(200, 'down');
    await element(by.id('a')).tap();
    await waitFor(element(by.id('ai')))
      .toBeVisible()
      .withTimeout(5000);
    await element(by.id('ai')).clearText();
    await element(by.id('ai')).typeText('123 Fake');
    await waitFor(element(by.id('a0')))
      .toBeVisible()
      .withTimeout(5000);
    await element(by.id('a0')).tap();

    await element(by.id('cs')).scrollTo('bottom');
    await element(by.id('di')).tap();
    await element(by.id(`d1`)).tap();

    if (device.getPlatform() === 'ios') {
      expect(element(by.id('pi'))).toHaveText('🗿');
    } else {
      expect(element(by.id('pi'))).toHaveText('😁');
    }
    expect(element(by.id('av'))).toHaveText('123 Fake');
    expect(element(by.id('dt'))).toHaveText('Roof Only 3D');
    await waitFor(element(by.id('sc')))
      .toBeVisible()
      .withTimeout(5000);
    await element(by.id('sc')).tap();
    await sleep(2000);
    await expect(element(by.id('carousel'))).not.toBeVisible();
  });
```

**Comment by MuckT** [comment]
Try adding a `beforeEach` to your `describe` block. It'll slow down your tests, but you should have a consistent starting state for each `it` block. [examples/demo-react-native-jest](https://github.com/wix/Detox/blob/master/examples/demo-react-native-jest/e2e/app-hello.e2e.ts) uses this.
```JavaScript
  beforeEach(async () => {
    await device.reloadReactNative()
  })
```
