### ISSUE TITLE
Unable to get the current location value. (POSITION_UNAVAILABLE)

### ISSUE THREAD

**Issue by jb9229** [wix/Detox#3127]
### Description
An error occurs when you bring up the current position value of the location.

#### Code:
```
import Geolocation from '@react-native-community/geolocation';
~~~~
Geolocation
  .getCurrentPosition((position: any) => {}, (error) => {console.error(error)})
```

#### Error Message:
error = { code: 2,
  message: 'Unable to retrieve location.',
  PERMISSION_DENIED: 1,
  POSITION_UNAVAILABLE: 2,
  TIMEOUT: 3 }

### Environment

 - Detox: 18.22.2
 - React Native: 0.63.4
 - Node: v14.17.0
 - Device: iPhone 12 pro max(Simulator)
 - OS: IOS
 - Test-runner (select one): `jest-circus`

**Comment by asafkorem** [comment]
@jb9229 can you try to launch the app with location permissions through the `launchApp` API?
```js
await device.launchApp({ permissions: { location: 'always' } });
```

Also use the `setLocation` API to configure your current position:
https://github.com/wix/Detox/blob/5e2b1d3ddd780af880f949b52ff9dc7e869c02a7/detox/index.d.ts#L611

**Comment by samuelvisscher** [comment]
I'm experiencing the same issue with:

react-native-geolocation-service

When running the app normally it works without a problem, but when running through detox test, with the script suggested by asafkorem (and/or with setLocation) I receive the same error as jb9229.

The permission shows as granted, but no location coordinates are coming through.

**Comment by Livijn** [comment]
I'm experiencing the same issue, however I am using Expo. The error I receive is: 
> Cannot obtain current location: Error Domain=kCLErrorDomain Code=0 "(null)"

However, if I run the `idb set-location` command when the fetch is in progress, I get a location. But only if I first "refresh" the app (but still launched with Detox).
