### ISSUE TITLE
(iOS) crashes (signal 6) due to missing UI components --

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#3137]
Try to see whether can be reported by the tester (not only the native side)

TC ref: 
http://tc.dev.wixpress.com/viewLog.html?buildId=129976631&tab=buildResultsDiv&buildTypeId=wix_one_groups_r_d774f_02

(artifact: http://tc.dev.wixpress.com/repository/download/wix_one_groups_r_d774f_02/129976631:id/places.ios.release.2021-12-14%2015-20-41Z/44FFE6DA-0F75-4EA7-B554-E90338C48FE4%202021-12-14%2015-22-30Z.startup.log)

https://wix.slack.com/archives/C6C38SVS4/p1639501807308300

**Comment by noomorph** [comment]
Looks like there is no objective reason to close it, but if we won't be able to retrieve the logs, artifacts – we should close it again.
