### ISSUE TITLE
Detox cant find element by RTL text

### ISSUE THREAD

**Issue by kholood-ea** [wix/Detox#3139]
### Description
detox cant seem to find element by text when text is written in other then english for ex:

this test passes ✅
```
<View flex><Text>Home page</Text> </View>

it('should show home page text ', async () => {
    await expect(element(by.text('Home page'))).toBeVisible();
});
```
but this one doesn't ❌
```
<View flex><Text>الرئيسية</Text> </View>

it('should show home page text', async () => {
    await expect(element(by.text('الرئيسية'))).toBeVisible();
  });
```
### Environment

 - Detox:19.3.1
 - React Native:0.64.1
 - Node:12.19.0
 - Device: iphone 13 pro max
 - OS: ios
 - Test-runner (select one): `jest-circus`

**Comment by sheydarezaee** [comment]
experiencing the same ☝🏽

**Comment by noomorph** [comment]
Assigning myself before I create a test case in Detox E2E repo.

**Comment by noomorph** [comment]
Hmm, I'll put this into iteration scope.

**Comment by noomorph** [comment]
I'm afraid I have to close this issue because no demo project was provided.  I tried the same in https://github.com/wix/Detox/pull/3985, but it works. 🤷
