### ISSUE TITLE
Error: Multiple interactions taking place simultaneously on await waitFor

### ISSUE THREAD

**Issue by jpoisch** [wix/Detox#3141]
### Description
When we updated  to  19.3.1, we now get the following error while executing an async await function like below:

Detox doc's example:
`await waitFor(element(by.text('Text5'))).toBeVisible().whileElement(by.id('ScrollView630')).scroll(50, 'down');`

The step in our framework (notice its identical):
```
Given(
  'I scroll to {string}',
  async function (elemText) {
    await waitFor(element(by.text(elemText)))
      .toBeVisible()
      .whileElement(by.id(ourId))
      .scroll(300,"down");
  },
);
```

```
DetoxRuntimeError: The pending request #1379 ("invoke") has been rejected due to the following error:
Detox has detected multiple interactions taking place simultaneously. Have you forgotten to apply an await over one of the Detox actions in your test code?
    at _callee6$ (/Users/administrator/actions-runner/_work/x-Mobile/x-Mobile/e2e/features/step_definitions/qa.js:147:8)
    at tryCatch (/Users/administrator/actions-runner/_work/x-Mobile/x-Mobile/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/Users/administrator/actions-runner/_work/x-Mobile/x-Mobile/node_modules/regenerator-runtime/runtime.js:274:22)
    at Generator.prototype.(computed) [as next] (/Users/administrator/actions-runner/_work/x-Mobile/x-Mobile/node_modules/regenerator-runtime/runtime.js:97:21)
    at tryCatch (/Users/administrator/actions-runner/_work/x-Mobile/x-Mobile/node_modules/regenerator-runtime/runtime.js:45:40)
    at invoke (/Users/administrator/actions-runner/_work/x-Mobile/x-Mobile/node_modules/regenerator-runtime/runtime.js:135:20)
    at /Users/administrator/actions-runner/_work/x-Mobile/x-Mobile/node_modules/regenerator-runtime/runtime.js:170:11
    at new Promise ((anonymous))
```

- [x] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

This is happening in 19.3.1 for us, and our last version where the bug did not occur was 18.22.2.

#### Expected behavior

We are using essentially the exact same code that you provide in the docs: https://github.com/wix/Detox/blob/master/docs/APIRef.ActionsOnElement.md#whileelementelement

It should scroll to the element as expected.

#### Environment

 - Detox: 19.3.1
 - React Native: ^0.66.4
 - Node: 16.13.0
 - Device: iPhone 13 simulator / Android emulators
 - Xcode: 13.0.0
 - iOS: 13
 - macOS: Big Sur 11.6
 - Test-runner (select one): `jest-circus` | `jest-jasmine2` (deprecated) | `mocha`

#### If you are experiencing a timeout in your test

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much), I have read [synchronization debug documentation](https://github.com/wix/DetoxSync/blob/master/IdleStatusDocumentation.md) and am providing the relevant synchronization debug output below:

#### If you are seeing a Detox build problem (e.g. during `npm install`, not `detox build`)

- [ ] I am providing the `npm install` log below:

<details>
 <summary>Npm logs</summary>
 <code>
 (paste logs here)
 </code>
</details>

#### Device and verbose Detox logs

- [ ] I have run my tests using the `--loglevel trace` argument and am providing the verbose log below:

<details>
 <summary>Detox logs</summary>
 <code>
 (paste logs here)
 </code>
</details>

<details>
 <summary>Device logs</summary>
 <code>
 (paste logs here)
 </code>
</details>

**Comment by asafkorem** [comment]
@jpoisch it's a bit hard to understand what is the real issue here, what test-runner do you use?

**Comment by asafkorem** [comment]
I'm mostly not sure what `Given(..)` syntax stands for, is that your custom method? is it possible that the passed `function` isn't called with `await`?

**Comment by jpoisch** [comment]
> I'm mostly not sure what `Given(..)` syntax stands for, is that your custom function? is it possible that the passed `function` isn't called with `await` from where it is used?

Hi @asafkorem, the `Given` is just a Cucumber step we use in the feature files. I believe this has nothing to do with the issue. Regardless, we're using the following if it helps to replicate:

`"cucumber": "^6.0.5"`
https://cucumber.io/docs/installation/javascript/

**Comment by owjsub** [comment]
I'm not sure if this helps, but after updating from detox 18.9.0 -> 19.4.1, I noticed some strange behavior in testing with `waitFor` & `whileElement` per https://github.com/nubank/detox/blob/master/docs/APIRef.waitFor.md#whileelementelement:
```
await waitFor(element(by.text('Text5'))).toBeVisible().whileElement(by.id('ScrollView630')).scroll(50, 'down');
await expect(element(by.text('Text5'))).toBeVisible();
```

In tests where a `describe` has a single `it`, the above works as expected. However, when I had multiple `it`, the test failed on `await expect(element(by.text('Text5'))).toBeVisible();`. I was able to workaround this by replacing the `expect` with another `waitFor` as follows:
```
await waitFor(element(by.text('Text5'))).toBeVisible().whileElement(by.id('ScrollView630')).scroll(50, 'down');
await waitFor(element(by.text('Text5'))).toBeVisible().withTimeout(5000);
```

**Comment by asafkorem** [comment]
@jpoisch sorry, I'm still missing with some context regarding the issue, the provided test and error message don't give me much information..

Note that it's likely that you are not using `await` on some other `async` method and that what causes the error here. Can you try to execute this test alone? Also, please check your other tests and see if there's another test that doesn't use `await` properly.

In case you still having this problem, can you please provide me the device & detox logs of the tests execution? 
* Detox logs can be obtained by passing the `loglevel` param.
* Device logs can be obtained by passing the `--record-logs all` param.

i.e. `detox test --record-logs all  --loglevel trace ...` (see [artifacts doc](https://wix.github.io/Detox/docs/api/artifacts) for more info).

**Comment by d4vidi** [comment]
@jpoisch the original problem is clearly due to the introduction of the associated feature in Detox [`19.2.0`](https://github.com/wix/Detox/releases/tag/19.2.0). Would be good to get your _device_ (simulator) logs and see.

**Comment by sierisimo** [comment]
Hi, I'm having a similar issue. From my side, the thing started just after I added a second `it(..., async () => { ... })` to my tests, even when I'm using `await` like: `await expect(element(by.id(...))).toBeVisible()`  my tests fail with the legend:

> DetoxRuntimeError: The pending request #4 ("invoke") has been rejected due to the following error:
> Detox has detected multiple interactions taking place simultaneously. Have you forgotten to apply an await over one of the Detox actions in your test code?

Strangely the lines suggested by Detox about the problem include the await and everything: 

```
      13 |    async assertVisible(): Promise<void> {
      14 |         await expect(element(by.id('arrowBackBtn'))).toBeVisible();
    > 15 |         await expect(element(by.id('contentWebView'))).toBeVisible();
         |                                                        ^
      16 |
      17 |         return new Promise(resolve => resolve());
      18 |     }
```

...and my understanding is that @jpoisch and @owjsub are seeing the same error which makes no sense. 

Also, the approach of replacing `expect` with `waitFor` did nothing in my case, I'm still seeing the error of **_multiple interactions taking place simultaneously_**, it does not matter is is checking for visibility or trying a `tap()`. It fails with more than 1 `it(...)` case.

**Comment by jamesmcn1** [comment]
I am getting a similar error. Have raised it in a seperate issue https://github.com/wix/Detox/issues/3284

**Comment by d4vidi** [comment]
@jpoisch / others, we would very much appreciate you rerunning your tests with the `--loglevel trace` argument to `detox test`, then pasting the logs here 🙏🏻
Or better yet, use our [template project](https://github.com/wix-incubator/DetoxTemplate) in order to reproduce in a clean, shared environment.

**Comment by sierisimo** [comment]
I was not able to reproduce the bug in the template project and also my project magically started working for some reason, I think some dependency related to jest or something changed but I'm unable to identify what was the change since I originally had the issue.

Thanks for your help @d4vidi
