### ISSUE TITLE
Network request doesn't finish when testing video/audio conference room

### ISSUE THREAD

**Issue by Calinteodor** [wix/Detox#3144]
### Description

I investigate mobile automation tests on Jitsi mobile app with Detox. 
I wrote some tests that run as expected on our welcome screen.
The problem is, when I navigate from the welcome screen to the actual conference room, I end up with this, multiple times in the terminal, and the test doesn't move to the next step.

-----
detox[17701] INFO:  Jitsi Meet App: is audio/video muted
detox[17701] INFO:  [APP_STATUS] The app is busy with the following tasks:
• Run loop "Main Run Loop" is awake.
• There are 1 work items pending on the dispatch queue: "Main Queue (<OS_dispatch_queue_main: com.apple.main-thread>)".
• 1 enqueued JavaScript timers:
  - Timer #1:
    + JS timer ID: 444.
    + Duration: 0.1.
    + Is recurring: NO.
detox[17701] INFO:  [APP_STATUS] The app is busy with the following tasks:
• Run loop "Main Run Loop" is awake.
• There are 1 work items pending on the dispatch queue: "Main Queue (<OS_dispatch_queue_main: com.apple.main-thread>)".
• 1 enqueued JavaScript timers:
  - Timer #1:
    + JS timer ID: 549.
    + Duration: 0.1.
    + Is recurring: NO.
-----

### Test
describe('Jitsi Meet App', () => {
    beforeAll(async () => {
        await device.launchApp({
            permissions: {
                camera: 'YES',
                microphone: 'YES'
            }
        });

        await device.setURLBlacklist([
            '.*meet\.jit\.si.*',
            '.*api2\.amplitude\.com.*'
        ]);
    });

    beforeEach(async () => {
        await device.reloadReactNative();
    });

    it('is audio/video muted', async () => {
        const roomName = 'TestMyRoomOrGoHome';

        await expect(element(by.id('room-name-input'))).toBeVisible();
        await element(by.id('room-name-input')).tap();
        await element(by.id('room-name-input')).typeText(roomName);
        await element(by.id('join-room-button')).tap();
        await expect(element(by.id('audio-mute-button'))).toBeVisible();
        await element(by.id('audio-mute-button')).tap();
    });
});

### Environment

 - Detox: 19.3.1
 - React Native: 0.61.5-jitsi.2
 - Node: 14.18
 - Device: iPhone 13 Pro simulator / Android emulators
 - OS: Big Sur 11.6
 - Xcode: 13.0.0
 - iOS: 15
 - Test-runner (select one): `jest`

**Comment by asafkorem** [comment]
Hi @Calinteodor, sorry, I totally missed this issue! Is it resolved?

**Comment by Calinteodor** [comment]
> Hi @Calinteodor, sorry, I totally missed this issue! 😞 Is it resolved?

Yes. I managed to fix it. Thanks!

**Comment by asafkorem** [comment]
OK great, glad to hear that

**Comment by Himani33** [comment]
Hi @Calinteodor... I am interested to know how did you resolve the issue as I am facing the same failure in detox Mobile tests where my mobile app also settings the "Microphone" permission in launchApp() and settings device.setURLBlacklist(['.*browser.com*' ]);

Thank you in advance!

**Comment by Himani33** [comment]
Ok thanks for the reply :)
