### ISSUE TITLE
Is there a way to run the e2e test on firebase test lab

### ISSUE THREAD

**Issue by HackGod2000** [wix/Detox#3151]
### Description

Is there a way to run the e2e test on firebase test lab , so that i can test my UI test on multiple devices .

### Environment

 - Detox: latest
 - React Native: latest
 - Node:latest
 - Device:
 - OS: 
 - Test-runner (select one): `mocha`

**Comment by d4vidi** [comment]
This issue is related: #2830.
I don't think there's a point in trying to run Detox on firebase test lab, because it runs native tests and in a Detox environment all JS tests are run under that same test, dispatched over and over again.
