### ISSUE TITLE
Detox fails launching with error: "Unable to obtain a list of simulators"

### ISSUE THREAD

**Issue by shamilovtim** [wix/Detox#3154]
### Description
Starting to see far more occurrences of a flakey launch error. It seems to happen when calling

```javascript
await device.launchApp({
    permissions: {
      camera: cameraPermissions,
      location: locationPermissions,
      notifications: notificationsPermissions,
      userTracking: 'NO'
    }
  });
```

Based on artifact screenshots / videos, the app is opened successfully but Detox crashes out with that error.

The error is as follows:
```
detox[7707] INFO:  [AppleSimUtils.js] com.shipt.groceries-staging launched. To watch simulator logs, run:
        /usr/bin/xcrun simctl spawn 760EAD26-C92A-42B7-9252-DF691A8E8FDF log stream --level debug --style compact --predicate 'process == "Shipt"'
detox[7707] INFO:  orders coupon tests is assigned to 760EAD26-C92A-42B7-9252-DF691A8E8FDF (iPhone 13 Pro Max)
detox[7707] INFO:  orders coupon tests: should signup for account and create order
detox[7707] ERROR: [EXEC_FAIL, #58] "applesimutils --byId 760EAD26-C92A-42B7-9252-DF691A8E8FDF --bundle com.shipt.groceries-staging --restartSB --setPermissions camera=YES,location=always,notifications=YES,userTracking=NO" failed with error = ChildProcessError: Command failed: applesimutils --byId 760EAD26-C92A-42B7-9252-DF691A8E8FDF --bundle com.shipt.groceries-staging --restartSB --setPermissions camera=YES,location=always,notifications=YES,userTracking=NO
Error: The data couldn’t be read because it isn’t in the correct format.. See “applesimutils --help” for usage.
Error: Unable to obtain a list of simulators. See “applesimutils --help” for usage.
 `applesimutils --byId 760EAD26-C92A-42B7-9252-DF691A8E8FDF --bundle com.shipt.groceries-staging --restartSB --setPermissions camera=YES,location=always,notifications=YES,userTracking=NO` (exited with error code 255) (code=255), stdout and stderr:

detox[7707] ERROR: [EXEC_FAIL, #58] 
detox[7707] ERROR: [EXEC_FAIL, #58] Error: The data couldn’t be read because it isn’t in the correct format.. See “applesimutils --help” for usage.
Error: Unable to obtain a list of simulators. See “applesimutils --help” for usage.
```

- [x] I have tested this issue on the latest Detox release and it still reproduces

#### Reproduction

Provide the steps necessary to reproduce the issue. If you are seeing a regression, try to provide the last known version where the issue did not reproduce.

1. Call `await device.launchApp()` on CI
2. receive the above error. Based on artifact screenshots / videos, the app is opened successfully but Detox crashes out with that error.

#### Expected behavior

Expect Detox to run

#### Environment
 - Detox: 19.4.1
 - React Native: 0.65.2
 - Node: 14.17.3
 - Device: 13 Pro Max Simulator
 - Xcode: 13.2.1
 - iOS: 15.2
 - macOS: 11.6
 - Test-runner (select one): `jest-circus` 

#### If you are experiencing a timeout in your test

- [x] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much), I have read [synchronization debug documentation](https://github.com/wix/DetoxSync/blob/master/IdleStatusDocumentation.md) and am providing the relevant synchronization debug output below:

#### Device and verbose Detox logs

- [x] I have run my tests using the `--loglevel trace` argument and am providing the verbose log below:

<details>
 <summary>Detox logs</summary>
 <code>
detox[7707] INFO:  [AppleSimUtils.js] com.shipt.groceries-staging launched. To watch simulator logs, run:
        /usr/bin/xcrun simctl spawn 760EAD26-C92A-42B7-9252-DF691A8E8FDF log stream --level debug --style compact --predicate 'process == "Shipt"'
detox[7707] INFO:  orders coupon tests is assigned to 760EAD26-C92A-42B7-9252-DF691A8E8FDF (iPhone 13 Pro Max)
detox[7707] INFO:  orders coupon tests: should signup for account and create order
detox[7707] INFO:  at e2e/server/detox-actions/detox-actions.js:7:13 
 Dispatching action { type: 'WIPE_STATE' }
detox[7707] ERROR: [EXEC_FAIL, #58] "applesimutils --byId 760EAD26-C92A-42B7-9252-DF691A8E8FDF --bundle com.shipt.groceries-staging --restartSB --setPermissions camera=YES,location=always,notifications=YES,userTracking=NO" failed with error = ChildProcessError: Command failed: applesimutils --byId 760EAD26-C92A-42B7-9252-DF691A8E8FDF --bundle com.shipt.groceries-staging --restartSB --setPermissions camera=YES,location=always,notifications=YES,userTracking=NO
Error: The data couldn’t be read because it isn’t in the correct format.. See “applesimutils --help” for usage.
Error: Unable to obtain a list of simulators. See “applesimutils --help” for usage.
 `applesimutils --byId 760EAD26-C92A-42B7-9252-DF691A8E8FDF --bundle com.shipt.groceries-staging --restartSB --setPermissions camera=YES,location=always,notifications=YES,userTracking=NO` (exited with error code 255) (code=255), stdout and stderr:

detox[7707] ERROR: [EXEC_FAIL, #58] 
detox[7707] ERROR: [EXEC_FAIL, #58] Error: The data couldn’t be read because it isn’t in the correct format.. See “applesimutils --help” for usage.
Error: Unable to obtain a list of simulators. See “applesimutils --help” for usage.
 </code>
</details>

<details>
 <summary>Device logs</summary>
 <code>
detox[7707] INFO:  [AppleSimUtils.js] com.shipt.groceries-staging launched. To watch simulator logs, run:
        /usr/bin/xcrun simctl spawn 760EAD26-C92A-42B7-9252-DF691A8E8FDF log stream --level debug --style compact --predicate 'process == "Shipt"'
detox[7707] INFO:  orders coupon tests is assigned to 760EAD26-C92A-42B7-9252-DF691A8E8FDF (iPhone 13 Pro Max)
detox[7707] INFO:  orders coupon tests: should signup for account and create order
detox[7707] ERROR: [EXEC_FAIL, #58] "applesimutils --byId 760EAD26-C92A-42B7-9252-DF691A8E8FDF --bundle com.shipt.groceries-staging --restartSB --setPermissions camera=YES,location=always,notifications=YES,userTracking=NO" failed with error = ChildProcessError: Command failed: applesimutils --byId 760EAD26-C92A-42B7-9252-DF691A8E8FDF --bundle com.shipt.groceries-staging --restartSB --setPermissions camera=YES,location=always,notifications=YES,userTracking=NO
Error: The data couldn’t be read because it isn’t in the correct format.. See “applesimutils --help” for usage.
Error: Unable to obtain a list of simulators. See “applesimutils --help” for usage.
 `applesimutils --byId 760EAD26-C92A-42B7-9252-DF691A8E8FDF --bundle com.shipt.groceries-staging --restartSB --setPermissions camera=YES,location=always,notifications=YES,userTracking=NO` (exited with error code 255) (code=255), stdout and stderr:

detox[7707] ERROR: [EXEC_FAIL, #58] 
detox[7707] ERROR: [EXEC_FAIL, #58] Error: The data couldn’t be read because it isn’t in the correct format.. See “applesimutils --help” for usage.
Error: Unable to obtain a list of simulators. See “applesimutils --help” for usage.
 </code>
</details>

**Comment by shamilovtim** [comment]
According to [this post](https://issueexplorer.com/issue/react-native-community/react-native-circleci-orb/43) `sudo` seems to fix the issue. Can that be added to the applesimutils call?

**Comment by asafkorem** [comment]
Is `sudo` fixes [this issue](https://github.com/wix/Detox/issues/3155) for you as well?

**Comment by asafkorem** [comment]
Thanks for the report @shamilovtim!

> 1. Call await device.launchApp() on CI

Which CI service do you use? If it happens to be CircleCI with _[react-native-circleci-orb](https://github.com/react-native-community/react-native-circleci-orb)_, it seems like this issue was resolved in version 4.0.4, here: https://github.com/react-native-community/react-native-circleci-orb/pull/47.

**Comment by shamilovtim** [comment]
Hey @asafkorem thanks for responding and for the help. We aren't using that orb. We're using CircleCI with the macOS medium executor, node orb `node: circleci/node@4.7.0`. The commentary on that discussion helped me see that there might be an issue with logging? We're triggering a log right before `launchApp()`, for example: `detox[8324] INFO:  at e2e/server/mock-api/utils/utils.js:77:19  clearMocks was sent`. 

I assume based on the commentary in that ticket, it's possible that our logging is interfering with the output that Detox is expecting? I'm trying to figure out how that's possible though and have no way of confirming that's the case. Is that a possibility?

**Comment by shamilovtim** [comment]
@asafkorem Is it possible for applesimutils to log out the stdout it received (rather than what it expected)? The problem I'm having now is that I see nothing in the logs that could indicate something interfering with applesimutils, so I have no real way to debug the message that it's getting instead of the message that it wants.

**Comment by asafkorem** [comment]
@shamilovtim it seems like it fails when trying to decode the JSON returned from `xcrun simctl list --json`..
Can you please execute `xcrun simctl list --json` on your CI and provide me with the result here?

**Comment by asafkorem** [comment]
Also, can you post here your AppleSimulatorUtils version? (`applesimutils --version`)

**Comment by shamilovtim** [comment]
@asafkorem  Thank you for responding!

> xcrun simctl list --json
https://pastebin.com/emHwTnj4

> applesimutils --list
This command took almost 20 seconds and has some sort of circular JSON. I hit a pastebin.com limit:
"You have exceeded the maximum paste size of 512 kilobytes per paste. PRO users don't have this limit!"

Here it is on gist:
https://gist.github.com/shamilovtim/e928a157bad50f98ace4568ca9e8c989

> sudo applesimutils --list
The first time, this returned an empty array:

<img width="487" alt="Screen Shot 2022-01-24 at 5 00 30 PM" src="https://user-images.githubusercontent.com/3495974/150872217-aef9f7a0-d2cf-4e99-89c5-a0d89540bd37.png">

I run it again and get this. Same as before, another massive JSON object that seems to be circular?
https://gist.github.com/shamilovtim/3ec5d83e3fbc18b6b94e022cc9f256b3

> and please post here your AppleSimulatorUtils version? (applesimutils --version) 🙏🏼

applesimutils version 0.9.4

**Comment by shamilovtim** [comment]
Regarding these bugs, one thing to point out is that the problem is intermittent, happens about 1 or 2 times every 20 test runs (error doesn't always occur, instead it flakes sometimes)

**Comment by shamilovtim** [comment]
It looks like using launchApp without any permissions fixes the issue

**Comment by arthuralee** [comment]
I'm having the same issue in a relatively large codebase. We are also using CircleCI, with applesimutils version 0.9.4. I was able to pull some debug logs and opened an issue in applesimutils: https://github.com/wix/AppleSimulatorUtils/issues/88
