### ISSUE TITLE
Question: Why do we need to run a release build on the CI?

### ISSUE THREAD

**Issue by itchingpixels** [wix/detox#317]
#### Description
Unfortunately building for release on iOS takes a lot longer than doing a Debug build.

Currently, our tests are failing with a timeout error if we switch to compiling a debug build (despite doing `react native bundle` manually beforehand).
But, only on the CI, locally it's fine.

What's the exact reason that we need to run a release build on the CI?
If I know that, we could potentially figure out an alternative & speed up our builds considerably :).

#### Node, Device, Xcode and macOS Versions

* Node: 8.5
* Device: MBP
* Xcode: 9.0
* macOS: 10.12.6

**Comment by LeoNatan** [comment]
We recommend testing the release build because this is the closest your users get in production. There are practical issues that could block your tests from working as expected in debug builds; yellow and red boxes being one of the issues.

**Comment by itchingpixels** [comment]
ok, thank you! actually yellow/red boxes are something we'd like to fail the E2E tests we have - but that's a different story. I'll try to investigate why the debug builds are failing.
