### ISSUE TITLE
how to make use of record-performance

### ISSUE THREAD

**Issue by dbilgin** [wix/Detox#3178]
### Description

I understand that mac instruments for network can be used for real iOS devices, but as far as I know detox doesn't support real iOS devices. I was looking at the [artifacts document](https://github.com/wix/Detox/blob/master/docs/APIRef.Artifacts.md) and there is the `record-performance` option there. I also looked at [this](https://github.com/wix/Detox/issues/1635) issue.

But whenever I run my detox tests on a simulator with `--record-performance all` it only just creates a folders for the tests under `artifacts` folder and they are completely empty. Am I supposed to be doing something for it to work?

I have also tried going through this and adding the necessary stuff: https://github.com/wix/DetoxInstruments/blob/master/Documentation/XcodeIntegrationGuide.md
but when I try to run the app like this I seem to get a Signal 11

### Environment

 - Detox: 19.4.2
 - React Native: 0.66.3
 - Node: 14.18.1
 - Device: Simulator iPhone 11 - iOS 15.2
 - OS: iOS
 - Test-runner: `jest-circus`

**Comment by d4vidi** [comment]
Hey, thanks for reporting this. Could you by any chance try this out with the latest Detox v17, and see whether it works for you?

**Comment by dbilgin** [comment]
Sorry what is detox v17? Isn't the latest version 19.4.2?

**Comment by dbilgin** [comment]
Ah you mean try it out with the latest version from the v17 back then, okay, I will take a look, thank you for your reply

**Comment by d4vidi** [comment]
Exactly. Sorry if I wasn't clear about it.

**Comment by d4vidi** [comment]
@dbilgin would love to hear back from you

**Comment by dbilgin** [comment]
@d4vidi will take a look at it soon, sorry about that, been rather busy lately

**Comment by dbilgin** [comment]
Okay, I created a clean project, reinstalled the detox instruments, I managed to open the application and watch the instruments do their thing from the Detox Instruments application, which didn't work before, but when I ran `detox test --configuration ios.sim.release --record-performance all` the artifact folders are still empty. I feel like I am missing a config or something somewhere

**Comment by noomorph** [comment]
@d4vidi shall we mark this feature as obsolete, maybe? in Detox 20 or 21? Let's be straight, we support neither actively nor passively this feature for more than a year... 🤷‍♂️  It's creating a bad smell.
