### ISSUE TITLE
scrolling until visible doesn't wait after scroll anymore

### ISSUE THREAD

**Issue by dbilgin** [wix/Detox#3181]
### Description

I was on version `17.14.9` of detox and this was working, I am not trying to upgrade to `19.4.2` and I am having a problem.
I have a `ScrollView` and I want to scroll down until a modal pops up from the bottom. In the last version of detox I think it first checks whether the expected element is visible (it's not because the modal is just coming into view) and then tries to scroll (it can't because now there is the modal) and it doesn't check again for the expected element and fails.

I am not sure what kind of a logic change happened between the two versions regarding this, but is there a way around this? I tried to make it wait a bit after every scroll but I couldn't find a way to do that either without manually writing the scroll. I am using the code below like in the documentation:

```
  waitFor(expectedElement)
    .toBeVisible()
    .whileElement(by.id(scrollElementId))
    .scroll(scrollOffset, direction, startPositionX, startPositionY);
```

### Environment

 - Detox: 19.4.2
 - React Native: 0.66.3
 - Node: 14
 - Device: Simulator
 - OS: iOS
 - Test-runner: jest-circus

**Comment by dbilgin** [comment]
For now I found the below code to be the solution, but I am not sure if it's a good idea to use it like this:

```
  waitFor(expectedElement)
    .toBeVisible()
    .whileElement(by.id(scrollElementId))
    .scroll(scrollOffset, direction, startPositionX, startPositionY)
    .catch(async (_) => {
      await waitFor(expectedElement).toBeVisible().withTimeout(timeout);
    });
```

**Comment by dbilgin** [comment]
Is it not possible to add a wait for this?

**Comment by asafkorem** [comment]
@dbilgin thanks for the report! 
I'm not really sure what happened here. Did it tried to continue the scrolling after the modal was already presented?

**Comment by dbilgin** [comment]
@asafkorem thanks for your reply. It goes like this:
- it scrolls
- waits for the element (I assume)
- the element is not available right away
- the modal slides in
- tries to scroll again (I could see it)
- cannot scroll and gives error saying it could neither scroll nor see the element

**Comment by asafkorem** [comment]
Have you considered the `scrollTo(edge)` API ([here](https://wix.github.io/Detox/docs/api/actions-on-element/#scrolltoedge))?
```js
await element(by.id(scrollElementId)).scrollTo('bottom');
await waitFor(expectedElement).toBeVisible().withTimeout(timeout);
```
Also, please provide the necessary logs as the issue template requires, it will help me to understand the problem better..

**Comment by dbilgin** [comment]
I did consider this, but it's an endless paginated flatlist and the modal appears at a certain point on the second page.

The workaround I came up with is working fine right now:
```
.catch(async (_) => {
      await waitFor(expectedElement).toBeVisible().withTimeout(timeout);
    });
```
But I was thinking it's probably not a nice way of doing it.

Let me get the logs for you, sorry about that

**Comment by asafkorem** [comment]
>the element is not available right away

OK I can see the problem here, if fails to scroll after he thinks that the element is not visible yet (because it wasn't last time it was tested)..
Well, in that case, your workaround makes some sense (given the existing API).

**Comment by dbilgin** [comment]
So these are the logs from when the modal starts appearing (all the logs were immensely huge so I cut this part):

```

detox[10090] INFO:  [APP_STATUS] The app is busy with the following tasks:
• 1 enqueued native timers:
  - Timer #1:
    + Fire date: 2022-01-24 13:14:57 +0100.
    + Time until fire: 0.100.
    + Repeat interval: 0.
    + Is recurring: NO.
• The event "Network Request" is taking place with object: "URL: “https://--”".
• The event "Network Request" is taking place with object: "URL: “https://--”".
• There are 9 work items pending on the dispatch queue: "Main Queue (<OS_dispatch_queue_main: com.apple.main-thread>)".
• Run loop "Main Run Loop" is awake.
• The event "Network Request" is taking place with object: "URL: “https://--”".
• There are 1 pending delayed selectors to be performed.
• The event "Network Request" is taking place with object: "URL: “https://--”".
• UI elements are busy:
  - Layers needs display: 4.
  - Layers needs layout: 3.
  - View needs layout: 2.
detox[10090] TRACE: [WSS_GET_FROM, #app] {"messageId":7,"params":{"details":"Unable to scroll down in “<RCTCustomScrollView: 0x7fe61d02f600>” and no elements found for “MATCHER(text == “Test!”)”","NSLocalizedDescription":"Unable to scroll down in “<RCTCustomScrollView: 0x7fe61d02f600>” and no elements found for “MATCHER(text == “Test!”)”","viewHierarchy":"<UIWindowScene: 0x7fe61f10b620; scene = <FBSScene: 0x600003ca8380; identifier: sceneID:com.example-default>; persistentIdentifier = CBD22D2C-2017-4BB2-9F96-5F98FF97D16B; activationState = UISceneActivationStateForegroundActive>\n   + <UIWindow: 0x7fe61c61d570; frame = (0 0; 414 896); layer = <UIWindowLayer: 0x600001460f00>>\n   |    | <UITransitionView: 0x7fe61c6211f0;
```

In the earlier version of detox it was actually waiting for this long enough, thanks for confirming my method of working around this, but I was wondering if it would be logical to add a timeout functionality to this

**Comment by asafkorem** [comment]
I understand.. ATM Detox doesn't support the combination of wait-for expectations with both action and timeout, however, the API you suggest sounds reasonable indeed, we are talking about something like:
```js
waitFor(expectedElement)
    .toBeVisible()
    .withTimeout(timeout)
    .whileElement(by.id(scrollElementId))
    .scroll(scrollOffset, direction, startPositionX, startPositionY);
```

**Comment by dbilgin** [comment]
yes! exactly something like this

**Comment by asafkorem** [comment]
Note that your current workaround will run faster than the suggested API (it will wait for timeout only on the last check), so I'm not convinced if waiting with timeout on each iteration will be the best practice on such cases.
Anyway, thanks, that's really an interesting scenario, I will think about it..

**Comment by asafkorem** [comment]
From the view hierarchy it seems like the scroll view is covered with a transition view, but the view that you're waiting for to be visible is not yet visible, so you may also consider something like:
```js
await waitFor(scrollElementId)
  .not.toBeVisible()
  .whileElement(by.id(scrollElementId))
  .scroll(scrollOffset, direction, startPositionX, startPositionY);
await waitFor(expectedElement).toBeVisible().withTimeout(timeout);
```

**Comment by dbilgin** [comment]
hmm, I never thought of doing it that way, I thought it would work honestly, but got a similar error again.
As far as I understand, it initially checks if the element is there and because the modal is not yet visible, it is there, then by the time it tries to scroll again, the modal is already there and it cannot scroll, so it fails at the scroll

![image](https://user-images.githubusercontent.com/15243788/150796319-68e397ce-c995-4370-a82a-49c2bdcb4b36.png)
