### ISSUE TITLE
Finding detox is the right tool for our mobile automation

### ISSUE THREAD

**Issue by karthikeyanalaguraja** [wix/Detox#3182]
I am working in QA, our dev developed native ios code through swift and Android uses Kotlin.  Is detox supports this? or will detox only support react native app?

**Comment by d4vidi** [comment]
Detox doesn't properly support native / brownfield apps on Android, I'm afraid.
iOS might be in better shape in that sense but we can't guarantee that it would stay that way.

**Comment by karthikeyanalaguraja** [comment]
Thanks. do you think we can implement detox for ios now?  do you think Wix may drop support for this?

**Comment by d4vidi** [comment]
I wish I could have guarantees, but I do not, at least not at the moment.
