### ISSUE TITLE
Stuck after tap action was called

### ISSUE THREAD

**Issue by nguyenhoanglam** [wix/Detox#3186]
### Description
My test case is a login flow. I expect to see the home screen after press the login button. When I run the test, login flow works as expected on simulator but the terminal keep waiting (doest not finish the test) until timeout error. 
```js
describe('React Native Boilerplate', () => {
  beforeAll(async () => {
    await device.launchApp();
  });

  it('should have sign in screen', async () => {
    await expect(element(by.id('emailLoginButton'))).toBeVisible();
  });

  it('should show handle sign in', async () => {
    await element(by.id('emailInput')).replaceText('yasuo@gmail.com');
    await element(by.id('passwordInput')).typeText('111111');
    await element(by.id('emailLoginButton')).tap();
    await expect(element(by.id('homeContent'))).toBeVisible();
  });
});
```
I found that the test will finish if:
- remove ```await``` from this line ```await element(by.id('emailLoginButton')).tap();```, and
- remove this line ```await expect(element(by.id('homeContent'))).toBeVisible();```

...but I can not test the home screen's visibility. So I think ```await element(by.id('emailLoginButton')).tap();``` is making my test keep waiting.

Any help for my issue?

### Environment

 - Detox: 19.4.2
 - React Native: 0.67.1
 - Node: 17.3.0
 - Device: iPhone 13 simulator 
 - OS: iOS
 - Test-runner (select one): `jest-circus`

**Comment by dooleyb1** [comment]
@nguyenhoanglam Did you manage to resolve this issue? Having the exact same problem also on `Detox: 19.4.2`
