### ISSUE TITLE
Upgrade to RN 0.67

### ISSUE THREAD

**Issue by jonathanmos** [wix/Detox#3197]
# Description
Add/verify support for the React Native 0.67 release:

- [x] Check (and migrate) Detox test app on developer env
- [ ] Upgrade demo apps (demo-react-native, then check demo-react-native-jest and detox-react-native-detox-instruments)
- [ ] Upgrade associated CI job config to always use 0.67
- [x] Update support table in main README.md

**Comment by gabrielmoncea** [comment]
Is the current version compatible with 0.67?

**Comment by d4vidi** [comment]
@gabrielmoncea almost there 😄 Be sure to track this issue
