### ISSUE TITLE
Prevent certain test specs from running temporarily

### ISSUE THREAD

**Issue by mhyousefi** [wix/detox#322]
So let's say one has some test spec files (<test file name>.spec.js) under the e2e folder. My understanding is that when you run `detox test`, those test spec files are run in order (according to their file names) For instance, test1.spec.js runs before test2.spec.js.

If I want to prevent one or more of these test spec files from running, I comment the content out and it works. But that's a bit messy; I was wondering if there is a cleaner way of doing that (of course given that you don't want to remove that file from the directory)

**Comment by rotemmiz** [comment]
This issue is test runner specific. Detox is not a test runner, it just uses one for convinience.
Please refer to your test runner’s documentation for more details (either it’s Mocha, AVA, Jest, they all have these festures)
