### ISSUE TITLE
Detox is failing to run

### ISSUE THREAD

**Issue by RachanaHT** [wix/Detox#3221]
### Description

getting this worning

detox[11970] WARN:  [DetoxConnection.js/ERROR, #61409] Action dispatched too early, there is no session to use:

HINT: Please report this issue on our GitHub tracker:
https://github.com/wix/Detox/issues

{
  type: 'AppWillTerminateWithError',
  params: [Object],
  messageId: -10000
}
detox[11970] WARN:  [DetoxConnection.js/ERROR, #61409] Action dispatched too early, there is no session to use:

HINT: Please report this issue on our GitHub tracker:
https://github.com/wix/Detox/issues

{
  params: [Object],
  type: 'AppWillTerminateWithError',
  messageId: -10000
}

detox[11970] ERROR: [APP_UNREACHABLE] Detox can't seem to connect to the test app(s)!

### Detox version

"detox": "^18.23.1"

### React Native version

"react-native": "^0.64.2"

### Node version

v17.4.0

### Device model

Iphone 12 Pro max

### Xcode version

Version 13.2.1 (13C100)

### macOS version

Monterry version 12.2

**Comment by d4vidi** [comment]
@RachanaHT please provide the full execution log, and configuration snippets.

**Comment by markpar** [comment]
Anecdotally, I've seen this error on Android 12, but not on Android 11.
