### ISSUE TITLE
Unify environment info in issue-tracker report schema

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#3225]
### What happened?

I think we should unify the various info fields (Detox version, RN version, etc.) to a single input box, because  until we do so the issues end up being reported like this (which isn't very convenient):

![image](https://user-images.githubusercontent.com/9818880/154071028-7078a8bc-b061-438a-ab32-dcdb7e000f31.png)

### What was the expected behaviour?

I was thinking about a single input box with content in the form of what we previously had (prompting the user to complete stuff inside) already set in:

```
Detox:
React Native:
Node:
Device:
OS:
Test-runner (select one): jest-circus / jest+jasmine / mocha / other
```

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Detox version

N/A

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by asafkorem** [comment]
@jonathanmos also suggested to add these to the list:
> buildToolsVersion, compileVersion, gradle wrapper version, gradle plugin version, kotlin version

**Comment by d4vidi** [comment]
Well sometimes those are a function of numerous configurations (coming from root and child projects). We can add it while bearing that in mind. In any case, we'd have to properly explain how to retrieve those, if we do.
