### ISSUE TITLE
How to interact with system alert dialogs

### ISSUE THREAD

**Issue by davidjonesdialexa** [wix/Detox#3227]
### Description

Our app calls a `Cancel/Continue` system alert dialog. The Matcher can't seem to locate the button to tap. Any ideas how to handle an element like this?

![Screen Shot 2022-02-18 at 4 08 59 PM](https://user-images.githubusercontent.com/84142414/154771553-7a86d2b2-7fad-4c64-9e69-b4ea918a9da3.png)
![Screen Shot 2022-02-18 at 4 51 21 PM](https://user-images.githubusercontent.com/84142414/154771699-cfe9ed2d-473c-4f7b-a141-8e4722d6ffe3.png)

### Detox version

19.4.5

### React Native version

0.66.3

### Device model

iphone 11

### Xcode version

13.2.1

### iOS version

15.2

### macOS version

12.2.1

### Test runner

jest-circus

**Comment by asafkorem** [comment]
Hi @davidjonesdialexa, unfortunately, Detox is not supporting interactions with system dialog, we are still working on this as part of [XCUITest](https://github.com/wix/Detox/issues/3208) integration.

In the meanwhile, I can suggest to use a launch argument that will disable the login while testing with Detox.

**Comment by cortisiko** [comment]
@davidjonesdialexa As a work around maybe you can you try something like this:

`element(by.label("Continue")).atIndex(0).tap();`

**Comment by activebiz** [comment]
> @davidjonesdialexa As a work around maybe you can you try something like this:
> 
> `element(by.label("Continue")).atIndex(0).tap();`

Tried this but doesnt work.

**Comment by nero2009** [comment]
Please what is the fix for this?

**Comment by sebbyrum** [comment]
Is this still something that is being developed? Would be very helpful for a lot of projects I'm sure

**Comment by sjors98** [comment]
This works sometimes for me: 
```
await element(by.label('Continue').and(by.type('_UIAlertControllerActionView'))).tap();
```
Where Continue is the text in the button you want to tap :)

**Comment by mariushorvat** [comment]
Is there a fix for this issue? Thanks!

**Comment by alfonsosn** [comment]
Bump.

**Comment by IvayloMetodiev** [comment]
Is there any development or workaround here? Finding elements `by.text` works in some cases but if there is a system alert on the screen nothing helps.

**Comment by hoangtrunnam** [comment]
I have the same problem, I can't fix this, Does anyone have an idea?

**Comment by KaterinaUK** [comment]
Hi everyone, any update on this issue? How can we pass through this issue?

**Comment by codeyogi911** [comment]
This is absolutely required, cannot login without this.

**Comment by hoangtrunnam** [comment]
@codeyogi911 you need to press the button on that dialog **with your finger or mouse pointer.** detox cannot catch that layout dialog

**Comment by AbdelhakLabyadh** [comment]
> _UIAlertControllerActionView

This is working fine for me on iOS simulator, but it doesn't for android emulator. 
I couldn't find an alternative for Android. 
Any solutions please ?

**Comment by d4vidi** [comment]
> > _UIAlertControllerActionView
> 
> This is working fine for me on iOS simulator, but it doesn't for android emulator. I couldn't find an alternative for Android. Any solutions please ?

This could come in handy for Android: https://wix.github.io/Detox/docs/api/device/#devicegetuidevice-android-only (also check the reference to the [Android dev guide](https://developer.android.com/reference/androidx/test/uiautomator/UiDevice)). I think techniques relying on [DPadDown](https://developer.android.com/reference/androidx/test/uiautomator/UiDevice#pressDPadDown()) could work best here.

**Comment by phoet** [comment]
how is anyone ever building a useful test suite with this library 😢

**Comment by asafkorem** [comment]
Support for system interactions was released with [Detox v20.22](https://github.com/wix/Detox/releases/tag/20.22.0)

**Comment by vomchik** [comment]
> Support for system interactions was released with [Detox v20.22](https://github.com/wix/Detox/releases/tag/20.22.0)

Thank you for this functionality! Should it works with react-native `Alert.alert` ?

**Comment by asafkorem** [comment]
> > Support for system interactions was released with [Detox v20.22](https://github.com/wix/Detox/releases/tag/20.22.0)
> 
> Thank you for this functionality! Should it works with react-native `Alert.alert` ?

Thanks! Yes :)

**Comment by vomchik** [comment]
> > > Support for system interactions was released with [Detox v20.22](https://github.com/wix/Detox/releases/tag/20.22.0)
> > 
> > 
> > Thank you for this functionality! Should it works with react-native `Alert.alert` ?
> 
> Thanks! Yes :)

@asafkorem For some reason it's doesn't works for me
![CleanShot 2024-06-17 at 14 26 44@2x](https://github.com/wix/Detox/assets/732085/340ad77b-985d-43bb-b86f-4a6f0dadf09e)

I have tried both options:
`const button = system.element(by.system.label("Continue"));` and `const button = system.element(by.system.type("button")).atIndex(0);`

Any ideas? 🤔

**Comment by vomchik** [comment]
![CleanShot 2024-06-17 at 14 48 11@2x](https://github.com/wix/Detox/assets/732085/7ec2ceaf-c611-45a5-8b89-7a8836f27b59)
Is it ok to see this path not related to my local machine?

**Comment by patriciazumo** [comment]
I'm having the same issue that @vomchik reported. I tried the latest version 20.23.0 but I didn't see any difference. Any idea of what I may be missing? Thank you!

**Comment by amitesh786** [comment]
@davidjonesdialexa @nero2009 @asafkorem @vomchik 
Have there been any developments or resolutions regarding this issue? I have attempted all available solutions, but unfortunately, none have resolved the problem. I would greatly appreciate any additional suggestions or solutions that may have been effective for others.

**Comment by asafkorem** [comment]
These alerts might not be at the system level. Try matching it with a regular Detox matcher instead @amitesh786 @vomchik @patriciazumo

**Comment by patriciazumo** [comment]
I tried `element(by.label('Log out').and(by.type('_UIAlertControllerActionView')))`
And it worked.

This solution is mentioned here https://stackoverflow.com/questions/47522081/detox-ios-simulator-how-to-confirm-alert-message.

Thank you!
