### ISSUE TITLE
Move app to background?

### ISSUE THREAD

**Issue by pke** [wix/Detox#3232]
### Describe your idea

Would it be possible to have a way to move the app to the background and then launch it again with a URL?

**Comment by MuckT** [comment]
@pke this should work!
```JavaScript
await device.sendToHome()
await device.launchApp({ url: 'your url', newInstance: false })
```

**Comment by pke** [comment]
That would be great! Trying out tomorrow!

**Comment by d4vidi** [comment]
Thanks @MuckT! @pke please close the issue if it works for you.

**Comment by pke** [comment]
Works as described! Thanks @MuckT
