### ISSUE TITLE
withAncestor matcher works on iOS devices, but on Android devices it does not

### ISSUE THREAD

**Issue by iMaupin** [wix/Detox#3235]
### Description

Currently I have a test that relies on assertions following this generic archetype:

```
 await expect(element(by.id('child_element')
      .withAncestor(by.id('parent_element'))))
      .toBeVisible()
```
I am testing that the child element switches parent elements based on specific use. The above assertion works on iOS, but when I run the same test on android, the test fails with the following message:

`Expected: (view has effective visibility and view.getGlobalVisibleRect() covers at least <75> percent of the view's area) Got: was null`

I have visually confirmed that the element in question is indeed on the screen. So, as far as I know, the test should pass.

I have tested this across multiple android devices on different operating systems and have ensured that I am running the most up-to-date version of detox; all to no avail.

Any advice on what might be causing this odd behavior would be much appreciated!

### Your environment

Detox version: 19.4.5
React Native version: 0.67
Node version: 14.17.6
Device model: Samsung Galaxy s21 +/Samsung Galaxy s8
OS: Android 12 / Android 9
Test-runner (select one): jest-circus

**Comment by asafkorem** [comment]
Hi @iMaupin, thanks for the report!

We would like to assist, but we can't do this without more data. Can you please provide us the logs? 

- Detox logs: run your tests using the `--loglevel trace` argument.
- Device logs: run your tests using the `--record-logs all` argument.

Also, can you provide us some more data on the view hierarchy? You can try to locate this view using Android Studio's Layout Inspector when running with debug build.

**Comment by iMaupin** [comment]
Hi @asafkorem,

Thanks for the reply. The functionality above seems to be isolated to a single case. I have confirmed that the views in question are nested as expected through the Layout Inspector on Android Studio. I think that the issue is perhaps related to how the views are built within our app. The views follow this archetype:

`<Text testId='parent'>{conditionalLogic && <View testID='child'/>}{<View styles={{ conditionalLogicForSpacer}}>}{dynamicText}hardCodedText</Text>`

Could the child view's placement within a Text element cause this issue on android?

**Comment by asafkorem** [comment]
@iMaupin I'm not sure if the Text element is the issue here..
Is it a copy paste from the code? it looks like you have some typo, please try to replace `testId` occurrences with `testID`.
Specifically, 
> <Text **testId**='parent'>...

**Comment by asafkorem** [comment]
@iMaupin we need more information to figure what causes the issue.
Have you tried to reproduce this issue without the conditional-logic?
Can you see the elements on the screen while the test is failing (`--take-screenshots failing` / `--record-videos failing`)?

**Comment by asafkorem** [comment]
@iMaupin 
After consulted with @jonathanmos, and a small investigation led by him, we found that nested components inside RN `Text` component are not being handled as sub-views in Android, therefore the View (`child`) is not a descendant of the Text (`parent`), but you are still able to locate them by their test-IDs.

They have some doc regarding how they handle [nested text components](https://reactnative.dev/docs/text#nested-text), but they don't mention sub components. 

We can only suggest a solution, try to move the `testID` from the parent (`Text`) to a view container that will wrap these views in hierarchy. 
I mean, if the original code is:
```
<Text testID='parent'>{conditionalLogic && <View testID='child'/>}{<View style={{ conditionalLogicForSpacer}}/>}{dynamicText}hardCodedText</Text>
```
replace it with:
```
<View testID='parent'>
<Text>{conditionalLogic && <View testID='child'/>}{<View style={{ conditionalLogicForSpacer}}/>}{dynamicText}hardCodedText</Text>
</View>
```

**Comment by iMaupin** [comment]
@asafkorem

Cool thanks, we already had such a view in place that I could use which makes the test pass. I appreciate your looking into this.

**Comment by asafkorem** [comment]
Glad to help! 😄
