### ISSUE TITLE
error: cannot find symbol TestButlerProbe.assertReadyIfInstalled()

### ISSUE THREAD

**Issue by arnaudambro** [wix/Detox#3236]
### What happened?

I try to setup test-butler but when I run 
`detox build --configuration android.debug`
with the configuration
```
"android.debug": {
      "type": "android.apk",
      "binaryPath": "android/app/build/outputs/apk/debug/app-debug.apk",
      "testBinaryPath": "android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk",
      "build": "cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && cd .."
    },
```
the build fail with 
```
> Task :app:compileDebugAndroidTestJavaWithJavac FAILED
myapp/app/android/app/src/androidTest/java/com/mano/DetoxTest.java:27: error: cannot find symbol
        TestButlerProbe.assertReadyIfInstalled();
        ^
  symbol:   variable TestButlerProbe
  location: class DetoxTest
```

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 19.4.5
React Native version: 0.66.4
Node version: 14
Device model: Pixel_3_API_30_AOSP
Android version: 30
Test-runner (select one): jest-circus

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by d4vidi** [comment]
`TestButlerProbe` isn't part of test-butler -- just a wrapper we created in our example project, [here](https://github.com/wix/Detox/tree/master/examples/demo-react-native/android/app/src/androidTest/java/com/example). You need to specify it in your project, add the library as a test dependency (in build.gradle) and follow through all installation steps, to the end ([this blogpost](https://medium.com/wix-engineering/how-to-execute-android-ui-tests-on-ci-and-stay-alive-eb9089d88c1f) overviews that)

**Comment by Zakini** [comment]
This ought to be mentioned in the setup guide. [Step 5](https://wix.github.io/Detox/docs/introduction/android/#5-create-a-detox-test-class) only mentions adding a copy of `DetoxTest.java`, not any of the files that depends on.

**Comment by d4vidi** [comment]
Thanks @Zakini. I've updated the [test-butler](https://wix.github.io/Detox/docs/next/introduction/android/#8-test-butler-support-optional) section to reference the blogpost.
