### ISSUE TITLE
React native app crashes with react-native versions 0.49

### ISSUE THREAD

**Issue by haishee** [wix/detox#324]
#### Description
I have been running detox with react-native 0.46.0 and everything works fine. But when I upgraded to react-native version 0.49.1 the build succeeds but the app crashes with no error information on the console. 

Note: the app runs fine when I run `react-native run-ios`. 

#### Steps to Reproduce
N/A

#### Node, Device, Xcode and macOS Versions
* Node: 8.1.4
* Device: iPhone 7 Simulator
* Xcode: 8.3.2
* macOS: 10.3.2 Sierra

**Comment by dsznajder** [comment]
@haishee related to #279.

**Comment by LeoNatan** [comment]
This is tracked in #279.
