### ISSUE TITLE
 android application crashes while trying to run detox test

### ISSUE THREAD

**Issue by aviatam** [wix/Detox#3241]
### Description

once i try to run android test using detox the application crashes , same test seems to work on ios simulator 
steps : 
1. build android app ---> application opened on the device
2. build detox 
3. run detox test on android emulator (Nexus 5X using OS 8.1)
result :
application crashes 
with the following log

    DetoxRuntimeError: No instrumentation runner found on device emulator-5554 for package com.fundbox.mobile

      39 | beforeAll(async () => {
      40 |   console.log("@@@@@@@@@@@@@@@@@ launching app @@@@@@@@@@@@@");
    > 41 |   await device.launchApp();
         |                ^
      42 | });
      43 |
      44 | beforeEach(async () => {

### Your environment

Detox version: 18.23.1
React Native version: 2.6.2
Node version: v16.14.0
Device model: Nexus 5X
OS: 8.1
Test-runner (select one): jest-circus

**Comment by jonathanmos** [comment]
@aviatam could you please run it with `--loglevel trace` and post the logs?

**Comment by aviatam** [comment]
@jonathanmos thanks for reaching out , managed to resolve the issue with bumping our sdk version and using latest detox version
