### ISSUE TITLE
How to test on verifying identity ? 

### ISSUE THREAD

**Issue by lisa710junyi** [wix/Detox#3248]
### Description

It is connected to firebase. After the sign up page, it will verify user identity. The verify method includes choosing the pictures that have trains, etc. 

I don't know how to continue this verification with detox.  

### Your environment
![Screen Shot 2022-03-05 at 10 33 45 PM](https://user-images.githubusercontent.com/83738368/156908098-1c20ce07-2257-4d4f-8371-eb02b6dd9157.png)

Detox version:   "19.4.2"
React Native version: 
Node version: ^0.64.2
Device model: ios
OS: 
Test-runner (select one): jest-circus / jest+jasmine / mocha / other

**Comment by asafkorem** [comment]
Hey @lisa710junyi, you can use [launch-arguments](https://wix.github.io/Detox/docs/api/launch-args) to disable this verification step while testing the app (for example, by passing some flag that disables it).

**Comment by lisa710junyi** [comment]
@asafkorem  thank you for helping.  Finally my team let me add 
```
auth().settings.appVerificationDisabledForTesting = true;
```
to the auth page. 
I works. 
I am trying your way, still not figure out how to. Once I have more time, I will deep into it.
