### ISSUE TITLE
How to choose the element in autocomplete 

### ISSUE THREAD

**Issue by lisa710junyi** [wix/Detox#3255]
### Description

I use google autocomplete component. After I tap it. It shows a drop down list and I want to choose one of them. How can I do it ?
![Screen Shot 2022-03-08 at 4 16 34 PM](https://user-images.githubusercontent.com/83738368/157326798-5c0d6bbb-66cf-4fbc-b2dc-3d4a8bc21baf.png)

Thank you 

### Your environment

Detox version: 
React Native version: 
Node version: 
Device model: 
OS: 
Test-runner (select one): jest-circus / jest+jasmine / mocha / other

**Comment by rajathrao** [comment]
Did you try by index ?

**Comment by lisa710junyi** [comment]
> Did you try by index ?

I use by.text() 
 await element(by.text('3401 Cardinal Court, Lakewood, NJ, USA')).tap()
and it works
