### ISSUE TITLE
typeText method is not working

### ISSUE THREAD

**Issue by Chrys123** [wix/detox#326]
Hi. am trying to type text on an input field, but it does not seem to be working on the app. 

Thats the error stack trace: 

Error: Error: An action failed. Please refer to the error trace below.
Exception with Action: {
  "Action Name" : "Type 'ws.mob.user.login@f1000.com'",
  "Element Matcher" : "(((((respondsToSelector(isAccessibilityElement) && isAccessibilityElement) && accessibilityLabel('Email address')) && !(descendantThatMatches((kindOfClass('RCTText') && ((respondsToSelector(isAccessibilityElement) && isAccessibilityElement) && accessibilityLabel('Email address')))))) && !(kindOfClass('RCTScrollView'))) || (kindOfClass('UIScrollView') && ((kindOfClass('UIView') || respondsToSelector(accessibilityContainer)) && ancestorThatMatches(((((respondsToSelector(isAccessibilityElement) && isAccessibilityElement) && accessibilityLabel('Email address')) && !(descendantThatMatches((kindOfClass('RCTText') && ((respondsToSelector(isAccessibilityElement) && isAccessibilityElement) && accessibilityLabel('Email address')))))) && kindOfClass('RCTScrollView'))))))"
}

Error Trace: [
  {
    "Description" : "Keyboard did not appear after tapping on element [E]. Are you sure that tapping on this element will bring up the keyboard?",
    "Description Glossary" :     {
      "E" : "<RCTText:0x7fbb3872f0a0; AX=Y; AX.label='Email address'; AX.frame={{16, 128}, {79, 14.5}}; AX.activationPoint={55.5, 135.25}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{0, 0}, {79, 14.5}}; alpha=1>"
    },
    "Error Domain" : "com.google.earlgrey.ElementInteractionErrorDomain",
    "Error Code" : "2",
    "File Name" : "GREYActions.m",
    "Function Name" : "+[GREYActions grey_actionForTypeText:atUITextPosition:]_block_invoke",
    "Line" : "579"
  }
]

**Comment by LeoNatan** [comment]
This issue has been discussed many times in the past. Please use search before opening more issues.

You need to make sure keyboard appears when a text field is first responder. They easiest way is to disable hardware keyboard in the simulator menu.

**Comment by Chrys123** [comment]
What do you mean to disable the hardware keyboard menu please? Why is the issue happening?

**Comment by LeoNatan** [comment]
Make sure this is **disabled**:
![screen_shot_2015-06-24_at_2_55_27_pm](https://user-images.githubusercontent.com/2270433/31392932-25a11ffe-ade3-11e7-9902-4e7a27e4944d.png)

**Comment by Chrys123** [comment]
Cool thanks i resolved the issue
