### ISSUE TITLE
Do we have have a Discord channel for Detox ? 

### ISSUE THREAD

**Issue by rajathrao** [wix/Detox#3267]
### Description

I know that Detox is open source and often we cannot expect ans immediately . But, It will be helpful if experienced folks and some Detox users like us or on the discord channel to resolve issues quickly. 

### Your environment

Detox version: 19
React Native version: .64
Node version: 
Device model: 
OS: 
Test-runner (select one): jest-circus / jest+jasmine / mocha / other

**Comment by asafkorem** [comment]
Hi @rajathrao!

Great question, we do have plans to establish one. 
We just decided to prioritize this, also thanks to your question. I will post the link here soon.
