### ISSUE TITLE
Detox with jest runner example

### ISSUE THREAD

**Issue by dsznajder** [wix/detox#327]
Hi!

We could add example implementation of detox with `jest` runner. I've created a basic implementation of this one on my [repo](https://github.com/dsznajder/detox-jest-example).

P.S. If there is no need of that, we can just close this one :)

**Comment by SMJ93** [comment]
@dsznajder there is a guide in the [docs](https://github.com/wix/detox/blob/master/docs/Guide.Jest.md)

**Comment by DanielMSchmidt** [comment]
Hey, thanks for taking the effort. 
If you can improve the current docs that @SMJ93 pointed out we would be pretty happy 👍 
I am closing this issue for now, hope that is ok for you ;)
