### ISSUE TITLE
Android App test stall under release config on CI - possible sync issues (looperidlingresource)

### ISSUE THREAD

**Issue by jamesmcn1** [wix/Detox#3273]
### Description

Hey guys :)

Recently we've been having some trouble with our Detox tests on Bitrise. These are running fine locally under the debug config. I've run the test command with the `--debug-synchronization` flag and it shows the app is busy with LooperIdlingResource until the test times out. I've ran this flag on iOS and there was alot of mentions of enqueued timers eg:
```
• There are 3 work items pending on the dispatch queue: "Main Queue (<OS_dispatch_queue_main: com.apple.main-thread>)".
• 9 enqueued native timers:
```

Would anyone be able to help us identify the source of the issue? I've attached the logs of a test run below.

Cheers!

[detox_issue.txt](https://github.com/wix/Detox/files/8343793/detox_issue.txt)

### Your environment

Detox version: 19.5.7
React Native version: 0.62.2
Node version: 
Device model: Pixel XL
OS: Android 28
Test-runner (select one): jest-circus

**Comment by MuckT** [comment]
@jamesmcn1 this looks similar to what I am seeing in the logs for https://github.com/wix/Detox/issues/3275.

```
Mar 25 16:23:33 detox[30205] TRACE: [WSS_SEND_TO, #tester] {"messageId":31,"type":"currentStatusResult","params":{"status":{"app_status":"busy","busy_resources":[{"name":"looper","description":{"thread":"\"LooperIdlingResource-252-mqt_js\" (JS Thread)","execution_type":"JavaScript code"}},{"name":"bridge"}]}}}
```

Can you take a screenshot of your failing tests with `--take-screenshots=failing` and see if an ANR is being served?

**Comment by d4vidi** [comment]
According to your log file, the JS thread is constantly occupied, which blocks Detox from moving forward, eventually resulting in a time out:
```
16:21:23.195 detox[12983] INFO:  [APP_STATUS] The app is busy with the following tasks:\
\'95 "LooperIdlingResource-221-mqt_js" (JS Thread) is executing (JavaScript code).\
```

Nothing comes to mind ATM that could be related to Bitrise or Detox specifically -- it's more of an app-specific thing. I'd suggest stripping down the app to the point where the problem disappears, and through that zeroing-in on the root of the problem.

**Comment by jamesmcn1** [comment]
Yeah i think the issue is more on running the android emulator in a VM environment than detox. I've changed my CI workflow to use Bitrise's off the shelf AVD Manager step which seemed to have sorted the issues. Cheers everyone!
