### ISSUE TITLE
IOS 12 Test app might have crashed prematurely, or has had trouble setting up the connection.

### ISSUE THREAD

**Issue by shaliniatwork** [wix/Detox#3274]
### What happened?

Hi I am working on running detox on multiple ios versions 12.4, 13, 14 and 15.2. Except iOS 14, remaining are failing due to the titled error. I have added debug synchronisation as well and could not find anything important. I am able to launch the simulator and app without any issue. But when the detox launches the app, it immediately closes the app and wait until jest timeout to produce the below error. 

### What was the expected behaviour?

App tests to be successful as like in iOS 14

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

I will try to add. 

### In what environment did this happen?

Detox version: ^19.3.1
React Native version: 0.65.2
Node version: v12.22.6
Device model: iPhone 8
iOS version: 12.4
macOS version: 11.4 Bit Sur
Xcode version: 13.0.x
Test-runner (select one): **jest-circus** / jest+jasmine / mocha / other

### Detox logs

<details><summary>Detox logs</summary>

detox[15688] DEBUG: [EXEC_CMD, #2] /usr/bin/xcrun simctl boot 0926278E-345F-48B7-B2A8-2133A2C97AC9 
detox[15688] DEBUG: [EXEC_TRY, #2] Booting device 0926278E-345F-48B7-B2A8-2133A2C97AC9...
detox[15688] TRACE: [EXEC_SUCCESS, #2] 
detox[15688] DEBUG: [EXEC_CMD, #3] /usr/bin/xcrun simctl bootstatus 0926278E-345F-48B7-B2A8-2133A2C97AC9
detox[15688] TRACE: [EXEC_SUCCESS, #3] Monitoring boot status for iPhone 8 (0926278E-345F-48B7-B2A8-2133A2C97AC9).
[2022-03-24 18:34:13 +0000] Status=2, isTerminal=NO, Elapsed=00:05.
	Waiting on Data Migration
		Reason:Running plugin com.apple.addressbook.migrator (AddressBookLegacy.migrator)
		Migration Elapsed:00:01 seconds

[2022-03-24 18:34:14 +0000] Status=2, isTerminal=NO, Elapsed=00:06.
	Waiting on Data Migration
		Reason:Running plugin com.apple.calendar.migrator (Calendar.migrator)
		Migration Elapsed:00:02 seconds

[2022-03-24 18:34:15 +0000] Status=2, isTerminal=NO, Elapsed=00:07.
	Waiting on Data Migration
		Reason:Running plugin com.apple.MobileSafari.migrator (MobileSafari.migrator)
		Migration Elapsed:00:03 seconds

[2022-03-24 18:34:16 +0000] Status=2, isTerminal=NO, Elapsed=00:08.
	Waiting on Data Migration
		Reason:Running plugin com.apple.MobileSafari.migrator (MobileSafari.migrator)
		Migration Elapsed:00:04 seconds

[2022-03-24 18:34:17 +0000] Status=2, isTerminal=NO, Elapsed=00:09.
	Waiting on Data Migration
		Reason:Running plugin com.apple.MobileSafari.migrator (MobileSafari.migrator)
		Migration Elapsed:00:05 seconds

[2022-03-24 18:34:18 +0000] Status=2, isTerminal=NO, Elapsed=00:10.
	Waiting on Data Migration
		Reason:Running plugin com.apple.MobileSafari.migrator (MobileSafari.migrator)
		Migration Elapsed:00:06 seconds

[2022-03-24 18:34:19 +0000] Status=2, isTerminal=NO, Elapsed=00:11.
	Waiting on Data Migration
		Reason:Running plugin com.apple.MobileSafari.migrator (MobileSafari.migrator)
		Migration Elapsed:00:07 seconds

[2022-03-24 18:34:20 +0000] Status=2, isTerminal=NO, Elapsed=00:12.
	Waiting on Data Migration
		Reason:Running plugin com.apple.MobileSafari.migrator (MobileSafari.migrator)
		Migration Elapsed:00:08 seconds

[2022-03-24 18:34:21 +0000] Status=2, isTerminal=NO, Elapsed=00:13.
	Waiting on Data Migration
		Reason:Running plugin com.apple.appleaccount.mergeandremovemobilemeaccounts.migrator (MergeAndRemoveMobileMeAccounts.migrator)
		Migration Elapsed:00:09 seconds

[2022-03-24 18:34:22 +0000] Status=2, isTerminal=NO, Elapsed=00:14.
	Waiting on Data Migration
		Reason:Running plugin com.apple.HealthMigrator (HealthMigrator.migrator)
		Migration Elapsed:00:10 seconds

[2022-03-24 18:34:23 +0000] Status=2, isTerminal=NO, Elapsed=00:15.
	Waiting on Data Migration
		Reason:Running plugin com.apple.PassbookDataMigrator (PassbookDataMigrator.migrator)
		Migration Elapsed:00:11 seconds

[2022-03-24 18:34:24 +0000] Status=2, isTerminal=NO, Elapsed=00:16.
	Waiting on Data Migration
		Reason:Running plugin com.apple.iTunesStore.migrator (iTunesStore.migrator)
		Migration Elapsed:00:12 seconds

[2022-03-24 18:34:25 +0000] Status=2, isTerminal=NO, Elapsed=00:17.
	Waiting on Data Migration
		Reason:Running plugin com.apple.VoiceShortcuts (Shortcuts.migrator)
		Migration Elapsed:00:13 seconds

[2022-03-24 18:34:26 +0000] Status=1, isTerminal=NO, Elapsed=00:18.
	Waiting on BackBoard

[2022-03-24 18:34:32 +0000] Status=4294967295, isTerminal=YES, Elapsed=00:24.
	Finished

detox[15688] TRACE: [ARTIFACTS_LIFECYCLE] artifactsManager.onBootDevice({
  deviceId: '0926278E-345F-48B7-B2A8-2133A2C97AC9',
  type: 'ios.simulator',
  coldBoot: true
})
detox[15688] DEBUG: [EXEC_CMD, #4] /usr/bin/xcrun simctl io 0926278E-345F-48B7-B2A8-2133A2C97AC9 screenshot "/dev/null"
detox[15688] TRACE: [EXEC_SUCCESS, #4] Wrote screenshot to: /dev/null

detox[15688] TRACE: [ARTIFACTS_LIFECYCLE] artifactsManager.onBeforeTerminateApp({
  deviceId: '0926278E-345F-48B7-B2A8-2133A2C97AC9',
  bundleId: 'com.company.HeroBuddy'
})
detox[15688] DEBUG: [EXEC_CMD, #5] /usr/bin/xcrun simctl terminate 0926278E-345F-48B7-B2A8-2133A2C97AC9 com.company.HeroBuddy
detox[15688] DEBUG: [EXEC_TRY, #5] Terminating com.company.HeroBuddy...
detox[15688] TRACE: [EXEC_SUCCESS, #5] 
detox[15688] DEBUG: [EXEC_SUCCESS, #5] com.company.HeroBuddy terminated
detox[15688] TRACE: [ARTIFACTS_LIFECYCLE] artifactsManager.onTerminateApp({
  deviceId: '0926278E-345F-48B7-B2A8-2133A2C97AC9',
  bundleId: 'com.company.HeroBuddy'
})
detox[15688] TRACE: [ARTIFACTS_LIFECYCLE] artifactsManager.onBeforeUninstallApp({
  deviceId: '0926278E-345F-48B7-B2A8-2133A2C97AC9',
  bundleId: 'com.company.HeroBuddy'
})
detox[15688] DEBUG: [EXEC_CMD, #6] /usr/bin/xcrun simctl uninstall 0926278E-345F-48B7-B2A8-2133A2C97AC9 com.company.HeroBuddy
detox[15688] DEBUG: [EXEC_TRY, #6] Uninstalling com.company.HeroBuddy...
detox[15688] TRACE: [EXEC_SUCCESS, #6] 
detox[15688] DEBUG: [EXEC_SUCCESS, #6] com.company.HeroBuddy uninstalled
detox[15688] DEBUG: [EXEC_CMD, #7] /usr/bin/xcrun simctl install 0926278E-345F-48B7-B2A8-2133A2C97AC9 "/Users/vagrant/git/ios/build/Build/Products/Release-iphonesimulator/HeroBuddy.app"
detox[15688] DEBUG: [EXEC_TRY, #7] Installing /Users/vagrant/git/ios/build/Build/Products/Release-iphonesimulator/HeroBuddy.app...
detox[15688] TRACE: [EXEC_SUCCESS, #7] 
detox[15688] DEBUG: [EXEC_SUCCESS, #7] /Users/vagrant/git/ios/build/Build/Products/Release-iphonesimulator/HeroBuddy.app installed
ROOT_DESCRIBE_BLOCK[15688] TRACE: [ARTIFACTS_LIFECYCLE] artifactsManager.onRunDescribeStart({ name: 'ROOT_DESCRIBE_BLOCK' })
Onboarding[15688] TRACE: [ARTIFACTS_LIFECYCLE] artifactsManager.onRunDescribeStart({ name: 'Onboarding' })
detox[15688] INFO:  Onboarding is assigned to 0926278E-345F-48B7-B2A8-2133A2C97AC9 (iPhone 8)
detox[15688] INFO:  at e2e/onboarding.e2e.js:13:21 
 awaiting launch app
detox[15688] TRACE: [ARTIFACTS_LIFECYCLE] artifactsManager.onBeforeTerminateApp({
  deviceId: '0926278E-345F-48B7-B2A8-2133A2C97AC9',
  bundleId: 'com.company.HeroBuddy'
})
detox[15688] DEBUG: [EXEC_CMD, #8] /usr/bin/xcrun simctl terminate 0926278E-345F-48B7-B2A8-2133A2C97AC9 com.company.HeroBuddy
detox[15688] DEBUG: [EXEC_TRY, #8] Terminating com.company.HeroBuddy...
detox[15688] TRACE: [EXEC_SUCCESS, #8] 
detox[15688] DEBUG: [EXEC_SUCCESS, #8] com.company.HeroBuddy terminated
detox[15688] TRACE: [ARTIFACTS_LIFECYCLE] artifactsManager.onTerminateApp({
  deviceId: '0926278E-345F-48B7-B2A8-2133A2C97AC9',
  bundleId: 'com.company.HeroBuddy'
})
detox[15688] TRACE: [ARTIFACTS_LIFECYCLE] artifactsManager.onBeforeLaunchApp({
  bundleId: 'com.company.HeroBuddy',
  deviceId: '0926278E-345F-48B7-B2A8-2133A2C97AC9',
  launchArgs: {
    detoxServer: 'ws://localhost:53932',
    detoxSessionId: '106c5ac1-f7cd-1c43-150d-e4451413c7b4'
  }
})
detox[15688] TRACE: [ARTIFACT_START] starting SimulatorLogRecording {
  udid: '0926278E-345F-48B7-B2A8-2133A2C97AC9',
  bundleId: 'com.company.HeroBuddy'
}
detox[15688] DEBUG: [EXEC_CMD, #9] /usr/bin/xcrun simctl get_app_container 0926278E-345F-48B7-B2A8-2133A2C97AC9 com.company.HeroBuddy
detox[15688] TRACE: [EXEC_SUCCESS, #9] /Users/vagrant/Library/Developer/CoreSimulator/Devices/0926278E-345F-48B7-B2A8-2133A2C97AC9/data/Containers/Bundle/Application/FEC7A7BC-4913-41FB-95F2-13A766DB6759/HeroBuddy.app

detox[15688] DEBUG: [SPAWN_CMD, #15934] /usr/bin/xcrun simctl spawn 0926278E-345F-48B7-B2A8-2133A2C97AC9 log stream --level debug --style compact --predicate "processImagePath beginsWith \"/Users/vagrant/Library/Developer/CoreSimulator/Devices/0926278E-345F-48B7-B2A8-2133A2C97AC9/data/Containers/Bundle/Application/FEC7A7BC-4913-41FB-95F2-13A766DB6759/HeroBuddy.app\""
detox[15688] DEBUG: [EXEC_CMD, #10] SIMCTL_CHILD_DYLD_INSERT_LIBRARIES="/Users/vagrant/Library/Detox/ios/22e3e14ec9d2c26d4a9f3e6867c0b5b49be9c5cb/Detox.framework/Detox" /usr/bin/xcrun simctl launch 0926278E-345F-48B7-B2A8-2133A2C97AC9 com.company.HeroBuddy --args -detoxServer ws://localhost:53932 -detoxSessionId 106c5ac1-f7cd-1c43-150d-e4451413c7b4 -detoxDebugVisibility YES -detoxDisableHierarchyDump YES
detox[15688] DEBUG: [EXEC_TRY, #10] Launching com.company.HeroBuddy...
detox[15688] TRACE: [EXEC_SUCCESS, #10] com.company.HeroBuddy: 15941

detox[15688] DEBUG: [EXEC_CMD, #11] /usr/bin/xcrun simctl get_app_container 0926278E-345F-48B7-B2A8-2133A2C97AC9 com.company.HeroBuddy
detox[15688] TRACE: [EXEC_SUCCESS, #11] /Users/vagrant/Library/Developer/CoreSimulator/Devices/0926278E-345F-48B7-B2A8-2133A2C97AC9/data/Containers/Bundle/Application/FEC7A7BC-4913-41FB-95F2-13A766DB6759/HeroBuddy.app

detox[15688] INFO:  [AppleSimUtils.js] com.company.HeroBuddy launched. To watch simulator logs, run:
        /usr/bin/xcrun simctl spawn 0926278E-345F-48B7-B2A8-2133A2C97AC9 log stream --level debug --style compact --predicate 'process == "HeroBuddy"'
detox[15941] TRACE: [ARTIFACTS_LIFECYCLE] artifactsManager.onLaunchApp({
  bundleId: 'com.company.HeroBuddy',
  deviceId: '0926278E-345F-48B7-B2A8-2133A2C97AC9',
  launchArgs: {
    detoxServer: 'ws://localhost:53932',
    detoxSessionId: '106c5ac1-f7cd-1c43-150d-e4451413c7b4',
    detoxDebugVisibility: 'YES',
    detoxDisableHierarchyDump: 'YES'
  },
  pid: 15941
})
detox[15688] TRACE: [ARTIFACTS_LIFECYCLE] artifactsManager.onHookFailure({
  error: 'Exceeded timeout of 120000 ms for a hook.\n' +
    'Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test.',
  hook: 'beforeAll'
})
detox[15688] TRACE: [ARTIFACT_START] starting SimulatorScreenshot
detox[15688] DEBUG: [EXEC_CMD, #12] /usr/bin/xcrun simctl io 0926278E-345F-48B7-B2A8-2133A2C97AC9 screenshot "/private/var/folders/g2/xnd8hpjs50v433gfrybz2nxh0000gn/T/d6413884-aa76-437b-8754-60e1b951ce40.detox.png"
detox[15688] TRACE: [EXEC_SUCCESS, #12] Detected file type 'PNG' from extension
Wrote screenshot to: /private/var/folders/g2/xnd8hpjs50v433gfrybz2nxh0000gn/T/d6413884-aa76-437b-8754-60e1b951ce40.detox.png

detox[15688] TRACE: [ARTIFACT_STOP] stopping SimulatorScreenshot
detox[15688] INFO:  Onboarding: should have welcome screen
detox[15688] INFO:  Onboarding: should have welcome screen [FAIL]
detox[15688] INFO:  Onboarding: should show login screen after tap
detox[15688] INFO:  Onboarding: should show login screen after tap [FAIL]
detox[15688] INFO:  Onboarding: should show signup screen after tap
detox[15688] INFO:  Onboarding: should show signup screen after tap [FAIL]
detox[15688] INFO:  Onboarding: should show forgot password screen after tap
detox[15688] INFO:  Onboarding: should show forgot password screen after tap [FAIL]
detox[15688] INFO:  Onboarding: should go through onboarding flow for North America
detox[15688] INFO:  Onboarding: should go through onboarding flow for North America [FAIL]
detox[15688] INFO:  Onboarding: should go through onboarding flow for Europe
detox[15688] INFO:  Onboarding: should go through onboarding flow for Europe [FAIL]
Onboarding[15688] TRACE: [ARTIFACTS_LIFECYCLE] artifactsManager.onRunDescribeFinish({ name: 'Onboarding' })
ROOT_DESCRIBE_BLOCK[15688] TRACE: [ARTIFACTS_LIFECYCLE] artifactsManager.onRunDescribeFinish({ name: 'ROOT_DESCRIBE_BLOCK' })
detox[15688] TRACE: [ARTIFACTS_LIFECYCLE] artifactsManager.onBeforeCleanup()
detox[15688] TRACE: [ARTIFACT_SAVE] saving SimulatorScreenshot to: /Users/vagrant/deploy/ios12.2022-03-24 18-34-00Z/beforeAllFailure.png
detox[15688] DEBUG: [MOVE_FILE] moving "/private/var/folders/g2/xnd8hpjs50v433gfrybz2nxh0000gn/T/d6413884-aa76-437b-8754-60e1b951ce40.detox.png" to /Users/vagrant/deploy/ios12.2022-03-24 18-34-00Z/beforeAllFailure.png
detox[15688] TRACE: [ARTIFACT_SAVE] saving SimulatorLogRecording to: /Users/vagrant/deploy/ios12.2022-03-24 18-34-00Z/0926278E-345F-48B7-B2A8-2133A2C97AC9 2022-03-24 18-36-52Z.startup.log
detox[15688] TRACE: [ARTIFACT_STOP] stopping SimulatorLogRecording
detox[15688] TRACE: [SPAWN_KILL, #15934] sending SIGINT to: /usr/bin/xcrun simctl spawn 0926278E-345F-48B7-B2A8-2133A2C97AC9 log stream --level debug --style compact --predicate processImagePath beginsWith "/Users/vagrant/Library/Developer/CoreSimulator/Devices/0926278E-345F-48B7-B2A8-2133A2C97AC9/data/Containers/Bundle/Application/FEC7A7BC-4913-41FB-95F2-13A766DB6759/HeroBuddy.app"
detox[15688] DEBUG: [SPAWN_END, #15934] /usr/bin/xcrun simctl spawn 0926278E-345F-48B7-B2A8-2133A2C97AC9 log stream --level debug --style compact --predicate "processImagePath beginsWith \"/Users/vagrant/Library/Developer/CoreSimulator/Devices/0926278E-345F-48B7-B2A8-2133A2C97AC9/data/Containers/Bundle/Application/FEC7A7BC-4913-41FB-95F2-13A766DB6759/HeroBuddy.app\"" finished with code = 130
detox[15688] DEBUG: [MOVE_FILE] moving "/private/var/folders/g2/xnd8hpjs50v433gfrybz2nxh0000gn/T/22b34c88-a444-4de2-9b77-4f03868ef66b.detox.log" to /Users/vagrant/deploy/ios12.2022-03-24 18-34-00Z/0926278E-345F-48B7-B2A8-2133A2C97AC9 2022-03-24 18-36-52Z.startup.log
detox[15688] TRACE: [ARTIFACT_START] starting FileArtifact
detox[15688] TRACE: [ARTIFACT_STOP] stopping FileArtifact
detox[15688] TRACE: [ARTIFACT_SAVE] saving FileArtifact to: /Users/vagrant/deploy/ios12.2022-03-24 18-34-00Z/detox_pid_15688.json.log { append: true }
detox[15688] TRACE: [ARTIFACT_START] starting FileArtifact
detox[15688] TRACE: [ARTIFACT_STOP] stopping FileArtifact
detox[15688] TRACE: [ARTIFACT_SAVE] saving FileArtifact to: /Users/vagrant/deploy/ios12.2022-03-24 18-34-00Z/detox_pid_15688.log { append: true }
detox[15688] DEBUG: [MOVE_FILE] moving "/private/var/folders/g2/xnd8hpjs50v433gfrybz2nxh0000gn/T/86de1434-b125-47a7-a007-0f751fee6173.detox.log" to /Users/vagrant/deploy/ios12.2022-03-24 18-34-00Z/detox_pid_15688.log
detox[15688] DEBUG: [MOVE_FILE] moving "/private/var/folders/g2/xnd8hpjs50v433gfrybz2nxh0000gn/T/84855cfb-9d2c-4dc9-bc0c-7019f8bd3583.detox.log" to /Users/vagrant/deploy/ios12.2022-03-24 18-34-00Z/detox_pid_15688.json.log
detox[15688] ERROR: [APP_UNREACHABLE] Detox can't seem to connect to the test app(s)!

HINT: 

The test app might have crashed prematurely, or has had trouble setting up the connection.
Refer to our troubleshooting guide, for full details: https://wix.github.io/Detox/docs/troubleshooting/running-tests#tests-execution-hangs 

detox[15688] DEBUG: [EXEC_CMD, #13] /usr/bin/xcrun simctl shutdown 0926278E-345F-48B7-B2A8-2133A2C97AC9
detox[15688] DEBUG: [EXEC_TRY, #13] Shutting down 0926278E-345F-48B7-B2A8-2133A2C97AC9...
detox[15688] TRACE: [SESSION_TORN] tester exited session 106c5ac1-f7cd-1c43-150d-e4451413c7b4
detox[15688] TRACE: [EXEC_SUCCESS, #13] 
detox[15688] DEBUG: [EXEC_SUCCESS, #13] 0926278E-345F-48B7-B2A8-2133A2C97AC9 shut down
detox[15688] DEBUG: [WSS_CLOSE] Detox server has been closed gracefully

</details>

### Device logs

<details><summary>Device logs</summary>

Filtering the log data using "processImagePath BEGINSWITH "/Users/vagrant/Library/Developer/CoreSimulator/Devices/0926278E-345F-48B7-B2A8-2133A2C97AC9/data/Containers/Bundle/Application/FEC7A7BC-4913-41FB-95F2-13A766DB6759/HeroBuddy.app""

</details>

### More data, please!

**.detoxrc.json**
```
{
  "testRunner": "jest",
  "runnerConfig": "e2e/config.json",
  "skipLegacyWorkersInjection": true,
  "apps": {
    "ios": {
      "type": "ios.app",
      "binaryPath": "ios/build/Build/Products/Release-iphonesimulator/HeroBuddy.app",
      "build": "xcodebuild -workspace ios/HeroBuddy.xcworkspace -scheme HeroBuddy-Alpha -configuration Release -sdk iphonesimulator -derivedDataPath ios/build EXCLUDED_ARCHS=arm64 "
    },
    "ios13.7": {
      "type": "ios.app",
      "binaryPath": "ios/build/Build/Products/Release-iphonesimulator/HeroBuddy.app",
      "build": "xcodebuild -workspace ios/HeroBuddy.xcworkspace -scheme HeroBuddy-Alpha -configuration Release -sdk iphonesimulator -derivedDataPath ios/build EXCLUDED_ARCHS=arm64 -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.7'"
    },
    "android.alpha.debug": {
      "type": "android.apk",
      "binaryPath": "android/HeroApp/build/outputs/apk/alpha/debug/HeroApp-alpha-debug.apk",
      "build": "cd android && ./gradlew -Dorg.gradle.jvmargs=-Xmx1536m assembleAlphaDebug assembleAlphaDebugAndroidTest -DtestBuildType=debug && cd .."
    },
    "android.beta.debug": {
      "type": "android.apk",
      "binaryPath": "android/HeroApp/build/outputs/apk/beta/debug/HeroApp-beta-debug.apk",
      "build": "cd android && ./gradlew assembleBetaDebug assembleAndroidTest -DtestBuildType=debug && cd .."
    }
  },
  "devices": {
    "simulator12": {
      "type": "ios.simulator",
      "device": {
        "type": "iPhone 8",
        "os": "iOS 12.4"
      }
    },
    "simulator13": {
      "type": "ios.simulator",
      "device": {
        "type": "iPhone 11",
        "os": "iOS 13.7"
      }
    },
    "simulator14": {
      "type": "ios.simulator",
      "device": {
        "type": "iPhone 12",
        "os": "iOS 14.3"
      }
    },
    "simulator15": {
      "type": "ios.simulator",
      "device": {
        "type": "iPhone 13",
        "os": "iOS 15.2"
      }
    },
    "emulator21": {
      "type": "android.emulator",
      "device": {
        "avdName": "Pixel_3a_API_21_x86"
      }
    },
    "emulator22": {
      "type": "android.emulator",
      "device": {
        "avdName": "Pixel_3a_API_22_x86"
      }
    },
    "emulator23": {
      "type": "android.emulator",
      "device": {
        "avdName": "Pixel_3a_API_23_x86"
      }
    },
    "emulator24": {
      "type": "android.emulator",
      "device": {
        "avdName": "Pixel_3a_API_24_x86"
      }
    },
    "emulator25": {
      "type": "android.emulator",
      "device": {
        "avdName": "Pixel_3a_API_25_x86"
      }
    },
    "emulator26": {
      "type": "android.emulator",
      "device": {
        "avdName": "Pixel_3a_API_26_x86"
      }
    },
    "emulator27": {
      "type": "android.emulator",
      "device": {
        "avdName": "Pixel_3a_API_27_x86"
      }
    },
    "emulator28": {
      "type": "android.emulator",
      "device": {
        "avdName": "Pixel_3a_API_28_x86"
      }
    },
    "emulator29": {
      "type": "android.emulator",
      "device": {
        "avdName": "Pixel_3a_API_29_x86"
      }
    },
    "emulator30": {
      "type": "android.emulator",
      "device": {
        "avdName": "Pixel_3a_API_30_x86"
      }
    },
    "emulator31": {
      "type": "android.emulator",
      "device": {
        "avdName": "Pixel_3a_API_31_x86"
      }
    }
  },
  "configurations": {
    "ios12": {
      "device": "simulator12",
      "app": "ios"
    },
    "ios13": {
      "device": "simulator13",
      "app": "ios13.7"
    },
    "ios14": {
      "device": "simulator14",
      "app": "ios"
    },
    "ios15": {
      "device": "simulator15",
      "app": "ios"
    },
    "android21": {
      "device": "emulator21",
      "app": "android.alpha.debug"
    },
    "android22": {
      "device": "emulator22",
      "app": "android.alpha.debug"
    },
    "android23": {
      "device": "emulator23",
      "app": "android.alpha.debug"
    },
    "android24": {
      "device": "emulator24",
      "app": "android.alpha.debug"
    },
    "android25": {
      "device": "emulator25",
      "app": "android.alpha.debug"
    },
    "android26": {
      "device": "emulator26",
      "app": "android.alpha.debug"
    },
    "android27": {
      "device": "emulator27",
      "app": "android.alpha.debug"
    },
    "android28": {
      "device": "emulator28",
      "app": "android.alpha.debug"
    },
    "android29": {
      "device": "emulator29",
      "app": "android.alpha.debug"
    },
    "android30": {
      "device": "emulator30",
      "app": "android.alpha.debug"
    },
    "android31": {
      "device": "emulator31",
      "app": "android.alpha.debug"
    }
  }
}

```
**onboarding.e2e.js**
```
describe('Onboarding', () => {
  beforeAll(async () => {
    console.log("awaiting launch app");
    await device.launchApp({
      newInstance: true,
      launchArgs: { 'DTXEnableVerboseSyncSystem': 'YES', 'DTXEnableVerboseSyncResources': 'YES' }
    });
    console.log("done launch app");

  });

  beforeEach(async () => {
    console.log("Awaiting react native");
    await device.reloadReactNative();
    console.log("Awaited react native");
  });

  it('should have welcome screen', async () => {
    await expect(element(by.id('appName'))).toBeVisible();
    await expect(element(by.id('signup_btn'))).toBeVisible();
    await expect(element(by.id('login_btn'))).toBeVisible();
  });
});
```

**Comment by asafkorem** [comment]
@shaliniatwork thanks for the report. Looking into it.

**Comment by asafkorem** [comment]
iOS 12.x support dropped in Detox v18.

[From the migration guide:](https://wix.github.io/Detox/docs/guide/migration/#180)
> Detox now requires iOS 13.0 and above iOS simulator runtimes, and iOS 12.x and below are no longer supported. This does not require that you drop support for iOS 12.x in your apps, just that tests will no longer work on iOS 12 and below. Please make sure your tests are running on iOS 13 or above
