### ISSUE TITLE
Test Butler unable to dismiss QuickStep ANR's in Detox 19.5.7

### ISSUE THREAD

**Issue by MuckT** [wix/Detox#3275]
### What happened?

After updating to Detox `19.5.7` from `Detox 19.4.5` [Test Butler](https://github.com/linkedin/test-butler) has been unable to dismiss QuickStep ANR Modals.

### Screenshot
<img src="https://user-images.githubusercontent.com/26950305/160176491-584d1a17-a643-4f96-b0b6-c155910bba59.png" width="50%" height="auto" />

### What was the expected behaviour?

QuickStep ANR system modal dismissed by Test Butler.

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

Will work on creating reproduction of this issue with the DetoxTemplate this upcoming week.

### In what environment did this happen?

Detox version: `19.5.7`
React Native version: `0.66.4`
Node version: `v12.22.0`
Device model: `Android SDK built for x86_64`
Android version: `10`
Test-runner (select one): `jest-circus`

### Detox logs

Detox Logs from CI are too long to attach - will include once able to reproduce in [DetoxTemplate](https://github.com/wix-incubator/DetoxTemplate).

### Device logs

Device Logs from CI are too long to attach - will include once able to reproduce in [DetoxTemplate](https://github.com/wix-incubator/DetoxTemplate).

### More data, please!

Will attempt to downgrade `Detox 19.5.7` --> `Detox 19.5.1` --> `Detox 19.4.5`.

**Comment by d4vidi** [comment]
Hey @MuckT! Could you also share how test butler is utilized in your environment? Namely, whether prebaked into your emulator images, or rather installed dynamically via Detox's `utilBinaryPath`? See [this blogpost](https://medium.com/wix-engineering/how-to-execute-android-ui-tests-on-ci-and-stay-alive-eb9089d88c1f) for more info.

**Comment by MuckT** [comment]
@d4vidi We install it dynamically [here](https://github.com/valora-inc/wallet/blob/main/packages/mobile/package.json#L298-L300) via `utilBinaryPath`. You can see our whole repo at [valora-inc/wallet](https://github.com/valora-inc/wallet) as it's open source. Running the e2e tests can be a bit difficult without access to a few things, but we are working on replacing that code with mocks to make outside contributions easier.

**Comment by d4vidi** [comment]
Well there are a few things that come to mind:
1. It is possible that while you have test-butler installed, it's service isn't running. Dive deeper into the the section on test-butler in the [blogpost](https://medium.com/wix-engineering/how-to-execute-android-ui-tests-on-ci-and-stay-alive-eb9089d88c1f) to see what's missing.
2. Since it's _Quickstep_ that isn't responding (the device's launcher) and not the app itself, it is fairly possible that the emulator is a bit slow during boot-time, and hence this happens regardless of Detox or your app. In such cases, the best practice is to have test-butler preinstalled and running on your emulator's quick-boot image.

**Comment by MuckT** [comment]
@d4vidi Thanks for the quick response! I went thought the blogpost and ended up setting up an Android snapshot with [Test Butler](https://github.com/linkedin/test-butler) enabled that we use in CI; since doing so I haven't seen a QuickStep ANR served 🤞. I've also moved away from launching Android Emulators on our own to having Detox launch them and that's it's working well with the aforementioned snapshot.

I used the .sh script below which needs to have the location of android-tools and the name of the avd. I'll include below for those who come across this issue later down the line. Thanks again!

```sh
#!/usr/bin/env bash

set -e

export ANDROID_SDK_ROOT=<where you put android-tools>/android-tools
cd $ANDROID_SDK_ROOT

# Setup QuickBoot for emulator and TestButler based on
# https://medium.com/wix-engineering/how-to-execute-android-ui-tests-on-ci-and-stay-alive-eb9089d88c1f
# Boot Device
$ANDROID_SDK_ROOT/emulator/emulator \
  -verbose \
  -no-boot-anim \
  -no-audio \
  -no-window \
  -gpu swiftshader_indirect \
  @<avd name> \
  &

# Wait for device to be ready
echo "Waiting for device to connect to Wifi, this is a good proxy the device is ready"
until [ `adb shell dumpsys wifi | grep "mNetworkInfo" | grep "state: CONNECTED" | wc -l` -gt 0 ]
do
  sleep 3
done

# Download test butler
curl -f -o ~/test-butler-2.2.1.apk https://repo1.maven.org/maven2/com/linkedin/testbutler/test-butler-app/2.2.1/test-butler-app-2.2.1.apk

# Install test butler
$ANDROID_SDK_ROOT/platform-tools/adb install ~/test-butler-2.2.1.apk

# Launch the test butler background service!
$ANDROID_SDK_ROOT/platform-tools/adb shell am startservice com.linkedin.android.testbutler/com.linkedin.android.testbutler.ButlerService

# Check that service is launched
until [ `$ANDROID_SDK_ROOT/platform-tools/adb shell ps | grep butler | wc -l` -gt 0 ]
do
  sleep 3
done

$ANDROID_SDK_ROOT/platform-tools/adb emu avd snapshot save ci_boot

killall qemu-system-x86_64-headless

```

**Comment by d4vidi** [comment]
Beautiful, thank you!
