### ISSUE TITLE
pipeline - detox build error

### ISSUE THREAD

**Issue by cchristman-shell** [wix/Detox#3276]
### What happened?

Github pipeline: 
run "detox build --configuration android.emu.release" failed

"android.emu.release": {
        "binaryPath": "android/app/build/outputs/apk/dev/release/app-dev-release.apk",
        "build": "cd android; ./gradlew --stacktrace assembleDevRelease assembleAndroidTest -DtestBuildType=release; cd ..",
        "type": "android.emulator",
        "name": "Pixel_API_26"
  }

The errors are in the attached below:
[detox-build-error.txt](https://github.com/wix/Detox/files/8353248/detox-build-error.txt)

### What was the expected behaviour?

Expect to build a executable app-dev-release.apk in the folder below

BUILD FAILED in 3m 45s
detox[5792] WARN:  [build.js] 
Important: after running the build command, Detox could not find your app at the given binary path:
	android/app/build/outputs/apk/dev/release/app-dev-release.apk

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

Tried the latest detox "19.5.7", it returned with the same errors when running "detox build ..." 

### In what environment did this happen?

Detox version: 18.20.2 (and 19.5.7)
React Native version: 0.61.4
Node version: v10.16.3
Device model:  Pixel-API-26
Android version:
Test-runner (select one): jest-circus / jest+jasmine / mocha / other

GitHub macOS agent entire environment attached:
[github-env.txt](https://github.com/wix/Detox/files/8353217/github-env.txt)

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by sandipgupta55** [comment]
"build": "cd android; ./gradlew --stacktrace assembleDevRelease assembleAndroidTest -DtestBuildType=release; cd ..",

need to change from assembleAndroidTest to assembleDevAndroidTest

**Comment by d4vidi** [comment]
@cchristman-shell your gradle build command failed. I'd focus on resolving:
```
\cf2       > Cannot find a version of 'androidx.vectordrawable:vectordrawable' that satisfies the version constraints: \
\pard\pardeftab720\qr\partightenfactor0
{\field{\*\fldinst{HYPERLINK "https://github.com/sede-x/react-client-app-generator/runs/5683693665?check_suite_focus=true#step:6:113"}}{\fldrslt \cf2 113}}\
\pard\pardeftab720\partightenfactor0
\cf2            Dependency path 'ExampleProject:app:unspecified' --> 'com.wix:detox:18.23.1' --> 'com.google.android.material:material:1.2.1' --> 'androidx.vectordrawable:vectordrawable:1.1.0'\
\pard\pardeftab720\qr\partightenfactor0
{\field{\*\fldinst{HYPERLINK "https://github.com/sede-x/react-client-app-generator/runs/5683693665?check_suite_focus=true#step:6:114"}}{\fldrslt \cf2 114}}\
\pard\pardeftab720\partightenfactor0
\cf2            Constraint path 'ExampleProject:app:unspecified' --> 'androidx.vectordrawable:vectordrawable:\{strictly 1.0.1\}' because of the following reason: productionReleaseRuntimeClasspath uses version 1.0.1\
\pard\pardeftab720\qr\partightenfactor0
{\field{\*\fldinst{HYPERLINK "https://github.com/sede-x/react-client-app-generator/runs/5683693665?check_suite_focus=true#step:6:115"}}{\fldrslt \cf2 115}}\
\pard\pardeftab720\partightenfactor0
\cf2            Dependency path 'ExampleProject:app:unspecified' --> 'com.facebook.react:react-native:0.61.4' --> 'androidx.appcompat:appcompat:1.1.0' --> 'androidx.appcompat:appcompat-resources:1.1.0' --> 'androidx.vectordrawable:vectordrawable:1.1.0'\
\pard\pardeftab720\qr\partightenfactor0
{\field{\*\fldinst{HYPERLINK "https://github.com/sede-x/react-client-app-generator/runs/5683693665?check_suite_focus=true#step:6:116"}}{\fldrslt \cf2 116}}\
\pard\pardeftab720\partightenfactor0
\cf2            Dependency path 'ExampleProject:app:unspecified' --> 'com.facebook.react:react-native:0.61.4' --> 'androidx.appcompat:appcompat:1.1.0' --> 'androidx.appcompat:appcompat-resources:1.1.0' --> 'androidx.vectordrawable:vectordrawable-animated:1.1.0' --> 'androidx.vectordrawable:vectordrawable:1.1.0'\
```

There are multiple messages of that sort.

Try to run `./gradlew assembleDevRelease` and `./gradlew assembleAndroidTest -DtestBuildType=release` separately and see. Also, try to use `testBuildType=debug` instead of `release.`
