### ISSUE TITLE
How can i force wait synchronization for retry requests (timeout retry)

### ISSUE THREAD

**Issue by timabilov** [wix/Detox#3278]
### Description

I don't want to be released right after first failed (timeout) request. Because i have to retry that request. Otherwise i get the error. Considering that i have a (central) http middleware where every failed timeout request getting retried, what are the possible optimal solutions here? Can i even use some manually exposed  `countingidlingresource` objects from native java as an example for Android?   

Currently i am planning  to listen directly on specific UI elements to detect the finishing requests , but 'middleware http retry' is far more general than any specific cases, and of course i want to stick to systematic synchronization  approach everywhere as much as i can. 

### Your environment

Detox version: 19.5.7
React Native version: 0.66.3
Node version: v17.7.1
Device model: AOSP Pixel 3
OS:  Mac OS Big Sure
Test-runner (select one): jest-circus

**Comment by d4vidi** [comment]
Hi @timabilov, Detox provides that out of the box, technically. As long as there is something happening in the system -- be it an in-flight network request, or a retry-timer, Detox awaits. Could you provide more details as to what made you think otherwise?
