### ISSUE TITLE
Can't run tests for Android in the debug mode after change port

### ISSUE THREAD

**Issue by PavelRazumov** [wix/Detox#3279]
### Description

Hi Team!
I want to create E2E tests for Android. I went through [this guide](https://wix.github.io/Detox/docs/introduction/android/).

- run build with configaration - detox build -c android.emu.staging.debug -> get success build apk.
- After it, run react-native start --port=8087 (Can't use default port, because it busy security programm McAfee)
- Run test with configuration - detox test -c android.emu.staging.debug
- After run test have error
![image](https://user-images.githubusercontent.com/28491189/160406666-3f70ae68-d387-4dd9-b4eb-37a3c075c220.png)
(Tests have already started running and **wait device.lauchApp()** )
- Then with Ctrl + M change bundle and set 10.0.2.2:8087
![image](https://user-images.githubusercontent.com/28491189/160406862-989b2db3-06ae-4cdd-842f-c5952a3a538b.png)
- After it bundle start building -> Success build.
- And then stuck on launchApp and get timeout error.

Tell please, how can I run test on different ports ? 

I find the same issue https://github.com/wix/Detox/issues/3190 and set bundleInDebug: true helped me, but i think it's the wrong direction.

### Your environment

Detox version: 17.14.3
React Native version: 0.66.0
Node version: 14.15.5
Device model: Android Emulator Pixel 2 API 30
OS: Windows
Test-runner (select one): jest-circus / jest+jasmine / mocha / other
jest

**Comment by d4vidi** [comment]
@jonathanmos can help you out with this

**Comment by PavelRazumov** [comment]
> @jonathanmos can help you out with this, but best if you post this in stack-overflow instead and post the link back here 🙏🏻

Yes, i create post in stack-overflow - https://stackoverflow.com/questions/71661245/cant-run-tests-for-android-in-the-debug-mode-after-change-port

**Comment by PavelRazumov** [comment]
@d4vidi, Can you please tell me, i don't understand, where @jonathanmos will help me on stackoverflow or here ?

**Comment by noomorph** [comment]
@d4vidi @jonathanmos guys, actually I'm inclined to tell you that we might have never checked this (exotic or not, no idea) scenario, so... I wouldn't hurry to close it.

Also, I think we might have hardcoded 8081 somewhere. Correct me if I'm wrong.

**Comment by PavelRazumov** [comment]
Hi team, I tried Jon's solutiuon in stackoverlow, change port with Settings->Debug Server host on 10.0.2.2:8087, then reload and change port with adb reverse. After it i had success build bundle and same timeout error and test stuck on launchApp()

**Comment by jonathanmos** [comment]
@PavelRazumov can you try with localhost:8087?

**Comment by PavelRazumov** [comment]
> @PavelRazumov can you try with localhost:8087?

I checked it, and have same error, launchApp stuck.

![image](https://user-images.githubusercontent.com/28491189/161216825-cde346c6-d864-44bc-ae3d-184b33eb361b.png)

**Comment by PavelRazumov** [comment]
@jonathanmos , Hi I checked hardcode port in node_modules/detox and nothing find. Plus i have a question how detox's tests understand which port used for running build, may be it's configuration during detox build and can change it?
![image](https://user-images.githubusercontent.com/28491189/161700362-dde18c15-cea7-49a9-889d-82af89434a68.png)

**Comment by jonathanmos** [comment]
@PavelRazumov I've reproduced this and had some success with reversing the port and setting the debug server host - the packager at that point can communicate with the emulator and load the bundle. To get the tests to run properly will probably also require increasing the rnContextLoadTimeoutSec in DetoxConfig, although I haven't had the chance to do this yet. I'll try tomorrow and hopefully we can solve this issue.

**Comment by jonathanmos** [comment]
@PavelRazumov Please perform the following steps.

Locate your `DetoxTest.java` file and insert the following lines:

At the top of the class:

        private static final String RN_DEBUG_HOST_KEY = "debug_http_host";

and inside the `runDetoxTests` method:

        Context context = InstrumentationRegistry.getInstrumentation().getTargetContext().getApplicationContext();

        SharedPreferences preferences =
                PreferenceManager.getDefaultSharedPreferences(context);
        preferences.edit().putString(RN_DEBUG_HOST_KEY, "localhost:8087").apply();

        DetoxConfig detoxConfig = new DetoxConfig();
        detoxConfig.rnContextLoadTimeoutSec = 500;

and finally pass the detoxConfig as the third argument to runTests. E.g.: 

        final ActivityTestRule<?> rule = resolveTestRule();
        Detox.runTests(rule, context, detoxConfig);

You will also have to reverse the port - you can do this either manually from the commandline, or by putting the following code inside the beforeAll of your tests:

       await device.reverseTcpPort(8087);

The test set should run properly after you rebuild. Please let me know if there are any issues.

**Comment by PavelRazumov** [comment]
@jonathanmos , thank you very match, I'll try to check solution today or tomorrow

**Comment by PavelRazumov** [comment]
Hi team, excuse me, that late with the answer, I checked this solution, all work great in debug mode. 
Thank you very much!! And in stackoverflow attached link

**Comment by SashaPltnchnk** [comment]
is there any other way to deal with another port? This one didn't work for me
