### ISSUE TITLE
questions about native modules

### ISSUE THREAD

**Issue by IlSassone** [wix/Detox#3280]
### Description

In my appication i have the need to implement various native modules on which the app is based on, so they cant be mocked because i need to test their behaviour.
But there could be some occasions in which the native modules remain pending (eg. connecting to a grpc server that could be offline) and then give a request timeout.
Is there a way to ignore the monitoring of the native modules or to ignore just the synchronization with the thread in which there are the native modules? (without going mad with `waitFor`)

### Your environment

Detox version: 19.5.7
React Native version: 0.67.0-rc.6
Node version: 14
Device model: iphone 13, ios 15.4
OS: macOS monterey
Test-runner (select one): jest-circus

**Comment by d4vidi** [comment]
First thing's first, there are built-in mocking capabilities in RN you can use, and we even have a [guide](https://wix.github.io/Detox/docs/guide/mocking/) for that (a bit out of date, sorry).
In addition, you might want to consider using the [disableSynchronization](https://wix.github.io/Detox/docs/api/device-object-api/#devicedisablesynchronization) API.
