### ISSUE TITLE
launchArgs does not effect Android Emulator

### ISSUE THREAD

**Issue by Brma1048** [wix/Detox#3282]
### What happened?

In my .detoxrc.json I added under apps > android.release > launchArgs: { "dns-server":"<example-dns>"} but it doesn't affect my emulator, I also tried it via the cli: detox test -c android --app-launch-args="-dns-server \"<example-dns\"" but both attempts didn't work. Only when I launch the emulator in another terminal before the test with "emulator -avd "EMULATOR_NAME" -dns-server "<example-dns>", then it works. But my problem is that I want to run this on a Ci and not start the emulator manually in another terminal before testing.

### What was the expected behaviour?

That the launch args affects the emulator start

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 19.4.5
React Native version: 0.66.4
Node version: 17.7.2
Device model: Emulator Pixel 4 APi 30
Android version: 11
Test-runner (select one): jest-circus

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by d4vidi** [comment]
I think you might have had `launchArgs`/`--app-launch-args` mixed up with `--device-launch-args`: https://wix.github.io/Detox/docs/api/detox-cli/#test
