### ISSUE TITLE
Possible bug with "Detox has detected multiple interactions taking place simultaneously" error?

### ISSUE THREAD

**Issue by jamesmcn1** [wix/Detox#3284]
### What happened?

Hey guys :)

I seem to get this error alot "Detox has detected multiple interactions taking place simultaneously", which seems to be a mistake.

Before I had Detox 17+, this would have worked fine:
```
    await waitFor(element(by.id(nextScreenId))).toExist()
    await expect(element(by.id(nextScreenId))).toExist();
   ```
   
However after migrating to Detox 19.15.7 I get this error complaining that there are multiple interactions happening simultaneously. The docs suggest this is due to `await` keywords missing but I have them on ever line. It's really frustrating as the only fix appears to be adding long delay's between each line, but even then it can still fail:
```
    await waitFor(element(by.id(nextScreenId)))
      .toExist()
      .withTimeout(10000);
    await waitFor(element(by.id(nextScreenId)))
    .toBeVisible()
    .withTimeout(10000);
    await delay(750);
    await expect(element(by.id(nextScreenId))).toExist();
    await delay(100);
  ```

UPDATE: Removing `withTimeout`s on `waitFor`s seems to improve slightly. This is the most stable setup I have found works most of the time. However the docs say `waitFor`s must have a `withTimeout` or they will do nothing:
 
 ```
     await waitFor(element(by.id(nextScreenId))).toExist();
    await waitFor(element(by.id(nextScreenId))).toBeVisible();
    await delay(2000);
    await expect(element(by.id(nextScreenId))).toExist();
 ```
 
where:
```
export const delay = async (time = 3000) => new Promise((resolve) => setTimeout(() => resolve(), time));
```

Is there anything that can be done to sort this?

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 19.5.7
React Native version: 0.62.2
Node version: 12.0.0
Device model: 
iOS version: 14.4
macOS version: 
Xcode version: 12+
Test-runner (select one): jest-circus

### Detox logs

<details><summary>Detox logs</summary>

```
DetoxRuntimeError: The pending request #115 ("invoke") has been rejected due to the following error:
    Detox has detected multiple interactions taking place simultaneously. Have you forgotten to apply an await over one of the Detox actions in your test code?
      108 |     await waitFor(element(by.id(screenNameTestIds.TwoFactorOtpValidationScreen))).toBeVisible();
      109 |     await delay(100);
    > 110 |     await expect(element(by.id(screenNameTestIds.TwoFactorOtpValidationScreen))).toExist();
          |                                                                                  ^
      111 |     await device.takeScreenshot('OtpValidationScreen - default');
      112 |   });
      113 |
      at _callee7$ (TwoFactor/TwoFactorSetupFlowTests.spec.js:110:82)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:293:22)
      at Generator.next (../node_modules/regenerator-runtime/runtime.js:118:21)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:63:40)
      at invoke (../node_modules/regenerator-runtime/runtime.js:154:20)
      at ../node_modules/regenerator-runtime/runtime.js:164:13
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by d4vidi** [comment]
@jamesmcn1 could you please rerun your test with the `--loglevel trace` argument to `detox test` and paste the logs? Thanks

**Comment by jamesmcn1** [comment]
Ah in the end, we release that some of our helpers weren't returning promises properly, which meant async/await wasn't working as expected. Stuff like this:
```
export const saveButton = {
buttonEnabled(.....
}
```

Instead of this:
```
export const saveButton => buttonEnabled()
```

All good now! thanks

**Comment by d4vidi** [comment]
Oh great find. Kudos
