### ISSUE TITLE
Clean up lint warnings

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#3292]
### Describe your idea

Simply put, I think we've had enough of seeing this in every PR:

![image](https://user-images.githubusercontent.com/9818880/161432472-153bb69e-a538-40d5-949f-a05750b7645f.png)

**Comment by noomorph** [comment]
Well, part of them will go away with Detox 20, but every item needs some groundwork to be resolved.

**Comment by d4vidi** [comment]
Great. I think lifting the restrictions over ToDo's would make a huge difference, for starters.

**Comment by noomorph** [comment]
I might take it tomorrow for 1-2 hours, maybe partially I can remove around 20 warnings.

**Comment by d4vidi** [comment]
Great if you could get to doing this, sometime soon. Will make our PR's much cleaner.

**Comment by noomorph** [comment]
@d4vidi oh damn it :) I forgot to push the branch 
Here it is
https://github.com/wix/Detox/pull/3719
You're welcome to see it.
