### ISSUE TITLE
Add expect methods to check all the accessibility properties

### ISSUE THREAD

**Issue by immohanrajmuthu1502** [wix/Detox#3301]
### Describe your idea

Currently detox supports to check the accessibility label, text and value.
Please provide expect methods to check the accessibilityHint and accessibilityRole

**Comment by noomorph** [comment]
Could you add a few lines of code to illustrate what you mean? These days I am working far from the matchers / expectations domain and I need some refreshal. 🙏  Thanks.

**Comment by d4vidi** [comment]
Closing in favor of #3116 (will reopen on account of objections).
