### ISSUE TITLE
Add a command line flag to disable `_getStatusSign`

### ISSUE THREAD

**Issue by SMJ93** [wix/Detox#3309]
### Describe your idea

I am trying to automate the generation and uploading of screenshots for my app using Detox and [fastlane](https://docs.fastlane.tools/getting-started/ios/screenshots/).

I have managed to build the path fastlane requires by passing in a custom artifacts location `--artifacts-location ios/fastlane/screenshots/` and naming my tests appropriately: `ios/fastlane/screenshots/hi/0_APP_IPHONE_55_0.png`

Unfortunately Detox automatically adds a `✓ ` before any tests that passes so the detox test outputs:
```ios/fastlane/screenshots/✓ hi/0_APP_IPHONE_55_0.png```

I managed to fix this by using [patch-package](https://github.com/ds300/patch-package) to update `node_modules/detox/src/artifacts/utils/ArtifactPathBuilder.js` -> `_getStatusSign` to always return `"" `.

It would be great if we could pass a cli argument such as `--disable-status-sign` which would disable this instead of needing to patch the library.

**Comment by noomorph** [comment]
Well, you can override that logic, I guess, if you specify your own path builder implementation. It is not brilliantly documented, probably, but we do have some docs on it:

https://wix.github.io/Detox/docs/api/artifacts/#:~:text=pathBuilder (in **Configuration Object** section)

Also, some code:

https://github.com/wix/Detox/blob/master/examples/demo-react-native-jest/e2e/detox.pathbuilder.js
https://github.com/wix/Detox/blob/master/examples/demo-react-native-jest/detox.config.js#L63

**Comment by SMJ93** [comment]
Cheers @noomorph, I will try to find some time over the next few weeks and create a PR 👍

**Comment by noomorph** [comment]
@SMJ93 do you mean PR to the docs or something else?

**Comment by SMJ93** [comment]
@noomorph this would require adding another CLI flag so a PR would need to update the docs + code.

e.g. Add `--disable-status-sign`.


```
detox test --configuration ios.sim.debug --disable-status-sign
```
