### ISSUE TITLE
Retaining Redux state

### ISSUE THREAD

**Issue by rengarima** [wix/detox#331]
#### Description
I want to test if the typed text is retained after moving between different forms. it works manually but fails on detox . Is it something detox can't do ? or do I need to do anything extra?
```js
await testHelper.replaceText(mandFields.payer_f_name, "Verify Form Closure");
await element(by.id(mandFields.payer_f_name)).swipe("left", "slow");
await element(by.id("protection.grossIncome")).swipe("right", "slow");
await testHelper.assertHasLabel(mandFields.payer_f_name,"Verify Form Closure");
```

**Comment by rotemmiz** [comment]
Not sure I can understand the issue from the little details you gave.
Please tell us more on what you are trying to accomplish, supply detox logs, device logs, and configuration if needed. 
Also, please state the versions of Detox, Node, Xcode, React Native...

**Comment by rengarima** [comment]
The app is for form filling, there are multiple "pages" for these forms, you can swipe back and forth between the "pages" but it retains the values in all pages ( maintained in redux state ). When I try out a test manually the details I have entered is retained in different pages even if i swipe in and out. However, the same test fails when written with Detox.

Is this a scenario that Detox can handle? 

RN: 0.47.2
Detox: 5.8.1
Node: 8.4.0
Device: "iPad Air 2, iOS 10.3"
Xcode: 9.0
macOS: 10.12.6

**Comment by LeoNatan** [comment]
As long as the app logic works, I don’t see how Detox can interfere. Could be that your internal logic does not work with `replaceText`, which acts as if the user “pasted” the text, rather than type it. Make sure your app handles all text events properly. Add logs to your app logic and see that it sees text changes properly and acts up them as you expect.
