### ISSUE TITLE
Example of Using Contact Picker, Date Picker

### ISSUE THREAD

**Issue by rengarima** [wix/detox#332]
Any example on how to work with 
1. Contact Picker
2. Date Picker

Thanks!

**Comment by SMJ93** [comment]
@rengarima we are testing the `react-native-modal-datetime-picker` in our project using `by.text()`.

add a `testID` to your datepicker and then run:

```
    await element(by.id('datepicker')).tap();
    await element(by.text('2017')).tap();
    await element(by.text('2016')).tap();
    await expect(element(by.text('OK'))).toBeVisible();
    await element(by.text('OK')).tap();
```

Hope this helps!

**Comment by LeoNatan** [comment]
@SMJ93 That is not a scalable solution. If you had a large range of years, such as 1901-2051 and you wanted to pick 1973, that element does not exist to be selected by text (internally, the picker view reuses views to only hold the visible views in memory).

**Comment by rengarima** [comment]
Thanks @SMJ93  this works! 

Would you have some idea for Contact Picker, I have tried searching by text, label but not sure if Detox can handle that?

**Comment by LeoNatan** [comment]
Since iOS 9, all contact view controllers render in a different process. That is not supported by Detox.
