### ISSUE TITLE
Documentation Issue Type

### ISSUE THREAD

**Issue by ball-hayden** [wix/Detox#3320]
### Describe your idea

I have a documentation issue to report - it's not an enhancement, or an iOS or Android bug.

Please can we have an issue type for generic documentation?

**Comment by asafkorem** [comment]
> Great idea. I will add another issue type.

Rethinking about this, it's pretty rare to have a documentation bug (for example, broken link), and in most cases it's quite easy to open a PR to fix it (this case was a bit unique). The "enhancement" issue type can fit most issues related to documentation..
Maybe any of you guys have a different opinion @wix/detox-team?

**Comment by noomorph** [comment]
Yes, docs belong to `enhancement` type.

**Comment by d4vidi** [comment]
I was proposing to Asaf that we would have the option of a "bug report - other" template, seeing that the limitation to iOS/Android is a bit simplistic to my taste. WDYT?

**Comment by asafkorem** [comment]
Resolved here: https://github.com/wix/Detox/pull/3327.
Thanks @ball-hayden
