### ISSUE TITLE
Parallel Test Execution on iOS

### ISSUE THREAD

**Issue by GuillaumeHemmen** [wix/Detox#3325]
### Description

Hello everyone,

I don't know if it's a bug or not but when I try to run parallel testing with iOS I have, as documented, some devices booted to match the number of runners (in my case 2).

As the tests run I see that detox stops using the running emulators to start a new one and does not reuse the existing ones.

At the end of my test, I end up with 6 (sometimes more) emulators instead of the expected 2.

To run my test I simply use the CLI: detox test -c 526-e2e-ios --record-logs all --take-screenshots all --record-videos all -w 2

From the logs generated I don't see any error that catches my eye, I have attached them if somebody wants to take a look at them (one log was generated by a runner): 
[detox_pid_69315.log](https://github.com/wix/Detox/files/8472846/detox_pid_69315.log)
[detox_pid_69316.log](https://github.com/wix/Detox/files/8472847/detox_pid_69316.log)

Are there any problems here or do  I miss anything?

### Your environment

Detox version: 19.6.5
React Native version: 0.65.1
Node version: 14.18.1
Device model: iPhone-12
OS: iOS 15.4
Test-runner (select one): jest-circus

**Comment by noomorph** [comment]
In your `e2e/config.json` do you have `maxWorkers: 1` ?

**Comment by GuillaumeHemmen** [comment]
Hello @noomorph, yes I can see `maxWorkers: 1` should I remove this line? I would have expected it to have the line overwritten if I pass the `workers` parameter to the CLI.

**Comment by noomorph** [comment]
Nope, I'm just checking if you have the fuse against running one-simulator-per-file situtation. Okay, you do have. I'll get back soon.

**Comment by noomorph** [comment]
What is your runner config and do you have `setupFilesAfterEnv` in your Jest config?

**Comment by GuillaumeHemmen** [comment]
Hello @noomorph,

I am not 100% sur of what you are asking for with `setupFilesAfterEnv` so here are my configs from the e2e folder:
 - [config.json](https://pastebin.com/3PrFdU0N)
 - [environment.js](https://pastebin.com/0D8d30K9)

Also, my [.detoxrc.json](https://pastebin.com/hjVveTER).

**Comment by noomorph** [comment]
Okay, interesting. Now I eliminated all other possibilities regarding the integration with test runners. I'll get back later.

**Comment by noomorph** [comment]
I think the problem is that you use:

```
    device: {
      name: 'iPhone 12',
      os: 'iOS 15.4'
    }
```

Change `name` to `type`.

**Comment by noomorph** [comment]
I'll explain what happens. Detox when it does not find a free device matching the criteria (you have 2 workers, one of which is occupying the said device), it creates a clone of such a device with `${name}-Detox`.

But the problem is that the next query (provided that the free device has `${name}-Detox` name) won't list it in the array of available simulators. That's why you again will be creating a new device on the basis of the device used by your first worker.

Please report if that solves your issue.

**Comment by GuillaumeHemmen** [comment]
Hello @noomorph,

This is my understanding: I would need to have X device with the name `iPhone 12` where X is my number of workers. Only then detox will be able to reuse these phones without having to create a phone with another name (here `${name}-Detox`).

Is my understanding correct?

**Comment by noomorph** [comment]
@GuillaumeHemmen no, you misunderstood me.

That is the fix for your situation. Fix your config:

```diff
 device: {
-    name: 'iPhone 12',
+    type: 'iPhone 12',
     os: 'iOS 15.4'
 }
```

**Comment by GuillaumeHemmen** [comment]
Ah ok, I completely misunderstood you. Now it's crystal clear! Thanks a million for your support and patience! I'll close the ticket.

Have a lovely day.

**Comment by noomorph** [comment]
Postmortem: shall we warn people about using `name` with multiple workers or shall we not append `-Detox` all the time? @d4vidi @asafkorem @jonathanmos Actually this is an interesting thing to muse over.
