### ISSUE TITLE
Make it clearer that only react-native is supported currently

### ISSUE THREAD

**Issue by mmeyer-eh** [wix/Detox#3383]
### What happened?

Its not clear from this projects headline that only react-native is fully supported at this time.

The readme states:
"Detox is built from the ground up to support React Native projects **as well as pure native ones**."

But after following the [first test docs](https://wix.github.io/Detox/docs/introduction/writing-first-test), It seems like all of the test examples assume the apps under test are react-native.
 
Believe this also might related to the detox-native effort, which appear to still be very much WIP:
https://github.com/wix/Detox/blob/485ba69e757faf71b6556c3ec6083690b949d744/detox/detox-native/README.md

If this assumption is incorrect, then better test example docs for non-react-native apps ( swift/obj-c/kotlin/java ) may be helpful.

**Comment by noomorph** [comment]
@d4vidi, @mmeyer-eh is totally right. It's not made clear enough. There's indeed some basic capability for native iOS apps, but even there I'm not sure whether it works well enough now.

**Comment by bytedissident** [comment]
@noomorph are there plans for Native (SwiftUI) compliance. I would love to use it.

**Comment by d4vidi** [comment]
Yes, we haven't had capacity to maintain native support for quite some time now.

**Comment by noomorph** [comment]
@asafkorem , could you comment about SwiftUI compliance? I have zero idea what this means. 🙏 


As for the
