### ISSUE TITLE
iOS builds from Xcode 13.4 don't work with Detox

### ISSUE THREAD

**Issue by phillip-kic** [wix/Detox#3408]
### What happened?

Any builds created with Xcode 13.4 are not controllable by Detox. When the test starts, app opens, the app crashes and test fails.

Crash in Device Logs is: `NSPredicate: NSFunctionExpression with selector 'dtx_text' is forbidden.`

The app only crashes when detox tries to trigger events, not in normal use.
Downgrading to Xcode 13.3.1 fixes it. May be related to this issue: #3384 

### What was the expected behaviour?

Detox server to be able to send events that are triggered in app without a crash

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [x] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 19.6.9
React Native version: 0.66.1
Node version: 14.17.3
Device model: MacBook Pro (2018), iPhone 12 Pro Max
iOS version: iOS 15.5
macOS version: 12.3.1
Xcode version: 13.4
Test-runner (select one): jest-circus

### Detox logs

<details><summary>Detox logs</summary>
[detox_pid_10436.json.log](https://github.com/wix/Detox/files/8725306/detox_pid_10436.json.log)

</details>

### Device logs

Full logs are too big to post. Showing a snippet with the crash
<details><summary>Device logs</summary>
[device.log](https://github.com/wix/Detox/files/8725308/device.log)

```
2022-05-19 15:14:26.650 I  App Nameer[11394:2b3cd7] [com.wix.Detox:WebSocket] Action received: waitForActive
2022-05-19 15:14:26.656 I  App Nameer[11394:2b3cd7] [com.wix.Detox:WebSocket] Action received: invoke
2022-05-19 15:14:26.658 A  App Nameer[11394:2b3cd7] (libsystem_trace.dylib) Activity for state dumps
2022-05-19 15:14:26.658 F  App Nameer[11394:2b3cd7] [com.apple.Foundation:general] NSPredicate: NSFunctionExpression with selector 'dtx_text' is forbidden.
2022-05-19 15:14:26.663 E  App Nameer[11394:2b3cd7] [com.wix.Detox:DetoxManager] App crashed: Signal 6 was raised
(
	0   Detox                               0x000000010e761915 +[NSThread(DetoxUtils) dtx_demangledCallStackSymbols] + 37
	1   Detox                               0x000000010e764370 __DTXHandleCrash + 464
	2   Detox                               0x000000010e764ab1 __DTXHandleSignal + 59
	3   libsystem_platform.dylib            0x00007fff701bddfd _sigtramp + 29
	4   ???                                 0x0000000000000000 0x0 + 0
	5   libsystem_c.dylib                   0x00007fff2010b6b7 abort + 130
	6   Foundation                          0x00007fff2087f78e +[_NSPredicateUtilities _predicateSecurityAction] + 42
	7   Foundation                          0x00007fff20775dba -[NSFunctionExpression expressionValueWithObject:context:] + 958
	8   Foundation                          0x00007fff2073116f -[NSComparisonPredicate evaluateWithObject:substitutionVariables:] + 326
	9   Foundation                          0x00007fff20734355 -[NSCompoundPredicateOperator evaluatePr<…>
2022-05-19 15:14:26.663 I  App Nameer[11394:2b3cd7] [com.wix.Detox:DetoxInstrumentsManager] Called stop but no recording in progress

```

</details>

**Comment by asafkorem** [comment]
Hey @phillip-kic, please try to run your tests with a iPhone Simulator with iOS version <= 15.0?
We experience some issues with iOS > 15.0 and this error message seems to be related. 
This is under investigation and we will update as soon as there's a solution.

Also, please update here if iOS <= 15.0 works for you.
