### ISSUE TITLE
Where to find `testSummary` mentioned in Detox test life cycle docs

### ISSUE THREAD

**Issue by RhyG** [wix/Detox#3409]
### Description

I am trying to enable video and screenshot artifacts for my Detox tests, and have bounced around the various pages and added `detox.beforeEach` and `detox.afterEach` as per [this page](https://github.com/wix/Detox/blob/master/docs/APIRef.Artifacts.md#screenshots-and-videos-do-not-appear-in-the-artifacts-folder).

I am not sure exactly how I am meant to get this `testSummary` value from within the `init.ts` of my tests, and the [link provided](https://github.com/wix/Detox/tree/master/examples/demo-react-native-jest/e2e/init.js) 404s, and I can't find the equivalent file in that directory.

Apologies if I have missed the page answering this, but have looked around everywhere and many links are broken or docs are missing. Would really appreciate learning how to get that `testSummary` from within the context on my `beforeEach` within my init file. Thanks!

### Your environment

Detox version: 19.5.8
React Native version: 0.67 
Node version: 16.1.0
Device model: n/a
OS: macOS Monterey
Test-runner (select one): jest

**Comment by noomorph** [comment]
Hi, thanks a lot for pointing this out! ❤️  That troubleshooting advice is enormously outdated. I removed it from the docs.

**Comment by RhyG** [comment]
Hey mate, thanks heaps for the update. I'm still not sure where to get that test summary information to pass through to my custom `pathBuilder` however. I understand I can set the details of the test via that `detox.beforeEach(testSummary)` but can't find the relevant docs on where to get the current test information.

I have looked at the [test lifecycle docs](https://wix.github.io/Detox/docs/api/test-lifecycle) but that also contains the same dead link, and the code sample won't work because there is no instance of `this` in the `init.ts`.

**Comment by RhyG** [comment]
> Hi, thanks a lot for pointing this out! ❤️ That troubleshooting advice is enormously outdated. I removed it from the docs.

Hey mate, thanks heaps for the update. I'm still not sure where to get that test summary information to pass through to my custom `pathBuilder` however. I understand I can set the details of the test via that `detox.beforeEach(testSummary)` but can't find the relevant docs on where to get the current test information.

I have looked at the [test lifecycle docs](https://wix.github.io/Detox/docs/api/test-lifecycle) but that also contains the same dead link, and the code sample won't work because there is no instance of this in the init.ts.

**Comment by noomorph** [comment]
@RhyG, if you register a custom path builder, it gets injected, see here an example:

https://github.com/wix/Detox/blob/master/examples/demo-react-native-jest/e2e/detox.pathbuilder.js#L13

**Comment by RhyG** [comment]
Yep I am that far and able to access it in the custom path builder, but from what I can tell from the docs that test summary is dynamically updated based on what you pass to `detox.beforeEach()` and `detox.afterEach()` so I was trying to find out how to get the current test information (test name, status etc) in order to generate that test summary and pass it to them. I am not currently using the Jasmine adapters I have seen in some docs so will try that.

I will just close this and keep searching the docs. Thanks a lot for the help. :)

**Comment by noomorph** [comment]
No worries, @RhyG , you can ask questions, as the docs might be out of sync on this topic. I am just not 100% sure what you are trying to achieve. Search for DetoxCoreListener in our codebase - you'll see that we forward Jest environment events (including so-called beforeEach/afterEach) to those Detox lifecycle handlers.
