### ISSUE TITLE
Cannot build project because of the @react-native-async-storage

### ISSUE THREAD

**Issue by maldzi** [wix/Detox#3419]
### What happened?

I am trying to set detox for my mobile app as mobile testing framework.
When I run command: detox build --configuration android.emu.debug, I constantly got this error:
![image](https://user-images.githubusercontent.com/18088259/170189915-4c12d24d-8e2f-4fef-bc21-4ed263b15c46.png)

I searched for similar issued but nothig found. 

I removed node_modules, cleared gradle caches. Nothing helps.

Is seems that there is a problem with a @react-native-async-storage_async-storage. Is is supported by detox? 

### What was the expected behaviour?

I want to be able to run to the tests.

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 19.6.6
React Native version: 0.64.2
Node version: 15.12.2
Device model: no applicable trying on simulator
Android version: no applicable trying on simulator
Test-runner (select one): jest-circus
Machine: Windows 11

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by maldzi** [comment]
Update: I removed @react-native-async-storage dependency from node modules, comment import from this library in the MainAplication.js and then try to run detox build. It ends with success. There are some problems with compatibility between detox and the @react-native-async-storage library.

**Comment by d4vidi** [comment]
Hi, the logs in the screenshot you've provided do not provide a whole lot of info. Could you try to rerun `gradlew` with --info or --debug so we could pinpoint the exact problem?

On more thing to try is to run app and test commands separately. Namely, instead of `gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug`, run:

```
gradlew assembleDebug
```

and only then:
```
gradlew assembleAndroidTest -DtestBuildType=debug
```

Please report the results back here.
