### ISSUE TITLE
App crashed and then displayed Signal 6 was raised

### ISSUE THREAD

**Issue by sivvoy** [wix/Detox#3422]
### What happened?

Hi, 

hope you are well. I'm new to detox testing and need some assistance. Since we upgrade to RN0.68.2, we been getting this signal 6 error when running IOS.

**Detox can launch simulator but when it tries to log in, it hang for about 5 secs and then crashed.** 

I have shared the following configs/code. 

**config.json**

{
    "setupFilesAfterEnv": ["<rootDir>/init.js"],
    "testEnvironment": "node"
}

**init.js**

// eslint-disable-next-line import/no-duplicates
import detox from 'detox';
import packageFile from '../package.json';
// eslint-disable-next-line import/no-duplicates
import { device } from 'detox';

const detoxConfig = packageFile.detox;

jest.setTimeout(120000);

beforeAll(async () => {
  await detox.init(detoxConfig, { launchApp: false });
  await device.launchApp();
});

afterAll(async () => {
  await detox.cleanup();
});

**jest test**

import { expect, by, element } from 'detox';

describe('Testing login', () => {
  it('user can successfully login', async () => {
    await element(by.id('usernameInput')).typeText('username');
    await element(by.id('passwordInput')).typeText('password');
    await element(by.id('logInButton')).tap();
  });
});

**package.json**

  "detox": {
    "testRunner": "jest",
    "runnerConfig": "e2e/config.json",
    "skipLegacyWorkersInjection": true,
    "apps": {
      "ios": {
        "type": "ios.app",
        "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/something.app",
        "build": "xcodebuild -workspace ios/something.xcworkspace -configuration Debug -scheme something -sdk iphonesimulator -derivedDataPath ios/build -arch x86_64 DETOX=1"
      }
    },
    "devices": {
      "simulator": {
        "type": "ios.simulator",
        "device": {
          "type": "iPhone 11"
        }
      }
    },
    "configurations": {
      "ios": {
        "device": "simulator",
        "app": "ios"
      }
    }
  }

"jest": "^26.6.3",
 "detox": "^19.5.7",

System:    OS: macOS 12.0
    CPU: (10) x64 Apple M1 Max
    Memory: 53.95 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.14.0/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 27, 28, 29, 30
      Build Tools: 29.0.2, 29.0.3, 30.0.3
      System Images: android-29 | Intel x86 Atom_64, android-30 | Intel x86 Atom_64, android-30 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.2 => 0.68.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### What was the expected behaviour?

Error

DetoxRuntimeError: The pending request #2 ("invoke") has been rejected due to the following error:

    The app has crashed, see the details below:

    Signal 6 was raised
    (
    	0   Detox                               0x0000000110453915 +[NSThread(DetoxUtils) dtx_demangledCallStackSymbols] + 37
    	1   Detox                               0x0000000110456370 __DTXHandleCrash + 464
    	2   Detox                               0x0000000110456ab1 __DTXHandleSignal + 59
    	3   libsystem_platform.dylib            0x000000011338d06d _sigtramp + 29
    	4   libsystem_malloc.dylib              0x0000000113014dee nanov2_allocate + 142
    	5   libsystem_c.dylib                   0x00000001132436b7 abort + 130
    	6   Foundation                          0x000000011252a78e +[_NSPredicateUtilities _predicateSecurityAction] + 42
    	7   Foundation                          0x0000000112420dba -[NSFunctionExpression expressionValueWithObject:context:] + 958
    	8   Foundation                          0x00000001123dc16f -[NSComparisonPredicate evaluateWithObject:substitutionVariables:] + 326
    	9   Detox                               0x0000000110457a46 __87+[UIView(DetoxMatchers) _dtx_appendViewsRecursivelyFromArray:passingPredicate:storage:]_block_invoke + 65
    	10  CoreFoundation                      0x000000011403a4a0 __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__ + 7
    	11  CoreFoundation                      0x0000000113fc4732 -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 224
    	12  Detox                               0x0000000110457980 +[UIView(DetoxMatchers) _dtx_appendViewsRecursivelyFromArray:passingPredicate:storage:] + 185
    	13  Detox                               0x0000000110457b61 +[UIView(DetoxMatchers) dtx_findViewsInWindows:passingPredicate:] + 89
    	14  Detox                               0x0000000110457d6d +[UIView(DetoxMatchers) dtx_findViewsInKeySceneWindowsPassingPredicate:] + 144
    	15  Detox                               0x00000001104733c6 Detox.Element.(views in _14E24C92C1353FEA1FC68E698CB917EF).getter : Swift.Array<__C.NSObject> + 214
    	16  Detox                               0x00000001104736f2 Detox.Element.(view in _14E24C92C1353FEA1FC68E698CB917EF).getter : __C.NSObject + 50
    	17  Detox                               0x0000000110465e0a merged Detox.TypeTextAction.perform(on: Detox.Element) -> Swift.Optional<Swift.Dictionary<Swift.String, Any>> + 138
    	18  Detox                               0x0000000110465d59 vtable thunk for Detox.Action.(perform in _04ABBB5C7C570871DB67625EF38728EC)(on: Detox.Element) -> Swift.Optional<Swift.Dictionary<Swift.String, Any>> dispatching to Detox.TypeTextAction.perform(on: Detox.Element) -> Swift.Optional<Swift.Dictionary<Swift.String, Any>> + 9
    	19  Detox                               0x0000000110464990 Detox.Action.(perform in _04ABBB5C7C570871DB67625EF38728EC)(on: Detox.Element, completionHandler: (Swift.Optional<Swift.Dictionary<Swift.String, Any>>, Swift.Optional<Swift.Error>) -> ()) -> () + 32
    	20  Detox                               0x000000011046a08b partial apply forwarder for closure #1 () -> () in Detox.Action.perform(completionHandler: (Swift.Optional<Swift.Dictionary<Swift.String, Any>>, Swift.Optional<Swift.Error>) -> ()) -> () + 43
    	21  Detox                               0x000000011046a0d1 partial apply forwarder for reabstraction thunk helper from @callee_guaranteed () -> () to @escaping @callee_guaranteed () -> () + 17
    	22  Detox                               0x0000000110466dfe reabstraction thunk helper from @escaping @callee_guaranteed () -> () to @escaping @callee_unowned @convention(block) () -> () + 14
    	23  Detox                               0x0000000110460140 +[DTXAssertionHandler try:error:] + 47
    	24  Detox                               0x0000000110464aa1 Detox.Action.perform(completionHandler: (Swift.Optional<Swift.Dictionary<Swift.String, Any>>, Swift.Optional<Swift.Error>) -> ()) -> () + 241
    	25  Detox                               0x00000001104716ba function signature specialization <Arg[1] = Dead, Arg[2] = Owned To Guaranteed, Arg[3] = Owned To Guaranteed> of function signature specialization <Arg[1] = [Closure Propagated : closure #1 (Swift.Optional<Swift.Dictionary<Swift.String, Any>>, Swift.Optional<Swift.Error>) -> () in closure #2 () -> () in Detox.DetoxManager.webSocket(_: Detox.WebSocket, didReceiveAction: Swift.String, params: Swift.Dictionary<Swift.String, Any>, messageId: __C.NSNumber) -> (), Argument Types : [Detox.DetoxManager__C.NSNumber]> of static Detox.InvocationManager.invoke(dictionaryRepresentation: Swift.Dictionary<Swift.String, Any>, completionHandler: (Swift.Optional<Swift.Dictionary<Swift.String, Any>>, Swift.Optional<Swift.Error>) -> ()) -> () + 954
    	26  Detox                               0x000000011048b621 partial apply forwarder for closure #2 () -> () in Detox.DetoxManager.webSocket(_: Detox.WebSocket, didReceiveAction: Swift.String, params: Swift.Dictionary<Swift.String, Any>, messageId: __C.NSNumber) -> () + 65
    	27  Detox                               0x0000000110466dfe reabstraction thunk helper from @escaping @callee_guaranteed () -> () to @escaping @callee_unowned @convention(block) () -> () + 14

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 19.5.7
React Native version: 0.68.2
Node version: 16.14.0
Device model: 
iOS version: 
macOS version: macOS 12.0
Xcode version: 13.4
Test-runner (select one): jest

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```
DetoxRuntimeError: The pending request #2 ("invoke") has been rejected due to the following error:

    The app has crashed, see the details below:

    Signal 6 was raised
    (
    	0   Detox                               0x0000000110453915 +[NSThread(DetoxUtils) dtx_demangledCallStackSymbols] + 37
    	1   Detox                               0x0000000110456370 __DTXHandleCrash + 464
    	2   Detox                               0x0000000110456ab1 __DTXHandleSignal + 59
    	3   libsystem_platform.dylib            0x000000011338d06d _sigtramp + 29
    	4   libsystem_malloc.dylib              0x0000000113014dee nanov2_allocate + 142
    	5   libsystem_c.dylib                   0x00000001132436b7 abort + 130
    	6   Foundation                          0x000000011252a78e +[_NSPredicateUtilities _predicateSecurityAction] + 42
    	7   Foundation                          0x0000000112420dba -[NSFunctionExpression expressionValueWithObject:context:] + 958
    	8   Foundation                          0x00000001123dc16f -[NSComparisonPredicate evaluateWithObject:substitutionVariables:] + 326
    	9   Detox                               0x0000000110457a46 __87+[UIView(DetoxMatchers) _dtx_appendViewsRecursivelyFromArray:passingPredicate:storage:]_block_invoke + 65
    	10  CoreFoundation                      0x000000011403a4a0 __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__ + 7
    	11  CoreFoundation                      0x0000000113fc4732 -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 224
    	12  Detox                               0x0000000110457980 +[UIView(DetoxMatchers) _dtx_appendViewsRecursivelyFromArray:passingPredicate:storage:] + 185
    	13  Detox                               0x0000000110457b61 +[UIView(DetoxMatchers) dtx_findViewsInWindows:passingPredicate:] + 89
    	14  Detox                               0x0000000110457d6d +[UIView(DetoxMatchers) dtx_findViewsInKeySceneWindowsPassingPredicate:] + 144
    	15  Detox                               0x00000001104733c6 Detox.Element.(views in _14E24C92C1353FEA1FC68E698CB917EF).getter : Swift.Array<__C.NSObject> + 214
    	16  Detox                               0x00000001104736f2 Detox.Element.(view in _14E24C92C1353FEA1FC68E698CB917EF).getter : __C.NSObject + 50
    	17  Detox                               0x0000000110465e0a merged Detox.TypeTextAction.perform(on: Detox.Element) -> Swift.Optional<Swift.Dictionary<Swift.String, Any>> + 138
    	18  Detox                               0x0000000110465d59 vtable thunk for Detox.Action.(perform in _04ABBB5C7C570871DB67625EF38728EC)(on: Detox.Element) -> Swift.Optional<Swift.Dictionary<Swift.String, Any>> dispatching to Detox.TypeTextAction.perform(on: Detox.Element) -> Swift.Optional<Swift.Dictionary<Swift.String, Any>> + 9
    	19  Detox                               0x0000000110464990 Detox.Action.(perform in _04ABBB5C7C570871DB67625EF38728EC)(on: Detox.Element, completionHandler: (Swift.Optional<Swift.Dictionary<Swift.String, Any>>, Swift.Optional<Swift.Error>) -> ()) -> () + 32
    	20  Detox                               0x000000011046a08b partial apply forwarder for closure #1 () -> () in Detox.Action.perform(completionHandler: (Swift.Optional<Swift.Dictionary<Swift.String, Any>>, Swift.Optional<Swift.Error>) -> ()) -> () + 43
    	21  Detox                               0x000000011046a0d1 partial apply forwarder for reabstraction thunk helper from @callee_guaranteed () -> () to @escaping @callee_guaranteed () -> () + 17
    	22  Detox                               0x0000000110466dfe reabstraction thunk helper from @escaping @callee_guaranteed () -> () to @escaping @callee_unowned @convention(block) () -> () + 14
    	23  Detox                               0x0000000110460140 +[DTXAssertionHandler try:error:] + 47
    	24  Detox                               0x0000000110464aa1 Detox.Action.perform(completionHandler: (Swift.Optional<Swift.Dictionary<Swift.String, Any>>, Swift.Optional<Swift.Error>) -> ()) -> () + 241
    	25  Detox                               0x00000001104716ba function signature specialization <Arg[1] = Dead, Arg[2] = Owned To Guaranteed, Arg[3] = Owned To Guaranteed> of function signature specialization <Arg[1] = [Closure Propagated : closure #1 (Swift.Optional<Swift.Dictionary<Swift.String, Any>>, Swift.Optional<Swift.Error>) -> () in closure #2 () -> () in Detox.DetoxManager.webSocket(_: Detox.WebSocket, didReceiveAction: Swift.String, params: Swift.Dictionary<Swift.String, Any>, messageId: __C.NSNumber) -> (), Argument Types : [Detox.DetoxManager__C.NSNumber]> of static Detox.InvocationManager.invoke(dictionaryRepresentation: Swift.Dictionary<Swift.String, Any>, completionHandler: (Swift.Optional<Swift.Dictionary<Swift.String, Any>>, Swift.Optional<Swift.Error>) -> ()) -> () + 954
    	26  Detox                               0x000000011048b621 partial apply forwarder for closure #2 () -> () in Detox.DetoxManager.webSocket(_: Detox.WebSocket, didReceiveAction: Swift.String, params: Swift.Dictionary<Swift.String, Any>, messageId: __C.NSNumber) -> () + 65
    	27  Detox                               0x0000000110466dfe reabstraction thunk helper from @escaping @callee_guaranteed () -> () to @escaping @callee_unowned @convention(block) () -> () + 14
    	28  DetoxSync                           0x0000000133f6d0c4 __36+[DTXSyncManager _tryIdleBlocksNow:]_block_invoke.128 + 184
    	29  libdispatch.dylib                   0x00000001131368e4 _dispatch_call_block_and_release + 12
    	30  libdispatch.dylib                   0x0000000113137b25 _dispatch_client_callout + 8
    	31  libdispatch.dylib                   0x0000000113145043 _dispatch_main_queue_drain + 1050
    	32  libdispatch.dylib                   0x0000000113144c1b _dispatch_main_queue_callback_4CF + 31
    	33  CoreFoundation                      0x0000000114036ed5 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
    	34  CoreFoundation                      0x00000001140316ca __CFRunLoopRun + 2761
    	35  CoreFoundation                      0x0000000114030704 CFRunLoopRunSpecific + 562
    	36  GraphicsServices                    0x000000011816cc8e GSEventRunModal + 139
    	37  UIKitCore                           0x00000001281e365a -[UIApplication _run] + 928
    	38  DetoxSync                           0x0000000133f68a52 __detox_sync_UIApplication_run + 362
    	39  UIKitCore                           0x00000001281e82b5 UIApplicationMain + 101
    	40  BetfairMobile                       0x000000010490b388 main + 104
    	41  dyld                                0x000000010ff8af21 start_sim + 10
    	42  ???                                 0x0000000207a4d4d5 0x0 + 8718177493
    	43  ???                                 0x0000000000000003 0x0 + 3
    )
</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by asafkorem** [comment]
@sivvoy please upgrade Detox to the latest version (19.7), this issue has been fixed there. See [release notes](https://github.com/wix/Detox/releases/tag/19.7.0).

**Comment by asafkorem** [comment]
I'm closing this issue because this bug has already been fixed.
Please let me know if you experience any additional issues with the latest version of Detox.

**Comment by sivvoy** [comment]
Thank you, I've upgrade and its all working. Thank you
