### ISSUE TITLE
How do I config the  apps' Build path in detoxrc.json if I have no Xcode project because the JS project is just an RN Plugin for a third party's APP

### ISSUE THREAD

**Issue by Zhangronger** [wix/Detox#3428]
### Description

How do I config the build path in detoxrc.json file under apps part if I have no Xcode project on my PC, because the JS project is just a RN Plugin for a third party's APP. I only have the binaryPath(.app file). I do not have APP's xcodeproj file.
Could anyone help me on this, thanks a lot~~
<img width="999" alt="image" src="https://user-images.githubusercontent.com/12654166/170940483-1221264f-e83a-4814-a9ca-eeff69abc3cd.png">

### Your environment

Detox version: newest
React Native version: 
Node version: 
Device model: 
OS: iOS
Test-runner (select one): jest-circus / jest+jasmine / mocha / other

**Comment by noomorph** [comment]
Probably you need to set up a separate React Native project which uses your plugin with some sort of a demo app. Then you can build it and test with Detox.

**Comment by d4vidi** [comment]
Yes, it's either that (what noomorph said) or that you don't build the app at all. The `detox build` command is just a convenience. If you have a prebuilt binary, then setting it in a predefined path and having the `binaryPath` (in `detoxrc.json`) containing that path should suffice (i.e. to just run `detox test` and that's that).
