### ISSUE TITLE
Set Environment Variable

### ISSUE THREAD

**Issue by pdaniloais** [wix/detox#343]
I would like to know if it is possible to define an environment variable when I run my 2e2 tests and get it in my js code.

Thx

**Comment by anton-unity** [comment]
`process.env.ENV_VAR`? See also https://stackoverflow.com/questions/12236890/run-mocha-tests-in-test-environment

**Comment by LeoNatan** [comment]
That would be for the tester project, not the app process.

**Comment by pdaniloais** [comment]
Ok, i'm using dotenv now, what's the best practice to call a particular .env file when I running `detox test`
