### ISSUE TITLE
Does Detox provide the ability to assert entered values?

### ISSUE THREAD

**Issue by Anantha-sb** [wix/Detox#3430]
### Description

My react native app allows a user to perform certain actions, inputs values, selects date and time, selects certain items from the menu. 

In the final screen, all of this information is shown so the user has the ability to visually verify whether the entered information are correct. This information is stored locally and then sent to cloud. The data is in the form of json. 

I have written detox e2e tests to automate this workflow. However, I am not sure how I can assert each entered value and validate. Is there a way I can achieve this?

I am interested know - what are some ways I can do assertions? Is verifying element visibility, text, all that I can do with Detox or is there a way to assert each value.

### Your environment

Detox version: 19.7.0
React Native version: 0.64

**Comment by d4vidi** [comment]
You might find this useful: https://wix.github.io/Detox/docs/api/expect/#tohavetexttext
Let's discuss this under a different scope that might be more apt
