### ISSUE TITLE
I can't add console.log into my tests

### ISSUE THREAD

**Issue by JB-CHAUVIN** [wix/Detox#3434]
### What happened?

I can't add console.logs into my tests. How can I do it ? 
**Logs are not showing up in the console...**

I tried a lot of things do add console.log with Jest, but it's not working. Neither with Jasmine.

I am running my tests with the following command :
```
DEBUG=jest detox test --watch --configuration ios.sim.debug --debug-synchronization 5000 "${DETOX_COMMAND_MODE_REUSE_OR_CLEANUP}" "$COLORS" --silent=false --loglevel "trace" --record-logs="all" --take-screenshots="all" --artifacts-location="${TEST_ARTIFCATS_FOLDER}/" --runner-config "${RUNNER_CONFIG}" 2>&1 | tee "${TEST_RESULT_DETOX_LOG}"
```

Test example : 
```
describe('*[GENERAL]* Lancer l\'application', () => {
  it('Test', async () => {
    console.info('global.executionPlanKey');
    console.log('global.executionPlanKey');
  });
});

```

Here is my detox config : 
```{
  "setupFilesAfterEnv": [
    "./init.js"
  ],
  "testEnvironment": "./environment",
  "testRunner": "jest-circus/runner",
  "reporters": ["detox/runners/jest/streamlineReporter"],
  "bail": 1,
  "testRegex": "\\pro.e2e\\.js$",
  "verbose": true,
  "silent": false
}
```

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### In what environment did this happen?

Detox version: 19.4.2
React Native version: 0.68
Node version: 14
Test-runner (select one): jest-circus

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by jonathanmos** [comment]
@JB-CHAUVIN  console.log should work. If you simplify the test command do you see the log output? E.g. 

`detox test --configuration ios.sim.debug`
