### ISSUE TITLE
Xcode Version Usage Survey

### ISSUE THREAD

**Issue by LeoNatan** [wix/detox#344]
Hi guys,

We are surveying which versions of Xcode you are using. Please state the version here, and if it is not the latest, please provide a reason why you have remained with an older version of Xcode.

Thanks

**Comment by sibelius** [comment]
I think it makes sense do support the latest version of xcode and maybe the latest beta as well

I'm using xcode 9

**Comment by rotemmiz** [comment]
If an app is not ready to support iPhone X, it can't be released from Xcode 9, am I right ? So until RN community finds a way to solve this, then upgrade these apps to the latest version of RN, that supports iPhone X layout... we'll need to support Xcode 8.3.3
This is something to take into consideration.

**Comment by LeoNatan** [comment]
I want to hear concrete evidence. For instance, using Reac Native Navigation takes you 70% there.

**Comment by rotemmiz** [comment]
Blah blah, evidence. Who needs it these day ?

**Comment by LeoNatan** [comment]
We can also move to a new major version. Old Xcode versions can use the current Detox version while Xcode 9 will move on.

**Comment by LeoNatan** [comment]
@sibelius 

> I think it makes sense do support the latest version of xcode and maybe the latest beta as well

Oh yes, this is for sure. I am trying to gauge more about older versions of Xcode.

**Comment by alexcfaber** [comment]
Stuck on Xcode 8.3.3 for a while longer due to having a combined legacy app with some dependancies that are out of our control but aren't updated for xcode 9 yet. Hope to move soon though.

**Comment by Kureev** [comment]
Version 9.0 (9A235)

**Comment by chadlwilson** [comment]
9.0.1 (9A1004) for us

**Comment by anton-unity** [comment]
Xcode 8.3.3. We can't used latest, because another SW (from matrix) doesn't support it..

**Comment by LeoNatan** [comment]
Guys that have code not supporting Xcode 9 and above—do you have any outlook on when said code will be upgraded to Xcode 9 by vendors?

@alexcfaber @anton-unity

**Comment by Kureev** [comment]
I'm wondering if guys who use XCode 9+ (@chadlwilson) experience similar problem https://github.com/wix/detox/issues/352

**Comment by anton-unity** [comment]
@LeoNatan 
Sorry for delay, we were figuring out that question. So, we can live with only Xcode 9 support, if it's unavoidable. But it's also good to have Xcode 8 optional support, if possible.

**Comment by LeoNatan** [comment]
Thanks. We are not dropping support yet. Once we start adding support for advanced features only supported on XC9, such as parallel simulator support, I am not sure it will be possible to have XC8 support. Older versions will always be available while XC8 support is required.

**Comment by heuism** [comment]
Currently run on both Xcode 8.2 and Xcode 9+. Xcode 9+ to get better updates, but the app was written using RN 0.39.2 and it is working fine and large scope project as well, I just don't want to screw up the project by updating the RN to the latest or newer version. That is the drawback of RN that I know everyone has.

Btw, which Detox version should I try for RN .39.2? I am trying to figure out one that is the best support.

Please help

**Comment by hellogerard** [comment]
Currently on Xcode Version 9.1 (9B55).

Can't fight the future.

**Comment by anton6** [comment]
Xcode 8.3.3, due to dependancies that aren't updated for xcode 9 yet.
