### ISSUE TITLE
Crash - NoSuchMethodError: No static method isBlank

### ISSUE THREAD

**Issue by ngandhy** [wix/Detox#3440]
### What happened?

App crashes with error 

```
AndroidRuntime: java.lang.NoSuchMethodError: No static method isBlank(Ljava/lang/CharSequence;)Z in class Lj/a/a/a/b; or its super classes (declaration of 'j.a.a.a.b' appears in /data/app/~~Y3v30P120k32Qg==/com.MY.APP-p1c2xMu-ymxs_w==/base.apk!classes2.dex)
AndroidRuntime: 	at com.wix.invoke.MethodInvocation.invoke(MethodInvocation.java:30)
AndroidRuntime: 	at com.wix.invoke.MethodInvocation.invoke(MethodInvocation.java:26)
AndroidRuntime: 	at com.wix.invoke.MethodInvocation.invoke(MethodInvocation.java:20)
AndroidRuntime: 	at com.wix.detox.adapters.server.InvokeActionHandler.handle(DetoxActionHandlers.kt:54)
AndroidRuntime: 	at com.wix.detox.adapters.server.ActionsExecutor$executeAction$$inlined$let$lambda$1.run(DetoxActionsDispatcher.kt:64)
AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
AndroidRuntime: 	at com.wix.detox.adapters.server.ActionsExecutor$1.run(DetoxActionsDispatcher.kt:50)
AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
```

### What was the expected behaviour?

Test should start and app should not crash

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

I'm currently reproducing by:
1) detox build --configuration android.release
2) detox test --configuration android.release

### In what environment did this happen?

Detox version: 19.7.1
React Native version: 0.66.4
Node version: 
Device model: 
Android version: 
Test-runner (select one): jest-circus

### Detox logs

<details><summary>Detox logs</summary>

23:52:25.496 detox[88664] TRACE: [ARTIFACTS_LIFECYCLE] artifactsManager.onTestFnFailure({
  error: DetoxRuntimeError: The pending request #1 ("invoke") has been rejected due to the following error:
  
  The app has crashed, see the details below:
  
  @Thread detox.primary(524):
  java.lang.NoSuchMethodError: No static method isBlank(Ljava/lang/CharSequence;)Z in class Lk/a/a/a/b; or its super classes (declaration of 'k.a.a.a.b' appears in /data/app/com.streetfoodfinder.vendorapp-pQ9M0e2WPZoTgWmCswUXeA==/base.apk!classes2.dex)
      at _callee3$ (/Users/Dev/UPGRADERN/STV/__tests__/e2e/tc01_login.e2e.js:22:45)
      at tryCatch (/Users/Dev/UPGRADERN/STV/node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (/Users/Dev/UPGRADERN/STV/node_modules/regenerator-runtime/runtime.js:294:22)
      at Generator.next (/Users/Dev/UPGRADERN/STV/node_modules/regenerator-runtime/runtime.js:119:21)
      at tryCatch (/Users/Dev/UPGRADERN/STV/node_modules/regenerator-runtime/runtime.js:63:40)
      at invoke (/Users/Dev/UPGRADERN/STV/node_modules/regenerator-runtime/runtime.js:155:20)
      at /Users/Dev/UPGRADERN/STV/node_modules/regenerator-runtime/runtime.js:190:11
      at new Promise (<anonymous>)
})
23:52:25.498 detox[88664] TRACE: [DETOX_AFTER_EACH] failed test: "Login Tests Should show login screen"

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by jonathanmos** [comment]
@ngandhy have you added the necessary [proguard configuration](https://wix.github.io/Detox/docs/introduction/android/#7-proguard-minification-obfuscation) to your project as part of the setup?

**Comment by ngandhy** [comment]
@jonathanmos - yup! for context, the tests were working fine not too long ago.

I've been slowly pulling one thing at a time, and I think Detox errors when proguard is turned on with https://github.com/henninghall/react-native-date-picker .  I've included that libraries proguard rules, so not sure what's going on. Any tips on how to debug?

**Comment by ngandhy** [comment]
For anyone that needs it - my PR fixes the proguard related crash by including org.apache.commons.lang3.StringUtils in proguard-rules-app.pro 

isBlank is used here in detox: https://github.com/wix/Detox/blob/master/detox/android/detox/src/full/java/com/wix/invoke/MethodInvocation.java

**Comment by jonathanmos** [comment]
@ngandhy do you know why this happened in your project? I want to try to reproduce

**Comment by aclopesjr** [comment]
@d4vidi, I was wondering if you can reopen that issue to append the `-keep class org.apache.commons.lang3.** { *; } ` in `detox/android/detox/proguard-rules-app.pro file`, please.

It seems it is missing on the latest version.

https://github.com/wix/Detox/blob/master/detox/android/detox/proguard-rules-app.pro

**Comment by aclopesjr** [comment]
@d4vidi here is the error.

`The pending request #2 ("invoke") has been rejected due to the following error:

    The app has crashed, see the details below:

    @Thread detox.primary(30674):
    java.lang.NoSuchMethodError: No static method isBlank(Ljava/lang/CharSequence;)Z in class Lorg/apache/commons/lang3/StringUtils; or its super classes (declaration of 'org.apache.commons.lang3.StringUtils' appears in /data/app/~~HFW8QZ3ACRw8_8C2L_CJyQ==/com.firstpremier.mypremiercreditcard.app-ruUDe70d20rXdV0Gm9qRYQ==/base.apk!classes2.dex)
    	at com.wix.invoke.MethodInvocation.invoke(MethodInvocation.java:30)
    	at com.wix.invoke.MethodInvocation.invoke(MethodInvocation.java:26)
    	at com.wix.invoke.MethodInvocation.invoke(MethodInvocation.java:20)
    	at com.wix.detox.adapters.server.InvokeActionHandler.handle(DetoxActionHandlers.kt:54)
    	at com.wix.detox.adapters.server.ActionsExecutor.executeAction$lambda-2$lambda-1(DetoxActionsDispatcher.kt:64)
    	at com.wix.detox.adapters.server.ActionsExecutor.$r8$lambda$nk3cF8ntnfFqbJOcVqd04vjb5nY(Unknown Source:0)
    	at com.wix.detox.adapters.server.ActionsExecutor$$ExternalSyntheticLambda1.run(Unknown Source:8)
    	at android.os.Handler.handleCallback(Handler.java:938)
    	at android.os.Handler.dispatchMessage(Handler.java:99)
    	at android.os.Looper.loop(Looper.java:223)
    	at com.wix.detox.adapters.server.ActionsExecutor._init_$lambda-0(DetoxActionsDispatcher.kt:50)
    	at com.wix.detox.adapters.server.ActionsExecutor.$r8$lambda$Hi5vyewqQiQqk57AkJy_cHqNGKY(Unknown Source:0)
    	at com.wix.detox.adapters.server.ActionsExecutor$$ExternalSyntheticLambda0.run(Unknown Source:4)
    	at java.lang.Thread.run(Thread.java:923)

    Check device logs for full details!`

I saw it was merged on the master, but when I checked the file, the line `-keep class org.apache.commons.lang3.** { *; }  in detox/android/detox/proguard-rules-app.pro file` is not there. I might be missed something here (🤔)

![Screen Shot 2023-03-22 at 18 29 46](https://user-images.githubusercontent.com/6538505/227042899-a140ca19-7452-49ca-aab2-bd52888c1341.png)

**Comment by d4vidi** [comment]
@aclopesjr it wasn't meant to be added to `proguard-rules-app.pro`, but rather to `proguard-rules.pro` (I know it's confusing): The former is associated with your app code, and the latter - with the test code, which is the soft spot here. Could you double check that you build Detox strictly in `debug` mode and without minification?

**Comment by aclopesjr** [comment]
@d4vidi oh I got that. I added that missing line on `proguard-rules.pro` (the one located on my local android project) and that worked fine.

**Comment by d4vidi** [comment]
> @d4vidi oh I got that. I added that missing line on `proguard-rules.pro` (the one located on my local android project) and that worked fine.

That's actually bad news for me. Are you 100% certain that you have `proguard-rules-app.pro` set in-place in your `build.gradle`?

**Comment by aclopesjr** [comment]
@d4vidi the `android/app/build.gradle` is like this:
![Screen Shot 2023-03-28 at 12 28 24](https://user-images.githubusercontent.com/6538505/228289058-112f4fd6-7617-48aa-9839-e4dfef0bb6b0.png)

However, I added the missing `org.apache.commons.lang3` in my own `android/app/proguard-rules.pro file`.
![Screen Shot 2023-03-28 at 12 30 07](https://user-images.githubusercontent.com/6538505/228289388-a62eeae5-dcdd-464f-829f-e70c4fae7fbf.png)

**Comment by d4vidi** [comment]
Oh. Well, double check that you've applied [this guide](https://wix.github.io/Detox/docs/guide/proguard-configuration/).
