### ISSUE TITLE
Validation Error: Module jest-circus/runner in the testRunner option was not found.

### ISSUE THREAD

**Issue by Twinbird24** [wix/Detox#3451]
### Description

I recently updated my version of Detox from 19.4.2 to 19.7.1, and now I'm seeing this error when I attempt to run my Detox tests: 
```
Module jest-circus/runner in the testRunner option was not found.
     <rootDir> is: /Users/myuser/Documents/my-app/e2e
```

config.json
```
{
    "maxWorkers": 1,
    "testEnvironment": "./environment",
    "testRunner": "jest-circus/runner",
    "testTimeout": 120000,
    "testRegex": "\\.e2e\\.js$",
    "setupFilesAfterEnv": ["./jest.setup.js"],
    "reporters": ["detox/runners/jest/streamlineReporter"],
    "verbose": true
}
```

environment.js
```
const {
  DetoxCircusEnvironment,
  SpecReporter,
  WorkerAssignReporter,
} = require('detox/runners/jest-circus')

class CustomDetoxEnvironment extends DetoxCircusEnvironment {
  constructor(config, context) {
    super(config, context)

    // Can be safely removed, if you are content with the default value (=300000ms)
    this.initTimeout = 300000

    // This takes care of generating status logs on a per-spec basis. By default, Jest only reports at file-level.
    // This is strictly optional.
    this.registerListeners({
      SpecReporter,
      WorkerAssignReporter,
    })
  }
}

module.exports = CustomDetoxEnvironment
```

### Your environment

Detox version: 19.7.1
React Native version: 0.66.3
Node version: 6.12.0
Device model: MacBook Pro, running tests on an android emulator (Pixel API 29 AOSP)
OS: macOS Big Sur (11.6.5)
Test-runner: jest-circus

**Comment by Twinbird24** [comment]
Does that message suggest I'm running from inside the `e2e` folder? I'm running from the root of my project (i.e. the `my-app` directory). My test script is: `detox test ./e2e  --configuration android --take-screenshots all`

**Comment by noomorph** [comment]
Could you share your `npm ls jest` output?

**Comment by Twinbird24** [comment]
npm ls jest:
```
myapp@0.0.1 /Users/myuser/Documents/myapp
├─┬ detox@19.7.1
│ └── jest@26.6.3 deduped
└── jest@26.6.3
```

**Comment by noomorph** [comment]
You need to install `jest-circus` then:

```bash
npm install --save-dev jest-circus@26
```

**Comment by Twinbird24** [comment]
Ah, thanks so much! I had tried installing the wrong version of jest-circus previously with no luck, oops 🙈
My only other question is why my current set-up worked on `19.4.2` without having `jest-circus` installed at all? 🤔

**Comment by noomorph** [comment]
I can't say for sure, but actually `jest-circus@26` is an optional dependency – you need it only if you run with the old Jest. The modern versions of Jest (27 and 28) have the circus out of the box. Make sure to upgrade your Jest whenever you can.
