### ISSUE TITLE
detox init - No such file or directory (linux)

### ISSUE THREAD

**Issue by alissa-ferro** [wix/detox#346]
I don't know if you guys already tested detox with Linux. I'm trying to configure, but I got stuck. 
When I try to run detox init, I get "init: NO such file or directory". Am I missing anything? 

* Detox: 5.8.4
* Node: 8.1.0
* Linux Ubuntu 
* Mocha: 4.0.1

**Comment by rotemmiz** [comment]
Please provide full logs!! (Can't emphasize this enough)
use `--loglevel verbose` command line argument.

Also, I noticed Mocha 4.x.x has weird issues with Detox, not sure what's changed there.
I recommend using Mocha 3.5.x until we figure the issue out.

**Comment by alissa-ferro** [comment]
I know, but in my case I get this message when I try to use verbose: 
detox: unrecognized option '--loglevel'
usage: detox [-hLnrvV] [-f configfile] [-s sequence] [--dry-run] [--special]
	  file [file ...]

Maybe there was something wrong with my configuration, can't figure out yet ...

**Comment by rotemmiz** [comment]
It seems like that's a different detox, unrelated to this library...

Make sure you remove it (depends on how you installed it of course), and install detox-cli

**Comment by rotemmiz** [comment]
Ho my, is it this https://linux.die.net/man/1/detox ?
I'm not sure, but I think it's a command line tool supplied with a few linux distributions. If you're not using it, overriding it with user bin path  will probably solve the issue.

**Comment by alissa-ferro** [comment]
Well, I don't really know why, but I closed the terminal and sudently worked... Sorry about that, and thanks for always helping me!
