### ISSUE TITLE
[XCUITest] improve the connection between XCUIElements and UIViews.

### ISSUE THREAD

**Issue by asafkorem** [wix/Detox#3463]
Match between `XCUIElement` and `UIView` (to both directions) by:
* `accessibilityIdentifier`
* `frame`

In order to create a one-to-one matching:

- [x] Inject a unique `accessibilityIdentifier` to elements without `accessibilityIdentifier` (UUID).
- [x] If two elements has the same `accessibilityIdentifier` and the same `frame`, chain one of the identifiers with a random UUID (for example: `"<original identifier>_Detox:<UUID>"`).

**Comment by asafkorem** [comment]
Done 🙂 ✅

**Comment by d4vidi** [comment]
![fxt5](https://user-images.githubusercontent.com/9818880/204129443-a06553b6-fe66-440f-ac65-0683417bb7f8.gif)
