### ISSUE TITLE
type/replaceText functions doesnt work with InputAccessoryView component

### ISSUE THREAD

**Issue by Vadko** [wix/Detox#3483]
### What happened?

text helpers functionality for TextInput wrapped into InputAccessoryView doesnt work

video: https://user-images.githubusercontent.com/9297785/178329467-376236e5-b9cf-43e7-9be1-f64d0420a45a.mov

### What was the expected behaviour?

TextInput wrapped into InputAccessoryView available for testing

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

reproducible demo forked from DetoxTemplate repo:

https://github.com/Vadko/DetoxTemplate

### In what environment did this happen?

Detox version: 
React Native version: 
Node version: 
Device model: 
iOS version: 
macOS version: 
Xcode version: 
Test-runner (select one): jest-circus / jest+jasmine / mocha / other

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by d4vidi** [comment]
@Vadko thanks for the detailed submission. We will look into it.

**Comment by d4vidi** [comment]
@Vadko could you try to better explain the use case here? Seems like you are bundling a text input inside what is meant to be a keyboard accessory view... Does that make sense at all, product-wise? How is iOS meant to even handle that?

**Comment by d4vidi** [comment]
Also, could you try to enable the soft-keyboard on your simulator?

**Comment by Vadko** [comment]
@d4vidi I've tried soft-keyboard, doesnt helped.

Regarding your question about purpose of this component - it is actually very important for complex screens like messenger apps, because it brings native iOS UX to attach automatically this component at the top of keyboard, native drag to close and more.

you can investigate it here:
https://reactnative.dev/docs/inputaccessoryview
