### ISSUE TITLE
[docs] sdkmanager path is outdated

### ISSUE THREAD

**Issue by adrienharnay** [wix/Detox#3484]
### Describe your idea

Hello,

While following the docs to setup an AOSP emulator, I noticed the sdkmanager path was outdated.

Previous: $ANDROID_HOME/tools/bin/sdkmanager
New: $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager

Have a nice day!

**Comment by asafkorem** [comment]
Hey @adrienharnay, thanks for the report! 
This path is version dependent and indeed changed in the latest versions.
We're planning to improve the Android docs and to fix some sections, so we'll make sure this will be fixed as well.

CC @jonathanmos
