### ISSUE TITLE
Detox scroll method on Android does not scroll a deterministic distance on every run.

### ISSUE THREAD

**Issue by dmaulick** [wix/Detox#3485]
### Background and the Problem

I am using Detox to step through my app, take screenshots and then upload them to a visual diffing mechanism ([percy](https://percy.io/)) to run a visual diff check.

A requirement of this is that I need to scroll an exact amount down a scrollView and for every scroll increment take a screenshot. As a result of this it is critical that the [`scroll`](https://github.com/wix/Detox/blob/master/docs/APIRef.ActionsOnElement.md#scrolloffset-direction-startpositionx-startpositiony) method from detox is 100% deterministic.

The problem is that it appears the  [`scroll`](https://github.com/wix/Detox/blob/master/docs/APIRef.ActionsOnElement.md#scrolloffset-direction-startpositionx-startpositiony) method for Android it is NOT 100% deterministic (on iOS it is 100% deterministic so far 🙏 ). For Android, pretty much every run is yielding a slightly different scroll distance resulting in visual diffs that resemble the following:

| Diff highlight shows subtle shift | If look closely you can see the shift without the highlight (most easily seen at very bottom) |
|-----|-----|
|<img width="956" alt="image" src="https://user-images.githubusercontent.com/10509630/178826859-f6b719c3-186f-4b47-b6db-cd5cfbeb0e1b.png"> | <img width="958" alt="image" src="https://user-images.githubusercontent.com/10509630/178827020-b1afac19-1d89-4d34-aaf3-a8774c4ff360.png"> |

The above scroll difference is a result of a single call to the below method using the default scroll pixel count of 600px. 

```
async function scrollToEnd(scrollViewId: string, pixels = 600) {
  try {
    await element(by.id(scrollViewId)).scroll(pixels, 'down');
  } catch {
    // this tells us we have reached the end of the scroll view.
    return true;
  }
  return false;
}
```

### What I have tried/ am going to try

One thing that I thought may have been the problem was my emulator configuration so I spent a decent amount of time re-reading the getting started docs and I confirmed my Android emulator configuration - I am also using AOSP emulators: https://wix.github.io/Detox/docs/introduction/android-dev-env/#android-aosp-emulators

I have taken a brief look into the detox code, two things I think may be worth investigating:
1. Maybe the [displayMetric density](https://github.com/wix/Detox/blob/45e21039b4245d85b31b5c350ee384dc1e551147/detox/android/detox/src/main/java/com/wix/detox/espresso/DeviceDisplay.kt#L7) is non-deterministic. Not exactly sure how to check this but working on it.
2. Maybe [scrollHelper](https://github.com/wix/Detox/blob/45e21039b4245d85b31b5c350ee384dc1e551147/detox/android/detox/src/main/java/com/wix/detox/espresso/scroll/ScrollHelper.java#L48) has an issue. 

### Closing thoughts

Without the scroll behavior being non-determistic on Android detox is really a no-go to be used as our test runner for visual regression tests. Would love to see if we can resolve this! 

### What was the expected behaviour?

The following method should always scroll exactly 600 no matter what on android so that we can compare screenshots exactly.

```
async function scrollToEnd(scrollViewId: string, pixels = 600) {
  try {
    await element(by.id(scrollViewId)).scroll(pixels, 'down');
  } catch {
    // this tells us we have reached the end of the scroll view.
    return true;
  }
  return false;
}
```

### Was it tested on latest Detox?
YES
- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?
NO
- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

There are no detox failures, it is simply a bug in the scroll distance on Android. 
To most effectively test I would recommend setting numbered lines on a screen so you can see exactly how far a scroll goes. Then use a variation of the following method to scroll and verify that the distance it scrolls is non-deterministic on each run.

```
async function scrollToEnd(scrollViewId: string, pixels = 600) {
  try {
    await element(by.id(scrollViewId)).scroll(pixels, 'down');
  } catch {
    // this tells us we have reached the end of the scroll view.
    return true;
  }
  return false;
}
```

### In what environment did this happen?

Detox version: 19.7.1
React Native version: 0.66.3
Node version: 

Device model: 
Android version: 
This is how we create our emulator (locally and on CI):
"$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --verbose 'system-images;android-30;default;x86_64'",
"echo no | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager --verbose create avd --force --name Pixel_3a_API_30 --package 'system-images;android-30;default;x86_64'"

Test-runner (select one): jest-circus / jest+jasmine / mocha / other:
using jest

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

### More data, please!

Any guidance on how to collect relevant data about the emulator configuration etc will be helpful here.

It seems this is either a bug with the way detox is scrolling or the emulator is not configured 100% correctly.

**Comment by hollislau** [comment]
I'm seeing this same issue and can reproduce this behavior

**Comment by dmaulick** [comment]
Interesting: https://github.com/wix/Detox/pull/1662
Seems like known issue of the team that scrolling on Android is not deterministic. Curious if there are recommended work arounds

**Comment by dmaulick** [comment]
@d4vidi Do you have any recommendations to get around this since you seem to have a lot of context here.

**Comment by dmaulick** [comment]
Summary of why it does not work:
Call site to scroll on Android: https://github.com/wix/Detox/blob/9229e64ec8f95574aab5beeeb4fa6bcc84844f69/detox/android/detox/src/main/java/com/wix/detox/espresso/scroll/ScrollHelper.java#L94

When `DetoxSwiper` calls perform, it calls `startAt`, `moveTo`, and `finishAt` of the `DetoxSwiper` interface; these methods accumulate an array of `MotionEvents` (the espresso action class); in `finishAt` we delegate to `UiController` to execute the series of actions:
https://github.com/wix/Detox/blob/9229e64ec8f95574aab5beeeb4fa6bcc84844f69/detox/android/detox/src/main/java/com/wix/detox/espresso/scroll/FlinglessSwiper.kt#L56


The core of the problem is that we do not specify an exact pixel/dpi amount to espresso. Espresso does not seem to have a mechanism that accepts pixel/dpi as input. As a result Detox manual converts a pixel/dpi value to a set of Motion events. The variance in scroll distance could be a result of the Detox calculation, or because espresso itself is non-deterministic. 

I have not investigated espresso directly, but given sentiment from Detox team (https://github.com/wix/Detox/pull/1662) it seems very possible that this is an espresso issue and not a Detox issue.

With this in mind I have a few lines of thought:
1. Is there a different mechanism outside of espresso that we can use? I would honestly be shocked if there is no mechanism that allows us to scroll an exact number of pixels.
2. If espresso is the problem, is there a way we can call it more directly to provide a deterministic result?

**Comment by dmaulick** [comment]
For context, this is how espresso scrolls:

this is where espresso scrolls: [https://github.com/android/android-test/blob/3cfaff2b2f0f8d7b52c7a9eb7b9798fc5b16a[…]sso/core/java/androidx/test/espresso/action/ScrollToAction.java](https://github.com/android/android-test/blob/3cfaff2b2f0f8d7b52c7a9eb7b9798fc5b16a5e5/espresso/core/java/androidx/test/espresso/action/ScrollToAction.java#L63)
[2:24](https://coinbase.slack.com/archives/D014QHUM5A8/p1658957064881529)

so it uses requestRectangleOnScreen to scroll
https://developer.android.com/reference/android/view/View#requestRectangleOnScreen(android.graphics.Rect,%20boolean)

**Comment by dmaulick** [comment]
@d4vidi

We found a workaround. 
[Actions.swipe](https://wix.github.io/Detox/docs/api/actions-on-element#swipedirection-speed-normalizedoffset-normalizedstartingpointx-normalizedstartingpointy) is deterministic on Android
