### ISSUE TITLE
How to tap the iOS simulator built-in numpad?

### ISSUE THREAD

**Issue by ansonliao** [wix/Detox#3489]
### Description

Hi,
My react-native mobile app includes some iOS native built-in numpad keyboard in the login process, I would like to know how can I tap the numpad of the keyboard?
I try to locate the numpad by `by.text()` or `by.label()`, for example, locate numpad key `1` by 
```javascript
await element(by.text('1')).tap();
```
or 
```javascript
await element(by.label('1')).tap();
```

but both `by.text()` and `by.label()` out of work to locate the numpad key `1` to tap.

Could you kindly help to advise how can I handle this?

Thanks.

<img width="426" alt="image" src="https://user-images.githubusercontent.com/6060224/179209543-191c2c9f-f77f-4ee5-abb8-273f89beabd7.png">

### Your environment

Detox version: 19.7.1
React Native version: 0.63.2
Node version: 14.16.0
Device model: iOS simulator 13 Pro Max with iOS 15.5
OS: macOS
Test-runner: mocha

**Comment by asafkorem** [comment]
@ansonliao can you please try:
```js
await element(by.id('<first input element id>')).typeText('123456');
```

you should replace `123456` with whatever password you want to type in, also replace `<first input element id>` with the first input view's id.
![image](https://user-images.githubusercontent.com/55082339/179391454-84d386d0-11c6-403e-a581-14f99bc86bc0.png)

See: https://wix.github.io/Detox/docs/next/api/actions-on-element#typetexttext

**Comment by ansonliao** [comment]
Hi @asafkorem , 
the input field is disabled to interactive (by our UX design), that why need to tap the Numpad keyboard.

**Comment by ansonliao** [comment]
Thanks @asafkorem .
We are blocked by this pin number input of the login process, as all features are behind the login.

**Comment by asafkorem** [comment]
@ansonliao for now, you can mock this phase on your flow, see:
https://wix.github.io/Detox/docs/guide/mocking
For examples: you can disable it or enable input selection just for the tests.

**Comment by asafkorem** [comment]
@ansonliao can you show me the error message that appears when you run:
```
await element(by.id('<first input element id>')).typeText('1');
```
You don't need to tap the element before

**Comment by asafkorem** [comment]
Also, if you can reproduce this issue in an isolated app, it will be very useful and will very help us work on the solution.
You can use our template for that: https://github.com/wix-incubator/DetoxTemplate

**Comment by ansonliao** [comment]
> @ansonliao can you show me the error message that appears when you run:
> 
> ```
> await element(by.id('<first input element id>')).typeText('1');
> ```
> 
> You don't need to tap the element before

Hi @asafkorem , 
Communicated with my developers, these 6 input text boxes actually are `the shadow boxes` of the real text input fields, the developers hidden the 6 real input text fields and they are testID are `hiddenTextInput`, when end user tap the numpad keyboard of iOS, actually the tapping will be fill to the hidden in text input fields, then reflecting to the disabled 6 text input fields as we see.

I tried fill the text to the `hidden text input fields`, but failed with error shows the element is not visible to interactive.

https://user-images.githubusercontent.com/55082339/179391454-84d386d0-11c6-403e-a581-14f99bc86bc0.png

**Comment by ansonliao** [comment]
Hi @asafkorem , I followed [the instruction of the Mock of Detox](https://wix.github.io/Detox/docs/guide/mocking/), to mock my SMS code input page, the mock strategy is enabled the custom keyboard instead of the native keyboard of the iOS simulator.

so the original react-native typescript code file of SMS code input page is for example: `src/scenes/login/inputPinNum.tsx`,
my mock file is `src/scenes/login/inputPinNum.mock.tsx`,

then updated `metro.config.js` as below:

```javascript
const {getDefaultConfig} = require('metro-config');

module.exports = (async () => {
  const {
    resolver: {sourceExts, assetExts},
  } = await getDefaultConfig();
  return {
    transformer: {
      getTransformOptions: async () => ({
        transform: {
          experimentalImportSupport: false,
          inlineRequires: false,
        },
      }),
      babelTransformerPath: require.resolve('react-native-svg-transformer'),
    },
    resolver: {
      assetExts: assetExts.filter((ext) => ext !== 'svg'),
      sourceExts:
        process.env.MY_APP_MODE === 'mocked'
          ? [...sourceExts, 'svg', 'mock.tsx']
          : [...sourceExts, 'svg'],
    },
  };
})();
```

then build the app to the iOS simulator by the command-lines:
```shell
$ export MY_APP_MODE=mocked
$ npx react-native run-ios
```

then execute the metro bundler by command-line:
```shell
MY_APP_MODE=mocked npx react-native start
```

After the app is running in the iOS simulator, I find that the mock file `src/scenes/login/inputPinNum.mock.tsx` doesn't build to the app.

So for my modification, anything is missed?

Thanks.
