### ISSUE TITLE
Expectation/matcher for counting elements

### ISSUE THREAD

**Issue by igorrKurr** [wix/detox#350]
Hello,

I'm looking for expectation/matcher to compare/get length of elements, but seems like there is no such functionality here now.
To be clearer, I need to test an amount of elements under some matcher.
It might look something like this: 
```js
await expect(element(by.id('row')).toHaveSizeOf(<number>)
```
of even would be better like that:
```js
const countOfRows = await element(by.id('row')).getCount()
expect(countOfRows).toEqual(<number>)
```
I've briefly looked through EarlGrey github and seems like there is something existing for that: https://github.com/google/EarlGrey/pull/430

But I'm not sure how to implement it here.

Also, if somebody knows some recipes how to do that, please let me know how.
Thanks.

**Comment by LeoNatan** [comment]
I don’t like such kind of API. It’s too … flaky. How would you guess the “<number>”? You are relying on both RN internal and iOS native layout systems to produce some arbitrary layout bounds. On top of that, you have many device types and configurations, where each would produce different bounds. Under iOS development, it is already considered bad practice to make assumptions on view bounds/frames, and I happen to agree with the reasons. Won’t do for now.
