### ISSUE TITLE
[RN 69] Android: remove dead code of React Native < 65 support

### ISSUE THREAD

**Issue by asafkorem** [wix/Detox#3509]
### Describe your idea

We have some dead Android-native code for RN < 64 support. Let's get that cleaned up 🙂

**Comment by noomorph** [comment]
Create a PR to `next` branch, if possible, since this is technically a breaking change.

**Comment by d4vidi** [comment]
@noomorph so glad to see you here again 😊

I actually decided to bundle this into the 69 compact issue. Thought it would make more sense. Anyways it's not in fact breaking because we publicly limit our support to the >=64 range.

**Comment by noomorph** [comment]
Ah, no worries then.
