### ISSUE TITLE
Failing the Detox tests due to AppWillTerminateWithError

### ISSUE THREAD

**Issue by gdpr1504** [wix/Detox#3515]
### What happened?

When I was running detox tests, I was facing with timeout error. The app was build properly but the testing is not working fine as the apps seems to be idle. It was working fine before but from few days it was giving the issue.
Logs:
![image](https://user-images.githubusercontent.com/64791710/181480948-d53b8daa-2614-425f-8ef4-77799ffa2744.png)

![image](https://user-images.githubusercontent.com/64791710/181481129-f889f938-12cb-4639-8a04-e80cf600d448.png)

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 
React Native version: 
Node version: 
Device model: 
Android version: 
Test-runner (select one): jest-circus / jest+jasmine / mocha / other

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by Stroi** [comment]
Any updates ? Also having this issue..

**Comment by mraible** [comment]
Me too.

**Comment by jmarek-sky** [comment]
Same here

**Comment by FadiAboMsalam** [comment]
@gdpr1504  have u managed to fix this ?
