### ISSUE TITLE
Unable to Detect device.launch() and Run Before callbacks on current version

### ISSUE THREAD

**Issue by ianjkaplan** [wix/Detox#3516]
### What happened?

Im unable to run any detox test scenario on my machine while some of my collegues have no problem. Ive done clean installs with the same node version (16.14.0) and npm version (8.3.1) and cleared the xcode build directory.  

Specifically the initial login screen loads, no action is performed and then i get an error beginning with
```
Detox can't seem to connect to the test app(s)!
```

### What was the expected behaviour?

When I run a test scenario and I call `device.lanchApp()` i should be able to setup scenarios where the app launches and then the test logs in and navigates to the screens under test/

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

im not sure how to reproduce as my collegues do not have this issue.

### In what environment did this happen?

Detox version: 
React Native version: 
Node version: 16.14.0
Device model:  iphone 13 (simulator)
iOS version: 15.5
macOS version: 12.4
Xcode version: 13.4.1
Test-runner (select one): jest-circus

### Detox logs

<details><summary>Detox logs</summary>

```
HINT:

Have you forgotten to call 'device.launchApp()' in the beginning of your test?
Refer to our troubleshooting guide, for full details: https://wix.github.io/Detox/docs/troubleshooting/running-tests#tests-execution-hangs

---
The following package could not be delivered:

{
  type: 'invoke',
  params: [Object],
  messageId: 3
}
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by asafkorem** [comment]
Hey @ianjkaplan, thanks for the report. 
This error is very generic and might indicate on many problems.
Please provide the device logs 🙂
