### ISSUE TITLE
Unable to do device.launchApp() using macos-11

### ISSUE THREAD

**Issue by sharan-SKY** [wix/Detox#3521]
### What happened?

Upgraded my vm image to macos-11 and tried running detox tests with latest version but I am not able to run ios app. Get an error saying 

```
    DetoxRuntimeError: The pending request #-1000 ("isReady") has been rejected due to the following error:

    The app has unexpectedly disconnected from Detox server.

       8 | describe('Attribution test', () => {
       9 |   beforeAll(async () => {
    > 10 |     await device.launchApp();

```

### What was the expected behaviour?

App is meant to launch and run tests without error.

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

Run any ios detox tests using macos vm image macos-11

### In what environment did this happen?

Detox version: 19.8.4
React Native version: 0.64.3
Node version: 
Device model: iPhone 12
iOS version: 
macOS version: macOS-11
Xcode version: 
Test-runner (select one): jest-circus / jest+jasmine / mocha / other

### Detox logs

<details><summary>Detox logs</summary>

```
running command: jest --config ../../__tests__/e2e/config.json --maxWorkers 1 --detectOpenHandles --group=mobile/any/smoke --group=mobile/default/smoke
09:41:46.941 detox[10875] WARN:  [composeDeviceConfig.js] --force-adb-install CLI override is not supported by device type = "ios.simulator" and will be ignored
09:41:46.946 detox[10875] WARN:  [composeDeviceConfig.js] --readonly-emu CLI overriding is not supported by device type = "ios.simulator" and will be ignored
09:44:41.445 detox[10875] WARN:  at ../../node_modules/browserslist/node.js:381:15 
 Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
09:44:43.739 detox[10875] INFO:  at ../../__tests__/detox-common/util/WSServer.ts:23:13 
 WebSocketServer started
09:44:44.812 detox[10875] INFO:  Attribution test is assigned to F2650D69-14E5-4193-B04B-A0144F417732 (iPhone 12)
09:44:53.001 detox[10875] INFO:  [AppleSimUtils.js] nz.co.sky.one.dev launched. To watch simulator logs, run:
        /usr/bin/xcrun simctl spawn F2650D69-14E5-4193-B04B-A0144F417732 log stream --level debug --style compact --predicate 'process == "Sky One"'
09:44:55.870 detox[10875] WARN:  [DetoxConnection.js/ERROR, #50438] Action dispatched too early, there is no session to use:

HINT: Please report this issue on our GitHub tracker:
https://github.com/wix/Detox/issues

{
  messageId: -10000,
  params: [Object],
  type: 'AppWillTerminateWithError'
}
09:45:04.050 detox[10875] INFO:  Attribution test: Open My Hub and tap on Licenses
09:45:04.082 detox[10875] INFO:  Attribution test: Open My Hub and tap on Licenses [FAIL]

```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by anabeatrizzz** [comment]
I'm having the same issue trying to run detox tests in Android emulator on debug mode.

**Comment by asimyaramis** [comment]
same issue on ios release mode

**Comment by mklb** [comment]
I had this error for over a year now. Finally solved it by upgrading `react-native-reanimated` to the latest version.

**Comment by jforaker** [comment]
Get this problem on IOS release mode, even when changing my app to this: 

```
  return (
    <View style={{ flex: 1, justifyContent: 'center', alignContent: 'center' }}>
      <Text>hello</Text>
    </View>
  );
```
