### ISSUE TITLE
RCT-Folly-Build

### ISSUE THREAD

**Issue by glenndonAi** [wix/Detox#3522]
### What happened?

Error:
The following build commands failed:
        CompileC /Path/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RCT-Folly.build/Objects-normal/i386/F14Table.o /Path/ios/Pods/RCT-Folly/folly/container/detail/F14Table.cpp normal i386 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'RCT-Folly' from project 'Pods')
(1 failure)

Pre-Condition:
1. Follow the setup detox latest version  
2. detox build --configuration iOS file.ts

Environment (please complete the following information):
Detox: ^19.6.5
React Native: 0.67.4
Node:v16.16.0
Device: Iphone 13 simulator
Xcode: 13.4.1 (13F100)
iOS: 15.0
macOS: Monterey
jest: 28.1.2

**Comment by d4vidi** [comment]
@glenndonAi if you happen to sort this out and feel something can be improved in the docs, please let us know.

**Comment by glenndonAi** [comment]
@d4vidi please can you help me?

**Comment by tokkozhin** [comment]
I have the same error but with the RN v0.69.1 and the next environment:
```System:
    OS: macOS 12.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 36.56 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /Users/macbookpro/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: 6.2.0 => 6.2.0 
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.1 => 0.69.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found```

**Comment by glenndonAi** [comment]
@d4vidi Please can you help us cc: @tokkozhin
