### ISSUE TITLE
Test is not terminated until timeout

### ISSUE THREAD

**Issue by bilalbugrauysal** [wix/Detox#3525]
### What happened?

The test is not completed when it reached to end of the code execution. Test gets stuck until jest timeout is exceeded. After that, it logs the following
```
ERROR: Exceeded timeout of 40000ms while handling jest-circus "test_done" event
INFO:  Example: should have welcome screen [OK]
ERROR: Exceeded timeout of 40000ms while handling jest-circus "test_done" event
```

### What was the expected behaviour?

The test should be completed when it reaches the end of the test code

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

The issue can be reproducible in the following repo.

https://github.com/bilalbugrauysal/RNAppForTesting

### In what environment did this happen?

Detox version: 19.8.4
React Native version: 0.69.3
Node version: v16.15.1
Device model: Emulator - Pixel 5.0 1080x1920 420dpi
Android version: Android 9.0 x86
Test-runner: jest-circus@26.6.3

### Detox logs

https://github.com/bilalbugrauysal/RNAppForTesting/blob/master/e2e/artifacts/android.2022-08-02%2013-05-55Z/detox_pid_34244.log

### Device logs

https://github.com/bilalbugrauysal/RNAppForTesting/blob/master/e2e/artifacts/android.2022-08-02%2013-05-55Z/%E2%9C%93%20Example%20should%20have%20welcome%20screen/device.log

**Comment by dmitriy-brikov** [comment]
I see I'm having the same problem so I'm wondering if a solution has been found for this?

**Comment by noomorph** [comment]
Disable instruments recording.

@d4vidi shall we remove instruments plugin at all, maybe?
