### ISSUE TITLE
Verify the color of an element using Detox

### ISSUE THREAD

**Issue by Skaramus1990** [wix/Detox#3557]
### Description

Hello there!

From time to time I need to validate the color change of an element after a click. Couldn't find a solution at the moment. I would be grateful for any information about my problem.

```
const attr = await element(by.id("the id")).getAttributes();
console.log(attr);
```
this prints out the height, width, etc. but not the styles.

### Your environment

Detox version: 19.7.0
React Native version: 0.67.3
Node version: 10.7.0
Device model: iPad Pro (9.7-inch)
OS: MacOs Monterey / IOS
Test-runner (select one): cucumber

**Comment by d4vidi** [comment]
Thanks @Skaramus1990! This is in fact a dup of #3297

**Comment by Skaramus1990** [comment]
@@dido  Thank you for your  quick answer. How about borderColor attribute? Generally in the css styles we can have a lot of attributes for verification.
