### ISSUE TITLE
Does codepush can get along with Detox?

### ISSUE THREAD

**Issue by chenop** [wix/Detox#3568]
### Description

I got no fact base for this claim - but its seems that Im reducing the flakiness factor in my tests if I disable codepush.
Also stumble into this [StackOverflow Answer](https://stackoverflow.com/a/57374186/1846993).

Is it a known issue?
What is your recommendation regarding using codepush with Detox?

### Your environment

Detox version: 19.10.0
React Native version: 0.66.4
Node version: 14.19.1
Device model: Iphone 13
OS: 
Test-runner (select one): jest-circus / jest+jasmine / mocha / other

**Comment by d4vidi** [comment]
Not aware of this problem TBH

**Comment by chenop** [comment]
Thanks @d4vidi for responding - one more thing to consider:
When an app has a codepush version to download then there will be this extra blink and restart that caused during the replacement of the bundle - do you think it might disrupt and fail a detox test?

**Comment by d4vidi** [comment]
I think it _might_ disrupt Detox, because it assumes the bundle loading takes place inherently during app launch. Nevertheless, that doesn't mean that Detox cannot fundamentally work with codepush; It sounds like the blindspots are mainly around the use cases where a new bundle is loaded.

**Comment by chenop** [comment]
Right exactly - this important point to take into consideration while running the tests - Thanks!
