### ISSUE TITLE
Artifacts location is undefined in XCode debug configuration

### ISSUE THREAD

**Issue by Kureev** [wix/detox#357]
Following https://github.com/wix/detox/blob/master/docs/Guide.DebuggingInXcode.md flow I found that there is an error that prevents code from working using detox xcode debug configuration. In `Device.js` there is a function called `_getAbsolutePath` that requires `--artifacts-location` or `binaryPath` to be set in order to compute artifacts location. There are three possible solutions to this:
- Add additional check for scheme name (like if it is `xcode` scheme, then use some custom pre-defined folder for artifacts)
- Add note to documentation describing this behaviour so people are aware of implications
- Disable artifacts altogether if not specified in cli command or detox config

Would like to hear you thoughts, @DanielMSchmidt @rotemmiz 

#### Steps to Reproduce

Follow https://github.com/wix/detox/blob/master/docs/Guide.DebuggingInXcode.md guide with Jest runner. The error will appear immediately

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 5.9.1
* Node: 8.6.0
* Device: any
* Xcode: any
* macOS: 10.12.6

#### Device and verbose Detox logs

N/A

**Comment by rotemmiz** [comment]
Or we can disable artifacts altogether if not specified in cli command or detox config

**Comment by Kureev** [comment]
This is also an option. Just let me know and I will compose a PR 😉

**Comment by rotemmiz** [comment]
Yes, I think we should disable it if users haven’t configured artifacts location.

**Comment by Kureev** [comment]
Okay, will compose a PR later this day

**Comment by danieldunderfelt** [comment]
I ran into this just now as I'm trying to get started with Detox and an example React Native project. I followed the steps in the Getting Started guide and https://github.com/wix/detox/blob/master/docs/Guide.Jest.md and it says `Could not create artifacts root dir` when trying to run the tests, and then it terminates the app.

**Comment by Kureev** [comment]
@danieldunderfelt as a temporary workaround, you can add `-a <folder-for-artifacts>` flag.

**Comment by Kureev** [comment]
Regarding the topic, I managed to disable artifacts, although it was more work than I expected. Lots of tests are failing now 😒, have to look into it deeper.
