### ISSUE TITLE
Type safety in configuration file

### ISSUE THREAD

**Issue by philiplindberg** [wix/Detox#3575]
### Describe your idea

I'm using detox with my typescript react native project, and while I've figured out a way to write my e2e tests in typescript (via ts-jest), it'd be great to also get type safety in the detox configuration file (`.detoxrc.json` or equivalent). Right now I'm using `detox.config.js` as my config file, but perhaps you could add support for `detox.config.ts` (notice the `.ts` extension) that could use the types already defined in `index.d.ts` (like the `DetoxConfig`, `DetoxAppConfig`, and `DetoxDeviceConfig` interfaces).

**Comment by asafkorem** [comment]
Hi @philiplindberg, makes sense.

I think it can be done by adding `detox.config.ts` to the external configs list in [loadExternalConfig.js](https://github.com/wix/Detox/blob/d7c387f33394eb94b0fb49256c69c3f417e149ab/detox/src/configuration/loadExternalConfig.js#L11). @noomorph please correct me if I'm wrong 🙂 

@philiplindberg I encourage you to try what I suggested (change Detox under your node modules) and open us a pull request if it works 😉

**Comment by noomorph** [comment]
@philiplindberg you could use JSDoc annotations for type checking for now:

```javascript
/** @type {Detox.DetoxConfig} */
module.exports = {
  // ...
};
```

That should do fine, if you configure TypeScript to check it.

@asafkorem nope, that's not that easy. I'd prefer not to start this thing with extra transformers, etc.

We might consider making it possible to work with ts-node (doesn't it work already btw???), but that's it.

By the way, Detox 20 will come with boilerplate like I demonstrated above to enforce type safety.

**Comment by philiplindberg** [comment]
I was able to get autocomplete in VS Code working by adding `/** @type {Detox.DetoxConfig} */` to the top of `detox.config.js`. Thanks @noomorph!

**Comment by noomorph** [comment]
Thanks @philiplindberg . I'll make this a default thing in `detox init`-generated projects starting from Detox 20.
