### ISSUE TITLE
Android device screenshots are transparent on Github Actions

### ISSUE THREAD

**Issue by ablok** [wix/Detox#3578]
### Description

I use Github Actions to run a pipeline that tests a react native app in both Android and iOS emulators.
I do screenshot comparisons in some cases for validations. On my local mac this all works as expected.
On Github Actions this also works fine for iOS, but for Android any **device** screenshots that I take show up as transparent images with the correct resolution. Taking screenshots of elements works just fine.

Any ideas of what might be causing this would be appreciated.

### Your environment

Detox version: 19.9.3
React Native version: 0.64 
Node version: 16.17.0
Device model: emulator pixel
OS: mac
Test-runner (select one): jest+jasmine

**Comment by DaveM80** [comment]
We're seeing the same issue

**Comment by wadey1** [comment]
Also having this issue

**Comment by ayush547** [comment]
Was facing the same issue, setting the avd to use "-gpu host" solved my issue.
