### ISSUE TITLE
Can't find device <udid> even though its loaded and available

### ISSUE THREAD

**Issue by Kureev** [wix/detox#358]
#### Description

I managed to get everything to work using xcode configuration (so the app is already running). Although, if I try the "classic" approach, then I have an issue: after booting device it stops detecting it and crashes with the logs below. 

#### Steps to Reproduce

Scaffold a new empty application and try to run tests using hardware configuration I reported below.

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 5.9.1
* Node: 8.6.0
* Device: iPhone 7 iOS 11.1
* Xcode: 9.1, 9.0
* macOS: 10.12

#### Device and verbose Detox logs

**console output:**
```
detox info 18:07:20: server listening on localhost:52009...
{ binaryPath: 'ios/build/Build/Products/Debug-iphonesimulator/Werkspot.app',
  build: 'xcodebuild -project ios/Werkspot.xcodeproj -scheme Werkspot -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build',
  type: 'ios.simulator',
  name: 'Test Phone' }
detox info 1: Searching for device matching Test Phone... 
detox info 5: Booting device 5923C6BC-B3DA-43A2-B0C3-39B860EC2D00 
  1) "before all" hook

  0 passing (49s)
  1 failing

  1) "before all" hook:
     Error: Can't find device 5923C6BC-B3DA-43A2-B0C3-39B860EC2D00
      at AppleSimUtils._callee3$ (node_modules/detox/lib/devices/AppleSimUtils.js:42:19)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at step (node_modules/detox/lib/devices/AppleSimUtils.js:1:809)
      at node_modules/detox/lib/devices/AppleSimUtils.js:1:969
      at <anonymous>
```

**simulator logs:**
```
Oct 23 18:07:35 Alexeys-MacBook-Pro com.apple.CoreSimulator.SimDevice.5923C6BC-B3DA-43A2-B0C3-39B860EC2D00[29232] (com.apple.mobileslideshow.PhotosFileProvider[29331]): assertion failed: 16G29: launchd_sim + 63487 [83848CEE-5530-38E6-81EB-0079E119BBF6]: 0x16
Oct 23 18:07:35 Alexeys-MacBook-Pro cfprefsd[29271]: BUG in libdispatch client: kevent[mach_recv] monitored resource vanished before the source cancel handler was invoked
```

**Comment by LeoNatan** [comment]
Xcode 9.1 comes with iOS 11.1 simulators
Xcode 9.0 comes with iOS 11.0 simulators
Each is in a different path. If you want to swap Xcodes, you need to `xcodeselect` and switch the path.
Have you done that?

**Comment by Kureev** [comment]
Nope. I'll try to do that tomorrow. Although, I have to say that the simulator starts either way.

**Comment by LeoNatan** [comment]
Any news on this issue?

**Comment by Kureev** [comment]
Sorry, didn't manage yet. I'll close it for now and re-open once I have more info to share.
