### ISSUE TITLE
Test Failures due to System Alert on CI--- Add retry

### ISSUE THREAD

**Issue by rengarima** [wix/detox#359]
Our CI is sitting behind proxy and sometimes (often) the tests fails due to proxy alerts. This is a mac issue but is there a workaround available? Like if the proxy alert is shown then retry? I dont get this locally but there is a 50% chance the test fails due to Proxy Alerts. Re-running usually resolves it but it is quite annoying

#### Detox, Node, Device, Xcode and macOS Versions
RN: 0.47.2
Detox: 5.8.1
Node: 8.4.0
Device: "iPad Air 2, iOS 10.3"
Xcode: 9.0
macOS: 10.12.6

#### Device and verbose Detox logs
Cannot perform action due to constraint(s) failure.
Exception with Action: {
  "Action Name" : "Tap",
  "Element Description" : "<RCTTextField:0x7fb9c7c264e0; AX=Y; AX.id='login-field'; AX.label='Username or email'; AX.frame={{291, 189.5}, {1024, 36}}; AX.activationPoint={803, 207.5}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{15, 5}, {1024, 36}}; opaque; alpha=1; text=''>",
  "Failed Constraint(s)" : "!(isSystemAlertViewShown)",
  "All Constraint(s)" : "(!(isSystemAlertViewShown) && ((respondsToSelector(isAccessibilityElement) && isAccessibilityElement) || kindOfClass('UIView')) && (enabled && !(((kindOfClass('UIView') || respondsToSelector(accessibilityContainer)) && ancestorThatMatches(!(enabled))))) && interactable)",
  "Recovery Suggestion" : "Adjust element properties so that it matches the failed constraint(s)."
}

[
  {
    "Description" : "Cannot perform action due to constraint(s) failure.",
    "Error Domain" : "com.google.earlgrey.ElementInteractionErrorDomain",
    "Error Code" : "1",
    "File Name" : "GREYBaseAction.m",
    "Function Name" : "-[GREYBaseAction satisfiesConstraintsForElement:error:]",
    "Line" : "66"
  }
]

**Comment by rotemmiz** [comment]
Retry is in the scope of your test runner, here are Mocha's docs https://mochajs.org/#retry-tests
Having network issues in e2e is a real pain, I suggest you either solve them or think about mocking your server endpoint (https://github.com/wix/detox/blob/master/docs/Guide.Mocking.md).

I am closing this issue, as it is out of Detox's scope.
