### ISSUE TITLE
latest XCode 14 / iOS 16 simulators broken with Detox

### ISSUE THREAD

**Issue by changey** [wix/Detox#3593]
### What happened?

After upgrading to iOS 16 simulators / XCode 14 I wasn't able to use Detox to open the app. I was able to get around by installing an iOS 15 simulator but want to flag that

Below is the error message

```
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
The operation couldn’t be completed. found nothing to terminate
found nothing to terminate
 `/usr/bin/xcrun simctl terminate 123 com.app` (exited with error code 3)
```

### What was the expected behaviour?

Detox should function normally after the iOS 16 simulators / XCode 14 upgrade

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [x] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 19.7.0
React Native version: 0.67.4
Node version: 
Device model: iPhone 13 Pro
iOS version: 16
macOS version: 
Xcode version: 14
Test-runner (select one): jest-circus / jest+jasmine / mocha / other

### Detox logs

<details><summary>Detox logs</summary>

```
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
The operation couldn’t be completed. found nothing to terminate
found nothing to terminate
 `/usr/bin/xcrun simctl terminate 123 com.app` (exited with error code 3)
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by changey** [comment]
@asafkorem thank you!

**Comment by asafkorem** [comment]
@changey is it resolved for you?
