### ISSUE TITLE
iOS 16 - app doesn't launch with permissions passed into device.launchApp() and freezes after setBiometricEnrollment()

### ISSUE THREAD

**Issue by Vadko** [wix/Detox#3597]
### What happened?

After updating xcode to version 14 and using iOS 16 simulator, app doest launch if device.launchApp have permissions passed inside configuration. If there are no permissions in configuration app launch as expected.

Also, after app started with empty config if we have device.setBiometricEnrollment(true) app instantly freezes.

Same config worked as expected on iOS 15 simulators.

Detox doesnt return any logs on any level due to app wasnt launched.

### What was the expected behaviour?

App launches correctly

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

launch app on iOS 16 simulator with any permissions passed

### In what environment did this happen?

Detox version: 19.12.1
React Native version: 0.68.2
Node version: 18.8.0
Device model: iPhone 11 Simulator
iOS version: 16
macOS version: 12.6
Xcode version: 14
Test-runner (select one): jest-circus

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by tylercote** [comment]
I can confirm I am having the same issue. Removing permissions from the launch config prevents the freeze.

**Comment by yaanr3is** [comment]
Apparently it didn't!

**Comment by asafkorem** [comment]
@Vadko what permissions are you trying to set on launch?

**Comment by asafkorem** [comment]
> Also have the same issue
> 
> ### Error log
> ```
> ChildProcessError: Command failed: applesimutils --byId 2D583D90-E586-4C25-B4A7-5837418F47C6 --bundle org.reactjs.native.example.example --restartSB --setPermissions health=YES
>     applesimutils[67220:3074627] DB Error: 1 "no such column: bundle_id"
>     applesimutils[67220:3074627] DB Query: select ROWID from sources where bundle_id == :bundle_id
>     applesimutils[67220:3074627] DB Path: /Users/xxx/Library/Developer/CoreSimulator/Devices/2D583D90-E586-4C25-B4A7-5837418F47C6/data/Library/Health/healthdb.sqlite
> ```

@alarm109 Looks like something has changed in the `healthdb.sqlite` "sources" table, maybe an easy fix, not sure. Need to figure whether this table field (`bundle_id`) has replaced with something else. I encourage you to investigate this yourself (and maybe to fix this as well), also - this is a pure [AppleSimUtils](https://github.com/wix/AppleSimulatorUtils) issue, so please open a new issue with this error there 🙏🏼

**Comment by yaanr3is** [comment]
> @Vadkoquais permissões você está tentando definir no lançamento?

I'm passing these permissions.

{
    "launchArgs": { "detoxPrintBusyIdleResources": "YES" },
    "permissions": {
      "location": "always",
      "notifications": "YES",
      "camera": "YES",
      "microphone": "YES",
      "contacts": "YES"
    }
}

**Comment by yaanr3is** [comment]
> > Também tem o mesmo problema
> > ### Registro de erros
> > ```
> > ChildProcessError: Command failed: applesimutils --byId 2D583D90-E586-4C25-B4A7-5837418F47C6 --bundle org.reactjs.native.example.example --restartSB --setPermissions health=YES
> >     applesimutils[67220:3074627] DB Error: 1 "no such column: bundle_id"
> >     applesimutils[67220:3074627] DB Query: select ROWID from sources where bundle_id == :bundle_id
> >     applesimutils[67220:3074627] DB Path: /Users/xxx/Library/Developer/CoreSimulator/Devices/2D583D90-E586-4C25-B4A7-5837418F47C6/data/Library/Health/healthdb.sqlite
> > ```
> 
> @alarm109Parece que algo mudou na `healthdb.sqlite`tabela "fontes", talvez uma correção fácil, não tenho certeza. Precisa descobrir se este campo de tabela ( `bundle_id`) foi substituído por outra coisa. Eu encorajo você a investigar isso sozinho (e talvez para corrigir isso também), também - este é um problema puro [do AppleSimUtils](https://github.com/wix/AppleSimulatorUtils) , então abra um novo problema com este erro 🙏🏼

I've tried everything and I couldn't.

**Comment by yaanr3is** [comment]
> aqui

Good morning, I don't know how I would solve this location, will there not be an update?

The strange thing is that my iOS is 15.5 and I have this problem.

**Comment by asafkorem** [comment]
> @alarm109, apparently, Apple has renamed the `bundle_id` with `udId` in this `sources` table. ![image](https://user-images.githubusercontent.com/55082339/196635642-880050b4-63ea-44fa-aaa3-277d3ade249b.png) I've opened the corresponding issue in AppleSimUtils, [here](https://github.com/wix/AppleSimulatorUtils/issues/105). If you want to fix this yourself, this can be a great open source contribution, if not, I'll fix this soon.

[ASU v0.9.8](https://github.com/wix/AppleSimulatorUtils/releases/tag/0.9.8) released with this fix (HealthKit). Thanks to @GGGava! 👏🏼 
Please upgrade your ASU version using homebrew.

@alarm109 

As for your issue @yaanr3is and @Vadko, please provide the error message you get, I suspect you have a different error than this.

**Comment by kyaroru** [comment]
Hi, thanks for the fixes. I am having the same issues & updated my applesimutils to `v0.9.8`. But running detox with 
```js
await device.launchApp({ newInstance: true, permissions: { notifications: 'YES' } })
```
still fails (as in it loads forever until timeout)

it was working fine before I updated my xcode from v13 to v14 with ios 16 simulator

The log i'm getting from `detox test --configuration ios.sim.debug --loglevel=verbose` is only load up to set permissions line & stopped
```sh
00:50:32.383 detox[36236] DEBUG: [EXEC_CMD, #7] applesimutils --byId 0838CF49-F522-4435-ABA7-6EA13CF25D83 --bundle com.xxx.xxx.dev --restartSB --setPermissions notifications=YES
00:50:32.383 detox[36236] DEBUG: [EXEC_TRY, #7] Trying to set permissions...
```
