### ISSUE TITLE
Can Detox android test with device server host ?

### ISSUE THREAD

**Issue by petchkubb** [wix/Detox#3599]
### Description

I have some question. my project have to run e2e on CI with android emulator run on server host use `adb -H host.docker.internal` for control emulator. is it possible detox can test with emulator on server host instead of local host server? 

> **$ yarn e2e:android --cleanup --take-screenshots failing**
yarn run v1.22.19
**$ detox test -c android.emu.release e2e/specs/ --cleanup --take-screenshots failing**
13:33:37.504 detox[495] INFO:  [test.js] DETOX_CLEANUP=true DETOX_CONFIGURATION="android.emu.release" DETOX_REPORT_SPECS=true DETOX_START_TIMESTAMP=1663223617482 DETOX_TAKE_SCREENSHOTS="failing" DETOX_USE_CUSTOM_LOGGER=true jest --config e2e/config.json --testNamePattern '^((?!:ios:).)*$' --maxWorkers 1 e2e/specs/
13:33:51.104 detox[507] INFO:  at e2e/helpers/index.ts:35:13 
 helper initialize
13:34:06.792 detox[507] ERROR: [EXEC_FAIL, #1] ""/sdk-tools-linux/platform-tools/adb"  shell "getprop ro.build.version.sdk"" failed with error = ChildProcessError: Command failed: "/sdk-tools-linux/platform-tools/adb"  shell "getprop ro.build.version.sdk"
adb: no devices/emulators found
 `"/sdk-tools-linux/platform-tools/adb"  shell "getprop ro.build.version.sdk"` (exited with error code 1) (code=1), stdout and stderr:
13:34:06.792 detox[507] ERROR: [EXEC_FAIL, #1] 
13:34:06.792 detox[507] ERROR: [EXEC_FAIL, #1] adb: no devices/emulators found
13:34:06.793 detox[507] ERROR: Command failed: "/sdk-tools-linux/platform-tools/adb"  shell "getprop ro.build.version.sdk"
adb: no devices/emulators found
 `"/sdk-tools-linux/platform-tools/adb"  shell "getprop ro.build.version.sdk"` (exited with error code 1)

### Your environment

Detox version: 19.8.0
React Native version: 0.69.5 
Node version: 16
Device model:  android emulator
OS: Mac os
Test-runner (select one): jest-circus

**Comment by d4vidi** [comment]
No, Detox cannot do that ATM, but we definitely accept contributions. Could you elaborate on that specific emulator mode you've described? What do you get if you run `adb devices` when such an emulator is up and running? Copy&paste the result.
