### ISSUE TITLE
Android version

### ISSUE THREAD

**Issue by talkol** [wix/detox#36]
Phase 1 - react-native-invoke for Java

Phase 2 - Integrate with Espresso

**Comment by rotemmiz** [comment]
Phase 1: https://github.com/wix/react-native-invoke/tree/master/android

**Comment by rotemmiz** [comment]
Phase 2 is currently being developed on a [feature branch ](https://github.com/wix/detox/tree/android), but the scope is bigger since it must include a refactor of index.js, argument parsing and js code restructure.

**Comment by LeoNatan** [comment]
This is tracked elsewhere, in an issue and PRs. Closing.
