### ISSUE TITLE
Adding "contain" to matchers and expectation functions

### ISSUE THREAD

**Issue by vasylshlapaks** [wix/Detox#3600]
### Describe your idea

I think it's must have to have ability to match element by containing of something and the same for expectations.
This is a common feature across all test libraries not only checking text by strict value but also checking if it's containing something

**Comment by d4vidi** [comment]
I think this is a dup of #3366, let me know if you think otherwise. You can upvote #3366.

**Comment by vasylshlapaks** [comment]
@d4vidi I would say that regex is a bit different, this can be covered by this I guess, but just simple `expect(element).toContain('something')` or `element(contain.id('someid')` would be much more user-friendly

And again examples can be found in Jest assertions in Playwright in WebdriverIO this is a common thing that makes work with screen easier 

Simple example of problem - my field shown not only country but flag as well, I don't like having flag icons in my matchers
Buy I agree that regex will help to fix this is well

**Comment by pradeipp** [comment]
this would be great if implemented. Either this or the [regex implementation](https://github.com/wix/Detox/issues/3366) would be very welcome.
