### ISSUE TITLE
Optimize multi-apps preinstallation flow

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#3604]
### Describe your idea

With respect to [these lines of code](https://github.com/wix/Detox/blob/105488778bbc4de4e2defed3e267ab0cc33fbe0b/detox/src/Detox.js#L251) under Detox's init:
```js
    for (const appName of appNames) {
      await this.device.selectApp(appName);
      await this.device.uninstallApp();
    }

    for (const appName of appNames) {
      await this.device.selectApp(appName);
      await this.device.installApp();
    }
```

As seen clearly in tests inside Wix, in multi-apps mode, preinstalling all apps in advance can REALLY add up to a long duration of setting things up -- resulting in hits of test-init timeouts.

We need to come up with a less-naive strategy of installing apps compared to the current one (i.e. taking the unnecessarily extreme assumption that they would _all_ be required during the test).

---

Side note: Once implemented, it can and should be followed by reducing time-outs in internal projects.

**Comment by noomorph** [comment]
We can do that in Detox 20.1 as a part of global device
allocation/deallocation driver.

ср, 21 вер. 2022 р. о 11:20 d4vidi ***@***.***> пише:

**Comment by noomorph** [comment]
See the PR in DWP repo.

**Comment by noomorph** [comment]
Closed via https://github.com/wix-private/detox-wix-preset/pull/241
