### ISSUE TITLE
Make matchers separately definable to facilitate Page Object Model-style implementation 

### ISSUE THREAD

**Issue by pradeipp** [wix/Detox#3612]
### Describe your idea

I'm new to detox along with js/ts and wanted to implement a Page Object Model structure where we define matchers and functions for reuse, readability and organization.

I wanted to organize my matchers, functions and specs in a fashion like shown below(I come from C#/Java so I wanted to use classes and objects and chain methods but it didn't make much sense in js/ts):

Page File:
```JS
import { element, by } from 'detox';

export NavBar = {
    homeTab: element(by.id('HomeTab')),
    discoverTab: element(by.id('Discover')),
    searchBar: element(by.id('q')),
    async searchText(query: string){
        await NavBar.searchBar.typeText(query);
        return await NavBar.searchBar.tapReturnKey();
    }
}
```

Spec file:
```JS
import { NavBar } from "./PageFile";
import { tap } from 'detox'

describe('My app', ()=>{
    it('should enter the search query in discover tab', ()=>{
        await NavBar.homeTab.tap();
        await NavBar.discoverTab.tap();
        await NavBar.searchText('Fantastic Mr.Detox');
    }
```

Currently, if we try to create a structure like this, it doesn't work. It fails with this error message pointed at the first matcher(for hometab): 
```
 DetoxRuntimeError: Detox instance has not been initialized

    HINT: Make sure to call detox.init() before your test begins
```

Any reason why this isn't supported or recommended? If I put the matchers inside a function however, that seems to work fine. But defining a function for each matcher would defeat the purpose of making the e2e code lean.

**Comment by noomorph** [comment]
It has nothing to do with your code style and architecture. It's just something misconfigured in your project.

You can create a minimal repository that reproduces the issue and then nudge me to look.
