### ISSUE TITLE
App freeze on iOS with new XCode

### ISSUE THREAD

**Issue by anija** [wix/Detox#3615]
### Description

After upgrading XCode some days ago, my tests, that where running fine, started to fails.
The app on the emulator freeze and became unresponsive, and the only thing I can do is to force quit it and start tests again.
Sometimes (1 every 50) i got a crash report without any useful information.
The app never freeze during development, on the same emulator.
Detox fails just saying that the app don't respond to an action, like "tap".

### Your environment

Detox version: 19.12.1
React Native version: 0.68.3
Node version: 16.13.2
Device model: iOS emulator, iPhone 14, iOS 16.0
Test-runner: jest-circus

**Comment by anija** [comment]
Thank you for the answer!
I've tried the --debug-synchronization without any luck (nothing got logged).

This morning I totally removed the reanimated animations from the app, and the tests started to go linear as usual. So i debugged deeper and I found a bug in a particular animation. The main difficulty was the concurrency of a lot of possible causes: updated iOS, updated xCode, updated Detox and updated the app that prevented from immediatly finding the real cause. I was pretty sure the bug wasn't Detox itself, but after a week of debug I didn't know what else to do so I tried posting here ;)

**Comment by asafkorem** [comment]
🙂 It's totally understandable, glad the problem was found!
What did you discover? Could you share it with us?

**Comment by asafkorem** [comment]
I mainly want to understand whether this is something we could catch and print on our logs

**Comment by anija** [comment]
Sadly, I've found nothing useful neither in detox logs at any level, neither in the crash reports. The app was freezing on the emulator but this was not related to detox at all, it's just a mistery why wasn't freezing also during development (I was launching detox tests both in develop and release mode)
