### ISSUE TITLE
Detox action firing but not resolving

### ISSUE THREAD

**Issue by sunny-mittal** [wix/Detox#3618]
### Description

I've been using model-based testing with xstate and detox and it's been going spectacularly well so far but I've run into an issue that's hard to debug. Initially I thought it was an xstate issue but I believe I've narrowed it down to detox using some logs. So I'm building a test path for my authentication flow. Every step works great but at the end, a skip button is pressed and it's firing but never resolving so the remainder of the test never executes. The relevant line in my test is:
```
console.log("Before skip", "AddPicture)
await element(by.id("SkipBtn").withAncestor(by.id("AddPicture))).tap()
console.log("After skip", "AddPicture")
```
I have the same type of log decoration around another skip press in the test but my detox logs come out as follows:
```
17:48:10.985 detox[74086] INFO:  at e2e/tests/login.spec.ts:319:37
 Before skip AddName
17:48:12.645 detox[74086] INFO:  at e2e/tests/login.spec.ts:328:37
 After skip AddName
17:48:15.894 detox[74086] INFO:  at e2e/tests/login.spec.ts:319:37
 Before skip AddPicture
17:48:26.032 detox[74086] INFO:  [APP_STATUS] The app is busy with the following tasks:
• Run loop "Main Run Loop" is awake.
• 1 enqueued native timers:
  - Timer #1:
    + Fire date: none.
    + Time until fire: 0.000.
    + Repeat interval: 0.
    + Is recurring: YES.
```
As you can see, the before/after logs for AddName come out just fine but only the before log for AddPicture comes out. The thing is, the line right after that log is to click the skip button and it does it just fine when observing the app in the simulator. Can anyone speculate as to what's going on? My best guess is that the action to click the Skip button fires but then other API calls start kicking off and one of them is not terminating, causing the action promise to never resolve.  Unfortunately, the debug log doesn't provide much help in identifying what that call might be so any suggestions would be greatly appreciated. Thank you!

### Your environment

Detox version: 19.12.1
React Native version: 0.66.4 
Node version: 16.9.1
Device model: iPhone 13
OS: 15.5
Test-runner (select one): jest+jasmine

**Comment by sunny-mittal** [comment]
Further debugging shows it's definitely something to do with the device sync but I dunno what to do exactly. When I change the code snippet I posted to:
```
await device.disableSynchronization()
console.log("Before skip", state.value)
await element(by.id("SkipBtn").withAncestor(by.id(state.value as string))).tap()
console.log("After skip", state.value)
await device.enableSynchronization()
```
the After skip log comes out and _then_ the test hangs. Are there any temporary hacks I can use to narrow down the cause of the issue so I can remedy it correctly?

**Comment by caiorrsdeg** [comment]
reopening this because it's not resolved

**Comment by sunny-mittal** [comment]
I forgot to report back on this but this might help someone else. In my case, the transition that happens when the detox test seemed to hang and never resolve involved an `Animated.View` from reanimated. By mocking the module, the test was able to proceed. Something like this:
```
// in reanimated.ts
import Animated from "react-native-reanimated"
export * from "react-native-reanimated"

export default Animated

// in reanimated.e2e.ts
export * from "react-native-reanimated"

export default {
  View: () => null,
  Text: () => null,
}
```
Of course you'll have to configure metro to favor the e2e extension when running your tests and then import reanimated modules from your custom version, but it's a pretty simple fix.

**Comment by KaterinaUK** [comment]
@sunny-mittal can you please provide more details on how you fixed the issue?

**Comment by mersiades** [comment]
> @sunny-mittal can you please provide more details on how you fixed the issue?

I got this to work by following the docs for Detox mocking are here: [https://wix.github.io/Detox/docs/guide/mocking/](https://wix.github.io/Detox/docs/guide/mocking/ )

This guide was also useful in that it gave me ideas, but didn't actually work for me: [https://hartaniyassir.medium.com/troubleshooting-detox-hang-from-animations-3-practical-solutions-49d891d76f1d](https://hartaniyassir.medium.com/troubleshooting-detox-hang-from-animations-3-practical-solutions-49d891d76f1d)

For me, rather than mocking out `Animated`, I created a mock version of the component that uses `Animated` (I only have one component that uses it.)

- `AnimatedEllipsis.tsx`
- `AnimatedEllipsis.detoxmock.tsx`

Hope that helps, @KaterinaUK , let me know if you have further questions.
