### ISSUE TITLE
Count all elements in a scrollview

### ISSUE THREAD

**Issue by Alaa-Ben** [wix/Detox#3622]
### Description

Hi !
First of all, thanks for Detox, it's awesome !
I'm having troubles understanding how the by.id works.
I thought it matched all elements (not only visible ones) so matchers as toExist could be applied.
But it seems it doesn't work that way: I have a scrollview with n elements, and i'm using the following function to try and count them:
```ts
export async function elementCount(matcher) {
  let attributes = { elements: [] }
  try {
    attributes = await element(matcher)?.getAttributes()
  } catch (e) {
    return 0
  }
  if ("elements" in attributes) {
    return attributes.elements.length
  } else {
    return 1
  }
}
```
I'm trying to test an element deletion, so the test expects the new count to be equal to the old count - 1, but it seems count is always 0
Any ideas on how to achieve what i'm trying to do ?

### Your environment

Detox version: 19.5.1
React Native version: 0.67
Node version: 14.19.1
Device model: Samsung Galaxy A
OS: Android
Test-runner: jest-circus

**Comment by pradeipp** [comment]
not stale

**Comment by asafkorem** [comment]
Hi @Alaa-Ben, this is a very interesting case, however, without reproduction, it will be very hard for us to investigate that. Can you please provide a small reproduction code (or project) for such view and test? this would be very helpful!

**Comment by Alaa-Ben** [comment]
@asafkorem Well as I said, it's a pretty standard case.
Take a classic Scrollview, put like a view or text element with a testID, then copy then element n times (as long as the scrollview becomes scrollable), then query the elements. And you'll notice only the visible elements are queried.

**Comment by d4vidi** [comment]
@Alaa-Ben wouldn't it be enough to assert that the element exists _before_ the deletion and that it does not _after_ it? Having it switched instead to somewhere outside the list's rendered area is very unlikely 😅

**Comment by d4vidi** [comment]
Also, could you share the error you get in -
```js
catch (e) {
    return 0
}
```
?

**Comment by d4vidi** [comment]
FWIW This is likely a duplicate of #3196, and probably works well on iOS (and will work well on Android once fixed).
