### ISSUE TITLE
launchApp vs reloadReactNative : differences of execution ?

### ISSUE THREAD

**Issue by shunxing** [wix/Detox#3623]
### Description

Hey there 👋 

I was writing some e2e tests and it turns our to be flaky. Sometimes my app is not triggering any app reload when using `await device.reloadReactNative()` and it expects the next element to be visible.

I'm wondering whether `reloadReactNative` could have been ignored.

I can see that there is another approach using `await device.launchApp({newInstance: true});` 

It says in the documentation that the first approach (`reloadReactNative`) is much faster than launching a new app. Except that, is there any benefit the second approach could bring such as reliability, less flakiness?

### Your environment

Detox version:  19.7.0
React Native version:  0.68.2
Node version: 16.13
Device model: iPhone 12
Test-runner (select one): jest-circus/runner

**Comment by noomorph** [comment]
I'll be straight with you: `device.reloadReactNative()` is fast but less reliable. If you see glitches, switch to `device.launchApp({ newInstance: true })`.
