### ISSUE TITLE
Configure permission

### ISSUE THREAD

**Issue by yaanr3is** [wix/Detox#3633]
### Description

Good morning guys, I have a problem that I can't configure the permissions of my simulator.

when starting the tests he keeps trying to configure the permissions and the timeout.

and my app does not open.

```
const detox = require('detox')

const config = require('../package.json').detox
import { list } from './app/blackList'
import launchConfig from './app/config.json'

// Set the default timeout
jest.setTimeout(300000)


beforeAll(async () => {
  await detox.init(config, { launchApp: false })
  await device.launchApp(launchConfig);
  await device.setURLBlacklist(list)
})

afterAll(async () => {
  await detox.cleanup()
})


export async function reset(){
  await device.terminateApp()
  await device.uninstallApp()
  await device.installApp()
  await device.launchApp(launchConfig)
  await device.setURLBlacklist(list)
}
```

### Your environment

Detox version: 19.7.1
React Native version: 0.65.0
Node version: v14.20.1
Device model: iPhone 8
OS: 
Test-runner (select one): jest-circus / jest+jasmine / mocha / other

**Comment by noomorph** [comment]
What kind of permissions? And what test runner do you use?
