### ISSUE TITLE
Detox for Andriod test build doesnt load css or images

### ISSUE THREAD

**Issue by Faziki** [wix/Detox#3635]
### Description

If I make a normal build release or Dev build the images and styling are available but if I make a build for detox and run my tests none of the styling and images in react-native displays and I cant test because detox says the element is not visible.

### Your environment

Detox version:   `  "detox": "^19.12.6",`
React Native version: ` "react-native": "0.69.4",`
Node version:  `v14.20.0`
Device model:  Android Pixel 4a
OS: `Windows 10` 
Test-runner (select one): `"jest": "29.2.0",`

**Comment by Faziki** [comment]
@d4vidi Could anyone please assist ?

**Comment by jonathanmos** [comment]
@Faziki does this work correctly on ios? Also, does this issue occur both for debug and release builds? Could you run the tests in verbose (`-l verbose`) and include any relevant output?

**Comment by Faziki** [comment]
Well I am on a windows PC so I cant say if its just my environment or not, but my college can test fully on IOS he doesn't have his android side setup.

not sure because this ticket is a bit old and I am fuzzy on the details need to test again to see if its on both debug and release
