### ISSUE TITLE
Detecting emulator boot on api ≥ 31

### ISSUE THREAD

**Issue by jonathanmos** [wix/Detox#3636]
### What happened?

This issue is to provide a single location to track the problem of detecting emulator boot on api >= 31. 

**Problem description:**
On API 31 and above when using a fresh emulator to run tests, the emulator boots but detox does not detect the emulator as ready and reaches a timeout instead of running the tests.

**Cause**
On api <= 30 we resolve device boot when we see [`Adb connected, start proxing data` in the emulator log.](https://github.com/wix/Detox/blob/master/detox/src/devices/allocation/drivers/android/emulator/launchEmulatorProcess.js#L23) 

However on 31 and above, for some reason, this line does not appear. Example of emulator logs from api 29 vs 31:

**API 29**
```
VERBOSE | got message from guest system fingerprint HAL
VERBOSE | onGuestSendCommand: [0x600002d41ba0] Adb connected, start proxing data
INFO    | boot completed
INFO    | boot time 6534 ms
````

**API 31**
```
VERBOSE | got message from guest system fingerprint HAL
INFO    | boot completed
INFO    | boot time 18310 ms
```

**Solution**
Searching for 'boot completed' seems to work for all api levels, however it's still unclear why on api >= 31 the onGuestSendCommand line is not printed in the log. 

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 
React Native version: 
Node version: 
Device model: 
Android version: 
Test-runner (select one): jest-circus / jest+jasmine / mocha / other

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by d4vidi** [comment]
@jonathanmos thanks. Please do your best in order to close all duplicate/similar issues (if needed) and reference this consolidation of them 🙏🏻

**Comment by jonathanmos** [comment]
Opened a new pr -> https://github.com/wix/Detox/pull/3672

**Comment by jonathanmos** [comment]
Fixed in https://github.com/wix/Detox/pull/3672
