### ISSUE TITLE
Detect if the app is in the background mode

### ISSUE THREAD

**Issue by shuuha** [wix/Detox#3656]
### Description

Hello.

I would like to detect if the app is in the background. So our app is opening  an external web url with the Linking, and we are not able to find a testable solution with Detox. While the url is open, calling methods like `element.isVisible(), element.exists()` does not help, Detox is analyzing the view hierarchy of the app even though it is in the background.
Is there anyway we could test such scenarios with Detox?
Would greatly appreciate any help. 

### Your environment

Detox version:  19.12.4
React Native version: 0.70.1 
Node version: 14.2
Device model: iPhone 11 simulator
OS: MacOS Monterey
Test-runner (select one): jest-circus

**Comment by adomanich** [comment]
Hello, 

I bumped into that a while ago, after some investigation I found only that Detox can't interact with anything outside of the app itself.

I suggest just using **traits** in that case and verifying that the element is a link.

`await waitFor(element(by.traits(['link']).and(by.id($ID))))).toBeVisible().withTimeout($TIMEOUT)`

**Comment by shuuha** [comment]
Thank you for your answer. So there is no way to know if the app is gone background after the link was activated?

**Comment by noomorph** [comment]
@d4vidi do we have a simple app like "isAppInBackground()" ?
