### ISSUE TITLE
"before all hook Timeout" (RN 0.45.1, XCode 9.0.1, Detox 5.9.2)

### ISSUE THREAD

**Issue by kyledmellander** [wix/detox#366]
#### Description
When running detox build/test the build works but the test seems to open the app, quickly close the app, then eventually times out during the before all and after all hooks.

#### Steps to Reproduce
I don't know how to reproduce the issue, other than following the getting started commands with a similar version of React Native, XCode and Detox. I've seen some similar issues tied to packages like firebase, but this app doesn't use firebase as a dependency. I'm unclear as to what version of Detox that would work with Xcode 9 and with React Native 0.45, but I'm struggling to find a version that works for me.

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 5.9.2
* Node: 8.1.2
* Device: IOS Simulator (iPhone 8, 9, 10, X)
* Xcode: 9.0.1
* macOS: Sierra: 10.12.6 (Sierra)
* React Native 0.45.1

#### Device and Detox logs
detox info 15:28:19: server listening on localhost:65352...
detox info 1: Searching for device matching iPhone 8... 
detox info 3: Uninstalling org.reactjs.native.example.mobileTech... 
detox info 3: org.reactjs.native.example.mobileTech uninstalled 
detox info 4: Installing /Users/kmellander/Projects/mobileTech/ios/build/Build/Products/Release-iphonesimulator/mobileTech.app... 
detox info 4: /Users/kmellander/Projects/mobileTech/ios/build/Build/Products/Release-iphonesimulator/mobileTech.app installed 
detox info 5: Terminating org.reactjs.native.example.mobileTech... 
detox info 5: org.reactjs.native.example.mobileTech terminated 
detox info 6: Launching org.reactjs.native.example.mobileTech... 
detox info 6: org.reactjs.native.example.mobileTech launched. The stdout and stderr logs were recreated, you can watch them with:
        tail -F $HOME/Library/Developer/CoreSimulator/Devices/F9732E28-49F9-4199-84EB-7EFCC0F6096C/data/tmp/detox.last_launch_app_log.{out,err} 
  1) "before all" hook

  0 passing (3m)
  1 failing

  1) "before all" hook:
     Error: Timeout of 180000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  

The error from the stdout logs send out this ...

2017-10-24 14:05:01.266 mobileTech[21768:262542] Crash handler setup started.
2017-10-24 14:05:01.266 mobileTech[21768:262542] Crash handler setup completed.
2017-10-24 14:05:01.266 mobileTech[21768:262542] Enabling accessibility for automation on Simulator.
2017-10-24 14:05:01.570 mobileTech[21768:262542] ☣️ DETOX:: Detox Action Sent: login
2017-10-24 14:05:01.691 mobileTech[21768:262542] ☣️ DETOX:: Detox Action Received: loginSuccess
2017-10-24 14:05:01.740 [info][tid:main][RCTCxxBridge.mm:184] Initializing <RCTCxxBridge: 0x6000001d1d00> (parent: <RCTBridge: 0x6000000bcb60>, executor: (null))
2017-10-24 14:05:01.756 [warn][tid:main][RCTBridge.m:114] Class RCTCxxModule was not exported. Did you forget to use RCT_EXPORT_MODULE()?
libc++abi.dylib: terminating with unexpected exception of type std::__1::bad_function_call: std::exception
Signal caught: Abort trap: 6
0   EarlGrey                            0x00000001259b6979 grey_signalHandler + 249
1   libsystem_platform.dylib            0x0000000116858b3a _sigtramp + 26
2   ???                                 0x000000010f1e66d8 0x0 + 4548617944
3   libsystem_c.dylib                   0x00000001164f6107 abort + 127
4   libc++abi.dylib                     0x000000011629091f __cxa_bad_cast + 0
5   libc++abi.dylib                     0x0000000116290aa3 _ZL25default_terminate_handlerv + 241

#### Detox in package.json
	"detox": {
		"configurations": {
			"ios.sim.debug": {
				"binaryPath": "ios/build/Build/Products/Release-iphonesimulator/mobileTech.app",
				"build": "xcodebuild -project ios/mobileTech.xcodeproj -scheme mobileTech -configuration Release -sdk iphonesimulator -derivedDataPath ios/build",
				"type": "ios.simulator",
				"name": "iPhone 8"
			}
		}
	}

**Comment by LeoNatan** [comment]
Upgrade you RN to latest version (0.49+) or use an older version of Detox.
