### ISSUE TITLE
WaitFor is missing the swipe action on Android

### ISSUE THREAD

**Issue by jonathanmos** [wix/Detox#3662]
### What happened?

waitFor is missing the swipe action (probably WaitForActionInteraction), and as a result calls to swipe within waitFor return errors similar to

`TypeError: waitFor(...)....swipe is not a function`

for example:

```
await waitFor(element(by.text('sometext'))).toBeVisible().whileElement(by.id('ScrollView')).swipe('down');
```

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 
React Native version: 
Node version: 
Device model: 
Android version: 
Test-runner (select one): jest-circus / jest+jasmine / mocha / other

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by andranikm97** [comment]
Seeing the same issue in our case, why has this issue been closed?

**Comment by d4vidi** [comment]
@andranikm97 It's actually open 🤷🏻

**Comment by andranikm97** [comment]
My fault, overlooked. Any resolution for this? We are using a `FlatList` component with a test id that we are trying to swipe on. The usual `scroll('bottom')` functionality does not work, so we opt-out for `swipe('up')`. BUT, the problem is that swiping cannot be chained to a `waitFor` statement. Is there any workaround for this?

**Comment by d4vidi** [comment]
@andranikm97 how come scroll() doesn't work for you?
