### ISSUE TITLE
Possible issues with iOS 16.1

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#3681]
### What happened?

todo @asafkorem 

https://github.com/wix/Detox/pull/3609#issuecomment-1309260744

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 
React Native version: 
Node version: 
Device model: 
iOS version: 
macOS version: 
Xcode version: 
Test-runner (select one): jest-circus / jest+jasmine / mocha / other

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by asafkorem** [comment]
The error from this comment is just a general error from a regular non-Detox iOS native application. Also it's the same error we had before the fix.

Both Xcode 14.1 and iOS 16.1 appears to work fine for me, just tested with our entire suite.
