### ISSUE TITLE
Improve iOS React Native sync mechanism

### ISSUE THREAD

**Issue by talkol** [wix/detox#37]
EarlGrey on iOS synchronizes with async OS tasks such as network requests using objects that conform to `GREYIdlingResource`. These objects listen on a resource like the network stack and are polled by EarlGrey to say whether this resource is busy or not (`isIdleNow`).

Our current phase 1 sync mechanism has 2 new Idling Resources specific for React Native.

The current implementation uses heuristics (moving average of the time that takes a bridge command to travel the full cycle) and this isn't ideal.

We want to improve the sync mechanism, remove the heuristics and make it more robust.

**Comment by LeoNatan** [comment]
Implemented.
