### ISSUE TITLE
How do I produce coverage data with this tool?

### ISSUE THREAD

**Issue by chenop** [wix/Detox#3707]
### Description

Thanks for creating this library - very useful.
I cannot understand how should I invoke coverage.
Currently running test with detox:
`npx detox test --configuration ios.debug`

What should I do in order to create the coverage for the tests Im running?

### Your environment

Detox version: 19.7.1
React Native version: 0.68.0
Node version: 14.x
Device model: 
OS: 
Test-runner (select one): jest / other

**Comment by noomorph** [comment]
This is a very untrivial task. You'd need to add source code transformations with Istanbul to the [Metro bundler](https://github.com/facebook/metro) and then extract the test coverage from the inside (e.g., sending to a localhost server for aggregating LCOV reports).

This is technically possible but requires a skilled developer to hack a solution.

Maybe React Native has better solutions, e.g., using built-in V8 code coverage, but I'm unaware of such ones now.

**Comment by chenop** [comment]
Appreciate the quick response!

**Comment by mikehardy** [comment]
@chenop there are two types of possible coverage, native code or javascript code coverage

I don't know how to do native code coverage for iOS (I have tried, but could not get the coverage files to dump :shrug: ) but, for android, you can do this to get native code coverage dumped:

https://github.com/invertase/react-native-firebase/blob/baea413c0a81f75d99d947ba0607737853ad08f4/tests/android/app/src/androidTest/java/com/invertase/testing/DetoxTest.java#L32-L53

That's useful for module authors that develop native code and need to check things.

For javascript code coverage (most people), you need to [instrument](https://github.com/invertase/react-native-firebase/blob/main/tests/nyc.config.js) the bundle first in a pre-build step, then as the last part of your test, you need to have some logic that you trigger at the javascript level that persists the coverage data (which will be in global variable `globals.coverage` I think?) to a file on the android emulator file system

Then you may fetch the dumped javascript coverage data file by using `adb pull` command

There are an infinite number of ways to do it but the same three steps will always apply: 1- instrument the code prior to execution, 2- dump the coverage data post-execution 3- locate/transfer/process the dumped coverage data somehow

**Comment by d4vidi** [comment]
@chenop @mikehardy we'd appreciate a blogpost about it (if you manage to sort this out). 'Promise to promote on our twitter account!
