### ISSUE TITLE
[APP_STATUS] The app is busy with the following tasks

### ISSUE THREAD

**Issue by bondPiyapan** [wix/Detox#3712]
### Description

I'm use test by react-native expo.

After login with firebase_auth with a phone number must click the button apply, wait for a long time, then a message appears.

My script test: 
```js
it('test', async () => {
  await waitFor(element(by.text("APPLY")))
    .toBeVisible()
    .withTimeout(5000);
  await element(by.text('APPLY')).tap()
})
```

Message:
```
[APP_STATUS] The app is busy with the following tasks:
• 1 enqueued native timers:
  - Timer # 1:
    + Fire date: none.
    + Time until fire: 0.000.
    + Repeat interval: 0.
    + Is recurring: YES.
• Run loop "Main Run Loop" is awake.
• There are 1 work items pending on the dispatch queue: "Main Queue (<OS_dispatch_queue_main: com.apple.main-thread>)".
```

Thank you.

### Your environment

Detox version: 19.9.2
React Native version:  0.64.3
Expo: 44
Node version:  16.14.1
Device model: Simulator iPhone 12
OS: IOS
Test-runner (select one): jest

**Comment by caiorrsdeg** [comment]
I'm having the same issue over here

**Comment by d4vidi** [comment]
I suggested reading [our guide on Detox synchronization](https://wix.github.io/Detox/docs/troubleshooting/synchronization).
These are mere indicators of that your app is being kept busy and therefore Detox cannot continue to performance the test operation.

Side-note, @bondPiyapan: There's no need to use `waitFor` with a timeout in this case. The `tap()` checks for visibility, and timeout usage in unnecessary in Detox's gray-box approach.

**Comment by dooleyb1** [comment]
@teogomes @caiorrsdeg @bondPiyapan - Did you ever get a resolution / workaround for this?

**Comment by MetodievIvaylo** [comment]
I have the same problem. Is there any solution?

**Comment by MetodievIvaylo** [comment]
My app has been waiting for cursor blinking animation to end until the test just timeout. Here is how I handle it:

```
await device.disableSynchronization()
await testFunction()
await device.enableSynchronization()
```
