### ISSUE TITLE
Unable to run example react native app

### ISSUE THREAD

**Issue by caiorrsdeg** [wix/Detox#3714]
### What happened?

I'm trying to implement Detox on my apps, then I started by cloning detox repo to run the example react native app and see if that works.

I'm able to build the android release, but when I try to run the tests I'm getting:

```
ChildProcessError: `/Users/myuser/Library/Android/sdk/platform-tools/adb -s emulator-16384 shell pm install -r -g -t /data/local/tmp/detox/Application.apk` failed with code 1
```

### What was the expected behaviour?

I was expecting to be able to run the tests flawlessly

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 20.0.3
React Native version: 0.69.7 
Node version: v16.17.0
Device model: Pixel_2_API_31 (Emulator with playstore)
Android version: 12
Test-runner (select one): jest

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by noomorph** [comment]
Oh, our example apps need some refinement in this context.
If you don't have much time, maybe try creating an empty RN app:
https://reactnative.dev/docs/environment-setup

and follow our guides:

https://wix.github.io/Detox/docs/introduction/getting-started
https://wix.github.io/Detox/docs/introduction/project-setup
https://wix.github.io/Detox/docs/introduction/your-first-test

Also, you might try your luck with this project (git checkout `with-tests` branch):
https://github.com/evgeniyaglovatskaya/detox-workshop

It used to work a couple of months ago on my machine, maybe it's less problematic to set up.

---

Last but not least, if you have time to contribute, please run Detox like that:

```
detox test ...your args... --record-logs all
```

And share the `artifacts` folder contents with us.
