### ISSUE TITLE
[Detox 20] (WIP) Finish Logger review

### ISSUE THREAD

**Issue by noomorph** [wix/Detox#3716]
### Describe your idea

See #3749 which finishes the logger review.

**Comment by d4vidi** [comment]
@noomorph reminder 😄 What should the actual task look like?

**Comment by noomorph** [comment]
It is about this code review and your comments on it:

https://github.com/wix/Detox/pull/3694

**Comment by d4vidi** [comment]
> It is about this code review and your comments on it:
> 
> #3694

OK I see now that's both about #3694 _and_ #3749. My task here is to review the latter, then.
