### ISSUE TITLE
Detox + GenyMotion tests hang on hitting mockserver endpoint with reversePort configured

### ISSUE THREAD

**Issue by jkelley79** [wix/Detox#3717]
### What happened?

Detox version 20.0.3
Using Genymotion cloud as my device

Running the tests on a local emulator work fine
Running the tests against Genymotion cloud device - they hang when the first network request to the mock server is made

The mock server running within the Detox tests is not recording any request being received where it works fine within the local emulator tests

### What was the expected behaviour?

Expected the tests to function the same using Genymotion vs local emulator

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

Below is my configuration 

The RN_SRC_EXT=e2e.ts used within the build command indicates to the metro packager to swap out server.config.ts with server.config.e2e.ts where we swap out the production URL to the localhost URL http://10.0.2.2:9091

In the beforeAll of our test file we call a method `startMockServer` which launches a Node express server on port 9091 and listens for requests that match our production URL endpoints

```
{
  "testRunner": {
    "$0": "jest",
    "args": {
      "config": "e2e/config.js",
        "_": ["e2e"]
    }
  },
  "apps": {
    "android.release": {
      "type": "android.apk",
      "binaryPath": "android/app/build/outputs/apk/release/app-release.apk",
      "build": "cd android && RN_SRC_EXT=e2e.ts ./gradlew assembleRelease assembleAndroidTest -DtestBuildType=release && cd ..",
      "reversePorts": [9091]
    }
  },
  "devices": {
    "genycloud": {
      "type": "android.genycloud",
      "device": {
        "recipeUUID": "cbdef2d8-a7e3-470d-a7d5-b5965b3567c5"
      }
    }
  },
  "configurations": {
    "android.genycloud.release": {
      "device": "genycloud",
      "app": "android.release"
    }
  }
}
```

### In what environment did this happen?

Detox version: 20.0.3
React Native version:  0.64.4
Node version: 14.17
Device model: Standard Google Pixel 3 
Android version: Android 11
Test-runner (select one): jest 

### Detox logs

<details><summary>Detox logs</summary>

```
```

</details>

[tracelogs.log](https://github.com/wix/Detox/files/10042921/tracelogs.log)

### Device logs

<details><summary>Device logs</summary>

```
```

</details>

### More data, please!

<img width="552" alt="Screen Shot 2022-11-18 at 7 46 03 AM" src="https://user-images.githubusercontent.com/5752368/202751649-83a5c586-2aab-4071-8cfc-9dd31dcbd683.png">

**Comment by noomorph** [comment]
Don't use 10.0.2.2, use localhost URL. The former way does not work on
Genymotion cloud devices, only on local emulators.

пт, 18 лист. 2022 р. о 18:19 Jon Kelley ***@***.***> пише:

**Comment by jkelley79** [comment]
That works. Thanks!
