### ISSUE TITLE
Does detox support native+ReactNative? 

### ISSUE THREAD

**Issue by jjzzzzjj** [wix/Detox#3723]
### Description

I have an app which is developed by android native + ReactNative，There is a case which entrance page is a native page（MainActivity），landing page is a ReactNative page（RNActivity），I want to test RNActivity with detox，is it support?  If
ye, but i encountered an error “com.wix.detox.common.DetoxErrors$DetoxRuntimeException: Waited for the new RN-context for too long! (180 seconds)”

MainActivity：
`public class MainActivity extends AppCompatActivity {

  @Override
  protected void onCreate(@Nullable Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);
    findViewById(R.id.click_to_jump).setOnClickListener(new View.OnClickListener() {
      @Override
      public void onClick(View v) {
        Intent intent = new Intent(MainActivity.this, RNActivity.class);
        startActivity(intent);
      }
    });
  }
}`

RNActivity：
public class RNActivity extends ReactActivity {
 @Override
 protected String getMainComponentName() {
   return "example";
 }
}

autoui.nativeexample.test.js：
`describe('Example2', function () {
beforeAll(async () => {
      await device.launchApp();
  });

  it('should have welcome screen', async () => {
    await expect(element(by.text('click_to_jump'))).toBeVisible();
    await element(by.text('click_to_jump')).tap();
  });

});`

DetoxTest：
@RunWith(AndroidJUnit4.class)
@LargeTest
public class DetoxTest {
    @Rule
    public ActivityTestRule<MainActivity> mActivityRule = new ActivityTestRule<>(MainActivity.class, false, false);
    @Test
    public void runDetoxTests() {
        DetoxConfig detoxConfig = new DetoxConfig();
        detoxConfig.idlePolicyConfig.masterTimeoutSec = 90;
        detoxConfig.idlePolicyConfig.idleResourceTimeoutSec = 60;
        detoxConfig.rnContextLoadTimeoutSec = (180);
        Detox.runTests(mActivityRule, detoxConfig);
    }
}

what i want to test is when i launch app, then press 'click_to_jump' button and it should jump to RNActivity，but now i recevied a error ' Waited for the new RN-context for too long! (180 seconds)' and after app launched, MainActivity cannot jump to RNActivity,  can anyone help me? 

### Your environment

Detox version: 20.0.0
React Native version: 0.63.0
Node version: 16.14.2
Device model: Pixel
OS: android
Test-runner (select one): jest / other:jest

**Comment by d4vidi** [comment]
Sadly no, that's currently broken. There is a way to get that fixed, if you're interested in contributing to the project. Please let us know!
