### ISSUE TITLE
Firebase Dynamic Links are Null

### ISSUE THREAD

**Issue by hkaras19** [wix/Detox#3726]
### What happened?

I am building an app that relies quite heavily on firebase dynamic links. As a result, I want to use detox to test the behavior of opening dynamic links in the app. However, the result of `dynamicLinks().getInitialLink()` is always null. I am using 'short links' that were built using the iOS simulator previously and attempting to load them during a test.

Note: I am using @react-native-firebase/dynamic-links

Test example:

`
await device.launchApp({
	url: MY_LINK,
	newInstance: true
})
`

### What was the expected behaviour?

The app should receive the link through `dynamicLinks().getInitialLink()`

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

```json
{
	"dependencies": {
		"@expo/vector-icons": "^13.0.0",
		"@react-native-community/picker": "^1.8.1",
		"@react-native-firebase/analytics": "^16.4.3",
		"@react-native-firebase/app": "^16.4.3",
		"@react-native-firebase/auth": "^16.4.3",
		"@react-native-firebase/crashlytics": "^16.4.3",
		"@react-native-firebase/dynamic-links": "^16.4.3",
		"@react-native-firebase/firestore": "^16.4.3",
		"@react-native-firebase/remote-config": "^16.4.3",
		"@react-navigation/drawer": "^6.5.0",
		"@react-navigation/elements": "^1.3.6",
		"@react-navigation/native": "^6.0.13",
		"@react-navigation/stack": "^6.3.4",
		"@testing-library/react-native": "^11.4.0",
		"dotenv": "^16.0.3",
		"expo": "~47.0.3",
		"expo-constants": "^14.0.2",
		"expo-splash-screen": "~0.17.4",
		"expo-status-bar": "~1.4.2",
		"firestore-jest-mock": "^0.19.0",
		"react": "18.1.0",
		"react-native": "0.70.5",
		"react-native-gesture-handler": "^2.8.0",
		"react-native-reanimated": "^2.12.0",
		"react-native-safe-area-context": "^4.4.1",
		"recoil": "^0.7.6"
	},
	"devDependencies": {
		"@babel/core": "^7.12.9",
		"@testing-library/jest-dom": "^5.16.5",
		"@wojtekmaj/enzyme-adapter-react-17": "^0.8.0",
		"detox": "^20.0.3",
		"jest": "^29.3.1",
		"jest-environment-jsdom": "^29.3.1",
		"jest-expo": "^47.0.1",
		"node-fetch": "2",
		"react-dom": "^18.2.0",
		"react-native-fs": "^2.20.0",
		"react-test-renderer": "^18.2.0"
	},
}
```

### More data, please!

e2e/jest.config.js
```
/** @type {import('@jest/types').Config.InitialOptions} */

module.exports = {
	rootDir: '..',
	testMatch: ['<rootDir>/e2e/**/*.test.js'],
	testTimeout: 120000,
	maxWorkers: 1,
	globalSetup: 'detox/runners/jest/globalSetup',
	globalTeardown: 'detox/runners/jest/globalTeardown',
	reporters: ['detox/runners/jest/reporter'],
	testEnvironment: 'detox/runners/jest/testEnvironment',
	verbose: true,
	setupFilesAfterEnv: [
		'<rootDir>/setupTests.js'
	],
	globals: {
		'__DEV__': true
	},
	preset: 'jest-expo',
	transformIgnorePatterns: [
		'node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg)'
	],
	'moduleDirectories': [
		'node_modules',
		'src'
	]
}
```

jest.config.json

```json
{
  "preset": "jest-expo",
  "transformIgnorePatterns": [
    "node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg)"
  ],
  "setupFilesAfterEnv": [
    "<rootDir>/setupTests.js"
  ],
  "testEnvironment": "node",
  "testRegex": "/*.test.js$",
  "collectCoverage": true,
  "coverageReporters": [
    "lcov"
  ],
  "coverageDirectory": "test-coverage",
  "coverageThreshold": {
    "global": {
      "branches": 0,
      "functions": 0,
      "lines": 0,
      "statements": 0
    }
  },
  "moduleDirectories": [
    "node_modules",
    "src"
  ]
}

**Comment by hkaras19** [comment]
update: calling `await Linking.getInitialURL()` gets the correct url (react natives deep link method). This leads me to believe that there is an issue running the firebase dynamic link methods while testing.

**Comment by asafkorem** [comment]
I found their test for `dynamicLinks().getInitialLink()`, may help as a reference:
https://github.com/invertase/react-native-firebase/blob/cafe9b06fbc7ba18007980c20111fe211041701a/packages/dynamic-links/e2e/dynamicLinks.e2e.js#L174

**Comment by asafkorem** [comment]
@hkaras19 any update on this? did you checked their repo?

**Comment by hkaras19** [comment]
@asafkorem thanks for the info and sorry for the late reply. I ended up using my Linking approach as I was able to get it working and didn't want to waste time. If I run into issues in the future, I may look back into your suggestions.
