### ISSUE TITLE
build failed with react-native-config

### ISSUE THREAD

**Issue by rudenick0309** [wix/Detox#3727]
### Description

when i ran 'detox build --configuration ios.sim.debug', the error occured.
for solve this, i upgraded react-native-config@1.4.11. but i still faced the error.

```
** BUILD FAILED **


The following build commands failed:
        Run custom shell script 'Run Script'
        PhaseScriptExecution [CP-User]\ Config\ codegen /Users/juho/code/app-front-dev/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-config.build/Script-9B13264B7B32F31586B7B4625C3E1C7A.sh (in target 'react-native-config' from project 'Pods')
(2 failures)
```

my packages:
    "detox": "^20.0.3",
    "jest": "^29",
    "react-native": "0.66.5",
    "react-native-config": "1.4.11",

System:
    OS: macOS 11.6.2
    CPU: (8) x64 Apple M1
    Memory: 49.50 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: 2022.10.17.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 23, 27, 28, 29, 30, 31, 32, 33
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Intel x86 Atom_64, android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a, android-TiramisuPrivacySandbox | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.5 => 0.66.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Your environment

Detox version: "^20.0.3",
React Native version: 0.66.5 
Node version: v16.16.0
Device model: iphone 12
OS: m1 pro
Test-runner (select one): jest

**Comment by noomorph** [comment]
Are you able to start app with React Native scripts?

**Comment by rudenick0309** [comment]
@noomorph yes, of course, the error occur when i run only detox build

**Comment by asafkorem** [comment]
What nvm version are you using? 
Upgrading nvm version may help here, but that's just a guess. Please try nvm 16 if you're using something lower.

1. `nvm install 16`
2. `nvm use 16`
3. `nvm unalias default`
4. `nvm alias default node`
