### ISSUE TITLE
element(by.id('textField')).typeText('passcode') find element but does not start typing

### ISSUE THREAD

**Issue by daankennes** [wix/Detox#3729]
### What happened?

This is a RN username input:
![image](https://user-images.githubusercontent.com/32707088/203562168-f850566d-c0dc-46f1-8b6f-8132ba8ee00b.png)

I write a test for this input field using `await element(by.id('BasicLoginScreenUsername')).typeText('default');`.
![image](https://user-images.githubusercontent.com/32707088/203562788-f0218404-0563-4e69-a830-0c5a3a56affd.png)

Then I run this using `detox build --configuration android.emu.debug` and next `detox test --configuration android.emu.debug --reuse`.

The test runs without errors. The input field is found and I can see Detox trying to focus the input field. However, when it starts typing, it seems to execute a long press on the input field causing it to display the autofill message. No text gets typed eventually. Programmatically tapping the button has the same problem: I notice the button being pressed but nothing happens. This is probably a long press instead of a short one.
![image](https://user-images.githubusercontent.com/32707088/203564097-ee421011-dfef-4a13-b0d0-ce2bbfadcc09.png)

I also tried running it on an attached device, but got the 'No instrumentation runner found on device a24723e4 for package xxx' error.

### What was the expected behaviour?

Text gets typed and button gets pressed instead of a long press on the input field and button.

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version:  20.0.3
React Native version: 0.68.5
Node version: 16.14.0
Device model: Pixel emulator
Android version: 13
Test-runner (select one): jest

### Detox logs

<details><summary>Detox logs</summary>

```
npm WARN invalid config loglevel="trace" set in command line options
npm WARN invalid config Must be one of: silent, error, warn, notice, http, timing, info, verbose, silly

> xxxxxxxx detox-test
> detox test --configuration android.emu.debug --reuse

14:57:42.540 detox[39688] B jest --config e2e/jest.config.jsd in 2ms
14:57:45.102 detox[20660] i starter.test.js is assigned to emulator-13450 (Pixel_3a_API_33_x86_64)
14:57:55.194 detox[20660] i Example: should have login screen in 2ms
14:57:55.259 detox[20660] i Example: should have login screen [OK]
14:57:55.261 detox[20660] i Example: should login with username and password
14:57:57.525 detox[20660] i Example: should login with username and password [FAIL]

 FAIL  e2e/starter.test.js (13.96 s)
  Example
    √ should have login screen (65 ms)
    × should login with username and password (2263 ms)

  ● Example › should login with username and password

    Test Failed: '(view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() covers at least <75> percent of the view's area)' doesn't match the selected view.
    Expected: (view has effective visibility <VISIBLE> and view.getGlobalVisibleRect() covers at least <75> percent of the view's area)
         Got: was null

      21 |         await element(by.id('BasicLoginScreenSignInButton')).tap();
      22 |
    > 23 |         await expect(element(by.text('Session settings'))).toBeVisible();
         |                                                            ^
      24 |     });
      25 |
      26 |     /*it('should show world screen after tap', async () => {

      at createErrorWithUserStack (node_modules/detox/src/utils/errorUtils.js:36:27)
      at Client._doSendAction (node_modules/detox/src/client/Client.js:164:32)
      at Client._sendMonitoredAction (node_modules/detox/src/client/Client.js:157:25)
      at Client.sendAction (node_modules/detox/src/client/Client.js:143:14)
      at Client.execute (node_modules/detox/src/client/Client.js:132:25)
      at InvocationManager.execute (node_modules/detox/src/invoke.js:12:39)
      at MatcherAssertionInteraction.execute (node_modules/detox/src/android/interactions/native.js:23:31)
      at NativeExpectElement.toBeVisible (node_modules/detox/src/android/core/NativeExpect.js:25:137)
      at Object.toBeVisible (e2e/starter.test.js:23:60)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)

14:57:57.674 detox[39688] E Command failed with exit code = 1:in 2ms
jest --config e2e/jest.config.js

```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by d4vidi** [comment]
Please try to avoid using `--reuse` and also remove the preliminary `.tap()` you have before each `.typeText()`.

**Comment by krunal3kapadiya** [comment]
Hi @daankennes 

Is this issue is resolved?
