### ISSUE TITLE
Detox v20 breaks Cucumber tests integration

### ISSUE THREAD

**Issue by jpoisch** [wix/Detox#3730]
### Description

**Background:** 
Hi guys! We are still relatively new to Detox, and I will try to explain our situation as much as I can. So please let me know if you need any additional details.

We are using Detox v19 currently with a Cucumber 8.4.0 setup as the test runner. We execute `cucumber.js` to kick off our test suite, and initiate `detox.init` as part of from Cucumber function `beforeAll`.

Here is an example of how it looks like in e2e/features/support/init.ts:
<img width="632" alt="2022-11-23_11-57-49" src="https://user-images.githubusercontent.com/51448684/203606176-2e5e66a0-f6a7-408b-9c59-abe23f936550.png">

Command to run the test:
`DETOX_CONFIGURATION=android:30:release:produs DETOX_RECORD_VIDEOS=failing node_modules/.bin/cucumber-js $1 --tags "$test" --require-module ts-node/register --require 'e2e/features/**/*.ts'`

**Issue:**
Since `detox.init` no longer exists in v20, it is no longer able to initiate detoxConfig and launch an emulators / simulators.

Here is what the adapter.js looks like:
<img width="622" alt="2022-11-23_12-00-03" src="https://user-images.githubusercontent.com/51448684/203606443-c868eda7-2963-43ca-b43f-ca857031b5b4.png">

And detox.config.js: 
<img width="1201" alt="2022-11-23_12-14-30" src="https://user-images.githubusercontent.com/51448684/203608603-f2dd12e2-c639-4fa7-bc0d-073fe43f22a5.png">

Is there any new way to initiate Detox as part of init.ts?

### Your environment

Detox version: 19.13.0
React Native version: 0.69.6
Node version: 16.13.0
Device model: All simulators / emulators
OS: Android & iOS
Test-runner (select one): Cucumber

**Comment by d4vidi** [comment]
Hey @jpoisch,

Thanks for this report!
[Detox v20](https://wix.github.io/Detox/docs/guide/migration/#200) has indeed came about with numerous breaking changes. We've actually changed mindset such that for these type of cases, it would be easier to integrate Detox by publicly introducing some [internal API's](https://wix.github.io/Detox/docs/api/internals/). Please try to require it from `detox/internal' and read about it in our documents.

**Comment by pacozaa** [comment]
@d4vidi Do you have code example? Or possible more details answer?

@jpoisch Any update from your side? How did you solve this problem?

**Comment by d4vidi** [comment]
I was mainly suggesting that `cleanup` and `init` should not be imported from `detox`, in Detox v20. Try to dive into the [internal API's](https://wix.github.io/Detox/docs/api/internals/#initoptions-promise), instead.

**Comment by noomorph** [comment]
@pacozaa this is the most simplistic way to use the Internals API: [see the file](https://github.com/wix/Detox/blob/9d1abe2d0a5d07044ceed4e02b527cf756596092/detox/test/integration/utils/simplistic-runner.js). I hope that helps.

**Comment by pacozaa** [comment]
@d4vidi @noomorph Thank you! This is cool.

**Comment by noomorph** [comment]
@pacozaa as for your trace file provided for #3850, I think the problem about artifacts is related to the fact you don't use the optional lifecycle: https://wix.github.io/Detox/docs/next/api/internals#optional-lifecycle . Make use of `onTestStart` and `onTestDone` at the very least, and you'll see artifacts appearing. Ideally, you should strive to implement all those calls in the optional lifecycle.

**Comment by pacozaa** [comment]
@noomorph  Wow Thank you. I didn't mean to lie haha. Looks like we are going into the right direction. Right now, I can access the `onTestStart` from `detox/internals` which is great. Do you have maybe a short snippet or example on how to implement it?

**Comment by noomorph** [comment]
> I didn't mean to lie haha. 

Take it easy. :) And make sure it to share your work with the community. I'm enthusiastic to see external integrations with other test runners.

@pacozaa, I don't have something specific as examples, here's how we use it here for Jest:

https://github.com/wix/Detox/blob/master/detox/runners/jest/testEnvironment/listeners/DetoxCoreListener.js#L117

The docs contain sample payloads for these function calls too, please pay attention:

<img width="521" alt="image" src="https://user-images.githubusercontent.com/1962469/213177885-c9150772-74b7-4f19-b229-d3193ec4e0fc.png">

**Comment by pacozaa** [comment]
so to conclude and answer the OP question

1. Replace `import detox from 'detox'` with `import detox from 'detox/internals'` then we can use for example `await detox.init()` in cucumber `BeforeAll` and `Before` function callback
2. For screenshot and video, you can place
```javascript
 await detox.onTestStart({
     title: 'test',
     fullName: 'test',
     status: 'running',
 })
```
Right after 
`await detox.init()`

Here is what your cucumber `init` file might looks like

```javascript
import { BeforeAll, AfterAll } from '@cucumber/cucumber'
import detox from 'detox/internals'

BeforeAll({ timeout: 120 * 1000 }, async () => {

    await detox.init()
    await detox.onTestStart({
        title: 'test',
        fullName: 'test',
        status: 'running',
    })
    await device.launchApp()

})

AfterAll(async () => {
    await detox.onTestDone({
        title: 'test',
        fullName: 'test',
        status: 'failed',
    })
    await detox.cleanup()
})
```

**Comment by pacozaa** [comment]
Good catch. Will show you when it's more complete.

**Comment by pacozaa** [comment]
The improved version to catch the real status would look like this(Please read the documentation here [Cucumber-JS API Reference](https://github.com/cucumber/cucumber-js/blob/main/docs/support_files/api_reference.md#afteroptions-fn))

```javascript
import { Before, BeforeAll, AfterAll, After,  ITestCaseHookParameter } from '@cucumber/cucumber'
import detox from 'detox/internals'

BeforeAll({ timeout: 120 * 1000 }, async () => {
    await detox.init()
    await device.launchApp()
})

Before(async (message: ITestCaseHookParameter) => {
    const { pickle } = message
    await detox.onTestStart({
        title: pickle.uri,
        fullName: pickle.name,
        status: 'running',
    })
})
After(async (message: ITestCaseHookParameter) => {
    const { pickle, result } = message
    await detox.onTestDone({
        title: pickle.uri,
        fullName: pickle.name,
        status: result ? 'passed' : 'failed',
    })
})

AfterAll(async () => {    
    await detox.cleanup()
})
```

Please let me know if you have any questions. I am happy to help. @noomorph

**Comment by noomorph** [comment]
Hmm, looks legit at first glance. @jpoisch WDYT?

**Comment by pacozaa** [comment]
@noomorph Should I put cucumber-js integration guide in [docs/guide](https://github.com/wix/Detox/tree/master/docs/guide)?

**Comment by jpoisch** [comment]
> Hmm, looks legit at first glance. @jpoisch WDYT?

@noomorph @pacozaa As an example, this looks great. I think everyone will obviously have their own unique setup for the `Before` and `After`, but in general this would put people on the right track 👍

**Comment by noomorph** [comment]
@pacozaa , yes, you could try writing a tutorial for that. After a couple of reiterations, we could merge it to the docs as a part of community tutorials.

**Comment by pacozaa** [comment]
https://github.com/wix/Detox/pull/3858 @noomorph here we go. Let's see how it goes.

**Comment by noomorph** [comment]
https://wix.github.io/Detox/docs/guide/cucumber-js-integration/
