### ISSUE TITLE
Detox setup help

### ISSUE THREAD

**Issue by dcardosoweb** [wix/Detox#3739]
### What happened?

In the company I work for, we are trying to use Detox, but without success. After we apply all the necessary changes indicated in the official documentation, when we run the test the emulator is initialized, as defined in detoxrc.json. But a failure occurs and we cannot identify the reason

![image](https://user-images.githubusercontent.com/615090/204369661-019ee2f1-b225-46fd-9d18-319b6be03a34.png)

According to logcat, the problem is related to the device_id, so we cannot identify what is missing from the configuration in this case.

![image](https://user-images.githubusercontent.com/615090/204369849-6ad6ba2e-b22c-4289-ac18-1a7c383979ba.png)

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version:  20X
React Native version: "0.70.5"
Node version:  "2.6.7"
Device model:  Pixel XL (Emulator)
Android version:  SDK 33
Test-runner (select one):  other

### Detox logs

<details><summary>Detox logs</summary>

PS D:\Projetos\Payface\Hibrid app payface-app-store-client\android> yarn e2e:test --loglevel trace
yarn run v1.22.19
$ detox test --loglevel trace
16:47:44.268 detox[14980] INFO:  [test.js] DETOX_LOGLEVEL="trace" DETOX_REPORT_SPECS=true DETOX_START_TIMESTAMP=1669664864259 DETOX_USE_CUSTOM_LOGGER=true jest --config e2e/config.json --testNamePattern "^((?!:ios:).)*$" e2e
16:47:49.719 detox[5068] TRACE: [DETOX_CREATE] created a Detox instance with config:                                                   
{                                                                                                                                      
  appsConfig: {                                                                                                                        
    default: {                                                                                                                         
      type: 'android.apk',                                                                                                             
      binaryPath: 'android/app/build/outputs/apk/reactNative/staging/app-reactNative-staging.apk',                                     
      build: 'cd android && .\\gradlew assembleReactNativeStaging assembleReactNativeStagingAndroidTest -DtestBuildType=debug && cd ..'
    }                                                                                                                                  
  },                                                                                                                                   
  artifactsConfig: {
    rootDir: 'artifacts\\android.2022-11-28 19-47-44Z',
    plugins: {
      log: {
        enabled: false,
        keepOnlyFailedTestsArtifacts: false
      },
      screenshot: {
        enabled: true,
        shouldTakeAutomaticSnapshots: false,
        keepOnlyFailedTestsArtifacts: false
      },
      video: {
        enabled: false,
        keepOnlyFailedTestsArtifacts: false
      },
      instruments: {
        enabled: false,
        keepOnlyFailedTestsArtifacts: false
      },
      timeline: {
        enabled: false
      },
      uiHierarchy: {
        enabled: false,
        keepOnlyFailedTestsArtifacts: false
      }
    },
    pathBuilder: ArtifactPathBuilder {
      _rootDir: 'artifacts\\android.2022-11-28 19-47-44Z'
    }
  },
  behaviorConfig: {
    init: {
      reinstallApp: true,
      exposeGlobals: true
    },
    cleanup: {
      shutdownDevice: false
    },
    launchApp: 'auto'
  },
  cliConfig: {
    loglevel: 'trace',
    useCustomLogger: true
  },
  configurationName: 'android',
  deviceConfig: {
    type: 'android.emulator',
    device: {
      avdName: 'Pixel_3a_API_33'
    }
  },
  runnerConfig: {
    testRunner: 'jest',
    runnerConfig: 'e2e/config.json',
    specs: 'e2e',
    skipLegacyWorkersInjection: true
  },
  sessionConfig: {
    autoStart: true,
    sessionId: '0db40334-cef0-de9b-cc1e-217b86b3b370',
    debugSynchronization: 10000
  }
}
16:47:49.727 detox[5068] DEBUG: [WSS_CREATE] Detox server listening on localhost:61478...
16:47:49.749 detox[5068] DEBUG: [WSS_CONNECTION, #61479] registered a new connection.
16:47:49.751 detox[5068] TRACE: [WS_OPEN] opened web socket to: ws://localhost:61478
16:47:49.754 detox[5068] TRACE: [WS_SEND] {"type":"login","params":{"sessionId":"0db40334-cef0-de9b-cc1e-217b86b3b370","role":"tester"},"messageId":0}
16:47:49.757 detox[5068] TRACE: [WSS_GET_FROM, #61479] {"type":"login","params":{"sessionId":"0db40334-cef0-de9b-cc1e-217b86b3b370","role":"tester"},"messageId":0}
16:47:49.758 detox[5068] TRACE: [SESSION_CREATED] created session 0db40334-cef0-de9b-cc1e-217b86b3b370
16:47:49.758 detox[5068] TRACE: [WSS_SEND_TO, #tester] {"type":"loginSuccess","params":{"testerConnected":true,"appConnected":false},"messageId":0}
16:47:49.759 detox[5068] TRACE: [SESSION_JOINED] tester joined session 0db40334-cef0-de9b-cc1e-217b86b3b370
16:47:49.760 detox[5068] TRACE: [WS_MESSAGE] {"type":"loginSuccess","params":{"testerConnected":true,"appConnected":false},"messageId":0}
 
16:47:50.187 detox[5068] DEBUG: [EXEC_CMD, #0] "C:\Users\dcard\AppData\Local\Android\Sdk\emulator\emulator.EXE" -list-avds --verbose
16:47:50.230 detox[5068] TRACE: [EXEC_SUCCESS, #0] Pixel_2_API_31                                                                   
Pixel_3a_API_33                                                  
Pixel_6_API_31                                                   

16:47:50.231 detox[5068] DEBUG: [EXEC_CMD, #1] "C:\Users\dcard\AppData\Local\Android\Sdk\emulator\emulator.EXE" -version 
16:47:50.693 detox[5068] TRACE: [EXEC_SUCCESS, #1] INFO    | Duplicate loglines will be removed, if you wish to see each indiviudal line launch with the -log-nofilter flag.
Android emulator version 31.3.13.0 (build_id 9189900) (CL:N/A)                                                                                                              
Copyright (C) 2006-2017 The Android Open Source Project and many others.                                                                                                    
This program is a derivative of the QEMU CPU emulator (www.qemu.org).

  This software is licensed under the terms of the GNU General Public
  License version 2, as published by the Free Software Foundation, and
  may be copied, distributed, and modified under those terms.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

INFO    | Android emulator version 31.3.13.0 (build_id 9189900) (CL:N/A)

16:47:50.695 detox[5068] DEBUG: [EMU_BIN_VERSION_DETECT] Detected emulator binary version { major: 31, minor: 3, patch: 13, toString: [Function: toString] }
16:47:50.696 detox[5068] DEBUG: [ALLOCATE_DEVICE] Trying to allocate a device based on "Pixel_3a_API_33"
16:47:50.699 detox[5068] DEBUG: [EXEC_CMD, #2] "C:\Users\dcard\AppData\Local\Android\Sdk\platform-tools\adb.EXE"  devices
16:47:50.749 detox[5068] DEBUG: [EXEC_SUCCESS, #2] List of devices attached

16:47:50.753 detox[5068] DEBUG: [ALLOCATE_DEVICE] Settled on emulator-11826
16:47:50.755 detox[5068] DEBUG: [SPAWN_CMD] C:\Users\dcard\AppData\Local\Android\Sdk\emulator\emulator.EXE -verbose -no-audio -no-boot-anim -port 11826 @Pixel_3a_API_33
16:52:49.685 detox[5068] ERROR: Exceeded timeout of 300000ms while handling jest-circus "setup" event
16:52:49.693 detox[5068] INFO:  Example is assigned to undefined
16:52:49.694 detox[5068] INFO:  Example: should show home and find text: Pagamento por reconhecimento facial
16:52:49.696 detox[5068] INFO:  Example: should show home and find text: Pagamento por reconhecimento facial [FAIL]

16:52:49.704 detox[5068] TRACE: [ARTIFACTS_LIFECYCLE] artifactsManager.onBeforeCleanup()
16:52:49.706 detox[5068] ERROR: Aborted detox.init() execution, and now running detox.cleanup()

HINT: Most likely, your test runner is tearing down the suite due to the timeout error
16:52:49.710 detox[5068] DEBUG: [WSS_CLOSE] Detox server has been closed gracefully
 FAIL  e2e/firstTest.e2e.js (301.016 s)
  ● Example › should show home and find text: Pagamento por reconhecimento facial

    Environment setup failed. See the detailed error below.

</details>

### Device logs

<details><summary>Device logs</summary>

PS D:\Projetos\Payface\Hibrid app payface-app-store-client\android> yarn e2e:test --record-logs all
yarn run v1.22.19
$ detox test --record-logs all
13:05:16.333 detox[12644] INFO:  [test.js] DETOX_RECORD_LOGS="all" DETOX_REPORT_SPECS=true DETOX_START_TIMESTAMP=1669651516324 DETOX_USE_CUSTOM_LOGGER=true jest --config e2e/config.json --testNamePattern "^((?!:ios:).)*$" e2e
13:05:21.700 detox[16876] ERROR: ChildProcessError: `C:\Users\dcard\AppData\Local\Android\Sdk\platform-tools\adb.EXE -s emulator-16872 shell pm install -r -g -t /data/local/tmp/detox/Application.apk` failed with code 1
    at ChildProcess.<anonymous> (D:\Projetos\Payface\Hibrid app payface-app-store-client\node_modules\child-process-promise\lib\index.js:132:23)                                                                          
    at ChildProcess.emit (node:events:513:28)                                                                                                                                                                             
    at ChildProcess.cp.emit (D:\Projetos\Payface\Hibrid app payface-app-store-client\node_modules\child-process-promise\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (node:internal/child_process:1093:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
13:05:21.708 detox[16876] INFO:  Example is assigned to undefined
13:05:21.709 detox[16876] INFO:  Example: should show home and find text: Pagamento por reconhecimento facial
13:05:21.711 detox[16876] INFO:  Example: should show home and find text: Pagamento por reconhecimento facial [FAIL]

 FAIL  e2e/firstTest.e2e.js
  ● Example › should show home and find text: Pagamento por reconhecimento facial
    Environment setup failed. See the detailed error below.

  ● Test suite failed to run

    ChildProcessError: `C:\Users\dcard\AppData\Local\Android\Sdk\platform-tools\adb.EXE -s emulator-16872 shell pm install -r -g -t /data/local/tmp/detox/Application.apk` failed with code 1

      at ChildProcess.<anonymous> (../node_modules/child-process-promise/lib/index.js:132:23)
      at ChildProcess.cp.emit (../node_modules/child-process-promise/node_modules/cross-spawn/lib/enoent.js:40:29)

13:05:21.866 detox[12644] ERROR: [cli.js] Command failed: jest --config e2e/config.json --testNamePattern "^((?!:ios:).)*$" e2e

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS D:\Projetos\Payface\Hibrid app payface-app-store-client\android> yarn e2e:test                  
yarn run v1.22.19
$ detox test
13:05:39.439 detox[25668] INFO:  [test.js] DETOX_REPORT_SPECS=true DETOX_START_TIMESTAMP=1669651539431 DETOX_USE_CUSTOM_LOGGER=true jest --config e2e/config.json --testNamePattern "^((?!:ios:).)*$" e2e

    Environment setup failed. See the detailed error below.

  ● Test suite failed to run

    ChildProcessError: `C:\Users\dcard\AppData\Local\Android\Sdk\platform-tools\adb.EXE -s emulator-16872 shell pm install -r -g -t /data/local/tmp/detox/Application.apk` failed with code 1

      at ChildProcess.<anonymous> (../node_modules/child-process-promise/lib/index.js:132:23)
      at ChildProcess.cp.emit (../node_modules/child-process-promise/node_modules/cross-spawn/lib/enoent.js:40:29)

13:05:44.561 detox[25668] ERROR: [cli.js] Command failed: jest --config e2e/config.json --testNamePattern "^((?!:ios:).)*$" e2e

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

</details>

### More data, please!

**detoxrc.json has this configuration:**
{"testRunner": "jest",

  "runnerConfig": "e2e/config.json",

  "skipLegacyWorkersInjection": true,

  "apps": {

    "android": {

      "type": "android.apk",

      "binaryPath": "android/app/build/outputs/apk/reactNative/staging/app-reactNative-staging.apk",

      "build": "cd android && .\\gradlew assembleReactNativeStaging assembleReactNativeStagingAndroidTest -DtestBuildType=debug && cd .."

    }

  },

  "devices": {

    "emulator": {

      "type": "android.emulator",

      "device": {

        "avdName": "Pixel_3a_API_33"

      }

    }

  },

  "configurations": {

    "android": {

      "device": "emulator",

      "app": "android"

    }

  }

}

One point that I must highlight is that the project was originally developed in native kotlin/java and we are applying react in the same project to carry out a migration of some parts, the implementation is being done in Mac, Linux and Windows machines. In the Detox documentation there is no mention of any restriction on the use of native technology and/or operating systems so that the tool is not used in possible scenarios. Any help with this problem we are facing is welcome, we also open space for indications of partner companies that provide Detox deployment and configuration services.

**Comment by KeflemTrindade** [comment]
I have the same problem

**Comment by asafkorem** [comment]
@dcardosoweb can you please update here if @KeflemTrindade's answer helped you?

**Comment by d4vidi** [comment]
@dcardosoweb We need the full _device_ log (i.e. using `adb logcat`) in order to be able to understand the issue. The error you've mentioned is not very informative.
