### ISSUE TITLE
Project with path ':detox' could not be found in project ':app'.

### ISSUE THREAD

**Issue by arthwood** [wix/Detox#3740]
### What happened?

Gradle build causes following error:

```
A problem occurred evaluating project ':app'.
> Project with path ':detox' could not be found in project ':app'.
```

This is very likely due to the proguard exemption:
```
proguardFile "${project(':detox').projectDir}/proguard-rules-app.pro"
```

### What was the expected behaviour?

Gradle build should complete with success.

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

I have a monorepo project and detox was initially installed on a root `node_modules` (which made maven path `url("$rootDir/../node_modules/detox/Detox-android")` invalid). I reconfigured project and now it's in the subproject's `node_modules`. I cleared Android studio and gradle cache, but it still fails with the error above.

I followed all the steps in Project Setup for both iOS and Android.

### In what environment did this happen?

Detox version: 20.0.3
React Native version: 0.66.4
Node version: 16.18.0
Device model: Pixel_XL_API_33
Android version: Tiramisu
Test-runner: jest

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by arthwood** [comment]
Ooh I just looked at documentation for Detox Next version and it has this entry instead:
```
proguardFile "${rootProject.projectDir}/../node_modules/detox/android/detox/proguard-rules-app.pro"
```
which makes gradle build successfully!
Probably should be the same for `20.x` documentation?

**Comment by noomorph** [comment]
Okay, we'll make sure to refresh the docs. @d4vidi cc

**Comment by nicolascavallin** [comment]
> Ooh I just looked at documentation for Detox Next version and it has this entry instead:
> 
> ```
> proguardFile "${rootProject.projectDir}/../node_modules/detox/android/detox/proguard-rules-app.pro"
> ```
> 
> which makes gradle build successfully! Probably should be the same for `20.x` documentation?

It works 👍🏼
