### ISSUE TITLE
Detox: Add packager command support

### ISSUE THREAD

**Issue by noomorph** [wix/Detox#3745]
### Describe your idea

Currently, you cannot have all the necessary information inside the Detox config to be able to run both the debug and release configurations.

For example, to be able to run tests on debug builds of React Native apps, you have to run the packager command together with the `detox test` command, i.e.:

```
npx react-native start ... & detox test ...
```

My suggestion is to support a new property for any app config called `packager`, `start`, `background` or something like that:

```json
{
  "type": "android.apk",
  "binaryPath": "...",
  "build": "./gradlew ...",
  "start": [
    "react-native start ...",
    "node myMockServer.js -p 3000",
  ]
}
```

That will allow us to keep the entire config as a part of the Detox preset and remove this knowledge from the wrapper tools such as Shono.

The suggested commands would be:

```bash
detox test -c ... # starts the commands by default
detox test -c ... --start=force # starts the tests even if some of the start commands fail
detox test -c ... --no-start # omits starting the commands
detox start -c ... # only starts the commands 
detox start -c ... --force # starts even if some of the commands fail
```

**Comment by professorkolik** [comment]
That's supported, whenever you ran build, packager will start automatically, I'm confident about iOS though.
you can create shell script. and define all your commands there

**Comment by noomorph** [comment]
@professorkolik this feature starts making more sense when you're using enterprise presets and you wish to keep "start" and "build" scripts together for better maintainability. Also, this proposal concerns "detox test" execution – the test+autostart feature should help users to run debug builds on CI as easily as the release ones.
