### ISSUE TITLE
Build Fails with Flipper enabled

### ISSUE THREAD

**Issue by jonohodgson** [wix/Detox#3750]
### What happened?

App builds successfully when running `react-native run-ios`

But with Flipper enabled debug build fails
`detox build --configuration ios.sim.debug; detox test --configuration ios.sim.debug`

```bash
** BUILD FAILED **
The following build commands failed:
        CompileC ../ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FlipperKit.build/Objects-normal/x86_64/FlipperWebSocket.o ../ios/Pods/FlipperKit/iOS/FlipperKit/FlipperWebSocket.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'FlipperKit' from project 'Pods')
(1 failure)
```

Version of Flipper doesn't seem to make a difference - have tried with
- 0.125.0
- 0.159.0
- 0.175.0

Successfully builds if Flipper is disabled

### What was the expected behaviour?

`detox build --configuration ios.sim.debug; detox test --configuration ios.sim.debug`

should build successfully without having to disable Flipper

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 20.0.3
React Native version: 0.70.6
Node version: 16.13.0
Device model: iPhone 14
iOS version: 16.1
macOS version: 13.0.1
Xcode version: 14.1
Test-runner (select one): jest

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by asafkorem** [comment]
@jonohodgson looks like the build is failing, which is definitely not related to Detox (`detox build` is just an alias to a regular iOS build command).

**Comment by asafkorem** [comment]
Please check this issue from React Native community: https://github.com/react-native-community/cli/issues/1311
Seems like the same problem.

**Comment by asafkorem** [comment]
From a brief look, this might be resolved by using iOS version at least 11.0 in the pod file`platform :ios, '11.0'`. Please let me know if that helped, or update here if you managed to solve it in a different way (and how).

**Comment by jonohodgson** [comment]
Thanks for the prompt feedback - will investigate

**Comment by jonohodgson** [comment]
Have raised https://github.com/facebook/flipper/issues/4381

**Comment by d4vidi** [comment]
@jonohodgson in light of https://github.com/facebook/flipper/issues/4381, is this still in-effect in Detox (in iOS versions ≥ 11)?

**Comment by d4vidi** [comment]
Will be followed-up in #3558
