### ISSUE TITLE
Detox fails to run test when using custom iOS simulator

### ISSUE THREAD

**Issue by JohnRBacon** [wix/Detox#3758]
### What happened?

Created a custom simulator with the following steps:

1. Xcode > Window > Devices and Simulators
2. tap on the (+) button and enter in the fields:
2a. Simulator Name: iPhone 14 Pro Max TEST
2b. Device Type: iPhone 14 Pro Max
2c. OS Version: iOS 16.0
3. Create
4. Run the following command to verify the custom simulator: applesimutils --list
5. Verify that the simulator exists:
5b.    
```
  },
    "dataPath" : "\/Users\/a6001691\/Library\/Developer\/CoreSimulator\/Devices\/9F830843-0401-4BEF-A71F-1CDFEE3A6F9E\/data",
    "dataPathSize" : 13316096,
    "logPath" : "\/Users\/a6001691\/Library\/Logs\/CoreSimulator\/9F830843-0401-4BEF-A71F-1CDFEE3A6F9E",
    "udid" : "9F830843-0401-4BEF-A71F-1CDFEE3A6F9E",
    "isAvailable" : true,
    "deviceType" : {
      "maxRuntimeVersion" : 4294967295,
      "bundlePath" : "\/Applications\/Xcode.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone 14 Pro Max.simdevicetype",
      "maxRuntimeVersionString" : "65535.255.255",
      "name" : "iPhone 14 Pro Max",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-14-Pro-Max",
      "productFamily" : "iPhone",
      "modelIdentifier" : "iPhone15,3",
      "minRuntimeVersionString" : "16.0.0",
      "minRuntimeVersion" : 1048576
    },
    "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-14-Pro-Max",
    "state" : "Shutdown",
    "name" : "iPhone 14 Pro Max TEST"
  },
```
6. Run a test with the new simulator: detox test -c ios.simulator -n 'iPhone 14 Pro Max TEST' PDPTests -t TRCID_1600066
7. Error message: 15:11:43.502 detox[19928] ERROR: Failed to find a device by type = "iPhone 14 Pro Max TEST"
HINT: Run 'applesimutils --list' to list your supported devices. It is advised only to specify a device type, e.g., "iPhone Xʀ" and avoid explicit search by OS version.
<img width="1497" alt="DetoxFailErrorMessage" src="https://user-images.githubusercontent.com/13742148/207469433-9d2fd1b3-388e-43f0-8ac1-8fcbf92bcaf7.png">
<img width="912" alt="XcodeSimulators" src="https://user-images.githubusercontent.com/13742148/207469465-2dd3544e-6338-4b22-b1de-
[applesimutils.txt](https://github.com/wix/Detox/files/10222960/applesimutils.txt)
4267baec54e0.png">
busercontent.com/13742148/207469435-a8e72443-b09d-4218-a52b-58a1525aa653.png">
[iPhone14ProMaxTEST.txt](https://github.com/wix/Detox/files/10222961/iPhone14ProMaxTEST.txt)

### What was the expected behaviour?

Expectation for a successful launch and execution of a test case using a custom simulators.  The error message states that if you run, "'applesimutils --list" and the supported device is listed the expectation is for the test to run successfully.

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

Created a custom simulator with the following steps:

1. Xcode > Window > Devices and Simulators
2. tap on the (+) button and enter in the fields:
2a. Simulator Name: iPhone 14 Pro Max TEST
2b. Device Type: iPhone 14 Pro Max
2c. OS Version: iOS 16.0
3. Create
4. Run the following command to verify the custom simulator shows in the output: applesimutils --list
5. Run a test with the new simulator: detox test -c ios.simulator -n 'iPhone 14 Pro Max TEST'

### In what environment did this happen?

Detox version: 19.11.0
React Native version: 0.63.42
Node version: 16.11.26
Device model: iPhone 14 Pro Max
iOS version: iOS 16.0
macOS version: 12.6.1
Xcode version: 14.0 (14A309)
Test-runner (select one): jest / other jest

### Detox logs

<details><summary>Detox logs</summary>

```
consumerAppNext-e2e git:(develop) ✗ detox test -c ios.simulator -n 'iPhone 14 Pro Max TEST' PDPTests -t TRCID_1600066 --loglevel trace
15:58:04.667 detox[52484] INFO:  [test.js] DETOX_CONFIGURATION="ios.simulator" DETOX_DEVICE_NAME="iPhone 14 Pro Max TEST" DETOX_LOGLEVEL="trace" DETOX_REPORT_SPECS=true DETOX_START_TIMESTAMP=1670975884659 DETOX_USE_CUSTOM_LOGGER=true jest --config e2e/tests/Consumer-App/Config/config.json --testNamePattern TRCID_1600066 --maxWorkers 1 PDPTests
15:58:06.545 detox[52485] TRACE: [DETOX_CREATE] created a Detox instance with config:
{
  appsConfig: {
    default: {
      binaryPath: './e2e/builds/company-mApp.app',
      build: 'xcodebuild -workspace ./ios/company-mApp.xcworkspace -scheme BB-AllUITests -configuration Debug -sdk iphonesimulator',
      type: 'ios.app'
    }
  },
  artifactsConfig: {
    rootDir: 'artifacts/ios.simulator.2022-12-13 23-58-04Z',
    plugins: {
      log: {
        enabled: false,
        keepOnlyFailedTestsArtifacts: false
      },
      screenshot: {
        enabled: true,
        shouldTakeAutomaticSnapshots: false,
        keepOnlyFailedTestsArtifacts: false
      },
      video: {
        enabled: false,
        keepOnlyFailedTestsArtifacts: false
      },
      instruments: {
        enabled: false,
        keepOnlyFailedTestsArtifacts: false
      },
      timeline: {
        enabled: false
      },
      uiHierarchy: {
        enabled: false,
        keepOnlyFailedTestsArtifacts: false
      }
    },
    pathBuilder: ArtifactPathBuilder {
      _rootDir: 'artifacts/ios.simulator.2022-12-13 23-58-04Z'
    }
  },
  behaviorConfig: {
    init: {
      reinstallApp: true,
      exposeGlobals: true
    },
    cleanup: {
      shutdownDevice: false
    },
    launchApp: 'auto'
  },
  cliConfig: {
    configuration: 'ios.simulator',
    deviceName: 'iPhone 14 Pro Max TEST',
    loglevel: 'trace',
    useCustomLogger: true
  },
  configurationName: 'ios.simulator',
  deviceConfig: {
    type: 'ios.simulator',
    device: {
      type: 'iPhone 14 Pro Max TEST'
    }
  },
  runnerConfig: {
    testRunner: 'jest',
    runnerConfig: 'e2e/tests/Consumer-App/Config/config.json',
    specs: 'e2e',
    skipLegacyWorkersInjection: false
  },
  sessionConfig: {
    autoStart: true,
    sessionId: '0866d193-114d-5bac-2131-f8928e1278ac',
    debugSynchronization: 10000
  }
}
15:58:06.551 detox[52485] DEBUG: [WSS_CREATE] Detox server listening on localhost:49528...
15:58:06.571 detox[52485] DEBUG: [WSS_CONNECTION, #49529] registered a new connection.
15:58:06.573 detox[52485] TRACE: [WS_OPEN] opened web socket to: ws://localhost:49528
15:58:06.577 detox[52485] TRACE: [WS_SEND] {"type":"login","params":{"sessionId":"0866d193-114d-5bac-2131-f8928e1278ac","role":"tester"},"messageId":0}
15:58:06.579 detox[52485] TRACE: [WSS_GET_FROM, #49529] {"type":"login","params":{"sessionId":"0866d193-114d-5bac-2131-f8928e1278ac","role":"tester"},"messageId":0}
15:58:06.580 detox[52485] TRACE: [SESSION_CREATED] created session 0866d193-114d-5bac-2131-f8928e1278ac
15:58:06.580 detox[52485] TRACE: [WSS_SEND_TO, #tester] {"type":"loginSuccess","params":{"testerConnected":true,"appConnected":false},"messageId":0}
15:58:06.581 detox[52485] TRACE: [SESSION_JOINED] tester joined session 0866d193-114d-5bac-2131-f8928e1278ac
15:58:06.582 detox[52485] TRACE: [WS_MESSAGE] {"type":"loginSuccess","params":{"testerConnected":true,"appConnected":false},"messageId":0}
 
15:58:07.059 detox[52485] DEBUG: [EXEC_CMD, #0] applesimutils --list --byType "iPhone 14 Pro Max TEST"
15:58:07.517 detox[52485] TRACE: [EXEC_SUCCESS, #0] [

]

15:58:07.519 detox[52485] ERROR: Failed to find a device by type = "iPhone 14 Pro Max TEST"

HINT: Run 'applesimutils --list' to list your supported devices. It is advised only to specify a device type, e.g., "iPhone Xʀ" and avoid explicit search by OS version.
ts-jest[versions] (WARN) Version 25.5.4 of jest installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=26.0.0 <27.0.0-0). Please do not report issues in ts-jest if you are using unsupported versions.
15:58:08.109 detox[52485] TRACE: [ARTIFACTS_LIFECYCLE] artifactsManager.onBeforeCleanup()
15:58:08.114 detox[52485] DEBUG: [WSS_CLOSE] Detox server has been closed gracefully
 FAIL  e2e/tests/Consumer-App/PDPTests.e2e.ts
  ● Test suite failed to run

    TypeError: detox_1.device.getPlatform is not a function

       7 | // Accessibility Labels
       8 | export const A11Y_ADD_TO_CART_LABEL =
    >  9 |   device.getPlatform() === ANDROID_OS ? 'Add to cart Button. ' : 'Add to cart Button. Double tap to activate'
         |          ^
      10 | export const A11Y_ADDED_TO_CART_LABEL = 'Product Added to cart'
      11 | export const A11Y_CART_BUTTON_LABEL =
      12 |   device.getPlatform() === ANDROID_OS ? 'cart, empty, button. ' : 'cart, empty, button. Double tap to activate'

      at Object.<anonymous> (../../helpers/constants.ts:9:10)
      at Object.<anonymous> (../../helpers/AppSupport.ts:3:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.554s
Ran all test suites matching /PDPTests/i with tests matching "TRCID_1600066".
**  jest-stare --reporters: wrote output report to e2e/jest-stare/index.html    **
15:58:08.200 detox[52485] TRACE: [SESSION_TORN] tester exited session 0866d193-114d-5bac-2131-f8928e1278ac
15:58:08.239 detox[52484] ERROR: [cli.js] Command failed: jest --config e2e/tests/Consumer-App/Config/config.json --testNamePattern TRCID_1600066 --maxWorkers 1 PDPTests
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
[detox_pid_55839.json.log](https://github.com/wix/Detox/files/10223044/detox_pid_55839.json.log)
[detox_pid_55839.log](https://github.com/wix/Detox/files/10223046/detox_pid_55839.log)

```

</details>

### More data, please!

<img width="1497" alt="DetoxFailErrorMessage" src="https://user-images.githubusercontent.com/13742148/207472534-786d2065-6ba2-423a-a0b7-897be3607bea.png">

![iPhone14ProMaxSDET json screenshot](https://user-images.githubusercontent.com/13742148/207472998-fa883e65-07b2-4140-be3b-7d90b8df8cde.png)
<img width="912" alt="XcodeSimulators" src="https://user-images.githubusercontent.com/13742148/207472605-f168b7a1-f923-47e7-a5da-80d675421361.png">
![Uploading github.json.png…]()
[github.simlist.json.txt](https://github.com/wix/Detox/files/10248101/github.simlist.json.txt)

**Comment by asafkorem** [comment]
Hey @JohnRBacon, that's actually an [ASU](https://github.com/wix/AppleSimulatorUtils) issue (and not Detox), but since we maintain both project I can answer you here.. 😅

From the devices list above, it looks like your simulator has a different name than what you described on the `detox test` command:

> "name" : "iPhone 14 Pro Max SDET",
..
..
> Failed to find a device by type = "iPhone 14 Pro Max TEST"

Also, I recommend to config your simulator in the configs file, please check: [device configs guide doc](https://wix.github.io/Detox/docs/next/introduction/project-setup#step-3-device-configs), [configs structure doc](https://wix.github.io/Detox/docs/next/config/overview/#config-structure).

**Comment by JohnRBacon** [comment]
Thanks @asafkorem for the catch.  I updated the files here and on my machine.  Am still getting the same error message. 

```
ERROR: Failed to find a device by type = "iPhone 14 Pro Max TEST"

HINT: Run 'applesimutils --list' to list your supported devices. It is advised only to specify a device type, e.g., "iPhone Xʀ" and avoid explicit search by OS version.
```

**Comment by JohnRBacon** [comment]
When running the command:  **xcrun simctl list devicetype**s, The created devices 'iPhone 14 Pro Max TEST' does not display in the list
<img width="820" alt="xcrun simctl list devicetypes" src="https://user-images.githubusercontent.com/13742148/208167313-3e7cde30-35da-43fc-b347-ce4d02c6f224.png">

**Comment by asafkorem** [comment]
Hey @JohnRBacon, `xcrun simctl` is a util of Apple (part of Xcode CLI tools), if there's any problem with this tool, I encourage you to contact them using the Apple Developers forum or via their feedback assitant.

You can try to locate the available devices with out tool: `applesimutils --list`, or more specifically to check if your device is available using `applesimutils --list --byName "iPhone 14 Pro Max TEST"`

**Comment by asafkorem** [comment]
Try running `xcrun simctl list` and not listing the device types, because there's a difference between the available devices and the available types.

**Comment by JohnRBacon** [comment]
Thanks for sticking with @asafkorem. I think this issue is getting narrowed down.
So I ran "applesimutils --list --byName "iPhone 14 Pro Max TEST"" and "xcrun simctl list".  When running both of the commands the custom sim is found -  "iPhone 14 Pro Max TEST".  
If the simulator is listed, why does Detox fail to find the custom simulator?  The error message,
ERROR: Failed to find a device by type = "iPhone 14 Pro Max TEST"

HINT: Run 'applesimutils --list' to list your supported devices. It is advised only to specify a device type, e.g., "iPhone Xʀ" and avoid explicit search by OS version.

>    applesimutils --list --byName "iPhone 14 Pro Max TEST"

    },
    "dataPath" : "\/Users\/xxxxxxx\/Library\/Developer\/CoreSimulator\/Devices\/9F830843-0401-4BEF-A71F-1CDFEE3A6F9E\/data",
    "dataPathSize" : 13316096,
    "logPath" : "\/Users\/xxxxxxx\/Library\/Logs\/CoreSimulator\/9F830843-0401-4BEF-A71F-1CDFEE3A6F9E",
    "udid" : "9F830843-0401-4BEF-A71F-1CDFEE3A6F9E",
    "isAvailable" : true,
    "deviceType" : {
      "maxRuntimeVersion" : 4294967295,
      "bundlePath" : "\/Applications\/Xcode.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Library\/Developer\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone 14 Pro Max.simdevicetype",
      "maxRuntimeVersionString" : "65535.255.255",
      "name" : "iPhone 14 Pro Max",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-14-Pro-Max",
      "productFamily" : "iPhone",
      "modelIdentifier" : "iPhone15,3",
      "minRuntimeVersionString" : "16.0.0",
      "minRuntimeVersion" : 1048576
    },
    "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-14-Pro-Max",
    "state" : "Shutdown",
    "name" : "iPhone 14 Pro Max TEST"
  }


  xcrun simctl list:

    iPhone 14 (C69B1D3F-D872-4FA0-827A-E51DE3D18C17) (Shutdown) 
    iPhone 14 Plus (F887700C-1605-41A9-B81C-8E3E6B42931C) (Shutdown) 
    iPhone 14 Pro (E1FF9C0A-06CD-4301-A846-76651A918D0F) (Shutdown) 
    iPhone 14 Pro Max (74071BF7-FBCC-4C96-BDBF-A7A93011DD6A) (Booted) 
    iPhone 14 Pro Max TEST (9F830843-0401-4BEF-A71F-1CDFEE3A6F9E) (Shutdown)

**Comment by noomorph** [comment]
I'd suggest improving Detox CLI – the `yargs` library can parse complex JSON objects.

```bash
detox test ... --device.name="..." --device.os="..."`
```

Yargs will compose `{ device: { name: ..., os: ... } }` object that we can use in our search queries.

**Comment by noomorph** [comment]
Related to https://github.com/wix/Detox/issues/1847

**Comment by d4vidi** [comment]
Try to look up based on the generated `udid` - `9F830843-0401-4BEF-A71F-1CDFEE3A6F9E`

**Comment by noomorph** [comment]
I see a workaround like this:
https://wix.github.io/Detox/docs/next/config/devices#examples

```js
iphone: {
  "type": "ios.simulator",
  "device": {
    "name": process.env.WORKAROUND_DEVICE_NAME || "iPhone 14",
  },
}
```

**Comment by JohnRBacon** [comment]
Thanks for the comments and suggestions @noomorph, @d4vidi, and @asafkorem.  Through your comments I found the issue and solution.  Implemented the idea and now the test suite runs with the custom names.  Basically what I changed was not using the option to override the device name '-n' as I use a script to run the test cases/suites.  I used @noomorph's workaround in the detox.config.json file

    "iOSSimulatorDaily": {
      "id": "543A9C14-C955-4309-B600-6B57ADA80ECC",
      "type": "ios.simulator",
      "device": {
        "byType": "iPhone 14 Pro Max",  
        "name": "iPhone 14 Pro Max Daily"
      }

    "ios.daily.simulator": {
      "device": "iOSSimulatorDaily",
      "app": "ios.companyname.uitest"
    },
