### ISSUE TITLE
iOS 16.2.0 test hangs on "Trying to set permissions..."

### ISSUE THREAD

**Issue by alexborton** [wix/Detox#3760]
### What happened?

Launching into the application with `{notifications: 'NO'}` seems to cause the app/test to hang and not be recoverable, causing it to fail;

```
...
  beforeEach(async () => {
    await device.launchApp({
      newInstance: true,
      // permissions: { notifications: 'NO' }, <-- when this line is present in the launch, the test fails to get started
    })
  })
...
```

```
thrown: "Exceeded timeout of 120000 ms for a hook.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      18 |   // })
      19 |
    > 20 |   beforeEach(async () => {
         |   ^
      21 |     await device.launchApp({
      22 |       newInstance: true,
      23 |       permissions: { notifications: 'NO' },

      at e2e/tests/kbaFullSignup.test.ts:20:3
      at Object.<anonymous> (e2e/tests/kbaFullSignup.test.ts:13:1)

11:09:37.902 detox[95297] i user A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks. Active timers can also cause this, ensure that .unref() was called on them.
```

**This issue only happens with latest simulator version; 16.2.0**

### What was the expected behaviour?

The permissions should be set successfully and the test continue

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

Run a test, setting a permission on launch in an iOS simulator using iOS version 16.2.0

### In what environment did this happen?

Detox version: 20.1.0
React Native version: 0.70.5
Node version: 16.17.0
Device model: iPhone 11
iOS version: 16.2.0
macOS version: 
Xcode version: 
Test-runner (select one): jest

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by asafkorem** [comment]
>This issue only happens with latest simulator version; 16.2.0

Thank you @alexborton for bringing this to our attention. I understand that you've attempted to reproduce this issue on previous versions of iOS. 

Can you please provide more details, specifically device logs, here to assist with further investigation?
