### ISSUE TITLE
how to test a spinner ?

### ISSUE THREAD

**Issue by pdaniloais** [wix/detox#377]
Hi,

I would like to test the spinner displaying.

The spinner stay visible about 0,5 sec

I check with

    await expect(element(by.id('spinnerPopup'))).toBeVisible();

But I have `Error: Cannot find UI Element.`. (The spinner was visible on my simulator)

Is a solution exists to test this kind of component ?

Thx

**Comment by rotemmiz** [comment]
Detox will only evaluate this expectation when the app is idle (no network request inflight, empty thread queues, no animations play etc.). What happens while your spinner is running ?

As a rule of thumb, try no to test transient states, write your tests like there are only steady states, e.g, for this scenario: tap a button -> init a network request (while displaying a spinner) -> render new view upon response, you would only need to write the following:

```js
await element(by.id('myButton')).tap();
await expect(element(by.id(viewRenderedAfterResponse)).toBeVisible();
```

**Comment by rumax** [comment]
If animation is the issue, is it be possible to do something like:

```
await device.disableSynchronization();

await delay(500)

await expect(element(by.id('spinnerPopup'))).toBeVisible();

device.enableSynchronization()

```

Moreover if the error is `Error: Cannot find UI Element.`, it shouldn't be synchronisation issue, otherwise the message should be `timeout`

**Comment by rotemmiz** [comment]
using `await delay(500)` is flaky since its not synced with the process under test, watch out from those kind of hacks, or else your tests will become unreliable.

Anyway, my previous comment holds, don't test transient states.
