### ISSUE TITLE
How to run one app in multiple devices

### ISSUE THREAD

**Issue by erwanlpfr** [wix/Detox#3774]
### Description

Hello,

I'm facing an issue where I try to test one app with a plenty of devices.
Basically, this need comes with the need of testing multiple devices quickly to speed up the CI. 

I read the doc where it is suggested to : 
- add devices in devices config (done),
- run detox test with `maxWorkers` flag (done) as mentioned [here](https://wix.github.io/Detox/docs/next/guide/parallel-test-execution).

And after, I don't get where to tell about the others devices.

For example, the configuration part : 
```js
    'ios.sim.debug': {
      device: 'ios_iphone14',
      app: 'ios.debug',
    },
```

Where can I specify to run on `ios_iphone14`, `ios_iphone13` and `ios_iphone6s`?
Or do I need to do `ios.sim.debug.iphone14`, etc?

It is just I don't get where to specify a such of information to run an app in multiple devices at the same time.
Maybe it is not possible?

Thank you for your work!

### Your environment

Detox version: 20.1.0
React Native version: 0.70.6 
Node version: 16.x
Device model: Mac M1
OS: MacOS
Test-runner (select one): jest

**Comment by noomorph** [comment]
### CLI

I'd suggest creating a script which runs multiple `detox test` commands and overrides `-n, --device-name`, e.g.:

```
detox reset-lock-file & \
detox test -c ios.sim.debug -n "iPhone 14" --keepLockFile & \
detox test -c ios.sim.debug -n "iPhone 13" --keepLockFile & \
wait;
```

See: https://wix.github.io/Detox/docs/cli/reset-lock-file
See: https://wix.github.io/Detox/docs/cli/test#options

### Configs

Indeed, you could generate multiple configs like that:

```js
// ...
for (const [key, type] of [['iphone14', 'iPhone 14'], ['iphone13', 'iPhone 13']]) {
  detoxConfig.devices[key] = {
    type: 'ios.simulator',
    device: { type },
  };

  detoxConfig.configurations[`ios.sim.debug.${key}`] = {
    ...detoxConfig.configurations[`ios.sim.debug`],
    device: key,
  };
}
// ...
module.exports = detoxConfig;
```

## More standard (automatic) approaches

We currently don't have such ones, but we're open to suggestions. Maybe we can come up with something later in 2023.

**Comment by erwanlpfr** [comment]
Thanks for your reply!

Great answer! In my case, I would keep the lock file since it may overlap other CI from other project.
Something like (in my CI case) :

```bash
detox test -c ios.sim.release -n "iPhone 14" --cleanup & \
detox test -c ios.sim.release -n "iPhone 13"  --cleanup & \
wait;
```

But that is great! Also, I will make it dynamic, as you mentioned at the end of your comment.

As suggestion, when I was looking for this feature, I tried the most basic approach by putting this : 
```js
  configurations: {
    'ios.sim.debug': {
      devices: ['ios_iphone14', 'ios_iphone13', 'ios_iphone6s', 'ios_iphone12', ], // <----------------------------------
      app: 'ios.debug',
    },
    'ios.sim.release': {
      device: 'ios_iphone14',
      app: 'ios.release',
    },
    'android.emu.debug': {
      device: 'ios_iphone14',
      app: 'android.debug',
    },
    'android.emu.release': {
      device: 'android_pixel2',
      app: 'android.release',
    },
  },
```
I tried this because I saw it was possible to pluralize the `app` attribute, so I thought the same for `device`.

And from here, doing internally the same threading process?

Thanks!

**Comment by noomorph** [comment]
> In my case, I would keep the lock file since it may overlap other CI from other project.

Okay, whatever works better for you.
`--cleanup` option might be slow still (we plan to fix it in the nearest months), but it should work.

> I tried this because I saw it was possible to pluralize the app attribute, so I thought the same for device.
No, we don't support multiple `devices` yet.

> And from here, doing internally the same threading process?
Not sure if I understood you question.

**Comment by erwanlpfr** [comment]
> No, we don't support multiple devices yet.
> Not sure if I understood your question.

I meant for a potential feature in this way (with this syntax), why not!

**Comment by N0x1k** [comment]
Hello, @noomorph, is this still the preferred method of running detox tests on multiple simulators in parallel? I also tried using the --maxWorkers cli option but that didn't seem to work correctly.

**Comment by noomorph** [comment]
@N0x1k in this discussion, we talked about different device types. If you need to spawn multiple devices of the same type (e.g. "iPhone 16"), `--maxWorkers` should work for you, and this issue is not a good place to continue the discussion.

As for the heterogenous multiple device types scenarios, we had no good opportunity to work on this so far, but this feature still looks worthy to implement. If/when we get to overhaul test runner integration and refactor Detox internals further, we'll likely provide this option, too, but I can't give any ETAs right now.
