### ISSUE TITLE
Detox iOS build not rendering png files

### ISSUE THREAD

**Issue by gabimoncha** [wix/Detox#3782]
### What happened?

Hi,

We just setup Detox in our projects and discovered that the iOS build is not rendering the `png` files. We found an old issue about this, but seems there was no fix and someone closed it.

https://github.com/wix/detox/issues/263

### What was the expected behaviour?

The iOS build should show the images.

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

`test command`
`detox test --configuration ios.sim.release --artifacts-location e2e/artifacts --take-screenshots=failing --record-videos=failing --record-logs=failing --loglevel info --debug-synchronization 50000 --loglevel trace`

`.detoxrc.js`

```javascript
/** @type {Detox.DetoxConfig} */
module.exports = {
  testRunner: {
    args: {
      $0: 'jest',
      config: 'e2e/jest.config.js',
    },
    jest: {
      setupTimeout: 120000,
    },
  },

  apps: {
    'ios.release': {
      type: 'ios.app',
      binaryPath:
        'ios/build/Build/Products/Release-iphonesimulator/MyApp.app',
      build:
        'xcodebuild -workspace ios/myapp.xcworkspace -scheme "myapp" -configuration Release -sdk iphonesimulator -derivedDataPath ios/build',
    },
  },
  devices: {
    simulator: {
      type: 'ios.simulator',
      device: {
        type: 'iPhone 14',
      },
    },
  },
  configurations: {
    'ios.sim.release': {
      device: 'simulator',
      app: 'ios.release',
    },
  },
};

```

`jest.config.js`
```javascript
/** @type {import('@jest/types').Config.InitialOptions} */
module.exports = {
  rootDir: '..',
  testMatch: ['<rootDir>/e2e/**/__tests__/**/*.spec.ts'],
  testTimeout: 120000,
  maxWorkers: 1,
  globalSetup: 'detox/runners/jest/globalSetup',
  globalTeardown: 'detox/runners/jest/globalTeardown',
  reporters: ['detox/runners/jest/reporter'],
  testEnvironment: 'detox/runners/jest/testEnvironment',
  verbose: true,
};
```

### In what environment did this happen?

Detox version: ^20.1.0
React Native version: 0.67.3
Node version: v16.18.1
Device model: iPhone 14
iOS version: 16.2
macOS version: 13.1
Xcode version: 14.2
Test-runner (select one): jest

**Comment by asafkorem** [comment]
Hi @gabimoncha, when running the app on Simulator without Detox, can you see those PNG images rendered properly?

**Comment by d4vidi** [comment]
@gabimoncha Would be great if you could reproduce this using the [DetoxTemplate](https://github.com/wix-incubator/DetoxTemplate) project. In any case, we desperately need more info here in order to be able to help out:
1. Screenshots of the app of what you're *seeing* on your device's screen
2. What use cases exactly don't work for you - which part of the app fails to load the `png`

Best if you join our Discord so we could discuss this further.

**Comment by gabimoncha** [comment]
The app works fine with in debug and production builds. Only in detox the pngs don't show.

**Comment by gabimoncha** [comment]
Was this issue fixed?

**Comment by noomorph** [comment]
I think that this request was not fulfilled:

![image](https://user-images.githubusercontent.com/1962469/221347973-a15a7a26-2fce-4407-b2dd-0d561afff72f.png)
