### ISSUE TITLE
Android lacks real time feedback on test failures

### ISSUE THREAD

**Issue by shamilovtim** [wix/Detox#3788]
### What happened?

On iOS when a test step fails it provides real time feedback in Jest so that the test can be cancelled early. This results in faster development iterations while developing or debugging.

On Android, Detox is not providing real time feedback during failures. I don't know why the failure occurred until the very end of the test suite. This is not ideal for fast development iterations or real time development.
<img width="1292" alt="Screen Shot 2022-12-28 at 1 41 31 PM" src="https://user-images.githubusercontent.com/3495974/209858321-c0938016-e447-4e64-97d6-adf1107474e2.png">

For example:
```
13:40:47.510 detox[57896] i lifecycle Buy Again Test: Should signup for an account and add a payment method [FAIL]
```

should include details of why the failure happened right away so I can cancel the test and keep working.

### What was the expected behaviour?

Expect Detox to provide why the test step failed in real time rather than only at the end summary of the test suite 

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 20.1.0
React Native version: 0.68.5
Node version: v16.18.0
Device model: Android AOSP
Android version: Android 11 API 30
Test-runner (select one): jest

**Comment by d4vidi** [comment]
@shamilovtim have you considered using Jest's `--bail`? In any case, this doesn't sound like anything platform-specific, TBH. We would appreciate any additional evidence (e.g. complete logs) showing that, or otherwise to be able to understand the difference between the errors you've had in the two platforms.
