### ISSUE TITLE
(WIP) Support setDatePickerDate for android as well

### ISSUE THREAD

**Issue by mauricedoepke** [wix/Detox#3789]
### Describe your idea

The method is currently ios only, but it would be nice to make it work for android as well.

API wise I think it would be nice, to stay somewhat compatible to the ios variant. Which looks like this:
```
await element(by.id('datePicker')).setDatePickerDate('2019-02-06T05:10:00-08:00', "ISO8601");
await element(by.id('datePicker')).setDatePickerDate('2019/02/06', "yyyy/MM/dd");
```
I suggest to support the first variant with the ISO8601 format as this is easy to parse and throw an error for the second as it does not really make sense to reimplement the exact behaviour of [NSDateFormatter](https://developer.apple.com/documentation/foundation/dateformatter). 

I did already do some research and it seems to me that this is quite doable. Apparently Detox uses espresso on Android.
And espresso supports updating date pickers: https://developer.android.com/reference/androidx/test/espresso/contrib/PickerActions

After some glance through the detox code, I think those files need changes:
- https://github.com/wix/Detox/blob/1dca8733b2446e66a386b0d522809cb156d36855/generation/index.js
This one apparently autogenerates some js bindings. I think one can use the DetoxAction and DetoxViewActions part as an example to add `androidx.test.espresso.contrib.PickerActions`

 - https://github.com/wix/Detox/blob/b1bd601e6d7407b7f1866e67542f49c31cfa59ea/detox/android/detox/src/full/java/com/wix/detox/espresso/DetoxAction.java
 This file seems to be some kind of wrapper for all actions, so I guess the DatePicker action needs to be added here as well.
 
 - https://github.com/wix/Detox/blob/20034e5e6fef1c3bdb145311d7c9d1c36f71ec40/detox/src/android/actions/native.js
 - https://github.com/wix/Detox/blob/9824d4be23749e76d3e153ec17377c781618d6a5/detox/src/android/core/NativeElement.js
 Theese two seem to be yet another wrapper layer
 
 - https://github.com/wix/Detox/tree/b1bd601e6d7407b7f1866e67542f49c31cfa59ea/detox/android/detox/src/full/java/com/wix/detox/espresso
 We might need a PickerActions.java here similar to DetoxAction.java or DetoxViewActions.jave
 
 
 I'd be willing to invest some time into this as this feature would help me, but I would definitely need help from the detox core team.
 Are you interested in having this feature added? Did I roughly identify the right files to change? Are there any obivious ones missing in my list?

**Comment by asafkorem** [comment]
Hi @mauricedoepke,

I don't think it would be necessary to throw an error when using the second option, as it should be fairly easy to implement using either the _SimpleDateFormat_ class or the _DateTimeFormatter_ class from the Java standard library.

I generally agree with your proposed approach to implement the _setDatePickerDate_ method on Android, but I think the implementation within the native code can be inside _DetoxAction_ and not part of _PickerActions_ or something. However, it would be best to get confirmation and guidance from someone that works on the Android side of Detox (@jonathanmos), to make sure that this is the correct approach.

We would love to have your contribution to this feature on Android. The Detox team will be happy to provide code reviews and assist with any questions you might have. Thank you for your proposal and willingness to contribute!

**Comment by d4vidi** [comment]
Closed via #3790. Thanks @mauricedoepke!

**Comment by noomorph** [comment]
Yes, I believe

**Comment by VishalKumar2016** [comment]
@noomorph @d4vidi @react-native-community/datetimepicker This also has a time picker how to select time.we can select date by this method but not time
               
` const datePicker = element(by.type('android.widget.DatePicker'))
`
`await datePicker.setDatePickerDate('2023-12-30T07:32:13.235Z', 'ISO8601');`
