### ISSUE TITLE
Add feature to mock image selection

### ISSUE THREAD

**Issue by mauricedoepke** [wix/Detox#3793]
### Describe your idea

It would be nice if one could test the image handling behaviour of ones app. 
Theoretically the emulators offer a couple of example images but these are hard to use in automated tests.

Instead of opening a real image selector it would be nice if detox could mock this behaviour.

proposed syntax:
```ts
interface MockImageOptions {
    //make android intent filters customizable here
}

//This would make all image pickers return this image until another one is defined.
device.setMockImage(image: Buffer, mime: string, options?: MockImageOptions);

//Turns off the mocking. The App will behave normally.
device.clearMockImage();
```

- Implementing this for Android looks straight forward with: https://developer.android.com/training/testing/espresso/intents
- On Ios it seems as it might be possible to mock the picker at compile time like this: https://github.com/yonat/MockImagePicker

I'd be willing to invest some time into this, but this has no high priority for me right now. So this would take some time to implement. Help would be welcome.

What are your general thoughts regarding this?

**Comment by asafkorem** [comment]
Hi @mauricedoepke,

Thanks for the suggestion to add the ability to mock image pickers to Detox. While Detox does not have the ability to be involved in the compilation process, it is possible to use libraries like [MockImagePicker](https://github.com/yonat/MockImagePicker) to mock this behavior within the app itself.

If you're working with a React Native app, you can also use Detox's mock utils or mock the respective module in your app to achieve this behavior. Please note that Detox does not provide any mocking functionality itself, but rather provides a framework where you can use tools like these. See our mocking guide: https://wix.github.io/Detox/docs/next/guide/mocking.

If you're interested in implementing this mock for use in Detox tests, we'd be happy to help and consult. You might also consider contributing your solution as open source to benefit the community.

**Comment by mauricedoepke** [comment]
Hey @asafkorem Thanks for your response.

I think having this directly built into detox would make this much more accessible than having to fiddle around with 3rd party libs.

At least for android it should not be too hard to implement as the required features are available via espresso. 
I would try to work on that after the setDatePicker is done.

Regarding IOS. I thought detox would be at least partially compiled into the app to take the commands from javascript. At least that's how I understood this section: 
>  [https://wix.github.io/Detox/docs/articles/how-detox-works/](https://wix.github.io/Detox/docs/articles/how-detox-works/)
Detox native client ([iOS](https://github.com/wix/Detox/tree/master/detox/ios) & [Android](https://github.com/wix/Detox/tree/master/detox/android)): A component that gets seamlessly integrated into the tested app on the tested device, right as Detox starts executing. It synchronizes with the app, matches user queries, executes user commands (e.g. taps, scrolls) and validates expectations.

Is this correct or was this a false assumption?

My hope was that this would maybe allow to optionally compile a similar mock approach as [MockImagePicker](https://github.com/yonat/MockImagePicker) into the app along with detox to support this feature.

**Comment by asafkorem** [comment]
@mauricedoepke, you were incorrect in your assumption that Detox is compiled into the app on iOS. Detox is actually integrated into the app on iOS at runtime using DYLD_INSERT_LIBRARIES (see: https://github.com/wix/Detox/blob/master/detox/src/devices/common/drivers/ios/tools/AppleSimUtils.js#L410). However, there are other ways to mock things, even on the native side, such as using ObjC swizzling for UIImagePickerController methods. 
I'd like to continue this discussion, especially regarding the API itself in [our Discord server](https://discord.gg/CkD5QKheF5) 😎

**Comment by d4vidi** [comment]
@mauricedoepke thanks for this proposal. We've discussed this internally for a bit and we largely agree that this type of mocking could be provided in ways similar to the standard mocking that we offer in our [mocking guide](https://wix.github.io/Detox/docs/guide/mocking) - albeit network-focused.
