### ISSUE TITLE
[Website] Showcase Cards CSS Gradient Fixes

### ISSUE THREAD

**Issue by moutro** [wix/Detox#3811]
#### There are 2 options we discussed for this task:

- [ ] Add gradient to card based on icon color

or

- [ ] Change card gradient color to purple

Sample Images of changes needed:

<img width="500" alt="Screenshot 2023-01-04 at 15 07 25" src="https://user-images.githubusercontent.com/34761997/210561751-060eaecd-ea27-4d99-bbbd-992051fc9fe7.png">

**Comment by moutro** [comment]
Additional context notes:

An idea was talked about to hard code this in the JSON - that we could choose the color of each icon using a color picker and then decide what the color of the background of the card should be. Every bg color will match the color of the icon we put in the JSON. So it will not be part of the CSS file, will be a style attribute using "style" prop to do it dynamically.

**Comment by noomorph** [comment]
This can be split into 2 phases:

1) use a static gradient;
2) advanced implementation: use pre-compilated gradient from the images;
