### ISSUE TITLE
[Website] Fix navbar mobile

### ISSUE THREAD

**Issue by moutro** [wix/Detox#3818]
### Describe your idea

Detox website's Figma Design Final tab for Mobile Styles: https://www.figma.com/file/QGhhB7djq0OxvLzULhs7u5/Detox?node-id=98%3A2284&t=hPcPyD8iBOlyDjmc-0

- [x] Place searchbox and hamburger on RHS on mobile screens

Sample Images of changes needed:

Mobile screens:

![Screenshot 2023-01-04 at 17 08 09](https://user-images.githubusercontent.com/34761997/210585455-b981b752-20d8-417e-b01d-536ed97f673d.png)

larger screens:

![Screenshot 2023-01-04 at 17 08 37](https://user-images.githubusercontent.com/34761997/210585557-86f3369d-2df1-4c53-89a0-287a7191e222.png)

**Comment by noomorph** [comment]
Thanks, @IrbisKronos. The issue is resolved.
