### ISSUE TITLE
[Website] Resolve PR Comments from #3640

### ISSUE THREAD

**Issue by moutro** [wix/Detox#3819]
### Describe your idea

PR: https://github.com/wix/Detox/pull/3640

- [ ] Reveiw and resolve comments made by Kobi Kadosh on this PR
- [ ] Good to show devs contributing their time to add comments to PR's that it's being appreciated and considered

**Comment by noomorph** [comment]
Leave here the cosmetic changes in the scope, please.

The task with rewriting JSX → MD of the "Benefits of Detox" (on the home page) – it is better to be separated into one more issue. 🙏
