### ISSUE TITLE
device.setOrientation is not working on iOS 16

### ISSUE THREAD

**Issue by mrbrentkelly** [wix/Detox#3823]
### What happened?

The Detox `device.setOrientation` API is no longer working when building using Xcode 14.1 and running on iOS 16.

Calling `await device.setOrientation('landscape');` just silently fails to do anything.

Using the `UIDevice.orientation` is [no longer supported](https://developer.apple.com/videos/play/wwdc2022/10068/?time=1400) in iOS 16, and I believe this is the API that Detox is [currently using](https://github.com/wix/Detox/blob/master/detox/ios/Detox/Actions/UIDevice%2BDetoxActions.m#L19) for setting orientation. 

### What was the expected behaviour?

Calling `await device.setOrientation('landscape');` should rotate the iOS simulator from portrait to landscape.

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

Build a React Native project using Xcode 14.1. Run a test on an iOS 16.1 simulator which calls `await device.setOrientation('landscape');`.

### In what environment did this happen?

Detox version: 19.12.5
React Native version: 0.70.6 
Node version: 16.4.2
Device model: iPhone 11 Simulator
iOS version: 16.1
macOS version: 13.1
Xcode version: 14.1
Test-runner: jest

**Comment by asafkorem** [comment]
Thank you @mrbrentkelly for bringing this to our attention. Detox is currently utilizing an API that accesses private headers to set the orientation. In order to resolve this issue, we will need to find an alternative API for iOS that can rotate the simulator programmatically. I am currently unsure of how to implement the recommended method (preferredInterfaceOrientation) as it is a property of a view-controller and not the device. I will investigate further but any additional help or contributions from others will be greatly appreciated.

**Comment by mrbrentkelly** [comment]
@asafkorem I've made an attempt at fixing this in the following PR https://github.com/wix/Detox/pull/3843. This [code](https://github.com/wix/Detox/pull/3843/files#diff-254cf136fd404ce481c29a11cbe4d233e32e9bbf6739d80c71defdfc055858c3R14-R17) is what we use in production for setting orientation in a React Native Native Module from iOS 16 onwards.

**Comment by d4vidi** [comment]
@asafkorem can this be closed?

**Comment by asafkorem** [comment]
Closing since the PR was merged and released on [v20.2.2](https://github.com/wix/Detox/releases/tag/20.2.2) 🎉
