### ISSUE TITLE
Android failing to launch on react-native 0.70.6

### ISSUE THREAD

**Issue by matthewparavati** [wix/Detox#3824]
### What happened?

We are trying to bump our project to `react-native: 0.70.x` but are running in to issues on detox. Android doesn't seem to run/launch.

I created a repo of the [DetoxTemplate](https://github.com/matthewparavati/DetoxTemplate) and reproduced the android issue. Since I needed to make changes to get this to work with the latest react-native and detox version, it's possible I'm missing some other changes but this seems to be the same issue that we are running in to with our project. 

iOS built and ran fine but for android, only the build succeed. This is happening in our project as well.

Probably too much/unnecessary details but we _do_ run in to this issue on Circleci for both android and iOS 🤷 but locally iOS is working

### What was the expected behaviour?

Android successfully runs and passes the demo test

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

Repo: [matthewparavati/DetoxTemplate](https://github.com/matthewparavati/DetoxTemplate)
npm install
npm run build:android-release
npm run test:android-release

### In what environment did this happen?

Detox version: 20.1.1
React Native version: 0.70.6
Node version: 14.21.1
Device model: Pixel 5
Android version: 31
Test-runner (select one): jest

### Detox logs

<details><summary>Detox logs</summary>

```
10:58:37.010 detox[53470] i child-process:EXEC_FAIL ""/Users/matthewparavati/Library/Android/sdk/platform-tools/adb" -s emulator-11606 shell "ps | grep \"com\.detoxtemplate$\""" failed with error = ChildProcessError: Command failed: "/Users/matthewparavati/Library/Android/sdk/platform-tools/adb" -s emulator-11606 shell "ps | grep \"com\.detoxtemplate$\""
 `"/Users/matthewparavati/Library/Android/sdk/platform-tools/adb" -s emulator-11606 shell "ps | grep \"com\.detoxtemplate$\""` (exited with error code 1) (code=1), stdout and stderr:

10:58:37.010 detox[53470] i child-process:EXEC_FAIL 
10:58:37.011 detox[53470] i child-process:EXEC_FAIL 
10:58:37.512 detox[53470] i child-process:EXEC_CMD "/Users/matthewparavati/Library/Android/sdk/platform-tools/adb" -s emulator-11606 shell "ps | grep \"com\.detoxtemplate$\""
10:58:38.101 detox[53470] B artifacts-manager onHookFailure
  args: ({"error":"Exceeded timeout of 120000 ms for a hook.\nUse jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test.","hook":"beforeAll"})
10:58:38.103 detox[53470] E artifacts-manager onHookFailure
10:58:38.105 detox[53470] E lifecycle beforeAll
  error: 'Exceeded timeout of 120000 ms for a hook.\n' +
    'Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test.'

 FAIL  e2e/ExampleScreen.e2e.js (122.034 s)
  Example Screen Tests
    ✕ should type into the text field (4 ms)

  ● Example Screen Tests › should type into the text field

    thrown: "Exceeded timeout of 120000 ms for a hook.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      1 | describe('Example Screen Tests', () => {
    > 2 |   beforeAll(async () => {
        |   ^
      3 |     await device.launchApp();
      4 |   });
      5 |

      at ExampleScreen.e2e.js:2:3
      at Object.<anonymous> (ExampleScreen.e2e.js:1:1)

10:58:38.155 detox[53470] i ipc dispatching event to  primary-53468 /tmp/detox.primary-53468  :  reportTestResults , {
  testResults: [
    {
      success: false,
      testFilePath: '/Users/matthewparavati/Code/DetoxTemplate/e2e/ExampleScreen.e2e.js',
      testExecError: undefined,
      isPermanentFailure: false
    }
  ]
}
10:58:38.155 detox[53468] i ipc received event of :  reportTestResults {
  testResults: [
    {
      success: false,
      testFilePath: '/Users/matthewparavati/Code/DetoxTemplate/e2e/ExampleScreen.e2e.js',
      isPermanentFailure: false
    }
  ]
}
10:58:38.155 detox[53468] i ipc dispatching event to socket  :  reportTestResultsDone {
  testResults: [
    {
      success: false,
      testFilePath: '/Users/matthewparavati/Code/DetoxTemplate/e2e/ExampleScreen.e2e.js',
      isPermanentFailure: false
    }
  ]
}
10:58:38.156 detox[53468] i ipc broadcasting event to all known sockets listening to  /tmp/detox.primary-53468  :   sessionStateUpdate {
  testResults: [
    {
      success: false,
      testFilePath: '/Users/matthewparavati/Code/DetoxTemplate/e2e/ExampleScreen.e2e.js',
      isPermanentFailure: false
    }
  ]
}
10:58:38.156 detox[53470] i ipc ## received events ##
10:58:38.156 detox[53470] i ipc detected event reportTestResultsDone {
  testResults: [
    {
      success: false,
      testFilePath: '/Users/matthewparavati/Code/DetoxTemplate/e2e/ExampleScreen.e2e.js',
      isPermanentFailure: false
    }
  ]
}
10:58:38.173 detox[53468] E lifecycle Command failed with exit code = 1:
jest --bail --config e2e/jest.config.js 
```

Subsequent runs showed a slightly different output:
```
FAIL  e2e/ExampleScreen.e2e.js (103.692 s)
  Example Screen Tests
    ✕ should type into the text field (1 ms)

  ● Example Screen Tests › should type into the text field

    PID still not available

      1 | describe('Example Screen Tests', () => {
      2 |   beforeAll(async () => {
    > 3 |     await device.launchApp();
        |                  ^
      4 |   });
      5 |
      6 |   it('should type into the text field', async () => {

      at ExampleScreen.e2e.js:3:18
      at asyncGeneratorStep (../node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (../node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)
      at ../node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:7
      at ../node_modules/@babel/runtime/helpers/asyncToGenerator.js:19:12
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
```

</details>

**Comment by asafkorem** [comment]
Hi @matthewparavati, RN .70 is not yet officially supported by Detox, we're not testing this version yet (see: https://github.com/wix/Detox#react-native).
We will certainly check that once we work on the v.70 upgrade for our tests suite. Thanks for the report.
You might find it helpful to join our [Discord server](https://discord.gg/CkD5QKheF5), perhaps someone has already solved it in his project.

**Comment by matthewparavati** [comment]
Hey @asafkorem, thanks for the response. Yeah, I saw that. We were trying to upgrade to expo 47 and RN 0.70.6 and everything seems to be working pretty well for us except our detox tests.

Thanks, I'll check it out 🤞

**Comment by matthewparavati** [comment]
@asafkorem I see some "issues" that look to be tracking detox's work on the RN 70 updates, is there a potential timeline on those upgrades being worked on and/or completed?

**Comment by d4vidi** [comment]
@matthewparavati Please track this under #3732

**Comment by matthewparavati** [comment]
Updated with some device logs about the specifics of the crash

**Comment by matthewparavati** [comment]
Closing this as our android builds are working again. I don't recall if I made any specific changes or if it was a result of a more recent detox update that officially supported RN 0.70.x 😅
