### ISSUE TITLE
[Website] Create a visual regression test suite

### ISSUE THREAD

**Issue by noomorph** [wix/Detox#3838]
## Description

- [x] Set up a test suite in the `website/` project using [Percy.io](https://percy.io).
- [ ] Create a corresponding step in [.github/workflows/website.html](https://github.com/wix/Detox/blob/master/.github/workflows/website.yml)

![Promo-image](https://percy.io/cdn-cgi/image/quality=85,width=1536,fit=scale-down/static/images/marketing/homepage_2x.png)

We could start from a simple set of test pages:

- home page
- documentation (demo page)
- blog page
- showcase page

Reportedly, the easiest way to start is **Percy Snapshots**:

https://docs.percy.io/docs/percy-snapshot

You can see a similar use case here:

* https://github.com/rohit-gohri/redocusaurus/tree/main/website
* https://github.com/rohit-gohri/redocusaurus/blob/main/website/package.json#L22
* https://github.com/rohit-gohri/redocusaurus/blob/main/website/snapshots.js

Although, I'd advise sticking with `snapshots.yml` (YAML format) just like the docs say.

**Comment by noomorph** [comment]
@moutro, so what is left now is to create a GitHub actions step for that. Please make it conditional, e.g., by using [this advice](https://stackoverflow.com/a/70711156). The condition would be: **if there are changes in `website/src/css` files, run the regression test step (percy ...).**

**Comment by moutro** [comment]
> @moutro, so what is left now is to create a GitHub actions step for that. Please make it conditional, e.g., by using [this advice](https://stackoverflow.com/a/70711156). The condition would be: **if there are changes in `website/src/css` files, run the regression test step (percy ...).**

Thanks for the doc and instructions. Created a GH Actions step - see PR#3866 linked here for review.
