### ISSUE TITLE
Build error with RN 0.71

### ISSUE THREAD

**Issue by badsyntax** [wix/Detox#3846]
### What happened?

I created a fresh 0.71 project, then do an Android build and get the following error:

`detox build --configuration android.emu.debug`:

```console
> Task :app:processDebugAndroidTestManifest FAILED
/Users/richardwillis/Projects/chevin/MyProject/android/app/build/intermediates/tmp/manifest/androidTest/debug/tempFile1ProcessTestManifest14921285148522303281.xml:27:9-33:20 Error:
        android:exported needs to be explicitly specified for element <activity#androidx.test.core.app.InstrumentationActivityInvoker$BootstrapActivity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.
/Users/richardwillis/Projects/chevin/MyProject/android/app/build/intermediates/tmp/manifest/androidTest/debug/tempFile1ProcessTestManifest14921285148522303281.xml:34:9-40:20 Error:
        android:exported needs to be explicitly specified for element <activity#androidx.test.core.app.InstrumentationActivityInvoker$EmptyActivity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.
/Users/richardwillis/Projects/chevin/MyProject/android/app/build/intermediates/tmp/manifest/androidTest/debug/tempFile1ProcessTestManifest14921285148522303281.xml:41:9-47:20 Error:
        android:exported needs to be explicitly specified for element <activity#androidx.test.core.app.InstrumentationActivityInvoker$EmptyFloatingActivity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.
```

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 20.1.1
React Native version: 0.71.0
Has Fabric (React Native's new rendering system) enabled: (yes/no)  Yes
Node version: 
Device model: 
Android version: 
Test-runner (select one): jest / other

**Comment by d4vidi** [comment]
Largely speaking, doesn't seem Detox-related :/

**Comment by badsyntax** [comment]
If I disable `androidTestImplementation('com.wix:detox:+')` the android build works again, so it seems detox related to me.

**Comment by badsyntax** [comment]
The README states:

> Future versions are most likely supported, but have not been tested yet. Please open issues if you find specific issues with newer React Native versions.

I am thus trying to help by opening an issue. Have I done the wrong thing? Do you require any other information? Do you want me to create an example repo? I don't know why you have closed the issue with your comment, very odd.

**Comment by d4vidi** [comment]
@badsyntax Oh sorry for the misunderstanding. I didn't close the issue, I just marked it as an issue preferable for posting/discussing on SO or discord; Our bot closes the issue automatically.

Have you trying taking up on the suggestion action in the error's description? - `Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.`

**Comment by alexeyfof** [comment]
Same here. Tested in brand new app. Please reopen the ticket or provide the solution.

**Comment by luisfuertes** [comment]
I had this same problem and it was because I had an error in the "build.gradle" configuration

Make sure that put this step on "allprojects" repositories instead on "buildscripts" repositories, i fix that and now all works fine.

**Comment by badsyntax** [comment]
@luisfuertes thank you, i can confirm that change has fixed it for me. in hindsight it seems like a silly mistake on my part, i guess the docs could be updated to support the new layout of build.gradle in 0.71, which is:

<details><summary>Working build.gradle</summary>

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 29
        compileSdkVersion = 32
        targetSdkVersion = 32

        // https://wix.github.io/Detox/docs/introduction/project-setup
        kotlinVersion = "1.7.20"

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.3.1")
        classpath("com.facebook.react:react-native-gradle-plugin")
        // https://wix.github.io/Detox/docs/introduction/project-setup
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion")
    }
}

allprojects {
    repositories {
        maven {
            // https://wix.github.io/Detox/docs/introduction/project-setup
            url("$rootDir/../node_modules/detox/Detox-android")
        }
    }
}
```

</details>

**Comment by jowparks** [comment]
> I had this same problem and it was because I had an error in the "build.gradle" configuration
> 
> Make sure that put [this step](https://wix.github.io/Detox/docs/introduction/project-setup#41-patching-build-scripts) on "allprojects" repositories instead on "buildscripts" repositories, i fix that and now all works fine.

FWIW this got me too, fixing the location of the maven detox stuff solved my issue.
