### ISSUE TITLE
All specs not running but detox exiting successfully when using --retries.

### ISSUE THREAD

**Issue by andrewlmurray** [wix/Detox#3848]
### What happened?

Hi guys - detox is a great project thanks for creating it. 

We run with `--maxWorkers=3 --retries = 1` to deal with occasional flakyness in CI.

We've been using it for years - upon updating the newest version I was running our tests manually and I noticed something odd. 

1. our first spec passed
2. our second spec failed and was retried
3. our second spec passed on retry

detox immediately exited after the second spec passed with a successful return code. 

This struck me as odd - so I pulled our CI logs and parsed our last 100 detox runs, I noticed that many times we were reporting a successful run, but not actually running all of our specs. 

Every time this happens I see the same pattern. A test retries then succeeds, then the run ends prematurely with a successful exit code. 

Are we holding it wrong? Is `--retries` dangerous?

Thanks!

### What was the expected behaviour?

All the specs should run when a test is retried. 

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 20.1.1 
React Native version: 0.70.6
Has Fabric (React Native's new rendering system) enabled: no
Node version: 16.15.0
Device model: iPhone SE (sim)
iOS version: 16.2
macOS version: 13.1
Xcode version: 14.2
Test-runner (select one): jest 29.3.1

**Comment by andrewlmurray** [comment]
Actually going to do some more digging on this to make sure this isn't something on our end w/ our task runner and to provide more logs - I'll reopen if this indeed looks like detox's fault.

**Comment by d4vidi** [comment]
Thanks @andrewlmurray, please be sure to post back

**Comment by noomorph** [comment]
> our first spec passed
> our second spec failed and was retried
> our second spec passed on retry

Sounds legit. E.g. you have 2 files: `test1` and `test2`:

1. `test1` (OK) and `test2` (FAIL)
2. `test2` (OK).

The overall result: OK.

🤔 Isn't that so?

**Comment by noomorph** [comment]
If you have more than two files, check if you don't have `--bail` option turned on in your test runner. I think retries are not compatible with `bail` at the moment, because it never occurred to me that this scenario is meant to be used with retries. Should I reconsider that? 🤔
