### ISSUE TITLE
Test without reinstalling the app

### ISSUE THREAD

**Issue by alissa-ferro** [wix/detox#385]
Is there a way for me to test my app without reinstalling the app? 

Here is my problem, i have another app that sets the endpoint to my developer environment, but doesn't work when I uninstall the app. 
A workaround that I see is accessing this other app after my app is installed, is there an easier way?

**Comment by vasyas** [comment]
Passing --reuse while starting tests should do the trick.

**Comment by alissa-ferro** [comment]
It does! Thanks
