### ISSUE TITLE
Can not see screenshots and video in artifacts folder but log file appear just fine

### ISSUE THREAD

**Issue by pacozaa** [wix/Detox#3850]
### Description

I am currently setting up a new project that uses Detox `20.1.1` and running the test.

Here is a snippet of my config from `.detoxrc.json`
```
"artifacts": {
        "rootDir": ".artifacts",
        "plugins": {
            "instruments": { "enabled": false },
            "log": { "enabled": true },
            "uiHierarchy": "enabled",
            "screenshot": {
                "shouldTakeAutomaticSnapshots": true,
                "keepOnlyFailedTestsArtifacts": true,
                "takeWhen": {
                    "testStart": true,
                    "testDone": true
                }
            },
            "video": {
                "android": {
                    "bitRate": 4000000
                },
                "simulator": {
                    "codec": "hevc"
                }
            }
        }
    },
```

The log file appears in `.artifacts` just fine and shows that the config file is read 

but somehow screenshot and video isn't in the `.artifacts` folder. I try to change different configs in the screenshot and video, but it still doesn't work.

Please help

### Your environment

Detox version: 20.1.1
React Native version: 0.70.6
Node version: v16.14.1
Device model: Simulator iPhone 14 iOS 16.2
OS: macOS Ventura
Test-runner (select one): jest

**Comment by noomorph** [comment]
Does your test fail?

**Comment by pacozaa** [comment]
@noomorph Thank you for the fast response.

 I tried both "fail" and "success" cases. Either case doesn't show the screenshot.

I also tried "screenshot": "all", "video":"all" same result, no photo or video only logs

**Comment by noomorph** [comment]
Could you share your `detox.trace.json` log please?

**Comment by pacozaa** [comment]
Here is my `detox.trace.json` https://gist.github.com/pacozaa/c528875fb26cfdb3051c90a9c994750f

**Comment by noomorph** [comment]
> Test-runner (select one): jest

Why lie? 😆

**Comment by noomorph** [comment]
Duplicate of #3730.

**Comment by noomorph** [comment]
Let's continue the necessary discussion in the relevant issue.
