### ISSUE TITLE
Runtime Error when running jest - DetoxRuntimeError: Detox worker instance has not been installed in this context (DetoxPrimaryContext)

### ISSUE THREAD

**Issue by IanMichaels118** [wix/Detox#3855]
### What happened?

I have used the detox documentation to set up the environment and configuration files, to use with **Jest** in **React Native** :

Getting started - https://wix.github.io/Detox/docs/introduction/getting-started
RN project setup - https://wix.github.io/Detox/docs/introduction/project-setup
Jest - https://wix.github.io/Detox/docs/19.x/guide/jest

I have used a basic starter test just to see if jest runs correctly without errors:

`const detox = require('detox');

const { device } = detox;

describe('Example', () => {
  beforeAll(async () => {
    await device.launchApp();
  });

  beforeEach(async () => {
    await device.reloadReactNative();
  });

  it('should test something', async () => {
    //
  });
});`

### What was the expected behaviour?

I expected to test to run without errors, as this is code from the boiler plate starter.test.js

After running "jest", the following error occurred: `DetoxRuntimeError: Detox worker instance has not been installed in this context (DetoxPrimaryContext)`

There is no init file created during set up (as there is for Mocha). 

 As for using `detox.installWorker()` ... there doesn't appear to be such property on the detox object (see screenshot)

images.githubusercontent.com/91470918/213212850-a7498c3e-0cec-4c35-b98a-981b6690b326.png">

Can someone point me in the right direction please?
<img width="1287" alt="Screenshot 2023-01-18 at 13 06 02" src="https://user-

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### In what environment did this happen?

Detox version: "20.1.1"
React Native version: "0.68.5"
Has Fabric (React Native's new rendering system) enabled: yes
Node version: v16.16.0
Test-runner (select one): jest

### Detox logs

<details><summary>Detox logs</summary>

```
15:22:20.294 detox[26931] B lifecycle node_modules/.bin/detox test ... --configuration ios.sim.debug --loglevel trace
  data: {
    "id": "8e0c4dc9-c6f4-9143-9b48-d807910b0582",
    "detoxConfig": {
      "configurationName": "ios.sim.debug",
      "apps": {
        "default": {
          "type": "ios.app",
          "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/YOUR_APP.app",
          "build": "xcodebuild -workspace ios/YOUR_APP.xcworkspace -scheme YOUR_APP -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build"
        }
      },
      "artifacts": {
        "rootDir": "artifacts/ios.sim.debug.2023-01-18 15-22-20Z",
        "plugins": {
          "log": {
            "enabled": false,
            "keepOnlyFailedTestsArtifacts": false
          },
          "screenshot": {
            "enabled": true,
            "shouldTakeAutomaticSnapshots": false,
            "keepOnlyFailedTestsArtifacts": false
          },
          "video": {
            "enabled": false,
            "keepOnlyFailedTestsArtifacts": false
          },
          "instruments": {
            "enabled": false,
            "keepOnlyFailedTestsArtifacts": false
          },
          "uiHierarchy": {
            "enabled": false,
            "keepOnlyFailedTestsArtifacts": false
          }
        }
      },
      "behavior": {
        "init": {
          "keepLockFile": false,
          "reinstallApp": true,
          "exposeGlobals": true
        },
        "cleanup": {
          "shutdownDevice": false
        },
        "launchApp": "auto"
      },
      "cli": {
        "configuration": "ios.sim.debug",
        "loglevel": "trace"
      },
      "device": {
        "type": "ios.simulator",
        "device": {
          "type": "iPhone 12"
        }
      },
      "logger": {
        "level": "trace",
        "overrideConsole": true,
        "options": {
          "showLoggerName": true,
          "showPid": true,
          "showLevel": false,
          "showMetadata": false,
          "basepath": "/Users/IanM/Desktop/118118Money.AllNewMobileApp/node_modules/detox/src",
          "prefixers": {},
          "stringifiers": {}
        }
      },
      "testRunner": {
        "retries": 0,
        "forwardEnv": false,
        "bail": false,
        "jest": {
          "setupTimeout": 120000,
          "teardownTimeout": 30000,
          "retryAfterCircusRetries": false,
          "reportWorkerAssign": true
        },
        "args": {
          "$0": "jest",
          "_": [
            "..."
          ],
          "config": "e2e/jest.config.js",
          "--": []
        }
      },
      "session": {
        "autoStart": true,
        "debugSynchronization": 10000
      }
    },
    "detoxIPCServer": "primary-26931",
    "testResults": [],
    "testSessionIndex": 0,
    "workersCount": 0
  }
15:22:20.339 detox[26931] i ipc Server path not specified, so defaulting to ipc.config.socketRoot + ipc.config.appspace + ipc.config.id /tmp/detox.primary-26931
15:22:20.341 detox[26931] i ipc starting server on  /tmp/detox.primary-26931 
15:22:20.342 detox[26931] i ipc starting TLS server false
15:22:20.342 detox[26931] i ipc starting server as Unix || Windows Socket
15:22:20.352 detox[26931] i ws-server Detox server listening on localhost:60982...
15:22:20.358 detox[26931] i lifecycle Serialized the session state at: /private/tmp/8e0c4dc9-c6f4-9143-9b48-d807910b0582.detox.json
15:22:20.361 detox[26931] B lifecycle jest --config e2e/jest.config.js ...
jest-haste-map: Watchman crawl failed. Retrying once with node crawler.
  Usually this happens when watchman isn't running. Create an empty `.watchmanconfig` file in your project's root folder or initialize a git or hg repository in your project.
  Error: Watchman error: std::__1::system_error: open: /Users/IanM/Desktop/118118Money.AllNewMobileApp: Operation not permitted. Make sure watchman is running for this project. See https://facebook.github.io/watchman/docs/troubleshooting.
Determining test suites to run...15:22:32.369 detox[26934] i ipc Service path not specified, so defaulting to ipc.config.socketRoot + ipc.config.appspace + id 
15:22:32.379 detox[26934] i ipc requested connection to  primary-26931 /tmp/detox.primary-26931
15:22:32.380 detox[26934] i ipc Connecting client on Unix Socket : /tmp/detox.primary-26931
15:22:32.382 detox[26931] i ipc ## socket connection to server detected ##
15:22:32.383 detox[26934] i ipc retrying reset
15:22:32.385 detox[26934] i ipc dispatching event to  primary-26931 /tmp/detox.primary-26931  :  registerContext , { id: 'secondary-26934' }
15:22:32.391 detox[26931] i ipc received event of :  registerContext { id: 'secondary-26934' }
15:22:32.392 detox[26931] i ipc dispatching event to socket  :  registerContextDone { testResults: [], testSessionIndex: 0 }
15:22:32.398 detox[26934] i ipc ## received events ##
15:22:32.399 detox[26934] i ipc detected event registerContextDone { testResults: [], testSessionIndex: 0 }
15:22:32.403 detox[26934] i user                                                                                 
=========================  THE NEW JOURNEY BEGINS  =============================
                                                                                
                https://wix.github.io/Detox/docs/guide/migration                
                                                                                
        Sorry to say that Detox 20 comes without old adapters for Jest.         
   You have to rearrange your init code before you can continue your journey.   
                                                                                
           Navigate to the link and follow the migration guide steps.           
                                                                                
                                Sincerely yours,                                
                                  Detox team.                                   
                                                                                
=========================  THE NEW JOURNEY BEGINS  =============================
                                                                                
                                                                                
  origin: at node_modules/detox/runners/deprecation.js:25:9
15:22:32.406 detox[26934] i user Error: An error occurred while adding the reporter at path "/Users/IanM/Desktop/118118Money.AllNewMobileApp/node_modules/detox/runners/jest/streamlineReporter.js".
Please follow the migration guide:
https://wix.github.io/Detox/docs/guide/migration


  origin: at node_modules/jest-cli/build/cli/index.js:164:15
15:22:32.433 detox[26931] E lifecycle Command failed with exit code = 1:
jest --config e2e/jest.config.js ...
15:22:32.434 detox[26931] i ws-server Detox server has been closed gracefully
15:22:32.436 detox[26931] i ipc socket disconnected secondary-26934
15:22:32.437 detox[26931] E lifecycle node_modules/.bin/detox test ... --configuration ios.sim.debug --loglevel trace
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by IanMichaels118** [comment]
> Why do you use docs for version 19? Your error message clearly implies that you have version 20 installed. If you use docs and product with different major versions, it is no surprise that something does not work.

My apologies. I linked to the wrong docs. I did indeed use version 20 docs during the set up. Problem still persists.

**Comment by lmasneri** [comment]
Same issue

**Comment by noomorph** [comment]
@lmasneri If the issue is the same, it means you haven't completed the migration guide.

**Comment by lmasneri** [comment]
> @lmasneri If the issue is the same, it means you haven't completed the migration guide.
> 
> https://wix.github.io/Detox/docs/guide/migration#new-jest-config

Thank you I will look at this!

**Comment by noomorph** [comment]
@lmasneri This is weirder, but the chances are you have an issue with jest config. Run Detox tests with `--showConfig` so that Jest prints its resolved config and let's check

**Comment by micahdasMA** [comment]
@noomorph I am also having this issue. 

Here is what my config looks like 

> {
  "configs": [
    {
      "automock": false,
      "cache": true,
      "cacheDirectory": "/private/var/folders/md/m_dqy0bs4fq6fzwr4z454jz00000gn/T/jest_dx",
      "clearMocks": false,
      "coveragePathIgnorePatterns": [
        "/node_modules/"
      ],
      "cwd": "/Users/micah/app",
      "detectLeaks": false,
      "detectOpenHandles": false,
      "errorOnDeprecated": false,
      "extensionsToTreatAsEsm": [],
      "fakeTimers": {
        "enableGlobally": false
      },
      "forceCoverageMatch": [],
      "globalSetup": "/Users/micah/app/node_modules/detox/runners/jest/globalSetup.js",
      "globalTeardown": "/Users/micah/app/node_modules/detox/runners/jest/globalTeardown.js",
      "globals": {},
      "haste": {
        "defaultPlatform": "ios",
        "platforms": [
          "android",
          "ios",
          "native"
        ]
      },
      "id": "10d45e00ebe600ac955153e1cd140ef2",
      "injectGlobals": true,
      "moduleDirectories": [
        "node_modules"
      ],
      "moduleFileExtensions": [
        "js",
        "mjs",
        "cjs",
        "jsx",
        "ts",
        "tsx",
        "json",
        "node"
      ],
      "moduleNameMapper": [],
      "modulePathIgnorePatterns": [],
      "openHandlesTimeout": 1000,
      "prettierPath": "prettier",
      "resetMocks": false,
      "resetModules": false,
      "restoreMocks": false,
      "rootDir": "/Users/micah/app",
      "roots": [
        "/Users/micah/app"
      ],
      "runner": "/Users/micah/app/node_modules/jest-runner/build/index.js",
      "sandboxInjectedGlobals": [],
      "setupFiles": [
        "/Users/micah/app/node_modules/react-native/jest/setup.js"
      ],
      "setupFilesAfterEnv": [],
      "skipFilter": false,
      "slowTestThreshold": 5,
      "snapshotFormat": {
        "escapeString": false,
        "printBasicPrototype": false
      },
      "snapshotSerializers": [],
      "testEnvironment": "/Users/micah/app/node_modules/detox/runners/jest/testEnvironment/index.js",
      "testEnvironmentOptions": {},
      "testLocationInResults": false,
      "testMatch": [
        "/Users/micah/app/e2e/**/*.test.ts"
      ],
      "testPathIgnorePatterns": [
        "/node_modules/"
      ],
      "testRegex": [],
      "testRunner": "/Users/micah/app/node_modules/jest-circus/runner.js",
      "transform": [
        [
          "^.+\\.(js|ts|tsx)$",
          "/Users/micah/app/node_modules/babel-jest/build/index.js",
          {}
        ],
        [
          "^.+\\.(bmp|gif|jpg|jpeg|mp4|png|psd|svg|webp)$",
          "/Users/micah/app/node_modules/react-native/jest/assetFileTransformer.js",
          {}
        ]
      ],
      "transformIgnorePatterns": [
        "node_modules/(?!((jest-)?react-native|@react-native(-community)?)/)"
      ],
      "watchPathIgnorePatterns": []
    }
  ],
  "globalConfig": {
    "bail": 0,
    "changedFilesWithAncestor": false,
    "ci": false,
    "collectCoverage": false,
    "collectCoverageFrom": [],
    "coverageDirectory": "/Users/micah/app/coverage",
    "coverageProvider": "babel",
    "coverageReporters": [
      "json",
      "text",
      "lcov",
      "clover"
    ],
    "detectLeaks": false,
    "detectOpenHandles": false,
    "errorOnDeprecated": false,
    "expand": false,
    "findRelatedTests": false,
    "forceExit": false,
    "globalSetup": "/Users/micah/app/node_modules/detox/runners/jest/globalSetup.js",
    "globalTeardown": "/Users/micah/app/node_modules/detox/runners/jest/globalTeardown.js",
    "json": false,
    "lastCommit": false,
    "listTests": false,
    "logHeapUsage": false,
    "maxConcurrency": 5,
    "maxWorkers": 1,
    "noStackTrace": false,
    "nonFlagArgs": [],
    "notify": false,
    "notifyMode": "failure-change",
    "onlyChanged": false,
    "onlyFailures": false,
    "openHandlesTimeout": 1000,
    "passWithNoTests": false,
    "projects": [],
    "reporters": [
      [
        "/Users/micah/app/node_modules/detox/runners/jest/reporter.js",
        {}
      ]
    ],
    "rootDir": "/Users/micah/app",
    "runTestsByPath": false,
    "seed": 1877328669,
    "skipFilter": false,
    "snapshotFormat": {
      "escapeString": false,
      "printBasicPrototype": false
    },
    "testFailureExitCode": 1,
    "testPathPattern": "",
    "testSequencer": "/Users/micah/app/node_modules/@jest/test-sequencer/build/index.js",
    "testTimeout": 120000,
    "updateSnapshot": "new",
    "useStderr": false,
    "verbose": true,
    "watch": false,
    "watchAll": false,
    "watchman": true,
    "workerThreads": false
  },
  "version": "29.5.0"
}

**Comment by noomorph** [comment]
@micahdasMA the config looks relatively good. are you sure you get the same error? could you record Detox log artifacts also?

**Comment by micahdasMA** [comment]
@noomorph the error is very slightly different - `DetoxRuntimeError: Detox worker instance has not been installed in this context (DetoxPrimaryContext).`

I also filed this issue here with some more information since I wasn't sure if this thread was dead or not https://github.com/wix/Detox/issues/4087

**Comment by dmaziar** [comment]
We use playwright with detox. For us, the reason for failure was `await detoxCleanup();` So commenting this out fixed the problem. Maybe it will be helpful for others.
