### ISSUE TITLE
Image picker mocking 

### ISSUE THREAD

**Issue by usandaBolder** [wix/Detox#3856]
### Description

I am new testing and detox and the App i am automating is trying to upload a picture and i cant seem to pull trigger on this 

metro.config.js

![Screenshot 2023-01-18 at 23 17 58](https://user-images.githubusercontent.com/123025355/213297355-6d5eaa86-67a2-4f6b-9de8-d8a69d5ddc0f.png)

imagePickerProvider.tsx
![Screenshot 2023-01-18 at 23 22 55](https://user-images.githubusercontent.com/123025355/213297813-568276e8-1e02-4e76-9d91-9b2d649e1697.png)

imagePickerProvider.mock.tsx
![Screenshot 2023-01-18 at 23 24 33](https://user-images.githubusercontent.com/123025355/213298193-5d61db94-c1b9-436a-9e98-2e84aabae2a4.png)
![Screenshot 2023-01-18 at 23 26 10](https://user-images.githubusercontent.com/123025355/213298433-f0b3745a-dbc2-45b2-bf01-256f6b4c31b7.png)

and this is my test and i want to upload the image on step 3
![Screenshot 2023-01-18 at 23 28 38](https://user-images.githubusercontent.com/123025355/213298997-d0b67042-2b58-45ea-82cb-ec07bca11bd1.png)

this is the app
stage 1  click on " Add Image"
![Screenshot 2023-01-18 at 23 30 28](https://user-images.githubusercontent.com/123025355/213299306-e3b5d8ce-40d6-418f-82b5-57eb51891ac0.png)
 Stage 2 click "photo gallery" well i guess this is where the mocking should be happening and i am not sure if i applied the mock work i saw online correctly but i cant use it
![Screenshot 2023-01-18 at 23 32 17](https://user-images.githubusercontent.com/123025355/213299702-8821f9a9-e07b-4b75-ae0d-22b5038dbcbe.png)

### Your environment

Detox version: 
React Native version: 
Node version: 
Device model: 
OS: 
Test-runner (select one): jest / other

**Comment by asafkorem** [comment]
Hey @usandaBolder, just checking, did you run your app with `APP_MODE=mocked`?

**Comment by usandaBolder** [comment]
Hey @asafkorem  i run my metro with  `RN_SRC_EXT=e2e.js react-native start`

**Comment by TharunGongati** [comment]
@usandaBolder is it working ? i mean triggering the mock or not when we are uploading the picture without opening the emulator local gallery
