### ISSUE TITLE
how to setup userParams in Detox 20.1.2

### ISSUE THREAD

**Issue by eilinwis** [wix/Detox#3859]
### Description

Hello!
i'm updating Detox from 19.13.0 to 20.1.2
i've got custom settings to setup userParams before tests launch
it looks like this:

```
const configuration = require('detox/src/configuration')

const FixtureManagerAndroid = require('./fixtures/FixtureManager.android')
const FixtureManagerIOS = require('./fixtures/FixtureManager.ios')

let fixtureManager = null

beforeAll(async () => {
  params = { launchApp: false }
  resolvedConfig = await configuration.composeDetoxConfig({
    override: config,
    userParams: params,
  })
  usedConfigurationName = resolvedConfig.cliConfig.configuration

  detoxInstance = await detox.init(config, params)
  fixtureManager = usedConfigurationName.includes('ios')
    ? new FixtureManagerIOS(config.configurations[usedConfigurationName].fixtures)
    : new FixtureManagerAndroid(config.configurations[usedConfigurationName].fixtures, detoxInstance.device)
  fixtureManager.subscribeToDeviceEvents(detoxInstance.device.deviceDriver.emitter)
})
```

And this code causes error:

`  ● Test suite failed to run

    TypeError: Cannot redefine property: __RESOLVED_TMP_DIR__
        at Function.defineProperty (<anonymous>)

      1 | const { device } = require('detox')
    > 2 | const configuration = require('detox/src/configuration')
`

Looks like that that function can't reach those fields (override and userParams)

And if we compare two configuration files from detox 20 and 19 we can see that userParams is gone!
19.13.0
```
async function composeDetoxConfig({
  cwd = process.cwd(),
  argv,
  override,
  userParams,
})
```

20.1.2
```
async function composeDetoxConfig({
  cwd = process.cwd(),
  argv = undefined,
  testRunnerArgv = undefined,
  errorComposer = new DetoxConfigErrorComposer(),
  override = undefined,
}) {

```
so i'm asking for help to find a solution to setup userParams

Here's the changes
https://github.com/wix/Detox/commit/91e011f059d7a40cfc12b44fefecac71f114d4a6

### Your environment

Detox version: 20.1.2
React Native version: 0.68.5
Node version: 16.14.2
Device model: iPhone 14 Simulator
OS: 16.1
Test-runner (select one): jest

**Comment by eilinwis** [comment]
@noomorph

**Comment by noomorph** [comment]
I'll try to look next week.

**Comment by eilinwis** [comment]
Thank you for responding!
We solve the problem ourselves
Here's how:

`const { device } = require('detox')
const { resolveConfig } = require('detox/internals')

const config = require('../.detoxrc.js')
const FixtureManagerAndroid = require('./fixtures/FixtureManager.android')
const FixtureManagerIOS = require('./fixtures/FixtureManager.ios')

let fixtureManager = null
beforeAll(async () => {
  params = { launchApp: false }
  const resolvedConfig = await resolveConfig()
  usedConfigurationName = resolvedConfig.cli.configuration
  const isIOS = usedConfigurationName.includes('ios')

  fixtureManager = isIOS
    ? new FixtureManagerIOS(config.configurations[usedConfigurationName].fixtures)
    : new FixtureManagerAndroid(config.configurations[usedConfigurationName].fixtures, device)
  fixtureManager.subscribeToDeviceEvents(device.deviceDriver.emitter)
})`
