### ISSUE TITLE
Jest is hanging after both Detox tests passed/failed

### ISSUE THREAD

**Issue by todorone** [wix/detox#387]
#### Description
Jest is hanging after both Detox tests passed/failed.

#### Steps to Reproduce
Running default testing sample file results in Jest never complete node process.
Maybe current `detox.cleanup()` implementation is not enough to indicate Jest to finish process?

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 5.9.2
* Node: 8.6.0
* Device: iPhone 6 Simulator
* Xcode: 9.1
* macOS: 10.13

**Comment by ferrannp** [comment]
This is the same as https://github.com/wix/detox/issues/368. You can use `forceExit: true` when running Jest for now...

**Comment by todorone** [comment]
@ferrannp 
Thanks!
