### ISSUE TITLE
While i try to install mocha then configuration is not for mocha but for jest: 

### ISSUE THREAD

**Issue by jstawow** [wix/Detox#3876]
### What happened?

precondition:
detox is installed in devDep
mocha is installed in devDep
detox-cli is installed in global

While i try to install mocha then configuration is not for mocha but for jest: output below.
npx detox init -r mocha
Created a file at path: .detoxrc.js
Created a file at path: e2e/jest.config.js
Created a file at path: e2e/starter.test.js

What i tried:
different installation of lib: by npm and yarn as well, i mean that i tried both: yarn and npm for all libs

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### In what environment did this happen?

Detox version: 20.1.2
React Native version: 
Has Fabric (React Native's new rendering system) enabled: (yes/no) 
Node version: v14.17.6
npm: 8.9.0
yarn: 1.22.18
Test-runner (select one): jest / mocha

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by noomorph** [comment]
Detox 20+ does not support Mocha.

There is a discussion in https://github.com/wix/Detox/issues/3772 if someone wants to try to create a third-party integration detox-mocha.
