### ISSUE TITLE
Add support for accessibilityActions

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#3882]
### Describe your idea

(Opened in retrospect for #3877)
Introduce an element-action API which would invoke its potential [`accessibilityActions`](https://reactnative.dev/docs/accessibility#accessibility-actions) specified action.

Example:

```js
// Component
<TouchableOpacity testID="button" accessibilityActions={[{ name: 'activate', label: 'activate' }]}>
  // ...
</TouchableOpacity>

// Test
await element(by.id('button')).performAccessibilityAction('activate');
```

**Comment by kaibarnes** [comment]
Hi @d4vidi. Just dropping a reminder here as there haven't been any updates on my PR for this ticket.
Please let me know if there's anything else you need so we can proceed with it.
