### ISSUE TITLE
[Epic] React Native .71 Compliance

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#3884]
```[tasklist]
- [ ] #4066
- [ ] #4067
- [ ] #4068
- [ ] #4069
- [ ] https://github.com/wix/Detox/issues/4119
- [ ] #4070
```

Related:
#3869, #3867, #3720 (new architecture)

**Comment by agent-0028** [comment]
Hey folks! Thanks for all the hard work on this "new architecture" business. What a journey eh?

I have a pretty large set of tests that was working fine before we upgraded to `0.70.4` with the fabric renderer enabled.

I got all excited when I saw the progress y'all are making and I did a spike to upgrade all the Detox related things.

I believe I am currently getting the exact same failure mode as described here by @tarikpnr 
https://github.com/wix/Detox/issues/3949

If there any confirmation from the folks working on this that we would expect Detox to work when Metro shows something like this:
` {"fabric":true,"initialProps":{"concurrentRoot":true},"rootTag":1}`

We are doing the documented thing and installing our pods thusly:
`RCT_NEW_ARCH_ENABLED=1 bundle exec pod install`

**Comment by d4vidi** [comment]
Hey @agent-0028, we're planning to start working on it within the current quarter (i.e. by June).

**Comment by venkateshrippling** [comment]
Is there an ETA on wrapping this EPIC as in a due-date @d4vidi

**Comment by d4vidi** [comment]
> Is there an ETA on wrapping this EPIC as in a due-date @d4vidi

It's generally unreasonable to give ETA's when it comes to open source project, but since this is mission-critical to us I could estimate that within 1-2 weeks.

**Comment by venkateshrippling** [comment]
@asafkorem @d4vidi is it 100% done or are there any pending things to wrap up? Because @d4vidi  marked it as completed.
