### ISSUE TITLE
Detox Server Logs not visible in output stream

### ISSUE THREAD

**Issue by Zemotacqy** [wix/Detox#3886]
### What happened?

- When we start detox server in our machine using the command:
```
❯ detox run-server --port 12345 --loglevel trace
Detox server listening on localhost:12345...

```
- Logs describing websocket connections do not appear in the output stream. The only logline that appears is that of server listening on port `P`.
- Upon, debugging, I was able to tail the logs from the `.jsonl` files
```
❯ tail -f /private/var/folders/22/9dxnk2js3274f0l_64mmd8bw0000gn/T/3d51e6cc-b9a1-a330-128b-5e0b926e9e44.76153.detox.jsonl
{"name":"detox","hostname":"ManishRanjan-C02YJ2THJHC8","pid":76153,"level":10,"cat":"ws-client,ws","ph":"i","tid":0,"data":"{\"type\":\"reactNativeReload\",\"params\":{},\"messageId\":-1000}","msg":"send message","time":"2023-01-31T06:12:13.574Z","v":0}
{"name":"detox","hostname":"ManishRanjan-C02YJ2THJHC8","pid":76153,"level":10,"cat":"ws-client,ws","ph":"i","tid":0,"data":"{\"messageId\":-1000,\"type\":\"ready\",\"params\":{}}\n ","msg":"get message","time":"2023-01-31T06:12:13.847Z","v":0}
{"name":"detox","hostname":"ManishRanjan-C02YJ2THJHC8","pid":76153,"level":10,"cat":"device","ph":"E","tid":0,"success":true,"msg":"reloadReactNative","time":"2023-01-31T06:12:13.847Z","v":0}
...
```
- The issue is that connection/ws messages to/from detox server are not being visible in the output stream.

### What was the expected behaviour?

We should be able to see the detox server connection/messages logs in the output stream of the detox server process itself.

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Help us reproduce this issue!

- Install detox globally using npm.
- Start detox server using the command with trace loglevel: `detox run-server --port 12345 --loglevel trace`
- Try running detox android tests with the following detox config:
```
  "session":{
    "server":"ws://localhost:12345"
  },
```
- Monitor the output stream of detox server process. Look out for logs depicting websocket messages.

### In what environment did this happen?

Detox version: 20.1.2
React Native version: 0.71.0
Has Fabric (React Native's new rendering system) enabled: (yes/no) 
Node version: 18.12.1
Test-runner (select one): jest 

### Detox logs

<details><summary>Detox logs</summary>

```
❯ detox run-server --port 18580 --loglevel trace
Detox server listening on localhost:18580...
^C

```

</details>

<details><summary>.detox.jsonl Logs</summary>

```
❯ tail -f /private/var/folders/22/9dxnk2js3274f0l_64mmd8bw0000gn/T/3d51e6cc-b9a1-a330-128b-5e0b926e9e44.76153.detox.jsonl
{"name":"detox","hostname":"ManishRanjan-C02YJ2THJHC8","pid":76153,"level":10,"cat":"ws-client,ws","ph":"i","tid":0,"data":"{\"type\":\"reactNativeReload\",\"params\":{},\"messageId\":-1000}","msg":"send message","time":"2023-01-31T06:12:13.574Z","v":0}
{"name":"detox","hostname":"ManishRanjan-C02YJ2THJHC8","pid":76153,"level":10,"cat":"ws-client,ws","ph":"i","tid":0,"data":"{\"messageId\":-1000,\"type\":\"ready\",\"params\":{}}\n ","msg":"get message","time":"2023-01-31T06:12:13.847Z","v":0}
{"name":"detox","hostname":"ManishRanjan-C02YJ2THJHC8","pid":76153,"level":10,"cat":"device","ph":"E","tid":0,"success":true,"msg":"reloadReactNative","time":"2023-01-31T06:12:13.847Z","v":0}

```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

### More data, please!

- As per past analysis, this issue has started happening on v20.1.2.
- Earlier in v19.x.x, when detox server
  - Was run using node_modules relative path -> Logs appearing in output stream
```
> node_modules/.bin/detox run-server
04:33:28.299 detox[476000] INFO:  [WSS_CREATE] Detox server listening on localhost:8099...
```  
-  - Was run using globally installed package -> Logs not appearing in output stream
```
> detox run-server
Detox server listening on localhost:8099...
```
![Screenshot 2023-01-31 at 12 18 11 PM](https://user-images.githubusercontent.com/28734169/215687049-a9651901-36a4-4ae5-b53a-d60467053a3f.png)

**Comment by gshah30** [comment]
> We never supported it properly, to be honest.
This used to work in Detox 19. We have server logs generated with Detox 19.

**Comment by noomorph** [comment]
@gshah30, I understand what you mean but that was just a happy coincidence why it worked. The logger class was horribly written and it knew to access CLI parameters directly. That's why you could make it use a custom log level.

Thanks for raising the issue, I'm going to see how problematic it is to add logger config support to `run-server`.
