### ISSUE TITLE
withTimeout not triggering with FlatList and react-native-loading-placeholder

### ISSUE THREAD

**Issue by ferrannp** [wix/detox#390]
#### Description

I have this piece of code:

```js
<FlatList 
  ...
  ListFooterComponent={someCondition ? renderLoading : null}
/>
```

Where `renderLoading` is a `PlaceHolderContainer` given by https://github.com/zeljkoX/react-native-loading-placeholder

Test hangs forever, it works just fine without that footer. The thing is, I used a timeout to debug it:

```js
await waitFor(element(by.id('some-id'))).toNotExist().withTimeout(8000);
await expect(element(by.id('some-id'))).toNotExist();
```

And the timeout never gets hit. Test just crashes when hits the Jest or Mocha global timeout.

I am still trying to figure out what is causing this issue. However, I open this as a bug as I would expect `withTimeout` to work.

I feel it is related to Animation work inside that library, removing the animation at all, makes test to work so... Even that we unmount the component, something is happening (looping animation stuff...).

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 5.9.2
* Node: 8.4.0
* Device: iPhone 7
* Xcode: 9.1
* macOS: High Sierra

#### Device and verbose Detox logs

When running with:

```sh
detox test --debug-synchronization [value in ms]
```

It keeps printing:

```
 JavaScript Timers: Javascript Timers Ids: 289
 Dispatch Queue: com.apple.main-thread
 JavaScript Timers: Javascript Timers Ids: 546
 Dispatch Queue: com.apple.main-thread
 JavaScript Timers: Javascript Timers Ids: 798
 Dispatch Queue: com.apple.main-thread
 JavaScript Timers: Javascript Timers Ids: 1049
 Dispatch Queue: com.apple.main-thread
 JavaScript Timers: Javascript Timers Ids: 1305
 Dispatch Queue: com.apple.main-thread
```

**Solution**

I can confirm is a bug in the library (leak in the animation).  That library needs to use `Animated.loop` or handle the loop without leaking (a way to stop it).

**Edit**
My fix does not solve this totally. If that component is shown (animating) test is stuck. `withTimeout` is ignored.

**Comment by rotemmiz** [comment]
Can you add debug-sync after your proposed fix ? Is it still JS timers ?

**Comment by LeoNatan** [comment]
This is not an issue with Detox. Closing the issue.
