### ISSUE TITLE
Detox build failed - ':react-native-inappbrowser-reborn:mergeDebugAndroidTestJavaResource'

### ISSUE THREAD

**Issue by Kornelg96** [wix/Detox#3911]
### Description

I have a problem with building tests in detox. It shows me this error:

What went wrong: Execution failed for task ':react-native-inappbrowser-reborn:mergeDebugAndroidTestJavaResource'.
A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction 2 files found with path 'META-INF/kotlin-stdlib-jdk8.kotlin_module' from inputs: - /home/sp/.gradle/caches/transforms-3/4f539c328e5bb19593050e3384e51919/transformed/jetified-kotlin-stdlib-jdk8-1.4.10.jar - /home/sp/.gradle/caches/transforms-3/c1d521098bb09d070895b1fa3c6468bd/transformed/jetified-kotlin-stdlib-1.8.0.jar Adding a packagingOptions block may help, please refer to https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html for more information

I've tried almost everything I found on the forums: kotlin.stdlib.jdk.variants.version.alignment=false

exclude("META-INF/kotlin-stdlib-common.kotlin_module")

exclude("META-INF/kotlin-stdlib-jdk7.kotlin_module")

exclude("META-INF/kotlin-stdlib-jdk8.kotlin_module")

exclude("META-INF/kotlin-stdlib.kotlin_module")

exclude("kotlin/annotation/annotation.kotlin_builtins")

exclude("kotlin/collections/collections.kotlin_builtins")

exclude("kotlin/coroutines/coroutines.kotlin_builtins")

exclude("kotlin/internal/internal.kotlin_builtins")

exclude("kotlin/kotlin.kotlin_builtins")

exclude("kotlin/ranges/ranges.kotlin_builtins")

exclude("kotlin/reflect/reflect.kotlin_builtins")

etc...

I got this error after adding: implementation(platform("org.jetbrains.kotlin:kotlin-bom:1.8.0")) - > in app/build.gradle

I had to add this line because the whole application was not building. After adding this line, the problem discussed above started to appear in detox Thank you very much for your help

This is my first time asking a question here, so if i did something wrong don't blame me ;) - i tried my best but i am new to mobile apps

### Your environment

Detox version:  "19.3.1"
React Native version: "0.66.4",
Node version: v16.19.0
Device model: Pixel 4 (emulator in android studio)
OS: Android
Test-runner (select one): jest

**Comment by etsraphael** [comment]
Have you found the solution here? I have the same issue
