### ISSUE TITLE
Allow setting permissions outside of `launchApp()`

### ISSUE THREAD

**Issue by skv-headless** [wix/detox#392]
#### Description

to launch app with permission I do:
```
before(async () => {
  await detox.init(config);
  await device.launchApp({permissions: {
    notifications: 'YES',
    location: 'always',
  }});
});
```
maybe exists another solution that I didn't find.
I that case app launches 2 times which is a little bit longer.
So my proposal to pass additional parameter to `detox.init`
for example like `detox.init(config, launchParams)`
and then later pass `launchParams` to `launchApp` here
https://github.com/wix/detox/blob/master/detox/src/devices/Device.js#L32

**Comment by LeoNatan** [comment]
@rotemmiz We should support `device.setPermissions()` directly. That way, the user can set their permissions once in `beforeAll`.

**Comment by rotemmiz** [comment]
Good idea, we would gladly accept a PR adding that functionality.

In the meantime, you can do the following:

```js
before(async () => {
  await detox.init(config, {launchApp: false});
  await device.launchApp({permissions: {
    notifications: 'YES',
    location: 'always'
  }});
});
```

**Comment by LeoNatan** [comment]
Thinking about this; since setting permissions requires a reboot of the sim, launch is necessary.
