### ISSUE TITLE
Does detox support pure native apps? Meaning non react native mobile apps?

### ISSUE THREAD

**Issue by gselsidi** [wix/Detox#3927]
### Description

Basically as the title says, can we use detox like we use appium, irrespective of what the app was built with? Can we use it to test regular native apps?

### Your environment

Detox version: 
React Native version: 
Node version: 
Device model: 
OS: 
Test-runner (select one): jest / other

**Comment by gselsidi** [comment]
by support i don't mean low level stuff, but similar functionality if not better than appium? basically is this a replacement for appium, or only for react native apps?

**Comment by aaronpliu** [comment]
actually it support native app. for iOS, you would use Xcode to build and launch App test with Detox. For Android, you may need to put your android native code into a RN project and install node_modules with Detox, configure DetoxTest.java to build App https://github.com/wix/Detox/blob/master/docs/guide/android-dev-env.md
