### ISSUE TITLE
DetoxInternalError: Detected an attempt to report failed tests using a non-initialized context. 

### ISSUE THREAD

**Issue by Zhao-Hansi** [wix/Detox#3937]
### Description

DetoxInternalError: Detected an attempt to report failed tests using a non-initialized context.
Please report this issue on our GitHub tracker:

### Your environment

Detox version: 
React Native version: 
Node version: 
Device model: 
OS: 
Test-runner (select one): jest / other

**Comment by tomgransden** [comment]
Have you tried https://github.com/wix/Detox/issues/3759 ?

**Comment by Zhao-Hansi** [comment]
Yes, I tried and I already followed the migration guide to change my configuration, Special i use the jest reporter.

**Comment by noomorph** [comment]
Most likely, you have a problem with your Jest config, but pasting only little excerpts instead of the full config won't do any good for you. I can't tell anything by looking at some little details.

Please run `detox test ... --showConfig` (i.e. add `--showConfig`) and paste your resolved Jest config it will print.

**Comment by Zhao-Hansi** [comment]
**This is my jest config**
{
  "configs": [
    {
      "automock": false,
      "cache": true,
      "cacheDirectory": "/private/var/folders/48/wvxn7wn93mz6tr96_g645fpr0000gn/T/jest_dx",
      "clearMocks": false,
      "coveragePathIgnorePatterns": [
        "/node_modules/"
      ],
      "cwd": "/Users/zhaozexin/IdeaProjects/AutomationTestForMsrs",
      "detectLeaks": false,
      "detectOpenHandles": false,
      "errorOnDeprecated": false,
      "extensionsToTreatAsEsm": [],
      "extraGlobals": [],
      "forceCoverageMatch": [],
      "globals": {},
      "haste": {
        "computeSha1": false,
        "enableSymlinks": false,
        "forceNodeFilesystemAPI": false,
        "throwOnModuleCollision": false
      },
      "injectGlobals": true,
      "moduleDirectories": [
        "node_modules"
      ],
      "moduleFileExtensions": [
        "js",
        "jsx",
        "ts",
        "tsx",
        "json",
        "node"
      ],
      "moduleNameMapper": [],
      "modulePathIgnorePatterns": [],
      "name": "4d77943be2f8c761b5c940ccfd1ce752",
      "prettierPath": "prettier",
      "resetMocks": false,
      "resetModules": false,
      "restoreMocks": false,
      "rootDir": "/Users/zhaozexin/IdeaProjects/AutomationTestForMsrs/ui-tests",
      "roots": [
        "/Users/zhaozexin/IdeaProjects/AutomationTestForMsrs/ui-tests"
      ],
      "runner": "/Users/zhaozexin/IdeaProjects/AutomationTestForMsrs/node_modules/jest-runner/build/index.js",
      "setupFiles": [],
      "setupFilesAfterEnv": [],
      "skipFilter": false,
      "slowTestThreshold": 5,
      "snapshotSerializers": [],
      "testEnvironment": "/Users/zhaozexin/IdeaProjects/AutomationTestForMsrs/node_modules/detox/runners/jest/testEnvironment/index.js",
      "testEnvironmentOptions": {},
      "testLocationInResults": false,
      "testMatch": [],
      "testPathIgnorePatterns": [
        "/node_modules/"
      ],
      "testRegex": [
        "\\.spec\\.js$"
      ],
      "testRunner": "/Users/zhaozexin/IdeaProjects/AutomationTestForMsrs/node_modules/jest-circus/runner.js",
      "testURL": "http://localhost",
      "timers": "real",
      "transform": [
        [
          "\\.[jt]sx?$",
          "/Users/zhaozexin/IdeaProjects/AutomationTestForMsrs/node_modules/babel-jest/build/index.js",
          {}
        ]
      ],
      "transformIgnorePatterns": [
        "/node_modules/",
        "\\.pnp\\.[^\\/]+$"
      ],
      "watchPathIgnorePatterns": []
    }
  ],
  "globalConfig": {
    "bail": 0,
    "changedFilesWithAncestor": false,
    "collectCoverage": false,
    "collectCoverageFrom": [],
    "coverageDirectory": "/Users/zhaozexin/IdeaProjects/AutomationTestForMsrs/ui-tests/coverage",
    "coverageProvider": "babel",
    "coverageReporters": [
      "json",
      "text",
      "lcov",
      "clover"
    ],
    "detectLeaks": false,
    "detectOpenHandles": false,
    "errorOnDeprecated": false,
    "expand": false,
    "findRelatedTests": false,
    "forceExit": false,
    "json": false,
    "lastCommit": false,
    "listTests": false,
    "logHeapUsage": false,
    "maxConcurrency": 5,
    "maxWorkers": 1,
    "noStackTrace": false,
    "nonFlagArgs": [],
    "notify": false,
    "notifyMode": "failure-change",
    "onlyChanged": false,
    "onlyFailures": false,
    "passWithNoTests": false,
    "projects": [],
    "reporters": [
      [
        "/Users/zhaozexin/IdeaProjects/AutomationTestForMsrs/node_modules/detox/runners/jest/reporter.js",
        {}
      ],
      [
        "/Users/zhaozexin/IdeaProjects/AutomationTestForMsrs/node_modules/jest-html-reporters/index.js",
        {
          "pageTitle": "Detox Test Report for undefined",
          "publicPath": "./test-artifacts/undefined-test-report.html",
          "filename": "undefined-test-report.html",
          "includeConsoleLog": true
        }
      ]
    ],
    "rootDir": "/Users/zhaozexin/IdeaProjects/AutomationTestForMsrs/ui-tests",
    "runTestsByPath": false,
    "skipFilter": false,
    "testFailureExitCode": 1,
    "testPathPattern": "",
    "testSequencer": "/Users/zhaozexin/IdeaProjects/AutomationTestForMsrs/node_modules/@jest/test-sequencer/build/index.js",
    "testTimeout": 300000,
    "updateSnapshot": "new",
    "useStderr": false,
    "verbose": true,
    "watch": false,
    "watchAll": false,
    "watchman": true
  },
  "version": "27.5.1"
}

**Comment by noomorph** [comment]
I don't see that you configured globalSetup or globalTeardown, or testEnvironment. Please follow Detox tutorial. You have insufficient Jest configuration

**Comment by Zhao-Hansi** [comment]
Thank you.  It works after i add the globalSetup and globalTeardown. Have a good day!
