### ISSUE TITLE
`detox build -c` does not return error exit code when `build` fails

### ISSUE THREAD

**Issue by leoylung** [wix/Detox#3938]
### What happened?

```
        'android.foobar': {
            type: 'android.apk',
            binaryPath:
                'android/app/...',
            testBinaryPath:
                'android/app/...',
            build:
                'cd android ; ./gradlew ...; cd -',
        },
    },

    configurations: {
        'android.emu.foobar': {
            device: 'android.emulator',
            app: 'android.foobar',
        },
    },
```

```
detox build -c android.emu.foobar
```
Above command does not exit with an error code when the gradew build step fails. This makes it difficult for CI environments to identify which step failed. Often, the build step would appear to succeed, and we get a file not found in the next step.

### What was the expected behaviour?

detox build -c exits with error code from build step.

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### In what environment did this happen?

Detox version: 
React Native version: 
Has Fabric (React Native's new rendering system) enabled: (yes/no) 
Node version: 
Test-runner (select one): jest / other

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by noomorph** [comment]
You should fix your build command then – use `&&`, not `;`:

[What is the difference between double-ampersand (&&) and semicolon (;) in Linux Bash?](https://stackoverflow.com/questions/25669540/what-is-the-difference-between-double-ampersand-and-semicolon-in-linux)
