### ISSUE TITLE
Detox not support to android version 33.

### ISSUE THREAD

**Issue by komalharmale** [wix/Detox#3945]
### What happened?

I Created one simulator `Pixel_4_API_33` of version `33` and test by detox command. 
For above device test cases execute but on screen it not shown required output 
I have written below test cases so once i run detox it should fill username in text input, but it didn't. Test cases are just executed one by one.
await element(by.id('username')).typeText('Komal');

### What was the expected behaviour?

The behavior should be once i run the detox `Komal` word should get type on text input.
This behavior working properly on emulation which having android version 32 or below 32
. 

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: ^20.1.4
React Native version: 0.71.3
Has Fabric (React Native's new rendering system) enabled: (yes/no) Yes
Node version: v18.13.0
Device model: Pixel_4_API_33
Android version: 33
Test-runner (select one): jest / other:Jest

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by komalharmale** [comment]
awaiting for response

**Comment by d4vidi** [comment]
Detox should work with SDK version 31. For newer version, see #3762.

**Comment by komalharmale** [comment]
Yes, it's works on version 31 and 32 the issue is only for version 33. 
Thank you for the support
