### ISSUE TITLE
How to run platform specific tests in Detox 20?

### ISSUE THREAD

**Issue by tomgransden** [wix/Detox#3948]
### Description

In Detox 19 and below, I could put in `:ios:` or `:android:` in the test name and Detox would know to only run the test on that particular platform. In Detox 20, this doesn't seem to be working any more. Is it possible to only run a test on a specific platform in Detox 20?

### Your environment

Detox version: 20.1.3
React Native version: 0.68.5
Node version: 16.19.0
Device model: N/A
OS: N/A
Test-runner (select one): jest

**Comment by noomorph** [comment]
Well, it should work. This feature is still supported: 

https://github.com/wix/Detox/blob/master/detox/runners/jest/testEnvironment/listeners/DetoxPlatformFilterListener.js#L12-L24

**Comment by tomgransden** [comment]
Cool thanks - looks like the regex now expects the `:android:` or `:ios:` to be at the very start of the test/describe name

![Screenshot 2023-02-24 at 15 17 35](https://user-images.githubusercontent.com/42301553/221215973-3ae92f7c-f940-4af0-a178-543957174b4c.png)

**Comment by tomgransden** [comment]
Happy for this to be closed I'll adapt my tests

**Comment by wootcot** [comment]
device.getPlatform() === "ios" ? "text1" : "text2";
