### ISSUE TITLE
Init Detox and Launch App programmatically

### ISSUE THREAD

**Issue by moonjava2005** [wix/Detox#3951]
### Description

Before version 2.x, I write the test with NodeJS file, then, I can start Detox by:
`const detox = require('detox')
detox.init(...configuration)
detox.device.launchApp()`

However, with version 2.x, the `detox.init` is not defined. I have tried with `init` from `detox/internal` but It did work too
So, what I want is:
- I have the detox config file already
- I can init and launch app from some JS file with specific configuration name passed to `init` function
I hope to get you guys help
Thanks in advance

### Your environment

Detox version:  2.x
React Native version: 0.71.2
Node version: 16.13.0
Device model: Simulator
OS: MacOS
Test-runner (select one): jest

**Comment by moonjava2005** [comment]
@noomorph Thanks for your help. I misunderstood the document

**Comment by noomorph** [comment]
@moonjava2005  if there are some missing or unclear parts in the Internals docs, you're welcome to create an issue or two.
