### ISSUE TITLE
[Detox-20] ts-jest configuration

### ISSUE THREAD

**Issue by wiulma** [wix/Detox#3952]
### Description

Hi! I can't figure out how make the new Detox 20 with ts-jest.
My broken configurations is:

detoxrc.js
````
module.exports = {
	testRunner: {
		args: {
			$0: 'jest',
			config: 'e2e/jest.config.js'
		},
		jest: {
			setupTimeout: 120000
		}
	},
	reporters: ['detox/runners/jest/streamlineReporter'],
	apps: {...}
}
````

e2e/jest.config.js
````
/** @type {import('@jest/types').Config.InitialOptions} */
module.exports = {
	preset: 'ts-jest',
	rootDir: '..',
	testMatch: ['<rootDir>/e2e/**/*.test.ts'],
	testTimeout: 120000,
	maxWorkers: 1,
	globalSetup: 'detox/runners/jest/globalSetup',
	globalTeardown: 'detox/runners/jest/globalTeardown',
	reporters: ['detox/runners/jest/reporter'],
	testEnvironment: 'detox/runners/jest/testEnvironment',
	verbose: true,
	setupFilesAfterEnv: ['<rootDir>/e2e/init.ts'],
	transform: {
		'\\.ts?$': 'ts-jest'
	}
}

````

Error:
detox[56259] E Command failed with exit code = 1:
jest --config e2e/jest.config.js

I followed the migration guide, everything seems correct.
do you have any suggestion?
thanks 

### Your environment

Detox version: 20.1.0
React Native version: 0.71.1 (notes: I know in theory it's not supported, but the js version works correctly, the ts version is broken)
Node version: 16.13.1
Device model: macbook pro  M1
OS: ventura 13.2
Test-runner (select one): jest

**Comment by noomorph** [comment]
You overwrite testEnvironment twice.

I am not familiar with this preset.

I usually just use **transform** section where I configure **ts-jest** transformer.

**Comment by wiulma** [comment]
ok. thanks. stupid copy/paste mistake there, I checked it again, and fix the code above. I also tried to add the transform section, but the error is still there.

**Comment by noomorph** [comment]
I don't have telepathic abilities. You have posted neither logs nor errors or screenshots, so I have no idea what kind of error you see. 😕 

Look at our example project – although the config is a bit old-fashioned, it works well thus far:

* [tsconfig.json](https://github.com/wix/Detox/blob/master/examples/demo-react-native/tsconfig.json)
* [e2e/jest.config.js](https://github.com/wix/Detox/blob/master/examples/demo-react-native/e2e/jest.config.js)

I hope these examples will help you.

**Comment by wiulma** [comment]
yes, thanks, I'm going throw them to be honest, but it seems I still can't make it working. 
I didn't add any logs because the script doesn't print anything (I also added the verbose flag in the jest cli args)
thanks for your response

**Comment by noomorph** [comment]
You can also pass `--debug` or `--showConfig` to Jest — it should print something (in theory).
You can use `DEBUG=* ...` environment variable override also.

**Comment by wiulma** [comment]
it seems the error was because of this:
````

const adapter = require('detox/runners/jest/adapter')
jasmine.getEnv().addReporter(adapter)
...
afterAll(async () => {
	await adapter.afterAll()
	await cleanup()
})
````
I required the adapter in the init function, in order to add the reporter and call its afterAll callback. but it seems I can't do it anymore because jest is configured in a different way. I had a generic error message in the console (because of node_modules/detox/runners/deprecation.js ). now it's working. thanks for your support

**Comment by noomorph** [comment]
Ok, please ensure you don't use any old adapters, including anything with `jasmine` in its name. I'm glad that the advice helped.
