### ISSUE TITLE
Accessibility testing (screenreader support)

### ISSUE THREAD

**Issue by adamivancza** [wix/Detox#3962]
### Describe your idea

We would like to maintain our ADA compliance in our app. To achieve this we're thinking about running automated e2e tests on our CI/CD. Right now we're using Detox to write and run e2e tests, however, the automated accessibility testing tools I have found are all using Appium:
https://www.perfecto.io/solutions/accessibility-testing
https://www.evinced.com/products/auto-test-sdks

As far as I know on iOS these tests would require an actual iOS device as the iOS simulator does not support this. Is this correct? Are there any plans/suggestions on how can we achieve this using Detox?

And I also found this one which is basically built on top of react-native-testing-library which is just component tests:
https://github.com/aryella-lacerda/react-native-accessibility-engine

**Comment by asafkorem** [comment]
Hi Adam. My apologies, but I'm not sure I understand your question. Are there any expectations APIs that are missing for your use-case? Unfortunately, I'm not very familiar with ADA compliance or with the APIs of the tools you mentioned, please be more specific - what are you trying to accomplish?

**Comment by asafkorem** [comment]
@adamivancza some of the expectations you're asking already exists: https://wix.github.io/Detox/docs/api/expect

Also, you have the [getAttributes()](https://wix.github.io/Detox/docs/api/actions#getattributes) API that can expose more accessibility attributes of an element. There's an open issue (feature suggestion) for exposing more attributes: https://github.com/wix/Detox/issues/3116, we generally plan to expose more accessibility attributes with Detox v21.
