### ISSUE TITLE
Throw error when tap element with visible but cannot edit in native App

### ISSUE THREAD

**Issue by aaronpliu** [wix/Detox#3966]
### What happened?

In Detox v19.x, it's OK to tap element which it's visible and editable=false in native iOS.
After upgrade to Detox v20.x (Actually from v19.1.3), it will throw error

### What was the expected behaviour?

Do not validate (throw error) if the element is visible and editable=false

### Was it tested on latest Detox?
Yes
Checked on v20.5.0

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!
Error message:
Test Failed: View is not hittable at its visible point. Failed to interact with the screen at point: {59.333333333333343, 12} 

### In what environment did this happen?

Detox version: 20.5.0
React Native version:  
Has Fabric (React Native's new rendering system) enabled: (yes/no)  no
Node version: 16.13
Device model: 
iOS version: 16.2
macOS version: 13.1
Xcode version: 14.2
Test-runner (select one): jest / other

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste your device.log here!
```

</details>

**Comment by aaronpliu** [comment]
is there anyone to help on this? I have to upgrade Detox latest version to fix other issues. However it broke test cases due to above-mentioned error. much appreciate if any help

**Comment by d4vidi** [comment]
> is there anyone to help on this? I have to upgrade Detox latest version to fix other issues. However it broke test cases due to above-mentioned error. much appreciate if any help @d4vidi

Yes we know why this happens in general but could you share a screenshot, view hierarchy snapshot and explain what the element in question is?

**Comment by d4vidi** [comment]
@aaronpliu we are likely to be able to help, please share necessary files (use [this guide](https://wix.github.io/Detox/docs/config/artifacts/#enabling-artifacts))

**Comment by aaronpliu** [comment]
thanks @d4vidi. 
the issue derived from #3150, it seems enhanced validation on scroll and impact tap action also
the change is from **UIView+DetoxUtils.m line 505**.  I did not touch test code now as project reason. Please let me know if need more details.

**Comment by d4vidi** [comment]
> @aaronpliu we are likely to be able to help, please share the necessary files (use [this guide](https://wix.github.io/Detox/docs/config/artifacts/#enabling-artifacts))

@aaronpliu WFIW we could still try to help you out if you share the necessary artifacts.
