### ISSUE TITLE
🚨 Possible synchronization issues with UI-lib dialogs

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#3971]
### What happened?

According to this [Wix-internal thread](https://wix.slack.com/archives/C1Y4D9BK8/p1677179075267309), recent changes in [UI-lib's](https://wix.github.io/react-native-ui-lib) dialog component (also used as the building block of action sheets) have caused associated Detox test to fail, allegedly, due to synchronization problems:

A press is attempted over one of the action-sheet items (`Edit plan`) while it's still animating in from the bottom - resulting in a tap over a different item, instead (`Hide plan`):

<img src="https://user-images.githubusercontent.com/9818880/223156222-39730713-b7b3-4216-9455-829306e73883.png" width=350 />

### What was the expected behaviour?

Not going to state the obvious.

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

The UI lib OSS project has a demo app. We can apply a Detox configuration to it and try to test it there. This would probably be the easiest way.

### In what environment did this happen?

Detox version: 20.x.x
React Native version: 68
Has Fabric (React Native's new rendering system) enabled: (yes/no) 
Node version: 
Device model: 
iOS version: 
macOS version: 
Xcode version: 
Test-runner (select one): jest / other

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste your device.log here!
```

</details>

**Comment by asafkorem** [comment]
See https://wix.slack.com/archives/C1Y4D9BK8/p1682796242671269?thread_ts=1677179075.267309&cid=C1Y4D9BK8
