### ISSUE TITLE
Keyboard does not show in headless mode

### ISSUE THREAD

**Issue by arcln** [wix/Detox#3983]
### What happened?

The iOS keyboard does not show when running with `--headless`. Same tests without `--headless` shows the keyboard.

The text input is actually focused, and typing into it works, but the keyboard is hidden, just like when using CMD-K in Simulator.app.

I took a screenshot to verify this. I run the tests on my computer (mac m1 monterey).

What I've tried without success :
- Making sure hardware keyboard is disconnected before exiting Simulator.app
- Running on a new simulator (i.e. that wasn't installed, so no config for this device exists)
- Tweaking `~/Library/Preferences/com.apple.iphonesimulator.plist` (doesn't do anything)
- Restarting my computer (yes, really)
- Reading and re-reading #1393 

### What was the expected behaviour?

I expected the keyboard to show up when using `typeText` in `--headless` mode on iOS.

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

Type text into a text input on iOS, run with `--headless`, take a screenshot, notice the keyboard is not there.

### In what environment did this happen?

Detox version: 20.5.0
React Native version: 0.71.4
Has Fabric (React Native's new rendering system) enabled: (yes/no) no
Node version: v16.13.0
Device model: mac m1 monterey / iphone 14 pro max simulator
iOS version: 16.2
macOS version: 12.6
Xcode version: 14.2
Test-runner (select one): jest

### Detox logs

<details><summary>Detox logs</summary>

```
Nothing relevant
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
Nothing relevant
```

</details>

**Comment by asafkorem** [comment]
Hi @arcln, interesting case. I believe it's the default behaviour of the Simulator app. It's possible that the iOS keyboard is not available because the Simulator app runs without user interface (headless mode). 

> Making sure hardware keyboard is disconnected before exiting Simulator.app

If I understand this correctly, you tried to uncheck "Connect Hardware Keyboard", right?

**Comment by arcln** [comment]
Yes, the "Connect Hardware Keyboard" option is not checked.
Is Detox using Simulator.app to run tests? I thought it use some lower-level API.

Are you saying this issue is not related to detox but to the iOS simulator itself?
