### ISSUE TITLE
Switch component is reported as visible when hidden by the navigation bar

### ISSUE THREAD

**Issue by arcln** [wix/Detox#3984]
### What happened?

I use the following code to scroll to a switch component and tap it :

```javascript
await waitFor(element(by.id('my-switch')))
	.toBeVisible()
	.whileElement(by.id('my-scroll-view'))
	.scroll(200, 'down');
await element(by.id('my-switch')).tap();
```

However on Android the tap action fails :

```
Test Failed: Couldn't click at: 950.5,1891.0 precision: 16.0, 16.0 . Tapper: com.wix.detox.espresso.action.DetoxSingleTap@58bd328 coordinate provider: VISIBLE_CENTER precision describer: FINGER. Tried 3 times. With Rollback? false
```

- By looking at the screen I can see the switch is not visible, but would be if there was no navigation bar.
- By looking at the coordinates I can see it taps at y = 1891, and the device is 1920px height, so it definitely is inside the navigation bar.

The device I test on is a Pixel API 28 emulator.

### What was the expected behaviour?

I expected the switch not to be reported as visible before it is actually tappable.

For now my workaround is to ask detox to scroll further than actually needed.

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

Put a switch in a scroll view, make sure it is low enough so scroll is required.
Then use the code snippet above to reach it and notice it stops scrolling too soon.

### In what environment did this happen?

Detox version: 20.5.0
React Native version: 0.71.4 
Has Fabric (React Native's new rendering system) enabled: (yes/no) no
Node version: 16.13.0
Device model: mac m1 monterey / pixel api 28 emulator
Android version: 9
Test-runner (select one): jest

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste your device.log here!
```

</details>

**Comment by asafkorem** [comment]
Hi @arcln, it's hard to figure what exactly was the cause for this issue based only on the issue description.
Is it possible that while the scrolling took effect, the navigation bar was hidden (and appeared after the scrolling was ended)?

**Comment by arcln** [comment]
No, the navigation bar does not hide or show, it never moves (on API 28 at least).

I will try to craft some minimal reproductible example but I'm not sure when I'll find the time for this.
