### ISSUE TITLE
Invalid Link for Design Principles

### ISSUE THREAD

**Issue by yasinosman** [wix/Detox#3989]
### What happened?

I was following the `README.md` file and under the _Core Principles_ section, there is a link like this:

... _See what Detox [does differently](https://wix.github.io/Detox/docs/introduction/design-principles)_.

The link is broken and returns 404

### What was the expected behaviour?

I was expecting to see an article about architectural decisions

### Was it tested on latest Detox?

- [ ] I have tested this issue on the latest Detox release and it still reproduces.

### Help us reproduce this issue!

Visit the link: https://wix.github.io/Detox/docs/introduction/design-principles

**Comment by asafkorem** [comment]
Thanks @yasinosman, resolved by https://github.com/wix/Detox/pull/3990
