### ISSUE TITLE
How can I test my error handling?

### ISSUE THREAD

**Issue by drumnation** [wix/detox#399]
I'm trying to test that my alert messages are correct and I'm having a hard time selecting the alert.  The message is in my redux store and have tried adding getState through thunk to access it, but didn't have any luck.  

What would be the best way to test that the alert message is correct when certain form validations fail?  In this case I want to see that test was able to signup, but if it fails validation, I'd like to have it pass another test showing that it received a specific error and handled it correctly.
```
describe("FINAL VALIDATION TESTS", async () => {
      it("STEP 24: Signup Button Tapped", async () => {
          const signupButton = await element(by.id("signupButton"));
          await signupButton.tap();
          await signupButton.tap();
      }),
      it("STEP 25: Main Menu Container Exists", async () => {
        try {
          const mainMenuContainer = await element(
            by.id("mainMenuContainer")
          );
          await expect(mainMenuContainer).toExist();
        } catch (err) {
          it("ERROR HANDLING: No Punctuation in Username", async () => {
            try {
              const message = await element(by.text('No punctuation like: . $ # [ ] / in your username.'));
              await expect(message).toExist();
              console.log("Error: ",  err, err.message);
              console.log("MESSAGE: ",  message);
            } catch (err) {
              console.log(err);
            }
          })
        }
      });
    });
```

```
 "detox": "^5.9.3",
 "detox-cli": "^1.0.2"
 "react-native": "^0.50.3"
```

**Comment by rotemmiz** [comment]
Detox has no idea of your redux state, it knows how to match and expect on elements in your native view hierarchy.

Regarding your test flows, try make consistent tests without branches (no `if`s or `try/catch`s). Create multiple tests, with different inputs in each, consistent inputs should produce consistent outputs. 

If you need help understanding how to view your native view hierarchy, take a look [here](https://github.com/wix/detox/blob/master/docs/Troubleshooting.RunningTests.md#debug-view-hierarchy)

**Comment by drumnation** [comment]
Thanks!
