### ISSUE TITLE
Need support in installing framework

### ISSUE THREAD

**Issue by ppj7887** [wix/Detox#3993]
### Description

I am trying to install the framework but I am not able to install it properly as getting different type of errors. If anyone has complete guide how to install a project that will be helpful.

### Your environment

Detox version: 
React Native version: 
Node version: 
Device model: 
OS: 
Test-runner (select one): jest / other

**Comment by asafkorem** [comment]
Hi @ppj7887, we have a very comprehensive guide for setting Detox on your project: https://wix.github.io/Detox/docs/next/introduction/getting-started

Did you try to follow it? If so, can you please be more specific, what errors do you get?

**Comment by ppj7887** [comment]
Getting error for test binary apk not found. I am not sure what should I do?
