### ISSUE TITLE
How to enable dynamic mocking?

### ISSUE THREAD

**Issue by Sid-Turner-Ellis** [wix/Detox#3996]
### Description

I'm trying to find a way to seed some apollo client reactive vars (in memory but persisted in async storage) in each test ([https://www.apollographql.com/docs/react/local-state/reactive-variables/](https://www.apollographql.com/docs/react/local-state/reactive-variables/))

I'm wondering on what the best approach to this would be, im considering:

1. Creating a UI to interface with these variables
    
    I would create a floating button that shows only in dev mode that can be pressed from a detox test, it would open up a modal for writing and reading the in memory vars
    
    ```jsx
    1. Open dev UI via button in detox test
    2. Write to an input field to create a value in detox test
    ```
    
2. Using a static mock + server
    
    Make a request to a server with the values I want the the reactive vars to be, then in my app have a mock of the function that initialises the vars by making a request to the same server. 
    
    ```jsx
    1. Make a network request to server with the initial values in detox test
    2. Override "initiateReactiveVars.ts" with "initiateReactiveVars.mock.ts"
    3. Have the mock initiate the reactiveVars by making a request to the server
    ```

### Your environment

Detox version: 20
React Native version: 70x
Node version: 15
Device model: Pixel
OS: Android
Test-runner (select one): jest

**Comment by d4vidi** [comment]
@Sid-Turner-Ellis That's an interesting discussion. Have you finalized you decision?

As a general approach, seeing that we are in a UI-testing environment, it's usually natural to make such dynamic state-mutations using a dedicating, dev-env UI. At Wix, we sometimes go as far as adding an extra tab in the bottom-tab navigation bar.

Server-based mocking can be helpful in those cases where you need to have things mocked outside the app, prematurely (i.e. before the app is even launched). I don't believe that this is your use case. Nevertheless, possibly, [launch arguments](https://wix.github.io/Detox/docs/config/artifacts/#launch-arguments) could be utilized, as a 3rd option.
