### ISSUE TITLE
Building fails in react native.

### ISSUE THREAD

**Issue by novatechzone** [wix/Detox#3997]
### Description

Hi, Please help me to resolve this issue.

React Native : 0.71.4
detox: "^20.6.0"

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
What went wrong:
Execution failed for task ':app:checkDebugAndroidTestDuplicateClasses'.
A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
Duplicate class com.genymotion.api.Battery found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
Duplicate class com.genymotion.api.Battery$1 found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
Duplicate class com.genymotion.api.Battery$2 found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
Duplicate class com.genymotion.api.Battery$Mode found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
Duplicate class com.genymotion.api.Battery$Status found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
Duplicate class com.genymotion.api.DiskIO found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
Duplicate class com.genymotion.api.GenydBinder found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
Duplicate class com.genymotion.api.GenydBinder$1 found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
Duplicate class com.genymotion.api.GenymotionException found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
Duplicate class com.genymotion.api.GenymotionManager found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
Duplicate class com.genymotion.api.GenymotionManager$1 found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
Duplicate class com.genymotion.api.GenymotionManager$TokenValidity found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
Duplicate class com.genymotion.api.Gps found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
Duplicate class com.genymotion.api.Gps$1 found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
Duplicate class com.genymotion.api.Gps$Status found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
Duplicate class com.genymotion.api.Id found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
Duplicate class com.genymotion.api.Id$1 found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
Duplicate class com.genymotion.api.LocationParams found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
Duplicate class com.genymotion.api.LocationParams$1 found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
Duplicate class com.genymotion.api.LocationParams$Builder found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
Duplicate class com.genymotion.api.MethodUnavailableException found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
Duplicate class com.genymotion.api.Network found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
Duplicate class com.genymotion.api.Network$Profile found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
Duplicate class com.genymotion.api.NotGenymotionDeviceException found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
Duplicate class com.genymotion.api.Orientation found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
Duplicate class com.genymotion.api.Radio found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
Duplicate class com.genymotion.api.Radio$1 found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
Duplicate class com.genymotion.api.Radio$2 found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
Duplicate class com.genymotion.api.Radio$3 found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
Duplicate class com.genymotion.api.package-info found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
Duplicate class com.genymotion.genyd.IGenydService found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
Duplicate class com.genymotion.genyd.IGenydService$Stub found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
Duplicate class com.genymotion.genyd.IGenydService$Stub$Proxy found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
Duplicate class com.genymotion.genyd.NetworkProfile found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
Duplicate class com.genymotion.genyd.NetworkProfile$1 found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
Duplicate class com.genymotion.genyd.NetworkProfile$Name found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
Duplicate class com.genymotion.genyd.NetworkProfile$Status found in modules jetified-detox-0.1.1-runtime (com.wix:detox:0.1.1) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)

 Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.
Try:
Run with --stacktrace option to get the stack trace.
Run with --info or --debug option to get more log output.
Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
What went wrong:
java.lang.StackOverflowError (no error message)

Try:

Run with --stacktrace option to get the stack trace.
Run with --info or --debug option to get more log output.
Run with --scan to get full insights.
==============================================================================

Get more help at https://help.gradle.org/
BUILD FAILED in 1m 56s
386 actionable tasks: 4 executed, 382 up-to-date

### Your environment

Detox version: "^20.6.0",
React Native version: "0.71.4"
Node version: v18.14.2
Device model: Galaxy M02
OS: Android
Test-runner (select one): jest / other

**Comment by rvasseur31** [comment]
The detox lib is not compatible with react native 71 (https://github.com/wix/Detox/issues/3884)

**Comment by d4vidi** [comment]
@novatechzone Could you try to get Detox working with RN .70 first?
