### ISSUE TITLE
Unrecognized font family

### ISSUE THREAD

**Issue by dayaki** [wix/Detox#3999]
### What happened?

Our detox testing were working fine, then we decided to add a new font family to the app. We can build and run successfully via CLI and Xcode but when we run our detox test, we get `Unrecognized font family` error on iOS.

We tired `detox clean-framework-cache && detox build-framework-cache` and problem still persists.

### What was the expected behaviour?

Expected detox test to be successful if we are using same simulator that was manually tested on and no unrecognized font errors.

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

Simply add a new font family to project and detox will complain about not seeing that font.

### In what environment did this happen?

Detox version: 20.5.0
React Native version: 0.70.3
Has Fabric (React Native's new rendering system) enabled: (yes/no) 
Node version: v16.16.0
Device model: iOS simulator iOS simulator
iOS version: 16.2
macOS version: 13.2.1
Xcode version: 14.2
Test-runner (select one): jest

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste your device.log here!
```

</details>

**Comment by asafkorem** [comment]
@dayaki please provide the full logs and error message you're getting. Also, a minimal reproduction repo will be useful here. Otherwise, it will be very hard to figure what problem you're dealing with and will be impossible to investigate.

**Comment by dayaki** [comment]
Thanks @asafkorem, but I can't seem to add the --trace log as it seems to be more than the 65536 characters limit. Here is the `--record-logs all` log:

```
detox test e2e/auth/signup.test.js --configuration ios.debug --record-logs all
17:20:39.450 detox[93450] B jest --config e2e/jest.config.js e2e/auth/signup.test.js
17:20:44.741 detox[93451] i signup.test.js is assigned to 81D7CBED-1761-4402-935D-58DB010F0320 (iPhone 13 Pro)
17:20:46.464 detox[93451] i com.gloverapp.v2 launched. To watch simulator logs, run:
        /usr/bin/xcrun simctl spawn 81D7CBED-1761-4402-935D-58DB010F0320 log stream --level debug --style compact --predicate 'process == "Glover"'
17:20:48.262 detox[93451] i Sign up screen: should show onboarding screen
17:20:48.613 detox[93451] i Sign up screen: should show onboarding screen [OK]
17:20:48.614 detox[93451] i Sign up screen: should navigate to the login screen
17:20:50.339 detox[93451] i Sign up screen: should navigate to the login screen [OK]
17:20:50.340 detox[93451] i Sign up screen: should navigate to the sign up and register
17:20:53.845 detox[93451] i Sign up screen: should navigate to the sign up and register [FAIL]

 FAIL  e2e/auth/signup.test.js (13.592 s)
  Sign up screen
    ✓ should show onboarding screen (292 ms)
    ✓ should navigate to the login screen (1661 ms)
    ✕ should navigate to the sign up and register (3446 ms)

  ● Sign up screen › should navigate to the sign up and register

    Test Failed: No elements found for “MATCHER(id == “select-item”)”

    HINT: To print view hierarchy on failed actions/matches, use log-level verbose or higher.

      18 |     await element(by.id('email')).typeText('testuser@gloverapp.co');
      19 |     await element(by.id('select-country')).tap();
    > 20 |     await element(by.id('select-item')).tap();
         |                                         ^
      21 |     await expect(element(by.id('password'))).toBeVisible();
      22 |     await element(by.id('password')).typeText('password');
      23 |     await element(by.text('Sign Up')).tap();

      at Object.tap (e2e/auth/signup.test.js:20:41)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)

17:20:53.983 detox[93450] E Command failed with exit code = 1:
jest --config e2e/jest.config.js e2e/auth/signup.test.js
```

**Comment by asafkorem** [comment]
@dayaki, I can't find the `Unrecognized font family` error you said you're getting, where is it coming from? Can you provide here the relevant error logs?

**Comment by asafkorem** [comment]
Anyhow, this is not a Detox error. But I can try and help you resolve this issue.

Please make sure that the font is registered correctly in your app and spelled correctly in your code. 

Also check [Apple docs](https://developer.apple.com/documentation/uikit/text_display_and_fonts/adding_a_custom_font_to_your_app) to make sure you didn't missed any step in using a custom font on your app.

It's possible that the font availability difference between Detox and regular run is due to using different build settings or targets. To ensure that the font is included in all targets and schemes, check that the font file is added to the "Copy Bundle Resources" build phase and that it's spelled correctly in your code. If you're using different build settings for Detox and regular run, make sure that the font file is included in both settings.

**Comment by dayaki** [comment]
@asafkorem everything was working perfectly fine until I changed the app font-family from `DMSans` to `BRFirma`, So I think it's more of a cache thing.

Is there any way to clear the detox cache? I googled and tried `detox clean-framework-cache && detox build-framework-cache` but didn't help.
