### ISSUE TITLE
error trying to run e2e tests

### ISSUE THREAD

**Issue by adigrinvald** [wix/detox#4]
Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "e2e"
npm ERR! node v5.8.0
npm ERR! npm  v3.8.1
npm ERR! code ELIFECYCLE
npm ERR! rn-example@0.0.1 e2e: `mocha e2e --opts ./e2e/mocha.opts`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the rn-example@0.0.1 e2e script 'mocha e2e --opts ./e2e/mocha.opts'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the rn-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha e2e --opts ./e2e/mocha.opts
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rn-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls rn-example
npm ERR! There is likely additional logging output above.

**Comment by talkol** [comment]
Please pull latest version (added a minor fix to react ver but it shouldn't make a difference)

Also take a look at https://github.com/wix/detox/blob/master/rn-example/README.md
Your issue looks like missing requirements, I added `Requirements` section to the readme to make sure your system has everything needed to run this example

I just ran the example locally with all the requirements and it works smoothly

**Comment by talkol** [comment]
Another thing, can you please try to type `mocha` in the rn-example project directory and see if mocha is in the path?

**Comment by adigrinvald** [comment]
-bash: mocha: command not found

**Comment by talkol** [comment]
ok.. try `npm install mocha -g`
if so, I'll add it to the requirements
usually `./node_modules/.bin` is in the path so it should find the locally installed version, but the global install will take care of it either way

**Comment by talkol** [comment]
I pushed a small fix that will use the local mocha explicitly, so if you pull you won't need to `npm install mocha -g` anymore

**Comment by talkol** [comment]
please re-open if issue still isn't fixed
