### ISSUE TITLE
Detox CI fails on device.launchapp

### ISSUE THREAD

**Issue by asimyaramis** [wix/Detox#4018]
### What happened?

My detox pipeline fails on macos vm device.launchapp

    The pending request #-1000 ("isReady") has been rejected due to the following error:

    The app has crashed, see the details below:

    Exception was thrown: 
    RCTFatalException: Unhandled JS Exception: TypeError: undefined is not a function, js engine: hermes
    Unhandled JS Exception: TypeError: undefined is not a function, js engine: hermes, stack:

       beforeAll(async () => {
                await device.installApp();
             **line 4** : await device.launchApp({
           
              permissions: { notifications: "YES", camera: "YES", location: "always" },
             });
           });

      at Object.launchApp (src/login.test.js:4:18)

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 20.0.3
React Native version: 0.71
Has Fabric (React Native's new rendering system) enabled: (yes/no) 
Node version: .16.16.0
Device model: Iphone 14
iOS version: 
macOS version: latest
Xcode version: 14.2
Test-runner (select one): jest

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste your device.log here!
```

</details>

**Comment by noomorph** [comment]
Sounds like you've included the test file inside your React Native app. Detox tests are meant to be executed in Node.js, not in Hermes mobile engine.
