### ISSUE TITLE
detox tests hangs on app crash

### ISSUE THREAD

**Issue by ambatisuman** [wix/detox#402]
#### Description

We have the detox tests running for ios app on ios simulators. In the case of app crash the simulator log says
`com.apple.CoreSimulator.SimDevice.FCCEA413-BB02-4395-9CF8-8B8D39F5D0FC[3318] (com.apple.videosubscriptionsd[43741]): Service exited with abnormal code: 1`

and the ios app got crashed (closed) and the detox tests goes to hang state.
After sometime we can see the status is like,
```  Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at ../../../../node_modules/jest-jasmine2/build/queue_runner.js:64:21
      at ontimeout (timers.js:475:11)
      at tryOnTimeout (timers.js:310:5)
      at Timer.listOnTimeout (timers.js:270:5)
```
We are using Jest as the test runner.
Is there any way we can handle these kind of abnormal crashes in the app?

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 5.9.3
* Node: 8.1.4
* Device: iPhone 7 (ios 11.1) simulator
* Xcode: 9.1
* macOS: 10.12.6

**Comment by LeoNatan** [comment]
This is tracked in #161.
