### ISSUE TITLE
Detox Build failed

### ISSUE THREAD

**Issue by Ahmed-Shehzad** [wix/Detox#4023]
### Description

cd ./android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /mnt/c/my-app/node_modules/detox/android/detox/src/full/java/com/wix/detox/Detox.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /mnt/c/my-app/node_modules/detox/android/detox/src/full/java/com/wix/detox/Delegator.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugAndroidTestDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.genymotion.api.Battery found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
     Duplicate class com.genymotion.api.Battery$1 found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
     Duplicate class com.genymotion.api.Battery$2 found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
     Duplicate class com.genymotion.api.Battery$Mode found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
     Duplicate class com.genymotion.api.Battery$Status found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
     Duplicate class com.genymotion.api.DiskIO found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
     Duplicate class com.genymotion.api.GenydBinder found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
     Duplicate class com.genymotion.api.GenydBinder$1 found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
     Duplicate class com.genymotion.api.GenymotionException found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
     Duplicate class com.genymotion.api.GenymotionManager found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
     Duplicate class com.genymotion.api.GenymotionManager$1 found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
     Duplicate class com.genymotion.api.GenymotionManager$TokenValidity found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
     Duplicate class com.genymotion.api.Gps found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
     Duplicate class com.genymotion.api.Gps$1 found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
     Duplicate class com.genymotion.api.Gps$Status found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
     Duplicate class com.genymotion.api.Id found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
     Duplicate class com.genymotion.api.Id$1 found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
     Duplicate class com.genymotion.api.LocationParams found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
     Duplicate class com.genymotion.api.LocationParams$1 found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
     Duplicate class com.genymotion.api.LocationParams$Builder found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
     Duplicate class com.genymotion.api.MethodUnavailableException found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
     Duplicate class com.genymotion.api.Network found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
     Duplicate class com.genymotion.api.Network$Profile found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
     Duplicate class com.genymotion.api.NotGenymotionDeviceException found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
     Duplicate class com.genymotion.api.Orientation found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
     Duplicate class com.genymotion.api.Radio found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
     Duplicate class com.genymotion.api.Radio$1 found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
     Duplicate class com.genymotion.api.Radio$2 found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
     Duplicate class com.genymotion.api.Radio$3 found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
     Duplicate class com.genymotion.api.package-info found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
     Duplicate class com.genymotion.genyd.IGenydService found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
     Duplicate class com.genymotion.genyd.IGenydService$Stub found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
     Duplicate class com.genymotion.genyd.IGenydService$Stub$Proxy found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
     Duplicate class com.genymotion.genyd.NetworkProfile found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
     Duplicate class com.genymotion.genyd.NetworkProfile$1 found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
     Duplicate class com.genymotion.genyd.NetworkProfile$Name found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)
     Duplicate class com.genymotion.genyd.NetworkProfile$Status found in modules jetified-detox-20.7.0-runtime (com.wix:detox:20.7.0) and jetified-genymotion-api-1.2.0 (genymotion-api-1.2.0.jar)

     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.     

### Your environment

Detox version: ^20.7.0
React Native version: 0.71.6
Node version: v18.16.0
Device model: Nexus_5X_API_33
OS: Android
Test-runner (select one): Jest

Package.json:
{
  "name": "my-app",
  "version": "1.0.0",
  "jest": {
    "preset": "jest-expo",
    "transformIgnorePatterns": [
      "node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg)"
    ],
    "collectCoverage": true,
    "collectCoverageFrom": [
      "**/*.{js,jsx,ts,tsx}",
      "!**/coverage/**",
      "!**/node_modules/**",
      "!**/babel.config.js",
      "!**/jest.setup.js"
    ]
  },
  "scripts": {
    "start": "expo start --dev-client",
    "detox:build:android:debug": "detox build -c android.emu.debug",
    "dev": "react-native start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "test": "jest"
  },
  "dependencies": {
    "@expo/match-media": "^0.4.0",
    "@expo/webpack-config": "^18.0.4",
    "expo": "~48.0.11",
    "expo-build-properties": "~0.6.0",
    "expo-dev-client": "~2.2.1",
    "expo-dev-launcher": "^2.2.1",
    "expo-splash-screen": "~0.18.1",
    "expo-status-bar": "~1.4.4",
    "expo-system-ui": "~2.2.1",
    "jest": "^29.5.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.71.6",
    "react-native-web": "~0.19.4",
    "react-responsive": "^9.0.2",
    "ts-node": "^10.9.1"
  },
  "devDependencies": {
    "@babel/core": "^7.21.4",
    "@testing-library/jest-dom": "^5.16.5",
    "@types/detox": "^18.1.0",
    "@types/jest": "^29.5.0",
    "@types/react": "~18.0.37",
    "@types/react-dom": "~18.0.11",
    "@types/react-native": "~0.71.6",
    "detox": "^20.7.0",
    "jest": "^29.5.0",
    "jest-expo": "^48.0.2",
    "typescript": "^5.0.4"
  },
  "peerDependencies": {
    "@expo/config-plugins": "~6.0.1"
  },
  "private": true
}

detoxrc.ts:
import appConfig from "./app.config";

///<reference path="node_modules/detox/index.d.ts.ts"/>
const config: Detox.DetoxConfig = {
  testRunner: {
    args: {
      $0: "jest",
      config: "e2e/jest.config.ts",
    },
    jest: {
      setupTimeout: 120000,
    },
  },
  apps: {
    "ios.debug": {
      type: "ios.app",
      binaryPath: `ios/build/Build/Products/Debug-iphonesimulator/${appConfig.name}.app`,
      build: `xcodebuild -workspace ios/${appConfig.name}.xcworkspace -scheme ${appConfig.name} -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build`,
    },
    "ios.release": {
      type: "ios.app",
      binaryPath: `ios/build/Build/Products/Release-iphonesimulator/${appConfig.name}.app`,
      build: `xcodebuild -workspace ios/${appConfig.name}.xcworkspace -scheme ${appConfig.name} -configuration Release -sdk iphonesimulator -derivedDataPath ios/build`,
    },
    "android.debug": {
      type: "android.apk",
      binaryPath: "android/app/build/outputs/apk/debug/app-debug.apk",
      build:
        "bash env.sh && cd ./android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug --stacktrace > stacktrace.debug.txt",
      reversePorts: [8081],
    },
    "android.release": {
      type: "android.apk",
      binaryPath: "android/app/build/outputs/apk/release/app-release.apk",
      build:
        "bash env.sh && cd ./android && ./gradlew assembleRelease assembleAndroidTest -DtestBuildType=release --stacktrace > stacktrace.release.txt",
    },
  },
  devices: {
    simulator: {
      type: "ios.simulator",
      device: {
        type: "iPhone 12",
      },
    },
    attached: {
      type: "android.attached",
      device: {
        adbName: ".*",
      },
    },
    emulator: {
      type: "android.emulator",
      device: {
        avdName: "Nexus_5X_API_33",
      },
    },
  },
  configurations: {
    "ios.sim.debug": {
      device: "simulator",
      app: "ios.debug",
    },
    "ios.sim.release": {
      device: "simulator",
      app: "ios.release",
    },
    "android.att.debug": {
      device: "attached",
      app: "android.debug",
    },
    "android.att.release": {
      device: "attached",
      app: "android.release",
    },
    "android.emu.debug": {
      device: "emulator",
      app: "android. Debug",
    },
    "android.emu.release": {
      device: "emulator",
      app: "android.release",
    },
    "android.emu.debug.manual": {
      device: "emulator",
      app: "android.debug",
      behavior: {
        launchApp: "manual",
      },
    },
  },
};

export default config;

**Comment by noomorph** [comment]
@d4vidi , ChatGPT says:

> Based on the provided information, the build is failing due to duplicate classes found in the detox and genymotion-api modules. To resolve this issue, you can try excluding the genymotion-api module from your project's dependencies, since it seems that detox already includes the required classes.

> In your android/app/build.gradle file, add the following lines to exclude the genymotion-api module:

```groovy
configurations {
    all {
        exclude group: 'com.genymobile', module: 'genymotion-api'
    }
}
```

> This code snippet will exclude the conflicting genymotion-api module from your dependencies, and the build should proceed without issues related to duplicate classes.

> After adding the exclusion, try running the build command again:

```sh
cd ./android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug
```

> If the issue persists, please provide any new error messages or further information to help diagnose the problem.

Does it make any sense to you on the Android part? 🧐
