### ISSUE TITLE
How to start the react-native debugger along with the test?

### ISSUE THREAD

**Issue by drumnation** [wix/detox#403]
If I enable "Debug JS Remotely" and then run my test the app will relaunch with "Debug JS Remotely" off.  

I'd like to be able to view my console.logs while I tried to debug an issue. I love having detox because I don't have to type anything to test the form and login flow... but for it to be useful besides knowing whether it passed each test I need to be able to see what happened when the test failed in the debugger.

Thanks!

**Comment by LeoNatan** [comment]
This is not supported and will not be implemented. When you use remote JS debugger, all JS calculation is performed on another process (Chrome) and Detox cannot sync your app reliably. You can read your logs after Detox finishes running your tests.
