### ISSUE TITLE
CI setup on Azure Devops

### ISSUE THREAD

**Issue by minnocci-bcgdv** [wix/Detox#4054]
### Description

Hi Everyone!

I am running CI on Azure Devops and I want to execute the Detox tests for my RN app on Android. I could not achieve this yet, hence I wanted to check here if anyone had to tackle a similar CI setup as I do for running Detox.

I ended up moving to a VMSS because of timeouts using hosted agents and because it seems to be impossible to run them on hosted agents using ubuntu.

I am running my tests against an imposter server and everything works fine locally, but the CI setup is being a bit painful.

Did happen anyone to have to setup run on CI for android?

Thank you!

### Your environment

Detox version: 20.0.3
React Native version: 0.70.5
Node version: 16.14.2
Device model: API32
OS: Android
Test-runner (select one): Jest

**Comment by minnocci-bcgdv** [comment]
Hi @asafkorem thanks for replying! Many issues and questions, let's start with these 3:
1) Can detox tests run on azure self hosted agents or is it too slow? (I was time-outing 1h easy)
2) Does matter to run on ubuntu / macos? (assuming iOS won't run on ubuntu, but scope of the Q is Android for now)
3) How to run the emulator? Tried several approaches:
```
      #     nohup $ANDROID_HOME/emulator/emulator -avd Pixel_XL_API_32 -skin 1080x1920 -no-snapshot -no-audio -no-boot-anim -accel auto -gpu auto -qemu -lcd-density 420 > /dev/null 2>&1 &
      #     $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'
```
Never worked because it waited forever. How can one launch the android emulator (if needed to have it launchedI?

Any insights super appreciated!

**Comment by minnocci-bcgdv** [comment]
My current state:

```
  ● Test suite failed to run

    ChildProcessError: `/opt/android-sdk/emulator/emulator -verbose -no-audio -no-boot-anim -read-only -port 18222 @Pixel_XL_API_32` failed with code null

      at ChildProcess.<anonymous> (../../../node_modules/child-process-promise/lib/index.js:132:23)
08:34:04.662 detox[18634] i `/opt/android-sdk/emulator/emulator -verbose -no-audio -no-boot-anim -read-only -port 18588 @Pixel_XL_API_32` failed with code null
  error: true
08:34:04.662 detox[18634] i INFO    | Android emulator version 32.1.13.0 (build_id 10086546) (CL:N/A)
INFO    | Found systemPath /opt/android-sdk/system-images/android-32/google_apis/x86_64/
WARNING | Please update the emulator to one that supports the feature(s): Vulkan
Fatal: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

What could it be? This is running on an ubuntu machine on Azure. We are executing the tests with the `--headless` flag...

**Comment by asafkorem** [comment]
Reopening, this might still be relevant.
@minnocci-bcgdv, did you manage to figure this out?

**Comment by minnocci-bcgdv** [comment]
Yes!
- Using a vmss (ubuntu)
- Building detox and running the tests in separate steps

To start the emulator with:
`sudo screen -S emu -d -m /opt/android-sdk/emulator/emulator -avd Pixel_XL_API_31 -skin 1080x1920 -no-snapshot -no-audio -no-boot-anim -accel auto -gpu auto -qemu -lcd-density 420`

Thanks @asafkorem for following up!
