### ISSUE TITLE
Issue finding Android APK

### ISSUE THREAD

**Issue by davidmcraejr** [wix/Detox#4057]
### Description

I am setting up detox in our React Native application, I have iOS running and now running into issues for Android.  In the `.detoxrc.js` config file I have `android/app/build/outputs/apk/androidTest/dev/debug/app-dev-debug-androidTest.apk` set as the `binaryPath` for Android but when I run `detox test --configuration android.emu.debug` I get the output of `The test APK could not be found at path: '/Users/xxx/Documents/git/mobile-app/android/app/build/outputs/apk/androidTest/androidTest/devDebug/androidTest/app-dev-debug-androidTest-androidTest.apk'`
Somehow it seems to be appending extra path and file data, thoughts?

### Your environment

Detox version: 20.7.2
React Native version:  0.71.3
Node version: 18.9.0
Device model: Emulator
OS: Android
Test-runner (select one): jest

**Comment by davidmcraejr** [comment]
didn't realize there was a `testBinaryPath` and a `binaryPath`

**Comment by KaterinaUK** [comment]
@davidmcraejr I have the exact same issue as you described, what did you place in each of testBinaryPath and binaryPath?

to build our app we use npx react-native run-android, which gives me only the android/app/build/outputs/apk/debug/app-debug.apk

and it seems I cannot put this path as the same location for both values.

**Comment by davidmcraejr** [comment]
@KaterinaUK we build a debug app and test app so have two apk's to use for each values, here what we have - 

```
binaryPath: 'android/app/build/outputs/apk/local/debug/app-local-debug.apk',
testBinaryPath: 'android/app/build/outputs/apk/androidTest/local/debug/app-local-debug-androidTest.apk',
```

**Comment by KaterinaUK** [comment]
> 

how are you going about building each of these?

**Comment by davidmcraejr** [comment]
We run

```
build: 'cd android && ./gradlew assembleDevDebug assembleAndroidTest -DtestBuildType=debug && cd ..',
```

NOTE: "assembleDevDebug" is a specific build type for us so you would have to set the build types that are associated with your project.

Once those are setup correctly and pointed correctly - Detox will install the correct app and run the tests
