### ISSUE TITLE
Could not resolve firebase dependancies while building android app

### ISSUE THREAD

**Issue by paryanihitesh** [wix/Detox#4059]
### What happened?

Getting this error while building android

`* What went wrong:
Could not determine the dependencies of task ':app:compileDebugAndroidTestJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugAndroidTestCompileClasspath'.
   > Could not find com.google.firebase:firebase-crashlytics:.
     Required by:
         project :app
   > Could not find com.google.firebase:firebase-analytics:.
     Required by:
         project :app`
         
Version
"detox": "19.1.0",
"jest": "27.5.1",
"jest-circus": "27.4.2",
"react-native": 0.69.6,
"expo": "46.0.0"

### What was the expected behaviour?

App should build successfully

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

Try building app with expo, react native with firebase analytics and crashlytics enabled

### In what environment did this happen?

Detox version: 19.1.0
React Native version: 0.69.6
Has Fabric (React Native's new rendering system) enabled: (yes/no) no
Node version: 16.0.0
Device model:
Android version: 
Test-runner (select one): jest

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste your device.log here!
```

</details>

**Comment by HassaanShahzad98** [comment]
Hello, were you able to find a solution for this? i am facing the same thing

**Comment by mhsfh** [comment]
i'm getting the same error

**Comment by adorum** [comment]
same problem here. Any suggestions?
