### ISSUE TITLE
Asynchronous function issue

### ISSUE THREAD

**Issue by heuism** [wix/detox#406]
I hope that the idea that I am saying will make sense.

FYI, The issue right now is that because of the asynchronous therefore when It look for the components, it still say it pass

This one is an example:
```
        tail -F $HOME/Library/Developer/CoreSimulator/Devices/47F630BB-0129-447A-AAA3-29B45114D902/data/tmp/detox.last_launch_app_log.{out,err} 
  Simple Cases
    ✓ should have welcome screen (10781ms)
    1) should click the ABOUT US button
```

Then later on, it failed because it can't locate the welcome screen. Which is really hard to debug in the long run if we have a lot of asynchronous function.

I am not sure is there a way to run it in synchronous? Or running these tests as asynchronous is the proper way to deal with testing.

Thanks.

**Comment by LeoNatan** [comment]
This is how the API is intended. However a following test will not proceed until the previous is finished.
