### ISSUE TITLE
[SG4] Implement a BiDi API and investigate potential issues ❗

### ISSUE THREAD

**Issue by noomorph** [wix/Detox#4080]
Try to "connect" to the Detox log and see how it goes with WebSockets.

**Comment by d4vidi** [comment]
@noomorph could you sum up your findings for future ref, and close this?

**Comment by noomorph** [comment]
I can't say I finished the investigation here completely, but the general summary is the following:

- Detox client needs to send a request for the BiDi in the capabilities request
- Selenium Grid Hub acts as a very dumb proxy – it cannot set up tunnels for us
- So, Detox Server must be the one to set up a WS tunnel end-to-end for our client

This is possible but not very easy. It will require a side-project for us.
Locally, this communication is trivial enough to set up, but I didn't advance anywhere further than a hello world example there, to be honest. @d4vidi

**Comment by d4vidi** [comment]
Thanks @noomorph
