### ISSUE TITLE
Resume detox recorder to simplify element identification and make detox easier

### ISSUE THREAD

**Issue by aaronpliu** [wix/Detox#4084]
### Describe your idea

It's regret to stop detox recorder support due to lack of manpower. auto recorder is an effective approach to simplify coding and a way to increase efficiency.
Not sure if it will be resumed in someday. I hope detox would align with other open source framework and make it better. Also, to support iOS real device.
I haven't found a better tool than Detox for RN app.

**Comment by d4vidi** [comment]
@aaronpliu Thanks, we might actually resume work on the recorder one day because of it will provide us great value as testers, as well. Nevertheless at the moment any improvement in the project will be based on voluntary contribution.

**Comment by asafkorem** [comment]
There's a repo for detox-recorder project (this is not part of detox itself). You can open this discussion there, maybe someone will be willing to contribute fixes to this open source project. 

https://github.com/wix-incubator/DetoxRecorder
