### ISSUE TITLE
DetoxRuntimeError: Detox worker instance has not been installed in this context (DetoxPrimaryContext)

### ISSUE THREAD

**Issue by micahdasMA** [wix/Detox#4087]
### What happened?

When attempting to run detox tests with typescript and Jest, the detox tests fail with the error 

    DetoxRuntimeError: Detox worker instance has not been installed in this context (DetoxPrimaryContext).
    
    HINT: If you are using Detox with Jest according to the latest guide, please report this issue on our GitHub tracker:
    https://github.com/wix/Detox/issues
    Otherwise, make sure you call detox.installWorker() beforehand.

      3 | describe('When accessing the app for the first time', () => {
      4 |   beforeAll(async () => {
    > 5 |     await device.launchApp();
        |                  ^
      6 |   });
      7 |
      8 |   beforeEach(async () => {

      at DetoxPrimaryContext.get (node_modules/detox/src/realms/DetoxContext.js:117:13)
      at node_modules/detox/src/realms/DetoxContext.js:72:36
      at directGetter (node_modules/funpermaproxy/lib/permaproxy.js:10:24)
      at Object.getter [as get] (node_modules/funpermaproxy/lib/permaproxy.js:21:22)
      at Object.<anonymous> (e2e/basicAppLogin.test.ts:5:18)`

### What was the expected behaviour?

Expected detox tests to run successfully as they had when running them directly through detox

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 20.9.1
React Native version: 0.71.7
Has Fabric (React Native's new rendering system) enabled: (yes/**no**) 
Node version: 16.20.0
Device model: iOS Simulator
iOS version: 
macOS version: 13.3.1 
Xcode version: 14.3
Test-runner (select one): **jest** / other

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste your device.log here!
```

</details>

### More data, please!

app/e2e/jest.config.ts
```
/** @type {import('@jest/types').Config.InitialOptions} */
module.exports = {
  preset: 'react-native',
  rootDir: '..',
  testMatch: ['<rootDir>/e2e/**/*.test.ts'],
  testTimeout: 120000,
  maxWorkers: 1,
  globalSetup: 'detox/runners/jest/globalSetup',
  globalTeardown: 'detox/runners/jest/globalTeardown',
  reporters: ['detox/runners/jest/reporter'],
  testEnvironment: 'detox/runners/jest/testEnvironment',
  verbose: true,
  setupTestFrameworkScriptFile: './init.ts'
};
```

app/.detoxrc.js

````
/** @type {Detox.DetoxConfig} */
module.exports = {
  testRunner: {
    args: {
      $0: 'jest',
      config: 'e2e/jest.config.ts'
    },
    jest: {
      setupTimeout: 120000
    }
  },
  apps: {
    'ios.debug': {
      type: 'ios.app',
      binaryPath: 'ios/build/Build/Products/Debug-iphonesimulator/MyApp.app',
      build: 'xcodebuild -workspace ios/MyApp.xcworkspace -scheme MyApp -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build'
    },
    'ios.release': {
      type: 'ios.app',
      binaryPath: 'ios/build/Build/Products/Release-iphonesimulator/MyApp.app',
      build: 'xcodebuild -workspace ios/MyApp.xcworkspace -scheme MyApp -configuration Release -sdk iphonesimulator -derivedDataPath ios/build'
    },
    'android.debug': {
      type: 'android.apk',
      binaryPath: 'android/app/build/outputs/apk/debug/app-debug.apk',
      build: 'cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug',
      reversePorts: [
        8081
      ]
    },
    'android.release': {
      type: 'android.apk',
      binaryPath: 'android/app/build/outputs/apk/release/app-release.apk',
      build: 'cd android && ./gradlew assembleRelease assembleAndroidTest -DtestBuildType=release'
    }
  },
  devices: {
    simulator: {
      type: 'ios.simulator',
      device: {
        type: 'iPhone 14'
      }
    },
    attached: {
      type: 'android.attached',
      device: {
        adbName: '.*'
      }
    },
    emulator: {
      type: 'android.emulator',
      device: {
        avdName: 'Pixel_3a_API_30_x86'
      }
    }
  },
  configurations: {
    'ios.sim.debug': {
      device: 'simulator',
      app: 'ios.debug'
    },
    'ios.sim.release': {
      device: 'simulator',
      app: 'ios.release'
    },
    'android.att.debug': {
      device: 'attached',
      app: 'android.debug'
    },
    'android.att.release': {
      device: 'attached',
      app: 'android.release'
    },
    'android.emu.debug': {
      device: 'emulator',
      app: 'android.debug'
    },
    'android.emu.release': {
      device: 'emulator',
      app: 'android.release'
    }
  }
};

**Comment by noomorph** [comment]
What is inside setupTestFrameworkScriptFile ?

**Comment by micahdasMA** [comment]
Whoops, some of these changes were leftover from trying various fixes found online. The `setupTestFrameworkScriptFile` was from a previous setup attempt. That file doesn't actually exist, but removing that line from the config doesn't change anything. The same is true with using jest.config.ts. I changed it back to jest.config.js and still no change 

I am attempting to use typescript for my tests, following this guide https://remarkablemark.org/blog/2023/02/21/detox-typescript/

**Comment by noomorph** [comment]
Let's see now about react-native preset removal.

**Comment by noomorph** [comment]
Actually I was not saying that you cannot use TypeScript everywhere, just saying that this is something I don't usually practice with Detox so it falls under suspicions while investigating your issue

**Comment by micahdasMA** [comment]
Commenting out `preset: react-native` also does not fix the error :/ 
Is there a particular place where I am supposed to call `detox.installWorker()` ?

**Comment by noomorph** [comment]
Interesting. Regarding `detox.installWorker`, this happens either in detox.init or in detox.installWorker here:

https://github.com/wix/Detox/blob/master/detox/runners/jest/testEnvironment/index.js#L110-L114

Try to add some console.logs and see whether your test environment is called locally in setup method : 
https://github.com/wix/Detox/blob/master/detox/runners/jest/testEnvironment/index.js#L68-L71

**Comment by micahdasMA** [comment]
@noomorph Can you give me a location where I should put the console.log? The test is 
```
import { by, device, expect, element } from 'detox';

describe('When accessing the app for the first time', () => {
  beforeAll(async () => {
    console.log('before test is run')
    await device.launchApp();
  });

  beforeEach(async () => {
    await device.reloadReactNative();
  });

it('should have swipeable value prop messages', async () => {
    await expect(element(by.id('GetStarted1'))).toBeVisible();
});
```

**Comment by noomorph** [comment]
I suggest entering `node_modules/detox/runner/jest/testEnvironment/index.js` and using `console.log like a machete in a jungle there.

**Comment by noomorph** [comment]
Also, @micahdasMA could you downgrade to some Jest 29.0 or 29.1 . Let's also check that it is not "a new version issue".

**Comment by micahdasMA** [comment]
Added a ton of `console.log`s in that file and none of them got hit aside from the one in the detox test itself! My guess is that the way Jest is configured is looking for every `*.test.*` file and trying to run these Detox tests in the Jest context and is not doing anything to set up the Detox tests first. The `npm test` command that I use to run the jest tests is executing `jest --collectCoverage --runInBand`

**Comment by aaronpliu** [comment]
suggest to using jest.config.js as recommended.
and add init:
```
const internals = require('detox/internals')
const config = require('../.detoxrc')  // load .detoxrc config
internals.init(config)
detox.device.launchApp()
```

**Comment by micahdasMA** [comment]
@aaronpliu Unfortunately that did not help either. I am still getting the same error when running `npm test`

**Comment by noomorph** [comment]
Sorry, not enough context. This is certainly a configuration/environment issue. Please come back with more details if necessary.
