### ISSUE TITLE
Can't turn off trace output

### ISSUE THREAD

**Issue by jzaefferer** [wix/Detox#4089]
### Description

While running detox on Bitrise, we're getting a lot of verbose output, like this:
```
15:13:07.309 detox[17005] i The app is busy with the following tasks:
• There are 10 work items pending on the dispatch queue: "Main Queue (<OS_dispatch_queue_main: com.apple.main-thread>)".
• UI elements are busy:
  - Layers pending animations: 96.
  - Layers needs layout: 173.
  - View needs layout: 74.
  - View needs display: 98.
  - Layers needs display: 90.
• Run loop "Main Run Loop" is awake.
• There are 1 pending delayed selectors to be performed.
• 2 enqueued native timers:
  - Timer #1:
    + Fire date: none.
    + Time until fire: 0.000.
    + Repeat interval: 0.
    + Is recurring: YES.
  - Timer #2:
    + Fire date: 2023-05-26 15:13:07 +0000.
    + Time until fire: 0.100.
    + Repeat interval: 0.
    + Is recurring: NO.
```
This seems to be trace-level output (comparing to https://hackmd.io/@lukerogerson/SJ9esRUyu ), which we didn't configure anywhere.

Our `.detoxrc.js` has no configuration for logging. Our jest.config.js looks like this:
```
module.exports = {
  maxWorkers: 4,
  testTimeout: 300000,
  verbose: true,
  rootDir: '..',
  testMatch: ['<rootDir>/e2e/**/*.e2e.js'],
  reporters: ['detox/runners/jest/reporter'],
  globalSetup: 'detox/runners/jest/globalSetup',
  globalTeardown: 'detox/runners/jest/globalTeardown',
  testEnvironment: 'detox/runners/jest/testEnvironment',
};
```
We've tried removing `verbose: true`, but that made no difference.

How can we turn off this trace output?

### Your environment

Detox version: 20.1.0
React Native version: 0.68.2
Node version: 16.18.1
Device model: iPhone 13 simulator
OS: iOS 16.x
Test-runner (select one): jest

**Comment by noomorph** [comment]
These specific logs are caused by this param: https://wix.github.io/Detox/docs/next/config/session/#sessiondebugsynchronization-number (as the docs say, set it to zero).

**Comment by jzaefferer** [comment]
Thanks! I'll give that a try. 

PS: I don't think I ever would've been able to find that myself. Maybe this could be a useful hint on https://wix.github.io/Detox/docs/next/config/logger/ ?

**Comment by noomorph** [comment]
Good suggestion. Added to the backlog: https://github.com/wix/Detox/issues/4090
