### ISSUE TITLE
Add a hint to logger docs about the synchronization

### ISSUE THREAD

**Issue by noomorph** [wix/Detox#4090]
### Describe your idea

Related to: #4089

> Maybe this could be a useful hint on https://wix.github.io/Detox/docs/next/config/logger/?

These specific logs are caused by this param: https://wix.github.io/Detox/docs/next/config/session/#sessiondebugsynchronization-number (as the docs say, set it to zero).

**Comment by jzaefferer** [comment]
Some more info on this: I ended up copying the example, changing from the default of 10,000 to the example of 20,000. This actually hides a lot of the debug output, but still keeps some when tests take a long time. For now that seems more useful.

I still don't really understand what this option does - if the recommendation is to turn it off, what would I loose? Why is it enabled by default?

**Comment by jzaefferer** [comment]
One more note: https://wix.github.io/Detox/docs/articles/how-detox-works explains about Detox syncs with the app state, which sounds related to the `session.debugSynchronization` setting, but there's no mention of it. If it's related, a link would be great. If not, an explainer how that's unrelated would help, too.

**Comment by jzaefferer** [comment]
I've finally discovered https://wix.github.io/Detox/docs/troubleshooting/synchronization/, too. Links to this page from how-detox-works, logger and config/session pages would be valuable as well.

**Comment by jzaefferer** [comment]
Trying to answer my own, earlier question:
> I still don't really understand what this option does - if the recommendation is to turn it off, what would I loose? Why is it enabled by default?

Setting it to `0` would turn off the logging, making it harder to understand why tests time out. So for me changing it to 20000 (20s) as the docs example suggest worked out fine. I get some debug output if tests are stuck a long time, but not from all the other tests.

At some point we need to investigate why so many tests have to wait 10+s for synchronisation though.

**Comment by noomorph** [comment]
@jzaefferer thanks for your involvement. I've been a bit busy lately, but I'm going to take this in the next couple of days for sure. Thanks for your patience and your helpful input.
