### ISSUE TITLE
[Detox Compatibility Inquiry] Support for React Native 0.71

### ISSUE THREAD

**Issue by salmaAlouane** [wix/Detox#4098]
### Description

Dear Detox Team,

I hope this message finds you well. Three weeks ago, I submitted an issue regarding the compatibility of Detox with React Native version 0.71. At that time, you responded by mentioning that Detox was compatible with React Native version 0.70 (#4056)  and that compatibility with version 0.71 was planned in the near future (#3884).

I would like to inquire whether Detox is now compatible with React Native version 0.71 or if you still plan to release a Detox version that supports this React Native version.

Thank you sincerely for your attention and the outstanding work you do with Detox. Your response would be greatly appreciated.

Best regards,

### Your environment

Detox version: ^20.9.0
React Native version: ^0.71.7
Node version: v18.12.1
Device model: DUB-LX1
OS: Android
Test-runner (select one): jest

**Comment by kevindice** [comment]
See https://github.com/wix/Detox/issues/3884
