### ISSUE TITLE
Support long press duration for element

### ISSUE THREAD

**Issue by jhen0409** [wix/detox#410]
We have a use case of two events for different long press duration, implement by `onPressIn` and `onPressOut`.

It would be great if we could support duration for [`longPress`](https://github.com/wix/detox/blob/a1ca6c35bdc2ed8264c4e880872b2bf384a4230c/detox/src/ios/expect.js#L60).

For iOS, we could use [`actionForLongPressWithDuration`](https://github.com/google/EarlGrey/blob/master/EarlGrey/Action/GREYActions.h#L54) of EarlGrey, but I don't know how to do for Android.

**Comment by LeoNatan** [comment]
Good suggestion, thanks!

PRs are welcome. Perhaps someone can assist with Android.

**Comment by LeoNatan** [comment]
Thanks for implementing!
