### ISSUE TITLE
Snyk is reporting high vulnerability in "org.json.json" dependency

### ISSUE THREAD

**Issue by akkadaya** [wix/Detox#4106]
### What happened?

Snyk is reporting a high vulnerability in "org.json.json:20140107" and recommends upgrading to "org.json.json:20230227" or higher

- https://security.snyk.io/vuln/SNYK-JAVA-ORGJSON-5488379
- https://security.snyk.io/vuln/SNYK-JAVA-ORGJSON-2841369

Dependency location:  
https://github.com/wix/Detox/blob/master/detox/android/detox/build.gradle#L136

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

Do `snyk test`

**Comment by asafkorem** [comment]
Thanks for the report @akkadaya. I've opened a PR: https://github.com/wix/Detox/pull/4174
