### ISSUE TITLE
Running multiple configurations

### ISSUE THREAD

**Issue by Perfect7M** [wix/Detox#4113]
### What happened?

Detox cannot destroy instances and run after `cleanup`. I have similar code in my application:
```tsx
const detox = require('detox/internals');

async function main() {
   await detox.init({
    argv: {
      configuration: 'ios.release'
    },
  });

  await detox.cleanup();

  await detox.init({
    argv: {
      configuration: 'android.release'
    },
  });
}

main();
```

I'm getting:
```
DetoxRuntimeError: Cannot initialize primary Detox context more than once.
```

What I want to achieve to run multiple configurations for different platforms in a single file.

### What was the expected behaviour?

There is a `.destroy` method or you can change configuration dynamically without destroying detox instance

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Help us reproduce this issue!

```js
module.exports = {
  testRunner: {
    args: {
      '$0': 'jest',
      config: 'e2e/jest.config.js'
    },
    jest: {
      setupTimeout: 120000
    }
  },
  apps: {
    'ios.release': {
      type: 'ios.app',
      binaryPath: "dist/ios-app.app",
    },
    'android.release': {
      type: 'android.apk',
      binaryPath: "dist/android-app.apk",
      testBinaryPath: "dist/android-app-test.apk"
    }
  },
  devices: {
    simulator: {
      type: 'ios.simulator',
      device: {
        type: 'iPhone 12'
      }
    },
    emulator: {
      type: 'android.emulator',
      device: {
        avdName: 'Pixel_3a_API_34_extension_level_7_arm64-v8a'
      }
    }
  },
  configurations: {
    'ios.release': {
      device: 'simulator',
      app: 'ios.release'
    },
    'android.release': {
      device: 'emulator',
      app: 'android.release'
    }
  }
};

```

### In what environment did this happen?

Detox version: 20.9.1
React Native version: expo rn-0.71.8
Has Fabric (React Native's new rendering system) enabled: expo
Node version: 16.20.0
Test-runner (select one): other

### Detox logs

<details><summary>Detox logs</summary>

```
N/A
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
N/A
```

</details>

**Comment by noomorph** [comment]
I understand what you mean. In v20 refactor I did not focus on this not so frequent use case to cut some corners.

I don't think I will address this due to fundamental architecture changes I am working on, exactly in this part.

But if you make a pull request sooner, I'll try to help you to complete it.

**Comment by Perfect7M** [comment]
I would love to contribute. Could you please share more about API and how it should work? And it will be awesome if you point me where should I start

**Comment by noomorph** [comment]
Well, that might be possible only for non-Jest tests. I mean, Jest integration is quite complex and I myself don't have a good idea yet how to make it work with test matrixes.

Do you want to implement it for Jest tests? Or you will be fine with some improvized quick and dirty test runner without any reporters, setups, etc.?

**Comment by Perfect7M** [comment]
An improvised one will work for me. I'm creating screenshots from the Android and ios app. Right now it works when I'm making screenshots for android or ios, but when I want to make screenshot for Android then change the configuration and make screenshots for ios this happens

**Comment by d4vidi** [comment]
Sorry for barging in but what about running Detox several times, each with a different config?

**Comment by Perfect7M** [comment]
@d4vidi It will be okay for me but when I'm config 
```js
await detox.init({
  argv: {
    configuration: 'android.release'
  },
});
```
how do "clear" that and init it again? Do you think of spawning child processes and cleanup detox at the end? Or using worker threads?

Could you please elaborate on what you have in mind?

**Comment by noomorph** [comment]
I managed to make this snippet work:

```js
// parent-runner.js
const path = require('path');
const { fork } = require('child_process');

async function runSandboxedTests(selectedConfiguration) {
  return new Promise((resolve, reject) => {
    const child = fork(path.join(__dirname, 'child-runner.js'), [selectedConfiguration]);

    child.on('error', reject);

    child.on('exit', (code) => {
      if (code === 0) {
        resolve();
      } else {
        reject(new Error(`Child process exited with code ${code}`));
      }
    });
  });
}

async function main() {
  await runSandboxedTests('ios.sim.debug');
  await runSandboxedTests('android.emu.debug');
}

main().catch(e => console.error(e));
```

```js
// child-runner.js
const detox = require('detox/internals');
const log = detox.log.child({ cat: ['lifecycle'] });

async function main(selectedConfiguration) {
  async function test1() {
    log.info('Test 1');
    await device.launchApp();
  }

  async function test2() {
    log.info('Test 2');
    await device.terminateApp();
  }

  try {
    await detox.init({ override: { selectedConfiguration } });
    await test1();
    await test2();
  } finally {
    await detox.cleanup();
  }
}

const selectedConfiguration = process.argv[2];

main(selectedConfiguration)
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
```

Although it seems to work, after all, I think I can't really dedicate story points to solving this issue in terms of Detox 20 architecture. We'll be moving in quite an "orthogonal" direction now, and I just see I'd have to repeat the same work and remove it then. I can't provide support for this snippet either – just giving it as one of the possible directions of thought.

**Comment by Perfect7M** [comment]
I understand you need to do your things. Thank you for this detailed example and for the help here. I'm happy with this solution and looking forward to a new iteration of Detox API.
