### ISSUE TITLE
Unable to run tests on react-native app that does not have detox native code embedded into it (running test on independent apk)

### ISSUE THREAD

**Issue by abajajct** [wix/Detox#4120]
### What happened?

 I have a react-native application that does not have Detox code embedded into it. I have set the path of the binary in detox config to point to the apk correctly. When I try running the test, it errors out stating 

> No instrumentation runner found on device emulator-14834 for package com.x.y

### What was the expected behaviour?

I was expecting the test to to run on a react-native application that does not have detox code embedded into it

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 20.9.1
React Native version: 0.71.8
Has Fabric (React Native's new rendering system) enabled: (yes/no) no
Node version: 18
Device model: Nexus 6
Android version:  Android 12
Test-runner (select one): jest / other jest

### Detox logs

<details><summary>Detox logs</summary>

```
e2e/starter.test.js (6.245 s)
  Example
    ✕ should have welcome screen (1 ms)
    ✕ should show hello screen after tap
    ✕ should show world screen after tap

  ● Example › should have welcome screen

    No instrumentation runner found on device emulator-14834 for package com.x.y

      1 | describe('Example', () => {
      2 |   beforeAll(async () => {
    > 3 |     await device.launchApp();
        |                  ^
      4 |   });
      5 |
      6 |   beforeEach(async () => {

      at Object.launchApp (e2e/starter.test.js:3:18)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)
      at node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:7
      at Object.<anonymous> (node_modules/@babel/runtime/helpers/asyncToGenerator.js:19:12)
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste your device.log here!
```

</details>

**Comment by abajajct** [comment]
@d4vidi @noomorph  Sorry for explicitly tagging you. I just wanted to check what I am trying to do is even possible with detox

**Comment by noomorph** [comment]
If you don't use test apks, it won't work

**Comment by abajajct** [comment]
Will really appreciate if you can elaborate. 

a) Does that mean I'll have to run the detox tests after building the app and app must have the detox code embedded into it?

b) How can we run the tests on a release apk (which has detox configuration embedded into it) i.e let's say I just have access to the apk file and not the code repo

**Comment by noomorph** [comment]
When you write instrumentation tests (tests that run on an Android device or emulator and have access to information about the app's environment) in Android, these are also compiled into an APK called "test APK". Ir is separate from your main APK, but it has a reference to the main APK. The Test APK can't be installed alone; it needs to be installed with the main APK because it calls the main APK during its testing processes.

Detox for Android operates on basis of test apks.

Release APK doesn't have Detox embedded into it (even if did, Detox would not be able to work that way). It should come as a pair of files: release APK, test APK for your release APK.

I hope that helps.

**Comment by drajnamichal** [comment]
Is there any solution? I have the same issue.

**Comment by abajajct** [comment]
@noomorph has provided a detailed response for the same. I don't think there is way out
