### ISSUE TITLE
Android Crash SIGSEGV running detox

### ISSUE THREAD

**Issue by davek1121** [wix/detox#413]
#### Description

We are getting a seg fault while running our detox tests on an Android emulator.
Emulator: x86   Pixel XL with Android API 25
Android: API 25
Detox version: 5.9.2

All tests run fine on iOS
All tests run fine on Android individually
The cpu runs high and the app crashes after about 10-12 tests.
I have tried other emulator versions with no success.

#### Steps to Reproduce
Not sure how to provide steps to reproduce.
Run detox tests with > 12 tests with multiple react-native screens.  Note:  We are using react-native navigation, not wix's react-native-navigation

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 5.9.2
* Node: 8.1.4
* Device: Android emulator with Android 25
* Xcode: N/A
* macOS: 10.12.6

#### Device and verbose Detox logs
[detoxsegfault.txt](https://github.com/wix/detox/files/1479648/detoxsegfault.txt)
[detoxsegfaultverbose.txt](https://github.com/wix/detox/files/1479649/detoxsegfaultverbose.txt)
[detoxtestverbose.txt](https://github.com/wix/detox/files/1479663/detoxtestverbose.txt)

Is there a way to break the suites into chunks and run them in smaller chunks?
I didn't see a way to assign specs with each configuration.

**Comment by rotemmiz** [comment]
These are quite huge logs there, not sure where to start. For starters, which react native version do you use? 
From what I see in the logs:
1. Seems like there's a problem with packaging/bundling resources, there are multiple log lines like this one
```
W/ResourceType: No package identifier when getting name for resource number 0x000001a3
```
2. Detox reloads react native, and then the 
```
11-16 12:47:16.804 13490-13526/com.ibm.mobile.connections.people I/Detox: Reloading React Native
...
11-16 12:47:16.815 13490-13693/com.ibm.mobile.connections.people D/ReactNative: ReactInstanceManager.createReactContext()
...
```
and then, tons of errors in JSCore, leading to a SIGSEGV (are you holding a reference to CatalystInstance in some way?)

**Comment by davek1121** [comment]
react-native version: react-native: 0.48.4

1.  I'm not sure what's causing the  "No package identifier..." log entries.  The app and resources are fine as the tests run in Detox.
2. If we are holding a CatalystInstance, I'm not aware of it.  Is there a way to check how many instances or if we're holding on to one?
Note:  We were able to work around the issue by adding the following before a couple of suites, but this work-around is just masking the real issue:
```
    before(async () => {
        if (device.getPlatform() === 'android'){
            await device.terminateApp();
            await device.launchApp();
        }
    });
```

**Comment by rotemmiz** [comment]
Does the app survive a few R+R (refreshing debug app through the packager)? One of the libraries you use might not clean up after itself when reloading.

**Comment by rotemmiz** [comment]
Is this issue still relevant ?
