### ISSUE TITLE
Web testing for iOS

### ISSUE THREAD

**Issue by alexandravychytill** [wix/Detox#4134]
Hello 
I wanted to ask shortly if there is any timeline for releasing a new supporting version for the web testing in iOS?

**Comment by asafkorem** [comment]
Another RC of v21 will be released soon (expected this week), and it will support web-view testing

**Comment by andresilveirah** [comment]
@asafkorem is the RC release you mentioned out? I can only find [21.0.0-rc3](https://github.com/wix/Detox/releases/tag/21.0.0-rc.3), but that's from May.

**Comment by asafkorem** [comment]
WebView testing support released with v20.19.
FYI @andresilveirah @alexandravychytill
