### ISSUE TITLE
How to get current test/spec name in Detox/Jest

### ISSUE THREAD

**Issue by eilinwis** [wix/Detox#4147]
### Description

Hello guys! I need some help.
I starting my tests with 

`detox test e2e/tests/learn.spec.js -c ios.sim.debug`

here are logs from the console:
```
18:22:06.431 detox[53554] B jest --config e2e/jest.config.js e2e/tests/learn.spec.js
Determining test suites to run...18:22:06.994 detox[53556] i qase: Current PID: 53556
18:22:06.998 detox[53556] i qase: QASE_REPORT env variable is not set. Reporting to qase.io is disabled.
18:22:11.674 detox[53556] i learn.spec.js is assigned to 20AAB2E7-92ED-4311-1111 (iPhone 14)
```

So is there any way that i can get the current test suite name and put it into a variable?
I guess there is cause detox somehow gets the name to put it in the logs

Unfortunately Jest 29.4 does not have the expect.getState().currentTestName method anymore.

### Your environment

Detox version: 20.4
React Native version: 0.71.6
Node version: 16.0.0
Device model: ios simulator 
OS: ios 16.2
Test-runner (select one): jest 29.4.1

**Comment by noomorph** [comment]
You can do that via a custom test environment if you want. 
Read this: https://jestjs.io/docs/next/configuration/#testenvironment-string

```js
// e2e/testEnvironment.js
const { DetoxCircusEnvironment } = require('detox/runners/jest');

class CustomDetoxEnvironment extends DetoxCircusEnvironment {
  async handleTestEvent(event, state) {
    if (event.name === 'test_start') {
      this.global.currentTest = event.test.name; // not sure test.name works, but it should be similar this
    }

    return super.handleTestEvent(event, state);
  }
}

module.exports = CustomDetoxEnvironment;
```

Inside your test file, you'll be able to access `globalThis.currentTest` accordingly.

**Comment by eilinwis** [comment]
Thanks for the suggestion! Didn't work for me for some reason
But i Did it that way and it worked!

`const { DetoxCircusEnvironment } = require('detox/runners/jest')

class CustomDetoxEnvironment extends DetoxCircusEnvironment {
  constructor(config, context) {
    super(config, context)
    this.global.currentTestPath = context.testPath
  }
}

module.exports = CustomDetoxEnvironment`

and then: 
const currentTestFile = globalThis.currentTestPath
