### ISSUE TITLE
Missing `setStatusBar` TypeScript declaration

### ISSUE THREAD

**Issue by kirillzyusko** [wix/Detox#4191]
### What happened?

Using code below:

```ts
await device.setStatusBar({
      time: '12:00',
      dataNetwork: 'wifi',
      wifiMode: 'active',
      wifiBars: '3',
      cellularMode: 'active',
      cellularBars: '4',
      batteryLevel: '100',
    });
```

I'm getting:

<img width="950" alt="image" src="https://github.com/wix/Detox/assets/22820318/415fff19-5c00-42d9-ac1d-3cb5610fc755">

### What was the expected behaviour?

TS shouldn't comply about missing method.

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Help us reproduce this issue!

Just use the code snippet above in TypeScript file.

### In what environment did this happen?

Detox version: 20.12.0
React Native version: 0.72.4
Has Fabric (React Native's new rendering system) enabled: no
Node version: 16.16.0
Test-runner (select one): jest

### Detox logs

I can't paste logs, because I don't run Detox :)

### Device logs

I can't paste logs, because I don't run app :)

**Comment by kirillzyusko** [comment]
Closed by https://github.com/wix/Detox/pull/4192

**Comment by noomorph** [comment]
I'll release tomorrow
