### ISSUE TITLE
Open app via URL - Error Due to Unescaped "&" in Command Param

### ISSUE THREAD

**Issue by sanduluca** [wix/Detox#4196]
### What happened?

When attempting to run the app via a deeplink (url) using the provided command, an error is encountered due to the presence of an unescaped "&" character within the detoxURLOverride parameter. This issue prevents the app from launching successfully when using this particular command.

```ts
await device.launchApp({
  newInstance: true,
  url: "https://exmaple.com/?param1=test&success=true",
  // url: "exmaple://?param1=test&success=true",
});
```
This code generate the following command:

```bash
adb -s 12171JEC205555 shell am instrument -w -r -e detoxServer ws://localhost:51206 -e detoxSessionId ff0da839-5392-559f-0764-c7d477345e2c -e detoxURLOverride https://exmaple.com/?param1=test&success=true -e debug false com.example.test/androidx.test.runner.AndroidJUnitRunner
```

### What was the expected behaviour?
The app should launch successfully without any errors when the command is executed.

### Actual Behavior:
An error occurs, likely due to the unescaped "&" character within the detoxURLOverride parameter value.

### Proposed Solution:
The issue appears to be related to the unescaped "&" character in the detoxURLOverride parameter. To resolve this, the value for `detoxURLOverride` should be quoted .
https://github.com/wix/Detox/blob/b489519a3166723194c83c5a43bd585bee1d9395/detox/src/devices/runtime/RuntimeDevice.js#L134

Example: 
```bash
adb -s 12171JEC205555 shell am instrument -w -r -e detoxServer ws://localhost:51206 -e detoxSessionId ff0da839-5392-559f-0764-c7d477345e2c -e detoxURLOverride "https://exmaple.com/?param1=test&success=true" -e debug false com.example.test/androidx.test.runner.AndroidJUnitRunner
```

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### In what environment did this happen?

Detox version: 20.11.2
React Native version: 0.72
Has Fabric (React Native's new rendering system) enabled: no
Node version: 20
Test-runner (select one): jest

### Detox logs

<details><summary>Detox logs</summary>

```bash
10:28:40.857 detox[59499] i child-process:SPAWN_CMD /Users/user/Library/Android/sdk/platform-tools/adb -s 12171JEC205581 shell am instrument -w -r -e detoxServer ws://localhost:51206 -e detoxSessionId ff0da838-5392-559f-0764-c7d477345e2c -e detoxURLOverride https://exmaple.com/?param1=test&success=true -e debug false com.example.test/androidx.test.runner.AndroidJUnitRunner
10:28:40.904 detox[59499] i child-process:SPAWN_STDERR /system/bin/sh: -e: inaccessible or not found

10:28:41.118 detox[59499] i child-process:SPAWN_STDERR 
Error: Argument expected after "https://exmaple.com/?param1=test"
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by noomorph** [comment]
Makes sense. Thanks for the report.

**Comment by noomorph** [comment]
I'll take it into the next sprint (next week).
