### ISSUE TITLE
Match by selector

### ISSUE THREAD

**Issue by doronpr** [wix/detox#42]
Support CSS-like syntax.
For example: `element(by.selector("#parentId @UIImage"))`
Will get the first element of type `UIImage` which is a descendent of an element with `testID` `parentId`

**Comment by talkol** [comment]
Let's move this to version 2, in the meantime I added matchers `withAncestor` and `withDescendant` here 639f335c669894c12f731acb1fe1ee15556a29f2

**Comment by LeoNatan** [comment]
Out of scope for the project.
