### ISSUE TITLE
Detox not working with iOS 9.3

### ISSUE THREAD

**Issue by anton6** [wix/detox#420]
#### Description
I have a simple detox test, which is: `await element(by.id('welcome'));`

I am trying to run this for a React-native app.

When I run detox with any simulator running on **iOS 9.3** I get a timeout error. But when I run the test under same conditions with **iOS 11.1** it works fine.

When I run `detox test` it manages to find and open the simulator; uninstall and install of the app steps are also fine.

When it opens the app however nothing happens, then a timeout error is thrown. I can interact with the app manually without problems once detox installs it and manages to open it (i.e. clicking on button etc).

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 5.10.0
* Node: v8.1.2
* Device: iPhone 5, iOS 9.3
* Xcode: 9.1
* macOS: High Sierra 10.13

#### Device and verbose Detox logs
```
1) "before all" hook

0 passing (2m)
1 failing

1) "before all" hook:
     Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

**Comment by LeoNatan** [comment]
Please enable synchronization test feature and post the log. Thanks

**Comment by anton6** [comment]
@LeoNatan I added the following code `await device.enableSynchronization();` as you suggested.

After running the test two log files are created: **detox.last_launch_app_log.err** and **detox.last_launch_app_log.out** inside the `$HOME/Library/Developer/CoreSimulator/Devices/932B2100-BAD3-488B-A6B1-B58D9FA5414C/data/tmp/` directory.

Inside **detox.last_launch_app_log.err** I am getting the following error:

```
dyld: warning: could not load inserted library '/Users/anton/Library/Detox/ios/dcbded2050005ff99b0bffc826182a2fb35fa7a4/Detox.framework/Detox' because no suitable image found.

Did find:
	/Users/anton/Library/Detox/ios/dcbded2050005ff99b0bffc826182a2fb35fa7a4/Detox.framework/Detox: no matching architecture in universal wrapper

```

But **detox.last_launch_app_log.out** is empty.

After sometime Detox prints out `Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.` in the console.

This time I was running the example app (/detox/examples/demo-react-native). If I run the app for example using "iPhone 5s, iOS 11.1" everything works as expected. As soon as I switch to "iPhone 5, iOS 9.3" I get no suitable image found error above.

Any ideas what this might be? Does detox 5.10.0 support iOS 9.3?

Thanks

**Comment by LeoNatan** [comment]
I meant this:
https://github.com/wix/detox/blob/master/docs/Troubleshooting.Synchronization.md#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much

I cannot say if Detox supports iOS 9.3. As far as I know, we didn’t break it, but I have not ran an iOS 9.x simulator in two years. Please note that we plan to officially drop iOS 9.x support very soon. Depending on your research here—if the issue is something small—I may provide a small fix. If the issue is a major one, we will call it quits and drop support for iOS 9.x earlier than expected. iOS 9.x is not a target we are interested in particularly.

**Comment by anton6** [comment]
Thanks for clarifying. I tried running with `detox test --debug-synchronization [value in ms]`, but the result was the same. Same behaviour, same Error messages.

After some further testing I think the problem was not in the iOS version as I initially said, but the simulators. When I try running for "iPhone 4s" and "iPhone 5" on iOS 9.3 it fails with above issues, but if I try and run the tests using "iPhone 5s" and above on iOS 9.3, tests work fine. The minimum device we support is "iPhone 5, iOS 9.3", that's why I was trying to use this specific simulator.

I suspect there is no point of looking into why it's not working with "iPhone 4s" and "iPhone 5" on iOS 9.3, so I'm going to close the issue.

Thanks for helping out.

**Comment by LeoNatan** [comment]
Ahh good. Detox is 64bit only, so those simulators are not supported.

**Comment by didjo972** [comment]
I'm sorry but i'm using the iPhone 7 Plus device and it doesn't work too. @anton6 can you test with others devices please ?

**Comment by anton6** [comment]
@didjo972 I'll try tonight

**Comment by anton6** [comment]
@didjo972, hi, sorry for late reply. So I tried it and it worked for me.

I'm running Detox: 6.0.4 with Node: 8.1.2. ( iPhone 7 Plus, iOS 11.2, Xcode 9.2, macOS: High Sierra 10.13).

I'm also using Jest instead of Mocha as test runner, not sure if that makes a difference.
