### ISSUE TITLE
Failed to find a device config "iPhone 14"

### ISSUE THREAD

**Issue by vksgautam1986** [wix/Detox#4200]
### What happened?

Hi , i am just trying to run my fist detox tests in the application. so i have done setup for ios only. but it is giving error.
command-- detox build --configuration ios.sim.debug

it is now allowing me to do anything. im using RN 0.71 with latest detox version. 

### What was the expected behaviour?

it should be running the test .

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

RN-0.71.8

### In what environment did this happen?

Detox version: 
React Native version: 0.71.8
Has Fabric (React Native's new rendering system) enabled: (yes/no) 
Node version:  16.14
Device model: 
iOS version: 
macOS version: 
Xcode version: 14.1
Test-runner (select one): jest / other

### Detox logs

<details><summary>Detox logs</summary>

```

Failed to find a device config "iPhone 14" in the "devices" dictionary of Detox config at path:
/Users/netsmartz/Desktop/Vivek/Ecommerce/.detoxrc.js

HINT: Below are the device configurations Detox was able to find:
* simulator
* attached
* emulator

Check your configuration "ios.sim.debug":

{
  device: 'iPhone 14',
  app: 'ios.debug'
}`

detox`/** @type {Detox.DetoxConfig} */
module.exports = {
  testRunner: {
    args: {
      $0: 'jest',
      config: 'e2e/jest.config.js',
    },
    jest: {
      setupTimeout: 120000,
    },
  },
  apps: {
    'ios.debug': {
      type: 'ios.app',
      binaryPath:
        'ios/build/Build/Products/Debug-iphonesimulator/Ecommerce.app',
      build:
        'xcodebuild -workspace ios/Ecommerce.xcworkspace -scheme Ecommerce -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build',
    },
    'ios.release': {
      type: 'ios.app',
      binaryPath:
        'ios/build/Build/Products/Release-iphonesimulator/Ecommerce.app',
      build:
        'xcodebuild -workspace ios/Ecommerce.xcworkspace -scheme Ecommerce -configuration Release -sdk iphonesimulator -derivedDataPath ios/build',
    },
    'android.debug': {
      type: 'android.apk',
      binaryPath: 'android/app/build/outputs/apk/debug/app-debug.apk',
      build:
        'cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug',
      reversePorts: [8081],
    },
    'android.release': {
      type: 'android.apk',
      binaryPath: 'android/app/build/outputs/apk/release/app-release.apk',
      build:
        'cd android && ./gradlew assembleRelease assembleAndroidTest -DtestBuildType=release',
    },
  },
  devices: {
    simulator: {
      type: 'ios.simulator',
      device: {
        type: 'iPhone 14',
      },
    },
    attached: {
      type: 'android.attached',
      device: {
        adbName: '.*',
      },
    },
    emulator: {
      type: 'android.emulator',
      device: {
        avdName: 'Pixel_3a_API_30_x86',
      },
    },
  },
  configurations: {
    'ios.sim.debug': {
      device: 'iPhone 14',
      app: 'ios.debug',
    },
    'ios.sim.release': {
      device: 'iPhone 14',
      app: 'ios.release',
    },
    'android.att.debug': {
      device: 'attached',
      app: 'android.debug',
    },
    'android.att.release': {
      device: 'attached',
      app: 'android.release',
    },
    'android.emu.debug': {
      device: 'emulator',
      app: 'android.debug',
    },
    'android.emu.release': {
      device: 'emulator',
      app: 'android.release',
    },
  },
};
```

</details>

### More data, please!

/** @type {Detox.DetoxConfig} */
module.exports = {
  testRunner: {
    args: {
      $0: 'jest',
      config: 'e2e/jest.config.js',
    },
    jest: {
      setupTimeout: 120000,
    },
  },
  apps: {
    'ios.debug': {
      type: 'ios.app',
      binaryPath:
        'ios/build/Build/Products/Debug-iphonesimulator/Ecommerce.app',
      build:
        'xcodebuild -workspace ios/Ecommerce.xcworkspace -scheme Ecommerce -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build',
    },
    'ios.release': {
      type: 'ios.app',
      binaryPath:
        'ios/build/Build/Products/Release-iphonesimulator/Ecommerce.app',
      build:
        'xcodebuild -workspace ios/Ecommerce.xcworkspace -scheme Ecommerce -configuration Release -sdk iphonesimulator -derivedDataPath ios/build',
    },
    'android.debug': {
      type: 'android.apk',
      binaryPath: 'android/app/build/outputs/apk/debug/app-debug.apk',
      build:
        'cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug',
      reversePorts: [8081],
    },
    'android.release': {
      type: 'android.apk',
      binaryPath: 'android/app/build/outputs/apk/release/app-release.apk',
      build:
        'cd android && ./gradlew assembleRelease assembleAndroidTest -DtestBuildType=release',
    },
  },
  devices: {
    simulator: {
      type: 'ios.simulator',
      device: {
        type: 'iPhone 14',
      },
    },
    attached: {
      type: 'android.attached',
      device: {
        adbName: '.*',
      },
    },
    emulator: {
      type: 'android.emulator',
      device: {
        avdName: 'Pixel_3a_API_30_x86',
      },
    },
  },
  configurations: {
    'ios.sim.debug': {
      device: 'iPhone 14',
      app: 'ios.debug',
    },
    'ios.sim.release': {
      device: 'iPhone 14',
      app: 'ios.release',
    },
    'android.att.debug': {
      device: 'attached',
      app: 'android.debug',
    },
    'android.att.release': {
      device: 'attached',
      app: 'android.release',
    },
    'android.emu.debug': {
      device: 'emulator',
      app: 'android.debug',
    },
    'android.emu.release': {
      device: 'emulator',
      app: 'android.release',
    },
  },
};

**Comment by cunderw** [comment]
`configurations: {
  'ios.sim.debug': {
    device: 'iPhone 14',
    app: 'ios.debug',
},`

Should be

`configurations: {
  'ios.sim.debug': {
    device: 'simulator',
    app: 'ios.debug',
},`

**Comment by vksgautam1986** [comment]
thanks it's working fine now.
