### ISSUE TITLE
[Docs] jestExpect - usage isn't clear

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#4237]
### Describe your idea

In some [places in the docs/code](https://github.com/search?q=repo%3Awix%2FDetox%20jestExpect&type=code), usage of `jestExpect` is solicited for making the more primitive type of assertions. However, the actual means of usage isn't well enough explained, with the most prominent case being the [docs](https://wix.github.io/Detox/docs/api/actions/#getattributes) and [typescript types](https://github.com/wix/Detox/blob/aef7ce9f4545252a4de13cc994b91b50bc910fea/detox/index.d.ts#L1483) of `getAttributes()` --

It is either unclear where to `require()` Jest's expect from, or that the suggested require path is wrong. We've found this could be confusing for devs trying to use `getAttributes()`, specifically. Also, link from types to API on doc-site is broken.

**Comment by noomorph** [comment]
Is this enough? https://github.com/wix/Detox/commit/e1acd36589edb341abc492ae4983ef9ff1235023
Or you want something more?

**Comment by d4vidi** [comment]
Thanks @noomorph!
This is good but also the documentation of it seems lacking. Best to just look it up everywhere and see - https://github.com/search?q=repo%3Awix%2FDetox%20jestExpect&type=code

**Comment by noomorph** [comment]
It's enough docs. Every snippet explains from where we import `jestExpect` so we're covered for now.
