### ISSUE TITLE
Android API 33 (v13) / API 34 (v14) tap fail

### ISSUE THREAD

**Issue by aaronpliu** [wix/Detox#4257]
### What happened?

Since #3762 had been fixed on Detox v20.13.1. I tested it and found some of different behavior in Android.

1. It's OK to tap on API 32 (v12)
2. It was tap+hold behavior on API 33 (v13) (longPress(100) is OK to tap)
3. It ran into error on API 34 (v14) (see error below)

### What was the expected behaviour?

The actions are good in different Android version

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: v20.13.1
React Native version: 0.71.4
Has Fabric (React Native's new rendering system) enabled: (yes/no) yes
Node version: v16.20
Device model: Android Simulator
Android version: v12  /v13 / v14
Test-runner (select one): other

### Detox logs

<details><summary>Detox logs</summary>

```
Error: Exception caught in tap: DetoxRuntimeError: Test Failed: Could't click at 917.0,2313.5 precision 16.0, 16.0 . Tapper: com.wix.detox.espresso.action.DetoxSingleTap@a50819a coordinate provider: VISIBLE_CENTER precision describer: FINGER. Tried 3 times. With Rollback? false
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste your device.log here!
```

</details>

**Comment by noomorph** [comment]
😭

**Comment by noomorph** [comment]
@ericschaal do you see anything like this on API 34?

**Comment by asafkorem** [comment]
I'm investigating this now, will update

**Comment by aaronpliu** [comment]
How's it going? @asafkorem , I saw someone reported same issue on latest Android API. Thanks for your checking

**Comment by aaronpliu** [comment]
@ericschaal would you please take a look it either?

**Comment by ericschaal** [comment]
Hey @aaronpliu! Do you have a reproduction project I could use to investigate?

All our pipelines are on android 33 and 34 and I didn't notice any issue! 

Thank you :)

**Comment by aaronpliu** [comment]
Thanks for your checking. perhaps cannot be shared since it was private project.
May I know if you checking on Android 13 / 14 image with API 33 / 34?
It was indeed appeared in API 33 / 34 and tried to check other App, same issue. There is no any extra actions to add , just using simplest tap action with Detox native method. It's working on API 32 with same test case.
I will try different version to get more information and maybe would offer details if possible. Thanks

**Comment by mhsfh** [comment]
i'm facing same issue

```
Test Failed: Couldn't click at: 100.0,232.0 precision: 16.0, 16.0 . Tapper: com.wix.detox.espresso.action.DetoxSingleTap@ef87b7e coordinate provider: com.wix.detox.espresso.DetoxAction$1@4a7a671 precision describer: FINGER. Tried 3 times. With Rollback? false
```

I'm using Android API 34 and the same is happening with Android API 33

**Comment by gosha212** [comment]
Hi @mhsfh, can you please share a link to example project with the specific problem? We need some help to reproduce it.

**Comment by aaronpliu** [comment]
any update for Android tap / swipe / scroll in API 33 / 34?

**Comment by gosha212** [comment]
@aaronpliu hi.
The tap works fine. #3762 fixed the issue. I've failed to reproduce any other issue with tap. You are welcome to send us a project with a sample code that reproduces the issue.
Regarding the problem with swipe on API 33/34 looks like it related to gesture navigation feature that is selected by default on 33 / 34 emulators (Looks like the issue will reproduce on older versions too). The current workaround is to set 3-button navigation in Navigation Mode settings on your emulator. This workaround should fix at least some of the problems. We are working on full solution for this issue.

**Comment by aaronpliu** [comment]
Hi @gosha212, thanks for your replying. 
I don't think #3762 fixed all in API 33 / 34 for tap action. @mhsfh or #4262 reported the same issue for tap action with same error info. I'm just using a normal RN app to check, no more specific behavior to simulate. Not sure why your scripts or example would be passed. Btw, my developing app compiled with Android SDK 34, those test scripts / cases would be run under API 32 smoothly.
Whatever, will further checking error and validate. Thank you

**Comment by gosha212** [comment]
@aaronpliu  @mhsfh 
[Here](https://github.com/gosha212/react-native-72-4-detox-example) is an example project that works with API 34.
Can you make a small side project that reproduces your problem?

**Comment by gosha212** [comment]
Another issue with swipe issue #4298

**Comment by jyotsna-hh** [comment]
Due to complications with the tap() and typeText() functions for API 33 and 34, I've opted for a workaround. I've substituted longPress() in place of tap() and replaceText() instead of typeText(). Even I'm on the latest detox version 20.14.3.

**Comment by gosha212** [comment]
@jyotsna-hh [here](https://github.com/wix/Detox/issues/4257#issuecomment-1859170671) is a short workaround for swipe issues.
The tap should work as expected on 33/34. Our [tests](https://github.com/wix/Detox/blob/master/detox/test/e2e/03.actions.test.js) are green on 33/34. Can you check that it also works for you? [Here](https://github.com/gosha212/react-native-72-4-detox-example) is a small side project with tap that works as expected.

**Comment by aaronpliu** [comment]
Thanks @gosha212. It seems working on API 33/34 after I upgraded to latest version (v20.14.5). Also re-build androidTest/ as you mentioned #4262 to follow configurations. I tested my scripts on API 33 / 34, they are OK to tap now. Thanks so much.
@mhsfh @jyotsna-hh @andreasalt41. you may double check your configuration refer to [here  ](https://wix.github.io/Detox/docs/introduction/project-setup/) and upgrade Detox to build apk and androidTest/.

For other issues, I saw have tickets to track. Let us follow them to get update. 
Will close this ticket later if no more discussion. Thanks a lot

**Comment by d4vidi** [comment]
Thanks for reporting back, @aaronpliu!
As per APK path configuration - PR #4311, which is meant for explaining things better, is still open . Until it is merged, consider referring to the associated discussion: #4307

**Comment by aaronpliu** [comment]
tap / swipe actions are good in Detox (v20.14.5). for scrollTo issue, see #4312 or temp workaround [here](https://github.com/wix/Detox/issues/4257#issuecomment-1859170671)
Much appreciate everyone's supporting and hard work
