### ISSUE TITLE
Test Failed: Couldn't click at:  Tapper: com.wix.detox.espresso.action.DetoxSingleTap@14b9e36 coordinate provider

### ISSUE THREAD

**Issue by andreasalt41** [wix/Detox#4262]
### What happened?

Got "Test Failed: Couldn't click at: 720.0,2811.0 precision: 16.0, 16.0 . Tapper: com.wix.detox.espresso.action.DetoxSingleTap@14b9e36 coordinate provider: VISIBLE_CENTER precision describer: FINGER. Tried 3 times. With Rollback? false" .
**[detox test  -l verbose  --debug-synchronization 2000      --configuration  android.emu.devel_release  -l trace --record-logs all]**
Here is test file:
`describe('Login', () => {
  beforeAll(async () => {
    await device.launchApp();
  });
  it('should be able to login', async () => {
    await expect(element(by.text('START'))).toBeVisible();
    await element(by.text('START')).tap();
  });
  it('should be able to login b', async () => {
    await expect(element(by.text('START'))).toBeVisible();
    await element(by.text('START')).tap();
  });
  it('should be able to login2', async () => {
    await expect(element(by.text('I already have an account'))).toBeVisible();
    await element(by.text('I already have an account')).tap();
  });
});
[detox.log](https://github.com/wix/Detox/files/13218517/detox.log)

### What was the expected behaviour?

Element PushButton is visible but it is not possible to tap it.

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 20.13.0
React Native version: 0.72.4
Has Fabric (React Native's new rendering system) enabled: (yes/no) 
Node version: v20.8.1
Device model: Pixel_6_Pro_API_34
Android version: 
Test-runner (select one): jest / other

### Detox logs

<details><summary>Detox logs</summary>

</details>
[detox.log](https://github.com/wix/Detox/files/13218762/detox.log)

### Device logs

<details><summary>Device logs</summary>

</details>
[device.log](https://github.com/wix/Detox/files/13218738/device.log)

**Comment by aaronpliu** [comment]
@andreasalt41 did you have more details provide? seems community maintainer would not repro the issue since lack of some key info. I also hv the same error as you reported.

**Comment by gosha212** [comment]
@andreasalt41 @aaronpliu Can you check please that you have the following line in your `app/build.gradle` file:
`proguardFile "${rootProject.projectDir}/../node_modules/detox/android/detox/proguard-rules-app.pro` as specified in our docs  [https://wix.github.io/Detox/docs/introduction/project-setup/#41-patching-build-scripts](docs).
Please verify that if it reproduces in debug.

**Comment by erksch** [comment]
This happened after upgrading our GenyMotion launch template from genymotion-android-12 to genymotion-android-14.
We solved this by updating from Detox 20.1.2 to 20.22.2.
