### ISSUE TITLE
Detox cannot interact with system dialogs

### ISSUE THREAD

**Issue by urbanclap-admin** [wix/Detox#4275]
### What happened?

We have a google phone number hint dialog that automatically invokes when tapping on the login field, and we cannot dismiss the dialog via detox as it cannot find the view.

This causes the text to fail unless we manually dismiss the dialog.

Is there any workaround for this?

### What was the expected behaviour?

The google phone number dialog should dismiss when tapped on the dismiss button

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 20.13.5
React Native version: 0.67
Has Fabric (React Native's new rendering system) enabled: No
Node version: v21
Device model: Any android device
Android version: any android version
Test-runner (select one): jest 

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste your device.log here!
```

</details>

**Comment by urbanclap-admin** [comment]
@noomorph any workaround for this?

**Comment by aaronpliu** [comment]
not supported! it's mentioned on v21 RC3.  Would see #3208 Next Phrase

**Comment by aaronpliu** [comment]
you would find simulator I/O - keyboard to chose "Connect Hardware Keyboard" or not. If you want to use soft keyboard or just wanna input by text, you are able to setup I/O on simulator.
For really system dialog interaction, it was not supported in current Detox release version. I just saw it in Detox v21 RC3 (with XCUITest). 
For iOS real device, hopefully Detox can support it a.s.a.p

**Comment by asafkorem** [comment]
Support released with [Detox v20.22](https://github.com/wix/Detox/releases/tag/20.22.0) (System API)
