### ISSUE TITLE
How to disable "The stdout and stderr logs"

### ISSUE THREAD

**Issue by linhnh123** [wix/detox#429]
This log file is created by default. I don't want to do that. How to disable this log file during running test. Please help.

**Comment by LeoNatan** [comment]
Any particular reason these logs are bothering you?

**Comment by linhnh123** [comment]
When i'm running test, sometime it delay (about 10 seconds) and then continue running. I don't want to create that log file, unless i'm getting any error that I want to know.

**Comment by rotemmiz** [comment]
I'm pretty sure it's the time the script waits for the app to install and launch, nothing to do with logs.

Try running test with --loglevel verbose to see exactly what happens while the script is halting.

**Comment by LeoNatan** [comment]
Any news? Please provided the logs requested.
