### ISSUE TITLE
React Native 0.34+ not supported - testee not connected, cannot fw action

### ISSUE THREAD

**Issue by mikelsons** [wix/detox#43]
I'm still having this this issue #20  with detox 3.2.0. ( Also tried on 3.1.0 )

``` json
06:12:37: server listening on localhost:8099...
06:12:41: role=tester login (sessionId=mytestapp)
06:12:47: role=tester action=isReady (sessionId=mytestapp)
06:12:47: role=testee not connected, cannot fw action (sessionId=mytestapp)
06:12:47: role=testee login (sessionId=mytestapp)
06:12:47: role=testee action=ready (sessionId=mytestapp)
06:12:47: role=tester action=reactNativeReload (sessionId=mytestapp)
06:13:07: role=tester action=cleanup (sessionId=mytestapp)
06:13:07: role=testee action=cleanupDone (sessionId=mytestapp)
06:13:07: role=tester disconnect (sessionId=mytestapp)
```

Simulators starts app but test isn't executed. I tried on iphone 6s, 6, 5s simulator as well and it was the same.

**Comment by talkol** [comment]
I assume it's related internally to #44 (the entire Apple ecosystem updated and we're still stuck on the previous versions). Can you confirm your setup? (Xcode ver, MacOS ver)

**Comment by mikelsons** [comment]
El Capitan ( 10.11.6 ) and XCode 7.3.1

**Comment by talkol** [comment]
On a second look, your server log looks good. this is what supposed to happen. The tester connected to the server first and is waiting for the testee. Then the testee connects and says he's ready. Then the tester asks him to reload their RN app and the testee doesn't respond.

What version of React Native are you using?

**Comment by mikelsons** [comment]
I was testing on React Native 0.34.1. Seem to work on 0.27.2, 0.28.0  0.32.1, 0.33.1 but not on 0.34.1 and 0.35.0. So the most current supported version is 0.33.1 ?

**Comment by talkol** [comment]
Wow, awesome work!
We'll get to it eventually as we're working to update all other dependencies to latest.
Since we rely on private React Native API on the native side, every RN update might break stuff.
You are welcome to help out, if you're able to locate the issue and PR.
I would also like to maintain compatibility to the older version though.
Thanks.

**Comment by LeoNatan** [comment]
Now supported.
