### ISSUE TITLE
Publish new npm version

### ISSUE THREAD

**Issue by brunolemos** [wix/detox#431]
There are some fixes that were recently merged that would be great to be available on npm. I'm currently using a local fork and using `yarn link` but that wouldn't work on travis and other users.

**Comment by rotemmiz** [comment]
We are gathering a few breaking changes together and releasing a major version soon. We don't want to release two major versions one after the other, that's the reason the release is being postponed

**Comment by brunolemos** [comment]
@rotemmiz ok. maybe the non breaking ones as patch? E.g. https://github.com/wix/detox/commit/418ddaca9cb0862cac9b9bb67a179d6925d70fa4

**Comment by LeoNatan** [comment]
We will release a new version soon.

**Comment by philss** [comment]
Hi, @LeoNatan and @rotemmiz. Thanks for the latest release! 😃 

Unfortunately seems that `npm install detox` is breaking because the `detox-server` version `6.0.0` was not released. Could you please take a look? Thanks!
