### ISSUE TITLE
scrollTo is not working as expected behavior on Android API 33 / 34

### ISSUE THREAD

**Issue by aaronpliu** [wix/Detox#4312]
### What happened?

behavior:
1. It's OK to scrollTo on API 32
2. It let the program go into the background on API 33 / 34 (w/o error)

### What was the expected behaviour?

As its definition to work (the edge to scrollTo "left"/"right"/"top"/"bottom")

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

 **Scenario**: there is a long terms to read and needs to scrollTo bottom and then tap continue button
**Action**: element.scrollTo(by.type('andorid.webkit.WebView'). 'bottom')

### In what environment did this happen?

Detox version: v20.14.5
React Native version: 0.71.4
Has Fabric (React Native's new rendering system) enabled: (yes/no) yes
Node version: v16.19.1
Device model: Android
Android version:  13 / 14
Test-runner (select one): jest / other

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste your device.log here!
```

</details>

**Comment by gosha212** [comment]
Hi @aaronpliu,
I'm working on this issue. [Here](https://github.com/wix/Detox/issues/4257#issuecomment-1859170671) is a temp workaround
