### ISSUE TITLE
detox.config.cjs

### ISSUE THREAD

**Issue by karlhorky** [wix/Detox#4374]
### Describe your idea

For an ESM project (`"type": "module"` in `package.json`), it would be great to be able to support `detox.config.cjs`

**Prior art:**

Metro also supports this `.cjs` alternative file extension, with `metro.config.cjs`:

- https://github.com/facebook/metro/commit/692293339e3b9f542f7b83c04bdccf46fef05766

**Comment by noomorph** [comment]
@karlhorky we have already implemented this in one of the recent releases (20.17.1, IIRC).

**Comment by karlhorky** [comment]
Oh, indeed in [`detox@20.17.1`](https://github.com/wix/Detox/releases/tag/20.17.1) via https://github.com/wix/Detox/pull/4358, nice!

Thanks, closing :)
