### ISSUE TITLE
Genycloud: Getting numerous "ADB tunnel communication failure" errors

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#4382]
### What happened?

Getting the following error from Genymotion sporadically on our internal CI environment:
```json
{
  "error": {
    "message": "ADB tunnel communication failure.",
    "details": "Failed to connect instance 99ae8967-ce6c-4c92-b6cb-e125eb570c76 to adbtunnel"
  },
  "exit_code": 12,
  "exit_code_desc": "ADBTUNNEL_GENERIC_ERROR"
}
```

@lilinor @igorgn 

Potential fix: Monitor all adb commands and try to reconnect when this specific error is thrown.

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 
React Native version: 
Has Fabric (React Native's new rendering system) enabled: (yes/no) 
Node version: 
Device model: 
Android version: 
Test-runner (select one): jest / other

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste your device.log here!
```

</details>

**Comment by d4vidi** [comment]
Actually I see now that the instance creation command hung for a long time (≥8min). That's the real issue, at least in one instance of the problem that I've seen:
```
10:20:22.138 detox[50078] i Allocating Genymotion Cloud instance Detox.29bf3bef-f1ad-f890-6196-949030ad6919.0 for testing. To access it via a browser, go to: https://cloud.geny.io/instance/a6c8a729-53c9-472a-8408-5830c30519f4

10:28:47.993 detox[50078] i ""/usr/local/pip3_libs/bin/gmsaas" --format compactjson instances adbconnect a6c8a729-53c9-472a-8408-5830c30519f4" failed with error = ChildProcessError: Command failed: "/usr/local/pip3_libs/bin/gmsaas" --format compactjson instances adbconnect a6c8a729-53c9-472a-8408-5830c30519f4
--
  | {"error": {"message": "ADB tunnel communication failure.", "details": "Failed to connect instance a6c8a729-53c9-472a-8408-5830c30519f4 to adbtunnel"}, "exit_code": 12, "exit_code_desc": "ADBTUNNEL_GENERIC_ERROR"}
  | `"/usr/local/pip3_libs/bin/gmsaas" --format compactjson instances adbconnect a6c8a729-53c9-472a-8408-5830c30519f4` (exited with error code 12) (code=12), stdout and stderr:
```

@lilinor Could you try to look into that, provided the specific instance uuid?

**Comment by lilinor** [comment]
Sorry @d4vidi for missing this ! 
I managed to find the udid of the instance but there are some logs that I couldn't get because those were already recycled as it happened more than 2 months ago.
I saw from the logs that you were using gmsaas 1.6 version at that time. Could you also upgrade to the latest version and see if you still encounter.
If you encounter the issue again, please share the instance udid and gmsaas logs if you can get them. We'll investigate.

**Comment by d4vidi** [comment]
We haven't been seeing this type of issues lately (probably since we moved to AWS - not validated). Closing for now.
