### ISSUE TITLE
`launchApp` with `delete: true` is keep `SecureStore` data between tests

### ISSUE THREAD

**Issue by grillorafael** [wix/Detox#4386]
### Description

I want to, on every spec test, get a brand new and fresh with no previous data tests app instance up.

I thought that by forcing a reinstall I would end up with that behaviour but instead internal app data stored by `SecureStore` is persisting across reinstall.

### Your environment

Detox version: 20.18.3
React Native version: 0.73.4
Node version: 18
Device model: iphone 15 simulator
OS: 17.2
Test-runner (select one): jest

**Comment by noomorph** [comment]
Hi, do you have multiple apps from the same vendor installed on a simulator?

cc @asafkorem please join the conversation 🙏 i am not tech savvy with iOS guts

**Comment by asafkorem** [comment]
As far as I understand `SecureStore` uses Keychain storage on iOS. This persistence is due to the way iOS handles data stored in the Keychain.. Keychain data is stored separately from the app's data therefore reinstallation won't clean it

**Comment by grillorafael** [comment]
Is there a way to clean up the keychain?

**Comment by noomorph** [comment]
@grillorafael could you try [`device.resetContentAndSettings()`](https://wix.github.io/Detox/docs/api/device#deviceresetcontentandsettings-ios-only). I know it is very slow but at least we should know if this fixes your problem.

**Comment by grillorafael** [comment]
I’ll give it a go and report back!

**Comment by adamivancza** [comment]
@grillorafael I use this piece of code in our AppDelegate.mm for this exact purpose:

```
  NSMutableDictionary *envs = [NSMutableDictionary dictionaryWithDictionary:[[NSProcessInfo processInfo] environment]];
  NSString* isTestingValue = [[RNCConfig envFor:@"APP_ENV"] isEqual:@"test"] ? @"TRUE" : @"FALSE";
  [envs setObject:isTestingValue forKey:@"IS_TESTING"];
  [[NSProcessInfo processInfo] setValue:[envs copy] forKey:@"environment"];

  // clear secure storage when app is reinstalled AND running tests
  if (isTestingValue && ![[NSUserDefaults standardUserDefaults] objectForKey:@"FirstRun"]) {
    NSArray *secItemClasses = @[(__bridge id)kSecClassGenericPassword,
                                (__bridge id)kSecClassInternetPassword,
                                (__bridge id)kSecClassCertificate,
                                (__bridge id)kSecClassKey,
                                (__bridge id)kSecClassIdentity];
    for (id secItemClass in secItemClasses) {
      NSDictionary *spec = @{(__bridge id)kSecClass: secItemClass};
      SecItemDelete((__bridge CFDictionaryRef)spec);
    }
    [[NSUserDefaults standardUserDefaults] setValue:@"1strun" forKey:@"FirstRun"];
    [[NSUserDefaults standardUserDefaults] synchronize];
  }
```

**Comment by grillorafael** [comment]
```typescript
export async function initApp(permissions?: DevicePermissions) {
  await uninstallApp();
  await device.installApp();
  await device.clearKeychain();
  await device.launchApp({
    newInstance: true,
    permissions,
  });
}

export async function uninstallApp() {
  await device.uninstallApp();
}

```

Essentially this
