### ISSUE TITLE
App crashes intermittently when running the same test repeatedly on iOS

### ISSUE THREAD

**Issue by crazyvan** [wix/Detox#4395]
### What happened?

When running the following test:

```ts
import { device } from 'detox';
import { componentNames } from './util';

describe('Login', () => {
    beforeAll(async () => {
        await device.launchApp({ newInstance: true, permissions: { notifications: 'YES' } });
    });

    it('should log in an existing user successfully', async () => {
        await waitFor(element(by.id(componentNames.welcome.screen)))
            .toBeVisible()
            .withTimeout(20000);
    });

    afterAll(async () => {
        await device.terminateApp();
    });
});
```

with:
```
detox test --configuration ios.sim.release e2e/login.e2e.ts
```

intermittently fails with:

```
[output.log](https://github.com/wix/Detox/files/14559583/output.log)
```

### What was the expected behaviour?

Test should pass consistently.

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 20.18.5
React Native version: 0.71.12
Has Fabric (React Native's new rendering system) enabled: no
Node version: 21.6.2
Device model: iPhone 14 Pro
iOS version: 16.0
macOS version: 14.2.1
Xcode version: 15.3
Test-runner (select one): jest

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
[detox.log](https://github.com/wix/Detox/files/14559593/detox.log)
```

</details>

**Comment by noomorph** [comment]
@asafkorem, could you look - can this be caused by DetoxSync mangling, or the failure likely is on the user's libraries' side?

**Comment by crazyvan** [comment]
Not a Detox issue. Crash is due to https://github.com/firebase/firebase-ios-sdk/issues/11403. Closing this, thanks!
