### ISSUE TITLE
Need to update dependencies - issues with Xcode 8, MacOS Sierra

### ISSUE THREAD

**Issue by talkol** [wix/detox#44]
The symptom you see is that the "testee" does not connect. The underlying reason is that Detox dynamic framework tries to load and fails because one of the dependencies throws an exception in runtime.

This project depends on several "hardcore" projects that are tightly coupled to internals and therefore might break on major version changes of Xcode and the OS:
1. EarlGrey - the version we depend upon does not load successfully after being compiled on Xcode 8
2. FBSimCtl - the version we depend upon does not work well on MacOS Sierra
3. RocketSocket - the version we depend upon also has a few problems under this setting

The solution is obvious, update these dependencies to latest version which solve all the issues. While we're at it, it's a good time to make the dependencies dynamic so they will update automatically by themselves from now on:
1. EarlGrey - rely on it as a git submodule that we can update easily by tag and change releases
2. FBSimCtl - download it pre-compiled from brew, this promises we get a correct ver per OS
3. RocketSocket - also change to rely on it as a git submodule

**Comment by talkol** [comment]
btw - my current setup that should be working well (on we do all development on it) is:

OSX El Capitan
Xcode 7.3

**Comment by LeoNatan** [comment]
Earl Grey and SocketRocket updated to support Sierra and Xcode 8.
