### ISSUE TITLE
WebView TypeText not working

### ISSUE THREAD

**Issue by alexandravychytill** [wix/Detox#4426]
### What happened?

When running on iOS type text functions is not working, even though on android it works.

Log: 
Test Failed: Failed to evaluate JavaScript on web view: <RNCWKWebView: 0x1078ba000; frame = (0 0; 393 713.333); gestureRecognizers = <NSArray: 0x600000ce33f0>; backgroundColor = UIExtendedSRGBColorSpace 1 1 1 1; layer = <CALayer: 0x6000005577c0>>. JS exception: The input element's type ('email') does not support selection.

Code: 
await web.element(by.web.id('identifier')).typeText('Hello World!');

### What was the expected behaviour?

TypeText should work

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version:  20.19.4
React Native version: 0.72.0
Has Fabric (React Native's new rendering system) enabled: yes
Node version: >=16
Device model: iPhone 15
iOS version: 17.2
macOS version: 14.4
Xcode version:  15.2 
Test-runner (select one): jest

### Detox logs

<details><summary>Detox logs</summary>

```
Test Failed: Failed to evaluate JavaScript on web view: <RNCWKWebView: 0x1078ba000; frame = (0 0; 393 713.333); gestureRecognizers = <NSArray: 0x600000ce33f0>; backgroundColor = UIExtendedSRGBColorSpace 1 1 1 1; layer = <CALayer: 0x6000005577c0>>. JS exception: The input element's type ('email') does not support selection.
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste your device.log here!
```

</details>

**Comment by asafkorem** [comment]
I'm able to reproduce this @alexandravychytill. Investigating

**Comment by asafkorem** [comment]
Related: https://w3.org/Bugs/Public/show_bug.cgi?id=24796
Working on a workaround 🙂

**Comment by asafkorem** [comment]
Hey @alexandravychytill, a fix for this issue was released with the latest Detox version ([20.19.5](https://github.com/wix/Detox/releases/tag/20.19.5)).

**Comment by swain** [comment]
@asafkorem I'm still seeing this issue on Detox 20.20.3. The field focuses, but the text does not get typed.

**Comment by aliub145** [comment]
@asafkorem I am still hitting this issue too, same as @swain - the field focuses but the text does not get typed. I will open up a new issue to track this

**Comment by asafkorem** [comment]
Thanks for the report @aliub145 @swain , I'll check the new issue soon. For now, if you could create some reproduction project / snippets for me it will be very helpful and might shorten the time for you to wait for the investigation 🙂

**Comment by pang0018** [comment]
> Thanks for the report @aliub145 @swain , I'll check the new issue soon. For now, if you could create some reproduction project / snippets for me it will be very helpful and might shorten the time for you to wait for the investigation 🙂

@asafkorem I made a reproduction project for iOS. I removed the node_modules and ios/Pods folder to make it smaller. Make sure you you disable new architecture with `RCT_NEW_ARCH_ENABLED=0 pod install`

[detoxWebTester.zip](https://github.com/user-attachments/files/17739949/detoxWebTester.zip)

**Comment by pang0018** [comment]
bump
