### ISSUE TITLE
Running detox test for Android on BrowserStack fails on Pipeline

### ISSUE THREAD

**Issue by alexandravychytill** [wix/Detox#4456]
### What happened?

When following the browserstack description and setting everything up, it works locally for running. But when I automated the steps via ci cd pipeline it always fails on the running. I am not sure why, because the setup is the same as in local. Uploading the apk works as well fine. I suspect the only difference is the proxy. I tried to set it for the running but the test is still failing. 

### What was the expected behaviour?

Success to open a connection to detox server

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

detox test -c android.cloud.debug --loglevel trace --setupFiles dotenv/config --device-boot-args="-http-proxy http://127.0.0.1:5454"

### In what environment did this happen?

Detox version: 20.13.1
React Native version: 0.72.0
Has Fabric (React Native's new rendering system) enabled: (yes/no) 
Node version: 
Device model: 
Android version: 
Test-runner (select one): jest / other

### Detox logs

```
Error: getaddrinfo ENOTFOUND
detox.browserstack.com
2358 at
GetAddrInfoReqWrap.onlookupa
II [as oncomplete] (node:dns:118:26)

Failed to open a connection to detox server
```

</details>

### Device logs

<details><summary>Device logs</summary>

```

```

</details>

**Comment by d4vidi** [comment]
Hey @alexandravychytill. You need to contact BrowserStack's support for this. Thanks.

**Comment by Mister-CK** [comment]
I also have issues running Detox with browserstack in the pipeline, locally it works. 
Where did you get the idea to add this to the run command? --device-boot-args="-http-proxy http://127.0.0.1:5454/ ? that is not in the docs.
