### ISSUE TITLE
 error: no such module 'CioTracking' import CioTracking (React-Native Firebase)

### ISSUE THREAD

**Issue by cinzianicoletti** [wix/Detox#4477]
### What happened?

in command:
`detox build --configuration ios.sim.debug
`

I get the following error, (which does not occur to me when compiling via React Native):

```
nameApp/ios/NotificationService/NotificationService.swift:3:8: error: no such module 'CioTracking'
import CioTracking

The following build commands failed:
  SwiftEmitModule normal arm64 Emitting\ module\ for\ NotificationService (in target 'NotificationService' from project 'Base')
SwiftCompile normal x86_64 nameApp/ios/NotificationService/NotificationService.swift (in target 'NotificationService' from project 'Base')
SwiftCompile normal x86_64 Compiling\ NotificationService.swift nameApp/ios/NotificationService/NotificationService.swift (in target 'NotificationService' from project 'Base')
SwiftCompile normal arm64 nameApp/ios/NotificationService/Env.swift (in target 'NotificationService' from project 'Base')
SwiftCompile normal arm64 Compiling\ Env.swift nameApp/ios/NotificationService/Env.swift (in target 'NotificationService' from project 'Base')
SwiftCompile normal x86_64 Compiling\ Env.swift nameApp/ios/NotificationService/Env.swift (in target 'NotificationService' from project 'Base')
SwiftCompile normal x86_64 nameApp/ios/NotificationService/Env.swift (in target 'NotificationService' from project 'Base')
SwiftEmitModule normal x86_64 Emitting\ module\ for\ NotificationService (in target 'NotificationService' from project 'Base')
SwiftCompile normal arm64 Compiling\ NotificationService.swift nameApp/ios/NotificationService/NotificationService.swift (in target 'NotificationService' from project 'Base')
SwiftCompile normal arm64 nameApp/ios/NotificationService/NotificationService.swift (in target 'NotificationService' from project 'Base')
(10 failures)
```

### What was the expected behaviour?

Let it execute the compilation.

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [x] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

It occurs after the insertion of the Firebase NotificationService

### In what environment did this happen?

Detox version: 20.20.3
React Native version: 0.73.6
Has Fabric (React Native's new rendering system) enabled: (yes/no) 
Node version: v19.9.0
Device model: Simulator
iOS version: 17.4.1
macOS version: Sonoma 14.4.1
Xcode version: 15.3
Test-runner (select one): jest

### Detox logs

<details><summary>Detox logs</summary>

```
 FAIL  e2e/starter.test.js
  ● Test suite failed to run

    field CFBundleIdentifier not found inside Info.plist of app binary at appName/ios/build/Build/Products/Debug-iphonesimulator/Base.app
        at _reinstallAppsOnDevice.next (<anonymous>)

      at getNextResult (node_modules/caf/src/caf.js:253:25)
      at DetoxWorker.runner (node_modules/caf/src/caf.js:293:5)
      at DetoxWorker.instance [as _reinstallAppsOnDevice] (node_modules/caf/src/caf.js:63:32)
          at init.next (<anonymous>)
      at getNextResult (node_modules/caf/src/caf.js:253:25)


```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste your device.log here!
```

</details>

**Comment by asafkorem** [comment]
This is an issue with your build, not related to Detox, `detox build` is just an alias for your own build command.
