### ISSUE TITLE
Backwards incompatible JDK version change between versions 20.18.4 and 20.18.8

### ISSUE THREAD

**Issue by cserby** [wix/Detox#4491]
### What happened?

Our project had `"detox": "~20.18.4",` defined as dependency, and was building just fine.
Some time ago, our Android build fails.
Turns out, today, this dependency is fulfilled with version `20.18.8`.
Android build fails with:
```
> Task :app:compileDebugAndroidTestJavaWithJavac FAILED
/home/.../.../android/app/src/androidTest/java/com/gowish/app/DetoxTest.java:7: error: cannot access Detox
import com.wix.detox.Detox;
                    ^
  bad class file: /home/.../.gradle/caches/transforms-3/732cffd61dabb4adeedbea6486beacfc/transformed/jetified-detox-20.18.5-api.jar(/com/wix/detox/Detox.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```

My understanding is that between versions `20.18.4` and `20.18.8`, most probably the `gradle`, thus the JDK version was changed in the `detox` build process.

I'd argue that this is a non-backwards-compatible change (as our situation shows), and thus should've triggered a version bump.

### What was the expected behaviour?

Patch versions are not supposed to introduce backwards incompatible changes.

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

Check `.class` version using `javap` on compiled `detox` `.jar` files for versions `20.18.4` and `20.18.8`.

### In what environment did this happen?

Detox version: 20.18.4 vs 20.18.8
React Native version: 0.72.3 (gradle 7.5.1)
Has Fabric (React Native's new rendering system) enabled: not relevant
Node version: not relevant (v18.16.0)
Device model: not relevant (building for emulator)
Android version: not relevant (33)
Test-runner (select one): other (playwright-test)

### Detox logs

Not relevant

### Device logs

Not relevant

### More data, please!

> Task :app:compileDebugAndroidTestJavaWithJavac FAILED
/home/.../.../android/app/src/androidTest/java/com/gowish/app/DetoxTest.java:7: error: cannot access Detox
import com.wix.detox.Detox;
                    ^
  bad class file: /home/.../.gradle/caches/transforms-3/732cffd61dabb4adeedbea6486beacfc/transformed/jetified-detox-20.18.5-api.jar(/com/wix/detox/Detox.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.

**Comment by noomorph** [comment]
Is there a chance you could use `~20.19.1` ?

**Comment by noomorph** [comment]
@cserby  could you elaborate where do you see `detox@20.18.8` ? 

This version does not exist: https://www.npmjs.com/package/detox/v/20.18.8

Make sure your computers are not compromised, we never released 20.18.8.

**Comment by noomorph** [comment]
I'm not sure if this is relevant but maybe `updateGradle.js` postinstall script doesn't find your react-native version and bumps your gradle to 8.3:

https://github.com/wix/Detox/blob/master/detox/scripts/updateGradle.js

Please check if this is the case.

**Comment by cserby** [comment]
@noomorph you're right, `~20.18.4` picks up `20.18.5`, which has the wrong `.class` versions. Trying to update to `20.19.0` now.

**Comment by cserby** [comment]
Nope, 20.19.0 gives:
```
/home/.../android/app/src/androidTest/java/com/.../app/DetoxTest.java:7: error: cannot access Detox
import com.wix.detox.Detox;
                    ^
  bad class file: /home/.../.gradle/caches/transforms-3/3d543f4f28a52cd80ef269d181783456/transformed/jetified-detox-20.19.0-api.jar(/com/wix/detox/Detox.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```
too.

For the time being, I'm happy with staying at `20.18.4`. We'll need to figure out how to update our own toolchain soon, and that'll allow us to use newer versions of `detox` too.

**Comment by noomorph** [comment]
@gosha212 if you have any ideas, please join the discussion :)

**Comment by gosha212** [comment]
@cserby try to upgrade to the latest version of detox. Move to the android folder and execute `./gradlew clean`
run detox build again.
Hope this solves your issue.

**Comment by Vikmanatus** [comment]
Hello !

I am also facing this issue on `detox` version `20.20.3` and `20.22.2`

## Environment
Detox version: `20.20.3` and `20.22.2`
React Native version: `0.72.6` (Gradle `8.0.1`)
Has Fabric (React Native's new rendering system) enabled: New architecture is not enabled
Node version: `v18.18.2`
Device model: Emulator `Pixel 6A API 33`
Android version: 33

We are trying to setup `detox` on `react-native 0.72.6` 

We were on version `20.20.3` of `detox` and the error was occurring

I just bumped the `detox` version to `20.22.2` and I did all the steps required to clean android caches :
- invalid cache in android studio
- remove `android/.gradle` folder
- delete root level `~/.gradle`
- `cd android && ./gradlew clean`

But we have the same kind of errors

We found a workaround by setting this in `android/app/build.gradle`
```gradle
    // Using legacy Detox version because of the following issue:
    // https://github.com/wix/Detox/issues/4491
    androidTestImplementation('com.wix:detox-legacy:+'){
        // Adding this extra config to avoid the following error:
        // https://github.com/wix/Detox/issues/3957
        // https://stackoverflow.com/a/68675881
        exclude module: "protobuf-lite"
    }
    // Some other dependencies
   implementation ("androidx.appcompat:appcompat:1.3.1") {
        version {
            strictly '1.3.1'
        }
    }
```

(I tried to bump `appcompat` but I currently can't as it breaks everything )

Do you have any ideas on how we could debug this issue to use the `com.wix:detox` as suggested in the documentation? 🙂

Does an upgrade to the latest version of `appcompat` could be a solution ?

Thanks in advance 

Best regards

**Comment by gosha212** [comment]
@Vikmanatus Hi, did it work for you with 1.3.1? You can try 1.6.1 for example. Let me know if it works. What is the exact error you are getting?

Can you send us a link to a sample project that reproduces the issue?
