### ISSUE TITLE
Does not launch ios simulator automatically on the Xcode 9.1

### ISSUE THREAD

**Issue by ghsdh3409** [wix/detox#450]
#### Description
* iOS simulator does not be launched automatically on the Xcode 9.1

#### Steps to Reproduce
* node_modules/.bin/mocha e2e --opts e2e/mocha.opts --configuration YOUR_CONFIGULATION_NAME

#### Detox, Node, Device, Xcode and macOS Versions
* Detox: 6.0.0
* Node: 8.9.1
* Device: iOS Simulator 11.0
* Xcode: 9.1
* macOS: 10.12.6

#### Solution
* Detox@5.10 have a change where xcode >= 9 boots simulator by `xcrun simctl boot ... ` in the https://github.com/hayanmind/detox/blame/master/detox/src/devices/AppleSimUtils.js#L197.
* But, I checked that `xcrun simctl boot ...` does not launch the ios simulator on the xcode 9.1. (I din't check that on the xcode 9.0)
* I suggests the following code to fix this issue
```diff
async boot(udid) {
  const device = await this.findDeviceByUDID(udid);
  if (_.isEqual(device.state, 'Booted') || _.isEqual(device.state, 'Booting')) {
    return false;
  }
  await this.waitForDeviceState(udid, 'Shutdown');
- await this._bootDeviceByXcodeVersion(udid);
+ await this._bootDeviceMagically(udid);
  await this.waitForDeviceState(udid, 'Booted');
}

```

**Comment by LeoNatan** [comment]
This is not a bug, it works as intended. With Xcode 9 simulator runtime, it is now possible to boot runtimes without opening the UI. The test still runs. If you want to see what's going, open the simulator app yourself, and when Detox boots the runtime, you will see a window open.
