### ISSUE TITLE
Scrolling the view Causes Timeout

### ISSUE THREAD

**Issue by heuism** [wix/detox#454]
So the issue is really simple but I am unsure it is because of detox or because of the test that I have written is:
` await element(by.id('${components.actions_scroll_view}')).scrollTo('bottom');`

or

`await element(by.id('${components.actions_scroll_view}')).scroll(pixel, direction);`

But they always stop there and give me times out.

Thanks

#### Detox, Node, Device, Xcode and macOS Versions
* Detox: 5.10
* Node: v 8.7.0
* Device: iPhone 7
* Xcode: 9.2
* macOS: 10.13

```
  1)  Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  

  2)  "after all" hook:
     Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

**Comment by GitBond** [comment]
i was having the same issue, with my app crashing whenever there was a scroll action - i'm pretty sure it's an Xcode 9.2/iOS 11.2 issue, i reverted back to Xcode 9.1/iOS 11.1 and the scrolling behavior works as desired there.

you can download Xcode 9.1 here: https://developer.apple.com/download/more/

**Comment by heuism** [comment]
@GitBond Thanks for you the input. I was just updated the Xcode and it happened. So I reckon it could be the reason as well, so thank for the confirmation.

**Comment by devinceble** [comment]
Any updates to make it work on 9.2

**Comment by Hamiltontx** [comment]
Any news about 9.2???
