### ISSUE TITLE
Test release on Android: app-release-androidTest.apk: No such file or directory

### ISSUE THREAD

**Issue by linhnh123** [wix/detox#455]
I'm running `detox test -c android.emu.release` and getting an error:

<img width="925" alt="screen shot 2017-12-08 at 2 38 12 pm" src="https://user-images.githubusercontent.com/13411581/33755968-daccf3e2-dc25-11e7-9eda-0334c74eb515.png">

With debug, it run success, the file app-debug-androidTest.apk is existing.

<img width="360" alt="screen shot 2017-12-08 at 2 46 22 pm" src="https://user-images.githubusercontent.com/13411581/33756130-9c7ee1da-dc26-11e7-8e11-87f3c65fff3d.png">

But release get that error. I don't know why the app-release-androidTest.apk does not generate, just have app-release.apk. Please help.

**Comment by DanielMSchmidt** [comment]
I believe I had the same error before, as well as @levito but somehow running it again did work for us for some arbitrary reason 🤔

**Comment by rotemmiz** [comment]
I updated the docs, please see if this solves your issue.
https://github.com/wix/detox/commit/6dd205c528496b1a5555a821447846ccd07e9147

**Comment by linhnh123** [comment]
@rotemmiz Yeah, it run ok. Thank you very much @rotemmiz . Close this issue.
