### ISSUE TITLE
Add Rosetta Simulator Instructions

### ISSUE THREAD

**Issue by d1fferenz** [wix/Detox#4571]
### Describe your idea

Hello :)
In our project, we unfortunately have to rely on a few dependencies that require the app to run on an iOS Rosetta simulator. I have used Detox in other projects before (it’s amazing), but I recently integrated it into this one with the mentioned dependencies.

When running the ‘detox build’ command multiple times in this project, you encounter different errors each time. However, they always relate to SwiftEmitModule or SwiftCompile. I couldn’t find any issues or documentation about these topics or about running Detox in a Rosetta environment. Therefore, I propose writing a documentation article addressing this problem. I resolved it as follows:

1. Changed my build command to the following: build: 'xcodebuild -workspace ios/MyApp.xcworkspace -scheme MyApp -configuration Debug -sdk iphonesimulator -arch x86_64 -derivedDataPath ios/build'
2. Run this command in the terminal: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
arch -x86_64 /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app/Contents/MacOS/Simulator

Now the build command was able to run flawless.

Thank you for your amazing work and greeting from germany!
Daniel

**Comment by asafkorem** [comment]
Thanks @differenzPriv, contributions are always welcome! `detox build` is just a proxy for your build, however, if that's a common issue, it might be a good idea to add that under our [build troubleshooting guide](https://wix.github.io/Detox/docs/troubleshooting/building-the-app).
Check our contribution docs for the Docs Site [here](https://wix.github.io/Detox/docs/contributing/documentation)
