### ISSUE TITLE
TypeError: system.element(...).toExist is not a function

### ISSUE THREAD

**Issue by m1chael-sp** [wix/Detox#4606]
### What happened?

According to the [documentation](https://wix.github.io/Detox/docs/next/api/system#toexist), I can use `await system.element(by.system.label('Allow')).toExist();` to assert that the alert exsist, however when I called exactly that, I got an error `system.element(...).toExist is not a function`. I also couldn't find any type definition for the `toExist` function.
![Screenshot 2024-10-11 at 3 14 36 PM](https://github.com/user-attachments/assets/000b860f-d71b-4492-8e73-021e5acd4793)

![Screenshot 2024-10-11 at 3 15 37 PM](https://github.com/user-attachments/assets/efdf220a-a219-44ce-a5e6-31610c18db1c)

### What was the expected behaviour?

await system.element(by.system.label('Allow')).toExist(); should work as expected

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 20.27.3
React Native version: 0.73.6
Has Fabric (React Native's new rendering system) enabled: (yes/no) 
Node version: 18.14.2
Device model: iPhone 16 simulator
iOS version: 18.0
macOS version: 14.6.1
Xcode version: 
Test-runner: jest

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste your device.log here!
```

</details>

**Comment by asafkorem** [comment]
You're right. This is a mistake in the docs, you should rewrite this with `expect(...).toExist()`. 

For instance:

```javascript
await expect(system.element(by.system.label('Allow'))).toExist();
```

We will update the docs, thanks.
