### ISSUE TITLE
Scrollview with multiple element matched

### ISSUE THREAD

**Issue by heuism** [wix/detox#462]
![image](https://user-images.githubusercontent.com/8481265/34025187-9ca31c68-e1a2-11e7-867d-e0b2aa6ef243.png)
![image](https://user-images.githubusercontent.com/8481265/34025206-b7237f1a-e1a2-11e7-89ff-b6eec6888b3b.png)

#### Description
As you can see for the pictures above, I only have 1 id for the scroll view, but then it gives me 4 matchers which is really weird and I have no idea why this one is up.

#### Steps to Reproduce
I guess it could be the KeyboardAwareScrollView?

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 5.10.0
* Node: 8.7.0
* Device: iPhone 7
* Xcode: 9.1
* macOS: 10.13.2

**Comment by heuism** [comment]
For more information, I can see there is a picker inside of the scrollview. And somehow I think the id is applied for the Picker or something, It just feel weird that I only got 1 picker, but It showed 4 UIPickerTableview that had the same id with the main ScrollView.

**Comment by heuism** [comment]
#164 #458 #433 would be similar thread

**Comment by heuism** [comment]
![image](https://user-images.githubusercontent.com/8481265/34027501-3eac679a-e1b1-11e7-9202-9a6cde9947dd.png)

Okay, it looks like the Picker generate like 3 layers of view for only 1 Picker, I guess that why i gives me 3 duplications for the matcher along with the main scrollview

**Comment by heuism** [comment]
I think this was mentioned somewhere else but I cannot recall so I just note down this again.

I saw in the log showed:

```
ancestorThatMatches((respondsToSelector(accessibilityIdentifier) && accessibilityID('incident_details_screen_scroll_view_')))
```

why the element which ancestor matches the selector would be considered as satisfied again?

**Comment by LeoNatan** [comment]
Pickers are an open issue we are yet to address. See #308. Let's track progress on the original issue.
