### ISSUE TITLE
Back button on Android

### ISSUE THREAD

**Issue by louismarie** [wix/Detox#463]
#### Description
How to simulate back button on Android with detox ?

**Comment by LeoNatan** [comment]
From a quick look in the docs and in the API, I didn't see anything related to back button, so marking this as enhancement request. Even if API exists, it should be better documented.

**Comment by rotemmiz** [comment]
You are right, and welcome to add that in a PR.
If not, I will add it in the close future, when we release v7.

**Comment by louismarie** [comment]
I followed contribution guide and I added PushBackButtonAction in expect API. 
There is no react-navigation in example app so I would like to try the new api call with my own project. 
Do you know how to try my new version of detox with my project instead of npm version ?

**Comment by rotemmiz** [comment]
I suggest you add a screen to the test app and use your new API function in Detox's test suite.
Use [BackHandler](https://facebook.github.io/react-native/docs/backhandler.html) to pop something to the screen and expect to find that this view poped .
Do not use react-navigation, we are trying to keep the test project dependency free.

**Comment by rotemmiz** [comment]
The easiest thing to do is actually use ADB to send this keycode event.
https://developer.android.com/reference/android/view/KeyEvent.html#KEYCODE_BACK
`adb shell input keyevent 4`

[Here's a useful list of keyevents](https://gist.github.com/Pulimet/5013acf2cd5b28e55036c82c91bd56d8#file-adbcommands-L103)

**Comment by LeoNatan** [comment]
Implemented in #505
