### ISSUE TITLE
toHaveToggleValue() fails with RN73

### ISSUE THREAD

**Issue by d4vidi** [wix/Detox#4639]
### What happened?

A common matcher such as:
```js
await expect(element(by.id('item.toggle'))).toHaveToggleValue(false);
```

seems to have stopped working when upgrading from RN 71 to 73. It introduces the following error:

```
Test Failed: Failed expectation: TOHAVEVALUE(value == “0”) WITH MATCHER(id == “item.toggle”)
```

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [ ] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

Should repro on any screen with a toggle coming from `react-native-ui-lib`.

### In what environment did this happen?

Detox version: 
React Native version: 
Has Fabric (React Native's new rendering system) enabled: (yes/no) 
Node version: 
Device model: 
iOS version: 
macOS version: 
Xcode version: 
Test-runner (select one): jest / other

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste your device.log here!
```

</details>

**Comment by d4vidi** [comment]
Heavy debugging shows that for toggles based on non-switch components (as in `react-native-ui-lib`), rather, utilize RN's [accessibility props](https://reactnative.dev/docs/0.73/accessibility#accessibilityvalue), the issue is reproduced. For example:
```jsx
      <TouchableOpacity {...this.getAccessibilityProps()} {...props} onPress={this.onPress}>
        {this.renderToggle()}
      </TouchableOpacity>

// where getAccessibilityProps is something like:
getAccessibilityProp() {
    return {
      accessible: true,
      accessibilityRole: 'switch',
      accessibilityState: {
        disabled,
        checked: value ? 'checked' : 'unchecked'
      },
      accessibilityValue: {
        text: value ? '1' : '0'
      }
    };

}
```

Starting RN73 (or 72), the _native_ accessibility value is now determined based on both `accessibilityValue` _and_ `accessibilityRole`. Up to RN71 it used to be set based on `accessibilityValue` alone. Namely, for a 'role=`switch`' and `value=`1`', this is the change that appears to have been introduced:

```
RN < 73:
iOS accessibility value = '1'

RN ≥ 73:
iOS accessibility value = 'switch, 1'
```

**Comment by d4vidi** [comment]
### Workaround
Resort to jest-expecting based on `getAttributes().value`

### Solution
1. (Best) `accessibilityValue` doesn't seem to be manipulated by RN when using the official RN `Switch` component. Need to have `react-native-ui-lib` either use it (instead of relying on a proprietary implementation) or at least better mimic what they are doing.
2. Adjust detox to compare either `value=<accessibilityValue>` or `value=<accessibilityRole, accessibilityValue>`

**Comment by LeoNatan** [comment]
I see RN continues to break platform norms like crazy. 🤦‍♂️

 The accessibility value is used for things like VoiceOver. So I guess now RN has broken VoiceOver support because … reasons.

**Comment by d4vidi** [comment]
> I see RN continues to break platform norms like crazy. 🤦‍♂️
> 
> The accessibility value is used for things like VoiceOver. So I guess now RN has broken VoiceOver support because … reasons.

Leo! How have you been? 😄
This time, I wouldn't say it's actually RN itself, but rather more in the places where it is used unconventionally. We're currently to get things fixed via ui-lib.

**Comment by LeoNatan** [comment]
Hello 🙂
If it’s a third party or internal framework, that’s fine. But if RN itself does it for all controls, that’s really bad.
