### ISSUE TITLE
Broken link on NPM page

### ISSUE THREAD

**Issue by danielrentz** [wix/Detox#4650]
### What happened?

The link "read the docs" on https://www.npmjs.com/package/detox results in 404.

### Was it tested on latest Detox?

- [ ] I have tested this issue on the latest Detox release and it still reproduces.

### In what environment did this happen?

Detox version: 
React Native version: 
Has Fabric (React Native's new rendering system) enabled: (yes/no) 
Node version: 
Test-runner (select one): jest / other

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

**Comment by noomorph** [comment]
Thanks, checking.
