### ISSUE TITLE
Is there a way to opt out of copilot?

### ISSUE THREAD

**Issue by calebmackdavenport** [wix/Detox#4655]
### Description

I would like to adopt Detox [20.28.0](https://github.com/wix/Detox/releases/tag/20.28.0) to resolve compatibility issues with iOS 18.1.

But my company's security team is opposed to anything related to AI assistants, such as copilot to exist, even as an unused dependency. Yeah..

Anyhow, is there a supported approach to opt out?

I can write a patch to accomplish this, but I'd prefer that the patch not be an impediment to adopting future Detox updates.

Thank you for your time, I appreciate all that your team does!

### Your environment

Detox version: 20.28.0

**Comment by asafkorem** [comment]
Copilot is meaningless without **your services** connected to it, we do not send any network request or communicate with any AI assistant.

**Comment by asafkorem** [comment]
If you could elaborate more on what they're trying to avoid, it would be helpful. It's no different from the fact that IDEs can use LLMs if you connect them (the LLMs aren't exist here).

**Comment by calebmackdavenport** [comment]
> Copilot is meaningless without **your services** connected to it, we do not send any network request or communicate with any AI assistant.

Thank you! I will take this back to my security team. Apologies for the nuisance, but your response is very helpful
