### ISSUE TITLE
Can't find device on React Native Demo Project

### ISSUE THREAD

**Issue by Igor1201** [wix/detox#467]
#### Description
Detox is able to boot up the iOS simulator, but the test fail by timeout with `Can't find device UDID`.

#### Steps to Reproduce
Run `detox test --configuration ios.sim.release` on _React Native Demo Project_.

#### Detox, Node, Device, Xcode and macOS Versions
* Detox: 6.0.4
* Node: 8.8.0
* Device: iPhone 7 Plus (but any other fails too)
* Xcode: 9.0.1
* macOS: 10.13.2 (High Sierra)

#### Device and verbose Detox logs
Detox logs: https://pastebin.com/B8qQiNV9
Device logs: https://pastebin.com/ZKBjZN1d

**Comment by Igor1201** [comment]
Update: it's probably related to High Sierra, as it works normally on my CI machine (which has macOS Sierra installed).

**Comment by Igor1201** [comment]
Another update: 
I've manually run `xcrun simctl list`, got a device UDID, booted it with `xcrun simctl boot UDID`.
If I run `xcrun simctl list` again, the device is not listed there anymore, and that's why detox/AppleSimUtils can't find it.
It's not a detox issue per se, but have someone stumbled on this issue?

**Comment by Igor1201** [comment]
One more update:
It's not related to High Sierra at all, as `xcrun` uses the binaries from the Xcode installation. I've checked the checksum of the `simctl` binary on two machines (one that work, other that doesn't), but still have no idea why this problem happens on just some machines.

**Comment by LeoNatan** [comment]
This sounds like an Apple bug. Closing for now. Please make sure to open a bug report with Apple at https://bugreport.apple.com. Post the radar number here so people can duplicate the report if they hit the same issue.

Thanks.
