### ISSUE TITLE
TypeError: this.openai.createChatCompletion is not a function

### ISSUE THREAD

**Issue by mustafahsz** [wix/Detox#4671]
### What happened?

i use createChatCompletion method but it shows `TypeError: this.openai.createChatCompletion is not a function` error

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Help us reproduce this issue!

to reproduce this issue just install last version of Detox and openAI

### In what environment did this happen?

Detox version: 20.28.0
React Native version: 0.75.4
Has Fabric (React Native's new rendering system) enabled: yes
Node version: 20.9.0
Test-runner (select one): jest 
openai: 4.77.0

**Comment by asafkorem** [comment]
Hey @mustafahsz, that sound like an [issue with Open AI API](https://community.openai.com/t/typeerror-openai-createchatcompletion-is-not-a-function/325886). 
I recommend checking their issues page: https://community.openai.com/search?q=createChatCompletion, this isn't related to Detox.
