### ISSUE TITLE
React Native + Mocha + Detox Can't Run Android Test

### ISSUE THREAD

**Issue by rbargux** [wix/detox#469]
#### Description
Error presented only on android device in IOS works. According to the data thrown by the verbose I am presented with the following error "INSTRUMENTATION_STATUS: Error = Unable to find instrumentation info for: ComponentInfo {com.testandroid.test / android.support.test.runner.AndroidJUnitRunner}" but based on the guide installation of wix / detox this instrumentation is declared in "android / app / biuld.gradle". Thank you very much and good day.

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: detox: ^6.0.4
* Mocha : 4.0.1
* Node: v8.9.3
* Device: genyMotion  Samsun Galaxy 7
* Xcode:
* macOS: Sierra . 10.12.6

#### Device and verbose Detox logs
MacBook-Pro-de-Admin:testandroid Ricardo.Bejarano$ detox test -c genyMotion -l verbose
node_modules/.bin/mocha e2e --opts e2e/mocha.opts --configuration genyMotion --loglevel verbose

detox-server info 13:49:35: server listening on localhost:64909...
detox verb ws onOpen [object Object]
detox verb ws send: {"type":"login","params":{"sessionId":"5486cdad-b4ed-38c6-f479-a464140031e6","role":"tester"},"messageId":0}
detox verb ws onMessage: {"type":"loginSuccess","params":{"sessionId":"5486cdad-b4ed-38c6-f479-a464140031e6","role":"tester"},"messageId":0}
detox verb ws
detox verb 1: /Users/Ricardo.Bejarano/Library/Android/sdk/platform-tools/adb  devices
detox verb 1: stdout: List of devices attached
detox verb 1: stdout: 192.168.56.101:5555   device
detox verb 1: stdout:
detox verb 1: stdout:
detox verb 2: /Users/Ricardo.Bejarano/Library/Android/sdk/platform-tools/adb -s 192.168.56.101:5555 shell input keyevent 82
detox verb 3: /Users/Ricardo.Bejarano/Library/Android/sdk/platform-tools/adb -s 192.168.56.101:5555 uninstall com.testandroid
detox verb 3: stdout: Success
detox verb 3: stdout:
detox verb 4: /Users/Ricardo.Bejarano/Library/Android/sdk/platform-tools/adb -s 192.168.56.101:5555 uninstall com.testandroid.test
detox verb 4: stdout: Failure [DELETE_FAILED_INTERNAL_ERROR]
detox verb 4: stdout:
detox verb 5: /Users/Ricardo.Bejarano/Library/Android/sdk/platform-tools/adb -s 192.168.56.101:5555 install -r -g /Users/Ricardo.Bejarano/Almundo/testandroid/android/app/build/outputs/apk/app-debug.apk
detox verb 5: stdout: [  0%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [  1%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [  2%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [  3%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [  4%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [  4%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [  5%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [  6%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [  7%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [  8%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [  9%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [  9%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 10%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 11%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 12%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 13%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 13%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 14%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 15%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 16%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 17%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 18%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 18%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 19%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 20%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 21%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 22%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 22%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 23%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 24%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 25%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 26%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 27%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 27%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 28%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 29%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 30%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 31%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 31%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 32%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 33%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 34%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 35%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 36%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 36%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 37%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 38%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 39%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 40%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 40%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 41%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 42%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 43%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 44%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 45%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 45%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 46%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 47%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 48%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 49%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 49%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 50%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 51%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 52%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 53%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 54%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 54%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 55%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 56%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 57%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 58%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 58%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 59%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 60%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 61%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 62%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 63%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 63%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 64%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 65%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 66%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 67%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 67%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 68%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 69%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 70%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 71%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 72%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 72%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 73%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 74%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 75%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 76%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 76%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 77%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 78%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 79%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 80%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 81%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 81%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 82%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 83%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 84%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 85%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 85%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 86%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 87%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 88%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 89%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 90%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 90%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 91%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 92%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 93%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 94%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 94%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 95%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 96%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 97%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 98%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 99%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [ 99%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: [100%] /data/local/tmp/app-debug.apk
detox verb 5: stdout: /Users/Ricardo.Bejarano/Almundo/testandroid/android/app/build/outputs/apk/app-debug.apk: 1 file pushed. 54.8 MB/s (8003661 bytes in 0.139s)
detox verb 5: stdout:       pkg: /data/local/tmp/app-debug.apk
detox verb 5: stdout: Success
detox verb 5: stdout:
detox verb 6: /Users/Ricardo.Bejarano/Library/Android/sdk/platform-tools/adb -s 192.168.56.101:5555 install -r -g /Users/Ricardo.Bejarano/Almundo/testandroid/android/app/build/outputs/apk/app-debug-androidTest.apk
detox verb 6: stdout: [  0%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [  1%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [  2%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [  3%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [  4%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [  4%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [  5%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [  6%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [  7%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [  8%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [  9%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [  9%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 10%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 11%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 12%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 13%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 13%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 14%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 15%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 16%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 17%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 18%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 18%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 19%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 20%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 21%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 22%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 23%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 23%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 24%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 25%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 26%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 27%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 27%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 28%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 29%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 30%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 31%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 32%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 32%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 33%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 34%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 35%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 36%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 36%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 37%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 38%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 39%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 40%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 41%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 41%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 42%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 43%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 44%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 45%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 46%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 46%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 47%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 48%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 49%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 50%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 50%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 51%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 52%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 53%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 54%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 55%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 55%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 56%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 57%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 58%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 59%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 59%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 60%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 61%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 62%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 63%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 64%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 64%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 65%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 66%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 67%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 68%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 69%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 69%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 70%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 71%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 72%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 73%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 73%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 74%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 75%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 76%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 77%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 78%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 78%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 79%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 80%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 81%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 82%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 83%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 83%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 84%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 85%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 86%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 87%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 87%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 88%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 89%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 90%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 91%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 92%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 92%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 93%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 94%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 95%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 96%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 96%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 97%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 98%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [ 99%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: [100%] /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: /Users/Ricardo.Bejarano/Almundo/testandroid/android/app/build/outputs/apk/app-debug-androidTest.apk: 1 file pushed. 55.5 MB/s (7972867 bytes in 0.137s)
detox verb 6: stdout:       pkg: /data/local/tmp/app-debug-androidTest.apk
detox verb 6: stdout: Failure [INSTALL_FAILED_PERMISSION_MODEL_DOWNGRADE]
detox verb 6: stdout:
detox verb 7: /Users/Ricardo.Bejarano/Library/Android/sdk/platform-tools/adb -s 192.168.56.101:5555 shell am force-stop com.testandroid
detox verb adb -s 192.168.56.101:5555 shell am instrument -w -r -e detoxServer ws://localhost:64909 -e detoxSessionId 5486cdad-b4ed-38c6-f479-a464140031e6 -e debug false com.testandroid.test/android.support.test.runner.AndroidJUnitRunner
detox verb Instrumentation spawned, childProcess.pid:  31455
detox verb ws send: {"type":"isReady","params":{},"messageId":-1000}
detox verb Instrumentation stdout:  INSTRUMENTATION_STATUS: id=ActivityManagerService
detox verb Instrumentation stdout:  INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{com.testandroid.test/android.support.test.runner.AndroidJUnitRunner}
detox verb Instrumentation stdout:
detox verb Instrumentation stdout:  INSTRUMENTATION_STATUS_CODE: -1
detox verb Instrumentation stdout:  android.util.AndroidException: INSTRUMENTATION_FAILED: com.testandroid.test/android.support.test.runner.AndroidJUnitRunner
detox verb Instrumentation stdout:          at com.android.commands.am.Am.runInstrument(Am.java:1093)
detox verb Instrumentation stdout:          at com.android.commands.am.Am.onRun(Am.java:371)
detox verb Instrumentation stdout:          at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
detox verb Instrumentation stdout:          at com.android.commands.am.Am.main(Am.java:100)
detox verb Instrumentation stdout:          at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
detox verb Instrumentation stdout:          at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)
detox verb Instrumentation stdout:
detox verb instrumentationProcess terminated due to receipt of signal null
  1) "before all" hook

  0 passing (10m)
  1 failing

  1) "before all" hook:
     Error: Timeout of 600000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

  0 passing (10m)
  1 failing

  1) "before all" hook:
     Error: Timeout of 600000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

child_process.js:644
    throw err;
    ^

Error: Command failed: node_modules/.bin/mocha e2e --opts e2e/mocha.opts --configuration genyMotion --loglevel verbose
    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at runMocha (/Users/Ricardo.Bejarano/Almundo/testandroid/node_modules/detox/local-cli/detox-test.js:61:6)
    at Object.<anonymous> (/Users/Ricardo.Bejarano/Almundo/testandroid/node_modules/detox/local-cli/detox-test.js:39:5)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)

**Comment by rotemmiz** [comment]
Did you play with your app's version code ?
```
detox verb 6: stdout: Failure [INSTALL_FAILED_PERMISSION_MODEL_DOWNGRADE]
```

Try uninstalling it manually and run tests again

**Comment by rotemmiz** [comment]
Anyway, you'll be better off asking in stackoverflow. We are using github issues to track bugs/crashes and feature requests.
