### ISSUE TITLE
Don't automatically install fbsimctl

### ISSUE THREAD

**Issue by DanielZlotin** [wix/detox#47]
This seems intrusive to do that as a postinstall step, better ask that in the installation instructions, and throw exceptions on the postinstall step.

**Comment by DanielZlotin** [comment]
Also, recommend to use fbsimctl as an *optional* dependency, and fallback on regular ios simulator CLI

**Comment by LeoNatan** [comment]
Regular iOS simulator CLI is not good to say the least. After investigating, I think we should keep the `fbsimctl` dependency. We may remove it from installing automatically, and require the users to install it themselves.

**Comment by talkol** [comment]
I think we should stop installing it automatically.. the installation isn't always working automatically due to brew flakiness.. you sometimes need to `brew uninstall fbsimctl`

let's add it to the readme and have people install manually and deal with the flakiness themselves

**Comment by talkol** [comment]
look at the strange errors it's giving me on post install:

```
Linking /usr/local/Cellar/fbsimctl/0.2.0... 
Error: Could not symlink Frameworks/XCTestBootstrap.framework/Modules
Target /usr/local/Frameworks/XCTestBootstrap.framework/Modules
already exists. You may want to remove it:
  rm '/usr/local/Frameworks/XCTestBootstrap.framework/Modules'

To force the link and overwrite all conflicting files:
  brew link --overwrite fbsimctl

To list all files that would be deleted:
  brew link --overwrite --dry-run fbsimctl
```
I prefer people google this stuff and handle it manually if it happens

**Comment by LeoNatan** [comment]
Why didn't the script figure out fbsimctl is already installed? We have checks for that.

**Comment by LeoNatan** [comment]
Also 0.2.0 is old. There is 0.2.2 out already

**Comment by talkol** [comment]
I had to `brew update` and fix several brew issues since the Sierra upgrade was pretty rough on brew

I installed 0.2.2 now.. but still.. you need to fiddle with brew
I prefer users will do it on their own so they can google issues there and not open issues for postinstall problems

**Comment by LeoNatan** [comment]
Yes, if you didn't maintain your `brew` installation, it causes issues. I agree about not installing fbsimctl, however in postinstall we must verify that fbsimctl is not installed and at the very least issue a colorful warning to let the user know.

**Comment by rotemmiz** [comment]
done in v5. updated docs.
