### ISSUE TITLE
Detox flakiness while testing on Circle CI

### ISSUE THREAD

**Issue by heuism** [wix/detox#471]
#### Description
I ran the test on Circle CI but there is a weird stuff because I just want to make sure the test pass properly so I ran 3 times, build + test. But then I failed the first 2 and pass the last one, or may be pass the first and fail the second. But this is not an often thing, it just gave me failed sometimes.

![image](https://user-images.githubusercontent.com/8481265/34238414-8a5cf2a6-e655-11e7-92f7-daea5bc599ea.png)

![image](https://user-images.githubusercontent.com/8481265/34241952-f63f9caa-e66c-11e7-97cb-e8c8fc0dc89d.png)

FYI, the error it gave for the **FAILED BUILDS** is:

```
Error: Command failed: xcodebuild -workspace ios/<project>.xcworkspace -scheme <project> -configuration Release -sdk iphonesimulator -derivedDataPath ios/build
    at checkExecSyncError (child_process.js:601:13)
```

The other times, it **built successfully** but was failed middle of the test while it already passed once before.

* Detox: 5.10.0
* Node: 
* Device: iPhone 7
* Xcode: 9.1
* macOS:

**Comment by LeoNatan** [comment]
I don't see how this is a Detox issue. You try to build your own project, which fails.
Please provide the build log so we can see what the issue is.

**Comment by heuism** [comment]
Hi @LeoNatan, I don't know when detox build doing, what is the background trying to do like bundling or packaging all the dependencies and stuffs. Would any case that the bundling and packaging is unstable or something? If it failed 3 times in the a row I wouldn't be too worried, but because it is 2 failed 1 passed and vice versa.

Here is the link [cool](https://drive.google.com/file/d/1fqNql0DUNsMBNtiN5iRevjuk6Fp7bBD7/view?usp=sharing)

**Comment by LeoNatan** [comment]
RNMixpanel fails compilation. It's right there in the log file.
This is not a Detox issue. All Detox does it run the command you provide it with in package.json.
