### ISSUE TITLE
Ubuntu  16.04.3, can't build debug apk for emulator

### ISSUE THREAD

**Issue by biboc** [wix/detox#472]
#### Description
On Ubuntu  16.04.3, I can't build my android app with Detox
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

And Detox "detox": "^5.10.0"

#### Steps to Reproduce
RNApp$ detox build --configuration android.emu.debug
pushd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && popd
/bin/sh: 1: pushd: not found
child_process.js:614
    throw err;
    ^

Could you move from /bin/sh to /bin/bash please if it is not already done

**Comment by LeoNatan** [comment]
Hmm, this is interesting. Thanks for bringing it to our attention!

**Comment by biboc** [comment]
Pushd is not included on /bin/sh on Ubuntu
Have you any idea how to change this to bash interpreter or not used popd(pushd)?

**Comment by rotemmiz** [comment]
build is just a convenience method added to detox-cli (read more about it in the docs)
You control this command, it's in your package.json...

Just use `cd android` instead:
`cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug`

**Comment by biboc** [comment]
Thanks for the answer
Would be nice if the build command is cross-platform

**Comment by LeoNatan** [comment]
It is. If you want to run your build command in a bash environment, either put it in a shell file with a bash shell or use `bash -c`.
