### ISSUE TITLE
[Feature request] Get current UI name and/or hanlder

### ISSUE THREAD

**Issue by dzunglht** [wix/detox#473]
Dear folk,
How to determine current screen/popup during the test ? Can we extract some meta data from business source code ?
Bunch of thanks and regards

**Comment by rotemmiz** [comment]
Can you please elaborate? Not sure I understand what you mean, and please include a use case to the feature you're requesting.

**Comment by LeoNatan** [comment]
This is not possible. Once RN does its magic and presents native views, it’s not possible to reverse this process in order to have some metadata.
