### ISSUE TITLE
Support Web Testing - React Native Web

### ISSUE THREAD

**Issue by amorenew** [wix/detox#482]
> Cross Platform: Write cross-platform tests in JavaScript. Currently supports iOS, Android is nearly complete. View the Android status page.

I am using [React Native Web](https://github.com/necolas/react-native-web) which allow using RN on the web.
Just I have to change .js to .web.js or .electron.js and voila I can customize UI to match web or desktop.
I wonder if there is an intention to support web testing too?

**Comment by LeoNatan** [comment]
Not on our plans, but a legit use case. Contributions welcome.

**Comment by amorenew** [comment]
@LeoNatan Thank you
