### ISSUE TITLE
Adding "reuse": true to configurations doesn't do anything

### ISSUE THREAD

**Issue by kdenz** [wix/detox#486]
* Detox: 6.0.4
* Node: 8.5
* Device: iOS 11.2
* Xcode: 9.2
* macOS: 10.13.1

I'm using Jest

According to @dariocavero in https://github.com/wix/detox/issues/143#issuecomment-330383124 , it's possible to add "reuse" under detox's config like this:
![image](https://user-images.githubusercontent.com/12795428/34514210-3c310fc0-f0a7-11e7-82a0-d0f9f70cbf7b.png)

My scripts in package.json
![image](https://user-images.githubusercontent.com/12795428/34514227-5af1c616-f0a7-11e7-88b9-4d0fda433c4a.png)

My init.js under e2e folder
![image](https://user-images.githubusercontent.com/12795428/34514087-753562cc-f0a6-11e7-9f55-b0c5f1d950f0.png)

My config.json under e2e folder
![image](https://user-images.githubusercontent.com/12795428/34514107-87067914-f0a6-11e7-94bb-25834326ff6a.png)

But it's not working, in the end I'll need to use `detox test -r` to make reuse work.

The reason I would prefer not using detox test is because it seems like detox test doesn't support flexible optional testing, such as if I just want to test the Welcome screen and not others. I can do this with `jest WelcomeScreen`. And also the unit and e2e tests can easily be chained together.

**Comment by rotemmiz** [comment]
This can be a welcome PR
https://github.com/wix/detox/blob/master/detox/src/devices/Device.js#L26

You'll need to also check if the app is installed on the device, and if not, throw an error
