### ISSUE TITLE
Can u add a feature to return values from Detox in an array

### ISSUE THREAD

**Issue by zetendra** [wix/detox#489]
We can automate more tests related to sorting order of list etc ....

**Comment by DanielMSchmidt** [comment]
Can you explain your use case a bit?

**Comment by zetendra** [comment]
Hi @DanielMSchmidt 
The case is, in my app i need to verify if all the accounts are sorted in ascending or descending order or not

**Comment by rotemmiz** [comment]
This use case fits unit tests much more than it fits e2e. If you want to test that your dataset is sorted, do it in unit tests... E2E is for functional tests, not data.

**Comment by zetendra** [comment]
Ok thank you @rotemmiz 

One more query on element attributes, can we get the element state? 

Example : If i want to check if button is enabled or disabled or selected and so on ......

**Comment by LeoNatan** [comment]
>If i want to check if button is enabled or disabled or selected and so on ......

This is very hard to do. Remember, we only have the native side of the story, while RN maintains its controls' state elsewhere in JS. It is not possible for us to deduce that state by looking at the native view hierarchy.
