### ISSUE TITLE
git submodules prevent from switching branches

### ISSUE THREAD

**Issue by talkol** [wix/detox#49]
maybe a new approach?

**Comment by LeoNatan** [comment]
This seems like "by design" of Git.

**Comment by talkol** [comment]
is it possible to add a remark in the README of detox/detox with a short explanation of this issue and what to do it about it? (a command line that deletes what needs to be deleted)?

**Comment by rotemmiz** [comment]
we are way past the v3 era, and v4 is in master. closing.
