### ISSUE TITLE
make "npm run e2e" work again

### ISSUE THREAD

**Issue by talkol** [wix/detox#50]
```
cd detox/detox
npm install
npm run build
npm run test-clean
npm run test-install
# don't run this now: npm run test
cd test
npm run e2e
```

The last line is how end users (not people developing detox itself) will eventually run detox
this means any parameters you want to send need to be designed to make sense there, like:
`npm run e2e -- --scheme=ios-simulator.release`
`npm run e2e -- --verbose`

If you want to improve the scripts for people developing detox, this must come as step 2 after the API for end users is finished and working

**Comment by LeoNatan** [comment]
It just works©.

Other improvements such as verbose, target and scheme should all come when CLI tools are developed (#56).
