### ISSUE TITLE
invalid top level package.json file and pre-release/beta release request

### ISSUE THREAD

**Issue by coderjonny** [wix/detox#501]
#### Description

Hello, thanks for this awesome e2e testing library for React Native!
I'm trying to using the latest greatest commit on Detox#master but Yarn/npm won't allow it. 
The top level `package.json` is invalid, so I've made pull request to address it:
https://github.com/wix/detox/pull/500

I would love to use the latest features and would it would help out greatly especially the android update.

Would you guys be open to do pre-releases or beta releases in the future? 

#### Steps to Reproduce

`yarn add https://github.com/wix/detox.git#master -D` 
will error out because the top level `package.json` is invalid

![screen shot 2018-01-08 at 1 47 30 pm](https://user-images.githubusercontent.com/753091/34694063-a56c0f7c-f47a-11e7-966e-28e5d33ad06d.png)

![screen shot 2018-01-04 at 2 12 42 pm](https://user-images.githubusercontent.com/753091/34694097-bbab4dde-f47a-11e7-83f4-2c171c077791.png)
The top level `package.json` is not valid.
http://package-json-validator.com/

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: detox@6.0.4
* Node: v8.9.3
* Yarn: 1.3.2

**Comment by LeoNatan** [comment]
As discussed in the PR, closing this issue.
