### ISSUE TITLE
detox 7

### ISSUE THREAD

**Issue by matyj** [wix/detox#507]
How do we install detox 7 by npm? Current version is still 6.0.4, but docs says that version 7 has support for Android Studio 3.0.

**Comment by fdnhkj** [comment]
Any ETA of detox 7 ? https://github.com/wix/detox/pull/468#issuecomment-355973971 https://github.com/wix/detox/issues/501
Or is there a fix for detox 6 with Gradle 4.1 Android projects? I am facing the same issue as in https://github.com/wix/detox/issues/503 .

**Comment by OisinOKeeffe** [comment]
@fdnhkj I was able to get passed this by going into the build.gradle file from detox\android\detox

declare product flavors and add them to the new or old OKhttp definitions like so:
`flavorDimensions "minReactNative46"

    productFlavors {
        newOkhttp {
          dimension "minReactNative46"
        }
    }`

**Comment by matyj** [comment]
well yeah, I did that as well, but in docs you can still find info that it's supported, but you cannot install it whatsoever. I'd rather use lib according to docs instead of modifying it ^^

**Comment by rotemmiz** [comment]
detox@7.0.0-alpha.0 is out. Try it, give feedback please.

**Comment by coderjonny** [comment]
Still having some `flavorDimensions` gradle build issues.
I did something similar to @OisinOKeeffe .
https://github.com/wix/detox/issues/515

**Comment by Karniej** [comment]
@rotemmiz Should the newest version of detox work with android and Genymotion ? 
 "react-native": "0.51.0",
   "detox": "^7.0.0-alpha.0",
    "babel-jest": "^22.1.0",
  "jest": "^22.1.0",

I got it working for iOS, but cannot work it out with android... Recreated all the steps from the tutorial.
