### ISSUE TITLE
detox-cli on fails to run on windows with nvm

### ISSUE THREAD

**Issue by nagyv** [wix/detox#509]
#### Description

Running detox.cmd as it should be:

```
detox.cmd
/bin/bash: C:\Program Files\nodejs\node_modules\detox-cli\cli.sh: No such file or directory
```

Running the cli as detox.cmd calls it:
```
bash.exe cli.sh
/mnt/c/ProgramData/nvm/v7.10.1/node_modules/detox-cli/node_modules/detox/package.json
detox is not installed in this directory
```

Thus it might be related to nvm, but I'm not sure about this, as running the nvm version directly has the same error as the first run:

```
"c:\ProgramData\nvm\v7.10.1\detox.cmd" help
/bin/bash: c:\ProgramData\nvm\v7.10.1\node_modules\detox-cli\cli.sh: No such file or directory
```

at the same time I can run detox with `node_modules\.bin\detox.cmd` and it prints its help.

#### Steps to Reproduce

just run `detox.cmd` on windows with nvm

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 6.0.4
* Node: 7.10.1
* Device: Windows 10 with nvm
* nvm version: 1.1.5

**Comment by rotemmiz** [comment]
Detox doesn't support windows currently. PRs are very welcome though.
You're welcome to open a [Feature request] issue to add support, or better yet, submit a PR.
I'm closing this issue.

**Comment by LeoNatan** [comment]
While Windows is not supported, the Linux Subsystem for Windows may be; I suggest trying to run Detox there.
