### ISSUE TITLE
Runner agnostic file targeting

### ISSUE THREAD

**Issue by jeremyeaton89** [wix/Detox#512]
Hey guys,

Realized i jumped the gun by submitting a PR before opening an issue. I'm using Jest and thought it would be great to have a runner agnostic way of targeting a specific file to run against via command line. 

I decided to try [this out](https://github.com/wix/detox/pull/502) — or perhaps there's an easy way of targeting a specific file using jest?

**Comment by noomorph** [comment]
This issue is resolved, right? Can we close it, @rotemmiz ?

**Comment by noomorph** [comment]
Both jest and mocha can run a test using Detox CLI like this, since `detox@12.1.x`:

```
detox test -c ios.your.configuration e2e/specific.test.js
```
