### ISSUE TITLE
In detox/build.gradle: Could not find method minReactNative44Implementation()

### ISSUE THREAD

**Issue by sunweiyang** [wix/detox#516]
#### Description / Steps to Reproduce
* Update to detox@7.0.0-alpha.0 (on react-native@0.52.0).
* Run `./gradlew clean` from the React Native project's `android/` directory.

This results in the following output:
```
Running  ./gradlew clean ...
Starting a Gradle Daemon (subsequent builds will be faster)
Reading env from: .env
Reading env from: .env

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/sunw/Skale/Repos/skale-react-native/Skale/node_modules/detox/android/detox/build.gradle' line: 60

* What went wrong:
A problem occurred evaluating project ':detox'.
> Could not find method minReactNative44Implementation() for arguments [com.squareup.okhttp3:okhttp:3.4.1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 7.0.0-alpha.0
* Node: 5.6.0
* Device: MacBook Pro 2016

**Comment by sunweiyang** [comment]
This issue still exists in detox@7.0.1.

**Comment by rborn** [comment]
Same for 7.1.0
I tried to follow the gradle 3 instructions but the app won't even compile :(

**Comment by shockdesign** [comment]
Upgrading Gradle worked for me...

Modified build.gradle in the root android folder

**Comment by shockdesign** [comment]
Also make sure in the `app/build.gradle` file you have this..

```
dependencies {
    ....
    androidTestCompile(project(path: ":detox", configuration: "newOkhttpDebug"), {
      exclude group: 'com.android.support', module: 'support-annotations'
    })
    androidTestCompile 'junit:junit:4.12'
    androidTestCompile 'com.android.support.test:runner:1.0.1'
    androidTestCompile 'com.android.support.test:rules:1.0.1'
}
```

**Comment by shockdesign** [comment]
And that should solve the `Test` issues you're having?

**Comment by sunweiyang** [comment]
Is there a solution that does not involve updating Gradle? It'd be nice to have Detox work right after `react-native init` (especially since that's generally more compatible with other RN libraries).

**Comment by sunweiyang** [comment]
@shockdesign the `app/build.gradle` dependencies alone (without upgrading Gradle) do not resolve the issue.

**Comment by shockdesign** [comment]
@sunweiyang you have to upgrade Gradle as Detox 7 relies on changes in Gradle to work properly.

**Comment by rborn** [comment]
@shockdesign I updated based on your suggestions and https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html but I get 2 errors now:

1. If I add the `newOkhttpDebug` line I get a `flavorDimensions not existent` error.
2. If I just do ` debugImplementation(project(path: ":detox"))` the app compiles, gets intalled on the genymotion sim or real device but then it doesn't start  and will lead to a timeout error.

Any ideas? 

Thank you!

**Comment by shockdesign** [comment]
@rborn Sorry, your `debugImplementation` should be `androidTestImplementation` but that should work with just `project(path: ":detox"))` and no configuration

**Comment by rborn** [comment]
@shockdesign I managed to fix it, but I don't remember what I did, it was me doing some stupid thing (more than sure I was changing stuff in the wrong place). Thanks for the reply and sorry for not getting back in time 😔

**Comment by noomorph** [comment]
Related to: https://github.com/wix/detox/issues/774

**Comment by rotemmiz** [comment]
Not really related since this is a build time dependency, the computer does a great job at stopping bad configurations/broken dependencies. Running tests however has no validation, I want to add runtime validation to versions of cli tools we use.

**Comment by rotemmiz** [comment]
Though this issue is closed, I would like to address a few of the issues raised here.

There are two flavours to detox Android, one for rn44-45, and the other for 46 and up. Please make sure you read the [Android setup docs](https://github.com/wix/detox/blob/master/docs/Introduction.Android.md#choosing-the-right-build-type-in-missingdimensionstrategy).

`newOkhttpDebug` is the old API, it was changed between Detox 6 and 7

**Comment by noomorph** [comment]
@rotemmiz , I see your point. In any case, it could be a more user-friendly error message, so maybe it's a nice-to-have one.

**Comment by rotemmiz** [comment]
We have bigger problems 😣
