### ISSUE TITLE
Simplify test failure output

### ISSUE THREAD

**Issue by CodingItWrong** [wix/Detox#518]
I would be interested in contributing to Detox to simplify the test failure output, if it's interesting and nobody is already working on it. Here's what I'm thinking:

## Current Behavior

Currently Detox passes EarlGrey test failures through fairly unchanged. For example, if I have the test step:

```js
await element(by.id('messageText')).typeText('New message');
```

But that element is not found, the error message I get is fairly complex:

> Error: Error: Cannot find UI element.
> Exception with Action: {
>   "Action Name" : "Type 'New message'",
>   "Element Matcher" : "(((respondsToSelector(accessibilityIdentifier) && accessibilityID('messageText')) && !(kindOfClass('RCTScrollView'))) || (kindOfClass('UIScrollView') && ((kindOfClass('UIView') || respondsToSelector(accessibilityContainer)) && ancestorThatMatches(((respondsToSelector(accessibilityIdentifier) && accessibilityID('messageText')) && kindOfClass('RCTScrollView'))))))",
>   "Recovery Suggestion" : "Check if the element exists in the UI hierarchy printed below. If it exists, adjust the matcher so that it accurately matches element."
> }

I was writing [a tutorial for doing TDD with Detox](http://learntdd.in/react-native/), and I found that I had to do a fair amount of work to explain to the reader how to find out from the error what actually went wrong. `accessibilityID('messageText')` is what you're looking for, but it's in the middle of other unrelated EarlGrey matchers that aren't what the user of Detox saw. Also, `accessibilityID` isn't a concept the user typed; they typed `element(by.id('messageText'))`.

## Proposed Behavior

I would love to see test failure output more like what [Cypress](https://cypress.io) provides on the web. If the following matcher fails:

```js
cy.get("[data-test='messageText']").type('New message');
```

The failure is:

```
Expected to find element: '[data-test='messageText']', but never found it.
```

Error messages when end-to-end testing in Ruby with RSpec and Capybara are similarly clear.

I think clearer error messages will make TDD in particular easier with Detox. If you are writing your tests after production code, you don't expect the tests to fail, so it's okay if it takes a little work to figure out what went wrong in the rare case that a test fails. But in TDD you make sure the test _always_ fails first, and you confirm that the _reason_ it failed is the reason you expected. That means always having to parse through test failures.

## Implementation

I haven't looked into the code yet, but I can see that currently Detox is returning an EarlGrey error. I think improving the failure messages would involve catching this failure internally and returning a version translated to match the terminology of the Detox test.

Questions:

1. Is there interest in improved failure messages?
2. Has anyone looked into it yet?
3. Is there anything in the architecture of Detox that would suggest that this isn't a feature that should be added right now?

Thanks for your thoughts—looking forward to contributing if I can!

**Comment by rotemmiz** [comment]
1. YES PLEASE!!!!!!!!!!!!
2. Issue #127 deals with it, but not in depth. This is a very important task and we'll be thrilled is someone can seriously commit to it.
It needs to be solved on both platforms BTW.

3. It's just a matter of time, it can be developed independently and has no known blockers.

**Comment by CodingItWrong** [comment]
Great, I'm glad this is potentially a valuable contribution I can make! Detox has made the difference for me between "not really interested in native dev" to "excited" so I'm glad to give back if I can! I'll keep this issue updated with my progress.

**Comment by Crash--** [comment]
If someone works on it, is there a way to make it configurable? Something like the `--verbose` flag? 
I understand the use case when you write TDD and you know why your tests are failing.  
But there is also another use case, like running detox on a CI pipeline. With this use case, the more information we have make the debugging easier. 

```
     Error: Error: Cannot perform action due to constraint(s) failure.
Exception with Action: {
  "Action Name" : "Swipe Left for duration 0.1",
  "Element Description" : "<RCTView:0x7fd8f606b820; AX=N; AX.id='card_8'; AX.label='Rappelez-vous d'effectuer une action Titre Note Date 03/01/2018 Heure 00:00 Créer un rappel'; AX.frame={{0, 64}, {375, 603}}; AX.activationPoint={187.5, 365.5}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {375, 603}}; opaque; alpha=1>",
  "Failed Constraint(s)" : "!(isSystemAlertViewShown)",
  "All Constraint(s)" : "(interactable && !(isSystemAlertViewShown) && kindOfClass('UIView') && respondsToSelector(accessibilityFrame))",
  "Recovery Suggestion" : "Adjust element properties so that it matches the failed constraint(s)."
}
```
Reading this error, tells me that detox can not swipe left because there is a `SystemAlertViewShown`. 

Also, if we arrive to have something like : 
` Error: Cannot perform "swipe left" because a SystemAlertView is shown` it will become even easier to debug on CI environment.

**Comment by LeoNatan** [comment]
Closing old issues. The error messages we print come directly from Earl Grey. It is out of scope for the project to try and somehow change them.
