### ISSUE TITLE
Failing tests pass, afterEach fails

### ISSUE THREAD

**Issue by yedidyak** [wix/detox#52]
When a test fails, the terminal marks it as passed, and the afterEach hook fails.

Expected: Failing tests should fail.

**Comment by LeoNatan** [comment]
I can verify this occurs when a test fails. There is a bug in the JS mechanism somewhere; could be just a visual glitch in the way things are presented.

**Comment by rotemmiz** [comment]
v5 doesn't need to hook on afterEach anymore. Due to its async-await nature it now fails in the appropriate scope.
