### ISSUE TITLE
Enhancement: Scroll until visible

### ISSUE THREAD

**Issue by OisinOKeeffe** [wix/detox#520]
Not sure where or how to request this but in order to reduce flakiness of tests it would be great to have an action that scrolled until an element was visible rather than having to scroll a specific amount of pixels.

The use case I am thinking of is a list of items each with a different onPress method for example. If I want to write a test to confirm that each of these items navigates correctly when pressed I currently have no other way of doing it.

**Comment by zetendra** [comment]
@OisinOKeeffe 

You can use below ...

await waitFor(element(by.id('<Some Id>'))).toBeVisible().whileElement(by.id('<Some Id>')).scroll('down');

**Comment by OisinOKeeffe** [comment]
@zetendra oh my that works perfect. I didnt know that whileElement() existed, where did you find that?

**Comment by zetendra** [comment]
@OisinOKeeffe It is mentioned in detox documentation, please tap on below link and scroll the page to end

https://github.com/wix/detox/blob/master/docs/APIRef.waitFor.md

**Comment by dmitrybirin** [comment]
Shouldn't it be 

await waitFor(element(by.text('Text5'))).toBeVisible().whileElement(by.id('ScrollView630')).scroll(**50**, 'down')

? 
With the 'speed' of scrolling as first parameter?
