### ISSUE TITLE
Generate JSDoc comments for generated code

### ISSUE THREAD

**Issue by DanielMSchmidt** [wix/detox#521]
It might be useful (especially for new contributors) to have jsdoc comments on the generated classes that indicate how to use it. These would also show up per autosuggest in some editors, which would be a nice benefit on top.

The reason why I want to add this is 

a) It's fairly easy to accomplish, we have all the information needed and only 2-5 special cases (`Matcher<View>`, `id<GREYMatcher>`, ...) to take care of
b) A bit of documentation could make the code a bit more understandable

My approach would be to have a JSDoc comment like this generated:

```js
/**
* Invokes scrollToEdge on com.wix.detox.espresso.Detoxaction
* @param {String} edge One of "top", "bottom", "left, and "right"
* @example 
*   this._call = invoke.callDirectly(DetoxAction.scrollToEdge("top"));
**/
scrollToEdge(edge) {
```

**Comment by DanielMSchmidt** [comment]
What do you think, is this something worth to spend time on or is it just me seeing a point here? Please be honest ;)

**Comment by LeoNatan** [comment]
Yes, very important!
I think we should most of our documentation to this type of code documentation and generate the .md files out of those. That's much easier for developers to follow.

**Comment by DanielMSchmidt** [comment]
Generating stuff from these comments is super hard :(

**Comment by LeoNatan** [comment]
Could you please elaborate?

**Comment by rotemmiz** [comment]
In @DanielMSchmidt we trust ! 
but yes, please elaborate :)

**Comment by DanielMSchmidt** [comment]
Will try my best 🙈 

@LeoNatan See the conversation in https://github.com/wix/detox/pull/491#issue-286503558 I tried to communicate it as good as I can :)

**Comment by DanielMSchmidt** [comment]
I would see #563 as follow up on this, so I close this issue now. If you disagree feel free to tell me, I will reopen this 👍
