### ISSUE TITLE
Enable detox-server to bind to something different than localhost

### ISSUE THREAD

**Issue by mverardo** [wix/Detox#526]
Currently, detox allows us to determine the address to which the client should connect [with the 
 `server` key in `package.json`](https://github.com/wix/detox/blob/master/docs/APIRef.Configuration.md#server-configuration). 

The problem is it lacks an option to set the IP to which `detox-server`'s websocket should bind, [defaulting to `localhost`](https://github.com/wix/detox/blob/master/detox-server/src/DetoxServer.js#L11), which doesn't allow us to connect to this server through an external device on the network.

For context: we bumped into this problem when trying to use detox on our device farm, in which devices are not connected directly to the machine running `detox-server`.

The fix to this would be simple: add a new config to the `session` key on package.json to override the `localhost` default [here](https://github.com/wix/detox/blob/master/detox-server/src/DetoxServer.js#L11) (WebSocketServer accepts a `host` key).

* Detox:  6.0.4
* Node: irrelevant
* Device: irrelevant
* Xcode: irrelevant
* macOS:  irrelevant

**Comment by LeoNatan** [comment]
This can have potential issues on iOS, as networking requires App Transport Security. Asking users to add exceptions to internal servers sounds sub-optimal to me. Any solution that deals with the issues brought here should also account for the ATS problem.

**Comment by LeoNatan** [comment]
As we've been moving more and more to integrate the server itself with the test runner process, we will not be implementing this.
