### ISSUE TITLE
How to update to later version?

### ISSUE THREAD

**Issue by heuism** [wix/detox#528]
Hi guys, this is not the bug,

As I saw the framework has been updated to 7.0 alpha. But when I ran `npm install detox --save-dev`. The version is stay as 5.10.0 even though I put the ^5.10.0 in the package.json.

Does anyone know why? I am running with "react-native": "0.48.4",

Thanks

**Comment by chadlwilson** [comment]
This seems like a standard npm question to me? `npm install` and `npm update` respect semantic versioning, so will not change your major version from `5.x.x` to `6.x.x` when your `package.json` says `^5.10.0`. See https://docs.npmjs.com/cli/update

You could just `npm remove` it and `npm add` it back again to get the latest bleeding-edge version.

**Comment by rotemmiz** [comment]
Also, take a look in you folder for package-lock.json and delete it if exists.
