### ISSUE TITLE
Run individual Detox test

### ISSUE THREAD

**Issue by CodingItWrong** [wix/Detox#536]
Running `detox test` runs all tests in the suite. Is there a way to run a subset of the tests? A single test file, or a single test case.

I've configured Detox to use Mocha as the test runner, as per the docs. I know that Mocha has a `-g` option to specify a pattern for the tests to run. But options passed to the `detox` command don't seem to be passed along to `mocha` (which makes sense):

```
# detox test -g mytestcase

error: unknown option `-g'
```

I can use Mocha's `.only()` function to designate one `it()` or `describe()` to run—but that involves changes in the source code. It would be great if I could have the option to use a command-line argument to specify which test to run instead. That would certainly be test-runner-specific, of course—so I think providing a way to pass arbitrary command-line arguments from `detox test` along to the test could be good.

I'm attempting to use Detox for TDD, and the quicker the feedback I  can get, the better. As my test suite grows, it would become less and less motivating to run tests as I develop if the time to run gets longer  and longer.

**Comment by rotemmiz** [comment]
It may be a good idea to passthrough command line arguments to test runners.
As always, this is a really good PR candidate :)

**Comment by CodingItWrong** [comment]
OK great, I will investigate! (I meant to say that.) This feels like it'd be an easier PR to start with than my #518 proposa.

**Comment by kdenz** [comment]
This is needed by our team as well!

**Comment by heuism** [comment]
you can use cucumber like i did for as the test runner. with Cucumber, there is a tag for the scenario and therefore can run your specific test case with the tag.

**Comment by rwgatorfan** [comment]
My team could also use this

**Comment by jeremyeaton89** [comment]
just curious to understand pros and cons of passing this particular flag to the test runners vs just overriding testFolder, [like this](https://github.com/wix/detox/pull/502), if anyone has insight

**Comment by kylethebaker** [comment]
This is something that I think is really important to have given how long some of the tests can take to run.

**Comment by sinewave440hz** [comment]
arbitrary command-line arguments from `detox test`, yes please! :) I'm using jest and have much more success with my tests when running `detox test` than using the jest runner directly. This would be a very useful enhancement.

**Comment by juddey** [comment]
This'd be a real time-saver :)

**Comment by kdenz** [comment]
Would be great if this is supported soon :)

**Comment by nezaidu** [comment]
+1

**Comment by wildseansy** [comment]
another temporary workaround is you can edit the e2e/mocha.opts, and [add a `grep` argument](https://mochajs.org/#usage) to only run a test file matching a certain string

**Comment by lukasgjetting** [comment]
Has work been started on this? If not, I will start working on it.

**Comment by CodingItWrong** [comment]
I haven't started work on this or heard of anyone who has. FYI though this PR implements something related that is Jest-specific. It's probably worth looking into how it's implemented to see if this issue is still needed: https://github.com/wix/Detox/pull/1083

**Comment by lukasgjetting** [comment]
Seems like a solution to pass all arguments to the test runner has already been implemented in #1025

**Comment by CodingItWrong** [comment]
@jeremyeaton89 Nice, thanks for adding us and for letting us know! I'm closing this issue as the `-f` option satisfies just what I was looking for.
