### ISSUE TITLE
Genymotion android config name setting

### ISSUE THREAD

**Issue by jeremyeaton89** [wix/Detox#538]
Currently we hardcode the name of genymotion emulator we get from `adb devices` e.g. 192.168.63.101:5555. 

Any plans on making this set dynamically so multiple devs can use?

**Comment by OkancanCosar** [comment]
https://github.com/wix/detox/blob/master/docs/More.AndroidSupportStatus.md

`"android.emu.release": {
        "binaryPath": "android/app/build/outputs/apk/release/app-release.apk",
        "build": "cd android && ./gradlew assembleRelease assembleAndroidTest -DtestBuildType=release",
        "type": "android.attached",
        "name": "192.168.56.101:5555"
      }
`

**Comment by LeoNatan** [comment]
@d4vidi Can this be closed?

**Comment by d4vidi** [comment]
Wow. I don't think so. Genycloud is quite different than this. Most likely, the problem is still there.

**Comment by noomorph** [comment]
@d4vidi  ?? :)

**Comment by d4vidi** [comment]
Lol. Reiterating, I see this was never related to genymotion _cloud_. I need to better understand the use case here.
