### ISSUE TITLE
Add navigation support

### ISSUE THREAD

**Issue by d4vidi** [wix/detox#54]
Need to be able to check various navigation scenarios, for example:

1.  Is this there root screen? - yes/no
2. (Mainly) for inner screens: get navigation bar info (e.g. title text) and nav buttons captions.
3. Same for modals...
4. Get the app name of current screen (e.g. Safari)

Also, need to be able to perform a 'back' navigation **action**.

**Comment by LeoNatan** [comment]
This is an issue of RN navigation. Need to provide testID for these elements.
CC @DanielZlotin

**Comment by DanielZlotin** [comment]
@d4vidi open an issue in Navigation please
