### ISSUE TITLE
Ionic compatibility

### ISSUE THREAD

**Issue by iGitScor** [wix/detox#547]
#### Description

Hi guys, I love your tool but I was a little bit confused when I tried to use it for a new project using Ionic. Do you think detox could handle ionic E2E tests on simulator ?

I hope it could be done, specially because there are sources for iOS application when we build the ionic app.

If it's possible could you add a working example ?
If it's not possible, do you think detox could be compatible with ionic in the future ?

Thank you !

**Comment by LeoNatan** [comment]
What does Ionic output? A webview?

**Comment by iGitScor** [comment]
After investigation, I think so !
Here screenshots of parts of the Xcode project navigator view:
<img width="240" alt="capture d ecran 2018-01-30 a 19 50 05" src="https://user-images.githubusercontent.com/2276944/35584984-f7550c20-05f6-11e8-9d71-5a1e96279824.png">
<img width="224" alt="capture d ecran 2018-01-30 a 19 50 41" src="https://user-images.githubusercontent.com/2276944/35584985-f782825e-05f6-11e8-88e6-e666a91263c7.png">

**Comment by rotemmiz** [comment]
Ionic is Cordova, It's a webview. Detox does not support webviews currently.

**Comment by LeoNatan** [comment]
Yes, in that case, unfortunately, this is not on our plan. It is a completely different platform to support and we have neither the expertise or time or will to look at this problem. Sorry.

**Comment by iGitScor** [comment]
Ok, thank you for the answer and good luck for Detox next releases 💯
