### ISSUE TITLE
Command line arg to keep simulator open

### ISSUE THREAD

**Issue by d4vidi** [wix/detox#55]
Need to see where it stopped :-/

**Comment by LeoNatan** [comment]
I will add a comment for this on issue #56, as this should be part of the eventual CLI tools.

**Comment by rotemmiz** [comment]
Actually, a screenshot is a better idea. Should be saved as a build artifact if the build breaks.

**Comment by LeoNatan** [comment]
fbsimctl supports recording a video.

**Comment by rotemmiz** [comment]
perfect!
