### ISSUE TITLE
How to disable the error log in console when the testcase is failed on Android

### ISSUE THREAD

**Issue by linhnh123** [wix/detox#550]
Hello,
I don't want to view the error log when the testcase is failed, because it's show out very much, and I have to take a long time to scroll up and find the exactly error. As you can see:

<img width="896" alt="screen shot 2018-02-01 at 2 28 59 pm" src="https://user-images.githubusercontent.com/13411581/35666547-1131d620-075d-11e8-9c70-7265050422d5.png">

I'm using detox v6.0.4
How to do that, thank you.

**Comment by LeoNatan** [comment]
The error output here displays the view hierarchy your app was displaying when attempted to match an element, This will not change in the foreseeable future.
