### ISSUE TITLE
Add Support for Device Shake Action

### ISSUE THREAD

**Issue by grabbou** [wix/detox#551]
Hey,

I am working on https://github.com/facebook/react-native/pull/17806 where I am attempting to remove Appium and start using Detox for internal tests of React Native as well as the release process.

The problem I am facing right now is lack of the ability to open up Dev Settings (in order to test whether Chrome Debugger or Live Reload is working).

I've done some research and found that one of the ways to do it would be to expose an action on `device`, called `toggleDevSettings` that could execute `show`(https://github.com/facebook/react-native/blob/e8eec24706e792314ee574bbf7f7c0066c4f3a7a/React/DevSupport/RCTDevMenu.m#L292) method which is exposed on `RCTDevMenu` native module.

Alternatively, we could go towards React Native agnostic solution and implement the ability to trigger shake gesture.

I am open to collaborating on this feature as I need it to move my PR forward.

**Comment by grabbou** [comment]
cc: @rotemmiz as we discussed this on Slack

**Comment by LeoNatan** [comment]
I think a `device.shake()` API is the correct way to go. iOS simulator has this option in the menu, so it could be possible to use that somehow. If not, it should be possible to implement using some Earl Grey trick or private API directly.

**Comment by LeoNatan** [comment]
Added support for shake in iOS native.
Need JS support from mr. RMM @rotemmiz

**Comment by grabbou** [comment]
Thanks @LeoNatan, any ideas when Android support might land?

**Comment by grabbou** [comment]
How would you attempt using that feature w/o a JS interface? Any workaround I can do to use it right now?

**Comment by LeoNatan** [comment]
I cannot say when Android support might be added. 

Regarding a workaround, I am not sure. The shake event that triggers the menu is generated from native. You could drill down in the JS API and somehow call that action directly, but that like implementing the actual JS API (if you do, please submit PR 😄).

**Comment by grabbou** [comment]
Haha, okay, I'll try to play around with it and I'll get you some details
back.

Is there anyone I can ping re: Android?

**Comment by rotemmiz** [comment]
Android, me.

**Comment by LeoNatan** [comment]
@rotemmiz According to [this](https://stackoverflow.com/questions/32914665/how-do-i-shake-an-android-device-within-the-android-emulator-to-bring-up-the-d), you can fake it with adb.

**Comment by rotemmiz** [comment]
`adb shell input keyevent 82` is not exactly shake, it's keycode for menu button. It works, but this is not "shake"

**Comment by LeoNatan** [comment]
True, it would be added as a separate action.

**Comment by LeoNatan** [comment]
For shake, I see some need to telnet into the simulator and change the accelerator. 😓😂

**Comment by grabbou** [comment]
If the name of method was open dev tools, then you could use the key press
as Android implementation j guess 👍

**Comment by rotemmiz** [comment]
We already have a pretty good telnet client, not gonna be very hard I hope.

Android has no shake property, it's not a thing in the official API... There is one good library that does that. 
They do though support mocking every hardware/software key available (KEYCODE_MENU, etc). Not everything is harder, but if we impose iOS APIs on Android that's what we get.

**Comment by LeoNatan** [comment]
So why not keep shake to iOS and menu for Android?

**Comment by rotemmiz** [comment]
Not the same thing, it will not work the same outside of react native

**Comment by LeoNatan** [comment]
But seems to me like those are two separate functionalities unrelated to each other. We could add shake now for iOS and menu only for Android (no menu on iOS), and then add shake later for Android (when necessary).

**Comment by rotemmiz** [comment]
I'm starting to think we need another abstraction layer, for react native related operations, that will use different driver APIs under the hood
😕

**Comment by LeoNatan** [comment]
I disagree. Detox is React Native neutral, and should remain that way.

**Comment by LeoNatan** [comment]
(`reloadReactNative` is also problematic)

**Comment by LeoNatan** [comment]
Further, dev menu is a debug feature, so it makes even less sense in adding it as official API for device.

**Comment by rotemmiz** [comment]
That's exactly my point, we don't want to add per platform react native specific behaviors, so we create a dedicated API for react native apps (reloadReactNaive will be added there as well), and native apps will not have these options as part of the API.
`reloadReactNative` or `openDevMenu` are only RN options.

Native APIs will include the available native commands for each platform.

I will try to draft something

**Comment by LeoNatan** [comment]
Other than this narrow use-case of testing the tools themselves, why should the dev menu be exposed? 
I dislike adding support for the kitchen sink.
On iOS, support for shake is something that is useful beyond dev menu. It's a used gesture for undo, and is often used. So adding support for that has merit. So is the menu button for Android. I just don't see it for RN.

**Comment by LeoNatan** [comment]
With these two APIs, for this narrow use-case, a workaround can be added to ask `if(iOS) shake() else menu()`.

**Comment by Salakar** [comment]
Not sure if this is the best place to chime in but I'd also like to have the ability to be able to control the Dev Settings in RN through detox - at least the ability to toggle remote debugging and to reload react native.

@LeoNatan I have a bit of a weirder use case here though than just tooling tests: whilst detox is great for controlling all things device/UI (which i'm internally still using) I needed a way of testing native modules e2e without extensive tests in native obj-c/java code or without having the tests in-app. 

![image](https://user-images.githubusercontent.com/5347038/36782495-0c82fc48-1c71-11e8-9cdc-b6001355215b.png)

As you can see in the above screenshot, this is just standard Node.js + mocha tests but I can now require native modules and use them fully - no mocking, bundle runs in-process automatically (as long as remote debugging is enabled and I have the ability to reload react native - this is where detox comes in). 

I plan to bundle this at some point into an NPM package to ease native module testing as there's only a handful of native modules doing testing well/extensively that I could see - I see this as a first step towards simplifying the testing process for native module developers.

> @rotemmiz: That's exactly my point, we don't want to add per platform react native specific behaviors, so we create a dedicated API for react native apps (reloadReactNaive will be added there as well), and native apps will not have these options as part of the API.
reloadReactNative or openDevMenu are only RN options.

Agree on this.

**Comment by LeoNatan** [comment]
@Salakar I think we should move the discussion to #207. I would like to hear more how you have implemented your solution and perhaps discuss how to add the functionality in Detox.

**Comment by LeoNatan** [comment]
Device shake has landed for iOS.

**Comment by grabbou** [comment]
Great. Been waiting for this for so long! Thanks, looks like it's time to
prototype some tests this week.
