### ISSUE TITLE
Create a CLI module

### ISSUE THREAD

**Issue by DanielZlotin** [wix/detox#56]
Will make working with the project a breeze. Instead of defining stuff in the package.json, pass arguments to the cli, for example: `detox build ios/MyApp.xcproj MyAppDev`, `detox run e2e/`,
then the cli automatically figures out what and where to build.
Then, in the user's package.json, he can define those scripts once like so `"e2e": "detox build ios/MyApp.xcproj MyAppDev && detox run e2e/"`, and forgo all other installation and configuration coupling to the build path

**Comment by LeoNatan** [comment]
As per #55, we should have an argument to close or not close the simulator.

**Comment by rotemmiz** [comment]
detox-cli is a part of detox 5 release.
