### ISSUE TITLE
Add flow-typed libdef for detox

### ISSUE THREAD

**Issue by coderjonny** [wix/Detox#565]
Thanks for exporting the globals! @trofima

#### Description
Have a flowTyped library definition so I can use detox on projects using `flow`.

#### Steps to Reproduce
Turn on flow for detox e2e tests.

Please review: 
https://github.com/flowtype/flow-typed/pull/1824

**Comment by rotemmiz** [comment]
PRs are welcome :)

**Comment by LeoNatan** [comment]
Out of scope for the project. If someone wants to do this, great! But we will not be able to accept it here. It should be part of a community project.
