### ISSUE TITLE
Swipe action starts in unexpected position

### ISSUE THREAD

**Issue by yogevbd** [wix/detox#566]
I'm trying to open side menu on android and can't get the swipe action to start in x=0 point.

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/10794586/35924947-1b76eb50-0c2d-11e8-9cea-4842d3f72db0.gif)

**Comment by guyca** [comment]
Still relevant

**Comment by guyca** [comment]
IIRC, We're matching against the root view, not against an offscreen view.

**Comment by rotemmiz** [comment]
Espresso will only interact with the matched view, the root view is not swipeable, therefore nothing will move when trying to swipe it.

**Comment by guyca** [comment]
Alright, how do you suggest we simulate swiping on the screen to open a side menu?

**Comment by rotemmiz** [comment]
Try matching the view you want to interact with. If it doesn't work, we may need to play a bit with espresso's assertions on the view's visibility (only interact when view is 75% visible)
