### ISSUE TITLE
Failed to await device.setOrientation() on android

### ISSUE THREAD

**Issue by yogevbd** [wix/Detox#567]
Look like a synchronization issue. Reproducing when trying to setOrientation multiple times.

**Comment by rotemmiz** [comment]
Doesn't turning animations off solve it?

**Comment by yogevbd** [comment]
No it doesn't :(

**Comment by yogevbd** [comment]
```js
await device.setOrientation('landscape');
await expect(element(by.id(testIDs.LANDSCAPE_ELEMENT))).toBeVisible();
(async () => { // Somehow invoking this part inside an anonymous function fix this test 
  await device.setOrientation('portrait');
  await expect(element(by.id(testIDs.PORTRAIT_ELEMENT))).toBeVisible();
})
```

Maybe this will give you a clue about what happening..

**Comment by Rob117** [comment]
@yogevbd 
Hey, just a heads up, I tried using an anonymous function in one of my tests and I found out that it simply ignores the code inside the function and passes the relevant test, so this might not actually be passing your test. The relevant code I ran was:

`async () => {
      await expect(element(by.text('Helvlo!!!'))).toExist();
    };`

It simply passes the test, even though no such text exists on the screen.

**Comment by LeoNatan** [comment]
Closing old issues. If this is still relevant, please open a new issue with the relevant logs from a modern version of Detox. Thanks.
