### ISSUE TITLE
Detox configuration should allow ability to specify app apk path and androidTest apk path

### ISSUE THREAD

**Issue by hoda0013** [wix/Detox#571]
#### Description
Currently Detox configuration asks for the file location of the apk file to be tested. It then uses convention to determine where the androidTest apk is located based on the filename it finds at the specified location. It would be nice to allow both paths to be specified in case the developer doesn't want to follow the file naming / hierarchy conventions.

**Comment by rotemmiz** [comment]
I agree. A PR is most welcome!

**Comment by savelichalex** [comment]
Yeah, that really frustrating. I just have started to work with `detox` and `apk` for `androidTest` is not that cli is expecting, though I followed docs

**Comment by savelichalex** [comment]
I added new property to configuration in this [commit](https://github.com/savelichalex/detox/commit/d97883a9e9a81d95f4be610b79bced6d17b76b72). What do you think about it? Is it ready for PR or I need to add some sort of tests?

**Comment by asztal** [comment]
Should be resolved by #1007 (not yet in a release though)

**Comment by rotemmiz** [comment]
Closed with #1007. Out with detox@9.0.7
