### ISSUE TITLE
Find element by text doesn't function with minimal project on latest version of RN and detox

### ISSUE THREAD

**Issue by Rob117** [wix/detox#572]
#### Description

I have a very, very simple project set up with one file, using the detox getting started guide. While searching by element id, I have no problem finding the element and all tests pass.

However, the problem is that searching by text returns an error saying that the UI element could not be found. I am not using any extra libraries or toolkits at all, and I have tried to run the tests with both Jest and Mocha using detox test.

Please find very simple project attached:

[Project](https://github.com/Rob117/detox-text-issue)

Main File
```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View, Button } from 'react-native';

type Props = {};

export default class App extends Component<Props> {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <View testID="welcome" style={styles.container}>
        <Text style={styles.welcome}>Welcome to React Native!</Text>
        <Text style={styles.instructions}>
          This is a React Native snapshot test.
        </Text>
        <Button title="Say Hello" color="#814584" testID="hello_button" />
        <Button title="To The World" color="#814584" testID="world_button" />
        <Text>Hello!!!</Text>
        <Text>World!!!</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF'
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5
  }
});
```

* Detox: 7.1.0
* Detox-server: 7.0.0
* Detox-cli: 1.1.0-alpha.0449f580
* Node: 9.4.0
* Device: iPhone 7 Emulator
* Xcode: 9.2
* macOS:  10.12.6
* react-native-cli: 2.0.1
* react-native: 0.53.0

I ran the tests with loglevel set to verbose. The output was huge, however, so I attached it in a gist.

https://gist.github.com/Rob117/57defa8a9c166bba2e2199d194a62ee1

If there is any additional information I could provide to be useful, or something obvious that I am overlooking here, please let me know.

Thank you.

**Comment by LeoNatan** [comment]
Thanks guys, we'll look at this issue soon.

**Comment by kumarpatel** [comment]
Same problem. 
Detox: 7.1.0
react-native: 0.53.0

It does work when react-native is downgraded to 0.50. But this isn't an option for us as there are critical bug fixes between RN .50 and .53

Any ideas as to where problem is? what file?

**Comment by chadlwilson** [comment]
@kumarpatel Detox 7.2.0 is working fine on RN 0.52.3, so you don't have to go as far back as 0.50 to still use Detox.

**Comment by LeoNatan** [comment]
I guess something changed with RN 0.53.0
I haven't yet had opportunity to debug.

**Comment by LeoNatan** [comment]
Fixed

**Comment by chadlwilson** [comment]
Great, thanks a lot @LeoNatan !

**Comment by maxkomarychev** [comment]
@LeoNatan thanks for the fix!
do you plan to publish an update to npm anytime soon?
It's not possible to install detox as`detox@wix/detox#master` since it's monorepo managed with lerna is it?

**Comment by LeoNatan** [comment]
Soon. There are still issues in CI with my fix, which I am working on right now.

**Comment by Rob117** [comment]
You are awesome, thank you so much!
