### ISSUE TITLE
tandalone `Standalone `detox-cli` npm package hasn't been updated to address issues with spaces in directories.

### ISSUE THREAD

**Issue by kylethebaker** [wix/detox#573]
#### Description
The standalone `detox-cli` npm package hasn't been updated to address issues with spaces in directories.

This is commit that fixes the issue in the detox repo, but the standalone package hosted on npm still has this issue: https://github.com/wix/detox/commit/f28d8ab3c96cf95a7f604b663a257a9fa254b23d

#### Steps to Reproduce
If you install detox-cli globally as recommended in the installation instructions (`npm install -g detox-cli`) and try to run detox from a project directory that contains spaces you will get a message saying `detox is not installed in this directory` (since it stops at the first space).

You can also check `/usr/local/bin/detox` and see that it is missing the quotes around `$DETOX_PACKAGE_JSON_PATH`

**Comment by rotemmiz** [comment]
Not sure why it wasn't updated automatically when change was introduced, just manually updated detox-cli to v7.0.0. Please see if this resolves your issue .

**Comment by kylethebaker** [comment]
Thanks, the updated package fixes this issue
