### ISSUE TITLE
The contributing guide is out of date

### ISSUE THREAD

**Issue by Rob117** [wix/detox#576]
Reference: [Guide](https://github.com/wix/detox/blob/master/docs/Guide.Contributing.md)

The problem:

I filed a previous issue, #572, and thought that I could at least dig around in the code and see what I could do. Unfortunately, I ran into some issues with the contributing guide that stopped me from investigating.

I had a minor issue with the step `npm run build` because it told me `build` wasn't found. No problem, I skipped right to `npm run build:ios`, but I then got the following error (pasted into gist for space efficiency):

[Error Log](https://gist.github.com/Rob117/1f31426b86b3a8b61a0c3a07ca073cf5)

#### Steps to Reproduce

Clone the project. Follow the contribution manual step by step. Notice that you cannot build the project.

* Detox: Master branch
* Node: 9.4.0
* Xcode:  9.2
* macOS:  10.12.6

**Comment by Rob117** [comment]
Not stale?

**Comment by Rob117** [comment]
This issue has been up for a few months, I'm going to close it.

**Comment by rotemmiz** [comment]
Went over the contribution guide again. The issue you had is related to compiling react native from source (added a section about that as well).
Changed added here https://github.com/wix/detox/commit/bd11fc58e543cc4182dfaf86de10c985c7d271da
