### ISSUE TITLE
Provide mechanism to pass test match patterns runner-agnostic via Detox CLI

### ISSUE THREAD

**Issue by chadlwilson** [wix/Detox#588]
#### Description
It'd be great to have way to pass test match patterns via the `detox test` CLI to run say a single test in a suite. So that you can do `yarn detox test --testMatch=e2e/**/blahSingleTest.js` when a single test is failing and you don't want to run the whole suite.

We use Detox with Jest, and have a way to work around this; but it involves launching Jest directly; pointing it to the same Jest configuration as Detox is using and doesn't seem to work when we have multiple Detox configurations as Detox doesn't have sufficient detail to know which configuration to pick.

`package.json`

```
  "detox": {
    "test-runner": "jest",
    "runner-config": "e2e/config.json",
    "configurations": {
      "ios.sim.debug": {
        "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/blah.app",
        "type": "ios.simulator",
        "name": "iPad Pro (10.5-inch), iOS 10.3"
      },
      "ios.sim.release": {
        "binaryPath": "ios/build/Build/Products/Release-iphonesimulator/blah.app",
        "type": "ios.simulator",
        "name": "iPad Pro (10.5-inch), iOS 10.3"
      }
    }
  },
```

Jest `e2e/config.json`
```
{
  "setupTestFrameworkScriptFile": "./setup-tests.js",
  "testMatch": [
    "**/tests/**/*/*.test.js"
  ],
  "testResultsProcessor": "../node_modules/jest-bamboo-formatter",
  "forceExit": true,
  "verbose": true
}
```

If there is another way to do this, would love to know!

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 7.1.0
* Node: 8.9.x
* Device: N/A
* Xcode: 8.2
* macOS: 10.13.3 High Sierra

**Comment by chadlwilson** [comment]
A workaround one of my team put in place (may be useful to others trying to solve the specific issue here in support picking the right configuration) was to export `configuration` when running Jest which also seems to work with Detox:

`package.json`
```
"test:e2e:one": "export configuration=ios.sim.debug && yarn jest --runInBand --config=e2e/config.json --testMatch=",
```

Seems not documented [here](https://github.com/wix/detox/blob/master/docs/APIRef.Configuration.md) but works all the same!

**Comment by noomorph** [comment]
@chadlwilson, I think it is possible already in `detox@12.4.0`, but I might be wrong in a few things (e.g. nowadays, passing custom `--testNamePattern` is still problematic), but you can do the following since 12.1.0:

`npx detox test -c ios.sim.debug e2e/device/*.test.js`

If your shell expands the glob, then all those file names will be passed through, to Jest or Mocha.

**Comment by noomorph** [comment]
@chadlwilson , does that address your issue?

**Comment by chadlwilson** [comment]
@noomorph That looks quite possible. I'm not actively working with RN at the moment so don't have a setup to verify this, but it does look like #1132 and #1109 have resolved this based on my reading.

**Comment by noomorph** [comment]
Thanks, Chad. If you'll see if something is broken about that, please file a new issue. Right now I'm closing this one. Good luck with your projects!
