### ISSUE TITLE
Remote testing

### ISSUE THREAD

**Issue by JAStanton** [wix/detox#59]
Do you guys have this working remotely in some sort of continuous integration environment? (i.e. CircleCi)

**Comment by LeoNatan** [comment]
Hi, we have successfully run tests on a projects in TravisCI. We have not tested on CircleCI yet, but it should work as long as they have feature parity in this tegard.

**Comment by LeoNatan** [comment]
See .travis.yml here:
https://github.com/wix/detox/blob/travist_testing/.travis.yml

And build script here:
https://github.com/wix/detox/blob/travist_testing/scripts/travis.sh
