### ISSUE TITLE
Mock Android notifications

### ISSUE THREAD

**Issue by coffenbacher** [wix/Detox#592]
According to [Mocking User Notifications and URLs](https://github.com/wix/detox/wiki/Mocking-User-Notifications-and-URLs), 
```
Detox supports mocking user notifications for iOS apps.
```

Are there plans to support this for Android? This is an important feature for my team. Thanks!

**Comment by LeoNatan** [comment]
We just discussed this today.
Yes, we have plans, soon, but I cannot say beyond that. There are some challenges we have to overcome.

**Comment by LeoNatan** [comment]
@rotemmiz

**Comment by LeoNatan** [comment]
Closing this issue in favor of #1192
