### ISSUE TITLE
Running Android tests on Linux

### ISSUE THREAD

**Issue by chrmod** [wix/detox#594]
#### Description

Running Detox on Linux fails before emulator is able to start and install the app. 

#### Steps to Reproduce

Try to start `detox test` for any of example projects on a Linux machine. We have problems doing that and have to update `demo-react-native` to do that https://github.com/wix/detox/pull/593

On MacOS the build and tests works correctly and all tests are green.

On Linux, same code base, start the emulator, and runs the tests, but tests start to fast and fail. 
(When emulator finally finishes the initialization, the apk is not installed)

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 7.1.0
* Node: 8.9.4
* Device: Android Emulator 22/25/26  x86/arm 
* Linux: 4.13

#### Device and verbose Detox logs

```
node_modules/.bin/jest e2e --config=e2e/config.json --runInBand
 server listening on localhost:33293...
 onOpen [object Object]
 send: {"type":"login","params":{"sessionId":"f01bf5bd-4da5-61d2-39ff-27239855f5ef","r
ole":"tester"},"messageId":0}
 onMessage: {"type":"loginSuccess","params":{"sessionId":"f01bf5bd-4da5-61d2-39ff-2723
9855f5ef","role":"tester"},"messageId":0}
  rbx
 : /home/chrmod/Android/Sdk/tools/emulator -list-avds --verbose
 Nexus_5X_API_22
 Nexus_5X_API_24
 Nexus_5X_API_26
 Pixel_XL_API_26
 : stdout:
 -verbose -gpu host -no-audio @Nexus_5X_API_22
 : /home/chrmod/Android/Sdk/platform-tools/adb  devices
 List of devices attached
 emulator-5554  device
 : stdout:
 : stdout:
 FAIL  e2e/firstTest.spec.js
  Example
    ✕ should have urlbar (3ms)
  ● Example › should have urlbar
    response not received
      at setTimeout (../node_modules/telnet-client/lib/index.js:150:47)
      at Timeout.callback [as _onTimeout] (../node_modules/jsdom/lib/jsdom/browser/Win
dow.js:633:19)
```

**Comment by chrmod** [comment]
PS. are you aware of any project tested of Detox running on Travis CI? I would assume that if it runs on Travis it will work on most Linux boxes. 
I'm willing to help with updating example projects accordingly and Travis CI setup.

**Comment by rotemmiz** [comment]
Does your CI support x86 emulators? Are you using x86 or ARM emulators ?
ARM emulators are terribly slow, and you might get this 3 minute timeout just because it takes it super long time to init the ARM emulator. Try a (much) higher timeout and see.

Re x86 emulators, Travis currently does not support that, this is the reason we don't run Android e2e in CI... We are working on creating a proprietary CI solution with nested virtualization support for our open source projects, just so we can run Android e2e tests.

**Comment by chrmod** [comment]
@rotemmiz this report is about running on developer station not in CI. So yes, I've tested with x86 emulator and with ARM one. In both cases tests finish to, before emulator even finish loading android. So app in not even installed.

This issue is potentially related: https://github.com/wix/detox/issues/524 - though I was able to run tests on MacOS, only Linux is a problem.
