### ISSUE TITLE
Add detox preStart script in config json

### ISSUE THREAD

**Issue by yedidyak** [wix/detox#60]
For example:

```json
"detox": {
   **"beforeStart": "npm run fake-server",**
    "session": {
      "server": "ws://localhost:8099",
      "sessionId": "abc"
    },
    "ios-simulator": {
      "app": "ios/DerivedData/WixOneApp/Build/Products/Debug-iphonesimulator/ABC.app",
      "device": "iPhone 6s, iOS 10.1"
    }
  }
```

**Comment by LeoNatan** [comment]
You can achieve this with a script already. @rotemmiz Do you think we should implement?

**Comment by rotemmiz** [comment]
This may be a good idea for running short lived tasks, but running servers is a pretty complex thing to deal with. We would need to save the forked process id and make sure it is killed when Detox dies. Starting to listen on signals and creating a complex mechanism for cleanup is not something I think Detox should be focused around.

Instead, I suggest that running mock servers (Node servers) will be a part of your test case, as such: https://github.com/wix/detox/blob/master/detox/test/e2e/m-network.js

**Comment by guyca** [comment]
@rotemmiz Can we use a similar approach to deal with disabling animations on android emulator?
Would be handy to be able to execute some script before tests run **and** after the emulator is running so I can setup my environment.

**Comment by AFGhazy** [comment]
Is this resolved yet ?

**Comment by rotemmiz** [comment]
The thing @guyca mentioned was resolved here: https://github.com/wix/react-native-navigation/blob/v2/e2e/init.js

Regarding the preStart script, I find it to be a confusing and a bad pattern. If you need something to be initiated or controlled, sovit from inside the test script.
