### ISSUE TITLE
Husky hooks bugged out when attempting a commit

### ISSUE THREAD

**Issue by LeoNatan** [wix/detox#606]
Had to delete all hooks for the commit to succeed.
The commit in question: 
https://github.com/wix/detox/pull/604/commits/6508b9867c0697b3c4d21688d8f583cbb1ce8c17

I see husky was added in Generation to run lint before committing. I am not sure whether my problem is due to husky or our own precommit hook, but either way, I am not sure this is the right place to run lint. 

Regarding husky, since git hooks are considered personal and installed by developer, I do not like type of "devious" injection of code—I felt "violated" 🙂. We can run the lint on CI.

**Comment by LeoNatan** [comment]
It is possible to have a script that installs some hooks that can then, by developer's choice, install these hooks. Similar to how `bootstrap.sh` works, maybe something for the hooks. But if the hooks can cause issues, I think they shouldn't run by default.

**Comment by LeoNatan** [comment]
Thanks

**Comment by LeoNatan** [comment]
Ping
@DanielMSchmidt What will happen if I remove it from package.json inside generation?

**Comment by DanielMSchmidt** [comment]
You will gain the possibility to check in unformatted code I guess

**Comment by LeoNatan** [comment]
OK, thanks
