### ISSUE TITLE
Introduce complementary UiAutomator API on Android  

### ISSUE THREAD

**Issue by guyca** [wix/Detox#607]
Motivation:
While Espresso is sufficient for most use cases, interacting with UI outside of the application is a common requirement.
Work has already been done in this regard [here](https://github.com/wix/detox/blob/master/detox/android/detox/src/main/java/com/wix/detox/uiautomator/UiAutomator.java)

**Comment by rotemmiz** [comment]
It can be very useful to generate UIAutomator's js API. @danielmschmidt

https://developer.android.com/reference/android/support/test/uiautomator/UiDevice.html

**Comment by d4vidi** [comment]
@omerwin please associated this ticket with your PR 🙏
