### ISSUE TITLE
Script to add scheme adds deployment target 7.0

### ISSUE THREAD

**Issue by yedidyak** [wix/detox#61]
Which is too low.

**Comment by LeoNatan** [comment]
Better option is to just warn the user if their deployment target is too low. I think requiring 8.0 deployment target and above is very reasonable.

**Comment by LeoNatan** [comment]
I will add a fix in `deploy_detox.rb`.

**Comment by LeoNatan** [comment]
No longer relevant. Detox is injected in runtime, and should work as long as officially iOS >= 9.0 and unofficially >= 8.0.
