### ISSUE TITLE
detox is not installed in this directory

### ISSUE THREAD

**Issue by thenewt15** [wix/detox#612]
Installed detox globally.
`npm install -g detox-cli`

Got this input in my terminal upon successful download.
```
/usr/local/bin/detox -> /usr/local/lib/node_modules/detox-cli/cli.sh
+ detox-cli@7.0.0
updated 1 package in 0.761s
```

Ran `detox -h`, and then got the following message.
> detox is not installed in this directory

I expected to see a list of available commands, per the documentation.

**Comment by LeoNatan** [comment]
Please read the documentation.

**Comment by thenewt15** [comment]
The docs say I should see a list of available commands. Instead I get an error message. 

Are the docs wrong, or am I just misunderstanding them?
