### ISSUE TITLE
reloadReactNative crashes the app

### ISSUE THREAD

**Issue by gameunite** [wix/detox#617]
#### Description
I just followed the getting started guide and put it on my app and it crashed here:

`1) "before each" hook for "should have password field"`

#### Steps to Reproduce
- Install and setup redux-persist and react-native-navigation
- Call the app like this
```
persistStore(store, null, () => {
  registerScreens(store, Provider);

  Storage.get('access_token').then((accessToken) => {
    if (accessToken) {
      store.dispatch(authenticated());
    } else {
      store.dispatch(appInitialized());
    }
  });
});
```
- Run test and call `await device.reloadReactNative();`

If I remove the reloadReactNative, it works perfectly.
If I remove the redux-persist, it works perfectly.

Is there any workaround for this? I need both of them

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 7.1.0
* Node: 9.5
* Device: iPhone 8 Plus
* Xcode: 9.2
* macOS: 10.13.3

#### Device and verbose Detox logs
`
Error: the string "Signal 11 was raised\n(\n\t0   Detox                               0x0000000109046ecf _ZL16__DTXHandleCrashP11NSExceptionP8NSNumberP8NSString + 469\n\t1   Detox                               0x0000000109046c7b _ZL17__DTXHandleSignali + 54\n\t2   libsystem_platform.dylib            0x000000010fd6ef5a _sigtramp + 26\n\t3   ???                                 0x0000000000000000 0x0 + 0\n\t4                               0x0000000108aeaf29 _ZN8facebook5react8Instance20loadScriptFromStringENSt3__110unique_ptrIKNS0_11JSBigStringENS2_14default_deleteIS5_EEEENS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEb + 2809\n\t5                               0x00000001088c8364 __51-[RCTCxxBridge executeApplicationScript:url:async:]_block_invoke + 7204\n\t6                                0x00000001088d372c _ZNSt3__128__invoke_void_return_wrapperIvE6__callIJRU8__strongU13block_pointerFvvEEEEvDpOT_ + 60\n\t7                                0x00000001088d3569 _ZNSt3__110__function6__funcIU8__strongU13block_pointerFvvENS_9allocatorIS4_EES2_EclEv + 41\n\t8                                0x000000010892dc7b _ZNKSt3__18functionIFvvEEclEv + 123\n\t9                                0x000000010892d968 _ZN8facebook5react17tryAndReturnErrorERKNSt3__18functionIFvvEEE + 24\n\t10                               0x00000001088b50b0 -[RCTCxxBridge _tryAndHandleError:] + 80\n\t11                               0x00000001088c666e -[RCTCxxBridge executeApplicationScript:url:async:] + 270\n\t12                               0x00000001088c5fe5 -[RCTCxxBridge enqueueApplicationScript:url:onComplete:] + 437\n\t13                               0x00000001088bf8dc -[RCTCxxBridge executeSourceCode:sync:] + 540\n\t14                               0x00000001088b81f4 __21-[RCTCxxBridge start]_block_invoke.213 + 164\n\t15  libdispatch.dylib                   0x000000010f8bc177 _dispatch_call_block_and_release + 12\n\t16  libdispatch.dylib                   0x000000010f8bd1ba _dispatch_client_callout + 8\n\t17  libdispatch.dylib                   0x000000010f8c7b29 _dispatch_root_queue_drain + 993\n\t18  libdispatch.dylib                   0x000000010f8c76ea _dispatch_worker_thread3 + 119\n\t19  libsystem_pthread.dylib             0x000000010fd801ca _pthread_wqthread + 1387\n\t20  libsystem_pthread.dylib             0x000000010fd7fc4d start_wqthread + 13\n)" was thrown, throw an Error :)
`

**Comment by rotemmiz** [comment]
What version of react native are you using ? 
Is this debug or release build ?

**Comment by gameunite** [comment]
@rotemmiz I'm using react-native 0.54.0. I just tried it on Release build and it works fine. So it just crashes on Debug build.

Btw, It has to have this. Because it works fine in the first run but failed on the second.
```
beforeEach(async () => {
     await device.reloadReactNative();
  })
```

**Comment by LeoNatan** [comment]
Could you please check with a completely new project of this reproduces for you?

**Comment by GetSource1234** [comment]
Have the same issue (RN 0.51).

**Comment by LeoNatan** [comment]
@GetSource1234 Please open a new issue and follow the template to provide all relevant information.

**Comment by wildseansy** [comment]
I'm having the same issue.  Will create new issue with relevant info.

**Comment by markhu** [comment]
I don't think @wildseansy 's issue #691 is similar, since it isn't about the infamous `Signal 11 was raised` issue.

    Signal 11 was raised
    ( 0   Detox                               0x000000010589b4ff _ZL16__DTXHandleCrashP11NSExceptionP8NSNumberP8NSString + 469
    1   Detox                               0x000000010589b2ab _ZL17__DTXHandleSignali + 54
    2   libsystem_platform.dylib            0x000000010d235b3a _sigtramp + 26
    3   ???                                 0x000070000d044540 0x0 + 123145520694592
    ... )
