### ISSUE TITLE
detox clean-framework-cache && detox build-framework-cache broken for internal development

### ISSUE THREAD

**Issue by LeoNatan** [wix/detox#619]
I make changes to the native code, run the command in the title in the test project directory and something is being built, but not what I expect (my most recent changes).

This is blocking me from doing any native development for Detox.

**Comment by LeoNatan** [comment]
This is blocking at least #615

**Comment by LeoNatan** [comment]
@rotemmiz

**Comment by rotemmiz** [comment]
This is handled in #621
