### ISSUE TITLE
Support es6 (import, async await etc)

### ISSUE THREAD

**Issue by yedidyak** [wix/detox#62]

**Comment by rotemmiz** [comment]
Supporting import nativity in node (JS V8 engine to be precise) is probably never going to happen, just use require instead.
Supporting async await is coming really soon, already supported in V8 v5.5 (node 7.3 still uses V8 5.4, hopefully in the next release).

**Comment by rotemmiz** [comment]
@yedidyak if you use node v7.1.0 and up you can add `--harmony_async_await` to your `mocha.opts` and it should do the `async await` magic.

**Comment by rotemmiz** [comment]
new async await api is no in master, check out the test project. upcoming detox version (5.0.0) breaks the api completely in favor of async await. 
Use node 7.6.0 and never babelify again.

**Comment by tackanoway35** [comment]
Why can't i use import syntax?

**Comment by rotemmiz** [comment]
AFAIK it is still not supported natively in node: https://nodejs.org/api/esm.html#esm_unsupported

You can use import if you Babel your tests.

**Comment by lucassus** [comment]
Migrate your specs from `mocha` to `jest` and you'll be set ;)
It seems that `jest` has build-in support for es6 imports
