### ISSUE TITLE
Android tap action fails silently

### ISSUE THREAD

**Issue by maartenschumacher** [wix/detox#620]
#### Description

I'm trying to get my tests running on android, getting stuck on an issue where a tap doesn't have an effect on the emulator, making the next expectation fail. What's strange is that I can't reproduce the issue when I only run the affected test suite (with mocha `describe.only`). The bug only happens when I run all the test suites. I reload RN between each suite.

Since the unresponsive element triggers a navigation transition, I thought the issue might be the synchronization not waiting long enough, but disabling it doesn't help. Only thing that worked so far is extending the `whileElement` api with a tap action, so that I can keep tapping the button until the next screen is visible.

So my questions are
1. Would you accept adding `tap` on `whileElement`?
2. How can I debug it to get a better understanding of why the tap silently fails?

#### Steps to Reproduce

Since I can only reproduce the bug as part of a bigger test suite making a demo project would be very difficult.

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 7.1.0
* React Native: 0.52.0
* Node: 9.3.0
* Device: Nexus_6_API_23
* Xcode: N/A
* macOS: 10.13.3

#### Device and verbose Detox logs

[Detox verbose log.txt](https://github.com/wix/detox/files/1802830/Log.at.2018-03-12.1-04-40.pm.txt)
[logcat.txt](https://github.com/wix/detox/files/1802833/logcat.txt)

**Comment by rotemmiz** [comment]
We have sync issues with Detox Android on RN>=51.
You can follow #608 for updates.

**Comment by LeoNatan** [comment]
Closing this issue for now. Feel free to reopen if issue still reproduces after #608 is fixed
