### ISSUE TITLE
android detox issue with jest + emulator 

### ISSUE THREAD

**Issue by YahyaQandel** [wix/detox#624]
Hello ,
I have a problem that consumed more than 4 hours .

after finishing detox android configuration with gradle and finally it builds successfully , i tried to run the tests with detox test .. but it fails with this error on the snapshot 

**Timeout - Async callback was not invoked within the 30000ms timeout specified by jest.setTimeout.**

i have tried using multiple emulator versions ( gennymotion , android studio ) but fails .

![screenshot from 2018-03-14 21-06-30](https://user-images.githubusercontent.com/8913666/37425338-a842f164-27cb-11e8-8b39-dbaac9147bd8.png)

here is my [repo](https://github.com/YahyaQandel/dtxexmple.git) that i'm working on 

Please Advice .

**Comment by rotemmiz** [comment]
Your project uses RN v54, which currently is not supported, we are trying to fix synchronization issues with modern versions of RN, but currently RN51 do not work with Detox.

Please follow this issue https://github.com/wix/detox/issues/608
