### ISSUE TITLE
Issue with setLocation (PR #532)

### ISSUE THREAD

**Issue by blumendorf** [wix/Detox#629]
We are experiencing an issue with setLocation from PR #532 (https://github.com/wix/detox/pull/532).

The problem seems to be that the iOS simulator and fbsimctl use localised number formats.
Meaning comma separated locations fail on our CI and dot separated locations fail locally (on a German machine).

I.E. 
`fbsimctl 417785CA-BB31-44D1-92FC-8D6F7A866562 set_location 12.345 12.345` works on our continuous integration system, but fails locally; 
`fbsimctl 417785CA-BB31-44D1-92FC-8D6F7A866562 set_location 12,345 12,345` works locally, but fails on CI.

**Comment by rotemmiz** [comment]
Do you have the same fbsimctl version on both machines?

**Comment by blumendorf** [comment]
yes, fbsimctl HEAD-1aef0d0 on both machines.

**Comment by rotemmiz** [comment]
Ho my, what a confusing API :(

**Comment by blumendorf** [comment]
Yeah! Also very annoying when copy'n'pasting locations in the simulator for testing.

**Comment by blumendorf** [comment]
Quick fix: Change your region to US in System Preferences.

**Comment by rotemmiz** [comment]
I suggest you open an issue in https://github.com/facebook/FBSimulatorControl.

**Comment by LeoNatan** [comment]
I wonder if we can somehow do it ourselves. Get the decimal delimiter from the current system locale and then try to replace any other possible delimiters with the system locale one.

**Comment by LeoNatan** [comment]
Or maybe we can put some environment var that would replace the fbsimctl locale with en_US. That would be preferable.

**Comment by LeoNatan** [comment]
OK, I looked how Xcode fakes the locale of apps for debug purposes; they add `-AppleLocale en_US` to the launch arguments. This is a problem because fbsimctl parses the argument list and complain about that option.

**Comment by LeoNatan** [comment]
If anyone wants to step in and implement a fix for this, it would be greatly appreciated. We don't currently have the resources. It shouldn't be difficult, and all can be done in JS.

This is my current idea of how to solve:
> Get the decimal delimiter from the current system locale and then try to replace any other possible delimiters with the system locale one.

**Comment by pleportz** [comment]
Hi ! Rather than changing my region to US in System Preferences, I used this workaround to make it work on both CI and local environment: 

```
try {
    await device.setLocation('48.8826941', '2.3201584');
  } catch (error) {
    await device.setLocation('48,8826941', '2,3201584');
  }
```

**Comment by ayelenmarie** [comment]
Hi everyone! Since I think this is related to an Issue I opened on `fbsimctl` repo ([https://github.com/facebook/idb/issues/512](url)), I'm here to comment that they implemented a new tool that includes `fbsimctl` and that supposedly fixed this Issue. It's called `idb`, it says it's still under construction but maybe it would be nice for Detox to implement it in a next release.

**Comment by LeoNatan** [comment]
@ayelenmarie Thanks for letting us know! Do you mind opening an enhancement request?

**Comment by ayelenmarie** [comment]
@LeoNatan Sure! here it is #1371

**Comment by LeoNatan** [comment]
This is an old issue and I don't think really related to Detox. Closing for now.
