### ISSUE TITLE
Test failing when launching on Android emulator with "before all" hook error

### ISSUE THREAD

**Issue by AndrewFisher093** [wix/detox#647]
Hello, I have an issue with launching a simple test on Android emulator.  Have I can fix this?
I'm using detox test --configuration android.emu.debug --loglevel verbose to run tests

#### Steps to Reproduce

* Detox: ^7.2.0
* React Native: 0.54.0
* Node: v9.9.0
* Android Studio: 3.0.1
* Xcode: Version 9.2
* macOS: High Sierra 10.13.3

"detox": {
    "configurations": {
      "ios.sim.debug": {
        "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/civimobile.app",
        "build": "xcodebuild -project ios/civimobile.xcodeproj -scheme civimobile -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build",
        "type": "ios.simulator",
        "name": "iPhone 7 Plus"
      },
      "ios.sim.release": {
        "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/civimobile.app",
        "build": "xcodebuild -project ios/civimobile.xcodeproj -scheme civimobile -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build",
        "type": "ios.simulator",
        "name": "iPhone 7 Plus"
      },
      "android.emu.debug": {
        "binaryPath": "android/app/build/outputs/apk/debug/app-debug.apk",
        "build": "pushd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && popd",
        "type": "android.emulator",
        "name": "Nexus_5X_API_27_x86"
      },
      "android.emu.release": {
        "binaryPath": "android/app/build/outputs/apk/app-debug.apk",
        "build": "pushd android && ./gradlew assembleRelease assembleAndroidTest -DtestBuildType=release && popd",
        "type": "android.emulator",
        "name": "Nexus_5X_API_27_x86"
      }
    }

**Comment by AndrewFisher093** [comment]
detox test --configuration android.emu.debug --loglevel verbose
node_modules/.bin/mocha e2e --opts e2e/mocha.opts --configuration android.emu.debug --loglevel verbose


detox info 17:15:36: server listening on localhost:58797...
detox verb ws onOpen [object Object]
detox verb ws send: {"type":"login","params":{"sessionId":"8179c9ab-c1dc-8aee-b458-214a0f516649","role":"tester"},"messageId":0}
detox verb ws onMessage: {"type":"loginSuccess","params":{"sessionId":"8179c9ab-c1dc-8aee-b458-214a0f516649","role":"tester"},"messageId":0}
detox verb ws
detox verb 1: /Users/user/Library/Android/sdk/tools/emulator -list-avds --verbose
detox verb 1: stdout: Nexus_5X_API_27_x86
detox verb 1: stdout: Pixel_API_27
detox verb 1: stdout:
detox verb /Users/user/Library/Android/sdk/tools/emulator -verbose -gpu host -no-audio @Nexus_5X_API_27_x86
detox verb 2: /Users/user/Library/Android/sdk/platform-tools/adb  devices
detox verb 2: stdout: List of devices attached
detox verb 2: stdout: emulator-5554     device
detox verb 2: stdout:
detox verb 2: stdout:
detox verb 3: /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop dev.bootcomplete
detox verb 3: stdout: 1
detox verb 3: stdout:
detox verb 4: /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell input keyevent 82
detox verb 5: /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 uninstall com.civimobile
detox verb 5: stdout: Success
detox verb 5: stdout:
detox verb 6: /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 uninstall com.civimobile.test
detox verb 6: stdout: Success
detox verb 6: stdout:
detox verb 7: /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop ro.build.version.sdk
detox verb 7: stdout: 27
detox verb 7: stdout:
detox verb 8: /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -r -g /Users/user/Desktop/civi-crm/civi-mobile/android/app/build/outputs/apk/debug/app-debug.apk
detox verb 8: stdout: Success
detox verb 8: stdout:
detox verb 9: /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop ro.build.version.sdk
detox verb 9: stdout: 27
detox verb 9: stdout:
detox verb 10: /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -r -g /Users/user/Desktop/civi-crm/civi-mobile/android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
detox verb 10: stdout: Success
detox verb 10: stdout:
detox verb 11: /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am force-stop com.civimobile
detox verb adb -s emulator-5554 shell am instrument -w -r -e detoxServer ws://localhost:58797 -e detoxSessionId 8179c9ab-c1dc-8aee-b458-214a0f516649 -e debug false com.civimobile.test/android.support.test.runner.AndroidJUnitRunner
detox verb Instrumentation spawned, childProcess.pid:  9831
detox verb ws send: {"type":"isReady","params":{},"messageId":-1000}
detox verb Instrumentation stdout:  INSTRUMENTATION_RESULT: stream=
detox verb Instrumentation stdout:
detox verb Instrumentation stdout:  Time: 0
detox verb Instrumentation stdout:
detox verb Instrumentation stdout:  OK (0 tests)
detox verb Instrumentation stdout:
detox verb Instrumentation stdout:
detox verb Instrumentation stdout:
detox verb Instrumentation stdout:  INSTRUMENTATION_CODE: -1
detox verb Instrumentation stdout:
detox verb instrumentationProcess terminated due to receipt of signal null

  0 passing (2m)

  1) "before all" hook
MacBook-Air-USER-5:civi-mobile user$ detox test --configuration android.emu.debug --loglevel verbose
node_modules/.bin/mocha e2e --opts e2e/mocha.opts --configuration android.emu.debug --loglevel verbose


detox info 17:26:14: server listening on localhost:60348...
detox verb ws onOpen [object Object]
detox verb ws send: {"type":"login","params":{"sessionId":"3164adf4-b887-68e1-a7a5-d46e108ffb27","role":"tester"},"messageId":0}
detox verb ws onMessage: {"type":"loginSuccess","params":{"sessionId":"3164adf4-b887-68e1-a7a5-d46e108ffb27","role":"tester"},"messageId":0}
detox verb ws
detox verb 1: /Users/user/Library/Android/sdk/tools/emulator -list-avds --verbose
detox verb 1: stdout: Nexus_5X_API_27_x86
detox verb 1: stdout: Pixel_API_27
detox verb 1: stdout:
detox verb /Users/user/Library/Android/sdk/tools/emulator -verbose -gpu host -no-audio @Nexus_5X_API_27_x86
detox verb 2: /Users/user/Library/Android/sdk/platform-tools/adb  devices
detox verb 2: stdout: List of devices attached
detox verb 2: stdout: emulator-5554     device
detox verb 2: stdout:
detox verb 2: stdout:
detox verb 3: /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop dev.bootcomplete
detox verb 3: stdout: 1
detox verb 3: stdout:
detox verb 4: /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell input keyevent 82
detox verb 5: /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 uninstall com.civimobile
detox verb 5: stdout: Success
detox verb 5: stdout:
detox verb 6: /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 uninstall com.civimobile.test
detox verb 6: stdout: Success
detox verb 6: stdout:
detox verb 7: /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop ro.build.version.sdk
detox verb 7: stdout: 27
detox verb 7: stdout:
detox verb 8: /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -r -g /Users/user/Desktop/civi-crm/civi-mobile/android/app/build/outputs/apk/debug/app-debug.apk
detox verb 8: stdout: Success
detox verb 8: stdout:
detox verb 9: /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop ro.build.version.sdk
detox verb 9: stdout: 27
detox verb 9: stdout:
detox verb 10: /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -r -g /Users/user/Desktop/civi-crm/civi-mobile/android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
detox verb 10: stdout: Success
detox verb 10: stdout:
detox verb 11: /Users/user/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am force-stop com.civimobile
detox verb adb -s emulator-5554 shell am instrument -w -r -e detoxServer ws://localhost:60348 -e detoxSessionId 3164adf4-b887-68e1-a7a5-d46e108ffb27 -e debug false com.civimobile.test/android.support.test.runner.AndroidJUnitRunner
detox verb Instrumentation spawned, childProcess.pid:  10219
detox verb ws send: {"type":"isReady","params":{},"messageId":-1000}
detox verb Instrumentation stdout:  INSTRUMENTATION_RESULT: stream=
detox verb Instrumentation stdout:
detox verb Instrumentation stdout:  Time: 0
detox verb Instrumentation stdout:
detox verb Instrumentation stdout:  OK (0 tests)
detox verb Instrumentation stdout:
detox verb Instrumentation stdout:
detox verb Instrumentation stdout:  INSTRUMENTATION_CODE: -1
detox verb Instrumentation stdout:
detox verb instrumentationProcess terminated due to receipt of signal null

  0 passing (2m)

  1) "before all" hook

**Comment by ohwillie** [comment]
Detox+Android is currently incompatible with RN >= 0.50: https://github.com/wix/detox/issues/608

**Comment by akqaaditya** [comment]
Could you please confrim if still Detox+Android is currently incompatible with RN >= 0.50?

**Comment by LeoNatan** [comment]
0.51 is supported.

**Comment by akqaaditya** [comment]
what about RN 55 ?

**Comment by LeoNatan** [comment]
I think Android doesn't support it yet, but iOS should work.

**Comment by akqaaditya** [comment]
Can any Team member confirm when Detox android will support RN 55, Any idea about the timeline?
i have explored it for iOS and I am pretty much interested for Android but after so many try got the idea that it's only working till RN 51.
