### ISSUE TITLE
CLI: `detox test` fails to determine a default configuration

### ISSUE THREAD

**Issue by askielboe** [wix/detox#648]
Seems you now have to specify the configuration manually (e.g. `detox test -c ios.sim.debug`), otherwise `detox test` crashes.

#### Description

After upgrading to detox 7.3.X, `detox test` fails with the following error:

```
/Users/askielboe/rntest/MyProject/node_modules/detox/local-cli/detox-test.js:37
const platform = (config.configurations[program.configuration].type).split('.')[0];
                                                               ^

TypeError: Cannot read property 'type' of undefined
    at Object.<anonymous> (/Users/askielboe/rntest/MyProject/node_modules/detox/local-cli/detox-test.js:37:64)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
```

It seems that `program.configuration` is undefined (unsurprisingly?). Setting the configuration using `detox test -c ios.sim.debug` makes `detox test` work again.

#### Steps to Reproduce

1. `react-native init MyProject`
2. Build using Xcode
3. `yarn global add detox-cli`
3. `yarn add detox --dev`
4. `yarn add mocha --dev`
5. Add detox config from [Getting Started](https://github.com/wix/detox/blob/master/docs/Introduction.GettingStarted.md) to `package.json`, replacing "example" with "MyProject"
6. `detox init`
6. `detox build`
6. `detox test`

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 7.3.2
* React Native: 0.54.3
* Node: 9.8.0
* Device: iPhone 7
* Xcode: 9.2 (9C40b)
* macOS: 10.13.3 (17D102)

#### Device and verbose Detox logs

See error log above.

**Comment by rotemmiz** [comment]
Thanks for reporting, this is indeed an issue caused by #639.

A workaround for this (till we publish a fix) would be to explicitly select a configuration:
`detox test -c myConfiguration`
