### ISSUE TITLE
device.launchApp won't give notification permissions on 7.3.2

### ISSUE THREAD

**Issue by vonovak** [wix/detox#653]
#### Description
I use detox for testing RN app only on ios and jest as test runner. After upgrade from 7.2.0 to 7.3.2, tests do not pass - they fail on timeout:

#### Steps to Reproduce
create an app that asks for notification permissions on start.

```js
//App.js
import FCM from 'react-native-fcm';
...
componentDidMount() {
    FCM.requestPermissions()
      .then(() => console.debug('notifications granted'))
      .catch(() => console.debug('notifications rejected'));
}
```

```js
//init.js
...
beforeAll(async () => {
  await detox.init(config);

  await device.launchApp({
    permissions: {
      notifications: 'YES',
    },
  });
});
...
```

boot simulator, reset its content and settings,  run `detox test` and you will see that app starts, and the alert asking for notification permissions shows up, but is not handled by detox. The app will hang in there until the timeout fails the tests.

Interestingly, if you kill the tests before the timeout and run them again, the notification permissions are set and the tests pass.

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 7.3.2
* React Native: 0.53
* Node:9.7.1
* Device: ios simulator
* Xcode: 9.2
* macOS: 10.13.3

#### Device and verbose Detox logs
first run (fails but I killed it before the timeout): [gist](https://gist.github.com/vonovak/776d9e032bce6f29fc99517e7f564bd1)
second run (succeeds): [gist](https://gist.github.com/vonovak/7e253dad655aae60648c84349e612744)

**Comment by LeoNatan** [comment]
On the first log, I don't see a call to `applesimutils --setPermissions`.

**Comment by LeoNatan** [comment]
I'm not sure why it wouldn't go through the `setPermission` code path. https://github.com/wix/detox/blob/792a78233e0c634d42b2e605c105cd4c6f6e41de/detox/src/devices/Device.js#L84

**Comment by vonovak** [comment]
I'll try do some debugging and get back to you, or create a minimal repro.

**Comment by vonovak** [comment]
sorry, not quite sure what happened, but I cannot reproduce it any more.

**Comment by LeoNatan** [comment]
If you reproduce again, please open a new issue. Thanks.
