### ISSUE TITLE
WebView and Photo picker support on Android

### ISSUE THREAD

**Issue by hoang17** [wix/detox#656]
Hello, is there a way to use detox to automate WebView testing? A feature that Im working on is e2e upload testing. I would like to find and scroll to an Upload button in WebView, click on it, it will ask for Camera or Photo Library, choose Photo Library, select photos to upload. Right now I can not find a detox api to control WebView and Photo picker. I tried to work around the WebView but still stuck with the Photo picker. The problem is detox can not find the Photo picker view hierarchy 
BTW, I see Espresso support element selector inside WebView so it would be great if detox support it

**Comment by paulbrittain** [comment]
Also interested, if your application uses OAuth how does Detox interact with the webview to log the user in?

**Comment by LeoNatan** [comment]
Web views are beyond our scope right now. Please mock APIs instead of displaying web views. Thanks
