### ISSUE TITLE
My app close immediately when run detox test.

### ISSUE THREAD

**Issue by tuanmai** [wix/detox#657]
#### Description
I run `detox test`, it installs the app but my app close immediately. Below is the log from `tail -F $HOME/Library/Developer/CoreSimulator/Devices/F1C50CD9-9029-4152-B071-88E9B822C861/data/tmp/detox.last_launch_app_log.err`
#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 7.1.0
* React Native: 0.51
* Node: 8.9
* Device: Iphone 6
* Xcode: 9.0.1
* macOS: 10.12.6

#### Device and verbose Detox logs
dyld: Symbol not found: __T0s8HashableMp
  Referenced from: /Users/tuanmai/Library/Detox/ios/1f234587b6bbcb4e827eab0494d1a18de1edbbee/Detox.framework/Frameworks/libswiftCoreFoundation.dylib
  Expected in: /Users/tuanmai/Library/Developer/CoreSimulator/Devices/F1C50CD9-9029-4152-B071-88E9B822C861/data/Containers/Bundle/Application/86C27211-F8BB-466A-838C-886D7B45ACBE/EHLife.app/Frameworks/libswiftCore.dylib
 in /Users/tuanmai/Library/Detox/ios/1f234587b6bbcb4e827eab0494d1a18de1edbbee/Detox.framework/Frameworks/libswiftCoreFoundation.dylib

**Comment by pgmemk** [comment]
@tuanmai How did you resolve it? I have exactly the same problem.

**Comment by pgmemk** [comment]
@LeoNatan Can you please help me out here?

**Comment by rotemmiz** [comment]
Please do not reply on closed issues, instead open a new issue and provide verbose script output and logs
