### ISSUE TITLE
Potential flakiness issue with detox 4 - Doron

### ISSUE THREAD

**Issue by talkol** [wix/detox#66]
I'm now running into something which I believe is a detox v4 issue.
When I run the tests, detox hangs on a simple selector that happens right after a "navigator back" and then times out after 40s without an output of any meaningful error.

Seems like a synchronization issue where the app is not responding when navigating back. I verified that the selector invocation is fired but there's no invokeResult coming back to the detox server. Also when I disable the back navigation, the test won't hang. So something is going on there. And worth noting that the same test and system under test worked with detox v3.

-- Doron

**Comment by LeoNatan** [comment]
Need example project. Thanks @talkol @doronpr

**Comment by LeoNatan** [comment]
@doronpr Does this still occur? If yes, could you please provide a demo project?

**Comment by doronpr** [comment]
No. Closing. Thanks!
