### ISSUE TITLE
device.launchApp won't give notification permissions on 

### ISSUE THREAD

**Issue by heuism** [wix/detox#661]
I just want to reopen the issue #653. It happened randomly. I thought maybe there is something wrong with the simulator or npm. So I just ignore it. But then today. I push to CI and it failed and the init phase for one test. while passed on the other test. on the same commit
![image](https://user-images.githubusercontent.com/8481265/38402614-cefa7692-39a0-11e8-8d21-b4137514a473.png)
![image](https://user-images.githubusercontent.com/8481265/38402632-e533d0ca-39a0-11e8-8d9b-82253be238ab.png)

- Detox: 7.3.2
- React Native: 0.48.4
- Node: 8.7.0
- Device: ios simulator
- Xcode: 9.1
- Machine: Circle CI

Thank you.

**Comment by LeoNatan** [comment]
@rotemmiz In the closed issue, I looked in the JS and didn't see a reason why it wouldn't go through the permissions codepath. Can you think of a reason why it wouldn't?

**Comment by rotemmiz** [comment]
Please provide a verbose log

**Comment by heuism** [comment]
thanks guys for having a look. @rotemmiz you mean the log of the test? which part of the process you are talking about? 👍

**Comment by rotemmiz** [comment]
Yes, verbose log of the test, I want to see if it launches applesimutils with correct params
