### ISSUE TITLE
Add small support for WebView

### ISSUE THREAD

**Issue by xcarpentier** [wix/detox#665]
### Description
A simple way to:
* Find element by ID in webview
* Replace text 

```js
await element(by.id('username')).replaceText('username@gmail.com')
```

### Why?
Some authentication way use an external provider with existing web form to login. (ie. auth0, keycloak, ...)

**Comment by paulbrittain** [comment]
Is this not supported by detox?

**Comment by LeoNatan** [comment]
Web views are not supported and it's out of scope. Please mock your API and do not display the web views. Thanks

**Comment by xcarpentier** [comment]
@LeoNatan, thanks for your response.

I already mocked.

I test my app with appium too and that is possible, why this is not in scope of detox project?

Thanks

**Comment by LeoNatan** [comment]
Because it's a big task. Research and pull requests are welcome. We use Earl Grey on iOS and Espresso on Android; both I think support some kind of web view manipulation. If someone wants to look, we will be glad to assist.
