### ISSUE TITLE
Add support for conditional logic around elements

### ISSUE THREAD

**Issue by etaiklein** [wix/detox#672]
This is a request to expose the ability to run code conditionally in detox tests based on the existence of elements.

For example:
```
const mainScreen = element(by.id('mainScreen'));
if (!mainScreen) {
  await doOnboarding();
}
await expect(mainScreen).toBeVisible();
```

**Comment by LeoNatan** [comment]
You can try/catch assertions and branch from that to the rest of your logic.

**Comment by rotemmiz** [comment]
Tests with branches are bad tests in my opinion.
A test should have a predictable input, and a predictable output. 
If it branches it's not one test, but two.

Try making your input predictable by mocking what needs to be mocked.
