### ISSUE TITLE
detox api to select photo from photo library ios 11

### ISSUE THREAD

**Issue by Brad19** [wix/detox#676]
#### Description
We've started using Detox for our E2E test which we felt good. But one of the problems that we face now is to select the photo from photo library in ios and for android as well. At first i tried to do for IOS, but got struck at the point when i find that the View hierarchy while debugging in Xcode doesn't return any Views for IOS 11. I happen to encounter the following link which explores the possibility, but didn't answer for IOS 11. 

https://stackoverflow.com/questions/48208456/e2e-select-an-image-from-a-uiimagepickercontroller-with-wix-detox

And found these one as well, 
https://stackoverflow.com/questions/29490728/how-to-use-uiautomation-to-select-image-from-uiimagepickercontroller?noredirect=1&lq=1

https://stackoverflow.com/questions/46404628/ios11-photo-library-access-is-possible-even-if-settings-are-set-to-never/46594741

I think, It looks like if we have access to PHPhotoLibrary, then our problem will be solved.

If you have any answer for this, Please advise. 

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 7.1.0
* React Native: 0.53.2
* Node: 8.9.1
* Device: IOS simulator 6, 11.2
* Xcode: 9.2
* macOS:  10.13.3

#### Device and verbose Detox logs
--

**Comment by LeoNatan** [comment]
As I explained in my comment and has been also mentioned elsewhere, `UIImagePickerController` runs in a different process, thus we cannot control it. `PHPhotoLibrary` is something completely different and has nothing to do with `UIImagePickerController`. If you use `PHPhotoLibrary` to build your own photo picker, you could make it work, but it doesn't help for `UIImagePickerController`, which most people use.

Your best bet is to mock the image picker API to just return some default image.

**Comment by Brad19** [comment]
@LeoNatan 
Thanks for your response. But i've couple of questions to clarify
1. If I'm mocking. how does that satisfy the condition in terms of flow to select an item from image library and uploading it to wherever i want
2. Can you pls provide some example to mock image Picker API for IOS? 
3. Please provide some time before closing this ticket, as it didn't exactly resolve my problem.

**Comment by LeoNatan** [comment]
I'm not sure how leaving it open would help in that case. It's an OS limitation which we cannot overcome, so you have too look at workarounds.

You mock only the image picker API, where your mock returns an image. You can then proceed to do the same logic as you normally do in your app, such as update your own UI or upload. I cannot provide examples, but for React Native apps, we have a section in the documentation, dedicated to mocking. Please see that.

**Comment by Brad19** [comment]
@LeoNatan 
Thanks for your quick response. What i meant was, the issue is under discussion and not sure if it is good to close. The reason why i asked was we have a solution working for IOS 10.2 version in one the links provided above. But now we can't use that as the OS version has been upgraded to 11 and the existing solution is not working due to system limitation. So I want to know if you guys are working anything on this?  If not, pls let me know. But anyway i'll give it a shot and get back to you guys in case i end up in trouble. Thanks!!!

**Comment by LeoNatan** [comment]
As I have said before, there is little to nothing we can do. There are numerous things that Apple has moved out of process for user security reasons (otoh, Safari view controller, contact view controller, image picker view controller, etc.).

The only workaround (I understand it's not a full solution) is to mock this API and not use it when testing.
