### ISSUE TITLE
Keyboard tutorial breaks tests

### ISSUE THREAD

**Issue by gnowenegue** [wix/detox#677]
#### Description
With iOS 11 and above, when typing on a fresh state of the simulator, there will be an overlay tutorial which requires users to click on "OK" to proceed. This has caused all my current tests to break when switching to iOS 11.3 simulators.

![qd92y50ct6az](https://user-images.githubusercontent.com/4962518/38983484-090324c8-43f7-11e8-8326-0257269a8735.jpg)

I can't help to notice that EarlGrey has already fixed this [issue](https://github.com/google/EarlGrey/issues/633) in their latest release. Was wondering if Detox is intending to pull EarlGrey's latest codes to fix this issue? Or if there is any workaround in Detox? Please advise. Thanks.

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 7.3.3
* React Native: 0.52.3
* Node: 8.11.1
* Device: Simulator — iPad Pro (10.5-inch), iOS 11.3
* Xcode: 9.3
* macOS: High Sierra 10.13.4

**Comment by LeoNatan** [comment]
We'll add it soon.

**Comment by LeoNatan** [comment]
@DanielMSchmidt @rotemmiz If the parser has been updated, can we update EG now?

**Comment by DanielMSchmidt** [comment]
What is EG? EarlGrey?

**Comment by LeoNatan** [comment]
Yes

**Comment by gnowenegue** [comment]
Any updates on this issue?
