### ISSUE TITLE
fbsimctl sometimes fails with timeout on Travis CI

### ISSUE THREAD

**Issue by LeoNatan** [wix/detox#68]
https://travis-ci.org/wix/detox/builds/186321306

**Comment by LeoNatan** [comment]
Same occurred here: https://travis-ci.org/wix/detox/builds/190579182

**Comment by rotemmiz** [comment]
This might be related to the infrastructure that runs these builds. Travis are working on MacStadium infrastructure (VMWare ESXi), not sure how they dedicate resources per VM, but it smells like this...

**Comment by LeoNatan** [comment]
The second issue that happened today was strange. There was a bug in package.json, but it first displayed the timeout issue. I then restarted the build, and it displayed the real issue, so I think the first run was a separate issue, like one in the original post. Very annoying.

**Comment by LeoNatan** [comment]
Another one…
https://travis-ci.org/wix/detox/builds/191240884

It fails for no apparent reason. The next build goes through.

**Comment by rotemmiz** [comment]
[v4.1.4 ](https://github.com/wix/detox/releases/tag/detox%404.1.4) should solve this issue. Let's keep an eye on CI builds.

**Comment by rotemmiz** [comment]
Patch looks good. Closing issue
