### ISSUE TITLE
NS_REFINED_FOR_SWIFT should be ignored by generated code

### ISSUE THREAD

**Issue by rotemmiz** [wix/detox#682]
[NS_REFINED_FOR_SWIFT macro](https://github.com/google/EarlGrey/commit/499474e02cc486b65c360da362173ec77e7495ee#diff-ad85ec7ab42faaa4cd1a922503fca1caR18) was added to a few of EarlGrey's functions. 

We need to make sure this is ignored by generated JS GREY* code. Till then we can not upgrade EarlGrey to a newer version.
https://github.com/DanielMSchmidt/objective-c-parser/issues/52

**Comment by LeoNatan** [comment]
This is the problem with text parsing. It is just not robust enough.
An alternative solution is to use an AST parser that uses the actual compiler's AST to get metadata for classes. For example [SourceKitten](https://github.com/jpsim/SourceKitten) supports producing an AST-backed "documentation" dump of Objective-C API from a header file.

**Comment by DanielMSchmidt** [comment]
Cool solution, I will give it a try, but I will first fix the issue in our current parser, as this is the faster fix for this immediately problem :)

**Comment by DanielMSchmidt** [comment]
I fixed it in version `1.2.3` of the objective c parser, here is a PR upgrading to that version in detox: https://github.com/wix/detox/pull/684

For the long run, what would be your preferred way:

1) First move every part of detox that relates to native code over to generated code and tackle the underlying parser afterwards
2) First try to exchange our hand-built parser with the solution you found and continue the migration afterwards?

**Comment by DanielMSchmidt** [comment]
@rotemmiz and I decided for solution 2, so I did the initial research. I think we can translate the output of SourceKitten over to the structure we need:

- Classes can be found as `"key.kind" : "sourcekitten.source.lang.objc.decl.protocol",`
- Methods can be found as `"key.kind" : "sourcekitten.source.lang.objc.decl.method.instance",`
	- Mehthodname is `"key.name"`
	- Comment is `"key.doc.comment"`
	- Parameters are `key.doc.parameters`
		- Name of a parameter: `name`
		- Type of a parameter: **???**
	- Return type: **???**

I need to investigate where we can get the missing types from, I "just" used the command @LeoNatan showed above, need to check for configuration options 🤔

**Comment by LeoNatan** [comment]
Can this be closed? I see that the PR has been merged. We will use the other issue to track SourceKitten progress.

**Comment by DanielMSchmidt** [comment]
Yeah, sure!

**Comment by LeoNatan** [comment]
Thanks
