### ISSUE TITLE
Missing package name and version

### ISSUE THREAD

**Issue by kristfal** [wix/detox#696]
#### Description
`package.json` is missing package name and version. This prevents `yarn` and `npm` from installing master branch or any other non-published branch/tag.

#### Steps to Reproduce
`yarn add https://github.com/wix/detox.git`

or

`
npm add https://github.com/wix/detox.git
`

#### Error

NPM
`npm ERR! Can't install git+https://github.com/wix/detox.git#866ee447bad07ba2896b79972be6dfb4e002c007: Missing package name`

Yarn
`error An unexpected error occurred: "Can't add undefined: invalid package version undefined.".`

**Comment by rotemmiz** [comment]
Detox is a multi package repo, managed with Lerna.
This is currently not supported, not sure if it ever will. Please consult yarn/npm documentation.
Moreover, we package native iOS code during prepublish stage, so the actual npm package is different than what we have on the actual repo.
