### ISSUE TITLE
detox test crash w/ Signal 6 in release mode

### ISSUE THREAD

**Issue by doronpr** [wix/detox#704]
#### Description
Detox crashes after running in release mode.

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 7.3.4
* React Native: 0.51.600
* Node: 8.9.1
* Device: iPhone8 Plus Simulator
* Xcode: 9
* macOS: 10.13.3

#### Device and verbose Detox logs
```detox ERR! App crashed in test 'undefined', here's the native stack trace:
detox ERR! Signal 6 was raised
detox ERR! (
detox ERR!     0   Detox                               0x000000010ce2550f _ZL16__DTXHandleCrashP11NSExceptionP8NSNumberP8NSString + 469
detox ERR!     1   Detox                               0x000000010ce252bb _ZL17__DTXHandleSignali + 54
detox ERR!     2   libsystem_platform.dylib            0x00000001145ebf5a _sigtramp + 26
detox ERR!     3   ???                                 0x000000000000ffff 0x0 + 65535
detox ERR!     4   libsystem_c.dylib                   0x00000001142810eb abort + 127
detox ERR!     5   libsystem_malloc.dylib              0x00000001143bbf42 malloc_zone_malloc + 0
detox ERR!     6   Foundation                          0x000000010cfaecbc -[NSConcreteMapTable grow] + 938
detox ERR!     7   Foundation                          0x000000010cfad258 -[NSConcreteMapTable setObject:forKey:] + 164
detox ERR!     8   Detox                               0x000000010ce1c655 -[GREYAppStateTracker(PrettyPrint) _pp__trackState:forObject:] + 144
detox ERR!     9   EarlGrey                            0x00000001254903cd -[__NSCFLocalDataTask_GREYAdditions grey_track] + 157
detox ERR!     10  EarlGrey                            0x0000000125490752 -[__NSCFLocalDataTask_GREYAdditions greyswizzled_resume] + 210
detox ERR!     11  Inbox                               0x000000010ca5092b -[RCTHTTPRequestHandler sendRequest:withDelegate:] + 670
detox ERR!     12  Inbox                               0x000000010ca48fb3 -[RCTNetworkTask start] + 149
detox ERR!     13  Inbox                               0x000000010ca4eb2d -[RCTNetworking sendRequest:responseType:incrementalUpdates:responseSender:] + 1254
detox ERR!     14  Inbox                               0x000000010ca4ff08 __44-[RCTNetworking sendRequest:responseSender:]_block_invoke + 212
detox ERR!     15  EarlGrey                            0x00000001254595c4 __60-[GREYDispatchQueueTracker grey_dispatchAsyncCallWithBlock:]_block_invoke + 36
detox ERR!     16  libdispatch.dylib                   0x0000000114139177 _dispatch_call_block_and_release + 12
detox ERR!     17  libdispatch.dylib                   0x000000011413a1ba _dispatch_client_callout + 8
detox ERR!     18  libdispatch.dylib                   0x0000000114141d3d _dispatch_queue_serial_drain + 654
detox ERR!     19  libdispatch.dylib                   0x00000001141425a0 _dispatch_queue_invoke + 329
detox ERR!     20  libdispatch.dylib                   0x000000011413ec97 _dispatch_queue_override_invoke + 477
detox ERR!     21  libdispatch.dylib                   0x0000000114144980 _dispatch_root_queue_drain + 568
detox ERR!     22  libdispatch.dylib                   0x00000001141446ea _dispatch_worker_thread3 + 119
detox ERR!     23  libsystem_pthread.dylib             0x00000001145fd1ca _pthread_wqthread + 1387
detox ERR!     24  libsystem_pthread.dylib             0x00000001145fcc4d start_wqthread + 13
detox ERR! )```

**Comment by LeoNatan** [comment]
Thanks
This appears iOS related, it's crashing in the `NSMapTable` internals. Not sure yet why.

**Comment by LeoNatan** [comment]
Could be related to thread safety. `NSMapTable` is not thread safe, so that could be the cause.

**Comment by doronpr** [comment]
That would make a lot of sense since it only happens in Release mode when the app responds significantly faster and perhaps triggering a race condition. What can we do about it?

**Comment by LeoNatan** [comment]
I will push a proposed fix soon, and @rotemmiz will release a new version. Let's see if my solution helps.

**Comment by LeoNatan** [comment]
@rotemmiz Please release a new patch version. Thanks

**Comment by LeoNatan** [comment]
@doronpr Please update on the status when you can. If my solution didn't work, I will reopen the issue.

**Comment by doronpr** [comment]
Solved. Thanks @LeoNatan !

**Comment by yogeshthanvi** [comment]
I am facing the same issue 
 Signal 6 was raised
 (R!x
 RR!x   0   Detox                               0x000000010afffcfa _ZL16__DTXHandleCrashP11NSExceptionP8NSNumberP8NSString + 469
 RR!x   1   Detox                               0x000000010afffaa6 _ZL17__DTXHandleSignali + 54
 RR!x   2   libsystem_platform.dylib            0x0000000114334f5a _sigtramp + 26
 RR!x   3   ???                                 0x000000000000ffff 0x0 + 65535
 RR!x   4   libsystem_c.dylib                   0x0000000113f6ac97 abort + 127
 RR!x   5   EarlGrey                            0x0000000126b2deee -[NSURLSession(GREYAdditions) greyswizzled_dataTaskWithRequest:completionHandler:] + 910
 RR!x   6   dibellas                            0x000000010a548448 -[RCTMultipartDataTask startTask] + 264
 RR!x   7   dibellas                            0x000000010a517543 _ZL36attemptAsynchronousLoadOfBundleAtURLP5NSURLU13block_pointerFvP18RCTLoadingProgressEU13block_pointerFvP7NSErrorP9RCTSourceE + 899
 RR!x   8   dibellas                            0x000000010a516f3c +[RCTJavaScriptLoader loadBundleAtURL:onProgress:onComplete:] + 636
 RR!x   9   dibellas                            0x000000010a4a3c1a -[RCTCxxBridge loadSource:onProgress:] + 1946
 RR!x   10  dibellas                            0x000000010a4a2443 -[RCTCxxBridge start] + 7683
 RR!x   11  dibellas                            0x000000010a48291c -[RCTBridge setUp] + 892
 RR!x   12  dibellas                            0x000000010a481c37 -[RCTBridge initWithDelegate:bundleURL:moduleProvider:launchOptions:] + 375
 RR!x   13  dibellas                            0x000000010a481a52 -[RCTBridge initWithBundleURL:moduleProvider:launchOptions:] + 146
 RR!x   14  dibellas                            0x000000010a5a1737 -[RCTRootView initWithBundleURL:moduleName:initialProperties:launchOptions:] + 183
 RR!x   15  dibellas                            0x000000010a237858 -[AppDelegate setAppViewWithOptions:] + 488
 RR!x   16  dibellas                            0x000000010a23720d -[AppDelegate application:didFinishLaunchingWithOptions:] + 477
 RR!x   17  Detox                               0x000000010affb5ad -[DetoxAppDelegateProxy application:didFinishLaunchingWithOptions:] + 169
 RR!x   18  UIKit                               0x000000010d5056fb -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 278
 RR!x   19  UIKit                               0x000000010d507172 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 4123
 RR!x   20  UIKit                               0x000000010d50c5cb -[UIApplication _runWithMainScene:transitionContext:completion:] + 1677
 RR!x   21  UIKit                               0x000000010d8cef7e __111-[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]_block_invoke + 866
 RR!x   22  UIKit                               0x000000010dca1a39 +[_UICanvas _enqueuePostSettingUpdateTransactionBlock:] + 153
 RR!x   23  UIKit                               0x000000010d8cebba -[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:] + 236
 RR!x   24  UIKit                               0x000000010d8cf3db -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:] + 675
 RR!x   25  UIKit                               0x000000010e240614 __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke + 299
 RR!x   26  UIKit                               0x000000010e2404ae -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:] + 433
 RR!x   27  UIKit                               0x000000010df2475d __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke + 221
 RR!x   28  UIKit                               0x000000010e11f4b7 _performActionsWithDelayForTransitionContext + 100
 RR!x   29  UIKit                               0x000000010df24627 -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:] + 223
 RR!x   30  UIKit                               0x000000010dca10e0 -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] + 392
 RR!x   31  UIKit                               0x000000010d50aeac -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 515
 RR!x   32  UIKit                               0x000000010daddbcb -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 361
 RR!x   33  FrontBoardServices                  0x0000000119c682f3 -[FBSSceneImpl _didCreateWithTransitionContext:completion:] + 331
 RR!x   34  FrontBoardServices                  0x0000000119c70cfa __56-[FBSWorkspace client:handleCreateScene:withCompletion:]_block_invoke_2 + 225
 RR!x   35  libdispatch.dylib                   0x0000000113e23709 _dispatch_client_callout + 8
 RR!x   36  libdispatch.dylib                   0x0000000113e288c1 _dispatch_block_invoke_direct + 317
 RR!x   37  FrontBoardServices                  0x0000000119c9c470 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 24
 RR!x   38  FrontBoardServices                  0x0000000119c9c12e -[FBSSerialQueue _performNext] + 439
 RR!x   39  FrontBoardServices                  0x0000000119c9c68e -[FBSSerialQueue _performNextFromRunLoopSource] + 45
 RR!x   40  CoreFoundation                      0x0000000111696bb1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
 RR!x   41  CoreFoundation                      0x000000011167b4af __CFRunLoopDoSources0 + 271
 RR!x   42  CoreFoundation                      0x000000011167aa6f __CFRunLoopRun + 1263
 RR!x   43  CoreFoundation                      0x000000011167a30b CFRunLoopRunSpecific + 635
 RR!x   44  GraphicsServices                    0x0000000118cc8a73 GSEventRunModal + 62
 RR!x   45  UIKit                               0x000000010d50e057 UIApplicationMain + 159
 RR!x   46  Detox                               0x000000010aff89ad __WX_UIApplicationMain + 197
 RR!x   47  dibellas                            0x000000010a236f2f main + 111
 RR!x   48  libdyld.dylib                       0x0000000113e98955 start + 1
 RR!x   49  ???                                 0x0000000000000006 0x0 + 6
 )R!x
