### ISSUE TITLE
Upgrade ws to secure version

### ISSUE THREAD

**Issue by FuadBalashov** [wix/Detox#706]
#### Description
The [version of websocket/ws](https://github.com/wix/detox/blob/master/detox/package.json#L57) currently used by detox is 1.1.1. This version has security vulnerabilities due to its usage of Math.random() as noted in [this PR](https://github.com/websockets/ws/pull/832).

This request is to upgrade ws to a secure version (anything after 2.0.0) the current version of ws is 5.1.1.

#### Steps to Reproduce
N/A

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: Current

#### Device and verbose Detox logs
N/A

**Comment by FuadBalashov** [comment]
I am happy to do this upgrade if y'all will merge it.

**Comment by LeoNatan** [comment]
We would appreciate a PR.

**Comment by LeoNatan** [comment]
It was updated.
