### ISSUE TITLE
Detox test overwrites mocha grep option with --grep :android: --invert 

### ISSUE THREAD

**Issue by Ljo2017** [wix/detox#712]
It seems that when running detox test, the grep options in mocha.opts gets overwritten by detox test and therefore not recognised.

Detox command used:
detox test -c ios.sim.release

Log:
node_modules/.bin/mocha e2e --opts e2e/mocha.opts --configuration ios.sim.release     **--grep :android: --invert** 

detox info 15:09:15: server listening on localhost:60573...
detox info 1: Searching for device matching iPhone 7... 

It looks as if --grep :android: --invert overwrites the grep option in mocha.opts.

If I run the command below, the grep option in mocha.opts is recognised:
node_modules/.bin/mocha e2e --opts e2e/mocha.opts --configuration ios.sim.release

Can we have this automatic platform deduction logic removed? Or is there any way not to have the mocha.opts option overwritten?

* Detox: 7.3.4
* React Native: .55
* Node: 8.9.4
* Device: iOS simulator
* Xcode: 9.2

**Comment by rotemmiz** [comment]
For mocha you don't need to use Detox command line tool.
You can actually just use mocha's command line directly:
`mocha e2e --opts e2e/mocha.opts --configuration ios.sim.release`

Every detox cli param is passed almost with no change.

**Comment by noomorph** [comment]
@Ljo2017  if you provide a function covered with integration tests that is able to merge `:platform` with an arbitrary user input, I think we could actually use it for mocha in next releases.

**Comment by Ljo2017** [comment]
@noomorph we've made changes to merge the platform grep expression with the existing grep options in mocha.opts file and tried to make a pull request but got a permission denied error.

ERROR: Permission to wix/detox.git denied to Ljo2017.
fatal: Could not read from remote repository.

Could you give me access to the repository to make a pull request?

**Comment by Ljo2017** [comment]
Thanks @noomorph.
Created a PR https://github.com/wix/detox/pull/748.
