### ISSUE TITLE
Any option to adopt the robot pattern

### ISSUE THREAD

**Issue by Diego-Franco** [wix/detox#713]
This is a simple question, do you have a plan to adopt the robot pattern for detox? 

Sample: [Robot pattern](https://dev.to/adammc331/leveraging-the-robot-pattern-for-espresso-tests)

Some times we have a lot of duplicate code, and will be nice to have clean code for unit test.

**Comment by rotemmiz** [comment]
This completely up to you how to write your unit tests, you can adopt this pattern even now, it's just reformatting your test code.
You can extract any duplicate login to helper functions/drivers/whatever-else.
