### ISSUE TITLE
Possible to specify Scroll start location?

### ISSUE THREAD

**Issue by compojoom** [wix/detox#715]
Ok, this might be considered a question and something for stackoverflow, but it's also kind of a bug/feature?

In our interface we have an absolutely positioned element over a scroll view. Trying to do scroll to Top fails. Here is a gif.
![2018-05-04 14 50 57](https://user-images.githubusercontent.com/693770/39628855-a20554fc-4faa-11e8-9026-f7b36572c643.gif)

Is there a way to specify a start position of the scroll? A real user might also start to scroll at the top, but once he notices that there is a tap on the button, he would start the scroll somewhere else.

**Comment by LeoNatan** [comment]
This is something we want, but have not had time to implement. #154 #589

**Comment by LeoNatan** [comment]
Hello,
This was recently implemented. You can now provide startX and startY percentage to scroll.
