### ISSUE TITLE
test runs fine on iOS, but tails on Android

### ISSUE THREAD

**Issue by compojoom** [wix/detox#716]
I have a simple login test:
```

  it('should be able to login', async () => {
    await element(by.id('login')).tap()
    await expect(element(by.id('LoginScreen'))).toBeVisible()
    await element(by.id('email')).typeText('xxx@xxx.com')
    await element(by.id('password')).replaceText('xxx')
    await element(by.id('loginButton')).tap()
    await expect(element(by.id('companiesScreen'))).toBeVisible()
  })
```

This works fine on iOS. The user is logged in and sees the companiesScreen. The test fails on Android at the last line:
await expect(element(by.id('companiesScreen'))).toBeVisible()

If I change this to:
    await waitFor(element(by.id('companiesScreen'))).toBeVisible().withTimeout(4000)

Then it works on android as well. The navigation in our app is done by react-native-router-flux, which users react-navigation. 
WaitFor works, but it defeats the purpose of all this. I have another tests that also fail with the same conditions... Is this expected behavior or a bug?

**Comment by rotemmiz** [comment]
What version of react native do you use?
Is there any setTimeout in your code which is set to run with delay smaller than 1500ms?

**Comment by markhu** [comment]
It is important to note which version of react-native your project uses, as there have been known-incompatibilities with wix-detox from time to time. Last time I was able to use them together was RN 49.
