### ISSUE TITLE
Detox and react-native-maps

### ISSUE THREAD

**Issue by compojoom** [wix/detox#718]
I'm trying to test the map functionality of our app, but I'm failing on interacting with our markers.

React-native-maps doesn't have a testID on it's markers, but there is an open Pull-request that ads it, so I decided to give it a try and see if I can make detox work with it.
https://github.com/react-community/react-native-maps/pull/1170/files

I've added the changes, I've captured a snapshot of the UI and as you can see:

<img width="656" alt="grafik" src="https://user-images.githubusercontent.com/693770/39768839-b8849394-52ea-11e8-84f4-f26efab6dbab.png">
the markers are rendered and have an identifier. However the error message from detox is:

```
  1) should be able to open map and see a single field:
     Error: Error: An assertion failed.
Exception with Assertion: {
  "Assertion Criteria" : "assertWithMatcher:matcherForSufficientlyVisible(>=0.750000)",
  "Element Matcher" : "(((respondsToSelector(accessibilityIdentifier) && accessibilityID('marker')) && !(kindOfClass('RCTScrollView'))) || (kindOfClass('UIScrollView') && ((kindOfClass('UIView') || respondsToSelector(accessibilityContainer)) && ancestorThatMatches(((respondsToSelector(accessibilityIdentifier) && accessibilityID('marker')) && kindOfClass('RCTScrollView'))))))"
}

Error Trace: [
  {
    "Description" : "Assertion with matcher [M] failed: UI element [E] failed to match the following matcher(s): [S]",
    "Description Glossary" :     {
      "M" : "matcherForSufficientlyVisible(>=0.750000)",
      "E" : "<AIRGoogleMapMarker:0x7f834ce28db0; AX=N; AX.id='marker'; AX.frame={{0, 0}, {46.5, 39}}; AX.activationPoint={23.25, 19.5}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {46.5, 39}}; opaque; alpha=1>",
      "S" : "matcherForSufficientlyVisible(>=0.750000)"
    },
    "Error Domain" : "com.google.earlgrey.ElementInteractionErrorDomain",
    "Error Code" : "3",
    "File Name" : "GREYAssertions.m",
    "Function Name" : "+[GREYAssertions grey_createAssertionWithMatcher:]_block_invoke",
    "Line" : "75"
  }
]

```

I'm wondering why this might be failing. in the screen snapshot all the markers seem to be one behind the other and in front of them are 2 RCTViews Calayer. Is detox able to look through those?

Any hints? Is this mission impossible?

* Detox: 7.3.5
* React Native: 0.55
* Node: 9.11
* Device: iphone 8 simulator
* Xcode: 9.3
* macOS: high sierra

**Comment by LeoNatan** [comment]
Seems like a similar issue to #250. PRs are welcome.

**Comment by compojoom** [comment]
@LeoNatan - don't fully agree with the duplicate tag. RN-maps doesn't support testID - this is why #250 doesn't work. But I've added a testID property now and as you can see from the screenshot above - it's applied to the generated views. However detox still doesn't see the elements

What does this mean:
```
    "Description Glossary" :     {
      "M" : "matcherForSufficientlyVisible(>=0.750000)",
      "E" : "<AIRGoogleMapMarker:0x7f834ce28db0; AX=N; AX.id='marker'; AX.frame={{0, 0}, {46.5, 39}}; AX.activationPoint={23.25, 19.5}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {46.5, 39}}; opaque; alpha=1>",
      "S" : "matcherForSufficientlyVisible(>=0.750000)"
    },
```

Does it mean that detox is seeing the element, but thinks that it isn't sufficiently visible?

**Comment by compojoom** [comment]
Ok, to answer my question myself :) It seems that the marker exist for detox, but for some reason it's not able to see it.

This code doesn't throw an error:
`await expect(element(by.id('marker'))).toExist()`

The problem is that I can't match anything inside of it. And now by the look of it - there is no view inside of the marker. Starting to think that the marker is not a UIView, but some sort of an image and one won't be able to match anything inside of it.

**Comment by LeoNatan** [comment]
Is it visible on screen when attempting?

**Comment by LeoNatan** [comment]
What happens if you use the Apple Maps service rather than Google?

**Comment by LeoNatan** [comment]
I think in Apple Maps, the marker can be a view, but could be that in Google Maps, the marker could be a CALayer directly, or their internal vector representation.

**Comment by LeoNatan** [comment]
Indeed, [`GMSMarker`](https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_marker) inherits from [`GMSOverlay`](https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_overlay), but it's just an `NSObject`.

**Comment by abdulkhaliquem9** [comment]
@LeoNatan  As per the reference https://stackoverflow.com/questions/29924564/using-espresso-to-unit-test-google-maps/30519001, it is not possible to test Google Maps with Espresso, We need to use UIAutomator library, that is what is mentioned in the reference. Is there any solution to test Google Map on Android.

**Comment by abdulkhaliquem9** [comment]
@LeoNatan @compojoom 
**Feature request**
It is mentioned in the link  https://stackoverflow.com/questions/29924564/using-espresso-to-unit-test-google-maps/30519001, that, we can use 
> UiDevice device = UiDevice.getInstance(getInstrumentation());
UiObject marker = device.findObject(new UiSelector().descriptionContains("marker title"));
marker.click();

We already have UIAutomator in Detox, and we are using it to launch the app while running the test, see https://github.com/wix/detox/blob/d4a19179beabcea568e7a282f7444a9871cc660e/detox/android/detox/src/main/java/com/wix/detox/uiautomator/UiAutomator.java
It would be helpfull if we use UIAutomator API and add as an enhancement to Detox the feature of clicking the marker of react-native-map on android, will really help.
