### ISSUE TITLE
iOS Permission - HealthKit

### ISSUE THREAD

**Issue by rfader** [wix/detox#736]
#### Description

We're using HealthKit in our app, which seems like it's supported in the argument of `launchApp`. However, we are still experiencing the permission sheet showing, which times out the remaining detox tests.

#### Steps to Reproduce

The first test case runs this:
```
await device.launchApp({
	permissions: {
		health: 'YES',
		notifications: 'YES'
	}
});
```
As provided below, this causes, what seems to be, the correct command to applesimutils.

Further in the app flow we ask permission to HealthKit, which causes the permission sheet to show.

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 7.3.7
* React Native: 0.55.4
* Node: 10.1.0
* Device: iPhone 7 - 11.3
* Xcode: 9.3
* macOS: 10.13.4

#### Device and verbose Detox logs

```
7: applesimutils --simulator E7259742-2154-4B7A-B0EA-C0ABF5440E96 --bundle <REMOVED> --setPermissions health=YES,notifications=YES
 : Trying to set permissions...
 : Permissions are set

```

**Comment by LeoNatan** [comment]
This is not the place for this issue. Please open a new issue on AppleSimUtils and if possible, share some code examples.

**Comment by LeoNatan** [comment]
https://github.com/wix/AppleSimulatorUtils
