### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by baranpirincal** [wix/detox#738]
Hey, my aim is make my portfolio better with contribute on open source projects in field of graphic. If you interested I can make a logo design for Detox. I can show my portfolio if you interested. I am waiting your feedback! Have a nice day.

Best Regards,
Baran Pirincal
Visual Communication Designer

**Comment by rotemmiz** [comment]
YESS!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by baranpirincal** [comment]
@rotemmiz Do you have an idea or suggestion about design&decision. Should design contain letters of Detox or is it not necessary?

**Comment by rotemmiz** [comment]
Not really an expert in the field, but I think the logo should be a drawing, no text.
Something that may translate into an icon or sticker in a good way.

**Comment by rotemmiz** [comment]
We had a few ideas in the past, but non translated in a good way to a logo, I don't want to limit anything.
What did you have in mind ?

**Comment by baranpirincal** [comment]
@rotemmiz Actually I will examine your project firstly. After that I will share my first experiments with you. If you want to show any object, metaphor or something like that you can share with me. It will be better for me

**Comment by LeoNatan** [comment]
Please no juices or drinks. 😜

**Comment by LeoNatan** [comment]
BTW, thank you for offering this. We are humbled by such an offer!

**Comment by baranpirincal** [comment]
@LeoNatan @rotemmiz 

Hey, you're welcome. I made my first experiment, what do you think about?

I tried to make a logo design that translate into an icon or sticker as you said. However, please feel free to say any request,idea and feedback.

![detox](https://user-images.githubusercontent.com/37786733/40362632-c49224da-5dd5-11e8-9b42-1c127e842b0d.jpg)

![detox2](https://user-images.githubusercontent.com/37786733/40363309-d252465c-5dd7-11e8-9bd9-52a53c054ea5.jpg)


![iphone 5 with macbook](https://user-images.githubusercontent.com/37786733/40362810-4a8db4f0-5dd6-11e8-8447-c49f3815fc18.jpg)

**Comment by LeoNatan** [comment]
Thanks for working on this!
We’ve discussed this a little internally and were thinking that maybe an automation robot could fit this project. What do you think?

**Comment by baranpirincal** [comment]
@LeoNatan You're welcome. Sorry for delay, I was too busy last week. I will work on Automation robot. It would be better, have a nice day!

**Comment by raj8github** [comment]
Hey Guys, was just thinking as the name is DetOX, how about a logo modified from an illustration of an ox face and if we could fit in "D" as an illustration on the same, it would then need no text as well. Just by looking at the logo we could make out its Detox. 

PS: I'm not an expert in Graphic / Logo Designs, just a thought struck to the mind and shared the same. Please ignore if it doesn't make any sense.

**Comment by rotemmiz** [comment]
💔
