### ISSUE TITLE
Access configuration name within spec file

### ISSUE THREAD

**Issue by ylac** [wix/detox#739]
#### Description

Would be great to be able to access the configuration name from within the spec files. I currently have a test that will break in either the debug or release variant of my app because of an app rating modal that will show up after a different number of times depending on the variant.

**Comment by rotemmiz** [comment]
Not sure you're going the right direction. Instead if the test having knowledge of the config, split your tests, or use repackager to add mocked confog. Anyway here's how you can do it, read the comments thread as well
https://stackoverflow.com/questions/49323694/how-to-get-the-currently-active-configuration-in-a-detox-test/49426119#49426119
