### ISSUE TITLE
Detox overrides React Native Navigation statusBarHidden

### ISSUE THREAD

**Issue by Gongreg** [wix/detox#741]
#### Description
Detox overrides React Native Navigation statusBarHidden with true.
When app is ran through detox the status bar is visible, even though it is set to false on RNN.

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 7.3.3
* React Native: 0.51
* Node: 8.7.0
* Device: Iphone 7
* Xcode: 9.3.1
* macOS: 10.13.3

**Comment by rotemmiz** [comment]
This doesn't make much sense. StatusBarHidden is an internal property of RNN, Detox doesn't touch it. 
The bug might be cussed by something else.  Can you provide a reproucable scenario ?

**Comment by LeoNatan** [comment]
I don't see how that can be, as Detox does not touch that part of the UI. Please provide a demo project.

**Comment by LeoNatan** [comment]
Reproduced in example project.

**Comment by LeoNatan** [comment]
You wound't believe. It's the touch indicator open source. 😂 Fixed
