### ISSUE TITLE
Where to locate these settings

### ISSUE THREAD

**Issue by heuism** [wix/Detox#747]
![image](https://user-images.githubusercontent.com/8481265/40294116-91500d08-5d17-11e8-89be-708ce44adc3d.png)
Hi guys, thanks for a wonderful framework.

I just happened to find these lines when looking for updating the frameworks as

It is not a bug, just want to figure out which version of detox has these features of video and screenshots as artifacts.

Kind regards.

**Comment by noomorph** [comment]
It is a work-in-progress feature at the moment. It is close to the finish but not stable enough to be used on CI.

If you wish to try it out locally and feel adventurous, you can try use directly this branch: https://github.com/wix/detox/tree/feature/test-artifacts?files=1

Please mind that this is an unreleased feature and I’m afraid we cannot provide a proper informational support for it.

The feature is expected to land to master very soon.
