### ISSUE TITLE
Device farming services issue. Need to test the app on multiple android and IOS devices.

### ISSUE THREAD

**Issue by abdulkhaliquem9** [wix/detox#750]
Is there any service which supports device farming to test the test suite on different devices. I am facing this problem as AWS (Amazon web services)  does not support device forming for react-native apps. 

Need help! Please inform or suggest if some body is using these kind of device farming third party services for testing the detox test cases.

**Comment by LeoNatan** [comment]
Hello,

This is not the place for such questions. This section is only for reporting Detox issues and making enhancement requests.
Also please note that Detox currently doesn’t have support for running on actual hardware devices, so this will limit the viability of a device farm for now.

Thanks
