### ISSUE TITLE
Is there any way to prioritise or sequencing the test file 

### ISSUE THREAD

**Issue by yogeshthanvi** [wix/detox#754]
I am trying to execute different test cases which I have created in different test files. I want to sequence these test file so that the execution will pick the test files on the basis of sequence . It would be really great if someone can help me on this.

**Comment by yershalom** [comment]
Hi @yogeshthanvi ,

You can give the files numbers, for example:
01-test.e2e.js
02-test.e2e.js
...

**Comment by yogeshthanvi** [comment]
Thanks @yershalom
