### ISSUE TITLE
Detox should allow us to set configuration outside package.json

### ISSUE THREAD

**Issue by Mokto** [wix/detox#758]
#### Description
Hi, it would be nice to configure detox outside package.json.

I get a `Cannot read property 'configurations' of undefined` when removing the configuration from package.json.

The reason behind this is that I have a lot of configurations, running them via a matrix Travis job.

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 7.3.7
* React Native: 0.55.4
* Node: 8
* Device: /
* Xcode: 9.3
* macOS: 10.13

Thanks !

**Comment by LeoNatan** [comment]
One workaround is to sed or echo into the package.json and change it according to your CI environment. We do this in our own test project. See here: https://github.com/wix/detox/blob/master/scripts/change_react_native_version.js
