### ISSUE TITLE
expose a method that returns the hierarchy for a given element

### ISSUE THREAD

**Issue by doronpr** [wix/detox#76]
Basically, we need the method to return GREYElementHierarchy for a given element which can be based on this code: https://github.com/wix/detox/commit/45a9c19cbf2d95338b6880b7b91689bd183aa62b#diff-6d470f1f5e297378206088228e32fd1cR17

JS Syntax should be something like this:
`element(by.id('someId')).printHierarchy();`

**Comment by LeoNatan** [comment]
Doesn't the hierarchy inspector in Xcode give this information? Is it not enough?

**Comment by talkol** [comment]
imagine a log in CI with this data.. cross platform for iOS and Android
I can see why it's useful

**Comment by LeoNatan** [comment]
I don't see this being useful outside of debug. A hierarchy is often huge and ugly. Why would you fill the CI log with it? On error, it should be printed. But per test?

**Comment by doronpr** [comment]
Yes. CI plus -
1. You don't need to have Xcode open 😉 
2. You don't need to put breakpoint etc. (if I want to get the hierarchy at a certain point in time deep inside the test)

**Comment by doronpr** [comment]
@LeoNatan I agree for the app level but hierarchy starting of a specific element down can be not so bad.

**Comment by rotemmiz** [comment]
As I see it, we should not let the user use this function, but include a print of it if a test fails.
This should be a part of a set of artifacts that detox should output upon a failed test:
1. video of the specific test
2. device log
3. hierarchy of that screen (On android there's an ability to extract `.hierarchy.uix` file, is there something similar in iOS?)

**Comment by LeoNatan** [comment]
We already print on failure.

**Comment by LeoNatan** [comment]
I don’t think this is needed. Detox is not a debugging tool. We already print the hierarchy in cases of failure, and we will improve the error messages to display a better information in the future.
