### ISSUE TITLE
Detox CLI: Replace commander with argparse

### ISSUE THREAD

**Issue by rotemmiz** [wix/Detox#767]
commander has [basic parsing issues](https://github.com/tj/commander.js/issues/400) which haven't been addressed for more than 3 years! 

Let's abandon it and move to something else.
argparse looks good enough, but it's open for suggestions. We need to up our game in detox-cli, code quality is not great, especially when things get a bit complicated, where we override package.json configuration etc.

**Comment by yershalom** [comment]
We can use this http://nodeca.github.io/argparse/ , looks like it solves the parsing issues.

**Comment by LeoNatan** [comment]
@noomorph Does the transition to yargs close this issue?

**Comment by noomorph** [comment]
Yes, thanks for checking! Closing it.
