### ISSUE TITLE
typeText failing on Invisible TextInput

### ISSUE THREAD

**Issue by jinshin1013** [wix/detox#769]
#### Description
I have a screen to enter received 6 digit code and the problem is that the design forced me to use device's keyboard but have custom container to show the code. Something like this.

<img width="331" alt="screen shot 2018-06-05 at 3 44 07 pm" src="https://user-images.githubusercontent.com/17612922/40957204-528c2892-68d7-11e8-97a6-ee355e43dc3f.png">

I do this by having a TextInput's style set to `display: none`. The problem is that when testing on Detox, it seems like it's not able to find the input. It works when not on detox, able to type in the code. 

On IOS, it's working without a problem. 

#### Steps to Reproduce
Put TextInput and set the style to `display: none` and on e2e test, `element(by.id('INPUT')).typeText('some text')`

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 7.4.0
* React Native: 0.55.4
* Node: 8.11.2
* Device: Android Emulator, Nexus_5X_API_27
* Xcode:
* macOS: 10.13.3

#### Device and verbose Detox logs
` 
send: {"type":"invoke","params":{"target":{"type":"Class","value":"com.wix.detox.espresso.EspressoDetox"},"method":"perform","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"android.support.test.espresso.Espresso"},"method":"onView","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"com.wix.detox.espresso.DetoxMatcher"},"method":"matcherForTestId","args":["CODE_INPUT"]}}]}},{"type":"Invocation","value":{"target":{"type":"Class","value":"android.support.test.espresso.action.ViewActions"},"method":"typeText","args":["111111"]}}]},"messageId":19}
 onMessage: {"messageId":19,"type":"error","params":{"error":"Error performing 'type text(111111)' on view 'with tag value: is \"CODE_INPUT\"'."}}
`

**Comment by abdulkhaliquem9** [comment]
@jinshin1013  try this
`await element(by.type('android.widget.EditText')).typeText('abcd');`
