### ISSUE TITLE
npm run build - builds the framework without any console messages

### ISSUE THREAD

**Issue by talkol** [wix/detox#77]
why did we add this step?

we should at least add a message that this is being built

**Comment by LeoNatan** [comment]
Due to npm ecosystem BS.
We needed the Detox source to be in a specific place in order to build a .framework on the client side in postinstall. Since that cannot be guaranteed (wonders of npm / yarn), we now build it before publish.

**Comment by LeoNatan** [comment]
Fixed with 03b0988
