### ISSUE TITLE
Headless test fails tap on RCTUITextField

### ISSUE THREAD

**Issue by mrozbarry** [wix/detox#772]
#### Description

When running a test in headless mode, finding a RCTUITextField and performing `.tap()` fails with the following exception:

```
    Error: Cannot perform action due to constraint(s) failure.
    Exception with Action: {
      "Action Name" : "Tap",
      "Element Description" : "<RCTUITextField:0x7fe6518ac600; AX=Y; AX.id='email'; AX.value='john.smith'; AX.frame={{46, 388}, {283, 25}}; AX.activationPoint={187.5, 400.5}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {283, 25}}; alpha=1; text=''>",
      "Failed Constraint(s)" : "interactable",
      "All Constraint(s)" : "(!(isSystemAlertViewShown) && ((respondsToSelector(isAccessibilityElement) && isAccessibilityElement) || kindOfClass('UIView')) && (enabled && !(((kindOfClass('UIView') || respondsToSelector(accessibilityContainer)) && ancestorThatMatches(!(enabled))))) && interactable)",
      "Recovery Suggestion" : "Adjust element properties so that it matches the failed constraint(s)."
    }

    [
      {
        "Description" : "Cannot perform action due to constraint(s) failure.",
        "Error Domain" : "com.google.earlgrey.ElementInteractionErrorDomain",
        "Error Code" : "1",
        "File Name" : "GREYBaseAction.m",
        "Function Name" : "-[GREYBaseAction satisfiesConstraintsForElement:error:]",
        "Line" : "66"
      }
    ]

      at Client.execute (../node_modules/detox/src/client/Client.js:72:13)
```

#### Steps to Reproduce

Write a react native test with a TextInput. `element(by.id('some-text-input-id')).tap()` will fail the test in _headless_ mode, but appears to work correctly when running in the simulator.

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 7.3.7
* React Native: 0.55.3
* Node: 9.11.1
* Device: iOS Simulator (iPhone 6)
* Xcode: 9.4
* macOS: 10.13.4 (17E202)

#### Device and verbose Detox logs

[text-input-headless-bug.log](https://github.com/wix/detox/files/2072326/text-input-headless-bug.log)

**Comment by rotemmiz** [comment]
Detox test suite runs in headless mode in CI, and occasionally locally as well. We could not recreate this issue.

If this issue indeed persists, please provide a working demo so we could take a look into that.
It could though, be something with Xcode 9.4.
