### ISSUE TITLE
Unable to select the date from 'UIPickerView'

### ISSUE THREAD

**Issue by zetendra** [wix/detox#778]
#### Description
Unable to select the date from the date picker. I am able to select the time and AM/PM

#### Steps to Reproduce
Its not working for the below case
element(by.type('UIPickerView')).setColumnToValue(0, Fri Jun 8');

Its working for the below
element(by.type('UIPickerView')).setColumnToValue(1, '11');
element(by.type('UIPickerView')).setColumnToValue(2, '22');
element(by.type('UIPickerView')).setColumnToValue(3, 'AM');

Can some one help me on this?

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 7.3.6
* React Native: 0.53.0
* Node: 8.11.2
* Device: iPhone 7
* Xcode: 9.1
* macOS: 
<img width="238" alt="datepicker" src="https://user-images.githubusercontent.com/1446116/41111511-c79ffc44-6a99-11e8-996b-54ae50a04755.png">

**Comment by rotemmiz** [comment]
Try to use the layout inspector and see the actual string rendered in the UI, is it exactly `Fri Jun 8` ?

**Comment by zetendra** [comment]
@rotemmiz  Thank you for responding to my query.

I used iOS inspector to find the exact format of the value, i see it is "Thu, Jun 14"
I tried the same in my code, i didnt work. I am attaching the screen shots and pasting the error

`await datePicker().setColumnToValue(0, `${day}, ${month} ${date}`);`

`     Error: Error: An action failed. Please refer to the error trace below.
Exception with Action: {
  "Action Name" : "Set picker column 0 to value 'Thu, Jun 14'",
  "Element Matcher" : "((kindOfClass('UIPickerView') && !(kindOfClass('RCTScrollView'))) || (kindOfClass('UIScrollView') && ((kindOfClass('UIView') || respondsToSelector(accessibilityContainer)) && ancestorThatMatches((kindOfClass('UIPickerView') && kindOfClass('RCTScrollView'))))))"
}

Error Trace: [
  {
    "Description" : "UIPickerView does not contain desired value!",
    "Error Domain" : "com.google.earlgrey.ElementInteractionErrorDomain",
    "Error Code" : "2",
    "File Name" : "GREYPickerAction.m",
    "Function Name" : "-[GREYPickerAction perform:error:]",
    "Line" : "120"
  }
]`

<img width="437" alt="screenshot-1" src="https://user-images.githubusercontent.com/1446116/41203042-a8c24ed2-6cef-11e8-9d2f-48a64ec8bb29.png">
<img width="244" alt="screenshot-2" src="https://user-images.githubusercontent.com/1446116/41203047-b07a6574-6cef-11e8-84c3-9764e15d858f.png">

**Comment by iegor-zabielin** [comment]
facing with the same issue, any look around?

**Comment by lochness42** [comment]
Try "Jun 14" or "14 Jun", coming from native XCUITest, that's actual values (depending on locale) that are under the hood and can be selected. I'm currently just looking into Detox so not sure whether it works with it, but I would suspect that it does.
