### ISSUE TITLE
detox-cli doesn't work on Yarn workspaces without nohoist

### ISSUE THREAD

**Issue by Zacqary** [wix/detox#779]
#### Description
Running the Detox CLI inside a subfolder within a Yarn workspace throws a `detox is not installed in this directory` error. This is because it's probably looking for `node_modules/detox` in the current directory, rather than in the hoisted `node_modules` at the monorepo root.

Adding `**/detox**` to the `nohoist` config prop in `package.json` works around this issue, but it'd be helpful if we didn't have to do this.

#### Steps to Reproduce
1. Create a [Yarn workspace](https://yarnpkg.com/lang/en/docs/workspaces/)
2. From within one of the workspace's sub-projects, run `yarn add --dev detox`. Note that it gets installed in `../node_modules` instead of `node_modules` because of Yarn's hoisting behavior.
3. Run `detox init`

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 7.4.0
* Node: 8.11.2
* macOS: 10.13.5

**Comment by rotemmiz** [comment]
Do you think you can create a PR to fix this?
