### ISSUE TITLE
Print Native View Hierarchy to console during a detox test.

### ISSUE THREAD

**Issue by eimius** [wix/Detox#802]
#### Description
When troubleshooting detox tests, sometimes I find a need to to see the view hierarchy (native). Currently I need to open xCode, run the project and check view inspector. I would like to have convenience method to print the layout/hierarchy which would be a simpler and faster way to inspect layout than to run the xCode project.

The general use case would be to call _print_ function in the middle of a _detox_ test (or right after failure of the test), which would print to the console current native view hierarchy, including props, like _accesibilityIdentifier_, in a standard way, e.g.
```
<UIScrollView frame="{{0, 20}, {320, 567}}" someNativeProperty= ...>
    <UIView ...
<UIScrollView/>
```
currently this functionality does not seem to be present. CC @rotemmiz

**Comment by LeoNatan** [comment]
Out of scope of the project. Please submit PR if you'd like to contribute.
