### ISSUE TITLE
Implement crash handling for Android

### ISSUE THREAD

**Issue by noomorph** [wix/Detox#809]
1. Implement `AppWillTerminateWithError` message sending in `detox/android` (implemented only on iOS).
2. This way (1) or another, improve quality of logs to help users understand what's going on in issues like these:

* https://github.com/wix/detox/issues/395
* https://github.com/wix/detox/issues/796
* https://github.com/wix/detox/issues/799 (although, it might be not related)

**Comment by LeoNatan** [comment]
This has been implemented by @d4vidi
