### ISSUE TITLE
dev scripts are broken

### ISSUE THREAD

**Issue by talkol** [wix/detox#81]
it is impossible to dev like this
debugging native in xcode is the only thing that now works
all the documented scripts in https://github.com/wix/detox/tree/master/detox
that help develop the JS part are now broken

**Comment by rotemmiz** [comment]
With new changes to project structure and the usage and lerna, I doubt we need them. I didn't need any of them this week.

**Comment by rotemmiz** [comment]
Dev scripts are dead. Look in the contribution guide for new instructions.
