### ISSUE TITLE
Installing detox nukes new React Native project

### ISSUE THREAD

**Issue by anchetaWern** [wix/detox#816]
#### Description
Not sure why, but everytime I install detox, my project folder is no longer recognized as a valid React Native project. That's a brand new React Native project which I got to run with `react-native run-ios` and `react-native run-android`. But right after installing Detox, I get this error:

```
Command `run-ios` unrecognized. Make sure that you have run `npm install` and that you are inside a react-native project.
```

I tried to execute `npm install` and then `react-native upgrade` to no avail.

#### Steps to Reproduce

1. Create a new RN project with:

```
react-native init ReactNativeTDD  --version react-native@0.55
```

2. Install detox:

```
npm install detox --save-dev
```

3. Run the project:

```
react-native run-ios
```

At this point, the project folder is no longer recognized as a valid RN project.

I specifically set it to RN version 0.55 because that's the latest RN version supported by Detox. 

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 8.0.0
* React Native: 2.0.1
* Node: 8.0.0
* Device: iOS simulator: iPhone 5s
* Xcode: 9.4
* macOS: High Sierra 10.13.5

#### Device and verbose Detox logs

Not applicable. I can't even run the project by normal means. But following the getting started guide (https://github.com/wix/detox/blob/master/docs/Introduction.GettingStarted.md) didn't succeed either.

**Comment by noomorph** [comment]
Not a Detox issue.
Either stick to `yarn add` instead of `npm install`, or uninstall `yarn`.
See:  https://github.com/yarnpkg/yarn/issues/5240

**Comment by anchetaWern** [comment]
@noomorph thanks for the quick reply! It's working now. I used yarn to install detox and mocha.
Perhaps update the getting started guide to use yarn instead of npm? https://github.com/wix/detox/blob/master/docs/Introduction.GettingStarted.md
