### ISSUE TITLE
[Docs] Screenshot comparison tool recommendations

### ISSUE THREAD

**Issue by etaiklein** [wix/detox#825]
Any recommendations for screenshot comparison tools? This would be great to include in the docs!

I want to upload my screenshots, compare them, and come out with a static link I can send to a designer or PM!

**Comment by LeoNatan** [comment]
I don't think this is a good approach. You are relying on many variables to have your screenshots, which you don't control: OS look and feel (fonts, colors, etc.), OS layout and RN layout. All of these are independent and can change with any environment change (such as minor OS version, new RN version, etc.).

**Comment by etaiklein** [comment]
@LeoNatan. I hear you! Changes to screenshots are certainly inevitable and a concern. I think there must be a sustainable way to expect certain changes, but also to catch and reject unexpected changes. This problem reminds me a lot of the discussion around [Jest Snapshot Testing](https://jestjs.io/docs/en/snapshot-testing).

**Comment by sibelius** [comment]
Loki provides this for storybook: https://github.com/oblador/loki

**Comment by LeoNatan** [comment]
Closing this issue. Maintaining such recommendations in docs is out of scope for the project.
