### ISSUE TITLE
Unable to build the demo project

### ISSUE THREAD

**Issue by bogobogo** [wix/detox#83]
Hey guys, 

I wanted to test the demo project so I:
1) Cloned the repository
2) Ran npm install both in the main file and in `detox/demo-react-native` 
3) Ran `./node_modules/.bin/detox-server.` and got the `server listening on localhost:8099...` message
4) Ran `export RCT_NO_LAUNCH_PACKAGER=true && xcodebuild -project ios/example.xcodeproj -scheme "example Release_Detox" -derivedDataPath ios/build -sdk iphonesimulator` in `detox/demo-react-native`.

 But than I got the following error message: `xcodebuild: error: The project named "example" does not contain a scheme named "example Release_Detox". The "-list" option can be used to find the names of the schemes in the project.`

Any suggestions? 
Thanks

**Comment by rotemmiz** [comment]
Hey @bogobogo 
I just [updated the example projects](https://github.com/wix/detox/commit/1d32dca5fe8bee25f1a0f692d3b48409c42c33f1) to be more user friendly, and documentation as well. Please take a look again, both `demo-react-native` and `demo-native-ios` now work.
