### ISSUE TITLE
Android: '-androidTest.apk' seems to get appended to a valid apk path

### ISSUE THREAD

**Issue by yamiscott** [wix/detox#830]
#### Description

Using Detox 8, if I set up an android build and get the detox build to successfully create the apk I need. Then set package json configuration for the android test to point at this apk and run detox test. Detox errors looking for the apk as it adds '-androidTest.apk' to the end of the path (stripping the existing .apk extension), resulting in never being able to run tests against that file.

apk file path (excluding personal path elements):

    /Users/[**REDACTED**]/android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk

package.json config:

    "android.emu.debug": {
        "binaryPath": "android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk",
        "build": "cd android && ./gradlew assembleAndroidTest -DtestBuildType=debug && cd ..",
        "type": "android.emulator",
        "name": "Nexus_4_Tester_"
      }

error:

    '/Users/[**REDACTED**]/android/app/build/outputs/apk/androidTest/debug/androidTest/app-debug-androidTest-androidTest.apk' could not be found, did you run './gradlew assembleAndroidTest' ?

The problem is inside APKPath.js line 23

    const testApkPath = path.join(tempPath.join(path.sep), 'androidTest', flavorDimensionsPath, buildType, `${originalApkPathObj.name}-androidTest${originalApkPathObj.ext}`);

As you can see (well you can if you head into the file), it splits on the last '-' and grabs the extension, then drops the 'variant' assuming it to be '-debug' or '-release', but without flavours, this isn't the case with a standard project.

It then rebuilds the path assuming the path is a flavoured build. Then finally it blanket adds a -androidTest on the end. Resulting in the error I'm seeing.

#### Steps to Reproduce

Basically follow the tutorial.

- install detox 8
- update gradle tools to 3+
- setup your android project with the androidTest flavour

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 8.0.x
* React Native: 0.55.4
* Node: 9.8.0
* Device: N/A
* Xcode: N/A
* macOS: 10.13.5

#### Device and verbose Detox logs

	 : /Users/scott.ewart/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop dev.bootcomplete
	3: stdout: 1
	 
	 : /Users/scott.ewart/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell input keyevent 82
	 : /Users/scott.ewart/Library/Android/sdk/platform-tools/adb -s emulator-5554 uninstall [REDACTED-BINARY-NAME].test
	5: stdout: Success
	 
	 : /Users/scott.ewart/Library/Android/sdk/platform-tools/adb -s emulator-5554 uninstall [REDACTED-BINARY-NAME].test.test
	 : /Users/scott.ewart/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop ro.build.version.sdk
	7: stdout: 25
	 
	8: /Users/scott.ewart/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -r -g /Users/[REDACTED-REPO-PATH]/android/app/build/outputs/apk/androidTest/debu /app-debug-androidTest.apk
	8: stdout: Success
	 
	 finalized artifacts successfully
	 FAIL  e2e/Home.spec.js
	  Home
	    ✕ should show the login page (5ms)

	  ● Home › should show the login page

	    '/Users/[REDACTED-REPO-PATH]/android/app/build/outputs/apk/androidTest/debug/androidTest/app-debug-androidTest-androidTest.apk' could not be found, did you run './gradlew assembleAndroidTest' ?

	at EmulatorDriver.getTestApkPath (../node_modules/detox/src/devices/AndroidDriver.js:62:13)
	at EmulatorDriver.installApp (../node_modules/detox/src/devices/AndroidDriver.js:55:43)

**Comment by neerajkumar-lad** [comment]
Hi


Run this and try :
**cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug && cd ..**

once succeed then check apk at **android/app/build/outputs/apk/debug/app-debug.apk**

Then run following
**detox build --configuration android.emu.debug && detox test --configuration android.emu.debug**

**_Node : this is for debug build_**

Following is my version:
xcode : 9.4.0
node: v10.6.0
Detox: v8.0.0
react-native-cli: 2.0.1
react-native: 0.53.3
Gradle : 3+

**Comment by neerajkumar-lad** [comment]
@yamiscott Any workaround till this get fix?

**Comment by neerajkumar-lad** [comment]
Hi 

Just want to update you that I have changed following in APKPath.js at line no 22

`const testApkPath = path.join(tempPath.join(path.sep),  buildType, 
${originalApkPathObj.name}${originalApkPathObj.ext}`);`

And following is the binarypath in package.json

 "binaryPath": "android/app/build/outputs/apk/debug/my.project-universal-debug.apk",
