### ISSUE TITLE
Detox incorrectly interacts with elements

### ISSUE THREAD

**Issue by LeoNatan** [wix/Detox#834]
This is an issue we found internally when testing [wix/react-native-navigation](https://github.com/wix/react-native-navigation).

When an overlay window is present, and it should swallow touches (returns a non-nil value from `hitTest:withEvent:`), elements on the main window still get tapped successfully (and incorrectly).

This stems from an Earl Grey issue (https://github.com/google/EarlGrey/issues/735):

> There seems to be an issue, where `isVisibleForInteraction:` returns `YES` despite there being a `UIWindow` instance that should take the touch of the user, rather than it reaching the element.
> 
> In addition to its current logic, the method should check first if there are other windows **visible and answering `hitTest:withEvent:` with a non-nil value**; if so, it should fail the interaction visibility check.

**Comment by LeoNatan** [comment]
CC @yogevbd

**Comment by cbrevik** [comment]
Wonder if this might be the same issue we encounter in our app using `react-navigation` (v2.17.0)? 

When we navigate from view `A`  to view `B`, then `B` is rendered over `A`. The problem is that both `A` & `B` contains components which have the same `testID`. Detox then complains with `Failed: Error: Multiple UI elements matched for the given criteria.`, even though view `A` is strictly not visible.

**Comment by LeoNatan** [comment]
@cbrevik This issue is unrelated. Here two native windows are incorrectly interacted with by Earl Grey.

Regarding your issue, there is nothing we can do about this. The framework you are using makes a mess. It is so wasteful to have all these views loaded. Please move to a better framework, such as `react-native-navigation`.

**Comment by LeoNatan** [comment]
I heard there are improvements in `react-navigation` that remove old views from the screen. Try using those improvements.

**Comment by LeoNatan** [comment]
It is now possible to specify a start position for X and Y, which should alleviate this problem. 

https://github.com/wix/Detox/blob/master/docs/APIRef.ActionsOnElement.md#scrollpixels-direction-startpositionxnan-startpositionynan
