### ISSUE TITLE
Screen-wide taps?

### ISSUE THREAD

**Issue by tachtevrenidis** [wix/detox#849]
Is there a way to tap on the screen somewhere (let's say the keyboard)? I see the the api to specify coordinates to tap but that is within the confines of a view.

I tried asking in on stack:

https://stackoverflow.com/questions/51218155/can-you-interact-with-the-app-in-test-using-absolute-positioning-in-detox

K

**Comment by LeoNatan** [comment]
Could you please specify what your needs are exactly? This is not an API we are looking to encourage.
