### ISSUE TITLE
e2e get stuck

### ISSUE THREAD

**Issue by ofiratt** [wix/detox#86]
please check "should show first screen" at https://github.com/ofiratt/react-native-movies-list/commit/4ba63bd829e640ab1e4ad83f1dc651594f9de978

**Comment by brentvatne** [comment]
same thing happens to me with a super simple assertion

```
const timeout = 20000;

describe('Example', () => {
  before(done => {
    simulator.relaunchApp(
      { url: 'exp://6b-dt8.notbrent.growler-prowler.exp.direct:80' },
      done
    );
  });

  it('should have welcome screen', () => {
    waitFor(element(by.label('Welcome to Exponent!')))
      .toBeVisible()
      .withTimeout(timeout);
    element(by.label('Got it')).tap();
    expect(element(by.label('Continue as a guest')).toBeVisible());
  });
});
```

**Comment by rotemmiz** [comment]
@ofiratt, the [issue is now fixed ](https://github.com/wix/detox/commit/98749ecb6905c8bb0afa7875ac2c15603d9ac99a)on your example, and will be released with detox 5.0.0 in the coming days. 

@brentvatne can you please supply a demo project with this crash, I want to test the fix on your use case as well

**Comment by rotemmiz** [comment]
summary of the issue: 
The crash is triggered when a `toBeVisible()` is called on RCTScrollView (React ScrollView or ListView).
In order for Earl Grey to test that the view is visible it makes some magic inside the view hierarchy, adding a subview to the view it asserts on, causing react-native to crash with RCTAssert “we should only have exactly one subview”.

**Comment by LeoNatan** [comment]
@rotemmiz Can we close this?

**Comment by brentvatne** [comment]
yup, this is fixed now
