### ISSUE TITLE
SecurityError: localStorage is not available for opaque origins

### ISSUE THREAD

**Issue by yogeshthanvi** [wix/detox#863]
Hi I am working detox test using Jest and I am getting the below issue recently . My RN version is 0.55.4 and using detox version 8.1.1 but the same tried with detox 8.0.0 version also and getting same issue. I am not sure this is a detox issue or not but if anyone have encountered such issue please let me know how to resolve this . Thanks 

configuration="ios.sim.debug" loglevel="verbose" artifactsLocation="artifacts/ios.sim.debug.2018-07-27 11-20-59Z" node_modules/.bin/jest e2e --config=e2e/config.json --maxWorkers=1 '--testNamePattern=^((?!:android:).)*$'
 FAIL  e2e/firstTest.spec.js
  ● Test suite failed to run

    SecurityError: localStorage is not available for opaque origins

      at Window.get localStorage [as localStorage] (../node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
          at Array.forEach (<anonymous>)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.888s
Ran all test suites matching /e2e/i with tests matching "^((?!:android:).)*$".
child_process.js:644
    throw err;
    ^

Error: Command failed: node_modules/.bin/jest e2e --config=e2e/config.json --maxWorkers=1 '--testNamePattern=^((?!:android:).)*$'
    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at runJest (/Users/yogesh/appname/node_modules/detox/local-cli/detox-test.js:150:6)
    at run (/Users/yogesh/appname/node_modules/detox/local-cli/detox-test.js:83:7)
    at Object.<anonymous> (/Users/yogesh/appname/node_modules/detox/local-cli/detox-test.js:213:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by rotemmiz** [comment]
What is the usecase of using jsdom with Detox ? I'm pretty sure this error is not related to Detox.

**Comment by rotemmiz** [comment]
Seems like this error also fails our unit test suite. Some dependency published a broken version (is it jsdom?)

**Comment by yogeshthanvi** [comment]
Hi all got the reason this due to new version of jest

**Comment by rotemmiz** [comment]
Can you add more details? Which version is broken?

**Comment by noomorph** [comment]
https://github.com/jsdom/jsdom/issues/2304

**Comment by rotemmiz** [comment]
Fix your config according to jsdom/jsdom#2304.
Use `"testEnvironment": "node"`
https://github.com/wix/detox/commit/3aaa79ddac8530bd2f9e82009e384aae202dd3b5

**Comment by XaviSmith** [comment]
I added both 
"testURL": "http://localhost/",
"testEnvironment": "node"

jest configuration in package.json and am still getting the error

**Comment by noomorph** [comment]
@XaviSmith examine the examples. You're adding it to the wrong place.

Where do you see jest configs in a package.json? There are no configs there.
https://github.com/wix/detox/blob/master/examples/demo-react-native-jest/package.json

Instead, you usually have `e2e` folder with `config.json` for Jest:
https://github.com/wix/detox/blob/master/examples/demo-react-native-jest/e2e/config.json

There you add it.

**Comment by yogeshthanvi** [comment]
It was happened with Jest ^23 version
