### ISSUE TITLE
CI: Switch Android emulator from google image to AOSP image

### ISSUE THREAD

**Issue by rotemmiz** [wix/detox#869]
Currently, tests in Jenkins run on `system-images;android-26;google_apis_playstore;x86` image. This image has issues with `Pixel Launcher`, which causes tons of ANRs even when in background.

Let's switch to a clean AOSP image `system-images;android-26;default;x86`, I tested its launcher today and it seems much more stable.

Good kitty! (default system image)
![screen shot 2018-07-31 at 19 06 22](https://user-images.githubusercontent.com/1361404/43472092-445f6fa0-94f5-11e8-8df1-3d0f26c8b622.png)

Bad kitty! (google apis system image)
![screen shot 2018-07-31 at 19 06 11](https://user-images.githubusercontent.com/1361404/43472093-4483ba54-94f5-11e8-9d52-ac5a13225726.png)

**Comment by yershalom** [comment]
Hi @rotemmiz ,
Since we are running few other projects on the same CI, can I create it by this name convention `Nexus_5X_API_26_DEFAULT` for example?

**Comment by rotemmiz** [comment]
Sounds great

**Comment by rotemmiz** [comment]
Not sure if `system-images;android-26;google_apis;x86_64` has pixel launcher, we may need to check. 
Anyway,  AOSP image has a cleaner adb logcat output, without crazy, spamming, never solved, google API crashes.

**Comment by rotemmiz** [comment]
For the sake of documentation.
Adb is missbehaving (stuck) on  both `system-images;android-28;default;x86_64` and `system-images;android-28;default;x86` on Linux.

There are no default images for API 25, 26,27.
Best working option is only `system-images;android-24;default;x86`
