### ISSUE TITLE
Allow override of simulator name?

### ISSUE THREAD

**Issue by robbiemccorkell** [wix/detox#875]
I was wondering if you all would be open to the idea of allowing the simulator name to be parameterised in CI. We would quite like to run our tests multiple times with the same build configuration but a different simulator device.

I was thinking we could add a new CI parameter called `--name` or `--deviceName` for this that would override the one defined in the `package.json` config. E.g:

```
detox build --configuration ios.sim.release --name 'iPhone X'
```

I would be more than happy to submit a PR to add this if you think it's a good idea.

Thanks

**Comment by noomorph** [comment]
I'm not sure about @rotemmiz , but personally I like this idea about `--deviceName` parameter. Can be handy for quick command line runs or more sophisticated scripts...

**Comment by robbiemccorkell** [comment]
Cool ok thanks. I'll add a quick PR later.

**Comment by robbiemccorkell** [comment]
Also I was being dumb in my example above, obviously I meant for this to be on the `test` command:

```
detox test --configuration ios.sim.release --deviceName 'iPhone X'
```

But you know what I mean.

**Comment by robbiemccorkell** [comment]
Submitted in #878
