### ISSUE TITLE
 GitLab CI Detox integration

### ISSUE THREAD

**Issue by burhanyilmaz** [wix/detox#877]
Is there any boilerplate  `GitLab CI` for detox?
I found this https://gist.github.com/adam-stasiak/1b2dd63f3d0963a38d46aaea73631072. it is not work :/

**Comment by noomorph** [comment]
Frankly speaking, I don't think that this is a properly created issue:

> Is there any boilerplate GitLab CI for detox?
> I found this https://gist.github.com/adam-stasiak/1b2dd63f3d0963a38d46aaea73631072. it is not work :/

However, as you might see in the documentation, there is no boilerplate for `GitLab CI` currently there:
https://github.com/wix/detox/blob/master/docs/Guide.RunningOnCI.md

So, the answer is *no*, there is no such boilerplate in the official detox documentation.

However, you are welcome:

1) to work on GitLab CI integration with detox;
2) figure out what is wrong for that script;
3) fix the issues;
4) create a tiny sample project with Detox+GitLab CI intergration;
5) open-source it to GitHub as a reference;
6) and, finally, contribute to the documentation:

https://github.com/wix/detox/blob/master/docs/Guide.RunningOnCI.md

Thanks.
