### ISSUE TITLE
Push Notification won't works with the iOS Simulator 

### ISSUE THREAD

**Issue by yogeshthanvi** [wix/detox#879]
Detox Version : 8.1.1
React Native Version : 55

I am using the commands to generate the PN on simulators as detox won't support real devices but I am not able to get any PN . I have used the Example template to create JSON for Push notification 
{
	"trigger": {
		"type": "push"
	},
	"title": "From push",
	"subtitle": "Subtitle",
	"body": "Body",
	"badge": 1,
	"payload": {
		"key1": "value1",
		"key2": "value2"
	},
	"category": "bundle Identifier",
	"content-available": 0,
	"action-identifier": "default"
}

I also checked the properties and ram getting proper value , even the test cases are getting passed but didn't receive any push notification . Can any one help on this

**Comment by vonovak** [comment]
Please see the docs https://github.com/wix/detox/blob/master/docs/APIRef.MockingUserNotifications.md

namely:

> NOTE: The mocking mechanism will not mimic the UI of a user notification. Instead, it will only simulate the flow of a user-selected notifications.
