### ISSUE TITLE
Detox catches SIGINT and SIGTERM, causing long running subprocesses to never end

### ISSUE THREAD

**Issue by rotemmiz** [wix/detox#881]
Detox catches SIGINT and SIGTERM to be able to cleanup artifacts currently being recorded on Android emualtors (and probably more things) before termination
https://github.com/wix/detox/blob/master/detox/src/utils/onTerminate.js#L4

Not sure if this is an issue with node, but currently, when a user tries to terminate the test (ctrl+c), any long running subprocess/server will continue running and will need to be forcefully killed. Node will not inform/kill those subprocesses/servers.

I think we should drop `onTerminate` event altogether, and keep things dirty if a user stops, and act exactly like test runners expect tests to run. This is not ideal, but will keep us out of trouble.

Instead of cleaning up upon `onTerminate`, we may cleanup the emulator from half baked artifacts during `deviceDriver.acquireFreeDevice`.

**Comment by LeoNatan** [comment]
This is not good and should be handled quickly.

**Comment by noomorph** [comment]
Sure.

**Comment by LeoNatan** [comment]
Hi guys,

Can this issue be closed now that merge? @rotemmiz @noomorph

**Comment by noomorph** [comment]
Yes and no. But let's close. There is another problem to solve (cleaning artifacts junk that you get if you Ctrl+C the runner), however.

**Comment by LeoNatan** [comment]
Why is there only one catch for signals? Can't we catch and then "rethrow"?

**Comment by noomorph** [comment]
I have not found a way in Node.js so far :/

**Comment by LeoNatan** [comment]
Node🤦‍♂️
