### ISSUE TITLE
docs: takeScreenshot from tests?

### ISSUE THREAD

**Issue by compojoom** [wix/detox#892]
I scanned the docs and this doesn't seem to be mentioned anywhere. Now with detox 8 - are we able to call the screenshot taking API anywhere inside of test? The automatic screenshots are taken at the beginning and at the end of a test, but I want to capture some more screenshots in the middle of a test. 

this comment here https://github.com/wix/detox/pull/541#issuecomment-362167447 mentions a _takeScreenshot(), but this is not existing anymore. Is it possible to take a screenshot in the middle of a test and if yes, can we document this

**Comment by noomorph** [comment]
See #807
