### ISSUE TITLE
Detox Primitive ReferenceError: Element is not defined

### ISSUE THREAD

**Issue by Kielan** [wix/detox#893]
potentially related issues
https://github.com/wix/detox/issues/795

#### Description
I am new to using Detox but it appears to me that primitives are not being properly set as jest globals following the setup and usage guides I could find in the documentation. I get the code in the console ReferenceError: element is not defined. Maybe there is a way to improve the logging to clarify these config errors for good

#### Repo to reproduce:
https://github.com/Kielan/OnyxWalletReactNative

Detox v8.1.6^
Node v8.9.4, 
React Native v0.56.0
Device iphone 7 sim release and debug,
Xcode v and macOS Versions
 

#### Device and verbose Detox logs

    ReferenceError: element is not defined

      14 | })
      15 | 
    > 16 | it(':ios: shows splash screen and then login', async () => {
         |                                                ^
      17 |   await expect(element(by.label('animateLoginLabel'))).toBeVisible()

**Comment by LeoNatan** [comment]
This is a usage question.
