### ISSUE TITLE
Handle iOS permission dialogs

### ISSUE THREAD

**Issue by talkol** [wix/detox#9]
EarlGrey has a hard time dealing with them since they're external to the app

https://github.com/google/EarlGrey/issues/55

this thread offers some interesting workarounds.. we can add them directly into detox

**Comment by talkol** [comment]
@LeoNatan this is not urgent since it's not for Version 1 milestone

**Comment by DanielZlotin** [comment]
Urgent. All tests fail once you get the dialog (for example notifications permissions usually happen on app launch or close to it)

**Comment by LeoNatan** [comment]
@DanielZlotin This is a big problem in Earl Grey also, due to in-process architecture. There seem to be several workarounds, including setting a DB file in the simulator subsystem to automatically allow permissions.

**Comment by LeoNatan** [comment]
http://stackoverflow.com/questions/28443578/ios-permission-alerts-removing-or-surpressing

**Comment by yedidyak** [comment]
If you can swizzle the permissions on demand at runtime, and have some JS API to mange it per test that would be best. If you could `expect` it that would be better. Something like:
`expect(permission.photos).toBeRequested()`
`allowNextPermission()`
`rejectNextPermission()`

**Comment by LeoNatan** [comment]
@yedidyak This will be a big issue to fix which will take much time. In the meantime, do not stop working on tests. Instead, mock the permission API to return success or failure.

**Comment by yedidyak** [comment]
@LeoNatan That's possible in some cases, but in others the permission itself is necessary for the functionality.

**Comment by LeoNatan** [comment]
I have decided to go against swizzling APIs. It just does not scale, as more and more APIs are added each year. Detox is a testing framework for native apps, not just the small subset of APIs wrapped in RN.

Instead, I have created [`applesimutils`](https://github.com/wix/AppleSimulatorUtils) and [DetoxHelper](https://github.com/wix/detox/tree/master/detox/ios/DetoxHelper/DetoxHelper).

`applesimutils` allows setting permissions before a process is launched, and thus can be used together with `relaunchApp` API to set permissions.

DetoxHelper is not ready for prime time just yet, but it intended to support switching of permissions on the fly.

For now, let's integrate `applesimutils` with Detox.

**Comment by irrigator** [comment]
Kudos for this ! @LeoNatan Has ```applesimutils``` been integrated into Detox yet? If not, how can we use it to set permissions before Detox test?

**Comment by LeoNatan** [comment]
@irrigator Unfortunately, integrating `applesimutils` with Detox is still not ready. In the mean time, you can indeed use `applesimutils` before running your Detox test. Just make sure to pass the same simulator name (or preferrably, unique identifier), and set the permissions as you need. You can read the usage in the readme for `applesimutils`; it should be simple and intuitive.

**Comment by mobinni** [comment]
@LeoNatan I used applesimutils in the following manner:

```function setPermissions(permissions) {
  cp.execSync(
    `applesimutils \\
    --simulator "1991C14B-9892-44E8-BCEF-EA63F308972E" \\
    --bundle io.rangle.starter.app \\
    --setPermissions "${permissions.join()}"`,
    {
      stdio: 'inherit',
    },
  );
}


beforeAll(async () => {
  await detox.init(config);
  await setPermissions(['camera=YES']);
}, 25000);```

It causes the simulator to refresh going black with a spinner then when the simulator is back on the app is closed and the tests fail. How would you suggest running it before the tests?

**Comment by LeoNatan** [comment]
Yes, you need to launch the app. 
This is being developed now, and we will have an official support soon. Stay tuned.

**Comment by ptomasroos** [comment]
Great news @LeoNatan !

**Comment by DanielMSchmidt** [comment]
@LeoNatan How far is this? As a current workaround I take the simulator ID from the global device object in the function mentioned by @mobinni but this approach feels a little hacky to me 👍

**Comment by LeoNatan** [comment]
In development. Cannot comment on how long it will take, as I am not the one developing it, but it is in active development and is coming soon.

**Comment by LeoNatan** [comment]
Guys, support has landed in Detox for this feature. For now, we have not yet updated the documentation yet, but you can see the syntax here:
https://github.com/wix/detox/blob/master/detox/test/e2e/l-permissions.js

As described in the [Getting Started document](https://github.com/wix/detox/blob/master/docs/Introduction.GettingStarted.md#4-install-applesimutils), you need to install `applesimutils` for this.

**Comment by rotemmiz** [comment]
Docs are here: https://github.com/wix/detox/blob/master/docs/APIRef.DeviceObjectAPI.md#devicerelaunchappparams

**Comment by stereodenis** [comment]
@LeoNatan @rotemmiz how to initial run app with permissions?

**Comment by Monte9** [comment]
@LeoNatan Thanks a lot for adding this feature! 💯 It works great!

**Comment by LeoNatan** [comment]
@Monte9 Cheers, thanks for the kind words!

**Comment by yogeshthanvi** [comment]
Can anyone give me an example to approve location permission

**Comment by LeoNatan** [comment]
RTFM

**Comment by menasameh** [comment]
@yogeshthanvi the options for the location permission are: 
> location=always|inuse|never

so you use it as the following
await device.launchApp({ permissions: { location: 'always' } })

**Comment by DanielMSchmidt** [comment]
@yogeshthanvi Could you tell me where you have looked for this information? Might make sense to add this info right there to help the next person even faster 🤔

**Comment by yogeshthanvi** [comment]
@menasameh Thanks man , love you

**Comment by LeoNatan** [comment]
Please make sure to read the documentation.

**Comment by suvodeep-pyne** [comment]
For ease of other users:
```
describe(':ios: Permissions', () => {

  it('Permissions is granted', async () => {
    await device.launchApp({permissions: {calendar: 'YES'}});
    await element(by.text('Permissions')).tap();
    await expect(element(by.text('granted'))).toBeVisible();
  });

  it('Permissions denied', async () => {
    await device.launchApp({permissions: {calendar: 'NO'}});
    await element(by.text('Permissions')).tap();
    await expect(element(by.text('denied'))).toBeVisible();
  });
});
```
Quoting from https://github.com/wix/detox/blob/master/detox/test/e2e/13.permissions.test.js
