### ISSUE TITLE
point to a single configuration file

### ISSUE THREAD

**Issue by oreporan** [wix/Detox#901]
#### Description
Currently it seems that detox allows configuring only in the `package.json` of the project. But using a mono-repo (lerna), we want to run detox in specific packages. However I don't want to duplicate our detox config in each package.json
I've seen a discussion in https://github.com/wix/detox/issues/175 but it doesn't mention creating the file outside the `package.json`
Possible solution:

`detox-config.json`

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 8.0.0
* Node: 8.9.4

**Comment by tomatobrown** [comment]
you can do this in the current build
```
const config = require('../config').detox;
await detox.init(config);
```

**Comment by oreporan** [comment]
Well wouldn't that be just for the `test` command?
I'm talking about 

`detox build --configuration`

**Comment by oreporan** [comment]
Unless I put a detox and configuration object in my `package.json`, I still get:

```js
 if (_.size(config.configurations) === 1) {
                    ^
TypeError: Cannot read property 'configurations' of undefined
    at getDefaultConfiguration (/Users/ore/env/dev/repos/x/node_modules/detox/local-cli/detox-test.js:207:21)
    at Object.<anonymous> (/Users/ore/env/dev/repos/x/node_modules/detox/local-cli/detox-test.js:23:151)
```js

**Comment by oreporan** [comment]
This is due to 

detox/local-cli.js
`const config = require(path.join(process.cwd(), 'package.json')).detox;`

**Comment by rotemmiz** [comment]
You're right, we should give an opportunity for users to get an external config file, not only in package.json. 
Logic may try getting config from package.json, and failover to a config file (or vice versa).

A PR is most welcome!

**Comment by oreporan** [comment]
Trying to run `scripts/ci.ios.sh` in the repo results in error:

```
> detox-test@0.0.1 build:ios /Users/ore/env/dev/open_source/detox/detox/test
> detox build --configuration ios.sim.release

/Users/ore/env/dev/open_source/detox/detox/local-cli/detox-build.js:28
  throw new Error(`Could not find build script in detox.configurations["${program.configuration}"]`);
  ^

Error: Could not find build script in detox.configurations["ios.sim.release"]
```

**Comment by noomorph** [comment]
@opherg , check what's inside of your `detox/tests/package.json`. Maybe you modified something?

**Comment by oreporan** [comment]
Sorry, I found the issue and removed the comment :)

**Comment by oreporan** [comment]
Made a PR
https://github.com/wix/detox/pull/906

**Comment by LeoNatan** [comment]
Closing in favor of #1238
