### ISSUE TITLE
[iOS] Fail to type text with azerty Keyboard 

### ISSUE THREAD

**Issue by padupuy** [wix/detox#92]
Hello,

I use the latest version of your library detox 4.3.1, detox-server 1.1.0 with RN 0.40.0.

I am a french user and use a physical azerty keyboard and my keyboard settings are set on French / numeric.
❌ When I try to execute a simple test, it fails miserably because the robot couldn't find the keys 😂.
✅ To pass the test to green, i have to change my keyboard settings to 'US International'

<img width="315" alt="capture d ecran 2017-03-03 a 18 29 36" src="https://cloud.githubusercontent.com/assets/715255/23561640/624105a2-003f-11e7-941e-d03a8084e3ee.png">

Here is the error log

```
Error: Cannot find UI element.
Exception with Action: {
  "Action Name" : "Type 'admin'",
  "Element Matcher" : "(respondsToSelector(accessibilityIdentifier) && accessibilityID('username'))",
  "Recovery Suggestion" : "Check if element exists in the UI, modify assert criteria, or adjust the matcher"
}

Error Trace: [
  {
    "Description" : "Failed to type string 'admin', because key [K] could not be found on the keyboard.",
    "Description Glossary" :     {
      "K" : "a"
    },
    "Domain" : "com.google.earlgrey.ElementInteractionErrorDomain",
    "Code" : "0",
    "File Name" : "GREYKeyboard.m",
    "Function Name" : "+[GREYKeyboard grey_setErrorForkeyNotFoundWithAccessibilityLabel:forTypingString:error:]",
    "Line" : "465"
  }
]
```

Here is my code
```
describe('Login', function () {
    it('should login', function () {
        element(by.id('username')).typeText('admin');
        element(by.id('password')).typeText('admin');
        element(by.label('connectButton')).tap();
    });
});
```

**Comment by gregorybesson** [comment]
This bug seems related to this one https://github.com/google/EarlGrey/issues/31 from the EarlGrey Project.

**Comment by rotemmiz** [comment]
Hey @padupuy , 
As @gregorybesson said, this is indeed an issue with EarlGrey. The implementation of `typeText` actually taps the character sequence on the device's virtual keyboard. 
This issue can be easily avoided by using `replaceText` instead of `typeText`.

Try this instead, it should work no matter what your keyboard setup is.
```
describe('Login', function () {
    it('should login', function () {
        element(by.id('username')).replaceText('admin');
        element(by.id('password')).replaceText('admin');
        element(by.label('connectButton')).tap();
    });
});
```

**Comment by padupuy** [comment]
@rotemmiz thank's for the tips, it works !

**Comment by LeoNatan** [comment]
@rotemmiz Perhaps we should keep this open and open an issue with Earl Grey?

**Comment by tirodkar** [comment]
Hello Folks, in case you need to type with a different language or a different keyboard, please take a look at using grey_replaceText() instead of grey_typetext(). Do tell us if there any issues.
