### ISSUE TITLE
replaceText duplicates the beginning of the pasted string

### ISSUE THREAD

**Issue by dat00ste** [wix/Detox#921]
#### Description
When I use replaceText in an empty textfield, the beginning of the string that should be pasted is duplicated. 
For example:  
element(by.id(elementId)).replaceText('abcdefgh');
paste the text "abcdefgabcdefgh" into the textfield. 

Detox version: 8.2.3

Update: We use typeText instead and that works fine since the field is always empty to begin with. I just thought this was a really strange bug :)

#### Steps to Reproduce

Use replaceText in an empty textfield. IT seems to work fine if the field is not empty to begin with.
It seems the error occur only when there is enough signs in the string. (>7 (?), but it seems a bit random)

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 8.2.3
* React Native: 0.55.3
* Node: 9.4.0
* Device: iPhone 7 (simulator)

**Comment by rengarima** [comment]
We used a workaround by adding delete before replacing 
```
await replaceText(Elements, "\b\b\b\b\b\b\b\b\b");
```

**Comment by dat00ste** [comment]
Thanks @rengarima , but not sure if that helps, since the problem is when using replace in an empty textField. We use typeText as a workaround  :).

**Comment by rengarima** [comment]
Yeah, the workaround was for the issue you faced - It was a bit too long ago so don't remember exactly why it worked we had debounced some of the action on the elements and replaceText was too fast or something. Try and see if it works - I always find typeText to be too slow and clunky.

**Comment by beckinfonet** [comment]
`it('should show membership scan screen after tap', async () => {
    await element(by.id('membership_btn')).tap();
    await expect(element(by.id('membership_scan'))).toBeVisible();
    await element(by.id('manual_entry')).tap();
    await expect(element(by.id('mbrshp_id_entry'))).toBeVisible();
    await element(by.id('mbrshp_num')).clearText();
    await element(by.id('mbrshp_num')).replaceText('10142120817317076');
  });
`

**typeText is not working in this example, replaceText works, but it repeats the beginning of the string. In the case of using typeText is giving me this error:**

`Error: Error: An action failed. Please refer to the error trace below.
Exception with Action: {
  "Action Name":  "Type '10142120817317076'",
  "Element Matcher":  "((!(kindOfClass('RCTScrollView')) && (respondsToSelector(accessibilityIdentifier) && accessibilityID('mbrshp_num'))) || (((kindOfClass('UIView') || respondsToSelector(accessibilityContainer)) && parentThatMatches(kindOfClass('RCTScrollView'))) && ((kindOfClass('UIView') || respondsToSelector(accessibilityContainer)) && parentThatMatches((respondsToSelector(accessibilityIdentifier) && accessibilityID('mbrshp_num'))))))"
}


Error Trace: [
  {
    "Description":  "Failed to type string '10142120817317076', because keyboard was not shown on screen.",
    "Error Domain":  "com.google.earlgrey.ElementInteractionErrorDomain",
    "Error Code":  "2",
    "File Name":  "GREYKeyboard.m",
    "Function Name":  "+[GREYKeyboard typeString:inFirstResponder:error:]",
    "Line":  "191"
  }
]
`

**I added the clearText() hoping it would eliminate the duplicate string, but not helping. What is your advice?**

**Comment by beckinfonet** [comment]
@dat00ste , yes, it is enabled. Does the code that I wrote seems to be correct?

**Comment by dat00ste** [comment]
@beckinfonet , I'm no expert in this, so I'm not really sure, but it looks ok I guess. One more thing I could think of is that you might need to tap the textfield before using typeText:

Try this:
await element(by.id('mbrshp_num')).tap(); 
await element(by.id('mbrshp_num')).typeText('10142120817317076'); });

**Comment by beckinfonet** [comment]
I also thought the same thing, but it didn't fix it. I believe typeText and replaceText have tap feature that gets executed before typing or replacing the text. For some reason the cursor is being placed in between 4th and 5th digit, not at the end the string. That is so weird.

**Comment by dat00ste** [comment]
@beckinfonet Then I don't think I can help you unfortunately :(. I agree, really strange.

**Comment by beckinfonet** [comment]
I don't know what has changed, it is working now.

**Comment by tonlen** [comment]
@beckinfonet I have the same issues as you.

**Comment by tonlen** [comment]
I think it's a "maxLength" issue

**Comment by rotemmiz** [comment]
Is this issue still relevant? If yes, please provide a ` detox test --loglevel trace` log. If not, you're free to close it.
