### ISSUE TITLE
detox test crash always when using atIndex()

### ISSUE THREAD

**Issue by hajermay** [wix/detox#923]
- ####

 Description
this is a parent component:
return (
           <FlatList
        **renderItem={({ item,  index }) => ( <Post  index={index} /> )} />**
);
 and this is the child where i should add test id on one item of the flat list
  <TouchableOpacity
      **testID={`likeButton ${index}`}**
      activeOpacity={1}
      onPress={() => { }}
      style={inModal ? styles.modalActionIconContainer : styles.actionIconContainer}>
      <View style={inModal ? styles.modalLeftIcon : styles.leftIcon}>
          <Icon color={liked ? Colors.blue : Colors.grey} name="thumb-up" style={styles.icon} size={20} 
          /><Text style={styles.actionText}>Like</Text>
      </View>
    </TouchableOpacity>

and this is the detox test 
it('should like post', async () => {
    **await element(by.text('likeButton')).atIndex(0).tap();**
  });

**Comment by juand89** [comment]
your test is wrong it should be 
```
it('should like post', async () => {
await element(by.id('likeButton0')).tap();
});

```
in order to work
