### ISSUE TITLE
Android - openURL is broken

### ISSUE THREAD

**Issue by stevechun** [wix/Detox#925]
Android - openURL is broken

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 9.0.1
* React Native: 0.55.3
* Node: 9.3.0
* Java: 1.8.0_172
* Device: Android Emulator
* Xcode: 9.4.1
* macOS: 10.13.6 High Sierra

#### Description

When `device.openUrl` is used to open the app with deeplink, there are 2 issues.

1. Error triggered with `device.openUrl` is used after `device.launch` due to openUrl not being triggered correctly (The deeplink is not triggered and test fails).

2. When using `device.openUrl` to open the app with deeplink, the following error gets triggered even the deeplink is opened properly. This is a known issue on 

```
Error: Could not launch intent Intent { act=android.intent.action.VIEW dat=scheme://deeplink/url flg=0x10000000 cmp=com.package.app/.MainActivity } within 45 seconds. Perhaps the main thread has not gone idle within a reasonable amount of time? There could be an animation or something constantly repainting the screen. Or the activity is doing network calls on creation? See the threaddump logs. For your reference the last time the event queue was idle before your activity launch request was 1523458140008 and now the last time the queue went idle was: 1523458185572. If these numbers are the same your activity might be hogging the event queue.

```

#### Analysis

For the issue 1, `device.sendToHome()` is required to be called before calling `device.openUrl` to make it work. We can probably make this to be a mandatory action for the openUrl func?

For the issue 2, looks like it is an issue related to the espresso library dependency. The workaround in the [old issue](https://github.com/wix/detox/issues/669) fixes the problem.

I can create a PR if this is something that we want to have as a workaround in place.

**Comment by noomorph** [comment]
@stevechun, thanks for your thorough investigation. I think it makes sense.
Could you elaborate on *espresso library dependency* part, what did you mean?

**Comment by stevechun** [comment]
@noomorph It was related to the update on the espresso library as it was working fine on the old version AFAIR. But didn't get a chance to go deeper.

**Comment by robertofrontado** [comment]
Sadly this is still an issue

**Comment by avanderberg** [comment]
I can use `openURL` successfully since https://github.com/wix/Detox/releases/tag/14.9.0
