### ISSUE TITLE
launchApp url params not being parsed correctly and ignored

### ISSUE THREAD

**Issue by stevechun** [wix/Detox#926]
#### Description

Try to use `device.launchApp` with deeplink URL that has more than 2 params

```
await device.launchApp({
	url:
        'scheme://deeplink/url?param1=a&param2=b&param3=c',
	newInstance: true,
});
```

Only the first param (`param1`) is taken into account to launch the app with URL, and `param2` and `param3` are cut and ignored.

#### Workaround

Use `device.openUrl` after simple `device.launchApp`.

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 9.0.1, 8.2.3
* React Native: 0.55.3
* Node: 9.3.0
* Device: Android Emulator
* Xcode: 9.4.1
* macOS: 10.13.6 High Sierra

**Comment by noomorph** [comment]
I'll check this on the next week. Thanks!
