### ISSUE TITLE
[RN56] Emulator cannot connect to detox server without relaunching an application

### ISSUE THREAD

**Issue by nezaidu** [wix/Detox#930]
#### Description
I am actively developing my tests, and i would detox to pick execution of a certain test if it fails where it left, because sometimes test fail nearly at the end, so it makes sense not to relauch the app, but to proceed executing test where it left, and then to execute as a whole after it was fixed.

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: ^9.0.1
* React Native: 0.56.0
* Node: v8.3.0
* Device: iPhone 6s 12 iOS
* Xcode: Xcode 10
* macOS: Mojave

#### Steps to Reproduce

I installed the application manually in debug mode, then i launched my test like this:
![image](https://user-images.githubusercontent.com/3225817/45221559-774d0e80-b2ba-11e8-9110-f4b9bed5bb51.png)
Everything works fine, application is lauched, testee is connected, test passes. But then i would like to make some modifications to my tests, but i would like detox to proceed where it left, so i try to run my test again without relaunching the application as to not to change the application state:
![image](https://user-images.githubusercontent.com/3225817/45221602-a5325300-b2ba-11e8-9644-0cb37c2e6d26.png)
Then i launch like this:
```
detox test -c ios.emu.release --loglevel verbose --reuse
```
and this is the logcat:
```
detox[27185] INFO:  [DetoxServer.js] server listening on localhost:59529...
detox[27185] DEBUG: [AsyncWebSocket.js/WEBSOCKET_OPEN] opened web socket to: ws://localhost:59529
detox[27185] DEBUG: [DetoxServer.js/LOGIN] role=tester, sessionId=f75ca835-2abb-1eb4-6374-35e5ad4f4dc7
detox[27185] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=tester, sessionId=f75ca835-2abb-1eb4-6374-35e5ad4f4dc7
detox[27185] DEBUG: [exec.js/EXEC_CMD, #0] /usr/bin/xcrun simctl list -j
detox[27185] DEBUG: [exec.js/EXEC_CMD, #1] applesimutils --list --byType "iPhone 6s" --byOS "12.0"
detox[27185] DEBUG: [exec.js/EXEC_TRY, #1] Searching for device matching iPhone 6s...
detox[27185] DEBUG: [exec.js/EXEC_CMD, #2] applesimutils --list --byId "D2CA897A-D50B-4F70-8A57-4133811F4309"
  Run clean application with notification/location permissions, sign up provider
detox[27185] DEBUG: [exec.js/EXEC_CMD, #3] /bin/cat /dev/null >/Users/bla/Library/Developer/CoreSimulator/Devices/D2CA897A-D50B-4F70-8A57-4133811F4309/data/tmp/detox.last_launch_app_log.out 2>/Users/bla/Library/Developer/CoreSimulator/Devices/D2CA897A-D50B-4F70-8A57-4133811F4309/data/tmp/detox.last_launch_app_log.err && SIMCTL_CHILD_DYLD_INSERT_LIBRARIES="/Users/bla/Library/Detox/ios/0a41f260686a7308c291eaa763a6dc04b8dcab52/Detox.framework/Detox" /usr/bin/xcrun simctl launch --stdout=/tmp/detox.last_launch_app_log.out --stderr=/tmp/detox.last_launch_app_log.err D2CA897A-D50B-4F70-8A57-4133811F4309 org.reactjs.native.example.bla2 --args -detoxServer ws://localhost:59529 -detoxSessionId f75ca835-2abb-1eb4-6374-35e5ad4f4dc7
detox[27185] DEBUG: [exec.js/EXEC_TRY, #3] Launching org.reactjs.native.example.bla2...
detox[27185] DEBUG: [exec.js/EXEC_SUCCESS, #3] org.reactjs.native.example.bla2 launched. The stdout and stderr logs were recreated, you can watch them with:
        tail -F /Users/bla/Library/Developer/CoreSimulator/Devices/D2CA897A-D50B-4F70-8A57-4133811F4309/data/tmp/detox.last_launch_app_log.{out,err}
detox[27185] DEBUG: [DetoxServer.js/CANNOT_FORWARD] role=testee not connected, cannot fw action (sessionId=f75ca835-2abb-1eb4-6374-35e5ad4f4dc7)
```
So practically nothing happens, application is not relaunched, testee is not connected, tester cannot proceed. Any ideas?

**Comment by noomorph** [comment]
I'll look into this next week.

**Comment by ZSeba** [comment]
Same problem here 😞

**Comment by nschurmann** [comment]
Same here!
