### ISSUE TITLE
Investigate docz as alternative for docusaurus

### ISSUE THREAD

**Issue by DanielMSchmidt** [wix/Detox#932]
#### Description

Docusaurus does not allow us to have cool features like having a toggle between iOS and Android docs. From reading the readme it seems like [docz](https://github.com/pedronauck/docz) could provide this and might be similar to use.

**Comment by noomorph** [comment]
It does not support versioning AFAIK and its MDX cannot be rendered by Github, which adds higher responsibility on this switch - the website should work consistently and just well. But I agree that it looks nicer in some aspects. The custom components idea feels right.
