### ISSUE TITLE
iOS: allow hybrid app tests to match both native and RN views by accessibility label

### ISSUE THREAD

**Issue by Ilushkanama** [wix/detox#934]
#### Description

This is an enhancement request.

When testing a hybrid app which has both native and RN screens, Detox only matches RN views. It seems to be impossible to test native screens in such app with current Detox implementation. Please consider adding ability to match views of both kinds in that case.

We managed to solve this problem by combining native and RN matchers in `detox_matcherForAccessibilityLabel` with `grey_anyOf`. If you think that this is a viable fix, I'd be happy to submit a PR.

**Comment by LeoNatan** [comment]
Could you create a small project where Detox fails for native parts? This sounds like a bug, not enhancement request. Thanks
