### ISSUE TITLE
Docs on https://wix.github.io/detox/ are outdated?

### ISSUE THREAD

**Issue by angly-cat** [wix/Detox#937]
#### Description
Subject. Docs on https://wix.github.io/detox/ show version as `8.1.6`, however there are actually many newer `8.x` versions and even `9.x` versions. Also I wasn't able to find a link to those github.io docs and ended up typing the address manually. Are those docs not supported? If they are, how about revising them and putting a link to repo description, where many other repos has links to their docs?

**Comment by noomorph** [comment]
@DanielMSchmidt , how do you think, could it be a flaky deploy CI job? Or we actually forgot to be running the deploy task on `master` branch after migration from Travis to Jenkins?

**Comment by noomorph** [comment]
@angly-cat , officially speaking, this website is not official in a way and never mentioned in docs and not even crawled by search engines. Anyway, I think we'll try to see what went wrong.

**Comment by DanielMSchmidt** [comment]
@noomorph I think the scripts relied on Travis, I will take a look at it this weekend and fix them :)

**Comment by LeoNatan** [comment]
Why isn't the website updated every time there is a push to mater?

**Comment by noomorph** [comment]
I believe  https://wix.github.io/detox/  is currently dead for some unknown reason... 😕

**Comment by DanielMSchmidt** [comment]
It's on my list to fix 😇 I first need to get through this other giant PR before I can focus on this
