### ISSUE TITLE
android:  DetoxRuntimeError: Failed to find PID of the launched bundle: com.tester

### ISSUE THREAD

**Issue by oguennec** [wix/detox#938]
#### Description
Detox test fails on android with  `DetoxRuntimeError: Failed to find PID of the launched bundle: com.tester`. Tests run fine on iOS.

#### Steps to Reproduce
detox build --configuration android.emu.debug
detox test --configuration android.emu.debug

#### Detox, Node, Device, Xcode and macOS Versions
* Detox: 9.0.1
* React Native: 0.56.0
* Node: 8.5
* Device: 
* Xcode: 9.2 - Build version 9C40b
* macOS: 10.12.16
* gradle: 4.10
* android compileSdkVersion: 27
* android buildToolsVersion: 27.0.3
* device tested: Nexus 6 - API 23 - Android 6.0

#### Device and verbose Detox logs
detox test --configuration android.emu.debug --loglevel verbose node_modules/.bin/jest e2e --config=e2e/config.json --maxWorkers=1 '--testNamePattern=^((?!:ios:).)*$'
configuration="android.emu.debug" loglevel="verbose" artifactsLocation="artifacts/android.emu.debug.2018-09-18 13-23-18Z" node_modules/.bin/jest e2e --config=e2e/config.json --maxWorkers=1 '--testNamePattern=^((?!:ios:).)*$'
detox[3056] INFO:  [DetoxServer.js] server listening on localhost:65165...
detox[3056] DEBUG: [AsyncWebSocket.js/WEBSOCKET_OPEN] opened web socket to: ws://localhost:65165
detox[3056] DEBUG: [DetoxServer.js/LOGIN] role=tester, sessionId=c424452c-9000-ffd7-5c49-de6cce8748d5
detox[3056] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=tester, sessionId=c424452c-9000-ffd7-5c49-de6cce8748d5
detox[3056] DEBUG: [exec.js/EXEC_CMD, #0] /Users/guenneco/Library/Android/sdk/emulator/emulator -list-avds --verbose
detox[3056] DEBUG: [exec.js/EXEC_CMD, #1] /Users/guenneco/Library/Android/sdk/platform-tools/adb  devices
detox[3056] DEBUG: [exec.js/EXEC_CMD, #2] /Users/guenneco/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop dev.bootcomplete
detox[3056] DEBUG: [exec.js/EXEC_CMD, #3] /Users/guenneco/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell dumpsys power | grep "^[ ]*m[UW].*="
detox[3056] DEBUG: [exec.js/EXEC_CMD, #4] /Users/guenneco/Library/Android/sdk/build-tools/28.0.2/aapt dump badging "/Users/guenneco/react-native/bg-mobile-docs/ModularArchitecture/packages/tester/android/app/build/outputs/apk/debug/app-debug.apk" | grep -e "package: name="
detox[3056] DEBUG: [exec.js/EXEC_CMD, #5] /Users/guenneco/Library/Android/sdk/platform-tools/adb -s emulator-5554 uninstall com.tester
detox[3056] DEBUG: [exec.js/EXEC_CMD, #6] /Users/guenneco/Library/Android/sdk/platform-tools/adb -s emulator-5554 uninstall com.tester.test
detox[3056] DEBUG: [exec.js/EXEC_CMD, #7] /Users/guenneco/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop ro.build.version.sdk
detox[3056] DEBUG: [exec.js/EXEC_CMD, #8] /Users/guenneco/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -rg /Users/guenneco/react-native/bg-mobile-docs/ModularArchitecture/packages/tester/android/app/build/outputs/apk/debug/app-debug.apk
detox[3056] DEBUG: [exec.js/EXEC_CMD, #9] /Users/guenneco/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop ro.build.version.sdk
detox[3056] DEBUG: [exec.js/EXEC_CMD, #10] /Users/guenneco/Library/Android/sdk/platform-tools/adb -s emulator-5554 install -rg /Users/guenneco/react-native/bg-mobile-docs/ModularArchitecture/packages/tester/android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
detox[3056] DEBUG: [exec.js/EXEC_CMD, #11] /Users/guenneco/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am force-stop com.tester
detox[3056] DEBUG: [exec.js/EXEC_CMD, #12] /Users/guenneco/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm list instrumentation
detox[3056] DEBUG: [exec.js/SPAWN_CMD, #13] [pid=3078] /Users/guenneco/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am instrument -w -r "-e detoxServer ws://localhost:65165 -e detoxSessionId c424452c-9000-ffd7-5c49-de6cce8748d5" -e debug false com.tester.test/android.support.test.runner.AndroidJUnitRunner
detox[3056] DEBUG: [exec.js/EXEC_CMD, #14] /Users/guenneco/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell ps | grep "com\.tester[ ]*$"
detox[3056] ERROR: [exec.js/EXEC_FAIL, #14] "/Users/guenneco/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell ps | grep "com\.tester[ ]*$"" failed with code = 1, stdout and stderr:

detox[3056] ERROR: [exec.js/EXEC_FAIL, #14]
detox[3056] ERROR: [exec.js/EXEC_FAIL, #14]
detox[3056] DEBUG: [exec.js/EXEC_CMD, #15] /Users/guenneco/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell ps | grep "com\.tester[ ]*$"
detox[3056] ERROR: [exec.js/EXEC_FAIL, #15] "/Users/guenneco/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell ps | grep "com\.tester[ ]*$"" failed with code = 1, stdout and stderr:

detox[3056] ERROR: [exec.js/EXEC_FAIL, #15]
detox[3056] ERROR: [exec.js/EXEC_FAIL, #15]
detox[3056] DEBUG: [DetoxServer.js/LOGIN] role=testee, sessionId=c424452c-9000-ffd7-5c49-de6cce8748d5
detox[3056] DEBUG: [DetoxServer.js/LOGIN_SUCCESS] role=testee, sessionId=c424452c-9000-ffd7-5c49-de6cce8748d5
detox[3056] DEBUG: [exec.js/EXEC_CMD, #16] /Users/guenneco/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell ps | grep "com\.tester[ ]*$"
detox[3056] ERROR: [exec.js/EXEC_FAIL, #16] "/Users/guenneco/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell ps | grep "com\.tester[ ]*$"" failed with code = 1, stdout and stderr:

detox[3056] ERROR: [exec.js/EXEC_FAIL, #16]
detox[3056] ERROR: [exec.js/EXEC_FAIL, #16]
detox[3056] DEBUG: [exec.js/EXEC_CMD, #17] /Users/guenneco/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell ps | grep "com\.tester[ ]*$"
detox[3056] ERROR: [exec.js/EXEC_FAIL, #17] "/Users/guenneco/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell ps | grep "com\.tester[ ]*$"" failed with code = 1, stdout and stderr:

detox[3056] ERROR: [exec.js/EXEC_FAIL, #17]
detox[3056] ERROR: [exec.js/EXEC_FAIL, #17]
detox[3056] DEBUG: [exec.js/EXEC_CMD, #18] /Users/guenneco/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell ps | grep "com\.tester[ ]*$"
detox[3056] ERROR: [exec.js/EXEC_FAIL, #18] "/Users/guenneco/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell ps | grep "com\.tester[ ]*$"" failed with code = 1, stdout and stderr:

detox[3056] ERROR: [exec.js/EXEC_FAIL, #18]
detox[3056] ERROR: [exec.js/EXEC_FAIL, #18]
detox[3056] DEBUG: [exec.js/EXEC_CMD, #19] /Users/guenneco/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell ps
detox[3056] WARN:  [AndroidDriver.js] USER      PID   PPID  VSIZE  RSS   WCHAN            PC  NAME
root      1     0     2964   1060  SyS_epoll_ 081249c5 S /init
root      2     0     0      0       kthreadd 00000000 S kthreadd
root      3     2     0      0     smpboot_th 00000000 S ksoftirqd/0
root      5     2     0      0     worker_thr 00000000 S kworker/0:0H
root      7     2     0      0     smpboot_th 00000000 S migration/0
root      8     2     0      0     rcu_gp_kth 00000000 S rcu_preempt
root      9     2     0      0     rcu_gp_kth 00000000 S rcu_bh
root      10    2     0      0     rcu_gp_kth 00000000 S rcu_sched
root      11    2     0      0     smpboot_th 00000000 S migration/1
root      12    2     0      0     smpboot_th 00000000 S ksoftirqd/1
root      14    2     0      0     worker_thr 00000000 S kworker/1:0H
root      15    2     0      0     rescuer_th 00000000 S khelper
root      16    2     0      0     worker_thr 00000000 S kworker/u4:1
root      317   2     0      0     rescuer_th 00000000 S writeback
root      319   2     0      0     rescuer_th 00000000 S bioset
root      321   2     0      0     rescuer_th 00000000 S kblockd
root      416   2     0      0     rescuer_th 00000000 S ata_sff
root      427   2     0      0     hub_thread 00000000 S khubd
root      436   2     0      0     rescuer_th 00000000 S md
root      445   2     0      0     rescuer_th 00000000 S cfg80211
root      540   2     0      0     worker_thr 00000000 S kworker/1:1
root      557   2     0      0         kswapd 00000000 S kswapd0
root      623   2     0      0     fsnotify_m 00000000 S fsnotify_mark
root      642   2     0      0     rescuer_th 00000000 S crypto
root      768   2     0      0     rescuer_th 00000000 S iscsi_eh
root      782   2     0      0     scsi_error 00000000 S scsi_eh_0
root      785   2     0      0     scsi_error 00000000 S scsi_eh_1
root      820   2     0      0     rescuer_th 00000000 S uether
root      840   2     0      0     rescuer_th 00000000 S dm_bufio_cache
root      872   2     0      0     rescuer_th 00000000 S binder
root      875   2     0      0     rescuer_th 00000000 S hd-audio0
root      896   2     0      0     rescuer_th 00000000 S deferwq
root      901   1     2704   636   poll_sched 0810c9d0 S /sbin/ueventd
root      1211  2     0      0     worker_thr 00000000 S kworker/0:1H
root      1212  2     0      0     kjournald2 00000000 S jbd2/vda-8
root      1213  2     0      0     rescuer_th 00000000 S ext4-dio-unwrit
root      1215  2     0      0     kjournald2 00000000 S jbd2/vdb-8
root      1216  2     0      0     rescuer_th 00000000 S ext4-dio-unwrit
logd      1223  1     13832  4148  sigsuspend b7599bf1 S /system/bin/logd
root      1224  1     12532  3088  hrtimer_na b736de01 S /system/bin/vold
root      1230  2     0      0     kauditd_th 00000000 S kauditd
root      1234  1     2528   352   SyS_epoll_ 08097175 S /sbin/healthd
root      1235  1     4076   1200  SyS_epoll_ b76ac685 S /system/bin/lmkd
system    1236  1     4144   1320  binder_thr b75371a6 S /system/bin/servicemanager
system    1237  1     76340  4224  SyS_epoll_ b7517685 S /system/bin/surfaceflinger
shell     1247  1     4084   1424  n_tty_read b751e7d6 S /system/bin/sh
root      1275  1     9776   684   poll_sched 0808e495 S /sbin/adbd
root      1282  2     0      0     worker_thr 00000000 S kworker/1:1H
root      1640  2     0      0     rescuer_th 00000000 S kdmflush
root      1642  2     0      0     rescuer_th 00000000 S bioset
root      1643  2     0      0     rescuer_th 00000000 S kcryptd_io
root      1644  2     0      0     rescuer_th 00000000 S kcryptd
root      1645  2     0      0     rescuer_th 00000000 S bioset
root      1671  2     0      0     kjournald2 00000000 S jbd2/dm-0-8
root      1672  2     0      0     rescuer_th 00000000 S ext4-dio-unwrit
root      1675  1     16308  2180  hrtimer_na b7413e01 S /system/bin/netd
root      1676  1     4164   1164  __skb_recv b74e97b3 S /system/bin/debuggerd
radio     1677  1     9224   1696  hrtimer_na b755be01 S /system/bin/rild
drm       1678  1     16480  3956  binder_thr b73c41a6 S /system/bin/drmserver
media     1679  1     140376 11988 binder_thr b6ffb1a6 S /system/bin/mediaserver
root      1680  1     4244   1664  unix_strea b75307d6 S /system/bin/installd
keystore  1681  1     7600   2268  binder_thr b739d1a6 S /system/bin/keystore
root      1682  1     1254164 53832 poll_sched b730b650 S zygote
system    1683  1     7028   2076  binder_thr b74271a6 S /system/bin/gatekeeperd
root      1685  1     4008   1176  hrtimer_na b74dee01 S /system/xbin/perfprofd
system    1686  1     8036   2080  binder_thr b74a91a6 S /system/bin/fingerprintd
system    1956  1682  1464776 108600 SyS_epoll_ b730a685 S system_server
media_rw  2217  1224  7668   2016  inotify_re b75317d6 S /system/bin/sdcard
u0_a15    2246  1682  1354440 84240 SyS_epoll_ b730a685 S com.android.systemui
media_rw  2282  1224  7672   2012  inotify_re b75667d6 S /system/bin/sdcard
u0_a16    2444  1682  1298980 30344 SyS_epoll_ b730a685 S com.google.android.googlequicksearchbox:interactor
u0_a35    2458  1682  1294188 50788 SyS_epoll_ b730a685 S com.android.inputmethod.latin
radio     2475  1682  1289884 47040 SyS_epoll_ b730a685 S com.android.phone
u0_a16    2535  1682  1502796 81076 SyS_epoll_ b730a685 S com.google.android.googlequicksearchbox:search
u0_a8     2593  1682  1282328 33260 SyS_epoll_ b730a685 S com.google.process.gapps
u0_a8     2764  1682  1681116 142188 SyS_epoll_ b730a685 S com.google.android.gms
u0_a8     2798  1682  1460428 107136 SyS_epoll_ b730a685 S com.google.android.gms.persistent
u0_a26    3289  1682  1266776 31216 SyS_epoll_ b730a685 S com.android.deskclock
u0_a9     3508  1682  1335696 75400 SyS_epoll_ b730a685 S com.android.launcher3
root      5408  2     0      0     worker_thr 00000000 S kworker/u4:2
u0_a2     10416 1682  1266844 34396 SyS_epoll_ b730a685 S android.process.acore
u0_a4     11364 1682  1261484 26428 SyS_epoll_ b730a685 S com.android.defcontainer
root      11517 2     0      0     worker_thr 00000000 S kworker/1:2
system    15253 1682  1261004 28216 SyS_epoll_ b730a685 S com.android.keychain
u0_a29    15272 1682  1264848 30040 SyS_epoll_ b730a685 S com.android.documentsui
root      15303 2     0      0     worker_thr 00000000 S kworker/0:1
u0_a6     15309 1682  1264960 31220 SyS_epoll_ b730a685 S android.process.media
u0_a7     15331 1682  1259688 25324 SyS_epoll_ b730a685 S com.android.externalstorage
u0_a45    15379 1682  1259660 23728 SyS_epoll_ b730a685 S com.svox.pico
u0_a8     16210 1682  1415048 56660 SyS_epoll_ b730a685 S com.google.android.gms.unstable
root      16748 2     0      0     worker_thr 00000000 S kworker/0:2
root      17219 2     0      0     worker_thr 00000000 S kworker/0:0
root      17569 1275  1087464 29580 futex_wait b73451e2 S app_process
u0_a83    17578 1682  1414212 127584 SyS_epoll_ b730a685 S com.tester
root      17634 1275  3980   1104           0 b751b7d6 R ps
detox[3056] ERROR: [index.js/DETOX_INIT_ERROR]

DetoxRuntimeError: Failed to find PID of the launched bundle: com.tester
...

#### Hint
_**When running:**_
`$ /Users/.../Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm list instrumentation`
instrumentation:com.android.emulator.smoketests/android.support.test.runner.AndroidJUnitRunner (target=com.android.emulator.smoketests)
instrumentation:com.android.smoketest.tests/com.android.smoketest.SmokeTestRunner (target=com.android.smoketest)
instrumentation:com.example.android.apis/.app.LocalSampleInstrumentation (target=com.example.android.apis)
instrumentation:com.tester.test/android.support.test.runner.AndroidJUnitRunner (target=com.tester)
C352117:tester guenneco$ /Users/guenneco/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am instrument -w -r "-e detoxServer ws://localhost:65165 -e detoxSessionId c424452c-9000-ffd7-5c49-de6cce8748d5" -e debug false com.tester.test/android.support.test.runner.AndroidJUnitRunner
INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.tester.DetoxTest:
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: test=runDetoxTests
INSTRUMENTATION_STATUS: class=com.tester.DetoxTest
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS_CODE: 1

_**The following process is visible:**_
u0_a83    18052 1682  1403180 119048 SyS_epoll_ b730a685 S com.tester

_**The following command included in detox, doesn't find this process:**_
$ /Users/.../Library/Android/sdk/platform-tools/adb -s emulator-5554 shell ps | grep "com\.tester[ ]*$"
ibrary/Android/sdk/platform-tools/adb -s emulator

_**but the following does find the process:**_
$ /Users/.../Library/Android/sdk/platform-tools/adb -s emulator-5554 shell ps | grep "com\.tester$"
ibrary/Android/sdk/platform-tools/adb -s emulator

**Comment by noomorph** [comment]
@oguennec, thanks for the reporting and taking time to describe the issue. It is a known one, I plan to resolve it tomorrow.

**Comment by noomorph** [comment]
See the original one: #924 
See the pull request in progress: #927 

Sorry for the inconveniences with the bugfix delay, this issue is not trivial to fix as it involves quite a lot of integration testing on different combinations of OS platforms and API levels. Hopefully tomorrow I'll have time to finish my pull request.
