### ISSUE TITLE
Jest tests don't finish when using --record-logs=all

### ISSUE THREAD

**Issue by EdwardDrapkin** [wix/Detox#939]
Hey there,

It seems that intermittently, the logger fails to log correctly and never finishes, hanging the test process.  Sometimes it finishes, sometimes it doesn't.

* Detox: 9.0.1
* React Native: 0.56.0
* Node: 10.5.0
* Device: iPhone 6 Simulator
* Xcode: 9.4.1
* macOS: High Sierra

I'm using this command to launch the tests:

`yarn detox test --configuration=ios.sim.debug --runner-config=test/detox-jest.json --specs=e2e/ --artifacts-location=./.e2e/flexmobile  -f '"e2e.*"' --record-logs=all`

If I remove the `--record-logs=all` it works consistently.

**Comment by noomorph** [comment]
@EdwardDrapkin , run with `--loglevel trace` and attach logs.

**Comment by noomorph** [comment]
By the way, @EdwardDrapkin, looks like I've found the issue. It was a hack in a third party lib that caused a race condition. Thanks for the feedback, anyways!
