### ISSUE TITLE
Switch from Mocha to another lib 

### ISSUE THREAD

**Issue by padupuy** [wix/detox#94]
Hello @rotemmiz @LeoNatan,
I'm not a big fan of Mocha test framework because a lot of things seems to be magic.
When I look at the examples https://github.com/wix/detox/blob/master/detox/test/e2e/a-sanity.js I don't understand where the different methods come from - describe, beforeEach, it, expect -
It's really confusing to understand what comes from the test framework or from Detox, you have to search deep to discover where comes from the magic https://github.com/wix/detox/blob/master/detox/src/ios/expect.js#L357

Is there any plan to be test framework agnostic ?

It will be awesome Detox works with Ava https://github.com/avajs/ava and expose a verbose API.

```
import DetoxClient, {element, expect} from 'detox';
import test from 'ava';

const DETOX_CONFIG = {
...
};

let client;
test.before(async () => {
    client = DetoxClient.init(DETOX_CONFIG);
    await client.start();
});

test('my passing test', async () => {
    await element(by.id('username')).replaceText('admin');
    await element(by.id('password')).replaceText('admin');
    await element(by.label('loginButton')).tap();
    await expect(element(by.label('Welcome'))).toBeVisible();
});

test.afterEach.always(async () => {
    await client.waitForTestResult();
});

test.after.always(async () => {
    await client.cleanup();
});

```

**Comment by LeoNatan** [comment]
Detox is runner agnostic and will work with other runners, such as Jest and Ava.
