### ISSUE TITLE
Global `expect` is overridden

### ISSUE THREAD

**Issue by Tommos0** [wix/detox#944]
Detox override's (jests) `expect` with its own version, which only works for detox matchers/testers. Since I'm running e2e tests, I'm also testing other things (e.g. get value from DB and just run `expect(dbValue).toBe(expectedValue)`), but these things don't work anymore. Would it be possible to change `expect` so it is still compatible with jests?

As a workaround I'm just using `jestExpect = expect` before initializing detox right now which works fine, but feels kind of hacky.

**Comment by noomorph** [comment]
https://stackoverflow.com/questions/51317247/mixing-jest-expect-with-detox-expect
