### ISSUE TITLE
Support TouchID functionality

### ISSUE THREAD

**Issue by fedeerbes** [wix/Detox#958]
#### Description
I want to know if there is a way to test TouchID, currently i'm using Detox as e2e framwork, and i have touchID logic in my app. It would be nice simulate success and failure and interactions with system alerts binding to the process.

**Comment by LeoNatan** [comment]
Hello,

Starting with [version 0.6.0](https://github.com/wix/AppleSimulatorUtils/commit/f6313ade30b91c8c89228c160b951f873dcc6b13), AppleSimulatorUtils fully supports the simulator biometric system. You can enable or disable enrollment, as well as approve or fail authentication attempts using face or finger.

Now the matter of implementing it in Detox. While not a hard task at all, it will take time, and we are currently busy with other tasks. If you would like to contribute a PR implementing this functionality, we will be very happy to assist.

In the mean time, as a workaround, you can call `applesimutils` directly with the appropriate commands. Search the issues (open and closed) for examples of how to do that.

**Comment by fedeerbes** [comment]
Thank @LeoNatan appreciate it. I don't have much time free in the future, but maybe i can work on an PR for this. Thanks for the help

**Comment by LeoNatan** [comment]
Thank you

**Comment by abunsen** [comment]
Claiming this - will start work on it now.

**Comment by LeoNatan** [comment]
@abunsen Fantastic, thank you!
I've reopened the issue, and we can discuss here if you need help.

**Comment by abunsen** [comment]
So I believe all that needs to be done is a few functions need to be added to `detox/src/devices/ios/AppleSimUtils.js`, this is what I was thinking:

```javascript
async matchBiometric(udid, matchType) {
    if (!['face', 'finger'].include(matchType)) {
      return;
    }
    const statusLogs = {
      trying: `Trying to match ${matchType}...`,
      successful: `Matched ${matchType}!`
    };

    await this._execAppleSimUtils({ args: `--byId ${udid} --${matchType}}` }, statusLogs, 1);
  }

  async unmatchBiometric(udid, matchType) {
    if (!['Face', 'Finger'].include(matchType)) {
      return;
    }
    const statusLogs = {
      trying: `Trying to match ${matchType}...`,
      successful: `Matched ${matchType}!`
    };

    await this._execAppleSimUtils({ args: `--byId ${udid} --unmatch${matchType}}` }, statusLogs, 1);
  }

  async setBiometricEnrollment(udid, toggle) {
    let yesOrNo = toggle ? 'YES' : 'NO'
    const statusLogs = {
      trying: `Turning ${toggle ? 'on' : 'off'} biometric enrollment`,
      successful: toggle ? 'Activated!' : 'Deactivated!'
    };
    await this._execAppleSimUtils({ args: `--byId ${udid} --biometricEnrollment ${yesOrNo}` }, statusLogs, 1);
  }
```

Then tests need to be added in `detox/src/devices/Device.test.js`. Does that sound about right @LeoNatan?

**Comment by abunsen** [comment]
This is now supported, here are the docs: https://github.com/wix/Detox/blob/master/docs/APIRef.DeviceObjectAPI.md#devicesetbiometricenrollmentbool-ios-only
