### ISSUE TITLE
Cannot run test on Ubuntu machine

### ISSUE THREAD

**Issue by semutmerah** [wix/Detox#959]
#### Description
Detox not able to run the test for Android on Ubuntu machine. 

#### Steps to Reproduce
I put the example code with instructions on this repo > https://github.com/semutmerah/rn-56-test-detox (I basically fork this from @merunga, then updated it to the latest detox version)

#### Environment

* Detox: 9.0.3
* React Native: 0.56.0
* Node: 8.12.0
* Yarn: 1.10.1
* Device: Android Emulator
* OS : Ubuntu 18.04.1 (Kernel 4.15)

#### Logs
```
detox[11333] ERROR: [EmulatorTelnet.js/TELNET_TIMEOUT] 
detox[11333] ERROR: [index.js/DETOX_INIT_ERROR] 
 Error: response not received
    at Timeout.setTimeout (/home/semutmerah/Workspace/learn_detox/node_modules/telnet-client/lib/index.js:150:47)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
Jest did not exit one second after the test run has completed.
```

**Comment by noomorph** [comment]
@semutmerah, thanks for a detailed bug report. I liked very much the fact you created a repo for that.

Personally I've seen this telnet issue on a few occasions on Windows machine, but I'm not sure if I'll be able to reproduce it. It appears only from time to time.

As a temporary suggestion, try to wipe data on your emulator and do a cold boot. Maybe that will help.

**Comment by semutmerah** [comment]
Thanks for the suggestion. Unfortunately, wipe data + cold boot does not solve the problem. Also, this is 100% reproducible in Ubuntu machine (I edited my comment above, to avoid confusion).

**Comment by noomorph** [comment]
@semutmerah , can you connect via telnet? e.g. `telnet localhost 5554` and for example run `avd name` ? Does it respond?

**Comment by semutmerah** [comment]
@noomorph, I do not bring my Ubuntu machine currently, but I did run the telnet command directly to the emulator, and the response was OK. Seems like something wrong happened with the telnet-client implementation. 

I also try to upgrade the telnet-client to the latest version (0.16.1), still no luck.

**Comment by HoaBo** [comment]
@noomorph Do we have any progress on this issue? We are experiencing the same telnet timeout error on Ubuntu 18.04

**Comment by noomorph** [comment]
@HoaBo, I've experienced this issue a couple of times,so I know what you're talking about, but I need some means to reproduce it because it stopped occurring quite a long time ago in my environment on Windows 10.

Do you have ideas on how to snapshot your environment so somebody can help you with investigation?
