### ISSUE TITLE
Globals are not resolved in Flow 0.81.0

### ISSUE THREAD

**Issue by erksch** [wix/Detox#960]
I recently upgraded to Flow 0.81.0 and Flow-Typed 2.5.1.
But I encountered problems with the detox globals.
So running flow results in a lot of:

Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ e2e/signUp.spec.js:17:27

Cannot resolve name by.

     14│   });
     15│
     16│   it('should sign up when correct form is submitted', async () => {
     17│     await waitFor(element(by.id('sign-up-username-input'))).toBeVisible();
     18│
     19│     await element(by.id('sign-up-username-input')).typeText(user.username);
     20│     await element(by.id('sign-up-email-input')).typeText(user.email);

Or Cannot resolve name...element/waitFor/device

This occurs after upgrading from Flow 0.66.0, I think it works until flow 0.75.0.

**Comment by rotemmiz** [comment]
We do not maintain flow types, they were added by the community to [flow-typed](https://github.com/flow-typed/flow-typed/blob/4797d7168a0a9644e47b176adb0ca904a8e1d39c/definitions/npm/detox_v7.x.x/test_detox_v7.x.x.js).

You are of course welcome to update/add what ever's necessary, but this is probably out of Detox's scope. :(
