### ISSUE TITLE
Running Detox on a real Android device - supported? 

### ISSUE THREAD

**Issue by EdwardDrapkin** [wix/Detox#968]
I'm trying to run my tests on a real device or in a Genymotion cloud AWS instance.  They complete successfully on a local emulator.

I've tried with a local Android emulator as device type `android.emulator` and a local Genymotion emulator as `android.attached`; both work correctly.  When I try to run `android.attached` with a real device ID, things start to go wrong.  The application builds and installs successfully, and it even launches successfully as well.   But then nothing ever happens until the Jest tests timeout with errors about `device` and `element` not being defined.

Looking at the log files, it seems like the test can't connect to the Detox server but I'm not sure if I'm reading things correctly.

* Detox: 9.0.4
* React Native: 0.56
* Node: 10.5
* Device: Google Pixel / ZTE Z983 / Genymotion AWS 8.0 image
* Xcode: n/a
* macOS: High Sierra

Here's my configuration...

```json
        "android.wallet.device": {
                "binaryPath": "android/app/build/outputs/apk/flexwallet/release/app-flexwallet-release.apk",
                "build": "cd android && ./gradlew assembleFlexwalletRelease assembleAndroidTest -DtestBuildType=release && cd ..",
                "type": "android.attached",
                "name": "9802d885"
            },
```

...and I launch it like so....

```
detox test --configuration=android.wallet.device --runner-config=test/detox-jest.json --specs=e2e/ --artifacts-location=./.e2e/flexmobile --loglevel=trace --record-logs=all
```

... and I get these logs: [detox_pid_87613.log](https://github.com/wix/Detox/files/2443477/detox_pid_87613.log) and [test.log](https://github.com/wix/Detox/files/2443485/test.log)

**Comment by EdwardDrapkin** [comment]
I read through the source code and it looks like running `detox run-server` and adding:

```
"session": {
            "sessionId": "manualsession",
            "server": "ws://192.168.41.137:8099" #output from detox run-server
        },```

to my Detox config that gets passed to init() was what I needed to do.  

Is this documented somewhere I missed?

**Comment by frankgerhardt** [comment]
I'm interested in this as well. I'm surprised that this issue is new. For iOS #95 is the second oldest open issue.

**Comment by EdwardDrapkin** [comment]
Upon further research, it seems that running `adb reverse tcp:8099 tcp:8099` and running the detox server on 8099 every time is the best solution.
