### ISSUE TITLE
device.launchApp launchArgs not passed to MainActivity on Android

### ISSUE THREAD

**Issue by elyalvarado** [wix/Detox#981]
#### Description
When using `device.launchApp` passing `launchArgs` this are received by the Instrumentation Activity (the DetoxTest) but not passed down to the actual Android app being run (the MainActivity).

I understand the rationale behind closing Issue #530. However, this is a completely different thing. Using iOS the launchArgs are received by the App being tested, but in Android detox swallows the launchArgs on the test runner and are not being received by the MainActivity, in which even if you have the logic to handle command line arguments they won't show up.

#### Steps to Reproduce
Create a test that launches the app:

```
  it('Receives command line arguments', async () => {
    await device.launchApp({
      newInstance: true,
      launchArgs: { name: 'world' },
    })
    await expect(element(by.text('Hello world!!!'))).toBeVisible()
  })
```

Handle the command line arguments on the MainActivity (in this case pass as initialProps):

```
package com.test.detoxCommandLineArgs;

import android.os.Bundle;
import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate;

public class MainActivity extends ReactActivity {

    /**
     * Sets the launch options for the React View
     */
    @Override
    protected ReactActivityDelegate createReactActivityDelegate() {
        return new ReactActivityDelegate(this, getMainComponentName()) {
            @Override
            protected Bundle getLaunchOptions() {
                return getIntent().getExtras();
            }
        };
    }

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "DetoxTestCommandLineArguments";
    }
}
```

#### Expected behavior
In the example above the app should receive the launchArgs as initial props. It works when launching the app from the command line passing the values as extras, but it doesn't when running the test.

**Comment by rotemmiz** [comment]
Android has no way to pass launch args into a process, it can though receive extra intent parama on its launch intent. I'm pretty sure this behaviour has not been addressed by Detox for Android yet.

**Comment by elyalvarado** [comment]
@rotemmiz that is why I made pr #982, this makes the behavior consistent between iOS and Android by passing the parameters to the MainActivity Intent.
I know that file (the one changed in PR #982) is just an example, but most people just copy and paste and that gives a hint on how to pass the detox parameters down to the launch intent.

**Comment by elyalvarado** [comment]
I still believe this is relevant for the sake of consistency between platforms. Either that, or explain somewhere in the docs that launch args are not supported on Android

**Comment by LeoNatan** [comment]
I think a better approach to passing test functionality to your RN code is using [Mocking](https://github.com/wix/Detox/blob/master/docs/Guide.Mocking.md). There is already an example in the test project how to run a mock server from a test, which can then be accessed using your mocked functionality, and that server can serve all the values you would need.

**Comment by elyalvarado** [comment]
keep open, still making progress on #982

**Comment by LeoNatan** [comment]
@d4vidi This was implemented right? Can we close the issue?

**Comment by d4vidi** [comment]
@LeoNatan yes, see referencing issue -- #1385

**Comment by LeoNatan** [comment]
For the next time, please include "Closes #..." in the PR notes so that issues are closed automatically. 🙂

**Comment by d4vidi** [comment]
https://media1.tenor.com/images/e5e91360089456411ef660428fb48270/tenor.gif?itemid=9900289

**Comment by LeoNatan** [comment]
🤷‍♂️😉
