### ISSUE TITLE
Android on first app installation - facebook::react::Recoverable: Could not open file/data/user/0/com.detoxtesting/files/ReactNativeDevBundle.js: No such file or directory

### ISSUE THREAD

**Issue by nadzic** [wix/Detox#985]
#### Description

After I first run the app via `react-native run-android` or `detox build -c android.emu.debug && detox test -c android.emu.debug` and click on screen I get red screen and the following error:

`facebook::react::Recoverable: Could not open file/data/user/0/com.detoxtesting/files/ReactNativeDevBundle.js: No such file or directory`

Try the following to fix the issue:
• Ensure that the packager server is running
• Ensure that your device/emulator is connected to your machine and has USB debugging enabled - run 'adb devices' to see a list of connected devices
• Ensure Airplane Mode is disabled
• If you're on a physical device connected to the same machine, run 'adb reverse tcp:8081 tcp:8081' to forward requests from your device
• If your device is on the same Wi-Fi network, set 'Debug server host & port for device' in 'Dev settings' to your machine's IP address and the port of the local dev server - e.g. 10.0.1.1:8081

```
facebook::react::Recoverable: Could not open file/data/user/0/com.detoxtesting/files/ReactNativeDevBundle.js: No such file or directory
loadScript
    JSBundleLoader.java:77
runJSBundle
    CatalystInstanceImpl.java:234
createReactContext
    ReactInstanceManager.java:1137
access$900
    ReactInstanceManager.java:113
run
    ReactInstanceManager.java:944
run
    Thread.java:761
```

If I restart app via simulator then app works, but the tests does not run. iOS build and tests work normally.

#### Steps to Reproduce

Run app and click on screen.

#### Detox, Node, Device, Xcode and macOS Versions

* Detox: 9.0.4
* React Native: 0.52
* Node: 8.6.0
* Device: Nexus 5X API 25
* Xcode: 9.4
* macOS: 10.13.6

#### Device and verbose Detox logs

```
facebook::react::Recoverable: Could not open file/data/user/0/com.detoxtesting/files/ReactNativeDevBundle.js: No such file or directory

Try the following to fix the issue:
• Ensure that the packager server is running
• Ensure that your device/emulator is connected to your machine and has USB debugging enabled - run 'adb devices' to see a list of connected devices
• Ensure Airplane Mode is disabled
• If you're on a physical device connected to the same machine, run 'adb reverse tcp:8081 tcp:8081' to forward requests from your device
• If your device is on the same Wi-Fi network, set 'Debug server host & port for device' in 'Dev settings' to your machine's IP address and the port of the local dev server - e.g. 10.0.1.1:8081



facebook::react::Recoverable: Could not open file/data/user/0/com.detoxtesting/files/ReactNativeDevBundle.js: No such file or directory
loadScript
    JSBundleLoader.java:77
runJSBundle
    CatalystInstanceImpl.java:234
createReactContext
    ReactInstanceManager.java:1137
access$900
    ReactInstanceManager.java:113
run
    ReactInstanceManager.java:944
run
    Thread.java:761
```

**Comment by rotemmiz** [comment]
Is this issue related to detox? Seems like a React Native configuration issue
