### ISSUE TITLE
Detox once initiate the app for every test suite though the suite is skipped or excluded 

### ISSUE THREAD

**Issue by yogeshthanvi** [wix/Detox#987]
Issue : 
There is an option to skip test suites by using skip or xdescribe but when the test runner is jest then irrespective of the keyword (skip or xdescribe) the app gets initiated for every test suite i.e. if there are 10 test suites and 9 have skipped then also the app is getting initiated for 10 times for each suite. 

Needed Solution : 
Detox should not initiate the app for every test suites only for those where the execution is needed or test suites which are included in test execution.

**Comment by rotemmiz** [comment]
Detox does not control the lifecycle, it merely suplies init and cleanup functions. What you describe is impossible to solve in Detox, and is actually an issue of Jest (there are a few open issues in Jest regarding that).
You can always use`detox test -f filePath` flag on Detox command line for more fine-grained runs.
