### ISSUE TITLE
React native 0.57

### ISSUE THREAD

**Issue by khrizt** [wix/Detox#997]
#### Description

This is not an issue is just a comment, I'm using detox v9 with version 0.57 of react-native and everything I'm using works correctly. There's just one thing that I needed to change. The mocking react-native config needs to be changed as this react-native version includes a metro-bundler version bump. The only way to achieve the same effect as the previous version of `rn-cli.config.js` is this one:

```js
const { getDefaultConfig } = require('metro-config');

const additionalExts = process.env.RN_SRC_EXT ? process.env.RN_SRC_EXT.split(',') : [];

module.exports = (async () => {
  const {
    resolver: { sourceExts },
  } = await getDefaultConfig();

  return {
    resolver: {
      sourceExts: [...additionalExts, ...sourceExts],
    },
  };
})();

```
In this new version of metro-bundler you need to specify all the extensions you want to use so you need to get the default extensions and add your own.

I think I got it all correct, and I'm open to testing additional things if needed.

#### Steps to Reproduce
Use detox v9 with react-native 0.57

#### Detox, Node, Device, Xcode and macOS Versions
* Detox: 9.0.5
* React Native: 0.57.2
* Node: 10
* Device: android && ios
* Xcode: 10

**Comment by LeoNatan** [comment]
Hello, thank you for posting. 

There is a PR that updates documentation with these instructions. We haven’t had time to test it yet, which is why it is open still.
