### ISSUE TITLE
Weird UI issues when running detox tests agains 0.57.x (0.57.4 included)

### ISSUE THREAD

**Issue by sync** [wix/Detox#998]
#### Description
Seeing all our text inputs and lots of visual glitches when running our test suite. It adds grey background everywhere.

![glitch-0 57-grey](https://user-images.githubusercontent.com/21725/47533355-1b3c5900-d8ff-11e8-9ef5-25c0b136a64d.png)

Test suite is also having a hard time entering text on multiline text fields. Detox seems to be unhappy about `keyboard was not shown on screen`.

#### Steps to Reproduce
Upgrade to latest react native version 0.57.4 and build and run test suite with latest detox.

If I kill the app and restart it manually (not using detox). UI is back to normal.

#### Detox, Node, Device, Xcode and macOS Versions
* Detox: latest master
* React Native: 0.57.4 (was seeing same issue with 0.57.3)
* Node:v8.11.3
* Device: iPhone X simularot (12.0)
* Xcode: Latest 10
* macOS: Latest Mojave

#### Device and verbose Detox logs
```
      17) space member and admin can archive a space
actionWithWait - tap matcherForAccessibilityID: PlacesMenu 
actionWithWait - tap matcherForAccessibilityID: searchIcon 
waitForElementVisible - detoxMatcherForBoth:and: [object Object]
(node:54486) UnhandledPromiseRejectionWarning: Error: Error: An action failed. Please refer to the error trace below.
Exception with Action: {
  "Action Name":  "Type 'denys'",
  "Element Matcher":  "((!(kindOfClass('RCTScrollView')) && (((respondsToSelector(accessibilityIdentifier) && accessibilityID('search')) && kindOfClass('RCTUITextField')) && matcherForSufficientlyVisible(>=0.750000))) || (((kindOfClass('UIView') || respondsToSelector(accessibilityContainer)) && parentThatMatches(kindOfClass('RCTScrollView'))) && ((kindOfClass('UIView') || respondsToSelector(accessibilityContainer)) && parentThatMatches((((respondsToSelector(accessibilityIdentifier) && accessibilityID('search')) && kindOfClass('RCTUITextField')) && matcherForSufficientlyVisible(>=0.750000))))))"
}


Error Trace: [
  {
    "Description":  "Failed to type string 'denys', because keyboard was not shown on screen.",
    "Error Domain":  "com.google.earlgrey.ElementInteractionErrorDomain",
    "Error Code":  "2",
    "File Name":  "GREYKeyboard.m",
    "Function Name":  "+[GREYKeyboard typeString:inFirstResponder:error:]",
    "Line":  "191"
  }
]
```

**Comment by LeoNatan** [comment]
Does this reproduce in Detox’ own test suite? If not, can you please attach a small demo project, reproducing the issue?

**Comment by sync** [comment]
Created a sample app and was unable to reproduce so will close

**Comment by LeoNatan** [comment]
If you continue seeing these issues, let us know in a new issue. It is a strange issue as Detox should not be interfering with any view rendering. There is a low chance that EarlGrey does, which is why I asked for a demo project.
